### ISSUE TITLE
PHP Parse from string

### ISSUE THREAD

**Issue by KeeperPharaoh** [protocolbuffers/protobuf#10002]
Good day.
This is my first time using protobuf. My task is to communicate with the mgtt server through the protobuf. I've run into a problem, maybe I'm dumb.
I send a request with $request->serializeToStream(), and the response is also a protobuf "��,j �z�─'�v觷����h", I have a question how can I parse this. As I understand it. I also get a protobuf as a string.
I would be very grateful if you help me

**Comment by gakowalski** [comment]
Create new instance of your response message class and use `mergeFromStream` method inherited from Message:
https://github.com/protocolbuffers/protobuf/blob/cd5cc376247720125b6e5bc672347af663dbe2e4/php/src/Google/Protobuf/Internal/Message.php#L760-L772

So essentialy you need something like this:
```php
$response_data = "��,j �z�─'�v觷����h";
$response = new Response;
$response->mergeFromStream($response_data);
```
