### ISSUE TITLE
JsonStringToMessage seems to "hallucinate" weird field contents

### ISSUE THREAD

**Issue by vabr-g** [protocolbuffers/protobuf#10013]
**What version of protobuf and what language are you using?**
Version: https://github.com/protocolbuffers/protobuf/commit/450d24ca820750c5db5112a6f0b0c2efb9758021
Language: C++

**What operating system (Linux, Windows, ...) and version?**
An up-to-date Debian Linux.

**What runtime / compiler are you using (e.g., python version or gcc version)**
I think it's a modern clang, but I'm not sure.

**What did you do?**
Given this proto definition:
```
message ParsedTexture {
  string path = 1;
}

message ParsedMetaJson {
  ParsedTexture diffuse_map = 1;
}

message ListOfParsedMetaJson {
  repeated ParsedMetaJson parsed_meta_json = 1;
}
```
I executed
```
constexpr absl::string_view kInput =
"{"
" \"parsedMetaJson\": {"
"  '': {"
"   '': {"
"    '': {}"
"   }"
"  }"
" }"
"}";

TEST(ParseJson, SurprisingField) {
  ListOfParsedMetaJson proto;
  JsonParseOptions options;
  options.ignore_unknown_fields = true;

  ASSERT_OK(JsonStringToMessage(kInput, &proto, options));

  EXPECT_THAT(proto, testing::EqualsProto(R"pb(
                parsed_meta_json { diffuse_map { path: "\n\000" } }
              )pb"));
}
```

**What did you expect to see**
Probably an error (is the JSON valid at all?) or some kind of empty message.

**What did you see instead?**
```
parsed_meta_json { diffuse_map { path: "\n\000" } }
```
Where does the strangely specific "\n\000" come from? In `kInput` there is just "{}" on the structurally corresponding place. Also how come the empty keys translate to `diffuse_map` and `path`?

**Anything else we should know about your project / environment**
This issue was originally found by a fuzzer.

**Comment by elharo** [comment]
path is a string whose default value contains a linefeed and the string termination character.

**Comment by haberman** [comment]
This seems like a bug to me.

**Comment by mcy** [comment]
This is in fact a bug. We have a new version of the JSON parser that we plan to ship in the next major release which fixes this bug (I verified it), so we can close this as fixed.
