### ISSUE TITLE
from google.protobuf.pyext import _message → "TypeError: bases must be types"

### ISSUE THREAD

**Issue by Geremia** [protocolbuffers/protobuf#10012]
**What version of protobuf and what language are you using?**
Version: 3.20.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Linux Slackware (current), kernel 5.17.9

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.9.12, GCC 11.3.0

**What did you do?**
```python
from google.protobuf.pyext import _message
```

**What did you expect to see**

It to import

**What did you see instead?**
```
TypeError: bases must be types
```

**Comment by elharo** [comment]
Do you have a complete reproducible test case?

**Comment by Geremia** [comment]
@elharo What do you mean?
Electrum tries importing it. Here's the context:
```python3
Traceback (most recent call last):
  File "/usr/bin/electrum", line 82, in <module>
    check_imports()
  File "/usr/bin/electrum", line 73, in check_imports
    from google.protobuf import descriptor
  File "/usr/lib64/python3.9/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

**Comment by elharo** [comment]
Absent a self-contained test case, it's unlikely we can reproduce or fix this, though perhaps someone more experienced in Python than me might recognize this. If it's an electrum issue without any user code, perhaps report it to electrum.

**Comment by Geremia** [comment]
@elharo When I startup `python3` interactive prompt and run `from google.protobuf.pyext import _message`, I get that error, so it's not only an issue with Electrum.

**Comment by tibbing** [comment]
Also seeing this error on import of `opencensus-ext-azure` but the error seems to originate from `google.protobuf.pyext`. Only get the error while Photon Acceleration is enabled in Databricks for some reason.

**Comment by haberman** [comment]
The exchange on https://github.com/spesmilo/electrum/issues/7825 suggests that this is due to a broken installation. Reinstalling into a virtualenv fixed the problem.

Is anyone able to reproduce this with a fresh install into a virtualenv/venv?

**Comment by Geremia** [comment]
Yes, this was due to a bad install. 3.18.1 and 3.20.1 were install on top of each other.
