### ISSUE TITLE
make typeURL point to fully qualified name in Any

### ISSUE THREAD

**Issue by 1zg12** [protocolbuffers/protobuf#10030]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Java

**Describe the problem you are trying to solve.**
Right now, the `Any` class is not very useful. Image the bytes from a protobuf class are retrieved, however, without knowing the class type for the bytes, it's hard to do much on the data, for example merge between different data/class.
https://github.com/protocolbuffers/protobuf/issues/10021

**Describe the solution you'd like**
If `Any` could not provide an implementation for `mergeFrom` rightly, at least the `typeURL` should provide a right info on the binary packed.
At the moment, it's something like `com.googleapi/clz` which is not helpful to tell what class this binary really parsed from. There could be different class named `clz`.

Instead, it could be `com.googleapi/pkg.filename.clz`.

**Describe alternatives you've considered**

**Additional context**

**Comment by elharo** [comment]
This would be an incompatible change that would break existing code.
