### ISSUE TITLE
protobuf v4.21.0 breaks torch tensorboard installation

### ISSUE THREAD

**Issue by awaelchli** [protocolbuffers/protobuf#10048]
**What version of protobuf and what language are you using?**
Version: 4.21.0
Language: Python

**What operating system (Linux, Windows, ...) and version?** 
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9

**What did you do?**

```commandline
conda create -n tb python=3.9
conda activate tb
pip install torch tensorboard
pip freeze | grep proto
python -c "import torch.utils.tensorboard"
```

**What did you expect to see**

No output (import succeeds).

**What did you see instead?**
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/anaconda3/envs/tb2/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Anything else we should know about your project / environment**

```
absl-py==1.0.0
cachetools==5.1.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
google-auth==2.6.6
google-auth-oauthlib==0.4.6
grpcio==1.46.3
idna==3.3
importlib-metadata==4.11.4
Markdown==3.3.7
numpy==1.22.4
oauthlib==3.2.0
protobuf==4.21.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
torch==1.11.0
typing_extensions==4.2.0
urllib3==1.26.9
Werkzeug==2.1.2
zipp==3.8.0
```

**Comment by haberman** [comment]
Protobuf 4.21.0 contains a breaking change for Python, as explained here: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The new version brings speed benefits, but also requires that you regenerate your `_pb2.py` files.

The output pasted above gives a very detailed explanation of the situation and what can be done to fix it.

In this case, the `tensorboard/compat/proto/tensor_shape_pb2.py` file needs to be regenerated with protoc >= 3.19.0.

**Comment by kavinbj** [comment]
i meet same problem

What operating system (Linux, Windows, ...) and version?
MacOS

What runtime / compiler are you using (e.g., python version or gcc version)
Python 3.9

  File "/Users/felix/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/felix/miniconda3/envs/py39/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

steps:
1: 
 I download  [protoc-21.0-osx-universal_binary.zip](https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protoc-21.0-osx-universal_binary.zip),

2、
To install protoc, and I copy this binary to /usr/local/bin/   and  include folder to  /usr/local/include/
so , 
$ protoc --version
libprotoc 3.21.0

3、I download [protobuf-all-21.0.zip](https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protobuf-all-21.0.zip)
cd python 
Build and run the tests:
$ python setup.py build
$ python setup.py test

all is ok

4、but how to regenerate the file,  tensorflow/core/framework/tensor_shape_pb2.py or above case, 
tensorboard/compat/proto/tensor_shape_pb2.py  with protoc >= 3.19.0.

 Compiling Protocol Buffers, need .proto, but I don't know where file
just like this? 
protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/addressbook.proto
(https://developers.google.com/protocol-buffers/docs/pythontutorial)

I don't know how to solve this problem
