### ISSUE TITLE
[Python] `MergeFrom()` raises `TypeError` for the same class

### ISSUE THREAD

**Issue by parthea** [protocolbuffers/protobuf#10040]
**What version of protobuf and what language are you using?**
Version: main
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9.12

**What did you do?**
1. Install the `google-cloud-gke-hub` client
2. Run the sample code provided in https://github.com/googleapis/python-gke-hub/issues/151

**What did you expect to see**
I expected the code to run without error.

**What did you see instead?**
I saw the following exception `TypeError('Parameter to MergeFrom() must be instance of same class: expected MembershipSpec got google.cloud.gkehub_v1.configmanagement_v1.types.configmanagement.MembershipSpec.')`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I'm working on troubleshooting an issue that a user reported in the python client library [here](https://github.com/googleapis/python-gke-hub/issues/151) where protobuf is raising `Parameter to MergeFrom() must be instance of same class:` . I'm able to re-create the error using the sample code that the user shared in the issue. I'm having trouble figuring out why these 2 classes are not the same. There is only one class with `MembershipSpec` and I'm not sure what's causing this issue. I tried debugging but I haven't been able to locate the discrepancy.
https://github.com/googleapis/python-gke-hub/search?q=%22class+MembershipSpec%22. 

```
>>_FullyQualifiedClassName(msg.__class__)
'google.cloud.gkehub_v1.configmanagement_v1.types.configmanagement.MembershipSpec'
>>_FullyQualifiedClassName(cls)
'MembershipSpec'
```
![image](https://user-images.githubusercontent.com/5184014/170249873-ea6519fd-5737-4965-949f-03746134ceb5.png)

**Comment by zhangskz** [comment]
What protobuf version are you on?

**Comment by parthea** [comment]
With `protobuf==3.20.1` , I get `TypeError('Parameter to MergeFrom() must be instance of same class: expected MembershipSpec got google.cloud.gkehub_v1.configmanagement_v1.types.configmanagement.MembershipSpec.')`

With protobuf 4.21.0 I see a different error
```
  File "/usr/local/google/home/partheniou/git/python-gke-hub/check.py", line 62, in <module>
    create_feature(client, parent, membership_name)
  File "/usr/local/google/home/partheniou/git/python-gke-hub/check.py", line 27, in create_feature
    member_spec = MembershipFeatureSpec(
  File "/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/proto/message.py", line 585, in __init__
    super().__setattr__("_pb", self._meta.pb(**params))
TypeError: Message must be initialized with a dict: google.cloud.gkehub.v1.MembershipFeatureSpec
```

**Comment by UrielShimony** [comment]
is there any news with this issue ?
(reproduced in our product as well only on M1 apple macs)

**Comment by lhuhn-wish** [comment]
We are also seeing this error on Apple M1. It occurs at least as far back as protobuf==3.8.0 on Python 2.x.

**Comment by lhuhn-wish** [comment]
We were able to resolve this by following the ideas in https://github.com/protocolbuffers/protobuf/issues/7408 and changing the path we import with.

**Comment by parthea** [comment]
I'm going to close this issue as my issue was unrelated to protobuf. I was using proto-plus which appears to have a bug in marshal.py. I've opened https://github.com/googleapis/proto-plus-python/pull/348 to start the process of proposing a fix.
