### ISSUE TITLE
protobuf C++ run on iOS App error

### ISSUE THREAD

**Issue by weirenfighting** [protocolbuffers/protobuf#10050]
I want to run google mediapipe on iOS device
I manually drag all files into Xcode instead of using bazel and tulsi
but I got an error when use protobuf C++ source

Version: v3.15.6
Language: C++

<img width="2206" alt="WX20220526-112421@2x" src="https://user-images.githubusercontent.com/17874839/170409723-e7b3ec38-8628-4733-bb37-bae29cdcbfe3.png">

**Comment by deannagarcia** [comment]
Closing due to a lack of response. If you're still seeing this issue, feel free to reopen and add more details.
