### ISSUE TITLE
Class 'AdapterManifest\Thing' not found but compiler creates class AdapterManifest_Thing.php

### ISSUE THREAD

**Issue by sim1barreto** [protocolbuffers/protobuf#10052]
On compiling the .proto file:

message AdapterManifest {
  message Thing {
  }
}

It creates class with underscore: AdapterManifest_Thing.php But this library searches for AdapterManifest\Thing

**Comment by zhangskz** [comment]
Can you provide more details including what protobuf version you are on, errors/logs, etc?

**Comment by sim1barreto** [comment]
Proto3 and "google/protobuf": "^3.20". Error is Class 'AdapterManifest\Thing' not found

**Comment by sim1barreto** [comment]
Any update here @zhangskz ?

**Comment by haberman** [comment]
Sorry for the very slow reply on this.

Our tests are currently using nested messages, see: https://github.com/protocolbuffers/protobuf/blob/6f1d88107f268b8ebdad6690d116e74c403e366e/php/tests/proto/test.proto#L119-L122

Used here: https://github.com/protocolbuffers/protobuf/blob/6f1d88107f268b8ebdad6690d116e74c403e366e/php/tests/DebugInfoTest.php#L15

If something is not working for you, it must be something that our tests do not exercise. If you are still experiencing this issue, please open a new issue with a full repro including the `.proto` file(s), your `.php` sources, and the full output that you get (including the error message).
