### ISSUE TITLE
PyPi repository for 4.21.0 doesn't specify required Python version

### ISSUE THREAD

**Issue by codrin-lanterne** [protocolbuffers/protobuf#10053]
Because the 4.21.0 release of protobuf on PyPi (https://pypi.org/project/protobuf/4.21.0) doesn't specify the required Python version, this leads to the installation of the library via `pip install protobuf` to fail when using Python versions smaller than 3.7 (leading to `protobuf requires Python '>=3.7' but the running Python is 3.6.9` for example). This also leads to other libraries such as `ortools` to fail installation.

How to replicate (the commands were ran from an Ubuntu 18.04.5 LTS machine):

1. `python3.6 -m venv venv`
2. `. venv/bin/activate`
3. `pip install protobuf`

**Comment by zhangskz** [comment]
Fixed in https://github.com/protocolbuffers/upb/commit/ef78b6a093f7301c1d1e00aa6308a3016916971d

**Comment by hemanth-vamper** [comment]
Is this fixed? I still see the dependency issue (python >= 3.7)

**Comment by zhangskz** [comment]
Not quite -- the fix is submitted to the upb repo and PR #10058 will update 21.x release branch to point to the updated upb repo commit.

This will probably end up in a 21.1 patch release.

**Comment by hemanth-vamper** [comment]
Thanks @zhangskz 
Do you know the time line for 21.1 patch release?

**Comment by perezd** [comment]
Planning for tomorrow EOD.

**Comment by nthostrup** [comment]
Issue persists. Presumably due to a requirement in protobuff for a specific python version.
Workaround is to specifically list `protobuf<4.21.0` in requirements.txt file.

**Comment by zhangskz** [comment]
Can you elaborate on what you mean by issue persists? Is this against 4.21.1 or are you still looking at 4.20.0 (which was un-yanked but not updated with fix).

**Comment by nthostrup** [comment]
Issue is fixed :) Thx (y)
