### ISSUE TITLE
[java] Rename of java_names.h -> names.h causes downstream breakages

### ISSUE THREAD

**Issue by jvolkman** [protocolbuffers/protobuf#10069]
**What version of protobuf and what language are you using?**
Version: v3.21.0
Language: Java

`google/protobuf/compiler/java/java_names.h` was renamed to `names.h` in https://github.com/protocolbuffers/protobuf/commit/40db3dabf0fe72b572e89c1e176318b04d3e2408. Ideally there'd be some forwarding header to ease this transition.

See discussion about grpc-java at https://github.com/grpc/grpc-java/pull/9218

Edited by ejona86: Fixed the commit link to reference protobuf instead of grpc PR commit

**Comment by ejona86** [comment]
Changing the name is fine from our perspective; we don't need the old header long-term. But it would have been good if the first release that included the new name didn't also delete the old one. That is a flag-day that is guaranteed to cause breakages and prevent upgrades.

**Comment by ejona86** [comment]
gRPC Java has preprocessor logic to fix the build starting in 1.47.0. Most people don't build the grpc java protoc plugin from source, so they aren't impacted either way. I expect this mainly impacted Bazel users. To upgrade to newer Protobuf, those Bazel users would also need to upgrade to newer gRPC.

At this point forwarding includes wouldn't hurt, but I don't know if it'd actually benefit someone.

**Comment by deannagarcia** [comment]
Ok I will go ahead and close this bug since I think it's likely people already did the necessary migrations.
