### ISSUE TITLE
[python] Protobuf 4.21.0 introduces a type change with upb

### ISSUE THREAD

**Issue by parthea** [protocolbuffers/protobuf#10062]
**What version of protobuf and what language are you using?**
Version: 4.21.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.9.12

**What did you do?**
Run unit test in python-tpu [here](https://github.com/googleapis/python-tpu/blob/main/tests/unit/gapic/tpu_v1/test_tpu.py#L830)

**What did you expect to see**
I expected the unit test to pass , as it does with protobuf 3.20.1

**What did you see instead?**
I noticed that the type of an object changed with protobuf 4.21.0

With protobuf 3.20.1
```
type(cloud_tpu.Node)
<class 'proto.message.MessageMeta'>
type(results[0])
<class 'google.cloud.tpu_v1.types.cloud_tpu.Node’>
isinstance(results[0], cloud_tpu.Node)
True
```

With protobuf 4.21.0
```
type(cloud_tpu.Node)
<class 'proto.message.MessageMeta'>
type(results[0])
<class 'Node'>
isinstance(results[0], cloud_tpu.Node)
False
```

With main
```
type(cloud_tpu.Node)
<class 'proto.message.MessageMeta'>
type(results[0])
<class 'google.cloud.tpu_v1.types.cloud_tpu.Node'>
isinstance(results[0], cloud_tpu.Node)
True
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

If I install protobuf from [main](https://github.com/protocolbuffers/protobuf/tree/main/python), I don't see the issue. I only see it in protobuf version 4.21.0.

**Comment by anandolee** [comment]
We do have type issue for cpp extension when use message_factory.

Can you help check if the 3 versions in the example are using pure python or cpp extension, by:
'''
from google.protobuf.internal import api_implementation
print(api_implementation.Type())
'''

Also can you let us know how do you get or create the `result`. And is message_factory used?

**Comment by parthea** [comment]
main
```
>>from google.protobuf.internal import api_implementation
>>api_implementation.Type()
'python'
```

protobuf==4.21.0
```
from google.protobuf.internal import api_implementation
api_implementation.Type()
'upb'
```

protobuf==3.20.1
```
from google.protobuf.internal import api_implementation
api_implementation.Type()
'cpp'
````

I'll work on creating a simple sample to reproduce the issue.

**Comment by parthea** [comment]
Thanks for the clue about the `api_implementation.Type()` . I'm going to close this issue and re-open it once I have a better understanding of the changes in 4.21.0.

**Comment by atulep** [comment]
The issue still persists with Protobuf 4.21.0 and implementation type `upb`. It only affects repeated fields - for example
```
nodes = [cloud_tpu.Node(), cloud_tpu.Node()]
foo = cloud_tpu.ListNodesResponse(
            nodes=nodes, # nodes is a repeated field of ListNodesResponse
            next_page_token="abc",
)

print(type(nodes[0]))
<class 'google.cloud.tpu_v2alpha1.types.cloud_tpu.Node'>
print(type(foo.nodes[0]))
<class 'Node'>
```

The class hierarchy is also different:

```
inspect.getmro(type(foo.nodes[0]))
(<class 'Node'>, <class 'google._upb._message.Message'>, <class 'google.protobuf.message.Message'>, <class 'object'>)

inspect.getmro(type(nodes[0]))
(<class 'google.cloud.tpu_v2alpha1.types.cloud_tpu.Node'>, <class 'proto.message.Message'>, <class 'object'>)
```

Do you have any clues why this may only affect repeated fields ? My investigation is still ongoing. My team uses protobuf indirectly via [protoplus](https://github.com/googleapis/proto-plus-python), where I am currently focusing my search efforts.

**Comment by atulep** [comment]
After some more debugging, the issue appears to happen with `marshal.to_python` from Protobuf.

With `upb` implementation:

```
print(type(pb_type))
<class 'google._upb._message.MessageMeta'>

print(type(pb_value))
<class 'google._upb._message.RepeatedCompositeContainer'>

x =  marshal.to_python(pb_type, pb_value, absent=False)

print(type(x[0]))
<class 'Node'>
```

With `python` implementation

```
print(type(pb_type))
<class 'google.protobuf.internal.python_message.GeneratedProtocolMessageType'>

print(type(pb_value))
<class 'google.protobuf.internal.containers.RepeatedCompositeFieldContainer'>

x =  marshal.to_python(pb_type, pb_value, absent=False)

print(type(x[0]))
<class 'google.cloud.tpu_v2alpha1.types.cloud_tpu.Node'>
```
