### ISSUE TITLE
Grpc.Tools & Windows 10 ARM64

### ISSUE THREAD

**Issue by vladimir-aubrecht** [protocolbuffers/protobuf#10079]
Hi guys, could you please share your plan on supporting Windows 10 ARM64?

**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
Grpc.Tools package currently contains two executables (protoc.exe, grpc_csharp_plugin.exe) which must be both executed through emulation on Windows 10 ARM64. I'd like to have native binaries for Windows ARM64.

**Describe the solution you'd like**
Executables protoc.exe and grpc_csharp_plugin.exe should be compiled in a way they can be natively executed on Windows ARM64.

**Describe alternatives you've considered**
Running both binaries under emulation which works, thou having performance impact from emulation.

**Additional context**

**Comment by deannagarcia** [comment]
Unfortunately we do not have any plans to support Windows ARM64 right now. Given that the workaround is pretty simple, we have decided not to prioritize this in the near future.
