### ISSUE TITLE
Add compiler version as a comment in _pb2.py files

### ISSUE THREAD

**Issue by simoncozens** [protocolbuffers/protobuf#10078]
**What language does this apply to?**

Python, but probably others too.

**Describe the problem you are trying to solve.**

There are some compiled protobuf files in a library I am using. When trying to use that library, I just got an error of the form

```
 If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```

So pb2.py files are linked to certain versions of the protobuf library, which is fine. To make that library work, I need to install the correct version of protobuf. But which version was it? The generated files don't tell me.

**Describe the solution you'd like**

The pb2.py files should contain a comment like:

```
# Generated by protoc 3.x.y.  DO NOT EDIT!
```

**Describe alternatives you've considered**

Sure, the library itself should set a dependency on the right version of protobuf, but it doesn't. This shouldn't be too hard to add and would probably help with debugging other version incompatibility problems too.

**Comment by fowles** [comment]
All generators should include the version of the compiler and plugin that generated them.  At minimum as comments, even better would be in a way that the host language can introspect on.

**Comment by haberman** [comment]
Agreed, this would be good to add to the Python generator.

**Comment by anandolee** [comment]
Thanks for the suggestion. I've created a feature request in google internal to make this a higher priority.
