### ISSUE TITLE
error CS0122: 'Unsafe' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ImCoturnix** [protocolbuffers/protobuf#10085]
unity 2021.3.2f1c1
Asseets -> Google.Protobuf

Assets\Google.Protobuf\WritingPrimitives.cs(80,17): error CS0122: 'Unsafe' is inaccessible due to its protection level

ty

**Comment by ImCoturnix** [comment]
> Can you please provide some more information? Specifically reproduction steps

Download  [Google.Protobuf](https://github.com/protocolbuffers/protobuf/tree/main/csharp/src/Google.Protobuf) .
create new unity project , (Google.Protobuf ) Copy to the Assets folder .
unity enable (Player Setting ->Other Setting -> allow 'unsafe' Code)
unity console show error more error CS0122 error

ty

**Comment by jskeet** [comment]
Which version of .NET is Unity targeting here?
If you've just copied the source code directly into the Assets folder, perhaps it's not picking up that the project as a dependency on the System.Runtime.CompilerServices.Unsafe package?

(Fundamentally, this is expected to be used *as a project* rather than having the source code compiled into another project.)

**Comment by ImCoturnix** [comment]
> I ran into this too. The Unsafe class that Unity provides is internal rather than public. It looks like [Unity has purposely removed the Unsafe package from the .NET version they provide](https://forum.unity.com/threads/bug-1214643-2019-3-0f5-system-runtime-compilerservices-unsafe-clashes-with-imported-dll.816426/), as that package seems to be updated faster than they release, and their version quickly gets out of date and clashes with other assets providing/requiring a more up-to-date version of the dll.
> 
> I believe Unity is expecting you to provide the Unsafe DLL version that works for you You can find this dll in your MSVC install location (ex. C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin) (other versions are also provided if you need a specific target platform) Just drop it in your Managed Plugins folder
> 
> Since this is all managed code, unity should be able to extract all the appropriate code out of this dll when building your project when using il2cpp (you may need to create a link.xml file to prevent il2cpp from stripping out code from the Google.Protobuf.dll)
> 
> ```
> <linker>
>   <assembly fullname="System" preserve="all"/>
>   <assembly fullname="Google.Protobuf" preserve="all"/>
> </linker>
> ```
> 
> [More on Unity and its .NET plan can be found here](https://blog.unity.com/technology/unity-and-net-whats-next)
> 
> So you should be able to build the Google.Protobuf.sln offline from this code base, and drop that dll in your Unity Asset (along with the unsafe dll) And run fine (I do this all the time)
> 
> If you are trying to deploy your app to iOS, this scheme should also work, you should not have to provide the C# code base in your Unity Scripts folder....

tyvm,ill try

**Comment by jskeet** [comment]
I'd like to close this issue as I don't think it's something we should be looking to address within this repo - effectively this is Unity breaking the public contract of System.Runtime.CompilerServices.Unsafe. While I think we should support Unity where it's reasonable to do so, I don't think we should be bending over backwards to handle Unity-specific breakages due to changes from the standard platform.

I'll close this issue next week unless anyone objects or proposes an alternative.

**Comment by jskeet** [comment]
Closing as Unity's issue, basically.

**Comment by wappenull** [comment]
I would like to drop info for future reader who might landed on this
For this specific error (in my case it is with ZString library in this screenshot)
![image](https://user-images.githubusercontent.com/58169531/197554954-be3d2359-ea57-41fc-a83a-beabc786de9d.png)

Unity also provides extra **"System.Runtime.CompilerServices.Unsafe.dll"** inside their Editor install folder.
For example in my case:
`"C:\Program Files\Unity\Hub\Editor\2022.1.15f1\Editor\Data\MonoBleedingEdge\lib\mono\msbuild\Current\bin\Roslyn\System.Runtime.CompilerServices.Unsafe.dll"`

Copy this file and let it sits inside your Unity project folder `"Assets/Plugins"`
And Unity will redirect project compilation to use this instead.
The same can be done if another .NET DLL dependency is requested, like **"System.Buffers.dll"** or **"System.Memory.dll"**
![image](https://user-images.githubusercontent.com/58169531/197554224-eacad818-ffb4-4967-b9ab-5d98765c8ede.png)

**But reader do note that this info might change or already changed in the future. 
So do test your project thoroughly if it is working correctly and without crash.**
