### ISSUE TITLE
util::MessageToJsonString() fails to parse gRPC messages from containerd

### ISSUE THREAD

**Issue by pprindeville** [protocolbuffers/protobuf#10100]
**What version of protobuf and what language are you using?**
Version: main/v3.19.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
CentOS 8.5 on x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ 8.5.0

**What did you do?**
1) I connect to `/run/containerd/containerd.sock` locally
2) I generate an unfiltered `SubscribeRequest`
3) I read `Envelope` objects on the `ClientReader<Envelope>`
4) From the `envelope.event()` I extract an `Any` const reference
5) I invoke `util::MessageToJsonString()` on that `Any`
6) I check the `status.ok()` and `status.message()` from the previous step

(6) results in `!status.ok()` and `status.message()` returning `Invalid type URL, type URLs must be of the form 'type.googleapis.com/<typename>', got: containerd.events.ContainerDelete`.

If `containerd` uses Protobuf and generates compliant messages, why isn't the `type_url()` in those messages compliant with the formatting/namespace that Protobuf expects to be able to parse and format them?

**What did you expect to see**
That `util::MessageToJsonString()` would just work with any message originating from `containerd`.

**What did you see instead?**
Mismatched type-url's on the messages `containerd` is sending me, or an inability by Protobuf to grok them.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
If the prefix of the URL is sometimes implicit, then it would be useful to have a method to either set to what the prefix should be when absent, or two inform Protobuf to assume that the missing prefix is `type.googleapis.com/` ...

**Comment by esorot** [comment]
Are you able to provide any additional information to help reproduce the problem? We're not able to proceed with further analysis at this time.

**Comment by deannagarcia** [comment]
Closing due to no response. If you are still seeing this error and can provide us a simple case to reproduce, feel free to reopen!

**Comment by skaravos** [comment]
I may be totally misunderstanding the usage of the type_url_prefix, but it's true that the json_utils seems to choke whenever dealing with a `type_url_prefix` that doesn't exactly match `"type.googleapis.com"` (which is the hard-coded default if no parameter is provided).

Here is some (C++) sample code that illustrates the problem:

```proto
// ExampleXyz.proto
syntax = "proto3";
package Example.Xyz;
import "google/protobuf/any.proto";

message Foo {
    google.protobuf.Any data = 1;
}
message Bar {
    string message = 1;
}
```


```c++
// Example.cpp
#include <iostream>
#include <google/protobuf/util/json_util.h>
#include "ExampleXyz.pb.h"

void pack_and_print(std::string type_url_prefix = "") {
  Example::Xyz::Foo foo;
  Example::Xyz::Bar bar;
  bar.set_message("HELLO!");

  if (! type_url_prefix.empty())
  {
    foo.mutable_data()->PackFrom(bar, type_url_prefix); // !!! breaks json_utils
  }
  else
  {
    foo.mutable_data()->PackFrom(bar);
  }

  std::string json_string;
  auto status = google::protobuf::util::MessageToJsonString(foo, &json_string);
  if (!status.ok()){
    std::cerr << "err[" << status.message() << "]\n";
  }

  // std::cout << foo.DebugString();
  std::cout << "json[" << json_string << "]\n";
}

int main(void)
{
  std::cout << "-- PART 1 --------------------------------------------------\n";

  pack_and_print(""); // OKAY

  std::cout << "-- PART 2 --------------------------------------------------\n";

  pack_and_print("example.xyz"); // ERROR

  return 0;
}
```


And here's a copy-paste of the output of running the above program.

```txt
-- PART 1 --------------------------------------------------
json[{"data":{"@type":"type.googleapis.com/Example.Xyz.Bar","message":"HELLO!"}}]
-- PART 2 --------------------------------------------------
[libprotobuf WARNING /opt/protobuf/src/google/protobuf/util/internal/json_objectwriter.cc:52] JsonObjectWriter was not fully closed.
err[Invalid type URL, type URLs must be of the form 'type.googleapis.com/<typename>', got: example.xyz/Example.Xyz.Bar]
json[{]
```
