### ISSUE TITLE
protoc 3.21.0 reintroduced dependency on GLIBC_2.14 

### ISSUE THREAD

**Issue by ah1010** [protocolbuffers/protobuf#10119]
**What version of protobuf and what language are you using?**
Version: v3.21.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
```

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)

**What did you do?**
```
objdump -p protoc-3.21.0-linux-x86_64.exe

Version References:
  required from libgcc_s.so.1:
    0x0b792650 0x00 13 GCC_3.0
  required from libc.so.6:
    0x0d696914 0x00 12 GLIBC_2.4
    0x06969194 0x00 11 GLIBC_2.14
    0x09691a75 0x00 05 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libstdc++.so.6:
    0x0297f868 0x00 10 GLIBCXX_3.4.18
    0x02297f89 0x00 09 GLIBCXX_3.4.9
    0x0297f861 0x00 08 GLIBCXX_3.4.11
    0x0297f864 0x00 07 GLIBCXX_3.4.14
    0x0bafd175 0x00 06 CXXABI_1.3.5
    0x056bafd3 0x00 03 CXXABI_1.3
    0x08922974 0x00 02 GLIBCXX_3.4
```

**What did you expect to see**
Output from v3.20.1 (which works fine)

```
objdump -p protoc-3.20.1-linux-x86_64.exe
Version References:
  required from ld-linux-x86-64.so.2:
    0x0d696913 0x00 08 GLIBC_2.3
  required from libm.so.6:
    0x09691a75 0x00 06 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696914 0x00 07 GLIBC_2.4
    0x0d696913 0x00 04 GLIBC_2.3
    0x09691a75 0x00 03 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 05 GLIBC_2.2.5
    0x09691972 0x00 02 GLIBC_2.3.2
```

**What did you see instead?**
Unresolved GLIB dependencies breaks build on RHEL6

**Anything else we should know about your project / environment**
I see this has happened a few times in the past. E.g.: https://github.com/protocolbuffers/protobuf/issues/4138

**Comment by haberman** [comment]
@deannagarcia 

This appears to also be the case with the 21.x release:

```
$ wget https://github.com/protocolbuffers/protobuf/releases/download/v21.1/protoc-21.1-linux-x86_64.zip
$ unzip protoc-21.1-linux-x86_64.zip 
$ objdump -p bin/protoc
[...]
Version References:
  required from libgcc_s.so.1:
    0x0b792650 0x00 13 GCC_3.0
  required from libc.so.6:
    0x0d696914 0x00 12 GLIBC_2.4
    0x06969194 0x00 11 GLIBC_2.14
    0x09691a75 0x00 05 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libstdc++.so.6:
    0x0297f868 0x00 10 GLIBCXX_3.4.18
    0x02297f89 0x00 09 GLIBCXX_3.4.9
    0x0297f861 0x00 08 GLIBCXX_3.4.11
    0x0297f864 0x00 07 GLIBCXX_3.4.14
    0x0bafd175 0x00 06 CXXABI_1.3.5
    0x056bafd3 0x00 03 CXXABI_1.3
    0x08922974 0x00 02 GLIBCXX_3.4
```

We are currently building the artifacts using [manylinux2014](https://github.com/pypa/manylinux#manylinux2014-centos-7-based), based on CentOS 7.

If we want to continue supporting RHEL6, it seems like we'll need to build with manylinux2010 (for x86-64 only, presumably), based on CentOS 6.  manylinux2010 is EOL at this point, but will probably still work for building a binary.

**Comment by Mizux** [comment]
FYI:

| Base image | GLIBC_2.X max |
| :--------------- | --------------------: |
| centos:6 | NA |
| centos:7 | 2.17 |
| quay.io/pypa/manylinux2010_x86_64 | 2.12 |
| quay.io/pypa/manylinux2014_x86_64 | 2.17 |

note:
```sh
docker run --platform linux/amd64 --rm --init -it centos:7
# find libc location using ldd on a random binary
$ ldd /usr/bin/gpg
  ...
  libc.so.6 => /lib64/libc.so.6 (0x00007f24eaf86000)
$ objdump -p /lib64/libc.so.6
...
22 0x00 0x0963cf85 GLIBC_PRIVATE
	GLIBC_2.17 
```

note on Centos:6:
> CentOS 6 binaries and/or libraries are built to expect some system calls to be accessed via vsyscall mappings. Some linux distributions have opted to disable vsyscall entirely (opting exclusively for more secure vdso mappings), causing segmentation faults.

ref: https://hub.docker.com/_/centos "A note about vsyscall"

**Comment by deannagarcia** [comment]
Unfortunately, we no longer support CentOS6 as documented in our [support policy](https://opensource.google/documentation/policies/cplusplus-support).
