### ISSUE TITLE
Protobuf bytes field decoding allocates extra memory bytes field is decoded to c++ string

### ISSUE THREAD

**Issue by sureshmbabu1** [protocolbuffers/protobuf#10110]
Hi,
We noticed that for large size strings(4MB), the string capacity is nearly 2x of the the size when the protobuf message is decoded to c++ string object.  When analyzing the protocolbuffers source code , we noticed the c++ string reserve or resize is not called upfront before appending the smaller buffers in the CodedInputStream object. We call reserve only when the min(current_limit_, total_bytes_limit_)  is not INT_MAX. 

https://github.com/protocolbuffers/protobuf/blob/20a30c675a4fa51736dd183ff9ecf16ef8300325/src/google/protobuf/io/coded_stream.cc#L283

int closest_limit = std::min(current_limit_, total_bytes_limit_);
  if (closest_limit != INT_MAX) {
    int bytes_to_limit = closest_limit - CurrentPosition();
    if (bytes_to_limit > 0 && size > 0 && size <= bytes_to_limit) {
      buffer->reserve(size);
    }
  }

Any reason why we don't call string::reserve when the closest_limit == INT_MAX? We use grpc with protobuf. Because of it our application memory usage nearly doubles when the large number of the requests are pending from the grpc server.  We have protobuf message with field of type bytes. The bytes field contains 4MB of data.

**Comment by yutsareva** [comment]
@jorgbrown Hi, I faced the same issue, are there any updates on this? Thanks

**Comment by jorgbrown** [comment]
@acozzette This is the issue i mentioned over email.
