### ISSUE TITLE
python: Breaking change of comparison for protobuf map to `dict` with upb API in python protobuf 4.21.0

### ISSUE THREAD

**Issue by gen-xu** [protocolbuffers/protobuf#10116]
**What version of protobuf and what language are you using?**
Version: 3.21.1 / python protobuf==4.21.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
OS Agonostic
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.10.4

**What did you do?**

with following protobuf
```protobuf
syntax = "proto3";
package hello;
message Hello{
  map<string, int32> m = 1;
}

```
and following python code
```python
from hello_pb2 import Hello

def test_1():
  test_case_1= { "1": 1, "2": 2 }
  assert Hello(m=test_case_1).m == test_case_1

def test_2():
  test_case_2= { "2": 1, "1": 2 }
  assert Hello(m=test_case_2).m == test_case_2

```
Both test cases passes in ealier version of `protobuf<=3.20.1`

But it fails if the api implementation is `upb`.  

More on this, even if one builds the proto with `protoc~=3.21` and set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` with python `protobuf~=4.21`, both cases would pass. 

In otherwords if `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb` both test cases fail.

This means even on same version of python protobuf there is inconsistent behaviors over different api implementation.

**What did you expect to see**

The test cases should pass with api implementation is `upb`

**What did you see instead?**

Both test cases fails when api implementation is `upb`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
```python
root@f97ef4e79334:/min# pytest example.py 
=========================================================== test session starts ===========================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /min
collected 2 items

example.py FF                                                                                                                       [100%]

================================================================ FAILURES =================================================================
_________________________________________________________________ test_1 __________________________________________________________________

    def test_1():
      test_case_1= { "1": 1, "2": 2 }
>     assert Hello(m=test_case_1).m == test_case_1
E     AssertionError: assert {'1': 1, '2': 2} == {'1': 1, '2': 2}
E       Use -v to get more diff

example.py:5: AssertionError
_________________________________________________________________ test_2 __________________________________________________________________

    def test_2():
      test_case_2= { "2": 1, "1": 2 }
>     assert Hello(m=test_case_2).m == test_case_2
E     AssertionError: assert {'1': 2, '2': 1} == {'1': 2, '2': 1}
E       Use -v to get more diff

example.py:9: AssertionError
========================================================= short test summary info =========================================================
FAILED example.py::test_1 - AssertionError: assert {'1': 1, '2': 2} == {'1': 1, '2': 2}
FAILED example.py::test_2 - AssertionError: assert {'1': 2, '2': 1} == {'1': 2, '2': 1}
```
**Anything else we should know about your project / environment**

**Comment by ericsalo** [comment]
This looks potentially similar to some other bugs I am currently investigating so assigning to myself.

**Comment by ericsalo** [comment]
I'm going to close this as a Won't Fix. The fact that this comparison happened to accidentally work in previous implementations is unfortunate. Generally speaking a protobuf map and a Python dictionary are two distinct types. Each is going to implement its own hash function and therefore iterate its keys in its own order. I suspect what happened is that previous implementations used Python directly to implement their maps, giving the illusion of sameness. Getting this to work with upb would be non-trivial and the cost would almost certain outweigh the benefits, especially since that would open the door to needing to support this kind of behavior across all other languages as well.

**Comment by ericsalo** [comment]
Having said all that...a cursory look at the Python source suggests that this should just be working anyway. So, we may investigate a bit further and if it happens that we can get this for free, we may add it anyway.

**Comment by ericsalo** [comment]
It turns out that we fixed a different bug in the 21.5 release which may have also fixed this one. Please update to the current release and let us know whether the problem persists.

**Comment by gen-xu** [comment]
@ericsalo yes I think this commit fixed issue https://github.com/protocolbuffers/upb/commit/fcb666d0401f10267a979a2f9d525084272930c6

**Comment by ericsalo** [comment]
Well okay, then! Awesome!
