### ISSUE TITLE
Support C++11 enum class Sample : char {}

### ISSUE THREAD

**Issue by chengm349** [protocolbuffers/protobuf#10147]
**What language does this apply to?**
proto3
C++

**Describe the problem you are trying to solve.**
current integer enum is not descriptive

**Describe the solution you'd like**
as requested. So I can use
enum class Sample : char {
  value = 'A';
}
**Describe alternatives you've considered**
No
**Additional context**

**Comment by esorot** [comment]
The cost to implement such a feature across all languages would outweigh the benefits. As a workaround, you can also use the ASCII int value then cast in your application to the appropriate char value. The only restriction on enum being that you have a 0 value as the default.
