### ISSUE TITLE
Add possibility to generate Kotlin message builder with DSL param either as a receiver or as an argument

### ISSUE THREAD

**Issue by sokomishalov** [protocolbuffers/protobuf#10144]
It would be great to have the possibility to generate a Kotlin message builder with DSL param as an argument:
```kt
public inline fun smth(block: (Smth.Dsl) -> Unit): Smth =
    SmthKt.Dsl._create(Smth.newBuilder()).also(block)._build()
    
val smth = smth { // use "it" rather than "this"
   it.foo = "foo"
   it.bar = 1
}
```

**Comment by deannagarcia** [comment]
How would this be different/better than the existing copy message:

```
inline fun MyMessage.copy(block: MyMessageKt.Dsl.() -> kotlin.Unit): MyMessage =
  MyMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
```

which allows for

```
val message = myMessage {
  foo = "foo"
}
val copiedMessage = message.copy {
  foo = "bar"
}
```

**Comment by sokomishalov** [comment]
@deannagarcia this approach should be applied to `copy` method as well
```kt
val message = myMessage { m ->
  m.foo = "foo"
}
val copiedMessage = message.copy { m ->
  m.foo = "bar"
}
```

**Comment by deannagarcia** [comment]
I still don't completely understand your proposal or what it provides. Can you provide a specific example of something you want to do with this but can't do with the existing DSL? Or a way that it improves on the DSL?

**Comment by deannagarcia** [comment]
Closing due to no response, feel free to reopen with more examples.
