### ISSUE TITLE
Toggle lite/full generation using protoc switch

### ISSUE THREAD

**Issue by zpostfacto** [protocolbuffers/protobuf#10145]
I would like to take the same .proto source and run protoc with different options to generate both regular and lite versions.  Because the memory/speed tradeoff varies per target platform.  (E.g. a client running on the Nintendo Switch versus a gameserver on linux.)

To my understanding, right now you control whether the output is "lite" or not by putting

`option optimize_for = LITE_RUNTIME; `

in the .proto file.  (If I'm wrong, please correct me, and accept my apology for wasting your time!)

What I'd like to do is add an option to the protoc compiler to control the "optimize" option, overriding anything that is present in the file.

I am totally happy doing this work and submitting a PR, if you give me opinions on the concept and some guidance on specific details, such as:
* What should the option name be?  (My opinion: `--optimize_for=value`)
* How should we handle it if the .proto file contains an optimize_for option?  Ignore it, issue a warning, treat as error, is there a separate option to force the override, etc.  (My opinion: silently ignore any existing `option optimize_for`.  if you used the option, you know that you are overriding this.)
* Do you want to make this more general, e.g. a generic method for overriding any option? (My opinion: no)

**Comment by acozzette** [comment]
This is actually already possible (at least for C++), though I don't think we have documented it anywhere. You can pass `--cpp_opt=lite`, `--cpp_opt=speed`, or `--cpp_opt=code_size` to protoc to override the optimization mode from the proto file.

**Comment by zpostfacto** [comment]
Ah, perfect!  Thanks.
