### ISSUE TITLE
clang compiler warning: generated_message_tctable_lite.cc:1740:10: warning: 'return' will never be executed [-Wunreachable-code-return]

### ISSUE THREAD

**Issue by rvandermeulen** [protocolbuffers/protobuf#10155]
```
protobuf/src/google/protobuf/generated_message_tctable_lite.cc:1740:10: warning: 'return' will never be executed [-Wunreachable-code-return]
  return Error(PROTOBUF_TC_PARAM_PASS);
         ^~~~~
```
Looks like a legit warning from what I can see, but I'm not sure if the solution is as simple as deleting the one line or if some other refactoring is needed. Happy to submit a PR depending on the desired solution.

**Comment by fowles** [comment]
Compilers like to produce conflicting errors about missing returns and non-executable ones.  We generally do not whack these moles.
