### ISSUE TITLE
Protobuf's constant initialization is not actually constant on Windows

### ISSUE THREAD

**Issue by davidben** [protocolbuffers/protobuf#10159]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 20H2

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang-cl from Visual Studio 2019

**What did you do?**
1. Install Visual Studio 2019
2. In the installer, include "C++ Clang tools for Windows"
3. `git clone https://github.com/protocolbuffers/protobuf.git`
4. `cd protobuf`
5. `git submodule update --init --recursive`
6. `cmake -B build-shared -D BUILD_SHARED_LIBS=1 -T ClangCL`
7. `cmake --build build-shared --parallel 16`

**What did you expect to see**
The build should succeed

**What did you see instead?**
The build fails with errors like:

```
...\protobuf\src\google\protobuf\compiler\plugin.pb.cc(75,31): message : required by 'require_constant_initializatio
n' attribute here [...\protobuf\build-shared\libprotoc.vcxproj]
...\protobuf\src\google/protobuf/port_def.inc(656,30): message : expanded from macro 'PROTOBUF_CONSTINIT' [...\pr
otobuf\build-shared\libprotoc.vcxproj]
...\protobuf\src\google\protobuf\compiler\plugin.pb.cc(91,125): error : variable does not have a constant initialize
r [...\protobuf\build-shared\libprotoc.vcxproj]
```

**Anything else we should know about your project / environment**
This was an issue updating protobuf in Chromium. We've applied a workaround by patching out the `PROTOBUF_CONSTINIT` in some configurations, but the root problem is that protobuf's new constant initialization was not actually cross-platform, and relies on assumption that aren't actually universally true.

While, for the repro steps, I used clang-cl, this is only because protobuf has a pre-C++20 version of `PROTOBUF_CONSTINIT` for Clang, `[[clang::require_constant_initialization]]`. When protobuf moves to C++20, I expect it will have the same problem on MSVC.

This happens because the protobuf constant initialization assumes it can reference `&fixed_address_empty_string`. `fixed_address_empty_string` lives in the protobuf dll, so when referenced from another dll or exe, is `__declspec(dllimport)`. But pointers to `dllimport` variables require a static initializer on Windows. See https://godbolt.org/z/5rn4xWrhE. As I understand it, Windows does not have a suitable relocation to express this.

As a result, the new constant initialization actually requires a per-message static initializer, which trips `PROTOBUF_CONSTINIT` and fails to build.

**Comment by davidben** [comment]
> When protobuf moves to C++20, I expect it will have the same problem on MSVC.

Yup! See https://godbolt.org/z/qTxb8vocb

**Comment by goldenbull** [comment]
I have the same problem. I have to use c++20 because `std::format` is only available in c++20. Currently I have to hack the header file `google\protobuf\port_def.inc`, change `#define PROTOBUF_CONSTINIT constinit` to `#define PROTOBUF_CONSTINIT`

**Comment by justusranvier** [comment]
Protobuf compilation on Windows is completely broken and they closed the bug as "not planned".

Wonderful.

Not only that, but they intentionally set up the headers with this so you can't even manually apply a define to fix their broken logic:

```
#ifdef PROTOBUF_CONSTINIT
#error PROTOBUF_CONSTINIT was previously defined
#endif
```

**Comment by googleberg** [comment]
This shouldn't have been autoclosed.

**Comment by LJXLJXLJX** [comment]
> Ran into this upon update to [4?.] 25.0, building w. clang-cl. Also many invalid offsetof() warnings..

Same here. MSVC can pass the compilation but clang-cl fail.

**Comment by kelteseth** [comment]
This issue is still valid and should be reopened.

**Comment by o3wiz** [comment]
Why was this issue closed?

**Comment by googleberg** [comment]
We've had trouble getting this prioritized since the development team doesn't have a good Windows test bed and the issue autocloser keeps closing it.

**Comment by SportsDataPlayground** [comment]
Unable to build cmake's [FindProtobuf example](https://cmake.org/cmake/help/latest/module/FindProtobuf.html#example-using-protobuf) with llvm 20.1.8 from msvs 2026 (clang-cl), with MSVC it is fine. protobuf v33.0.

**Comment by esrauchg** [comment]
> Protobuf compilation on Windows is completely broken and they closed the bug as "not planned".

Sorry about the bug, but if this is an issue only with clang-cl and not with MSVC that wouldn't really be 'completely broken on Windows'. Formally speaking Google's OSS policy support matrix doesn't extend to clang-cl (though we try to support it anyway):

https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md

We've had a number of annoying edge cases with constexpr differences on different platforms and versions of compilers, and it has unfortunately been a costly whackamole even when limited to the official support matrix. If three is a clang-cl specific patch that fixes it, we would almost definitely accept the PR.

**Comment by davidben** [comment]
@esrauchg No, the updated issue title is incorrect. Please reread the original report, which both makes this clear and provides a godbolt that demonstrates this. In both clang-cl and MSVC, there is a static initializer. The only thing that is clang-cl-specific is the Clang-specific pre-C++20 variant of `constinit`. But this is purely what makes the problem visible, not the underlying problem. Also see https://github.com/protocolbuffers/protobuf/issues/10159#issuecomment-1162243165

Indeed you'll see how https://github.com/protocolbuffers/protobuf/pull/10232/files "fixed" this by suppressing the `constinit` on MSVC. The quotation marks (also in the original PR) are correct because you all didn't fix it, only suppressed what was making the problem visible.

Additionally, given how Windows is supported in both Chromium and google3, I find protobuf's position that clang-cl is unsupported rather dubious. I filed this based on a need that Chromium had. Regardless, there was nothing clang-cl-specific about this.

**Comment by davidben** [comment]
I've reverted the incorrect issue title, but I can't update the rest of the incorrect triaging on my own.

**Comment by esrauchg** [comment]
Discussed with davidben offline, I misunderstood a number of things from the previous replies. My mistake and thanks for reverting the title back.

**Comment by davidben** [comment]
Uploaded cl/850876823 (internal), which is https://github.com/protocolbuffers/protobuf/pull/25086. I _think_ that will fix the workaround a bit? Going through the history, it seems the workaround was actually OK-ish when first added in c1278f83587fd4084e487451440082c620a4474a, but then it got messed up over time as folks misinterpreted a Windows dll limitation for something specific to MSVC and/or clang-cl.

**Comment by sbenzaquen** [comment]
Is this fixed by the work in https://github.com/protocolbuffers/protobuf/commit/38927bf2b93a42e2a155b49f9d610c70cc5942ec ?
