### ISSUE TITLE
Clang Static Analyzer detected: Called function pointer is null (null dereference)

### ISSUE THREAD

**Issue by tommy87** [protocolbuffers/protobuf#10161]
Running the static analyzer on Ubuntu22.04 on code which uses Protobuf (Protobuf Package Version: 3.12.4-1ubuntu7) will lead to the error "Called function pointer is null (null dereference)" in file "/usr/include/google/protobuf/metadata_lite.h"

![Screenshot 2022-06-22 155759](https://user-images.githubusercontent.com/2715569/175048718-ba2b7190-95ff-4113-940f-16e05c8621d2.jpg)

[2022-06-22-125401-1971-1.zip](https://github.com/protocolbuffers/protobuf/files/8958311/2022-06-22-125401-1971-1.zip)

**Comment by fowles** [comment]
This is a false positive.  You cannot have a null pointer when `have_unknown_fields` returns true
