### ISSUE TITLE
protobuf-all-21.1.zip contains protobuf-3.21.1/

### ISSUE THREAD

**Issue by ejona86** [protocolbuffers/protobuf#10172]
Downloading the release binary from https://github.com/protocolbuffers/protobuf/releases/tag/v21.1 , there is protobuf-all-21.1.zip and protobuf-all-21.1.tar.gz. Extracting them we find the directory protobuf-3.21.1. Clearly there is version confusion and one of the versions should be changed to match the other version.

**Comment by ejona86** [comment]
I don't think you've looked at what I actually wrote. The version on the file does not match the top-level folder in that file. Nothing in the link changes that. Please download and inspect https://github.com/protocolbuffers/protobuf/releases/download/v21.1/protobuf-all-21.1.zip

**Comment by fowles** [comment]
Appologies, I pattern matched too quickly.

**Comment by ejona86** [comment]
Yeah, that will probably be happening more as in day-to-day development people doing cross-language protobuf development will generally be ignoring the major version.

**Comment by deannagarcia** [comment]
Release 21.2 has dist files where the directory matches the file name!
