### ISSUE TITLE
Proto3 optional and Kotlin nullable type compatibility

### ISSUE THREAD

**Issue by j-min5u** [protocolbuffers/protobuf#10178]
**What language does this apply to?** Kotlin
If it's a proto syntax change, is it for proto2 or proto3? Proto3
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
**Describe the solution you'd like**
Hi, I have a question about proto3 optional
since 3.15, protocol buffers support the 'optional' keyword on protobuf message fields
which, when compiled to java, adds a wrapper around the annotated field to enable null check with has~ function.

this is great, and usable in kotlin but it would be awesome if we could just access the optional fields as kotlin nullable field. (which internally does the has~ check in the .value getter ( getValue() for current java impl ) with variating return types between nullable and non-nullable type according to whether it is optional )
currently, this seems impossible to implement since protobuf kotlin uses the java implementation. (+ It would be wrong to alter the java implementation in this direction, since java can't distinguish return type's nullability)
Is there any chance of getting this feature in future versions, maybe by adding an java-independent kotlin implementation of protocol buffers?

**Describe alternatives you've considered**

**Additional context**

**Comment by deannagarcia** [comment]
Kotlin currently has a `getValueOrNull` accessor for message fields. Unfortunately there are no plans to support this for non-message fields because of the reasons you mentioned and a more proto-wide concern about having no default values for non-message fields.

**Comment by yassenb** [comment]
I don't understand the explanation. What's stopping you from replacing the generated Kotlin implementation from, say
```kotlin
    /**
     * `optional int32 quantity = 8;`
     */
    public var quantity: kotlin.Int
      @JvmName("getQuantity")
      get() = _builder.getQuantity()
      @JvmName("setQuantity")
      set(value) {
        _builder.setQuantity(value)
      }
```

to

```kotlin
    /**
     * `optional int32 quantity = 8;`
     */
    public var quantity: kotlin.Int?
      @JvmName("getQuantity")
      get() = if (_builder.hasQuantity()) _builder.getQuantity() else null
      @JvmName("setQuantity")
      set(value) {
        if (value == null) _builder.clearQuantity() else _builder.setQuantity(value)
      }
```

This is a major pain for Kotlin developers used to proper null-safety who have to remember to call `hasQuantity()` to check for what appears to be a not-nullable property `quantity`

**Comment by Wallman** [comment]
@deannagarcia Could you clarify more what blocker from achieving this is? Like @yassenb I don't understand either, and I feel like this could be re-opened if it is possible.

**Comment by mscheong01** [comment]
This was a such a pain that I made a thirdparty protobuf wrapper [codegen library] to be free of this issue.(https://github.com/mscheong01/krotoDC)
It would be great if this could be solved int the original protobuf implementation.

**Comment by Wallman** [comment]
@anandolee @mkruskal-google @haberman 

It seems @deannagarcia is no longer active. Can you take a look? Thanks!

**Comment by haberman** [comment]
Keep in mind that [primitive fields can have default values](https://protobuf.dev/programming-guides/proto2/#optional) (not in proto3, but in proto2 and the upcoming [editions](https://protobuf.dev/news/2023-06-29/) version of proto):

```proto
message Foo {
    optional int32 quantity = 8 [default = "123"];
}
```

If we make the `int32` getter return `null` for unset values, then we have no way of returning the default when it is appropriate to do so.

Optional is not the same as nullable, because primitive fields have default values which must be returned in the case of an unset field.

**Comment by deannagarcia** [comment]
Sorry for the delay, I have been out on leave. See Josh's explanation above about default values.

The other main issue here is language parity. While in kotlin the issue might seem more straightforward, we don't want to implement the `get` function in kotlin to return a different result or work differently than in Java/all other languages we support.
