### ISSUE TITLE
Can we dynamic load a proto file twice？

### ISSUE THREAD

**Issue by daohu527** [protocolbuffers/protobuf#10191]
**What language does this apply to?**
c++ proto2

**Describe the problem you are trying to solve.**
I have two shared libraries both static link a proto file, and load in one process. My question is do this will cause problem?

**Describe alternatives you've considered**
I need to consider the problem of repeated loading of global variables and singletons in the proto.pb.h or proto.pb.cc, Is there anything else I need to check?

**Comment by Austin-Hu** [comment]
@daohu527, I had the [File already exists in database](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor_database.cc#L642) error when trying to load a .proto file twice. And you can review the same issue by searching with `protobuf File already exists in database` from Google, like [here](https://stackoverflow.com/questions/37051635/several-shared-object-using-same-proto-leading-the-the-error-file-already-exist) and [here](https://groups.google.com/g/protobuf/c/RZRCnOywdSk/m/s5QvifLCBgAJ?utm_medium=email&utm_source=footer).

I worked around this issue by setting `option optimize_for = LITE_RUNTIME;` in the .proto file per the [suggesion](https://groups.google.com/g/protobuf/c/RZRCnOywdSk/m/HsOaheyFCQAJ) but it'd remove reflection support.

Hopefully it (or other more elegant solutions) would unblock your work.

**Comment by Austin-Hu** [comment]
@mcy, thanks for your answer! It makes sense to me, and I "resolved" this issue by combining my implementation into single library.

**Comment by daohu527** [comment]
@mcy 
That's the problem. In autonomous driving, modules are loaded by plugins.

Sometimes it's hard to avoid this problem. like
a. proto  // which is a base proto
b.proto (import a.proto)

and 
- in moduleX which include a.proto, then build it as a moduleX.so.
- in moduleY which include b.proto, then build it as a moduleY.so.

Most of the time we will load them into different processes, but sometimes we will load them into one process. Then a. proto will load twice.

This seems to be fine in most cases, because it only overwrites in the case of loading, we do not dynamically load multiple times. But if it is loaded dynamically multiple times, I am not sure that the global variable of protobuf is of static type
