### ISSUE TITLE
protoc generate inconsistent DESCRIPTOR for python

### ISSUE THREAD

**Issue by eric-nextsense** [protocolbuffers/protobuf#10193]
**What version of protobuf and what language are you using?**
Version: main/v3.15.3/v3.21.2 (Tried with both)
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.8

**What did you do?**
Protobuf file:

```
syntax = "proto2";

package io.nextsense;

message Sample {
  repeated float samples = 1;
}
```

I had a pb2.py containing this serialized_pb value:
b'\n\rsamples.proto\x12\x0cio.nextsense"\x19\n\x06Sample\x12\x0f\n\x07samples\x18\x01 \x03(\x02'

When i generate with protoc in the environment i described, same .proto file, i get:
b'\n\rsamples.proto\x12\x0cio.nextsense\"\x19\n\x06Sample\x12\x0f\n\x07samples\x18\x01 \x03(\x01'

The only change is the x02 to x01 at the end.

The proto deserializes without error but the samples array is empty.

If i edit the newly generated pb2.py file and put the x02 value at the end, it works fine, i get data as expected.

**What did you expect to see**

many records in the samples array

**What did you see instead?**

empty array in the samples array

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Cannot remember what version was used to generate the pb2 at first, it was done at least a year ago.

**Comment by haberman** [comment]
I see this:

```
$ python -c 'import sys; sys.stdout.buffer.write(b"""\n\rsamples.proto\x12\x0cio.nextsense"\x19\n\x06Sample\x12\x0f\n\x07samples\x18\x01 \x03(\x02""")' | src/protoc --decode google.protobuf.FileDescriptorProto src/google/protobuf/descriptor.proto 
name: "samples.proto"
package: "io.nextsense"
message_type {
  name: "Sample"
  field {
    name: "samples"
    number: 1
    label: LABEL_REPEATED
    type: TYPE_FLOAT
  }
}
```

```
$ python -c 'import sys; sys.stdout.buffer.write(b"""\n\rsamples.proto\x12\x0cio.nextsense"\x19\n\x06Sample\x12\x0f\n\x07samples\x18\x01 \x03(\x01""")' | src/protoc --decode=google.protobuf.FileDescriptorProto src/google/protobuf/descriptor.proto 
name: "samples.proto"
package: "io.nextsense"
message_type {
  name: "Sample"
  field {
    name: "samples"
    number: 1
    label: LABEL_REPEATED
    type: TYPE_DOUBLE
  }
}
```

It looks like the second payload has the field type as `double`. I can't think of any reason why `protoc` would change a `float` field to `double`. Is there any chance you have a different copy of the proto where the field is `double`?

**Comment by eric-nextsense** [comment]
yes sorry that was a mixup on our side.
