### ISSUE TITLE
Incompatible ABI when building shared libs with cmake vs autotools

### ISSUE THREAD

**Issue by antonio-rojas** [protocolbuffers/protobuf#10209]
**What version of protobuf and what language are you using?**
Version: 21.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 12

**What did you do?**
Compiling shared libraries with autotools doesn't define PROTOBUF_USE_DLLS. Therefore, in
https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/arena.cc#L223
the compiled shared library exports the `ThreadSafeArena::thread_cache_` symbol.

On the other hand, compiling then with cmake defines PROTOBUF_USE_DLLS so the symbol `ThreadSafeArena::thread_cache()` is exported instead in
https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/arena.cc#L217,
which makes the ABI different depending on the build system used.

**Comment by fowles** [comment]
Protobuf does not support heterogenous build modes like this.  Medium term we plan on removing autotools support entirely
