### ISSUE TITLE
An error was reported during make."./.libs/libprotoc.so: error: undefined reference to 'descriptor_table_google_2fprotobuf_2fdescriptor_2eproto'"

### ISSUE THREAD

**Issue by clearlove7plus** [protocolbuffers/protobuf#10205]
**What version of protobuf and what language are you using?**
Version: main/v3.19.1/v3.19.1 etc.
protobuf-cpp-3.19.1.tar.gz
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.3 LTS
**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Go to 
'./autogen.sh 
./configure 
make -j8 '
3. Click on 'terminal'
4. Scroll down to '....'
5. See error

**What did you expect to see**
./.libs/libprotoc.so: error: undefined reference to 'descriptor_table_google_2fprotobuf_2fdescriptor_2eproto'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:3990：protoc] 
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

  CXX      google/protobuf/compiler/main.o
  CXX      google/protobuf/any_lite.lo
  CXX      google/protobuf/arena.lo
  CXX      google/protobuf/arenastring.lo
  CXX      google/protobuf/extension_set.lo
  CXX      google/protobuf/generated_enum_util.lo
  CXX      google/protobuf/generated_message_table_driven_lite.lo
  CXX      google/protobuf/generated_message_tctable_lite.lo
  CXX      google/protobuf/generated_message_util.lo
  CXX      google/protobuf/implicit_weak_message.lo
  CXX      google/protobuf/inlined_string_field.lo
  CXX      google/protobuf/io/coded_stream.lo
  CXX      google/protobuf/io/io_win32.lo
  CXX      google/protobuf/io/strtod.lo
  CXX      google/protobuf/io/zero_copy_stream.lo
  CXX      google/protobuf/io/zero_copy_stream_impl.lo
  CXX      google/protobuf/io/zero_copy_stream_impl_lite.lo
  CXX      google/protobuf/map.lo
  CXX      google/protobuf/message_lite.lo
  CXX      google/protobuf/parse_context.lo
  CXX      google/protobuf/repeated_field.lo
  CXX      google/protobuf/repeated_ptr_field.lo
In file included from /usr/include/string.h:495,
                 from ./google/protobuf/stubs/port.h:39,
                 from ./google/protobuf/stubs/common.h:48,
                 from ./google/protobuf/message_lite.h:45,
                 from google/protobuf/message_lite.cc:36:
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)’ at ./google/protobuf/io/coded_stream.h:706:16,
    inlined from ‘virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) const’ at ./google/protobuf/implicit_weak_message.h:84:28,
    inlined from ‘bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const’ at google/protobuf/message_lite.cc:412:30:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: warning: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX      google/protobuf/stubs/bytestream.lo
  CXX      google/protobuf/stubs/common.lo
  CXX      google/protobuf/stubs/int128.lo
  CXX      google/protobuf/stubs/status.lo
  CXX      google/protobuf/stubs/statusor.lo
  CXX      google/protobuf/stubs/stringpiece.lo
  CXX      google/protobuf/stubs/stringprintf.lo
  CXX      google/protobuf/stubs/structurally_valid.lo
  CXX      google/protobuf/stubs/strutil.lo
  CXX      google/protobuf/stubs/time.lo
  CXX      google/protobuf/wire_format_lite.lo
  CXX      google/protobuf/any.lo
  CXX      google/protobuf/any.pb.lo
  CXX      google/protobuf/api.pb.lo
  CXX      google/protobuf/compiler/importer.lo
  CXX      google/protobuf/compiler/parser.lo
  CXX      google/protobuf/descriptor.lo
  CXX      google/protobuf/descriptor.pb.lo
  CXX      google/protobuf/descriptor_database.lo
  CXX      google/protobuf/duration.pb.lo
  CXX      google/protobuf/dynamic_message.lo
  CXX      google/protobuf/empty.pb.lo
  CXX      google/protobuf/extension_set_heavy.lo
  CXX      google/protobuf/field_mask.pb.lo
  CXX      google/protobuf/generated_message_bases.lo
  CXX      google/protobuf/generated_message_reflection.lo
  CXX      google/protobuf/generated_message_table_driven.lo
  CXX      google/protobuf/generated_message_tctable_full.lo
  CXX      google/protobuf/io/gzip_stream.lo
  CXX      google/protobuf/io/printer.lo
  CXX      google/protobuf/io/tokenizer.lo
  CXX      google/protobuf/map_field.lo
  CXX      google/protobuf/message.lo
  CXX      google/protobuf/reflection_ops.lo
  CXX      google/protobuf/service.lo
  CXX      google/protobuf/source_context.pb.lo
  CXX      google/protobuf/struct.pb.lo
  CXX      google/protobuf/stubs/substitute.lo
  CXX      google/protobuf/text_format.lo
  CXX      google/protobuf/timestamp.pb.lo
  CXX      google/protobuf/type.pb.lo
  CXX      google/protobuf/unknown_field_set.lo
  CXX      google/protobuf/util/delimited_message_util.lo
  CXX      google/protobuf/util/field_comparator.lo
  CXX      google/protobuf/util/field_mask_util.lo
  CXX      google/protobuf/util/internal/datapiece.lo
  CXX      google/protobuf/util/internal/default_value_objectwriter.lo
  CXX      google/protobuf/util/internal/error_listener.lo
  CXX      google/protobuf/util/internal/field_mask_utility.lo
  CXX      google/protobuf/util/internal/json_escaping.lo
  CXX      google/protobuf/util/internal/json_objectwriter.lo
  CXX      google/protobuf/util/internal/json_stream_parser.lo
  CXX      google/protobuf/util/internal/object_writer.lo
  CXX      google/protobuf/util/internal/proto_writer.lo
  CXX      google/protobuf/util/internal/protostream_objectsource.lo
  CXX      google/protobuf/util/internal/protostream_objectwriter.lo
  CXX      google/protobuf/util/internal/type_info.lo
  CXX      google/protobuf/util/internal/utility.lo
  CXX      google/protobuf/util/json_util.lo
  CXX      google/protobuf/util/message_differencer.lo
  CXX      google/protobuf/util/time_util.lo
  CXX      google/protobuf/util/type_resolver_util.lo
  CXX      google/protobuf/wire_format.lo
  CXX      google/protobuf/wrappers.pb.lo
  CXX      google/protobuf/compiler/code_generator.lo
  CXX      google/protobuf/compiler/command_line_interface.lo
  CXX      google/protobuf/compiler/plugin.lo
  CXX      google/protobuf/compiler/plugin.pb.lo
  CXX      google/protobuf/compiler/subprocess.lo
  CXX      google/protobuf/compiler/zip_writer.lo
  CXXLD    libprotobuf-lite.la
  CXX      google/protobuf/compiler/cpp/cpp_enum.lo
  CXX      google/protobuf/compiler/cpp/cpp_enum_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_extension.lo
  CXX      google/protobuf/compiler/cpp/cpp_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_file.lo
  CXX      google/protobuf/compiler/cpp/cpp_generator.lo
  CXX      google/protobuf/compiler/cpp/cpp_helpers.lo
  CXX      google/protobuf/compiler/cpp/cpp_map_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_message.lo
  CXX      google/protobuf/compiler/cpp/cpp_message_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_padding_optimizer.lo
  CXX      google/protobuf/compiler/cpp/cpp_parse_function_generator.lo
  CXX      google/protobuf/compiler/cpp/cpp_primitive_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_service.lo
  CXX      google/protobuf/compiler/cpp/cpp_string_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_doc_comment.lo
  CXX      google/protobuf/compiler/csharp/csharp_enum.lo
  CXX      google/protobuf/compiler/csharp/csharp_enum_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_field_base.lo
  CXX      google/protobuf/compiler/csharp/csharp_generator.lo
  CXX      google/protobuf/compiler/csharp/csharp_helpers.lo
  CXX      google/protobuf/compiler/csharp/csharp_map_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_message.lo
  CXX      google/protobuf/compiler/csharp/csharp_message_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_primitive_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_reflection_class.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_enum_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_message_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_primitive_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_source_generator_base.lo
  CXX      google/protobuf/compiler/csharp/csharp_wrapper_field.lo
  CXX      google/protobuf/compiler/java/java_context.lo
  CXX      google/protobuf/compiler/java/java_doc_comment.lo
  CXX      google/protobuf/compiler/java/java_enum.lo
  CXX      google/protobuf/compiler/java/java_enum_field.lo
  CXX      google/protobuf/compiler/java/java_enum_field_lite.lo
  CXX      google/protobuf/compiler/java/java_enum_lite.lo
  CXX      google/protobuf/compiler/java/java_extension.lo
  CXX      google/protobuf/compiler/java/java_extension_lite.lo
  CXX      google/protobuf/compiler/java/java_field.lo
  CXX      google/protobuf/compiler/java/java_file.lo
  CXX      google/protobuf/compiler/java/java_generator.lo
  CXX      google/protobuf/compiler/java/java_generator_factory.lo
  CXX      google/protobuf/compiler/java/java_helpers.lo
  CXX      google/protobuf/compiler/java/java_kotlin_generator.lo
  CXX      google/protobuf/compiler/java/java_map_field.lo
  CXX      google/protobuf/compiler/java/java_map_field_lite.lo
  CXX      google/protobuf/compiler/java/java_message.lo
  CXX      google/protobuf/compiler/java/java_message_builder.lo
  CXX      google/protobuf/compiler/java/java_message_builder_lite.lo
  CXX      google/protobuf/compiler/java/java_message_field.lo
  CXX      google/protobuf/compiler/java/java_message_field_lite.lo
  CXX      google/protobuf/compiler/java/java_message_lite.lo
  CXX      google/protobuf/compiler/java/java_name_resolver.lo
  CXX      google/protobuf/compiler/java/java_primitive_field.lo
  CXX      google/protobuf/compiler/java/java_primitive_field_lite.lo
  CXX      google/protobuf/compiler/java/java_service.lo
  CXX      google/protobuf/compiler/java/java_shared_code_generator.lo
  CXX      google/protobuf/compiler/java/java_string_field.lo
  CXX      google/protobuf/compiler/java/java_string_field_lite.lo
  CXX      google/protobuf/compiler/js/js_generator.lo
  CXX      google/protobuf/compiler/js/well_known_types_embed.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_enum.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_enum_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_extension.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_file.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_generator.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_helpers.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_map_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_oneof.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_primitive_field.lo
  CXX      google/protobuf/compiler/php/php_generator.lo
  CXX      google/protobuf/compiler/python/python_generator.lo
  CXX      google/protobuf/compiler/ruby/ruby_generator.lo
  CXXLD    libprotobuf.la
  CXXLD    libprotoc.la
  CXXLD    protoc
./.libs/libprotoc.so: error: undefined reference to 'descriptor_table_google_2fprotobuf_2fdescriptor_2eproto'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:3990：protoc]

**Comment by boegel** [comment]
I'm running into this same problem with `protobuf` 3.21.9...

@clearlove7plus Do you have any updates on this?

**Comment by boegel** [comment]
It seems like this problem is fixed by https://github.com/protocolbuffers/protobuf/pull/11032

**Comment by NobinPegasus** [comment]
@boegel I'm facing the same error.
But I don't know how to use the fix you suggested.

**Comment by boegel** [comment]
@NobinPegasus The patch file we used in https://github.com/easybuilders/easybuild-easyconfigs/pull/16937/files shows the code changes that need to be made to circumvent the problem
