### ISSUE TITLE
How can I get enum type name with lower version protobuf(3.5.2)?

### ISSUE THREAD

**Issue by foreverlms** [protocolbuffers/protobuf#10203]
I have downgraded my protobuf version from 3.19 to 3.5.2. And for enum type. the method `Enum_name()` doesn't exist anymore.

And I searched the stackoverflow:
https://stackoverflow.com/questions/32161409/how-to-get-protobuf-enum-as-string

Also, I haven't found a generated method like `UserStatus_descriptor()` in generated h/cpp files.

Any one has some suggestions?

**Comment by deannagarcia** [comment]
Protobuf version 3.5.2 is 5 years old and does not contain the newer convenience methods that are available now. If you would like to use those you should use a newer protobuf version.
