### ISSUE TITLE
missing distfiles for 21.2 release

### ISSUE THREAD

**Issue by 0-wiz-0** [protocolbuffers/protobuf#10204]
The 21.2 release only has the protoc-* files not the language specific protobuf-* files.
Compare:
https://github.com/protocolbuffers/protobuf/releases/tag/v21.1
with
https://github.com/protocolbuffers/protobuf/releases/tag/v21.2

Please add the missing distfiles. Thanks!

**Comment by deannagarcia** [comment]
We can post them but we are considering not releasing them anymore since you can download the source code from the release automatically. What is your use case for needing the language specific zip/tar files?

**Comment by 0-wiz-0** [comment]
We're using the distfile in pkgsrc for packaging. We only package the C bindings, so we don't need the rest; and we currently use the autoconf framework for building - the old distfile included the generated files (configure, Makefile.in), the "src" tarball from github does not.
These are of course solvable problems. If you say "just use the src tarball" we can switch to that, but I had thought it was an oversight.

**Comment by 0-wiz-0** [comment]
Oh, one more thing - the tarball for the 21.1 release was called "3.21.1", why is the version number different there?

**Comment by fowles** [comment]
That is an error on our part from when we adjusted our versioning scheme

**Comment by zhangskz** [comment]
Unless I'm misunderstanding something, I think the version numbers are correct. For 21.1, the language-specific artifacts include the per-language major version (4.21.1 for python, 3.21.1 for other languages) but protobuf-all still shows 21.1. Is this what you were referring to?

**Comment by deannagarcia** [comment]
Yep it was an oversight on this release. I will work on fixing the bug and releasing them today

**Comment by deannagarcia** [comment]
Dist files are released and the related bug: https://github.com/protocolbuffers/protobuf/issues/10172 has been fixed!
