### ISSUE TITLE
What may caused a printer used in implementating a codeGenerator and construstructed from generator_context.open not generating the output file?

### ISSUE THREAD

**Issue by AlanYiNew** [protocolbuffers/protobuf#10207]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Is there any problem with my following code? Everything works fine except that it's not generating a out.json file and there is no error generated

<pre>
    bool CResourceGenerator::Generate(const FileDescriptor* file,
          const string& parameter,
          GeneratorContext* generator_context,
          string* error) const {
          string filename = file->name();
          string output_filename = filename+"txt";  
          
          Printer printer(generator_context->Open("out.json"), '$');
          for (int i = 0; i < file->message_type_count(); i++) {
              const Descriptor* message_descriptor = file->message_type(i);
              
              for (int j = 0; j < message_descriptor->field_count(); ++j) {
                  const FieldDescriptor* field_descriptor = message_descriptor->field(j);
                  std::map<string, string> vars;
                  vars["func"] = field_descriptor->name();
                  //CMessageGenerator* generator = new CMessageGenerator(message_descriptor);
                  std::cout << field_descriptor->name() << std::endl;
                  printer.Print(vars, "field:$func$;\n");
                  printer.PrintRaw("wtf\n");
              }
          }
    
          return true;
    }

int main(int argc, char* argv[]) {
    //CGenerator generator;
    //google::protobuf::compiler::PluginMain(
    //   argc, argv, &generator);
    google::protobuf::compiler::CommandLineInterface cli;

    CResourceGenerator generator;
    CTotalGenerator cgenerator;

    cli.RegisterGenerator("--foo_out", &generator,
        "Generate Foo file.");
    argc = 6;
    argv[1] = "--foo_out=./";
    argv[2] = "-IC:\\Users\\guoha\\source\\repos\\AConvert\\AConvert\\include";
    argv[3] = "-IC:\\Users\\guoha\\source\\repos\\AConvert\\AConvert\\proto";
    argv[4] = "-IC:\\Users\\guoha\\source\\repos\\AConvert\\AConvert";
    argv[5] = "C:\\Users\\guoha\\source\\repos\\AConvert\\AConvert\\AResource.proto";

   
    return cli.Run(argc, argv);
    
}
</pre>
**What did you expect to see**
The out.json file is geneated with my content printed in.
**What did you see instead?**
I can't find the out.json anywhere.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
windows 10 platform built using visual studio

**Comment by fowles** [comment]
What verion of protobuf are you using?

**Comment by fowles** [comment]
Not sure if it is relevant, but code changes over time and sometimes folks are using very old versions.

**Comment by AlanYiNew** [comment]
> Not sure if it is relevant, but code changes over time and sometimes folks are using very old versions.

The version is 3.21.1. Should be the latest one
