### ISSUE TITLE
Code generator (--pyi_out) doesn't support optional field now (Proto3)

### ISSUE THREAD

**Issue by hantien** [protocolbuffers/protobuf#10246]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
=> proto3
If it's about generated code change, what programming language?
=> Python

**Describe the problem you are trying to solve.**
Currently we're using v3.20.1, and it doesn't support optional field when adding --pyi-out for protoc.

Error message:
>protos/test.proto: is a proto3 file that contains optional fields, but code generator --pyi_out hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.Target //protos:test_py_pb2 failed to build

**Describe the solution you'd like**
Code generator (--pyi_out) can support optional field. Does the team has a plan to support it down the road?

**Comment by haberman** [comment]
Fixed in https://github.com/protocolbuffers/protobuf/commit/a4c9effec11aa7aba35a69c90ed9b3bb550aaa74#diff-01797b24ebb93559bc63461c83e6cd5c06e45904f20cc2c393faff13f3f5d3ce which was release in 4.21.0.

**Comment by hantien** [comment]
Thank you @haberman !
