### ISSUE TITLE
Calling enums Name or Value breaks MyPy typecheck

### ISSUE THREAD

**Issue by arthur-proglove** [protocolbuffers/protobuf#10240]
**What version of protobuf and what language are you using?**
Version: 4.21.2
Language: Python

**What operating system (Linux, Windows, ...) and version?**
ArchLinux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7

**What did you do?**

* Create a simple Protobuf enum 

```proto
enum Foo {
  FOO_ZERO = 0;
  FOO_ONE = 1;
  FOO_TWO = 2;
}
```

* Generate the the Python code

```
protoc --python_out=. --pyi_out=. foo.proto
```

* Use the generated code

```python
from foo_pb2 import Foo

print(Foo.Name(0))
```

* Verify the code with MyPy

**What did you expect to see**

MyPy should pass without errors

**What did you see instead?**

MyPy complains that the type does not have the `Name` attribute

```
 error: "Type[Foo]" has no attribute "Name"
```

**Anything else we should know about your project / environment**

**Comment by ajasmin** [comment]
mypy is reporting errors on the generated stubs. Those will have to be addressed.

Form enums:
```
class MyEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
```

Mixing inheritance and metaclasses is not supported.
```
esmart/proto/firmware/firmware_data_pb2.pyi:154: error: Metaclasses not inheriting from "type" are not supported
```

**Comment by bcmills** [comment]
This seems to still be an issue. I heard Google has some fancy new AI models — any chance you could automate _fixing_ the bugs instead of _ignoring them_ without action?
