### ISSUE TITLE
python: Segfault comparing default message fields with protobuf 4.21.x

### ISSUE THREAD

**Issue by villainy** [protocolbuffers/protobuf#10257]
**What version of protobuf and what language are you using?**
Version: v21.2
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux 20.04.4 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.10.5/3.9.13/3.8.13

**What did you do?**
1. Create a protobuf outer message with an inner submessage field
2. Build python module with protoc v21.2
3. Compare (==) the default value of the outer message's field with a standalone instance of the inner message
4. See Python segfault

**What did you expect to see**

Not a segfault

**What did you see instead?**

A segfault

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Versions:
```
$ lsb_release -d
Description:    Ubuntu 20.04 LTS

$ protoc --version
libprotoc 3.21.2

$ python --version
Python 3.10.5

$ pip show protobuf|grep Version
Version: 4.21.2
```

Minimal reproducible protobuf `repro.proto`:
```protobuf
syntax = "proto3";

package repro;

message OuterMessage {
    uint32 id = 1;
    InnerMessage msg = 2;
}

message InnerMessage {
    uint32 id = 1;
}
```

Minimal reproducible python `repro.py`:
```python
from repro_pb2 import OuterMessage, InnerMessage

outer = OuterMessage(id=1)
inner = InnerMessage(id=2)

outer.msg == inner

print("Segfault before we get here.")
```

Example output:
```
$ ls
repro.proto  repro.py

$ protoc --python_out . repro.proto

$ ls
repro.proto  repro.py  repro_pb2.py

$ python repro.py
Segmentation fault
```

**Anything else we should know about your project / environment**

**Comment by ericsalo** [comment]
This looks identical to https://github.com/protocolbuffers/protobuf/issues/10208, which I fixed three days ago. Please confirm whether this bug still exists after a fresh sync.

**Comment by villainy** [comment]
Confirmed *cannot reproduce* from main. Thanks for the quick reply and sorry for the noise.
