### ISSUE TITLE
text_format Augmented map syntax

### ISSUE THREAD

**Issue by semtexzv** [protocolbuffers/protobuf#10251]
**What language does this apply to?**
text_format

**Describe the problem you are trying to solve.**
Currently, the text_format s a nice debugging tool, However, there are a few drawbacks, when trying to use it as a proper developer-facing interface. One of the issues is maps. We currently don't have a native syntax for specifying maps, apart from emulating them with messages.

**Describe the solution you'd like**
Add following lines to text_format [spec](https://developers.google.com/protocol-buffers/docs/text-format-spec) and implement the changes in text_format parser and generator.

Section Fields:
```
MapMessageField = ScalarValue ":" ( MessageValue | MessageList ) [ ";" | "," ];
MapScalarField = ScalarValue ":" ( ScalarValue | ScalarList ) [ ";" | "," ];
change:
Field = ScalarField | MessageField ;
to: 
Field = ScalarField | MessageField | MapScalarField | MapMessageField ;
```

This would allow us to write a following syntax:

```
position_map {
  "name": 1 ,
  "value: 2
}
```

```
map_field {
  0: "Hello"
  1: "World"
}
```
This format is already used by `protoc --decode_raw`.

**Drawbacks**
Since we're adding new variants to the `Field` syntactic elements, All parsers would  have to have one more branch to reject this element if not applicable

**Describe alternatives you've considered**
Changing the spec in following way
```
MessageField = ScalarValue, [ ":" ], ( MessageValue | MessageList ) [ ";" | "," ];
ScalarField  = ScalarValue, ":",     ( ScalarValue  | ScalarList  ) [ ";" | "," ];
```
Would result in a much simpler grammar, but in this grammar, parser for each message would have to deal with field keys that are literals, and fail if it did not accept the map syntax.

**Additional context**
I'm implementing a protobuf implementation that contains this feature, and since this has been a very useful feature so far, I want to standardize it.

**Comment by acozzette** [comment]
This sounds like it would be a nice thing to have, but unfortunately I don't think we will be able to prioritize this any time soon. Text format changes are not easy to do since they have to be implemented in all languages for consistency.
