### ISSUE TITLE
Protocol Buffer Basics: C++ document typo

### ISSUE THREAD

**Issue by wxgisu** [protocolbuffers/protobuf#10258]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What did you expect to see**
In document [Protocol Buffer Basics: C++](https://developers.google.com/protocol-buffers/docs/cpptutorial), section [The Protocol Buffer API](https://developers.google.com/protocol-buffers/docs/cpptutorial#the-protocol-buffer-api), second paragraph after the code block, I see a sentence saying:

> If you had a singular message field in this example, it would also have a mutable_ method but not a set_ method.

**What did you see instead?**
I expect to see: "If you had a repeated message..."

**Comment by devjgm** [comment]
Fixed: 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/9447643/187981589-029e4999-476a-493a-b952-d5ba9e75e11b.png">
