### ISSUE TITLE
release version error

### ISSUE THREAD

**Issue by Mr1X** [protocolbuffers/protobuf#10253]
![release version](https://user-images.githubusercontent.com/34152252/178914294-8ecd1249-dc02-4969-80b4-ce8cef8dc2b2.png)

**What did you expect to see**

Is the name wrong that protobuf-python ?

**Comment by fowles** [comment]
This was deliberate because it a new major version for python.

https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning
