### ISSUE TITLE
i dont know to handle the problem that  "protobuf requires Python '>=3.7' but the running Python is 3.6.9"

### ISSUE THREAD

**Issue by 1027743011** [protocolbuffers/protobuf#10250]
Hi,
i want to  install  ### bosdyn-client bosdyn-mission bosdyn-api bosdyn-core in ubuntu 18.04, so i  use the command    ### pip3 install bosdyn-client bosdyn-mission bosdyn-api bosdyn-core ,  the terminal will  output ### protobuf requires Python '>=3.7' but the running Python is 3.6.9 . 
i have noticed that someone said protobuf 4.21.0  have already fixed the problem , but when i used ### protobuf-4.21.0-py2.py3-none-any.whl   to pip install ,  the problem will occur again. so what did i do for handle this question 
thanks

**Comment by brenopenia1** [comment]
Note: The following steps might take a bit of time. These packages are said to be successfully installed if the console displays any message like Successfully installed ... after each package installation.

Update the pip package manager.

pip install --upgrade pip
Install the Flask package of version 1.1.2 as follows. Use the following command in the console.

pip install Flask==1.1.2
Install the tensorflow package of version 1.14.0 as follows.

python -m pip install --upgrade setuptools

pip install protobuf==3.17.3

pip install --no-cache-dir  --force-reinstall -I grpcio==1.11.0

pip install tensorflow==1.14.0
Install the pillow package of version 6.2.2 as follows, for working with images(like loading the images which we would see later).

pip install pillow==6.2.2
