### ISSUE TITLE
Please add removeLast() method of repeated values in Java.

### ISSUE THREAD

**Issue by nethibernate** [protocolbuffers/protobuf#10278]
Currently in Java, it appears the only way to remove an element from the list is to get the list from Builder, call clearXXX(), and then call addXXX() for all but the last element. This is an expensive procedure.

Would you please add removeLast() method just like cpp? The remove method of ArrayList in Java will not copy the underlying array if the last element is removed, so it will not impact the performance.

**Comment by googleberg** [comment]
@nethibernate that seems like a reasonable request. We can take a look at this (though it is likely going to be lower on the priority list), or if you'd like to send a PR, we can look at that.
