### ISSUE TITLE
 ./configure: command not found 

### ISSUE THREAD

**Issue by huaizhixu** [protocolbuffers/protobuf#10277]
**What version of protobuf and what language are you using?**
Version: v3.3.x
Language: C++

**What operating system (Linux, Windows, ...) and version?**
ubuntu 16.04
**What runtime / compiler are you using (e.g., python version or gcc version)**GCC
GCC
**What did you do?**
Steps to readme

**What did you expect to see**
successful
**What did you see instead?**
./configure: command not found 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
[stack](https://unix.stackexchange.com/questions/158960/can-not-run-configure-command-no-such-file-or-directory) is not working

**Comment by fowles** [comment]
3.3 is a very old version of protobuf.  Does the problem persist on the 21.x release?

**Comment by huaizhixu** [comment]
I try to compile 21 x. This problem does not exist in the new version, but I want to do embedded porting, so I used a lower version, which caused this problem

**Comment by fowles** [comment]
I am sorry.  3.3 is from 2017 and we simply don't support it any longer.
