### ISSUE TITLE
Ruby Proto3 Struct/Value Support for Encoding to JSON

### ISSUE THREAD

**Issue by mohsin-sq** [protocolbuffers/protobuf#10288]
**What language does this apply to?**
proto3

**If it's about generated code change, what programming language?**

Proto3

**Describe the problem you are trying to solve.**
We would like to use Proto3 Struct/Values to represent JSON, however, no convenience library is provided for the conversion in Ruby as they are in Java/C++. 

For example:

When we try to convert the following JSON:
```
{ "$ref" => "https://example.com/schema#common.String" }
```
We get an error because the proto conversion expects the following:
```
{
   "fields"=> {
      "$ref""=> {
         "string_value"=>"https://example.com/schema#common.String" 
      }
   }
}
```

**Describe the solution you'd like**

Add a helper library to do the conversion or build it into the generated code.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangskz** [comment]
This seems like a reasonable utility to add, perhaps in a new `protobuf/ruby/utils` folder. I think helper library similar to Java/C++ makes more sense instead of adding to generated code.

We're unlikely to get to this super soon, but you're welcome to contribute and send us a PR for this as well.

**Comment by haberman** [comment]
> `{ "$ref" => "https://example.com/schema#common.String" }`

This is not JSON, this is a Ruby `Hash`. So it's true, this will not work:

```
>>> Google::Protobuf::Struct.new({"$ref" => "https://example.com/schema#common.String"})
(irb):4:in `initialize': Unknown field name '$ref' in initialization map entry. (ArgumentError)
```

However if you turn this into JSON first, it will work:

```
>>> Google::Protobuf::Struct.decode_json(JSON.generate({"$ref" => "https://example.com/schema#common.String"}))
=> <Google::Protobuf::Struct: fields: {"$ref"=><Google::Protobuf::Value: string_value: "https://example.com/schema#common.String">}>
```

This is equivalent to the following JSON. The Ruby `json_decode` function supports all of the same well-known types cases as Java and C++:

```
>>> Google::Protobuf::Struct.decode_json('{"$ref":"https://example.com/schema#common.String"}')
=> <Google::Protobuf::Struct: fields: {"$ref"=><Google::Protobuf::Value: string_value: "https://example.com/schema#common.String">}>
```

I'll close this now since we support the expected functionality here.
