### ISSUE TITLE
Unable to reserve a 0 value Enum.

### ISSUE THREAD

**Issue by collinforsyth** [protocolbuffers/protobuf#10287]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.19.4
Language: Go

**What operating system (Linux, Windows, ...) and version?**
Mac OS

**What runtime / compiler are you using (e.g., python version or gcc version)**
`protoc-gen-go v1.26.0`

**What did you do?**
```proto
syntax = "proto3";
package test;
option go_package = "github.com/collinforsyth/test";


// This compiles!
enum GoodEnum {
	G_FOO = 0;
	G_BAR = 1;
}

// This also compiles
enum ReservedEnum {
	reserved 1;
	R_FOO = 0;
	R_BAR = 2;
}

// This does not compile
enum BadEnum {
	reserved 0;
	B_FOO = 1;
	B_BAR = 2;
}
```

2. Compile this proto:
```bash
protoc test.proto --go_out=./ --go_opt=module=github.com/collinforsyth/test
```

**What did you expect to see**
A compiled version of the `BadEnum`.

**What did you see instead?**
```
test.proto:22:17: The first enum value must be zero in proto3.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I suppose I'm really just looking for clarification if this is intentional or not. Personally, I think that being able to reserve the first value of an enum makes sense in the case that value is no longer intended to be used for an enum.

**Comment by fowles** [comment]
proto3 requires the first enum field to be zero.  This is a hard requirement, so you cannot do what you want here.

**Comment by collinforsyth** [comment]
Any chance you could clarify why?

**Comment by fowles** [comment]
This choice predates me, so I cannot give you the full context.  The general strokes of it are:

- proto3 decided to have zero defaults for everything and not to allow them to be configuration
- proto2 enums default to the first enum value

Speculating, I believe that this combined to make the fastest path forward to be for proto3 to require zero be the first enum value.

**Comment by collinforsyth** [comment]
> This choice predates me, so I cannot give you the full context. The general strokes of it are:
> 
> * proto3 decided to have zero defaults for everything and not to allow them to be configuration
> * proto2 enums default to the first enum value
> 
> Speculating, I believe that this combined to make the fastest path forward to be for proto3 to require zero be the first enum value.

Ok thanks for clarifying, and appreciate the quick follow up!
