### ISSUE TITLE
Ruby: extension types should define a proper `memsize` function

### ISSUE THREAD

**Issue by casperisfine** [protocolbuffers/protobuf#10280]
Here's an snippet from a Ruby heap dump (generated with `ObjectSpace.dump_all`

```
{"address":"0x7fa2dadd7320", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
{"address":"0x7fa2dadd1678", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
{"address":"0x7fa2dadd3c70", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
{"address":"0x7fa2dadcfaa8", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
{"address":"0x7fa2dadc9c98", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
{"address":"0x7fa2dadcb390", "type":"DATA", "class":"0x7fa3eb7ab408", "struct":"Google::Protobuf::Internal::Arena", "memsize":40}
```

As you can see, all these `Google::Protobuf::Internal::Arena` instances claim to be 40 bytes, which is obviously a lie.

This is because the `memsize` function is not defined: https://github.com/protocolbuffers/protobuf/blob/520c601c99012101c816b6ccc89e8d6fc28fdbb8/ruby/ext/google/protobuf_c/protobuf.c#L192

**What language does this apply to?**

Ruby

**Describe the problem you are trying to solve.**

I'd like to have a semi-accurate idea of how much memory the `google-protobuf` gem is holding onto.

**Describe the solution you'd like**

I'd like these functions to be defined (`Arena`, `Message`, etc). They don't have to be 100% accurate, not particularly fast. It's a debugging facility.

**Describe alternatives you've considered**

I don't see any.

cc @zhangskz because https://github.com/protocolbuffers/protobuf/issues/9384#issuecomment-1189950068

**Comment by zhangskz** [comment]
This makes sense and would be helpful as a whole for debugging and understanding memory usage.

We previously investigated implementing `dsize` which similarly allows extensions to report the object's memory per [ruby extension documentation](https://github.com/ruby/ruby/blob/master/doc/extension.rdoc#c-struct-to-ruby-object-) when addressing memory leak  https://github.com/protocolbuffers/protobuf/issues/9467. 

Implementing a trivial dsize that reported a large number didn't help trigger more frequent GC so we didn't pursue this further at the time, but this is still useful for profiling memory used by Arena objects.

**Comment by casperisfine** [comment]
> We previously investigated implementing `dsize` which similarly allows extensions to report the object's memory

That's the same thing.

> Implementing a trivial dsize that reported a large number didn't help trigger more frequent GC

Yes it's purely for introspection. To notify the GC of allocations, you need to use the ruby malloc functions.
