### ISSUE TITLE
Versions issue with 3.21 assests

### ISSUE THREAD

**Issue by ronaldpetty** [protocolbuffers/protobuf#10309]
The 3.21.3 protoc assets are missing the major version in the URL and names.

`https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-linux-x86_64.zip`

I thought I would find.

`https://github.com/protocolbuffers/protobuf/releases/download/v3.21.3/protoc-3.21.3-linux-x86_64.zip`

It does report correctly though.

```
root@build:/data# /protoc/bin/protoc --version
libprotoc 3.21.3
```

Not sure if its a bug and missed something.

**Comment by fowles** [comment]
We have changed our major version policy as part of https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning so 21.3 is correct.

The binary itself is still reporting 3.21.3, which we may need to look into.

**Comment by ronaldpetty** [comment]
Thank you @fowles , should I make a new ticket for the binary or just leave this one? Sorry I missed the doc, I did try to look around, just missed it I guess.

**Comment by fowles** [comment]
Just leave this one.  We are talking about how to resolve it internally

**Comment by deannagarcia** [comment]
Fixed with https://github.com/protocolbuffers/protobuf/pull/10386. We need to do more work to migrate the version completely over since our C++ runtime version and compiler version have become very mixed together.
