### ISSUE TITLE
Provide documentation for protobuf_generate

### ISSUE THREAD

**Issue by SamVanheer** [protocolbuffers/protobuf#10303]
**What language does this apply to?**
C++ when using CMake

**Describe the problem you are trying to solve.**
The CMake function [`protobuf_generate`](https://github.com/protocolbuffers/protobuf/blob/316a97bfea2de479787908b9fe9f2bd9e7949d52/cmake/protobuf-config.cmake.in) is undocumented. Aside from a [single example](https://github.com/protocolbuffers/protobuf/blob/316a97bfea2de479787908b9fe9f2bd9e7949d52/examples/CMakeLists.txt#L45) there is no information about how it works or how it should be used.

**Describe the solution you'd like**
The function's purpose, arguments and usage should be documented somewhere.

**Describe alternatives you've considered**
CMake's `FindProtobuf` module [provides documentation](https://cmake.org/cmake/help/latest/module/FindProtobuf.html) for the older `protobuf_generate_cpp` and `protobuf_generate_python` functions but there is no documentation for this newer function.

**Additional context**
CMake's Gitlab has a number of issues related to this: https://gitlab.kitware.com/cmake/cmake/-/issues/?search=protobuf_generate&sort=created_date&state=all&first_page_size=20
Ideally CMake's version of this should be kept in sync with the version in Protobuf itself. This is only needed for module mode `find_package` calls since config mode relies on the version provided by Protobuf.

**Comment by Tradias** [comment]
Indeed, I have just written an article that could act as a foundation for documentation the function. If someone can let me know in what format the documentation should be then I can open a pull request. 

[https://medium.com/3yourmind/generate-grpc-source-files-using-cmake-ec3acd246b45](https://medium.com/3yourmind/generate-grpc-source-files-using-cmake-ec3acd246b45)

**Comment by Logofile** [comment]
Thanks, @Tradias. We are about to launch a major revamp of the docs in a way that our community will be able to submit PRs to help keep everything up-to-date. In the short term, can you create a PR in https://github.com/protocolbuffers/protobuf/tree/main/docs? I will find a better place your content when the new documentation is published.
