### ISSUE TITLE
V3.21.3 An error occurred while executing the EXE file

### ISSUE THREAD

**Issue by WoDeDianNaoPo** [protocolbuffers/protobuf#10307]
![GM5E3W)3S}@$Q~G))GI1J3T](https://user-images.githubusercontent.com/47267137/180605878-2fa72e08-f6a2-4ddd-987a-15ff412ef575.png)

**Comment by anandolee** [comment]
Just translate the Chinese in the picture
无法定位程序输入点： Unable to locate program
于动态链接库： at dll
