### ISSUE TITLE
Published prebuilt protoc archives should make protoc executable

### ISSUE THREAD

**Issue by anuraaga** [protocolbuffers/protobuf#10301]
I didn't check all the OS's but at least the OSX universal binary contains a `protoc` binary which isn't marked executable (i.e., `chmod +x`).

https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-osx-universal_binary.zip

This makes using the archives less convenient by requiring an additional step to mark executable, which is not conventional for such archives from what I've seen. Notably, gRPC plugin archives like the mainline plugins and Go do have the plugin marked executable in their published archives.

Actually, it seems `readme.txt` is marked executable which is probably not intended. Because it has `r-x` permissions for all users, it is not only dubiously executable, but also requires `rm -f` to remove the file. `rw-r--r--` would probably be a better default for it, and `rwxr-xr-x` for `protoc`

**Comment by deannagarcia** [comment]
Thanks for the report! I did some investigation and I think this is only for the OSX universal binary since it's newly published. I will fix this in the release process so the next release gives it proper permissions.

**Comment by deannagarcia** [comment]
I think this has been fixed in newer releases. If you are still seeing this problem, feel free to reopen!
