### ISSUE TITLE
version 3.21.3 Unable to resolve reference 'System.Runtime.CompilerServices.Unsafe'  in Unity 2021 

### ISSUE THREAD

**Issue by xinyangcuncun** [protocolbuffers/protobuf#10311]
Protobuf.dll  type is  netstandard2.0 in Unity 2021 has error

**Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'Google.Protobuf'.**
**Assembly 'Assets/Plugins/Google.Protobuf.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Runtime.CompilerServices.Unsafe'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.**

**Comment by amanda-tarafa** [comment]
Please see my comment here https://github.com/protocolbuffers/protobuf/issues/9618#issuecomment-1185348928 and also take a look at #10085 for related comments and possible workarounds.

Basically, there's not much else we can do on this repo, as this is just Unity moving away from .NET standards, which will continue to follow.

I'll close this issue now, but do feel free to leave a comment if you belive we could help further.
