### ISSUE TITLE
Deprecation warnings when generating Kotlin binding 

### ISSUE THREAD

**Issue by lemartin** [protocolbuffers/protobuf#10328]
**What version of protobuf and what language are you using?**
Version: v3.21.4
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
Debian 11.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Kotlin 1.7.10

**What did you do?**
1. Deprecate a field in a proto message 
    ```
    syntax = "proto3";
    
    message Foo {
      string bar = 1 [deprecated = true];
    }
    ```
3. Generate Kotlin binding
4. Observe Kotlin compile output

**What did you expect to see**

I did expect to see *no* deprecation warnings for the deprecated field, when generating the Kotlin binding. I do expect deprecation warnings only when using the deprecated field in non-generated code.

**What did you see instead?**

Deprecation warnings during compilation.

```
w: .../kotlin-protoc/build/generated/source/proto/main/kotlin/FooKt.kt: (28, 24): 'getBar(): String!' is deprecated. Deprecated in Java
w: .../lemartin/kotlin-protoc/build/generated/source/proto/main/kotlin/FooKt.kt: (31, 18): 'setBar(String!): FooOuterClass.Foo.Builder!' is deprecated. Deprecated in Java
w: .../kotlin-protoc/build/generated/source/proto/main/kotlin/FooKt.kt: (39, 16): 'clearBar(): FooOuterClass.Foo.Builder!' is deprecated. Deprecated in Java
```

Or, if you use `allWarningsAsErrors=true`, even compilation errors.

**Anything else we should know about your project / environment**

Above example: https://github.com/lemartin/kotlin-protoc

**Comment by fowles** [comment]
This is likely because the builders use the methods from the Java API directly (which are the ones marked deprecated).  We probably need suppresession annotations.

**Comment by deannagarcia** [comment]
Suppression annotations were added in https://github.com/protocolbuffers/protobuf/commit/e8ab276325d9a7598a118022e421cbed581000f6#diff-f34332f53194a822438f42063a2c54982362f4ca665561dea0005af83781641b
