### ISSUE TITLE
[PHP] incorrect large uint32 reading

### ISSUE THREAD

**Issue by akovalevskiy-nexters** [protocolbuffers/protobuf#10335]
Version: v3.21.4
Language: PHP
Host: Mac OS, running in docker: Debian GNU/Linux 11 (php:7.4-cli)
PHP 7.4.30

Steps to reproduce the behaviour:
```
$sourceValue = 0x80000000;
$output = new CodedOutputStream(10);
GPBWire::writeUint32($output, $sourceValue);
$data = $output->getData();
$input = new CodedInputStream($data);
GPBWire::readUint32($input, $protobufValue);
echo $sourceValue . ' => ' . $protobufValue . PHP_EOL;
```

Expect to see:
```2147483648 => 2147483648```

I see:
```2147483648 => -2147483648```

Additional information:
Same situation for all numbers larger than 0x7FFFFFFF, for example for `3437758328` i get `3437758328 => -857208968`. `readUint32` uses `readVarint32`, where leading bits (33-64) are set to 1 for negative numbers. This behaviour is correct for signed numbers, but is wrong for unsigned.

Related issue: https://github.com/protocolbuffers/protobuf/issues/5101

**Comment by esorot** [comment]
duplicate: https://github.com/protocolbuffers/protobuf/issues/10335
