### ISSUE TITLE
iOS交叉编译动态库

### ISSUE THREAD

**Issue by FanChiang911** [protocolbuffers/protobuf#10338]
使用一套c++代码编译pc端、Android、iOS的protobuf动态库，在iOS平台如何编译动态库？

**Comment by perezd** [comment]
Hi there, would you be able to translate this to english for us to help?

**Comment by anandolee** [comment]
Hi FanChiang911, can you help to create another issue with English? So more members in our team can help with it. I do understand Chinese but not familiar with dll in iOS.

Going to close this one and hope you do not mind.
