### ISSUE TITLE
Message Container doesn't provide the generated method that enables ParseContext-based parsing

### ISSUE THREAD

**Issue by afarber** [protocolbuffers/protobuf#10330]
**What version of protobuf and what language are you using?**
Version: 3.21.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
VS 2022, ASP.NET Core 6

**What did you do?**

In my .csproj files I have:

```
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.4" />
    <PackageReference Include="Google.Protobuf.Tools" Version="3.21.4" />
     ...
  </ItemGroup>
```

In my web controller, which receives Protobuf data via HTTP POST I use the code:

```
[HttpPost]
[Route(RouteContainerUpload)]
public async Task UploadDataAsync()
{
    do  // a loop to read complete ReadOnlySequence from BodyReader
    {
        ReadResult readResult = await Request.BodyReader.ReadAsync();
        if (readResult.IsCompleted || readResult.IsCanceled)
        {
            try
            {
                // UPDATE: there is also ProtobufV3 in the real code. The app supports several versions...
                ProtobufV2.Container uplReq = ProtobufV2.Container.Parser.ParseFrom(readResult.Buffer);
                ...
            }
            catch (Exception ex)
            {
                // log parsing exception
            }

            // All bytes in the buffer have been consumed by the app
            // and can now be discarded by the pipe reader.
            Request.BodyReader.AdvanceTo(readResult.Buffer.End);
            Request.BodyReader.Complete();
            break;
        }

        // All bytes in the buffer have been examined by the app,
        // but no bytes have been consumed by the app yet
        // so the pipe reader should continue reading.
        Request.BodyReader.AdvanceTo(readResult.Buffer.Start, readResult.Buffer.End);
    } while (true);
    // send response to the web client
}
```

And I have generated .cs files by using protoc.exe from the [protoc-21.4-win64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v21.4/protoc-21.4-win64.zip) release

```
protoc.exe .\ProtobufV2.proto --csharp_out=..\Model
```

**What did you expect to see**

No exception and the ProtobufV2.Container object has been parsed successfully

**What did you see instead?**

> An exception occurred when parsing upload request: Message Container doesn't provide the generated method that enables ParseContext-based parsing. You might need to regenerate the generated protobuf code.

**Anything else we should know about your project / environment**

In the source code of [ParsingPrimitiveMessages.cs](https://github.com/protocolbuffers/protobuf/blob/main/csharp/src/Google.Protobuf/ParsingPrimitivesMessages.cs) I see the comment:

```
if (ctx.state.CodedInputStream == null)
{
    // This can only happen when the parsing started without providing a CodedInputStream instance
    // (e.g. ParseContext was created directly from a ReadOnlySequence).
    // That also means that one of the new parsing APIs was used at the top level
    // and in such case it is reasonable to require that all the nested message provide
    // up-to-date generated code with ParseContext support (and fail otherwise).
    throw new InvalidProtocolBufferException($"Message {message.GetType().Name} doesn't provide the generated method that enables ParseContext-based parsing. You might need to regenerate the generated protobuf code.");
}
```

But I am not sure, what in my controller code above is causing this or is it a bug.

Thank you

**Comment by jskeet** [comment]
I'm on vacation until Monday, but I'll look then.

**Comment by jskeet** [comment]
Please could you provide the proto file as well, or ideally some minimal version of it that demonstrates the problem? (If you're able to reproduce the problem in a simple console app, that would be absolutely ideal.)

Additionally, could you provide the full stack trace of the error instead of just the message? That would provide some more information about what's going on too.

**Comment by afarber** [comment]
Thank you for replying, Jon! 

The .proto file has 20 messages defined and 2 oneof's. Unfortunately, I cannot distribute it here and I don't have a simple test case to demonstrate the issue yet.

The error messages (delivered by the unit tests) are unfortunately very short:

```
    Log exception: 8/1/2022 4:22:58 PM - An exception occurred when parsing upload request: Message Container doesn't provide the generated method that enables ParseContext-based parsing. You might need to regenerate the generated protobuf code.
Log exception stack trace:    at Google.Protobuf.ParsingPrimitivesMessages.ReadRawMessage(ParseContext& ctx, IMessage message)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, ReadOnlySequence`1 data, Boolean discardUnknownFields, ExtensionRegistry registry)
   at Google.Protobuf.MessageParser`1.ParseFrom(ReadOnlySequence`1 data)
   at VehicleController.UploadDataAsync() in src\FabricApps\Services\VehicleService\Controllers\VehicleController.cs:line 317
```
   
Is there maybe a trick to make them more verbose?

**Comment by afarber** [comment]
I have prepared a console app and will mail the project to you, Jon:

![image](https://user-images.githubusercontent.com/1884458/182177747-8d2074dd-eefb-432a-923f-3a8322073fbd.png)

**Comment by afarber** [comment]
Thank you Jon for finding out that I have used old version of protoc.exe

After I have run the latest protoc-21.4-win64\bin\protoc.exe my issue disappeared and the ReadOnlySequence objects in my unit tests are parsed fine now.
