### ISSUE TITLE
Allow PHP reserved words as valid constant names

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#10331]
As of PHP 7.0, all [the reserved words](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/php/php_generator.cc#L50) listed in `kReservedNames` are now allowed (and can also be added to `kValidConstantNames`) with the exception of `"class"`. Although it'd probably be better to refactor the list to be `kReservedConstantNames` with just "class".

As the latest version of protobuf for PHP now supports a minimum of 7.0, we can open up these words. As changing these would break backwards compatibility, it would be better to target a future major version of protobuf for PHP with this change.

**Comment by bshaffer** [comment]
This is still a valid (and important) change that should be made

**Comment by haberman** [comment]
Reopened. Please feel free to submit a PR for this.
