### ISSUE TITLE
C++ Using reflection, can't get a bool field, which set on 'false'

### ISSUE THREAD

**Issue by Kartofelniy-lord** [protocolbuffers/protobuf#10349]
**What version of protobuf and what language are you using?**
Version: v3.21.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 22.05

**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ 12.01.0

I need to get with reflection variables from protobuf message.
I created .proto file with the next message:
```
message Person {
   bool sync_sign = 1; 
   bool alarm = 2;  
}
```
Then i create object of this message in C++:
```
new_space::Person person;
person.set_alarm( false );
person.set_sync_sign( true );
```
I use google::protobuf::Reflection::ListFields() method to get from this message all fields, which are currently set. Both my variables are set. Then i add this code: 
```
std::vector<const google::protobuf::FieldDescriptor*> vec; // Vector to store descriptors
auto reflection = person.GetReflection(); // Get reflection
reflection->ListFields( person, &vec ); // Put in vector fields from person
std::cout << vec.size() << std::endl; // Print size of vector
```
There with reflection i get vector of google::protobuf::FieldDescriptors of fields, which are currently **set** and then i print size of this vector. The output is `1`. The problem is that bool variable, which set on 'false', is not included in this vector. I suggest this is because in binary in protobuf type bool is Varint. 
![Screenshot_20220802_221612](https://user-images.githubusercontent.com/55811660/182435237-802c8247-4878-417c-9bb6-8820e832bd9d.png)

And 'false' field transorm to zero, so protobuf thinks that this is a field, which is not set and doesn't put this field into vector.
**How can i get with reflection bool field, which set in 'false'?**

**Comment by fowles** [comment]
You can mark the field `optional` to get proper has bit tracking, but a non-optional bool field in proto3 will never report as being set to false explicitly.
