### ISSUE TITLE
Why is Google\Protobuf\Internal\GPBUtil::checkEnum false and it can’t work?

### ISSUE THREAD

**Issue by dongasai** [protocolbuffers/protobuf#10344]
https://github.com/protocolbuffers/protobuf-php/blob/b760544e2ad1225415643ebe1b234c2797c3dad9/src/Google/Protobuf/Internal/GPBUtil.php#L105-L109

There are two parameters when used, but only one is used, the key parameter not use

https://github.com/protocolbuffers/protobuf-php/blob/b760544e2ad1225415643ebe1b234c2797c3dad9/src/Google/Protobuf/Api.php#L343

**Comment by deannagarcia** [comment]
Sorry for the late response. Can you expand on what, if any, errors this is actually causing?
