### ISSUE TITLE
new keywords

### ISSUE THREAD

**Issue by gwojdaszewicz** [protocolbuffers/protobuf#10345]
[This commit](https://github.com/protocolbuffers/protobuf/commit/bade043986a4514ee1877a06ae03d29e081b27c9) added new reserved keywords, can you please create new release with it?

For now i have to override your GPBUtil class in composer.json to make it work like this:
`"autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "exclude-from-classmap": ["vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php"],
        "files": ["src/Google/GPBUtil.php"]
    },`

**Comment by deannagarcia** [comment]
I think this was released in 21.5, please reopen if you are still seeing this issue.
