### ISSUE TITLE
“internalAddGeneratedFile” method  expects exactly 1 parameter, 2 given in GPBMetadata files

### ISSUE THREAD

**Issue by igo9go** [protocolbuffers/protobuf#10347]
https://github.com/protocolbuffers/protobuf-php/blob/ee8f63b02861d88f6cc3955788e97f1912741992/src/Google/Protobuf/Internal/DescriptorPool.php#L58

GPBMetadata files Generated by protoc-gen-grpc
![](http://ww1.sinaimg.cn/large/924848f2ly1g1nbk0chk7j210v0ee0wx.jpg)

**Comment by deannagarcia** [comment]
Sorry for the very late response. I'm going to close this due to age. If you are still seeing this error please provide more details about this problem including version of protoc, environment run, and reproduction instructions.
