### ISSUE TITLE
Protobuf Unexpected Wire Type

### ISSUE THREAD

**Issue by farhanabdmusa** [protocolbuffers/protobuf#10342]
I'm using Google Analytics Data API in PHP 7.2
Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected wire type.

**Comment by Mendel-Chodaton** [comment]
I got the same e issue when i tried to use the google ads api

**Comment by perezd** [comment]
can you please share the actual schemas you are attempting to use? Not sure how to help without a lot more context.
