### ISSUE TITLE
BC Math extension should be a hard requirement

### ISSUE THREAD

**Issue by tab1293** [protocolbuffers/protobuf#10348]
Right now `ext-bcmath` is listed as a suggested dependency in composer.json but it should be a hard dependency. 

Using timestamps in any protobuf definition requires that this extension be installed: https://github.com/protocolbuffers/protobuf-php/blob/master/src/Google/Protobuf/Internal/GPBUtil.php#L461

**Comment by esorot** [comment]
duplicate: https://github.com/protocolbuffers/protobuf/issues/4465
