### ISSUE TITLE
symbol lookup error [undefined symbol: _ZN5Zivid6Detail21InitializeStaticStateC1Ev]

### ISSUE THREAD

**Issue by AbrahamGhanem** [protocolbuffers/protobuf#10352]
**What version of protobuf and what language are you using?**
Version: main/v3.21.4
Language: C++

**What operating system Linux and version? - ubuntu18.04

**What runtime / compiler are you using: g++7.5.0

**What did you do?**
1. Trying to build a docker container to run a c++ application that uses Protobuf libraries, the docker file contains the following run command as described in the README

  RUN apt-get install -y autoconf automake libtool curl make g++ unzip && \
      git clone https://github.com/protocolbuffers/protobuf.git && \
      cd protobuf && \
      git submodule update --init --recursive && \
      ./autogen.sh && \
      ./configure  && \
      make -j$(nproc) # $(nproc) ensures it uses all cores for compilation && \
      make check && \
      make install && \
      ldconfig # refresh shared library cache. 

2.  The build completes successfully with the use of "docker build -t [name] ."
3. When trying to run the docker container with the application inside using "docker run [name]" I get the following error **"symbol lookup error: /app/build/app_name: undefined symbol: _ZN5Zivid6Detail21InitializeStaticStateC1Ev"**

**Comment by deannagarcia** [comment]
I think it's possible that this is just a docker error (maybe from a base image?) or a missing dependency. 

Can you reproduce this issue on a local machine?
