### ISSUE TITLE
Clearly document Ruby/PHP arena GC behavior, and workarounds

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/protobuf#10359]
There is a corner case in Ruby and PHP where joining a short-lived message to a long-lived message will prevent the short-lived message from being GC'd. We should clearly document this issue and the workarounds.

See: https://github.com/protocolbuffers/protobuf/issues/10106

**Comment by haberman** [comment]
@Logofile where would be the best place to document this performance edge case?

**Comment by Logofile** [comment]
The [Ruby generated code guide](https://protobuf.dev/reference/ruby/ruby-generated/) and the [PHP generated code guide](https://protobuf.dev/reference/php/php-generated/) are the most likely candidates.

**Comment by dazuma** [comment]
@haberman This still seems relevant?
