### ISSUE TITLE
Build both static and dynamic libraries

### ISSUE THREAD

**Issue by koudonojinchuu** [protocolbuffers/protobuf#10365]
I use protobuf on Linux, where it is a dependency of many of my distro's packages (in `.so` form),
but I'm also working (for my job) with the statically linked `.a` form (this is a requirement that I cannot change).

Currently it is cumbersome to have both forms available on the system, as I need to launch cmake twice with a different `protobuf_BUILD_SHARED_LIBS` option value.

Would it be possible to allow building both in only one go?

**Comment by junyer** [comment]
https://alexreinking.com/blog/building-a-dual-shared-and-static-library-with-cmake.html describes the contortions needed, but its focus is really on making it ergonomic to use one or the other, so you still end up building and installing twice anyway.
