### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by febrimaulana** [protocolbuffers/protobuf#10369]
`gem install google-protobuf -v 3.21.4 --platform=ruby`

Building native extensions. This could take a while...
ERROR:  Error installing google-protobuf:
        ERROR: Failed to build gem native extension.

    current directory: /Users/febrimaulana/.rvm/gems/ruby-2.3.6@**********/gems/google-protobuf-3.21.4/ext/google/protobuf_c
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/bin/ruby -I /Users/febrimaulana/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0 extconf.rb
creating Makefile

current directory: /Users/febrimaulana/.rvm/gems/ruby-2.3.6@********/gems/google-protobuf-3.21.4/ext/google/protobuf_c
make DESTDIR\= sitearchdir\=./.gem.20220807-73981-q8x4yz sitelibdir\=./.gem.20220807-73981-q8x4yz clean

current directory: /Users/febrimaulana/.rvm/gems/ruby-2.3.6@******/gems/google-protobuf-3.21.4/ext/google/protobuf_c
make DESTDIR\= sitearchdir\=./.gem.20220807-73981-q8x4yz sitelibdir\=./.gem.20220807-73981-q8x4yz
compiling protobuf.c
In file included from protobuf.c:31:
In file included from ./protobuf.h:34:
In file included from /Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:23:
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/oniguruma.h:101:1: error: unknown type name 'RUBY_SYMBOL_EXPORT_BEGIN'
RUBY_SYMBOL_EXPORT_BEGIN
^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/oniguruma.h:832:1: error: unknown type name 'RUBY_SYMBOL_EXPORT_END'
RUBY_SYMBOL_EXPORT_END
^
In file included from protobuf.c:31:
In file included from ./protobuf.h:34:
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:25:25: error: expected ';' after top level declarator
RUBY_SYMBOL_EXPORT_BEGIN
                        ^
                        ;
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:29:28: error: use of undeclared identifier 'RUBY_FL_USHIFT'
    RUBY_ENCODING_SHIFT = (RUBY_FL_USHIFT+10),
                           ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:63:37: error: use of undeclared identifier 'RUBY_FL_USER8'
    RUBY_ENC_CODERANGE_7BIT     = ((int)RUBY_FL_USER8),
                                        ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:64:38: error: use of undeclared identifier 'RUBY_FL_USER9'
    RUBY_ENC_CODERANGE_VALID    = ((int)RUBY_FL_USER9),
                                        ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:65:40: error: use of undeclared identifier 'RUBY_FL_USER8'
    RUBY_ENC_CODERANGE_BROKEN   = ((int)(RUBY_FL_USER8|RUBY_FL_USER9)),
                                         ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:65:54: error: use of undeclared identifier 'RUBY_FL_USER9'
    RUBY_ENC_CODERANGE_BROKEN   = ((int)(RUBY_FL_USER8|RUBY_FL_USER9)),
                                                       ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:118:22: error: unknown type name 'VALUE'
int rb_enc_get_index(VALUE obj);
                     ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:119:23: error: unknown type name 'VALUE'
void rb_enc_set_index(VALUE obj, int encindex);
                      ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:121:26: error: a parameter list without types is only allowed in a function definition
int rb_to_encoding_index(VALUE);
                         ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:122:29: error: a parameter list without types is only allowed in a function definition
rb_encoding *rb_to_encoding(VALUE);
                            ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:123:31: error: a parameter list without types is only allowed in a function definition
rb_encoding *rb_find_encoding(VALUE);
                              ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:124:25: error: a parameter list without types is only allowed in a function definition
rb_encoding *rb_enc_get(VALUE);
                        ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:125:38: error: redefinition of parameter 'VALUE'
rb_encoding *rb_enc_compatible(VALUE,VALUE);
                                     ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:125:32: error: a parameter list without types is only allowed in a function definition
rb_encoding *rb_enc_compatible(VALUE,VALUE);
                               ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:126:33: error: redefinition of parameter 'VALUE'
rb_encoding *rb_enc_check(VALUE,VALUE);
                                ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:126:27: error: a parameter list without types is only allowed in a function definition
rb_encoding *rb_enc_check(VALUE,VALUE);
                          ^
/Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h:127:1: error: unknown type name 'VALUE'
VALUE rb_enc_associate_index(VALUE, int);
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [protobuf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/febrimaulana/.rvm/gems/ruby-2.3.6@*********/gems/google-protobuf-3.21.4 for inspection.
Results logged to /Users/febrimaulana/.rvm/gems/ruby-2.3.6@*********/extensions/x86_64-darwin-21/2.3.0/google-protobuf-3.21.4/gem_make.out

**Comment by febrimaulana** [comment]
what should i do to solve the above problem, because i run "bundle" on my project and error like this

An error occurred while installing google-protobuf (3.21.4), and Bundler cannot continue.

**Comment by haberman** [comment]
I think something is broken in your environment. The compile error you pasted is not coming from protobuf code, it is in the Ruby headers themselves.

I notice that some of your include paths look like:

> /Users/febrimaulana/.rvm/rubies/ruby-2.3.6/include/ruby-2.3.0/ruby/encoding.h

It looks like you have Ruby 2.3.0 inside a directory for Ruby 2.3.6, which seems suspect.
