### ISSUE TITLE
Built-in option 'java-package' not found

### ISSUE THREAD

**Issue by RyanShun-511** [protocolbuffers/protobuf#10370]
I am new to gRPC, I hope you can help me.I'm having trouble writing the.proto file on Android Studio.I want to implement my client on an Android phone.
**What version of protobuf and what language are you using?**
Version: libprotoc 3.21.4.
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
IDEA:Android studio

**What did you expect to see**
I want to write an Android client using gRPC.

**build.gradle(Project)**
plugins {
    id 'com.android.application'
}
apply plugin:'com.google.protobuf'
android {
    compileSdk 31

    defaultConfig {
        applicationId "com.gitlab.grpcdemo"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}
// 和android以及dependencies平级
protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.7.1' }
    plugins {
        javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.20.0' // CURRENT_GRPC_VERSION
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc { // Options added to --grpc_out
                    option 'lite' }
            }
        }
    }
}

dependencies {
    implementation 'io.grpc:grpc-okhttp:1.20.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.20.0'
    implementation 'io.grpc:grpc-stub:1.20.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'

    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.3.5'
    implementation 'androidx.navigation:navigation-ui:2.3.5'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
**build.gradle(Module)**
plugins {
    id 'com.android.application'
}
apply plugin:'com.google.protobuf'
android {
    compileSdk 31

    defaultConfig {
        applicationId "com.gitlab.grpcdemo"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}
// 和android以及dependencies平级
protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.7.1' }
    plugins {
        javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.20.0' // CURRENT_GRPC_VERSION
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc { // Options added to --grpc_out
                    option 'lite' }
            }
        }
    }
}

dependencies {
    implementation 'io.grpc:grpc-okhttp:1.20.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.20.0'
    implementation 'io.grpc:grpc-stub:1.20.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'

    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.3.5'
    implementation 'androidx.navigation:navigation-ui:2.3.5'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
**I think I've got dependencies and plug-ins all worked out.**
**Can someone help me with this? Thanks a million.**

**Comment by DjuroRad** [comment]
I had a similar issue. I was getting it from a plugin
`HIGAN's Protobuf plugin`. 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/65571380/206112906-ace947af-2a31-42ab-9012-87ffb934c732.png">
Try changing it to standard 
`JetBrains Protocol Buffer plugin`
<img width="312" alt="image" src="https://user-images.githubusercontent.com/65571380/206113107-dea4e070-c46f-42d1-9b44-3e234d5e9b45.png">

Hope it works afterwards.
