### ISSUE TITLE
Compiling Mingw-w64

### ISSUE THREAD

**Issue by magicse** [protocolbuffers/protobuf#10381]
**What version of protobuf and what language are you using?**
Version: cpp v3.21.4
Language: C++
Windows 7
GCC 12.0
CMake 3.24

mingw32-make -j4
All compiling well until 83%

here log file with errors

	Line  55: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2584:30: error: expected identifier before numeric constant
	Line  56:  2584 |   enum ReturnCode { SUCCESS, ERROR };
	Line  58: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2584:30: error: expected '}' before numeric constant
	Line  60:  2584 |   enum ReturnCode { SUCCESS, ERROR };
	Line  62: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2584:30: error: expected unqualified-id before numeric constant
	Line  63:  2584 |   enum ReturnCode { SUCCESS, ERROR };
	Line  66: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2547:5: error: 'WriteUnittestProtoDescriptorSet' was not declared in this scope
	Line  69: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2548:5: error: 'duped_stdin_' was not declared in this scope
	Line  73: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2552:10: error: 'duped_stdin_' was not declared in this scope
	Line  77: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2594:15: error: 'GetParam' was not declared in this scope
	Line  80: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2600:39: error: 'unittest_proto_descriptor_set_filename_' was not declared in this scope
	Line  83: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2619:5: error: 'captured_stdout_' was not declared in this scope
	Line  86: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2620:5: error: 'captured_stderr_' was not declared in this scope
	Line  97: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2631:17: error: 'captured_stdout_' was not declared in this scope
	Line 107: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2638:5: error: 'ExpectStdoutMatchesText' was not declared in this scope; did you mean 'ExpectStdoutMatchesTextFile'?
	Line 113: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2642:15: error: 'StripCR' was not declared in this scope
	Line 131: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:156:66: error: template argument 1 is invalid
	Line 149: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/gtest.h:2050:60: error: template argument 1 is invalid
	Line 164: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2642:47: error: 'captured_stdout_' was not declared in this scope
	Line 180: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2646:15: error: 'StripCR' was not declared in this scope
	Line 198: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:156:66: error: template argument 1 is invalid
	Line 216: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/gtest.h:2050:60: error: template argument 1 is invalid
	Line 232: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2646:47: error: 'captured_stderr_' was not declared in this scope
	Line 248: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2650:23: error: 'captured_stderr_' was not declared in this scope
	Line 263: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2650:15: error: 'StripCR' was not declared in this scope
	Line 279: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2654:2: error: expected unqualified-id before 'private'
	Line 283: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2691:18: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_Encode_Test::Run(std::__cxx11::basic_string<char>)'
	Line 297: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2701:10: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_Decode_Test::Run(std::__cxx11::basic_string<char>)'
	Line 313: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2712:10: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_Partial_Test::Run(std::__cxx11::basic_string<char>)'
	Line 329: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2727:18: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_DecodeRaw_Test::Run(const char [13], bool)'
	Line 343: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2736:10: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_UnknownType_Test::Run(std::__cxx11::basic_string<char>)'
	Line 358: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc: In member function 'virtual void google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test::TestBody()':
	Line 359: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2744:10: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test::Run(const char [59])'
	Line 375: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2760:18: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_EncodeDeterministicOutput_Test::Run(std::__cxx11::basic_string<char>)'
	Line 391: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2771:10: error: no matching function for call to 'google::protobuf::compiler::EncodeDecodeTest_DecodeDeterministicOutput_Test::Run(std::__cxx11::basic_string<char>)'
	Line 407: Z:\AI_SDK\CPP_GFPGAN\ProtoBuf_GIT\protobuf-cpp-3.21.4\protobuf-3.21.4\src\google\protobuf\compiler\command_line_interface_unittest.cc:2787:1: error: expected declaration before '}' token
	Line 422: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/internal/gtest-param-util.h: In instantiation of 'class testing::internal::ParameterizedTestFactory<google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test>':
	Line 423: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/internal/gtest-param-util.h:449:12:   required from 'testing::internal::TestFactoryBase* testing::internal::TestMetaFactory<TestSuite>::CreateTestFactory(ParamType) [with TestSuite = google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test; ParamType = google::protobuf::compiler::{anonymous}::EncodeDecodeTestMode]'
	Line 425: Z:/AI_SDK/CPP_GFPGAN/ProtoBuf_GIT/protobuf-cpp-3.21.4/protobuf-3.21.4/third_party/googletest/googletest/include/gtest/internal/gtest-param-util.h:404:7: warning: 'testing::internal::ParameterizedTestFactory<google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test>' has a field 'testing::internal::ParameterizedTestFactory<google::protobuf::compiler::EncodeDecodeTest_ProtoParseError_Test>::parameter_' whose type uses the anonymous namespace [-Wsubobject-linkage]
	Line 447: mingw32-make[2]: *** [CMakeFiles\tests.dir\build.make:151: CMakeFiles/tests.dir/src/google/protobuf/compiler/command_line_interface_unittest.cc.obj] Error 1
	Line 502: mingw32-make[1]: *** [CMakeFiles\Makefile2:324: CMakeFiles/tests.dir/all] Error 2
	Line 503: mingw32-make: *** [Makefile:145: all] Error 2

**Comment by fowles** [comment]
I suspect that there is something defining `SUCCESS` and `ERROR` as a macro before including these files.

**Comment by fowles** [comment]
Very likely there is a file that is missing an include for `port_def.inc`.

**Comment by magicse** [comment]
In <windows.h> ERROR is defined as 0. So unless you were to undefine ERROR before your enum you would be writing

enum ERR_CODE { SUCCESS, 0 };

**Comment by magicse** [comment]
I had replace ReturnCode { SUCCESS, ERROR };
with ReturnCode { B_SUCCESS, B_ERROR };
and all compiled successfully. 

[ 89%] Linking CXX executable tests.exe
[100%] Built target tests

**Comment by magicse** [comment]
may it need change to something like this:  enum ReturnCode { B_SUCCESS=0, B_ERROR=1 };

**Comment by fowles** [comment]
most likely the file that failed to compile is missing an include for port_def.inc

**Comment by magicse** [comment]
The "port_def.inc" file is included as needed in "command_line_interface_unittest.cc"

// Must be included last.
#include <google/protobuf/port_def.inc>

I think the problem is that word "ERROR" is a reserved word windows.h. and the best option is to do it like this: enum ReturnCode { B_SUCCESS=0, B_ERROR=1 }; instead of enum ReturnCode { SUCCESS, ERROR };

**Comment by fowles** [comment]
it shouldn't be a reserved word, it should be a macro and that should be handled in https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/port_def.inc#L877-L878

**Comment by magicse** [comment]
https://www.daniweb.com/programming/software-development/threads/428990/need-help-with-enum-code-error

**Comment by magicse** [comment]
In any way file "port_def.inc" included correctly and it didn't work.
But with changes like this ReturnCode { B_SUCCESS=0, B_ERROR=1 };
**All compiled successfully.**

**Comment by fowles** [comment]
I get that, but I am trying to figure out why this works for all the other compilers we support

**Comment by magicse** [comment]
This is miracle ;-))

**Comment by laramiel** [comment]
It might be related to something special in the mingw build, like this for optional: https://sourceforge.net/p/mingw-w64/bugs/134/
