### ISSUE TITLE
Compiler error in wire_format_lite.cc with clang trunk

### ISSUE THREAD

**Issue by carlosgalvezp** [protocolbuffers/protobuf#10397]
Hi,

I'm getting the following compile error in Clang trunk:

```
src/google/protobuf/wire_format_lite.cc:102:9: error: integer value -1 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
        static_cast<WireFormatLite::WireType>(-1),  // invalid
        ^
```

Casting an integer outside of the range of an unscoped enum without underlying type is Undefined Behavior, which the compiler is required to diagnose on constant expressions.

**Comment by fowles** [comment]
We have an internal fix for this and will push it out soon

**Comment by ayermolo** [comment]
Thanks!
