### ISSUE TITLE
Cannot convert the result of SerializeToString() to str type

### ISSUE THREAD

**Issue by lovepyu** [protocolbuffers/protobuf#10406]
**What version of protobuf and what language are you using?**
Version: main/v3.19.4
Language: Python3.6.8

**What operating system (Linux, Windows, ...) and version?**
Linux and Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
python3.6.8

**What did you do?**
1. msg_tmp = NoticeInfoMsg_pb2.NoticeInfoMsg()
2. msg_serialized = msg_tmp.SerializeToString().decode('utf-8')
3. print(msg_setialized, type(msg_serialized))

**What did you expect to see**
I wish print 'notice_info', and type of msg_serialized is 'str'
**What did you see instead?**
'utf-8' codec can't decode byte 0xea in position 0: invalid continuation byte

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I use proto2, not proto3.

**Comment by anandolee** [comment]
Hi Yingying, SerializeToString() is our wire format. I guess you are looking for something that is human readable. Text format and json format may what you want
