### ISSUE TITLE
Incorrect required_conan_version in conanfile.py

### ISSUE THREAD

**Issue by siaInSpace** [protocolbuffers/protobuf#10405]
**What version of protobuf and what language are you using?**
Version: 3.20.0 also in 3.24.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux - Ubuntu 18.04
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python - 3.6.9
gcc - 8.4.0
conan - 1.48.1

**What did you do?**
1. Add protobuf to conan requirements
2. Run conan install
3. Get error

**What did you expect to see**
Sucessfull installation

**What did you see instead?**
ERROR: protobuf/3.20.0: Cannot load recipe.
....
from conan.tools.files import rename, get, apply_conandata_patches, replace_in_file, rmdir, rm
ImportError: cannot import name 'rm'

With the newest revision to protobuf 3.20.0 on conan center features from conan v1.50.0 was used (conan.tools.files rm). This results in installs using a older conan version to fail. Updating my conan version solves this, or selecting an old revision. However, your conanfile.py claims required_conan_version = ">=1.43.0", which is now false. This should be updated to reflect the usage of newer features

**Comment by anandolee** [comment]
Sorry but I'm afraid there is not much we can do to help unfortunately, because we don't have any involvement with Conan.
You may contact the Conan community and see if they can help
