### ISSUE TITLE
src/README.md instructions for bazel on Ubuntu/Debian don't work

### ISSUE THREAD

**Issue by glandium** [protocolbuffers/protobuf#10419]
The README says:

>   On Ubuntu/Debian, for example, you can install them with:
>   ```
>   sudo apt-get install g++ git bazel
>   ```

There is no bazel package in either Ubuntu or Debian.

**Comment by mkruskal-google** [comment]
Hey Mike,

See https://bazel.build/install for more instructions.  The key step is that you need to route apt to Bazel's repository (https://bazel.build/install/ubuntu#install-on-ubuntu).  The README.md file does link to those instructions, but if you have any ideas on how to make this clearer I'm open to it
