### ISSUE TITLE
protoc can generate conflicting names for synthetic oneof for proto3 optional fields

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#10413]
The code that generates synthetic oneofs [only looks at the names of other fields and oneofs](https://github.com/protocolbuffers/protobuf/blob/aa22c5e0de189b74271335eea179e5321d88768e/src/google/protobuf/compiler/parser.cc#L778-L784). So the following file successfully compiles:
```protobuf
syntax = "proto3";

message Foo {
  optional string oo = 1;

  oneof _oo {
    string X_oo = 2;
  }
}
```
(The synthetic oneof ends up with a name of `XX_oo` to avoid conflicting with the oneof and field already declared.)

However, none of the following files will compile. They all fail with a very mysterious error message that `_oo` is already defined (mysterious unless you are familiar with the implementation details of how proto3 optional fields are represented in the descriptor).
```protobuf
syntax = "proto3";

message Foo {
  optional string oo = 1;

  message _oo {}
}
```

```protobuf
syntax = "proto3";

message Foo {
  optional string oo = 1;

  enum _oo {Z = 0;}
}
```

```protobuf
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message Foo {
  optional string oo = 1;

  extend google.protobuf.MessageOptions {
    string _oo = 1001;
  }
}
```

To avoid these confusing name collisions, the code should also examine the names of nested messages, enums, and extensions, in addition to oneofs and fields.

**Comment by fowles** [comment]
https://github.com/protocolbuffers/protobuf/issues/10491 is the real issue I am going to dedup a bunch of symptoms into as there is really an overarching problem
