### ISSUE TITLE
protoc allows option that incorrectly indicates multiple values for the same map key

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#10411]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.21.5
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
Mac OS 12.5

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
Tried to compile the following source, which should be invalid since it attempts to set multiple values for map key '"foo"`:

```protobuf
// test.proto
syntax = "proto3";
import "google/protobuf/descriptor.proto";
message HasMap {
    map<string, string> m = 1;
}
extend google.protobuf.FileOptions {
    HasMap hm = 1001;
}

option (hm) = {
  m: [
    {key: "foo", value: "bar"},
    {key: "foo", value: "baz"}
  ]
};
```
Compiled via:
```
protoc test.proto -o test.protoset
```

**What did you expect to see**
I expected to see an error related to the fact that a map field can only include a single entry per key.

**What did you see instead?**
The compile succeeded. The resulting descriptor's binary encoding includes both values, which means any code that tries to examine it at runtime will effectively discard the earlier value and see only `"baz"`.

```protobuf
// relevant snippet of output from:
// protoc test.proto google/protobuf/descriptor.proto \
//       --decode google.protobuf.FileDescriptorSet \
//       < test.protoset
  options {
    [hm] {
      m {
        key: "foo"
        value: "bar"
      }
      m {
        key: "foo"
        value: "baz"
      }
    }
  }
```

**Comment by perezd** [comment]
This is correct behavior. We don't enforce order or uniqueness here, as per the wire format, it's possible for you to merge/overload/override any field value and only the "last" value remains present in the resulting output.

Options are encoded as wire format, and so that behavior applies here. You should not rely on the compiler to detect this sort of condition if it's relevant to your needs.

**Comment by perezd** [comment]
For more context, this is outlined in some detail within the scope of this larger article:
https://carlmastrangelo.com/blog/why-does-grpc-insist-on-trailers

**Comment by jhump** [comment]
I am quite familiar that this is valid on the wire. However, contrary to what you suggest is "expected behavior", `protoc` already:
1) Prevents you from setting the same field more than once with options.
2) Prevents you from trying to set more than one field inside a oneof.
Why are the above worthy of validation but the constraints for map keys not? This is a consistency issue.
