### ISSUE TITLE
emscripten wasm-ld: error: 'atomics' feature is disallowed by arena.cc.o

### ISSUE THREAD

**Issue by nsourligas** [protocolbuffers/protobuf#10425]
Hi,

About this issue I have already posted it on the emscripten github repository. From my discussion with the team of emscripten compiler and it seems that for some reason the `arena.cc.o` has to be compiled with `-pthread` option. How it could be possible to do that in my case?

**What version of protobuf and what language are you using?**

Version: 3.15.8
Language: C++, Qt, WebAssembly. emscripten

**What operating system (Linux, Windows, ...) and version?**

Linux Ubuntu 18.04.6 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc: 8.4.0
g++: 8.4.0
Qt: 5.1.5.0
emcc: 1.39.8
em++: 139.8
emscripten: 1.39.8

**What did you do?**

```
CC=emcc CXX=em++ AR=emar cmake .. -Dprotobuf_BUILD_SHARED_LIBS=OFF -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/home/anteam/protobuf-wasm
emmake make libprotoc libprotobuf-lite
emmake make install libprotoc libprotobuf-lite
```

**What did you expect to see**

Compile protobuf library for wasm (WebAssembly) normally and then able to link libraries on my project in order to generate the Qt WebAssembly associated files

**What did you see instead?**

```
wasm-ld: error: 'atomics' feature is disallowed by arena.cc.o, so --shared-memory must not be used
wasm-ld: error: Target feature 'atomics' used in main.o is disallowed by arena.cc.o. Use --no-check-features to suppress.
```

**Comment by anandolee** [comment]
I guess there's not much we can help with the issue. Here seems a better place:
https://github.com/emscripten-core/emscripten/issues/17665
