### ISSUE TITLE
Table Driven has worse performance than base in benchmark

### ISSUE THREAD

**Issue by PandaBlueYellow** [protocolbuffers/protobuf#10421]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Mac Monterey

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 13.1.6 

**What did you do?**
1. `bazel run benchmarks/cpp --copt=-O3 -- $(for file in $(find . -type f -name "dataset.*.pb" -not -path "./tmp/*"); do echo "$(pwd)/$file"; done | xargs)`
2. in top dir BUILD, for cc_toolchain, change command line to `command_line = "--cpp_out=experimental_tail_call_table_mode=always:$(OUT)",`
3. repeat step 1

**What did you expect to see**
step3 has better performance than step1

**What did you see instead?**
step1 has better performance than step3 (e.g., google_message1_proto2_parse_reuse has 718M/s in step 1 but 651M/S in step 3)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Base
------------------------------
Running benchmarks/cpp/cpp_benchmark
Run on (10 X 2400 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x10)
  L1 Instruction 128 KiB (x10)
  L2 Unified 4096 KiB (x5)
Load Average: 39.44, 16.30, 7.91
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
google_message1_proto2_parse_new             670 ns          670 ns      1029366 bytes_per_second=324.715M/s
google_message1_proto2_parse_reuse           303 ns          303 ns      2412013 bytes_per_second=718.606M/s
google_message1_proto2_parse_newarena        845 ns          845 ns       826417 bytes_per_second=257.421M/s
google_message1_proto2_serialize             169 ns          165 ns      4290162 bytes_per_second=1.28381G/s
google_message1_proto3_parse_new             684 ns          682 ns      1007020 bytes_per_second=318.613M/s
google_message1_proto3_parse_reuse           445 ns          445 ns      1552695 bytes_per_second=488.21M/s
google_message1_proto3_parse_newarena        798 ns          798 ns       869738 bytes_per_second=272.56M/s
google_message1_proto3_serialize             163 ns          163 ns      4273609 bytes_per_second=1.26037G/s
google_message2_parse_new                 325679 ns       325620 ns         2147 bytes_per_second=247.688M/s
google_message2_parse_reuse               123359 ns       122421 ns         5850 bytes_per_second=658.811M/s
google_message2_parse_newarena            238273 ns       238112 ns         2928 bytes_per_second=338.716M/s
google_message2_serialize                  65420 ns        65403 ns        10649 bytes_per_second=1.20425G/s

Table Driven
-------------------------
Running benchmarks/cpp/cpp_benchmark
Run on (10 X 2400 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x10)
  L1 Instruction 128 KiB (x10)
  L2 Unified 4096 KiB (x5)
Load Average: 43.41, 19.18, 11.14
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
google_message1_proto2_parse_new             707 ns          707 ns       873112 bytes_per_second=307.553M/s
google_message1_proto2_parse_reuse           334 ns          334 ns      2156301 bytes_per_second=651.292M/s
google_message1_proto2_parse_newarena        900 ns          900 ns       781625 bytes_per_second=241.659M/s
google_message1_proto2_serialize             163 ns          162 ns      4259877 bytes_per_second=1.30759G/s
google_message1_proto3_parse_new             673 ns          673 ns      1031672 bytes_per_second=322.949M/s
google_message1_proto3_parse_reuse           443 ns          443 ns      1594268 bytes_per_second=490.978M/s
google_message1_proto3_parse_newarena        821 ns          820 ns       850547 bytes_per_second=265.013M/s
google_message1_proto3_serialize             157 ns          157 ns      4406756 bytes_per_second=1.30808G/s
google_message2_parse_new                 327690 ns       327596 ns         2120 bytes_per_second=246.194M/s
google_message2_parse_reuse               122555 ns       122555 ns         5677 bytes_per_second=658.089M/s
google_message2_parse_newarena            246321 ns       246099 ns         2816 bytes_per_second=327.722M/s
google_message2_serialize                  65881 ns        65860 ns        10462 bytes_per_second=1.1959G/s

**Comment by fowles** [comment]
Yes, it currently does have worse performance.
