### ISSUE TITLE
protobuf CMake dependency management using add_subdirectory

### ISSUE THREAD

**Issue by cblichmann** [protocolbuffers/protobuf#10435]
I'm having a similar issue to this one reported on gRPC a while back:
https://github.com/grpc/grpc/issues/29608

Namely: I have a C++ project (https://github.com/google/binexport), that already includes Abseil and uses protobuf via CMake's `add_subdirectory()`. \
We don't use the LTS version of Abseil and therefore have no "install" of it (so no `absl-config.cmake`, etc.).

Now, Protobuf only has two modes for using Abseil: "module" (Git submodule) or "package" (system-wide install). Neither works out of the box or without resorting to workaround/hacks.

I suggest a similar solution to the one chosen by the gRPC team: Check if there exists an `absl::strings` target in the project. If there is one, skip any/all special handling for Abseil, as it is already there. If not, continue with `protobug_ABSL_PROVIDER`.

**Comment by cblichmann** [comment]
Note: for PR #10436 to work on a non-LTS Abseil, one needs to set `protobuf_INSTALL` to false before including protobuf.
These are the settings that I just confirmed working:
```CMake
set(protobuf_ABSL_PROVIDER "package" CACHE STRING "" FORCE)
set(protobuf_INSTALL OFF CACHE BOOL "" FORCE)

# Download/check out into `_deps`. This ultimately calls `add_subdirectory()`
FetchContent_MakeAvailable(protobuf)
# Protobuf targets available starting here

# Make protobuf_generate_cpp available by providing necessary info to find_package()
set(Protobuf_INCLUDE_DIR "${protobuf_SOURCE_DIR}/src" CACHE INTERNAL "")
set(Protobuf_LIBRARIES protobuf::libprotobuf CACHE INTERNAL "")
find_package(Protobuf 3.21 REQUIRED)
```

**Comment by mkruskal-google** [comment]
Thanks for the fix Christian!
