### ISSUE TITLE
Error Occurring During Parsing : Unexpected Wire Type

### ISSUE THREAD

**Issue by Mendel-Chodaton** [protocolbuffers/protobuf#10439]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0
Language: PHP

What operating system : Windows, ...) and version 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. I use The google ads api to build an app on shopify
2. The app is suppose to redirect users to google Oauth 2 page when theirs ask to connect and use the app.  
3. After theirs choose theirs google accoun t and complete authorisation; theirs are redirect on the app and can use it. But since i update the google ads pi to V10 i goot this error 
 Google\Protobuf\Internal\GPBDecodeException {#1579 ▼
  #message: "Error occurred during parsing: Unexpected wire type."
  #code: 0
  #file: "/var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php"
  #line: 353
  trace: {▼
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:353 {▼
      Google\Protobuf\Internal\Message->skipField($input, $tag) …
      › case GPBWireType::END_GROUP:
      ›     throw new GPBDecodeException("Unexpected wire type.");
      › default:
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:512 {▼
      Google\Protobuf\Internal\Message->parseFieldFromStream($tag, $input, $field) …
      › if ($value_format === GPBWire::UNKNOWN) {
      ›     $this->skipField($input, $tag);
      ›     return;
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:811 {▼
      Google\Protobuf\Internal\Message->parseFromStream($input) …
      › 
      ›     $this->parseFieldFromStream($tag, $input, $field);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php:289 {▼
      Google\Protobuf\Internal\GPBWire::readMessage(&$input, &$message) …
      ›     $recursion_limit);
      › if ($recursion_limit < 0 || !$message->parseFromStream($input)) {
      ›     return false;
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:435 {▼
      Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag($input, $field, &$value) …
      › }
      › if (!GPBWire::readMessage($input, $value)) {
      ›     throw new GPBDecodeException(
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:515 {▼
      Google\Protobuf\Internal\Message->parseFieldFromStream($tag, $input, $field) …
      › } elseif ($value_format === GPBWire::NORMAL_FORMAT) {
      ›     self::parseFieldFromStreamNoTag($input, $field, $value);
      › } elseif ($value_format === GPBWire::PACKED_FORMAT) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:811 {▼
      Google\Protobuf\Internal\Message->parseFromStream($input) …
      › 
      ›     $this->parseFieldFromStream($tag, $input, $field);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php:289 {▼
      Google\Protobuf\Internal\GPBWire::readMessage(&$input, &$message) …
      ›     $recursion_limit);
      › if ($recursion_limit < 0 || !$message->parseFromStream($input)) {
      ›     return false;
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:435 {▼
      Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag($input, $field, &$value) …
      › }
      › if (!GPBWire::readMessage($input, $value)) {
      ›     throw new GPBDecodeException(
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:515 {▼
      Google\Protobuf\Internal\Message->parseFieldFromStream($tag, $input, $field) …
      › } elseif ($value_format === GPBWire::NORMAL_FORMAT) {
      ›     self::parseFieldFromStreamNoTag($input, $field, $value);
      › } elseif ($value_format === GPBWire::PACKED_FORMAT) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:811 {▼
      Google\Protobuf\Internal\Message->parseFromStream($input) …
      › 
      ›     $this->parseFieldFromStream($tag, $input, $field);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php:289 {▼
      Google\Protobuf\Internal\GPBWire::readMessage(&$input, &$message) …
      ›     $recursion_limit);
      › if ($recursion_limit < 0 || !$message->parseFromStream($input)) {
      ›     return false;
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:435 {▼
      Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag($input, $field, &$value) …
      › }
      › if (!GPBWire::readMessage($input, $value)) {
      ›     throw new GPBDecodeException(
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:515 {▼
      Google\Protobuf\Internal\Message->parseFieldFromStream($tag, $input, $field) …
      › } elseif ($value_format === GPBWire::NORMAL_FORMAT) {
      ›     self::parseFieldFromStreamNoTag($input, $field, $value);
      › } elseif ($value_format === GPBWire::PACKED_FORMAT) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:811 {▼
      Google\Protobuf\Internal\Message->parseFromStream($input) …
      › 
      ›     $this->parseFieldFromStream($tag, $input, $field);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php:289 {▼
      Google\Protobuf\Internal\GPBWire::readMessage(&$input, &$message) …
      ›     $recursion_limit);
      › if ($recursion_limit < 0 || !$message->parseFromStream($input)) {
      ›     return false;
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:435 {▼
      Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag($input, $field, &$value) …
      › }
      › if (!GPBWire::readMessage($input, $value)) {
      ›     throw new GPBDecodeException(
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:515 {▼
      Google\Protobuf\Internal\Message->parseFieldFromStream($tag, $input, $field) …
      › } elseif ($value_format === GPBWire::NORMAL_FORMAT) {
      ›     self::parseFieldFromStreamNoTag($input, $field, $value);
      › } elseif ($value_format === GPBWire::PACKED_FORMAT) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:811 {▼
      Google\Protobuf\Internal\Message->parseFromStream($input) …
      › 
      ›     $this->parseFieldFromStream($tag, $input, $field);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:775 {▼
      Google\Protobuf\Internal\Message->mergeFromString($data) …
      ›     $input = new CodedInputStream($data);
      ›     $this->parseFromStream($input);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/DescriptorPool.php:61 {▼
      Google\Protobuf\Internal\DescriptorPool->internalAddGeneratedFile($data, $use_nested = false) …
      › $files = new FileDescriptorSet();
      › $files->mergeFromString($data);
      › 
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/googleads/google-ads-php/metadata/Google/Ads/GoogleAds/V10/Errors/Errors.php:3353 {▼
      GPBMetadata\Google\Ads\GoogleAds\V10\Errors\Errors::initOnce() …
      › 
      › "in GPBMetadata\Google\Ads\GoogleAds\V10\Errors\Errors::initOnce()"
      › 
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V10/Errors/GoogleAdsFailure.php:45 {▼
      Google\Ads\GoogleAds\V10\Errors\GoogleAdsFailure->__construct($data = null) …
      › public function __construct($data = NULL) {
      ›     \GPBMetadata\Google\Ads\GoogleAds\V10\Errors\Errors::initOnce();
      ›     parent::__construct($data);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Util/V10/GoogleAdsFailures.php:92 {▼
      Google\Ads\GoogleAds\Util\V10\GoogleAdsFailures::init() …
      › ) {
      ›     new GoogleAdsFailure();
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/GoogleAdsClient.php:59 {▼
      Google\Ads\GoogleAds\Lib\V10\GoogleAdsClient->__construct(GoogleAdsClientBuilder $builder) …
      › if (!self::getGrpcDependencyStatus()) {
      ›     GoogleAdsFailures::init();
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/GoogleAdsClientBuilder.php:328 {▼
      Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder->build() …
      › 
      ›     return new GoogleAdsClient($this);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/app/Http/Controllers/GoogleauthController.php:160 {▼
      App\Http\Controllers\GoogleauthController->ListAccessibleCustomers(Request $request) …
      ›         ->withOAuth2Credential($oAuth2Credential)
      ›         ->build();   
      › } catch (Exception $e) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 {▼
      Illuminate\Routing\Controller->callAction($method, $parameters) …
      › {
      ›     return $this->{$method}(...array_values($parameters));
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 {▼
      Illuminate\Routing\ControllerDispatcher->dispatch(Route $route, $controller, $method) …
      › if (method_exists($controller, 'callAction')) {
      ›     return $controller->callAction($method, $parameters);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239 {▼
      Illuminate\Routing\Route->runController() …
      › return $this->controllerDispatcher()->dispatch(
      ›     $this, $this->getController(), $this->getControllerMethod()
      › );
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php:196 {▼
      Illuminate\Routing\Route->run() …
      › if ($this->isControllerAction()) {
      ›     return $this->runController();
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685 {▼
      Illuminate\Routing\Router->Illuminate\Routing\{closure} …
      › return $this->prepareResponse(
      ›     $request, $route->run()
      › );
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › try {
      ›     return $destination($passable);
      › } catch (Throwable $e) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/app/Http/Controllers/Controller.php:28 {▼
      App\Http\Controllers\Controller->App\Http\Controllers\{closure} …
      ›     $shop_name = session('shop');
      ›     return $next($request);
      › });
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      ›     // the appropriate method and arguments, returning the results back out.
      ›     return $pipe($passable, $stack);
      › } elseif (! is_object($pipe)) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/app/Http/Middleware/Cors.php:22 {▼
      App\Http\Middleware\Cors->handle($request, Closure $next) …
      › header('Access-Control-Allow-Headers: Content-Type, Accept, Authorization, X-Requested-With, Application');
      › $response = $next($request);
      › $response->header('Content-Security-Policy', 'frame-ancestors https://'.request()->get('shop').' https://admin.shopify.com');
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 {▼
      Illuminate\Routing\Middleware\SubstituteBindings->handle($request, Closure $next) …
      › 
      ›     return $next($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78 {▼
      Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle($request, Closure $next) …
      › ) {
      ›     return tap($next($request), function ($response) use ($request) {
      ›         if ($this->shouldAddXsrfTokenCookie()) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 {▼
      Illuminate\View\Middleware\ShareErrorsFromSession->handle($request, Closure $next) …
      › 
      ›     return $next($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:116 {▼
      Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Request $request, $session, Closure $next) …
      › 
      › $response = $next($request);
      › 
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62 {▼
      Illuminate\Session\Middleware\StartSession->handle($request, Closure $next) …
      › } else {
      ›     return $this->handleStatefulRequest($request, $session, $next);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 {▼
      Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle($request, Closure $next) …
      › {
      ›     $response = $next($request);
      › 
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67 {▼
      Illuminate\Cookie\Middleware\EncryptCookies->handle($request, Closure $next) …
      › {
      ›     return $this->encrypt($next($this->decrypt($request)));
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 {▼
      Illuminate\Pipeline\Pipeline->then(Closure $destination) …
      › 
      ›     return $pipeline($this->passable);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:687 {▼
      Illuminate\Routing\Router->runRouteWithinStack(Route $route, Request $request) …
      ›                         );
      ›                     });
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662 {▼
      Illuminate\Routing\Router->runRoute(Request $request, Route $route) …
      › return $this->prepareResponse($request,
      ›     $this->runRouteWithinStack($route, $request)
      › );
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:628 {▼
      Illuminate\Routing\Router->dispatchToRoute(Request $request) …
      › {
      ›     return $this->runRoute($request, $this->findRoute($request));
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:617 {▼
      Illuminate\Routing\Router->dispatch(Request $request) …
      › 
      ›     return $this->dispatchToRoute($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:165 {▼
      Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure} …
      › 
      ›     return $this->router->dispatch($request);
      › };
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › try {
      ›     return $destination($passable);
      › } catch (Throwable $e) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▼
      Illuminate\Foundation\Http\Middleware\TransformsRequest->handle($request, Closure $next) …
      › 
      ›     return $next($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▼
      Illuminate\Foundation\Http\Middleware\TransformsRequest->handle($request, Closure $next) …
      › 
      ›     return $next($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 {▶}
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63 {▶}
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/fideloper/proxy/src/TrustProxies.php:57 {▼
      Fideloper\Proxy\TrustProxies->handle(Request $request, Closure $next) …
      › 
      ›     return $next($request);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▼
      Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure} …
      › $carry = method_exists($pipe, $this->method)
      ›                 ? $pipe->{$this->method}(...$parameters)
      ›                 : $pipe(...$parameters);
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 {▼
      Illuminate\Pipeline\Pipeline->then(Closure $destination) …
      › 
      ›     return $pipeline($this->passable);
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:140 {▼
      Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter($request) …
      ›                 ->through($this->app->shouldSkipMiddleware() ? [] : $this->middleware)
      ›                 ->then($this->dispatchToRouter());
      › }
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:109 {▼
      Illuminate\Foundation\Http\Kernel->handle($request) …
      › 
      ›     $response = $this->sendRequestThroughRouter($request);
      › } catch (Throwable $e) {
    }
    /var/www/vhosts/apps.oxedent.com/httpdocs/public/index.php:55 {▼
      › $response = $kernel->handle(
      ›     $request = Illuminate\Http\Request::capture()
      › );
    }
  }
}

**What did you expect to see**
I expect to be redirect on the app. whatever the mistake. This make me incapable to use the google ads api
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by perezd** [comment]
Can you share the .proto file that generated these files?

**Comment by perezd** [comment]
Also, using 3.6.0, is very old and we'd recommend you attempt this with a much newer version of the compiler/runtime. Our latest release is 3.21.5. I'd advise you to update to the latest, and re-open if you still see an issue.

**Comment by perezd** [comment]
OK I'll focus on helping over there, thanks!
