### ISSUE TITLE
install error when protoc is a statically linked executable 

### ISSUE THREAD

**Issue by leleliu008** [protocolbuffers/protobuf#10432]
**What version of protobuf and what language are you using?**
Version: 21.5
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
cmake version 3.24.0

cc --version
cc (Alpine 10.3.1_git20211027) 10.3.1 20211027
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**What did you do?**

```
podman run -it --name alpine-3.16 alpine:3.16 sh

apk add g++ cmake ninja curl tar gzip xz

curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protobuf-all-21.5.tar.gz
tar vxf protobuf-all-21.5.tar.gz --no-same-owner
cd protobuf-21.5
cmake -S . -B build.d -G Ninja -DCMAKE_CXX_FLAGS=-static -DCMAKE_INSTALL_PREFIX=$PWD/out
cmake --build build.d
cmake --install build.d
```

**What did you expect to see**
no error.

**What did you see instead?**
```
-- Install configuration: ""
-- Installing: /protobuf-21.5/out/lib/libprotobuf-lite.a
-- Installing: /protobuf-21.5/out/lib/libprotobuf.a
-- Installing: /protobuf-21.5/out/lib/libprotoc.a
-- Installing: /protobuf-21.5/out/bin/protoc-3.21.5.0
-- Installing: /protobuf-21.5/out/bin/protoc
CMake Error at build.d/cmake_install.cmake:79 (file):
  file RPATH_CHANGE could not write new RPATH:

    $ORIGIN/../lib

  to the file:

    /protobuf-21.5/out/bin/protoc-3.21.5.0

  No valid ELF RPATH or RUNPATH entry exists in the file;
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by leleliu008** [comment]
```
cmake -S . -B build.d -G Ninja -DCMAKE_CXX_FLAGS=-static -DCMAKE_SKIP_RPATH=ON -DCMAKE_INSTALL_PREFIX=$PWD/out
```

this works for me.

**Comment by mkruskal-google** [comment]
It sounds like you figured it out

**Comment by roastduck** [comment]
Same issue here. Although it is possible to configure `CMAKE_SKIP_RPATH=ON` manually, it is quite bothersome because I use Protobuf as a sub-project in CMake. If possible, I would like Protobuf's CMake script to skip changing the RPATH automatically.
