### ISSUE TITLE
Cygwin support breaks due to abseil-cpp

### ISSUE THREAD

**Issue by chronoxor** [protocolbuffers/protobuf#10434]
The latest protobuf build failed in Cygwin due to:
```
#if defined(__CYGWIN__)
#error "Cygwin is not supported."
#endif
```
in protobuf/third_party/abseil-cpp/absl/base/policy_checks.h 

```
In file included from /cygdrive/d/a/CppSerialization/CppSerialization/modules/protobuf/third_party/abseil-cpp/absl/base/config.h:86,
                 from /cygdrive/d/a/CppSerialization/CppSerialization/modules/protobuf/third_party/abseil-cpp/absl/base/attributes.h:37,
                 from /cygdrive/d/a/CppSerialization/CppSerialization/modules/protobuf/third_party/abseil-cpp/absl/base/log_severity.h:21,
                 from /cygdrive/d/a/CppSerialization/CppSerialization/modules/protobuf/third_party/abseil-cpp/absl/base/log_severity.cc:15:
/cygdrive/d/a/CppSerialization/CppSerialization/modules/protobuf/third_party/abseil-cpp/absl/base/policy_checks.h:40:2: error: #error "Cygwin is not supported."
   40 | #error "Cygwin is not supported."
      |  ^~~~~
```

**Comment by chronoxor** [comment]
@mkruskal-google, Mike, I think this change `Update CMake configuration to add a dependency on Abseil (#10401)` makes protobuf unsupported in Cygwin anymore...

**Comment by fowles** [comment]
The dependency on Abseil is a very important change for removing literal decades of tech debt from protobuf.

In the short term, you can say on the 21.x release line which does not have an abseil dep (and won't). In the medium term, you can contribute patches to abseil and protobuf to make them work on your system.

Both protobuf and abseil publish their supported platform criteria at https://opensource.google/documentation/policies/cplusplus-support. If your platform is not officially supported it would fall under "best effort" and would likely require contributions to ensure continued compatibility.

**Comment by chronoxor** [comment]
Got it! Thanks for the information. Currently I'll switch to 21.x and then will look if it is possible to make abseil work in Cygwin.
