### ISSUE TITLE
Ruby: RI documentation can't be parsed for descriptor_pb.rb

### ISSUE THREAD

**Issue by johnnyshields** [protocolbuffers/protobuf#10456]
I get the following non-fatal error when attempting to install `google-protobuf` ruby gem:

```
unable to convert "\xDB" from ASCII-8BIT to UTF-8 for lib/google/protobuf/descriptor_pb.rb, skipping
```

Full output is here:

```
$> gem install google-protobuf
Successfully installed google-protobuf-3.21.5-x64-mingw-ucrt
Parsing documentation for google-protobuf-3.21.5-x64-mingw-ucrt
unable to convert "\xDB" from ASCII-8BIT to UTF-8 for lib/google/protobuf/descriptor_pb.rb, skipping
Done installing documentation for google-protobuf after 0 seconds
1 gem installed
```

**Comment by JasonLunn** [comment]
The message you see is technically correct, but there is no RI doc in that file that is being lost as a result. I can confirm locally that other files that do contain RI doc are being processed.

I'm surprised that RI doc is reading past `__END__` where the binary data. While we could potentially work around this by looking into alternative encoding mechanism is the generated file, it's not a priority at the moment.
