### ISSUE TITLE
"Initialization segment must not change during translation unit" error when unity build is enabled

### ISSUE THREAD

**Issue by MoodieG** [protocolbuffers/protobuf#10459]
**What version of protobuf and what language are you using?**
Version: v3.20.1 (Linking to protobuf-lite but was able to reproduce with protobuf too)
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows 10 Enterprise 19044.1889

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC 19.29

**What did you do?**
1. Unzip the attached file
2. Run the command `cmake . -B out -G "Visual Studio 16 2019" -A x64 -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=2`
3. Navigate to the generated "out" folder.
4. Open up the project in visual studio 16 2019.
5. Compile the project.

**What did you expect to see**

I expected the project to compile successfully.

**What did you see instead?**

I see C2356 error code that says "Initialization segment must not change during translation unit".

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

[ProtobufInitSegTest.zip](https://github.com/protocolbuffers/protobuf/files/9418770/ProtobufInitSegTest.zip)

**Comment by ianeuman** [comment]
Any updates on this?

**Comment by MoodieG** [comment]
I believe this is still an issue, so I am adding a comment to reactivate it.
