### ISSUE TITLE
Question: what is syntax = "editions"?

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#10466]
In a [recent push](https://github.com/protocolbuffers/protobuf/commit/f2358cf60be8b0330ee2933899441df237c7d9ef), the following was updated/added to `FileDescriptorProto` in [`descriptor.proto`](https://github.com/protocolbuffers/protobuf/blob/f2358cf60be8b0330ee2933899441df237c7d9ef/src/google/protobuf/descriptor.proto#L88-L95):
```protobuf
  // The syntax of the proto file.
  // The supported values are "proto2", "proto3", and "editions".
  //
  // If `edition` is present, this value must be "editions".
  optional string syntax = 12;

  // The edition of the proto file, which is an opaque string.
  optional string edition = 13;
```

But there are no references to it anywhere else in the repo and nothing about this in the parser. Was this a preview/leak of some upcoming feature? Or was this meant to be internal to google3 only?

**Comment by mcy** [comment]
Yes, this is an upcoming feature. You can safely ignore it for the time being. We may remove it from the OSS version to minimize confusion, though.

**Comment by jhump** [comment]
@mcy, will it be an external feature, or internal only? If external, any timeline (not asking for commitments, just curious) when this might be communicated to the community?

**Comment by fowles** [comment]
@jhump it is still early, but I can give you a very broad strokes feel for this.  We are working on a design that allows for explicit evolution of generated APIs at a cadence controllable by users.  This is lightly modeled on the concept of "editions" in Rust.  It will be an external feature and we are hoping to have designs we can share with the community in oct/nov.  Ideally, we will start seeing major releases for this early next year.
