### ISSUE TITLE
segmentation fault on `ClearField("oneof_field")`

### ISSUE THREAD

**Issue by nipunn1313** [protocolbuffers/protobuf#10461]
**What version of protobuf and what language are you using?**
Python Protobuf 4.21.5
Corresponds to 21.5

**What operating system (Linux, Windows, ...) and version?**

Mac Monterey 12.3.1 (M1 processor in case it's relevant)

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.8.13

**What did you do?**

Compile this proto to python generated code
```proto
message CrashTest {
  oneof crasher {
    string a = 1;
    string b = 2;
  }
}
```

Then execute:
```
Python 3.8.13 (default, Aug 23 2022, 16:21:08)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import __version__
>>> __version__
'4.21.5'
>>> from testproto.test3_pb2 import CrashTest
>>> CrashTest().ClearField("a")
>>> CrashTest().ClearField("crasher")
[1]    9694 segmentation fault  PYTHONPATH=test/generated venv_3.8.13/bin/python3
```

**What did you expect to see**

According to the docs, this should clear the set field of the oneof.
It definitely should not segfault

**What did you see instead?**

Segfault! Here's a stack trace
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x54)
  * frame #0: 0x000000010159ad80 _message.abi3.so`upb_FieldDef_IsMap
    frame #1: 0x00000001015908c4 _message.abi3.so`PyUpb_Message_DoClearField + 76
    frame #2: 0x0000000101592568 _message.abi3.so`PyUpb_Message_ClearField + 124
    frame #3: 0x0000000100063ba4 python3`cfunction_vectorcall_O + 296
    frame #4: 0x00000001000f6228 python3`call_function + 296
    frame #5: 0x00000001000f35d8 python3`_PyEval_EvalFrameDefault + 23796
    frame #6: 0x00000001000f6f84 python3`_PyEval_EvalCodeWithName + 2500
    frame #7: 0x00000001000ed850 python3`PyEval_EvalCode + 60
    frame #8: 0x0000000100134918 python3`PyRun_InteractiveOneObjectEx + 736
    frame #9: 0x0000000100133e9c python3`PyRun_InteractiveLoopFlags + 156
    frame #10: 0x0000000100133dbc python3`PyRun_AnyFileExFlags + 72
    frame #11: 0x0000000100152d4c python3`Py_RunMain + 2028
    frame #12: 0x000000010015304c python3`pymain_main + 324
    frame #13: 0x00000001001530ec python3`Py_BytesMain + 40
    frame #14: 0x0000000100379088 dyld`start + 516
```

**Comment by nipunn1313** [comment]
I confirmed it reproes on python 3.10.6 as well - so it seems unlikely to be specific to python version.

Also confirmed it regression happens somewhere between 3.20.1 (good) and 4.21.1 (bad) - so it seems likely to be a regression within the native C extension to python.

**Comment by ericsalo** [comment]
I am able to reproduce this failure. Working on a fix now.

**Comment by ericsalo** [comment]
Fixed and pushed.

**Comment by ericsalo** [comment]
I added a unit test for this to the protobuf repo, which is separate from the upb repo since it covers all implementations.

**Comment by nipunn1313** [comment]
oh awesome! Thanks @ericsalo . That's even better.

**Comment by nipunn1313** [comment]
Hi friends.

I was checking the newest release 4.21.6 and this segfault still reproes. The fix landed 6 days before the release.

I'm not familiar with the delay times in your release process - so pardon my ignorance - but I just wanted to check in to make sure the fix is on its way. Is it possible some inter-repository pin (upb?) wasn't pulled forward?

**Comment by ericsalo** [comment]
Hmm. That's strange. I made a specific point of cherrypicking the fix into the 21.x tree, and I have just verified that it is there. But yeah, 4.21.6 was something of a special case so I guess I am not entirely surprised that this one may have somehow fallen through the cracks.
