### ISSUE TITLE
Java proto支持嵌套List的语法吗？

### ISSUE THREAD

**Issue by hakusai22** [protocolbuffers/protobuf#10475]
proto支持嵌套List的语法吗？我现在是对象里面包一个List，对象包对象，有没有直接List<List<String>> 这种结构

**Comment by ericsalo** [comment]
Unfortunately there are very few of us who can read this in its original text, would it be possible to translate into English?

**Comment by shaod2** [comment]
Literally means "Does proto support embedding List? I'm now having a List embedded inside an object and object inside object. But do we have a List<List> structure?"

My reply is that I don't quite understand the question. Can you explain what you're trying to achieve exactly and maybe with some examples?

**Comment by perezd** [comment]
I wonder if this is about the AddAll* methods?
https://developers.google.com/protocol-buffers/docs/reference/java-generated#repeated-fields

**Comment by perezd** [comment]
Also for questions like this we suggest using StackOverflow or our mailing list:
https://groups.google.com/g/protobuf

We prefer to use issues for tracking feature requests and bugs, Thanks!

**Comment by shaod2** [comment]
> I wonder if this is about the AddAll* methods? https://developers.google.com/protocol-buffers/docs/reference/java-generated#repeated-fields

alright, that works for List<Object>, if you want Add with List<List>, you might suggest flattening it at first.
