### ISSUE TITLE
`optional repeated`

### ISSUE THREAD

**Issue by misha-antonenko** [protocolbuffers/protobuf#10489]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3? proto3
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

Suppose you pass around configurations as protobuf messages. You want to be able to parse configurations from JSON using `util::JsonStringToMessage` and override a configuration with another one using `MergeFrom` (so that all fields in the first one which are present in the second one are overwritten). This works fine, as long as all your fields are optional and singular. But then you want to be able to override `repeated` fields; in particular, you want to be able to override a non-empty list of values with an empty one. To date, this is not possible, as the representations of JSONs with `"a": []` for a repeated field `a` are indistinguishable from representations of those where the field is not present.

**Describe the solution you'd like**

Support `optional repeated`

**Describe alternatives you've considered**

Wrap all `repeated` fields in something like
```proto
message MyMessage {}

message MyMessageList {
  repeated MyMessage values = 1;
}
```

**Additional context**

**Comment by fowles** [comment]
Unfortunately this has very very large implication across the entire ecosystem and is not something we would consider doing.

**Comment by misha-antonenko** [comment]
At first sight this seems to admit a non-invasive implementation that would depend on a bit of syntactic sugar and do not require changes to the binary format
