### ISSUE TITLE
proto syntax returns data structure problem (Java)

### ISSUE THREAD

**Issue by hakusai22** [protocolbuffers/protobuf#10485]
The proto syntax now only has a keyword of repeated. I want to use the structure of List<List<String>> to return data, but proto does not support it, so I can only use List<Object>, which has a List<String> nested in it. . I would like to ask if there are two repeated keywords to use?
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/58761705/187575778-803f3369-c764-48d3-8088-e20e7ebbdce4.png">
I am now adding a layer of objects in the middle to solve it, I don't want this layer of intermediate objects

**Comment by ericsalo** [comment]
Your use case looks idiomatic to my eyes, If there is a more succinct way to express this layout I do not know what it is.

**Comment by hakusai22** [comment]
I wonder if there is such a way of writing?-> {repeated repeated  CbtProgramDayPlanDetail}

**Comment by hakusai22** [comment]
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/58761705/187600260-70de01a1-0fda-49f1-9fa9-d296e29458d1.png">

My idea is that you can directly use the step 1 - > 3 instead of using the intermediate object 2 to nest the data structure returned by the list. @ericsalo

**Comment by ericsalo** [comment]
I am relatively certain that your existing structure is as simple as things can be while still retaining the semantics that you need, so I am going to close this thread.
