### ISSUE TITLE
How to write matrix data into .proto file and accessing the file using either cpp or python ?

### ISSUE THREAD

**Issue by amarnathreddy0201** [protocolbuffers/protobuf#10483]
Hi Sir/Mam,
I read this article for write the data into file and read the same file with different programming language.

I tried on python with single value it's working.
"""example.proto"""
```
syntax = "proto2";

package tutorial;

message Yaml_data {
    

    optional string name = 1;
    //optional int32 id = 2;
    optional int32 id = 2;
    optional string email = 3;
    
    // message Foo{
    //     repeated int32 nums=1;
    // }
}

message Yaml_output {
  repeated Yaml_data people = 1;
}
```

I am able to write and Read .

What is the way to write multi dimensationa array using cpp matrix or python numpy.

**Comment by perezd** [comment]
Hello, this isn't a bug or feature but a request for advice, I'd suggest you move this question to StackOverflow or our mailing list: https://groups.google.com/g/protobuf

Thanks!
