### ISSUE TITLE
make  php c extension equal  php package

### ISSUE THREAD

**Issue by DengWang** [protocolbuffers/protobuf#10498]
**What language does this apply to?**
php c extension

**Describe the problem you are trying to solve.**
I want to serialize RepeatedField and MapField to Json string , but I can't get key_type or value_type from obj in c extension, it only defined in php package

**Describe the solution you'd like**
Add RepeatedField::getType And MapField::getKeyType MapField::getValueType in c Extension

**Describe alternatives you've considered**

**Additional context**

**Comment by haberman** [comment]
`RepeatedField` and `MapField` are an internal types, in the `Google\Protobuf\Internal` namespace. The internal types are not for public consumption, and there is no guarantee that the API will be the same between PHP and the C extension.

You can use the public reflection types to get information about field types, including for repeated and map fields. You can see some examples here: https://github.com/protocolbuffers/protobuf/blob/a8c600f9008da0161270d0f2fc10cdc4eb7231bb/php/tests/DescriptorsTest.php#L209-L219
