### ISSUE TITLE
Use a different naming pattern for "major-less" tags

### ISSUE THREAD

**Issue by h-vetinari** [protocolbuffers/protobuf#10497]
Hi!

I help package protobuf for the conda-forge ecosystem, and to be able to integrate over a whole ecosystem, we rely on automated scraping of upstream repos for new tags, and more specifically, tags that follow the pattern specified in the recipe, e.g.
`v{{ version }}` or `packagename-{{ version }}`.

Whenever the bot encounters a new tag of that pattern, it will raise a PR to update the respective packaging repo to the newest available version. This works really well in general, but now that protobuf is [publishing](https://github.com/protocolbuffers/protobuf/tags) both (e.g.) `v3.21.5` & `v21.5` as pointing to the same commit, the bot picks up "21.5" because it is higher.

TBH I've no seen any other project publish `minor.patch` tags, and so working around this would require some protobuf-specific & fragile hacks in our infrastructure.

So I wanted to ask: Would it be possible to use a different naming pattern between the major-full & major-less tags (i.e. not both using `v[\d\.]+`)?

**Comment by h-vetinari** [comment]
Also, it would be interesting to know roughly when a 3.22 is planned, or if the new scheme will be to stay on 3.21 indefinitely.

**Comment by fowles** [comment]
22.x is roughly planned for November, but we don't have high confidence in that estimate.  The good news for you is that 22.x and k.22.y is the same for all our releases so you can safely grab 22.x.

**Comment by h-vetinari** [comment]
> 22.x is roughly planned for November, but we don't have high confidence in that estimate.

Thanks for the info!

> The good news for you is that 22.x and k.22.y is the same for all our releases so you can safely grab 22.x.

I get that they are pointing to the same commit, and this (in conjunction with using the same tagging template) is actually the issue I tried to point out in the OP.

**Comment by fowles** [comment]
Because of other constraints throughout the ecosystem, I don't think change our naming convention is something we want to embark on here.
