### ISSUE TITLE
deprecate for enum value not adding obsolete to generated c# models

### ISSUE THREAD

**Issue by zagforward** [protocolbuffers/protobuf#10513]
**What version of protobuf and what language are you using?**
Version: v3.21.5
Language: C#
OS: Windows 10

**What did you do?**
I have a protobuf schema, which has an enum, some of the enum values are no longer required and I want to deprecate them, I added deprecate = true with the values but it doesn't add the [Obsolete] attribute in the generated c# model
here is the code example

`enum Months{`
`	JANUARY = 0 [deprecated = true];`
`	FEBRUARY = 1 [deprecated = true];`
`	MARCH = 2 [deprecated = true];`
`	APRIL = 3 [deprecated = true];`
`	MAY = 4;`
`	JUNE = 5 [deprecated = true];`
`	JULY = 6 [deprecated = true];`
`	AUGUST = 7;`
`	SEPTEMBER = 8 [deprecated = true];`
`       OCTOBER = 9;`
`       NOVEMBER = 10;`
`       DECEMBER = 11;`
`}`

**Comment by jskeet** [comment]
Thanks, I'll pick this up - I don't expect it to be too hard to implement.

**Comment by zagforward** [comment]
Thank you @jskeet for quickly responding and fixing
