### ISSUE TITLE
Efficient approach to retrive a value in a map using the C++ reflection API

### ISSUE THREAD

**Issue by ketgo** [protocolbuffers/protobuf#10517]
**What language does this apply to?**
I am primarily interested in C++ API but the feature can be extended to other languages. 

**Describe the problem you are trying to solve.**

The map field in a protobuf message is stored as a repeated field with each field value containing the key and value. Using the reflection API once can access the map field as if its a repeated field. However this results in in-efficient lookup of value for a key of interest. Currently one needs to go through all the entries to find the desired value. 

**Describe the solution you'd like**

Provide an interface in the reflection API to efficiently retrieve a key-value pair for a map field. It should internally use the hash value of the key to get the desired key-value pair.

**Describe alternatives you've considered**

The only way currently I can lookup a value is through iterating over all the map entries.

**Comment by deannagarcia** [comment]
The protobuf team has looked into creating an interface for this, but we haven't settled on a final design and it is not a high priority for us. So unfortunately you're going to just have to use the workaround.
