### ISSUE TITLE
######why are negative numbers of type int32 encoded using 64-bit varints? Instead of using 32-bit varint encoding

### ISSUE THREAD

**Issue by luoluoyuyu** [protocolbuffers/protobuf#10521]
Why are negative numbers of type int32 encoded using 64-bit varints? Instead of using 32-bit varint encoding

**Comment by deannagarcia** [comment]
Can you add a bit more detail here? What language/architecture are you using? Can you provide an example/something reproducible so we can run it?

**Comment by boscosiu** [comment]
> Why are negative numbers of type int32 encoded using 64-bit varints? Instead of using 32-bit varint encoding

The designers wanted the 32-bit varints to be forward compatible with their 64-bit counterparts.

From https://developers.google.com/protocol-buffers/docs/proto3#updating

> int32, uint32, int64, uint64, and bool are all compatible – this means you can change a field from one of these types to another without breaking forwards- or backwards-compatibility. If a number is parsed from the wire which doesn't fit in the corresponding type, you will get the same effect as if you had cast the number to that type in C++ (for example, if a 64-bit number is read as an int32, it will be truncated to 32 bits).

and

> sint32 and sint64 are compatible with each other but are not compatible with the other integer types.

**Comment by luoluoyuyu** [comment]
thank
