### ISSUE TITLE
Enum value reservation not in language spec

### ISSUE THREAD

**Issue by Feyko** [protocolbuffers/protobuf#10524]
I am sorry that I did not fill an issue template but I believe none were relevant to this issue

I was reading the proto3 language specification from [here](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec)
When I got to the Enum definition, I was surprised to see that `enumBody` does not allow for `reserved` to be used. The [Language Guide](https://developers.google.com/protocol-buffers/docs/proto3) says that this is a supported feature and indeed I was able to properly use protoc on a protobuf file that has an enum with reserved fields

Was enum reservation forgotten to be included in the language spec? Is the spec I'm reading somehow outdated? Or am I simply missing something obvious? :smile:

**Comment by deannagarcia** [comment]
I can't seem to find the part of the language specification that says it's not supported, can you link me to the specific section?

Enum value reservation should be available, I can fix any documentation that's incorrect.

**Comment by Feyko** [comment]
Bad wording on my part 😄 The spec doesn't say it's unsupported but it doesn't say that it is
It should be in [here](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#enum_definition) but there's no mention of it

**Comment by Feyko** [comment]
Bump, was this addressed?

**Comment by deannagarcia** [comment]
Just fixed it [here](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#enum_definition) and in the proto2 language spec as well.
