### ISSUE TITLE
php/generate_descriptor_protos.sh (via generate_descriptor_protos.sh) fails on macOS

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#10567]
php/generate_descriptor_protos.sh seems to expect a local command (or shell primitive) of `realpath`, but that doesn't exist on atleast macOS.

```
$ ./generate_descriptor_protos.sh
...
Generating messages for PHP.
php/generate_descriptor_protos.sh: line 8: realpath: command not found
```

**Comment by haberman** [comment]
Looks like this was introduced in https://github.com/protocolbuffers/protobuf/commit/4c5454b86db0aa9e97d06e39d969edf5d9ac7c1f
