### ISSUE TITLE
Java/Maven releases for 3.21.6 / 3.20.2 / 3.19.5 are missing 

### ISSUE THREAD

**Issue by edwardxia** [protocolbuffers/protobuf#10568]
**What version of protobuf and what language are you using?**
Version: 3.21.6 / 3.20.2 / 3.19.5
Language: Java

**What operating system (Linux, Windows, ...) and version?**
All.

**What did you do?**
Search maven central.

**What did you expect to see**
See releases for 3.21.6 / 3.20.2 / 3.19.5.

**What did you see instead?**
Java/Maven releases for 3.21.6 / 3.20.2 / 3.19.5 are missing.

**Comment by edwardxia** [comment]
My understanding is that whenever a release is cut, all supported languages should receive a release even if they don't have changes. E.g. I can see ruby & python are published without any changes.

**Comment by deannagarcia** [comment]
Yep we will release an artifact for all languages. The maven releases should be out soon and we have already done our part to release them but it takes a while for them to sync to maven. Let me know if you still can't find it after waiting.
