### ISSUE TITLE
What's in 3.19.5?

### ISSUE THREAD

**Issue by nhc-motosumo** [protocolbuffers/protobuf#10562]
Yesterday, `pypi` had a new version `3.19.5` available, which was picked up by one of my builds (indicrectly, through another dependency). It caused the build to break, so I was looking to see Release Notes for 3.19.5, but I cannot find them in this project.

Can you please guide me to the right place? :-)

**Comment by horseBatteryStapler** [comment]
Same for me - multiple packages, `3.20.2` also has the same issue:

```
    import google.protobuf.pyext._message as _grpc_message_lib
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```

**Comment by akursar** [comment]
Similarly seeing performance issues with python 3.20.2. The default impl seems to have changed from cpp to python.

```
> docker run --rm  python:3.10 /bin/bash -c 'pip install -q protobuf==3.20.1; python -c "from google.protobuf.internal import api_implementation; print(api_implementation.Type())"'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
cpp

> docker run --rm  python:3.10 /bin/bash -c 'pip install -q protobuf==3.20.2; python -c "from google.protobuf.internal import api_implementation; print(api_implementation.Type())"'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
python
```

**Comment by deannagarcia** [comment]
I'm sorry about this issue, I'm looking into the problem now. What operating system/architecture are you using?

**Comment by deannagarcia** [comment]
I believe the issue here was that we had not released all the artifacts. I uploaded the missing artifacts, and am closing the issue but definitely reopen the issue if you still see this error.
