### ISSUE TITLE
Release 3.19.5 on pypi but not listed on GitHub

### ISSUE THREAD

**Issue by nhc-motosumo** [protocolbuffers/protobuf#10584]
GitHub does not allow me to reopen https://github.com/protocolbuffers/protobuf/issues/10562, which was closed without resolving my problem, so I will try to elaborate in this new issue.

Two days ago, on Sep 15 2022, a new new `protobuf` release, version `3.19.5`, appeared on `pypi`, see https://pypi.org/project/protobuf/#history and search for `3.19.5`. That versions caused some problems for our builds, so I was looking to investigate what changed from `3.19.4` to `3.19.5`.

However, when I search this project's releases, `3.19.5` does not appear, see https://github.com/protocolbuffers/protobuf/releases?q=3.19.5&expanded=true

So now I have the following questions:

- Is `3.19.5` a release at all or could it be malicious code uploaded in this project's name?
- If `3.19.5` is a release you made, what are the changes from `3.19.4`? More precisely, where do I find the information? I normally look the project's release list.

**Comment by deannagarcia** [comment]
I'm sorry the issue wasn't reopenable.

The GitHub release page is [right here](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.5) it just took us a bit of extra time to get the full release out. Was the update in the pypi release able to solve your error?

**Comment by horseBatteryStapler** [comment]
Hello @deannagarcia - can I check if other wheels were also re-released with the missing artifact? We had some builds break even with protobuf==3.19.4.

- Python 3.6 (Faced this problem with both 3.6.3 and 3.6.8)
- protobuf==3.19.4 (resolving to protobuf-3.19.4-py2.py3-none-any.whl)
- pip 9.0.1

To replicate, from a completely clean set up:
`python3.6 -m venv venv && . venv/bin/activate && venv/bin/pip install --upgrade pip==9.0.3 && venv/bin/python3.6 -m pip install protobuf==3.19.4 && venv/bin/python3.6 -c "import google.protobuf.pyext._message"`

If we use a later pip version like pip==21.0.1, it works fine **(make sure to remove the previous step's venv/ before running this)**
`python3.6 -m venv venv && . venv/bin/activate && venv/bin/pip install --upgrade pip==21.0.1 && venv/bin/python3.6 -m pip install protobuf==3.19.4 && venv/bin/python3.6 -c "import google.protobuf.pyext._message"`

**Comment by deannagarcia** [comment]
There should not have been any changes to 3.19.4. I think this is a separate issue, can you file a separate bug?

**Comment by nhc-motosumo** [comment]
> I'm sorry the issue wasn't reopenable.

It seems GitHub only allows collaborators to re-open their own issues. So I was the only person on GitHub unable to re-open it :slightly_smiling_face: 

> The GitHub release page is [right here](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.5) it just took us a bit of extra time to get the full release out. Was the update in the pypi release able to solve your error?

Thanks. My build works with 3.19.5. now :+1:
