### ISSUE TITLE
Wrong link of WORKSPACE in README document

### ISSUE THREAD

**Issue by rockingdice** [protocolbuffers/protobuf#10617]
The link from the [README](https://github.com/protocolbuffers/protobuf/blob/main/src/README.md) is 404:

https://github.com/protocolbuffers/protobuf/blob/main/src/examples/WORKSPACE

**Comment by p-alik** [comment]
should be replaced by https://github.com/protocolbuffers/protobuf/blob/main/examples/WORKSPACE
