### ISSUE TITLE
protobuf-java 2.7

### ISSUE THREAD

**Issue by ale5000-git** [protocolbuffers/protobuf#10631]
Hi,
could you please publish protobuf-java 2.7 on maven?

**Comment by shaod2** [comment]
I don't think we have any plan for old 2.x release. Can you give a bit more information why it is needed other than all other newer protobuf-java releases? https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

**Comment by ale5000-git** [comment]
This library can cast to Chromecast devices: https://github.com/vitalidze/chromecast-java-api-v2
And the library is currently using protobuf-java 2.6.0; I think that using version 3 may break compatibility with Chromecast devices.

**Comment by perezd** [comment]
Sorry, we don't plan to support the 2.x line. I suggest forking that repo and sending them a PR to upgrade to the latest. FWIW, I don't think Java has changed all that much so that shouldn't be difficult.
