### ISSUE TITLE
string variables in a gRPC response are always overwritten to the last one that is been set in a C++ server on MacOS

### ISSUE THREAD

**Issue by littlegrasscao** [protocolbuffers/protobuf#10638]
Given a protobuf example as below:
```
syntax = "proto3";
rpc TestCall(xxx)returns(Test){}

message Foo{
string a = 1;
}
message Test {
string x = 1;
string y = 2;
string z = 3;
map<string, string> map = 4;
Foo f = 5;
}

Status Interface::TestCall(ServerContext* context,const xxx* request,Test* response)
{
response->set_x("x");
response->set_y("y");
response->set_z("z");
// Leave foo.a and map blank

cout << response->x() << endl; //"z"
cout << response->y() << endl; //"z"
cout << response->z() << endl; //"z"
return Status::OK;
}
```

On a Mac machine, if I build up a C++ gRPC server and fill in the response, all the string variables x/y/z/a are overwritten to the last string I set("z" in this example). This issue only happens on Mac, not Windows or Linux. Also, this issue only applies to string, not int/bool/map/list.

Has anyone seen this issue before? Is there a workaround for this issue?

**Comment by fowles** [comment]
What version of protobuf and grpc are you using?

**Comment by littlegrasscao** [comment]
> What version of protobuf and grpc are you using?

I am using grpc: '1.32.1' and protobuf: '3.12.0'.
I have tried to use protobuf: '3.19.0' and still saw the same issue.

**Comment by fowles** [comment]
It looks like you already have a fairly minimal repro.  Would you mind putting that in a git repo or tar file somewhere so we can be sure to reproduce your setup correctly?

**Comment by littlegrasscao** [comment]
> It looks like you already have a fairly minimal repro. Would you mind putting that in a git repo or tar file somewhere so we can be sure to reproduce your setup correctly?

The code I give in the example is pseudo code that mimics what my company's server does. I didn't actually build that code.

**Comment by fowles** [comment]
The code that you have posted would be such a massive bug that I cannot imagine it being unknown to us.  On the other hand, I can imagine a variety of undefined behavior things that could lead to something similar.

Have you tried minimizing the example further?  
Have you tried running in asan and msan?

**Comment by littlegrasscao** [comment]
> The code that you have posted would be such a massive bug that I cannot imagine it being unknown to us. On the other hand, I can imagine a variety of undefined behavior things that could lead to something similar.
> 
> Have you tried minimizing the example further? Have you tried running in asan and msan?

I agree that this issue would impact many developers if it truly exists. I guess not many people develop a C++ gRPC server on a Mac? 

I have tried various ways to set the string variable in a response. All of them produce the same issue on Mac. 

I have seen this issue once before when a response contains both bytes and string. I solved the issue by using oneof because we only need either bytes or string in that response. But in this case, we need all 3 strings to be returned. I don't have a workaround so far.

Also, I can identify the same issue even on Windows if I set the string variables of a response in a C++ forward declaration. 

No, I haven't tried asan or msan.

**Comment by fowles** [comment]
Do you mind producing a minimal reproduction?

**Comment by littlegrasscao** [comment]
> Do you mind producing a minimal reproduction?

Yeah, I can definitely try to reproduce this in a separate project. It would take some time though as I don't have much experience to build a grpc server on Mac. This is bad because I usually rely on the company's infrastructure :(

**Comment by littlegrasscao** [comment]
I found out it is the same root cause as this one: https://github.com/protocolbuffers/protobuf/issues/6031#issue-432692758

We should only define protobuf in a single module.
