### ISSUE TITLE
std::vector::insert equivalent missing at repeated fields [C++]

### ISSUE THREAD

**Issue by yoavmil** [protocolbuffers/protobuf#10633]
C++
proto3

Problem:
I want to add an element in the middle of a repeated field container, no way to do it but creating a new container then overwriting original one.

Solution:
a way to insret in the mid of container `std::vector::insert`

Cheers!

**Comment by mkruskal-google** [comment]
STL provides this indirectly via `std::rotate`.  Basically, you can append the new element and then rotate it into the new location.  For example:
```
void insert(RepeatedPtrField<Type>* field, const Type& element, int index) {
  field->Add(element);
  std::rotate(field->pointer_begin()+index, field->pointer_begin() + field->size() - 1, field->pointer_end());
}
```
