### ISSUE TITLE
PHP: Use type hints for method setters instead of GPBUtil

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#10632]
**Enhancement**

The generated messages use the `GPBUtil` class to check types. This is fine in some cases, such as with `RepeatedField` or `Map` types, where the setter needs to verify the keys and/or the values of an `iterable` type. However, for other setters which only accept a class, it would be better to let PHP type hinting do the magic:

For primitive types ([Timestamp.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Timestamp.php#L145)):
```php
public function getSeconds(): int
{
      return $this->seconds;
}

public function setSeconds(int $seconds)
{
    $this->seconds = $seconds;

    return $this;
}
```

For message classes ([Api.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Api.php#L299))
```php
public function getSourceContext(): \Google\Protobuf\SourceContext
{
    return $this->source_context;
}

public function setSourceContext(\Google\Protobuf\SourceContext $sourceContext)
{
    $this->source_context = $sourceContext;

    return $this;
}
```

For map fields and repeated fields, we can still typehint better than we are currently doing by using the `iterable` typehint ([Struct.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Struct.php#L64)):
```php
public function getFields(): iterable
{
    return $this->fields;
}

public function setFields(iterable $fields)
{
    $arr = GPBUtil::checkMapField($fields, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
    $this->fields = $arr;

    return $this;
}
```

**Comment by hkargv** [comment]
> **Enhancement**
> 
> The generated messages use the `GPBUtil` class to check types. This is fine in some cases, such as with `RepeatedField` or `Map` types, where the setter needs to verify the keys and/or the values of an `iterable` type. However, for other setters which only accept a class, it would be better to let PHP type hinting do the magic:
> 
> For primitive types ([Timestamp.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Timestamp.php#L145)):
> 
> ```
> public function getSeconds(): int
> {
>       return $this->seconds;
> }
> 
> public function setSeconds(int $seconds)
> {
>     $this->seconds = $seconds;
> 
>     return $this;
> }
> ```
> 
> For message classes ([Api.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Api.php#L299))
> 
> ```
> public function getSourceContext(): \Google\Protobuf\SourceContext
> {
>     return $this->source_context;
> }
> 
> public function setSourceContext(\Google\Protobuf\SourceContext $sourceContext)
> {
>     $this->source_context = $sourceContext;
> 
>     return $this;
> }
> ```
> 
> For map fields and repeated fields, we can still typehint better than we are currently doing by using the `iterable` typehint ([Struct.php](https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Struct.php#L64)):
> 
> ```
> public function getFields(): iterable
> {
>     return $this->fields;
> }
> 
> public function setFields(iterable $fields)
> {
>     $arr = GPBUtil::checkMapField($fields, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
>     $this->fields = $arr;
> 
>     return $this;
> }
> ```

**Comment by haberman** [comment]
Sorry for the slow reply. Does PHP provide a guarantee? What happens if you call `setSeconds("123")` in your example?

**Comment by bshaffer** [comment]
By default, PHP would cast the string `"123"` into the int `123`. If the file in which the method is called implements `declare(strict_types=true)`, then a `TypeError` is thrown, same as if `setSeconds("abc")` is called.

**Comment by bshaffer** [comment]
This is still a valid (and important) change that should be made.
