### ISSUE TITLE
The Old Version of abseil used by libprotobuf Caused Complie Error C4996 by CMake with MSVC 19.33.31630.0 on Windows

### ISSUE THREAD

**Issue by FangCunWuChang** [protocolbuffers/protobuf#10659]
**What version of protobuf and what language are you using?**  
Version: main  
Language: C++20   

**What operating system (Linux, Windows, ...) and version?**  
Windows 10.0.22000.1042  

**What runtime / compiler are you using (e.g., python version or gcc version)**  
MSVC  19.33.31630.0  

**What did you do?**  
```
#CMakeLists.txt
set (PROTOBUF_DIR ${CMAKE_CURRENT_SOURCE_DIR}/protobuf) 
set (protobuf_BUILD_SHARED_LIBS ON)
add_subdirectory (${PROTOBUF_DIR})
#...
include_directories (${PROTOBUF_DIR}/src)
#...
target_link_libraries (
	${TARGET_NAME}
	protobuf::libprotobuf
)
#...
```

**What did you expect to see**  
I wanna link the libprotobuf shared library in my target.

**What did you see instead?**  
My target is also a shared library, when I link this target into another target, I got the Error C4996:  
*D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\ciso646(15): error C4996: '_Header_ciso646': warning STL4036: <ciso646> is removed in C++20. You can define _SILENCE_CXX20_CISO646_REMOVED_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.*  
The relationship of the targets is like this:  
libprotobuf<---my target<---another target  

**Anything else we should know about your project / environment**  
I found this error was caused by the old version of abseil, look at this:  
https://github.com/abseil/abseil-cpp/issues/1251  
And it was fixed by commit [3e54e87](https://github.com/abseil/abseil-cpp/commit/3e54e87f020c71440217ce2ad382b800c4658970) on 11 Aug.  So I wonder if the version of abseil used by libprotobuf could be updated.

**Comment by FangCunWuChang** [comment]
Now I have to `add_compile_definitions (_SILENCE_CXX20_CISO646_REMOVED_WARNING=1)` in all of my CMakeLists.txt to avoid the problem.

**Comment by googleberg** [comment]
Hi FangCunWuChang, protobuf does not yet officially support C++20. We hope to soon, but we do not have a firm release targeted for that support.
