### ISSUE TITLE
How to get leading comments and tailing comments in python api?

### ISSUE THREAD

**Issue by wngus606** [protocolbuffers/protobuf#10655]
- proto3
- python

`protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/addressbook.proto`

If the protoc command is executed according to the protobuf guide, the `addressbook_pb2.py` file is created. I want to get comment information from the file, but there is no method to get `SourceCodeInfo` in python api. Is there a way?

**Comment by googleberg** [comment]
I believe you need the --include_source_info flag.
