### ISSUE TITLE
Allow Value to support an int64 value

### ISSUE THREAD

**Issue by trajano** [protocolbuffers/protobuf#10669]
**What language does this apply to?**
proto3
Java

**Describe the problem you are trying to solve.**
Loss of precision due to conversion of any numeric data to `double`

**Describe the solution you'd like**

```protobuf
message Value {
  oneof kind {
    ...
    double number_value = 2;
    ...
    // add this
    int64 integral_value = 7;
  }
}
```

At https://github.com/protocolbuffers/protobuf/blob/main/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1604

```
} else if (parserAllowsIntegralValue && primitive.isNumber() && canBeIntregral(primitive)) {
  builder.setField(type.findFieldByName("integral_value"), primitive.getAsBigInteger()));
}
```
Then this method can be added
```
boolean canBeIntregral(JsonPrimitive primitive) {
  // this is likely inefficient but should work
  // https://stackoverflow.com/questions/1078953/check-if-bigdecimal-is-an-integer-in-java shows how to check
  // but getAsBigDecimal().stripTrailingZeros().scale() <= 0; will prevent `0.0` from being represented as a decimal so do not
  // strip the trailing zeros so if the input data is `0.0` or `0.0E100` then allow it to be converted but make sure `0` `1` etc uses integral
  return getAsBigDecimal().scale() == 0;
}
```
It should also be configurable to ensure backwards compatibility so there needs to be something that sets `parserAllowsIntegralValue` like
```
JsonFormat.parser().allowsIntegralValue()
```

**Describe alternatives you've considered**
* [allow override for one field in Struct](https://stackoverflow.com/questions/73878752/how-do-i-override-the-type-of-one-of-the-struct-fields-but-keep-the-unknown-valu?noredirect=1#comment130450503_73878752)

**Additional context**

**Comment by googleberg** [comment]
I believe this type was developed for JSON that allows interop with JavaScript and as such limits the numeric type to the IEEE 754 double.

This seems in line with https://www.rfc-editor.org/rfc/rfc7159

We're unlikely to update this type with int64 support since that would break interoperability.

As a workaround, you could use a string to carry larger integers and convert them in the application layer.
