### ISSUE TITLE
[3.19.4]Protobuf Build Errors On Android

### ISSUE THREAD

**Issue by naahmedea** [protocolbuffers/protobuf#10661]
Protobuf version - `3.19.4`

When i am trying to build protobuf for android, Getting the below error can some one please help??

Error:
`protobuf\3.19.4\protobuf-3.19.4\src\google/protobuf/stubs/port.h(366,45): error : use of undeclared identifier '__swap64'`

**Comment by googleberg** [comment]
@naahmedea Can you provide a little more information so we can try to reproduce the problem? What OS are you developing on? What commandline did you run?
