### ISSUE TITLE
I cannot build an example because of bazel

### ISSUE THREAD

**Issue by danghai** [protocolbuffers/protobuf#10663]
I try to build example. Unfortunately, I got this error. I am not sure how I can fix it. Does anyone take the chance to look at it? Thank you
![image](https://user-images.githubusercontent.com/10912671/192620231-dfdbfedb-25ed-460e-9d3a-fa56e90997bf.png)

**Comment by perezd** [comment]
What specifically are you trying to build? `:all` is a bit aggressive and may not work as you want (you'll need multi-language dependencies to be setup)

**Comment by danghai** [comment]
Ah I see. How can I build for `C++`?

**Comment by perezd** [comment]
Note, typically bazel projects rely on proto_library and lang rules vs invoking the compiler directly.
https://github.com/bazelbuild/rules_proto

You'd use proto_library and cc_proto_library rules respectively vs directly building artifacts.

https://bazel.build/reference/be/c-cpp#cc_proto_library
https://bazel.build/reference/be/protocol-buffer#proto_library

**Comment by danghai** [comment]
Thank you. It works for me now.  I installed: `bazel build :protoc :protobuf`
For testing `example`: 
```
bazel build addressbook_proto
bazel build addressbook_cc_proto
```
It creates for me `bazel-bin, bazel-example, and bazel-out`

I try to use `make cpp` to build example code. It does not work
![image](https://user-images.githubusercontent.com/10912671/192628733-99c0126d-0050-44ee-a959-e8aca0a87568.png)

However, It works when I build by `bazel`
```
bazel build add_person_cpp
bazel build list_people_cpp
```

Thank you for helping
