### ISSUE TITLE
Add a method in Python SDK: Compile one/more .proto file(s) into a group of google.protobuf.Message python classes

### ISSUE THREAD

**Issue by ruodingt** [protocolbuffers/protobuf#10699]
**What language does this apply to?**
python sdk

**Describe the problem you are trying to solve.**
Thanks for your time reviewing my issue:)

I am new to protobuf and my solution or problem may not necessary the make sense to you. Feedbacks are welcome if you see a better alternative solution.

In an application we are expecting to build a proto schema registry storing groups of `.proto` file to be adaptive to changing business . 

And we hope from time to time a data pipeline can fetch latest schema from the proto schema registry and compile the schema into and python `google.protobuf.Message` class to validate the message schema.

Without a method in python SDK to directly bridge `.proto` files to  a group of `google.protobuf.Message` classes the solution will be a bit ugly:

.proto files -> compile to FileDescriptorSet and upload to schema registry (use `protoc` cli) -> data pipline pull the FileDescriptorSet binary files and convert it into `google.protobuf.Message`

**Describe the solution you'd like**

Add a method in Python SDK: Compile one/more .proto file(s) into a group Python `google.protobuf.Message` classes

**Describe alternatives you've considered**

For python user, I only see one way to convert `.proto` files into `google.protobuf.Message`:

.proto files -> compile to FileDescriptorSet and upload to schema registry (use `protoc` cli) -> data pipline pull the FileDescriptorSet binary files and convert it into `google.protobuf.Message` classes in python

It would be great to have a short cut method in python SDK to support direct schema loading: `.proto` files -> `google.protobuf.Message` clases in python

**Additional context**

Appreciate your time to review my issue. 
If you see a better alternative to achieve the goal it would be great to have your professional opinion.

**Comment by googleberg** [comment]
It sounds like you are asking for a version of protoc implemented in python. We are unlikely to implement that. 

Your alternative solution using the protoc cli sounds workable, but I'm not familiar with all of your constraints.
