### ISSUE TITLE
3.21.7 Java Compile Error on parseUnknownField

### ISSUE THREAD

**Issue by Scottmitch** [protocolbuffers/protobuf#10695]
**What version of protobuf and what language are you using?**
Version: 3.21.7
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS 12.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
openjdk 17.0.3 2022-04-19 LTS

**What did you do?**
```proto
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.servicetalk.performance.test";
option java_outer_classname = "TestProto";

package test;

message TestPayload {
    bytes body = 1;
    int32 expectedSize = 2;
}
```

**What did you expect to see**
No compile error

**What did you see instead?**
```shell
.../TestPayload.java:391: error: cannot find symbol
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                        ^
  symbol: method parseUnknownField(CodedInputStream,ExtensionRegistryLite,int)
```

```java
    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              body_ = input.readBytes();

              break;
            } // case 10
            case 16: {
              expectedSize_ = input.readInt32();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
```

**Comment by cb-tong-zhou** [comment]
I got the same thing as well! can someone take a look of it please?

**Comment by tbjorch-m** [comment]
Have also occurred for me

**Comment by AldiNFitrah** [comment]
I got this issue, too

**Comment by googleberg** [comment]
If you are receiving this message, you are using new codegen with old runtime code. The recent security fix uses new methods in GeneratedMessageV3.Builder.
https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java (line 823)

Old generated code will work with the new runtime (but will not be security-fixed)
New generated code will not work with pre-patched runtimes.

**Comment by duktig666** [comment]
I also!

**Comment by googleberg** [comment]
This should be solved by updating the runtime in use to match freshly generated code.

**Comment by googleberg** [comment]
@anandkanav92 can you post your pom file or a link to it or at least the protobuf snippet?

**Comment by anandkanav92** [comment]
@googleberg Please find below the snippet of pom. Unfortunately I cannot share the whole thing 😿 
version:
```xml
<protobuf.version>3.21.7</protobuf.version>
```
dependency:
```xml
<configuration>
  <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
  <pluginId>grpc-java</pluginId>
  <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
</configuration>
```
```xml
<dependency>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protobuf-java</artifactId>
</dependency>
```

Let me know if this helps in any way or if you need any more information.

**Comment by googleberg** [comment]
@anandkanav92 Does it help to update the dependency stanza to this (with the explicit version):
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>3.21.7</version>
</dependency>

**Comment by ChisatoNishikigi73** [comment]
> 

thx a lot, it's work

**Comment by kodlan** [comment]
I'm also having the same issue. I've tried using 3.21.9 and 3.21.7 as protobuf.version:
```
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.2</version>
      </extension>
    </extensions>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.6.1</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.21.9:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.51.0:exe:${os.detected.classifier}</pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>19</source>
          <target>19</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Any ideas what else can I try?

**Comment by ravenblackx** [comment]
> If you are receiving this message, you are using new codegen with old runtime code. The recent security fix uses new methods in GeneratedMessageV3.Builder. https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java (line 823)

I have a similar error message, but I think either the opposite is true here, or `v21.12` has a problem.
In the 21.x branch, [parseUnknownField takes 4 parameters](https://github.com/protocolbuffers/protobuf/blob/21.x/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java#L334-L341).
But my generated code (which *may not* be generated using v21.12's protoc, the build system I'm working with makes it hard to tell) still contains calls with 3 parameters
```
             if (!super.parseUnknownField(input, extensionRegistry, tag)) {
```

Which suggests
> Old generated code will work with the new runtime (but will not be security-fixed)

may not be true.

Also, I just checked, manually running `@com_google_protobuf//:protoc` with `--java_out`, it outputs files with calls to parseUnknownField with 3 parameters. So it seems like `v21.12` is broken for java.

**Comment by SpringDay6** [comment]
i solved this .I use protobuf-java-util，this depends on protobuf-java 。so I do this as picture.
![1674107951457](https://user-images.githubusercontent.com/44592974/213367015-79c902f0-b8cf-4387-87d7-f7a4ba44889f.png)

**Comment by nalbion** [comment]
I'm having the same problem, using the versions from here: https://github.com/grpc/grpc-kotlin/blob/master/build.gradle.kts

```
val grpcVersion = "1.46.0"
val protobufVersion = "3.21.7"
val grpcKotlinVersion = "1.3.0"

plugins {
  id("com.google.protobuf") version "0.9.3"
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:${protobufVersion}"
  }
  plugins {
    create("grpc") {
      artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
    }
    create("grpckt") {
      artifact = "io.grpc:protoc-gen-grpc-kotlin:${grpcKotlinVersion}:jdk8@jar"
    }
  }
  generateProtoTasks {
    all().forEach {
      it.plugins {
        create("grpc")
        create("grpckt")
      }
      it.builtins {
        create("kotlin")
      }
    }
  }
}

dependencies {
  implementation(group="io.grpc", name="grpc-kotlin-stub", version=grpcKotlinVersion)
  implementation(group="io.grpc", name="grpc-stub", version=grpcVersion)
  implementation(group="io.grpc", name="grpc-protobuf", version=grpcVersion)
  implementation(group="com.google.protobuf", name="protobuf-java-util", version=protobufVersion)
  implementation(group="com.google.protobuf", name="protobuf-kotlin", version=protobufVersion)
}

**Comment by nalbion** [comment]
I've also tried

val grpcVersion = "1.55.1"
val protobufVersion = "3.22.3"
val grpcKotlinVersion = "1.3.0"

and the latest versions:

val grpcVersion = "1.55.1"
val protobufVersion = "3.23.0"
val grpcKotlinVersion = "1.3.0"

**Comment by nalbion** [comment]
Actually, it seems that IntelliJ is resolving com.google.protobuf 3.19.4 

This is one of the generated lines that I'm having trouble with:


if (!super.parseUnknownField(input, extensionRegistry, tag)) {

**Comment by pranjal5215** [comment]
Specifically Adding version [3.21.7] for protobuf-java worked

```
<dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.21.7</version>
        </dependency>
```

**Comment by justinzhuguangwen** [comment]
To resolve the "Java Compile Error on parseUnknownField", please follow the steps below:

1. Ensure that the version of the runtime libraries in your `.gradle` file is consistent with the version of `protoc.exe`. For example, you could have something like this in your `.gradle` file:

```groovy
compile group: 'com.google.protobuf', name: 'protobuf-java', version: '3.21.7'
```

2. Delete any other version directories in your Gradle file cache. These directories can be found in the following path: `C:\\Gradle\\gradle-4.8\\caches\\modules-2\\files-2.1\\com.google.protobuf\\protobuf-java`.

By following these steps, you should be able to resolve the compile error.
