### ISSUE TITLE
Inconsistent versioning (3.21.7 vs 21.7)

### ISSUE THREAD

**Issue by AMDmi3** [protocolbuffers/protobuf#10704]
Latest version seem to have dropped major component (e.g. 21.7 instead of 3.21.7) https://github.com/protocolbuffers/protobuf/releases/tag/v21.7, however some files protobuf-cpp etc. still use old version (3.21.7). Please keep versioning consistent (by sticking with the one and only scheme everywhere - tag and release names, download file names, changelog, build system), otherwise it introduces mess and makes downstream package maintainership harder.

**Comment by zhangskz** [comment]
This is actually WAI. In release 21.0, we switched to per-language major versions. Thus, the release is now "v21.7" with "3.21.7" or "4.21.7" referring to the major versions used for each specific language. For example, cpp is on 3.21.7 but python is on 4.21.7.

Note, we still have add tags for each language's major versions (v21.7, v3.21.7, v4.21.7) for now.

See https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning

**Comment by AMDmi3** [comment]
Is it really a good idea to spawn a bunch of different versions from a single codebase? It complicates packaging (for instance, when all language counterparts are created from a single source package, versioned after "main" version, they'll have "main" version too), automaked new release notifications and checking against vulnerability databases.

**Comment by h-vetinari** [comment]
> Is it really a good idea to spawn a bunch of different versions from a single codebase?

Not with the exact same tag-pattern, but unfortunately, it was [rejected](https://github.com/protocolbuffers/protobuf/issues/10497) to change this.

> It complicates packaging (for instance, when all language counterparts are created from a single source package, versioned after "main" version, they'll have "main" version too), automaked new release notifications and checking against vulnerability databases.

Agreed on all counts.

**Comment by teub** [comment]
meirl, looking at tags and version numbers : "I really don't get it"

_checks closed issues_

Sure enough, I'm not the only one. Small relief
