### ISSUE TITLE
Missing instructions for building Python wheel with upb

### ISSUE THREAD

**Issue by ajasmin** [protocolbuffers/protobuf#10719]
**What version of protobuf and what language are you using?**
Version: 21.7
Language: Python
OS: Linux

**What did you do?**
I'm trying to build a wheel of protobuf 21.7 with support for PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb
This is the same as the pre-compiled wheels available on PyPI.

The existing documentation only shows how to build with the legacy c++ implementation:
https://github.com/protocolbuffers/protobuf/blob/main/python/README.md

I can produce the upb module with `bazel build @upb//python:_message` but `python/setup.py` doesn't seem to have a way to install or package it with the Python code.

**Comment by ajasmin** [comment]
> ```
> $ bazel build -c opt @upb//python/dist:binary_wheel
> ```

That works, Thank You! I must confess I have minimal knowledge of bazel.

It may be instructive to have the deployment files on github (Docker and all) if it's not already there.

**Comment by perezd** [comment]
Our docker files are not currently open sourceable in their current form, sadly. They contain some proprietary libraries we cannot release, yet.

**Comment by ajasmin** [comment]
It's still not clear to me that python/README covers building the upb version with bazel

The command above can be documented without having to share any proprietary code.
