### ISSUE TITLE
Version 3.20.3 doesn't have release assets for osx-aarch_64

### ISSUE THREAD

**Issue by iampava** [protocolbuffers/protobuf#10748]
Looking at version [3.20.2](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.2) I can see it has assets for `osx-aarch_64`.

However, version [3.20.3](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.3) is missing those.

**Comment by mkruskal-google** [comment]
@deannagarcia Was this intentional or do we have an issue in our release process?  I'm looking through all our recent releases and I'm not seeing much pattern to whether or not this asset is included

**Comment by britter** [comment]
@iampava the latest release 3.21.7 does have the ARM binaries. Maybe you can upgrade to that one?

**Comment by deannagarcia** [comment]
In 3.20.2 and a few earlier releases we were incorrectly releasing binaries labeled for osx-aarch_64 that were actually copies of our osx-x86_64 binaries. To clarify, we removed those in newer releases.

If you need a binary for osx-aarch_64 you should use version 21.7.

**Comment by oianmol** [comment]
I am getting the following error when using 3.21.8, can you confirm if this is an issue at your end ?

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GPBCodedInputStream", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_GRPCCall2", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_GRPCMutableCallOptions", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_GRPCRequestOptions", referenced from:
      objc-class-ref in result.o
  "_GPBComputeRawVarint32SizeForInteger", referenced from:
      _cocoapods_Protobuf_GPBComputeRawVarint32SizeForInteger_wrapper88 in result.o
  "_GPBComputeInt32Size", referenced from:
      _cocoapods_Protobuf_GPBComputeInt32Size_wrapper50 in result.o
  "_GPBComputeTagSize", referenced from:
      _cocoapods_Protobuf_GPBComputeTagSize_wrapper64 in result.o
  "_GPBComputeInt64Size", referenced from:
      _cocoapods_Protobuf_GPBComputeInt64Size_wrapper49 in result.o
  "_GPBComputeStringSize", referenced from:
      _cocoapods_Protobuf_GPBComputeStringSize_wrapper54 in result.o
  "_GPBComputeBoolSize", referenced from:
      _cocoapods_Protobuf_GPBComputeBoolSize_wrapper53 in result.o
  "_GPBWireFormatForType", referenced from:
      _cocoapods_Protobuf_GPBWireFormatForType_wrapper45 in result.o
  "_GPBWireFormatMakeTag", referenced from:
      _cocoapods_Protobuf_GPBWireFormatMakeTag_wrapper41 in result.o
  "_GRPCDefaultTransportImplList", referenced from:
      _cocoapods_GRPCClient_GRPCDefaultTransportImplList_getter_wrapper7 in result.o
ld: symbol(s) not found for architecture x86_64`

**Comment by deannagarcia** [comment]
This is a different error. Can you open a new issue and fill out the template with more information so I can reproduce this?
