### ISSUE TITLE
Back porting OpenBSD fix to 3.19, 3,20, and 21 branches

### ISSUE THREAD

**Issue by brad0** [protocolbuffers/protobuf#10741]
Could the following commit please be back ported back to the 3.19, 3.20 and 21 branches?

https://github.com/protocolbuffers/protobuf/commit/644d7ec8cfa51739bf78ab0ce7ffd5c871095083

**Comment by fowles** [comment]
feel free to offer PR's cherry picking it back to those branches

**Comment by brad0** [comment]
Ok, I was nit sure what the process was for back porting. Will do.
