### ISSUE TITLE
Why does protoc version name can not conssitent with .so version?

### ISSUE THREAD

**Issue by jinfagang** [protocolbuffers/protobuf#10742]
This is really bothering me, protobuf is the most time consuming lib I have ever seen, it was widely used, but **always** have confict problems due to every single env might have their own protobuf version ,adn this version is anonying specially with `cmake` .

I have a protoc tells me:

```
-- libprotobuf: 3.12.4

```

but I have lib like this:

```
libprotobuf.a
libprotobuf-lite.a
libprotobuf-lite.so
libprotobuf-lite.so.23
libprotobuf-lite.so.23.0.4
libprotobuf.so
libprotobuf.so.23
libprotobuf.so.23.0.4

```

Why not just make the protoc version same as .so? I can not tell if they are consist or not!!

**Comment by mkruskal-google** [comment]
3.12.4 is very old and no longer actively supported.  Are you seeing this issue on any of the more recent versions?  I took a look at the current version installed on my machine and see:
```
libprotobuf.a                 libprotobuf-lite.so.3.21.4.0  libprotoc.a
libprotobuf-lite.a            libprotobuf.so                libprotoc.so
libprotobuf-lite.so           libprotobuf.so.32             libprotoc.so.32
libprotobuf-lite.so.32        libprotobuf.so.3.21.4.0       libprotoc.so.3.21.4.0
```
which look correct (I have 3.21.4 installed).  We've recently revamped our versioning scheme, and hopefully this will be smoother now :)

**Comment by jinfagang** [comment]
thank u! That would be much more life saving!

BTW, may I ask a further question?

1. From which version start the protoc --version is same as version str as lib?
2. if you have 3.21.4, but protoc is 3.21.2 or 3.21.1, will they still claim `your protoc version is older than lib` even just minor version mismatch?

**Comment by mkruskal-google** [comment]
So there are two different versioning schemes today.  For protoc, we have no major version numbers (e.g. 21.7, 22.1) and for the language runtimes we have major+minor versions (e.g. 3.21.7, 4.22.1).  The major version numbers indicate breaking changes to the runtimes, and the minor versions indicate changes to protoc.  The third patch number represents backwards-compatible bug fixes.

In general we recommend that you use matching versions of both the runtime libraries and the compiler.  In many cases mismatched patch numbers will be compatible though, and we have internal logic for checking this (e.g. see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/stubs/common.h)
