### ISSUE TITLE
What PROTOBUF_USE_TABLE_PARSER_ON_REFLECTION does?

### ISSUE THREAD

**Issue by yushizhao** [protocolbuffers/protobuf#10759]
Hi team, 
I come across this marco when investigating a performance issue when using reflection API. Looks like PROTOBUF_USE_TABLE_PARSER_ON_REFLECTION  may improve performance but I cannot find documentations. Would you help me understand when should we enable this marco? What is the trade off?  
Thanks!

**Comment by fowles** [comment]
it exists only for temporarily rolling back a feature in case there were bugs.  It is now on uncoditionally in mainline.  It should be a pretty large speed up for parsing using reflection in C++

**Comment by yushizhao** [comment]
Thanks! Looks good! I notice that this is not included in releases. May I ask do you have a plan to release it soon?

**Comment by fowles** [comment]
We will probably cut the 22.x release sometime in the couple months, we have not set a firm data because we want to finish some cleanups enabled by having abseil as an explicit dependency
