### ISSUE TITLE
Regression: Python FromString(bytearray()) broken on upb

### ISSUE THREAD

**Issue by ajasmin** [protocolbuffers/protobuf#10774]
**What version of protobuf and what language are you using?**
Version: git main and 4.21.7
Language: Python upb

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
```
python -c 'from google.protobuf import timestamp_pb2; timestamp_pb2.Timestamp.FromString(bytearray())'
```

**What did you expect to see**
The program should run without error.

**What did you see instead?**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: expected bytes, bytearray found
```
**Workarounds**

1. Install a 3.* version of the python package
2. `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`
3. Use a memoryview:
```
with memoryview(byte_array) as mv:
    ts = timestamp_pb2.Timestamp.FromString(mv)
```

Other than bytearray, it may also be useful to add a regression test for memoryview (which currently works)

**Comment by ajasmin** [comment]
It seems a fix was committed in [ebaecb7e093aeb039db7a71daa7486c3c273bd2e](https://github.com/protocolbuffers/upb/commit/ebaecb7e093aeb039db7a71daa7486c3c273bd2e) then immediately reverted in https://github.com/protocolbuffers/upb/commit/b19c811493fafc552fd23479a65d0c15cec10f54

**Comment by ericsalo** [comment]
Wow, I have no idea what happened here (and I apologize for not noticing until today that this issue was still open).  Reproducing your patch manually on our side now, it should be pushed to GH within another day.

**Comment by ericsalo** [comment]
Oh, now I'm starting to remember what happened: I believe the problem was PyBuffer_Release(), which was not added to the stable API until 3.11 and is therefore not something that we can use (yet).

**Comment by ranlu** [comment]
Is it possible to make python packages for each major version, instead of a single package fit the stable ABI? Otherwise do we have to wait for another 3 years until 3.10 reaches EOL?

**Comment by jensbjorgensen** [comment]
This is broken as of python protobuf package 4.25.3. Older code works fine on bytearray objects, ParseFromString on bytearray fails with TypeError: expected bytes, bytearray found
