### ISSUE TITLE
Missing binaries in python runtime 4.x version

### ISSUE THREAD

**Issue by yigor** [protocolbuffers/protobuf#10778]
**What version of protobuf and what language are you using?**
Version: 4.21.7
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux (Debian bullseye), MacOS (Monterey, Intel)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.11

**What did you do?**
pip install protobuf=="4.21.7"
python -c "from google.protobuf.pyext import _message"

**What did you expect to see**
No error output

**What did you see instead?**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_message' from 'google.protobuf.pyext'

**Anything else we should know about your project / environment**
Same sequence of commands worked fine for versions 3.x including 3.20.3.

Maybe I'm missing something but starting from 4.21.0 release pypi doesn't seem to contain various kinds of wheels it used to contain for versions 3.x. Simply compare https://pypi.org/project/protobuf/4.21.7/#files to https://pypi.org/project/protobuf/3.20.3/#files 
During the installation it does use protobuf-4.21.7-cp37-abi3-manylinux2014_x86_64.whl for Linux and protobuf-4.21.7-cp37-abi3-macosx_10_9_universal2.whl for MacOS respectively (which might be a valid behavior), but they do not contain any binaries in google/protobuf/pyext folder.
And it's not like it can be explained by API change because this import I'm trying to make is still [present](https://github.com/protocolbuffers/protobuf/blob/0cb8c1353bfbc6ba6c992c9c1c22ef1845be79e5/python/google/protobuf/descriptor.py#L51) in the latest code.

**Comment by ajasmin** [comment]
The native module in the pre-packaged wheels of `protubuf>=4` was changed from one based on the c++ implementation to the new upb library (a lightweight C implementation). This is what prompted a major version bump of the Python package (4.*) and the v21 nomenclature for this GitHub repo. 

You can check the native extension is installed correctly:
```
import google._upb._message
```

This should be used by default unless you explecitly set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` to something other than upb.

**Comment by zhangskz** [comment]
Closing for now, since this seems to be answered by @ajasmin (thanks!) but @yigor please feel free to reopen if this is not resolved yet.

**Comment by yigor** [comment]
@ajasmin thank you so much for your explaination! I wish different python implementations were documented more thoroughly [here](https://developers.google.com/protocol-buffers/docs/reference/python-generated) for example.
