### ISSUE TITLE
undefined reference to 'strtof' error from protobuf lib when using minSdkVersion 19.

### ISSUE THREAD

**Issue by naahmedea** [protocolbuffers/protobuf#10782]
Description
When I use minSdkVersion 19 compile my project, and in the link step, I got this error:
protobuf/android/armeabi-v7a/libProtobuf.a(strutil.cc.o):strutil.cc:function protobuf::safe_strtof(char const*, float*): error: undefined reference to 'strtof'
But I change my minSdkVersion to 21, the error disappear.
My APP must support API 19, Do we have some workaround to solve this problem?

Environment Details
NDK Version: 19, 21 ( I have tried some version, got the same error)
Build system: cmake
ABI: armeabi-v7a
STL: c++static

**Comment by mkruskal-google** [comment]
This looks like a duplicate of https://github.com/android/ndk/issues/770.  Do any of those solutions work for you?

**Comment by naahmedea** [comment]
No, didn't work :(

**Comment by mkruskal-google** [comment]
What did you try?  It looks like the issue there was the toolchain being used.  Another option was if including `cstdlib` in our strutil.cc file fixes your issue?  If it does I have no problem adding it, but I'd need verification it worked
