### ISSUE TITLE
Assertion for Point class with GeneratedProtocolMessageType failing

### ISSUE THREAD

**Issue by ishanema1** [protocolbuffers/protobuf#10791]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem) protobuf = 4.21.6/4.21.8

Language: Python 3.9

**What operating system (Linux, Windows, ...) and version?** MacOs

**What runtime / compiler are you using (e.g., python version or gcc version)** Python 3.9

**What did you do?**
1. t = element of Point class
2. assert isinstance(t, GeneratedProtocolMessageType)
E           AssertionError: assert False
E            +  where False = isinstance(<class 'Point'>, GeneratedProtocolMessageType)
3. It used to pass till 15 Oct.

**What did you expect to see** Assertion passes

**What did you see instead?** Assertion failed

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
What version did you move to 4.21.6/4.21.8 from? If it was 3.20.x or below the major version bump moving python to use upb is likely what broke you.

You can check your python api implementation via the following:

```
from google.protobuf.internal import api_implementation
print(api_implementation.Type())
```

In 4.21.0 we changed python implementation to use upb ([announce](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates)) which likely changed the classes. Setting the [PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION](https://developers.google.com/protocol-buffers/docs/reference/python-generated#sharing-messages) can override the default api implementation to verify this.

GeneratedProtocolMessageType is used by pure python and cpp extension, but upb might use a different class. You can use [mro](https://docs.python.org/3/library/stdtypes.html#class.mro) to find the type to check against.
