### ISSUE TITLE
The numbers of bytes needed when float and int32 type serialized to string are different.

### ISSUE THREAD

**Issue by Neronjust2017** [protocolbuffers/protobuf#10790]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.14.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.3 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0

**What did you do?**
protobuf file: test_float.proto

```
syntax = "proto3";

message FloatPoint {
  float x = 1;
  float y = 2;
  float z = 3;
}

message FloatPoints {
  repeated FloatPoint float_points = 1;
}

message Int32Point {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}

message Int32Points {
  repeated Int32Point int32_points = 1;
}
```

test_float.cpp
```
#include <iostream>

#include "./test_float.pb.h"
using namespace std;

int main() {
  int num_points = 10;

  FloatPoints float_points;
  for (int i = 0; i < num_points; i++) {
    auto float_point = float_points.add_float_points();
    float_point->set_x(1.0);
    float_point->set_y(2.0);
    float_point->set_z(3.0);
  }

  Int32Points int32_points;
  for (int i = 0; i < num_points; i++) {
    auto int32_point = int32_points.add_int32_points();
    int32_point->set_x(1);
    int32_point->set_y(2);
    int32_point->set_z(3);
  }

  string float_string, int32_string;
  bool float2str = float_points.SerializeToString(&float_string);
  bool int322str = int32_points.SerializeToString(&int32_string);

  cout << "float string size: " << float_string.size() << endl;
  cout << "int string size: " << int32_string.size() << endl;
}
```

**What did you expect to see**
The sizes of float_string and  int32_string should be the same ?

**What did you see instead?**
When I run test_float.cpp, I get
```
float string size: 170
int string size: 80
```

The sizes are different and The float string size is much more larger than int32 string. It seems strange to me. Could anyone please explain this? Thanks!

**Comment by zhangskz** [comment]
3.14.0 is very old, it is recommended that you upgrade to our latest versions 3.21.x or 3.20.x.

[SerializeToString serializes to binary format](https://developers.google.com/protocol-buffers/docs/cpptutorial#parsing-and-serialization) but float and int32 are encoded differently in [Protobuf's wire format encoding](https://developers.google.com/protocol-buffers/docs/encoding) so a difference in the encoding length is not surprising. 

int32 is encoded using wire type VARINT (1 byte in your example) and float is encoded using I32 (4 bytes).
