### ISSUE TITLE
[CSharp] generate internal classes, not public

### ISSUE THREAD

**Issue by vpenades** [protocolbuffers/protobuf#10798]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**

I would like to generate c# code where the generated classes are internal, not public. Is such a thing possible?

**Describe the solution you'd like**

I understand I would need a compiler flag or a proto option to tell the compiler to replace "public" by "internal"

**Motivation**

The classes generated by proto are to be used for serialization/deserialization and not as part of a public API

On more complex scenarios, I have a proto that is shared across multiple messages in multiple libraries/projects; Because the classes are public, I am forced to generate the code in its own library, and that library is shared between the projects that require these messages.

If classes would be allowed to be internal, I could generate the classes directly into the projects that require it. Yes, the classes would be duplicated on each project that uses it, but since the classes would be internal there would be no type collisions.

**Comment by jskeet** [comment]
Documentation updated internally; it'll appear when the site is next published. I'll close this issue now as there's no further work to do.
