### ISSUE TITLE
Decode "bytes" fields as hexadecimal when printing to standard out

### ISSUE THREAD

**Issue by bobjobob** [protocolbuffers/protobuf#10794]
**What language does this apply to?**
N/A - decoding protobuf into text by running "protoc --decode" from the command line

**Describe the problem you are trying to solve.**
Trying to decode and read a "bytes" type field is very tedious.  Instead of the output being shown as a string of hexadecimal bytes, the output is a combination of octal and ASCII characters.  Then a user must manually convert that to hexadecimal bytes, which is presumably the most human-readable option that users would prefer when using a data type of "bytes".  This makes troubleshooting issues time-consuming and often confusing to those who are less familiar with the output format.

**Describe the solution you'd like**
I'd argue that the default behavior should be to use hexadecimal for bytes, but alternatively there could be an option passed in when using --decode that would force the protoc executable to output all "bytes" fields in a hexadecimal format, rather than the current default.

**Additional context**
Current output of a bytes field:  
`value: "\001\nu%J\320"`

Desired output of that same bytes field:
`value: "\x01\x0A\x75\x25\x4A\xD0"`

**Comment by fowles** [comment]
Depending on what you are trying to do, you might find https://github.com/protocolbuffers/protoscope to be a better tool.  Text format has a lot of usage already so we are unlikely to change it lightly.

**Comment by bobjobob** [comment]
I'll look into protoscope to see if it's feasible for us, but I'd still argue that adding this support to the text format is a valid and reasonable request.  Using hexadecimal in strings is already supported when encoding text files into protobuf; I don't understand why we wouldn't want to allow an option for the decoding logic to produce the same output, especially for something that seems to make a lot more sense than the default behavior.

**Comment by fowles** [comment]
Command line flags on protoc itself have a fairly high cost.  I would argue that the tool should probably not have a `--decode` flag at all, but that ship has clearly sailed.
