### ISSUE TITLE
Failed use protobuf 3.20.1 in python3.8

### ISSUE THREAD

**Issue by tangcent** [protocolbuffers/protobuf#10804]
I use protobuf in java success. But when I tried to use it in python, I failed.
I had read the [pythontutorial](https://developers.google.com/protocol-buffers/docs/pythontutorial).
I am so sad that I've spent hours trying to solve this problem. I've tried several versions of protobuf.
Any help would be greatly appreciated!

**What version of protobuf and what language are you using?**
Version: 3.20.1
Language: Python3.8
<img width="228" alt="image" src="https://user-images.githubusercontent.com/17569144/197100344-575e0a27-0d27-4757-bae3-4994cfb88968.png">

**What operating system (Linux, Windows, ...) and version?**

MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python3.8

**What did you do?**
1. Create ctx.proto:
```proto
syntax = "proto3";

package task;

message Ctx {
  optional string task_id = 1;
}
```
2. Generate the pb2 file by `./protoc-3.20.1-rc-1-osx-aarch_64/bin/protoc  --python_out=output ctx.proto`:
```
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor, reflection, message
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tctx.proto\x12\x04task\"\'\n\x03\x43tx\x12\x14\n\x07task_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_task_idb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CTX._serialized_start = 19
    _CTX._serialized_end = 58


# @@protoc_insertion_point(module_scope)
```
4. Create class Ctx:
```python
class Ctx(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = ctx_pb2.DESCRIPTOR
```
5. Try use it:
```
if __name__ == '__main__':
    ctx = Ctx()
    ctx.task_id = "xxx"
    print(ctx.SerializeToString())
```
6. Run, Then it raise an Error:
```
    if descriptor.full_name in well_known_types.WKTBASES:
AttributeError: 'FileDescriptor' object has no attribute 'full_name'
```
the code line raise the Error is https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/python_message.py#L148

**What did you expect to see**

It should serialize success!

**Comment by zhangskz** [comment]
Why are you creating class Ctx yourself in step 4? This shouldn't be needed -- protoc should generate this for you into --python_out=output.

**Comment by tangcent** [comment]
Oh! You are right. This is really a bit of a trick.

When I try to use `Ctx`:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/17569144/197364053-2561c43b-cfc3-4406-a585-6ab16270cc57.png">

And the [pythontutorial](https://developers.google.com/protocol-buffers/docs/pythontutorial) show this:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/17569144/197364010-e54e609f-8d04-455b-89e2-d7d92795e805.png">

The warning `Cannot find reference` and the code in pythontutorial drove me to create a class `Ctx`. 😂

Anyway, Everything is ok now. Thank you very much for your help.
