### ISSUE TITLE
Disabling protobuf's TLS callbacks on Windows

### ISSUE THREAD

**Issue by Ou7law007** [protocolbuffers/protobuf#10814]
Platform: Windows
Version: protobuf:x64-static-windows=3.21.4 (vcpkg)

Protobuf is generating TLS callbacks.

Just by including any .cc files (generated by protobuf) in the project, protobuf causes the final executable to have TLS callbacks present inside of it.

1- What's the purpose of these TLS callbacks?
2- How would one disable this behavior?

`option optimize_for` does not change anything about this.

**Comment by fowles** [comment]
Assuming "TLS" means "thread local storage", protobuf uses thread locals for some concurrency optimizations.  Assuming you mean "transport layer security", I am quite stumped.

**Comment by Ou7law007** [comment]
> transport layer security

I've never heard of transport layer security **callbacks** before 😅

Is it possible to omit these "concurrency optimizations" and manage them myself?

The compiler flag /Zc:threadSafeInit- (with the hyphen) allows for exactly this.

I'm not sure how to apply it for an external library such as protobuf or even better, if this was probably a built-in option?

Please don't tell me "compiling protobuf myself is the only option" because it was so painful and didn't even work in the end.

I also tried using vcpkg's triplets as follows:

set(VCPKG_CXX_FLAGS "/Zc:threadSafeInit-")
set(VCPKG_CXX_FLAGS_DEBUG "/Zc:threadSafeInit-")
set(VCPKG_CXX_FLAGS_RELEASE "/Zc:threadSafeInit-")
set(VCPKG_C_FLAGS "/Zc:threadSafeInit-")
set(VCPKG_C_FLAGS_DEBUG "/Zc:threadSafeInit-")
set(VCPKG_C_FLAGS_RELEASE "/Zc:threadSafeInit-")

The TLS callbacks were still present.

Is protobuf maybe using some other external libraries that are using TLS callbacks? Isn't there a recursive way or some built in feature? I've been struggling with this for a while now.
