### ISSUE TITLE
Version 3.21.8 causes symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by anmolvermamm** [protocolbuffers/protobuf#10813]
I am using protobuf in a project and I'm getting the following errors

`Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_GPBCodedInputStream", referenced from: objc-class-ref in result.o "_OBJC_CLASS_$_GRPCCall2", referenced from: objc-class-ref in result.o "_OBJC_CLASS_$_GRPCMutableCallOptions", referenced from: objc-class-ref in result.o "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from: objc-class-ref in result.o "_OBJC_CLASS_$_GRPCRequestOptions", referenced from: objc-class-ref in result.o "_GPBComputeRawVarint32SizeForInteger", referenced from: _cocoapods_Protobuf_GPBComputeRawVarint32SizeForInteger_wrapper88 in result.o "_GPBComputeInt32Size", referenced from: _cocoapods_Protobuf_GPBComputeInt32Size_wrapper50 in result.o "_GPBComputeTagSize", referenced from: _cocoapods_Protobuf_GPBComputeTagSize_wrapper64 in result.o "_GPBComputeInt64Size", referenced from: _cocoapods_Protobuf_GPBComputeInt64Size_wrapper49 in result.o "_GPBComputeStringSize", referenced from: _cocoapods_Protobuf_GPBComputeStringSize_wrapper54 in result.o "_GPBComputeBoolSize", referenced from: _cocoapods_Protobuf_GPBComputeBoolSize_wrapper53 in result.o "_GPBWireFormatForType", referenced from: _cocoapods_Protobuf_GPBWireFormatForType_wrapper45 in result.o "_GPBWireFormatMakeTag", referenced from: _cocoapods_Protobuf_GPBWireFormatMakeTag_wrapper41 in result.o "_GRPCDefaultTransportImplList", referenced from: _cocoapods_GRPCClient_GRPCDefaultTransportImplList_getter_wrapper7 in result.o ld: symbol(s) not found for architecture x86_64`

**Comment by deannagarcia** [comment]
Can you fill out the template to provide us more information in order to reproduce this?
