### ISSUE TITLE
If Protobuf is statically linked into a binary, but also dynamically loaded as a transitive dependency of a shared library, reflection breaks

### ISSUE THREAD

**Issue by adamnovak** [protocolbuffers/protobuf#10810]
**What version of protobuf and what language are you using?**
Version: 3.12.4 (as shipped in Ubuntu 22.04)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 22.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0

**What did you do?**
1. Run these commands:
```bash
cat >thingy.proto <<EOF
syntax = "proto3";
package ex;
message Thingy {
    string text = 1;
}
EOF
protoc thingy.proto --cpp_out=.
cat >library.hpp <<EOF
#include "thingy.pb.h"
ex::Thingy make_thingy();
EOF
cat >library.cpp <<EOF
#include "library.hpp"
ex::Thingy make_thingy() {
    ex::Thingy made;
    made.set_text("Hello world");
    return made;
}
EOF
g++ -fPIC -c thingy.pb.cc -o thingy.pb.o
g++ -fPIC -c library.cpp -o library.o
g++ -shared library.o thingy.pb.o -o liblibrary.so
cat >executable.cpp <<EOF
#include "library.hpp"
#include <iostream>
#include <google/protobuf/descriptor.h>
int main(int argc, char** argv) {
    std::cerr << "Checking for Protobuf descriptor pool..." << std::endl;
    const google::protobuf::DescriptorPool* pool =  google::protobuf::DescriptorPool::generated_pool();
    if (pool == nullptr) {
        throw std::runtime_error("Cound not find Protobuf descriptor pool: is libvgio working?");
    }
    std::cerr << "Found descriptor pool at " << pool << std::endl;
    ex::Thingy thingy = make_thingy();
    std::cout << thingy.text() << std::endl;
    return 0;
}
EOF
g++ -fPIC executable.cpp -llibrary -lprotobuf -o executable # One copy, dynamic
./executable # Works
g++ -fPIC executable.cpp -llibrary -Wl,-Bstatic -lprotobuf -Wl,-Bdynamic -o executable # One copy, static
./executable # Works

g++ -shared library.o thingy.pb.o -lprotobuf -o liblibrary-protodep.so # Two dependencies on dynamic libprotobuf (so one copy)
g++ -fPIC executable.cpp -llibrary-protodep -lprotobuf -o executable
./executable # Works
g++ -fPIC executable.cpp -llibrary-protodep -Wl,-Bstatic -lprotobuf -Wl,-Bdynamic -o executable # Static direct dependency and dynamic transitive dependency
./executable # Fails
```

**What did you expect to see**

In version 3.6.1 of Protobuf, I didn't see any problems arise from linking Protobuf statically into the binary and also dynamically as a transitive dependency of a dynamic library dependency. At least as long as the same version/build of Protobuf was used in both cases. (Though my reproduction above throws `system_error` from inside Protobuf on library load on 20.04, even when I link only one copy, my actual project is different somehow and works.)

I'm not sure if linking "the same" library multiple times in multiple ways is supposed to be allowed or not.

I would like to be able to statically link Protobuf without having to worry about whether Protobuf is a transitive dependency of any of my dynamically-linked library dependencies. For example, if `libcurl` someday starts to depend on Protobuf, and I dynamically link `libcurl` and statically link Protobuf, I don't want my application to break when built against the new Protobuf-using `libcurl`.

**What did you see instead?**

```
Checking for Protobuf descriptor pool...
Found descriptor pool at 0x5584bf440780
Hello world
Checking for Protobuf descriptor pool...
Found descriptor pool at 0x55ce8ff69200
Hello world
Checking for Protobuf descriptor pool...
Found descriptor pool at 0x55b270855780
Hello world
Checking for Protobuf descriptor pool...
[libprotobuf FATAL google/protobuf/generated_message_reflection.cc:2376] CHECK failed: file != nullptr: 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file != nullptr: 
Aborted (core dumped)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Hi Adam, long time no see! I think you can accomplish what you're trying to do, but it requires two important things:
- Keep all protobuf symbols hidden so that they're not visible across dynamic library boundaries. This will prevent ODR violations.
- Treat the main binary and each protobuf-using dynamic library as its own private protobuf universe. So each one will have its own descriptor pool and other global data structures, and don't try to pass protos from one to another. (If you really need to do this, you can serialize the message on one side, send it over as raw bytes, and then parse it on the other side.)

**Comment by adamnovak** [comment]
Hey Adam! Nice to see you again too; thanks for working on this extremely useful thing!

Unfortunately in my application what I actually want is one Protobuf universe between the library and the rest of the code, since my library interface involves Protobuf types. But luckily I control the library and the application, so I can make sure that the whole tree uses exactly one of `libprotobuf.so` and `libprotobuf.a`.

I'm reluctant to blame the C++ ODR for why using both versions of the library doesn't work, because I can't find a version of the ODR from the standard that says anything about static or dynamic linking or even `.o` files. The circa C++20 version is [here](https://timsong-cpp.github.io/cppwp/n4868/basic.def.odr), and it only talks about "translation units", which the standard [seems to define](https://timsong-cpp.github.io/cppwp/n4868/lex.separate#def:translation_unit) as something like output strings of the preprocessor.

I would say that all the .o files that go into `libprotobuf.a` are the same "translation units" as the ones that go into `libprotobuf.so`, as long as the set of defines isn't being changed inside the Protobuf build process, because the same preprocessor output is being used to build each of them.

But `ld` doesn't seem to agree with me; it won't even work properly if I feed it the same compiled translation unit twice on one command line:

```
cat >library.hpp <<EOF
int do_thing();
EOF
cat >library.cpp <<EOF
#include "library.hpp"
int do_thing() {
    return 5;
}
EOF
g++ -c library.cpp -o library.o
cat >executable.cpp <<EOF
#include "library.hpp"
int main(int argc, char** argv) {
    return do_thing();
}
EOF
g++ -c executable.cpp -o executable.o
# This will fail
g++ -o executable executable.o library.o library.o
```

The linker seems to think that multiple visits to the output of translating the same translation unit are actually multiple distinct translation units:
```
/usr/bin/ld: library.o: in function `do_thing()':
library.cpp:(.text+0x0): multiple definition of `do_thing()'; library.o:library.cpp:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

I don't see why `ld.so` would handle this any better. But I also don't see where in the standard it is pulling from when it decides this, so this might *really* be a linker limitation rather than something the standard says I shouldn't be allowed to do.

Either way, I don't think Protobuf is going to be able to do much to avoid it. And the workaround of hiding all the Protobuf symbols from the application's linker is going to work perfectly for the hypothetical Protobuf-enabled `libcurl` that I was talking about.
