### ISSUE TITLE
Protoc finds "oneof" where it isn't present

### ISSUE THREAD

**Issue by negram** [protocolbuffers/protobuf#10822]
**What version of protobuf and what language are you using?**
Version: 3.21.7
Language: plain "protoc"

**What operating system (Linux, Windows, ...) and version?**
Linux, Mac OS

**What did you do?**
We just faced quite a weird issue. Basically, there is the following directory structure:
```
$ tree
.
├── descriptor.proto
└── proto
    └── antispamtextcheck.proto
```
**descriptor.proto** is a standard protobuf file, antispamtextcheck.proto looks like this:
```proto
syntax = "proto3";

package com.bumble.contract.service;


// Which service is calling us
enum ContentSource {
  CONTENT_SOURCE_UNSPECIFIED = 0;
}

message CheckTextRequest {
  optional int64 collective_id = 2;
  optional ContentSource content_source = 4;
  // For example, the hive_id
  optional int64 content_id = 5;
}
```

When we build "proto" subfolder into a "file-descriptor-set", we can see the following:
```
$ protoc --descriptor_set_out=out-new-proto.bin -I . proto/antispamtextcheck.proto
$ protoc --decode=google.protobuf.FileDescriptorSet descriptor.proto < out-new-proto.bin
file {
  name: "proto/antispamtextcheck.proto"
  package: "com.bumble.contract.service"
  message_type {
    name: "CheckTextRequest"
    field {
      name: "collective_id"
      number: 2
      label: LABEL_OPTIONAL
      type: TYPE_INT64
      oneof_index: 0
      json_name: "collectiveId"
      proto3_optional: true
    }
    field {
      name: "content_source"
      number: 4
      label: LABEL_OPTIONAL
      type: TYPE_ENUM
      type_name: ".com.bumble.contract.service.ContentSource"
      oneof_index: 1
      json_name: "contentSource"
      proto3_optional: true
    }
    field {
      name: "content_id"
      number: 5
      label: LABEL_OPTIONAL
      type: TYPE_INT64
      oneof_index: 2
      json_name: "contentId"
      proto3_optional: true
    }
    oneof_decl {
      name: "_collective_id"
    }
    oneof_decl {
      name: "_content_source"
    }
    oneof_decl {
      name: "_content_id"
    }
  }
  enum_type {
    name: "ContentSource"
    value {
      name: "CONTENT_SOURCE_UNSPECIFIED"
      number: 0
    }
  }
  syntax: "proto3"
}
```

It shows that now we have a "oneof" field which actually looks like something wrong.

**Comment by negram** [comment]
Okay, as far as I can see this is how field presence is implemented in proto3 (https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md)

This leads us to some questions:

- Is there a way to differentiate the "optional" field from the explicitly added "oneof"? 
   It is essential for us as we use the Descriptor to implement various checks against proto-files
   and for transformations
- Is adding an "optional" label incompatible change?

**Comment by acozzette** [comment]
- I'm not sure about other languages, but in C++ you can call `FieldDescriptor::real_containing_oneof()`, which will return the `OneofDescriptor` only if it's a real oneof and otherwise return `nullptr`. `OneofDescriptor::is_synthetic()` will also tell you if the oneof is a "synthetic" one (i.e. created internally as part of an `optional` field).
- Adding `optional` to an existing singular proto3 field is fine, but just keep in mind that binaries using the old definition will of course not know about it, so for example they might think a 0-valued `optional` field is unset and drop it.
