### ISSUE TITLE
Documentation is missing build/linking instructions

### ISSUE THREAD

**Issue by hk0i** [protocolbuffers/protobuf#10820]
## What version of protobuf and what language are you using?
Version: 

```sh
protoc --version
libprotoc 3.21.8
```

Language: C++

## What operating system (Linux, Windows, ...) and version?
Mac OS 12.6 / Apple Silicon ARM64

```sh
uname -srm
Darwin 21.6.0 arm64
```

## What runtime / compiler are you using (e.g., python version or gcc version)

```sh
g++ --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

## What did you do?
Read the manual

### Steps to reproduce the behavior:
1. Install via homebrew
```sh
brew install protobuf
```

2. Read [how to write a message](https://developers.google.com/protocol-buffers/docs/cpptutorial#writing-a-message) 

## What did you expect to see
Instructions on how to compile code sample and link against libraries. 

## What did you see instead?
Absolutely no build instructions.

Could not find any details on compiling in any of the github readmes or any of the online C++ docs.

## What else did you try?
1. Searching Google on "how to build protobuf"
2. Guessing random build configurations:

```sh
llvm-g++ main.cc
In file included from main.cc:4:
./addressbook.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

```sh
g++ -L/opt/homebrew/lib -lprotobuf  main.cc
In file included from main.cc:4:
./addressbook.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by hk0i** [comment]
Was able to figure it out on my own, after running into several other issues (like c++11 requirements)

```sh
g++ -I/opt/homebrew/include -L/opt/homebrew/lib -lprotobuf -std=c++11 main.cc addressbook.pb.cc -o addressbook
```

I still think it would be worth mentioning in the actual documentation, however.

**Comment by deannagarcia** [comment]
I'm glad you were able to figure it out!

I agree it is worth documenting, and this is something we have plans for but haven't had time to prioritize. Any contributions to the docs with what you learned would be greatly appreciated!

**Comment by nikiexpo** [comment]
brew installs `libprotoc 3.19.1` and not the latest version. Any fix for this?
Already tried `brew upgrade protobuf` , it warns me that the latest is already installed

**Comment by deannagarcia** [comment]
The protobuf team does not maintain installation through homebrew. My understanding is that is maintained by homebrew directly, so I would reach out to them.

**Comment by DotIN13** [comment]
I was able to build pycld3 which is based on libprotoc on M1 MacBook Air by installing latest protobuf 21.12 and running

```shell
export LDFLAGS=-L/opt/homebrew/lib      
export CPPFLAGS=-I/opt/homebrew/include 
```

**Comment by osnortb** [comment]
> I was able to build pycld3 which is based on libprotoc on M1 MacBook Air by installing latest protobuf 21.12 and running
> 
> ```shell
> export LDFLAGS=-L/opt/homebrew/lib      
> export CPPFLAGS=-I/opt/homebrew/include 
> ```

Thank you very much for that solution it worked on my M1 MacBook Pro also 👍  I've stumbled upon some other solution if that doesn't work for you maybe the other does.(https://github.com/google/cld3/issues/80)

```shell
pip install --global-option=build_ext  --global-option="-I/opt/homebrew/Cellar/protobuf/21.12/include" --global-option="-L/opt/homebrew/Cellar/protobuf/21.12/lib" gcld3
```
