### ISSUE TITLE
Provide Python 3.11 wheels on PyPI

### ISSUE THREAD

**Issue by EwoutH** [protocolbuffers/protobuf#10836]
Currently only wheels up to Python 3.11 are provided [on PyPI](https://pypi.org/project/protobuf/#files). It would be great if Python 3.11 wheels could also be build and deployed to PyPI.

**Comment by haberman** [comment]
For versions 4.21.0 and later, the protobuf extension module uses the limited API. This means that existing artifacts (eg. protobuf-4.21.9-cp37-abi3-manylinux2014_x86_64.whl (for example)) should work on Python 3.11.

Have you tried the existing wheels with 3.11?

**Comment by haberman** [comment]
Closing, as our newest release supports Python 3.11.
