### ISSUE TITLE
Segment Fault on Python 3.8 for anaconda setup (tensorboard)

### ISSUE THREAD

**Issue by titu1994** [protocolbuffers/protobuf#10840]
**What version of protobuf and what language are you using?**
Version: 3.19.4
Language: Python 

(Note: using the latest version does not work with tensorboard with following error)

Install the latest version of tensorboard (4.21.5 https://pypi.org/project/protobuf/#history):

pip install protobuf==4.21.5
We get a dependency clash:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wandb 0.13.2 requires protobuf<4.0dev,>=3.12.0, but you have protobuf 4.21.5 which is incompatible.
tensorboard 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.5 which is incompatible.
onnx 1.12.0 requires protobuf<=3.20.1,>=3.12.2

**What operating system (Linux, Windows, ...) and version?**
Debian 10 VM, GCP, Azure, local install etc, but can be easily replicated on local conda install. 

**What runtime / compiler are you using (e.g., python version or gcc version)**
Dependency of tensorboard installation in python.

**What did you do?**

See thread for overall issue and partial resolution - https://github.com/NVIDIA/NeMo/issues/4800

1. conda create --name nemo python=3.8
2. conda activate nemo
3. Install PyTorch using their [configurator](https://pytorch.org/get-started/locally/). 
  - conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
4. apt-get update && apt-get install -y libsndfile1 ffmpeg
5. pip install Cython
6. pip install nemo_toolkit['all']
7. python -c "import nemo.collections.asr"

**What did you expect to see**

Not to segment fault. 

**What did you see instead?**

This will cause the following segment fault message (or some equivalent) 

![image](https://user-images.githubusercontent.com/3048602/198870342-896a4c85-ea07-4aef-8d84-c63d6716db4c.png)

**Anything else we should know about your project / environment**

This issue can be trivially resolved by two methods - 

https://github.com/NVIDIA/NeMo/issues/4800#issuecomment-1259819917

## Simplest way

conda create -n ... python=3.9

After this follow basic nemo install steps - install pytorch from conda first, install Cython, then install NeMo toolkit and everything works out of the box. This is because the pre-compiled protobuf for python 3.9 works out of the box.

## More convoluted way if you absolutely must use python=3.8

conda uninstall tensorboard protobuf
conda install tensorboard protobuf -c conda-forge

The problem is that for some use cases, the Python 3.9 solution is not possible (VM lock, incompatible libraries, Google colab still stuck on 3.7.x which may eventually move to 3.8.x and cause this problem there)

So while it's great that the partial uninstall and reinstall from conda forge works well, it's not a great out of the box solution. 

Any help wrt this would be appreciated.

**Comment by acozzette** [comment]
Sorry but unfortunately I don't think we're in a good position to fix this problem. Tensorflow is stuck on an old protobuf version and I strongly suspect that that is the problem. I believe there is work underway to get Tensorflow compatible with more recent protobuf versions and into a more stable setup, so we likely just need to wait for that work to be done.
