### ISSUE TITLE
RepeatedPtrField::mutable_data deprecation referring to non-existent repeated_field_util.h

### ISSUE THREAD

**Issue by danieljennings** [protocolbuffers/protobuf#10866]
`RepeatedPtrField::mutable_data` deprecation message (and comment) refers to non-existent `repeated_field_util.h`:

https://github.com/protocolbuffers/protobuf/blob/d993377d14e70a770bb743edf7d0a41137789ddc/src/google/protobuf/repeated_ptr_field.h#L996-L1003

Not sure what file it's intending to point API users toward - there weren't any obvious candidates in `src\google\protobuf` or `src\google\protobuf\util` so I'm not sure which utilities are being referenced here.

**Comment by deannagarcia** [comment]
Thanks for filing this issue, it was caused between a difference between internal and external code.

We have submitted https://github.com/protocolbuffers/protobuf/commit/9542560b0325acd433509af9ec5a557a815451f9 to remove that deprecation message.

**Comment by danieljennings** [comment]
Thanks!
