### ISSUE TITLE
Missing MacOSX Wheels in multiple versions for python 3.10

### ISSUE THREAD

**Issue by RyanSiu1995** [protocolbuffers/protobuf#10864]
**What version of protobuf and what language are you using?**
Version: 3.19.5, 3.19.6, 3.20.2, 3.20.3
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python3.10 Cpython.

**What did you do?**
`pip install protobuf==${VERSION}`

**What did you expect to see**
The wheel downloaded should be the cp310 like `protobuf-3.19.4-cp310-cp310-macosx_10_9_universal2.whl`

**What did you see instead?**
Pip downloaded the any version like this `protobuf-3.19.6-py2.py3-none-any.whl`.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Thank you for the bug report, but unfortunately I don't think we're going to be able to fix this in 3.20 or earlier. We've significantly revamped Python protobuf in 4.21 and can't prioritize going back to 3.20 or earlier for this kind of improvement. You can still use the slower pure-Python implementation in 3.20, but to get the faster implementation please upgrade to 4.21.
