### ISSUE TITLE
Codesign protoc osx binaries

### ISSUE THREAD

**Issue by kukushechkin** [protocolbuffers/protobuf#10880]
**What language does this apply to?**
Any

**Describe the problem you are trying to solve.**
In order to compile .proto files we need to use the `protoc`. It is distributed as a prebuilt binary, e.g. https://github.com/protocolbuffers/protobuf/releases/tag/v21.9. However osx-aarch_64 contains unsigned binaries, which makes it impossible to run without manually overriding default macOS security mechanisms.

![Screenshot 2022-11-02 at 9 52 31](https://user-images.githubusercontent.com/898110/199431719-1814c0a2-787a-4976-8f18-
63a3c6bdcce2.png)

**Describe the solution you'd like**
Release artifacts are code signed using Apple Developer certificates.

**Describe alternatives you've considered**
Do not codesign macOS binaries and continue asking developers working on Macs to explicitly trust random binaries downloaded from the internet.

**Additional context**

**Comment by acozzette** [comment]
This is not ready yet but we are working on it. Let me close this only because #6232 already covers signing our build artifacts.
