### ISSUE TITLE
Generate Kotlin `sealed interfaces` for Protobuf `oneOf`s

### ISSUE THREAD

**Issue by jackgene** [protocolbuffers/protobuf#10894]
**What language does this apply to?**
Kotlin

**Describe the problem you are trying to solve.**
A more type safe approach to handling Protobuf `oneOf`

**Describe the solution you'd like**
To have `oneOf` fields from Protobuf represented as `sealed interface`s in Kotlin

**Describe alternatives you've considered**
In theory, for the simplest cases, `enum class`es is a possible solution, but we should probably reserve those for Protobuf `enum`s. `sealed interface`s (or `sealed class`es) are a more appropriate solution here.

**Additional context**
For instance, we have a `oneOf` message like:
```proto
message Identifier {
  oneof identifier {
    string map_id = 1;
    string common_id = 2;
    string person_id = 3;
  }
}
```

In our system, we had to manually create:
```kotlin
sealed interface Identifier {
    fun asProtobuf(): UserPrivacyControlProtos.Identifier
}
data class CommonId(val value: String) : Identifier {
    override fun asProtobuf() = identifier { commonId = this@CommonId.value}
}
data class MapId(val value: String) : Identifier {
    override fun asProtobuf() = identifier { mapId = this@MapId.value}
}
data class PersonId(val value: String) : Identifier {
    override fun asProtobuf() = identifier { personId = this@PersonId.value}
}
```

And to convert from the current generated Protobuf class:
```kotlin
fun UserPrivacyControlProtos.Identifier.asSealedData(): Identifier? =
    when (this.identifierCase) {
        IdentifierCase.COMMON_ID -> CommonId(this.commonId)
        IdentifierCase.MAP_ID -> MapId(this.mapId)
        IdentifierCase.PERSON_ID -> PersonId(this.personId)
        IdentifierCase.IDENTIFIER_NOT_SET, null -> null
    }
```

It would be nice if this can be automated by the Protobuf Kotlin code generator.

**Comment by wfhartford** [comment]
The way @jackgene has suggested this feature be implemented, you would only pay the cost of allocating an object when the `asSealedData` function is called. In performance constrained environments, the traditional strategy could be used avoiding that allocation cost.

I think that getting a compilation failure when a new field is added is the feature @jackgene is really looking for. The advantage of a sealed class/interface is that the compiler can let us know when a case is missed. As with the performance considerations, if a user does not want code that could fail to compile when a new cases is added, they can opt out of this feature by simply not calling the `asSealedData` function.

**Comment by lowasser** [comment]
Historically, the protobuf project as a whole has been unwilling to add APIs that you should use only in some cases that can be footguns in others.  Compare, for example, the complete omission of `required` fields from proto3 -- a very comparable decision, actually, a choice to omit up-front checking of some constraints that could be footguns.  Relatedly, this also affects API constraints for protos you don't own -- this introduces new risks for a team evolving a proto and breaking code that depends on that proto.  (In particular, this _forces_ you to change the proto and all its consumers atomically if you want to keep the build green, which is very concerning.)

That said, as I think about it, it may _already_ be the case that the exhaustive when on enums breaks when a new oneof field is offered.  This is quite unfortunate -- and actually adds a little motivation to add the class representation just so we have an option that _isn't_ sealed.
