### ISSUE TITLE
protobuf 4.21.9 python distribution missing LICENSE file

### ISSUE THREAD

**Issue by zookae** [protocolbuffers/protobuf#10936]
**What version of protobuf and what language are you using?**
Version: 4.21.9
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 11. Linux.

**What runtime / compiler are you using (e.g., python version or gcc version)**
Pip install only.

**What did you do?**
Download the protobuf python package:
```
mkdir _tmp
pip install -t _tmp protobuf==4.21.9
dir _tmp\protobuf-4.21.9.dist-info
dir _
```
Shows:
```
11/07/2022  04:08 PM    <DIR>          .
11/07/2022  04:08 PM    <DIR>          ..
11/07/2022  04:08 PM                 4 INSTALLER
11/07/2022  04:08 PM               540 METADATA
11/07/2022  04:08 PM            11,177 RECORD
11/07/2022  04:08 PM                 0 REQUESTED
11/07/2022  04:08 PM               100 WHEEL
               5 File(s)         11,821 bytes
               2 Dir(s)  408,855,826,432 bytes free
```

**What did you expect to see**
The LICENSE file included in the dist-info list.

**What did you see instead?**
No LICENSE file.

**Anything else we should know about your project / environment**
We use a script to gather licenses for python packages we include when shipping our products. Protobuf is one of the packages that does not include a license file for us to gather, requiring extra manual steps to collect. Ideally the solution would fix this for all protobuf versions going forward as we've encountered the same problem with many previous protobuf releases. Thanks!

Related issues: #8904 and #7536 (https://github.com/protocolbuffers/protobuf/issues/7536)

**Comment by deannagarcia** [comment]
Thanks for this report. https://github.com/protocolbuffers/upb/commit/92dbe4b8bbb026282111f4d45d01feed35209803 should fix the issue and the LICENSE file should be in the wheel for the next release.
