### ISSUE TITLE
Use `raise ... from e` instead of `raise ...` only when catching error with try-except in python

### ISSUE THREAD

**Issue by TommyDew42** [protocolbuffers/protobuf#10949]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
In some of the python code, we only `raise` an error without using the `from` after catching an error with `except`.
For example: [json_format.py ](https://github.com/protocolbuffers/protobuf/blob/9b81aaae58be0a4db4c06180042e035c383c7e90/python/google/protobuf/json_format.py#L627-L635)
This makes debugging sometimes difficult, especially the try block is a huge chunk of logic. We are not sure which line of code caused the error.

**Describe the solution you'd like**
Use `raise ... from ...` instead of `raise ...` only

**Describe alternatives you've considered**

**Additional context**
Happy to work on this if we think it's a good idea.

**Comment by acozzette** [comment]
This sounds like a reasonable change and we would be happy to have someone review it if you would like to send a pull request.
