### ISSUE TITLE
Any reason why protobuf doesn't use the last version of bazel skybuild?

### ISSUE THREAD

**Issue by Clement-Jean** [protocolbuffers/protobuf#10965]
**What version of protobuf and what language are you using?**

`libprotoc 3.21.6`

**What operating system (Linux, Windows, ...) and version?**

MacOS, Apple M1 Max, Ventura 13.0

**What did you do?**

I defined a Bazel workspace from scratch, such as:

```bazel
workspace(name = "my_workspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.4/rules_cc-0.0.4.tar.gz"],
    sha256 = "af6cc82d87db94585bceeda2561cb8a9d55ad435318ccb4ddfee18a43580fb5d",
    strip_prefix = "rules_cc-0.0.4",
)

http_archive(
    name = "rules_proto",
    sha256 = "80d3a4ec17354cccc898bfe32118edd934f851b03029d63ef3fc7c8663a7415c",
    strip_prefix = "rules_proto-5.3.0-21.5",
    urls = ["https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.5.tar.gz"],
)

load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")
rules_cc_dependencies()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
```

then, I have an empty BUILD file in my root and the following BUILD file in the proto directory:

```bazel
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

cc_proto_library(
    name = "account_cc_proto",
    deps = [":account_proto"],
)

proto_library(
    name = "account_proto",
    srcs = ["account.proto"]
)
```

**What did you expect to see**

I expected it to create my library.

**What did you see instead?**

if I run `bazel build //proto:account_cc_proto`, I have the following error:

```
ERROR: /private/var/tmp/_bazel_clement/117db2068dbf3b2a936098c10c02808c/external/com_google_protobuf/BUILD:85:10: error loading package '@com_github_protocolbuffers_protobuf//': cannot load '@bazel_skylib//rules:common_settings.bzl': no such file and referenced by '@com_google_protobuf//:cc_toolchain'
```

**Anything else we should know about your project / environment**

After finding [this issue comment](https://github.com/bazelbuild/rules_go/issues/2530#issuecomment-639647805), I added:

```bazel
http_archive(
    name = "bazel_skylib",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()
```

in my WORSKSPACE, before loading proto rules and it built.

Is there any reason protobuf doesn't using the last version of skybuild? I'm also not sure if this issue should be here or in the rules_proto because I saw that the module there doesn't use the last version ([MODULE.bazel](https://github.com/bazelbuild/rules_proto/blob/master/MODULE.bazel))

**Comment by acozzette** [comment]
I think we're just pinned on an older version because we haven't gotten around to updating yet. If you want to send us a pull request to upgrade to the latest version, we would be happy to accept it as long as nothing breaks.

**Comment by Clement-Jean** [comment]
@acozzette What would be the best way to check if it breaks anything ? I just updated it and run some bazel commands:

- `bazel build :protobuf`
- `bazel build :protoc`

and it seems to work. But are there some further tests I can run?

**Comment by acozzette** [comment]
If you just open a pull request then we can automatically run all the CI tests, and as long as those pass I think we will be in good shape.
