### ISSUE TITLE
Q: How to override CMAKE_CXX_STANDARD?

### ISSUE THREAD

**Issue by JCash** [protocolbuffers/protobuf#10972]
Hi!
I couldn't find any documentation regarding this, and clearly my cmake skills are failing me.

My (clang-based) compiler is using "C++14" and above, and as such it won't work with passing "-std=c++11" on the command line.
However, no matter what I've tried, I cannot make the configure step change C++ version.
I've also tried overriding it using the flags, but then the compiler will still chooose the last occurance of the "-std" directive.

I'd be very grateful to any help pointing out what I'm doing wrong.

Here's the setup that I would have thought would work:
```
cmake -G "Unix Makefiles" ^
    -DCMAKE_INSTALL_PREFIX=%INSTALL_TARGET% ^
    -DCMAKE_CXX_STANDARD=17 ^
    -DCMAKE_C_COMPILER="%CROSS_CC%" ^
    -DCMAKE_CXX_COMPILER="%CROSS_CXX%" ^
    -DCMAKE_C_COMPILER_WORKS=1 ^
    -DCMAKE_CXX_COMPILER_WORKS=1 ^
    -DCMAKE_INSTALL_LIBDIR="%INSTALL_TARGET%\%TARGET_PLATFORM%" ^
    -DCMAKE_C_FLAGS=%FLAGS% ^
    -DCMAKE_CXX_FLAGS=%FLAGS% ^
    -Dprotobuf_BUILD_PROTOC_BINARIES=OFF ^
    -Dprotobuf_BUILD_EXAMPLES=OFF ^
    -Dprotobuf_BUILD_TESTS=OFF ^
    -Dprotobuf_BUILD_CONFORMANCE=OFF ^
    -Dprotobuf_BUILD_LIBPROTOC=OFF ^
    -Dprotobuf_BUILD_SHARED_LIBS=OFF ^
    -Dprotobuf_DISABLE_RTTI=OFF ^
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ^
    -DWITH_PROTOC=%SOURCE_HOST%\_build\Release\protoc.exe ^
    ..
````

Regards,
Mathias

**Comment by aayush749** [comment]
Maybe just add these two lines in the beginning of the `CMakeLists.txt` file

```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
```

**Comment by JCash** [comment]
Thanks.
I was hoping there was a way to configure this using cmake, not having to make a fork of the repo and do manual edits to the source.

**Comment by JCash** [comment]
It also seems that [this commit](https://github.com/protocolbuffers/protobuf/commit/4efbcc44605731dc31507b94f0b81d2bd5ec169b) has an update for this issue, but it hasn't made it to the latest release yet.

I will try that commit specifically, to see if that makes a difference.

**Comment by esorot** [comment]
fix already commit, but not released: https://github.com/protocolbuffers/protobuf/commit/4efbcc44605731dc31507b94f0b81d2bd5ec169b
