### ISSUE TITLE
Java | Suggesting `Message::newEmptyBuilder` functionality for less repetitive load on clients trying to build GRPC requests using the provided Builder Pattern

### ISSUE THREAD

**Issue by Dhi13man** [protocolbuffers/protobuf#10987]
## What language does this apply to?

This applies to the Code generated in Java, specifically the Message Builders.

## Describe the problem you are trying to solve

I do not understand why the generated builder's setters need to throw `NullPointerException` when a `null` value is passed into it. This makes it so clients always have to give in non-null wrapped values while mapping from POJO to GRPC DTOs through the builder.

Eg.
```java
public static BalanceRequestGrpc fromPlainRequest(
    com.pay.dto.requests.BalanceRequest request
) {
   // return BalanceRequestGrpc.newBuilder().setUserId(null).build() -> This throws NullPointerException
    return BalanceRequestGrpc.newBuilder()
        .setUserId(emptyIfNull(request.getUserId()))
        .setBankRefId(emptyIfNull(request.getBankRefId()))
        .setCustomerAddress(emptyIfNull(request.getCustomerAddress()))
        .setRequestId(emptyIfNull(request.getRequestId()))
        .setSourceList(emptyIfNull(request.getSourceList()))
        .build();
}
```

## Describe the solution you'd like

I was wondering if instead of throwing `NullPointerExceptions` directly, we could integrate the `emptyIfNull` functionality into the Builder itself so clients don't have to manually ensure null safety every single time for every single field.

Or, to preserve backwards compatibility I propose a completely separate `Message::newEmptyBuilder` functionality that instead of throwing `NullPointerException` on null input, can accept null values and set empty values when null is passed to any of the setters. This would decrease the load on clients as follows

```java
public static BalanceRequestGrpc fromPlainRequest(
    com.pay.dto.requests.BalanceRequest request
) {
   // return BalanceRequestGrpc.newEmptyBuilder().setUserId(null).build() -> This will set user ID in the GRPC Request to empty string ("")
    return BalanceRequestGrpc.newEmptyBuilder()
        .setUserId(request.getUserId())
        .setBankRefId(request.getBankRefId())
        .setCustomerAddress(request.getCustomerAddress()) 
        .setRequestId(request.getRequestId())
        .setSourceList(request.getSourceList())
        .build();
}
```

## Describe alternatives you've considered

The current way my GRPC builder clients deal with this, as shown above, is through custom `emptyIfNull` methods that have to wrap every single field every single time I try to use the builder to create GRPC DTOs.

```java
public static String emptyIfNull(String value) {
    return Objects.isNull(value) ? "" : value;
}
  
public static Long emptyIfNull(Long value) {
    return Objects.isNull(value) ? 0L : value;
}
  
public  <T> static List<T> emptyIfNull(List<T> value) {
    return Objects.isNull(value) ? Collections.emptyList() : value;
}
```

## Additional context

N/A

**Comment by googleberg** [comment]
Hi @Dhi13man, Unfortunately, This behavior has a long history and is difficult to change. We are not likely to introduce a new set of builder methods that accept null since that would greatly bloat code size. We're open to other suggestions though.
