### ISSUE TITLE
What steers the lineseparator \r\n or \n used in protoc-generated output files

### ISSUE THREAD

**Issue by yhzs8** [protocolbuffers/protobuf#11007]
**What version of protobuf and what language are you using?**
Version: main/v3.21.9 win32 version (since win64 version uses v.3.19.4 according to https://github.com/protocolbuffers/protobuf/issues/11002)

Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
N/A

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
Generate .go file using protoc with the following flags:
```
--experimental_allow_proto3_optional
--go_out
--go_opt=paths=source_relative
--go-grpc_opt=paths=source_relative
```

**What did you expect to see**
The generated file has \r\n line separators

**What did you see instead?**
The generated file has \n line separators

**Comment by deannagarcia** [comment]
This repository doesn't support go protos, please file a bug in [golang's repository](https://github.com/golang/protobuf) instead.
