### ISSUE TITLE
Add Automatic-Module-Name (for Java libs)

### ISSUE THREAD

**Issue by hendrikebbers** [protocolbuffers/protobuf#11005]
The java modules does have a `module-info.java` or provide an "Automatic-Module-Name" (in MANIFEST.MF). At least the info to the manifest should be added to provide compatibility in modern projects. More details: http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by phillipgziprecruiter** [comment]
is anything preventing this from moving?  If I created a `module-info.java` in an PR, anything I should be wary of?
