### ISSUE TITLE
protoc-21.9-win64.zip contains protoc version 3.19.4

### ISSUE THREAD

**Issue by yhzs8** [protocolbuffers/protobuf#11002]
**What version of protobuf and what language are you using?**
Version: main/v3.21.9

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
Download https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-win64.zip, extract it and run 
protoc --version

**What did you expect to see**
libprotoc 3.21.9

**What did you see instead?**
libprotoc 3.19.4

**Anything else we should know about your project / environment**
the win32 version (https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-win32.zip) is fine, it uses the latest libprotoc 3.21.9

This problem apply to:
https://github.com/protocolbuffers/protobuf/releases/download/v21.8/protoc-21.8-win64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protoc-21.7-win64.zip
as well, 

while:
https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-win64.zip
uses libprotoc 3.20.3 as expected.

**Comment by deannagarcia** [comment]
Thanks for reporting this. On preliminary investigation I can confirm that the executable is building from source at 21.x, so I think the executable is built on new code. I'm looking into why the versioning is wrong now.

**Comment by deannagarcia** [comment]
We weren't able to reproduce this issue. Please ensure that you are running the protoc from the new zip file you installed rather than an old protoc path.
