### ISSUE TITLE
Typo in the comment to SerializeDelimitedToFileDescriptor function

### ISSUE THREAD

**Issue by ujos** [protocolbuffers/protobuf#11027]
**What version of protobuf and what language are you using?**
Version:  v3.21.9
Language: C++

**What operating system (Linux, Windows, ...) and version?**
NA

**What runtime / compiler are you using (e.g., python version or gcc version)**
NA

**What did you do?**
The comment to `SerializeDelimitedToFileDescriptor` function is incorrect (src\google\protobuf\util\delimited_message_util.h:51). 

**What did you expect to see**
```cpp
// Write a single size-delimited message to the given stream.
```

**What did you see instead?**
```cpp
// Write a single size-delimited message from the given stream. 
```

**Comment by esorot** [comment]
The "from" refers to reading from the file descriptor.

**Comment by esorot** [comment]
https://github.com/protocolbuffers/protobuf/commit/568672c733be81bfb4915400a870c6f45afb33ce
