### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none) ERROR: No matching distribution found for mediapipe

### ISSUE THREAD

**Issue by Aryandeshmukh85** [protocolbuffers/protobuf#11030]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by Aryandeshmukh85** [comment]
My python is the latest one but still the same error is visible

**Comment by Aryandeshmukh85** [comment]
My system is windows

**Comment by Aryandeshmukh85** [comment]
language python

**Comment by esorot** [comment]
Need further clarification
