### ISSUE TITLE
python protobuf wheels do not contain cpp implementation in 4.x

### ISSUE THREAD

**Issue by tommilligan** [protocolbuffers/protobuf#11062]
**What version of protobuf and what language are you using?**
Version: 4.21.9
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.8

**What did you do?**

Build the following docker image (linux version not relevant, python 3.8, protobuf python client 4.21.x)

```bash
docker build -f Dockerfile -t gcloud-install-fail-repro .
```
```Dockerfile
# Dockerfile
FROM python:3.8-bullseye

RUN python -m venv /env
ENV PATH=/env/bin:$PATH \
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp \
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2 \
    VIRTUAL_ENV=/env
RUN pip install -U pip && \
    pip install google-api-python-client==2.66.0 && \
    pip install protobuf==4.21.9

ENV CLOUDSDK_VERSION=410.0.0-0
ENV CLOUDSDK_PYTHON=/env/bin/python
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
          http://packages.cloud.google.com/apt cloud-sdk \
          main" | \
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt-get update && \
    apt-get install -qyy --no-install-recommends --no-install-suggests \
        "google-cloud-sdk=${CLOUDSDK_VERSION}"
```

**What did you expect to see**

A successful installation of `google-cloud-sdk`

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```log
#7 3.055 Get:1 http://packages.cloud.google.com/apt cloud-sdk/main amd64 google-cloud-sdk all 410.0.0-0 [130 MB]
#7 5.196 debconf: delaying package configuration, since apt-utils is not installed
#7 5.260 Fetched 130 MB in 2s (61.7 MB/s)
#7 5.346 Selecting previously unselected package google-cloud-sdk.
(Reading database ... 23422 files and directories currently installed.)
#7 5.356 Preparing to unpack .../google-cloud-sdk_410.0.0-0_all.deb ...
#7 5.360 Unpacking google-cloud-sdk (410.0.0-0) ...
#7 14.81 Setting up google-cloud-sdk (410.0.0-0) ...
#7 15.29 ERROR: gcloud failed to load: No module named 'cloudsdk.google.protobuf.pyext'
#7 15.29     gcloud_main = _import_gcloud_main()
#7 15.29     import googlecloudsdk.gcloud_main
#7 15.29     from googlecloudsdk.calliope import base
#7 15.29     from googlecloudsdk.calliope import display
#7 15.29     from googlecloudsdk.calliope import display_taps
#7 15.29     from googlecloudsdk.core.resource import resource_printer_base
#7 15.29     from googlecloudsdk.core.resource import resource_projector
#7 15.29     import proto  # pylint: disable=g-import-not-at-top
#7 15.29     from .enums import Enum
#7 15.29     from cloudsdk.google.protobuf import descriptor_pb2
#7 15.29     from cloudsdk.google.protobuf import descriptor as _descriptor
#7 15.29     from cloudsdk.google.protobuf.pyext import _message
#7 15.29
#7 15.29 This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
#7 15.29
#7 15.29 Please verify that the following is the path to a working Python 3.5+ executable:
#7 15.29     /env/bin/python
#7 15.29
#7 15.29 If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 3.5+ executable.
#7 15.29
#7 15.29 If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
#7 15.29     https://cloud.google.com/sdk/
#7 15.31 dpkg: error processing package google-cloud-sdk (--configure):
#7 15.31  installed google-cloud-sdk package post-installation script subprocess returned error exit status 1
#7 15.32 Errors were encountered while processing:
#7 15.32  google-cloud-sdk
#7 15.34 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

If the filesystem is inspected prior to installing `google-cloud-sdk`, you can see the compiled cpp implementation is missing:

```bash
$ pip install -U protobuf~=4.0
...
  Downloading protobuf-4.21.9-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
...
$ ls /env/lib/python3.8/site-packages/google/protobuf/pyext/
__init__.py  __pycache__  cpp_message.py
```

Whereas in protobuf 3.x versions, it is present:

```bash
$ pip install -U protobuf~=3.0
...
  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
...
$ ls /env/lib/python3.8/site-packages/google/protobuf/pyext/
__init__.py  __pycache__  _message.cpython-38-x86_64-linux-gnu.so  cpp_message.py
```

**Anything else we should know about your project / environment**

I tried installing wheels of various versions and found that on my target environment (Linux, Python 3.8), I was able to automatically install the cpp version from a python wheel up to the latest 3.x version.

I reviewed the changelog for the python packages 4.x and did not see this listed as a breaking change anywhere.

If the environment variable `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp` is removed the install succeeds, using the python protobuf implementation. However, this is not suitable for our production use case for performance reasons.

Please advise if this is part of a known issue, and if there is any suitable workaround. I see several open issues that look potentially related:

- https://github.com/protocolbuffers/protobuf/issues/10618
- https://github.com/protocolbuffers/protobuf/issues/10443

**Comment by haberman** [comment]
This is intended. In 4.21.0 the Python protobuf implementation switched from C++ to a new implementation in C. More info here: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

If you want fast performance, you can remove the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` environment variable. Or if you want to assert that you are getting the (fast) C implementation, you can set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb`.

**Comment by tommilligan** [comment]
Thanks for the explanation and the linked information - that makes sense!

Is it possible this could be added as a clear breaking change in the relevant GitHub release, as someone who was not aware of the linked page until now? Or that page more clearly linked as the source of truth for future breaking changes?
