### ISSUE TITLE
Could we directly turn json or dict to protobuf serialized message without .proto in Python?

### ISSUE THREAD

**Issue by Lunaticf** [protocolbuffers/protobuf#11076]
Suppose we have a service received different schema and insert corresponding records to bigQuery with protobuf.

But we have no way to know all schemas in advance and prepare all .proto files.

Is there any way we can directly convert json to seralized proto message without .proto and the compiled python class? Or can we do it in runtime? like gen .proto and compile it and use the python class?

I find xia-easy-proto this lib exactly do the things I want. But it is not open sourced and seems not much people used, wondering if there is any other better lib or method. thanks

**Comment by junyer** [comment]
You need to generate the field name → type mappings from the input data yourself, but you want `MakeSimpleProtoClass()` in [`google/protobuf/proto_builder.py`](https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/proto_builder.py); see [`google/protobuf/internal/proto_builder_test.py`](https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/proto_builder_test.py) for some example usage.

**Comment by Lunaticf** [comment]
@junyer  Hi, thanks for the kindly answer. It really helps and works like a charm. I can use this and python setAttr function to jgenerate class and set fields. Thanks
