### ISSUE TITLE
build dynamic library (.dylib) in Mac/Linux

### ISSUE THREAD

**Issue by DCMinds** [protocolbuffers/protobuf#11109]
Hi Team,

When I am building he protobuf-cpp using came, by default it is building static library(.a) in Mac/linux.
I want to build it as dynamic library (.dylib) in Mac/linux.

Can you please help or guide me the steps need to be followed?

**Comment by junyer** [comment]
See https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#dlls-vs-static-linking for more information.
