### ISSUE TITLE
Error Unable to load descriptor: public_dep X is out of range

### ISSUE THREAD

**Issue by tforesti** [protocolbuffers/protobuf#11146]
**What version of protobuf and what language are you using?**
protobuf 3.21.6
PHP 8.1
protoc 3.12.4

**What operating system (Linux, Windows, ...) and version?**
Linux Debian 11

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
We got an error with php protobuf extension on versions after 3.19.4 (it is ok on 3.19.4) and it seems to be a bug.
It happens in a specific case : when we build a protobuf message (from a generated PHP class) and when the equivalent protobuf file imports another protobuf which also imports a protobuf file.
I don't know if it is clear so I have reproduced it here:
https://github.com/tforesti/php-protobuf-ext-issue
Just build and run Dockerfile.

Error:
```
PHP Fatal error:  Unable to load descriptor: public_dep 0 is out of range
 in /app/build/GPBMetadata/Prototest.php on line 20
```

I found these error messages here:
https://github.com/protocolbuffers/protobuf/blob/main/php/ext/google/protobuf/def.c#L950
https://github.com/protocolbuffers/protobuf/blob/main/php/ext/google/protobuf/php-upb.c#L9431

Are you aware of this? Did we do something wrong?

Thank you!

**Comment by tforesti** [comment]
Hi, this issue is still relevant with version after 3.19.4.

I have updated my use cases here https://github.com/tforesti/php-protobuf-ext-issue with a OK Dockerfile (with 3.19.4) and KO Dockerfile (with latest version).

Thank you!

**Comment by haberman** [comment]
I suspect this is a bug in the code generator. There is some code that manually munges the dependency list: https://github.com/protocolbuffers/protobuf/blob/9473beb76c573e10eed3c98a246fe1411708ff14/src/google/protobuf/compiler/php/php_generator.cc#L839-L1049

I'm guessing that this code is removing a dependency from the list, but not updating the `public_dependency` list to match.

**Comment by tforesti** [comment]
Yes, this is still an issue preventing us from updating our PHP Protobuf version. I test regularly with new versions.
What do you mean by _adding proper extensions support to PHP_?
I tried to investigate with what you mentioned, but I must admit that it was a little complicated for me at the moment 🙂.

**Comment by joec4i** [comment]
Can we please reopen this issue?

This problem still occurs with code generated by the latest grpc_php_plugin for protoc. The regression was introduced in https://github.com/protocolbuffers/protobuf/pull/9585 (3.20.0RC3) The last working version of the PHP extension is 3.20.0RC1 from PECL: https://pecl.php.net/package/protobuf/3.20.0RC1 . The first broken version is 3.20.0RC3 but there's no pecl package for it. 3.20.0RC2 has a broken build configuration which is unrelated to this problem.

Notably, this issue only affects the PHP extension — the composer package `google/protobuf` does not exhibit the same problem.

Thank you! cc @haberman
