### ISSUE TITLE
Please include latest python sources in distfiles

### ISSUE THREAD

**Issue by 0-wiz-0** [protocolbuffers/protobuf#11145]
@haberman wrote in https://github.com/protocolbuffers/protobuf/issues/11031 :

> It looks like you are trying to build the old extension. The code in https://github.com/protocolbuffers/protobuf/tree/main/python/google/protobuf/pyext is deprecated in OSS and is no longer used in our official releases.
> If you install binary wheels from our PyPI packages, it should support 3.11 without you needing to compile anything. That said, we should make it easier to build from source when necessary. Our source packages appear to contain the old extension code. We should update that to contain the new extension from https://github.com/protocolbuffers/upb/tree/main/python instead.

Please update the source to include the latest version of the Python module like @haberman suggested.

**Comment by deannagarcia** [comment]
To clarify: Are you talking about the source files we release on [github](https://github.com/protocolbuffers/protobuf/releases/tag/v21.11) (protobuf-python-4.21.11.zip) or the source distribution we release on [pypi](https://pypi.org/project/protobuf/#files) (protobuf-4.21.11.tar.gz)?

**Comment by 0-wiz-0** [comment]
I'm asking in particular for the source files distributed via pypi.
(Are the github ones up-to-date?)

**Comment by deannagarcia** [comment]
So both are the most recent version of the code, but both are also the python implementation and not the UPB implementation. We are planning to release source distributions of the UPB implementation in 22.x on pypi which you should expect to see in January. 

The source distribution released from github is being deprecated, which is why I wanted to ensure you were downloading it from pypi.

**Comment by haberman** [comment]
This was fixed in 4.22.0. There is now a source distribution that contains the same sources that are released in the binary wheel.
