### ISSUE TITLE
Java generation: allow non-final generation for classes

### ISSUE THREAD

**Issue by MarinaShaposhnikova** [protocolbuffers/protobuf#11162]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?
Java.

**Describe the problem you are trying to solve.**
I am trying to write unit tests for the generated classes, but because they are not final I can't mock it.
I have to use mock-maker-inlined, however, I do not want to have an extra overload and affect performance, I am keen to have not final classes (open/interfaces) to mock it properly.

**Describe the solution you'd like**
An option to disable "public final class"

**Describe alternatives you've considered**
Using a third-party library to mock it.

**Additional context**

Code example:

```
public  final class MyResponse extends
``` 
where final can not be mocked

**Comment by esorot** [comment]
Is there a particular end state or goal you're aiming for which you would need to mock the generated classes?

**Comment by perezd** [comment]
Protobufs should not ever be mocked. We have extensive experience with this at large scale internally at Google and can emphatically and definitively say this is not the right approach to testing that involves Protobuf messages.

If you want to write unit tests to assert the functionality of generated classes, test the actual code, not what your mocks say is the actual code. This gives you a false sense of security if/when we change things on you. Who would know to update the mocks?

**Comment by artnaseef** [comment]
100% disagree about mocking.  Please learn how mocks and pure white-box unit tests work.

Whatever you guys did wrong in learning that lesson, please look at it again.  The entire rest of the world, outside of google, in my experience, seems to get it.

**Comment by artnaseef** [comment]
Here is the key problem with that argument:

> test the actual code, not what your mocks say is the actual code.

We are NOT testing GRPC's generated code in those tests.  We ARE testing our own code, that uses GRPC.  Hence the mock.  That's a pure whitebox test.  We use pure black-box tests to validate third-party code.

**Comment by fowles** [comment]
@artnaseef two distinct points,

1.  I believe you are conflating mocking grpc's code with mocking protobuf classes.  If you would like to discuss mocking for grpc objects, then you should probably discuss this in the appropriate grpc forum (likely https://github.com/grpc/grpc-java).  Protobuf classes are in memory value types without external dependencies, so mocking them is usually unnecessary.  It is generally better to have code under test actually do mutation/creation of protobuf objects and to make assertions on the resultant values.
2.  Your tone is quite dismissive bordering on outright rude.  Please maintain a respectful demeanor when engaging with the [protobuf community](https://github.com/protocolbuffers/.github/blob/main/profile/CODE_OF_CONDUCT.md).

**Comment by artnaseef** [comment]
@fowles was just reminded of this thread, so hope the late response is welcome.

On (1) you are right that we don't want to mock model objects (as long as they are clean model objects without any logic in them).  I did not intend to suggest that we want to mock model objects.  However, there is a lot of generated code with logic/functionality and using those - without mocking - requires sockets, so very bad for a pure unit test.  So I understand why you think I might have been conflating issues, but I don't believe that was the case.

On (2) you are right - my response saying "please learn" and more - was too much.  I apologize.  I lost my patience.  At the same time, there should be a response to the comments from @perezd.  Making such strong assertions that clearly indicate a lack of interest to work with the OP is stonewalling, and certainly does not show any consideration of the position of the users of the protobuf tools.

Lastly, would love to have an actual conversation on the merits of unit testing and mocks, and how protobuf (and perhaps other google projects) participate and enable good development practices for the users of those libraries / tools.

**Comment by fowles** [comment]
@artnaseef  I am genuinely confused.  Where do the sockets come into this?  I will admit to way more familiarity with C++ protobuf than Java protobuf, but I am pretty sure the generated objects don't have any dependency on sockets or any networking anything.  Can you point me towards what you are referring to?

**Comment by artnaseef** [comment]
@fowles here is a project I worked on.  It's been a little while, so I need to fully refresh my memory.

**POM using maven plugin to generate sources**
https://github.com/OpenNMS-Cloud/lokahi/blob/develop/shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/pom.xml

**PROTO file**
https://github.com/OpenNMS-Cloud/lokahi/blob/develop/shared-lib/lokahi-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms_minion_ipc.proto

See the service definition:

    service CloudService {

This results in the generated file `target/generated-sources/protobuf/grpc-java/org/opennms/cloud/grpc/minion/CloudServiceGrpc.java` with the following:

    @javax.annotation.Generated(
        value = "by gRPC proto compiler (version 1.54.1)",
        comments = "Source: opennms_minion_ipc.proto")
    @io.grpc.stub.annotations.GrpcGenerated
    public final class CloudServiceGrpc {

Perhaps there's conflating of gRPC and protobuf here?  IIRC, we only had 1 maven plugin to compile both - `protobuf-maven-plugin`.

**Comment by fowles** [comment]
Yup, that is definitely in the gRPC side of things.

**Comment by artnaseef** [comment]
OK, so the OP really needed to be pointed over there.  Simple mistake.  Too bad it wasn't caught earlier.
