### ISSUE TITLE
protobuf src  examples make error

### ISSUE THREAD

**Issue by CYuSir** [protocolbuffers/protobuf#11181]
➜  examples git:(main) ✗ make       
[ 12%] Running cpp protocol buffer compiler on addressbook.proto
[ 12%] Building CXX object CMakeFiles/add_person_cpp.dir/add_person.cc.o
[ 12%] Building CXX object CMakeFiles/add_person_cpp.dir/addressbook.pb.cc.o
[ 12%] Linking CXX executable add_person_cpp
/usr/bin/ld: CMakeFiles/add_person_cpp.dir/addressbook.pb.cc.o: in function `google::protobuf::internal::VerifyUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, char const*)':
addressbook.pb.cc:(.text._ZN6google8protobuf8internal10VerifyUTF8EPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc[_ZN6google8protobuf8internal10VerifyUTF8EPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc]+0x37): undefined reference to `google::protobuf::internal::VerifyUTF8(std::basic_string_view<char, std::char_traits<char> >, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/add_person_cpp.dir/build.make:169：add_person_cpp] 错误 1
make[1]: *** [CMakeFiles/Makefile2:85：CMakeFiles/add_person_cpp.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
➜  examples git:(main) ✗

**Comment by esorot** [comment]
Need further details on reproducing please.
