### ISSUE TITLE
got redefinition error when use unity_build in cmake

### ISSUE THREAD

**Issue by jituihanbao** [protocolbuffers/protobuf#11202]
when I set UNITY_BUILD property in cmake, I got these errors 

A.pb.cc:110:65: error: redefinition of 'schemas'
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
                                                                ^
B.cc:68:65: note: previous definition is here
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
                                                                ^
A.pb.cc:114:55: error: redefinition of 'file_default_instances'
static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
                                                      ^
B.pb.cc:72:55: note: previous definition is here
static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
                                                      ^

is there anyway to avoid this?

**Comment by sanyi0127** [comment]
resolved?
