### ISSUE TITLE
New Version Request

### ISSUE THREAD

**Issue by FrankXie05** [protocolbuffers/protobuf#11251]
I am the maintainer of the [vcpkg](https://github.com/microsoft/vcpkg). 
Recently, we received a issue that the  new installation method of the header files have changed so that the user's needs cannot be met.

**Describe the problem you are trying to solve.**

For the new header file installation method of cmake, new header files are added and improved. As a result, the latest version of `21.11` cannot meet the user's requirements for header files e.g:

- `google/protobuf/compiler/cpp/field.h`
- `google/protobuf/compiler/cpp/options.h`

**Describe the solution you'd like**

When to release a new version to use the latest header file？

**Describe alternatives you've considered**

Make patches according to https://github.com/protocolbuffers/protobuf/pull/10306 to use the latest installation method.

**Additional context**
https://github.com/protocolbuffers/protobuf/blob/1f58f1d7b83ec333ab6076bf2e76797dd8de3e45/cmake/install.cmake#L46
```
include(${protobuf_SOURCE_DIR}/src/file_lists.cmake)
set(protobuf_HEADERS
  ${libprotobuf_hdrs}
  ${libprotoc_hdrs}
  ${wkt_protos_files}
  ${descriptor_proto_proto_srcs}
  ${plugin_proto_proto_srcs}
)
```

**Comment by FrankXie05** [comment]
Link vcpkg https://github.com/microsoft/vcpkg/issues/28284

**Comment by mkruskal-google** [comment]
These are internal headers we've never exported.  If they're suddenly visible in main that's a bug we should fix.  Their Bazel targets are marked private, but it seems like the new CMake installation might be picking them up.

**Comment by FrankXie05** [comment]
This issue is not resolved in the latest version.
