### ISSUE TITLE
Can we add additional service methods (e.g. Publish / Subscribe) to the Protobuf IDL? 

### ISSUE THREAD

**Issue by dh1tw** [protocolbuffers/protobuf#11267]
Hi,
If I understand the protobuf docs right, by today a protobuf service only supports the method rpc. However a lot of microservices these days are also using publish/subscribe mecanisms for async communication where protobuf is used for serialization / deserialization.

Is there an easy way to add additional methods like publish and subscribe to a Service definition in the protobuf IDL?

I was thinking about something like:

[omitting the message definitions]

service Greeter {
   rpc SayHello (HelloReq) returns (HelloResp); // as already implemented
   pub Announce (Announcement); // publish -> async fire & forget; does not return anything 
   sub Listen (Annoucement); // subcribe to async Annoucement events
}

I understand that this is probably not doable with HTTP(2), but including the puband sub methods in the IDL would allow us to autogenerate the server/client code through a plugin for the desired PubSub mecanism (e.g. NATS, NSQ...).

Any thoughts & ideas welcome!

**Comment by chriscarter6988** [comment]
> @anandolee can u help

**Comment by dh1tw** [comment]
any help, comments or pointers would really be appreciated!
