### ISSUE TITLE
CMake documentation doesn't work

### ISSUE THREAD

**Issue by shareefj** [protocolbuffers/protobuf#11336]
@Tradias I've been trying to follow your CMake documentation [here](https://github.com/protocolbuffers/protobuf/blob/main/docs/cmake_protobuf_generate.md) but it falls over because the `generated` directory doesn't exist.  Is there a missing step to create it?  CMake seems to expect it at `/path/to/cmake/build/generated`.

**Comment by Tradias** [comment]
Yes, it appears that for certain kind of CMake generators it does not automatically create the ouput directory (e.g `NMake Makefiles`). As a workaround you can create the directory yourself, by adding the following somewhere in your CMakeLists:

```cmake
file(MAKE_DIRECTORY "${PROTO_BINARY_DIR}")
```

Or use a different generator, like [Ninja](https://ninja-build.org/) or "Visual Studio 17 2022".

-------------------------------

A proper solution inside protobuf-generate is unfortunately not so easy. Using the above approach would mean that the directory is not part of "CMake clean" and if it where added to [ADDITIONAL_CLEAN_FILES](https://cmake.org/cmake/help/latest/prop_dir/ADDITIONAL_CLEAN_FILES.html?highlight=clean) then it would not be recreated automatically whenever `proto-objects` are build. And the other approach of adding this to the `add_custom_command` inside `protobuf_generate` 

```cmake
COMMAND "${CMAKE_COMMAND}" -E make_directory "${PROTO_BINARY_DIR}"
```

has the issue of introducing race conditions in some generators.

**Comment by shareefj** [comment]
Thanks.  I'll take a look at those options.
