### ISSUE TITLE
Protobuf import failure on version 4.21.12

### ISSUE THREAD

**Issue by AnandInguva** [protocolbuffers/protobuf#11374]
**What version of protobuf and what language are you using? = 4.21.12**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: Python
**What operating system (Linux, Windows, ...) and version? = Linux, Mac**

**Python version: 3.10, 3.9"

**What did you do?**
1. Install protobuf==4.21.12
2. python
3. import google.protobuf.pyext._message as pyext

Results in 
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf.pyext._message as pyext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```
This works in protobuf=3.20.3

**Comment by AnandInguva** [comment]
It can be related to artifacts missing in PYPI. Reference: https://github.com/protocolbuffers/protobuf/issues/10564

**Comment by deannagarcia** [comment]
In python's major version bump from 3.20 to 4.21 the syntax for this changed.

You should now use `from google._upb import _message`. I confirmed that this works on my machine but feel free to reopen if you have any problems.

**Comment by AnandInguva** [comment]
Hi, can you point me to the change log where this is documented? I am not able to find it

**Comment by fowles** [comment]
all names with a leading `_` are considered private, so this was not documented in the change log
