### ISSUE TITLE
Request to add entry to extension registry

### ISSUE THREAD

**Issue by joldf** [protocolbuffers/protobuf#11397]
I would like to add an entry to the extension registry: https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md

This is for SAPIENT, a communication protocol standard for autonomous sensor systems.

Here is suggested text for the addition:

1. SAPIENT
   * Website: https://www.gov.uk/guidance/sapient-autonomous-sensor-system
   * Extension: 1181

(suggested text above previously said: ~~Extension: 1179~~)

I'd be happy with any extension number, I just picked 1179 because it appears to be the next one available. We are likely to use multiple option extensions, but as suggested in the docs we will nest them in a message so we will only need one extension number.

I would have preferred to open a pull request to save everyone some hassle, but unfortunately I can't sign the CLA.

**Comment by fowles** [comment]
The CLA is a strict legal requirement.  We cannot bend on that point.

**Comment by joldf** [comment]
@fowles  The CLA is a strict legal requirement for pull requests, I understand that. That's why I didn't open a pull request. But I thought it was not a requirement to add a feature in response to an issue, isn't that right?

**Comment by fowles** [comment]
still waiting on a clarification from legal.  Will likely have to wait till after the holidays

**Comment by joldf** [comment]
@thisisnotapril 

Thanks for that explanation April.

I think the confusion here is that I'm not actually trying to submit a contribution. I'm asking for some documentation to be changed but I've only specified the change should contain the technology name (which is the single word "SAPIENT"), a number (I've suggested one but feel free to use another), and a URL. Those three things are not a sufficiently creative work to be copyrightable. In fact, to use a URL you don't even need the permission of the owner let alone a license agreement. A Googler can compose those three things into the actual change, which would be a bullet point in a list (and I don't think even that is creative enough that it is copyrightable).

I can try to arrange for a CLA to be signed if you would still like that. But it would be a pity as it would set a precedent that CLAs should be signed in future even for requests that really do not require it.

**Comment by thisisnotapril** [comment]
Thanks for the clarification @joldf! You're correct, if you're not contributing the documentation change yourself then no need for a CLA. 

@fowles I think we treat this like a feature request, and it's open for whomever to make the change/contribution.

**Comment by joldf** [comment]
@fowles  Would you be kind enough to make this change? I realise it doesn't impact most customers of protobuf but it would be really helpful for us.

**Comment by joldf** [comment]
@fowles  Apologies for chasing but would you be able to make this change or find someone that could? I only expect it would take a few moments and would really help us out. If it's not done soon then we might just have to proceed with publication of proto files with the assumption that 1179 is available to us. This could cause confusion if someone else updates that page without noticing this issue.

**Comment by joldf** [comment]
Sorry for the noise but I've just seen that 1179 an 1180 are already used (they're just not at the end of the file) so it would need to be at least 1181.

**Comment by joldf** [comment]
Following on from my last comment: it appears others have had the same confusion as me because 1179 and 1180 are both now duplicated allocations (see the [current `options.md`](https://github.com/protocolbuffers/protobuf/blob/v23.1/docs/options.md)): 1179 is allocated to both ygot (entry 25) and Cybozu (entry 89) while 1180 is allocated to both ygot (entry 25) and Wire use_array (entry 90).
