### ISSUE TITLE
Help wanted:  TypeError: Couldn't build proto file into descriptor pool!

### ISSUE THREAD

**Issue by acrobat888** [protocolbuffers/protobuf#11404]
Developing in Python 3.10.8
MacOS 12.6.2
syntax = "proto3";

**_Issue:_**

I have a proto file in `Package_A` that I am trying to import into `Package_B`. 
`Package_A` is installed via pip install, so it lives in the `site_packages` of my venv.

`Package_B`'s proto file includes the import "package_a/package_a.proto" at the top of the file.

When I use protoc to compile `Package_B`'s grpc & pb2 files it all works fine, but when I try running `Package_B`, I get the following error:

ImportError while loading testfile.py

pacakge_b/src/package_b.py:18: in <module>

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
E   TypeError: Couldn't build proto file into descriptor pool!
E   Invalid proto descriptor for file "package_b.proto":
E     package_a/protos/package_a.proto: Import "package_a/protos/package_a.proto" has not been loaded.
E     package_b.Message.foo: "foo" seems to be defined in "package_a.proto", which is not imported by "package_b.proto".  To use it here, please add the necessary import.

The only way I can seem to make it work is effectively copying all the data from `Package_B` -- proto files and generated pb files -- into `Package_A`, which doesn't make sense.

I've read a lot of documentation about relative vs. absolute paths, but seems everything I have tried with generating new files isn't working.  I'm trying to leverage building packages and then importing only what's needed for each other package.

Any suggestions would be welcome, and hope all have a great holiday.

**Comment by acrobat888** [comment]
Resolved with some research.

**Comment by cp15512516229** [comment]
I'm having the same same problem, can you tell me how to fix it?
