### ISSUE TITLE
Can you provide some methods to directly transfer to PHPArray? like "serializeToPHPArray" and "mergeFromPHPArray"

### ISSUE THREAD

**Issue by hkargv** [protocolbuffers/protobuf#11436]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
![a](https://user-images.githubusercontent.com/61319333/210160545-7be31535-532f-4b53-9f22-5207a118a8ee.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I think json_encode has performance loss. Can I use PHP Array directly?like :
![b](https://user-images.githubusercontent.com/61319333/210160551-20ea8511-42bd-4111-9646-390582d36836.png)

**Comment by haberman** [comment]
Have you tried this?

```
$c2s = new XMan\Get\Request($C2S);
```

**Comment by hkargv** [comment]
Get.proto
```php
syntax = "proto3";
package Get;

option php_namespace = "XMan\\Get";
option php_metadata_namespace = "XMan\\Get\\pb";

message C2S
{
	int32 uid = 1;
}

message Request
{
	C2S c2s = 1;
}
```

php:
```php
<?php
include(__DIR__ . '/../vendor/autoload.php');

function protobuf_autoloader($class){
	if (strncmp($class, 'XMan\\', 5) === 0) {
		include_once(__DIR__ . '/' . str_replace('\\', '/', $class) . '.php');
	}
}
spl_autoload_register('protobuf_autoloader');

$C2S = array(
	'c2s' => array(
		'uid' => 2000
	)
);
$c2s = new XMan\Get\Request($C2S);
/**Uncaught Exception: Expect XMan\Get\C2S. in /wwwroot/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:198
Stack trace:
#0 /wwwroot/tests/XMan/Get/Request.php(61): Google\Protobuf\Internal\GPBUtil::checkMessage()
#1 /wwwroot/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1080): XMan\Get\Request->setC2S()
#2 /wwwroot/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(79): Google\Protobuf\Internal\Message->mergeFromArray()
#3 /wwwroot/tests/XMan/Get/Request.php(32): Google\Protobuf\Internal\Message->__construct()
#4 /wwwroot/tests/zx.php(16): XMan\Get\Request->__construct()
#5 {main}
  thrown in /wwwroot/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php on line 198**/

die();

//The following code works fine
$c2s = new XMan\Get\Request();
$c2s->mergeFromJsonString(json_encode($C2S), true);
$C2S = $c2s->serializeToString();

$c2s = new XMan\Get\Request();
$c2s->mergeFromString($C2S);
$C2S = $c2s->serializeToJsonString(); //Can you provide a method like 'serializeToPHPArray' ?
$C2S = json_decode($C2S, true);
print_r($C2S);
```

**Comment by hkargv** [comment]
> Have you tried this?
> 
> ```
> $c2s = new XMan\Get\Request($C2S);
> ```

Can you provide a method like 'serializeToPHPArray' ? thanks.

**Comment by haberman** [comment]
It looks like the library is accepting the array, but it doesn't like the sub-array for the `c2s` field initializer.

It looks like you are using pure PHP. Does this example work with the Native C extension?

If so, we should fix the pure-PHP library to match.

**Comment by hkargv** [comment]
> It looks like the library is accepting the array, but it doesn't like the sub-array for the `c2s` field initializer.
> 
> It looks like you are using pure PHP. Does this example work with the Native C extension?
> 
> If so, we should fix the pure-PHP library to match.

Neither "pure PHP" nor "Native C extension"

IN Native C extension:
```php
PHP Fatal error:  Uncaught TypeError: Given value is not an instance of XMan\Get\C2S. in /wwwroot/tests/XMan/Get/Request.php:32
Stack trace:
#0 /wwwroot/tests/XMan/Get/Request.php(32): Google\Protobuf\Internal\Message->__construct()
#1 /wwwroot/tests/zx.php(21): XMan\Get\Request->__construct()
#2 {main}
  thrown in /wwwroot/tests/XMan/Get/Request.php on line 32
  ```
