### ISSUE TITLE
well_known_types is deprecated and suggests using :descriptor_proto_srcs, which does not exist

### ISSUE THREAD

**Issue by ravenblackx** [protocolbuffers/protobuf#11430]
**What version of protobuf and what language are you using?**
Version: v21.12
Language: Python

**What did you do?**
1. Try to build a thing that depends on `@com_google_proto//:well_known_types` after updating to v21.12
2. Get WARNING message `depends on deprecated target '@com_google_protobuf//:well_known_protos': Prefer :well_known_type_protos instead.`
3. Look in [BUILD.bazel](https://github.com/protocolbuffers/protobuf/blob/main/BUILD.bazel#L132-L145) to see that this "Prefer" is an incomplete message, and the full message in the comment says
    ```
    # DEPRECATED: Prefer :well_known_type_protos for the Well-Known Types
    # (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)
    # or :descriptor_proto(_srcs) for descriptor.proto (source), or
    # :compiler_plugin_proto for compiler/plugin.proto.
    ```
4. Try using variations of those to no avail.
5. Look in BUILD.bazel again, and see that there is no `:descriptor_proto_srcs` target (I see it in the `main` branch, but not in 21.12)

**What did you expect to see**
Some option that will work in the context where `deps=["@com_google_protobuf//:well_known_types"]` previously worked, without a deprecation warning. With `:descriptor_proto_srcs` the problem is the missing target. With the other three options as deps, there is a lengthy error message that I am not confident doesn't include NDA information so cannot include here. It seems reasonably clear that the issue is not including srcs, since that's the only difference between `deps=[":well_known_types"]` and `deps=[the three that exist]`.

**What did you see instead?**
No combination of the suggested alternatives will build that target.

My current workaround is to simply patch out the `deprecation` tag and continue to use `:well_known_types` for now.

**Comment by mkruskal-google** [comment]
It looks like 21.x went out while our Bazel refactoring was underway, and in 22.x these targets do exist.  Is ignoring the deprecation warning in 21.x a viable solution or should we just remove it in 21.x?

**Comment by ravenblackx** [comment]
Ignoring it is pretty inconvenient in a large build environment - we get hundreds to thousands of instances of the warning, which could easily make us miss other build issues. (Hence patching it out in our http_archive targets.)
It's not a problem for me at this point because I already made that patch, but I'd say it's probably worth addressing for others if this is a supported branch.

**Comment by mkruskal-google** [comment]
K, I'll update 21.x to give a better deprecation message.  The targets it's *supposed* to be pointing to are `:well_known_type_protos`, `:compiler_plugin_proto`, and `:descriptor_proto`

**Comment by ravenblackx** [comment]
I think this solution may not actually help if you have Python code that depends on (what is later) `:descriptor_proto_srcs`. I'm pretty sure I looked for any targets that provided the necessary files, and the deprecated target was the only one in this version.

**Comment by mkruskal-google** [comment]
I'm not following.  `:well_known_protos` is a deprecated filegroup containing both the WKT protos, descriptor.proto, and plugin.proto.  We have individual filegroups already that export all of those, so you can just switch to those.  `//:well_known_type_protos`, `//:compiler_plugin_proto`, and `//:descriptor_proto` are all in 21.12, and should give you the access you want

**Comment by ravenblackx** [comment]
Right, our code currently depends on `:well_known_protos`.

If we change the code to depend on all three of those other targets, it still doesn't build, because none of those targets include the `:descriptor_proto_srcs` content (that target is available on main but not on 21.12); that content is what (in some targets) `:well_known_protos` is included for.

i.e. the deprecation warning tells us to change our build rules in a way that we cannot, in fact, change the build rules while depending on this version.

**Comment by mkruskal-google** [comment]
`:descriptor_proto_srcs` is just a filegroup exporting `descriptor.proto` in 22.x (i.e. main).  In 21.x you can use `//:descriptor_proto`, which does the same thing...

**Comment by ravenblackx** [comment]
No, `//:descriptor_proto` is [this proto library](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/BUILD.bazel#L155) in both versions (unless you changed that in addition to changing documentation).
`//:descriptor_proto_srcs` is [this filegroup](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/BUILD.bazel#L465).

They both have srcs="descriptor.proto", but `descriptor_proto_srcs` makes that proto file itself available to its clients, while `descriptor_proto`'s proto_library target makes only the generated code available.

**Comment by mkruskal-google** [comment]
Ah sorry, I missed that this was a `proto_library` rule in 21.x.  Let me update 21.x to properly export this similarly to what we've done on main

**Comment by ravenblackx** [comment]
This problem has returned again in another new version - it was fixed by what you did, but "well_known_protos" now flags as deprecated and exposes
```
    srcs = [
        ":descriptor_proto_srcs",
        ":well_known_type_protos",
        "//src/google/protobuf/compiler:plugin.proto",
    ],
```

The comment says
```
# DEPRECATED: Prefer :well_known_type_protos for the Well-Known Types
# (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)
# or :descriptor_proto(_srcs) for descriptor.proto (source), or
# :compiler_plugin_proto for compiler/plugin.proto.
```

But the target `:compiler_plugin_proto` doesn't exist.

(Also, it would be nice if the `deprecated=` tag said all the same options the comment says, because otherwise when we update this our developers are going to get this warning telling them to switch to only `:well_known_type_protos` which may or may not actually work for their use-case.)

**Comment by ravenblackx** [comment]
Turns out the issue doesn't reopen with a comment, so I've made a new issue for this "same problem different update".
