### ISSUE TITLE
Inconsistent version in released zip packages

### ISSUE THREAD

**Issue by mkaltenh** [protocolbuffers/protobuf#11440]
Hi,
our team noticed that the naming of the generated .tar.gz and .zip files in inconsistent as of v21.x

For v20.3 all bundles were still named as expected:
```
protobuf-all-3.20.3.tar.gz
protobuf-all-3.20.3.zip
protobuf-cpp-3.20.3.tar.gz
protobuf-cpp-3.20.3.zip
protobuf-csharp-3.20.3.tar.gz
protobuf-csharp-3.20.3.zip
protobuf-java-3.20.3.tar.gz
protobuf-java-3.20.3.zip
protobuf-js-3.20.3.tar.gz
protobuf-js-3.20.3.zip
protobuf-objectivec-3.20.3.tar.gz
protobuf-objectivec-3.20.3.zip
protobuf-php-3.20.3.tar.gz
protobuf-php-3.20.3.zip
protobuf-python-3.20.3.tar.gz
protobuf-python-3.20.3.zip
protobuf-ruby-3.20.3.tar.gz
protobuf-ruby-3.20.3.zip
protoc-3.20.3-linux-aarch_64.zip
protoc-3.20.3-linux-ppcle_64.zip
protoc-3.20.3-linux-s390_64.zip
protoc-3.20.3-linux-x86_32.zip
protoc-3.20.3-linux-x86_64.zip
protoc-3.20.3-osx-x86_64.zip
protoc-3.20.3-win32.zip
protoc-3.20.3-win64.zip
```

However with the change to v3.21.7 and ever since this has changed. Since then protobuf-all is named with 21.x and the rest as 3.21.x also notice how python is 4.21.x since then.

Since v21.7 the version is different between languages:
```
protobuf-all-21.7.tar.gz
protobuf-all-21.7.zip
protobuf-cpp-3.21.7.tar.gz
protobuf-cpp-3.21.7.zip
...
protobuf-python-4.21.7.tar.gz
protobuf-python-4.21.7.zip
...
protoc-21.7-linux-aarch_64.zip
protoc-21.7-linux-ppcle_64.zip
protoc-21.7-linux-s390_64.zip
protoc-21.7-linux-x86_32.zip
protoc-21.7-linux-x86_64.zip
protoc-21.7-osx-aarch_64.zip
protoc-21.7-osx-universal_binary.zip
protoc-21.7-osx-x86_64.zip
protoc-21.7-win32.zip
protoc-21.7-win64.zip
```

After adding (for example) the protoc-21.12-win64.zip to path it still returns its version number as 3.21.12 so it seems this is unintentional on your side. Autogenerated Changelogs on your [release page](https://github.com/protocolbuffers/protobuf/releases) now also use "Protocol Buffers v21.x" as header text.

This becomes an issue with 3rd party libraries such as @protobuf-ts/protoc which has trouble finding the installer for 3.21.x because of this naming and fails.

**Comment by zhangskz** [comment]
This is an intentional change to our versioning scheme to decouple per-language major versions as announced in https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning.

Releases can now largely be referred to using the minor version (aka v21.x release) which will be the same for all languages though each language will have its own major version (3.21.x, 4.21.x). I believe the major version number for protoc continues to follow the C++ major version.
