### ISSUE TITLE
Creation of dynamic property is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by stanislav-janu** [protocolbuffers/protobuf#11452]
Please change classes like that:
```diff
-class Message
+class Message extends \stdClass
{
```
This allows using dynamic properties.

**Comment by bshaffer** [comment]
@stanislav-janu Ideally, we would fix this error by _not_ assign dynamic properties to classes in PHP. 

The error I'm getting is:

```
PHP Deprecated:  Creation of dynamic property Google\Protobuf\Internal\MapFieldIter::$key_type is deprecated in google/protobuf/src/Google/Protobuf/Internal/MapFieldIter.php on line 63
```

There may be other instances of this error, however. Could you provide the stack trace for yours?

**Comment by bshaffer** [comment]
I see, it seems like these issues are actually in the subclasses, but the warning is thrown in the `Message` class, since it's the parent class. 

This is a different issue than the one I fixed, so we should keep this open.

**Comment by bshaffer** [comment]
I looked into this a little more, and the expected property would is [$schema_restriction_response](https://github.com/googleapis/google-cloud-php/blob/main/AnalyticsData/src/V1beta/ResponseMetaData.php#L32), so I'm not sure why the one you have is prefixed with an underscore. Is it possible that you're using an outdated version of protobuf? 

Run `composer info google/protobuf`, and provide to us the version you're using. Also, if you could, run `php -i | grep proto` and provide the results as well (to see if you're using the protobuf extension)

**Comment by stanislav-janu** [comment]
In composer I have:
```
		"google/apiclient": "^2.12",
		"google/analytics-admin": "^0.6.2",
		"google/analytics-data": "^0.8.0",
		"googleads/google-ads-php": "^17",
```

in composer.lock I see:
```
            "name": "google/protobuf",
            "version": "v3.21.12",
```

After i tried upgrade, is it same:
```
		"google/apiclient": "^2.13",
		"google/analytics-admin": "^0.8",
		"google/analytics-data": "^0.9",
		"googleads/google-ads-php": "^17",
```

Problem maybe in repo [googleapis/php-analytics-data](https://github.com/googleapis/php-analytics-data/blob/master/metadata/V1Beta/Data.php)/metadata/V1Beta/Data.php:171, there I see underscored `$_schema_restriction_response`.

**Comment by bshaffer** [comment]
@stanislav-janu that part of the file is binary, so I'm not sure that's what is causing it. Could you provide the code you used to duplicate the issue? I tried with the following and was unsuccessful: 

```php
$r = new \Google\Analytics\Data\V1beta\ResponseMetaData();
$r->setSchemaRestrictionResponse(new \Google\Analytics\Data\V1beta\ResponseMetaData\SchemaRestrictionResponse());
echo $r->serializeToJsonString();
// {"schemaRestrictionResponse":{}}
```

**Comment by s2x** [comment]
I get a lot of errors about deprecation but only for `oneof` or `optional` fields. Here is example

```
[2023-01-12T13:32:46.169434+01:00] deprecation.INFO: Deprecated: Creation of dynamic property DeliveryItem::$_disabled is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Creation of dynamic property DeliveryItem::$_total is deprecated at .../vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:152)"} []
```

here is the code of `google/protobuf/src/Google/Protobuf/Internal/Message.php` in my case the `disabled` is `optional bool disabled` and the code is generating `_disbaled` property
```php
            } else if ($field->getOneofIndex() !== -1) {
                $oneof = $this->desc->getOneofDecl()[$field->getOneofIndex()];
                $oneof_name = $oneof->getName();                      //<--------$oneof_name = '_disbaled`
                $this->$oneof_name = new OneofField($oneof);
            } else if ($field->getLabel() === GPBLabel::OPTIONAL &&
```

**Comment by stanislav-janu** [comment]
All the errors reported to me come from the same place `vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php in Google\Protobuf\Internal\Message::initWithGeneratedPool at line 152`
https://github.com/protocolbuffers/protobuf/blob/main/php/src/Google/Protobuf/Internal/Message.php#L152

**Comment by roxblnfk** [comment]
Hi.
I have the same issue. I see there is a problem with release script.

https://github.com/protocolbuffers/protobuf-php/commit/1fc16ac4b14107db52597c98b08a80a85a3167d5
![img](https://user-images.githubusercontent.com/4152481/217159453-32888663-148b-470e-a985-4871605793cd.png)

There are all the fixes of PHP 8.2 deprecations in this commit (`master` branch)...
But look at the tag name: `vnull`

**Comment by stanislav-janu** [comment]
@roxblnfk I have no issue after this upgrade. Thank you.

**Comment by roxblnfk** [comment]
FYI `v3.22.0` was released.
https://github.com/protocolbuffers/protobuf-php/releases/tag/v3.22.0
