### ISSUE TITLE
Service definition with same name in different packages causes duplicate internal struct definition

### ISSUE THREAD

**Issue by mgallathe** [protocolbuffers/protobuf#11456]
**What version of protobuf and what language are you using?**
Version: v3.19.4 
Language: C++

**What operating system**
Windows 10

**What runtime / compiler are you using**
gcc 11.2 

**What did you do?**
See also example [PlcNextGrpcTest.zip](https://github.com/protocolbuffers/protobuf/files/10345315/PlcNextGrpcTest.zip)
1. Create 2 proto files with same name in different directories. Content is the same or similar. Package is different for different namespaces. At least the service names in both files should be the same. See example: `PlcNextGrpcTest\protos\Sample\world1\helloworld.proto` and `PlcNextGrpcTest\protos\Sample\world2\helloworld.proto`
2. use protobuf and C++ plugin to generate C++ stub code. Please find already generated code at `PlcNextGrpcTest\GrpcSimpleClient\src\GrpcStubs`
3. Compile and link C++ code

**What did you expect to see**
Compile should succeed. No naming conflicts

**What did you see instead?**
```
error : CMakeFiles/GrpcSimpleClient.dir/src/GrpcStubs/world2/helloworld.pb.cc.o:(protodesc_cold+0x0): multiple definition of `TableStruct_helloworld_2eproto::offsets'; CMakeFiles/GrpcSimpleClient.dir/src/GrpcStubs/world1/helloworld.pb.cc.o:(protodesc_cold+0x0): first defined here(message from c:/sdks/.../11.2.0/real-ld.exe)
error : CMakeFiles/GrpcSimpleClient.dir/src/GrpcStubs/world2/helloworld.pb.cc.o:C:/m_git/PlcNextGrpcTest/GrpcSimpleClient/src/GrpcStubs/world2/helloworld.pb.cc:87: multiple definition of `descriptor_table_helloworld_2eproto'; CMakeFiles/GrpcSimpleClient.dir/src/GrpcStubs/world1/helloworld.pb.cc.o:C:/.../PlcNextGrpcTest/GrpcSimpleClient/src/GrpcStubs/world1/helloworld.pb.cc:87: first defined here(message from c:/.../11.2.0/real-ld.exe)
```
I wonder if the struct declaration and definition of `TableStruct_helloworld_2eproto` and definition of `descriptor_table_helloworld_2eproto` should be included in a namespace or its name should contain information of the package to make it unique.

**Anything else we should know about your project / environment**
* Attached example proto files are written as easy as possible. In our implementation we have different services with same name because of their purpose. But the messages inside are different. 
* Since the service names are defined as interface before we cannot simply change the names to make them unambiguously and avoid this problem. 
* Attached VS project uses a specific cross compile toolchain. You can use your gnu compiler instead if you need to compile the code.

**Comment by perezd** [comment]
I think you might want to file this with https://github.com/grpc/grpc project, as the service definitions are generated using grpc plugins, typically.

**Comment by mgallathe** [comment]
Thank you for your answer. I filed the issue to the protobuf project since from the information in the header of the generated file the duplicate definitions are generated by the protobuf compiler, see helloworld.pb.h
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto
...
// Internal implementation detail -- do not use these members.
struct TableStruct_helloworld_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
```
If with this information you still think that the issue should be filed to the grpc project then I will do that. Otherwise please reopen this issue.

**Comment by mgallathe** [comment]
We found a solution to let the protobuf compiler generate unique names for the structure definition. The key for the solution is in starting the protobuf compiler not defining the proto_path in that in our real project (not this sample) beside the source *.proto further .proto files exist that include each other.

Generating the stub code by these commands leads to the naming conflict
```
protoc.exe --proto_path=.\world1 --grpc_out=..\..\GrpcSimpleClient\src\GrpcStubs\world1 --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe .\world1\*.proto
protoc.exe --proto_path=.\world2 --grpc_out=..\..\GrpcSimpleClient\src\GrpcStubs\world2 --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe .\world2\*.proto
```
Generating the stub code by these commands solves above problem
```
protoc.exe  --grpc_out=..\..\GrpcSimpleClient\src\GrpcStubs --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe .\world1\*.proto
protoc.exe  --grpc_out=..\..\GrpcSimpleClient\src\GrpcStubs --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe .\world2\*.proto
```
By the fix the issue is solved for us and can remain closed
