### ISSUE TITLE
Missing JsonPrintOptions for bytes to debug communication

### ISSUE THREAD

**Issue by ChristianToepfer** [protocolbuffers/protobuf#11454]
To print messages as json is a create feature to debug the communication in detail, but to see a big binary blob within a message string is not very help full at this point. 

A big advantage over string based json communication is, that one can very easy embed images or generally binary data.
The full binary blob is self-contained and usually another construction site. Clarity is lost when the entire binary data is printed.  "To debug message with binary data, is more like watching at the header info of a file".

Really helpful would be to print only the size of the binary data.
`{ "name": "text",
   "data": "[212 bytes]" }`

instead of the base64 encoding string:

`{ "name": "text",
   "data": "ChBoYW4udmZuLmxhbjo0NTM5ElJ...." }`

With an extra option `print_simple_size_info_for_bytes` in JsonPrintOptions, the user can change the print behavior for that.
The flag is then only need to handle in JsonObjectWriter::RenderBytes, to support this great feature.

---
Christian

**Comment by perezd** [comment]
Adding @mcy for comment/feedback on request.
