### ISSUE TITLE
C++: x64-linker problem with ArenaString method ExplicitlyConstructed

### ISSUE THREAD

**Issue by boro0607** [protocolbuffers/protobuf#11479]
**What version of protobuf and what language are you using?**
Version: v3.21.08
Language: C++
OS: Windows 10
Compiler: MS VS 2022 Prof. 
Toolset: 143
Language: ISO C++17 standard, ISO C17
SDK: 10.0.22
Package Manager: vcpkg, version 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba

**What did you do?**
1. Compiled protobuf (without zlib) using vcpck and triplets x86-windows-static / x64-windows-static
2. Compiled my code with referencing to resulting libs for x86 and x64
3. Code compiled/linked without any problems for win32/x86

**What did you expect to see**
Code to link for x64 as well (as it did using protobuf 3.10.0)

**What did you see instead?**
Linker error:
1>mylib.lib(messages.pb.obj) : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,8> google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$07@123@A)
1>mylib.lib(messages.pb.obj) : error LNK2001: unresolved external symbol "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)
1>mylib.lib(messages.pb.obj) : error LNK2001: unresolved external symbol "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlobalEmptyTable@internal@protobuf@google@@3QBQEAXB)

**Anything else we should know about your project / environment**
1. The problem, does not occur when I link dynamically. However, for some reasons we may want to stick to static linkage.
2. The problem also occurs when I link the library statically but the CRT dynamically.
3. We use protobuf since three years to exchange data for a complex model. The model obviously contains string information. I noticed that changes to the MemoryArena have been applied and that the error appeared in the past. However, I found no hint to fix it.
4. We simply want to upgrade after a long period.

**Comment by jorgbrown** [comment]
It's odd that it would work with dynamic linkage but not static.  Have you tried asking Microsoft?

**Comment by jorgbrown** [comment]
Assigning to Adam for triage.

**Comment by boro0607** [comment]
> Nope, we haven't contact MS!

**Comment by arthur-tacca** [comment]
Have you tried printing out the full command line passed to the linker? (You can do then when building in the Visual Studio IDE by turning up the build verbosity in options.) You should verify that mylib.lib is earlier in the link line than protobuf.lib. If it is later (i.e. if your link line looks like "`... protobuf.lib ... mylib.lib`" then that would explain the linker error, and you would need to adjust your CMakeLists.txt to fix it (make `mylib` target depend on `protobuf` target, rather than both depended on from some higher-level target).

This may not be the problem, just an idea worth trying. Sorry if it is a distraction.

**Comment by boro0607** [comment]
> Have you tried printing out the full command line passed to the linker? (You can do then when building in the Visual Studio IDE by turning up the build verbosity in options.) You should verify that mylib.lib is earlier in the link line than protobuf.lib. If it is later (i.e. if your link line looks like "`... protobuf.lib ... mylib.lib`" then that would explain the linker error, and you would need to adjust your CMakeLists.txt to fix it (make `mylib` target depend on `protobuf` target, rather than both depended on from some higher-level target).
> 
> This may not be the problem, just an idea worth trying. Sorry if it is a distraction.

Hi, the linker command seems to be fine. As mentioned, it works for 32 bit compilation, it only fails for 32 bit and only if linked statically.

Cheers,
   SB
