### ISSUE TITLE
Cannot build protobuf_cpp 

### ISSUE THREAD

**Issue by quickiwiki** [protocolbuffers/protobuf#11489]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 19.10

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 8.4.0 

**What did you do?**
1. downloaded https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.zip
2. extracted to protobuf-cpp-3.21.12
3. cd protobuf-cpp-3.21.12
4. bazel build :protoc :protobuf

**What did you expect to see**
the build
**What did you see instead?**

ERROR: Traceback (most recent call last):
	File "/home/user/src/protobuf-3.21.11/WORKSPACE", line 65, column 20, in <toplevel>
		kotlin_repositories()
	File "/home/user/.cache/bazel/_bazel_el/4ff2ab00280bf986db63a7ce46013904/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
		rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
ERROR: Error computing the main repository mapping: at /home/user/.cache/bazel/_bazel_el/4ff2ab00280bf986db63a7ce46013904/external/io_bazel_rules_kotlin/kotlin/core.bzl:2:5: at /home/user/.cache/bazel/_bazel_el/4ff2ab00280bf986db63a7ce46013904/external/io_bazel_rules_kotlin/kotlin/internal/opts.bzl:16:5: Encountered error while reading extension file 'kotlin/opts.bzl': no such package '@io_bazel_rules_kotlin_configured//kotlin': error loading package 'external': Could not load //external package

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
This is a bug with one of our dependencies: https://github.com/bazelbuild/rules_kotlin/issues/883

There are 2 easy workarounds:
1. Use a bazel version < 6.0
2. Delete the lines referencing io_bazel_rules_kotlin in the WORKSPACE file
