### ISSUE TITLE
CMake files are not installed when built with autoconf

### ISSUE THREAD

**Issue by a-andre** [protocolbuffers/protobuf#11545]
CMake is planning to deprecated `FindProtobuf in favour of the cmake files provided by protobuf, because it is difficult to maintain compatibility with protobuf's cmake files, see [[1]](https://gitlab.kitware.com/cmake/cmake/-/issues/23037#note_1288748) and [[2]](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8045) But that relies on distributions shipping these cmake files. Some distributions, like Debian or Fedora, don't ship the files, yet, because the distributions are using autoconf to build protobuf.

Please install CMake files when using autoconf+*make install* or remove autoconf files from release tarballs to force distributions to provide protobuf's CMake files.

**What version of protobuf and what language are you using?**
Version: v21.12
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
Arch Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Extract protobuf tarball (https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.tar.gz)
2. `./configure`
3. `make`
4. `make install` 

**What did you expect to see**
CMake files installed, like it is done when using CMake to build protobuf.

**What did you see instead?**
No cmake files installed.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by mkruskal-google** [comment]
We've removed autotools support as of https://github.com/protocolbuffers/protobuf/pull/10132 and will no longer be shipping those configs.  The only supported mechanism for system installation in 22.x and beyond will be cmake.  Note, you can *also* use cmake to install protobuf in 21.x, in which case the cmake files should get set up properly.

Given that we plan to release 22.x in the next few weeks, I'm going to close this.  Let me know if you have some more specific need for this in 21.x w/ autotools though.

**Comment by a-andre** [comment]
Thanks, that information helps.
