### ISSUE TITLE
Bazel build of py_proto_library with generated source fails

### ISSUE THREAD

**Issue by mikex-oss** [protocolbuffers/protobuf#11553]
**What version of protobuf and what language are you using?**
Breakage starting at https://github.com/protocolbuffers/protobuf/commit/b55c8e40843855716c79aaa9a01aca89c636cf65 via bisection. Initially found by attempting to upgrade from v3.20.0 to v.21.12.
Language: Python

**What operating system (Linux, Windows, ...) and version?** Linux 3.10.0-1160.76.1.0.1.el7.x86_64 

**What runtime / compiler are you using (e.g., python version or gcc version)** Bazel 5.2

**What did you do?**
1. Create build file with generated src .proto.
```
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

#  py_proto_library depend on the source proto being in the same package as the consuming rule
genrule(
    name = "generated_proto",
    srcs = ["@external_repo//path/to:foo.proto"],
    outs = ["foo.proto"],
    cmd = "cp $< $@",
)

py_proto_library(
    name = "foo_py_pb2",
    srcs = ["foo.proto"],
)
```

1. Build the py_proto_library.
```
bazel build //my_project/proto:foo_py_pb2
```

**What did you expect to see**

Before the commit mentioned above, the build completed successfully.

```
$ bazel build //my_project/proto:foo_py_pb2
INFO: Analyzed target //my_project/proto:foo_py_pb2 (42 packages loaded, 710 targets configured).
INFO: Found 1 target...
...
INFO: From ProtoCompile my_project/proto/foo_pb2.py:
<path>/sandbox/linux-sandbox/1047/execroot/my_project_repo
Target //my_project/proto:foo_py_pb2 up-to-date:
  bazel-bin/my_project/proto/foo_pb2.py
INFO: Elapsed time: 75.079s, Critical Path: 16.77s
INFO: 202 processes: 2 internal, 200 linux-sandbox.
INFO: Build completed successfully, 202 total actions
```

**What did you see instead?**

```
ERROR: <path>/my_project/proto/BUILD:206:17: ProtoCompile my_project/proto/foo_pb2.py failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
foo.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
mv: cannot stat 'bazel-out/k8-fastbuild/bin/foo_pb2.py': No such file or directory
<path>/sandbox/linux-sandbox/510/execroot/my_project_repo
Target //my_project/proto:foo_py_pb2 failed to build
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

I also commented here: https://github.com/protocolbuffers/protobuf/pull/9735#issuecomment-1355839717

**Anything else we should know about your project / environment**

**Comment by phst** [comment]
Probably best to switch to `py_proto_library` from `rules_python` instead.  It had a similar problem in the past, but IIRC that's fixed.

**Comment by mikex-oss** [comment]
> Probably best to switch to `py_proto_library` from `rules_python` instead. It had a similar problem in the past, but IIRC that's fixed.

We did eventually migrate but generated proto sources are still a problem due to some weird "_virtual_imports" behavior. https://github.com/bazelbuild/rules_python/issues/1597
