### ISSUE TITLE
Abseil absl::string_view TransparentSupport & StringPiece

### ISSUE THREAD

**Issue by Arcnor** [protocolbuffers/protobuf#11627]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
Now that protobuf is going to use abseil under the covers, may I suggest you add support for `absl::string_view` in the same places `std::string_view` is currently used (which for what I can see is just `TransparentSupport` in maps & `StringPiece`?

**Comment by mkruskal-google** [comment]
We've already started migrating `const std::string&` to `absl::string_view` in many places.  I didn't realize we had any `std::string_view` uses, I'll migrate those right now :)

**Comment by Arcnor** [comment]
Good to hear, thanks!

**Comment by mkruskal-google** [comment]
Thanks for the suggestion!  This will make it *just* in time for the upcoming 22.0 release :)
