### ISSUE TITLE
Cannot compile generated C++ code

### ISSUE THREAD

**Issue by DeadFishw** [protocolbuffers/protobuf#11706]
Hi! 
I am working on installing cruzdb, and when I compile (make) the code generated by protoc, it runs into problem that it cannot find "google/protobuf/port_def.inc". 
error message: 
fatal error: google/protobuf/port_def.inc: No such file or directory
   11 | #include "google/protobuf/port_def.inc"
I am using libprotoc 21.12 and c++, and I am on WSL ubuntu

If anyone could tell me what the problem is I would be most grateful~

**Comment by palade** [comment]
Are you including the protobuf headers? For example, `g++ -I/home/user/.local/include`, 

where `ls /home/user/.local/include`

```
google 
```

**Comment by computerquip-work** [comment]
This shouldn't be closed, it's still a problem somehow two years later.
