### ISSUE TITLE
"unified_protos" or "Unified Python/C++ support": Python protobuf backed by generated C++ protos reducing cross-language serialization cost

### ISSUE THREAD

**Issue by fahhem** [protocolbuffers/protobuf#11707]
**What language does this apply to?**
Python, though it affects compilation for C++ protos when the flag is enabled.

**Describe the problem you are trying to solve.**
When using Python C-extensions, such as via pybind11, and passing a protobuf from Python to C++ (or vice versa) the "best" way is to serialize the protobuf in the source language then pass it as a buffer across the barrier, and deserialize from the buffer. This means passing large protos across the barrier can be more expensive than implementing the C++ function in Python.

However, if the Python protobuf was actually backed by a C++ generated protobuf, then when passing the object the C++ message could be pulled out and passed to C++ directly. And when passed back to Python, a protobuf could be created that either took ownership of the C++ proto or knew that the C++ proto was owned externally.

**Describe the solution you'd like**
This could all be done by using the `PyProto_API` object and either building a CPython entrypoint with the protos all statically linked in, or (as I managed to get working) by building shared libraries for every C++ proto and loading them before loading every Python proto.

I'd like to propose, and eventually merge, the shared library solution, with the documented caveat that all the shared libraries need to be generated and built by the same version of libprotobuf that is loaded as well. 

**Describe alternatives you've considered**

There is a path where `py_binary` is replaced/implemented by a `cc_binary` entrypoint that statically (or dynamically) links in all protos used directly or indirectly, and possibly all C extensions. However, that requires modifying the users codebase and cannot be done within the protobuf codebase itself. It also is non-optimal if users want to use or ship multiple py_binary's that use an overlapping set of protos, since every proto would necessarily be loaded into memory more than once while in the shared library implementation they would be loaded once by the OS and shared across binaries.

**Additional context**
I got this working internally in my codebase by implementing a custom bazel flag (as opposed to the define-based flag that protobuf uses for `use_fast_cpp_protos`) and by altering both `py_proto_library` and `cc_proto_library`, and by depending on undocumented protoc C++ generator options and protoc plugin options.

However, I would be happy to alter that approach as necessary to get this feature upstreamed, as I think it would be a big boon to the Python protobuf community to be able to use pybind11 or other C extensions with "zero-overhead" protobuf passing. It would definitely make protobufs more useful in performance sensitive applications, such as my use-case.

**Comment by haberman** [comment]
We want to support better sharing between Python and C/C++, but not through the old bindings code in https://github.com/protocolbuffers/protobuf/tree/main/python/google/protobuf/pyext

The future is the Python/upb bindings in https://github.com/protocolbuffers/upb/tree/main/python  You might notice that we no longer ship the old extension in our PyPI packages. Ever since 4.21 we are shipping the upb-based extension instead.

Unfortunately upb's user-level C++ API is still in its infancy. It lives in https://github.com/protocolbuffers/upb/tree/main/protos, but it is not mature enough yet for us to offer it generally to users. But that is the way forward.

**Comment by fahhem** [comment]
So there's no interest in the working solution while we wait for the future solution? I've literally done all the work already for internal use, and am willing to port it to upstream.

**Comment by arthur-tacca** [comment]
@haberman Is the plan for upb's C++ API to replace the current C++ protobuf API entirely? Or would it just be used in interoperability contexts like this?

**Comment by haberman** [comment]
> So there's no interest in the working solution while we wait for the future solution?

If it was a minimally-intrusive change that did not increase our support burden, we could review a change. However based on the discussion in https://github.com/protocolbuffers/protobuf/pull/11669 it looks like your design relies on insertion points, which we are strongly moving away from.

I would echo the comment on https://github.com/protocolbuffers/protobuf/pull/11669 which suggests engaging with us early if you are interested in contributing a behavior or API change. I understand the frustration if you have something that's working for you already, but we need to make sure that contributions align with our intended future directions.

> Is the plan for upb's C++ API to replace the current C++ protobuf API entirely? Or would it just be used in interoperability contexts like this?

There are a lot of unknowns in this space. The existing C++ API has a lot of legacy warts that we would like to deprecate. However it also has a very large body of existing users, and migrating those users to something new is a very large task.
