### ISSUE TITLE
Maven Version protobuf-java-util package In M2 Repositories Wrong

### ISSUE THREAD

**Issue by vanducvo** [protocolbuffers/protobuf#11719]
**What version of protobuf and what language are you using?**
Version: 
```xml
<groupId>com.google.protobuf</groupId>
<artifactId>protobuf-java-util</artifactId>
<version>[3.10.0,3.99)</version>
```
Language: Java

**What operating system (Linux, Windows, ...) and version?**
MacOS Big Sur 11.3.1
**What runtime / compiler are you using (e.g., python version or gcc version)**
OpenJDK Runtime Environment Zulu17.30+15-CA
**What did you do?**
1. Create Maven project have dependencies
```xml
<groupId>com.google.protobuf</groupId>
<artifactId>protobuf-java-util</artifactId>
<version>[3.10.0,3.99)</version>
```
2. Run command
```shell
mvn clean package
```
3. Version resolved is: `3.22.0-RC1`
4. See error:
```
Failed to collect dependencies at com.google.protobuf:protobuf-java-util:jar:3.22.0-RC1: Failed to read artifact descriptor for com.google.protobuf:protobuf-java-util:jar:3.22.0-RC1: com.google.protobuf:protobuf-parent:pom:3.22.0-RC1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**What did you expect to see**
Not resolved version 3.22.0-RC1.
**What did you see instead?**
Not resolved version 3.21.12.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
The version 3.22.0-RC1 is not have in web: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util.
But in xml metadata it have: https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java-util/maven-metadata.xml
**Anything else we should know about your project / environment**
No.

**Comment by shubhati** [comment]
I am facing the same issue

**Comment by phani-chakradhar-tech** [comment]
> Could not find com.google.protobuf:protobuf-parent:3.22.0-RC1.
      > Could not resolve com.google.protobuf:protobuf-java:3.22.0-RC1.
I'm also facing same.

**Comment by phani-chakradhar-tech** [comment]
Updating the gradle dependency to 3.21.12 solves my issue.
https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/3.21.12

But using 3.+ is resolving to 3.22.0-RC1, which is not exist in maven central.

**Comment by travisdowns** [comment]
This is an urgent issue that will break everyone's build who uses java-protobuf and a version range like 3.+ or [3.5, 4.0), etc.

**Comment by deannagarcia** [comment]
I now see a 3.22.0-RC1 version of protobuf-java and protobuf-java-util on Maven. I think that was just a synchronization issue in Maven.

A 3.22.0-RC1 version of protobuf-parent was missing, and I am releasing it right now.

**Comment by travisdowns** [comment]
3.22.0-**rc-1** is there: https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-parent/3.22.0-rc-1/

Note the - in `rc-1`. It seems like the referring project is looking for 3.22.0-**rc1** (no dash). Is that the problem?

**Comment by jlogsdon** [comment]
Looks that way. Blaming this on a synchronization issue seems like a deflection, this release simply failed to complete correctly.

```
   > Could not resolve com.google.protobuf:protobuf-javalite:{strictly [3.0, 4.0[}.
     Required by:
         project :_redacted-internal-project_
      > Could not resolve com.google.protobuf:protobuf-javalite:3.22.0-RC1.
         > Could not parse POM https://jcenter.bintray.com/com/google/protobuf/protobuf-javalite/3.22.0-RC1/protobuf-javalite-3.22.0-RC1.pom
            > Could not find com.google.protobuf:protobuf-parent:3.22.0-RC1.
      > Could not resolve com.google.protobuf:protobuf-javalite:3.22.0-RC1.
         > Could not parse POM https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-javalite/3.22.0-RC1/protobuf-javalite-3.22.0-RC1.pom
            > Could not find com.google.protobuf:protobuf-parent:3.22.0-RC1.
```

**Comment by travisdowns** [comment]
It seems like [the pom](https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java-util/3.22.0-RC1/protobuf-java-util-3.22.0-RC1.pom) for protobuf-java-util refers to protobuf-parent as a dependecy, using RC1:

```
<parent>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protobuf-parent</artifactId>
  <version>3.22.0-RC1</version>
</parent>
```

However, the parent uses rc-1 not RC1 as the version suffix, as noted above.

**Comment by lee-corey** [comment]
Having same problem with below error.
```
Could not resolve com.google.protobuf:protobuf-parent:3.22.0-RC1
```
How to fix this?

**Comment by travisdowns** [comment]
> How to fix this?

You can wait for the authors to fix it, but in the meantime it's probably just easiest to pin java-protobufs to an earlier version like `3.21.12` which doesn't have this problem (how you do this varies based on your project build setup).

**Comment by deannagarcia** [comment]
Sorry for this delay, I see that the release candidate suffix is wrong and I'm releasing 3.22.0-RC1 for protobuf-parent and protobuf-bom right now.

In the meantime you can pin to an old version, and to avoid issues like this in the future you can exclude release candidates.

**Comment by deannagarcia** [comment]
3.22.0-RC1 is out for both protobuf-parent and protobuf-bom now. Please let me know if you see any more issues.

**Comment by deannagarcia** [comment]
Closing this for now, feel free to reopen if you see any more issues.
