### ISSUE TITLE
Empty metadata summary breaks buildroot compilation

### ISSUE THREAD

**Issue by BoreaWolf** [protocolbuffers/protobuf#11723]
**What version of protobuf and what language are you using?**
Version: v4.21.12
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux: Ubuntu 22.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.10.6

**What did you do?**
While trying to generate the buildroot package of python-protobuf v4.21.12 on a linux machine, the process unsuccessfully terminates due to the `summary` metadata field being empty.

**What did you expect to see**
A correct package configuration and following compilation.

**What did you see instead?**
Error related to the `summary` metadata.

**Comment by shaod2** [comment]
Can you give more details of the error you got?
