### ISSUE TITLE
22.0rc1 : can't compile with -fno-rtti anymore

### ISSUE THREAD

**Issue by hzeller** [protocolbuffers/protobuf#11742]
I am [currently trying](https://github.com/chipsalliance/verible/pull/1665) the new 22.0RC1 version.

In our environment we try to make sure that code can be compiled without rtti, however this is not possible anymore with the latest protobuf version. Looks like this is due to the new JSON subsystem ?

Protobuf library is used in a [WORKSPACE](https://github.com/chipsalliance/verible/pull/1665/files#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5) file in a bazel project.

Here is where the compiles fails message when [compiling with `-fno-rtti`](https://github.com/chipsalliance/verible/actions/runs/4059607679/jobs/6987841723#step:10:85)

```
external/com_google_protobuf/src/google/protobuf/json/internal/untyped_message.cc: In member function 'absl::Status google::protobuf::json_internal::UntypedMessage::InsertField(const google::protobuf::json_internal::ResolverPool::Field&, T)':
external/com_google_protobuf/src/google/protobuf/json/internal/untyped_message.cc:542:41: error: cannot use 'typeid' with '-fno-rtti'
  542 |                         number, typeid(T).name(), slot.index()));
```

Hopefully the ues of RTTI can be worked around before the release.

**Comment by mcy** [comment]
We do not explicitly support building with `-fno-rtti`, and we do not have tests for this. If you can produce a PR that fixes this issue, we will take it, but we cannot guarantee this will remain stable over time.

The shape of PR I would accept is one that adds the following function to `port.h`:

```cc
template <typename T>
absl::string_view TypeName() {
  // TBD
}
```

and uses it in place of `typeid(T).name()`.
