### ISSUE TITLE
gcc12.2 compiling error

### ISSUE THREAD

**Issue by risemeup1** [protocolbuffers/protobuf#11791]
**What version of protobuf and what language are you using?**
Version: v21.12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc12.2
**What did you do?**
I use docker base image 11.7.0-devel-ubuntu18.04 and manually upgrade the gcc version from gcc8 to gcc12.2 ，This error is raised at compile time

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/62429225/216531255-da2b23ef-ef31-43ba-ba97-b5dc5a6ddede.png">

In file included from /usr/local/gcc-12.2/include/c++/12.2.0/set:60,
                 from /home/workspace/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc:41:
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_tree.h: In instantiation of ‘static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(_Const_Link_type) [with _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; _Const_Link_type = const std::_Rb_tree_node<const google::protobuf::FieldDescriptor*>*]’:
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_tree.h:2117:47:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; key_type = const google::protobuf::FieldDescriptor*]’
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_tree.h:2170:4:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = const google::protobuf::FieldDescriptor* const&; _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>]’
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_set.h:512:25:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(const value_type&) [with _Key = const google::protobuf::FieldDescriptor*; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator = std::_Rb_tree<const google::protobuf::FieldDescriptor*, const google::protobuf::FieldDescriptor*, std::_Identity<const google::protobuf::FieldDescriptor*>, google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare, std::allocator<const google::protobuf::FieldDescriptor*> >::const_iterator; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other = std::allocator<const google::protobuf::FieldDescriptor*>; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key> = __gnu_cxx::__alloc_traits<std::allocator<const google::protobuf::FieldDescriptor*>, const google::protobuf::FieldDescriptor*>::rebind<const google::protobuf::FieldDescriptor*>; typename _Allocator::value_type = const google::protobuf::FieldDescriptor*; value_type = const google::protobuf::FieldDescriptor*]’
/home/workspace/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc:97:54:   required from here
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/gcc-12.2/include/c++/12.2.0/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare&, const google::protobuf::FieldDescriptor* const&, const google::protobuf::FieldDescriptor* const&>’ evaluates to false
CMakeFiles/libprotoc.dir/build.make:582: recipe for target 'CMakeFiles/libprotoc.dir/home/workspace/build/third_party/protobuf/src/extern_protobuf/src/google/

**Comment by n0099** [comment]
How did you fix this?

**Comment by klaussilveira** [comment]
@risemeup1 don't leave us hanging. :stuck_out_tongue:

**Comment by Qengineering** [comment]
Either downgrade to GCC 10.x or use clang.
