### ISSUE TITLE
[PHP] JSON serialization fails for negative durations

### ISSUE THREAD

**Issue by nesk** [protocolbuffers/protobuf#11792]
**What version of protobuf and what language are you using?**
Version: `3.19.4` and tested with `21.12` for this issue
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Tested on **Debian Buster** (Docker) and **macOS Ventura 13.01**

**What runtime / compiler are you using (e.g., python version or gcc version)**
`protoc` binary from [the Github releases](https://github.com/protocolbuffers/protobuf/releases)

**What did you do?**
Serializing a `Duration` with negative seconds fails [despite being authorized](https://github.com/protocolbuffers/protobuf/blob/373d8225af42e9dbfc01431b46ff48be0eabae90/src/google/protobuf/duration.proto#L104-L106):

```php
$d = new \Google\Protobuf\Duration();
$d->setSeconds(3600);
$d->serializeToJsonString(); // OK
$d->setSeconds(-3600);
$d->serializeToJsonString(); // Error occurred during JSON serialization: bad duration
```

However, deserialization works:

```php
$d = new \Google\Protobuf\Duration();
$d->mergeFromJsonString('"-3600s"')
$d->getSeconds(); // returns `-3600`
```

**What did you expect to see**

Serialization shouldn't fail and should return `"-3600s"`.

**What did you see instead?**

```
Fatal error: Uncaught Exception: Error occurred during JSON serialization: bad duration in /path/to/project/index.php:9
Stack trace:
#0 /path/to/project/index.php(9): Google\Protobuf\Internal\Message->serializeToJsonString()
#1 {main}
  thrown in /path/to/project/index.php on line 9
```

**Comment by tforesti** [comment]
This issue is fixed on 3.22.0 and later.
For those who cannot upgrade to this version like us, I found a crappy workaround, this error occur here :
https://github.com/protocolbuffers/protobuf/blob/v21.12/php/ext/google/protobuf/php-upb.c#L3999-L4002
So add a "fake“ nanosecond to have a negative nanosecond too : `-3600.000000001s` or `->setNanos(-1)`
