### ISSUE TITLE
`optional` is not working, it doesn't allow me to set a field to null

### ISSUE THREAD

**Issue by yingshaoxo** [protocolbuffers/protobuf#11790]
As I tested out, the Python, Javascript/Typescript, Rust, Dart, they all support or about to support optional filed to null.

Why Java and Cpp can't do that?

https://github.com/grpc/grpc-java/issues/9868

**Comment by v-chernyshev** [comment]
I'm not a maintainer, but everything works as designed here, `null` values are not allowed. `optional` instructs the compiler to generate the `has*` methods for the corresponding fields.

**Comment by yingshaoxo** [comment]
Then why `python,javascript,rust`, they support `null`?

If `java` do not support it, then nobody would use `java` to communicate with `python,javascript/typescript,rust,dart` by using `grpc`

**Comment by v-chernyshev** [comment]
Null fields do not exist in protobuf. Getters, for example, should never return null, irrespective of the language. Please note that a similar question has already been asked [before](https://github.com/protocolbuffers/protobuf/issues/8781) and the official advice is to rely on the `clear*` methods to get a consistent behaviour.

**Comment by yingshaoxo** [comment]
Could you guys make a simple logic check like this:

```
def a_set_function(value):
    if value == null:
        call clear* method, so that property won't exist in the response (return value)
```

And in the client side, the program will do this:

```
if protocol optional definition fields not exists in the return value, it sets that field to null
```

**Comment by esorot** [comment]
This is working as intended. Feel free to create a PR with your intended changes where we can review.

**Comment by wirekang** [comment]
This is so weird. Some language implementations treat `optional` as `nullable` but some is not.
