### ISSUE TITLE
Weakref to protobuf objects broken in protobuf v4+

### ISSUE THREAD

**Issue by azhou95** [protocolbuffers/protobuf#11834]
It seems that with the latest versions of protobuf (4.+) we can no longer [create weak references](https://docs.python.org/3/extending/newtypes.html#weakref-support) to protobuf objects. This used to work with previous versions e.g. 3.20

The motivation is to be able to implement the flyweight design pattern for protobuf objects.

**What version of protobuf and what language are you using?**
Version: 4.21.9
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9

**What did you do?**

For example:
```
import sample_pb2
from weakref import WeakValueDictionary
wvd = WeakValueDictionary()
wvd["test"] = sample_pb2.Sample()
```

**What did you expect to see**
Expect to see a weakref dict with the proto object as a value

**What did you see instead?**
TypeError: cannot create weak reference to 'Sample' object

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by ashleystendel** [comment]
Hi! 
I am seeing the same issue too. I was wondering if it were possible to take a look? We are seeing higher memory usages in our projects since we can't use WeakValueDictionary. 
Thanks!

**Comment by Redoubts** [comment]
comment
