### ISSUE TITLE
Using a dictionary in a message and generated code

### ISSUE THREAD

**Issue by devmikew** [protocolbuffers/protobuf#11833]
**What version of protobuf and what language are you using?**
PackageReference Include="Google.Protobuf" Version="3.22.0-rc2" 
C#

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What runtime / compiler are you using (e.g., python version or gcc version)**
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

**What did you do?**
There seems to be a (strange) problem , or a misunderstanding, with Prortbuf messages.

All docs I've read says that if you want a Dictionary in your message then you should declare a sub message and use that sub message as the data type of the dictionary. Eg:

message CallContext
{
  message MapData
  {
    map<string, string> map = 1;
  }
  repeated MapData attributes = 1;
  map<string, string> it = 2;
  repeated string string_list = 3;
  repeated uint32 uint_list = 4;
}

Ive also read that you cant use a Map field directly in a message if you want to have it repeated.

However, the strange part, the MapField<TKey, TValue> already implements:
    IDeepCloneable<MapField<TKey, TValue>>,
    IDictionary<TKey, TValue>,
    ICollection<KeyValuePair<TKey, TValue>>,
    IEnumerable<KeyValuePair<TKey, TValue>>,
    IEnumerable,
    IEquatable<MapField<TKey, TValue>>,
    IDictionary,
    ICollection,
    IReadOnlyDictionary<TKey, TValue>,
    IReadOnlyCollection<KeyValuePair<TKey, TValue>>
i.e, a list itself.

Thus in the above message one ends up with a Repeated field containing a MapField<TKey, TValue>. I.e, a dictionary as the contents of the outer(the repeated field) list.

However 'it' in the above message generates, IMO, the correct code. I.e, a dictionary at the top level of the message as generated by protoc.

The following is the generated code(minus some code not pertinent):

  public sealed partial class CallContext : pb::IMessage<CallContext>
...
  {
...
    /// <summary>Field number for the "attributes" field.</summary>
...
    public pbc::RepeatedField<global::Shared.Contracts.Protos.CallContext.Types.MapData> Attributes {
      get { return attributes_; }
    }
...
    public pbc::MapField<string, string> It {
      get { return it_; }
    }
...
    public pbc::RepeatedField<string> StringList {
      get { return stringList_; }
    }
...
    public pbc::RepeatedField<uint> UintList {
      get { return uintList_; }
    }
...
  }
The generated MapData:
  public sealed partial class MapData : pb::IMessage<MapData>
...
  {
...
	/// <summary>Field number for the "map" field.</summary>
...
	public pbc::MapField<string, string> Map {
	  get { return map_; }
	}
...
  }
  
So what is the 'truth'?

**Comment by devmikew** [comment]
I forgot to add the following doc reference https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-maps

**Comment by esorot** [comment]
`All docs I've read says that if you want a Dictionary in your message then you should declare a sub message and use that sub message as the data type of the dictionary.` 
What's mentioned in the docs, is that if you want to have a repeated map<k,v> you would have to create a submessage, then make that message repeated. 
A little unclear about your exact question here. If you could clarify that would appreciated.

**Comment by devmikew** [comment]
I know what is in the docs.
However im saying that the docs are wrong or the code for a Map is wrong.
As i said  MapField<TKey, TValue> already implements:
IDeepCloneable<MapField<TKey, TValue>>,
IDictionary<TKey, TValue>,
ICollection<KeyValuePair<TKey, TValue>>,
IEnumerable<KeyValuePair<TKey, TValue>>,
IEnumerable,
IEquatable<MapField<TKey, TValue>>,
IDictionary,
ICollection,
IReadOnlyDictionary<TKey, TValue>,
IReadOnlyCollection<KeyValuePair<TKey, TValue>>
i.e, a list itself.

Therefore there is no need to wrap it in a repeated field.

Im using, successfully, a message that contains a Map. "It acts like a duck, quacks like a duck, therefore is a duck". In this case a duck is a dictionary, a list, a collection with no need to wrap it with a repeated field.

**Comment by jskeet** [comment]
No, I'm afraid you are just wrong. There's a difference between a dictionary and a list of dictionaries - where the latter is what a repeated map in proto would represent. Note that sticking to just C#, `Dictionary<TKey, TValue>` implements `IEnumerable<KeyValuePair<TKey,TValue>>` - but is still not a list of dictionaries.

> All docs I've read says that if you want a Dictionary in your message then you should declare a sub message and use that sub message as the data type of the dictionary.

No, that's only if you want a *repeated* map, because "repeated map" is not supported in proto.

If you believe the docs say a custom type is needed for a *single* dictionary, please quote that part of the docs.

**Comment by jskeet** [comment]
Closing as stale - hopefully my clarification has made this sufficiently clear now.
