### ISSUE TITLE
Grammar does not allow adjacent strings.

### ISSUE THREAD

**Issue by JakeWharton** [protocolbuffers/protobuf#1186]
But the compiler happily consumes and concatenates them in both proto2 and proto3.

```
strLit = ( "'" { charValue } "'" ) |  ( '"' { charValue } '"' )
```

yet `test_extra_interfaces.proto` has:

``` proto
  option experimental_java_builder_interface =
      "com.google.protobuf.ExtraInterfaces.HasStringValueBuilder"
      "<Proto1, Builder>";
```

**Comment by haberman** [comment]
Another one for @LisaFC.

**Comment by elharo** [comment]
Grammar is wrong here, need to update

**Comment by devjgm** [comment]
It looks like the [grammar spec](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec) needs to be updated. We may consider open-sourcing these specs so folks can send us PRs to fix issues like this. Otherwise, @Logofile may be able to get to this at some point.

**Comment by Logofile** [comment]
The description was updated to:
```
strLit = strLitSingle { strLitSingle }
strLitSingle = ( "'" { charValue } "'" ) | ( '"' { charValue } '"' )
```
