### ISSUE TITLE
Grammar does not allow more than one parenthesized identifier.

### ISSUE THREAD

**Issue by JakeWharton** [protocolbuffers/protobuf#1187]
Defined as

```
option = "option" optionName  "=" constant ";"
optionName = ( ident | "(" fullIdent ")" ) { "." ident }
```

with

```
ident = letter { letter | unicodeDigit | "_" }
fullIdent = ident { "." ident }
```

yet in `unittest_custom_options.proto` there's:

``` proto
message VariousComplexOptions {
  option (.protobuf_unittest.complex_opt1).foo = 42;
  option (protobuf_unittest.complex_opt1).(.protobuf_unittest.quux) = 324;
  option (.protobuf_unittest.complex_opt1).(protobuf_unittest.corge).qux = 876;
  option (protobuf_unittest.complex_opt1).foo4 = 99;
  option (protobuf_unittest.complex_opt1).foo4 = 88;
  option (complex_opt2).baz = 987;
  option (complex_opt2).(grault) = 654;
  option (complex_opt2).bar.foo = 743;
  option (complex_opt2).bar.(quux) = 1999;
  option (complex_opt2).bar.(protobuf_unittest.corge).qux = 2008;
  option (complex_opt2).(garply).foo = 741;
  option (complex_opt2).(garply).(.protobuf_unittest.quux) = 1998;
  option (complex_opt2).(protobuf_unittest.garply).(corge).qux = 2121;
  option (ComplexOptionType2.ComplexOptionType4.complex_opt4).waldo = 1971;
  option (complex_opt2).fred.waldo = 321;
  option (complex_opt2).barney = { waldo: 101 };
  option (complex_opt2).barney = { waldo: 212 };
  option (protobuf_unittest.complex_opt3).qux = 9;
  option (complex_opt3).complexoptiontype5.plugh = 22;
  option (complexopt6).xyzzy = 24;
}
```

half of which have multiple parenthesized identifiers.

**Comment by haberman** [comment]
@LisaFC looks like this is worth investigating.

By the way, @JakeWharton do you have your own `.proto` file parser? Would be curious to know the use case for that.

**Comment by JakeWharton** [comment]
We have systems which need to parse, read, and write protos dynamically at runtime in Java. We also ship our own "compiler" and Java runtime which generates files that are much more terse than protoc's Java format but not as crazy as the choices made by JavaNano. The latter is targeted at Android.

**Comment by anandolee** [comment]
How about
optionName = ( ident | bracedFullIdent ) { "." ( ident | bracedFullIdent ) }
bracedFullIdent = "(" ["."] fullIdent ")"

**Comment by elharo** [comment]
correct spec

**Comment by Logofile** [comment]
I'm working on correcting the spec based on the suggestion from @anandolee and the updates already made to the proto3 spec.

**Comment by elharo** [comment]
@Logofile what's the status on this? Issue should remain open until fixed. (and that bot really needs to be turned off. It's actively rude to contributors.)

**Comment by Logofile** [comment]
I've sent a change to @anandolee to review.

**Comment by Logofile** [comment]
The change has been committed internally. We push internal change to the external site about once a week.
