### ISSUE TITLE
Severe presentation issues in C++ documentation

### ISSUE THREAD

**Issue by tweenk** [protocolbuffers/protobuf#11919]
Documentation has recently been redirected from developers.google.com to protobuf.dev. This has caused a massive regression in usability:

- The main page of the documentation is structured by namespace and file - the overview is gone
- All links that reference a code entity are broken
- There is no longer a summary TOC on the side
- Very long, hard to read lines
- The very top of the page is obscured by the header
- Incorrect vertical alignment of return types in class summaries
- Low contrast color scheme that breaks accessibility guidelines (yellow on gray)
- Code block formatting is gone
- Font sizes are random
- Vertical spacing is random, there's excessive space around lists and paragraphs but no space between classes
- and many more.

Please consider restoring the old documentation site until the new one is usable.

**Comment by tweenk** [comment]
Another regression: clicking anchor links no longer copies them.

**Comment by undisputed-seraphim** [comment]
Yes, it's been frustrating. The new website is clearly not ready.

**Comment by Logofile** [comment]
I'm working with the Eng team on a different doc generation process that should resolve these issues. I'll update this issue when we've pushed out a new version of the C++ API docs.

**Comment by devjgm** [comment]
@Logofile how's the new doc generation process coming along?

**Comment by Logofile** [comment]
C++ is the first language that we're creating a new generation pipeline for (partly because C++ is central to much of protobuf, but also partly because it's got so many problems in the current presentation layer).

**Comment by Logofile** [comment]
This is still on our radar, but the person involved in API doc generation has been out on extended leave. We have made some improvments on the generated output (not ideal, but better than waiting until the generation process is fixed).

**Comment by alexolog** [comment]
It's been three months, has there been any progress?

**Comment by Logofile** [comment]
Unfortunately, no progress as of right now. We'll be looking at Q1 planning in the next week or two, and will assess this along with other docs tasks for priority.

**Comment by alexolog** [comment]
The issue should remain active
