### ISSUE TITLE
Segmentation fault (core dumped) when importing in python after pytorch_lightning

### ISSUE THREAD

**Issue by louismartin** [protocolbuffers/protobuf#11934]
**What version of protobuf and what language are you using?**
Version: protobuf==3.20.0 (required by sentencepiece: https://github.com/google/sentencepiece/blob/master/python/src/sentencepiece/sentencepiece_pb2.py)
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.5 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.15

**What did you do?**
```
python -c "import pytorch_lightning; from google.protobuf import descriptor"
```

**What did you expect to see**
Program exits successfully

**What did you see instead?**
```
$ python -c "import pytorch_lightning; from google.protobuf import descriptor"
Segmentation fault (core dumped)
```

Changing the import order does not cause the problem:
`python -c "from google.protobuf import descriptor; import pytorch_lightning"`
I also tried with torch but the problem doesn't appear either: `python -c "import torch; from google.protobuf import descriptor"`

**Anything else we should know about your project / environment**
protobuf==3.20.0 (required by sentencepiece: https://github.com/google/sentencepiece/blob/master/python/src/sentencepiece/sentencepiece_pb2.py)
pytorch-lightning==1.9.0
python 3.8.15
Ubuntu 20.04.5 LTS

**Comment by esorot** [comment]
Wasn't able to reproduce the problem. Try upgrading to pytorch-lightning=1.9.1
