### ISSUE TITLE
Cannot generate protocol buffer file to go code

### ISSUE THREAD

**Issue by aditya113141** [protocolbuffers/protobuf#11936]
I am having issues with generating the protocol buffer file in Golang. I couldn't find any instruction to generate in golang. protoc --help shows instructions only for languages in the picture. My version is libprotoc 3.21.12

![Screenshot (67)](https://user-images.githubusercontent.com/56213335/218713717-c9896c95-c05e-41bf-838b-01c91f5cc249.png)

**Comment by deannagarcia** [comment]
Unfortunately our compiler does not support go. Check out https://github.com/golang/protobuf for golang protobuf support.
