### ISSUE TITLE
Java protoc plugin always generates OuterClasses for services with a single defined RPC

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [protocolbuffers/protobuf#11961]
**What version of protobuf and what language are you using?**
Version: 3.21.12
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Mac OS Ventura 13.1, M2 arch

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java openjdk 19.0.2

**What did you do?**
I have a `.proto` file with a service with a single RPC: https://github.com/reify-tanner-stirrat/api/blob/1170-add-java-multiple-files/authzed/api/v1/watch_service.proto#L1-L20

I also have a `.proto` file with a service with multiple RPCs: https://github.com/reify-tanner-stirrat/api/blob/1170-add-java-multiple-files/authzed/api/v1/permission_service.proto#L4-L36

I ensured that `option java_multiple_files = true` was present in both files.

I ran the build step to generate the classes based on this proto.

**What did you expect to see**
I expected to see `WatchService.java` in the output files.

**What did you see instead?**
Instead I have `WatchServiceOuterClass.java` in the output files. It isn't clear from the structure of the proto why I would have one and not the other, and that's frustrating to me as a developer, because I want to have a simple mental rule/model for how the contents of a proto file will map to the generated code.

**Anything else we should know about your project / environment**
If this is expected behavior, and there actually is a simple rule for how a service definition gets turned into a java class, I'd like to see that documented somewhere. Otherwise it results in me having to manually inspect the generated JAR files which is a pain in the butt.

**Comment by deannagarcia** [comment]
You are correct that if you have `option java_multiple_files = true`, you should see `WatchService.java` and not `WatchServiceOuterClass.java` in the output files.

Can you provide more details on how the files were generated so I can reproduce? If I clone the repo, how can I run the build step?
