### ISSUE TITLE
Release 3.22.0 jar no longer contains pom files

### ISSUE THREAD

**Issue by jradcliff** [protocolbuffers/protobuf#11976]
**What version of protobuf and what language are you using?**

Version: v3.22.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
n/a

**What did you do?**
1. Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.0/protobuf-java-3.22.0.jar
2. Search contents of `/META-INF`

**What did you expect to see**
I expected to see `pom.properties` and `pom.xml` under `/META-INF/maven/com.google.protobuf/protobuf-java/`, as in past releases.

**What did you see instead?**
The `/META-INF` directory is missing `maven` altogether.

**Anything else we should know about your project / environment**
This is a change since `3.12.0`.

```
Downloads 10021$ jar -tvf protobuf-java-3.22.0.jar | grep META-INF
     0 Fri Feb 01 00:00:00 EST 1985 META-INF/
    93 Fri Feb 01 00:00:00 EST 1985 META-INF/MANIFEST.MF
Downloads 10022$ jar -tvf protobuf-java-3.12.0.jar | grep META-INF
   849 Fri May 15 23:44:52 EDT 2020 META-INF/MANIFEST.MF
     0 Fri May 15 16:44:52 EDT 2020 META-INF/
     0 Fri May 15 16:44:52 EDT 2020 META-INF/maven/
     0 Fri May 15 16:44:52 EDT 2020 META-INF/maven/com.google.protobuf/
     0 Fri May 15 16:44:52 EDT 2020 META-INF/maven/com.google.protobuf/protobuf-java/
   142 Fri May 15 23:44:52 EDT 2020 META-INF/maven/com.google.protobuf/protobuf-java/pom.properties
  5564 Fri May 15 20:26:22 EDT 2020 META-INF/maven/com.google.protobuf/protobuf-java/pom.xml
```

The library for Google Ads API used the `pom.properties` file for recording the protobuf version used in gRPC headers and logs. If this information is now captured elsewhere in .jar files, could you let me know where?

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.0/protobuf-java-util-3.22.0.pom

Maybe I found related problem. `protobuf-java-util` does not have `protobuf-java` dependency.

**Comment by deannagarcia** [comment]
We have changed our release process to now make use of [bazel build rules](https://github.com/bazelbuild/rules_jvm_external/blob/master/docs/api.md#java_export) to build the Maven jar. Unfortunately, that did have the side effect of not putting the pom file into the jar and rather publishing it separately on Maven. You should be able to access the same information from the pom file we are still publishing to maven.

I am currently working on the issue where `protobuf-java-util` doesn't have a `protobuf-java` dependency and you should expect to see a release with that fix this week.

**Comment by liff** [comment]
Should [protobuf-kotlin](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-kotlin/3.22.0/protobuf-kotlin-3.22.0.pom) also depend on protobuf-java? It [used to](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-kotlin/3.21.12/protobuf-kotlin-3.21.12.pom).

**Comment by deannagarcia** [comment]
It should, thanks for letting me know about the issue I will get that fixed as well. (similarly for kotlin-lite)
