### ISSUE TITLE
C# possible incorrect implementation of CreateJsonFieldMap causes JSON data corruption during parse

### ISSUE THREAD

**Issue by mgravell** [protocolbuffers/protobuf#11987]
Relevant code: https://github.com/protocolbuffers/protobuf/blob/6d776dfed52e36a58f318c0ba3acc93445ed710e/csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs#L117-L126

(proposed fix shown at bottom)

Problem: I believe the *intent* is that the json names should take precedence, but the *reality* is that later fields can corrupt this, in particular when names overlap. The following is arguably a pathological case, but consider:

``` protobuf
syntax = "proto3";

package EvilJson;

message Oof {
  int32 a = 1 [json_name = 'b'];
  int32 b = 2 [json_name = 'a'];
  int32 c = 3 [json_name = 'd'];
}
```

with example:

``` c#
using EvilJson;
using Google.Protobuf;

var msg = new Oof { A = 123, B = 456, C = 789 };
var json = JsonFormatter.Default.Format(msg);
Console.WriteLine(json); // { "b": 123, "a": 456, "d": 789 } as expected

var clone = Oof.Parser.ParseJson(json);

Write(msg);
Write(clone);

static void Write(Oof oof)
{
    Console.WriteLine();
    Console.WriteLine($"A={oof.A}");
    Console.WriteLine($"B={oof.B}");
    Console.WriteLine($"C={oof.C}");
}
```

which has output:

``` txt
{ "b": 123, "a": 456, "d": 789 }

A=123
B=456
C=789

A=0
B=456
C=789
```

Here field 1 claims `a` then `b`, then field 2 *also* claims `b` then `a`. This causes parse to not match format, since field 2 gets everything and field 1 gets nothing.

Proposed fix:

``` c#
foreach (var field in fields)
{
    map[field.Name] = field;
}
foreach (var field in fields)
{
    map[field.JsonName] = field;
}
```

this would ensure that `JsonName` claims always take priority over `Name` claims, which I *believe* is the intended implementation.

---

Unrelated: maybe `protoc` should emit a warning if a `JsonName` conflicts with a `Name` / `JsonName` of a **different** field on the same message, or any reserved name.

(I'm happy to contribute a PR with the proposed fix and tests)

**Comment by JamesNK** [comment]
Java does the same thing: https://github.com/protocolbuffers/protobuf/blob/6d776dfed52e36a58f318c0ba3acc93445ed710e/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1465-L1476 - C# copied a lot from Java so that's not surprising.

Golang appears to prefer the JSON name:
https://github.com/protocolbuffers/protobuf-go/blob/246af0d153cae8ef4e2915a8d212167ad0751985/encoding/protojson/decode.go#L177-L181

**Comment by jskeet** [comment]
Yes, this looks like a bug to me. I don't know whether protoc catches the situation where there's genuine ambiguity (either with duplicate json_name annotations for different fields, or a json_name that conflicts with an un-annotated field). But where there's a clearly unambiguous mapping (e.g. with your pathological case) it would make sense to follow that. It looks like we probably need to fix this in both C# and Java, and *possibly* do something in protoc.
