### ISSUE TITLE
docs: add notice of move to C++14 toolchain

### ISSUE THREAD

**Issue by johanbrandhorst** [protocolbuffers/protobuf#11998]
The latest release (v3.22.0 or v22.0) appears to have moved the minimum supported C++ toolchain to C++14. This wasn't noted in [the release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0) as far as I can tell. It required explicitly specifying the toolchain to fix build errors in a repository I maintain. It would be nice if the protobuf bazel target itself could specify a minimum supported toolchain version, but I don't know if this is possible.

**Comment by fowles** [comment]
We announced it in https://protobuf.dev/news/2022-08-03/#c11-support, but we failed to add a release note.  Sorry about that.

**Comment by zhangskz** [comment]
Thanks, this has been added to the release notes for 22.0: https://github.com/protocolbuffers/protobuf/releases/tag/v22.0

Note that the release notes state "[Protobuf News](https://protobuf.dev/news/) may include additional announcements or pre-announcements for upcoming changes." but we will propagate breaking changes like dropping C+11 over to release notes as well.
