### ISSUE TITLE
cmake no longer builds on version 22.0

### ISSUE THREAD

**Issue by nemith** [protocolbuffers/protobuf#12016]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux in docker
root@buildkitsandbox:/src/protobuf-22.0# uname -a
Linux buildkitsandbox 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

```
gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**What did you do?**
1. Donwloaded protobuf-22.tar.gz
2. Extracted it to /src/protobuf-22.0
3. Ran cmake 

**What did you expect to see**

cmake to complete after checks

**What did you see instead?**

```
root@buildkitsandbox:/src/protobuf-22.0# cmake . -DCMAKE_CXX_STANDARD=14
-- 
-- 4.22.0.0
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at cmake/gtest.cmake:7 (message):
  Cannot find third_party/googletest directory that's needed to build tests.
  If you use git, make sure you have cloned submodules:

    git submodule update --init --recursive

  If instead you want to skip tests, run cmake with:

    cmake -Dprotobuf_BUILD_TESTS=OFF

Call Stack (most recent call first):
  CMakeLists.txt:342 (include)


-- Configuring incomplete, errors occurred!
See also "/src/protobuf-22.0/CMakeFiles/CMakeOutput.log".
See also "/src/protobuf-22.0/CMakeFiles/CMakeError.log".
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Turning of build tests just errors on the next depenency

```
root@buildkitsandbox:/src/protobuf-22.0#     cmake -Dprotobuf_BUILD_TESTS=OFF .
-- 
-- 4.22.0.0
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Warning at cmake/abseil-cpp.cmake:28 (message):
  protobuf_ABSL_PROVIDER is "module" but ABSL_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:345 (include)


CMake Error at third_party/utf8_range/CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /src/protobuf-22.0/third_party/abseil-cpp

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/src/protobuf-22.0/CMakeFiles/CMakeOutput.log".
See also "/src/protobuf-22.0/CMakeFiles/CMakeError.log".
```

Those directories in third_party do exist.

**Anything else we should know about your project / environment**

**Comment by nemith** [comment]
Looks like third-party is missing from the archive. Only the sub-directories are there. 

```
oot@buildkitsandbox:/src/protobuf-22.0# find third_party/
third_party/
third_party/googletest
third_party/abseil-cpp
third_party/zlib.BUILD
third_party/jsoncpp
third_party/utf8_range
third_party/utf8_range/main.c
third_party/utf8_range/.bazelrc
third_party/utf8_range/ascii.cpp
third_party/utf8_range/utf8_corpus_dir
third_party/utf8_range/utf8_corpus_dir/utf8_corpus_kuhn.txt
third_party/utf8_range/utf8_corpus_dir/utf8_corpus_durst.txt
third_party/utf8_range/lemire-neon.c
third_party/utf8_range/workspace_deps.bzl
third_party/utf8_range/utf8_range.h
third_party/utf8_range/boost.cpp
third_party/utf8_range/README.md
third_party/utf8_range/range2-neon.c
third_party/utf8_range/range-sse.c
third_party/utf8_range/.gitignore
third_party/utf8_range/CONTRIBUTING.md
third_party/utf8_range/range-neon.c
third_party/utf8_range/range2-sse.c
third_party/utf8_range/CMakeLists.txt
third_party/utf8_range/UTF-8-demo.txt
third_party/utf8_range/fuzz
third_party/utf8_range/fuzz/utf8_fuzzer.dict
third_party/utf8_range/fuzz/utf8_validity_fuzzer.cc
third_party/utf8_range/fuzz/BUILD.bazel
third_party/utf8_range/lemire-sse.c
third_party/utf8_range/range-avx2.c
third_party/utf8_range/.github
third_party/utf8_range/.github/workflows
third_party/utf8_range/.github/workflows/bazel_tests.yml
third_party/utf8_range/.github/workflows/cmake_tests.yml
third_party/utf8_range/utf8_validity.h
third_party/utf8_range/cmake
third_party/utf8_range/cmake/utf8_range-config.cmake.in
third_party/utf8_range/utf8_validity_test.cc
third_party/utf8_range/lookup.c
third_party/utf8_range/WORKSPACE
third_party/utf8_range/LICENSE
third_party/utf8_range/utf8_validity.cc
third_party/utf8_range/naive.c
third_party/utf8_range/utf8_to_utf16
third_party/utf8_range/utf8_to_utf16/main.c
third_party/utf8_range/utf8_to_utf16/iconv.c
third_party/utf8_range/utf8_to_utf16/Makefile
third_party/utf8_range/utf8_to_utf16/naive.c
third_party/utf8_range/lemire-avx2.c
third_party/utf8_range/BUILD.bazel
third_party/utf8_range/utf8_range-config.cmake
third_party/utf8_range/CMakeFiles
third_party/utf8_range/third_party
third_party/utf8_range/third_party/abseil-cpp
third_party/jsoncpp.BUILD
third_party/BUILD.bazel
```

**Comment by deannagarcia** [comment]
It is intended behavior that the code from subrepositories is not in the archive we release. You should be using the `-Dprotobuf_BUILD_TESTS=OFF` flag and you can use the `-Dprotobuf_ABSL_PROVIDER=package` flag to use your own abseil package.

**Comment by nemith** [comment]
This is not the case with 21.x with the -all package.  abseil may be a new dependency but googletests were packaged before.  Is this a change in direction?

**Comment by deannagarcia** [comment]
Somewhat. Before our distribution files were created with autotools and now are using `git archive` since we turned down autotools. That also created a difference in what distribution files we release: you can see we no longer have language-specific distribution files.

The addition of the extra subrepo/dependency (abseil) has caused us to reevaluate some of how we are dealing with dependencies. Specifically, we want users to install dependencies on their own instead of relying on us to package them. This will also allow more customization in which version of our dependencies to use.

**Comment by nemith** [comment]
Last thing I want in protoc is customization.  :)   But i get it.  There may be some documentation that needs updating.

**Comment by mmjkelso** [comment]
The CMake build instructions could be updated: they still refer to protobuf-cpp-[VERSION].tar.gz , and following them fails when it hits the empty third_part/abseil  directory.

**Comment by Baloads** [comment]
I have encountered this issue as well following the README docs, but running cmake on Windows. 

Is there any guidance about how to handle the situation while documentation is being updated? I glean from this post that I can either go with 21.x or pursue handling each missing dependency myself by using the `-Dprotobuf_ABSL_PROVIDER=package` flag. Are those my two options?

**Comment by mmjkelso** [comment]
FYI I got it working by using -Dprotobuf_ABSL_PROVIDER=package, and pointing -Dabsl_DIR at the subdirectory within the Abseil install directory that had the abslConfig.cmake file . In my case it was .../install/x64/debug/lib/cmake/absl , where .../install/x64/debug was the CMAKE_INSTALL_PREFIX used when making Abseil .

Which feels a bit kludgy - there might be some intended way of doing it which is better.

**Comment by Baloads** [comment]
> FYI I got it working by using -Dprotobuf_ABSL_PROVIDER=package, and pointing -Dabsl_DIR at the subdirectory within the Abseil install directory that had the abslConfig.cmake file . In my case it was .../install/x64/debug/lib/cmake/absl , where .../install/x64/debug was the CMAKE_INSTALL_PREFIX used when making Abseil .
> 
> Which feels a bit kludgy - there might be some intended way of doing it which is better.

@mmjkelso Thanks for the information, I was going down this path too, but to no avail. So I downloaded the Asbeil 20230125.2 release and used cmake to configure and build the package. I created a separate build directory for Asbeil and ran the following:

`cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=rootDir\abseil-cpp-20230125-build\install\ -DBUILD_TESTING=OFF rootDir\abseil-cpp-20230125.2\`

then 

`cmake --build rootDir\abseil-cpp-20230125-build --target install`

None seemingly out of the ordinary, my CMAKE_INSTAL_PREFIX path is successfully populated with a /lib and /include directories. However, when I execute my protobuf cmake command:

`cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=rootDir\protobuf-22.2-build\install\ -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_ABSL_PROVIDER=rootDir\abseil-cpp-20230125-build\install\ -Dabsl_DIR=rootDir\abseil-cpp-20230125-build\install\lib\cmake\absl\ rootDir\protobuf-22.2\`

I encounter the error described here: https://github.com/abseil/abseil-cpp/releases/tag/20230125.2

I have also tried building the asbeil master branch with same result. At this point I'm double checking my entire process and questioning whether I missed something important during the Asbeil build step.

**Comment by maxost90** [comment]
I can't get it working unfortunately.
What i did:
1. downloaded [Protobuf ](https://github.com/protocolbuffers/protobuf/archive/refs/tags/v23.0.zip)
2. extracted to D:\src\protobuf
3. downloaded [Abseil ](https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.2.zip)
4. extracted to D:\src\protobuf\third_party\abseil-cpp
5. run CMake

My CMake command:
`cmake -G "Visual Studio 17 2022" -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_ABSL_PROVIDER=package  -DCMAKE_PREFIX_PATH=D:\src\protobuf\third_party\abseil-cpp\ D:\src\protobuf\`

Result:
`-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
--
-- 23.0.0
CMake Error at cmake/abseil-cpp.cmake:36 (find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:339 (include)`
