### ISSUE TITLE
Please detect support for large-file-support related build flags and set them automatically

### ISSUE THREAD

**Issue by Allen-Webb** [protocolbuffers/protobuf#12034]
When building for 32-bit architectures like ARM on Linux, off_t is not big enough to represent large files. This leads to system calls like stat and seek failing when called on a large file. If the proper build flags are set, the system calls are replaced with alternatives that support large files.

While this likely won't have an immediate impact on the maximum serialized protobuf, it ought to make the error messages better with respect to large files, and remove an obstacle toward supporting larger maximum protobufs.

**Comment by acozzette** [comment]
Can you say more about what this change would look like? We have not thought a lot about large files on 32-bit architectures. One thing to note is that even if we do this, we're probably not going to support a larger maximum protobuf size any time soon. That would be a big change affecting all languages and would require a lot of thought and planning, and I'm not even sure that it's a feature we would want to pursue.

**Comment by Allen-Webb** [comment]
There is a good explanation of with an example from wireshark on how to enable large file support with CMake: https://stackoverflow.com/a/61343213/1549171

It pretty much just detects if certain compile-time flags are available and if they are, sets them. The consequences of this are off_t is a different size for 32-bit architectures and different system calls are used like lseek64 instead of lseek and fstat64 instead of fstat.
