### ISSUE TITLE
Can't access custom FieldOptions in Python

### ISSUE THREAD

**Issue by upcFrost** [protocolbuffers/protobuf#12049]
**What version of protobuf and what language are you using?**
Version: 4.22.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9.7

**What did you do?**
I'm trying to write a custom plugin for protoc using python. 
After I parse serialized `plugin_pb2.CodeGeneratorRequest`, the `options` container on fields is always empty.
Instead, the FieldOption is being stored inside the `options._unknown_fields` properly of the field.

**What did you expect to see**
Field options being populated

**What did you see instead?**
Parser failing to decode/identify field options

Sample proto file:
```protobuf
syntax = "proto3";
import "google/protobuf/descriptor.proto";
package test;

extend google.protobuf.FieldOptions {
  bool my_opt = 50002;
}

message Msg {
  string data = 1 [(my_opt) = true];
}
```

**Comment by acozzette** [comment]
This most likely indicates that your plugin doesn't know about the custom options and is therefore treating them as unknown fields. If you have your plugin take a dependency on the generated code for `my_opt` then it should be able to parse that option successfully.

**Comment by upcFrost** [comment]
Custom options (`my_opt` in this case) are declared in the proto file and come inside the same request, I can see them on the FileDescriptorProto level. They are parsed by the same `plugin_pb2.CodeGeneratorRequest.FromString` call as the rest of the request. 

Standard python plugin somehow manages to put options inside the message descriptor, but apparently it parses the request, registers all extensions, and then re-parses it. I'm not 100% sure I can do this in pure python. Probably it's possible to create `FieldDescriptor` from each `FieldDescriptorProto`, but this doesn't feel like a correct way of doing this. 

>If you have your plugin take a dependency on the generated code for my_opt

There is no generated code at that point, only the protoc request. Otherwise it will require first generating classes using the standard generator, and then re-generating same classes using the custom generator.

**Comment by acozzette** [comment]
Why does the plugin need to know about this option? I was assuming it configured some aspect of the plugin's behavior, but if the plugin doesn't know about it until runtime then presumably that is not the case. If you just need to include the option in the generated code then you can include the serialized bytes without needing to interpret them.

If for some reason you do need to interact with the fully-parsed options, I think the way to do it would be to do the equivalent of `DynamicMessage` from C++ and Java. I'm less familiar with Python but I believe the Python way to do it is with `message_factory.GetMessageClass(descriptor)`, which allows you to generate a message based on a descriptor which is not known until runtime. If you then parse the options using that dynamic message (built from descriptors from the CodeGeneratorRequest), then you should be able to see the custom options there.

**Comment by upcFrost** [comment]
>Why does the plugin need to know about this option

To give more context, I'm trying to write an alternative codegen plugin to generate proto-plus code. So far it all works well except for custom options. For my current case, option values will be static, but I still need to know them beforehand to generate the code properly.

So far the only working solution I've found is kinda similar to the standard codegen - parse, register, re-parse.

```python3
req = plugin_pb2.CodeGeneratorRequest.FromString(data)
for file in req.proto_file:
    for ext in file.extension:
        descriptor_pb2.FieldOptions.RegisterExtension(FieldDescriptor(...))
req = plugin_pb2.CodeGeneratorRequest.FromString(data)
```

I'll try to check if it'd look better with dynamic messages, but I guess in the end the mechanism would be pretty similar to just re-parsing the proto file.

**Comment by upcFrost** [comment]
To summarize, I guess my issue is resolved, i'll stick with the parse-register-reparse solution as it makes the plugin code easy to understand (with some comments added).

Still, imo from the user perspective it's not immediately obvious why some things like messages are being parsed properly on the first run, and some other things like extensions require some extra steps, so it honestly feels like a bug, or at least an undocumented design decision.
