### ISSUE TITLE
3.22.0 Kotlin output has dependencies not provided by protobuf-kotlin, BUT protobuf-java

### ISSUE THREAD

**Issue by alwyn** [protocolbuffers/protobuf#12056]
Version: v3.22.0
Language: Kotlin
OS: Arch Linux
JDK:  Version 17

Steps to reproduce:
1) Clone https://github.com/alwyn/protobuf-issue as a test project.  This project has only a .proto file.
2) ./gradlew clean build   -> Success
3) Change the protobufVersion variable in build.gradle.kts to "3.22.0".
4) ./gradlew clean build   -> Fails

What is wrong?
1) 3.22.0 creates code that depends on protobuf-java library to compile, despite already having protobuf-kotlin.
2) 3.22.0 adds errorprone annotations to the Kotlin code.

What I would like to see?
1) No dependency on protobuf-java to build.
2) No hard dependency on errorprone since a consumer may not want to even use it.  Thus add a way to disable it.

Attaching the output files for the different failures.

[Failure.txt](https://github.com/protocolbuffers/protobuf/files/10829080/Failure.txt)

**Comment by deannagarcia** [comment]
Sorry for this new breakage and thanks for the report.

protobuf-kotlin has always had a dependency on protobuf-java but unfortunately the dependency in the pom file got removed in 3.22.0. I have already sent a fix for that (https://github.com/protocolbuffers/protobuf/pull/12009) and it will be released in 22.1 this week. 

The errorprone dependency creeped in, I am removing it now and that fix will also be in the release this week.

**Comment by bitsydarel** [comment]
It seems that now, if a project has dependencies on both protobuf-kotlin and protobuf-java, the project build is failing due to a duplicate classes error.

**Comment by bitsydarel** [comment]
#14830
