### ISSUE TITLE
Complicated versioning schema between various languages

### ISSUE THREAD

**Issue by georgthegreat** [protocolbuffers/protobuf#12062]
As I see, at the time the following rules apply:

* C++ protobuf releases version numbered `{major}.{minor}`
* Python protobuf adds `4.` prefix to the versions (so git tag `v21.12` becomes [4.21.12](https://pypi.org/project/protobuf/4.21.12/) on pypi).
* Java add `3.` prefix to the versions (hence git tag `v21.12` becomes [3.21.12](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.21.12).

In order to correspond to various versioning schemas, git tags also get multiplied, i. e. [v22.0](https://github.com/protocolbuffers/protobuf/tree/v22.0), [v3.22.0](https://github.com/protocolbuffers/protobuf/tree/v3.22.0) and [v4.22.0](https://github.com/protocolbuffers/protobuf/tree/v4.22.0) do actually point to the same commit [a847a8d](https://github.com/protocolbuffers/protobuf/commit/a847a8dc4ba1d99e7ba917146c84438b4de7d085).

Is there any rationale behind this schema?
Do you have plans to unify the versioning?

**Comment by fowles** [comment]
This was a deliberate shift to allow language bindings to evolve independently.  This was announced at https://protobuf.dev/news/2022-05-06/#versioning

The alternatives were 

* bump major versions when *any* language needed a breaking change 
* not bump major versions when *some* language did have a breaking change.
* never making breaking changes

All of these were unacceptable for various reasons, so here we are.

We should give this a dedicated space in our docs (not just the announcement section), so I will leave this bug open to track that.

**Comment by georgthegreat** [comment]
The problem is that making versioning independent actually did not achieved this.

Code generation is still being done by C++ version of protoc which get released according to C++ versioning schema (i. e. _every release is a breaking change_).

Python bindings for protobuf still depend on a pyext (and have harsh performance if build without one).
As I am maintaining protobuf updates in our monorepo, I would appreciate a doc section on this indeed.

**Comment by Logofile** [comment]
https://protobuf.dev/support/version-support/ covers our versioning schema. If this doesn't fully address the things raised in this issue, please reopen this and provide a delta so that I know what you'd like to see added/changed. Thanks.

**Comment by Logofile** [comment]
That output seems correct, yes. Were you expecting something different? If so, what and why?

**Comment by georgthegreat** [comment]
@Logofile, it is out internal problem, everything is correct with the protobuf.
However it would be more convenient for us, if `protoc` binary was produced by the linker, and `protoc-${version}` would be symlinked to it.
