### ISSUE TITLE
Provide access to unknown field information when parsing text format

### ISSUE THREAD

**Issue by greg-dennis** [protocolbuffers/protobuf#12061]
**What language does this apply to?**
No syntax wouldn't change, but the text format parsers and the representation of unknown fields for all languages would be changed.

**Describe the problem you are trying to solve.**

I am trying to give code the ability to introspect unknown field information after parsing a proto text format. Currently, that information is at most logged when parsing text format, whereas when ingesting wire format the unknown fields are available for introspection.

**Describe the solution you'd like**

I would like unknown field structs to be augmented with fields for the field name and value as read from the text proto and for this information to be populated when parsing text protos when unknown fields are encountered. The "value" could be strongly-typed to the one that the text proto parsers currently "guess"; although perhaps it should be less strongly-typed to one of {string, list<string>, map<string, object>}.

**Describe alternatives you've considered**

A mode in which a text proto can be parsed without a schema into a map/dictionary.

**Additional context**

None

**Comment by fowles** [comment]
This would require keeping two distinct flavors of "unknown fields" (text and number based) on all of our platforms.  It would further lead to ambiguities if both are set and the name and number were for the same field (had one known the schema).  Given the volume of ambiguities to resolve and that it would need to be implemented in many languages I don't think this is a feature we are likely to add

**Comment by greg-dennis** [comment]
@fowles, what do you think about providing access to the unknown fields from a getter on the TextFormat Parser object? This would not be the same "unknown field" type that's part of messages today; it would be the one used internally to the TextFormat parser, augmented to also contain the value of the field. Thoughts?

**Comment by fowles** [comment]
That is a very interesting proposal, that I would be willing to entertain on a per language basis.

**Comment by greg-dennis** [comment]
It was determined that this would not be a good idea, because it would essentially allow textproto to function like an unstructured markup language. There is other work in motion that should better address my original use case.
