### ISSUE TITLE
Fast conversion RepeatedScalarFieldContainer to numpy array

### ISSUE THREAD

**Issue by harmankaya** [protocolbuffers/protobuf#12076]
**What language does this apply to?**
this is about the generated code change for python.

**Describe the problem you are trying to solve.**
Fast conversion from RepeatedScalarFieldContainer to numpy array

**Describe the solution you'd like**
I want a fast conversion from RepeatedScalarFieldContainer to a numpy array. I have several messages which contain repeated data int32 array. Example of how I convert to a numpy array:

`data_array = np.array(person.data)`

This takes around ~0.03s to convert on my machine, but it can be up to a million arrays that need to be converted to numpy, which takes a long time.

**Describe alternatives you've considered**
I am having some trouble finding other alternatives. If there is, it would be nice to know.

**Comment by harmankaya** [comment]
Hi, are there any updates?

**Comment by harmankaya** [comment]
@deannagarcia @anandolee , are there any updates on this issue? I saw it is similar as this: https://github.com/protocolbuffers/protobuf/issues/10930

**Comment by thisch** [comment]
Yes, this issue should remain active.

**Comment by harmankaya** [comment]
remain active

**Comment by harmankaya** [comment]
remain active

**Comment by harmankaya** [comment]
Remain active

**Comment by harmankaya** [comment]
please let this be open
