### ISSUE TITLE
The behavior that emit fields with default values in JSON encoding has discrepancy between proto2 optional and proto3 optional

### ISSUE THREAD

**Issue by toga4** [protocolbuffers/protobuf#12079]
Related to https://github.com/golang/protobuf/issues/1525.

**What version of protobuf and what language are you using?**
Version: v3.21.12
Language: Go/C++/Java

**What operating system (Linux, Windows, ...) and version?**
Mac

**What runtime / compiler are you using (e.g., python version or gcc version)**
Go: 1.20.1
C++: Apple clang version 14.0.0 (clang-1400.0.29.202)
Java: openjdk version "19.0.2"

**What did you do?**

Marshal proto message contains optional fields to json.

proto2:
```protobuf
syntax = "proto2";

package com.example.foo;

option go_package = "example.com/main";

option java_package = "com.example.foo";
option java_outer_classname = "FooProtos2";

message Foo2 {
  optional string foo = 1;
}
```

proto3:
```protobuf
syntax = "proto3";

package com.example.foo;

option go_package = "example.com/main";

option java_package = "com.example.foo";
option java_outer_classname = "FooProtos3";

message Foo3 {
  optional string foo = 1;
}
```

Generate sources:
```
protoc *.proto --go_out . --go_opt paths=source_relative --java_out=app/src/main/java --cpp_out=.
```

Go:
```go
package main

import (
	"fmt"

	"google.golang.org/protobuf/encoding/protojson"
)

func main() {
	marshaller := &protojson.MarshalOptions{EmitUnpopulated: true}

	foo2 := &Foo2{}
	b2, _ := marshaller.Marshal(foo2)
	fmt.Printf("%s\n", b2)

	foo3 := &Foo3{}
	b3, _ := marshaller.Marshal(foo3)
	fmt.Printf("%s\n", b3)
}

```

C++:
```c++
#include <google/protobuf/util/json_util.h>
#include "foo_proto2.pb.h"
#include "foo_proto3.pb.h"

int main()
{
  google::protobuf::util::JsonPrintOptions options;
  options.always_print_primitive_fields = true;

  std::string json2;
  com::example::foo::Foo2 foo2;
  MessageToJsonString(foo2, &json2, options);
  std::cout << json2 << std::endl;

  std::string json3;
  com::example::foo::Foo3 foo3;
  MessageToJsonString(foo3, &json3, options);
  std::cout << json3 << std::endl;
}
```

Java:
```java
package com.example.foo;

import com.example.foo.FooProtos2.Foo2;
import com.example.foo.FooProtos3.Foo3;
import com.google.protobuf.util.JsonFormat;

public class Main {
    public static void main(String[] args) throws Exception {
        JsonFormat.Printer printer = JsonFormat.printer().includingDefaultValueFields().omittingInsignificantWhitespace();

        Foo2 foo2 = Foo2.newBuilder().build();
        System.out.println(printer.print(foo2));

        Foo3 foo3 = Foo3.newBuilder().build();
        System.out.println(printer.print(foo3));
    }
}
```

Run All.

**What did you expect to see**

```
{"foo":null}
{"foo":null}
```

**What did you see instead?**

```
{"foo":null}
{}
```

This behavior seems to be due to that proto3 optional is implemented as oneof with a single type, but there is discrepancy between proto2 and proto3. Is this intended behavior?

**Comment by divad** [comment]
+1 I'd love it if messagetodict/json would include unset optional fields, e.g. in python the field would be in the dict/json but would be set to `None` (null).

The docs (https://protobuf.dev/programming-guides/proto3/#specifying_field_rules) say:

> the field is unset, and will return the default value.

Except, with message to json does not return the default value, it returns nothing at all!

**Comment by toga4** [comment]
This issue significantly impacts my use of grpc-gateway. 

Specifically, in Go code written with proto3, I expect that optional fields, when unset, should return null in the JSON response. However, currently, these fields are not included in the JSON output at all.
This behavior causes confusion among API users and hinders data processing on the front end. 

I would greatly appreciate guidance or updates from the Protocol Buffers team to resolve this issue, as it aligns with the specifications of protobuf.
