### ISSUE TITLE
Generated CPP for Parsing Boolean Fields Causes Compiler Warning C4800

### ISSUE THREAD

**Issue by sgh-msg** [protocolbuffers/protobuf#12112]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
OS: Windows 11 (22000.1574)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Compiler: MSVC v143 (with Cmake)

**What did you do?**
1. Define a protobuf with a `bool` field
2. Generate the cpp using `protoc --cpp_out`
3. Generated `.cc` file's `_InternalParse` method will contain the following line: `_impl_.[FIELD NAME]_= ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);` which will cause [Compiler Warning C4800](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4800?view=msvc-170) "Implicit conversion from 'type' to bool. Possible information loss"

**What did you expect to see**
Non-implicit casting to the boolean field value. Something to the effect of the following change to `parse_function_generator.cc` would be ideal:
```
switch (wiretype) {
  case WireFormatLite::WIRETYPE_VARINT: {
    switch (field->type()) {
      case FieldDescriptor::TYPE_ENUM: {
        format.Set("enum_type",
                    QualifiedClassName(field->enum_type(), options_));
        ...
        }
        break;
      }
      case FieldDescriptor::TYPE_BOOL: {
        format(
            "$uint64$ val = ::$proto_ns$::internal::ReadVarint64(&ptr);\n"
            "CHK_(ptr);\n");
        if (field->is_repeated() || field->real_containing_oneof()) {
          format(
              "$msg$_internal_$put_field$(static_cast<bool>(val));\n");
        } else {
          if (internal::cpp::HasHasbit(field)) {
            format("_Internal::set_has_$name$(&$has_bits$);\n");
          }
          format(
              "$msg$$field$ = static_cast<bool>(val);\n");
        }
        break;
      }
      default: {
        std::string size = (field->type() == FieldDescriptor::TYPE_INT32 ||
                            field->type() == FieldDescriptor::TYPE_SINT32 ||
                            field->type() == FieldDescriptor::TYPE_UINT32)
                                ? "32"
                                : "64";
        ...
```

**Anything else we should know about your project / environment**
Possibly a duplicate of https://github.com/protocolbuffers/protobuf/issues/3572 which was closed without comment. Precedent for this kind of cleanup includes https://github.com/protocolbuffers/protobuf/pull/10353
Thanks for taking a look!

**Comment by fowles** [comment]
If you would like to send a PR for this, we would be happy to take a look
