### ISSUE TITLE
Erros in python setup build

### ISSUE THREAD

**Issue by erelsgl** [protocolbuffers/protobuf#12120]
**What version of protobuf and what language are you using?**

Version: libprotoc 3.21.12
Language: Python
Cmake: version 3.26.0-rc5

**What operating system (Linux, Windows, ...) and version?**

Windows 11 22H2

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.10.10

**What did you do?**
1. `D:\vcpkg\vcpkg install protobuf protobuf:x64-windows`
2. Added the folder containing protoc.exe `D:\vcpkg\installed\x64-windows\tools\protobuf` to the path.
3. `protoc --version`  (got 3.21.12)
4. `git clone https://github.com/protocolbuffers/protobuf.git`
5. `cd protobuf\python`
6. `python setup.py build`

**What did you expect to see**

Successful build.

**What did you see instead?**

```
PS D:\protobuf\python> python setup.py build
C:\Users\Erel Segal-Halevi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\setuptools\dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
  warnings.warn(msg, SetuptoolsDeprecationWarning)
running build
running build_py
Generating google/protobuf/map_unittest_pb2.py...
google/protobuf/unittest.proto:1662:49: Option "debug_redact" unknown. Ensure that your proto definition file imports the proto which defines the option.
google/protobuf/map_unittest.proto:35:1: Import "google/protobuf/unittest.proto" was not found or had errors.
google/protobuf/map_unittest.proto: "ForeignMessage" is not defined.
google/protobuf/map_unittest.proto: "ForeignMessage" is not defined.
google/protobuf/map_unittest.proto: "TestAllTypes" is not defined.
google/protobuf/map_unittest.proto: "TestAllTypes" is not defined.
google/protobuf/map_unittest.proto: "TestRequired" is not defined.
google/protobuf/map_unittest.proto: "ForeignMessage" is not defined.
```

**Comment by erelsgl** [comment]
I installed using `vckpg` as instructed here: https://github.com/protocolbuffers/protobuf/blob/895edc4e316f6ff00fecd17264bb3e2768217353/src/README.md and this is the version I got. How can I tell vcpkg to give me version 4.22?

**Comment by deannagarcia** [comment]
Unfortunately `vcpkg` hasn't upgraded to 4.22 https://github.com/microsoft/vcpkg/blob/master/ports/protobuf/vcpkg.json so you can't yet. It appears they are waiting on upgrading another dependency.

I do think I figured out your original problem though. When you were using protoc 3.21.12, did you run on main? You should be using the `.proto`/runtime files from the `21.x` branch to match the protoc version. I think that option (`debug_redact`) was added between 21.12 and 22.0.

**Comment by erelsgl** [comment]
Sorry, I did not understand - how exactly can I get the " .proto/runtime files from the 21.x branch"?

**Comment by deannagarcia** [comment]
You can either download the source code from [our release](https://github.com/protocolbuffers/protobuf/releases/tag/v21.12) or you can clone the 21.x branch.
