### ISSUE TITLE
ruby: Provide aarch64-linux pre-compiled native gems

### ISSUE THREAD

**Issue by chadlwilson** [protocolbuffers/protobuf#12144]
**What language does this apply to?**
ruby

**Describe the problem you are trying to solve.**

Current as of `3.22.0` pre-compiled extensions are only provided for `x86-linux` and `x66_64-linux` (see on [RubyGems](https://rubygems.org/gems/google-protobuf/versions/3.22.0-x86_64-linux)). This adds complexity and slowness to Gem installs on this platform which is a shame.

**Describe the solution you'd like**

It'd be great to have the aarch64 extensions available to simplify/speed up installing the gems on aarch64/arm64 hosts, similar as what seems to be done for [the Python wheels](https://pypi.org/project/protobuf/4.22.0/#files) or `arm64-darwin`.

https://github.com/protocolbuffers/protobuf/blob/49589719e241a83d82ce67139006d2a9be391fce/ruby/Rakefile#L109-L113

**Describe alternatives you've considered**

The default install compiles from source which works fine (most of the time!), but is not ideal.

**Additional context**
**Edit**: Likely duplicate of closed issue #8682 so this can be closed as a duplicate in favour of that if it is re-opened, or alternate approach decided.

**Comment by deannagarcia** [comment]
We are currently working on adding a pre-compiled aarch64-linux gem, and we intend to release it in a patch release of v22 in the next few weeks.

**Comment by chadlwilson** [comment]
Fantastic - thank you @deannagarcia !
