### ISSUE TITLE
Automatic-Module-Name entry missing in release 3.22.1

### ISSUE THREAD

**Issue by xazap** [protocolbuffers/protobuf#12175]
I upgraded from protobuf-java 3.21.9 to 3.22.0 and found that module name "com.google.protobuf" was no longer resolving in my module-info. This is due to the "Automatic-Module-Name" entry missing from `META-INF/MANIFEST.MF`. Can this please be restored? The entry in 3.21.x was:

`Automatic-Module-Name: com.google.protobuf`

This might be related to #12017 where it is noticed that the OSGi entries are also missing from the manifest.

**Comment by deannagarcia** [comment]
I think this is the same issue as https://github.com/protocolbuffers/protobuf/issues/12017, so I'm closing as a duplicate. Working on a fix now, should get a fix released soon.
