### ISSUE TITLE
Protobuf cmake build on windows fails on requiring absl targets which are "not in the export set".

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#12185]
(This issue prevents grpc from upgrading to protobuf's 22.x release)

When protobuf is added as a grpc dependency (via cmake's `add_subdirectory`), it seems that the protobuf cmake build is misconfigured on windows and the build fails with the following error:
```
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_absl_check" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_absl_log" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_algorithm" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_base" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_bind_front" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_bits" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "absl_btree" that is not in the export set.
...
other similar errors follow.
``` 

(On linux the cmake builds seems to work just file). Is there something special about how the absl dependency is added to protobuf on windows that could cause this?

**Comment by jtattermusch** [comment]
CC @veblush 
@deannagarcia @mkruskal-google @perezd  can you please take a look? This one of the long list of issue that are preventing gRPC from upgrading to protobuf 22.x

**Comment by acozzette** [comment]
There is some [logic](https://github.com/protocolbuffers/protobuf/blob/2dd03a570a385dbee141c657e5be0ac33061dfc7/cmake/abseil-cpp.cmake#L40) specific to MSVC that could be related. Is there a way we could reproduce the error?

**Comment by jtattermusch** [comment]
I have some initial evidence that his behavior might be cmake version dependent. The original reproduction was with cmake 3.10 and when I tried with cmake 3.25, I could no longer reproduce. So it seems that this issue might not be a hard blocker for for protobuf upgrade (since our windows workers now have cmake 3.25), but we should investigate this behavior anyway (just not as urgently).

I will post an update here to confirm that I can no longer reproduce on cmake 3.25 once I double check my experiments.

**Comment by jtattermusch** [comment]
At this point I'm 99% sure that the issue can only be reproduced on older cmake versions (I tried cmake 3.10) and things work fine with newer cmake (I tried 3.25). So this issue is no longer a blocker for grpc's upgrade to 22.x (since our windows workers have new-enough cmake and our tests pass), but we should investigate which cmake version is that last one that's broken and perhaps that would tell us what the issue is (I suspect it's some change in how cmake handles exporting targets?).

I can look into figuring out the last broken cmake version later, but currently I'm too busy trying to finish grpc's protobuf upgrade.

**Comment by mkruskal-google** [comment]
FWIW we only support cmake 3.25+

**Comment by gmcchessney** [comment]
I'm getting the same errors with CMake 3.26.4 when using FetchContent to include the 1.55.0 release of gRPC. I also tried cloning the gRPC repository and running CMake build directly in the repository and that succeeds.

```cmake_minimum_required(VERSION 3.26)
project (my_project)

include(FetchContent)
FetchContent_Declare(
  gRPC
  GIT_REPOSITORY https://github.com/grpc/grpc
  GIT_TAG        v1.55.0
)
set(FETCHCONTENT_QUIET OFF)
FetchContent_MakeAvailable(gRPC)

**Comment by AliHadiOzturk** [comment]
I'm getting the same error with CMake 3.25.1 and 1.55.1 version of grpc. I tried with FetchContent and adding as a submodule both give the same error.

**Comment by AliHadiOzturk** [comment]
> I've worked around this issue with gRPC and FetchContent by setting `set(ABSL_ENABLE_INSTALL ON)` before `FetchContent_Declare`.

This is working. Thank you. Save me a lot of time 💯

**Comment by oneengineer** [comment]
set(ABSL_ENABLE_INSTALL ON)  is till the solution, meeting the same error when compiling grpc. But protobuf itself compiling doesn't trigger such error

**Comment by RGAA-Software** [comment]
> Another option is to disable install with
> 
> ```
> set(protobuf_INSTALL OFF)
> set(utf8_range_ENABLE_INSTALL OFF)
> ```

You are the HERO!!!

**Comment by HO-COOH** [comment]
This is still happening today. Does this really get fixed?
