### ISSUE TITLE
So many annoying undefined reference to protobuf interfaces, is there lacking definitions for them???

### ISSUE THREAD

**Issue by richen666** [protocolbuffers/protobuf#12213]
**What version of protobuf and what language are you using?**
Version: v3.12.4
Language: C++
"Please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem?" I think it may not useful for me.

**What operating system (Linux, Windows, ...) and version?**
Linux 5.19.0-35-generic, Ubuntu

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Python 3.10.6

**What did you do?**
1.sudo apt-get install **libprotoc-dev protobuf-compiler libprotobuf-dev**
![image](https://user-images.githubusercontent.com/71740544/224552891-7fa334bb-e984-460f-978d-97f1ead161fc.png)
So I use the default version of the system, and **protoc is also 3.12.4**  (so there is no conflict between protoc and protobuf).
![image](https://user-images.githubusercontent.com/71740544/224554880-ce85b413-81d9-49db-ad80-fa8482069623.png)
![image](https://user-images.githubusercontent.com/71740544/224555033-13a893e3-2c26-43e8-9695-9899032734ad.png)

2. But when I compile my project, cmake give me annoying errors as follows:
****there are so many undefined references, I can't understand them. Please hele me!!!** I think that their definitions have been in system files in /usr/lib, but  why these errors?**

[cyf@vm ~/cpp-projects/muduo-protorpc]$ ./build.sh 
+ pwd
+ SOURCE_DIR=/home/cyf/cpp-projects/muduo-protorpc
+ BUILD_DIR=../build
+ BUILD_TYPE=debug
+ INSTALL_DIR=../debug-install-cpp11
+ MUDUO_DIR=/home/cyf/cpp-projects/muduo-protorpc/../build/debug-install-cpp11
+ mkdir -p ../build/protorpc-debug
+ cd ../build/protorpc-debug
+ cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=../debug-install-cpp11 -DMUDUO_PATH=/home/cyf/cpp-projects/muduo-protorpc/../build/debug-install-cpp11 /home/cyf/cpp-projects/muduo-protorpc
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cmake_build_type: debug
-- muduo_path: /home/cyf/cpp-projects/muduo-protorpc/../build/debug-install-cpp11
-- Muduo include /home/cyf/cpp-projects/build/debug-install-cpp11/include
-- Muduo lib /home/cyf/cpp-projects/build/debug-install-cpp11/lib
-- /home/cyf/cpp-projects/build/debug-install-cpp11/lib/libmuduo_base.a
-- /home/cyf/cpp-projects/build/debug-install-cpp11/lib/libmuduo_net.a
-- /home/cyf/cpp-projects/build/debug-install-cpp11/lib/libmuduo_protorpc_wire.a
-- /home/cyf/cpp-projects/build/debug-install-cpp11/lib/libmuduo_cdns.a
**-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0")  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (found version "3.12.4")** 
-- found tcmalloc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cyf/cpp-projects/build/protorpc-debug
+ make
/usr/bin/cmake -S/home/cyf/cpp-projects/muduo-protorpc -B/home/cyf/cpp-projects/build/protorpc-debug --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/cyf/cpp-projects/build/protorpc-debug/CMakeFiles /home/cyf/cpp-projects/build/protorpc-debug//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/cyf/cpp-projects/build/protorpc-debug'
make  -f muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/build.make muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/depend
make[2]: Entering directory '/home/cyf/cpp-projects/build/protorpc-debug'
cd /home/cyf/cpp-projects/build/protorpc-debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/cyf/cpp-projects/muduo-protorpc /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2 /home/cyf/cpp-projects/build/protorpc-debug /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/cyf/cpp-projects/build/protorpc-debug'
make  -f muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/build.make muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/build
make[2]: Entering directory '/home/cyf/cpp-projects/build/protorpc-debug'
[  1%] Building CXX object muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/gen.cc.o
cd /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 && g++  -I/home/cyf/cpp-projects/muduo-protorpc -I/home/cyf/cpp-projects/build/protorpc-debug -I/home/cyf/cpp-projects/build/debug-install-cpp11/include -g -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -Werror -Wconversion -Wno-unused-parameter -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wno-error=shadow -Wwrite-strings -march=native -std=c++11 -O0 -MD -MT muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/gen.cc.o -MF CMakeFiles/protoc-gen-rpc.dir/gen.cc.o.d -o CMakeFiles/protoc-gen-rpc.dir/gen.cc.o -c /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/gen.cc
[  2%] Building CXX object muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o
cd /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 && g++  -I/home/cyf/cpp-projects/muduo-protorpc -I/home/cyf/cpp-projects/build/protorpc-debug -I/home/cyf/cpp-projects/build/debug-install-cpp11/include -g -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -Werror -Wconversion -Wno-unused-parameter -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wno-error=shadow -Wwrite-strings -march=native -std=c++11 -O0 -MD -MT muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o -MF CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o.d -o CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o -c /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc
[  3%] Linking CXX executable ../../bin/protoc-gen-rpc
cd /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 && cp /home/cyf/cpp-projects/build/debug-install-cpp11/include/muduo/net/protorpc/rpcservice.proto rpcservice.proto
cd /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 && sed -i "/option cc_generic_services/d" rpcservice.proto
cd /home/cyf/cpp-projects/build/protorpc-debug/muduo/protorpc2 && /usr/bin/cmake -E cmake_link_script CMakeFiles/protoc-gen-rpc.dir/link.txt --verbose=1
g++ -g -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -Werror -Wconversion -Wno-unused-parameter -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wno-error=shadow -Wwrite-strings -march=native -std=c++11 -O0 CMakeFiles/protoc-gen-rpc.dir/gen.cc.o CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o -o ../../bin/protoc-gen-rpc   -L/home/cyf/cpp-projects/build/debug-install-cpp11/lib  -Wl,-rpath,/home/cyf/cpp-projects/build/debug-install-cpp11/lib: -lprotoc -lprotobuf -lpthread 
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/gen.cc.o: in function `google::protobuf::io::Printer::PrintInternal(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, char const*)':
/usr/include/google/protobuf/io/printer.h:304: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/gen.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::RpcGenerator::Generate(google::protobuf::FileDescriptor const*, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/gen.cc:79: undefined reference to `google::protobuf::compiler::cpp::StripProto(std::string const&)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/gen.cc:108: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/gen.cc.o:(.data.rel.ro._ZTVN6google8protobuf8compiler3cpp8muduorpc12RpcGeneratorE[_ZTVN6google8protobuf8compiler3cpp8muduorpc12RpcGeneratorE]+0x28): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::ServiceGenerator(google::protobuf::ServiceDescriptor const*, std::string const&, int)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:63: **undefined reference to `google::protobuf::SimpleItoa(int)'**
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateDeclarations(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:70: **undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateInterface(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:79: u**ndefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:88: u**ndefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:112: **undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateStubDefinition(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:121: u**ndefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o:/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:127: **more undefined references to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)' follow
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function** `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateMethodSignatures(google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::StubOrNon, google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:157: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:158: **undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:159: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:163: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:168: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'**
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateDescriptorInitializer(google::protobuf::io::Printer*, int)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:182: undefined reference to `google::protobuf::SimpleItoa(int)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:184: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateImplementation(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:191: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:216: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateNotImplementedMethods(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:237: undefined reference to `google::protobuf::SimpleItoa(int)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:238: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:239: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:241: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateCallMethod(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:254: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:266: undefined reference to `google::protobuf::SimpleItoa(int)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:267: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:268: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:272: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:280: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateGetPrototype(google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::RequestOrResponse, google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:292: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:295: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:299: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:310: undefined reference to `google::protobuf::SimpleItoa(int)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:311: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:313: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:318: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
/usr/bin/ld: CMakeFiles/protoc-gen-rpc.dir/cpp_service.cc.o: in function `google::protobuf::compiler::cpp::muduorpc::ServiceGenerator::GenerateStubMethods(google::protobuf::io::Printer*)':
/home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:333: undefined reference to `google::protobuf::SimpleItoa(int)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:334: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:335: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:336: undefined reference to `google::protobuf::compiler::cpp::ClassName(google::protobuf::Descriptor const*, bool)'
/usr/bin/ld: /home/cyf/cpp-projects/muduo-protorpc/muduo/protorpc2/cpp_service.cc:338: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/build.make:118: bin/protoc-gen-rpc] Error 1
make[2]: Leaving directory '/home/cyf/cpp-projects/build/protorpc-debug'
make[1]: *** [CMakeFiles/Makefile2:335: muduo/protorpc2/CMakeFiles/protoc-gen-rpc.dir/all] Error 2
make[1]: Leaving directory '/home/cyf/cpp-projects/build/protorpc-debug'
make: *** [Makefile:139: all] Error 2

**What did you expect to see**
Hope to compile completely and produce library for my own use.

**What did you see instead?**
I try all solutions mentioned from Internet, whether stackoverflow or google. For example: 
**Add -D_GLIBCXX_USE_CXX11_ABI=0, or -lprotoc -lprotobuf -lpthread**
![image](https://user-images.githubusercontent.com/71740544/224553905-ae570584-2957-417a-bb38-e48885c26045.png)
![image](https://user-images.githubusercontent.com/71740544/224554149-50c015d9-5691-420b-ad47-db34dab71437.png)

or **force to link static library libprotobuf.a.**
![image](https://user-images.githubusercontent.com/71740544/224554406-bfdca6fe-72f8-4622-a76f-c3caf8ad896d.png)

and other unuseful solutions.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
Protobuf 3.12.4 is a very old version and is out of our support window. Can you try to use a newer version and see if that fixes your problem?

**Comment by richen666** [comment]
But I want to know why protobuf in library from Ubuntu can’t be used to successfully compiled as a link library(then there so many undefined references). Is it only a problem from the ubuntu?
Thank for your advice, and I planed to use newer version.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送


________________________________
发件人: deannagarcia ***@***.***>
发送时间: Tuesday, March 14, 2023 1:51:03 AM
收件人: protocolbuffers/protobuf ***@***.***>
抄送: richen ***@***.***>; Author ***@***.***>
主题: Re: [protocolbuffers/protobuf] So many annoying undefined reference to protobuf interfaces, is there lacking definitions for them??? (Issue #12213)


Protobuf 3.12.4 is a very old version and is out of our support window. Can you try to use a newer version and see if that fixes your problem?

―

**Comment by deannagarcia** [comment]
I've never seen this error before, so I don't know what it is or if it's ubuntu specific and I will not be investigating since the version is outside of our support window.

**Comment by richen666** [comment]
Ok, thank you. I have a try for it.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月15日 00:16
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [protocolbuffers/protobuf] So many annoying undefined reference to protobuf interfaces, is there lacking definitions for them??? (Issue #12213)


I've never seen this error before, so I don't know what it is or if it's ubuntu specific and I will not be investigating since the version is outside of our support window.

―
