### ISSUE TITLE
Question: How to compile protobuf at runtime in Java?

### ISSUE THREAD

**Issue by siddhsql** [protocolbuffers/protobuf#12210]
I am dynamically fetching a protobuf in my application. I have the protobuf as a String. Now I want to compile it and get a Java class object corresponding to this protobuf. i.e., I am looking to do the equivalent of:

```
$ protoc --java_out=core/src/main/java -I../src
../src/google/protobuf/descriptor.proto
```

inside my Java application. I am looking for a method:

```
Class<> c = compileProto(protoAsString);
```

Thanks.

**Comment by rymarm** [comment]
@siddhsql As far as I know, protobuf hasn't any implementation of such interfaces in Java. But you can overcome it and use protobuf compilator (`protoc`) directly from Java using `Runtime` :
https://www.baeldung.com/run-shell-command-in-java

It's a more complicated way to compile a proto file than you wished, but it is kind of a solution.

**Comment by siddhsql** [comment]
thanks Rymar.
