### ISSUE TITLE
text format's "expanded Any syntax" does not accept all valid messages

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#12211]
The [documentation for the `type_url` field](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/src/google/protobuf/any.proto#L129-L156) of `google.protobuf.Any` describes the type URL as a normal, legal URL, with the only constraints being it must contain at least one slash (`/`) character; the scheme, if present, must be "http" or "https"; it may not end in a slash (implied by [this](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/src/google/protobuf/any.proto#L97-L98)); and the last path component must be a valid fully-qualified name in canonical form (no leading dot).

However, the [text format specification](https://protobuf.dev/reference/protobuf/textformat-spec/#field-names) for the "expanded Any syntax" allows only a domain name, a single slash, and then the fully-qualified name. So it allows no scheme and no  additional path components. Also, the grammar definition for the domain is defined to exactly match that of a qualified Protobuf identifier, which disallows numerous characters that are technically allowed in a domain name (most markedly absent is hyphen `-`).

The specification exactly matches the [C++ implementation](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/src/google/protobuf/text_format.cc#L1259-L1275). Some implementations are more lenient; for example [Go](https://github.com/protocolbuffers/protobuf-go/blob/fe5bc5404151983756ef8980016a7d59bd63bb7e/internal/encoding/text/decode.go#L427-L431) allows hyphens (but still does not allow a scheme and still excludes other characters allowed in domains and URI paths), and [Java](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/java/core/src/main/java/com/google/protobuf/TextFormat.java#L2193-L2216) allows multiple path components (but does not allow hyphens or other characters and also does not allow a scheme).

[Buf's language spec](https://protobuf.com/docs/language-spec#protobuf-text-format) describes the format the same way as the spec and C++ implementation (since it was derived from the C++ implementation, before the text format spec was published).

Having said all of that, _all_ implementations will happily **produce** text format that cannot be parsed -- because they simply emit the type URL (without validating it, aside from making sure a configured resolver can provide a message descriptor for it) into the expanded Any syntax ([C++](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/src/google/protobuf/any_lite.cc#L78-L89), [Java](https://github.com/protocolbuffers/protobuf/blob/fe0a809d5ef4f2fdacee91d69dc20780b7cb4f31/java/core/src/main/java/com/google/protobuf/TextFormat.java#L388-L413), [Go](https://github.com/protocolbuffers/protobuf-go/blob/fe5bc5404151983756ef8980016a7d59bd63bb7e/encoding/prototext/encode.go#L362-L363)).

One possible remedy is to update all of the text format printer implementations to first check that the type URL matches the very simple and constrained form in the text format spec before using the expanded Any syntax. However, the much better and user-friendly solution would be to augment the text format spec to accommodate any legal URL that has at least one slash. Something like so:
```abnf
# These reference 'dec' and 'hex' lexical elements of existing text format spec grammar
url = [ scheme ], domain, "/", { path_component, "/" }, path_component ;

scheme = [ "http://" | "https://" ] ;
domain = domain_component, { ".", domain_component } ;

# different than proto identifier letter, which includes underscore
domain_letter = 'a'..'z' | 'A'..'Z' ;
# must start with letter and end with letter or number
domain_component = domain_letter, [ { domain_letter | dec | "-" }, ( domain_letter | dec ) ] ;

path_char = domain_letter | dec |
            "-" | "." | "_" | "~" | "!" | "$" | "&" | "\" | "(" | ")" |
            "*" | "+" | "," | ";" | "=" | ":" | "@" | path_char_hex_encoded ;
path_char_hex_encoded = "%", hex, hex ;
path_component = path_char, { path_char } ;
```

**Comment by jhump** [comment]
One thing possibly interesting to note is that many implementations allow whitespace (and comments) in between components of the URL. For example, the following is allowed:
```
[ type . googleapis . com /  google . protobuf . FileDescriptorSet ]: <
  file: [ <name: "foo.proto"> ]
>
```
Given how many of the tokenizer implementations work, an implementation of the above grammar would similarly allow whitespace and comments around all characters that are punctuation. This might be worth changing, as it is confusing that whitespace (and comments) can be freely inserted in so many places where it would not be allowed by an actual URL parser. However, such a change would not be backwards compatible, so maybe not worth thinking about.

**Comment by Logofile** [comment]
Thanks for the detailed write-up and all of the research and testing that went into putting it together. This is really helpful. I'll work with mcy@ to address this discrepancy in the docs and/or upstream in the language code.
