### ISSUE TITLE
21.x and 22.x versions are missing from maven central

### ISSUE THREAD

**Issue by gbaso** [protocolbuffers/protobuf#12234]
I see from #9725, #10568 and others that this seems to be a recurring issue.

**Comment by deannagarcia** [comment]
The issues you linked are old and I thought they were fixed. Can you provide more details here? Which package/version is missing?

**Comment by gbaso** [comment]
According to mvnrepository for [protobuf-java](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java) and [protoc](https://mvnrepository.com/artifact/com.google.protobuf/protoc) the last available version is 3.22.2. The entire 21.x and 22.x branches seems to be missing.

**Comment by bjornjorgensen** [comment]
Yes, I have the same problem. 

"Downloaded from gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/maven2/com/google/protobuf/protoc/3.22.0/protoc-3.22.0-linux-x86_64.exe" 

https://github.com/bjornjorgensen/jupyter-spark-master-docker/actions/runs/4445420581/jobs/7804528899#step:7:37971

**Comment by deannagarcia** [comment]
This may be a misunderstanding of our new [versioning system](https://protobuf.dev/support/version-support/). The newest version of java is 3.22.0. The 22 in 22.x refers to the minor version since we have moved to language-specific major versions.
