### ISSUE TITLE
Support using a single JSON key when serializing the message to JSON with oneof

### ISSUE THREAD

**Issue by deeTEEcee** [protocolbuffers/protobuf#12246]
The problem I want to solve is that when I'm using oneof, I would like the parsed json format (when using something like Python's `MessageToDict()` to use the oneof name as the actual key. For example, given something like this:
```
            oneof value {
                uint32 int_value        = 3;
                uint64 long_value       = 4;
                float  float_value      = 5;
                double double_value     = 6;
                bool   boolean_value    = 7;
                string string_value     = 8;
                ParameterValueExtension extension_value = 9;
            }
```

The resulting json should give me something like `{"value": <some_value>}` but it seems there's no way to solve that with the current library and protobuf spec. I gave `json_name` a try but then it leads to duplicates.

**Comment by deeTEEcee** [comment]
k i figured it out. can just do something like
```
        if field.containing_oneof and self.use_oneof_name:
          name = field.containing_oneof.name
        elif self.preserving_proto_field_name:
          name = field.name
        else:
          name = field.json_name
```

where I added a new option for that.

**Comment by deeTEEcee** [comment]
@fowles not really sure why you just went and closed this ticket with no response. imo it's a pretty obvious case that the user would like an option for.

**Comment by fowles** [comment]
I was on autopilot from closing out things that were solved on google's internal question answer service.
