### ISSUE TITLE
[libprotobuf FATAL google/protobuf/descriptor.cc:810] CHECK failed: checkpoints_.empty()

### ISSUE THREAD

**Issue by Avogar** [protocolbuffers/protobuf#12240]
**What version of protobuf and what language are you using?**
Version: 3.17.3.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux x86_64, Ubuntu 22.04

**What runtime / compiler are you using**
clang-15

**What did you do?**

1) Create `schema.proto` file inside `schemas` directory with not existed message type:
```
syntax = "proto3";

message Message {
    NotExisted x = 1;
}
```

2) Create `protobuf.cpp` file with the next content:
```
#include <google/protobuf/compiler/importer.h>

struct ErrorCollector : public google::protobuf::compiler::MultiFileErrorCollector
{
    void AddError(const std::string&, int, int, const std::string&msg) override
    {
        throw std::runtime_error(msg);
    }
};

int main()
{
    google::protobuf::compiler::DiskSourceTree disk_source_tree;
    disk_source_tree.MapPath("", "schemas");
    ErrorCollector collector;
    google::protobuf::compiler::Importer importer(&disk_source_tree, &collector);
    try
    {
        importer.Import("schema.proto");
    }
    catch(...)
    {
    }

    const auto * res = importer.pool()->FindMessageTypeByName("Message");
    if (res)
        std::cerr << "Message was found\n";
    else
        std::cerr << "Message was not found\n";
}
```

3) Build it (protobuf library was build in debug mode):
```
clang++-15 protobuf.cpp -lprotobuf
```

4) Run and see the error:
```
$ ./a.out
Message was found
[libprotobuf FATAL google/protobuf/descriptor.cc:810] CHECK failed: checkpoints_.empty():
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: checkpoints_.empty():
Aborted (core dumped)
```

Note that after removing line `disk_source_tree.MapPath("", "schemas")` and changing `importer.Import("schema.proto")` to `importer.Import("schemas/schema.proto");` program finishes without abort and with output `Message was not found`.

**What did you expect to see**
Program should finish normally and message should not be found in pool, because parsing of `.proto` file failed.

**What did you see instead?**
Program was aborted and message was found in pool.

**Anything else we should know about your project / environment**
This bug was found during testing Protobuf input/output format in [ClickHouse](https://github.com/ClickHouse/ClickHouse). You can see how we work with protobuf schemas [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Formats/ProtobufSchemas.cpp).

**Comment by fowles** [comment]
The volume of work required to audit our code for exception safety in the face of callbacks is too large, so I doubt we will ever make this a supported use case.
