### ISSUE TITLE
Add riscv64 support

### ISSUE THREAD

**Issue by ernado** [protocolbuffers/protobuf#12266]
Add support for linux/riscv64.

Ref: https://github.com/protocolbuffers/protobuf/pull/12244

**Comment by ernado** [comment]
This is still  relevant.

**Comment by zhangskz** [comment]
Unfortunately, adding support for riscv64 would also require us to update our internal release process and images accordingly to compile for riscv64, which we are unlikely to be able to staff at the moment especially considering lack of support in manylinux currently: https://github.com/pypa/manylinux/discussions/1426

Per https://github.com/kubernetes/kubernetes/pull/123661#issuecomment-1977297851, it appears Kubernetes itself does not officially support riscv64 either. Closing accordingly, but we can revisit this in the future if demand changes.

**Comment by nickolaev** [comment]
Shall we reconsider this, now that we have https://github.com/pypa/manylinux/discussions/1426#discussioncomment-13822437
