### ISSUE TITLE
The "cmake/CMakeLists.txt -> CMakeLists.txt" redirection deactivates some policies silently.

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#12263]
The "cmake/CMakeLists.txt" is now deprecated, but there are some hidden problems with how it's forwarding to /CMakeLists.txt (in the repo root).

I found that some cmake policies get silently deactivated if one uses cmake/CMakeLists.txt

E.g. here:
https://github.com/protocolbuffers/protobuf/blob/244b245002270ee699dce8d80b8984844d7fc97f/CMakeLists.txt#L10

Since `CMP0091` needs to be set before languages are initialized, but https://github.com/protocolbuffers/protobuf/blob/244b245002270ee699dce8d80b8984844d7fc97f/cmake/CMakeLists.txt#L5 is reached first, the policy won't be active (which is quite counterintuitive)
and settings made here https://github.com/protocolbuffers/protobuf/blob/244b245002270ee699dce8d80b8984844d7fc97f/CMakeLists.txt#L233 will be overridden by e.g. `/MD` still being present in CMAKE_CXX_FLAGS_*

(at least this is my interpretation of what happens, but I've observed `/MD` flag being present when it should not).

**Comment by acozzette** [comment]
I think we should probably just delete that file at this point. @jtattermusch Would that be ok from your perspective or would that break gRPC?
