### ISSUE TITLE
[MSVC] Protobuf failed to build on Windows due to error C2794, error C2938, error C2955 and error C2975

### ISSUE THREAD

**Issue by Zhaojun-Liu** [protocolbuffers/protobuf#12289]
Hi, we updatet the commit of protobuf recently, and it failed to build with msvc due to the below errors. Could you please take a look? Thanks.

**What version of protobuf and what language are you using?**
Version: main (I tried commit 244b245 and commit 9b4a3ed9e, the same results)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows Version: Windows server 2022
**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio Version: VS2022 V17.5.1
**What did you do?**
Repro steps:
1. git clone https://github.com/protocolbuffers/protobuf F:\gitP\google\protobuf
2. git -C "F:\gitP\google\protobuf" submodule sync
3. git -C "F:\gitP\google\protobuf" submodule update --init --recursive
4. mkdir F:\gitP\google\protobuf\build_amd64 and cd mkdir F:\gitP\google\protobuf\build_amd64
5. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..\cmake
6. msbuild /p:Platform=x64 /p:Configuration=Release protobuf.sln /t:Rebuild

**What did you expect to see**
build successfully.
**What did you see instead?**
```
F:\gitP\google\protobuf\third_party\abseil-cpp\absl/meta/type_traits.h(683,66): error C2794: 'type': is not a member of any direct or indirect base class of 'std::result_of<const Compare (const Key &,const Key &)>' [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]
  F:\gitP\google\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(90,26): error C2938: 'absl::lts_20230125::result_of_t' : Failed to specialize alias template (compiling source file F:\gitP\google\protobuf\src\google\protobuf\map_test.cc) [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]
  F:\gitP\google\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(335,51): error C2955: 'std::is_same': use of class template requires template argument list (compiling source file F:\gitP\google\protobuf\src\google\protobuf\map_test.cc) [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]
  F:\gitP\google\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(336,73): error C2955: 'std::is_convertible': use of class template requires template argument list (compiling source file F:\gitP\google\protobuf\src\google\protobuf\map_test.cc) [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]
  F:\gitP\google\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(372,27): error C2975: 'B': invalid template argument for 'absl::lts_20230125::conditional_t', expected compile-time constant expression (compiling source file F:\gitP\google\protobuf\src\google\protobuf\map_test.cc) [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]
  F:\gitP\google\protobuf\third_party\abseil-cpp\absl/meta/type_traits.h(683,66): error C2794: 'type': is not a member of any direct or indirect base class of 'std::result_of<const absl::lts_20230125::container_internal::key_compare_adapter<Compare,Key>::checked_compare (const Key &,const Key &)>' [F:\gitP\google\protobuf\build_amd64\tests.vcxproj]

    15 Warning(s)
    6 Error(s)
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

The build log:
[build.log](https://github.com/protocolbuffers/protobuf/files/11025662/build.log)

**Comment by mkruskal-google** [comment]
Hey June,

Are you building with C++20?  It looks like this was only available from C++11 to C++17, so we might need to add some conditonal logic here

**Comment by mkruskal-google** [comment]
I wasn't able to reproduce this with VS 2019, so it looks like it may be specific to 2022 (where I am able to reproduce it).  Note, setting `-Dprotobuf_BUILD_TESTS=OFF` should work around this for downstream users.  Still investigating the root issue in the meantime
