### ISSUE TITLE
Make json_name take priority over name (fully) in Java parsing

### ISSUE THREAD

**Issue by jskeet** [protocolbuffers/protobuf#12290]
Java has the same issue reported for C# in #11987.

Test used for C# code:

```proto
message Issue11987Message {
  int32 a = 1 [json_name = 'b'];
  int32 b = 2 [json_name = 'a'];
  int32 c = 3 [json_name = 'd'];
}
```

- Create a message with a=10, b=20, c=30
- Format as JSON - expect  `{ "b": 10, "a": 20, "d": 30 }`
- Parse from the JSON           
- Assert equality with original message

The [current Java code](https://github.com/protocolbuffers/protobuf/blob/6d776dfed52e36a58f318c0ba3acc93445ed710e/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1465-L1476) - like the previous C# code - populates a map with a single pass over the fields, putting both the name and json_name into the map each time... which means that the "name" of field `b` overrides the `json_name` of field `a`.

The fix should be the same as for C#, first putting all the names in the map, then all the JSON names:

```java
for (FieldDescriptor field : descriptor.getFields()) {
  fieldNameMap.put(field.getName(), field);
}
for (FieldDescriptor field : descriptor.getFields()) {
  fieldNameMap.put(field.getJsonName(), field);
}
```

**Comment by parwalayush** [comment]
@jskeet 
Is this fixed for java code?

**Comment by jskeet** [comment]
@parwalayush: I don't know whether it's ever been a problem in Java. I don't work in the Java code, only the C#.

**Comment by parwalayush** [comment]
Thanks, Do you have any idea with whom I can check this?
