### ISSUE TITLE
Please delete tag v22.2

### ISSUE THREAD

**Issue by LocutusOfBorg** [protocolbuffers/protobuf#12348]
Hello both v4.22.2 and v22.2 tags were pushed. Same sha, looks like a wrong tag that makes automatic new version show 22.2 as available. This is a serious issue in case somebody grabs that version. Please delete it.
git tag -d v22.2
git push origin :v22.2
or similar should do the trick
cc @zhangskz

**Comment by LocutusOfBorg** [comment]
or is it something intended? why keep two different versioning then?

**Comment by zhangskz** [comment]
This is WAI. See https://protobuf.dev/news/2022-05-06/#versioning for the announcement on how our versioning system works. "v22.2" is the general protobuf release with corresponding Github release / notes. The "v4.22.2" tag corresponds to the C++ and Python major versions for this release.
