### ISSUE TITLE
Python 'cpp' protobuf backend is not available for protobuf 3.x and python3.11

### ISSUE THREAD

**Issue by nikita-uvarov** [protocolbuffers/protobuf#12351]
**What version of protobuf and what language are you using?**
Version: protobuf==3.20.3
Language: Python 3.11

**What operating system (Linux, Windows, ...) and version?**
Linux, reproduce is in docker image python:3.11 from https://hub.docker.com/_/python

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.11

**What did you do?**

Install protobuf 3.20.3 (latest package from 3.x branch) from PyPI in Python 3.11, observe that 'python' protobuf backend is used.

```
~$ sudo docker run -ti --rm python:3.11 /bin/bash                                                                                                                                 
...
root@492034476e29:/# python3 -m pip install protobuf==3.20.3                                                                                                                                                      
Collecting protobuf==3.20.3                                                                                                                                                                                       
  Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)                                                                                                                                                       
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 1.9 MB/s eta 0:00:00                                                                                                                                 
Installing collected packages: protobuf                                                                                                                                                                           
Successfully installed protobuf-3.20.3                                                                                                                                                                            
root@492034476e29:/# python3 -c "import google.protobuf.internal.api_implementation; print(google.protobuf.internal.api_implementation.Type())"
python
root@492034476e29:/# ls /usr/local/lib/python3.11/site-packages/google/protobuf/pyext/
__init__.py  __pycache__  cpp_message.py
```

**What did you expect to see**
'cpp' protobuf backend being used and C++ _message.cpython-311-x86_64-linux-gnu.so library to be present in google/protobuf/pyext.

**What did you see instead?**
'python' protobuf backend is used. This is observed as huge performance degradation from python 3.10 -> 3.11 upgrade (provided that protobuf package version is fixed to 3.x), that is not so easy to debug if you are not familiar with the protobuf internals. This issue is not present in protobuf 4.x branch.

I'm wondering whether it is intended or is a bug, and also want to document this behaviour for others to know, even if it is not going to be fixed. Of course, 3.x protobuf branch is now obsolete with the release of 4.x and upb backend, however, some users may have considerations to stick to 3.x branch.

**Note**
In python3.10 and below, 'cpp' backend is correctly used, and the shared library with Python/C++ extensions is present.
```
~$ sudo docker run -ti --rm python:3.10 /bin/bash
root@959cbd650c05:/# python3 -m pip install protobuf==3.20.3
...
root@959cbd650c05:/# python3 -c "import google.protobuf.internal.api_implementation; print(google.protobuf.internal.api_implementation.Type())"
cpp
root@959cbd650c05:/# ls /usr/local/lib/python3.10/site-packages/google/protobuf/pyext/
__init__.py  __pycache__  _message.cpython-310-x86_64-linux-gnu.so  cpp_message.py
..

**Comment by anandolee** [comment]
It is a known issue but we can not change the released version's default backend.  We would ask users to use newest version instead of stick to 3.X
