### ISSUE TITLE
Building Protobuf using CocoaPods in Xcode 14.3 generates a lot of warnings

### ISSUE THREAD

**Issue by cgomez-rb** [protocolbuffers/protobuf#12372]
**What version of protobuf and what language are you using?**
Version: 3.22.0.
Language: Objective-C through CocoaPods

**What operating system (Linux, Windows, ...) and version?** 
MacOS Ventura

**What runtime / compiler are you using (e.g., python version or gcc version)** 
Python 3.9.6
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix

**What did you do?**
1. Add Protobuf as a Cocoapod dependency
2. Open Xcode 14.3
3. Try to build the project.
4. See the warnings appear.

**What did you expect to see**
I expect not to see the warnings.

**What did you see instead?**
A list of more than 100 warnings.
For example:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/116831591/228938786-ec2f5c12-c335-4744-b349-041b9a6ecec1.png">

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I'm running the project using an M1 Mac, I also noticed in [another project](https://github.com/transmission/transmission/pull/4031/files) based on C++, that adding the flag `GENERATE_MASTER_OBJECT_FILE = YES;` will solve the issue.

**Comment by thomasvl** [comment]
You say Objective-C, but those symbol names in the screen shot appear to be C++.  Can you please clarify exactly what was done so we know if it  Objective-C for C++?

**Comment by thomasvl** [comment]
Please upload an example project then, because I have no idea how you'd get `asbl` symbols in the Objective-C code. For example: `_ZNK4absl14flags_internal8FlagImpl17AtomicBufferValueEv` demangles to: `absl::flags_internal::FlagImpl::AtomicBufferValue() const`
