### ISSUE TITLE
protobuf_generate passes options in the wrong order to protoc.

### ISSUE THREAD

**Issue by MSK61** [protocolbuffers/protobuf#12375]
https://github.com/protocolbuffers/protobuf/blob/47861d28926205f4d04d369301fba024404fb2e7/cmake/protobuf-generate.cmake#L141
The plugin options `${_plugin_options}` are misplaced between `--${protobuf_generate_LANGUAGE}_out` and `${protobuf_generate_PROTOC_OUT_DIR}`. Even stranger, the options are nonsensically concatenated with a colon `:` to `${protobuf_generate_PROTOC_OUT_DIR}`. I think the correct format for the arguments should be something like:
```
ARGS ${protobuf_generate_PROTOC_OPTIONS} --${protobuf_generate_LANGUAGE}_out ${protobuf_generate_PROTOC_OUT_DIR} ${_plugin_options} ${_plugin} ${_protobuf_include_path} ${_abs_file}
```

**Comment by acozzette** [comment]
The format may look strange but I think it's actually correct. A typical flag would look something like `--cpp_out=option1,option2:path`.

**Comment by MSK61** [comment]
> The format may look strange but I think it's actually correct. A typical flag would look something like `--cpp_out=option1,option2:path`.

Does this agree with the `--cpp_out` option description [here](https://protobuf.dev/reference/cpp/cpp-generated/#invocation)? It's stated that --cpp_out should only take the directory where the generated files are placed.

**Comment by acozzette** [comment]
You are right, it looks like this is not covered in the docs yet.
