### ISSUE TITLE
Segmentation fault in python protobufs when assigning the wrong message type 

### ISSUE THREAD

**Issue by gwenwahl** [protocolbuffers/protobuf#12373]
**What version of protobuf and what language are you using?**
Version: 4.22.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Appears in MacOS as well as Debian based linux, seems to be platform independent

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.10.5

**What did you do?**
If you set the value of a protobuf Message field, that is itself a Message field, to the wrong type of message, this will cause a segmentation fault in python.

An example using included well known types:

Installed packages
```
-> pip list
Package    Version
---------- -------
pip        22.0.4
protobuf   4.22.1
setuptools 58.1.0

-> python
Python 3.10.5 (main, Jun 28 2022, 11:18:23) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import api_pb2
>>> api_pb2.Api(source_context=api_pb2.Mixin())
[1]    61055 segmentation fault  python
```

**What did you expect to see**
I would expect to get an illegal argument exception or something, instead of a seg fault.

**What did you see instead?**
A segmentation fault

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
I got TypeError instead:
```
$ python
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import api_pb2
>>> api_pb2.Api(source_context=api_pb2.Mixin())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.SourceContext got google.protobuf.Mixin.
```

Verified for pure python, c++ extension and upb

**Comment by freider** [comment]
I have the same issue (segfault), using `protobuf-4.22.3-cp37-abi3-manylinux2014_x86_64.whl` and Python 3.10.8 as well as 3.11.1, if that's any help.
```
>>> from google.protobuf import api_pb2
>>> api_pb2.Api(source_context=api_pb2.Mixin())
fish: “python” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by nmariz** [comment]
This issue is limiting us [MySQL Connector/Python](https://github.com/mysql/mysql-connector-python/) to add support for 4.22.x. The issue is only observable using >=4.22.0.
