### ISSUE TITLE
Undefined use of PROTOBUF_RTTI in port.h

### ISSUE THREAD

**Issue by s-perron** [protocolbuffers/protobuf#12412]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux 

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc 12.2

**What did you do?**

I tried updating the spirv-tools project to use the latest commit in main (also fails with v22.2).

**What did you expect to see**

I expect a clean compilation.

**What did you see instead?**

When compiling I got a warning (which we treat as errors) that `PROTOBUF_RTTI` is used in port.h before it is defined:

https://github.com/protocolbuffers/protobuf/blob/f7a2f4acea7c981108f75210185ecdee8c13ea82/src/google/protobuf/port.h#L46-L56

From what I can tell, the `#include "google/protobuf/port_def.inc"` at line 56 defines `PROTOBUF_RTTI`, so the macro is undefined when used at line 46. Everything compiled fine if I moved lines 46-48 after line 56.

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Thank you for the bug report, I think you are right that we're trying to access `PROTOBUF_RTTI` before it is defined. I will send out a change to fix this.
