### ISSUE TITLE
GitHub Pages Deployment "error"

### ISSUE THREAD

**Issue by Anass-23** [protocolbuffers/protobuf#12435]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
None

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
None

**What did you do?**
1. Go to https://github.com/protocolbuffers/protobuf
2. Click on environments > github-pages
3. Press View Deployment
4. The attached file contains the "error"

**What did you expect to see**
I expected to see the reference page of the repository / documentation / ...

**What did you see instead?**
The page responded with an error 404, because the route https://protobuf.dev/protobuf/ does not exists it should redirect to https://protobuf.dev/

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
![Screenshot 2023-04-10 at 14 40 35](https://user-images.githubusercontent.com/56134601/230903215-674f2702-8b75-4072-b57c-8cf183f3a958.jpg)

**Comment by Anass-23** [comment]
yes

**Comment by HARSHARORA9** [comment]
@Anass-23 Can you please elaborate problem what issue you are actually facing. Please 🥺 elaborate as I am new to open source
