### ISSUE TITLE
third_party/abseil-cpp is missing in the tarball

### ISSUE THREAD

**Issue by yurivict** [protocolbuffers/protobuf#12448]
When built from [this](https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protobuf-22.2.tar.gz) provided tarball configure breaks:
```
Make Error at third_party/utf8_range/CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /usr/ports/devel/protobuf/work/protobuf-22.2/third_party/abseil-cpp

  does not contain a CMakeLists.txt file.
```

Tarball should contain all necessary components. Git modules can't work from the tarball.

**What version of protobuf and what language are you using?**
Version: 22.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 13.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. cmake .

```

**Comment by BlackMetalz** [comment]
Confirmed

**Comment by seifashraf1** [comment]
Confirmed

**Comment by yurivict** [comment]
IMO you should make a new release with the fix.

**Comment by deannagarcia** [comment]
We purposefully don't put abseil files in our distribution tarball. Please download directly from https://github.com/abseil/abseil-cpp. This keeps our distribution tarball a reasonable size and also ensures files aren't duplicated if users were already using abseil.

**Comment by yurivict** [comment]
@deannagarcia 
Why don't you/is there a way to use externally installed abseil-cpp?

**Comment by deannagarcia** [comment]
Our README was updated to include the command you need to use externally installed abseil-cpp: https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md. Specifically, you'll need to add these flags: `-Dprotobuf_ABSL_PROVIDER=package` and  `-DCMAKE_PREFIX_PATH=/tmp/absl  # Path to where I installed Abseil`
