### ISSUE TITLE
C# - Resizing RepeatedField with RepeatedField<T>.Capacity does not allow this[index] = value set indexer

### ISSUE THREAD

**Issue by Alexejhero** [protocolbuffers/protobuf#12442]
**What version of protobuf and what language are you using?**
Version: 3.22.1
Language: C#

**What did you do?**
1. Create a new .proto file containing a `repeated` field.
2. Generate the C# source for it
3. Create a new instance of that object
4. Call `.Capacity = 1` on the `RepeatedField` property
5. Call `this[0] = something` on the `RepeatedFieldProperty
6. See error: `ArgumentOutOfRangeException`

**What did you expect to see**
The set indexer should succeed

**What did you see instead?**
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Google.Protobuf.Collections.RepeatedField`1.set_Item(Int32 index, T value)
```

---

The set indexer checks for the `count` field in the `RepeatedField` class, not the capacity, I think this is a bug and not intentional.

https://github.com/protocolbuffers/protobuf/blob/f11079b01f075bc7c5b3286d85a8feca798c09e9/csharp/src/Google.Protobuf/Collections/RepeatedField.cs#L624-L627

**Comment by jskeet** [comment]
> The set indexer checks for the count field in the RepeatedField class, not the capacity, I think this is a bug and not intentional.

No, it's absolutely intentional. It's the same as the `List<T>` indexer.

The capacity is effectively an implementation detail to allow users to avoid repeated re-allocation of the internal array. But it's *not* intended to affect whether an indexer operation succeeds or not.

**Comment by Alexejhero** [comment]
You are correct actually.
