### ISSUE TITLE
C++ Phonebook example doesn't compile on Windows with protobuf from vcpkg and latest LLVM/MSVC toolchain

### ISSUE THREAD

**Issue by e8y** [protocolbuffers/protobuf#12455]
**What version of protobuf and what language are you using?**
Version: 3.21.12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10, 64-bit

**What runtime / compiler are you using (e.g., python version or gcc version)**
- Installed protobuf from vcpkg as per [these instructions](https://github.com/protocolbuffers/protobuf/blob/main/src/README.md#c-protobuf---windows) (vcpkg install protobuf protobuf:x64-windows)
- Installed latest LLVM toolchain from their [releases](https://github.com/llvm/llvm-project/releases) (LLVM-16.0.1-win64.exe)
- Installed Visual Studio 2022 (cl.exe version is 19.35.32215)

**What did you do?**
1. Save [this proto structure](https://protobuf.dev/getting-started/cpptutorial/#protocol-format) as addressbook.proto
2. Run `C:\vcpkg\packages\protobuf_x64-windows\tools\protobuf\protoc.exe --cpp_out=. addressbook.proto`
3. Save [this code](https://protobuf.dev/getting-started/cpptutorial/#writing-a-message) as writer.cpp
4. Run `C:\Program Files\LLVM\bin\clang-cl.exe /std:c++20 '/IC:\vcpkg\packages\protobuf_x64-windows\include' -EHsc .\writer.cpp /MD /link '/LIBPATH:C:\vcpkg\packages\protobuf_x64-windows\lib'`

**What did you expect to see**
Successful compilation

**What did you see instead?**
A compiler error in the `protoc`-generated C++ code using `offsetof` in a `constexpr` statement. The MSVC-provided `offsetof` macro uses `reinterpret_cast`.

```
In file included from .\writer.cpp:4:
In file included from ./addressbook.pb.h:26:
In file included from C:\vcpkg\packages\protobuf_x64-windows\include\google/protobuf/generated_message_util.h:54:
In file included from C:\vcpkg\packages\protobuf_x64-windows\include\google/protobuf/implicit_weak_message.h:39:
In file included from C:\vcpkg\packages\protobuf_x64-windows\include\google/protobuf/repeated_field.h:60:
C:\vcpkg\packages\protobuf_x64-windows\include\google/protobuf/repeated_ptr_field.h(645,27): error: constexpr variable
      'kRepHeaderSize' must be initialized by a constant expression
  static constexpr size_t kRepHeaderSize = offsetof(Rep, elements);
                          ^                ~~~~~~~~~~~~~~~~~~~~~~~
C:\vcpkg\packages\protobuf_x64-windows\include\google/protobuf/repeated_ptr_field.h(645,44): note: cast that performs
      the conversions of a reinterpret_cast is not allowed in a constant expression
  static constexpr size_t kRepHeaderSize = offsetof(Rep, elements);
                                           ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stddef.h(47,32): note: expanded from macro 'offsetof'
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by sbenzaquen** [comment]
That standard library used does not follow the requirements for `offsetof`. It is required that it evaluates to an integer constant expression.
How old is this standard library? You might want to upgrade to a newer one.
