### ISSUE TITLE
Missing release assets in 22.3?

### ISSUE THREAD

**Issue by medb** [protocolbuffers/protobuf#12467]
The [v22.3 release](https://github.com/protocolbuffers/protobuf/releases/tag/v22.3) does not include many of the archives included in previous releases (22.12 release has 26 assets, while 22.3 has just 12 assets).

Is this deliberate, or an oversight?

**Comment by deannagarcia** [comment]
This is deliberate, and all v22.x releases have the same number of assets. We announced [here](https://protobuf.dev/news/2022-08-03/#lang-specific-distros) that starting with 22.0 we will no longer publish language specific distributions, just a single tar/zip file for the whole repository.
