### ISSUE TITLE
Staleness tests fails on forked repo

### ISSUE THREAD

**Issue by rasteve** [protocolbuffers/protobuf#12522]
**What version of protobuf and what language are you using?**
Version: main
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
N/A

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
1. Fork the project via Github (main branch)
2. Run Staleness tests action OR wait until 10am UTC
3. Check Actions via Github fork or emails

**What did you expect to see**
No failures

**What did you see instead?**
Actions failing / email notifications about "run failed at startup"

Error reported as below:

> Check failure on line 20 in .github/workflows/staleness_check.yml
> 
> GitHub Actions
> / Staleness tests
> Invalid workflow file
> The workflow is not valid. .github/workflows/staleness_check.yml (Line: 20, Col: 9): Unrecognized named-value: 'matrix'. Located at position 68 within expression: github.event.repository.full_name == 'protocolbuffers/protobuf' || matrix.branch == 'main '

It appears intentional that this should not run for forks anyway (see commit [09677a6]).  Also, there is an extra space within the quotes here: `matrix.branch == 'main '` - unsure if that causes problems too.

**Anything else we should know about your project / environment**
N/A

**Comment by mkruskal-google** [comment]
This is intentional.  All our GHA use our GCP project for Bazel caching, and we can't release our access token.  If you have your own GCP account you could in theory set up your repo to run our tests though
