### ISSUE TITLE
Duplicate json_name in protobuf python > 4

### ISSUE THREAD

**Issue by maxnoe** [protocolbuffers/protobuf#12525]
Consider the following (much simplified) proto file:

```protobuf
syntax = "proto2";

package ProtoDataModel;

message CameraEvent {
	optional fixed32 eventType = 1;
	optional fixed32 event_type = 2;
}
```

This file works fine with protoc / python protobuf 3.20 but raises the following error on protobuf 4.x:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mnoethe/Projects/duplicate_json_name/L0_pb2.py", line 16, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08L0.proto\x12\x0eProtoDataModel\"4\n\x0b\x43\x61meraEvent\x12\x11\n\teventType\x18\x01 \x01(\x07\x12\x12\n\nevent_type\x18\x02 \x01(\x07')
TypeError: Couldn't build proto file into descriptor pool: duplicate json_name (eventType)
```

**Comment by zhangskz** [comment]
@ericsalo I assume this is UPB -- is there additional escaping that we could easily add here?

**Comment by maxnoe** [comment]
Any update on this? This is blocking our update to the current protobuf version...

**Comment by ericsalo** [comment]
Yikes! I deeply apologize, never noticed that this one was assigned to me. What's happening here is that upb is attempting to convert field names to lowerCamelCase for JSON as per the spec. In this example, both field names end up mapping to 'eventType' and this causes a name collision.

You should be able to manually set the JSON name via a field option, something like the following:

message CameraEvent {
	optional fixed32 eventType = 1;
	optional fixed32 event_type = 2 [json_name="event_type"];
}

**Comment by maxnoe** [comment]
I found that solution, but that means changing the protobuf definition, which are not really under my control and also need to still support older versions of libprotobuf, which didn't yet have the json_name option it seems.

**Comment by ericsalo** [comment]
Yikes again. If the protobuf definition is not under your control then I am unfortunately out of suggestions.

**Comment by maxnoe** [comment]
How was this handled in 3.20 by the old python bindings?

**Comment by maxnoe** [comment]
This protobuf documentation contains a recipe for handling co flicting json names:

https://protobuf.com/docs/language-spec#json-name-conflicts

**Comment by ericsalo** [comment]
> How was this handled in 3.20 by the old python bindings?

I have no idea - that was before my time. What json names does your code expect to see?

**Comment by ericsalo** [comment]
> This protobuf documentation contains a recipe for handling conflicting json names:
> 
> https://protobuf.com/docs/language-spec#json-name-conflicts
> 
> It notes that it should not be an error under proto2

We have passed the point at which I can discuss this topic usefully since I do not know any of the history here, so imma hand it off to someone who can.

**Comment by maxnoe** [comment]
>  I have no idea - that was before my time. What json names does your code expect to see?

We only use the binary representation

**Comment by maxnoe** [comment]
@mkruskal-google 

>  You can set the option deprecated_legacy_json_field_conflicts on the message to disable the JSON uniqueness check for now. 

Thanks!

How can I set this option?

**Comment by AJsamk** [comment]
Has this been addressed? I have the same issue and the message definitions are not under my control.

**Comment by maxnoe** [comment]
This issue is still relevant

**Comment by mkruskal-google** [comment]
Sorry, this option needs to be set on the proto message.  Note: this will work for pure python and python/C++, but upb currently doesn't recognize this option.  I'll add support there
