### ISSUE TITLE
Protobuf compiler version 22.3 doesn't match library version 4.22.3 in cmake 

### ISSUE THREAD

**Issue by sunflower-knight** [protocolbuffers/protobuf#12539]
**What version of protobuf and what language are you using?**
Version: release v22.3   
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu22.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
1. Go to 'protobuf and compile it from source and install '
2. Click on 'cmake FindProtobuf '

**What did you expect to see**
cmake FindProtobuf work well. 
maybe  protoc --version is 4.22.3 is great.
**What did you see instead?**
When I use protoc --verision , answer is 22.3 
but the version in common.h that cmake will use is 4.22.3

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
The protoc and cmake version numbers should be WAI. See https://protobuf.dev/news/2022-05-06/#versioning -- I believe protoc only has the shared minor version (22.3) but CMake uses the C major version number (4.22.3) 

Are you encountering an actual error when using [FindProtobuf](https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake)? If so, what is the error?

**Comment by jin-111** [comment]
I meet the issue too with the version 4.22.3.  I switch to protoc(3.21.12), and this issue does not  arises.  It's nessary to check why this issue arises。
My cmake version is 3.26.3， witch is on windows 10。 When I built the protoc 4.22.3 with gcc in mingw64， I notice that the version of protoc show by was 22.3。 And I built it successful。As I used find_package to get protobuf, cmake raised issues witch are "Protobuf compiler version 22.3 doesn't match library version 0.22.3" and "Found Protobuf: C:/Program Files (x86)/protobuf/lib/libprotobuf.a (found version "4.22.3") ".

**Comment by weston-wang** [comment]
I'm still running into this with Protobuf 4.24.3, i.e. "Protobuf compiler version 24.3 doesn't match library version 4.24.3". I tried both the built-in toolchain in CLIon which is CMake 3.26.4, and command line latest Homebrew installed CMake 3.27.4.  Is there a resolution on the horizon?  protoc --version shows libprotoc 24.3

**Comment by msherman13** [comment]
also seeing this issue when importing into cmake after a fresh build from source of v26.1. I am also not able to specify `find_package(Protobuf 26.1 REQUIRED)` in cmake now because it says it is only finding 5.26.1.

**build steps:**
```
    cmake \
        -DCMAKE_BUILD_TYPE=Release \\\
        -Dprotobuf_BUILD_TESTS=OFF \
        -Dprotobuf_BUILD_PROTOBUF_BINARIES=ON \
        -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
        -DBUILD_SHARED_LIBS=OFF ..
    make
    make install

```
**cmake command to import:**
```
set(Protobuf_USE_STATIC_LIBS ON)
find_package(Protobuf REQUIRED)

```
**warning when running cmake:**
```
CMake Warning at /usr/share/cmake-3.26/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version 26.1 doesn't match library version 5.26.1
```

**Comment by XR-stb** [comment]
> also seeing this issue when importing into cmake after a fresh build from source of v26.1. I am also not able to specify `find_package(Protobuf 26.1 REQUIRED)` in cmake now because it says it is only finding 5.26.1.
> 
> **build steps:**
> 
> ```
>     cmake \
>         -DCMAKE_BUILD_TYPE=Release \\\
>         -Dprotobuf_BUILD_TESTS=OFF \
>         -Dprotobuf_BUILD_PROTOBUF_BINARIES=ON \
>         -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
>         -DBUILD_SHARED_LIBS=OFF ..
>     make
>     make install
> ```
> 
> **cmake command to import:**
> 
> ```
> set(Protobuf_USE_STATIC_LIBS ON)
> find_package(Protobuf REQUIRED)
> ```
> 
> **warning when running cmake:**
> 
> ```
> CMake Warning at /usr/share/cmake-3.26/Modules/FindProtobuf.cmake:524 (message):
>   Protobuf compiler version 26.1 doesn't match library version 5.26.1
> ```
Have you solved this problem?

**Comment by msherman13** [comment]
> > also seeing this issue when importing into cmake after a fresh build from source of v26.1. I am also not able to specify `find_package(Protobuf 26.1 REQUIRED)` in cmake now because it says it is only finding 5.26.1.
> > **build steps:**
> > ```
> >     cmake \
> >         -DCMAKE_BUILD_TYPE=Release \\\
> >         -Dprotobuf_BUILD_TESTS=OFF \
> >         -Dprotobuf_BUILD_PROTOBUF_BINARIES=ON \
> >         -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
> >         -DBUILD_SHARED_LIBS=OFF ..
> >     make
> >     make install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **cmake command to import:**
> > ```
> > set(Protobuf_USE_STATIC_LIBS ON)
> > find_package(Protobuf REQUIRED)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **warning when running cmake:**
> > ```
> > CMake Warning at /usr/share/cmake-3.26/Modules/FindProtobuf.cmake:524 (message):
> >   Protobuf compiler version 26.1 doesn't match library version 5.26.1
> > ```
> 
> Have you solved this problem?

Yes changing the find package line to the below solves the issue for me:

find_package(Protobuf CONFIG REQUIRED)
