### ISSUE TITLE
Improve JsonFormat.print() performance

### ISSUE THREAD

**Issue by muhyousufmemon** [protocolbuffers/protobuf#12546]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3? proto3
If it's about generated code change, what programming language? java

**Describe the problem you are trying to solve.**
We are using JsonFormat.Printer to write out proto messages to json. Problem? Protobuf uses reflection under the hood for some reason and it happens every time. 

**Describe the solution you'd like**
Ideally, I would like to see a `toJson()` function in the generated jar by protoc which would simply give the json equivalent of the message

**Describe alternatives you've considered**
Cache the reflection 

**Additional context**
[https://drive.google.com/file/d/1nMIrfYGQo9f2xju49i0vlABX2Qgp7Xrs/view?usp=sharing](FlameGraph)

**Comment by zhangskz** [comment]
Unfortunately this use-case and performance win is likely not worth the trade-off of the across the board binary size increase that would result. I think similarly, implementing this for Java would also mean implementing for every other languages for consistency, which I don't think will happen.
