### ISSUE TITLE
Building through Cmake encountering abseil-cpp related Cmake Error

### ISSUE THREAD

**Issue by Zarca** [protocolbuffers/protobuf#12549]
Hi,
I'm trying to build protobuf using Cmake 3.10 on Ubuntu18.04.
I git clone the protobuf repo and did:
```shell
git submodule update --init --recursive
```
the i continued to type:
```shell
mkdir build
cd build
cmake .. -DCMAKE_CXX_STANDARD=14
```
My Cmake command show some error like :

>CMake Error at cmake/tests.cmake:111 (add_executable):
  Target "test_plugin" links to target "absl::scoped_mock_log" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:390 (include)

CMake Error at cmake/tests.cmake:87 (add_executable):
  Target "tests" links to target "absl::scoped_mock_log" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:390 (include)

So here comes my wondering questions:
Q1.Should I build  abseil-cpp in advance even there is a third-party download dependency already in protobuf's git repository?

Q2.After I tried to build abseil-cpp  and install it on my ubuntu successfully, but it seems did not work, the Error Informations continued as before.（P.S. i have set the  env variable CMAKE_PREFIX_PATH to where abseil-cpp installed, it dose not work, either  ）

How to solve this problems, thanks for your helping!

**Comment by acozzette** [comment]
Which version of Abseil are you using? I believe it might need to be somewhat recent for it to include `absl::scoped_mock_log`.

Building Abseil in advance or using the submodule in the protobuf Git repo should both be fine.

**Comment by Zarca** [comment]
@acozzette Hi, 
I have solved it since it seems that i somewhat deleted some files manually in third_party by mistake,
and also my Cmake version is a little bi  low(which is 3.10.2), after upgrading it to Cmake 3.26, the building process got nothing wrong, thanks for your help 🥇
