### ISSUE TITLE
[Protoc - Java] Is there a way to override hashCode() and equals() methods for a proto message?

### ISSUE THREAD

**Issue by ceregador** [protocolbuffers/protobuf#12569]
Hello,

we were using protobuf-java library version 2.3.0 at our enterprise software,
until recently several security vulnerabilities were found in this version and we have to upgrade it at some point.

Protoc compiler version 2.3.0 didn't generate _hashCode()_ and _equals()_ methods,
so we inserted the corresponding custom code explicitly into generated Java files using the _protoc_insertion_point_.

A newer version of protoc (e.g. 3.16.3) generates the implementation of _hashCode()_ and _equals()_ by default.
And I have not found a way how to control it.
E.g. disable completely in order to insert my own code or somehow mark the fields at a proto file to generate _hashCode()_ and _equals()_ methods with custom set of the fields by protoc).

Is there a way to control/override this?

**Comment by benjaminballard** [comment]
I also want to do this, but am not as far along as you, so I'm glad you posted this. What I'm considering is to extend the generated protobuf message class, so I can override hashCode() and equals() and then put the items in a HashSet and use set methods to manage them. I am new to protobuf, but I imagine overriding or adding methods to generated classes is a common need.

**Comment by ceregador** [comment]
The question is still actual.
