### ISSUE TITLE
Expose `transitive_pb_h` option or comparable to not generate `dependency.pb.h` includes

### ISSUE THREAD

**Issue by Danielku15** [protocolbuffers/protobuf#12605]
**What language does this apply to?**
proto3 generating C++

**Describe the problem you are trying to solve.**
We are using protoc to generate `pb.cc` and `pb.h` files for our messages we transfer through a custom protocol via wire. 
Due to some missing features in terms of customizing the generated C++ code (e.g. pre compiled header or custom headers) we are doing the following: 

* We let protoc generate the files to a "temp" directory. 
* We have custom C++ Header and Source files where we respectively import the Headers and sources from protoc after our custom includes and defines. 

This now causes some weird conflits in our case when we have protobufs across library boundaries due to declspecs and include orders being twisted.  

**Describe the solution you'd like**
We would like to disable that if you `include "proto1.proto"` in a `proto2.h` that there is a `#include "proto1.pb.h` in the `proto1.h`. We want to fully take care of correct includes (order and relative paths) ourselves. 

**Describe alternatives you've considered**
We are trying to currently get things at least compiling by adding the individual include paths, add everywhere manually the right includes. 

**Additional context**
There is already an option `transitive_pb_h` in the C++ generation code which decides on whether include statements of dependencies are generated. But there is no way to specfiy this option from outside within the proto file or via command line. 

https://github.com/protocolbuffers/protobuf/blob/f6c7fdf88cdba6a8c7e2215f72578b0b50d2c4ca/src/google/protobuf/compiler/cpp/file.cc#L340-L342

**Comment by deannagarcia** [comment]
Unfortunately we can't currently prioritize this work in the short/medium term but it is an idea we have thought about and could potentially work on longer term.
