### ISSUE TITLE
Allow specifying @Generated annotation

### ISSUE THREAD

**Issue by esfomeado** [protocolbuffers/protobuf#12616]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
As of now if the `annotate_code` option is used the `@javax.annotation.Generated` will be added to the generated code.

This works fine for most cases but if you want to specify your own `@Generated` annotation it's not possible.

You may need to use your own custom `@Generated` annotation with a different Retention policy for instance to get the generated code removed from certain tools.

**Describe the solution you'd like**
An option to allow specifying the `@Generated` annotation

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by trajano** [comment]
It may be language dependent so it should be prefixed with `java_` e.g. `java_generated_annotation`
