### ISSUE TITLE
CMake issues when linking against Protobuf v22.3 with Abseil dependency

### ISSUE THREAD

**Issue by alist** [protocolbuffers/protobuf#12637]
Hello!

I encountered issues when using Protobuf v22.3 with CMake due to its Abseil dependency. I have documented the steps I took and the issues I faced below.

I built and installed Protobuf v22.3 from source with the following commands:

```
$ cmake -Dprotobuf_BUILD_TESTS=OFF -DABSL_PROPAGATE_CXX_STD=ON -Dprotobuf_BUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ..
$ cmake --build . -j 10
$ sudo cmake --install .
```

Then, in my project's CMakeLists.txt, I added:

`find_package(Protobuf REQUIRED)`

and linked the Protobuf libraries to my target:

`target_link_libraries(${TARGET_NAME} PRIVATE protobuf::libprotobuf protobuf::libprotoc)`

However, when building my project, I faced multiple unresolved symbols related to `utf8-range` and `Abseil`. To resolve these issues, I tried the following:

1. Manually `find_package(utf8_range)` and added `utf8_range::utf8_validity utf8_range::utf8_range` to my target (resolving some errors).
2. Manually added `find_package(absl)` and  and linked multiple `absl::*` targets (the [same ones as in the cmake protobuf build script](https://github.com/protocolbuffers/protobuf/blob/482156c0f96dd670b9f1ba4f946e66edeb04535f/cmake/abseil-cpp.cmake#L46-L81)), but still had missing symbols
3. Built Protobuf as a static library and linked against it, but still faced unresolved symbols related to Abseil.

Eventually, I reverted to Protobuf v3.21.12, which has no Abseil dependency while still supporting CMake. With this version, I could build and run my project without any issues using `find_package(Protobuf REQUIRED)`, `target_link_libraries` as before and nothing else.

I believe there should be a more straightforward way to handle the Abseil dependencies when using Protobuf v22.3 with CMake. Also, I still don't understand why a static build of protobuf would require additional imports. Any guidance or improvements in this area would be greatly appreciated.

Thank you!

**Comment by puremourning** [comment]
I had the exact same issue. I spent a few hours battling the linker and came up with this:

```
ABSL_LIBS=                         \
  -labsl_str_format_internal       \
  -labsl_strings                   \
  -labsl_strings_internal          \
  -labsl_log_initialize            \
  -labsl_log_entry                 \
  -labsl_log_flags                 \
  -labsl_log_severity              \
  -labsl_log_internal_check_op     \
  -labsl_log_internal_conditions   \
  -labsl_log_internal_message      \
  -labsl_log_internal_nullguard    \
  -labsl_log_internal_proto        \
  -labsl_log_internal_format       \
  -labsl_log_internal_globals      \
  -labsl_log_internal_log_sink_set \
  -labsl_log_sink                  \
  -labsl_raw_logging_internal      \
  -labsl_log_globals               \
  -lutf8_validity                  \
  -labsl_cord                      \
  -labsl_cordz_info                \
  -labsl_cordz_handle              \
  -labsl_cordz_functions           \
  -labsl_cord_internal             \
  -labsl_crc_cord_state            \
  -labsl_crc32c                    \
  -labsl_crc_internal              \
  -labsl_exponential_biased        \
  -labsl_synchronization           \
  -labsl_time                      \
  -labsl_time_zone                 \
  -labsl_int128                    \
  -labsl_examine_stack             \
  -labsl_stacktrace                \
  -labsl_symbolize                 \
  -labsl_demangle_internal         \
  -labsl_debugging_internal        \
  -labsl_malloc_internal           \
  -labsl_throw_delegate            \
  -labsl_strerror                  \
  -labsl_raw_hash_set              \
  -labsl_hash                      \
  -labsl_city                      \
  -labsl_low_level_hash            \
  -labsl_base                      \
  -labsl_spinlock_wait

```

not pretty.

**Comment by coryan** [comment]
Seems like a dup of #12292 see  https://github.com/protocolbuffers/protobuf/issues/12292#issuecomment-1529680040

You need to use `find_package(Protobuf CONFIG REQUIRED)`

**Comment by puremourning** [comment]
Are there instructions for using protobufs without cmake or Bazel?

**Comment by alist** [comment]
Makes sense! Can the point of this issue be to add this to the documentation somewhere? I didn't see much docs on _using_ protobuffs with cmake.

From chat:

> When you use find_package(protobuf REQUIRED), CMake will first look for a Findprotobuf.cmake module, which is a script provided by the CMake package or the user. If it doesn't find this module, it will fall back to using the package configuration file (protobuf-config.cmake), which is generated by the package itself when it's built and installed. The Findprotobuf.cmake module might not handle the Abseil dependency correctly, causing the issues you encountered.
> 
> By using find_package(protobuf REQUIRED CONFIG), you explicitly tell CMake to use the package configuration file (protobuf-config.cmake) instead of the Findprotobuf.cmake module. This file should handle the Abseil dependency correctly, making it easier to link and use Protobuf in your project.

**Comment by coryan** [comment]
> Are there instructions for using protobufs without cmake or Bazel?

Maybe this example helps?

https://github.com/protocolbuffers/protobuf/blob/main/examples/Makefile

It uses `pkg-config` to find the flags and dependencies for protobuf.

**Comment by puremourning** [comment]
> > Are there instructions for using protobufs without cmake or Bazel?
> 
> 
> 
> Maybe this example helps?
> 
> 
> 
> https://github.com/protocolbuffers/protobuf/blob/main/examples/Makefile
> 
> 
> 
> It uses `pkg-config` to find the flags and dependencies for protobuf.
> 
> 

Thanks. Will try it. But for the record I did try the pkg config shipped with protobuf and it didn't not include any of the abseil libraries. Possible I did it wrong of course.

**Comment by coryan** [comment]
> But for the record I did try the pkg config shipped with protobuf and it didn't not include any of the abseil libraries. Possible I did it wrong of course.

I think it is likely that you did nothing wrong, but ran into #12439, or #12698, or some other problem.  If you have a repro that would help the Protobuf team.

**Comment by fwsGonzo** [comment]
This is horrible! How is adding a new dependency like that breaking builds everywhere good software practice?

**Comment by fwsGonzo** [comment]
Solution that worked for me:
```
$ wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-protobuf-21.9-1-any.pkg.tar.zst
$ pacman -U --noconfirm mingw-w64-x86_64-protobuf-21.9-1-any.pkg.tar.zst
$ cmake ..
$ ninja
```
Basically downgrade to a version with the old dependencies. I will migrate to capnproto whenever this is no longer possible.

**Comment by jonringer** [comment]
For anyone stumbling upon this.. This should work with more recent versions of protobuf:
```
# populates protobuf:: targets
find_package(Protobuf REQUIRED)

# Communicate to downstream consumers that they also need to link against libprotobuf
target_link_libraries(${TARGET_NAME}-lib
  PUBLIC protobuf::libprotobuf
)

# Should also link against abseil and protobuf
target_link_libraries(${TARGET_NAME}-exe ${TARGET_NAME}-lib)
```

**Comment by jonringer** [comment]
> My main problem is that cmake is not generating protobuf-targets.cmake and then not linking utf-8_range.

This should be getting generated in both the binary directory (during a build with `EXPORT(TARGETS`), and in the install directory (through `INSTALL(EXPORT`). Generally you do something like `sudo apt install protobuf-dev` and it will install headers, pkg-config files, an the cmake files.

**Comment by mvf** [comment]
> Generally you do something like `sudo apt install protobuf-dev` and it will install headers, pkg-config files, an the cmake files.

That's how it *should* be, but Linux distros don't ship `protobuf-config.cmake`[^1], so `find_package(Protobuf CONFIG REQUIRED)` is a CMake error when building against system libs.

This Works For Me™:
- Keep using the CMake module. Backwards-compatible and avoids having to port to `protobuf_generate`.
- On Protobuf >=22, ask `pkg-config` for the version found by CMake and link that to get `abseil` & friends.

```cmake
# No changes here, keep using CMake module + protobuf_generate_*
find_package(Protobuf REQUIRED)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS foo.proto bar.proto)

...

# Make it link with recent Protobuf
string(REGEX REPLACE "^[0-9]+\.([0-9]+\.[0-9]+)$" "\\1.0" proto_libver "${Protobuf_VERSION}")
if(proto_libver VERSION_GREATER_EQUAL "22")
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(protobuf REQUIRED IMPORTED_TARGET protobuf=${proto_libver})
    target_link_libraries(myapp PRIVATE PkgConfig::protobuf)
else()
    target_link_libraries(myapp PRIVATE protobuf::libprotobuf)
endif()
```

The regex converts the Protobuf version from the headers (e.g., `4.24.1`) to the library version (e.g., `24.1.0`, [context](https://protobuf.dev/news/2022-05-06/#versioning)).[^2] Linking against the imported targets ensures header/defs/libs consistency, even if CMake and `pkg-config` somehow manage to find different installations. Make sure to not also use `${Protobuf_INCLUDE_DIRS}`/`${Protobuf_LIBRARIES}` to avoid possible issues.

[^1]: Arch is the only exception I found.
[^2]: This doesn't build with pre-releases of Protobuf since their library versions don't end in `.0`.

**Comment by daynauth** [comment]
I have the same problem and ended up downgrading, too. Downgrading fixed the issue, but something tells me that some other issue with protobuf will pop up eventually.

**Comment by smod** [comment]
Since Google led me here, let me share this: https://github.com/protocolbuffers/protobuf/issues/15604#issuecomment-1929929148

Hope it might help.

**Comment by yimingqpa** [comment]
abseil-cpp 是一坨狗屎，加在工程里面一堆问题。

**Comment by YanzhaoW** [comment]
The current version can't work with CMake's own `FindProtobuf.cmake` module script, which many old projects are still relying on. I can't find any solution other than using older Protobuf version, such as v3.21.12.

**Comment by fwsGonzo** [comment]
This is still broken. It's still "impossible" to use static linking with protobuf using official package.

**Comment by jonringer** [comment]
> This is still broken. It's still "impossible" to use static linking with protobuf using official package.

Unfortunately this is kind of awkward with CMake in general. One potential solution would be to honor the `FindProtobuf.cmake`'s usage of `Protobuf_USE_STATIC_LIBS`. Then in the cmake config file, it could inspect if that is set, and expose the right alias:

```
cmake .. -DProtobuf_USE_STATIC_LIBS
...
# CMakeLists.txt
find_package(Protobuf CONFIG REQUIRED) # protobuf::libprotobuf is actually static
```
Another option would be to just expose a `_static` variant

```
find_package(Protobuf REQUIRED)
target_link_libraries(myLib PUBLIC protobuf::libprotobuf_static)
```

**Comment by Patrick-ICT** [comment]
> Makes sense! Can the point of this issue be to add this to the documentation somewhere? I didn't see much docs on _using_ protobuffs with cmake.
> 
> From chat:
> 
> > When you use find_package(protobuf REQUIRED), CMake will first look for a Findprotobuf.cmake module, which is a script provided by the CMake package or the user. If it doesn't find this module, it will fall back to using the package configuration file (protobuf-config.cmake), which is generated by the package itself when it's built and installed. The Findprotobuf.cmake module might not handle the Abseil dependency correctly, causing the issues you encountered.
> > By using find_package(protobuf REQUIRED CONFIG), you explicitly tell CMake to use the package configuration file (protobuf-config.cmake) instead of the Findprotobuf.cmake module. This file should handle the Abseil dependency correctly, making it easier to link and use Protobuf in your project.

Hi, I changed the find_package to `find_package(protobuf REQUIRED)`, however I ran into this problem while cmake:
<img width="934" alt="Screenshot 2024-07-17 at 16 02 32" src="https://github.com/user-attachments/assets/7094fc6c-69f9-4c51-97a7-cabd0b4e0bab">
Is there any solution?

**Comment by jonringer** [comment]
I think you truncated some of the output, can you copy it into a gist and past the link?

**Comment by Patrick-ICT** [comment]
Sorry, I have switched to an older version of protobuf, and the error is gone now. Thanks for the reply.

**Comment by MarinBagrin** [comment]
find_package(Protobuf REQUIRED **CONFIG**)

**Comment by Storynow** [comment]
The problem come out again. 系统上有多个版本的 pb 报问题真诡异。

**Comment by Bosch-SW** [comment]
As long as the issue seems still be out there, we have faced it in the following setup:
* CMake 3.31.11
* gcc 9.4.0
* g++ 9.4.0
* protobuf version 29.6  (revision:  `e9e7dd6d624098aea6b41f220361cc5d1eadf59f `)

we will show what linkage options helped us finally to bring it up.

In case of having some capacity we probably will make a PR to protobuf to fix it...

For some reason the `find_package(Protobuf REQUIRED CONFIG)` has not helped, nor `find_package(Protobuf REQUIRED)` worked with older (v3.16 from distro) nor newer CMake (v.3.31.11 built from src).

We have ended up with digging manually through the `protobuf`, `abseil` and `utf8_range` code to finally generate the linkage instruction which has brought our project to life.

so, here is it (we hope this at least helps some guys out there to solve similar issues):

* checkout the protobuf including its submodules
* build&install the Abseil from protobuf submodule dir
* build&install the Google Test from protobuf submodule dir
* build&install utf8_range from protobuf submodule dir

And finally in your project:

```
# somewhere in your project CMake
target_link_libraries(VeryCoolTarget  PRIVATE   ${NICE_PROTOBUF_LIBS})
```

and your build command with CMake:

```
# NOTE: the library linkage order matters, so, for example if you swap the protobuf and utf8_validity libs at the end
#    of the line, the build will/might fail in your case. 
cmake -DNICE_PROTOBUF_LIBS="absl::strings;absl::log;absl::log_internal_check_op;absl::log_internal_message;absl::cord;absl::raw_hash_set;absl::absl_check;absl::absl_log;absl::algorithm;absl::base;absl::bind_front;absl::bits;absl::btree;absl::cleanup;absl::cord;absl::core_headers;absl::debugging;absl::die_if_null;absl::dynamic_annotations;absl::flags;absl::flat_hash_map;absl::flat_hash_set;absl::function_ref;absl::hash;absl::if_constexpr;absl::layout;absl::log_initialize;absl::log_globals;absl::log_severity;absl::memory;absl::node_hash_map;absl::node_hash_set;absl::optional;absl::random_distributions;absl::random_random;absl::span;absl::status;absl::statusor;absl::strings;absl::synchronization;absl::time;absl::type_traits;absl::utility;absl::variant;protobuf;utf8_validity;" PATH_TO_YOUR_NICE_SOURCE
```

We hope this helps someone who has faced with the similar issue.

**Comment by jonringer** [comment]
You should be able to do `cmake --trace` which will emit what it's doing, search for when it hits the line looking for `PROTOBUF` and see what files it's traversing. Likely it's not finding the `protobuf-*.cmake` file which should be getting installed when you install protobuf.
