### ISSUE TITLE
`google::protobuf::util::TimeUtil::GetCurrentTime()` not usable on Windows

### ISSUE THREAD

**Issue by coryan** [protocolbuffers/protobuf#12673]
This is more a documentation bug than a problem in the code.  I believe the [release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0) and/or the [migration guide](https://protobuf.dev/support/migration/) should warn folks that a helpful `#undef` is gone.

**What version of protobuf and what language are you using?**

Version: 22.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC 2019 and MSVC 2022

**What did you do?**

Call `google::protobuf::util::TimeUtil::GetCurrentTime()` from application code.

**What did you expect to see**

A successful build.

**What did you see instead?**

A compile-time error.

```
google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc(101): error C2039: 'GetTickCount': is not a member of 'google::protobuf::util::TimeUtil'
T:\b\rvommcsc\execroot\google_cloud_cpp\bazel-out\x64_windows-fastbuild\bin\external\com_google_protobuf\src\google\protobuf\util\_virtual_includes\time_util\google/protobuf/util/time_util.h(64): note: see declaration of 'google::protobuf::util::TimeUtil'
google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc(101): error C2678: binary '+': no operator found which takes a left-hand operand of type 'DWORD' (or there is no acceptable conversion)
T:\b\rvommcsc\execroot\google_cloud_cpp\bazel-out\x64_windows-fastbuild\bin\external\com_google_protobuf\src\google\protobuf\util\_virtual_includes\time_util\google/protobuf/util/time_util.h(244): note: could be 'google::protobuf::Duration google::protobuf::operator +(const google::protobuf::Duration &,const google::protobuf::Duration &)' [found using argument-dependent lookup]
T:\b\rvommcsc\execroot\google_cloud_cpp\bazel-out\x64_windows-fastbuild\bin\external\com_google_protobuf\src\google\protobuf\util\_virtual_includes\time_util\google/protobuf/util/time_util.h(307): note: or       'google::protobuf::Timestamp google::protobuf::operator +(const google::protobuf::Timestamp &,const google::protobuf::Duration &)' [found using argument-dependent lookup]
T:\b\rvommcsc\execroot\google_cloud_cpp\bazel-out\x64_windows-fastbuild\bin\external\com_google_protobuf\src\google\protobuf\util\_virtual_includes\time_util\google/protobuf/util/time_util.h(311): note: or       'google::protobuf::Timestamp google::protobuf::operator +(const google::protobuf::Duration &,const google::protobuf::Timestamp &)' [found using argument-dependent lookup]
google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc(101): note: while trying to match the argument list '(DWORD, google::protobuf::util::TimeUtil::Duration)'
```

**Anything else we should know about your project / environment**

The [code in question](https://github.com/googleapis/google-cloud-cpp/blob/3c4f6d7205e5f29385d49d19ad18da1bcc7fe3ff/google/cloud/bigtable/tests/admin_backup_integration_test.cc#L81) used to compile with 21.x.  I think because previously `time_util.h` included:

https://github.com/protocolbuffers/protobuf/blob/3f13a1de2cfa2d6788b803da82c03233e8f315e6/src/google/protobuf/util/time_util.h#L105-L109

Whereas in 22.x it reads:

https://github.com/protocolbuffers/protobuf/blob/dbb9f9b5fc8cdf143cd14aa27013328dcd027d6b/src/google/protobuf/util/time_util.h#L124-L126

I think protobuf 22.x is probably doing the "Right Thing":tm: . However applications need a heads up.  Regardless, the function is not usable without the application also doing some `#undef` or protecting against the macro expansion.

**Comment by Nathan-M-code** [comment]
same problem with gcc 12.3 with protobuf 23.1.0
```error: 'GetTickCount' is not a member of 'google::protobuf::util::TimeUtil'
   24 |     auto t = google::protobuf::util::TimeUtil::GetCurrentTime();```

**Comment by Logofile** [comment]
Thanks, @Nathan-M-code, for the additional feedback. [This commit](https://github.com/protocolbuffers/protocolbuffers.github.io/commit/fc83ce0ed79cb131fc81b6dee110af25358ed4b9#diff-e6af1fade88408a71967654bff41a78d66780950913c162800bc1abcce53ec6a) addressed the original issue reported by @coryan. I'll keep this issue open until your issue has also been addressed in the docs.

**Comment by coryan** [comment]
As @Logofile  points out, the documentation now includes good guidelines on how to use `GetCurrentTime()` on Windows. See:

https://protobuf.dev/support/migration/#getcurrenttime 

I think we can close this bug.  The code in Protobuf 22.x (and higher) is doing the right thing, and the documentation showing how to workaround the problems is published.

**Comment by Logofile** [comment]
Thanks, @coryan. @Nathan-M-code, feel free to reopen this issue or submit a new one if you find that the docs don't sufficiently address your issue.

**Comment by saschasc** [comment]
@coryan Thanks for the info. At least for my code I needed to check `#ifdef GetCurrentTime` and not `#ifdef GetCurrent` as stated in the docs. Incorrect docs?

**Comment by coryan** [comment]
@saschasc good catch.  I think I missed that when reviewing the documentation.  @Logofile please consider updating the docs.

**Comment by Logofile** [comment]
CL already sent and approved. It should be in on the protobuf.dev site sometime tomorrow. Thanks @saschasc for reporting back on what you ran into!
