### ISSUE TITLE
CMake files use `string(JOIN)` while only requesting CMake >= 3.5

### ISSUE THREAD

**Issue by coryan** [protocolbuffers/protobuf#12672]
**What version of protobuf and what language are you using?**

Version: 22.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

GCC 7.5

**What did you do?**

I used this Dockerfile:

https://github.com/coryan/google-cloud-cpp/blob/414854fb53439c3d34ccb17766312c518afa9e3d/ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile#L66-L76

**What did you expect to see**

A successful build.

**What did you see instead?**

```
Step #0: -- The C compiler identification is GNU 7.5.0
Step #0: -- The CXX compiler identification is GNU 7.5.0
Step #0: -- Check for working C compiler: /usr/bin/cc
Step #0: -- Check for working C compiler: /usr/bin/cc -- works
Step #0: -- Detecting C compiler ABI info
Step #0: -- Detecting C compiler ABI info - done
Step #0: -- Detecting C compile features
Step #0: -- Detecting C compile features - done
Step #0: -- Check for working CXX compiler: /usr/bin/c++
Step #0: -- Check for working CXX compiler: /usr/bin/c++ -- works
Step #0: -- Detecting CXX compiler ABI info
Step #0: -- Detecting CXX compiler ABI info - done
Step #0: -- Detecting CXX compile features
Step #0: -- Detecting CXX compile features - done
Step #0: -- 
Step #0: -- 22.4.0
Step #0: -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT
Step #0: -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT - Success
Step #0: -- Looking for pthread.h
Step #0: -- Looking for pthread.h - found
Step #0: -- Looking for pthread_create
Step #0: -- Looking for pthread_create - not found
Step #0: -- Looking for pthread_create in pthreads
Step #0: -- Looking for pthread_create in pthreads - not found
Step #0: -- Looking for pthread_create in pthread
Step #0: -- Looking for pthread_create in pthread - found
Step #0: -- Found Threads: TRUE  
Step #0: -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
Step #0: -- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
Step #0: -- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - SuccessStep #0: CMake Error at cmake/install.cmake:9 (string):
Step #0:   string does not recognize sub-command JOIN
Step #0: Call Stack (most recent call first):
Step #0:   CMakeLists.txt:409 (include)
```

**Anything else we should know about your project / environment**

`string(JOIN)` ships with CMake >= 3.12:

https://cmake.org/cmake/help/latest/command/string.html#join

However Protobuf 22.4 requires CMake >= 3.5:

https://github.com/protocolbuffers/protobuf/blob/dbb9f9b5fc8cdf143cd14aa27013328dcd027d6b/CMakeLists.txt#L2

You could bump the CMake requirements but notice that the overall foundations matrix still says CMake >= 3.10:

https://github.com/google/oss-policies-info/blob/6587f128170c23282eb40949c914403a4010079a/foundational-cxx-support-matrix.md?plain=1#L6

**Comment by fowles** [comment]
Somewhere around here:

https://github.com/protocolbuffers/protobuf/blob/dbb9f9b5fc8cdf143cd14aa27013328dcd027d6b/cmake/install.cmake#L9

One needs to write a loop

```
CMake
  set(_protobuf_PC_REQUIRES "")
  set(_sep "")
  foreach (_target IN LISTS _pc_target_list)
    string(CONCAT _protobuf_PC_REQUIRES "${_protobuf_PC_REQUIRES}" "${_sep}" "${_target}")
    set(_sep " ")
  endforeach ()
```
