### ISSUE TITLE
Might not FieldMaskTree.Merge call itself with a null `source`?

### ISSUE THREAD

**Issue by LyndonGingerich** [protocolbuffers/protobuf#12685]
I'm looking specifically at
```csharp
private void Merge(
            Node node,
            string path,
            IMessage source,
            IMessage destination,
            FieldMask.MergeOptions options)
```
in `protobuf/csharp/src/Google.Protobuf/FieldMaskTree.cs`, line 248 as of 9f58ee3. (I discovered this behavior while working with an older version.)

What happens when `sourceField` is null but `destinationField` is not?
```csharp
var sourceField = field.Accessor.GetValue(source); // hypothetically null
var destinationField = field.Accessor.GetValue(destination); // hypothetically not null
if (sourceField == null
    && destinationField == null) // false because `destinationField` is not null
{
    continue;
}

if (destinationField == null) // false, but doesn't matter
{
    destinationField = field.MessageType.Parser.CreateTemplate();
    field.Accessor.SetValue(destination, destinationField);
}

var childPath = path.Length == 0 ? entry.Key : path + "." + entry.Key;
Merge(entry.Value, childPath, (IMessage)sourceField, (IMessage)destinationField, options); // called
continue;
```

Unless I misread, `Merge` is recursively called, and in immediately checking `if (source.Descriptor != destination.Descriptor)`, throws a `NullReferenceException`.

Should `FieldMaskTree.Merge` pass `null` into itself while not checking explicitly for `null` arguments?

**Comment by jskeet** [comment]
I'll look at this on Tuesday. (IIRC, this was basically taken from the Java code, so we should see whether the same problem is there too.)

**Comment by marner2** [comment]
```csharp
if (sourceField != null
    || !options.ReplacePrimitiveFields)
{
    field.Accessor.SetValue(destination, sourceField);
}
else
{
    field.Accessor.Clear(destination);
}
```

This merge code has more problems. It's doing null checks where it should be calling `field.Accessor.HasValue()` (especially relevant in the case of primitives), thus resulting in things like empty strings showing up where there wasn't a value before. The output of `Merge` should be the same as `IMessage.MergeFrom` if all fields are specified, correct? If so, we also should only be calling `field.Accessor.Clear(destination)` if `options.ReplacePrimitiveFields` is true.

Should be:
```csharp
if ((!field.HasPresence && sourceField != null) || field.Accessor.HasValue(source))
{
    field.Accessor.SetValue(destination, sourceField);
}
else if (options.ReplacePrimitiveFields)
{
    field.Accessor.Clear(destination);
}
```

**Comment by marner2** [comment]
Here is a minimal test showing the second problem that is fixed by the above code suggestion:
```csharp
[Test]
public void MergeOptionalFieldsWithNullFieldsInSource()
{
    var destination = new MixedRegularAndOptional();
    var source = new MixedRegularAndOptional();

    Assert.False(source.HasOptionalField);
    Assert.False(destination.HasOptionalField);

    Merge(new FieldMaskTree().AddFieldPath("optional_field"),
        source,
        destination,
        new FieldMask.MergeOptions(),
        false);

    Assert.False(destination.HasOptionalField);
}
```

**Comment by jskeet** [comment]
(Another day when I haven't got to this... fortunately I'm running out of higher-priority things to do this week, so I'm *reasonably* hopeful I'll get to this tomorrow. Sorry for the delay.)
