### ISSUE TITLE
Question about extension declarations

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#12719]
In the latest version of `descriptor.proto`, the extension declarations stuff includes the following:
```protobuf
  // go/protobuf-stripping-extension-declarations
  // Like Metadata, but we use a repeated field to hold all extension
  // declarations. This should avoid the size increases of transforming a large
  // extension range into small ranges in generated binaries.
  repeated Declaration declaration = 2 [retention = RETENTION_SOURCE];
```

Is there anything in the `go/protobuf-stripping-extension-declarations` Go link that can be made public or added to the docs site? I did a quick search of the [docs site repo](https://github.com/protocolbuffers/protocolbuffers.github.io) for "declaration" and didn't see anything that looked relevant there.

Also, is `Metadata` some internal type in `descriptor.proto`? Is there any info about it that could be made public so this comment has more context?

Also, the release notes for v23 are bit misleading. In particular, these items in the **Compiler** section imply (to me at least) that the extension declarations feature is enabled in this release:
> * Extension declaration: Enforce that if the extension range has a declaration then all extensions in that range must be declared. This should prevent non-declared extensions from being added. (https://github.com/protocolbuffers/protobuf/commit/5dc171f71eca66579b06d4400ee5c94bfa68947a)
> * Implement "reserved" for extension declaration. (https://github.com/protocolbuffers/protobuf/commit/41287bd5d5373e91277b849e93c7ae2a0238b5c3)
> * Open-source extension declaration definition. (https://github.com/protocolbuffers/protobuf/commit/145900f06c732974af996a28a3e2c211ae104888)

(Particularly that last commit, which shows additional logic added to`DescriptorBuilder::ValidateFieldOptions`).

However, extension declarations are _not_ actually enabled due to eecb4cef1da2b576e62cfa93abe98e8eea4b5065. It might be good to revise the release notes to make this more clear.

Thanks!

**Comment by googleberg** [comment]
@jhump We're in the process of open sourcing extension declarations. We have to wait for an internal cleanup to clear first, then we'll be able to have full documentation and everything. In the meantime, we can clean up the comments at least.

**Comment by jhump** [comment]
> And we're still in the process to open source it and we'll not make it into v24.0

Could you provide a little guidance in the meantime? Is the existing `DescriptorBuilder::CheckExtensionDeclaration` logic still look close to the shape of the validation, once enabled? Also, there is now a `verification_state` field on `ExtensionRangeOptions`. Would I be correct in guessing that misconfigurations of declarations won't be a compiler error until the corresponding extension range's `verification_state == DECLARATION`? (If so, perhaps the default verification state should be a feature, so it can be safely changed in a future edition?)

**Comment by jhump** [comment]
Also, IIUC, there will be a "sidecar" configuration file that contains extension declarations for the options types in `google/protobuf/descriptor.proto`. This is so that creating new extensions/custom options doesn't need to involve a PR that changes `descriptor.proto`. If that is correct, is there any trace of that yet in the open-source codebase? Is it yet known where that configuration will live? Will it be included as a file in the binary distributions, or is it more likely to be linked into the compiler (kind of like how the bytes for the core `google/protobuf/descriptor.proto` descriptors are linked in)? Since the `declaration` field has retention set to source (not runtime), I assume this configuration will be solely a concern of the compiler, not of the runtime.

Sorry to bombard you with questions. I was hoping to get started with implementing this feature in Buf's compiler, so it can be released around the same time as it is released in protoc.

**Comment by shaod2** [comment]
Oh hi Buf, we just had a meeting with ashah and pedge ~10 days ago talking about OSS plan for extension declarations.

There were not many issues with extension declarations, and we were mainly discussing about the special file for descriptor.proto. Can you leave your contact here so that I can give you more details?
