### ISSUE TITLE
Compiling proto files in v22.4 fails in abseil dependency with GCC 11 when Address Sanitizer is enabled

### ISSUE THREAD

**Issue by keith-bennett-airmap** [protocolbuffers/protobuf#12734]
**What version of protobuf and what language are you using?**
Version: :exclamation::stop_sign: [v22.4 with Address Sanitizer enabled](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/bca78e32f293014964a15203ae3472715182b6ac)
Version: :heavy_check_mark::heavy_check_mark: [v22.4 without Address Sanitizer](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/059d262d625f6f29116a439370bf598496492946)

Language: C++

**What operating system (Linux, Windows, ...) and version?**
[Ubuntu 20.04 LTS](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/b9519db3f971f0156706829b6a7e739c697e15a2/docker/ubuntu-2004-toolchain.Dockerfile#L2)

**What runtime / compiler are you using (e.g., python version or gcc version)**
`gcc --version` ->
```
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**What did you do?**
I was trying to determine if v22.4 also includes the stack smashing issue when importing particular proto files ([reported separately](https://github.com/protocolbuffers/protobuf/issues/12732))

It _appears_ that v22.4 resolves the stack smashing issue. However, v22.4 appears to have a separate problem: compiling with Address Sanitizer enabled causes compilation failure when compiling the `.pb.h` and `.ph.cc` generated by `protoc`. Ironically, [the compiler error message indicates a problem with a function named "Sanitizer-Safe Copy"](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/bca78e32f293014964a15203ae3472715182b6ac) :rofl:

Address Sanitizer is an important guard rail for C++ developers.

**What did you expect to see**
:heavy_check_mark: Per initial commit [here](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/e5d2b931dc2f86e68d85ace675050f2739be116d):
`./build.sh` ->
```
Successfully built 55df7a9eb834
Successfully tagged grpc-stacksmash:latest
greeter service created -- no stacksmash
```

**What did you see instead?**
:exclamation: :stop_sign: `./build.sh` ->
```
[ 40%] Building CXX object proto/external/CMakeFiles/proto-external.dir/google/api/field_behavior.pb.cc.o
In file included from /usr/local/include/absl/strings/cord_analysis.h:22,
                 from /usr/local/include/absl/strings/cord.h:82,
                 from /usr/local/include/google/protobuf/io/coded_stream.h:134,
                 from /usr/src/grpc-stacksmash/src/build/proto/external/google/api/field_behavior.pb.h:24,
                 from /usr/src/grpc-stacksmash/src/build/proto/external/google/api/field_behavior.pb.cc:4:
/usr/local/include/absl/strings/internal/cord_internal.h: In copy constructor 'constexpr absl::lts_20230125::cord_internal::InlineData::InlineData(const absl::lts_20230125::cord_internal::InlineData&)':
/usr/local/include/absl/strings/internal/cord_internal.h:821:38: error: call to non-'constexpr' function 'absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const'
  821 |     : rep_(rhs.rep_.SanitizerSafeCopy()) {
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/include/absl/strings/internal/cord_internal.h:771:9: note: 'absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const' declared here
  771 |     Rep SanitizerSafeCopy() const {
      |         ^~~~~~~~~~~~~~~~~
In file included from /usr/local/include/absl/strings/cord_analysis.h:22,
                 from /usr/local/include/absl/strings/cord.h:82,
                 from /usr/local/include/google/protobuf/io/coded_stream.h:134,
                 from /usr/src/grpc-stacksmash/src/build/proto/external/google/protobuf/descriptor.pb.h:24,
                 from /usr/src/grpc-stacksmash/src/build/proto/external/google/protobuf/descriptor.pb.cc:4:
/usr/local/include/absl/strings/internal/cord_internal.h: In copy constructor 'constexpr absl::lts_20230125::cord_internal::InlineData::InlineData(const absl::lts_20230125::cord_internal::InlineData&)':
/usr/local/include/absl/strings/internal/cord_internal.h:821:38: error: call to non-'constexpr' function 'absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const'
  821 |     : rep_(rhs.rep_.SanitizerSafeCopy()) {
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/include/absl/strings/internal/cord_internal.h:771:9: note: 'absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const' declared here
  771 |     Rep SanitizerSafeCopy() const {
      |         ^~~~~~~~~~~~~~~~~
make[2]: *** [proto/external/CMakeFiles/proto-external.dir/build.make:92: proto/external/CMakeFiles/proto-external.dir/google/api/field_behavior.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [proto/external/CMakeFiles/proto-external.dir/build.make:106: proto/external/CMakeFiles/proto-external.dir/google/protobuf/descriptor.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: proto/external/CMakeFiles/proto-external.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Anything else we should know about your project / environment**
See [the stack smashing issue description](https://github.com/protocolbuffers/protobuf/issues/12732) for more information

**Comment by mkruskal-google** [comment]
Hey Keith,

This actually looks like a bug in https://github.com/abseil/abseil-cpp.  All we're doing in our code is including `cord.h`.  I think we should transfer this issue to them

**Comment by mkruskal-google** [comment]
Hey Keith,

What version of Abseil are you using?  It looks like https://github.com/abseil/abseil-cpp/pull/1399 fixed this and made it into 20230125.1, but 20230125.0 is missing the fix

**Comment by keith-bennett-airmap** [comment]
Hi, I have made zero changes to abseil dependency so I am using whatever protobuf comes with. You can see [the protobuf installation script in the Dockerfile](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/bca78e32f293014964a15203ae3472715182b6ac/docker/protobuf-toolchain.Dockerfile#L8-L34)

**Comment by mkruskal-google** [comment]
Ah yes sorry, looks like we were shipping with 20230125.0.rc3 until 22.5.  You can either upgrade to 22.5 or manually update the Abseil version to a later release
