### ISSUE TITLE
iOS Thread-local storage is not supported for the current target. / PROTOBUF_NO_THREADLOCAL not  defined / ThreadLocalStorage not find

### ISSUE THREAD

**Issue by vin-zhou** [protocolbuffers/protobuf#12759]
**What version of protobuf and what language are you using?**
Version: v3.22.3 and later
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS 12.6.3

**What runtime / compiler are you using (e.g., python version or gcc version)**
gnu++14

**What did you do?**
Compiling protobuf, with several errors
1. PROTOBUF_NO_THREADLOCAL not defined but used in thread_safe_arena.h and arena.cc.   Only find the macro GOOGLE_PROTOBUF_NO_THREADLOCAL defined in  platform_macros.h, which is not used anywhere. (In old version, it's used)

2. After adding the define of   PROTOBUF_NO_THREADLOCAL in port_def.h,  error "google/protobuf/arena.cc:493:21: error: no template named 'ThreadLocalStorage' in namespace
      'google::protobuf::internal'
      new internal::ThreadLocalStorage<ThreadCache>();"
Compare with v3.21.3, missing the define of ThreadLocalStorage  in stubs/mutex.h

**What did you expect to see**
No errors, just like version 3.21.3

**Comment by fowles** [comment]
@haberman given that this is mac specific, I suspect it would be easiest for you and isn't likely to be too hard

**Comment by vin-zhou** [comment]
Hi @haberman, could you help to take a look? Thank you very much! cc @fowles

**Comment by haberman** [comment]
What compiler are you using? You put "gnu++14", but there is no GCC version with that name (newest is GCC 12.3).

Can you put the exact repro steps you used to build protobuf? Did you use CMake, Bazel, etc?

**Comment by vin-zhou** [comment]
Hi @haberman, I use macOS with CMake and XCode(14.2).  
1. Run script `cmake .. -G Xcode -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_SYSTEM_NAME=iOS ..` in temp folder under protobuf root folder  to generate probobuf.xcodeproj 
2. Run `xcodebuild -project probobuf.xcodeproj -target libprotobuf-lite -configuration "Release" -sdk "iOS" ARCHS="arm64" ` to get the .a

**Comment by haberman** [comment]
I wasn't able to reproduce this.

Here are the commands I used:

```
$ cmake .. -G Xcode -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_CXX_STANDARD=14 ..
$ xcodebuild -project protobuf.xcodeproj -target libprotobuf-lite -configuration "Release" -sdk "iphoneos16.4" ARCHS="arm64"
```

The build succeeded for me. This is on an M1 Mac.
