### ISSUE TITLE
PHP 8.1 and 8.2 support

### ISSUE THREAD

**Issue by GrahamCampbell** [protocolbuffers/protobuf#12760]
The README at https://github.com/protocolbuffers/protobuf/tree/main/php indicates that PHP 8.0 is supported, but not 8.1 or 8.2.

**Comment by fowles** [comment]
I am sorry, that is out of date.  Our official support for PHP is defined by https://cloud.google.com/php/getting-started/supported-php-versions which we try to keep up to date in https://github.com/google/oss-policies-info/blob/main/foundational-php-support-matrix.md.  We will adjust the readme

**Comment by fowles** [comment]
@GrahamCampbell yes, we should already support it 8.2.  Please open bug for any incompatibilities you find with 8.2
