### ISSUE TITLE
Include special chars in a protobuf message in java

### ISSUE THREAD

**Issue by amar1019** [protocolbuffers/protobuf#12840]
I want to include special chars like � and <nbsp> in a protobuf message. Protobuf is converting them into \302\240 when building the message. Is there any way we can build the message with these chars. One option is to use bytes filed in the proto. I want to other options

**Comment by acozzette** [comment]
Proto `string` fields are required to store valid UTF8, so if you want to store non-UTF8 data then you will need to use `bytes` fields instead.
