### ISSUE TITLE
how to modify environment variable for protobuf_generate custom command

### ISSUE THREAD

**Issue by abdelmaged** [protocolbuffers/protobuf#12872]
I'm using CMake macro protobuf_generate, and I need to modify LD_LIBRARY_PATH environment variable to include some library directories needed to run protoc, however I cannot find a way to do this, and the custom command is failing due to missing libraries.

Usually, for other used custom commands that needs env vars modfications, I'm doing something like ${CMAKE_COMMAND} -E env --modify LD_LIBRARY_PATH=path_list_prepend:<my_path>

**Comment by mkruskal-google** [comment]
protobuf_generate should already link everything that needs to get linked in to produce gencode (e.g. just protoc I believe).  What are you trying to link in?  The only use-case I can see for this is plugins, which can be specified via the PLUGIN arguments (see docs/cmake_protobuf_generate.md)

Also, what is `${CMAKE_COMMAND}` in your example?  It's not clear to me if you're trying to run this from a cmake file or from the commandline.

**Comment by abdelmaged** [comment]
I'm trying to put protoc shared library dependencies into LD_LIBRARY_PATH, mainly libtstdc++.so.

for `${CMAKE_COMMAND}`, I was giving an example of how I do this for other custom commands `add_custom_command` that required certain shared library path in LD_LIBRARY_PATH from CMakeList.txt files.

**Comment by mkruskal-google** [comment]
`protobuf_generate` depends on `protoc` though, so it should include any shared library dependencies already when it's called from cmake.  Can you give reproduction steps for the issue you're seeing?

**Comment by DaveAbraham00** [comment]
I hope it's acceptable to piggy back on this question... I'm running into the same issue.

I'm using 

protobuf_generate(TARGET protos LANGUAGE grpc GENERATE_EXTENSIONS .grpc.pb.h .grpc.pb.cc PLUGIN "protoc-gen-grpc=${grpc_cpp_plugin_location}")

which is using the protoc-gen-grpc plugin.  That plugin requires libgrpc_plugin_support.so which it can't seem to find.  If I manually set LD_LIBRARY_PATH outside of the cmake call, it works.  I'd like to have cmake expose that library path and then set LD_LIBRARY_PATH automatically.
