### ISSUE TITLE
Add c# serializationDeterministic 

### ISSUE THREAD

**Issue by fmg-lydonchandra** [protocolbuffers/protobuf#12881]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
DeterministicSerialization for c#

**Describe the solution you'd like**
Same API CodedOutputStream.SetSerializationDeterministic for C# binding (same as Java/Ruby/Python API)

**Describe alternatives you've considered**
PInvoke into C++ library

**Additional context**
None

Is there any technical reason this has not been implemented for c# ?

**Comment by jskeet** [comment]
I'd never heard of it before, but I don't see any reason why it can't be implemented for C#.

Looking at the Java implementation, it looks like this is *just* about the order in which map entries are serialized - is that your understanding as well?

I doubt that I'll have the time to work on it as a feature any time soon, but I'd happily review a pull request.

**Comment by jskeet** [comment]
Fixed in #13160
