### ISSUE TITLE
Interest in modernizing the python code (use new py3.7+ language features)?

### ISSUE THREAD

**Issue by thisch** [protocolbuffers/protobuf#12896]
I hope that it is fine that this is a feature request .I can post the question also on the mailing-list if desired.

Is there interest in cleaning up the python bindings to make use of new language features that are supported by the oldest python version that is currently supported by protobuf (=python3.7)?

The code could be automatically cleaned up by using tools like e..g `pyupgrade --py3-only --py37-plus` or `ruff`. 

Some things that would be changed by pyupgrade:

* Call `super()` without any args
* Use f-strings instead string-formatting via `%` or `.format()`
* Removal of the unicode literal, which is no longer needed
* Use new-style classes (classes that don't inherit from `object`)
* Use dict comprehension instead of calling `dict(...)` with a iterator (This has a minor performance benefit, since now lookup of the global `dict` is needed)
* Use `yield from`
* ...

**Comment by haberman** [comment]
Yes, I think that modernizing within the range of Python versions we support would be very welcome. Feel free to send a PR.

**Comment by fowles** [comment]
Sorry that this slipped between the cracks.  I have asked @anandolee to take a look
