### ISSUE TITLE
Generated pb.cc file references unknown WriteInt32ToArrayWithField

### ISSUE THREAD

**Issue by AlmeidaVitor** [protocolbuffers/protobuf#12890]
**Version with issue:** 22.4.0 and 23.0.0 and 23.0.1
**Language:** C++
**OS:** Windows 10 - 22H2
**Development environment:** VS 2022

**Issue:** 

The protobuf files generated by "protoc.exe" differ between debug "protoc.exe" and release "protoc.exe", and in the debug version they generate references to unknown WriteInt32ToArrayWithField

**When Issue first appeared:** 

22.4.0 was the first version with this issue. Older versions are working fine.

**How to reproduce:**

1. Have a proto file that declares something using **int32**. Something like the following:

message _MyMessage {
	int32 propertyOfMessage = 1;
}

2. Generate the pb.h and the pb.cc files.
In release mode. and in older version debug mode you would get something containing this:

   // int32 propertyOfMessage = 1;
  if (this->_internal_propertyOfMessage() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_propertyOfMessage());
  }

in the new debug ones you get something like this:

  // int32 propertyOfMessage  = 1;
  if (this->_internal_propertyOfMessage() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_propertyOfMessage(), target);
  }

The problem we are facing is that WriteInt32ToArrayWithField is not defined anywhere.

**Comment by acozzette** [comment]
I suspect that you might be mixing different versions of protoc and the runtime library. For C++ these versions have to exactly match. For example if you use protoc 23.0 to generate code then you will have to build that against version 3.23.0 of the library.

**Comment by AlmeidaVitor** [comment]
We are not mixing different versions. We use the same version to generate both the code and to build against.

**Comment by acozzette** [comment]
Are you sure you're not mixing versions? The `WriteInt32ToArrayWithField()` function was added fairly recently in 97c351319ffa9715ed11a883c4adbaadf63a2fcc on May 3. The only possibility that makes sense to me is that you're using a protoc version that picked up that change but building against a runtime that does not include it. Are you building protoc from source or using a prebuilt binary from our release page?
