### ISSUE TITLE
ImportError: cannot import name 'builder'

### ISSUE THREAD

**Issue by jiuzhou0102** [protocolbuffers/protobuf#12938]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
using python 
turn into ptotobuf.py but there are some questions to use it, as following:
from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder'

The import modules are as follows.
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

**Comment by anandolee** [comment]
Looks like it is using an old protobuf python runtime with new generated code.
Upgrade the protobuf python runtime will resolve this error
