### ISSUE TITLE
Some symbols in `libprotobuf`'s public API are hidden

### ISSUE THREAD

**Issue by coryan** [protocolbuffers/protobuf#12932]
**What version of protobuf and what language are you using?**

Version: 23.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux, Fedora 37.  Probably applies to all Linux variants and 

**What runtime / compiler are you using (e.g., python version or gcc version)**

GCC 12.2

**What did you do?**

This was motivated by https://github.com/conda-forge/protobuf-feedstock/pull/191#issuecomment-1569020333.  It seems the "c++ backend" for Python is not loadable when compiled as a .so.  Maybe because some symbols are hidden:

https://github.com/conda-forge/protobuf-feedstock/pull/191#issuecomment-1569108909

**What did you expect to see**

I expect that public symbols are not hidden.  `google::protobuf::io::SafeDoubleToFloat(double)` seems like a public symbol.  I would have expected it to be exported.

**What did you see instead?**

The symbol is hidden:

```
nm /usr/local/lib64/libprotobuf.so.23.2.0 | c++filt | grep SafeDoubleToFloat
000000000018f350 t google::protobuf::io::SafeDoubleToFloat(double)
```
**Anything else we should know about your project / environment**

N/A

This reminds me of: #12618

**Comment by h-vetinari** [comment]
Thanks for opening this issue @coryan. One other aspect about having the protobuf-bindings built on top of shared libs is that it's missing the now-required linkage to abseil. In particular, our link check infrastructure shows (at least) `absl_spinlock_wait` and `absl_strings` should be there:
```
   INFO (protobuf,lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libprotobuf.so.23.2.0 found in conda-forge::libprotobuf-4.23.2-hd1fb520_1
   INFO (protobuf,lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libabsl_spinlock_wait.so.2301.0.0 found in conda-forge::libabseil-20230125.2-cxx17_h59595ed_2
   INFO (protobuf,lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libabsl_strings.so.2301.0.0 found in conda-forge::libabseil-20230125.2-cxx17_h59595ed_2
```

**Comment by coryan** [comment]
Partially address by #12957.  I suspect there are more hidden symbols that should not be.  The fixes are typically easy, but I have no way to tell what is consider part of the public API (and thus should not be hidden) and what is "internal only" and should be hidden.

**Comment by h-vetinari** [comment]
Quoting @coryan from above:

> Partially address by #12957. I suspect there are more hidden symbols that should not be. The fixes are typically easy, but I have no way to tell what is consider part of the public API (and thus should not be hidden) and what is "internal only" and should be hidden.

To my understanding this is still current.

**Comment by h-vetinari** [comment]
I guess it's fine to close this, and I'll open another issue if we run into it again.

**Comment by bartdesmet** [comment]
We hit the same issue for

hidden symbol `_ZNK6google8protobuf11MessageLite16SerializeToArrayEPvi' in /var/local/ext/x64/bin/lib/libprotobuf.a([message_lite.cc](http://message_lite.cc/).o)
