### ISSUE TITLE
Protobuf is missing a logo

### ISSUE THREAD

**Issue by quazgar** [protocolbuffers/protobuf#12956]
**Describe the problem you are trying to solve.**

When writing about protobuf or giving talks and lectures, I can only give the name.  If there was a catchy logo, that could be used instead.

**Describe the solution you'd like**

A recognizable logo that stands for Protobuf. Preferably as SVG.

**Describe alternatives you've considered**

A short web search gives a few results, all "still" featuring the Google colors.  Maybe one of those could be changed around enough so that is can be used without trademark or copyright issues?

**Comment by perezd** [comment]
Thanks for the feedback! We totally agree, and we're working on it!
