### ISSUE TITLE
Add built-in proto files that support HTTPAPI

### ISSUE THREAD

**Issue by itbencn** [protocolbuffers/protobuf#12968]
**What language does this apply to?**
Proto3、C#/NET7

**Describe the problem you are trying to solve.**
In NET7, the GRPC server can support both GRPC and `JSON Web API` requests based on `Microsoft.AspNetCore.Grpc.Swagger` packets
But it is necessary to 
```
import "google/api/annotations.proto";
import "http.proto";
```
in each proto file
These two files are not built-in, which makes it very troublesome to connect them in the development environment

**Describe the solution you'd like**
Build the aforementioned proto files into the protobuf project, just like `google/protobuf/descriptor.proto`

**Additional context**
[annotations.proto](https://github.com/dotnet/aspnetcore/blob/main/src/Grpc/JsonTranscoding/test/testassets/Sandbox/google/api/annotations.proto)
[http.proto](https://github.com/dotnet/aspnetcore/blob/8b601c3a73ba66de4e6ca35530b5d32a48c76c5b/src/Grpc/JsonTranscoding/test/testassets/Sandbox/google/api/http.proto)
<img width="795" alt="Snipaste_2023-06-03_00-22-50" src="https://github.com/protocolbuffers/protobuf/assets/42700064/09237583-afa6-48b1-ba42-96e4abce3ede">

**Comment by jskeet** [comment]
No, these are fundamentally not part of protobuf. Microsoft may well be able to add to the gRPC tooling to make the API-oriented protos easier to consume, but they really don't belong in this project I'm afraid.

**Comment by itbencn** [comment]
What I mean is to embed two proto files into the protobuf project
According to the [google.api](https://cloud.google.com/service-infrastructure/docs/service-management/reference/rpc/google.api#http) document
The above two files are required during the implementation of `gRPC/REST` mapping process

**Comment by jskeet** [comment]
But those are protos that simply don't belong in the protobuf project. Protobuf and gRPC are entirely distinct - indeed, even gRPC doesn't fundamentally depend on protobuf, even though it's by far the most common payload type.
