### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool: duplicate file name

### ISSUE THREAD

**Issue by BulNik** [protocolbuffers/protobuf#13013]
**What version of protobuf and what language are you using?**
protobuf = 4.23.2

Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS Ventura 13.2.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.10.6

**What did you do?**
1. Compile pb2.py/pb2.pyi/pb2_grpc.py file with command `python3 -m grpc_tools.protoc -I=  --python_out= --pyi_out= --grpc_python_out= path_to_proto`
2. run script (tests with pytest)
3. Getting this error:(

**What did you expect to see**
successfully run script

I tried updating the protobuf version to the latest (4.23.2), but this solution did not help

**Comment by deannagarcia** [comment]
Can you post the full error logs that you're seeing?
