### ISSUE TITLE
Rename shadowed variables

### ISSUE THREAD

**Issue by 4kangjc** [protocolbuffers/protobuf#13037]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
```cpp
# Compile failed
$ bazel build --copt='-Wshadow-all' :protoc :protobuf
$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**What did you expect to see**
Shadowed variables can cause readability issues. Ensure a shadowed
variable isn't used in header files which may be used in a dependent
project that explicitly disables them.
`bazel build --copt='-Wshadow-all' :protoc :protobuf` executed successfully.

**Comment by deannagarcia** [comment]
Thanks for reporting this issue! I was able to successfully reproduce it and I see errors with shadowed variables.

For future record, here is an example of the logs:
```
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/protobuf_lite/google/protobuf/serial_arena.h: In constructor 'google::protobuf::internal::ArenaBlock::ArenaBlock(google::protobuf::internal::ArenaBlock*, size_t)':
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/protobuf_lite/google/protobuf/serial_arena.h:71:39: error: declaration of 'size' shadows a member of 'google::protobuf::internal::ArenaBlock' [-Werror=shadow]
   71 |   ArenaBlock(ArenaBlock* next, size_t size)
      |                                ~~~~~~~^~~~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/protobuf_lite/google/protobuf/serial_arena.h:86:16: note: shadowed declaration is here
   86 |   const size_t size;
      |                ^~~~
```

**Comment by fowles** [comment]
I'm sorry, but we don't support compiling with this warning enabled.  The best thing you can do here is to modify [port_def.inc](https://github.com/protocolbuffers/protobuf/blob/381b31e9c93614270491c3fb007e76a308699d35/src/google/protobuf/port_def.inc#L1023).  Feel free to send a PR

**Comment by 4kangjc** [comment]
> I'm sorry, but we don't support compiling with this warning enabled.  The best thing you can do here is to modify [port_def.inc](https://github.com/protocolbuffers/protobuf/blob/381b31e9c93614270491c3fb007e76a308699d35/src/google/protobuf/port_def.inc#L1023).  Feel free to send a PR

OK

**Comment by 4kangjc** [comment]
![image](https://github.com/protocolbuffers/protobuf/assets/73515066/20f107ee-c3f9-4c26-82ed-57901e38c047)

I feel that the naming of this variable called `option` is not very standardized.

**Comment by 4kangjc** [comment]
![image](https://github.com/protocolbuffers/protobuf/assets/73515066/2c2a53a0-3fa9-4d57-a00c-58588d111087)

**Comment by fowles** [comment]
Renaming existing violations won't stop backsliding in the future, I would strongly prefer a PR that suppresses the warnings.

**Comment by 4kangjc** [comment]
> 

OK, I see.

**Comment by fowles** [comment]
started https://github.com/protocolbuffers/protobuf/pull/13088 to cherry pick this back to 23.x.  We won't spin a release specifically for this, but it will be picked up in the next 23.x point release

**Comment by 4kangjc** [comment]
> started #13088 to cherry pick this back to 23.x. We won't spin a release specifically for this, but it will be picked up in the next 23.x point release

OK, I see.

**Comment by fowles** [comment]
Don't worry, we will spin a point release for https://github.com/protocolbuffers/protobuf/pull/13075 once it lands, so I don't think you have long to wait
