### ISSUE TITLE
How to create a message without using code generation by CPP

### ISSUE THREAD

**Issue by qiqistyle** [protocolbuffers/protobuf#13036]
I want to use protobuf characters and use a class extends the message class  to avoid define a proto file . But, I find out that it is hard for me to pass the compile. 

**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
**proto3**
If it's about generated code change, what programming language?
**CPP**
**Describe the problem you are trying to solve.**
here are my cpp code
```CPP
#include<iostream>
#include<google/protobuf/message.h>
class Person : public message
{ 
public:
    int id;
    int age;
    string name;
};
int main()
{
   Person person;
   person.id=1;
   person.age=2;
   person.name="test";
   string str;
   person.SerializeToString(str);
   cout<<str<<endl;
}

```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deannagarcia** [comment]
Your proto definitions should be in a `.proto` file and not directly in a `.cc` file. Our [website](https://protobuf.dev/) has a [C++ tutorial](https://protobuf.dev/getting-started/cpptutorial/) that should help you get started using protobuf in C++.
