### ISSUE TITLE
Google_protobuf failed to run test due to error: Expected equality of these values 0 return_code_  Which is: 1

### ISSUE THREAD

**Issue by Eva-An** [protocolbuffers/protobuf#13073]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?
Windows Server 2022 Datacenter 21H2

**What runtime / compiler are you using (e.g., python version or gcc version)**
msvc
**What did you do?**
1. Open a VS2022 x64 command prompt
2. git clone https://github.com/google/protobuf F:\gitP\google\protobuf
3. cd F:\gitP\google\protobuf
4. git fetch --recurse-submodules=no --force
5. git reset --hard ad677f3
6. git remote prune origin
7. git submodule sync
8. git submodule foreach git reset --hard
9. git submodule foreach git clean -xdf
10. git submodule update --init --recursive
11. cd F:\gitP\google\protobuf\build_amd64
12. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..
13. cd F:\gitP\google\protobuf\build_amd64_Itcg
14. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_EXE_LINKER_FLAGS="/LTCG" -DCMAKE_C_FLAGS="/GL" -DCMAKE_CXX_FLAGS="/GL" ..
15. cd F:\gitP\google\protobuf\build_amd64
16. msbuild /p:Platform=x64 /p:Configuration=Release protobuf.sln /t:Rebuild
17. cd F:\gitP\google\protobuf\build_amd64_Itcg
18. msbuild /p:Platform=x64 /p:Configuration=Release protobuf.sln /t:Rebuild
19. cd F:\gitP\google\protobuf\build_amd64\Release
20. .\tests.exe --gtest_filter=-BootstrapTest.GeneratedDescriptorMatches:RubyGeneratorTest.GeneratorTest:RubyGeneratorTest.GeneratorTest:TextFormatTest.Basic:TextFormatExtensionsTest.Extensions:TextFormatMapTest.Sorted:CsharpBootstrapTest.GeneratedCsharpDescriptorMatches:BootstrapTest.GeneratedFilesMatch:TextFormatMapTest.DynamicMessage:RubyGeneratorTest.Proto2GeneratorTest:IoTest.LargeOutput:AnyTest.TestPackFromSerializationExceedsSizeLimit:ArenaTest.SpaceAllocated_and_Used:ArenaTest.BlockSizeSmallerThanAllocation:MapImplTest.RandomOrdering
21. .\lite-test.exe
22. cd F:\gitP\google\protobuf\build_amd64_Itcg\Release
23. .\tests.exe --gtest_filter=-BootstrapTest.GeneratedDescriptorMatches:RubyGeneratorTest.GeneratorTest:RubyGeneratorTest.GeneratorTest:TextFormatTest.Basic:TextFormatExtensionsTest.Extensions:TextFormatMapTest.Sorted:CsharpBootstrapTest.GeneratedCsharpDescriptorMatches:BootstrapTest.GeneratedFilesMatch:TextFormatMapTest.DynamicMessage:RubyGeneratorTest.Proto2GeneratorTest:IoTest.LargeOutput:AnyTest.TestPackFromSerializationExceedsSizeLimit:ArenaTest.SpaceAllocated_and_Used:ArenaTest.BlockSizeSmallerThanAllocation:MapImplTest.RandomOrdering
24. .\lite-test.exe

**What did you expect to see**
Test pass
**What did you see instead?**
[ RUN      ] CommandLineInterfaceTest.DescriptorSetOptionRetention
F:\gitP\google\protobuf\src\google\protobuf\compiler\command_line_interface_unittest.cc(426): error: Expected equality of these values:
  0
  return_code_
    Which is: 1
F:\gitP\google\protobuf\src\google\protobuf\compiler\command_line_interface_unittest.cc(427): error: Expected equality of these values:
  ""
  error_text_
    Which is: "src: warning: directory does not exist.\ngoogle/protobuf/descriptor.proto: File not found.\nfoo.proto:3:11: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\nfoo.proto:4:18: \"google.protobuf.FileOptions\" is not defined.\nfoo.proto: \"google.protobuf.FileOptions\" is not defined.\n"
With diff:
@@ -1,1 +1,5 @@
-""
+src: warning: directory does not exist.
+google/protobuf/descriptor.proto: File not found.
+foo.proto:3:11: Import \"google/protobuf/descriptor.proto\" was not found or had errors.
+foo.proto:4:18: \"google.protobuf.FileOptions\" is not defined.
+foo.proto: \"google.protobuf.FileOptions\" is not defined.\n

F0000 00:00:1686745652.705046   15300 command_line_interface_unittest.cc:508] Check failed: File::GetContents(path, &file_contents, true) is OK (NOT_FOUND: Could not open file) 
*** Check failure stack trace: ***
    @   00007FF64D99062D  (unknown)
    @   00007FF64DF5201C  (unknown)
    @   00007FF64DF3A010  (unknown)
    @   00007FF64DF3A786  (unknown)
    @   00007FF64DF4BC17  (unknown)
    @   00007FF64DF520BB  (unknown)
    @   00007FF64DF4A6EA  (unknown)
    @   00007FF64DF7B070  (unknown)
    @   00007FFB27C74DE0  (unknown)
    @   00007FFB291DE3DB  (unknown)
**Anything else we should know about your project / environment**

**Comment by pranav-vm** [comment]
Hi I may suggest you to execute it from the root location of the folder than from the directory. i.e, if the test binaries are built in the "Build" directory, it's better to run "./build/tests" than "cd build && ./tests" as the path for descriptor is hardcoded in the testcase.
