### ISSUE TITLE
`$dllexport_decl$` is missing in generated `.pb.cc`

### ISSUE THREAD

**Issue by owent** [protocolbuffers/protobuf#13084]
**What version of protobuf and what language are you using?**
Version: v21/v23
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows,Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

GCC 13, GCC 4.8, MSVC 19.36

**What did you do?**

1. Using `--cpp_out=dllexport_decl=XXX_API:<OUTPUT DIR>`.
2. Set the visibility to hidden.
3. Build generated `.pb.cc` as shared libraries.

**What did you expect to see**

Linking success.

**What did you see instead?**

Unresolved reference to `PACKAGE::_MESSAGE_default_instance_`.

**Anything else we should know about your project / environment**

`$dllexport_decl$` is missing for default instance in generated `.pb.cc`.

**Comment by deannagarcia** [comment]
Can you provide some more details here? What version of C++ are you using? What's the full command you are running? And can you copy over error logs?

**Comment by fowles** [comment]
They sent a PR that I am already reviewing, so no need for details

**Comment by owent** [comment]
> Can you provide some more details here? What version of C++ are you using? What's the full command you are running? And can you copy over error logs?

For the usage in our project.

1. We write a message in proto file , for example `message DBattleAffix {...}` in `affix.proto`
2. Generate `affix.pb.h` and `affix.pb.cc` with `protoc --cpp_out=dllexport_decl=TGF_BATTLE_PROTOCOL_API:$SOURCE_DIR` and build them as a dll and define `TGF_BATTLE_PROTOCOL_API=__declspec(dllexport)`.(Unreal Engine plugin on Windows)
3. In another dll(another Unreal Engine plugin on Windows), we use the generated header file above (`affix.pb.h`) and  define `TGF_BATTLE_PROTOCOL_API=__declspec(dllimport)` .
4. When linking, it shows `TGFBattleUtility.lib(BattleAffixAlgorithm.obj): Error LNK2001: unresolved external symbol "struct tgf::DBattleAffixDefaultTypeInternal tgf::_DBattleAffix_default_instance_" (?_DBattleAffix_default_instance_@tgf@@3UDBattleAffixDefaultTypeInternal@1@A)`


I think there is similar problems when we build these `.pb.cc` files with `-fvisibility=hidden` and define `TGF_BATTLE_PROTOCOL_API=__attribute__((visibility("default")))` , but I didn't test it yet.
