### ISSUE TITLE
Add method to set the value of 'allow_unknown_enum_' on text_format.h 

### ISSUE THREAD

**Issue by yxjeag** [protocolbuffers/protobuf#13098]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
proto3
If it's about generated code change, what programming language?
C++
**Describe the problem you are trying to solve.**
I want to ignore the unknown enum when parse the text-format proto by using `google::protobuf::TextFormat::Parser`, but here not exsist the method to control it, only had a private bool variable called `allow_unknown_enum_` on [address]( https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/text_format.h#L763).

**Describe the solution you'd like**
Add a method like `AllowUnknownEnum(bool allow)` to contorl  the value of `allow_unknown_enum_`.
**Describe alternatives you've considered**
Here seems no alternatives way to solve the compatibility of text-fomat proto parsing.
**Additional context**
It is a private variable of `google::protobuf::TextFormat::Parser`: 
`bool allow_unknown_enum_`

**Comment by mkruskal-google** [comment]
Can you expand on why you want this?  textproto isn't designed to be a wire-format so this is mostly just adding a dangerous API that will silence error-checking
