### ISSUE TITLE
Add new Struct-like type that supports integers

### ISSUE THREAD

**Issue by erinboyle** [protocolbuffers/protobuf#13094]
We're using protobuf 2 to pass messages python <-> scala. I need to pass flexible nested dictionaries from python and their integer values need to stay integers, so struct won't work.

I see you have [good reasons you can't add int to Struct Values](https://github.com/protocolbuffers/protobuf/issues/10255#issuecomment-1185654033). But what if you added a new type instead? (Porting my comment over.) E.g. StructWithInt, which would prioritize supporting int to the exclusion of whichever other constraints are in the way.

Thanks for considering. Would be excited to migrate away from passing my proto message as the string, `json.dumps(dict)`.

**Comment by fowles** [comment]
generally speaking, we avoiding adding new "well known types" they tend to have a fairly high long term maintenance cost for us.  I recommend creating the type you need local toyour particular project.
