### ISSUE TITLE
Allow reduction of allocations to Serialization in Java

### ISSUE THREAD

**Issue by NikolayMetchev** [protocolbuffers/protobuf#13102]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
In a single threaded java application I want to reduce allocations during serialization

**Describe the solution you'd like**
Adding a reset() method to com.google.protobuf.CodedOutputStream to allow the object to be re-used with the same underlying buffer should significantly reduce the number of allocations.

**Describe alternatives you've considered**
Copy paste the code and modify it myself 

**Additional context**

**Comment by googleberg** [comment]
@NikolayMetchev do you have any benchmarks to show the benefits of this?
