### ISSUE TITLE
Can we cross-compile it with RISC-V?

### ISSUE THREAD

**Issue by dayeol** [protocolbuffers/protobuf#13114]
Hi,

I am wondering if the library can work with cross compilers, especially with the RISC-V toolchain.
Can we compile libprotobuf in RISC-V, ideally statically?

Thanks!

**Comment by fowles** [comment]
This should be entirely doable.

**Comment by dayeol** [comment]
Thanks!
I think I can add RISC-V toolchain to this file 
https://github.com/protocolbuffers/protobuf/blob/adb2c4b415c35cda3e4394384ec579ea8dd8ec92/toolchain/BUILD.bazel#L7

Does this seem a correct approach to you?

**Comment by fowles** [comment]
yup, that seems correct
