### ISSUE TITLE
MapFieldIter PHP segfault

### ISSUE THREAD

**Issue by minituex** [protocolbuffers/protobuf#13116]
**What version of protobuf and what language are you using?**
Version: protobuf version 3.23.3
Language: PHP 7.4

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.5 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**What did you do?**

* proto defintion of  contain map field `map<uint64, MyObject> my_object_by_id`
* checking the generated php code for this reveals that `MyObjectById` object contains MapField. 
* Using this with ->getIterator() returns `MapFieldIter`. checking this object, it contains methods `current()` and `key()` among others
* using either of the two mentioned above, results in php breaking (segfault)

**What did you expect to see**
* using ->key(), I expect to  get the key ;)

**What did you see instead?**

error message: `php: /tmp/pear/temp/protobuf/php-upb.c:2791: upb_strtable_iter_key: Assertion '!upb_strtable_done(i)' failed.`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I can only post abstract code/information as the project I am using this with, is not in the public domain. I hope you can understand and I will be happy to provide anything else that might help, as long as I can do so in a somewhat abstract matter.

**Comment by fowles** [comment]
While I understand that you cannot post your entire project, is it possible for you to create a minimal reproduction?

**Comment by minituex** [comment]
I create an example project [here](https://github.com/minituex/protbuf-error-example). I hope this helps and you can work with it. If you need any more info, I am happy to help!

**Comment by minituex** [comment]
Any updates on this? Questions about the issue, the repo?

**Comment by minituex** [comment]
please keep this open as the issue persits
