### ISSUE TITLE
Add option to generate lightweight Model inner class (or constant static field map) for swagger

### ISSUE THREAD

**Issue by linxuhao** [protocolbuffers/protobuf#13140]
**Java, and maybe others**
If it's a proto syntax change, is it for proto2 or proto3? **add an option** of code generation
If it's about generated code change, what programming language? **Java**

**Describe the problem you are trying to solve.**
Recently I've been working with GRPC backend servers and the flutter front end.
The front sends rest requests to the backend, while the backend servers communicate with protobuf between them.
When implementing a swagger for the front developers, I see using the protobuf generated Java class as schema in leads to unresponsive swagger whenever I try to see the definition of a given API (probably too many definitions with all the parents classes)

For example: 
@PostMapping("/edit")
public String edit(@RequestBody @Schema(implementation = **ProtoMessage**.class) String json)

With maven dependency 
springdoc-openapi-ui 1.6.1
And spring-boot 2.7.0
The generated swagger will become unresponsive when I click on the API /edit

**Describe the solution you'd like**
I would like that when protobuf is generating classes, it can generate a lightweight Model inner class, or a lightweight json model static field (for languages like python)
So when trying to use it on swagger, I can simply do as below

@PostMapping("/edit")
public String edit(@RequestBody @Schema(implementation = ProtoMessage.**Model**.class) String json)

**Describe alternatives you've considered**
What I've been using, is to automatically copy the generated *OrBuilder.java files, and do some regex so it becomes *Model.java files, which contains only the necessary getter of the real fields for given class, then use them in code

For example 
@PostMapping("/edit")
public String edit(@RequestBody @Schema(implementation = **ProtoMessageModel**.class) String json)

**Additional context**
I can work on adding the feature if someone is willing to guide me

**Comment by linxuhao** [comment]
My actual process of generation in pom.xml (using Maven) 

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <id>java</id>
                        <configuration>
                            <target name="Generate Java Models for Swagger">
                                <copy todir="${basedir}/src/generated/java/example/model">
                                    <fileset dir="${basedir}/src/generated/java/example/proto">
                                        <include name="**/*OrBuilder.java"/>
                                    </fileset>
                                    <globmapper from="*OrBuilder.java" to="*Model.java"/>
                                    <filterchain>
                                        <replaceregex pattern="example\.proto" replace="example.model"/>
                                        <replaceregex pattern=".*get.*OrBuilder\(\)\;" replace=""/>
                                        <replaceregex pattern="OrBuilder extends" replace="Model"/>
                                        <replaceregex pattern="com.google.protobuf.MessageOrBuilder" replace=""/>
                                        <replaceregex pattern="Message " replace="MessageModel "/>
                                        <replaceregex pattern="Message\>" replace="MessageModel>"/>
                                        <replaceregex pattern=".*OrBuilder.*" replace=""/>
                                        <replaceregex pattern="      int index\)\;" replace=""/>
                                        <replaceregex pattern=".*ByteString.*" replace=""/>
                                        <replaceregex pattern=".*get.*Bytes\(.*" replace=""/>
                                        <replaceregex pattern="int.*get.*Value\(.*" replace=""/>
                                        <replaceregex pattern="Generated by the protocol buffer compiler." replace="Generated by the protocol buffer compiler. Modified by antrun plugin."/>
                                        <replaceregex pattern="example\.model\.ExempleEnum" replace="example.proto.ExempleEnum"/>
                                    </filterchain>
                                </copy>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by fowles** [comment]
I don't think this is something we would have the bandwidth to guide you through or even a desire to accept were it offered in the short term.

My suggestion is to refactor your `.proto` files a bit to not use nested messages.  Then you can have client and server views for the same files some of which do not have fields as needed.

Keeping the fields in sync is slightly awkward at the moment, but we have plans to release a tool called Prototiller to help with this in the future.
