### ISSUE TITLE
C++ HasBits with 64 bit generates 'argument': conversion from 'size_t' to 'int'

### ISSUE THREAD

**Issue by lbermes** [protocolbuffers/protobuf#13143]
Version: 3.21.12 (build via vcpkg)
Language: C++

Windows 10 latest version

VC 2022 64 bit latest runtime version

I builded it via vcpkg with x86 and x64.
Then I used it in my project to create classes from proto files.
With x86 I see no issue but now I started to switch to 64 bit and see for every _InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) 
here for the Or
---
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
---

the following warning
8>XXXX\protobuf-3.21.12\include\google\protobuf\has_bits.h(84,30): message : see reference to class template instantiation 'google::protobuf::internal::HasBits<1>' being compiled (compiling source file XXXX\vc\Debug.x64\pb\message\APIClientLocalization.pb.cc)
8>XXXX\protobuf-3.21.12\include\google\protobuf\has_bits.h(74,66): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data (compiling source file XXXX\vc\Debug.x64\pb\message\YYYYY.pb.cc)
8>XXXX\protobuf-3.21.12\include\google\protobuf\has_bits.h(73,8): message : while compiling class template member function 'void google::protobuf::internal::HasBits<1>::Or(const google::protobuf::internal::HasBits<1> &)' (compiling source file XXXX\vc\Debug.x64\pb\message\YYYYY.pb.cc)
8>XXXX\vc\Debug.x64\pb\message\YYYYY.pb.cc(823,23): message : see the first reference to 'google::protobuf::internal::HasBits<1>::Or' in 'ASC::Google::Messages::ZZZZZ_ZZZZ::_InternalParse'

it refers to
template <>
inline bool HasBits<1>::empty() const {
  return !has_bits_[0];
}

and
void Or(const HasBits<doublewords>& rhs) {
    for (size_t i = 0; i < doublewords; i++) has_bits_[i] |= rhs[i];
  }

Reason seems in bot cases to be that the operator[](int index) uses an int instaed of size_t

It is for debug and release the same

**Comment by lbermes** [comment]
Sorry for the formatting didn't see that some parts were marked bold

**Comment by lbermes** [comment]
I tested using int instead of size_t and this keeps the compiler quite and still works

**Comment by fowles** [comment]
We do not support compiling with arbitrary warning enabled.  We will accept patches to fix these warning where reasonable, but you can expect regressions in the long term.

**Comment by lbermes** [comment]
Thank you for your response. As I'm porting some 32 bit software to 64bit it was essential for me to check the size mismatches. I will create a pull request with my changes.

**Comment by lbermes** [comment]
Will be processed via #13200

**Comment by lbermes** [comment]
Seems, it was a mistake to close this too early as a bot closed the merge before it was done

**Comment by fowles** [comment]
https://github.com/protocolbuffers/protobuf/commit/532d2a24800890890d764e2de8fc2716eb3213e9 appears to have merged this, so I think it is done.
