### ISSUE TITLE
[MessageToDict] field.message_type.GetOptions() caused segmentation fault

### ISSUE THREAD

**Issue by yananzhao689** [protocolbuffers/protobuf#13151]
**What version of protobuf and what language are you using?**

Version: 4.23.3

Language: Python

**What operating system (Linux, Windows, ...) and version?**

Mac (13.2)

Linux (Linux version 5.15.49-linuxkit)

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.11.4

**What did you do?**

1. Install below python libs:

```shell
python3 -m pip install grpcio-tools==1.53.0
python3 -m pip install protobuf==4.23.3
```

2. Prepare the descriptor.proto file got from <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto>

3. Prepare a proto file named as pb.proto, codes as below:

```text
syntax = "proto3";
import "descriptor.proto";

message Rows {
    repeated uint64 mask = 2;
}

message PushData {
    Rows DataSet = 4;
}
```

4. Use grpcio-tools(1.53.0) command to compile these 2 proto files into python files

```shell
python3 -m grpc_tools.protoc -I ./ --python_out=. --grpc_python_out=. --pyi_out=. ./descriptor.proto
python3 -m grpc_tools.protoc -I ./ --python_out=. --grpc_python_out=. --pyi_out=. ./pb.proto 
```

5. Execute below python codes in test.py with command "python3 test.py":

```python
import faulthandler
faulthandler.enable()
from pb_pb2 import PushData

push_data = PushData()
push_data.DataSet.mask.append(1)
fields = push_data.ListFields()
for field, value in fields:
    print(field)
    print(field.message_type.GetOptions().map_entry)
```

**What did you expect to see**

```shell
<google.protobuf.pyext._message.FieldDescriptor object at 0x10343bfd0>
False
```

**What did you see instead?**

```shell
<google._upb._message.FieldDescriptor object at 0x10187ad60>
Fatal Python error: Segmentation fault

Current thread 0x00007ff85332f640 (most recent call first):
  File "/Users/me/Desktop/codes/test.py", line 10 in <module>

Extension modules: google._upb._message (total: 1)
[1]    119 segmentation fault  /usr/local/bin/python3.11 
```

**Anything else we should know about your project / environment**

1. I run into issue because I am using the MessageToDict/ MessageToJson from google.protobuf.json_format, when I try to convert some protobuf data into python dict or json object, I found my program always run into Fatal Python error: Segmentation fault. After analyzing the source code from json_format.py, I see the problem caused by the "field.message_type.GetOptions().map_entry" in _IsMapEntry function.
2. This issue is NOT reproduced in Python 3.10.12 and Python 3.9.17 in Mac (13.2);
3. This issue CAN be reproduced in Linux system (Linux version 5.15.49-linuxkit) with ALL python versions above.

**Comment by yananzhao689** [comment]
@anandolee hello, sorry to disturb you, could you help me to have a look at the issue above.

**Comment by 0x26res** [comment]
I had a similar issue, with a segfaults when calling `GetOptions`. It turns out that for some reason, the `google/protobuf/descriptor_pb2.py` provided by the protobuf library was overwriten by an internal library I was using. Once I've fixed that the issue went away.

@yananzhao689 I suspect that you have the same problem. I don't think you should be calling protoc on descriptor.proto.

Instead import the one provided by google.

```
syntax = "proto3";
import "google/protobuf/descriptor.proto";

message Rows {
    repeated uint64 mask = 2;
}

message PushData {
    Rows DataSet = 4;
}

```

This is how I resolve the its location and add it as a `--proto_path` option:
```
python3 -m grpc_tools.protoc -I ./ --python_out=. --grpc_python_out=. --pyi_out=. ./pb.proto \
  --proto_path=$( python -c "import pathlib;import grpc_tools;print(pathlib.Path(grpc_tools.__file__).parent.absolute() / '_proto')")
```
