### ISSUE TITLE
compile generated csharp file to assembly(dll) file error

### ISSUE THREAD

**Issue by unitymatrix** [protocolbuffers/protobuf#13152]
.net framework ：4.8
protobuf version：3.23.2
I have generated csharp files base proto file. while I use "CodeDomProvider" to compile it to dll， report error:

> error: “8981”不是有效的警告编号
error: “8981”不是有效的警告编号
error: “8981”不是有效的警告编号
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.WriteContext”已过时:“Types with embedded references are not supported in this version of your compiler.”
error: “Google.Protobuf.ParseContext”已过时:“Types with embedded references are not supported in this version of your compiler.

code like this:
>                         CodeDomProvider codeProvider = CodeDomProvider.CreateProvider("CSharp");
                            CompilerParameters parameters = new CompilerParameters();
                            parameters.GenerateExecutable = false;
                            parameters.OutputAssembly = dllPath;
                            parameters.ReferencedAssemblies.Add("/Core/Google.Protobuf.dll");
                            parameters.ReferencedAssemblies.Add("System.dll");
                            cSharpInputPath = Path.GetFullPath("generated csharp file path");
                            string[] files = Directory.GetFiles(cSharpInputPath, "*.cs");
                            CompilerResults results = codeProvider.CompileAssemblyFromFile(parameters, files);
                            if (results.Errors.HasErrors)
                            {
                                Console.WriteLine("gen dll error");
                                foreach (CompilerError err in results.Errors)
                                {
                                    Console.WriteLine("error: "+err.ErrorText);
                                }
                            }

**Comment by unitymatrix** [comment]
when I remove "parameters.ReferencedAssemblies.Add("System.dll");" then the error is:
can't find System.CodeDom.

**Comment by jskeet** [comment]
I believe this is cause CodeDomProvider uses the old pre-Roslyn compiler, which doesn't understand ref struct types like `Span<T>`.

If at all possible, I'd encourage you to adopt Roslyn for your dynamic compilation instead of `CodeDomProvider` - it will provide a better long-term experience.

In the short term, if you define the `GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE` symbol in your compiler parameters then the compiler will use the slower but more compatible code path that doesn't support ref structs.

I haven't tested this with `CodeDomProvider` directly, but using the compiler under `c:\Windows\Microsoft.NET\Framework` directly, I'm able to reproduce the original issue and the fix.

**Comment by jskeet** [comment]
I'll close this issue now, having proposed short and long term fixes, and having heard no response.

**Comment by unitymatrix** [comment]
> I believe this is cause CodeDomProvider uses the old pre-Roslyn compiler, which doesn't understand ref struct types like `Span<T>`.
> 
> If at all possible, I'd encourage you to adopt Roslyn for your dynamic compilation instead of `CodeDomProvider` - it will provide a better long-term experience.
> 
> In the short term, if you define the `GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE` symbol in your compiler parameters then the compiler will use the slower but more compatible code path that doesn't support ref structs.
> 
> I haven't tested this with `CodeDomProvider` directly, but using the compiler under `c:\Windows\Microsoft.NET\Framework` directly, I'm able to reproduce the original issue and the fix.

finally I chose an old version,3.9.4
that version is ok.
while it is still a problem whith the latest version

**Comment by jskeet** [comment]
> while it is still a problem whith the latest version

Even with the workaround I suggested of defining `GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE`? You haven't given any feedback on that specifically. (I would still strongly encourage you to migrate to using Roslyn, mind you.)
