### ISSUE TITLE
Starting with 22.0 protobuf sources for well known types are no longer included in `protobuf-java-sources.jar`

### ISSUE THREAD

**Issue by marcoferrer** [protocolbuffers/protobuf#13167]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
Java

**What operating system (Linux, Windows, ...) and version?**
n/a

**What runtime / compiler are you using (e.g., python version or gcc version)**
3.23.3

**What did you do?**
1. Download the sources jar for version 3.21.12 from https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.21.12/protobuf-java-3.21.12-sources.jar
2. Unzip the jar and confirm that the `google/protobuf/*.proto` files are included
3. Download any sources jar starting from 3.22.0 or newer. https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.0/protobuf-java-3.22.0-sources.jar
3. Unzip the jar and confirm the proto sources are missing

**What did you expect to see**
Proto sources are ommitted

**What did you see instead?**
The well know proto sources like in older jar versions

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Its not clear if this was an intentional change. It doesnt seem to be part of the 22.0 release notes

**Comment by marcoferrer** [comment]
Judging by the bazel rule it looks like there are still supposed to be included. Im not very familiar with bazel but if I had to guess, I think the issue may have been introduced from either:
* The switch from `java_export` to `protobuf_java_export`
* The switch from `//:built_in_runtime_protos` to `//src/google/protobuf:descriptor_proto_srcs`

### Before 22.0
https://github.com/protocolbuffers/protobuf/blob/f0dc78d7e6e331b8c6bb2d5283e06aa26883ca7c/java/core/BUILD.bazel#L189-L199

### After
https://github.com/protocolbuffers/protobuf/blob/d97c8ed86025a855058b20ed484b59a69284d1c6/java/core/BUILD.bazel#L228-L238

**Comment by marcoferrer** [comment]
I may be able to contribute a fix for this if I'm able to get some guidance on what needs to be looked at and how I can package the jars so I can debug. Just looking for any way I can be of assistance here since this is blocking roll out of an upgrade to multiple applications and automation systems.

**Comment by zhangskz** [comment]
So what likely changed here is the adoption of these bazel rules for our release process. I believe we had previously used Maven for these source jars prior to 22.x.

Based on https://bazel.build/reference/be/java#java_library and https://github.com/bazelbuild/bazel/issues/8457, it seems `resources` (which is where the missing well known types and `descriptor.proto` are included) has *never* been included in the outputted source jars and these bazel targets actually work as intended. This seems to be true for 21.x as well.

Can you help us understand your use-case for these protos, and if/why this currently causes problems for your systems? Arguably, these protos probably shouldn't have been included in our source jars in the first place and they can still be accessed instead via the non-source jars. Would this work for your use case?

Note that for the above changes:
* the switch from `java_export` to `protobuf_java_export` was trivial and simply wrapped `java_export` to set flags to support java8
* the switch from `//:built_in_runtime_protos` to `//src/google/protobuf:descriptor_proto_srcs` shouldn't affect this either

**Comment by marcoferrer** [comment]
> they can still be accessed instead via the non-source jars. Would this work for your use case?

I didn't realize that was the case. It should work for our purposes. There may have been something IDE specifc (intellisense / inspection realted) that caused us to originally rely on the sources jar. Not sure if this would affect other users that have the same dependency. 

I did notice the compiler protos are missing. Would there be another jar that contains the compiler protos or was the intention to completely omit them? We have and edge case with some tooling that depends on referencing the types in those protos.

For context, in some scenarios we use jars for proto publication, distribution and consumption since they are natively handled by the [protobuf gradle plugin](https://github.com/google/protobuf-gradle-plugin).

**Comment by zhangskz** [comment]
By compiler protos do you mean `google/protobuf/compiler/plugin.proto`? This change seems to stem from the switch from `//:built_in_runtime_protos` to `//src/google/protobuf:descriptor_proto_srcs` which no longer includes this proto.

Is the tooling you mentioned that depends on referencing these the protobuf gradle plugin as well, or is that something separate?
