### ISSUE TITLE
Error compiling Kotlin code when field names conflict with top-level package names

### ISSUE THREAD

**Issue by pkwarren** [protocolbuffers/protobuf#13182]
**What version of protobuf and what language are you using?**
Version: 23.3
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
n/a

**What did you do?**
1. Create the following file in path `net/example/v1/example.proto`:
```proto
syntax = "proto3";

package net.example.v1;

message Sample {
  string net = 1;
}
```
2. Generate the code with:
```
$ mkdir -p src/main/{java,kotlin}
$ protoc --java_out src/main/java --kotlin_out src/main/kotlin net/example/v1/example.proto
```
3. Compile the code with Maven/Gradle/etc. Here's the pom.xml I used: https://gist.github.com/pkwarren/ea8315f579dc0b2b5ebd362ea46e75d7

**What did you expect to see**
No error compiling generated code.

**What did you see instead?**
```
$ ./mvnw compile
...
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.8.22:compile (compile) on project example: Compilation failure: Compilation failure: 
[ERROR] /example/src/main/kotlin/net/example/v1/SampleKt.kt:[50,7] Unresolved reference: example
[ERROR] /example/src/main/kotlin/net/example/v1/SampleKt.kt:[50,65] Can't inline 'block' here: it may contain non-local returns. Add 'crossinline' modifier to parameter declaration 'block'
[ERROR] /example/src/main/kotlin/net/example/v1/SampleKt.kt:[50,70] No value passed for parameter 'p1'
[ERROR] -> [Help 1]
```

The following change to the generated code appears to resolve the issue - I'm guessing the Kotlin compiler needs to be updated to use backticks for fully qualifying package names:

```diff
diff --git a/src/main/kotlin/net/example/v1/SampleKt.kt b/src/main/kotlin/net/example/v1/SampleKt.kt
index f1f9dd4..f703d05 100644
--- a/src/main/kotlin/net/example/v1/SampleKt.kt
+++ b/src/main/kotlin/net/example/v1/SampleKt.kt
@@ -47,5 +47,5 @@ public object SampleKt {
 }
 @kotlin.jvm.JvmSynthetic
 public inline fun net.example.v1.Example.Sample.copy(block: net.example.v1.SampleKt.Dsl.() -> kotlin.Unit): net.example.v1.Example.Sample =
-  net.example.v1.SampleKt.Dsl._create(this.toBuilder()).apply { block() }._build()
+  `net.example.v1`.SampleKt.Dsl._create(this.toBuilder()).apply { block() }._build()
 
```

**Anything else we should know about your project / environment**

**Comment by fowles** [comment]
This is absolutely a bug.  If you are willing to send a PR to help fix it that will likely be the fastest thing.  Otherwise we will put this in our queue and get to it when we can.

**Comment by pkwarren** [comment]
> This is absolutely a bug. If you are willing to send a PR to help fix it that will likely be the fastest thing. Otherwise we will put this in our queue and get to it when we can.

Opened #13310 with a proposed fix.
