### ISSUE TITLE
ValueError while using the `update` method to convert a `dict` to Struct

### ISSUE THREAD

**Issue by vishalratnam6** [protocolbuffers/protobuf#13205]
**What version of protobuf and what language are you using?**
Version: main
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python3.9+

**What did you do?**
Steps to reproduce the behaviour:
1. Create a python `dict` with any string key and the `value` as a nested `list` of `tuple`s:
  ```
  document = { 
    'coordinates': 
        [
            [
              (78, 25), 
              (76, 22), 
              (78, 21), 
              (80, 24), 
              (78,25)
              ]
        ]
   }
```

2. Use the `update` function from `google.protobuf.struct_pb2.Struct` to convert the `dict` into a protobuf `Stuct`.
   ```
   for key in document:
        s = Struct()
        s.update({key: document[key]})
    ```

3.  Run the file with: `python3 filename.py`
 
**What did you expect to see**
The `dict` should've been converted to the `Struct` object without the error.

**What did you see instead?**
 A python `ValueError`:
 ```
     _SetStructValue(self.values.add(), value)
     File "/usr/local/anaconda3/envs/myenv/lib/python3.9/site-packages/google/protobuf/internal/well_known_types.py", line 456, in 
     _SetStructValue
     raise ValueError('Unexpected type')
     ValueError: 
 ```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Modifying the file `well_known_types.py` at `google/protobuf/internal` by adding the following piece of code fixes the error:**
Function `_SetStructValue` on line `435` in the `main` branch. Add the following block after `451`:
```
 elif isinstance(value, (tuple, ListValue)):
     struct_value.list_value.Clear()
     struct_value.list_value.extend(value)
```
**Anything else we should know about your project / environment**
No

**Comment by vishalratnam6** [comment]
@shaod2 any update on this?

**Comment by vishalratnam6** [comment]
@anandolee any update on this?

**Comment by anandolee** [comment]
Thanks for raise it up. Prepared a CL in internal

**Comment by GustavoYamaguchi** [comment]
You can parse your dict to a json string to overcomer this bug:
```
for key in document:
    Parse(jsons.dumps(document), Struct())
```

**Comment by vishalratnam6** [comment]
> You can parse your dict to a json string to overcome this bug:
> 
> ```
> for key in document:
>     Parse(jsons.dumps(document), Struct())
> ```

Hi! The `Parse` function is provided by?

**Comment by GustavoYamaguchi** [comment]
> Hi! The Parse function is provided by?

Hey @vishalratnam6, will post full example for clarity:

```
import jsons
from google.protobuf.json_format import Parse
from google.protobuf.struct_pb2 import Struct

document = {
  'coordinates':
      [
          [
            (78, 25),
            (76, 22),
            (78, 21),
            (80, 24),
            (78,25)
            ]
      ]
 }

for key in document:
    Parse(jsons.dumps(document), Struct())
```

**Comment by vishalratnam6** [comment]
> > Hi! The Parse function is provided by?
> 
> Hey @vishalratnam6, will post full example for clarity:
> 
> ```
> import jsons
> from google.protobuf.json_format import Parse
> from google.protobuf.struct_pb2 import Struct
> 
> document = {
>   'coordinates':
>       [
>           [
>             (78, 25),
>             (76, 22),
>             (78, 21),
>             (80, 24),
>             (78,25)
>             ]
>       ]
>  }
> 
> for key in document:
>     Parse(jsons.dumps(document), Struct())
> ```

@GustavoYamaguchi amazing! This worked for me. Thank you! 😄
