### ISSUE TITLE
DiscardUnknownFields unnecessarily triggers SyncRepeatedWithMap

### ISSUE THREAD

**Issue by PandaBlueYellow** [protocolbuffers/protobuf#13222]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 11

**What did you do?**
1. use generated api to insert a value to a map<int32, int32> field
2. Call DiscardUnknown on parent message
3. gdb into DiscardUnknownFields

**What did you expect to see**
no SyncRepeatedWithMap is called

**What did you see instead?**
SyncRepeatedWithMap is called

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by PandaBlueYellow** [comment]
In 3.8, https://github.com/protocolbuffers/protobuf/blob/3.8.x/src/google/protobuf/reflection_ops.cc#L249C9-L268C9
Looks like if map is int, int, L266 was executed, which doesn't cause SyncRepeatedWithMap.

However, in main, https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/reflection_ops.cc#L353C5-L364C74
If the map is int, int, it will go into the branch for handling repeated field

**Comment by shaod2** [comment]
Hi,

Map fields should be both is_repeated and is_map, so I'm not sure why L266 was executed for Map<int, int> in 3.8. It the main branch, it is because is_map is now cheaper than is_repeated so that's why it's called first instead.

**Comment by PandaBlueYellow** [comment]
For 3.8, L251, the check is false because the value field of map<int, int> is int instead of message.

**Comment by PandaBlueYellow** [comment]
@shaod2 for main, the point is that, for map<int, int>, it shouldn't go to L366, which triggers SyncRepeatedWithMap.

**Comment by shaod2** [comment]
Yes I see what you meant. I'm checking the intention behind this.

**Comment by PandaBlueYellow** [comment]
Let me know if this could work
```
    for (const FieldDescriptor* field : fields) {
      // Skip over non-message fields.
      if (field->cpp_type() != FieldDescriptor::CPPTYPE_MESSAGE) {
        continue;
      }   
      // Discard the unknown fields in maps that contain message values.
      const MapFieldBase* map_field = field->is_map() ?
          reflection->MutableMapData(message, field) : nullptr;
      if (field->is_map() && map_field->IsMapValid()) {
        if (IsMapValueMessageTyped(field)) {
          MapIterator iter(message, field);
          MapIterator end(message, field);
          for (map_field->MapBegin(&iter), map_field->MapEnd(&end); iter != end;
               ++iter) {
            iter.MutableValueRef()->MutableMessageValue()->DiscardUnknownFields();
          }   
        }   
        // Discard every unknown field inside messages in a repeated field.
      } else if (field->is_repeated()) {
        int size = reflection->FieldSize(*message, field);
        for (int j = 0; j < size; j++) {
          reflection->MutableRepeatedMessage(message, field, j)
              ->DiscardUnknownFields();
        }   
        // Discard the unknown fields inside an optional message.
      } else {
        reflection->MutableMessage(message, field)->DiscardUnknownFields();
      }
    }
```

**Comment by PandaBlueYellow** [comment]
@shaod2 any idea?
