### ISSUE TITLE
zlib(BUILD.bazel): Maybe it would be better to use @platforms instead of @bazel_tools?

### ISSUE THREAD

**Issue by 4kangjc** [protocolbuffers/protobuf#13250]
Hi! Maybe it would be better to use @platforms instead of @bazel_tools?
https://github.com/protocolbuffers/protobuf/blob/a01d047456783b46a4ca675eee881de110a88799/third_party/zlib.BUILD#L60-L67

``` Python
 copts = select({ 
     "@platforms//os:windows": [], 
     "//conditions:default": [ 
         "-Wno-deprecated-non-prototype", 
         "-Wno-unused-variable", 
         "-Wno-implicit-function-declaration", 
     ], 
 }), 
```

**Comment by acozzette** [comment]
That sounds like a good idea. If you would like to send a PR with this change then I would be happy to review it.

**Comment by 4kangjc** [comment]
> That sounds like a good idea. If you would like to send a PR with this change then I would be happy to review it.



> That sounds like a good idea. If you would like to send a PR with this change then I would be happy to review it.

OK.
