### ISSUE TITLE
google.protobuf has no attribute pyext

### ISSUE THREAD

**Issue by risemeup1** [protocolbuffers/protobuf#13300]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
3.20.2 3.19.2 3.20.3 both have this problem

Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
C++
**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc
**What did you do?**
1 import google.protobuf
2 google.protobuf.pyext._message
<img width="1323" alt="9c910d1d6c32f42fb7d9de6cdb2270c0" src="https://github.com/protocolbuffers/protobuf/assets/62429225/5780410f-edc3-470e-b1e4-c9bd83ecfa7b">

**What did you expect to see**
import google.protobuf
google.protobuf.pyext._message success
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by haberman** [comment]
`google.protobuf.pyext._message` is an internal-only module, as indicated by the leading underscore. It is removed completely in 4.21.x.

Why are you trying to import this module directly?
