### ISSUE TITLE
allow users to set the recursion limit in proto files

### ISSUE THREAD

**Issue by zhouyuan** [protocolbuffers/protobuf#13301]
**What language does this apply to?**
proto3
java

**Describe the problem you are trying to solve.**
I'm running some stress test which may introduce deep protobuf recursion. The protobuf java file is auto generated from a base proto file. So it's not easy to add the `setRecursionLimit()` in each file.  
here's the issue: https://github.com/oap-project/gluten/issues/1727

**Describe the solution you'd like**
Would be nice to allow users to set the recursion limit in proto files

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by acozzette** [comment]
Sorry but I don't think we want to go in this direction, because it would be a fairly big change and would require updating all language generators to respect the recursion limit in the proto file. Can you say more about why it's not feasible to set the recursion limit from your Java code?

**Comment by zhouyuan** [comment]
@acozzette hi, thanks for looking on this, 

the issue I ran into is there are many data structures defined in proto:
https://github.com/oap-project/gluten/tree/main/gluten-core/src/main/resources/substrait/proto/substrait

then we used `protoc `plugin to compile those into java files:
https://github.com/oap-project/gluten/blob/main/gluten-core/pom.xml#L282-L300

after that there are 100+ files, in each file there some code snips on `CodeInputStream`, like below:
```
    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {

```
one way is to manually modify the code, to add input.setRecursionLimit(), however there are too many calls on this `input` in each function :-(

I agree the efforts to change is really too big, do you see if there's one easy way to fix my use case? 

thanks, -yuan

**Comment by lgbo-ustc** [comment]
can update the default value to a large enough value?

**Comment by zhouyuan** [comment]
closing this as we build a local protobuf with modified bigger value for recursion limit
