### ISSUE TITLE
PHP: Hope to support registration binding Any.type_url to class

### ISSUE THREAD

**Issue by reatang** [protocolbuffers/protobuf#13319]
language: php
protobuf version: 3.21.12

**Describe the problem you are trying to solve.**
I use an `google.protobuf.Any` field in the message to store some of my variable data.
but it cannot be automatically decoded in PHP, and an exception will be reported. 
```protobuf
import "google/protobuf/any.proto";

message MyResponse {
  google.protobuf.Any detail = 1
}

```
```php
[$response, $status] = $call->wait();
echo $response->serializeToJsonString();
```
`Exception: Error occurred during JSON serialization: Couldn't find Any type:reatang.rpc.SomeDetail`

In code: [php-upb.c#L5162](https://github.com/protocolbuffers/protobuf/blob/main/php/ext/google/protobuf/php-upb.c#L5162)
,I inquired that the `type_url` of the custom message was not registered in `php-upb`.

**Describe the solution you'd like**

Is it possible to open the function of `type_url` mapping to the corresponding class in the php extension.

**Describe alternatives you've considered**

I'm currently manually decoding the Any field

**Comment by haberman** [comment]
> Is it possible to open the function of type_url mapping to the corresponding class in the php extension.

Can you be more specific? How would you like this to work in code?

**Comment by reatang** [comment]
> > Is it possible to open the function of type_url mapping to the corresponding class in the php extension.
> 
> Can you be more specific? How would you like this to work in code?

For example, open a function to register the association between type_url and class

```php
<?php

namespace Grpc;

function register_any_type($type_url, $class_name) ;

```

```php

use Reatang\Rpc\SomeDetail;

register_any_type("type.googleapis.com/reatang.rpc.SomeDetail", SomeDetail::class);

```

The `type_url` registered using this function can automatically identify the `Any` type by `serializeToJsonString`.

**Comment by haberman** [comment]
It shouldn't generally be necessary to do that. Any message that you `use` should get registered into the pool that is used to look up types by name.

You can see some examples in the unit tests: https://github.com/protocolbuffers/protobuf/blob/5c7b41a76974bf1af0b605090fed27ce63fcd36b/php/tests/EncodeDecodeTest.php#L1518-L1535

I am not sure why that didn't work in your case.  Did you have `use Reatang\Rpc\SomeDetail;` in the code where you called `serializeToJsonString()`?
