### ISSUE TITLE
Protobuf 23.4 CMAKE link error

### ISSUE THREAD

**Issue by smahapatra1** [protocolbuffers/protobuf#13359]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**
At link time, I see utf8-range symbol not found error. I saw some issue that was similar using pkgconfig and a fix was merged. I am on the latest release branch 23.4. Should I fall back to 21x version?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by sbenzaquen** [comment]
We need more information to make the report actionable.
Would you mind filling the missing questions report template?
Without reproduction information is hard to know how to help.
