### ISSUE TITLE
Conan package 3.17.1 (or newer) CMake build issue "The filename, directory name, or volume label syntax is incorrect."

### ISSUE THREAD

**Issue by ibosnic00** [protocolbuffers/protobuf#13362]
Issue:
When compiling C++ project with CMake and Visual Studio 17 generator, error pops out:

```
Running cpp protocol buffer compiler on C:/Users/user.name/cppTest/proto/ecu_state.proto
  The filename, directory name, or volume label syntax is incorrect.
```

I have created demo project to easily reproduce the issue.

Steps to reproduce:

- git clone https://github.com/ibosnic00/demo_cmake_conan.git
- cd demo_cmake_conan
- start build_and_compile.bat script

Note: 
In conanfile.py, line 22 make sure the version of protobuf is 3.17.1 or newer `self.requires("protobuf/3.17.1")`

It looks like 3.17.1 and newer packages are not adding protoc to PATH (when added manually, build passes), while 3.16.0 package does it okay.

**Comment by zhangskz** [comment]
Thanks for reporting this. Note that Conan is not an officially supported package manager for Protobuf, but we'd be happy to accept a patch here if you would like to contribute one. Is this a Conan-specific issue? And does manually adding protoc to PATH cause any problems?

Note that 3.17.x is out of our official support window. We would likely only address this type of fix in our next minor release per [go/proto-version-support](https://goto.google.com/proto-version-support).
