### ISSUE TITLE
CodedOutputStream: Option to throw an exception for unpaired surrogates

### ISSUE THREAD

**Issue by robinst** [protocolbuffers/protobuf#13388]
**What language does this apply to?**

Java library class `CodedOutputStream`.

**Describe the problem you are trying to solve.**

Currently, when using [`CodedOutputStream`](https://github.com/protocolbuffers/protobuf/blob/d4f2d48101b1aba771b3ac4c09b3a38c3591e0bd/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L59C1-L59C1) and writing strings that contain unpaired surrogates, they are replaced by `?` characters and a warning is logged, see [`inefficientWriteStringNoTag`](https://github.com/protocolbuffers/protobuf/blob/d4f2d48101b1aba771b3ac4c09b3a38c3591e0bd/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L982C33-L982C33) method.

If a user wants to avoid that, they currently have to manually check all strings before using `CodedOutputStream`, adding some performance overhead.

**Describe the solution you'd like**

It would be very useful if the `CodedOutputStream` could throw an exception in that case instead. Note that there's even a TODO in the code for that:

https://github.com/protocolbuffers/protobuf/blob/d4f2d48101b1aba771b3ac4c09b3a38c3591e0bd/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1478-L1483

The existing behavior can't be changed because of compatibility, but a setting could be added that turns on the new behavior (there is precedence for this with the `useDeterministicSerialization` setting).

So the changes to `CodedOutputStream` would be:

1. Add a `private boolean throwOnUnpairedSurrogates;` field (defaulting to `false`) and a setter/getter method
2. In `writeStringNoTag` methods (or `inefficientWriteStringNoTag`), when encountering unpaired surrogates, check the field and if it's true, throw an `IOException` instead. Otherwise, keep the existing behavior.

I'm happy to create a PR with those changes if that sounds good.

**Describe alternatives you've considered**

I initially thought I could extend `CodedOutputStream` until I saw that the constructor is private :). As mentioned above, the only alternatives I can think of is to build a wrapper around it and check all strings before passing them to `writeStringNoTag`, which adds a performance overhead.

**Comment by zhangskz** [comment]
Thanks for the request! In the long run, we would like to move towards stricter UTF8 validation behavior in general which should include validating unpaired surrogates on serialization.

Our hope is to eventually address this via [Editions](https://protobuf.dev/editions/overview/) features to move towards stricter behavior here rather than introducing additional configuration points within individual classes/methods. This probably wouldn't make it in our first edition, but is on our radar.

**Comment by robinst** [comment]
Thanks, that makes sense!
