### ISSUE TITLE
Deserializing even floats do not work in C++

### ISSUE THREAD

**Issue by mquilling** [protocolbuffers/protobuf#13406]
Floats are not being deserialized correctly in c++ when the float is even e.g. 2.0

**What version of protobuf and what language are you using?**
Version: main (but tested multiple versions)
Language: C++/Python

**What operating system (Linux, Windows, ...) and version?**
Linux/Mac

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.11
g++  11.3.0

**What did you do?**
proto
```
syntax = "proto3";

message ApiMessage {
  float test = 1;
}
```
python
```
msg = proto.ApiMessage(test=2.0)
ser = [hex(x) for x in msg.SerializeToString()]
print('bytes', ser)
print('byte string', '\\' + '\\'.join([x.replace('0x', 'x') for x in ser]))
print(proto.ApiMessage.FromString(msg.SerializeToString()))
```
output
```
bytes ['0xd', '0x66', '0x66', '0x6', '0x40']
byte string \xd\x66\x66\x6\x40
test: 2
```
c++
```
#include "api.pb.h"

int main() {
    ApiMessage msg;
    msg.ParseFromString("\xd\x66\x66\x6\x40");
    std::cout << msg.DebugString() << std::endl;
}
```
outputs nothing

changing 2.0 to 2.1 results in correct behavior

**Comment by zhangskz** [comment]
Can you reproduce when constructing and serialize `ApiMessage` in C++ with test=2.0 before parsing instead of trying to pass the transformed byte string?

**Comment by mquilling** [comment]
that does work. we are seeing this in our production applications which python is sending serialized messages over serial and the other end is C++. The C++ end always truncates the entire message if the float is even.

Could it be the string is getting truncated bc of the null charecters?

```
#include "api.pb.h"

int main() {
    ApiMessage msg;
    msg.ParseFromString("\xd\x0\x0\x0\x40");
    std::cout << "ParseFromString Python " << msg.DebugString() << std::endl;

    ApiMessage msg_1;
    msg_1.set_test(2.0);
    std::string output;
    msg_1.SerializeToString(&output);
    std::cout << "SerializeToString ";
    std::cout << std::hex;
    for (char ch : output)
    {
        std::cout << "0x" << static_cast<unsigned int>(static_cast<unsigned char>(ch)) << ' ';
    }
    std::cout << std::endl;
    ApiMessage msg_2;
    msg_2.ParseFromString(output);
    std::cout << "ParseFromString C++ " << msg_2.DebugString() << std::endl;
}
```

**Comment by ericsalo** [comment]
> Could it be the string is getting truncated bc of the null charecters?

That would be my guess, yes. You don't appear to be passing in a C++ std::string (which contains a length), but instead a C (char*).

**Comment by mquilling** [comment]
this does work
```
    std::string data("");
    data.push_back(0xd);
    data.push_back(0);
    data.push_back(0);
    data.push_back(0);
    data.push_back(0x40);
    msg.ParseFromString(data);
    std::cout << "ParseFromString Python " << msg.DebugString() << std::endl;
```
so would you say this is not a bug in the library but the fact that the const char * is getting truncated when converting to a std::string?

**Comment by ericsalo** [comment]
> so would you say this is not a bug in the library but the fact that the const char * is getting truncated when converting to a std::string?

Yes. The library is correctly parsing the truncated string that it is being given.

**Comment by mquilling** [comment]
great - thanks, closing.
