### ISSUE TITLE
[Java] protoc v3.20.3 is missing build artifacts for osx-aarch_64 (M1)

### ISSUE THREAD

**Issue by danepitkin** [protocolbuffers/protobuf#13402]
`protoc` v3.20.3 release is missing osx-aarch64 artifacts. Is there any precedent for uploading/rebuilding missing artifacts for old releases?

**What version of protobuf and what language are you using?**
Version: v3.20.3
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
Mac M1 (aarch64)

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
1. Go to maven repo: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.20.3/
2. osx-aarch_64 build is missing
3. Go to Github releases: https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.3
4. protoc osx-aarch_64 is missing

**What did you expect to see**
osx-aarch_64 build artifacts

**What did you see instead?**
No artifacts

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
N/A

**Comment by zhangskz** [comment]
Unfortunately we cannot upload missing artifacts to Maven after-the-fact for an existing release -- typically we would need to create a new patch release. 

I believe we were still in the process of introducing these artifacts when releasing the `20.x` line so these artifacts may not have been built/named correctly yet, until officially released/supported in `21.x`. Apologies for the confusion!

`20.x` is also long out of support window per https://protobuf.dev/support/version-support/ -- we recommend upgrading to a current protobuf version (e.g. `23.x`)  which should also include the missing artifacts.

**Comment by danepitkin** [comment]
Sounds good. I appreciate the response! Thank you.
