### ISSUE TITLE
PHP: Deprecation message for "return_immediately" is thrown which is impossible to fix

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#13428]
See https://github.com/googleapis/google-cloud-php/issues/5350

@pkruithof has reported the following, which seems to be an error in the Protobuf package. The  function `getReturnImmediately` is being called internally without any way (as far as we can tell) to prevent it from happening:

Because the `return_immediately` option has been deprecated some time ago, this produces a deprecation log on every pull request:

```
[2022-06-17T06:57:33.459907+00:00] deprecation.INFO: User Deprecated: return_immediately is deprecated. {"exception":"[object] (ErrorException(code: 0): User Deprecated: return_immediately is deprecated. at /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php:138)"} []
[2022-06-17T06:57:33.460273+00:00] deprecation.INFO: User Deprecated: return_immediately is deprecated. {"exception":"[object] (ErrorException(code: 0): User Deprecated: return_immediately is deprecated. at /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php:118)"} []
[2022-06-17T06:57:33.460353+00:00] deprecation.INFO: User Deprecated: return_immediately is deprecated. {"exception":"[object] (ErrorException(code: 0): User Deprecated: return_immediately is deprecated. at /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php:118)"} []
```

At first I thought to submit a workaround for this, so that the deprecation is only shown when the option is set to `true` (`false` is the default):

```php
    public function getReturnImmediately()
    {
        if ($this->return_immediately === true) {
            @trigger_error('return_immediately is deprecated.', E_USER_DEPRECATED);
        }
        return $this->return_immediately;
    }
```

The setter should still always trigger the deprecation, so you still see it when you use the option and set it to `false`.

However, then I noticed that this code is generated. So I don't think this is possible, unless there's a way to customize generated classes like this?

In any case, I would very much like to be able to remove this deprecation from our processes, as it's polluting our logs, making them harder to read. Is there another way to go here?

Here is the stack trace

```
PHP Fatal error:  Uncaught ErrorException: return_immediately is deprecated. in /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php:167
Stack trace:
#0 [internal function]: {closure}(16384, 'return_immediat...', '/app/vendor/goo...', 167)
#1 /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php(167): trigger_error('return_immediat...', 16384)
#2 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1598): Google\Cloud\PubSub\V1\PullRequest->getReturnImmediately()
#3 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1842): Google\Protobuf\Internal\Message->existField(Object(Google\Protobuf\Internal\FieldDescriptor))
#4 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1931): Google\Protobuf\Internal\Message->fieldByteSize(Object(Google\Protobuf\Internal\FieldDescriptor))
#5 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1564): Google\Protobuf\Internal\Message->byteSize()
#6 /app/vendor/grpc/grpc/src/lib/AbstractCall.php(117): Google\Protobuf\Internal\Message->serializeToString()
#7 /app/vendor/grpc/grpc/src/lib/UnaryCall.php(39): Grpc\AbstractCall->_serializeMessage(Object(Google\Cloud\PubSub\V1\PullRequest))
#8 /app/vendor/grpc/grpc/src/lib/BaseStub.php(295): Grpc\UnaryCall->start(Object(Google\Cloud\PubSub\V1\PullRequest), Array, Array)
#9 /app/vendor/grpc/grpc/src/lib/BaseStub.php(545): Grpc\BaseStub->Grpc\{closure}('/google.pubsub....', Object(Google\Cloud\PubSub\V1\PullRequest), Array, Array, Array)
#10 /app/vendor/google/gax/src/Transport/GrpcTransport.php(218): Grpc\BaseStub->_simpleRequest('/google.pubsub....', Object(Google\Cloud\PubSub\V1\PullRequest), Array, Array, Array)
#11 /app/vendor/google/gax/src/GapicClientTrait.php(751): Google\ApiCore\Transport\GrpcTransport->startUnaryCall(Object(Google\ApiCore\Call), Array)
#12 /app/vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(59): Google\Cloud\PubSub\V1\Gapic\SubscriberGapicClient->Google\ApiCore\{closure}(Object(Google\ApiCore\Call), Array)
#13 /app/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(68): Google\ApiCore\Middleware\CredentialsWrapperMiddleware->__invoke(Object(Google\ApiCore\Call), Array)
#14 /app/vendor/google/gax/src/Middleware/RetryMiddleware.php(85): Google\ApiCore\Middleware\FixedHeaderMiddleware->__invoke(Object(Google\ApiCore\Call), Array)
#15 /app/vendor/google/gax/src/Middleware/OptionsFilterMiddleware.php(62): Google\ApiCore\Middleware\RetryMiddleware->__invoke(Object(Google\ApiCore\Call), Array)
#16 /app/vendor/google/gax/src/GapicClientTrait.php(725): Google\ApiCore\Middleware\OptionsFilterMiddleware->__invoke(Object(Google\ApiCore\Call), Array)
#17 /app/vendor/google/cloud-pubsub/src/V1/Gapic/SubscriberGapicClient.php(1264): Google\Cloud\PubSub\V1\Gapic\SubscriberGapicClient->startCall('Pull', 'Google\\Cloud\\Pu...', Array, Object(Google\Cloud\PubSub\V1\PullRequest))
#18 [internal function]: Google\Cloud\PubSub\V1\Gapic\SubscriberGapicClient->pull('projects/dev-pk...', 1000, Array)
#19 /app/vendor/google/cloud-core/src/ExponentialBackoff.php(97): call_user_func_array(Array, Array)
#20 /app/vendor/google/cloud-core/src/GrpcRequestWrapper.php(148): Google\Cloud\Core\ExponentialBackoff->execute(Array, Array)
#21 /app/vendor/google/cloud-core/src/GrpcTrait.php(82): Google\Cloud\Core\GrpcRequestWrapper->send(Array, Array, Array)
#22 /app/vendor/google/cloud-pubsub/src/Connection/Grpc.php(411): Google\Cloud\PubSub\Connection\Grpc->send(Array, Array)
#23 /app/vendor/google/cloud-pubsub/src/Subscription.php(688): Google\Cloud\PubSub\Connection\Grpc->pull(Array)
#24 /app/bin/pubsub.php(18): Google\Cloud\PubSub\Subscription->pull()
#25 {main}
  thrown in /app/vendor/google/cloud-pubsub/src/V1/PullRequest.php on line 167
```

**Comment by fowles** [comment]
https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L1227-L1228 this field is marked deprecated.   If you wish to not have the deprecation warning, you need to mark the field as non-deprecated.

**Comment by pkruithof** [comment]
The issue is not that the field is deprecated, but that some internal call is being done which triggers the deprecation warning, without any way to avoid that.

Please consider reopening the issue, as it is not fixed.

**Comment by fowles** [comment]
Ah, I misunderstood.  Is there a way to suppress specific calls to deprecated methods at the callsite?

**Comment by pkruithof** [comment]
Issue is still active.

**Comment by bshaffer** [comment]
I see two potential solutions here:

1. Since this call is used internally, we could just remove the `trigger_error` warning, and say that the `@deprecated` notice will suffice 
2. Similar to @pkruithof's suggestion, we can wrap `trigger_error` in a conditional so it only happens if the field has been set. This would look something like this:
```php
    public function getSomeDeprecatedField()
    {
        if ($this->some_deprecated_field !== null) {
            @trigger_error('some_deprecated_field is deprecated.', E_USER_DEPRECATED);
        }
        return $this->some_deprecated_field;
    }
```

@fowles I'm happy to submit a PR for either of these if you think they're acceptable.

**Comment by bshaffer** [comment]
I can also take this on, if the solution is approved!

**Comment by pkruithof** [comment]
@fowles can you give a 👍 or 👎 in this so we can either fix it, or find another solution to it?

**Comment by googleberg** [comment]
Experience with doc comments is that they are ignored -- a reasonable amount of log nagging is a good nudge in the right direction. Option 2 (triggering deprecation logging only when set), looks good from a protobuf perspective. @bshaffer @pkruithof I leave it to the two of you to decide who implements.

**Comment by pkruithof** [comment]
The issue is still active, however I made a start for the fix in #17607, only I need some help getting it finished. I was hoping @bshaffer could find some time so we can (finally) get this issue resolved 😁 🤞

**Comment by bshaffer** [comment]
@pkruithof I'll take a look!

**Comment by bshaffer** [comment]
@pkruithof I've made my own PR for this, because there were some tricky implementation details. See https://github.com/protocolbuffers/protobuf/pull/17788

**Comment by patrick-levesque** [comment]
Re-opening to get an update on this.

@bshaffer I've checked your PR and it seems it has not yet been merged. Having the same issue with deprecated warning on every pull requests.

**Comment by pkruithof** [comment]
It is actually merged, [it seems](https://github.com/protocolbuffers/protobuf/commit/6d84da5e2d42a8c83373c0bc6d7ed0ca6f78aade). I thought there wasn't a release with this change yet, but it seems it's available since v29.0: https://github.com/protocolbuffers/protobuf/releases/tag/v29.0 🎉

**Comment by bshaffer** [comment]
You're right, we haven't upgraded to protobuf v29 yet, we are still on v25

https://github.com/googleapis/googleapis/blob/master/WORKSPACE#L152

**Comment by pkruithof** [comment]
Do you have an estimate when this will be upgraded?

**Comment by bshaffer** [comment]
@pkruithof not yet but I'll look into it

**Comment by lcobucci** [comment]
@bshaffer our logs are also getting quite noisy and I'd really appreciate if you could share an estimate.

**Comment by bshaffer** [comment]
@lcobucci Sorry for the delay here. The way our client library generation is currently set up, there is one version of protobuf set for ALL client library languages. Unfortunately there are a number of breaking changes in `26.x` which has held up this - and protobuf editions - adoption. 

One option would be to backport these changes into `25.x`. I can look into this and discuss with the protobuf team!

**Comment by bshaffer** [comment]
@lcobucci I have backported the fix for `25.x` in https://github.com/protocolbuffers/protobuf/pull/21033, and confirmed with the protobuf team that we can do a release for that version once this fix gets merged. Then I'll be able to upgrade the client libraries, and get the fix added.

I don't have a time estimate yet - I don't know Protobuf's release schedule, but I'll provide an update once I found out. Once it's released in protobuf, I should be able to get the fix in our client libraries within a week.

**Comment by bshaffer** [comment]
@lcobucci this should be fixed by the end of the week

**Comment by bshaffer** [comment]
@lcobucci This has now been rolled out across all google cloud client libraries. If you consider to see this issue in an up-to-date version of the client libraries, please file a new bug!

**Comment by lcobucci** [comment]
Thanks @bshaffer, we'll rollout the new versions and let you know if anything unexpected happens.

**Comment by pkruithof** [comment]
Thanks @bshaffer for moving this forward. Unfortunately, I'm starting at a new job in a week, and they don't use Google Cloud, so I won't be able to see the result 😅. But still glad to know this annoyance has been fixed!

**Comment by patrick-levesque** [comment]
Thanks @bshaffer, I confirm that the deprecation messages are now gone! 🙌🏻
