### ISSUE TITLE
Camelcase/underscore enforcement make C++ macro reflection difficult. 

### ISSUE THREAD

**Issue by FluorineDog** [protocolbuffers/protobuf#13423]
In most case, the protobuf coding style is fine. However, when deal with generic types, it becomes a real headache. 

we define the following: 
```protobuf
message Cat {...}
message Dog {...}
message Animal {
    oneof animal {
        Cat myCat;
        Dog myDog;
    }
}
```

we have an X macro
```c++
#define APPLY_ANIMAL_TYPES(X)\
X(Cat)\
X(Dog)\

// some code to deal with proto
#define X(TYPE) if(proto.has_my ## X ()) cout << #X;
APPLY_ANIMAL_TYPES(X)
#undef X 
```
but prototbuf will always generate API using `mycat` instead of `myCat`, making the codegen impossble. 

Any workaround to this? google.protobuf.Any is too slow so we don't consider it.

**Comment by fowles** [comment]
unfortunately, any change to these rules would be a very large breaking change for our users.
