### ISSUE TITLE
Support Proto2 in PHP

### ISSUE THREAD

**Issue by shaqaruden** [protocolbuffers/protobuf#13431]
Support Proto 2 already. It's been 6 years

**Comment by fowles** [comment]
In what?  proto2 is supported in all the major languages except pure PHP

**Comment by shaqaruden** [comment]
> In what?  proto2 is supported in all the major languages except pure PHP

Exactly.

**Comment by fowles** [comment]
Odds are strong that we would do this by dropping the pure PHP implementation entirely and only using the upb backed native implementation.  Does that change your interest or desire for this?
