### ISSUE TITLE
Map performance drop introduced between v3.13.0 and v3.14.0

### ISSUE THREAD

**Issue by dkalinowski** [protocolbuffers/protobuf#13437]
**What version of protobuf and what language are you using?**
Version: Previously v3.9.2, issue with upgrading to v3.19.1 - issue **narrowed down to specific commit** between v3.13.0 and v3.14.0 (read below)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
Bazel 5.3.1
GCC 9.4.0-1ubuntu1~20.04.1

**What did you do?**
1. Run OpenVINO Model Server and stress test gRPC endpoint https://github.com/openvinotoolkit/model_server (it contains protobuf v3.9.2)
2. Rebuild OpenVINO Model Server with protobuf v3.19.1 and similar stress tests show 33% perf drop (RPS) with the same message.

**Anything else we should know about your project / environment**
The issue appears only for TensorFlow Serving proto (using proto map as data container), but does not appear for KServe proto (using repeated as data container) - therefore we believe it has something to do with protobuf::Map.
TensorFlow Serving proto: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto#L22
KServe proto: https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/grpc_predict_v2.proto#L183

**Issue narrowed down to one specific commit from this repo**
The performance drop starts from v3.14.0 release, however we managed to narrow down to specific commits on 3.14.x branch: https://github.com/protocolbuffers/protobuf/commit/3fff95e1bd59209a17cd6e3f7e0218eacb35cd88 which is result of merge as seen in picture below:

![commit](https://github.com/protocolbuffers/protobuf/assets/53942023/034f925e-ce7e-4a87-a073-e8d6681e869a)

**Comment by fowles** [comment]
This is far enough in the past that I do not think we will sort through it.  A huge volume of the implementation of map has changed in the intervening years.
