### ISSUE TITLE
protoc: reserved names should be identifiers in the grammar, not strings

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#13440]
As a follow on from #6335, the grammar for reserved names should be updated to support identifiers as values, not just strings:

```diff
- reserved = "reserved" ( ranges | strFieldNames ) ";"
+ reserved = "reserved" ( ranges | strFieldNames | fieldNames ) ";"
  ranges = range { "," range }
  range =  intLit [ "to" ( intLit | "max" ) ]
  strFieldNames = strFieldName { "," strFieldName }
  strFieldName = "'" fieldName "'" | '"' fieldName '"'
+ fieldNames = fieldName { "," fieldName }
```

Bare identifiers aren't as error-prone since there's no risk of forgetting a comma causing the parser to concatenate adjacent tokens into an unintended reserved name.

Eventually, it would be nice to deprecate or remove support for using string values, but removal would be a backwards-incompatible change.

**Comment by fowles** [comment]
@Logofile for the doc part of this

**Comment by jhump** [comment]
@fowles, @Logofile, just to be clear, this isn't a doc bug for the grammar, but a proposal to change the actual parser to accept identifiers (instead of string literals).

This was discussed in a tier 1 review on October 7th, 2022. IIUC, this part of the proposal (the grammar/parser change) was to be delayed until "edition zero". I opened this issue since it looks like "edition zero" is getting close and also for posterity, so this proposal is documented in GitHub.

**Comment by Logofile** [comment]
Ah! That's the piece I was missing. I will add this to the list of things that need to be documented for Editions.

**Comment by mkruskal-google** [comment]
This has been bundled into edition 2023, where we will enforce this new grammar and use prototiller to migrate
