### ISSUE TITLE
Protobuf implementation header and generated headers are incompatible with C++\CLI code

### ISSUE THREAD

**Issue by zhenkas** [protocolbuffers/protobuf#13450]
Currently we are using protobuf 3.1.0 which works good in mixed C++\CLI code, however, newer version(3.21.x) are simply not includable.
So currently it is impossible to compile mixed wrappers with new protobuf.

The problems I found so far:
1. "**nullptr**" is reserved for .NET "**null**" keyword when compiled in mixed mode
     Proposed solution: should be replaced with "**__nullptr**" under **#ifdef _MANAGED**
3. Include of std **mutex.h** is not supported
     Proposed solution: move **stubs\mutex.h** implementation to cc file, like it was in 3.1.0 version

Errors example:
`2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mutex(8): fatal error C1189: #error:  <mutex> is not supported when compiling with /clr or /clr:pure.`

Protobuf version: **3.21.X**
Compiler used: **Visual C++\CLI 2015**

**Comment by fowles** [comment]
We are going to need slightly more information to reproduce this.  Also, I think you are trying to compile in a hybrid CLR mode or something, but I am not quite sure from your description.

MSVC 2019 is the minimum required version of msvc.

https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md
