### ISSUE TITLE
recursive template instantiation exceeded maximum depth of 1024

### ISSUE THREAD

**Issue by PandaBlueYellow** [protocolbuffers/protobuf#13454]
**What version of protobuf and what language are you using?**
Version: v3.21.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 11

**What did you do?**
Compile a proto with 1W+ fields

**What did you expect to see**
Compile succeed

**What did you see instead?**
recursive template instantiation exceeded maximum depth of 1024
the log mentioned the memswap in InternalSwap

**Anything else we should know about your project / environment**
https://github.com/protocolbuffers/protobuf/blob/f607b66d9ff2a65b910ca28b56248ee86c2a7107/src/google/protobuf/compiler/cpp/message.cc#L3247C1-L3279C39
Looks like the ShouldSplit always returns false. Should it consider that the span for memswap cannot exceed 1024?

**Comment by fowles** [comment]
Not sure exactly when we will get to this, but if you have cycles to offer a PR for it that would be appreciated
