### ISSUE TITLE
Protoc generates faulty C# namespace

### ISSUE THREAD

**Issue by nickwinger** [protocolbuffers/protobuf#13482]
Hello,

i'm not sure if this is a bug or how to fix this, haven't found anything on the internet.
We have a package like "my.name.space._3".
This works in protobuf and java generated code.
However in C# generated code the unserscore gets removed, and then the C# Compiler tells an error about that namespace "my.name.space.3".
Seems like only having a number in the namespace in C# is not working.

So how to handle this issue ? And we cannot change the protobuf files, since they are delivered by 3rd party.

C:\protoc --version
libprotoc 24.0

actually it should have been fixed: https://github.com/protocolbuffers/protobuf/pull/10268

Thanks for help,
Nick

**Comment by jskeet** [comment]
Please could you post your specific .proto file? (It's not clear what you mean by "namespace" here - protobuf package, or csharp_namespace option. If you want a specific C# namespace, the simple fix would be to specify it explicitly.)

**Comment by nickwinger** [comment]
Hello,

i mean package in proto file, e.g.:

package my.scope._3

in C#:

namespace my.scope.3

the underscore gets removed which does not work in C#.
The bugfix i linked seem to only preserve the underscore before numbers at the beginning, but the routine has to check and preserve the underscore before numbers on every part of the package/namespace string separated by dots.

**Comment by nickwinger** [comment]
Thank you for the suggestion, i will try it out as a workaround. However it’s not the best solution as we have to modify and scan the delivered 3rd party proto files

**Comment by nickwinger** [comment]
I will try to do a PR based on the fix that has already been made

**Comment by nickwinger** [comment]
here is the PR: https://github.com/protocolbuffers/protobuf/pull/13504

**Comment by jskeet** [comment]
We still intend to address this, but it's unlikely to be in 2023 due to higher-priority issues.

**Comment by jskeet** [comment]
(#13504 is merged, so presumably this is at least better than it was - but I believe there are still improvements we want to make.)
