### ISSUE TITLE
third_party component not present in release 23.4

### ISSUE THREAD

**Issue by onocpj** [protocolbuffers/protobuf#13483]
following documentation:
https://github.com/protocolbuffers/protobuf/blob/v23.4/cmake/README.md

Steps to reproduce:

```
wget https://github.com/protocolbuffers/protobuf/archive/refs/tags/v23.4.zip
unzip v23.4.zip
cd protobuf-23.4
cmake -Dprotobuf_BUILD_TESTS=OFF .
```

result in error:

```
CMake Error at third_party/utf8_range/CMakeLists.txt:31 (add_subdirectory):
  The source directory
   ~/protobuf-23.4/third_party/abseil-cpp

  does not contain a CMakeLists.txt file.
```

conclusion:
release 23.4 do not contain source for third_party dependencies so it is not buildable on its own so it is not possible to compile just from release source package

**Comment by zhangskz** [comment]
Dependencies should be installed separately per the instructions in https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md to keep our distribution to a reasonable size.

"You need to have [CMake](http://www.cmake.org/), [Git](http://git-scm.com/), and [Abseil](https://github.com/abseil/abseil-cpp) installed on your computer before proceeding. We currently support CMake 3.5 and newer on both [Windows](https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#windows-builds) and [Linux](https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#linux-builds)."

You will need to set the `-Dprotobuf_ABSL_PROVIDER=package` and `-DCMAKE_PREFIX_PATH` flags per the documentation in the README.

See https://github.com/protocolbuffers/protobuf/issues/12448 for more details.
