### ISSUE TITLE
Add API to prevent boxing of `Enumerator`s

### ISSUE THREAD

**Issue by KnapSac** [protocolbuffers/protobuf#13503]
**What language does this apply to?**

C#

**Describe the problem you are trying to solve.**

When iterating over `MapField`s and `RepeatedField`s using the `GetEnumerator` method, the
enumerator struct is boxed, as the signature of `GetEnumerator` is:

```csharp
public IEnumerator<T> GetEnumerator()
```

The interface return type causes the enumerator to always be boxed. This is not only slower, but
also allocates some memory. The amount of allocated memory is usually not a problem, but if you're
doing it inside of a loop, this might end up being an issue. See the benchmark results at the bottom
of this issue for more details.

**Describe the solution you'd like**

I'd like an API which exposes the enumerator without boxing it. Collections in the BCL also do this,
see
https://github.com/dotnet/runtime/blob/b68382b60349fece947020d234d4a590e9bd5fe8/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L365.

Unfortunately it isn't possible to change the return type of `GetEnumerator`, as that method is
required by the `IEnumerable` interface. One option would be to make the implementation explicit, in
which case adding a new `GetEnumerator` method with a different return type becomes possible. This
has the benefit that `foreach` loops will also use this overload, increasing their performance.
However, this would be a breaking change.

An alternative to that might be to simply expose a new method `GetEnumeratorWithoutBoxing`, which
could be consumed manually. For `MapField` this is as simple as exposing the `LinkedList`
enumerator. For `RepeatedField` this would be slightly more involved, as arrays in C# don't have a
struct enumerator, but it would still be a very straight forward implementation. I included the
implementations I used for the benchmarks at the end of this issue.

I'd be more than happy to create a PR for this, if this is something you're interested in.

**Describe alternatives you've considered**

As shown in the benchmarks below, boxing of the `RepeatedField` enumerator can be avoided by using a
`for` loop, which performs comparably to an enumerator which isn't boxed. This workaround is not
possible for the `MapField` type, as you can't index it with an `int`.

**Benchmarks.**

<details>
<summary>Benchmark results MapField</summary>

```

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 7.0.400
  [Host]             : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 7.0           : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET Framework 4.8 : .NET Framework 4.8.1 (4.8.9167.0), X64 RyuJIT VectorSize=256


```

| Method           | Job                | Runtime            |     Mean |    Error |   StdDev |   Gen0 | Allocated |
| ---------------- | ------------------ | ------------------ | -------: | -------: | -------: | -----: | --------: |
| DefaultForeach   | .NET 7.0           | .NET 7.0           | 53.59 ns | 1.085 ns | 1.372 ns | 0.0038 |      48 B |
| CustomEnumerator | .NET 7.0           | .NET 7.0           | 40.98 ns | 0.606 ns | 0.567 ns |      - |         - |
| DefaultForeach   | .NET Framework 4.8 | .NET Framework 4.8 | 90.82 ns | 1.738 ns | 1.626 ns | 0.0088 |      56 B |
| CustomEnumerator | .NET Framework 4.8 | .NET Framework 4.8 | 43.02 ns | 0.465 ns | 0.435 ns |      - |         - |

</details>

<details>
<summary>Benchmark results RepeatedField</summary>

```

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 7.0.400
  [Host]             : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 7.0           : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET Framework 4.8 : .NET Framework 4.8.1 (4.8.9167.0), X64 RyuJIT VectorSize=256


```

| Method           | Job                | Runtime            |      Mean |     Error |    StdDev |   Gen0 | Allocated |
| ---------------- | ------------------ | ------------------ | --------: | --------: | --------: | -----: | --------: |
| DefaultForeach   | .NET 7.0           | .NET 7.0           | 33.161 ns | 0.3042 ns | 0.2846 ns | 0.0032 |      40 B |
| CustomEnumerator | .NET 7.0           | .NET 7.0           |  5.833 ns | 0.1348 ns | 0.1195 ns |      - |         - |
| DefaultFor       | .NET 7.0           | .NET 7.0           |  5.375 ns | 0.0696 ns | 0.0651 ns |      - |         - |
| DefaultForeach   | .NET Framework 4.8 | .NET Framework 4.8 | 46.320 ns | 0.7284 ns | 0.6457 ns | 0.0063 |      40 B |
| CustomEnumerator | .NET Framework 4.8 | .NET Framework 4.8 | 14.018 ns | 0.1128 ns | 0.1000 ns |      - |         - |
| DefaultFor       | .NET Framework 4.8 | .NET Framework 4.8 | 13.320 ns | 0.0847 ns | 0.0793 ns |      - |         - |

</details>

<details>
<summary>MapField custom enumerator implementation</summary>

```csharp
public LinkedList< KeyValuePair< TKey, TValue > >.Enumerator GetCustomEnumerator( ) => list.GetEnumerator( );
```

</details>

<details>
<summary>RepeatedField custom enumerator implementation</summary>

```csharp
public Enumerator GetCustomEnumerator( ) => new( this );

public struct Enumerator : IEnumerator< T >
{
    private const int UNSET_IDX = -1;
    private readonly RepeatedField< T > repeatedField;

    private int idx;

    internal Enumerator(
        RepeatedField< T > repeatedField )
    {
        this.repeatedField = repeatedField;
        idx = UNSET_IDX;
    }

    public readonly void Dispose( )
    {
    }

    public bool MoveNext( ) => ++idx < repeatedField.count;

    public void Reset( ) => idx = UNSET_IDX;

    readonly object IEnumerator.Current => repeatedField[idx];

    public readonly T Current => repeatedField[idx];
}
```

</details>

<details>
<summary>Benchmark implementations</summary>

```csharp
[MemoryDiagnoser]
[SimpleJob( RuntimeMoniker.Net70 )]
[SimpleJob( RuntimeMoniker.Net48 )]
public class RepeatedFieldEnumeratorBenchmark
{
    private RepeatedField< int > repeatedField;

    [GlobalSetup]
    public void Setup( )
    {
        repeatedField = new RepeatedField< int >( );
        for ( int i = 0;
              i < 10;
              i++ )
        {
            repeatedField.Add( i );
        }
    }

    [Benchmark]
    public int DefaultForeach( )
    {
        int result = 0;
        foreach ( int i in repeatedField )
        {
            result = i;
        }
        return result;
    }

    [Benchmark]
    public int CustomEnumerator( )
    {
        int result = 0;
        using( RepeatedField< int >.Enumerator enumerator = repeatedField.GetCustomEnumerator( ) )
        {
            while ( enumerator.MoveNext( ) )
            {
                result = enumerator.Current;
            }

            return result;
        }
    }

    [Benchmark]
    public int DefaultFor( )
    {
        int result = 0;
        var repeated = repeatedField;
        for ( int i = 0;
              i < repeated.Count;
              i++ )
        {
            result = repeated[ i ];
        }
        return result;
    }
}

[MemoryDiagnoser]
[SimpleJob( RuntimeMoniker.Net70 )]
[SimpleJob( RuntimeMoniker.Net48 )]
public class MapFieldEnumeratorBenchmark
{
    private MapField< int, int > mapField;

    [GlobalSetup]
    public void Setup( )
    {
        mapField = new MapField< int, int >( );
        for ( int i = 0;
              i < 10;
              i++ )
        {
            mapField.Add(
                i,
                i );
        }
    }

    [Benchmark]
    public int DefaultForeach( )
    {
        int result = 0;
        foreach ( KeyValuePair< int, int > keyValuePair in mapField )
        {
            result = keyValuePair.Value;
        }
        return result;
    }

    [Benchmark]
    public int CustomEnumerator( )
    {
        int result = 0;
        using( LinkedList< KeyValuePair< int, int > >.Enumerator enumerator = mapField.GetCustomEnumerator( ) )
        {
            while ( enumerator.MoveNext( ) )
            {
                result = enumerator.Current.Value;
            }

            return result;
        }
    }
}
```

</details>

**Comment by jskeet** [comment]
While I acknowledge the small performance benefit available, I would really rather not address this. I would be really surprised to see this make a significant difference in any real application code, and the additional code has complexity just due to being "additional code".

If you have evidence that this is causing a problem in *real* code instead of microbenchmarks, I'm happy to reconsider - but I don't like micro-optimizing just because there's an opportunity to do so.

**Comment by KnapSac** [comment]
I came across this when profiling a real world application. The application has some hot loops where the boxing causes enough garbage to put pressure on the garbage collector. Caching the enumerator also isn't really an option, as the collection may be modified.

The `for` loop workaround is fine for the `RepeatedField`, but I could find no such workaround for the `MapField`. If you have any suggestions as to how I might prevent boxing the `MapField` enumerator too often, I'm all ears.

**Comment by KnapSac** [comment]
I was iterating over non-empty fields, during which I collect some values. These values are used later on. Which values are collected depends on some input arguments, which is why the lookup has to happen quite often. Changing this is not feasible, and because modifications are possible caching is also quite hard.

I do get your point about the benefits potentially not outweighing the maintenance cost, so if you decide not to add this, I understand. There are other areas where the application can be improved performance wise, but as these boxed enumerators showed up as a significant part of the allocations I thought it would be worth asking at least :).

**Comment by jskeet** [comment]
Okay, thanks for the conversation. I'll mull on it... 

For the map iterator type, I'd definitely want us to have our own custom struct rather than building the implementation detail of `LinkedList<KeyValuePair<TKey,TValue>>.Enumerator` being exposed in the API. But I suspect that could be an implementation which just delegates all calls. It's a shame we can't do that for the `RepeatedField` iterator as well (which we could if we used `List<T>` behind the scenes).

Will discuss it with colleagues and see. (Even if we end up doing it, it won't be for a while - just to set expectations.)

**Comment by jskeet** [comment]
I'm looking at this again, thinking about what it might look like if we *did* implement this. Having to call GetCustomEnumerator and then use the enumerator explicitly is somewhat annoying.

How would you feel about a method called `CreateNonBoxingEnumerable()`, returning a struct that then had a custom enumerator? That way users would be able to write:

```csharp
RepeatedField<string> x = ...;
foreach (var value in x.CreateNonBoxingEnumerable())
{
    ...
}
```

(Obviously the name is up for debate.)

**Comment by KnapSac** [comment]
I feel like that's a fine trade-off, I don't mind having to use a slightly more inconvenient API to get more performance.

**Comment by jskeet** [comment]
@KnapSac: My suggestion is that having a method returning an enumerable rather than an enumerator would be *more* convenient than your original proposal. I agree with your analysis that it would be a breaking change to simply change the type of the existing method. (That's something we could do in a new major version, if that ever happens, of course.)

If you think `CreateNonBoxingEnumerator()` (or whatever) would be preferable go `CreateNonBoxingEnumerable()`, please let me know your reasoning. I may have missed something.

**Comment by KnapSac** [comment]
@jskeet so would you be open to a PR adding `CreateNonBoxingEnumerable()`?

**Comment by jskeet** [comment]
@KnapSac: I still need to discuss it with colleagues. The fact that it's entirely separate from the "normal" flow at least reduces the risk - if we get something wrong in the optimized flow, it won't affect anyone else.

I'm happy for you to create a PR for it should you wish, but without any guarantees that we'll take it in the end. It's *probably* simplest for you to just sit tight - I don't expect the code to take me long if we decide to do it.

**Comment by KnapSac** [comment]
Alright, I'll wait and see.

**Comment by jskeet** [comment]
Okay, I've discussed this with a colleague, and given that it's purely opt-in (so there's no risk of breaking existing users) we're happy to go ahead. Now we get to bike-shed on the names :) I'd suggest nested struct names of "Enumerable" and "Enumerator"... so we just need the name of the method to create the enumerable. Thoughts welcome :)

**Comment by KnapSac** [comment]
How about `EnumerateNonBoxing`? I feel like that captures the intent of the method pretty well, while also providing a reason for its existence in addition to the regular `IEnumerable` implementation.

**Comment by jskeet** [comment]
Hmmm... arguably it doesn't *start* enumerating - it just provides what you need to do so.

How about `AsNonBoxingEnumerable()`? The "As" gives the appropriate impression of "this returns something which is a view over the original data"... it's a bit long-winded though.
(I'm expecting this to go back and forth a lot - and we might end up coming back to EnumerateNonBoxing at the end. Hope it's not too frustrating.)

**Comment by KnapSac** [comment]
Haha, no problem!

I like the `As` part, especially because this is quite a common pattern in C#. What would be a more concise way of saying non-boxing? Perhaps `AsStructEnumerable` might be an option, but I don't really like that more than `AsNonBoxingEnumerable`.

**Comment by jskeet** [comment]
@KnapSac: Please could you look at #14284 and see if this looks okay to you in terms of the code? If it does, I'll write up the docs, which will probably take longer than the code...
