### ISSUE TITLE
MessageToDict(including_default_value_fields=True) Not Supplying Defaults For Nested Messages Or `google.protobuf.BoolValue` types

### ISSUE THREAD

**Issue by alordthorsen** [protocolbuffers/protobuf#13518]
**What version of protobuf and what language are you using?**
Version:  3.21.12 (I'll need to custom compile protoc to upgrade since this is the latest version I can get from apt for AL2)
python-protobuf == "4.24.0"
Language: Python

**What operating system (Linux, Windows, ...) and version?**
 Docker Image from public.ecr.aws/lambda/python:3.9 (AKA, Amazon Linux 2)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9

**What did you do?**
I have a nested schema
```
message Shipment {
    reserved 9;
    string objectId = 1;
    string metadata = 2;
    CustomsDeclaration customsDeclaration = 3;
    }
    
message CustomsDeclaration {
  string objectId = 1;
  bool certify = 2;
  google.protobuf.BoolValue isTest=3;
}
```

That Is then parsed via ParseByString
```
shipment = rating_pb2.Shipment()
shipment.ParseFromString(protobuf_encoded) 
```

**What did you expect to see**
I expected `MessageToDict(shipment, including_default_value_fields=True)` to define default values for each of the fields in the nested`customsDeclaration`. 
```
MessageToDict(shipment, including_default_value_fields=True)["customsDeclaration"]
{'objectId': '', 'certify': False, 'isTest': False}
```

**What did you see instead?**

When Using `MessageToDict` I'm not seeing default  Values for `CustomsDeclaration` for cases when `CustomsDeclaration` is missing

```
(Pdb) shipment.customsDeclaration

(Pdb) hasattr(shipment, "customsDeclaration")
True
(Pdb) MessageToDict(shipment)["customsDeclaration"]
*** KeyError: 'customsDeclaration'
(Pdb) MessageToDict(shipment, including_default_value_fields=True)["customsDeclaration"]
*** KeyError: 'customsDeclaration'
(Pdb) type(shipment.customsDeclaration)
<class 'rating.customs_pb2.CustomsDeclaration'>
```
I'm additionally not seeing defaults supplied for `google.protobuf.BoolValue` types which are requiring direct invocations of `MessageToDict` 

```
(Pdb) MessageToDict(shipment.customsDeclaration.isTest, including_default_value_fields=True)
False
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by bmaxdk** [comment]
Have you try install correct version of `portoco buffer`?
Try this method. I had same issue before but I solved through this.

## Troubleshooting `protocol buffer`
Issue appeared when `protoc version` is not supported to current `turtlebot_gazebo` setup.First need to check **protocol buffer** version:

```bash
$ protoc --version
```

if `protoc` version is higher, try libprotoc 3.6.1:

Download `protobuf-cpp-3.6.1.tar.gz` in [Protocol Buffers v3.6.1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1)

```bash
$ tar -xzf protobuf-cpp-3.6.1.tar.gz
$ cd protobuf-3.6.1
# Install Dependencies for prtobuf
$ sudo apt-get install autoconf automake libtool curl make g++ unzip
$ ./autogen.sh

# Compile and install:
$ ./configure
$ make
$ sudo make install
# Update the Shared Libarary Cache:
$ sudo ldconfig

# Varify protoc version
$ protoc --version

```
