### ISSUE TITLE
Failed to generate libprotobuf.lib on Windows11 #8312

### ISSUE THREAD

**Issue by lizexu-nreal** [protocolbuffers/protobuf#13532]
What version of protobuf and what language are you using?
Version: v3.8.0.
Language: C++
What operating system (Linux, Windows, ...) and version?
Windows11
What runtime / compiler are you using (e.g., python version or gcc version)
MSVC
TensorRT-master v 8.2.0.6
What did you do?
cmake .. `
>> -G "Visual Studio 15 2017 Win64" `
>> -DTRT_LIB_DIR="D:/TensorRT-8.2.0.6/lib" `
>> -DTRT_OUT_DIR="$(Get-Location)\out" `
>> -DCMAKE_CUDA_COMPILER="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/bin/nvcc.exe" `
>> -DCUBLASLT_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cublasLt.lib" `
>> -DCUBLAS_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cublas.lib" `
>> -DCUDART_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cudart.lib" `
>> -DCUDNN_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cudnn.lib" `
>> -DCMAKE_CXX_FLAGS="/WX-"
Protobuf settings
![image](https://github.com/protocolbuffers/protobuf/assets/134259938/4cfe0010-ee1d-4d3e-a08c-8df88fd0704d)
“D:\TensorRT-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“D:\TensorRT-master\build\parsers\onnx\nvonnxparser.vcxproj”(默认目标) (10) ->
(Link 目标) ->
  LINK : fatal error LNK1104: 无法打开文件“..\..\third_party.protobuf\lib\libprotobuf.lib” [D:\TensorRT-master\build\parsers\
onnx\nvonnxparser.vcxproj 
  I generated libprotobufd.lib under this path

**Comment by zhangskz** [comment]
v3.8.0 is very old and far out of our support window -- the latest version is v24.x. Can you check if you still hit this using a newer protobuf version?
