### ISSUE TITLE
[Kotlin] error: duplicate class: 

### ISSUE THREAD

**Issue by nesteiner** [protocolbuffers/protobuf#13535]
**What version of protobuf and what language are you using?**
Version: I don't know, I just find libprotoc 23.4

Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
Linux nesteiner 6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
![image](https://github.com/protocolbuffers/protobuf/assets/46296608/935ecdcd-bc42-48ad-aef9-8bf7caa775ae)

to compile the `.protoc` file, cd the project directory, enter the `protoc -I=src/main/proto/ --kotlin_out=src/main/kotlin/ --java_out=src/main/java .proto`

and in the `java` directory
![image](https://github.com/protocolbuffers/protobuf/assets/46296608/76eccbcf-3b85-4ed1-8c55-5d4b7c3743fc)
![image](https://github.com/protocolbuffers/protobuf/assets/46296608/b609ae3e-db82-4e37-a795-edb662909582)

the duplicate class is in the 
![image](https://github.com/protocolbuffers/protobuf/assets/46296608/d159084b-e497-48ed-8d32-d97ec428dd76)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
this is my `build.gradle.kts`
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "3.1.2"
	id("io.spring.dependency-management") version "1.1.2"
	kotlin("jvm") version "1.8.22"
	kotlin("plugin.spring") version "1.8.22"
	id("com.google.protobuf") version "0.9.4"
}

group = "com.transfer-clippy"
version = "0.0.1-SNAPSHOT"

java {
	sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.springframework.boot:spring-boot-starter-websocket")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	runtimeOnly("org.postgresql:postgresql")
	implementation("org.jetbrains.exposed:exposed-spring-boot-starter:0.41.1")

	testImplementation("org.springframework.boot:spring-boot-starter-test")
	implementation("org.apache.commons:commons-lang3:3.13.0")
	// https://mvnrepository.com/artifact/com.google.protobuf/protobuf-kotlin
	implementation("com.google.protobuf:protobuf-kotlin:3.24.0")

}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xjsr305=strict"
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

**Comment by sjlee2016** [comment]
I had the same issue and I was able to resolve it by adding this to build.gradle.kts 
tasks {
   withType<Copy> {
      filesMatching("**/*.proto") {
         duplicatesStrategy = DuplicatesStrategy.INCLUDE
  } 
}
}

**Comment by nesteiner** [comment]
actually I found that just delete the src/main/proto can solve the problem

**Comment by zhangskz** [comment]
Looks like using DuplicateStrategy.INCLUDE in gradle should work around this and that this issue is otherwise resolved. Please reopen if further action is needed here.
