### ISSUE TITLE
Protobuf-C++ Cocoapods build failure due to missing dependencies on abseil and utf8_range

### ISSUE THREAD

**Issue by combinatorial** [protocolbuffers/protobuf#13596]
**What version of protobuf and what language are you using?**
Version: 4.24.0 (Protobuf-C++ via cocoapods)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS 13.4.1 (c) 
targeting iOS 15 or greater

**What runtime / compiler are you using (e.g., python version or gcc version)**
Xcode 14.3

**What did you do?**
1. Upgraded from 3.19.5 -> 4.24.0 via `pod update  Protobuf-C++`
2. Rebuilt code

**What did you expect to see**
Code builds

**What did you see instead?**

The following error: `'absl/strings/string_view.h' file not found`

I then manually added the following to the Header Search Paths: `$(SRCROOT)/abseil`

And get the error: `'utf8_validity.h' file not found`

I'd be happy to work on a fix. The dependency on abseil is an easy fix, but the utf8_range dependency is less clear. It is not available as a "pod". I could submit a change for that repo to create a pod, but it would then require maintaining with new releases. It looks like gRPC embeds utf8_range as a 3rd party project. What is the preferred approach here?

**Comment by lovivid** [comment]
> The only C++ build systems we actively support are Bazel and CMake. However, we will accept PRs to fix our Cocoapods setup if you work out the fix. Abseil is likely in a similar boat, where you'd have to convince them to accept a PR adding the config. For utf8_range, now that upb has been merged into the protobuf repo, we'll be doing the same there. So the source of truth should be here after that

If you know your product can not run via cocoapods, why publish new version one after another。
Waiting another guy fix Known bug for your product。
Shame on you。

**Comment by mkruskal-google** [comment]
> If you know your product can not run via cocoapods, why publish new version one after another

We didn't know, that's the point.  Our official support matrix can be found at https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md.  Anything not listed there isn't actively maintained by us, and we rely on the community to find and fix issues.

**Comment by spencersalazar** [comment]
> However, we will accept PRs to fix our Cocoapods setup if you work out the fix.  

I have this working in a local dev environment, would be happy to submit a PR soon. It would depend on abseil also accepting a PR for Cocoapods support (which I also can submit a PR for).

**Comment by mkruskal-google** [comment]
That would be great, I can backport this into 23.x too for our next patch release

**Comment by e-n-0** [comment]
Hello!
I'm unfortunately having the same issue when building with the pod `Protobuf-C++`.

**Comment by kimle78** [comment]
> It would depend on abseil also accepting a PR for Cocoapods support (which I also can submit a PR for).

@spencersalazar Did you also submit a PR to abseil based on your above comment? Can you share that PR link here?

**Comment by gansh8** [comment]
Try building abseil-cpp with `-std=c++17`

It's worked for me.
