### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool: out of memory

### ISSUE THREAD

**Issue by harupy** [protocolbuffers/protobuf#13630]
**What version of protobuf and what language are you using?**
Version: 4.24.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc version (v3.19.4)?

**What did you do?**

```
git clone https://github.com/harupy/proto-oom
cd proto-oom
docker build .
```

https://github.com/harupy/proto-oom contains all the files/code required to reproduce the issue.

**What did you expect to see**

No error?

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from bar.scalapb_pb2 import *
  File "/bar/scalapb_pb2.py", line 18, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61r/scalapb.proto\x12\x0b\x62\x61r.scalapb\x1a google/protobuf/descriptor.proto\"L\n\x0eScalaPbOptions\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66lat_package\x18\x02 \x01(\x08\x12\x0e\n\x06import\x18\x03 \x03(\t\"!\n\x0eMessageOptions\x12\x0f\n\x07\x65xtends\x18\x01 \x03(\t\"\x1c\n\x0c\x46ieldOptions\x12\x0c\n\x04type\x18\x01 \x01(\t:K\n\x07options\x12\x1c.google.protobuf.FileOptions\x18\xfc\x07 \x01(\x0b\x32\x1b.bar.scalapb.ScalaPbOptions:N\n\x07message\x12\x1f.google.protobuf.MessageOptions\x18\xfc\x07 \x01(\x0b\x32\x1b.bar.scalapb.MessageOptions:H\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xfc\x07 \x01(\x0b\x32\x19.bar.scalapb.FieldOptionsB\x1e\n\x1corg.mlflow.scalapb_interface')
TypeError: Couldn't build proto file into descriptor pool: out of memory
```

**Anything else we should know about your project / environment**

**Comment by smurching** [comment]
Hi @anandolee , thanks for helping out with this issue - do you have a sense for when you might be able to take a look? This is currently blocking us from fixing a bug in an open source project (https://github.com/mlflow/mlflow/issues/9360) that we maintain, so any suggestions would be much appreciated

**Comment by osomdev** [comment]
Not sure if this is the only issue but in my case I was able to narrow this down to re-use of id of message option (in `google.protobuf.MessageOptions`) - when 2 protocols are using the same id it hits OOME. After changing the id to unique value it works just fine.

proto_a.proto:

```proto
syntax = "proto2";

import "google/protobuf/descriptor.proto";

package proto_a;

extend google.protobuf.MessageOptions {
  optional int32 option_x = 50000 [default = -1]; // <===========
}

message SomeMessageA {
  option (option_x) = 0;
  optional string message = 1;
}
```

proto_b.proto:

```proto
syntax = "proto2";

import "google/protobuf/descriptor.proto";

package proto_b;

extend google.protobuf.MessageOptions {
  optional int32 option_x = 50000 [default = -1]; // <===========
}

message SomeMessageB {
  option (option_x) = 0;
  optional string message = 1;
}
```

Changing 50000 to 50001 in one of files allows to import messages from both protocols.

Not sure if this is expected (maybe for some reason you cannot re-use the ids) or a bug. It's very inconvenient for sure.

**Comment by tardyp** [comment]
To conclude on this topic, the error message 'out of memory' comes from upb, and it is not really an out of memory.

The message is confusing, it actually means there is  conflict of extension number.

you probably have two .proto files, that define extension using the same number ( 50001 in the example abox)
