### ISSUE TITLE
How to unsign the CLA?

### ISSUE THREAD

**Issue by graywolf** [protocolbuffers/protobuf#13703]
Hello, this project requires a CLA, and I did sign it in the past. However, I would like to revoke the signature going forward. How can I do so?

**Comment by zhangskz** [comment]
I believe you can manage your agreements at https://cla.developers.google.com/ -- perhaps this includes revoking or a contact to help do so?

**Comment by zhangskz** [comment]
Received the following answer internally: "Unfortunately, it is not possible for a contributor to "unsign" our ICLA. They are welcome to cease contributing. But past contributions will continue to be governed by the CLA, and if the contributor wants to make any future contributions, they will need to be made under the terms of our CLA."

Unfortunately it looks like what you're asking for isn't possible, but you're welcome to avoid future contributions to Protobuf. Closing as resolved, but of course feel free to respond / reopen if you have further followups.

**Comment by zhangskz** [comment]
You can email [cla-submissions@google.com](mailto:cla-submissions@google.com) to notify Google if you have become aware of any facts or circumstances that would make the CLA representations inaccurate.
