### ISSUE TITLE
Python weakref support for upb protobuf implementation.

### ISSUE THREAD

**Issue by bostikforever** [protocolbuffers/protobuf#13727]
Weakref support was dropped in the upb-backed  implementation of protobuf for python.

This is a regression as you can imagine, since any application depending on weakref to cache shared proto objects cannot work with the upb implementation. See for instance this issue: https://github.com/protocolbuffers/protobuf/issues/11834

The pre-existing python and cpp message implementations have support for weakref: support in the python implementation is trivial as objects defined in python are weakrefable by default, except for a few cases. For the cpp implementation it seems that the weakref protocol was appropriately implemented using the CPython APIs.

If there are no design considerations as to why upb should not have weakref support then I propose we add them similarly to what we have for the cpp implementation.

I have opened the following two PRs to address this issue:
1. https://github.com/protocolbuffers/protobuf/pull/13464 this adds tests to the protobuf repository to expose the weakref regression (note that the tests would not fail in the protobuf repo as they are exercised only against the python and cpp implementations.
2. https://github.com/protocolbuffers/upb/pull/1458 this adds weakref support to the upb impelementation. Prior to this changeset, linking the upb python package against the protobuf repo @ https://github.com/bostikforever/protobuf/tree/weakref-tests should cause these new test failures:
   * See https://github.com/bostikforever/upb/tree/weak-ref-tests-fail pointing to https://github.com/bostikforever/protobuf/tree/weakref-tests where the weakref tests fail without the weakref support added, and
   * https://github.com/bostikforever/upb/tree/weakref-support-test where the weakref tests pass as we have weakref support on this branch. 

The changes themselves are quite trivial, I am open to modifying to suit style, etc. Please give feedback regarding objections as to why weakref support might not be suitable for upb.

**Comment by haberman** [comment]
@anandolee can you take a look?

**Comment by anandolee** [comment]
sorry for late reply Bolutife. Can you have these two PRs together and assign me to review? The PR will not pass the test for merge if only add the test first

**Comment by bostikforever** [comment]
Hi @anandolee Thanks for the reply. As I recall the PRs were created separately because at the time of filling them, the python ubp implementation lived in a separate repo: https://github.com/protocolbuffers/upb/pull/1458#issuecomment-1710782359

I would work on consolidating the PRs into a single PR and assign to you tomorrow (it's quite late here already).

**Comment by bostikforever** [comment]
Hi @anandolee I have now updated https://github.com/protocolbuffers/protobuf/pull/13464 to contain the fix from the old upb PR (https://github.com/protocolbuffers/upb/pull/1458)

**Comment by bostikforever** [comment]
@anandolee @haberman I've updated my branch 2 weeks ago on your request, can you please take a look?
