### ISSUE TITLE
upb cmake libraries have names that conflict with absl libraries.

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#13738]
cmake targets `base`, `hash` (and possibly some others) have the same name as targets from absl cmake build.
So if one includes both upb and absl in a single cmake project via `add_subdirectory`, you'll get the error listed below.

gRPC depends on both upb and absl, so if we were using upb's cmake build, we would run into this problem.
For now gRPC uses a custom build for upb (for team internal reasons), but we want to switch to using the official upb's CMakeLists.txt soon and this issue prevents it.

The error:
```
CMake Error at third_party/upb/cmake/CMakeLists.txt:96 (add_library):
  add_library cannot create target "base" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "/usr/local/google/home/jtattermusch/github/grpc/third_party/abseil-cpp/absl/base".
  See documentation for policy CMP0002 for more details.


CMake Error at third_party/upb/cmake/CMakeLists.txt:102 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "base".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * third_party/abseil-cpp/CMake/AbseilHelpers.cmake:255 (target_link_libraries)



CMake Error at third_party/upb/cmake/CMakeLists.txt:299 (add_library):
  add_library cannot create target "hash" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "/usr/local/google/home/jtattermusch/github/grpc/third_party/abseil-cpp/absl/hash".
  See documentation for policy CMP0002 for more details.


CMake Error at third_party/upb/cmake/CMakeLists.txt:304 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "hash".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * third_party/abseil-cpp/CMake/AbseilHelpers.cmake:255 (target_link_libraries)
```

**Comment by haberman** [comment]
> if we were using upb's cmake build

upb's current CMake build isn't really used by anybody right now. I agree we want to get to a point where gRPC would be using a upb CMake build, but to get there I think we should probably start from scratch. I don't think incremental evolution of the existing CMake files is the way to go, especially since they use a Bazel -> CMake translator that we need to re-evaluate.

It would help to get a set of requirements from gRPC about what parts of the library you use. I think we'd want to keep our set of exposed targets relatively small, rather than translate every cc_library() into a public CMake target like we do now.

**Comment by veblush** [comment]
Oh this looks to be caused by how gRPC pulls in dependencies. gRPC has two ways of doing this; i) `add_subdirectory` and ii) `find_package`. `find_package` doesn't have this limit where two different libraries cannot have targets with the same name but `add_subdirectory` does.

- https://gitlab.kitware.com/cmake/cmake/-/issues/22687
- https://github.com/grpc/grpc/issues/29608

So gRPC may need to revisit this issue of dropping `add_subdirectory` option for its dependencies.

**Comment by jtattermusch** [comment]
> Oh this looks to be caused by how gRPC pulls in dependencies. gRPC has two ways of doing this; i) `add_subdirectory` and ii) `find_package`. `find_package` doesn't have this limit where two different libraries cannot have targets with the same name but `add_subdirectory` does.
> 
> * https://gitlab.kitware.com/cmake/cmake/-/issues/22687
> * [gRPC Cmake dependency management using add_subdirectory grpc/grpc#29608](https://github.com/grpc/grpc/issues/29608)
> 
> So gRPC may need to revisit this issue of dropping `add_subdirectory` option for its dependencies.

So this make sense from some perspective, but generally CMake's `add_subdirectory` (or FetchContent, which under the hood does add_subdirectory anyway AFAIK) is quite a common way to add dependencies in the cmake world (especially if you are using a "developer" build, not a final installation by the end user), so using it doesn't really strike me as wrong.

Ad @ericsalo 's comment: yes, in a sense library names need to be globally unique (or it's a big advantage at least) - for example, look at library names in linux distributions, you can't have two libraries of the same name.  I think for upb's cmake build, this can be achieved by combination of two approaches:
- add a "upb_" prefix to all the libraries exposed by cmake (= the ones other projects are supposed to depend on) - this greatly reduces the chance that other projects will chose to name their libraries with the same name
- reduce the number for libraries exposed by upb's cmake (e.g. by amalgamating internal upb libraries into "public" targets and not exposing them in the CMakeLists.txt directly). Fundamentally, cmake is a different build system than bazel and it has different needs. While in bazel it makes a lot of sense to have a large number of very granular library targets with possibly complex dependency trees, in cmake you should only publicly expose libraries that are supposed to be visible public libraries in e.g. the linux/unix style - i.e. they need to be installable into e.g. /usr/lib, which requires them to have "globally" unique nam. Since such libraries are often packaged separately (dpkg, vcpkg etc)., there's high overhead on having many publicly exposed libraries.
