### ISSUE TITLE
Build Error with c++20

### ISSUE THREAD

**Issue by Alfus** [protocolbuffers/protobuf#13742]
I am trying to build gRPC from source and I get the following error message:
```
external/upb/upbc/names.cc:89:26: error: ISO C++20 considers use of overloaded operator '!=' (with operand types 'upb::MessageDefPtr::FieldIter' and 'upb::MessageDefPtr::FieldIter') to be ambiguous despite there being a unique best viable function with non-reversed arguments [-Werror,-Wambiguous-reversed-operator]
  for (const auto& field : message.fields()) {
                         ^
external/upb/upb/reflection/def.hpp:321:10: note: candidate function with non-reversed arguments
    bool operator!=(const FieldIter& other) { return i_ != other.i_; }
         ^
external/upb/upb/reflection/def.hpp:322:10: note: ambiguous candidate function with reversed arguments
    bool operator==(const FieldIter& other) { return i_ == other.i_; }
         ^
```

I tried several different ways to disable this error using my bazel env, but it looks like the actual build target for names.cc is specifying the flags:
https://github.com/protocolbuffers/upb/blob/main/bazel/build_defs.bzl#L35

Any suggestions on a work around or a fix?

Thanks!

**Comment by kgreenek** [comment]
For those finding this from a google search, here is the work-around I found. This disables all warnings for external projects by adding `-w` to the copts for any targets under external.

Put these lines in your `.bazelrc`

```
# Disable warnings for targets that are outside the workspace.
build --per_file_copt=external/.*@-w
build --host_per_file_copt=external/.*@-w
```
