### ISSUE TITLE
Serveral problem of cmake users(output name, including path and installation config)

### ISSUE THREAD

**Issue by owent** [protocolbuffers/protobuf#13751]
Hi, I'm a cmake user and I tried to use `cmake/make_cmakelists.py` to generate `CMakeLists.txt` and integrate upb into my project and find some problems.

1. The generated dependency of `utf8_range` is invalid because it has a `/third_party/` prefix.
2. CMake CONFIG files and is missing and also nothing to install when I try to create a prebuilt package.
3. Should all exported header be under `upb/` ? The `third_party/utf8_range/utf8_range.h` is a different path from others.
4. Could all output name of libraries in upb startswith `upb` ? There are a lot of targets (`extension_registry`, `mini_table`, `fastdecode` and etc) now , and if we install them into any path, we can not tell which files are belong to upb.

Could we have a disscuss these topics and can I create a PR for them?

**Comment by owent** [comment]
#15114 also fix this issue.

**Comment by haberman** [comment]
We have some new CMake support in the works. Assigning @ericsalo who is working on this.

**Comment by ericsalo** [comment]
Bouncing over to @mkruskal-google who actually did the work.
