### ISSUE TITLE
DescriptorProtos' `leading_comment` (etc) should keep indentation 

### ISSUE THREAD

**Issue by pd-nisse** [protocolbuffers/protobuf#13826]
**What language does this apply to?**
I am using both proto2 and proto3, and my plugin is written using the Python library

**Describe the problem you are trying to solve.**
During writing my own `protoc` plugin in Python, I noticed that when accessing `leading_comment` (or any of the other comment properties), that any indentation is stripped and all lines in a multi-line comment appear to be equally indented.
This is a bit of a challenge, because we include certain formatting in our `.proto` file comments that we would like to pass on to custom output classes.

**Describe the solution you'd like**
Ideally all indentation is passed on to the `leading_comment` (and other) function, and the user can then normalize indentation on their side, e.g., by using `inspect.cleandoc` in Python or other means.

**Describe alternatives you've considered**
Another alternative might be to convert indentations to special characters (e.g., "@" for each `tab`) in the `proto` file so they are being retained, but that is going to make writing and understanding comments in the `.proto` files cumbersome.

**Comment by shashankram** [comment]
@haberman I am interested in a fix for the same. Did you find a workaround?
