### ISSUE TITLE
Conflicting registered options

### ISSUE THREAD

**Issue by oldergod** [protocolbuffers/protobuf#13833]
Hi

I noticed that the options 1179 and 1180 appear multiple times in docs/options.md.
Both are under Ygot https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md?plain=1#L187-L190 cc @robshakir
1179 is then taken by Cybozu https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md?plain=1#L460-L463 cc @ymmt2005 (お疲れ様です)
1180 by Wire https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md?plain=1#L465-L468  This is us.

Not sure what to do as yet.

**Comment by ymmt2005** [comment]
Hello,
We can change the number, but I'd like to say the `options.md` should have a
table of registered numbers sorted to prevent this from happening again.
