### ISSUE TITLE
Optionally annotate extern symbols with __declspec(dllimport)/__declspec(dllexport) so they are exported from a Windows DLL

### ISSUE THREAD

**Issue by dawidcha** [protocolbuffers/protobuf#13887]
I'm currently working with developers on grpc/grpc to make it possible to build gRPC libraries as shared libraries (DLLs) under Windows. One sticking point is that µpb-generated code can't expose its symbols from a DLL because there is no mechanism for annotating functions with the __declspec(dllexport) and __declspec(dllimport) decorations - which is a requirement for doing so.

It is possible to do that with protoc, for example.

I'd like to propose a change that would facilitate this. So for example we might support command line parameters which nominate macro names that can be declared by the code building the DLL or the code consuming the DLL (or not declared at all for static builds)

So, running (as before):
protoc-gen-upbc < my_proto.proto

...will emit code like:
extern const upb_MiniTable envoy_admin_v3_SimpleMetric_msg_init;

Whereas:
protoc-gen-upbc MY_PROTO_DLL < my_proto.proto

...would instead emit:
extern const MY_PROTO_DLL upb_MiniTable envoy_admin_v3_SimpleMetric_msg_init;

This is similar to what happens with protoc's --cpp_out=dllexport_decl=MY_PROTO_DLL:... 

I can do this work, with your agreement

**Comment by fowles** [comment]
Yeah, this is a thing we would be willing to accept.  Can you work with @veblush on initial design?
