### ISSUE TITLE
Generate libprotoc.lib under uwp triplet

### ISSUE THREAD

**Issue by FrankXie05** [protocolbuffers/protobuf#13913]
**What version of protobuf and what language are you using?**
Version: v3.21.12 
Language: C++

**What operating system (Linux, Windows, ...) and version?**
uwp

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2022

**What did you do?**
1. git clone https://github.com/microsoft/vcpkg.git
2. cd vcpkg/
3. Turn on the option that disables `libprotoc` generation  https://github.com/microsoft/vcpkg/blob/7b5ca09708ae42dba9517d4e0a0c975d087f1061/ports/protobuf/portfile.cmake#L24
5. ./vcpkg install protobuf:x64-uwp
6. See error
```
FAILED: CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/subprocess.cc.obj 
C:\PROGRA~1\MICROS~3\2022\PROFES~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\arm64\cl.exe   /TP -DGOOGLE_PROTOBUF_CMAKE_BUILD -DLIBPROTOC_EXPORTS -DPROTOBUF_USE_DLLS -Dlibprotoc_EXPORTS -IF:\vcpkg\buildtrees\protobuf\arm64-uwp-dbg -IF:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /MDd /Od /RTC1  -MDd /MP /utf-8 /wd4065 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4800 /wd4996 /bigobj /showIncludes /FoCMakeFiles\libprotoc.dir\src\google\protobuf\compiler\subprocess.cc.obj /FdCMakeFiles\libprotoc.dir\ /FS -c F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc
F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc(105): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier
F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc(106): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier
F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc(110): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier
F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc(111): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier
F:\vcpkg\buildtrees\protobuf\src\v3.21.12-fdb7676342.clean\src\google\protobuf\compiler\subprocess.cc(120): error C2065: 'STARTF_USESTDHANDLES': undeclared identifier

```
[install-arm64-uwp-dbg-out.log](https://github.com/protocolbuffers/protobuf/files/12558225/install-arm64-uwp-dbg-out.log)

**What did you expect to see**
Build libprotoc.lib

**Anything else we should know about your project / environment**

Sorry, I didn't find the option for the question, thus opening a bug. 😁

We recently received an issue https://github.com/microsoft/vcpkg/issues/33622, the downstream `grpc` needs `libprotoc.lib`, 
but our `vcpkg` prohibits the generation of `libprotoc` under uwp. 

Andwhen I open this option locally, the above error occurs. 
https://github.com/microsoft/vcpkg/blob/7b5ca09708ae42dba9517d4e0a0c975d087f1061/ports/protobuf/portfile.cmake#L25

Since the modification time is too long, I ask the solution again:

1. Does `protobuf` not support generating `libprotoc` under uwp ?
2. If 1 is no, is there any suggestion for my error? Because it seems that the definition of the function cannot be found.🤔

Thanks,
Frank

**Comment by FrankXie05** [comment]
It seems that the default api does not work in uwp. eg: `STARTF_USESTDHANDLES`  `HANDLE_FLAG_INHERIT`

**Comment by hlopko** [comment]
Did you mean to write 'enables' instead of 'disables' in `Turn on the option that disables libprotoc generation microsoft/vcpkg@7b5ca09/ports/protobuf/portfile.cmake#L24`?

**Comment by FrankXie05** [comment]
> Did you mean to write 'enables' instead of 'disables' in `Turn on the option that disables libprotoc generation microsoft/vcpkg@7b5ca09/ports/protobuf/portfile.cmake#L24`?

In the processing of `uwp` by vcpkg, this macro  `protobuf_BUILD_LIBPROTOC` is  `OFF` by default.

**Comment by FrankXie05** [comment]
We currently disable it.
https://github.com/microsoft/vcpkg/pull/33697

**Comment by mkruskal-google** [comment]
This bit of code is under a win32-specific block in subprocess.cc.  I'm not surprised that uwp is missing some macros we assume exist in win32, but I'm not sure uwp is in our [official support matrix](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md).  That said, this only means we don't test against it and don't guarantee support.  We would accept PRs to fix issues there, and it looks like this one is fairly limited in scope

**Comment by FrankXie05** [comment]
> This bit of code is under a win32-specific block in subprocess.cc. I'm not surprised that uwp is missing some macros we assume exist in win32, but I'm not sure uwp is in our [official support matrix](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md).

Thanks, that's enough to me. :)
