### ISSUE TITLE
Consider dropping support for "generate all in one directory" for C#

### ISSUE THREAD

**Issue by jskeet** [protocolbuffers/protobuf#1394]
Currently if you specify a C#-specific option of "base_namespace" the C# codegen will generate directories relative to that "base" (e.g. with a base namespace of Foo.Bar and a generated class namespace of Foo.Bar.Baz.Qux, we'd create a Baz/Qux directory and put the .cs file in there.) If you don't specify a base namespace at all, we put all the generated files in the directory specified by the --csharp_out option, without creating any directories.

This was raised as a concern by @haberman on #1390. I think we'd have to default to a base-namespace of "", i.e. generate directories assuming the csharp_out directory is a "root".

Pros:
- Avoids the problem where two proto files have the same name, so the latter would just "win"

Cons:
- I suspect this would be surprising behaviour for most C# developers, and it almost never causes an issue in practice. Where it does, it can be fixed by the dev _consuming_ the protos - it doesn't require a change to the proto file itself.

Other options:
- Notice the issue (if all the files are being generated in one go) and warn/error

// cc @jtattermusch, @chrisdunelm

**Comment by gvaish** [comment]
There are 3 general options for folder names:

1. All in `csharp_out` folder. Has risks.
2. In corresponding `csharp_out/{namespace}/{subnamespace}` folders (see [corefx](https://github.com/dotnet/corefx/tree/master/src) [sub-projects](https://github.com/dotnet/corefx/tree/master/src/System.Collections/src) for example) - currently possible using `base_namespace` option
3. In corresponding `csharp_out/{namespace}.{subnamespace}` folders (see [mono](https://github.com/mono/mono/tree/master/mcs/class/System.Web)) for example)

Any thoughts on the 3rd option?

**Comment by jskeet** [comment]
@gvaish: Isn't the third option really separated by assembly/project rather than namespace? That's why each directory has a Makefile. This is basically option 2, but with no subspace because everything in the assembly is in the same namespace.

**Comment by gvaish** [comment]
@jskeet Look at the folders within https://github.com/mono/mono/tree/master/mcs/class/System.Web

* [`mcs/class/System.Web`](https://github.com/mono/mono/tree/master/mcs/class/System.Web) is assembly
* [`mcs/class/System.Web/System.Web.UI.WebControls`](https://github.com/mono/mono/tree/master/mcs/class/System.Web/System.Web.UI.WebControls) is a namespace in the assembly.
* [`mcs/class/System.Web/System.Web.Caching`](https://github.com/mono/mono/tree/master/mcs/class/System.Web/System.Web.Caching) is another namespace in the assembly.

I've lost touch with active C# development lately but I always preferred this option for two reasons:

1. Not too deep folder hierarchy - that created problems on Windows at times (long path).
2. Still allowed grouping related files together (in the namespace).

**Comment by jskeet** [comment]
Ah - I must have stumbled on some subdirectories with makefiles. Sorry about that.

Unless we have evidence of this being more pervasive than just in Mono, I'd rather not support it - it's the first time I've ever seen it, and I don't think it's often going to be useful... I don't see why it's particularly handy to have the directory for System.Web.UI *not* a parent of the directory for System.Web.UI.WebControls, for example.

**Comment by gvaish** [comment]
Not a problem. I just wanted to let you know :)

**Comment by haberman** [comment]
@jskeet @gvaish realistically is this likely to be changed at this point? If not I can just close the issue.

**Comment by jskeet** [comment]
@anandolee is probably the decider here, but I would suggest leaving it as it is at this point to avoid breaking people's builds.

Maybe we should close this but create a new issue to warn/error if multiple protos end up writing out the same file?

**Comment by gvaish** [comment]
@jskeet Is this on the radar?

**Comment by jskeet** [comment]
@gvaish: I very rarely have the time to contribute in this repository any more; @anandolee is the person to ask. But I doubt that anyone has been working on this.

**Comment by elharo** [comment]
not likely to be changed at this point
