### ISSUE TITLE
Documentation for Decoder.py is confusing with respect to the type of 'buffer'

### ISSUE THREAD

**Issue by dixonjoel** [protocolbuffers/protobuf#14037]
**What version of protobuf and what language are you using?**
Version: main/v24.3
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A (Documentation issue)

https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/decoder.py#L15
Says that buffer is a string.

https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/decoder.py#L277
Says that buffer is a memoryview

**Comment by haberman** [comment]
Please feel free to open a new issue if there is a problem with the public APIs.
