### ISSUE TITLE
protobuf_generate command not found when building ns3gym

### ISSUE THREAD

**Issue by sgxcy** [protocolbuffers/protobuf#14081]
I am trying to build ns3gym following the instructions in [https://github.com/tkn-tub/ns3-gym](url). I have installed all the required packages, but I get the error message "-- protobuf_generate command not found -> use a local copy from /home/sgxcy1/ns-3-dev/contrib/opengym/protobuf-generate.cmake". There are additional error messages printed out at the end of the building process, which I think is caused by the aforementioned error. The messages are as follows:

"
CMake Error at scratch/CMakeLists.txt:47 (add_executable):
  Target "scratch_scratch-simulator" links to target "protobuf::libprotobuf"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  scratch/CMakeLists.txt:67 (create_scratch)

CMake Error at scratch/CMakeLists.txt:47 (add_executable):
  Target "scratch_subdir_scratch-simulator-subdir" links to target
  "protobuf::libprotobuf" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  scratch/CMakeLists.txt:97 (create_scratch)
"

In case it matters, I am using Ubuntu 22.04 on Windows Subsystem for Linux. The protoc and cmake versions are as follows:

"
sgxcy1@DESKTOP-R887JOJ:~/ns-3-dev$ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
sgxcy1@DESKTOP-R887JOJ:~/ns-3-dev$ protoc --version
libprotoc 3.12.4
"

I wonder how to solve this problem urgently. I am stuck here for days. Thanks for any reply and potential solutions.

**Comment by sgxcy** [comment]
I forgot to say that the I got the error messages after running "./ns3 build"

**Comment by hlopko** [comment]
I suspect the instructions over at ns3-gym are incorrect, your https://github.com/tkn-tub/ns3-gym/issues/90 is the right place to report this issue.
