### ISSUE TITLE
[MSVC][amd64]Google_Protobuf failed to build with error C2018, error C3646, error C2059, error C2238, error C2182, error C2061, error C2065, error C2988, error C2275, error C2096

### ISSUE THREAD

**Issue by WillaCao** [protocolbuffers/protobuf#14095]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC
**What did you do?**
1. git clone https://github.com/protocolbuffers/protobuf F:\gitP\google\protobuf
2. cd F:\gitP\google\protobuf
3. git fetch --recurse-submodules=no --force
4. git reset --hard 8f1c050
5. git remote prune origin
6. git submodule sync
7. git submodule foreach git reset --hard
8. git submodule foreach git clean -xdf
9. git submodule update --init --recursive
10. cd F:\gitP\google\protobuf\build_amd64
11. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..
12. cd F:\gitP\google\protobuf\build_amd64_Itcg
13. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_EXE_LINKER_FLAGS="/LTCG" -DCMAKE_C_FLAGS="/GL" -DCMAKE_CXX_FLAGS="/GL" ..
14. set _CL_=/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR
15. cd F:\gitP\google\protobuf\build_amd64
16. msbuild /p:Platform=x64 /p:Configuration=Release protobuf.sln /t:Rebuild

**What did you expect to see**
Build pass.
**What did you see instead?**
error C2018: unknown character '0x7f'
error C3646: 'UNREDACTED': unknown override specifier
error C3646: 'NESTED': unknown override specifier
error C3646: 'STRINg': unknown override specifier
error C2059: syntax error: ')'
error C2238: unexpected token(s) preceding ';'
error C2182: 'set_OPTIONAL': this use of 'void' is not valid
error C2182: 'set_allocated_OPTIONAL': this use of 'void' is not valid
error C2061: syntax error: identifier 'UNREDACTED'
error C2065: 'ptr': undeclared identifier
error C2988: unrecognizable template declaration/definition
error C2275: 'std::string': expected an expression instead of a type
error C2096: 'set_allocated_OPTIONAL': A data member cannot be initialized with a parenthesized initializer
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by hlopko** [comment]
Sorry for the slow reply. Could you still reproduce the error at HEAD? We do have windows coverage on the CI and it is green.
