### ISSUE TITLE
Document for google.protobuf.json_format has bad formatting

### ISSUE THREAD

**Issue by hj929** [protocolbuffers/protobuf#14112]
**What version of protobuf and what language are you using?**
Document

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
Visited this link: https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html#

**What did you expect to see**
Expected it is well formatted

**What did you see instead?**
Code and comment are written in 1 line like below.

```
# Create a proto object and serialize it to a json format string. message = my_proto_pb2.MyMessage(foo=’bar’) json_string = json_format.MessageToJson(message)

# Parse a json format string to proto object. message = json_format.Parse(json_string, my_proto_pb2.MyMessage())
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
This document is autogened that we can barely do any change on it
