### ISSUE TITLE
Windows releases for libprotobuf

### ISSUE THREAD

**Issue by em-eight** [protocolbuffers/protobuf#14193]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
It would be very convenient if windows binaries were added in the release for the runtime library.

For now, only the compiler is distributed and I'm not sure what the use case of getting just the compiler is but I think most of the time people also want the runtime libs. At the same time choco seems to only install the compiler while vcpkg only the runtime (and also takes 15 minutes to build)?

I have a cross platform project that depends on protobuf and making a CI pipeline for it is a nightmare and I can't find an example of anyone actually doing it. On windows, it seems that the only way to do it is:
- Build protobuf with vcpkg
- Cache protobuf's binaries so the build time is reasonable
- Download the compiler (while being careful that it matches the version built by vcpkg)
- Manually wire protoc and libprotobuf with cmake or other build system

**Describe the solution you'd like**
A windows release with both protoc and libprotobuf would eliminate all this

**Describe alternatives you've considered**
Open to any I'm not aware of

**Additional context**
-

**Comment by em-eight** [comment]
My mistake  - protoc does come with the vcpkg distribution. I haven't checked that it comes with static libraries and it still a shame that it needs to be built from source and cached, but I'm closing the issue for now

**Comment by yeheshuah** [comment]
@em-eight 
Sorry, could you build the Protobuf runtime library?

**Comment by em-eight** [comment]
> @em-eight Sorry, could you build the Protobuf runtime library?

Yes I am able to build it, but there's no windows release (at least at the time I wrote this issue). Which is annoying for downstream projects using it, because there is no good support on any Windows package manager
