### ISSUE TITLE
This library failed at the very first step of the instruction

### ISSUE THREAD

**Issue by jerryyanmj** [protocolbuffers/protobuf#142]
I failed to install this.

./autogen.sh 
Google Test not present.  Fetching gtest-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1136k  100 1136k    0     0   614k      0  0:00:01  0:00:01 --:--:--  614k
- sed -i -e 's/RuntimeLibrary="5"/RuntimeLibrary="3"/g;
         s/RuntimeLibrary="4"/RuntimeLibrary="2"/g;' gtest/msvc/gtest-md.vcproj gtest/msvc/gtest.vcproj gtest/msvc/gtest_main-md.vcproj gtest/msvc/gtest_main.vcproj gtest/msvc/gtest_prod_test-md.vcproj gtest/msvc/gtest_prod_test.vcproj gtest/msvc/gtest_unittest-md.vcproj gtest/msvc/gtest_unittest.vcproj
- autoreconf -f -i -Wall,no-obsolete
  ./autogen.sh: line 40: autoreconf: command not found

**Comment by RahulSDeshpande** [comment]
@xfxyjwf !!

You saved my day :dancer: 
Thanks a lot !! :+1:

**Comment by milinddeore** [comment]
You will find all dependences [here](https://github.com/google/protobuf/blob/master/src/README.md).
