### ISSUE TITLE
AIP-161-compliant field masks are rejected by FieldMaskUtil.isValid

### ISSUE THREAD

**Issue by iot2198** [protocolbuffers/protobuf#14239]
I am using filed mask on the same proto structure as mentioned in https://google.aip.dev/161. I am doing this in kotlin. The dependencies being used are :
- com.google.protobuf:protobuf-java:3.23.2
- com.google.protobuf:protobuf-java-util:3.23.2
- com.google.protobuf:protobuf-kotlin:3.23.2
- io.grpc:grpc-protobuf:3.23.2

The issue i face is that when validating if it is a correct field mask for the example given in 161 it always gives false:
  require(FieldMaskUtil.isValid(Book::class.java, request.mask)) { "Invalid Field mask" }
  values i have tried are: "book.reviews.smith", "reviews.smith", "reviews.`smith`", "reviews.*.smith" etc
  i have tried all possible combinations.
  Can you guide me is this supported in protobuf current version and am i missing anything ?

**Comment by iot2198** [comment]
@jskeet

**Comment by jskeet** [comment]
I'm travelling at the moment, but will answer properly next week. The TL;Dr is - yup, the protobuf libraries and AIP-161 are unfortunately in conflict at the moment. I have a longstanding task to try to at least document and ideally improve this, but it's not likely to be soon. More detail next week.

**Comment by jskeet** [comment]
Right, now I'm back...

Basically there are *multiple* discrepancies between how field masks are described in [fieldmask.proto](src/google/protobuf/field_mask.proto) and how they're described in AIP-161.

#12524 describes how some field masks described in AIP-161 don't have a valid JSON representation. In addition, there are various utility classes in protobuf runtimes which either prohibit the additional features of AIP-161 entirely, or implement them partially and inconsistently. `FieldMaskUtil.isValid` is just part of this.

This has been on my plate for a while, in terms of trying to improve things as much as I can *without breaking anything* - that last part being absolutely the most important. (There will always be *some* risk to changes, even safe-sounding ones like expanding JSON serialization/deserialization, but it'll be a trade-off.) As a sort of "side-project" it's frankly hard to find time for this - but I'm *trying* to do so.
