### ISSUE TITLE
upb-generator to emit code that can be used in a Windows shared library (DLL)

### ISSUE THREAD

**Issue by dawidcha** [protocolbuffers/protobuf#14255]
**What language does this apply to?**
upb generated code

**Describe the problem you are trying to solve.**
Make upb-generated symbols accessible when compiled into Windows shared libraries (i.e. DLLs)

**Describe the solution you'd like**
Add a parameter to protoc-gen-upb and protoc-gen-upbdefs which causes the necessary annotations to be added

**Describe alternatives you've considered**
I can export all symbols by including a def file with an EXPORTS section, but there is no way since the IMPORTS section was deprecated for clients to consume those symbols

**Additional context**
This is part of an ongoing effort to compile the gRPC libraries as a DLL.
I have added a PR with what I believe are the necessary code changes [here](https://github.com/protocolbuffers/protobuf/pull/14230)

**Comment by haberman** [comment]
I'm unassigning myself from this issue because I'm not working on it myself. But https://github.com/protocolbuffers/protobuf/pull/14981 will fix this issue if/when it is submitted.
