### ISSUE TITLE
C#:  preserve directory structure in generated code

### ISSUE THREAD

**Issue by rofrankel** [protocolbuffers/protobuf#14282]
**What language does this apply to?**

C#

**Describe the problem you are trying to solve.**

We have a tool that generates a package with a potentially large number of .proto files with a specific directory structure.  The file _paths_ are of course unique, but file _names_ are based on user input and aren't guaranteed to be unique.  When there's a collision, this means that generating C# code fails, because the C# code generator generates a flat directory of `.cs` files with filenames matching the input filenames.

This problem does not exist in C++, Go (with `paths=source_relative`), or Swift; these all preserve the directory structure.  It also doesn't existing with Java/Kotlin, where the output is in a flat directory but the filenames are based on message names or the `java_outer_classname` option.

**Describe the solution you'd like**

A protoc plugin option to generate code with a directory structure matching that of the input.  This is the same behavior exhibited by C++, Swift, and (with `paths=source_relative`) Go.

**Describe alternatives you've considered**

* Modifying the generator to guarantee unique filenames (but this uglifies our output)
* Forking the C# protoc plugin

**Comment by jskeet** [comment]
While there isn't an option to preserve the directory structure of the *source* protos, there's an option to create a directory structure based on *namespace*. Specify the `base_namespace` option (which can be empty):

```sh
protoc --csharp_out=. --csharp_opt=base_namespace= p1/test.proto p2/test.proto
```

The files will then be generated base on the C# namespace for each file (based on the proto package or the `csharp_namespace` option in the file). Hopefully that matches the structure of the files anyway - and is more in-keeping with typical C# practices for source control.

If you specify a non-empty base namespace, then that prefix is effectively removed - so if you generated code in a C# namespace of "A.B.C.D" and specified `base_namespace` as `A.B` then it would create a file under a directory of `C/D`.

Does that solve your problem? I'd personally rather not add a completely separate option for folder structure to the generator.

**Comment by rofrankel** [comment]
I tried that option, and it doesn't (in isolation) solve my problem.  Let's assume I generate a directory structure like (forced toy example):

* resources/
  * check.proto
  * receipt.proto
* custom_methods/
  * receipt/
    * check_receipt.proto

(Whether that last file is `check_receipt.proto` or `check.proto`, I have a filename collision.)

I _could_ generate different C# namespaces for these files, e.g. `resources/receipt.proto` and `custom_methods/receipt/check_receipt.proto` are both about the `Receipt` resource and so could have a `My.Api.V1.Receipt` namespace.  This comes at a (small, admittedly) developer experience cost for the API implementor, and it also adds a bit of complexity to the generator (right now it doesn't specify `csharp_namespace` at all).

I recognize that changing the C# protoc plugin is a heavier lift that my changing our API contract generator.  But I thought it was worth asking, given that this isn't an issue with any of the several other languages I checked, and given that someone else could easily run into this problem as well.  Having unique filenames seems like an idiosyncratic requirement.

**Comment by jskeet** [comment]
I may be missing something, but I'd expect your toy example to work, generating Check.cs, Receipt.cs and CheckReceipt.cs.

One thing that's really important to note is that the reflection class within the file (CheckReflection etc) is based on the filename as well... so even if we *did* generate source files in the same directory structure, they still wouldn't be able to be compiled together afterwards. Are you expecting to be able to compile all the generated code together in one assembly? If so, the fully-qualified name really will need to be unique.

Also note that you don't have to specify csharp_namespace in particular - the namespace is derived from the protobuf package if you don't specify the csharp_namespace option. I don't think forcing "package + filename" to be a unique combination is particularly strange, personally.

**Comment by rofrankel** [comment]
Hmm, yes, I somehow confused myself while (re)writing that example and messed it up.  There should have been a third file called resources/check_receipt.proto...but of course that's a less realistic resource name, which undermines the example a bit. :/  I can try to think of a more realistic example if that would help.  (Right now I haven't run into a real one, just noticed that a filename collision is possible.  This came up because the current version of our generator actually uses `custom_methods/receipt/check.proto`, which _does_ cause a collision today, because we have two different resources with a custom method named `:increment`.  Changing to e.g. custom_methods/receipt/check_receipt.proto addresses the kind of collision we had, but while I'm at it I'd want to make all filename collisions impossible, if that's what we need to do.)

> I don't think forcing "package + filename" to be a unique combination is particularly strange, personally.

It seems to be a uniquely C# requirement when it comes to protobuf, and it is a stricter constraint than filesystems impose (which is of course that file _paths_ must be unique, but not file _names_).

Anyway, it all seems irrelevant given your point about generated reflection classes, since changing how that works seems infeasible.  Thanks for the info and the quick responses!
