### ISSUE TITLE
Migrate to Bzlmod for managing external dependencies

### ISSUE THREAD

**Issue by meteorcloudy** [protocolbuffers/protobuf#14313]
With future Bazel LTS versions, Bzlmod will become the default system for external dependencies management.

Please consider migrating all your external dependencies in WORKSPACE to MODULE.bazel

For more information, please check https://github.com/bazelbuild/bazel/issues/18958

Related issue is https://github.com/protocolbuffers/protobuf/issues/13618, but #13618 is more about providing a Bazel modules for users, this one is for tracking the migration of protobuf itself to use Bzlmod for managing both prod and dev external deps.

**Comment by meteorcloudy** [comment]
ping, to keep it active

**Comment by aaliddell** [comment]
.

**Comment by ianb-pomelo** [comment]
.

**Comment by touchinglie** [comment]
I'm installing the ProtoBuf lib on my Radxa Rock 3A Debian Bullseye to compile the source code for NCNN.
When I executed the command, 

`bazel build :protoc :protobuf`

it raise an error:

`INFO: Reading rc options for 'build' from /home/radxa/protobuf-28.1/.bazelrc:
  Inherited 'common' options: --noenable_bzlmod --repo_env=BAZEL_NO_APPLE_CPP_TOOLCHAIN=1
ERROR: --noenable_bzlmod :: Unrecognized option: --noenable_bzlmod`

Any Idea or help pls.

**Comment by ianb-pomelo** [comment]
This is still active and will help downstream migration to BZLMOD

**Comment by zhangskz** [comment]
Should be able to close this with the addition of MODULE.bazel since ~v27.x. See https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/protobuf.

Please reopen (or file a new issue) for any dependencies missing in bzlmod.

**Comment by Mizux** [comment]
Protobuf still use workspace as default, please edit the issue description to "Add support to bzlmod" OR reopen this issue until Protobuf default to bzlmod...

src: https://github.com/protocolbuffers/protobuf/blob/233098326bc268fc03b28725c941519fc77703e6/.bazelrc#L31-L33

PS: Could be also good to label properly this issue and also use "milestone" with a version ? (so downstream google project like google/or-tools or pybind/pybind11_protobuf can easily track and follow your roadmap...)
