### ISSUE TITLE
[Windows] TypeError: Couldn't build proto file into descriptor pool: duplicate file name

### ISSUE THREAD

**Issue by XuanWang-Amos** [protocolbuffers/protobuf#14345]
**What version of protobuf and what language are you using?**
Version: protobuf==4.24.3 and protobuf==4.24.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 

We're still experiencing duplicate file name issue (https://github.com/protocolbuffers/protobuf/issues/10158) in windows using latest version of protobuf.

Has the fix been included in Windows wheels yet?

**Comment by matteius** [comment]
Just encountered this issue in windows trying to get the object_detection examples of tensorflow to build.

**Comment by matteius** [comment]
Actually figured out this morning that I was building it in powershell and trying to use it in git bash which was incompatible, once I built it in git bash (where I was using it) I got past that error.

**Comment by haberman** [comment]
If you encounter the error again, please open a new issue.

**Comment by alexandco78** [comment]
The bug hasn't been fixed, I have the same issue with google.duration type when I try to use protos_and_services()
