### ISSUE TITLE
PHP Fatal error:  Unable to load descriptor: type mismatch when resolving 

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#14376]
We are receiving the following error in PHP 7.4 when the protobuf c-extension is enabled: 

```
PHP Fatal error:  Unable to load descriptor: type mismatch when resolving google.shopping.merchant.reports.v1beta.ProductPerformanceView.destination: couldn't find name .g
 in /home/runner/work/google-cloud-php/google-cloud-php/ShoppingMerchantReports/metadata/V1Beta/Reports.php on line 465
```

See our failing job at https://github.com/googleapis/google-cloud-php/actions/runs/6499416650/job/17652727560?pr=6705#step:8:323

Does this have to do with the fact that the C-extension no longer supports 7.4, and the protos in question are implementing something not supported in the previous version?

[Here is the proto in question](https://github.com/googleapis/googleapis/blob/master/google/shopping/merchant/reports/v1beta/reports.proto), which doesn't seem to have changed significantly, so I'm stumped.

This works in other versions of PHP which use the `protobuf` native PHP library. I have not tested this using PHP 8.0 and the protobuf C-extension, but I will.

**Comment by bshaffer** [comment]
I believe this is because in the PR, an enum changed to a message. It could be that this is such unexpected behavior that it resulted in this strange (and difficult to understand) error message.

If it's a simple fix, we could try to make the error message better (as the one we have now is very odd).

**Comment by haberman** [comment]
I think the root cause is that the error message got truncated. Right now we truncate error messages at 127 bytes. We should probably at least double this, maybe x4 would be safer: http://google3/third_party/upb/upb/base/status.h;l=16;rcl=602850921
