### ISSUE TITLE
protoc-gen-pyi: program not found or is not executable

### ISSUE THREAD

**Issue by vcozzolino** [protocolbuffers/protobuf#14372]
Problem: Unable to generate the .pyi files using `protoc`.

OS: Ubuntu 20.04
Python version: Python 3.8.10
gRPC/protobuf versions as shown by `pip list`:
```
grpcio                   1.54.2
grpcio-testing           1.54.2
grpcio-tools             1.14.1
grpclib                  0.4.6
googleapis-common-protos 1.60.0
protobuf                 4.23.2
```
Installed packages as shown by `apt search protobuf-compiler`:
```
protobuf-compiler/focal-updates,focal-security,now 3.6.1.3-2ubuntu5.2 amd64 [installed]
  compiler for protocol buffer definition files

python-protobuf/focal-updates,focal-security,now 3.6.1.3-2ubuntu5.2 amd64 [installed]
  Python bindings for protocol buffers

python3-protobuf/focal-updates,focal-security,now 3.6.1.3-2ubuntu5.2 amd64 [installed]
  Python 3 bindings for protocol buffers
```

This is what happens when I run the following command to generate the .py and .pyi bindings:
```
python3 -m grpc_tools.protoc -I=../protos --python_out=pyi_out:../libraries/gen --pyi_out=../libraries/gen ../protos/robosvc/FollowService.proto --grpc_python_out=../libraries/gen
```

Output:
```
protoc-gen-pyi: program not found or is not executable
--pyi_out: protoc-gen-pyi: Plugin failed with status code 1.
```

I have exactly the same libs installed under Windows, and there it works. How is that possible?

**Comment by codebykyle** [comment]
I also am receiving this in a GitHub action. On my local computer, my script runs fine. I will let you know if I've found anything.

**Comment by vcozzolino** [comment]
I found out the issue in the end: the underlying libgrpc installed by the package manager was outdated. After installing manually the latest one, everything worked fine.

**Comment by vcozzolino** [comment]
Closing

**Comment by jizezhang** [comment]
Hello, I am facing the same issue. May I ask how you manually installed libgrpc? Thanks.

**Comment by yeqown** [comment]
> Hello, I am facing the same issue. May I ask how you manually installed libgrpc? Thanks.

I resolved by upgrade `grpcio-tools`:
```bash
pip install grpcio-tools --upgrade
```

**Comment by simawn** [comment]
I had the same issue: it worked on my machine but didn't on the pipelines. Turns out the pipelines was using protoc v3 but my local one is protoc v25. protoc in Ubuntu repository is outdated: https://github.com/protocolbuffers/protobuf/issues/15521#issuecomment-1950239889

I ended up adding an extra step in my pipeline to use the binary directly from https://github.com/protocolbuffers/protobuf/releases
Don't forget to copy the contents of the `/include` folder into `/usr/local/include/`

**Comment by zzr93** [comment]
> > Hello, I am facing the same issue. May I ask how you manually installed libgrpc? Thanks.
> 
> I resolved by upgrade `grpcio-tools`:
> 
> ```shell
> pip install grpcio-tools --upgrade
> ```

This solved my issue, thx!
