### ISSUE TITLE
ERROR: no such package '@com_google_protobuf//' with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [protocolbuffers/protobuf#14383]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3379#018b2723-e292-48fc-8571-d7d09097bced

Platform : Windows, MacOs, Ubuntu

Logs:
```
ERROR: no such package '@com_google_protobuf//': The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined
(03:55:15) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a270cf9078705688cac67ea00d82328b/external/bazel_tools/tools/proto/BUILD:10:6: no such package '@com_google_protobuf//': The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined and referenced by '@bazel_tools//tools/proto:protoc'
(03:55:15) ERROR: Analysis of target '//java/core:conformance_test' failed; build aborted: Analysis failed
(03:55:15) INFO: Elapsed time: 1.367s, Critical Path: 0.03s
(03:55:15) INFO: 1 process: 1 internal.
(03:55:15) ERROR: Build did NOT complete successfully
(03:55:15) ERROR: No test targets were found, yet testing was requested
(03:55:15) FAILED:
```

Steps:
```
git clone -v https://github.com/google/protobuf.git
git reset 42fe8b9927911cc81bf9a47c680c34b4413ee179 --hard
export USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b
bazel test  --proto_toolchain_for_cc=//:cc_toolchain //:all //java/...

```

cc Greenteam @mai93

**Comment by mai93** [comment]
@Wyverald can this be related to https://github.com/bazelbuild/bazel/commit/9be1be93ff17dbb4cf0effb4f885911ec99cc30c?

**Comment by sgowroji** [comment]
@meteorcloudy

**Comment by comius** [comment]
cc @thesayyn and @alexeagle, I don't think this is connected to recent protobuf_repo removal, but also there was no investigation yet.

**Comment by acozzette** [comment]
I was able to reproduce it like this and narrow it down at least a little bit:
```
USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b bazelisk build @bazel_tools//tools/proto:protoc
```

**Comment by comius** [comment]
@acozzette you're saying this exact commit in bazel makes it fail?

**Comment by acozzette** [comment]
No, that was just a simple way to reproduce it. I'm running a bisect right now that will hopefully find the exact commit, though.

**Comment by acozzette** [comment]
The bisect pointed to this as the first Bazel commit that makes this fail: https://github.com/bazelbuild/bazel/commit/9be1be93ff17dbb4cf0effb4f885911ec99cc30c

**Comment by comius** [comment]
Cc @Wyverald

**Comment by sgowroji** [comment]
Moved this issue here https://github.com/bazelbuild/bazel/issues/19973
