### ISSUE TITLE
Request for freebsd-x86_64.exe  in maven repo

### ISSUE THREAD

**Issue by hweelim** [protocolbuffers/protobuf#14402]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?
We are using Java and proto3 proto syntax

**Describe the problem you are trying to solve.**
Server is running FreeBSD, will have pom.xml to pull protoc on the fly and compile .proto file. We found that Maven repo is lacking the protoc file for freebsd.

**Describe the solution you'd like**
Please publish .exe for freebsd on Maven repo for 3.16.3 and above

**Describe alternatives you've considered**
Please provide instructions on how we can generate the exe and host the file on our own repo.

**Additional context**

**Comment by hlopko** [comment]
Is it an option for you to build protoc on freebsd from scratch, or use the binary package on freebsd (`pkg install protobuf`)?

**Comment by yjqg6666** [comment]
Any update for this?

**Comment by deannagarcia** [comment]
Unfortunately I don't believe we are able to prioritize this issue right now.

We believe there is a workaround to build protoc from scratch or use the binary package on freebsd. Please respond with more context if this workaround isn't working.
