### ISSUE TITLE
oneof fields when creating c# class

### ISSUE THREAD

**Issue by grigoras** [protocolbuffers/protobuf#14410]
**What version of protobuf and what language are you using?**
Version: Protocol Buffers v24.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc version

**What did you do?**
1. Create a simple proto contract with oneOf fields:

```
syntax = "proto3";

// The options 'java_package' and 'java_outer_classname' may be changed.
// Version 3
option java_package = "de.suu.proto";
option java_outer_classname = "UploadVxProtoMEB";
option csharp_namespace = "CCG.SUU.ProtobufV3";

// COMMUNICATION CONTROL BETWEEN VEHICLE AND BACKEND
message Response {
 string id = 1; // Timestamp when it was created
 // The message payload
 oneof data {
  Class1 class1 = 2;
  Class2 class2=3;
  Class3 clas3=4;
 }
}

message Class1{ 
 double number=1; 
 string name=2;
}

message Class2{ 
 double number=1; //micro degrees to degrees (*10^-6)
 string type=2;
}

message Class3{ 
 double number=1;
 string description=2;
}
```

2. Generate a c# class

`./protoc.exe ./myProto.proto --csharp_out=./`

3. The new generated will have the properties with getter and setter inside:

```
/// <summary>Field number for the "class1" field.</summary>
    public const int Class1FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CCG.SUU.ProtobufV3.Class1 Class1 {
      get { return dataCase_ == DataOneofCase.Class1 ? (global::CCG.SUU.ProtobufV3.Class1) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Class1;
      }
    }
```

4. The problem is that data_ (the object that contains one of the fields) will be overwritten by the latest field from the oneof block, because the setter does not check if the data_ is already set, or not. so if only Class1 have value, we will end up with null value for it because the last one who enters the setter, Class3, will set data_ to null.

if we receive something like:
{
...
    "class1": {
    ...
    }
    "class2": null,
    "class3": null,
...
}

**What did you expect to see**

```
/// <summary>Field number for the "class1" field.</summary>
    public const int Class1FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CCG.SUU.ProtobufV3.Class1 Class1 {
      get { return dataCase_ == DataOneofCase.Class1 ? (global::CCG.SUU.ProtobufV3.Class1) data_ : null; }
      set {
        data_ = value == null ? data_ : value;
        dataCase_ = value == null ? dataCase_ : DataOneofCase.Class1;
      }
    }
```

I would expect to check if the value is null, and if so, just let the value that was already set in the oneof fields. Also dataCase_ should maintain the value.

**What did you see instead?**

As I wrote above

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

I've inserted the .proto file in the step 1.

**Anything else we should know about your project / environment**

**Comment by jskeet** [comment]
This is how oneof fields have worked in all languages that I'm aware of.
I don't believe we'd want to make any change for just C#.

Indeed, it's described in the [documentation](https://protobuf.dev/programming-guides/proto3/#oneof-features):

> Setting a oneof field will automatically clear all other members of the oneof. So if you set several oneof fields, only the last field you set will still have a value.

As such, this is working as intended - if you want to propose a completely different model for oneofs, that wouldn't be done just for C#.

**Comment by esrauchg** [comment]
Yes: the behavior listed is deliberate. Besides the quote jskeet wrote see also the sentence further above in the same documentation:

> Note that if multiple values are set, the last set value as determined by the order in the proto will overwrite all previous ones.

Especially in the explicit setters api, if we had the 'first write sticks' it would likely be even more confusing because it would mean silently discarding the second write.

Apologies for any confusion on this case!
