### ISSUE TITLE
Getting issue on Mac M2 Chip Android Studio

### ISSUE THREAD

**Issue by Kishan10008** [protocolbuffers/protobuf#14482]
> Task :core:generateDebugProto FAILED
Execution failed for task ':core:generateDebugProto'.
> java.io.IOException: Cannot run program "/Users/admin/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.17.3/53db7dd118d8dfc87d48f8a31a816bcdee6f0f5d/protoc-3.17.3-osx-aarch_64.exe": error=86, Bad CPU type in executable

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

Issue -: Cause: error=86, Bad CPU type in executable

**Comment by hlopko** [comment]
Please fill in all the information in the issue template, we cannot help with the context you provided.
