### ISSUE TITLE
Regarding compilation error of gRPC

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [protocolbuffers/protobuf#14504]
I am using gRPC v1.49.2 and envoy 1.26.4 version
language: C++
operating system: Linux f52fb5b18ecf 4.18.0-372.26.1.2210101416.el7_9.emrs.ulnx.x86_64 https://github.com/protocolbuffers/protobuf/pull/1 SMP Sun Oct 16 20:33:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
runtime / compiler: gcc c++11 compiler

envoy dependency link:
https://www.envoyproxy.io/docs/envoy/v1.26.4/intro/arch_overview/security/external_deps#external-dependencies-build

We make libenvoy.so that include below dependencies 
gRPC v1.49.2
protobuff which comes with gRPC v1.49.2 under third_party folder
xds which comes with gRPC v1.49.2 under third_party folder
opencensus-proto which comes with gRPC v1.49.2 under third_party folder
opentelemetry-proto which comes with gRPC v1.49.2 under third_party folder
googleapis which comes with gRPC v1.49.2 under third_party folder
protoc-gen-validate v0.10.1 which is mentioned in envoy dependency link
 
With the above combination, we are trying to make libenvoyapi.so but we are getting compilation error. I have attached the compile.txt which consist of compilation error. Please help me in resolving the compilation error.
[compile.txt](https://github.com/protocolbuffers/protobuf/files/13070286/compile.txt)

**Comment by hlopko** [comment]
Please report this issue over at envoy repository, the errors you're getting are not protobuf specific, they suggest a problem in the overall build configuration. Either the instructions are not complete, or there is a problem in your system/checkout.

**Comment by Gaurav0411GitHub** [comment]
Hi,
As these are googleApis error, Can you please suggest how can i resolve this kind of error?
