### ISSUE TITLE
Cannot install 3.25.0.rc.2 on Ruby 3.3.0-preview2

### ISSUE THREAD

**Issue by marcotc** [protocolbuffers/protobuf#14509]
**What version of protobuf and what language are you using?**
Version: 3.25.0.rc.2
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Docker [ruby:3.3.0-preview2](https://hub.docker.com/layers/library/ruby/3.3.0-preview2/images/sha256-399438a546c8f768c95da4c6adc0c50c285a9c402beb3f8be18e877399d25295?context=explore): `Linux 387032e9f908 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 GNU/Linux`

**What runtime / compiler are you using (e.g., python version or gcc version)**

ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) [x86_64-linux]
gcc version 12.2.0 (Debian 12.2.0-14)

**What did you do?**
1. Execute `docker run --rm -it ruby:3.3.0-preview2 gem install google-protobuf -v 3.25.0.rc.2`
1. See error: `LoadError: cannot load such file -- ffi-compiler/compile_task`

**What did you expect to see**

Gem installed successfully.

**What did you see instead?**

```
Fetching google-protobuf-3.25.0.rc.2.gem
Building native extensions. This could take a while...
ERROR:  Error installing google-protobuf:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/google-protobuf-3.25.0.rc.2/ext/google/protobuf_c
/usr/local/bin/ruby -rrubygems /usr/local/lib/ruby/gems/3.3.0+0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/usr/local/bundle/extensions/x86_64-linux/3.3.0+0/google-protobuf-3.25.0.rc.2 RUBYLIBDIR\=/usr/local/bundle/extensions/x86_64-linux/3.3.0+0/google-protobuf-3.25.0.rc.2
rake aborted!
LoadError: cannot load such file -- ffi-compiler/compile_task
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:128:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:128:in `require'
/usr/local/bundle/gems/google-protobuf-3.25.0.rc.2/lib/google/tasks/ffi.rake:1:in `<top (required)>'
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/google-protobuf-3.25.0.rc.2 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/3.3.0+0/google-protobuf-3.25.0.rc.2/gem_make.out
```

**Anything else we should know about your project / environment**

**Comment by JasonLunn** [comment]
How are protobuf dependencies installed in this environment? The [gemspec](https://github.com/protocolbuffers/protobuf/blob/main/ruby/google-protobuf.gemspec#L37) lists the https://github.com/ffi/ffi-compiler as a development dependency. Installing that gem first explicitly should fix the immediate problem as a workaround, but there is more than one development dependency.

**Comment by JasonLunn** [comment]
`bundle install` installs the development dependencies automatically, but `gem install` doesn't. The #14538 adds a safety check so that users can `gem install` without having `ffi-compiler` if they don't need access to the new FFI-based implementation.
