### ISSUE TITLE
Add NET8 support

### ISSUE THREAD

**Issue by patrick-dmxc** [protocolbuffers/protobuf#14523]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
Hi, there is a Preview awailable for NET8 and so i wold migrate soon to NET8 but as long Protubuf is not capable of NET8 i cant migrate

**Describe the solution you'd like**
Compile as NET8 and publish on nuget

**Describe alternatives you've considered**
none

**Additional context**

**Comment by jskeet** [comment]
Any library targeting .NET 6 (or earlier, or .NET Standard) can already be used from .NET 8. What makes you think it can't? If you're having a specific problem, please provide a minimal repro and details of the error you're receiving.

**Comment by patrick-dmxc** [comment]
Currently the Package is only Targeting Net 5 or Net Standart2.0.
When i use Protobuff in my Net8.0 Applikation, the Compolet Target the the Protobuff-Library to Net Standart 2.0.
In the Dev-Environment this works.
But if i whant to Publish my application as Self-contained Single file or Ready to Run EXE, Net-Standart is to old and this leeds to an non-functional Compiled EXE.

Allso .NET 6 LTS is gone reach end of LTS

**Comment by jskeet** [comment]
No, .NET 6 is still supported unt November 2024.

If you're having problems with a specific publication model, you should give details of that rather than making a blanket statement that protobuf doesn't work with .NET 8. It's unlikely that *just* targeting .NET 7 would fix that, but until we have details of what's not working we can't really test.

**Comment by patrick-dmxc** [comment]
What ar whe talking abaut,
Currently Protobuf is not Targeted to Net6.0 at all
And nobody is hurt if this is addes

**Comment by jskeet** [comment]
> And nobody is hurt if this is addes

It makes the package larger for everyone, and adds additional testing requirements. I'm not going to add a target just for the sake of it, without any evidence that it actually addresses any problems. Please put more details about the actual problem you're facing and we can look into it (although time is limited right now, so it may take a while before we can get to it).

**Comment by EnemyArea** [comment]
This should be updated because its using an deprecated .net version. .net 5 is not longer supported: https://www.nuget.org/packages/Microsoft.NETCore.Targets/ and this goes for some of the dependencies.

**Comment by jskeet** [comment]
@EnemyArea: It's not "using" a deprecated version - it's *supporting* a deprecated version. We do have plans to update the targets at some point, but I don't regard it as hugely urgent.

At some point we'll probably want to target .NET 8 specifically for AOT reasons - but that's a slightly different project.

**Comment by patrick-dmxc** [comment]
We still want it

**Comment by jskeet** [comment]
@patrick-dmxc: As I noted before:

> Please put more details about the actual problem you're facing and we can look into it

I have vague memories that this was actually about supporting AOT, but I *definitely* don't have time to go back and forth for ages trying to get a concrete, specific set of requirements. *If* we have those I *might* have time to do the work to get it AOT-compatible (which will be non-trivial) but I'm definitely not going to put effort in without more concrete requirements. The package works with .NET 8 when using it in the same way as other targets.
