### ISSUE TITLE
Build fails on RISCV 

### ISSUE THREAD

**Issue by apcameron** [protocolbuffers/protobuf#14549]
The Build using the latest github version fails to build on RISCV with /usr/lib/gcc/riscv64-unknown-linux-gnu/12/../../../../riscv64-unknown-linux-gnu/bin/ld: third_party/abseil-cpp/absl/log/libabsl_log_internal_globals.a(globals.cc.o): in function `.L0 ':
globals.cc:(.text._ZNSt6atomicIbE8exchangeEbSt12memory_order[_ZNSt6atomicIbE8exchangeEbSt12memory_order]+0x44): undefined reference to `__atomic_exchange_1'
[screenlog.txt](https://github.com/protocolbuffers/protobuf/files/13192775/screenlog.txt)

**Comment by davids91** [comment]
here's the demangled missing symbol, should it help anyone: `std::atomic<bool>::exchange(bool, std::memory_order)[std::atomic<bool>::exchange(bool, std::memory_order)]`

**Comment by hlopko** [comment]
This seems like a problem in [abseil](https://github.com/abseil/abseil-cpp) (which protobuf depends on). Could you please file this issue over there? Thank you!

**Comment by apcameron** [comment]
Please REOPEN this as the problem is with your CMAKE file
The following DIFF gets it to compile clean on RISCV
<pre><b>diff --git a/CMakeLists.txt b/CMakeLists.txt</b>
<b>index f78fccc27..51e866bc1 100644</b>
<b>--- a/CMakeLists.txt</b>
<b>+++ b/CMakeLists.txt</b>
<font color="#2AA1B3">@@ -191,7 +191,8 @@</font> if (NOT MSVC)
       return static_cast&lt;int&gt;(std::atomic&lt;int64_t&gt;{});
     }
   &quot; protobuf_HAVE_BUILTIN_ATOMICS)
<font color="#C01C28">-  if (NOT protobuf_HAVE_BUILTIN_ATOMICS)</font>
<font color="#26A269">+  if (NOT protobuf_HAVE_BUILTIN_ATOMICS OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES</font>
<font color="#26A269">+</font>       <font color="#26A269">  &quot;riscv&quot;)</font><span style="background-color:#C01C28"> </span>
     set(protobuf_LINK_LIBATOMIC true)
   endif (NOT protobuf_HAVE_BUILTIN_ATOMICS)
   set(CMAKE_REQUIRED_FLAGS ${OLD_CMAKE_REQUIRED_FLAGS})
</pre>

**Comment by Boring545** [comment]
> 请重新打开此文件，因为问题出在您的 CMAKE 文件上 以下 DIFF 让它在 RISCV 上编译干净
> 
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index f78fccc27..51e866bc1 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -191,7 +191,8 @@ if (NOT MSVC)
>        return static_cast<int>(std::atomic<int64_t>{});
>      }
>    " protobuf_HAVE_BUILTIN_ATOMICS)
> -  if (NOT protobuf_HAVE_BUILTIN_ATOMICS)
> +  if (NOT protobuf_HAVE_BUILTIN_ATOMICS OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES
> +         "riscv") 
>      set(protobuf_LINK_LIBATOMIC true)
>    endif (NOT protobuf_HAVE_BUILTIN_ATOMICS)
>    set(CMAKE_REQUIRED_FLAGS ${OLD_CMAKE_REQUIRED_FLAGS})

I successfully solved the problem using the method.

**Comment by Boring545** [comment]
I successfully solved the problem using the method. Thank you, apcameron
