### ISSUE TITLE
[bazel] Automate publishing releases to Bazel's central registry

### ISSUE THREAD

**Issue by alexeagle** [protocolbuffers/protobuf#14564]
Currently https://github.com/protocolbuffers/protobuf/releases has many releases beyond what currently appears on https://registry.bazel.build/modules/protobuf, which is currently 10mo old.

We could attempt to keep this updated manually, but like many processes that live in OSS, it will be easy for Googler maintainers to miss this.

Fortunately the Bazel community already created a GitHub app, https://github.com/bazel-contrib/publish-to-bcr/ . With a bit of configuration in this repo, and after "installing" that app to the repo, then every release will be automatically published as a pull request to https://github.com/bazelbuild/bazel-central-registry/pulls

I'm happy to take on this work, just filing the issue first to have a place for discussion. Note that we may need a couple of extra releases when we "launch" in case of mistakes in the automation which are hard to test ahead of time.
FYI @comius @thesayyn

**Comment by malt3** [comment]
Still relevant

**Comment by erikkerber** [comment]
Just hit us (lightly) as well—hoping to pull in a fix for a build warning but BCR is still in 23.1 (current release 25.2)

**Comment by david-crouse** [comment]
Relevant to pybind11_protobuf, we could use latest version in BCR as well.

**Comment by wffurr** [comment]
Why is this closed?  The latest version in the Bazel Central Registry is still 23.1.  bzlmod support is only part of the answer, the rest is publishing to BCR.

**Comment by alexeagle** [comment]
This work is complete, actually. It was a few hours too late to make the last protobuf release, but the next one should include a current MODULE.bazel file and an automation for creating the BCR entry.

**Comment by wffurr** [comment]
Fantastic news - thank you!
