### ISSUE TITLE
Protobuf only supports Abseil version 20230125.3 and newer

### ISSUE THREAD

**Issue by dingjingmaster** [protocolbuffers/protobuf#14561]
I made an error when using protobuf library on archlinux. The error message, protobuf version and abseil version are shown below. How to solve it?

```
/usr/include/google/protobuf/port_def.inc:224:15: error: static assertion failed: Protobuf only supports Abseil version 20230125.3 and newer.
  224 | static_assert(PROTOBUF_ABSL_MIN(20230125, 3),
      |               ^~~~~~~~~~~~~~~~~
In file included from test.pb.cc:18:
/usr/include/google/protobuf/port_def.inc:224:15: error: static assertion failed: Protobuf only supports Abseil version 20230125.3 and newer.
  224 | static_assert(PROTOBUF_ABSL_MIN(20230125, 3),
      |               ^~~~~~~~~~~~~~~~~
make: *** [Makefile:18: test.run] Error 1
rm test.pb.cc

172.20.10.2 c++ [📝🤷✓] via C v13.2.1-gcc as 👩‍💻 took 5s ✗  pacman -Ss abseil
extra/abseil-cpp 20230802.1-1 [installed]
    Collection of C++ library code designed to augment the C++ standard library
extra/python-absl 1.4.0-3
    Abseil Python Common Libraries

172.20.10.2 c++ [📝🤷✓] via C v13.2.1-gcc as 👩‍💻 ➜  pacman -Qn protobuf
protobuf 24.4-1
```
My system environment is as follows：
- Linux dingjing-pc 6.1.60-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 25 Oct 2023 11:10:15 +0000 x86_64 GNU/Linux
- protobuf 24.4-1
- abseil-cpp 20230802.1-1

**Comment by hlopko** [comment]
I looked into this, and this is the situation I see:

1) you are using recent-enough abseil-cpp (20230802.1 should be > 20230125.3).
2) abseil-cpp is built as a LTS in archlinux.
3) I don't know what else can go wrong with https://github.com/protocolbuffers/protobuf/blob/5f146f8dfefd136eb969ed3bb73bdd95a462c4f3/src/google/protobuf/port_def.inc#L170.

Could you maybe add some debug prints into the PROTOBUF_ABSL_MIN to see where it's failing?

**Comment by flavienbwk** [comment]
Hi, I'm getting the problem on a clean Windows install with VCPKG and MSVC 2022 in my Cmake project.

My vcpkg.json file :

```
{
  "name": "myproject",
  "version": "0.0.1",
  "dependencies": [
    "abseil",
    "protobuf",
    "grpc"
  ],
  "overrides": [],
  "builtin-baseline": "f1c6efee2245009540dde947e0e3d008f3aa7dbb"
}
```

Has anyone an idea what's going wrong ?
