### ISSUE TITLE
C# documentation differs from actual FieldMask proto

### ISSUE THREAD

**Issue by roblojoe** [protocolbuffers/protobuf#14574]
The [C# protobuf.dev documentation](https://protobuf.dev/reference/csharp/api-docs/class/google/protobuf/well-known-types/field-mask.html#class_google_1_1_protobuf_1_1_well_known_types_1_1_field_mask) states:
`If a repeated field is specified for an update operation, the existing repeated values in the target resource will be overwritten by the new values.`
whereas the [FieldMask proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/field_mask.proto) states:
`If a repeated field is specified for an update operation, new values will
be appended to the existing repeated field in the target resource.`

The C# documentation also says:
`If a sub-message is specified in the last position of the field mask for an update operation, then the existing sub-message in the target resource is overwritten.`
whereas the FieldMask documentation says:
`If a sub-message is specified in the last position of the field mask for an
update operation, then new value will be merged into the existing sub-message
in the target resource.`

Is this difference in documentation intentional, or should the C# docs match the protobuf ones?

**Comment by jskeet** [comment]
It looks like protobuf.dev does not have the latest documentation. If you look at the [C# actual code](https://github.com/protocolbuffers/protobuf/blob/main/csharp/src/Google.Protobuf/WellKnownTypes/FieldMask.pb.cs) it's up-to-date.

I know a while ago there was a problem regenerating the documentation for the web site - I don't know whether that's still the case. I'll find the relevant person and check with them.

**Comment by jskeet** [comment]
@Logofile Are you the right person to check what the status is here?

**Comment by Logofile** [comment]
Generating docs is still a work in progress. Yes, I'm the right person to assign this bug to.
