### ISSUE TITLE
Java generated builder method naming convention for repeated fields

### ISSUE THREAD

**Issue by aoguzperdahci** [protocolbuffers/protobuf#14627]
Hello, I have a issue about the generated java codes.

### Is your feature request related to a problem?
Yes. The problem is caused by the builder method naming convention in the jar file that created. As you know, the repeated fields in the proto file take "List" suffix at the end of the getter method. But the adder methods doesn't have this suffix. Because of this naming convention mapstruct cannot map the classes if there are more than one lists of the same type (if there is only one list of the same type, it can be match by the type). 

We can look with some sample codes:
![image](https://github.com/grpc/grpc-java/assets/86795767/cf3f87e6-2fae-49f1-9fcc-c97fd1e93592)
Using this proto file I compiled a jar. And the jar contains following codes.
![image](https://github.com/grpc/grpc-java/assets/86795767/fb990019-f30c-43c7-b5b5-6d0c74152e4b)
![image](https://github.com/grpc/grpc-java/assets/86795767/5aa9c199-2805-4305-96bb-3ba2cdd15741)
(Also, same methods for items2List and samplesList)

Then I created this java class:
![image](https://github.com/grpc/grpc-java/assets/86795767/d60ce8c9-4dec-4e9b-92f0-75f4087d3c55)

Now, when I try to map HelloRequestInboundDto to ExternalProto.HelloRequest as the following:
![image](https://github.com/grpc/grpc-java/assets/86795767/f28dab3d-f32d-4d2c-a0cd-b449e406a783)

The generated code:
![image](https://github.com/grpc/grpc-java/assets/86795767/4fd22b3f-0637-4859-aa0f-f577c00bb761)

The problem here is this. Because of the naming convention of grpc-java builder methods adder methods of the fields doesn't match (fields have "List" suffix like items1List, items2List, samplesList but the adder methods doesn't have List suffix like addItems1, addItems2, addSamples and they don't match). When add methods and the fields don't match it tries to get the list and add all items to that list. But this mapping throws exception because getter method of the list returns unmodifiableList and when it tries to add items to that list it throws UnsupportedOperationException. Notice the samplesList mapping is what is suppose to be (it uses adder method of the class not getter) because there is only one kind of adder method that accepts Sample type.

### Describe the solution you'd like
To solve that problem the first thing comes to mind add "List" suffix to add method names. This way field names and the adder method names match and there would be no problem. For example, the filed name is items1List, getter method is already named getItems1List so we can change addItems1 to addItems1List. I copied the jar contents and made this change and it works.

### Describe alternatives you've considered
Also, there is another alternative. If you wouldn't want to change existing method names, this solves the problem too. It's about setter methods. Currently, builder methods only have setter for single item in the list. 
Example:
![image](https://github.com/grpc/grpc-java/assets/86795767/6958d7e2-8ba6-4db4-9532-da487b85258a)

But also there could be setter for the whole list in the builder. Since builder methods only used in the creation of the object, it would totally be okay to have such method. Also, it has to named with "List" suffix.
It could be something like this:
![image](https://github.com/grpc/grpc-java/assets/86795767/cc5c3c2c-fc24-4d33-8418-f133212dc173)

### Additional context
There are issues opened for this in mapstruct but it uses exact match for field name (getter method) and setter or adder method so, I think this issue suppose to be handled here. There is a inconsistency here and "List" suffix could be added adder and setter methods or it could be removed from the getter methods altogether.

**Comment by deannagarcia** [comment]
Making that syntax change for a core feature like list setters would break way too many users, so that unfortunately isn't really an option.

However, protobuf does already provide a setter that allows you to set the whole list with the `addAlll` prefix. You can see that documented, along with the other repeated methods [here](https://protobuf.dev/reference/java/java-generated/#repeated). Can you use that?

**Comment by aoguzperdahci** [comment]
Yes I have seen those addAll methods but they also doesn't have "List" suffix like addAllItems1List(). If we write custom mappings we can use any add or addAll methods but in default protoc and mapstuct doesn't compatible in multiple list scenario. Both libraries are used widely. So, I think they should be compatible by default. 

Making that syntax change on existing methods would be a breaking change that I agree. However, I think adding setter for list methods should be okey (see the Describe alternatives you've considered section). Currently there is addAll for manipulation for whole list but there is no setter available for this. There is only setter for elements of the list. If a setter method were added with "List" suffix at the end that would fix the issue. And since we don't change anything already existed, it wouldn't break anything.

**Comment by deannagarcia** [comment]
When adding new methods, protobuf would need to add them for all languages as we try to keep languages as similar as possible. While this naming might not be ideal for java in the specific context of mapstructs, overall our naming works best for the set of languages we support and adding a new setter to every repeated field isn't feasible.

I found this [issue](https://github.com/mapstruct/mapstruct/issues/743) in mapstruct that details this issue and provides workarounds that may be helpful.
