### ISSUE TITLE
Y10K timestamp issue

### ISSUE THREAD

**Issue by domino14** [protocolbuffers/protobuf#14639]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
Note that the timestamp supported by google.protobuf.Timestamp only goes up to the year 9999:

https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto#L53-L55

We have some time to fix this, but I believe it's responsible to open an issue for it. As we continue to assume years have 4 digits this problem will become exponentially harder to solve (i.e. the Y2K problem).

**Describe the solution you'd like**
Since timestamp already internally encodes an int64 for seconds, we should remove the RFC3339 compatibility requirement. For example ISO8601 can support more than 4-digit years by prior agreement between sender and receiver. 

Note that 64-bit time should suffice until the year 292,277,026,596. By then we are likely to be long into the degenerate era (no star formation) so it probably won't matter when we roll over to negative time then.

**Comment by zhangskz** [comment]
Thanks for raising this. I agree that this will eventually be a problem when Y10K rolls around, but its likely too early for us to prioritize addressing this anytime soon.

I'm don't know that we're ready to drop RFC3339 standard yet, and should likely revisit this closer to when this rolls around.
