### ISSUE TITLE
BONUS BUG, which goes in the same direction:

### ISSUE THREAD

**Issue by hothanhloc68** [protocolbuffers/protobuf#14645]
BONUS BUG, which goes in the same direction:
https://svelte.dev/repl/fec873bb251e4f90bb4b418e8212bda9?version=4.2.2
changes to main REPL:
In Navigation.svelte, click-function was modified.
"active = item.value"
is now processed for any NavigationItem.

With this change, is is possible to see many "active" Items (which should never happen).
If you click Submenu first and then quickly collapse/expand Menu.

_Originally posted by @dm-de in https://github.com/sveltejs/svelte/issues/9361#issuecomment-1784177467_

**Comment by hothanhloc68** [comment]
> BONUS BUG, which goes in the same direction:
> https://svelte.dev/repl/fec873bb251e4f90bb4b418e8212bda9?version=4.2.2
> changes to main REPL:
> In Navigation.svelte, click-function was modified.
> "active = item.value"
> is now processed for any NavigationItem.
> 
> With this change, is is possible to see many "active" Items (which should never happen).
> If you click Submenu first and then quickly collapse/expand Menu.
> 
> _Originally posted by @dm-de in https://github.com/sveltejs/svelte/issues/9361#issuecomment-1784177467_

**Comment by zhangskz** [comment]
This issue is inactionable. Feel free to reopen with additional details on what you are trying to resolve and a repro.
