### ISSUE TITLE
 _ZTISt16invalid_argument: invalid version 6 (max 0)

### ISSUE THREAD

**Issue by linchenxuan** [protocolbuffers/protobuf#14648]
protoc version: libprotoc 25.0
ld: /usr/local/bin/protoc: _ZTISt16invalid_argument: invalid version 6 (max 0)
ld: /usr/local/bin/protoc: error adding symbols: bad value

**Comment by zhangskz** [comment]
Do you have more details on the problem and repro?

**Comment by zhangskz** [comment]
Closing this as inactionable. Please reopen if you have more details on the error encountered or repro here.
