### ISSUE TITLE
well_known_types is deprecated and suggests using :compiler_plugin_proto, which does not exist

### ISSUE THREAD

**Issue by ravenblackx** [protocolbuffers/protobuf#14675]
Version: HEAD
Language: bazel build rules

See https://github.com/protocolbuffers/protobuf/issues/11430 for a prior incarnation of the same problem.

`well_known_protos` now flags as deprecated and exposes

```
    srcs = [
        ":descriptor_proto_srcs",
        ":well_known_type_protos",
        "//src/google/protobuf/compiler:plugin.proto",
    ],
```

The comment says

```
# DEPRECATED: Prefer :well_known_type_protos for the Well-Known Types
# (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)
# or :descriptor_proto(_srcs) for descriptor.proto (source), or
# :compiler_plugin_proto for compiler/plugin.proto.
```

But the target `:compiler_plugin_proto` doesn't exist, and there's no visibility to the inner target.

(Also, it would be nice if the `deprecated=` tag said all the same options the comment says, because otherwise when we update this our developers are going to get this warning telling them to switch to only `:well_known_type_protos` which may or may not actually work for any given use-case.)

**Comment by mkruskal-google** [comment]
//:compiler_plugin_proto does exist as an alias at the top level, is that not sufficient (granted, we could clean up our comments here)

**Comment by ravenblackx** [comment]
Weird, I must have made a *whole series* of mistakes to think that wasn't there (both in code search and in a build rule trying to depend on it, somehow). Sorry about that!
(But yes, would still be good to make the dependency here on the alias instead of directly, and to make the deprecated= string mention all three things. Not as critical of an issue as I somehow thought though!)

**Comment by ravenblackx** [comment]
Ah! It wasn't just me making a mistake, it was literally the same problem as last time, and you've said the equivalent thing to what you said last time!

```
alias(
    name = "descriptor_proto",
    actual = "//src/google/protobuf:descriptor_proto",  # proto_library
    visibility = ["//visibility:public"],
)

alias(
    name = "descriptor_proto_srcs",
    actual = "//src/google/protobuf:descriptor_proto_srcs",  # filegroup
    visibility = ["//visibility:public"],
)

alias(
    name = "compiler_plugin_proto",
    actual = "//src/google/protobuf/compiler:plugin_proto",  # proto_library
    visibility = ["//visibility:public"],
)
```

```
filegroup(
    name = "well_known_protos",
    srcs = [
        ":descriptor_proto_srcs",
        ":well_known_type_protos",
        "//src/google/protobuf/compiler:plugin.proto",
    ],
    deprecation = "Prefer :well_known_type_protos instead.",
    visibility = ["//visibility:public"],
)
```
The alias is for `plugin_proto` not for `plugin.proto`, i.e. it's like `descriptor_proto` not like `descriptor_proto_srcs`.

**Comment by ravenblackx** [comment]
Just to make life extra awkward, over in the compiler build file there *is* a `compiler_plugin_srcs` but it's got cpp and h files in it too, and a `compiler_plugin_src` that has the file we actually need but lacks visibility.

My patch that makes this usable is:
```
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -129,6 +129,12 @@ alias(
     visibility = ["//visibility:public"],
 )

+alias(
+    name = "compiler_plugin_proto_srcs",
+    actual = "//src/google/protobuf/compiler:plugin_proto_src",  # filegroup
+    visibility = ["//visibility:public"],
+)
+
 cc_library(
     name = "cc_wkt_protos",
     deprecation = "Only for backward compatibility. Do not use.",
@@ -148,7 +154,7 @@ filegroup(
         ":well_known_type_protos",
         "//src/google/protobuf/compiler:plugin.proto",
     ],
-    deprecation = "Prefer :well_known_type_protos instead.",
+    deprecation = "Prefer :well_known_type_protos, :descriptor_proto_srcs and/or :compiler_plugin_proto_srcs instead.",
     visibility = ["//visibility:public"],
 )


--- a/src/google/protobuf/compiler/BUILD.bazel
+++ b/src/google/protobuf/compiler/BUILD.bazel
@@ -188,7 +188,10 @@ filegroup(
 filegroup(
     name = "plugin_proto_src",
     srcs = ["plugin.proto"],
-    visibility = ["@upb//:__subpackages__"],
+    visibility = [
+        "@upb//:__subpackages__",
+        "//:__subpackages__",
+    ],
 )

 exports_files(
```

**Comment by mkruskal-google** [comment]
lol deja vu 🤦‍♂️.  Why do you need the source file at all?  I think we ideally *would* want that to be private..

Anyway, if you send me a PR with those changes we can sort it out there

**Comment by ravenblackx** [comment]
I think we're processing the source file in order to have access to the descriptors in python. Maybe there's a more modern way to do that with a python genfile from the proto library target or something, but when I'm struggling to update the version of protobuf used by a monorepo, the less gigantic refactorings of everything that depends on it the better!

(This time I've already removed all reliance on javascript protobufs from our entire monorepo because the google-protobuf-javascript github repo had been broken for over a year - then a few days after I'd done that it finally got an unbreaking update, of course.)
