### ISSUE TITLE
google::protobuf::compiler::rust::Map

### ISSUE THREAD

**Issue by city-invoker** [protocolbuffers/protobuf#14685]
i compile the source code and got an error in the link

buf8compiler4rust3MapD5Ev]'
/usr/bin/ld: libprotoc.a(accessors.cc.o): in function `google::protobuf::compiler::rust::Map::Map()':
accessors.cc:(.text._ZN6google8protobuf8compiler4rust3MapC2Ev[_ZN6google8protobuf8compiler4rust3MapC5Ev]+0x1f): undefined reference to `vtable for google::protobuf::compiler::rust::Map'
/usr/bin/ld: libprotoc.a(accessors.cc.o): in function `google::protobuf::compiler::rust::Map::~Map()':
accessors.cc:(.text._ZN6google8protobuf8compiler4rust3MapD2Ev[_ZN6google8protobuf8compiler4rust3MapD5Ev]+0x13): undefined reference to `vtable for google::protobuf::compiler::rust::Map'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/protoc.dir/build.make:174: protoc-25.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1099: CMakeFiles/protoc.dir/all] Error 2

**Comment by honglooker** [comment]
Hi @city-invoker, thanks for taking a look! This code is experimental, and is liable to break without warning [1].

[1] https://github.com/protocolbuffers/protobuf/commit/89d6b74dea804995488980c44d3f53855e926d69
