### ISSUE TITLE
php8.1  php-c-extension: protobuf  not work fine as same as  using  pure php vendor  

### ISSUE THREAD

**Issue by ahardstone** [protocolbuffers/protobuf#14682]
env：
centos7.6
php-8.1.25
protoc : 24.4 [download protoc-24.4-linux-x86_64.zip  and add lnk to /usr/bin/protoc]
I tried many version  protobuf  both verion-24.*[vendor code replace] and version-25.*
while i use  the pure php vendor   by using   composer   require google/protobuf
the code always work fine .
but if  i remove composer    package  google/protobuf,  and  use pecl install  protobuf [i'm sure install success ,php -m show right]
the code  always work wrong.  
the code  demo like:
`
$protoClass = "\\App\\Protocol\\Protobuf\\GPBClass\\Message\\{$proto}";

                    $pbObject = new $protoClass(); //return \Google\Protobuf\Internal\Message

                    $json = json_encode($data);

                    $pbObject->mergeFromJsonString($json,true);

                    $content = $pbObject->serializeToString();
                    var_dump(PHP_EOL . '--content=' . $content . '---len='.strlen($content).'----' . PHP_EOL);
`
I expect  the result  show like :
--content=
<ss--G703441111111111111111111111111a111111111111111111111111ȥ╝G
8G703441111111111111111111111111a111111111111111111111111╔2(╔8╔@╔P╔X╔"

192.168.1.31K*r╝1111z╝1111---len=187----
(1)same code  run  as  expect  if i use  composer    package  google/protobuf 
 
(2)but never  run well  if I use  the c-extension: protobuf [pecl install protobuf]
in (2)  i had tred view the  c code  but still  cannot solve it .

the  c-extionsion  i use  for  improve performance but always return error:

Error occurred during parsing: Error parsing JSON @1:615: Expected string","json":"{\"sessionId

AnyOne  can help  ?

**Comment by zhangskz** [comment]
Have you followed the documentation in https://github.com/protocolbuffers/protobuf/blob/main/php/README.md to install the PHP C-Extension (e.g. including installing any prereqs)?

What is the full JSON parse error message you are hitting and where are you hitting it?

**Comment by ahardstone** [comment]
I 'm sure  as  the doc [ https://github.com/protocolbuffers/protobuf/blob/main/php/README.md ]
doc show  follow:
[Installation from PECL](https://github.com/protocolbuffers/protobuf/blob/main/php/README.md#installation-from-pecl)
When we release a version of Protocol Buffers, we will upload the extension to [PECL](https://pecl.php.net/). To use this pre-packaged extension, simply install it as you would any other extension:

sudo pecl install protobuf-{VERSION}

in fact ,i can only run cmd: [pecl install protobuf]  but  no cmd like pecl install protobuf-3.24

**Comment by zhangskz** [comment]
Full error message you are hitting? Can you confirm what version of protobuf installed after `pecl install protobuf`?

**Comment by ahardstone** [comment]
[protobuf-3.25.0.tgz]
download link  show https://pecl.php.net/get/protobuf-3.25.0.tgz

**Comment by ahardstone** [comment]
I use try catch  get the error message:
 Error occurred during parsing: Error parsing JSON @1:615: Expected string","json":"{"sessionId……
after  "json"  just show the  value of the var $json ,  I cannot find  any other  message

**Comment by haberman** [comment]
What is the JSON string in `$json`?

It looks like the pure PHP library is accepting some JSON that the C extension is rejecting. It would help to know what the JSON string is. Also what does the message look like in the `.proto` file?

**Comment by haberman** [comment]
Please feel free to open a new issue if you are still experiencing this problem. Please include the JSON string that is failing to parse.
