### ISSUE TITLE
JSON Unmarshal some Unicode escape sequence result in error

### ISSUE THREAD

**Issue by denis-zyk** [protocolbuffers/protobuf#14718]
**What version of protobuf and what language are you using?**
Version:
```bash
protoc --version
libprotoc 23.4

protoc-gen-go --version
protoc-gen-go v1.31.0
```
Golang lib:
```
google.golang.org/protobuf v1.30.0
```

Language: Golang

**What operating system (Linux, Windows, ...) and version?**
Linux: `Linux 6.1.0-0.deb11.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64 GNU/Linux`
macOS: `Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64`

**What runtime / compiler are you using (e.g., python version or gcc version)**
Linux: `go version go1.20.11 linux/amd64`
macOS: `go version go1.21.4 darwin/arm64`

**What did you do?**
1. Have a JSON string containing the following Unicode escape sequence `\udca0`, e.g. `{"name":"'unsafe-eval'; object?src\udca0'none'"}`.
2. Unmarshal byte slice of JSON string in question to protobuf message using `google.golang.org/protobuf/encoding/protojson` package.
3. See error `proto: syntax error (line 1:9): invalid escape code "'none'" in string`.

**What did you expect to see**
Unmarshalled value `name:"'unsafe-eval'; object?src�'none'"`. I.e. same unmarshalled string value as in Golang core JSON lib.

**What did you see instead?**
Unpopulated message and an error message `proto: syntax error (line 1:9): invalid escape code "'none'" in string`.

Code snippet for reproducing issue:
```golang
package main

import (
	"encoding/json"
	"fmt"
	"google.golang.org/protobuf/encoding/protojson"
	
	"pkg.my.package/microservices/models"
)

func main() {
	j1 := []byte(`{"name":"'unsafe-eval'; object?src\uc2a0'none'"}`)	# unmarshal is OK
	j2 := []byte(`{"name":"'unsafe-eval'; object?src\udca0'none'"}`)	# unmarshal error in protojson

	// protojson lib

	// models.Client is a golang struct compiled using `protoc` binary, from Client protobuf message.
	// Protobuf message for the sake of reproducing has 1 string field:
	//   Name       string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	outProto1 := &models.Client{}
	outProto2 := &models.Client{}

	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}

	err1 := unmarshaler.Unmarshal(j1, outProto1)
	err2 := unmarshaler.Unmarshal(j2, outProto2)

	fmt.Println("protojson lib")
	fmt.Println(string(j1), err1, outProto1)
	fmt.Println(string(j2), err2, outProto2)

	// core lib
	outCore1 := make(map[string]interface{})
	outCore2 := make(map[string]interface{})

	err1 = json.Unmarshal(j1, &outCore1)
	err2 = json.Unmarshal(j2, &outCore2)

	fmt.Println("core lib")
	fmt.Println(string(j1), err1, outCore1)
	fmt.Println(string(j2), err2, outCore2)
}
```

Produces the following output:
```
protojson lib
{"name":"'unsafe-eval'; object?src\uc2a0'none'"} <nil> name:"'unsafe-eval'; object?src슠'none'"
{"name":"'unsafe-eval'; object?src\udca0'none'"} proto: syntax error (line 1:9): invalid escape code "'none'" in string 
core lib
{"name":"'unsafe-eval'; object?src\uc2a0'none'"} <nil> map[name:'unsafe-eval'; object?src슠'none']
{"name":"'unsafe-eval'; object?src\udca0'none'"} <nil> map[name:'unsafe-eval'; object?src�'none']
```

**Comment by zhangskz** [comment]
Go protobuf does not belong to this repository. Please refile this issue to https://github.com/golang/protobuf.
