### ISSUE TITLE
PLEASE make Protobuf backwards compatible.

### ISSUE THREAD

**Issue by tyler-suard-parker** [protocolbuffers/protobuf#14755]
Whenever you release a new version of Protobuf, it should be compatible with code written for the last Protobuf.  As it is currently, Protobuf 4 introduces changes that break scripts written for Protobuf 3.  That is such a huge pain to find and fix, and have to rewrite my scripts every time a new version comes out.  Please be considerate of the people who use your software, and make sure that each new version is compatible with scripts written using the previous version.

**Comment by zhangskz** [comment]
Thanks for the feedback. Note that our versioning scheme is explained in https://engdoc.corp.google.com/eng/doc/devguide/proto/news/2022-05-06.md#versioning. We only increment major versions (e.g. 3.x.x to 4.x.x) for a language when we have breaking changes, following [SemVer](https://semver.org/) convention.

These breaks are important to allow Protobuf to evolve (e.g. deprecate old APIs after deprecation warnings). We pre-announce breaking changes in our [News](https://protobuf.dev/news/) page so you should be able to plan for these accordingly.

Minor releases with the same major version (e.g. v24.x -> v25.x) should remain backwards compatible. Please file issues if you see compatibility issues like this in a minor release.

You can also see https://protobuf.dev/support/cross-version-runtime-guarantee/ for our cross version runtime guarantees.
