### ISSUE TITLE
libprotobuf.dll loadlibrary 3765269347 in XP

### ISSUE THREAD

**Issue by dearwangsen** [protocolbuffers/protobuf#14759]
I built Protobuf as a dynamic library using:

`vs2015 update3 v140_xp windows10`

When I attempt to 'loadlibrary()' on an windows XP, it returns 'null' with 'GetLastError()' reporting '3765269347'. This issue occurs in protobuf version >= '3.6.0'. This issue does not occur with version <= '3.5.2'.

I used the following cmake command to generate the solution:

`cmake -G "Visual Studio 14 2015" -A Win32 -DGOOGLE_PROTOBUF_SUPPORT_WINDOWS_XP=1 -Dprotobuf_BUILD_TESTS=OFF ..`

In vs2015, I used:

`/D "_WIN32_WINNT=0x502" /Zc:threadSafeInit- /MT`

Additionally, when I statically link protobuf to my executable, the program runs without issues.

**Comment by zhangskz** [comment]
These are pretty old versions of Protobuf and dependencies.

Can you confirm if you hit similar issues on a Protobuf version that is still [under support](https://protobuf.dev/support/version-support/) (e.g. v25.0). Note that our foundational support matrix also indicates that our windows support is for >= 10 so errors on windows XP may be expected.

**Comment by dearwangsen** [comment]
When I use `v25.0`, The error message reads: 
`fatal error C1189: #error: "This package requires Visual Studio 2019 (MSVC++ 16.0) or higher.`
I attempted to build `libprotobuf.dll` versions `v3.21.0`, `v3.15.0`, `v3.12.0` using `vs2015 v140_xp` in a `Windows10`. When calling `LoadLibraryA("libprotobuf.dll")` on an `WindowsXP`, it returns `null` with 'GetLastError()' showing '3765269347'."
The netizen reminded me: `Because the DllMain() function inside the DLL died due to an unhandled C++ exception.`, but I can't find the problem of `libprotobuf.dll`.
I statically linked ‘libprotobuf.lib’ to my `.exe`, and performed a basic operation (set_value) . `.exe` runs normally.

**Comment by dearwangsen** [comment]
> These are pretty old versions of Protobuf and dependencies.
> 
> Can you confirm if you hit similar issues on a Protobuf version that is still [under support](https://protobuf.dev/support/version-support/) (e.g. v25.0). Note that our foundational support matrix also indicates that our windows support is for >= 10 so errors on windows XP may be expected.

When I use `v25.0`, The error message reads: 
`fatal error C1189: #error: "This package requires Visual Studio 2019 (MSVC++ 16.0) or higher.`
I attempted to build `libprotobuf.dll` versions `v3.21.0`, `v3.15.0`, `v3.12.0` using `vs2015 v140_xp` in a `Windows10`. When calling `LoadLibraryA("libprotobuf.dll")` on an `WindowsXP`, it returns `null` with 'GetLastError()' showing '3765269347'."
The netizen reminded me: `Because the DllMain() function inside the DLL died due to an unhandled C++ exception.`, but I can't find the problem of `libprotobuf.dll`.
I statically linked ‘libprotobuf.lib’ to my `.exe`, and performed a basic operation (set_value) . `.exe` runs normally.

**Comment by dearwangsen** [comment]
Could anyone please help me? This issue is bound to happen. I suspect that certain C++11 syntax in `libprotobuf.dll` may not be compatible with XP.

**Comment by zhangskz** [comment]
The requirement of Visual Studio 2019+ in v25.0 is from absl: https://github.com/abseil/abseil-cpp/blob/2fca64174fe9aefe9250bdab1586eb5d69649cca/absl/base/policy_checks.h#L50 which we added a dependency on in 22.x.

Our [OSS support matrix](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md) indicates support for Windows 10+, so this is probably the cause for C+11 / Windows XP compatibility. Can you upgrade to Windows 10 instead? I'm not sure exactly when we dropped Windows XP support but its possible that was in 3.6.0.
