### ISSUE TITLE
Can not read protobuf message from shared memory. Ask for help

### ISSUE THREAD

**Issue by neuliyiping** [protocolbuffers/protobuf#14774]
I create a Message with Arena on shared memory in process A, But when I get Message from shared memory in process B, there is a segment fault happened.

Proto: 
```
syntax = "proto3";

package walle.hdmap;

option cc_enable_arenas = true;

message S {
  repeated string signal_id = 1;
}

message ProtoTest {
  int64 id = 1;
  S signal = 2;
}
```

proto_test address & shared memory range in process A:
![5381be7dcc9f32364d4b5c40fd065eef328907](https://github.com/protocolbuffers/protobuf/assets/52898354/80b0d0d6-1831-4a56-b14c-ac2a54d67541)

proto_test address & shared memory range in process B:
![a1f6bc9469ed6cbeba72fb970c66410c359543](https://github.com/protocolbuffers/protobuf/assets/52898354/99ec691e-bb1e-4de8-aad3-ade6a26321da)

As shown in the figure above, the address of proto_test in process B is the same as the address in process A and is not within the shared memory range.

If I want to put Message into shared memory, do I have to serialize it into string (byte arrays) first?

**Comment by DyXel** [comment]
I was wondering the same thing as the OP: Is it possible to use protobuf with shared memory in order to avoid needlessly encoding and decoding a message when crossing process boundaries?

**Comment by shynur** [comment]
Have you figured out a solution?

**Comment by DyXel** [comment]
No.
