### ISSUE TITLE
[C#] Ensure enum members are preserved with trimming

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#14788]
Note: I haven't seen anything broken by this issue. These are my thoughts in the area in case it does become a problem in the future.

---

AOT and trimming will remove unused members. That can include enum fields. I have tested places that use enum fields with reflection (e.g. JSON parser with enum values) and it appears to work, but I don't think that is a guarantee it will work forever.

The typical fix to this problem is to use `DynamicallyAccessedMembersAttribute` (DAM) to explicitly preserve values. However, that isn't possible when enum descriptors are registered because [GeneratedClrTypeInfo](https://github.com/protocolbuffers/protobuf/blob/b0d7441f83a4cc79d3937f65f8cc2b46931ea639/csharp/src/Google.Protobuf/Reflection/GeneratedClrTypeInfo.cs) accepts enum types in an array, and an array can't be annotated.

I see two ways to fix this:

One way is generate a dummy method that has a `Type` parameter and returns `Type`. The method parameter would have the DAM attribute on it:

```cs
private Type EnsureEnumMembers([DynamicallyAccessedMembers(PublicFields)] Type t) => t;
```

And then call it when values are passed to `GeneratedClrTypeInfo`. e.g.

```cs
new pbr::GeneratedClrTypeInfo(
    new[] { EnsureEnumMembers(typeof(global::Conformance.WireFormat)), EnsureEnumMembers(typeof(global::Conformance.TestCategory)) },
    ...);
```

That would signal to the linker that public fields for these enum types should never be trimmed.

Or have an `AddEnumType` method on `GeneratedClrTypeInfo` used to add enum types. That method can be annotated with the DAM attribute. The downside here is `GeneratedClrTypeInfo` is designed to be immutable (mostly, the arrays can be set, but they're not intended to be.

**Comment by jskeet** [comment]
I still need to get back to this.
