### ISSUE TITLE
add native Optional API for languages which support it

### ISSUE THREAD

**Issue by rursprung** [protocolbuffers/protobuf#14786]
**What language does this apply to?**
(focused on proto3, but might also apply to proto2 - i have no experience with proto2, though)

this applies to all programming languages which have a built-in notion of optional values, e.g. Java ([`java.lang.Optional`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html)) or Rust ([`std::option::Option`](https://doc.rust-lang.org/std/option/enum.Option.html)). the examples below are given in java.

**Describe the problem you are trying to solve.**
currently it is hard to deal with optional values in an idiomatic way in languages which would support this.

stripped-down example (extracted from a real-world example):
`example.proto`:
```proto
syntax = "proto3";

package example;

message Foo {
  sint64 example = 1;
}

message Example {
  optional sint64 example = 1;
  Foo foo = 2;
}
```

currently the java code to then access this data looks something like this:
```java
  public void foo(final Example example) {
    // directly:
    final long someDefaultValue = 42;
    final long bar = example.hasExample() ? example.getExample() : someDefaultValue;
    final long foo = example.hasFoo() ? example.getFoo().getExample() : someDefaultValue;

    // as optional:
    final Optional<Long> optionalBar = example.hasExample() ? Optional.of(example.getExample()) : Optional.empty();
    final Optional<Long> optionalFoo = example.hasFoo() ? Optional.of(example.getFoo().getExample()) : Optional.empty();
  }
```

**Describe the solution you'd like**
it should be possible to tell protoc that the generated classes (or equivalents thereof in other languages) should generate APIs with `Optional` (or its equivalent) instead of `has[..]` & `get[...]` so that it can be used directly:
```java
  public void foo(final Example example) {
    // directly:
    final long someDefaultValue = 42;
    final long bar = example.getExample().orElse(someDefaultValue);
    final long foo = example.getFoo().map(Foo::getExample).orElse(someDefaultValue);

    // as optional:
    final Optional<Long> optionalBar = example.getExample();
    final Optional<Long> foo = example.getFoo().map(Foo::getExample);

    // you can still check for presence:
    final bool hasBar = example.getExample().isPresent();
    final bool hasFoo = example.getFoo().isPresent();
  }
```

**Describe alternatives you've considered**
manually writing this code all the time is very cumbersome and makes it harder to generalise the handling of optional values which are present in multiple messages (you can't just pass the `Optional` directly from the message to the handler, you have to manually convert it to an `Optional` first or have an ugly API which accepts both a presence indicator and a value).

making this the default behaviour would be a breaking change, accordingly i propose to introduce this as an optional feature which can be enabled when triggering the code generation (_maybe_ this could be turned into the default at some point in the future with a major release, though the ripple effects would probably be too big as all consuming code dealing with optional values would have to deal with this).

**Additional context**

**Comment by rursprung** [comment]
this is IMHO still a desirable feature

**Comment by googleberg** [comment]
Hi rursprung,

As Sandy says, we tend to be very careful about adding new features or new idioms that can only be represented in a single language. What she did not spell out explicitly is that Optional APIs are problematic for Java lite on Android where creating an Optional wrapper around the field value incurs an allocation of an Optional object. While this may not be a big performance penalty on the server side, it can add up to be enough to cause a problem on the mobile side.

You might then ask, "why can't Android code call the non-Optional APIs but have the Optional ones for those that can use them?". And the answer is that on Android, generating unused methods is not good -- code size is a real problem there. Whole program optimization like ProGuard can remove unused methods, but if a few callsites are introduced, you can't remove those methods.

The next logical question is then, "how about an option to generate these methods?" and the answer there is that every option expands the support surface and increases the combinatorial complexity of testing the ecosystem.

What about "just in Java not in JavaLIte". We try to avoid divergence of the Java and JavaLite API. In addtion to the combinatorial complexity / maintenance argument, there is also the migration path: the less divergence, the more likely an Android App can migrate from Full to LIte.

If a sufficient argument for the impact of `Optional` comes along that overrides the problems of mobile performance, code size, and maintenance complexity we will absolutely reconsider. But for now, the `has` + `get` API provides a workable solution.
