### ISSUE TITLE
MSVC compilation warnings due to non-portable -std=c++17 flag

### ISSUE THREAD

**Issue by erocs** [protocolbuffers/protobuf#14781]
**What version of protobuf and what language are you using?**
Version: tag v25.0 / HEAD of main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Win11

**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC 2022 Community with cl.exe version "19.37.32825"

**What did you do?**
1. Install git, bazel, MSVC
2. Clone the protobuf repository locally
3. Open the x64 Native Tools Command Prompt for VS 2022
4. Attempt to build with Bazel: bazel build //src/google/protobuf/compiler:protoc_lib
5. Note the frequent repeated compiler warning "cl : Command line warning D9002 : ignoring unknown option '-std=c++17'"
6. Edit the repository's .bazelrc and update the --cxxopt and --host_cxxopt options on line 1 so they are both '/std:c17'
7. Attempt to build with Bazel: bazel build //src/google/protobuf/compiler:protoc_lib
8. Notice the warning condition is remedied

**What did you expect to see**
I expected the C++17 support to be activated for the MSVC compiler without warnings.

**What did you see instead?**
Warnings about an incorrect flag and a failure to activate the compiler's c++17 support.

The compiler parameter specified in protobuf's .bazelrc file, added via commit d99134f6f8e3, is incompatible with the MSVC compiler, which uses the flag '/std:c17'. The options should be specified in a platform independent manner so both MSVC and linux based compilers read it properly.

**Comment by scfwilson** [comment]
By the following the example of .bazelrc in grpc and changing the line to build:windows in protobuf's .bazelrc I was able to get rid of this warning. So in grpc the code looks like this and therefore I would suggest something similar needs to be done for protobuf
`build:windows --cxxopt='/std:c++14'
build:windows --host_cxxopt='/std:c++14'
build:linux   --cxxopt='-std=c++14'
build:linux   --host_cxxopt='-std=c++14'`

**Comment by phst** [comment]
Yes; in addition, you need

```
common --enable_platform_specific_config
```

so that the `build:windows` syntax works.

Also add

```
build:macos   --cxxopt='-std=c++14'
build:macos   --host_cxxopt='-std=c++14'
```

so that macOS builds continue working.
