### ISSUE TITLE
[C#] Update .NET solution to use .NET 8 SDK

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#14790]
The .NET solution currently uses an old .NET 6 SDK:

https://github.com/protocolbuffers/protobuf/blob/4864e43b7d62a30bf335f1b5ba56d07515b3f959/global.json#L3

It should be updated to .NET 8 to keep tooling modern.

**Comment by jskeet** [comment]
This is definitely something to aspire to, but it may take longer than expected due to complexities in terms of *internal* tooling.

**Comment by embeddetech** [comment]
Wow, @JamesNK wrote Newtonsoft.Json??? 

https://images.app.goo.gl/yjNLXn18L9A7XqyX8

**Comment by jskeet** [comment]
> I'm also needing to use protobuf with .NET 8 soon...

There's nothing stopping you doing that now. You don't need the Google.Protobuf library to explicitly target .NET 8, or for it to be built with the .NET 8 SDK, for you to use it from .NET 8.

**Comment by jskeet** [comment]
Reopening, as we do want to do this eventually.

**Comment by JamesNK** [comment]
FYI .NET 6 is end-of-life November 12, 2024

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by jskeet** [comment]
Yup, we definitely need to get on this - if only I could clone myself...

**Comment by JamesNK** [comment]
Still need

**Comment by jskeet** [comment]
cc @amanda-tarafa - we might want to see what our team can do to help the Protobuf team on this one.
