### ISSUE TITLE
I have two imports, but only one is generated, so that I cannot get the complete dependency in FileDescriptorProto.

### ISSUE THREAD

**Issue by crayxn** [protocolbuffers/protobuf#14864]
**What version of protobuf and what language are you using?**
Version: libprotoc 25.1
Language:  PHP

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 8.1.2
**What did you do?**

I have two imports, but only one is generated, so that I cannot get the complete dependency in FileDescriptorProto.
1. my proto
```
syntax = "proto3";

package partner.v1;

import "partner/v1/base.proto";
import "google/protobuf/empty.proto";
...
```
2. generated code (Metadata)

![image](https://github.com/protocolbuffers/protobuf/assets/21336335/90c83898-f005-4503-9b29-0f1c960b3aed)

3. If there is only one import, it will get empty dependency  from FileDescriptorProto.

**What did you expect to see**
I can get the complete dependency in FileDescriptorProto.
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by haberman** [comment]
Sorry for the slow reply. Can you be more specific about what went wrong? Did you get an error message at runtime? Or did you call an API and get a return value that wasn't what you expected?

**Comment by haberman** [comment]
Please feel free to open a new issue if you are still experiencing this problem.
