### ISSUE TITLE
from google.protobuf.pyext import _message → "TypeError: bases must be types"

### ISSUE THREAD

**Issue by lijithomas88** [protocolbuffers/protobuf#14880]
**What version of protobuf and what language are you using?**
Version: 4.25.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux  4.14.251  aarch64  GNU/Linux (yocto distribution)

uname -a shows below output.
Linux PROCONNECT-00112B04341E 4.14.251 #1 SMP Mon Oct 25 13:18:52 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.11 
[GCC 9.3.0] on linux

**What did you do?**
I have installed protobuf using pip3 install protobuf==4.25.1.
Compiled my proto file using protoc-25.1-linux-aarch_64 downloaded from https://github.com/protocolbuffers/protobuf/releases/tag/v25.1. 
On running my python script to read can message and convert to protobuf, I am getting below error message.

File "/usr/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 17, in <module>
    from google.protobuf.internal import api_implementation
  File "/usr/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 81, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
Try to set the env PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION to 'upb' ?

**Comment by lijithomas88** [comment]
Above issue is not occuring after setting this. Thanks.

**Comment by lijithomas88** [comment]
closing the issue
