### ISSUE TITLE
How to use protobuf-javalite

### ISSUE THREAD

**Issue by farsunset** [protocolbuffers/protobuf#14949]
How to generate match javalite source code
I use https://repo1.maven.org/maven2/com/google/protobuf/protoc-gen-javalite/3.0.0/
./protoc  --javalite_out=./ Message.proto

but have code error
Cannot resolve symbol 'ExtensionRegistry'
Cannot resolve symbol 'MessageOrBuilder'

**Comment by zhangskz** [comment]
Please see https://github.com/protocolbuffers/protobuf/blob/main/java/lite.md#use-the-protobuf-java-lite-runtime for instructions on using java lite on a current version of protobuf.

Note, you should be able to use `protoc` directly, not `protoc-gen-java-lite` 3.0.0 which is very old and no longer unsupported.
