### ISSUE TITLE
Feature Request: Shared library version of utf8_range

### ISSUE THREAD

**Issue by spotaws** [protocolbuffers/protobuf#14958]
**Describe the problem you are trying to solve.**

Current versions of protobuf include a copy of utf8_range, which generates two static libraries, along with cmake and pkg-config files. Most Linux distributions would prefer shared libraries over static libraries, especially for items which are intended to be reused (as signaled by the inclusion of cmake and pkg-config files). Could you please consider enabling support for the utf8_range libraries to be built as shared libs?

**Describe the solution you'd like**

utf8_range libraries built as proper shared libs.

**Describe alternatives you've considered**

I did make an attempt to get cmake to build shared libraries for utf8_range, but this just resulted in it making versioned static-pie ... things that were neither shared libraries nor static libraries, so I undid all of that and opened this feature request instead. cmake is confusing sometimes.

**Comment by garrettkajmowicz** [comment]
I would be interested in a shared library version of this as well.
