### ISSUE TITLE
--proto_path fails on Windows

### ISSUE THREAD

**Issue by cuongkbtg** [protocolbuffers/protobuf#14965]
Version: protobuf-25.1
Language: Go
OS: Windows 11

``proto_path`` will not work on Windows.
proto_path:           Specify the directory in which to search for
                              imports.  May be specified multiple times;
                              directories will be searched in order.  If not
                              given, the current working directory is used.
                              If not found in any of the these directories,
                              the --descriptor_set_in descriptors will be
                              checked for required proto file.
As you can see, I tried to specify the current directory, but it failed.
Only when I input the file did the protoc command  works.
Anyone have any idea how to fix this.
Thank you.
```
C:\Users\CuongNguyen\GolandProjects\Coral\upg-kratos\proto\upg\kgp\common>ls
common.proto

C:\Users\CuongNguyen\GolandProjects\Coral\upg-kratos\proto\upg\kgp\common>protoc --proto_path=. --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:.
Missing input file.

C:\Users\CuongNguyen\GolandProjects\Coral\upg-kratos\proto\upg\kgp\common>protoc common.proto --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:.

C:\Users\CuongNguyen\GolandProjects\Coral\upg-kratos\proto\upg\kgp\common>ls
common.pb.go  common.proto
```

![image](https://github.com/protocolbuffers/protobuf/assets/152852751/b075fdf6-d387-4fb4-a0b9-a37e726cbfc6)

**Comment by haberman** [comment]
What output did you expect? It looks like the source files were generated successfully by the third command?

**Comment by vipetrul** [comment]
It appears that searching within a directory doesn't work, but it does work when specifying proto file path explicitly.

**Comment by Erutan409** [comment]
@vipetrul Did you ever figure this out?

**Comment by googleberg** [comment]
@vipetrul this seems resolved. If not, feel free to reopen.
