### ISSUE TITLE
replace memset with memset_s in generated code

### ISSUE THREAD

**Issue by GradyLee** [protocolbuffers/protobuf#14977]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
I hope to replace memset with memset_s and memcpy with memcpy_s in the generated code.

**Describe the solution you'd like**
add new option(-std=c++11) to the protoc to indicate the language standard to compile for, if user specify c++11 standard then replace memset with memset_s and memcpy with memcpy_s

**Describe alternatives you've considered**

**Additional context**
protoc --std=c++11 --cpp_out=./ foo.proto

**Comment by haberman** [comment]
Why do you want the generated code to use `memset_s` and `memcpy_s`?  These are bounds-checked functions which will incur runtime overhead. The C++ proto library relies on its own internal logic to ensure that bounds are safe. Changing these functions would add little safety overall, while introducing extra CPU overhead.
