### ISSUE TITLE
When calling the object's toString() method, if the content of the string type attribute is a multi-byte character, octal will be output.

### ISSUE THREAD

**Issue by haytoo** [protocolbuffers/protobuf#14978]
**What version of protobuf and what language are you using?**
Version: 25.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Win11

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java21

**What did you do?**
proto file：
```
message WxMsg
{
    uint64 id      = 3;  // message id
    uint32 type    = 4;  // message type
    uint32 ts      = 5;  // 
    string content = 7;  // text message
    string sender  = 8;  // message sender
    string sign    = 9;  // 
    string xml     = 12; // 
}
```
java code：
```java
size = rpcMsgSocket.receive(bb, true);
long Wcf.WxMsg wxmsg = Wcf.Response.parseFrom(bb.slice(0, (int) size)).getWxmsg();
log.info("收到消息=\n{}", wxmsg);
```

**What did you expect to see**
```
收到消息=
id: 6308366405297852584
type: 1
ts: 1701855847
content: "我很帅"
sender: "id_1111111"
sign: "8ff4459eda0e9e60ec79015fbd58be07"
xml: "<msgsource>\n\t<pua>1</pua>\n\t<signature>v1_kJkAX+8v</signature>\n\t<tmp_node>\n\t\t<publisher-id></publisher-id>\n\t</tmp_node>\n</msgsource>\n"
```
**What did you see instead?**
```
收到消息=
id: 6308366405297852584
type: 1
ts: 1701855847
content: "\346\210\221\345\276\210\345\270\205"
sender: "id_1111111"
sign: "8ff4459eda0e9e60ec79015fbd58be07"
xml: "<msgsource>\n\t<pua>1</pua>\n\t<signature>v1_kJkAX+8v</signature>\n\t<tmp_node>\n\t\t<publisher-id></publisher-id>\n\t</tmp_node>\n</msgsource>\n"
```

**Anything else we should know about your project / environment**
Look at the content attribute.
When calling the object's toString() method, if the content of the object's String type field is in Chinese, it will be directly output in octal, Inconvenient to read when debugging

**Comment by zhangskz** [comment]
I believe this is handled in escapeText(): https://github.com/protocolbuffers/protobuf/blob/adacf6d0e17bb90d37965a5901478ddce23656c6/java/core/src/main/java/com/google/protobuf/TextFormatEscaper.java#L130.

The comment here indicates that only ASCII characters between 0x20 and 0x7e are printable which is probably why you are getting this outputted in octal.
