### ISSUE TITLE
Python DeprecationWarning: uses PyType_Spec with a metaclass that has custom tp_new

### ISSUE THREAD

**Issue by sodul** [protocolbuffers/protobuf#15077]
**What version of protobuf and what language are you using?**
Version: Python protobuf 4.25.1 (latest)
Language: Python

**What operating system (Linux, Windows, ...) and version?**
macOS 14.1.2, Ubuntu 20.04 LTS.

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.12.1

**What did you do?**
Run internal code that uses protobufs.

**What did you expect to see**
No deprecation warnings.

**What did you see instead?**
```
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.
```

**Comment by FrancescElies** [comment]
I also see this with v4.25.2, I think this might be related to #12186

**Comment by googleberg** [comment]
@zhangskz Can you take a look at this?
