### ISSUE TITLE
Python: Error on packing Any "'Any' object has no attribute 'type_url'"

### ISSUE THREAD

**Issue by TechArtCorner** [protocolbuffers/protobuf#15156]
### Specs
Python protobuf module, version 4.25.1
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win3
Windows 10 Pro

### Steps to reproduce the behavior:
1. Run following code
```python
from google.protobuf.internal.well_known_types import Any
Any().Pack(message)
```
Expected behavior:
`Any` object is created and then, a message is packed into it.

`Any` reference: https://protobuf.dev/reference/python/python-generated/#any

### Actual behavior:

```
lib\site-packages\google\protobuf\internal\well_known_types.py", line 54, in Pack
    self.type_url = '%s%s' % (type_url_prefix, msg.DESCRIPTOR.full_name)
AttributeError: 'Any' object has no attribute 'type_url'
```
----
I tested it with was a simple String message declared as such:
```protobuf
message StringGrpc{
    string string = 1;
}
```
```python
Any().Pack(StringGrpc(string="test"))
```

### The bug
I believe it fails due to error in `well_known_types.py`.
Let me paste the implementation:
```python
class Any(object):
  """Class for Any Message type."""

  __slots__ = ()

  def Pack(self, msg, type_url_prefix='type.googleapis.com/',
           deterministic=None):
    """Packs the specified message into current Any message."""
    if len(type_url_prefix) < 1 or type_url_prefix[-1] != '/':
      self.type_url = '%s/%s' % (type_url_prefix, msg.DESCRIPTOR.full_name)
    else:
      self.type_url = '%s%s' % (type_url_prefix, msg.DESCRIPTOR.full_name)
    self.value = msg.SerializeToString(deterministic=deterministic)
```
The issue is that this class uses slots. It tries to access `type_url` and `value` properties in `Pack()` method but those properties are not added to slots.

Slots reference: https://wiki.python.org/moin/UsingSlots

### Workaround
The simplest workaround you can do is subclassing Any and providing slots yourself.
```
from google.protobuf.internal.well_known_types import Any


class MyOwnAny(Any):

    __slots__ = ("type_url", "value")
```

**Comment by RanveerMeel** [comment]
@TechArtCorner  I am facing the same issue. 
MacOS: 13.6
Python 3.8.16
protobuf  = 4.25.1, 4.25.0,4.24.4, 4.23.4
Tried all the above versions.
I tried with Python 3.10 also but same issue.

**Comment by RanveerMeel** [comment]
My issue is resolved. I was packing it wrong.

**Comment by TechArtCorner** [comment]
Guess I was wrong, good to hear that the module is alright.

I used different solution than using `Any` type. "Workaround" resulted in a simpler logic and cleaner code in my case so I didn't spend more time with `Any`.

Could you share a snippet of a working code?
