### ISSUE TITLE
Deserializing Modify Global Time Zone

### ISSUE THREAD

**Issue by SongTing0711** [protocolbuffers/protobuf#15188]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
1.6.0
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
Java
**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
I just used PB to serialize an object data, which was filled with a GregorianCalendar type field and set the initial 0 time zone. When I deserialized it, my time zone was changed to the time zone of the previous data.
2. private static final DefaultIdStrategy ID_STRATEGY = ((DefaultIdStrategy)[RuntimeEnv.ID](http://runtimeenv.id/)_STRATEGY);

private static <T> byte[] serialPojoByClass(T value) {
byte[] result = null;

 Class<T> clazz = (Class<T>)value.getClass();
 Schema<T> schema = RuntimeSchema.getSchema(clazz, ID_STRATEGY);
 result = ProtobufIOUtil.toByteArray(value, schema, LinkedBuffer.allocate());

 return result;
}

public static class DateTest {
private GregorianCalendar testDate;

 public void setT(GregorianCalendar testDate) {
this.testDate = testDate;
 }
}

public static <T> T deserializePojo(byte[] bytes, Class<T> clazz)
throws IllegalAccessException, InstantiationException {

if (bytes == null || bytes.length == 0) {
return null;
 }

return deserializePojo(bytes, 0, bytes.length, clazz);
}

private static <T> T deserializePojoByClass(byte[] bytes, int offset, int length, Class<T> clazz)
throws IllegalAccessException, InstantiationException {
if (clazz.isArray()) {
return null;
 }

Schema<T> schema = RuntimeSchema.getSchema(clazz, ID_STRATEGY);
 T result = clazz.newInstance();
 ProtobufIOUtil.mergeFrom(bytes, offset, length, result, schema);
 return result;
}

public static <T> T deserializePojo(byte[] bytes, int offset, int length, Class<T> clazz)
throws InstantiationException, IllegalAccessException {

if (bytes == null || bytes.length == 0) {
return null;
 }

return deserializePojoByClass(bytes, offset, length, clazz);
}

public static void main(String[] args) throws IOException, InstantiationException, IllegalAccessException {
DateTest dateTest = new DateTest();
 GregorianCalendar t = new GregorianCalendar(1, 0, 1, 0, 0, 0);
 t.setTimeZone(ZoneInfo.getTimeZone("UTC"));
 dateTest.setT(t);
 byte[] s = serialPojoByClass(dateTest);
 System.out.println("序列化前：" + TimeZone.getDefault().getID());
 deserializePojo(s, DateTest.class);
 System.out.println("序列化后：" + TimeZone.getDefault().getID());

}
3. Click on '....'
4. Scroll down to '....'
5. See error
![image](https://github.com/protocolbuffers/protobuf/assets/90837835/03a80eb7-9673-4ac2-ad42-552861da0359)

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by buchgr** [comment]
Hi @SongTing0711 , from the code you posted it looks like you using the *protostuff* package and not protobuf. While this package offers a class named `ProtobufIOUtil` this is not our code. I'd suggest it's best to file your bug with https://github.com/protostuff/protostuff.
