### ISSUE TITLE
csharp: Support for generated types name customization

### ISSUE THREAD

**Issue by ronimizy** [protocolbuffers/protobuf#15299]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**

The main problem is naming collision with types generated from proto contracts.
Most of our team's projects use hexagonal architecture with gRPC living in a presentation layer. Because we don't have dedicated domain model, we use anaemic data model with types shared between application, infrastructure and presentation (because models are just records). To avoid code duplication, we don't use separate dto's, meaning that the naming for application models and proto messages is virtually the same.

This leads to naming collision between our own types, and types that are generated from proto contracts. As gRPC projects in our applications are basically glorified mappers, this issue is pretty severe, because the only solution right now is to use using alias directives (prefix proto generated types with `Proto`) or qualifying type names with namespaces. This "hacky" solution results in messy, and sometimes hard to comprehend or even ambiguous code.

Other potential solutions are to prefix messages with `Proto` right in contract names, or postfix them with `Dto`. First is kinda verbose for contracts (if it is in .proto file, it is already clear that it is proto, right?) and it differs from conventions that are used by other teams (using other languages). Second solution is not really applicable to all projects (there are places where dto's exist), so the problem either would persist but in smaller range of services, or contracts for these services would be missing the postfix. Both solutions are not ideal and would lead to contract inconsistency.

**Describe the solution you'd like**

The ability to define patterns to names of types generated from proto messages project wide would solve the problem. It can be implemented via new attribute in .csproj's `Protobuf` tag. Parameterising just the prefix or postfix would do as well.

**Describe alternatives you've considered**

Alternative solution is to use options in proto contracts themselves (ex: `csharp_type_name_prefix`) similar to `csharp_namespace`. It is better from portability standpoint (you do not have to alter `Protobuf` tag in your csproj). But it is way worse in transferability, as you have to do it right away in contracts, which can be an issue when consuming contracts from services that do not follow this convention (ex: services written in other languages).

**Additional context**

As i do not know much about internals of C# protobuf library, i cannot judge the complexity of changes that this feature requires. But I am up for learning these internals and contributing to implementation.
Additionally, if there is a way to achieve desired result in an existing state of library, i would be glad to know about it.

**Comment by acozzette** [comment]
Sorry but I don't think this is a change we would want to accept. We tend to be extremely reluctant to add new flags if we can avoid it, since they add complexity and become a permanent maintenance cost. It seems to me like if a lot of naming conflicts are happening then some sort of namespacing is the way to go. I'm not sure I fully understand your situation but I would try disambiguating using `csharp_namespace`, or if that doesn't work (i.e. because other teams own some of the proto files) then perhaps use a different namespace for your C# models.

**Comment by ronimizy** [comment]
Sad to hear that.

There is not exact (namespace + type name) conflicts, only type name conflicts. Types were in different namespaces from the beginning, but that namespacing is exactly what leads to messy code.
