### ISSUE TITLE
--rust_out doesn't generate services

### ISSUE THREAD

**Issue by TMason11095** [protocolbuffers/protobuf#15335]
**What version of protobuf and what language are you using?**
Version: v3.25.1
Language: Rust

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc

**What did you do?**
1. Ran `protoc --proto_path=. --rust_out=experimental-codegen=enabled,kernel=cpp:. ./generic.proto`

**What did you expect to see**
Generated Rust files with service/rpc functions from the proto file.

**What did you see instead?**
Generated Rust files without service/rpc functions.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I couldn't find any documentation on if --rust_out needs the proto file to have an option to enable rpc generation, like `option java_multiple_files = true;`, or if you need to use another package to generate rpc functions, like C#.

**Comment by acozzette** [comment]
Protoc does not directly handle code generation for services; this would ordinarily be done by a protoc plugin as part of gRPC or another RPC framework. gRPC does not yet support Rust as far as I know, so unfortunately I don't know of an RPC implementation to recommend. There are some Rust gRPC implementations out there, but they're not part of the official gRPC project.
