### ISSUE TITLE
Location of proto files in protobuf-kotlin JAR changed to src directory in version 3.25

### ISSUE THREAD

**Issue by wfhartford** [protocolbuffers/protobuf#15407]
**What version of protobuf and what language are you using?**
3.25.x
Version: 3.25.x
Language: Java & Kotlin

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version

**What did you expect to see**
Location of proto files in protobuf-kotlin JARs should be consistent across versions, and with the protobuf-java JARs.

**What did you see instead?**
protobuf-kotlin JARs in versions 3.25 and later nested the proto files under a new `src` directory. This directory was not present in previous versions, or in any recent or current version of the protobuf-java JARs.

**Anything else we should know about your project / environment**
This change in JAR layout caused a build failure in my gradle project when protobuf was updated to 3.25.1. The build error was caused by declarations of the `Any` type at two different paths. I fixed the build by ensuring that these JARs are not included in the code generation phase, this complicated the build files, but probably produced a more better build.

**Comment by mkruskal-google** [comment]
@zhangskz I know you've done some recent work here, I'm not really sure how our Maven configs are setup across build/release

**Comment by berksean** [comment]
Just an additional note here. `protobuf-kotlin` expresses a dependency on `protobuf-java`, which already packages the well-know proto files.

I'm not sure what the intent is w.r.t. packaging proto + generated code, but there's some potential conflict with the files coming from multiple locations... particularly with respect to compatibility with the various protobuf gradle/maven plugins.

Is it kosher to simply delegate to the expressed `protobuf-java` dependency as the source of the proto files?

**Comment by berksean** [comment]
@mkruskal-google / @zhangskz - Sounds like someone was going to follow up on this?

**Comment by tinder-ryantrontz** [comment]
Hey folks, just wanted check in here and see if there was any follow-up or resolution. We went ahead and sort of followed @berksean's approach and stripped out `src/main/google/protobuf` from `extracted-include-protos` during the build process, and while it works fine, it does feel like the duplicate inclusion is a bug, lacking a better explanation. @mkruskal-google @zhangskz, is there any additional context you can share with us?

**Comment by jebbench** [comment]
For anyone else runing into this adding the doLast actions below to my gradle build resolved it for me.

```groovy
tasks.extractIncludeProto.doLast {
    project.delete(layout.buildDirectory.dir('extracted-include-protos/main/src'))
}
tasks.extractIncludeTestProto.doLast {
    project.delete(layout.buildDirectory.dir('extracted-include-protos/test/src'))
}
```
