### ISSUE TITLE
issue with protobuf while grpc cross compilation

### ISSUE THREAD

**Issue by udhai98** [protocolbuffers/protobuf#15420]
**What version of protobuf and what language are you using?**

Initial protobuf verison - 3.15.8 then updated protobuf version to 3.18.0 using update_version.py
these are the versions of protobuf inside grpc package.  

Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux (ubuntu - 20.04)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version and g++ version - 11.2.0

**What did you expect to see**
Need to cross compile the grpc package to arm format using petalinux environment.

**What did you see instead?**
i am getting errors from protobuf while compiling grpc package,i am attaching error logs here 
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc: In member function 'void grpc::channelz::v1::ChannelConnectivityState::SharedDtor()':
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2010:17: error: 'GetArenaForAllocation' was not declared in this scope
 2010 |   GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/third_party/protobuf/src/google/protobuf/stubs/logging.h:151:5: note: in definition of macro 'GOOGLE_LOG_IF'
  151 |   !(CONDITION) ? (void)0 : GOOGLE_LOG(LEVEL)
      |     ^~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/third_party/protobuf/src/google/protobuf/stubs/logging.h:181:48: note: in expansion of macro 'GOOGLE_CHECK'
  181 | #define GOOGLE_DCHECK(EXPRESSION) while(false) GOOGLE_CHECK(EXPRESSION)
      |                                                ^~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2010:3: note: in expansion of macro 'GOOGLE_DCHECK'
 2010 |   GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
      |   ^~~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.h: In member function 'void grpc::channelz::v1::SocketOption::unsafe_arena_set_allocated_additional(google::protobuf::Any*)':
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.h:12198:7: error: 'GetArenaForAllocation' was not declared in this scope
12198 |   if (GetArenaForAllocation() == nullptr) {
      |       ^~~~~~~~~~~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc: In member function 'virtual size_t grpc::channelz::v1::ChannelConnectivityState::ByteSizeLong() const':
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2106:10: error: 'MaybeComputeUnknownFieldsSize' was not declared in this scope
 2106 |   return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc: At global scope:
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2109:41: error: 'ClassData' in 'class google::protobuf::Message' does not name a type
 2109 | const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChannelConnectivityState::_class_data_ = {
      |                                         ^~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2113:41: error: 'ClassData' in 'class google::protobuf::Message' does not name a type
 2113 | const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChannelConnectivityState::GetClassData() const { return &_class_data_; }
      |                                         ^~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc: In member function 'void grpc::channelz::v1::ChannelConnectivityState::InternalSwap(grpc::channelz::v1::ChannelConnectivityState*)':
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2147:23: error: 'class google::protobuf::internal::InternalMetadata' has no member named 'InternalSwap'
 2147 |   _internal_metadata_.InternalSwap(&other->_internal_metadata_);
      |                       ^~~~~~~~~~~~
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc: In member function 'virtual google::protobuf::Metadata grpc::channelz::v1::ChannelConnectivityState::GetMetadata() const':
/home/myuser/arun/grpcarm2/grpc/cmake/build_arm/gens/src/proto/grpc/channelz/channelz.pb.cc:2153:7: error: cannot convert 'const google::protobuf::internal::DescriptorTable* (*)()' to 'const google::protobuf::internal::DescriptorTable*'
 2153 |       &descriptor_table_src_2fproto_2fgrpc_2fchannelz_2fchannelz_2eproto_getter, &descriptor_table_src_2fproto_2fgrpc_2fchannelz_2fchannelz_2eproto_once,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       |
      |       const google::protobuf::internal::DescriptorTable* (*)()

**Anything else we should know about your project / environment**

      petalinux environment

**Comment by acozzette** [comment]
This looks like a mismatch between the protoc version used to generate code and the protobuf library headers you're building against. It's important to make sure that these are the exact same version.

**Comment by googleberg** [comment]
@udhai98 
Protobuf versions 3.15 and 3.18 are out of our support window.

Here are the instructions for installing the latest protobuf version for C++:
https://github.com/protocolbuffers/protobuf/blob/main/src/README.md

As Adam mentioned, it is very important for C++ that you use `protoc` and the Protobuf C++ runtime library from the same release.
