### ISSUE TITLE
Bug：Special characters failed to be escaped using protobuf

### ISSUE THREAD

**Issue by wizard2318** [protocolbuffers/protobuf#15447]
**What version of protobuf and what language are you using?**
Version:  v1.31.0
Language:goland

**What operating system (Linux, Windows, ...) and version?**
Windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version
**What did you do?**
1.Fields in openstack (for example, OS-DCF:diskConfig) cannot be defined using protobuf, and then escape fails；
2.Then escaping with [(json_name)] fails

**What did you expect to see**
Special characters can be escaped with the [(json name)] option

**What did you see instead?**
    string OS_DCF_diskConfig = 14[json_name = "OS-DCF:diskConfig"];

**Anything else we should know about your project / environment**

**Comment by buchgr** [comment]
Hi @wizard2318, can you please share a minimal reproducer that we can run to verify and understand the problem better?
