### ISSUE TITLE
protobuf to json field and binary value unexcepted

### ISSUE THREAD

**Issue by haegThe** [protocolbuffers/protobuf#15458]
**What version of protobuf and what language are you using?**
Version: main/v3.19.0/v3.22.2 etc.
Language: Java

**What operating system (Linux, Windows, ...) and version?**
windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
idea
**What did you do?**
1. use `JsonFormat.printer().print(data)` convert protobuf to json
2. one field is string type,  when value contains char '=', json is \u003d.
for example:  fied value is "ns=100;s=DEVICE_NAME", but to json is "ns\u003d100;s\u003dDEVICE_NAME"
4. one field is bytestype,  when convert to json, the value is not excepted.
for example:  fied value is "QPJ", but to json is "UVBK"
some code like:
```
message Field {
    string name = 1;
    oneof Value {
        double float_value = 2;
        int64 int_value = 3;
        bool bool_value = 4;
        bytes binary_value = 5;
        Ints int_values = 6;
        Floats float_values = 7;
    }
}
```
```
fieldBuilder.setName("ns=100;s=DEVICE_NAME").setBinaryValue(ByteString.copyFrom("QPJ".getBytes(StandardCharsets.UTF_8)));
```
json output:
```
"fields":[{"name":"ns\u003d100;s\u003dDEVICE_NAME","binaryValue":"UVBK"}]
```

**What did you expect to see**
two question:
1. why character '=' to json is '\u003d' ?
2. I know binary value may not readable, but json is for read, how to convert binary value to readable string as above "QPJ" set to protobuf and out to json is always "QPJ"?

**Comment by buchgr** [comment]
> why character '=' to json is '\u003d' ?

I believe this is because all html characters are escaped in the JSON format. You can read more about it here: https://groups.google.com/g/google-gson/c/JDHUo9DWyyM

> I know binary value may not readable, but json is for read, how to convert binary value to readable string as above "QPJ" set to protobuf and out to json is always "QPJ"?

In JSON format binary values are encoded with base64. You'll either need to use a string type instead of bytes or base64 decode your bytes.
