### ISSUE TITLE
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.

### ISSUE THREAD

**Issue by yangyile1990** [protocolbuffers/protobuf#15452]
my proto file define is this:
```
import "google/api/annotations.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
```

in my ubuntu computer the result is:
```
import (
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.

while in my macbook computer the result is:
```
import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)
```
it is ok.

So what is the most likely reason in my ubuntu?

I have  run the command:
```
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
```

my protoc is download from https://github.com/protocolbuffers/protobuf/releases/tag/v25.2
protoc-25.2-linux-x86_64.zip

so I think maybe the reason is the ubuntu download from the:
https://github.com/protocolbuffers/protobuf/releases
protoc-25.2-linux-x86_64.zip

may be not same with the macbook `brew install protobuf`.

I don't know the reason.

**Comment by zhangskz** [comment]
Looks like your problem is likely with the

```
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
```
lines.

Closing since I think this should be filed with the go protobuf repo: https://pkg.go.dev/google.golang.org/protobuf#section-readme for additional support with go protobuf. Please reopen if you have additional questions here about protoc, etc.

**Comment by yangyile1990** [comment]
Thank you! @zhangskz 

I try my best to find the reason is that. 
I copy the file to my local project:
```
third_party/google/protobuf/duration.proto
third_party/google/protobuf/timestamp.proto
```
while the code of them is old version. because I copy them before 1 year ago. maybe 2 years ago. so the proto file is old version. which says the option go_package = "github.com/golang/protobuf/ptypes/duration";

I don't know why I must copy the proto into the third_party directory. but the reason is that.

so after I update the proto file it is ok.
