### ISSUE TITLE
Confusion around packed enum fields

### ISSUE THREAD

**Issue by rcorre** [protocolbuffers/protobuf#15480]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Write the following proto:
```
syntax = "proto3";

enum Foo {
    FOO_UNSPECIFIED = 0;
}

message Bar {
    repeated Foo foo = 1 [packed=true];
}
```
2. Compile with `protoc`, see no errors

**What did you expect to see**

```
 [packed = true] can only be specified for repeated primitive fields.
```

**What did you see instead?**

Successful compilation.

I suspect this is just a documentation bug. The [section](https://protobuf.dev/programming-guides/encoding/#packed) on packed fields says:

> repeated fields of a primitive type (any scalar type that is not string or bytes) can be declared as “packed”

The [scalar types](https://protobuf.dev/programming-guides/proto2/#scalar) link takes you to a table that does _not_ include enums.
I suppose enums can be packed because they use varint as their wire type, but this was unclear to me from the docs.

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
Looks like our IsTypePackable() indeed treats enums as as packable: https://github.com/protocolbuffers/protobuf/blob/adacf6d0e17bb90d37965a5901478ddce23656c6/src/google/protobuf/descriptor.h#L2774

We should update this documentation to clarify this accordingly.

**Comment by rcorre** [comment]
I think the docs still need to be updated. I'd submit a patch but I'm not sure where the source is.

**Comment by Logofile** [comment]
Thanks for the comment to keep this open.

**Comment by rcorre** [comment]
This is still relevant. Is the source for the docs available anywhere?

**Comment by Logofile** [comment]
Source for the docs is available at https://github.com/protocolbuffers/protocolbuffers.github.io
