### ISSUE TITLE
[Python] Import error cannot import name 'python_edition_defaults' from 'google.protobuf.internal' 

### ISSUE THREAD

**Issue by parthea** [protocolbuffers/protobuf#15486]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Protobuf at HEAD
Python

**What operating system (Linux, Windows, ...) and version?**

Debian GNU/Linux rodete
Debian 6.5.13-1rodete1

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.9.16
GCC 12.2.0

**What did you do?**

1. Install protobuf at HEAD using `pip install -e "git+https://github.com/protocolbuffers/protobuf@main#egg=protobuf&subdirectory=python"`
2. In python terminal, run `from google.protobuf import descriptor_pool` 

**What did you expect to see**

I expected the import statement `from google.protobuf import descriptor_pool` to succeed

**What did you see instead?**

I received an ImportError
```
ImportError: cannot import name 'python_edition_defaults' from 'google.protobuf.internal' 
```

```
>>> from google.protobuf import descriptor_pool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/google/protobuf/descriptor_pool.py", line 44, in <module>
    from google.protobuf.internal import python_edition_defaults
ImportError: cannot import name 'python_edition_defaults' from 'google.protobuf.internal' (/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/google/protobuf/internal/__init__.py)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I see that there is a file `python_edition_defaults.py.template` instead of `python_edition_defaults.py` which could be the cause of the error
https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/python_edition_defaults.py.template

**Comment by mkruskal-google** [comment]
Has this pip workflow ever worked for you?  AFAIK the pip command simply installs a directory verbatim.  I was able to reproduce this with a local directory, but considering descriptor_pb2.py is a generated file we don't check in anyway, even if `python_edition_defaults.py` existed you'd run into issues quickly the second you tried to *use* protos.

The root problem here is that `python_edition_defaults.py`, `descriptor_pb2.py`, and the gencode for all the well-known types are all generated files.  Bazel will automatically generate them, and they get shipped in our releases.  But trying to import the source tree is going to hit issues unless we also check them into github

**Comment by parthea** [comment]
Thanks @mkruskal-google! My mistake. I'll try building the package with Bazel as recommended in the docs: https://github.com/protocolbuffers/protobuf/tree/main/python#building-packages-from-this-repo
