### ISSUE TITLE
Protobuf compiler version 3.12.4 doesn't match library version 4.25.0

### ISSUE THREAD

**Issue by Lukas-Kozel** [protocolbuffers/protobuf#15521]
Hello,
I would like to ask for help. I have installed protobuf via command: _sudo apt install libprotobuf-dev protobuf-compiler_ (i am using Ubuntu).
When I use _protoc --version_ I get: libprotoc 25.0. I am trying to compile my Qt app in C++ where I am using gRPC so my Cmake looks like this: 
`cmake_minimum_required(VERSION 3.5)

set(RPC_DIR "../../RPC")

set(Protobuf_PROTOC_EXECUTABLE /usr/bin/protoc)

find_package(Protobuf REQUIRED)
find_package(gRPC REQUIRED)

include_directories(${RPC_DIR})

add_executable(
    ${RPC_DIR}/service.pb.cc 
    ${RPC_DIR}/service.grpc.pb.cc 
)

target_link_libraries(
  gRPC::grpc++
  gRPC::grpc++_reflection
  protobuf::libprotobuf
)
`
I have found out that I have there installed version 3.12.4 and I am getting this error: 
CMake Warning at /home/luky/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version 3.12.4 doesn't match library version 4.25.0
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)

What version of compiler do I need? And how can I install this specific version of compiler?

Thank you very much.

**Comment by googleberg** [comment]
Hi @Lukas-Kozel,

Unfortunately, the version of protobuf in the ubuntu repository is quite out of date and we do not maintain that. To install `protoc` please follow these instructions:
https://github.com/protocolbuffers/protobuf/blob/main/src/README.md
