### ISSUE TITLE
[Java] Changing behavior when loading a java proto with Gson

### ISSUE THREAD

**Issue by jorgerod** [protocolbuffers/protobuf#15542]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
Prior to version **v.24.0**, we populated the objects generated with protobuf-java with the **Gson** library by reading from a json file.

```java
syntax = "proto3";

package mypackage;

import "google/protobuf/wrappers.proto";

option java_outer_classname = "ItemProto";

message Item {

    google.protobuf.StringValue code = 1;

    google.protobuf.StringValue ref = 2;
}
```

```java
    final Item item = new Gson().fromJson(fileText, Item.class);

    Assertions.assertThat(item.getRef()).isNotNull();
    Assertions.assertThat(item.hasRef()).isTrue(); //prior v.24.0 works,  v.24.0 or higher, fails
```

Subsequently, we did a has{_MyField_} and it returned true.

As of 3.24.0, when doing the has{_MyField_}, it returns false but if a get{MyField} is done the field has value.

This is because the _bitField0__ is not updated. 

Is there any way to populate an object from a json/string...?

**Describe the solution you'd like**

Could we add a method that recomputes that _bitField0__?

**Describe alternatives you've considered**

**Additional context**

**Comment by buchgr** [comment]
@jorgerod hi there, sorry about your issue. I'd love your input on triaging this bug.

- Does Gson officially support populating generated classes from Protobuf?
- How did you decide to file this bug with Protobuf rather than Gson?

thanks!

**Comment by juliojgd** [comment]
Hello @buchgr I think the code snippet provided by @jorgerod includes Gson only as an example of a library that creates protobuf objects without the builder (via reflection I guess). So it's not about Gson specifically but about any library or mechanism that creates objects without the builder (that I guess there are several of them when deserializing from a file)

In these cases, it would be useful keep the already working behavior, and this could be done by adding a method like "reComputeBitFields" or "reHashBitFields" (name to be defined but you understand the semantics) to invoke it after this (let's call them) weird object creation process.

But, for sure @jorgerod can confirm if I'm right about he wanted to explain 😄

**Comment by juliojgd** [comment]
Thanks in advance @buchgr and @deannagarcia ; the main point here is that prior to v24.0 it worked flawlessly; I am sure that the change made in the version is for the best, but having a way to not break existing use cases would be great (e.g. the "recompute" methods or sth like that)

**Comment by googleberg** [comment]
@jorgerod @juliojgd 
I'm sorry that this has stopped working, but GSON's default mode of operation is hostile to changes of generated protobuf classes and is not supported. GSON effectively turns private implementation details into public json fields. For example: `bitField0_` is an internal field for tracking field presence and should never be directly read or manipulated outside of the generated message class.

If you must convert proto messages to JSON, the protobuf team recommends using protobuf JsonFormat:
https://github.com/protocolbuffers/protobuf/blob/main/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java

If you must continue to use GSON we suggest trying the proto adapter distributed with GSON:
https://github.com/google/gson/blob/main/proto/src/main/java/com/google/gson/protobuf/ProtoTypeAdapter.java
