### ISSUE TITLE
Protobuf Isse

### ISSUE THREAD

**Issue by elibutller** [protocolbuffers/protobuf#15563]
I have protobuf in my request i want to bypass to in readable form or json but i did not have .proto file where its defination define is it possible without proto file?

**Comment by buchgr** [comment]
I believe `protoc --decode_raw` is what you are looking for. See https://stackoverflow.com/questions/7343867/raw-decoder-for-protobufs-format for more details.

**Comment by elibutller** [comment]
Thank you for your answer but I already test that its give me every time failed to parse input msg
