### ISSUE TITLE
Enums for Protobuf PHP?

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#15567]
PHP 8.1 brought us [Enumerations](https://www.php.net/manual/en/language.enumerations.php), which are absolutely perfect for use in Protobuf. Specifically, backed Enumerations would bring us exactly what we want:

```php
enum Status: int
{
    case STATUS_UNDEFINED = 0;
    case ACTIVE = 1;
    case INACTIVE = 2;
}
```

Now that this library supports a minimum of PHP 8.1, would the protobuf team entertain a change like this? We would want to put it behind an option, so as to prevent breaking changes.

**Comment by buchgr** [comment]
@haberman do you have any thoughts on this?

**Comment by haberman** [comment]
Brent, we'd love to take advantage of the new PHP feature. We'd have to stage the change to allow for a migration, possibly using editions: https://protobuf.dev/editions/overview/

If you could write a proposal for this, we could review it and review a PR to implement it.

**Comment by antonkomarev** [comment]
@haberman any progress on it? It will be very helpful, because 8.0 is widely adopted and we will have much better DX. What we need to do to push it forward? Is there example of proposal which is required?

**Comment by bshaffer** [comment]
I'd love to look at doing this for a major protobuf release! Although maintaining compatibility would be tricky, and may require an additional protobuf flag.
