### ISSUE TITLE
gem google-protobuf fails compilation. fix already available.

### ISSUE THREAD

**Issue by bschwand** [protocolbuffers/protobuf#15585]
Describe the problem as clearly as you can
attempting to install gem google-protobuf fails compilation. This is on cygwin clean installed with the latest cygwin installer, adding ruby 3.2 and ruby-gems. Then run the gem install command.

The issue appears to already be fixed in this commit
https://github.com/protocolbuffers/protobuf/commit/75455eae6c5cfc8eccfcf04e6a80e3f0485f8b1e
however it is not included in the current 3.25.2 google-protobuf gem.

Did you try upgrading RubyGems?
already using latest available in cygwin

Post steps to reproduce the problem
install cygwin, select ruby and ruby-gems. bring up a cygwin prompt, run gem install google-protobuf

Which command did you run?
gem install google-protobuf

What were you expecting to happen?
sucessfull install of gem google-protobuf

What actually happened?
Building native extensions. This could take a while...
ERROR: Error installing google-protobuf:
ERROR: Failed to build gem native extension.

current directory: /home/bruno/.local/share/gem/ruby/3.2.0/gems/google-protobuf-3.25.2/ext/google/protobuf_c
/usr/bin/ruby.exe -I/usr/share/rubygems extconf.rb
creating Makefile

current directory: /home/bruno/.local/share/gem/ruby/3.2.0/gems/google-protobuf-3.25.2/ext/google/protobuf_c
make DESTDIR= sitearchdir=./.gem.20240124-1841-iprlql sitelibdir=./.gem.20240124-1841-iprlql clean

current directory: /home/bruno/.local/share/gem/ruby/3.2.0/gems/google-protobuf-3.25.2/ext/google/protobuf_c
make DESTDIR= sitearchdir=./.gem.20240124-1841-iprlql sitelibdir=./.gem.20240124-1841-iprlql
compiling protobuf.c
compiling convert.c
convert.c: In function ‘Msgval_IsEqual’:
convert.c:295:58: warning: passing argument 4 of ‘shared_Msgval_IsEqual’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
295 | type_info.def.msgdef, &status);
| ~~~~~~~~~~~~~^~~~~~~
In file included from convert.c:21:
shared_convert.h:19:60: note: expected ‘upb_MessageDef *’ but argument is of type ‘const upb_MessageDef ’
19 | upb_CType type, upb_MessageDef msgdef,
| ~~~~~~~~~~~~~~~~^~~~~~
convert.c:299:5: error: format not a string literal and no format arguments [-Werror=format-security]
299 | rb_raise(rb_eRuntimeError, upb_Status_ErrorMessage(&status));
| ^~~~~~~~
convert.c: In function ‘Msgval_GetHash’:
convert.c:308:41: warning: passing argument 3 of ‘shared_Msgval_GetHash’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
308 | val, type_info.type, type_info.def.msgdef, seed, &status);
| ~~~~~~~~~~~~~^~~~~~~
In file included from convert.c:21:
shared_convert.h:23:48: note: expected ‘upb_MessageDef *’ but argument is of type ‘const upb_MessageDef ’
23 | upb_MessageDef msgdef, uint64_t seed,
| ~~~~~~~~~~~~~~~~^~~~~~
convert.c:312:5: error: format not a string literal and no format arguments [-Werror=format-security]
312 | rb_raise(rb_eRuntimeError, upb_Status_ErrorMessage(&status));
| ^~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:249: convert.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/bruno/.local/share/gem/ruby/3.2.0/gems/google-protobuf-3.25.2 for inspection.
Results logged to /home/bruno/.local/share/gem/ruby/3.2.0/extensions/x86_64-cygwin/3.2.0/google-protobuf-3.25.2/gem_make.out

Run gem env and paste the output below
$ gem env
RubyGems Environment:

RUBYGEMS VERSION: 3.4.12
RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [x86_64-cygwin]
INSTALLATION DIRECTORY: /usr/share/gems
USER INSTALLATION DIRECTORY: /home/bruno/.local/share/gem/ruby/3.2.0
RUBY EXECUTABLE: /usr/bin/ruby.exe
GIT EXECUTABLE: /cygdrive/c/Program Files/Git/cmd/git.EXE
EXECUTABLE DIRECTORY: /usr/bin
SPEC CACHE DIRECTORY: /home/bruno/.local/share/gem/specs
SYSTEM CONFIGURATION DIRECTORY: /etc
RUBYGEMS PLATFORMS:
ruby
x86_64-cygwin
GEM PATHS:
/usr/share/gems
/home/bruno/.local/share/gem/ruby/3.2.0
/usr/local/share/gems
GEM CONFIGURATION:
:update_sources => true
:verbose => true
:backtrace => true
:bulk_threshold => 1000
"gem" => "--user-install --bindir /home/bruno/bin"
REMOTE SOURCES:
https://rubygems.org/
SHELL PATH:
/usr/local/bin
/usr/bin
/cygdrive/c/Program Files/Common Files/Oracle/Java/javapath
/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath
/cygdrive/c/Python39/Scripts
/cygdrive/c/Python39
/cygdrive/c/Program Files (x86)/STMicroelectronics/st_toolset/asm
/cygdrive/c/ProgramData/Oracle/Java/javapath
/cygdrive/c/WINDOWS/system32
/cygdrive/c/WINDOWS
/cygdrive/c/WINDOWS/System32/Wbem
/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0
/cygdrive/c/Program Files/Perforce
/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn
/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0
/cygdrive/c/Program Files (x86)/Skype/Phone
/cygdrive/c/Program Files (x86)/CMake/bin
/cygdrive/c/Program Files/Git/cmd
/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/cygdrive/c/Program Files/PuTTY
/cygdrive/c/ProgramData/chocolatey/bin
/cygdrive/c/Program Files/nodejs
%JAVA_HOME/bin
/cygdrive/c/Program Files/dotnet
/cygdrive/c/Program Files/VSCodium/bin
/cygdrive/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
/cygdrive/c/Program Files/Graphviz/bin
/cygdrive/c/Program Files/gs/gs10.02.1/bin
/cygdrive/c/Program Files/Calibre2
/cygdrive/c/Users/bruno/AppData/Roaming/npm
/cygdrive/c/Users/bruno/AppData/Roaming/npm
/cygdrive/c/Python39/Scripts
/cygdrive/c/Python39
/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath
/cygdrive/c/Program Files (x86)/STMicroelectronics/st_toolset/asm
/cygdrive/c/ProgramData/Oracle/Java/javapath
/cygdrive/c/WINDOWS/system32
/cygdrive/c/WINDOWS
/cygdrive/c/WINDOWS/System32/Wbem
/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0
/cygdrive/c/Program Files/Perforce
/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn
/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0
/cygdrive/c/Program Files (x86)/Skype/Phone
/cygdrive/c/Program Files (x86)/CMake/bin
/cygdrive/c/Program Files/Git/cmd
/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/cygdrive/c/Program Files/PuTTY
/cygdrive/c/Program Files/Calibre2
/cygdrive/c/ProgramData/chocolatey/bin
/cygdrive/c/Program Files/nodejs
/cygdrive/c/Program Files (x86)/Nmap
/cygdrive/c/Users/bruno/.platformio/penv/Scripts
/cygdrive/c/perso/savedfromdellVostro/cygwin/bruno/android/platform-tools
/cygdrive/c/perso/savedfromdellVostro/cygwin/bruno/android/allwinnerTools/PhoenixSuit_V1.10
/home/bruno/bin
/home/bruno/bin

**Comment by buchgr** [comment]
Hi @bschwand, sorry about your issue. The commit that you are referencing has not yet been released. See https://github.com/protocolbuffers/protobuf/commits/v25.2/ for commits that are part of the 25.2 release.

To unblock yourself and given that you are already building from source, you could try to build the gem from the main branch until there is a new release.

I am marking this issue as closed because I believe there is nothing for us to act on at this moment.

Please leave a comment and re-open this bug if you believe this is a mistake.

**Comment by bschwand** [comment]
ok I am sorry I am rather new to the ruby/gem stuff and I don't seem to figure how to force the gem utility to use the main brain instead of a known version number... any pointers ? thanks a lot.
