### ISSUE TITLE
PHP: Segmentation fault

### ISSUE THREAD

**Issue by gnumoksha** [protocolbuffers/protobuf#15599]
**What version of protobuf and what language are you using?**
Version: [3.25.2](https://pecl.php.net/package/protobuf/3.25.2)
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Debian bookworm under Docker

**What runtime / compiler are you using (e.g., python version or gcc version)**
```console
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**What did you do?**
This is complicated because I see the segmentation fault when my unit test suite runs. I was not able to isolate the issue.

**What did you expect to see**
My test suite to pass.

**What did you see instead?**
My test suite stops and then I see the message "Segmentation fault (core dumped)"

**Anything else we should know about your project / environment**
I have the dumped `core` file.

**Comment by buchgr** [comment]
Hi @gnumoksha, for us to take a further look please provide a minimal reproducer fro the problem you have.
