### ISSUE TITLE
protobuf version incompatibilities

### ISSUE THREAD

**Issue by Lukas-Kozel** [protocolbuffers/protobuf#15618]
**What version of protobuf and what language are you using?**
Version: 3.12.4 and 25.2
Language: C++/Python

**What operating system (Linux, Windows, ...) and version?**
Linux ubuntu 

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 

**What did you do?**
build any project via cmake with protobuf used

**What did you expect to see**
correct build 

**What did you see instead?**
I am trying to build app px4-autopilot, but the core output is the same with every cmake app I try to build.
*- Could NOT find gz-transport (missing: gz-transport_DIR)
-- Looking for gz-transport12 -- found version 12.2.1
-- Searching for dependencies of gz-transport12
CMake Warning at /home/luky/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version 3.12.4 doesn't match library version 4.25.0
Call Stack (most recent call first):
  /usr/share/cmake/gz-cmake3/cmake3/FindGzProtobuf.cmake:34 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gz-transport12/gz-transport12-config.cmake:92 (find_package)
  src/modules/simulation/gz_bridge/CMakeLists.txt:40 (find_package)*
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by googleberg** [comment]
Hi @Lukas-Kozel 
Version 3.12.4 is out of support window.

Please follow the C++ installation instructions to get the latest version:
https://github.com/protocolbuffers/protobuf/blob/main/src/README.md
