### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by hanzhi0410** [protocolbuffers/protobuf#15621]
I encountered the following issues while compiling my program
/usr/include/ignition/msgs5/ignition/msgs/color.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
/usr/include/ignition/msgs5/ignition/msgs/color.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers.  Please
      |  ^~~~~
/usr/include/ignition/msgs5/ignition/msgs/color.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
In file included from /usr/include/gazebo-11/gazebo/msgs/msgs.hh:32,
                 from /home/hn/test/src/unitree_ros/unitree_gazebo/plugin/draw_force_plugin.cc:8:

Looking forward to your help

**Comment by zhangskz** [comment]
Assuming this is for the v26.0-rc1 release, this should be due to poison pilling mechanisms we introduced to enforce our cross-version runtime guarantees which disallows mixing generated code and runtimes across major version boundaries: https://protobuf.dev/news/2023-12-05/#poison-pilling-gencode--runtime-mismatches.

If /usr/include/ignition/msgs5/ignition/msgs/color.pb.h is old checked-in generated code, please regenerate this generated code using a newer version of protoc, as indicated in the error message.

**Comment by shaod2** [comment]
This looks like an older version of protoc than 26.x. But note that we require exact match of versions for Protobuf C++. Make sure you follow our [C++ cross-version guarantees](https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp)

**Comment by hanzhi0410** [comment]
Thank you very much for your reply. The code I am using should have been generated using protoc2.6.1. My gazebo11 software requires protoc3.6.1, so I have installed both versions of protobuf and added INCLUDE to the CMakeList file_ DICTORIES (/my_path/include/)
LINK_ DICTORIES (/my_path/lib/)
The content has passed the compilation. But when running the code, a warning is displayed as follows
This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.5.1). Contact the program author for an update If you have compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link time library (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj x86_64 Linux gnu/src/protobuf/mir_protobuf. pc".)
Aborted (core dumped)
May I ask if you have a good solution

**Comment by hanzhi0410** [comment]
Thank you very much for your reply. The code I am using should have been generated using protoc2.6.1. My gazebo11 software requires protoc3.6.1, so I have installed both versions of protobuf and added INCLUDE to the CMakeList file_ DICTORIES (/my_path/include/)
LINK_ DICTORIES (/my_path/lib/)
The content has passed the compilation
