### ISSUE TITLE
Why version 4.26.0RC1

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#15620]
Can you explain the big version bump from **3.25.2** to **4.26.0RC1** ?

Should it be 3.26.0RC1 ?

If a major API change, should it be 4.0.0 ?
(btw, 4.0.0RC2 was released in 2020 but no new GA version)

Notice 
- pecl version 3.25.2 was build from **tag = 25.2**
- pecl version 4.26.0RC1 was build from **tag = 26.0-rc1**

**Comment by zhangskz** [comment]
v26.x release bumps the major version for PHP for breaking changes were announced in [News](https://engdoc.corp.google.com/eng/doc/devguide/proto/news/2023-12-27.md?cl=head) and [the release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0-rc1.

This follows our versioning scheme per https://protobuf.dev/support/version-support/. Note the prior 2020 4.0.0RC2 is unrelated and was prior to our changed versioning scheme.

**Comment by remicollet** [comment]
@zhangskz News link is not authorized :p

**Comment by zhangskz** [comment]
Updated to [the correct news link](https://protobuf.dev/news/2023-12-27/)!
