### ISSUE TITLE
computeMessageNoTagSize nullPointException

### ISSUE THREAD

**Issue by aoMao** [protocolbuffers/protobuf#15624]
**What version of protobuf and what language are you using?**
Version: 3.20.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
when we use toByteArray, NullPointException maybe heppened, but we checked all the repeated message and message, it can't be null, so does some one haved this problem??

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by googleberg** [comment]
Version 3.20 is no longer supported. Please try updating to the latest version.
