### ISSUE TITLE
No _message.py in google.protobuf.pyext package.

### ISSUE THREAD

**Issue by przna** [protocolbuffers/protobuf#15643]
Installed: protobuf==4.25.2
Installled in Mac M2

_message.py file is not present in the protobuf, which is also referenced in google.protobuf.pyext.cpp_message. This is causing an error.

**Comment by haberman** [comment]
Could you be more specific about what you tried (including code) and what error message you received?

**Comment by satista** [comment]
I have the same issue - pyext is raising an attribute error. 
I am trying to get the RepeatedScalarContainer class which is in the _message.py file part of pyext module but the pyext module does not exist in python 3.10 but is there in 3.8

I am using python 3.10.13
Protobuf version 3.19.0 seems to be an issue when I use later versions of python beyond 3.8.

**Comment by haberman** [comment]
It sounds like you are trying to reference symbols like `google.protobuf.pyext._message.RepeatedScalarContainer`.

Modules with names that begin in underscores, like `_message`, are private to the implementation. They are not part of the public API, and therefore can break at any time.

Our `RepeatedScalarContainer` type implements the `collections.abc.MutableSequence` interface. If you are looking for a public type to reference, you should use `MutableSequence` instead.
