### ISSUE TITLE
Should not produce empty byte array in case of default value is set

### ISSUE THREAD

**Issue by anaconda875** [protocolbuffers/protobuf#15678]
**What language does this apply to?**
protoc: 3.25
maven dependency: com.google.protobuf;version="3.24.3"
jdk: 17

I have a simple proto like this (I cannot edit this file, please don't ask why):

```
syntax = "proto3";
package abc;
message Status {

  StatusCodeType statusCode = 1;

  enum StatusCodeType {
    SUCCESS = 0;
    ERROR = 1;
  }
}
```

I use a maven plugin to compile it to java class:

    <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>${protobuf.maven.plugin.version}</version>
        <configuration>
            <protoSourceRoot>${project.basedir}/src/main/resources/protobuf</protoSourceRoot>
            <protocExecutable>protoc</protocExecutable>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>compile</goal>
                    <goal>test-compile</goal>
                </goals>
            </execution>
        </executions>
    </plugin

When I tried to serialize the Status object that have the StatusCodeType.SUCCESS, I received empty byte array:
```

  public static void main(String[] args) {
    StatusOuterClass.Status s = StatusOuterClass.Status.newBuilder()
            .setStatusCode(StatusOuterClass.Status.StatusCodeType.SUCCESS)
            .build();
    System.out.println(s.toByteArray().length);  //PRINT 0
  }
```

I dig into the generated code and I find this logic:

```
@java.lang.Override
public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
  if (statusCode_ != abc.StatusOuterClass.Status.StatusCodeType.SUCCESS.getNumber()) {
    output.writeEnum(1, statusCode_);
  }
  getUnknownFields().writeTo(output);
}
```

Can see that it will only write to the byte array if statusCode_ != abc.StatusOuterClass.Status.StatusCodeType.SUCCESS.getNumber()

I think it is a feature of protobuf to optimize payload size, but it cause a problem in my project. If I invoke an API written by Spring boot and send this empty byte array as payload, then the controller will reject as 400 bad request.

Of course I can edit the controller method and make the payload optional, but it is not the proper way. For ex, how can we know whether client send success payload or didn't send anything (because in both case, the payload is null)?

So my request is:  **produce a valuable byte array in any case.**

PS: I have contacted with some python/C++ guys and they said that their code will produce an array of {8, 0} instead of empty. How is it possible?

**Comment by googleberg** [comment]
@anaconda875 
Your friends may be using `syntax = "proto2";` or they may be using proto3 + optional fields.

If you specify your field as optional (in proto2 or proto3), even the default 0 value will get serialized:
```
syntax = "proto3";
package abc;
message Status {

  optional StatusCodeType statusCode = 1;

  enum StatusCodeType {
    SUCCESS = 0;
    ERROR = 1;
  }
}
```

*Best Practices Note:* If you want to stick with "implicit" presence, which is the default in proto3, we recommend that you use the 0 enum value for a placeholder value named `STATUS_CODE_UNSPECIFIED`.

To learn more about field presence read here:
https://protobuf.dev/programming-guides/proto3/#field-labels
