### ISSUE TITLE
Support for Half floating point type.

### ISSUE THREAD

**Issue by vpenades** [protocolbuffers/protobuf#15720]
**What language does this apply to?**
proto3+

**Describe the problem you are trying to solve.**

Right now, Protobuf supports both Single (32bit) and Double (64bit) floating point data types.

As far as I know, there's no support for Half (16bit) floating point data type. This I would like to request to support it.

**Describe the solution you'd like**

To have Half floating point support natively, at the same level as the rest of the data types.

**Describe alternatives you've considered**

The only way I can figure out right now is to cast the data to bytes, or shorts.

**Additional context**

Given that TensorFlow supports different ways of saving weights, I was wondering how it stores FP16...

**Comment by googleberg** [comment]
@vpenades 
Unfortunately, it is very difficult to add a new type to the protobuf wire format and none of the existing types lend themselves to `float16`:
https://protobuf.dev/programming-guides/encoding/#structure

While there are some unused type specifiers, it is considered nearly completely infeasible to use those to add a new field type. There would have to be a tremendous business case for the effort.

Until that business case comes along, we recommend packing your `float16` values into a bytes field.
