### ISSUE TITLE
Which Protobuf version is compatible with grpc latest version

### ISSUE THREAD

**Issue by RSowndarya** [protocolbuffers/protobuf#15742]
hi,

i'm using grpc 1.58.0 version and protobuf 3.11.0.
While cross compiling observed below error:

CMake Error at cmake/protobuf.cmake:58 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:332 (include)

It will be helpful, if any inputs given on this issue

**Comment by jinmeiib** [comment]
protobuf 3.24.4 worked for me to build grpc 1.59.2. You'll likely need to use protobuf that can be built using cmake to avoid the errors you saw. I've not checked 3.11.0, but it's quite old so I suspect it dosn't use cmake.
