### ISSUE TITLE
oneof issue in protobuf

### ISSUE THREAD

**Issue by jeena1030** [protocolbuffers/protobuf#15777]
Hi I have requirement in that my data is an array which is having json objects and each object contains id, area, value and this value variable can have int, float, int array, float array, string data types. I have defined in the .proto file as 

message Data {
    int64 id = 1;
   oneof value {
        int32 int_value = 2;
        double double_value = 3;
        string string_value = 4;
        repeated int32 int_array_value = 5;
        repeated double double_array_value = 6;
    }
    int32 area = 7;

}

but protoc is complains that it cannot have repeated in one of what is the alternative for this.

**Comment by googleberg** [comment]
@jeena1030 
`oneof` is not allowed to contain a `repeated` field.

The most common solution is to make a wrapper message for your repeated field.

In this case with these generic field names:
```
message Int32List {
  repeated int32 value = 1;
}
message DoubleList {
  repeated double value = 1;
}
message Data {
  int64 id = 1;
  oneof value {
    int32 int_value = 2;
    double double_value = 3;
    string string_value = 4;
    Int32List int32 int_array_value = 5;
    DoubleList repeated double double_array_value = 6;
  }
  int32 area = 7;
}
```

Note that it is tempting to create a generic list wrapper type for the primitive values like `Int32List` and reuse it in multiple situations. That can lead to confusion about the sensitivity of data in fields using that list type. In general, I would recommend creating list wrapper messages with *specific* names and documentation for the data contained there.

Creating wrapper messages like this is a pattern that can also be used if you need to detect that a repeated field is "present and empty" or "not present at all" which cannot be distinguished in the direct repeated field case.
