### ISSUE TITLE
protobuf does not build with Bazel when using rules_pkg >= 0.10.0

### ISSUE THREAD

**Issue by aiuto** [protocolbuffers/protobuf#15779]
protobuf depends on a deprecated file `@rules_pkg://mappings.bz`l.  It was removed in version 0.10.0 as part of addressing https://github.com/bazelbuild/rules_pkg/issues/562.

The fix is to change the ~34 instances of it's use from
```
load("@rules_pkg//:mappings.bzl", ...)
```
to
```
load("@rules_pkg//pkg:mappings.bzl", ...)
```

If you'll take the patch, I will be happy to work on it.

**What version of protobuf and what language are you using?**
Version: Head
Language: N/A

**What operating system (Linux, Windows, ...) and version?** N/A

**What runtime / compiler are you using (e.g., python version or gcc version)** N/A

**What did you do?**
Try to build a Bazel project that uses protobuf, without having previously pinned rules_pkg at a version below 0.10.0

I don't have a quick reproduction. The issue is discussed in
https://github.com/bazelbuild/rules_pkg/issues/810

**What did you expect to see**
Clean build.

**What did you see instead?**
```
ERROR: error loading package '@@com_google_protobuf//': cannot load '@@rules_pkg~0.10.0//:mappings.bzl': no such file
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment** N/A

**Comment by zhangskz** [comment]
Thanks for raising this! We would be happy to take a patch here, and should be able to patch this back to our latest releases.

**Comment by aiuto** [comment]
I created one in https://github.com/protocolbuffers/protobuf/pull/15780,
but it looks like someone on the team must unlock it to run in CI.

**Comment by SArshpreetAI** [comment]
I am facing an issue 

```error loading package '@@com_google_protobuf//': Label '@@rules_pkg//pkg:mappings.bzl' is invalid because 'pkg' is not a package; perhaps you meant to put the colon here: '@@rules_pkg//:pkg/mappings.bzl'?```
