### ISSUE TITLE
CI "Check for Safety" provide no actionable feedback.

### ISSUE THREAD

**Issue by bcsgh** [protocolbuffers/protobuf#15847]
**What version of protobuf and what language are you using?**

Current main branch

**What operating system (Linux, Windows, ...) and version?**

GitHub's CI

**What runtime / compiler are you using (e.g., python version or gcc version)**

Not relevent?

**What did you do?**
1. Create a random fork as a random contributor and do something in a new branch.
2. Create a draft merge request.
3. Look at the Action the merge requests kicks off
4. See `This pull request is from an unsafe fork and hasn't been approved to run tests!` without even a link to what to do about that.

**What did you expect to see**

A message that says what to do.

**What did you see instead?**

A non-actionable message. (It does at least say *what's* wrong, jut not what to **do** next.)

**Comment by googleberg** [comment]
@acozzette Can you see if this message is customizable?
