### ISSUE TITLE
upb cmake problem

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/protobuf#15865]
**What version of protobuf and what language are you using?**

master branch 0ce48b30b5c925fc2e30fa2d8f234fc9e3611276

**What operating system (Linux, Windows, ...) and version?**

macOS 13.6.4 

**What runtime / compiler are you using (e.g., python version or gcc version)**

Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0

**What did you do?**

1.  git clone https://github.com/protocolbuffers/protobuf
2. cd protobuf/upb
3. cmake ./cmake -LA  
4. make

**What did you expect to see**

expect get libupb.a 

**What did you see instead?**

make do nothing (there is no output or file generated, finish at once)

**Comment by anuraaga** [comment]
Hi @calvin2021y - I happened to run into this too. While I'm not sure, I believe the `upb/cmake` folder is an input into updating the build in this repo but not meant to be executed directly.

The normal repo's CMake config contains a build target for `libupb`, so it can be built with e.g. `cmake --build build --target libupb`

https://github.com/protocolbuffers/protobuf/blob/main/cmake/libupb.cmake

**Comment by calvin2021y** [comment]
Thanks for update, I am not verify this method since I use bazel now.
