### ISSUE TITLE
Removal of Empty/Struct/Timestamp etc for python Protobuf Package

### ISSUE THREAD

**Issue by Zahlii** [protocolbuffers/protobuf#15886]
Following imports lo longer work. I could also not find any up to date documentation except for https://googleapis.dev/python/protobuf/latest/google/protobuf/timestamp_pb2.html, which still points to this namespace as the correct one. Going forward, how can we import and use these fields in Python? This now breaks all my gRPC builds. I sadly cannot pinpoint the exact version it is breaking.

```
from google.protobuf.empty_pb2 import Empty
from google.protobuf.json_format import MessageToDict
from google.protobuf.struct_pb2 import Struct
from google.protobuf.timestamp_pb2 import Timestamp
```

**Comment by Zahlii** [comment]
Maybe to add on this, I used to be able to do something like if isinstance(message, Empty) with the above code. This lo longer works. Also, these seem to break pylint rather than the import itself.

**Comment by honglooker** [comment]
Hey @anandolee, did we move those imports? e.g. `google.protobuf.empty_pb2` or `google.protobuf.json_format`. Is there a new path or an alternative that Zahlii can take?
