### ISSUE TITLE
AIP-161-compliant field masks are rejected by FieldMaskUtil in JAVA

### ISSUE THREAD

**Issue by Abhinav171** [protocolbuffers/protobuf#15880]
I am using filed mask on the same proto structure as mentioned in https://google.aip.dev/161. I am doing this in JAVA. The dependencies being used are :

com.google.protobuf:protobuf-java:3.23.2
com.google.protobuf:protobuf-java-util:3.23.2
io.grpc:grpc-protobuf:3.23.2

The issue i face is that when validating if it is a correct field mask for the example given in 161 it always gives false: 

require(FieldMaskUtil.isValid(Book::class.java, request.mask)) { "Invalid Field mask" }

Values i have tried are: "book.reviews.smith", "reviews.smith", "reviews.smith", "reviews.*.smith" etc

I have tried all possible combinations.

Can you guide me is this supported in protobuf current version and am i missing anything?

Also I have tried FieldMaskUtil.merge() as well it is not working as expected as per details mentioned in https://google.aip.dev/161.

**Comment by honglooker** [comment]
Hi @Abhinav171, could you write out a minimal repo and write the errors you get? Thank you.
