### ISSUE TITLE
SerializeToString does not serialize msg correctly with "repeated double" 

### ISSUE THREAD

**Issue by NR-Daichi** [protocolbuffers/protobuf#15889]
**What version of protobuf and what language are you using?**
Version: libprotoc 27.0-dev was built from main branch and installed through CMake But it has an issues and I tried libprotoc 25.3. Both of them have same bug 
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
cmake version 3.28.1
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

**What did you do?**
With the following code, I send messages (three values) through udp. When 1.0002 is sent, the buffer length is 8 (on sender side) and it decoded as "4.45015e-312" and the data size is also 1 instead of 3.  However, the buffer length is 33 (on sender side) and message is received correctly when 1.0003 is sent. So I believe that there is an issue in serialization.

Moreover, if the first data is set to 1.0002 and other two set to 1.0003, the buffer length is 8 and it cannot received correctly.

Message definition (.proto)
```
syntax = "proto3";

message Test{
    message Data{
    	double pos = 2;
    }
    repeated Data data = 1;
}
```

Sender:
```
void sendMsg(){
   Test test_;
    test_.clear_data();

    Test::Data *datahandler;

    datahandler = test_.add_data();
    datahandler->set_pos(1.0002);

    datahandler = test_.add_data();
    datahandler->set_pos(1.0002);

    datahandler = test_.add_data();
    datahandler->set_pos(1.0002);

    for(int i=0;i<test_.data_size();i++){
        std::cout<<"data"<<i<<" : "<<test_.data()[i].pos() <<std::endl;
    }
    std::string array1;
    test_.SerializeToString(&array1);
    size_t buffer_length=strlen(array1.c_str());
    std::cout<<"buffer_length "<<buffer_length<<std::endl;
    int sent_byte = sendto(sockfd_snd, array1.data(), buffer_length, 0, (const struct sockaddr *)&sendingTo, sizeof(sendingTo));
    if(sent_byte != buffer_length){
        std::cout<<"[udpConnector::Error] sending message failure "<<errno<<std::endl;
        exit(EXIT_FAILURE);
    }
}
```
Receiver:
```
void rcvMes() {
 Test test_;
    int data;
    socklen_t len;
    len = sizeof(clientaddr);
    data = recvfrom(sockfd_rcv, (char *)rcv_buffer, sizeof(rcv_buffer), 0, (struct sockaddr *) &clientaddr, &len);
    if(data > 0 ){
        test_.ParseFromString(rcv_buffer);
        char *strAdd = inet_ntoa(clientaddr.sin_addr);

        for(int i=0; i< test_.data_size(); i++){
            std::cout<<"[receve message] data"<<i<<" : "<<test_.data()[i].pos()<<" "<<strAdd<<std::endl;
        }
    }
}

```

**Comment by honglooker** [comment]
Hey @acozzette can you take a look when you have a chance?

Remark:
- nested `double pos` should `= 1`, not `= 2`

**Comment by acozzette** [comment]
I think the likely problem is that `test_.ParseFromString(rcv_buffer)` is treating `rcv_buffer` as a C-style string and therefore considering the string terminated at the first zero byte. Serialized protocol buffers can have zero bytes within them, so this is likely cutting the message short.

Sending protocol buffers over a socket is actually somewhat tricky to do correctly. Protocol buffers do not indicate their own length, so this is something you have to handle separately. The typical way to do it would be to send the size of the message before the message itself, and then the receiver can first read the size to know how many bytes to read for the actual message.

I would recommend trying out an RPC framework such as gRPC since that will handle a lot of these tricky details.

**Comment by NR-Daichi** [comment]
Thank you for commenting on my post. I have some follow up questions and I would appreciate if you spend time to address them.

- So, the root cause is a known issue of ParseFromString(). Do you have any plan to fix/improve soon?
- Just for confirmation, other methods (ParseFromIstream, ParseFromArray, etc) also have the same issue, right? 

- Also I heard that this is not an issue in nano protobuf. However, their document says that nano protobuf is not optimized in speed. So I was wondering if gRPC can work faster than nano protobuf
