### ISSUE TITLE
Can field names start with an underscore?

### ISSUE THREAD

**Issue by tenderlove** [protocolbuffers/protobuf#15899]
**What version of protobuf and what language are you using?**

I'm using proto3, `libprotoc 25.3`.

Language: Ruby, Python

**What operating system (Linux, Windows, ...) and version?**

macOS

**What I did**

I created a protobuf file like this:

```proto
syntax = "proto3";

message Message {
  optional bool _hello = 1;
}
```

**What I expected**

I expected the `protoc` compiler to fail

**What actually happened**

The `protoc` compiler succeeded.

The protobuf language specification says [field names are identifiers](https://protobuf.dev/reference/protobuf/proto3-spec/#identifiers), but the definition of `identifier` isn't allowed to start with an `_`.

`fieldName` is supposed to be an `ident`, and idents aren't supposed to start with an `_`:

```
letter = "A" ... "Z" | "a" ... "z"
ident = letter { letter | decimalDigit | "_" }
fieldName = ident
```

Is this a bug in the website, or a bug in `protoc`?

Thanks for your time!

**Comment by honglooker** [comment]
Hey @tenderlove -- nice find! You are reading the spec correctly. 

Ideally, identifiers would not start with `_`. Right now, we do not expect `protoc` to fail when an `ident` starts with `_`. However, do note that we have inconsistent behavior across languages. 

You'd see `_hello` in c++, but `hello` in Kotlin, for example.

Our current stance is that underscores as ident prefixes are discouraged, but protoc will not fail to build. 

Thanks,
--Hong

**Comment by tenderlove** [comment]
@honglooker thanks for the clarification! 🙇🏻‍♀️
