### ISSUE TITLE
Make versioning between protoc and protocol buffers sane

### ISSUE THREAD

**Issue by adamf-db** [protocolbuffers/protobuf#15909]
**What language does this apply to?**
All

**Describe the problem you are trying to solve.**
The current version naming is very confusing. The split in versioning (protoc at v2x.x, the language runtime at v4.x.x or v3.x.x) makes it hard to know what to install when. 

For example, looking at https://grpc.io/docs/protoc-installation/ - it requests `protoc-3.15.8`. Looking at https://protobuf.dev/support/version-support/ it looks like that's not supported and very, very old given that protoc is at version 25.x. Where do I get protoc-3.15.8? 

It's not at all clear from the github releases page what the _runtime_ version is: https://github.com/protocolbuffers/protobuf/releases has v25.3 as latest and doesn't list any language runtime versions. If I download that, `protoc --version` says v25.3. Does that mean there are no more language runtime versions? Compare this to https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.8 which has specific language runtime versions. 

I'm not really sure how to fix this. Perhaps on the version-support page the version number text in the language runtime tables are linked to correct latest release tags for that major version?

**Comment by honglooker** [comment]
@zhangskz is there a better page where we can direct Adam to? I was thinking about `https://protobuf.dev/support/version-support/`, but it looks like he's already taken a look.
