### ISSUE TITLE
Regression: Python FromString(bytearray()) broken on upb

### ISSUE THREAD

**Issue by jensbjorgensen** [protocolbuffers/protobuf#15911]
**What version of protobuf and what language are you using?**
Python protobuf 4.25.3
Version: since python backend changed to upb
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux (ubuntu 22.04.3)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.10.12

**What did you do?**
`python -c 'from google.protobuf import timestamp_pb2; timestamp_pb2.Timestamp.FromString(bytearray())'`

**What did you expect to see**
The program should run without error.

**What did you see instead?**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: expected bytes, bytearray found

```

**Workarounds**

1. Install a 3.* version of the python package
2. export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
3. Use a memoryview:
```
with memoryview(byte_array) as mv:
    ts = timestamp_pb2.Timestamp.FromString(mv)

```

I've copied this in from issue #10774 which was closed and archived. This is still not fixed and is a nasty surprise if your python protobuf package requirement is not pinned to 3.x. Bytearrays are more efficient than bytes to work with so I would expect this usage is very common.

**Comment by honglooker** [comment]
@ericsalo do you mind taking a look?

**Comment by ericsalo** [comment]
Bouncing this over to @anandolee who knows way more about this stuff than I do.

**Comment by chrismiller** [comment]
Ouch, I've just been hit by this trying to upgrade our large Python large codebase from an old protobuf version to 5.26.1:
```
$ python -c 'import google.protobuf; from google.protobuf import timestamp_pb2; print(google.protobuf.__version__); timestamp_pb2.Timestamp.FromString(bytearray())'
5.26.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: expected bytes, bytearray found
```

Note that this behaviour is at odds with [the documentation](https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.MergeFromString), which says: 

> Parameters: serialized ([bytes](https://docs.python.org/3/library/stdtypes.html#bytes)) – Any object that allows us to call memoryview(serialized) to access a string of bytes using the buffer interface.

Some (admittedly very quick and dirty) benchmarks show that having to convert via bytes(bytearray) or memoryview(bytearray) has a significant performance hit for us:

```
msg.ParseFromString(bytes_data) time: 1.6248738765716553
msg.ParseFromString(bytes(array_data)) time: 2.5375828742980957
msg.ParseFromString(memoryview(array_data)) time: 2.834777355194092
```
Even so, 5.26.1 is still quite a bit faster than the old version (which works fine with bytearray), so the concern I have is more about the 50+ places in our codebase that will need wrapping with bytes() conversions than the performance overhead.

Out of interest, here's some comparison benchmarks for our old protobuf version, which show no overhead for using bytearray vs bytes:
```
msg.ParseFromString(bytes_data) time: 4.132054328918457
msg.ParseFromString(array_data) time: 4.144273519515991
```

**Comment by jensbjorgensen** [comment]
@anandolee I submitted a quite small PR that would fix this, do you have time to take a look? 🙏

**Comment by chrismiller** [comment]
This fix doesn't seem to be in the new 27.2 release from yesterday, is that to be expected?

**Comment by jensbjorgensen** [comment]
I haven't tested it myself, but looking at the tag it should be in there

**Comment by chrismiller** [comment]
Ah OK - no I haven't tried it, I just didn't see it mentioned in the release notes and I couldn't see it on the [27.x branch](https://github.com/protocolbuffers/protobuf/blob/11307ca72574db357c2c011baa2f2bd859ba4177/python/message.c#L1260), but I probably just misunderstand the release process. I'll grab 27.2 and give it a go. Thanks! :)

**Comment by jensbjorgensen** [comment]
I take it back @chrismiller I looked at the log and also checked out v27.2 in my working copy and I concur that the change is not present in this tag. I'm puzzled as to why.

**Comment by chrismiller** [comment]
Ah that's unfortunate, thanks for confirming though. Not sure quite how other changes do make it into the 27.x branch, but I guess 28.x won't be all that far away at least.

**Comment by jensbjorgensen** [comment]
the PR to fix this was merged into version 28
