### ISSUE TITLE
absl linking issue when the protobuf is built as shared

### ISSUE THREAD

**Issue by SriSanthanaa** [protocolbuffers/protobuf#15993]
**What version of protobuf and what language are you using?**
Version: main/v3.25.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux 
version: ubuntu-20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
compiler: gcc
version: 9.4.0

**What did you do?**
Built protobuf for ubuntu target using CMake.
Created the package using conan version 1.59.0
Inside the package when tried to run the ./protoc --version faced an linking issue.

To resolve this issue tried building abseil as static.
The linking issue faced in the executable was resolved.
When tried to run the test executable ./tests some test cases are failing and the method at where the testcases are failing is google::protobuf::internal::KeyMapBase<>::BucketNumber()
Error message: F0000 00:00:1709101935.465052   40804 map.h:1069] Check failed: BucketNumberFromHash(hash_function()(k)) == VariantBucketNumber(RealKeyToVariantKey<Key>{}(k)) (6 vs. 5)

When both protobuf and abseil is built as shared or static the test cases are running successfully.
But if anyone of them is changed the test case is getting failed and the execution gets aborted.

I want abseil as static and protobuf as shared. How to proceed from here? Can anyone provide a feedback!
If possible please provide a solution for resolving the linking issue faced in the protoc executable when both the protobuf and abseil are built as shared. 

**What did you expect to see**
Both build and testing is working fine.

**Anything else we should know about your project / environment**

**Comment by dembekadam** [comment]
Faced the same issue  when moved  to protobuf 26.0 and absl lts_2024_01_16. 
Earlier the same code  was  working fine with protobuf 23.4 and absl lts_2023_01_25
