### ISSUE TITLE
undefined symbol: upb_prm_2bt_maxmaxb with amalgamation build

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/protobuf#16005]
**What version of protobuf and what language are you using?**

master branch, c 

**What operating system (Linux, Windows, ...) and version?**

linux, debian 12

**What runtime / compiler are you using (e.g., python version or gcc version)**

upb with amalgamation

**What did you do?**
1. git clone https://github.com/protocolbuffers/protobuf.git
2.  cd protobuf
3.  bazel build :protoc
4.  bazel build //upb_generator:protoc-gen-upb
5.  bazel build //upb_generator:protoc-gen-upb_minitable
6.  bazel build //upb:gen_amalgamation
7.  build amalgamation files with generate files by protoc
8.  get error undefined symbol: upb_prm_2bt_maxmaxb  upb_prs_1bt upb_prm_1bt_max128b  upb_ppv4_1bt

**What did you expect to see**

expect it link without problem

**What did you see instead?**

```sh
error: undefined symbol: upb_prm_1bt_maxmaxb
```

**Anything else we should know about your project / environment**

I am not sure where is the location of the symbol `upb_prm_1bt_maxmaxb`, I can not find it by searching source code.  

Is this function generate by scripts ?

**Comment by calvin2021y** [comment]
build with `-DUPB_ENABLE_FASTTABLE` seems fix the problem. 

Still I am not able to find where is upb_prs_1bt defined. Any document about fast table ?

**Comment by calvin2021y** [comment]
seems not a bugs, make sure build with UPB_ENABLE_FASTTABLE all the time.

**Comment by haberman** [comment]
I don't recommend enabling `UPB_ENABLE_FASTTABLE`.  The fasttable parser is experimental, and known to contain bugs.

I'm surprised you got this error with the amalgamation. But I also wouldn't recommend using the amalgamation. We're planning to phase it out when possible.
