### ISSUE TITLE
google_protobuf_Struct_clear_fields vs google_protobuf_Struct_fields_clear

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/protobuf#16004]
since there is no discussions enabled, I will drop the question here.

what is the difference between google_protobuf_Struct_clear_fields and google_protobuf_Struct_fields_clear ?

**What language does this apply to?**

`proto2`

**Describe the problem you are trying to solve.**

confuse with the  google_protobuf_Struct_clear_fields vs google_protobuf_Struct_fields_clear

**Describe the solution you'd like**

add document some where

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by anandolee** [comment]
I believe google_protobuf_Struct_clear_fields clears the fields as a field in Struct message, so map will not be there. google_protobuf_Struct_fields_clear clears the map content, the map is still there with size 0.
