### ISSUE TITLE
Test suite failure on windows with 26.0-rc3

### ISSUE THREAD

**Issue by h-vetinari** [protocolbuffers/protobuf#16026]
**What version of protobuf and what language are you using?**
v26.0-rc3

**What operating system (Linux, Windows, ...) and version?**
windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
vs2019

**What did you do?**
Build libprotobuf [for conda-forge](https://github.com/conda-forge/libprotobuf-feedstock/pull/213) according to our existing [recipe](https://github.com/conda-forge/libprotobuf-feedstock/blob/main/recipe/build-lib.bat), which boils down to roughly:
```batch
mkdir build
cd build

cmake -G "Ninja" ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_CXX_STANDARD=17 ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -Dprotobuf_ABSL_PROVIDER="package" ^
    -Dprotobuf_BUILD_SHARED_LIBS=ON ^
    -Dprotobuf_JSONCPP_PROVIDER="package" ^
    -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ^
    -Dprotobuf_USE_EXTERNAL_GTEST=ON ^
    -Dprotobuf_WITH_ZLIB=ON ^
    ..
if %ERRORLEVEL% neq 0 exit 1

cmake --build .
if %ERRORLEVEL% neq 0 exit 1

ctest --progress --output-on-failure
if %ERRORLEVEL% neq 0 exit 1

cmake --install .
if %ERRORLEVEL% neq 0 exit 1
```

**What did you expect to see**

Successful installation

**What did you see instead?**

```
50% tests passed, 1 tests failed out of 2

Total Test time (real) =  10.67 sec

The following tests FAILED:
	  2 - full-test (Failed)

%SRC_DIR%\build-shared>if 8 NEQ 0 exit 1
```
I've rerun this to check if it's flaky, and the same error persists.

There are no failed tests as far as I can see in the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=888409&view=results), the only indication of something going wrong that I found is
```
[----------] 28 tests from DescriptorTest
[ RUN      ] DescriptorTest.Name
[       OK ] DescriptorTest.Name (0 ms)
[ RUN      ] DescriptorTest.ContainingType
[       OK ] DescriptorTest.ContainingType (0 ms)
[ RUN      ] DescriptorTest.FieldNamesDedup
[       OK ] DescriptorTest.FieldNamesDedup (0 ms)
[ RUN      ] DescriptorTest.FieldNameDedupJsonEqFull
[       OK ] DescriptorTest.FieldNameDedupJsonEqFull (0 ms)
[ RUN      ] DescriptorTest.FieldsByIndex
[       OK ] DescriptorTest.FieldsByIndex (0 ms)
[ RUN      ] DescriptorTest.FindFieldByName
[       OK ] DescriptorTest.FindFieldByName (0 ms)
[ RUN      ] DescriptorTest.FindFieldByNumber
[       OK ] DescriptorTest.FindFieldByNumber (0 ms)
Errors while running CTest                                      # <-- HERE
[ RUN      ] DescriptorTest.FieldName
[       OK ] DescriptorTest.FieldName (0 ms)
[ RUN      ] DescriptorTest.FieldFullName
[       OK ] DescriptorTest.FieldFullName (0 ms)
```

though I'm almost certain that it has nothing to do with this test in particular, and just rather randomly pops up in the log, because during the first failed run, it popped up somewhere else.

From a quick search, I couldn't tell what exit code 8 means for gtest.

**Anything else we should know about your project / environment**

**Comment by h-vetinari** [comment]
This is still an issue as of 26.0. CC @fowles

**Comment by mkruskal-google** [comment]
I think this is the relevant piece, it looks like a test is crashing:
```
2024-03-04T01:46:03.3936501Z [----------] 155 tests from CommandLineInterfaceTest
2024-03-04T01:46:03.3936683Z [ RUN      ] CommandLineInterfaceTest.BasicOutput
2024-03-04T01:46:03.3936773Z 
2024-03-04T01:46:03.3936832Z 
2024-03-04T01:46:03.3936971Z 50% tests passed, 1 tests failed out of 2
2024-03-04T01:46:03.3937058Z 
2024-03-04T01:46:03.3937185Z Total Test time (real) =  10.67 sec
```

**Comment by mkruskal-google** [comment]
It would also be useful to know what versions of your external dependencies are installed (e.g. absl, jsoncpp, gtest)

**Comment by mkruskal-google** [comment]
Nvm, this is easily reproducible on my windows machine in both bazel and cmake.  Not sure why our CI didn't catch this...

**Comment by mkruskal-google** [comment]
Disabling our stdout/stderr capturing in the CLI tester, I found that this was caused by a crash during our `getenv` call.  Not sure why CI didn't catch this, but the fix is easy

**Comment by h-vetinari** [comment]
Thank you very much! I can confirm that this fixes the problem we were seeing! 🙏
