### ISSUE TITLE
golang generated code does not contain has methods for fields with the optional label

### ISSUE THREAD

**Issue by YannikGrossmann** [protocolbuffers/protobuf#16079]
**What version of protobuf and what language are you using?**
Version: v5.26.0--rc3
Language: Golang

**What operating system (Linux, Windows, ...) and version?**
macOS 13.4 aarch64

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc-gen-go v1.33.0

**What did you do?**
1. Create message with optional field like so
``` proto 
message Foo{
  optional string bar = 1;
}
```
3. Generate go files (used `protoc -I=./test --go_out=./test ./test/test.proto`)
4. Generated struct is missing HasBar func

**What did you expect to see**
According to the documentation since version 3.15 proto3 supports optional fields.
Those fields should contain a `has_foo()` func to indicate if the field was explicitly set or if it has the default value.
See https://protobuf.dev/programming-guides/field_presence/#semantic-differences

**Anything else we should know about your project / environment**
Its not enough to check for the default value. The value can be explicitly set to nil or it can be ignored, which is not possible without the has func.

**Comment by puellanivis** [comment]
A field given as type `optional string` will have type `*string`. Testing for presence is accomplished by testing that field for the value `nil`.

**Comment by YannikGrossmann** [comment]
But what if i need to check if a value is explicitly set to nil or it was not entered.
The documentation says that if you add optional, the explicit presence can be checked using the has_foo() method.
https://protobuf.dev/programming-guides/field_presence/#how-to-enable-explicit-presence-in-proto3
The C++ compiler also provides those functions.

**Comment by puellanivis** [comment]
In protobuf for golang, there is no semantic difference between being explicitly set to `nil` or it simply not appearing, as there is no semantic concept of “nil” in protobuf. The proto wire only allows a field to be either unpopulated, or set to a valid value. This follows into the JSON mapping, where `null` is equivalent to the field being not present.

The documentation does indeed say that presence can be checked by using `has_foo()`, however, that is for other languages. The [example code shown for Golang](https://github.com/protocolbuffers/protobuf/issues) make it clear:
```go
m := GetProto()
if m.Foo != nil {
  // Clear the field:
  m.Foo = nil
} else {
  // Field is not present, so set it.
  m.Foo = proto.Int32(1)
}
```
