### ISSUE TITLE
C# - "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

### ISSUE THREAD

**Issue by szigetics** [protocolbuffers/protobuf#16095]
**What version of protobuf and what language are you using?**
Version: main/v3.21.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise

**What runtime / compiler are you using (e.g., python version or gcc version)**
Micorosft Visual Studio 2022, .Net Framework 4.5.0

**What did you do?**
1. Build a dll, which is using Google.Protobuf 3.21.4. Make sure that all the dependencies are deployed next to the dll : 
System.Buffers.dll, System.Memory.dll, System.Runtime.CompilerServices.Unsafe.dll
2. Open Powershell
3. Call `Add-Type -Path ./mydll.dll`
4. Call a function, from the dll, which is using protobuf

**What did you expect to see**
No issues, the function should work without issues on all machines.

**What did you see instead?**
The following error was reported on **SOME** machines : 
`Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

We are not sure what is causing this to happen only on some machines. We don't have access to these machines and we weren't able to reproduce the issue. Using Procmon we see that the `System.Runtime.CompilerServices.Unsafe.dll` was not tried to be loaded from the path to which we deployed it : 
![not_working](https://github.com/protocolbuffers/protobuf/assets/7099208/ad30d903-6698-4951-ae92-2233848835a6)

**Anything else we should know about your project / environment**
Previously we compiled our dll using .Net Framework 3.5 and Google.Protobuf 3.6.1 . This older version didn't have the `System.Runtime.CompilerServices.Unsafe.dll` dependency. We didn't have the above issue with this combination.

**Comment by szigetics** [comment]
> I strongly suspect that this is a problem with the way Powershell manages dependencies. I'd also note that .NET 4.5 is out of support from Microsoft now.

We are forced to use 4.5 because the oldest Windows/Windows Server version that we support is shipped with 4.5 .
( according to : https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies ).

Please note that it shouldn't be a problem to set 4.5 as a target, and use the built app/dll with a newer .net version : 
https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#remarks-for-version-45-and-later 

> 
> Are you able to try again with a more recent version of the .NET Framework (4.6.2 or later)? 
As I mentioned above, we am forced to use 4.5 .

We are running automated tests our dlls with different .net framework versions, and none of the .net framework versions caused any issues. So far we couldn't reproduce the issue that our customers are seeing. Please note that the issue only appears on a small subset of our customers' devices.

> If you could specify the version of Powershell you're using, that would help too
We are testing with different Powershell versions as well, but none of the Powershell versions has shown the issue so far.

> - along with a project file for the assembly you're building in step 1. (There are so many variations of how you build that DLL, it would be really helpful to have concrete repro steps.)

Sure, I can share the project file, but unfortnately I don't have concrete repro steps yet. All that I know is that some of our customers have the issue on some of their devices. We tried to rule out different factors : for example we asked them to disable/remove their AV software temporarily and similar things, but nothing helped so far in fixing those machines which are having the issue. We also couldn't spot yet what is causing the issue only on those machines.

> 
> If you're able to reproduce the problem without Powershell being involved at all, that would be even better.

No, we couldn't reproduce the problem yet.
Do you have any ideas what could potentially cause the issue to only surface on some machines?
What information should we gather from the machines which have the issue, other than the : 
- Windows version
- Powershell version
- .Net Framework version

?

**Comment by jskeet** [comment]
> We are forced to use 4.5 because the oldest Windows/Windows Server version that we support is shipped with 4.5 .

Does that mean you're supporting versions of Windows that are themselves out of support from Microsoft? (For example, support for Windows Server 2012 and 2012 R2 ended in October 2023.)

Please note that at some point we're likely to remove support for .NET 4.5 from Protobuf. [Microsoft does not support .NET 4.5 any more](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/) so you should expect more and more libraries to stop supporting it too.

However, I suspect the main cause of this issue is PowerShell rather than .NET 4.5. Fundamentally, as I'm not a PowerShell user myself, other details that *don't* include a repro are unlikely to help. It looks like this is going to be some core detail of PowerShell dependency resolution not conforming with what is expected by the rest of the ecosystem - I'm afraid that's not something we're going to be able to support.

The only idea I have that you could look at in terms of seeing why it only happens on some machines is to look at the GAC...
