### ISSUE TITLE
v1.33.0 of google.golang.org/protobuf Fails to Compile

### ISSUE THREAD

**Issue by Jac0bDeal** [protocolbuffers/protobuf#16163]
What version of protobuf and what language are you using?
Version: N/A (indirect dependency)
Language: GoLang

What operating system (Linux, Windows, ...) and version?
Linux/MacOS

What runtime / compiler are you using (e.g., python version or gcc version)
Go 1.20.12

What did you do?

Update the version of google.golang.org/protobuf in go.mod to v1.33.0. Run go build. Build fails due to undefined constant in the package.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
# github.com/golang/protobuf/protoc-gen-go/descriptor
../../../go/pkg/mod/github.com/golang/protobuf@v1.5.3/protoc-gen-go/descriptor/descriptor.pb.go:106:61: undefined: descriptorpb.Default_FileOptions_PhpGenericServices
```
Upon inspection of the source, it would appear that the offending constant `descriptorpb.Default_FileOptions_PhpGenericServices` is indeed not defined in v1.33.0 and so it is failing to compile.

Anything else we should know about your project / environment
n/a

**Comment by orius123** [comment]
Happens also to me with Go 1.21.6

**Comment by yuanyp8** [comment]
any update？

**Comment by yuanyp8** [comment]
```shell
# go get github.com/golang/protobuf@latest 
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go: upgraded github.com/golang/protobuf v1.5.2 => v1.5.4
```

**Comment by dosten** [comment]
Happening to me too

**Comment by markphelps** [comment]
Can confirm, bumping `github.com/golang/protobuf` to `1.5.4` allows this this change to compile. https://github.com/flipt-io/flipt/pull/2855/files

**Comment by Jac0bDeal** [comment]
Since it seems to work for multiple people, I'll close this issue.
