### ISSUE TITLE
Proto_library fails to build with abseil-cpp version = "20240116.0"

### ISSUE THREAD

**Issue by chokychou** [protocolbuffers/protobuf#16186]
Copy paste from [here](https://github.com/abseil/abseil-cpp/issues/1638#issue-2178120060). So basically ==>

> ### Describe the issue
> I want to compile proto with latest version [20240116.1](https://registry.bazel.build/modules/abseil-cpp), but fail to compile. Not sure what the cause is.
> 
> What has been working is to roll back to version 20230802.0. What might be the cause of the issue?
> 
> ### Steps to reproduce the problem
> proto
> 
> ```
> syntax = "proto3";
> 
> option java_multiple_files = true;
> option java_package = "io.grpc.examples.sample";
> option java_outer_classname = "SampleProto";
> option objc_class_prefix = "HLW";
> 
> package sample;
> 
> // The sample service definition.
> service ProcessSample {
>     // Sends a transaction
>     rpc ProcessTransaction (ProcessTransactionRequest) returns (ProcessTransactionResponse) {}
> }
> ```
> 
> BUILD file
> 
> ```
> load("@rules_proto//proto:defs.bzl", "proto_library")
> load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
> 
> package(default_visibility = ["//visibility:public"])
> 
> proto_library(
>     name = "sample_proto",
>     srcs = ["sample.proto"],
> )
> ```
> 
> In the MODULE.bazel, I have declare below but bazel doesn't compile. Logs show below.
> 
> ```
> bazel_dep(name = "bazel_skylib", version = "1.5.0")
> bazel_dep(name = "protobuf", version = "23.1")
> bazel_dep(name = "grpc", version = "1.56.3")
> bazel_dep(name = "rules_cc", version = "0.0.9")
> bazel_dep(name = "rules_python", version = "0.31.0")
> bazel_dep(name = "rules_proto", version = "6.0.0-rc2")
> bazel_dep(name = "zlib", version = "1.3")
> bazel_dep(name = "googletest", version = "1.14.0", repo_name = "com_google_googletest")
> 
> # =========================================
> # Cpp dependencies
> # =========================================
> 
> bazel_dep(name = "abseil-cpp", version = "20240116.0")
> bazel_dep(name = "rules_foreign_cc", version = "0.10.1")
> ```
> 
> Log
> 
> ```
> INFO: Analyzed target //src/proto:sample_proto (86 packages loaded, 1340 targets configured).
> INFO: Found 1 target...
> ERROR: /home/user/.cache/bazel/_bazel_user/36085a489d0698627f098f95cacee125/external/protobuf~23.1/src/google/protobuf/BUILD.bazel:318:11: Compiling src/google/protobuf/arena.cc [for tool] failed: (Exit 1): gcc failed: error executing command (from target @protobuf~23.1//src/google/protobuf:arena) 
>   (cd /home/user/.cache/bazel/_bazel_user/36085a489d0698627f098f95cacee125/sandbox/linux-sandbox/884/execroot/_main && \
>   exec env - \
>     PATH='/home/user/.vscode/cli/servers/Stable-019f4d1419fbc8219a181fab7892ebccf7ee29a2/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/VMware/VMware Workstation/bin/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR:/mnt/c/Users/draly/AppData/Local/Programs/Python/Python312/Scripts/:/mnt/c/Users/draly/AppData/Local/Programs/Python/Python312/:/mnt/c/Users/draly/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/draly/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/draly/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/draly/.dotnet/tools:/snap/bin' \
>     PWD=/proc/self/cwd \
>   /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_objs/arena/arena.d '-frandom-seed=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_objs/arena/arena.o' '-DBAZEL_CURRENT_REPOSITORY="protobuf~23.1"' -iquote external/protobuf~23.1 -iquote bazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1 -iquote external/abseil-cpp~20240116.0 -iquote bazel-out/k8-opt-exec-2B5CBBC6/bin/external/abseil-cpp~20240116.0 -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/arena -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/arena_align -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/stubs/_virtual_includes/lite -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/port_def -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/arena_allocation_policy -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/arena_config -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/arena_cleanup -Ibazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_virtual_includes/string_block -g0 -g0 '-std=c++23' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/protobuf~23.1/src/google/protobuf/arena.cc -o bazel-out/k8-opt-exec-2B5CBBC6/bin/external/protobuf~23.1/src/google/protobuf/_objs/arena/arena.o)
> # Configuration: a95b69ee4c4c959853d22e8caf204e1bd3ec4f72282af74cb657a29833555e5d
> # Execution platform: @local_config_platform//:host
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> external/protobuf~23.1/src/google/protobuf/arena.cc:472:49: error: 'Layout' in namespace 'absl::lts_20240116::container_internal' does not name a template type
>   472 |   using layout_type = absl::container_internal::Layout<
>       |                                                 ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc:494:20: error: 'layout_type' does not name a type
>   494 |   constexpr static layout_type Layout(size_t n) {
>       |                    ^~~~~~~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'absl::lts_20240116::Span<const std::atomic<void*> > google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ids() const':
> external/protobuf~23.1/src/google/protobuf/arena.cc:417:12: error: 'Layout' was not declared in this scope
>   417 |     return Layout(capacity()).Slice<kIds>(ptr()).first(safe_size());
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc:417:50: error: request for member 'first' in '((const google::protobuf::internal::ThreadSafeArena::SerialArenaChunk*)this)->google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ptr()', which is of non-class type 'const char*'
>   417 |     return Layout(capacity()).Slice<kIds>(ptr()).first(safe_size());
>       |                                                  ^~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'absl::lts_20240116::Span<std::atomic<void*> > google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ids()':
> external/protobuf~23.1/src/google/protobuf/arena.cc:420:12: error: 'Layout' was not declared in this scope
>   420 |     return Layout(capacity()).Slice<kIds>(ptr()).first(safe_size());
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc:420:50: error: request for member 'first' in '((google::protobuf::internal::ThreadSafeArena::SerialArenaChunk*)this)->google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ptr()', which is of non-class type 'char*'
>   420 |     return Layout(capacity()).Slice<kIds>(ptr()).first(safe_size());
>       |                                                  ^~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'std::atomic<void*>& google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::id(uint32_t)':
> external/protobuf~23.1/src/google/protobuf/arena.cc:424:12: error: 'Layout' was not declared in this scope
>   424 |     return Layout(capacity()).Pointer<kIds>(ptr())[i];
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'absl::lts_20240116::Span<const std::atomic<google::protobuf::internal::SerialArena*> > google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::arenas() const':
> external/protobuf~23.1/src/google/protobuf/arena.cc:429:12: error: 'Layout' was not declared in this scope
>   429 |     return Layout(capacity()).Slice<kArenas>(ptr()).first(safe_size());
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc:429:53: error: request for member 'first' in '((const google::protobuf::internal::ThreadSafeArena::SerialArenaChunk*)this)->google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ptr()', which is of non-class type 'const char*'
>   429 |     return Layout(capacity()).Slice<kArenas>(ptr()).first(safe_size());
>       |                                                     ^~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'absl::lts_20240116::Span<std::atomic<google::protobuf::internal::SerialArena*> > google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::arenas()':
> external/protobuf~23.1/src/google/protobuf/arena.cc:432:12: error: 'Layout' was not declared in this scope
>   432 |     return Layout(capacity()).Slice<kArenas>(ptr()).first(safe_size());
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc:432:53: error: request for member 'first' in '((google::protobuf::internal::ThreadSafeArena::SerialArenaChunk*)this)->google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::ptr()', which is of non-class type 'char*'
>   432 |     return Layout(capacity()).Slice<kArenas>(ptr()).first(safe_size());
>       |                                                     ^~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'const std::atomic<google::protobuf::internal::SerialArena*>& google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::arena(uint32_t) const':
> external/protobuf~23.1/src/google/protobuf/arena.cc:436:12: error: 'Layout' was not declared in this scope
>   436 |     return Layout(capacity()).Pointer<kArenas>(ptr())[i];
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'std::atomic<google::protobuf::internal::SerialArena*>& google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::arena(uint32_t)':
> external/protobuf~23.1/src/google/protobuf/arena.cc:440:12: error: 'Layout' was not declared in this scope
>   440 |     return Layout(capacity()).Pointer<kArenas>(ptr())[i];
>       |            ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In static member function 'static constexpr size_t google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::AllocSize(size_t)':
> external/protobuf~23.1/src/google/protobuf/arena.cc:465:56: error: 'Layout' was not declared in this scope
>   465 |   constexpr static size_t AllocSize(size_t n) { return Layout(n).AllocSize(); }
>       |                                                        ^~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'google::protobuf::internal::SerialArenaChunkHeader& google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::header()':
> external/protobuf~23.1/src/google/protobuf/arena.cc:479:13: error: 'layout_type' has not been declared
>   479 |     return *layout_type::Partial().Pointer<kHeader>(ptr());
>       |             ^~~~~~~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In member function 'const google::protobuf::internal::SerialArenaChunkHeader& google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::header() const':
> external/protobuf~23.1/src/google/protobuf/arena.cc:482:13: error: 'layout_type' has not been declared
>   482 |     return *layout_type::Partial().Pointer<kHeader>(ptr());
>       |             ^~~~~~~~~~~
> external/protobuf~23.1/src/google/protobuf/arena.cc: In static member function 'static google::protobuf::internal::ThreadSafeArena::SerialArenaChunk* google::protobuf::internal::ThreadSafeArena::NewSerialArenaChunk(uint32_t, void*, google::protobuf::internal::SerialArena*)':
> external/protobuf~23.1/src/google/protobuf/arena.cc:627:61:   in 'constexpr' expansion of 'google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::AllocSize(0)'
> external/protobuf~23.1/src/google/protobuf/arena.cc:627:63: error: 'constexpr' call flows off the end of the function
>   627 |   constexpr size_t kHeaderSize = SerialArenaChunk::AllocSize(0);
>       |                                                               ^
> external/protobuf~23.1/src/google/protobuf/arena.cc:628:60:   in 'constexpr' expansion of 'google::protobuf::internal::ThreadSafeArena::SerialArenaChunk::AllocSize(1)'
> external/protobuf~23.1/src/google/protobuf/arena.cc:628:66: error: 'constexpr' call flows off the end of the function
>   628 |   constexpr size_t kEntrySize = SerialArenaChunk::AllocSize(1) - kHeaderSize;
>       |                                                                  ^~~~~~~~~~~
> Target //src/proto:sample_proto failed to build
> INFO: Elapsed time: 13.947s, Critical Path: 2.93s
> INFO: 107 processes: 18 internal, 89 linux-sandbox.
> FAILED: Build did NOT complete successfully
> ```
> 
> ### Temporary solution
> Version 20230802.0 works. What might be the cause of the issue?
> 
> ### What version of Abseil are you using?
> bazel_dep(name = "abseil-cpp", version = "20240116.1")
> 
> ### What operating system and version are you using?
> Ubuntu subsystem in windows 11
> 
> ### What compiler and version are you using?
> gcc -v
> 
> ```
> $ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
> Thread model: posix
> Supported LTO compression algorithms: zlib zstd
> gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
> ```
> 
> In .bazelrc
> 
> ```
> build --cxxopt=-std=c++23
> build --host_cxxopt=-std=c++23
> ```
> 
> ### What build system are you using?
> bazel 6.3.2
> 
> ### Additional context
> _No response_

**Comment by zhangskz** [comment]
Looks like you are using Protobuf 23.1 which is out of support, and does not necessarily support the latest ABSL version. Please try with the latest v26.0 release, which should support absl 20240116, and reopen if you still hit compatibility problems here.

**Comment by monkeynova** [comment]
I see that it's not latest in the repo, but the bazel central repository's latest version (https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/protobuf/metadata.json) is 23.1

If this is fixed at 26.0 can you please update the BCR to reflect that?

**Comment by ryanli** [comment]
+1 this is affecting us as well. Please update BCR?

**Comment by keith** [comment]
A workaround in the meantime is to force abseil to a _lower_ version that's compatible:

```
# Downgrade absl to avoid https://github.com/protocolbuffers/protobuf/issues/16186 until there's a newer version of protobuf in the BCR
bazel_dep(name = "abseil-cpp", version = "20230802.0.bcr.1", repo_name = "com_google_absl")
single_version_override(
    module_name = "abseil-cpp",
    version = "20230802.0.bcr.1",
)
```

**Comment by monkeynova** [comment]
Or, what I did was downgrade protobuf using the same method. I wanted the features in absl more than I wanted the features in protobuf.

**Comment by wffurr** [comment]
This is not fixed with protobuf 26.1.  I get the exact same error when using abseil 20240116.1.

**Comment by zhangskz** [comment]
Are you certain you're using 26.1? The error you are hitting should've been fixed in https://github.com/protocolbuffers/protobuf/commit/e052928c94f5a9a6a6cbdb82e09ab4ee92b7815f which was included in 26.1 (but not 23.1 which is the BCR version)

**Comment by zhangskz** [comment]
Based on the line number of the error, it looks like this is still using protobuf 23.1.

**Comment by wffurr** [comment]
I figured out what's going on.  I was transitively getting protobuf 23.1 and the root declaration for protobuf 26.1 was just ignored.  Both one of my project's dependencies and protobuf's own dependencies were transitively including 23.1 from the Bazel central registry.

I discovered the `bazel mod all_paths protobuf` command which showed the dependency tree.  `rules_python`, `rules_proto`, and `upb` all cyclically include `protobuf`, which was getting 23.1 from BCR since I was including those as `bazel_dep` rather than downloading them as an `http_archive` (along with all *their* transitive dependencies).

```
├───rules_proto@5.3.0-21.7
│   ├───bazel_skylib@1.5.0 (*)
│   ├───protobuf@23.1 (*)
│   └───rules_cc@0.0.9 (*)
├───rules_python@0.31.0
│   ├───bazel_skylib@1.5.0 (*)
│   ├───platforms@0.0.9 (*)
│   ├───protobuf@23.1 (*)
│   ├───rules_proto@5.3.0-21.7 (*)
│   └───bazel_features@1.1.1
├───upb@0.0.0-20230516-61a97ef
│   ├───abseil-cpp@20240116.2 (*)
│   ├───bazel_skylib@1.5.0 (*)
│   ├───platforms@0.0.9 (*)
│   ├───protobuf@23.1 (*)
│   ├───rules_pkg@0.7.0 (*)
│   └───rules_proto@5.3.0-21.7 (*)
```

I discovered I can specify a version of a `bazel_dep` that doesn't actually exist in the registry if I provide an override for it, which I did with the latest commit from the protobuf repository:
```
bazel_dep(
    name = "protobuf",
    version = "27.0",
)
# Protobuf 27 is not yet published to the Bazel central registry, so download it from head.
PROTOBUF_COMMIT = "0e8115fed85d2fc755d9b53a78247a61ac1f8ca6"
archive_override(
    module_name = "protobuf",
    strip_prefix = "protobuf-" + PROTOBUF_COMMIT,
    urls = "https://github.com/protocolbuffers/protobuf/archive/" + PROTOBUF_COMMIT + ".zip",
)
```
Hopefully this all goes away once Protobuf 27.0 is published to the Bazel central registry which should be very soon.

**Comment by keith** [comment]
im adding 26.0 to the BCR hoping to solve this https://github.com/bazelbuild/bazel-central-registry/pull/1806/
