### ISSUE TITLE
Protobuf release artifacts do not include language-specific features protos

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#16211]
The release artifacts for v26.0 do not include the protos for controlling language specific features. The repo includes `google/protobuf/cpp_features.proto` and `google/protobuf/java_features.proto` (though the latter is a bit buried, actually in `java/core/src/main/java/com/google/protobuf`). And the [Editions docs](https://protobuf.dev/editions/features/) reference these two files. But the actual distribution does not include them:

```
~/protoc-26.0> find include 
include
include/google
include/google/protobuf
include/google/protobuf/timestamp.proto
include/google/protobuf/field_mask.proto
include/google/protobuf/api.proto
include/google/protobuf/duration.proto
include/google/protobuf/struct.proto
include/google/protobuf/wrappers.proto
include/google/protobuf/source_context.proto
include/google/protobuf/any.proto
include/google/protobuf/type.proto
include/google/protobuf/empty.proto
include/google/protobuf/compiler
include/google/protobuf/compiler/plugin.proto
include/google/protobuf/descriptor.proto
```

Is this a mistake? If not, how are users intended to obtain these files in order to import them from their own proto sources?

**Comment by mkruskal-google** [comment]
This is a bug assuming you got these results by installing protoc and the C++ runtime.  We should be shipping features protos with the corresponding runtime, so you should see cpp_features.proto here.  Java features are separately put in the wrong place (see https://github.com/protocolbuffers/protobuf/issues/16155)

**Comment by jhump** [comment]
> This is a bug assuming you got these results by installing protoc and the C++ runtime. 
I just downloaded the relevant artifact for my machine from the "Artifacts" section, at the bottom of the [GitHub release](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0).

So if I download the Java runtime, I'm expected to manually unpack the proto source from that JAR and put that directory in my include path? Why not include it with the other standard include files? If that location in the runtime JAR is easily consumed from a code gen task in Maven or Gradle, what about if I'm using the same proto and doing code gen for many languages, and need access to all of the feature from a single file? Then I need the Java features source file, even for generating C++, since the source file imports it.

**Comment by mkruskal-google** [comment]
yea that's a good point, maybe we should include all of these from our GH artifacts

**Comment by mkruskal-google** [comment]
The major problem I see is that we're also shipping these protos and their gencode with our runtime releases.  So there's a concern about version skew if we release them to two different places

**Comment by jhump** [comment]
> So there's a concern about version skew if we release them to two different places

How are they different from `descriptor.proto` and `plugin.proto` (where gencode is also shipped with most runtime releases)? Is it just that they are expected to change/evolve more frequently/quickly than those files?
