### ISSUE TITLE
editions: deconflate the two aspects of "OPEN" enum type

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#16249]
This is a feature request.

Currently, the "OPEN" enum type combines two independent aspects of proto3 enums:
1. The values are open. Values other than those declared in the source are allowed. This is the intuitive constraint, just per the naming of the feature and its values.
2. The values must start with zero. This one is really orthogonal to whether an enum's allowed values are open or closed.

Furthermore, an enum field with "IMPLICIT" field presence _requires_ that the enum's type be "OPEN". However, it really should only care that the values start with zero, since the field's default value must necessarily be zero (due to having implicit presence).

So de-conflating these two aspects would change the meanings a little:
1. If an enum type is "OPEN", it does not matter what it's first value is. Its default value will be the first enum value (which could be non-zero). This is the same as "CLOSED". So the only difference between the two is that an "OPEN" enum allows values outside those declared in source, which more intuitively aligns with the names "OPEN" vs. "CLOSED".
2. If an enum field has "IMPLICIT" presence, the corresponding enum type must have an initial value that is zero. So it would be acceptable for an implicit field to refer to a _closed_ enum, as long as that enum's default value is zero (which matches the implicit default value of the field).

This would technically be a backwards-compatible change: it only relaxes constraints and adds to the set of acceptable sources. It wouldn't reject any sources that compile and validate with the rules implemented in v26.0 today.

**Comment by mkruskal-google** [comment]
Hey Josh,

yea this one is definitely on our radar for 2024.  The reason we added this constraint in 2023 was to minimize the new surface we were introducing.  You're correct that the only real requirement for implicit presence is that the enum default be 0, but we also want to burn down implicit presence long-term. 

We have some additional enum changes we'd like to make too (e.g. proper scoping), so it's likely that `OPEN` won't be our final enum type.
