### ISSUE TITLE
protoc does not follow the protobuf spec for reserved field names

### ISSUE THREAD

**Issue by lg-stripe** [protocolbuffers/protobuf#16272]
**What version of protobuf and what language are you using?**

Version: main (https://github.com/protocolbuffers/protobuf/commit/821e854b5a350bbf9e3e5f34abc3d666bef09fdd)
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
```
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
```

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc

**What did you do?**

1. Create a file name `./reversed-repro.proto ` with the following content:
    ````proto
    syntax = "proto3";
    
    package reserved_repro;
    
    message AMessage {
      reserved 'something' 'somethingElse';
      string AProperty = 1;
    }
    ````
2. (if protoc not already built) Run `bazel build //:protoc`
3. Run `bazel-bin/protoc --descriptor_set_out=/tmp/out.pb ./reversed-repro.proto`

**What did you expect to see**

stdout: ` `

stderr: `examples/addressbook.proto:7:23: Expected ",".`

return code: `1` (or anything else that is not `0`)

According to https://protobuf.dev/reference/protobuf/proto3-spec/#reserved, the list of reserved field names should be separated by a `,`.

**What did you see instead?**

stdout: ` ` 

stderr: ` `

return code: `0`

**Anything else we should know about your project / environment**

Not that I can think of.

**Comment by jhump** [comment]
@lg-stripe, take another look at the grammar for string literals:
https://protobuf.dev/reference/protobuf/proto3-spec/#string_literals

In your example, the two adjacent string literals get concatenated. So your example _does_ match the spec and is the equivalent of this:
```proto
syntax = "proto3";

package reserved_repro;

message AMessage {
  reserved 'somethingsomethingElse';
  string AProperty = 1;
}
```

Note that this will be fixed in editions, which uses identifiers, not string literals, so an errant space/missing comma won't be silently interpreted as concatenation.

Also see #6335 and #13440.

**Comment by lg-stripe** [comment]
@jhump Thanks for the quick answer! 

I did not realized that strings could be concatenated using spaces between expressions with quotes. Is the intent here to allows multiline string concatenation or something like that?

Is there any plan to add an operator to make the concatenation more explicit? `+` maybe?
