### ISSUE TITLE
Windows DLL available to download

### ISSUE THREAD

**Issue by macintoshplus** [protocolbuffers/protobuf#16283]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/tools-and-utilities/protobuf-292

If you have any questions, I am available to discuss them.

**Comment by zhangskz** [comment]
Thanks for sharing that this is now available for PHP Windows users!

Note there's a google group for protobuf users if the intent of this issue is for visibility for Protobuf PHP users:
https://github.com/protocolbuffers/protobuf?tab=readme-ov-file#developer-community
