### ISSUE TITLE
Can we make the compilation system support C++builder compilers？Rad studio requires protobuf

### ISSUE THREAD

**Issue by luxiao9999** [protocolbuffers/protobuf#16287]
As is well known, rad studio is still widely used. But I found out he couldn't compile protobuf, with a bunch of errors. The macro definition of protobuf also does not support C++builder compilers. So, I hope our team can support us a bit

**Comment by acozzette** [comment]
We don't have plans to add support for any additional compilers, but we would be happy to review pull requests with fixes.
