### ISSUE TITLE
What happened between v4.24.2 and v4.25.3

### ISSUE THREAD

**Issue by imran-iq** [protocolbuffers/protobuf#16316]
Looking at the tags via: https://github.com/protocolbuffers/protobuf/compare/v4.24.4...v4.25.3 commits from 2009 are showing up.

I only noticed this due to a dependabot update, what is causing the entire commit history to show up between those tags?

**Comment by zhangskz** [comment]
We merged the [upb repo](https://github.com/protocolbuffers/upb) into the protobuf repo around that time.

We intentionally merged in a way that preserved the commit history / blames, but the side effect was that all upb commits show up in the commit history between 24.x and 25.x. We had to handle this for our 25.x changelog generation as well.
