### ISSUE TITLE
compilation on macos, ccache error

### ISSUE THREAD

**Issue by squm** [protocolbuffers/protobuf#16326]
**What version of protobuf and what language are you using?**
Version: main/v5.26.0 (latest)
Language: bazel

**What operating system (Linux, Windows, ...) and version?**
macos

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
`bazel build :protoc :protobuf`

**What did you expect to see**

`INFO: Build completed successfully`

**What did you see instead?**
```
ERROR: /external/com_google_absl/absl/debugging/BUILD.bazel:196:11: Compiling absl/debugging/internal/elf_mem_image.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@com_google_absl//absl/debugging:debugging_internal) external/local_config_cc/cc_wrapper.sh 

ccache: invalid option -- U

ERROR: Build did NOT complete successfully
```

when compiling on macos, if `ccache` is installed, bazel generates `cc_wrapper.sh` with invalid use of `ccache`
problem goes away if `ccache` is uninstalled
`CMakeLists.txt` option `protobuf_ALLOW_CCACHE` is ignored

**Comment by zhangskz** [comment]
Might be related to https://github.com/protocolbuffers/protobuf/issues/16314 which also seems to be macos / cmake / absl problems.

**Comment by mkruskal-google** [comment]
This looks like a bad bazel/ccache interaction.  Is this protobuf-specific or do you hit this in other projects (e.g. Abseil)?
