### ISSUE TITLE
utf8_range::utf8_validity is not automatically installed (and it can't easily be installed)

### ISSUE THREAD

**Issue by ProjectHSI** [protocolbuffers/protobuf#16334]
**What version of protobuf and what language are you using?**
Version: v26.0 (Tag)
Language: C++

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC. Dependent project with Ninja (default of Visual Studio), Protobuf with MSBuild (Ninja wouldn't work through command-line, don't know what magic Visual Studio does)

**What did you do?**
1. Build with MSVC (x64) (with a non-C: or non-default install prefix).
2. Install

**What did you expect to see**
The project is able to build, and it can compile .proto files.

**What did you see instead?**
An error with utf8_range that can't be resolved easily. (The following targets are referenced, but are missing: utf8_range::utf8_validity)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
1> [CMake]   Found package configuration file:
1> [CMake] 
1> [CMake]     D:/ProjectHSI/Development/Software/Env/CMakePrefix/protobuf/cmake/protobuf-config.cmake
1> [CMake] 
1> [CMake]   but it set protobuf_FOUND to FALSE so package "protobuf" is considered to
1> [CMake]   be NOT FOUND.  Reason given by package:
1> [CMake] 
1> [CMake]   The following imported targets are referenced, but are missing:
1> [CMake]   utf8_range::utf8_validity
```

**Anything else we should know about your project / environment**
Building with tests.

This might not be related to the Non-C: install path considering CMake *should* automatically handle that (and other projects can handle it just fine) but even if it's not related this is still a bug.

**Comment by ProjectHSI** [comment]
UPDATE:
> This might not be related to the Non-C: install path considering CMake should automatically handle that (and other projects can handle it just fine) but even if it's not related this is still a bug.

**Comment by LukeSkyD** [comment]
Same problem here i cannot seem to solve it anyway are there news about it?

**Comment by ProjectHSI** [comment]
@LukeSkyD workaround here: use a vendored copy of protobuf

**Comment by LukeSkyD** [comment]
> @LukeSkyD workaround here: use a vendored copy of protobuf

For now im using 3.20.1. i would prefer using the official one

**Comment by ProjectHSI** [comment]
> > @LukeSkyD workaround here: use a vendored copy of protobuf
> 
> Thanks! for now im using 3.20.1. i would prefer using the official one

maybe i'm using the wrong... terms here. i'm a newbie anyway.

by vendored i meant added as a subdirectory

**Comment by ntomer** [comment]
I came across this as well.  solved by adding the cmake variable utf8_range_DIR=C:/path_to/protobuf/lib/cmake/utf8_range`

**Comment by MasterpieceNKA** [comment]
I came across this too. I solved it by adding the directories with relevant cmake config files

# find Protobuf
set(PROTOBUF_SRC_ROOT_FOLDER "${CMAKE_CURRENT_LIST_DIR}/build/protobuf-install-dir")

set(absl_DIR "${PROTOBUF_SRC_ROOT_FOLDER}/lib/cmake/absl")
set(protobuf_DIR "${PROTOBUF_SRC_ROOT_FOLDER}/lib/cmake/protobuf")
set(utf8_range_DIR "${PROTOBUF_SRC_ROOT_FOLDER}/lib/cmake/utf8_range")

find_package(absl CONFIG REQUIRED)
find_package(protobuf CONFIG REQUIRED)
find_package(utf8_range CONFIG REQUIRED)
