### ISSUE TITLE
  target "libprotobuf-lite" which requires target "utf8_validity" that is not in the export set.

### ISSUE THREAD

**Issue by liangguohao66** [protocolbuffers/protobuf#16347]
# cmake /usr/src/go/protobuf-26.0/ -Dprotobuf_ABSL_PROVIDER=package   -DCMAKE_PREFIX_PATH=/usr/src/abseil-cpp-master/build/CMakeFiles/Export/lib64/cmake/absl    
-- 
-- 26.0.0
-- Configuring done
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf-lite" which requires target "utf8_validity" that is not in the export set.
CMake Error: install(EXPORT "protobuf-targets" ...) includes target "libprotobuf" which requires target "utf8_validity" that is not in the export set.
-- Generating done
-- Build files have been written to: /usr/src/go/protobuf-26.0

cmake version 3.13.0

**Comment by acozzette** [comment]
Thank you for the bug report, I will take a look at this on Monday. This may be related to #16334.
