### ISSUE TITLE
iOS Privacy manifest for Protobuf-3.19.4

### ISSUE THREAD

**Issue by naahmedea** [protocolbuffers/protobuf#16358]
Let's say we are using an old version of protobuf(3.19.4) that uses mach_absolute_time(). Based on the provided code, the mach_absolute_time() function is being used to generate a seed to ensure randomness, not to measure the amount of time that has elapsed between events or to perform calculations to enable timers. Therefore, it does not appear necessary to declare any of these reasons `35F9.1`, `8FFB.1`, `3D61.1`

Could some one please confirm on the above statement??

@zhangskz

**Comment by naahmedea** [comment]
@zhangskz  Latest version of protobuf is not compatible with our SDK, So we are planning to stay on 3.19.4. But that version uses mach_absolute_time() call, So any work around's and suggestions? cuz if that API is used then it will definitely fail app submission. Any suggestion to overcome this situation?

**Comment by zhangskz** [comment]
19.x is out of support, so we are not planning on adding further patches here.

I believe you could include required reasons (if needed) for the use of mach_absolute_time() directly in your privacy manifest rather than pulled from ours.

Why can't you update to ~25.x+? Our [news page](https://protobuf.dev/news/) and [migration guide](https://protobuf.dev/support/migration/) should provide some guidance around breaking changes if this is preventing you from moving off of 19.x+.

**Comment by zhangskz** [comment]
8FFB.1 seems like it might be the closest. @thomasvl do you have any additional guidance here?

It looks like a request can also be submitted to add additional required reasons, though I'm not sure the random seed thing we've already removed in currently supported releases would qualify:

"Apple continually reviews the list of required reason APIs and reasons for usage, and will update this article from time to time. If your app uses required reason API to provide benefits to the people using the app, for a reason that isn’t listed here, [submit a request for a new approved reason](https://developer.apple.com/contact/request/privacy-manifest-reason/)."
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#overview

**Comment by naahmedea** [comment]
@zhangskz , thank you for providing the reasoning behind the API usage.
@thomasvl , could you assist us by pointing out the specific commits we need to integrate to eliminate those API calls in 3.19.4? Alternatively, if you could provide a patch for version 3.19.4 to address this issue, that would be greatly beneficial for us.

**Comment by thomasvl** [comment]
https://github.com/protocolbuffers/protobuf/pull/15662 is the fix on the 26 branch.

**Comment by zhangskz** [comment]
The API call was removed from 25.x+ in https://github.com/protocolbuffers/protobuf/commit/76d05d4cb9200c371c8894df21f37ba4060bdc8a which is also our oldest supported version for C++. 

3.19.x out of support, so we're not planning on making further patch releases to it per our [version support policy](https://protobuf.dev/support/version-support/) -- we've already turned down a lot of infra associated with this release series. We could probably cherry pick the commit to the 3.19.x branch in github, but won't be doing a patch release.

**Comment by naahmedea** [comment]
Thanks @zhangskz!  Let us know once the 3.19.4 branch is ready with that commit.

**Comment by naahmedea** [comment]
Any update @zhangskz ?
