### ISSUE TITLE
Facilitate Swift Plugin 

### ISSUE THREAD

**Issue by abdelazizSalah** [protocolbuffers/protobuf#16356]
**What language does this apply to?**  => Swift
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
I found a high difficulty in installing proto buff on Mac, the process should be much easier than this.
**Describe the solution you'd like**
Make a clear way to facilitate installing protobuf on mac
**Describe alternatives you've considered**

**Additional context**

**Comment by shaod2** [comment]
Sorry to hear that. Can you give some more details about what difficultly you were facing that's related to Swift?

**Comment by thomasvl** [comment]
All you should need is `protoc`, which this project does include prebuilt binaries for with the releases.

If you have suggestions for the documentation on Swift Protobufs, I'm sure they would be welcome there and PRs to improve docs on either project are probably also appreciated.

**Comment by abdelazizSalah** [comment]
It was a complete nightmare actually to install protoc and put the release in the environment variables, because the documentations was not clear at all, so I suggest that we can enhance the documentation by adding a step by step Video link in the readme file to be able to install it easily, and I can make this video for you, and upload it on my channel on YouTube, and then you can just add the link in the readme file
