### ISSUE TITLE
[C#]Make ByteString implements `Count` instead of Length

### ISSUE THREAD

**Issue by yyjdelete** [protocolbuffers/protobuf#1635]
This should be like an Collection<byte> instead of Array, make it works like IReadOnlyList<byte> in .Net4.5, Some lib like `CompareNETObjects` depend on this to works with `public byte this[int index]`.
`
    "Indexer must have a corresponding Count property that is an integer for object .Data[0].Data.Empty"
`

**Comment by jskeet** [comment]
The point of `Length` isn't that it's like array - it's that it's like `String` (hence the name). We could potentially add `Count` *as well* of course...

**Comment by jskeet** [comment]
Given the lack of other users requesting this, I'm going to close this issue now. (I'd rather not add a redundant member without a really compelling reason.)
