### ISSUE TITLE
/usr/include/c++/11/ctime:62:11: error: ‘tm’ has not been declared in ‘::’    62 |   using ::tm;

### ISSUE THREAD

**Issue by ssssaf** [protocolbuffers/protobuf#16359]
I get an error when I use cmake to build protobuf , It's reporting an error in the standard library, and I don't understand why
In file included from ./time.h:80,
                 from /usr/include/c++/11/ctime:42,
                 from /usr/include/c++/11/chrono:42,
                 from /root/medium/protobuf/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_if.h:18,
                 from /root/medium/protobuf/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_if.cc:15:
/usr/include/c++/11/ctime:62:11: error: ‘tm’ has not been declared in ‘::’
   62 |   using ::tm;
      |           ^~
/usr/include/c++/11/ctime:64:11: error: ‘clock’ has not been declared in ‘::’
   64 |   using ::clock;
      |           ^~~~~
/usr/include/c++/11/ctime:65:11: error: ‘difftime’ has not been declared in ‘::’
   65 |   using ::difftime;
      |           ^~~~~~~~
/usr/include/c++/11/ctime:66:11: error: ‘mktime’ has not been declared in ‘::’
   66 |   using ::mktime;
      |           ^~~~~~
/usr/include/c++/11/ctime:67:11: error: ‘time’ has not been declared in ‘::’
   67 |   using ::time;
      |           ^~~~
/usr/include/c++/11/ctime:68:11: error: ‘asctime’ has not been declared in ‘::’
   68 |   using ::asctime;
      |           ^~~~~~~
/usr/include/c++/11/ctime:69:11: error: ‘ctime’ has not been declared in ‘::’
   69 |   using ::ctime;
      |           ^~~~~
/usr/include/c++/11/ctime:70:11: error: ‘gmtime’ has not been declared in ‘::’
   70 |   using ::gmtime;
      |           ^~~~~~
/usr/include/c++/11/ctime:71:11: error: ‘localtime’ has not been declared in ‘::’
   71 |   using ::localtime;
      |           ^~~~~~~~~
/usr/include/c++/11/ctime:72:11: error: ‘strftime’ has not been declared in ‘::’
   72 |   using ::strftime;
      |           ^~~~~~~~

**Comment by shaod2** [comment]
How to reproduce the error? What protobuf version you're using?
