### ISSUE TITLE
editions: how to prevent use of new "string_type" feature in edition 2023?

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#16369]
A new `string_type` feature was recently added to `google/protobuf/cpp_features.proto`, and some validation was added requiring the new feature be used instead of the `ctype` field option in edition 2024.

This appears to be a new 2024-specific feature. However, `protoc` does not complain if I use `string_type` in my file that indicates `edition = "2023"`. I can compile the file using the newer `descriptor.proto` with `protoc` v26, but I am also allowed to compile the file and use the new feature when using a `protoc` built from the latest main branch (b497787aef641e52846514c1ec60be9a18805590).

Before this new feature finds its way into a release (v27?) I suspect some new mechanism (like a new `FieldOption`) is needed to indicate the edition in which a feature was introduced, so that when compiling files for older editions, references to newer features can be prevented.

**Comment by jhump** [comment]
I guess this was good timing, since this issue appears to be addressed by a commit that was pushed very shortly after I filed this: b09b3e46fe2a111d412251f6d043649334e9cbee

**Comment by mkruskal-google** [comment]
Hah yea @thomasvl flagged this kind of issue a few weeks ago, and I have a design I'm working on implementing as we speak to get this in before 27.0.

As for `string_type`, we decided to actually release this for edition 2023.  As it stands now, we'll be allowing *either* `ctype` or `string_type` in 2023 (not ideal but it's hard to undo this decision internally), and only `string_type` in 2024+

**Comment by jhump** [comment]
@mkruskal-google, I just thought of a related issue: if new values are added to an existing enum, for example if an `ALWAYS_SERIALIZE` option were added to `FeatureSet.FieldPresence` (which is something mentioned in one of the design docs as a step towards removing support for `LEGACY_REQUIRED`), how would one prevent an older edition file (like 2023) from referencing the newer value? I think `EnumValueOptions` may also need an `optional FeatureSupport feature_support` field.

**Comment by jhump** [comment]
@mkruskal-google, would it be helpful if I create a separate issue for feature lifetime of enum values (see previous paragraph)?
