### ISSUE TITLE
Python Collision for Enums using underscores

### ISSUE THREAD

**Issue by shelilevine** [protocolbuffers/protobuf#16375]
**What version of protobuf and what language are you using?**
Version: 4.21.3
Language: Python

**What operating system (Linux, Windows, ...) and version?**.  MacOS Sonoma 14.3.1 M1 

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.11

**What did you do?**
running protoc on proto file with the below message type. (we are using grpc_tools.protoc for this) 

`enum Category {
    CAT1_1 = 0;
    CAT1_2 = 1;
    CAT11 = 2;
    CAT11_1 = 3;
}
`

**What did you expect to see**
Proto is compiled successfully

**What did you see instead?**
Proto compiling fails with error.  
Imports of problematic file fail `Import example.proto was not found or had errors`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

The below message is also shown
`Enum name CAT11 has the same name as CAT1_1 if you ignore case and strip out the enum name prefix (if any). (If you are using allow_alias, please assign the same numeric value to both enums.)`

when problematic enums are removed, proto file is compiled successfully. 

**Anything else we should know about your project / environment**

**Comment by shaod2** [comment]
I think the original intention is to distinguish the `CamelCase` names inferred from the enum name. For example, "MY_FOO" and "MyFoo" should have the same value.

**Comment by shelilevine** [comment]
This is a breaking change and we cannot easily update our proto schema.  Is there a reason this cannot be supported?
