### ISSUE TITLE
Macos M2 Docker image create while error occure protoc: stdout: . stderr: terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by amraupward** [protocolbuffers/protobuf#16399]
![Screenshot 2024-04-03 at 18 56 55](https://github.com/protocolbuffers/protobuf/assets/154990295/3cb46985-a96a-4e58-928b-b12ba5a70a2b)

build.gradle and docker.docker file is here
![Screenshot 2024-04-03 at 18 56 28](https://github.com/protocolbuffers/protobuf/assets/154990295/17ccfdc0-7d8d-4720-acd4-192bf86e0f32)
![Screenshot 2024-04-03 at 18 56 48](https://github.com/protocolbuffers/protobuf/assets/154990295/e503c161-95dd-43d6-b3bb-f217329249d0)

How to fix this in M2 Macos? 
I tried osx-aarch, osx_x86-64 protocs. still same error occured. 
HELP ME PLEASE?..

**Comment by amraupward** [comment]
<img width="1002" alt="Screenshot 2024-04-03 at 19 34 14" src="https://github.com/protocolbuffers/protobuf/assets/154990295/2450f499-361b-49f7-8403-2a64c4c5e8ba">


still same error occured. I tried below protobuf configurations in my build.gradle

protobuf {
    protoc {
        if (project.hasProperty('protoc_platform')) {
            artifact = "com.google.protobuf:protoc:3.25.3:${protoc_platform}"
        } else {
            artifact = "com.google.protobuf:protoc:3.25.3"
        }
//            artifact = 'com.google.protobuf:protoc:3.25.3'
    }
    plugins {
        grpc {
            if (project.hasProperty('protoc_platform')) {
                artifact = "io.grpc:protoc-gen-grpc-java:1.62.2:${protoc_platform}"
            } else {
                artifact = 'io.grpc:protoc-gen-grpc-java:1.62.2'
            }
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

**Comment by amraupward** [comment]
<img width="1878" alt="Screenshot 2024-04-03 at 20 15 56" src="https://github.com/protocolbuffers/protobuf/assets/154990295/b9bed4b2-6daf-473f-934f-3bceeb5e04eb">

**Comment by zhangskz** [comment]
I think the error seems to be coming from https://github.com/google/protobuf-gradle-plugin or https://github.com/grpc/grpc-java (e.g. does the prootobuf-gradle-plugin version you're using support grpc-java 1.62.2 or protoc 25.3?). You might want to file this there, since neither of those are owned by this repo.

Please reopen if this seems to require a fix in the protobuf 25.x release!
