### ISSUE TITLE
--version should indicate beta version

### ISSUE THREAD

**Issue by cwelton** [protocolbuffers/protobuf#1639]
Currently `protoc --version` produces `libprotoc 3.0.0` for beta-1, beta-2, and beta-3 builds, which makes it very difficult to tell which beta version of protobuf you have installed.

This is a problem when the beta builds are not compatible and issues such as  https://github.com/google/protobuf/issues/1605 make it impractical to use beta-3 with java, while beta-2 is  viable.

**Comment by mkruskal-google** [comment]
@deannagarcia This sounds reasonable to me.  Is there any reason not to include rc numbers in the version?  Feel free to assign back to me if you agree

**Comment by deannagarcia** [comment]
This has already been implemented, but we are now using release candidates.
