### ISSUE TITLE
issue with upgrade com.google.protobuf:protobuf-java  to 4.26.1

### ISSUE THREAD

**Issue by rakum23** [protocolbuffers/protobuf#16409]
**What version of protobuf and what language are you using?**
Version: V 4.26.1
Language: Java

**What operating system (Linux, Windows, ...) and version?
iOs

**What runtime / compiler are you using (e.g., python version or gcc version)**
Mavan

RUN:
./mvnw package to add jar

Error like:
/target/generated-sources/com/ingka/rc/protobuf/AuditLogProto.java:[892,34] cannot find symbol
[ERROR]   symbol:   class SingleFieldBuilderV3
[ERROR]   location: package com.google.protobuf

/target/generated-sources/com/ingka/rc/protobuf/ItemKeyProto.java:[44,26] cannot find symbol
[ERROR]   symbol:   class GeneratedMessageV3
[ERROR]   location: package com.google.protobuf

**Comment by shaod2** [comment]
You probably need to re-generate the Java proto code, as GeneratedMessageV3 is gone in the [v26.0 release](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0)

**Comment by rakum23** [comment]
I am trying to generate but it always refer to GeneratedMessageV3, as i know this "GeneratedMessage/GeneratedMessageV3 is not supposed to be referenced directly by users code." does any change needed in the message decleartion, I am using syntax = "proto3";
