### ISSUE TITLE
SerializeToArray and SerializeToOstream getting a difference result?

### ISSUE THREAD

**Issue by kiraYuukiAsuna** [protocolbuffers/protobuf#16410]
**What version of protobuf and what language are you using?**
Version: 3.21.12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
complied by msvc

**What did you do?**

my proto message schema:
```
syntax = "proto3";

message Info {
    string wi = 1;
}

message AddressBook {
    string name = 1;
    string age = 3;
    Info info = 4;
}
```

c++ code:
```
#include "schema.pb.h"
#include <fstream>
#include <format>
#include "google/protobuf/util/json_util.h"

int main() {
    AddressBook address_book;
    address_book.set_name("My Address Book");
    address_book.set_age("12");
    address_book.mutable_info()->set_wi("1234");
    std::ofstream out("address_book.bin");
    address_book.SerializeToOstream(&out);
    out.close();

    std::string json;
    google::protobuf::util::JsonPrintOptions options;
    options.add_whitespace = true;
    options.always_print_primitive_fields = true;
    options.preserve_proto_field_names = true;
     MessageToJsonString(address_book, &json, options).ok();
    std::cout<<json<<std::endl;

    std::vector<char> array;
    array.resize(address_book.ByteSizeLong());
    address_book.SerializeToArray(array.data(), array.size());

    for(auto& c: array) {
        std::cout<<std::format("{:02x}", c);
    }
}
```

file 'address_book.bin' content generated by SerializeToOstream:
```
0D 0A 0F 4D 79 20 41 64 64 72 65 73 73 20 42 6F
6F 6B 1A 02 31 32 22 06 0D 0A 04 31 32 33 34
```

binary content generated by SerializeToArray:
```
0a0f4d79204164647265737320426f6f6b1a02313222060a0431323334
```

This is obvious that two binary sequence is not the same.

Binary sequence generated by SerializeToOstream have two extra byte '0D' at the beginning and the middle.

**What did you expect to see**
Using SerializeToOstream and SerializeToArray to generate binary sequence should have the same content?

**What did you see instead?**
Generated two binary sequence is not the same using SerializeToOstream and SerializeToArray.

**Comment by shaod2** [comment]
I feel like `OD OA` are carriage return and line feed, if you open and save the file with text mode. If you read with e.g. `fopen(filename, "wb")`, it should roundtrip correctly

**Comment by kiraYuukiAsuna** [comment]
> I feel like `OD OA` are carriage return and line feed, if you open and save the file with text mode. If you read with e.g. `fopen(filename, "wb")`, it should roundtrip correctly

Yes! Indeed it caused by open and save file with text mode. I didn't pay attention to the file open mode. Thanks for your reply!
