### ISSUE TITLE
abseil-cpp, absl in thirdparty conflict with abseil-cpp, absl in unreal5 project

### ISSUE THREAD

**Issue by kdongin** [protocolbuffers/protobuf#16450]
i am trying to include protobuf lastest version 3.26.1 (ver 2024-04) in unreal 5. (i am using vs2022 community)

when i include protobuf using thirdparty abseil-cpp,
i face compile error C2373(redefinition). like below

-----------------------------
Error	C2373	'absl::container_internal::node_type': redefinition; different type modifiers	TestProtoForUnreal	C:\Users\blackstorm_kdongin\Documents\Unreal Projects\TestProtoForUnreal\Source\ThirdParty\abseilcpp\absl\container\internal\btree.h	1653		
------------------------------
 it seems that absl\container\internal\btree.h causes that error.
i assume that it conflicts with another absl\btree.h included unreal engine 5 some where.
i found out several same abseil in unreal engine 5.
could you fix or recommend a workaround????

**Comment by zhangskz** [comment]
Are the other absl's in your project imported under a different name than `com_google_absl`?

Protobuf pulls in an absl version automatically via [`protobuf_deps.bzl`](https://github.com/protocolbuffers/protobuf/blob/59d8afde6b580d3824e8d52a8bdfbbf45949552b/protobuf_deps.bzl#L42) if one is not already found per https://github.com/protocolbuffers/protobuf/blob/59d8afde6b580d3824e8d52a8bdfbbf45949552b/protobuf_deps.bzl#L42

Perhaps you may need to rename / upgrade your other installs to `com_google_absl` to avoid multiple absl's causing problems here?
