### ISSUE TITLE
Clarify the license of utf8_range

### ISSUE THREAD

**Issue by takeh1k0** [protocolbuffers/protobuf#16457]
**What language does this apply to?**

N/A

**Describe the problem you are trying to solve.**

[utf8_range](https://github.com/protocolbuffers/utf8_range) was moved to the protobuf repository on November 9, 2023, but the license of the source code after the move is unclear.

[The license file](https://github.com/protocolbuffers/protobuf/blob/main/third_party/utf8_range/LICENSE) exists in the `third_party/utf8_range` directory, but since this directory was copied from the original repository, it is not clear if this license still applies.

**Describe the solution you'd like**

If the license of `utf8_range` has not been discussed and the license can be changed, I would like the license to be changed to the same license as `protobuf` .

**Describe alternatives you've considered**

If the current `utf8_range` license is identical to `protobuf`, the old LICENSE file should be deleted.

If it is different from the license of `protobuf`, it should be mentioned in the `README` of protobuf, etc. so that it is easy to understand.

**Additional context**

nothing

**Comment by zhangskz** [comment]
@acozzette Can you investigate if the license file can / should be change given the repo move, or if this needs to be documented accordingly?

**Comment by acozzette** [comment]
Unfortunately I don't think we can change the license. From what I understand, we originally forked utf8_range from another project, and as a result we don't own the full copyright.
