### ISSUE TITLE
"warning: refname 'HEAD' is ambiguous" is shown.

### ISSUE THREAD

**Issue by justoneplanet** [protocolbuffers/protobuf#16520]
The tag name "[head](https://github.com/protocolbuffers/protobuf/tags)" might be problematic.

**What version of protobuf and what language are you using?**

The latest repository of protobuf regardless of the language.

**What operating system (Linux, Windows, ...) and version?**

macOS 14.3.1 

**What did you do?**

1. `git status` shows "On branch main..."
2. `git fetch`
3. `git status`

**What did you expect to see**

"On branch main..." is shown again.

**What did you see instead?**

The following warning is shown.

```txt
warning: refname 'HEAD' is ambiguous.
warning: refname 'HEAD' is ambiguous.
On branch main
...
```

**Comment by zhangskz** [comment]
Thanks for reporting -- I don't think the `head` tag (and `vhead`) was pushed intentionally and has since been deleted after we received a similar report internally. This should be fixed now, but please reopen if you're still having issues here
