### ISSUE TITLE
Protocol Buffers Python API Reference for v5.x is missing

### ISSUE THREAD

**Issue by aliaugmenta** [protocolbuffers/protobuf#16550]
**What version of protobuf and what language are you using?**
Version: 5.x  
Language: Python

**What operating system (Linux, Windows, ...) and version?**
NA 

**What runtime / compiler are you using (e.g., python version or gcc version)**
NA 

**What did you do?**
NA 

**What did you expect to see**
I expect to see v5.x in https://googleapis.dev/python/protobuf/latest/index.html. 

**What did you see instead?**
The latest version documented is 4.21.1.

![image](https://github.com/protocolbuffers/protobuf/assets/59850288/6718d397-8ea4-46e8-901a-b54080685760)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by Logofile** [comment]
This is perfect timing for your issue! I've just taken ownership this quarter to fix our reference documentation generation infrastructure so that we can get the refdocs updated. I will let you know when the Python docs are brought current.

**Comment by nibudd** [comment]
any progress on this? My team just ran into a dependency issue that ultimately was the result of using outdated reference docs (leading us to believe a function that no longer existed does exist)

**Comment by Logofile** [comment]
The task for fixing our refdocs generation process rolled over to this current quarter. I don't have an ETA for this effort outside of a goal of the current quarter.
