### ISSUE TITLE
Segmentation fault build failure when building on MacOS

### ISSUE THREAD

**Issue by nabilwadih** [protocolbuffers/protobuf#16575]
**What version of protobuf and what language are you using?**
We are depending on version 26.0 from the Bazel Central Registry
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS Arm 14.4.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
Building with bazel 7.1.0-homebrew

**What did you do?**
1. include this line in your MODULE.bazel
bazel_dep(name = "protobuf", version = "26.0", repo_name = "com_google_protobuf")

2. Create a build target which references this
3. Attempt to build on MacOS: bazel build <your target>

**What did you expect to see**
A succesfull build

**What did you see instead?**
ERROR: /private/var/tmp/_bazel_nwadih/87360afb55bf1d415338954b6c465e8c/external/protobuf~/BUILD.bazel:225:10: Linking external/protobuf~/protoc [for tool] failed: (Exit 1): sandbox-exec failed: error executing CppLink command
...
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_nwadih/87360afb55bf1d415338954b6c465e8c/sandbox/darwin-sandbox/2933/sandbox.sb /var/tmp/_bazel_nwadih/install/c4c3c76558a4c3b15295977186b3bb0a/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_nwadih/87360afb55bf1d415338954b6c465e8c/sandbox/darwin-sandbox/2933/stats.out' external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt-exec-ST-13d3ddad9198/bin/external/protobuf~/protoc-2.params)
ld64.lld: warning: option -L/usr/local/lib references a non-directory path
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by nabilwadih** [comment]
This ended up being fixed by switching to using AppleClang which comes with Xcode installation, instead of using a brew installed version of llvm

**Comment by spaghettifunk** [comment]
Thank you @nabilwadih so much for the resolution! Took me weeks of constant trial-and-error until I bumbed to this message! Removing `llvm` from homebrew was the key 🚀
