### ISSUE TITLE
 v27.0-rc1 breaks tagging for archives multiple builds taking the latest tag breaks due to extra - in file name

### ISSUE THREAD

**Issue by ami-descope** [protocolbuffers/protobuf#16571]
**What did you do?**
1. download the latest tag and build the download url using the latest tag
2. 
    ```bash
    PROTBUF_LATEST_RELEASE=$(curl --retry 3 --retry-delay 5 --silent 
   "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
      PROTOC_VERSION=${PROTBUF_LATEST_RELEASE:1}
     unzip "protoc-${PROTOC_VERSION}-linux-x86_64.zip" -d protoc
   ```

3. the file name is `https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc-1-linux-x86_64.zip`
4. unable to unzip because its mismatc the tag name which is  `v27.0-rc1`
bad url => https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc1-linux-x86_64.zip

**What did you expect to see**
file name should match the tag name

**What did you see instead?**
extra dash between the rc and the 1 

**Anything else we should know about your project / environment**
Yes, can you please not tag latest  for release candidate?

**Comment by tbertran** [comment]
FWIW same issue with the Win64 file
![image](https://github.com/protocolbuffers/protobuf/assets/2054914/fcd947df-5140-431a-9c81-033adb4567f2)

**Comment by j6u** [comment]
+1

**Comment by ami-descope** [comment]
@mkruskal-google sorry for tagging you here, but maybe you can help route it faster to the person who can fix this?

Currently we have over 20 repo's that are using the latest tag and this breaks our CI/CD pipelines, so its kinda urgent to fix

Any chance you can help us with the routing of this issue?

**Comment by tbertran** [comment]
It may not be helpful to everyone but fixing the version number to the latest usable one (`26.1`) fixed it for me:
```
"config": {
    "protocVersion": "26.1"
 }
```
See https://www.npmjs.com/package/@protobuf-ts/protoc#user-content-installing-a-specific-version

**Comment by ami-descope** [comment]
yeah, i would have to do over 20 PRs to my services to fix it like that

**Comment by anuraaga** [comment]
I also noticed this though not quite in a broken way, just didn't expect my auto-update script to run

https://github.com/wasilibs/go-protoc-gen-builtins/pull/29

Was it intended to mark an RC as latest release instead of prerelease? Perhaps the release should be edited to switch it to prerelease.

**Comment by timostamm** [comment]
> Perhaps the release should be edited to switch it to prerelease.

That would be very helpful. 

Unlike previous pre-releases such as [v25.0-rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v25.0-rc1), the new [v27.0-rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1) is set as the latest release on GitHub.

Tools that automatically install `protoc` would typically use the GitHub URL https://github.com/protocolbuffers/protobuf/releases/latest to retrieve the latest stable version.

Since v27.0-rc1 is set as latest, such tools will will install the unstable pre-release.

**Comment by zhangskz** [comment]
RC's are normally marked pre-release and not latest. Looks like somehow 27.0-rc1 was accidentally marked as latest instead of pre-release, which was not intentional. This should be fixed now, but please reopen if this is still affecting you. Apologies for the noise!
