### ISSUE TITLE
Generate the pre-built protoc like maven repo

### ISSUE THREAD

**Issue by DingliZhang** [protocolbuffers/protobuf#16582]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
Similar to this question:
https://github.com/protocolbuffers/protobuf/issues/14402
I want to manually generate the following files by myself:
https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.7.1/protoc-3.7.1-linux-x86_64.exe

I followed this documentation:
https://github.com/protocolbuffers/protobuf/blob/v3.7.1/src/README.md
And with the `./configure --disable-shared` parameter, the `protoc` file size generated by `make install` is 67MB, which is much larger than the exe file on maven repo.
I would like to ask how to manually generate the pre-built files in the maven repo?

Thanks a lot!

**Describe the solution you'd like**
Manually generate the following files by myself:
https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.7.1/protoc-3.7.1-linux-x86_64.exe

**Describe alternatives you've considered**

**Additional context**

**Comment by DingliZhang** [comment]
@hlopko Could you give some advice please? Thank you very much.

**Comment by zhangskz** [comment]
Is it intentional that you're linking to release / documentation from v3.7.1? This is a *very* old release, and you should probably move to a supported protobuf version instead: https://protobuf.dev/support/version-support/

Can you elaborate more on why you need to manually generate our prebuilts? Using the artifacts published to maven is recommended.

We generate these artifacts via internally using the [`protoc_release`](https://github.com/protocolbuffers/protobuf/blob/734729afc2ace9dc33e41b91a34fd16bb53594d9/pkg/BUILD.bazel#L87) bazel target and `--config=linux-x86_64`.

**Comment by DingliZhang** [comment]
> Is it intentional that you're linking to release / documentation from v3.7.1? This is a _very_ old release, and you should probably move to a supported protobuf version instead: https://protobuf.dev/support/version-support/
> 
> Can you elaborate more on why you need to manually generate our prebuilts? Using the artifacts published to maven is recommended.
> 
> We generate these artifacts via internally using the [`protoc_release`](https://github.com/protocolbuffers/protobuf/blob/734729afc2ace9dc33e41b91a34fd16bb53594d9/pkg/BUILD.bazel#L87) bazel target and `--config=linux-x86_64`.

Thank you for your patience and timely response!
Similar to the https://github.com/protocolbuffers/protobuf/issues/14402 issue, but what I'm trying to do is to use the artifacts on RISC-V. The following error was reported when I build other maven projects on RISC-V:
```
[ 8292s] [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile (src-compile-protoc) on project hadoop-common: Missing:
[ 8292s] [ERROR] ----------
[ 8292s] [ERROR] 1) com.google.protobuf:protoc:exe:linux-riscv64:3.7.1
[ 8292s] [ERROR] 
[ 8292s] [ERROR]   Try downloading the file manually from the project website.
[ 8292s] [ERROR] 
[ 8292s] [ERROR]   Then, install it using the command: 
[ 8292s] [ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.7.1 -Dclassifier=linux-riscv64 -Dpackaging=exe -Dfile=/path/to/file
[ 8292s] [ERROR] 
[ 8292s] [ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ 8292s] [ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.7.1 -Dclassifier=linux-riscv64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ 8292s] [ERROR] 
[ 8292s] [ERROR]   Path to dependency: 
[ 8292s] [ERROR]   	1) org.apache.hadoop:hadoop-common:jar:3.3.6
[ 8292s] [ERROR]   	2) com.google.protobuf:protoc:exe:linux-riscv64:3.7.1
```
It seems that the latest version is also not released for RISC-V, so I have to follow the error and build protoc manually.
Thanks again for your help!

**Comment by DingliZhang** [comment]
For v3.7.1, it's useful to cross-compile on x86 for riscv64:
https://github.com/DingliZhang/protobuf/commit/648d55f2d96ed3a5b1ae4b5d430c04a8acb552f1
