### ISSUE TITLE
Fatal error: Uncaught Google\Protobuf\Internal\GPBDecodeException

### ISSUE THREAD

**Issue by MiDo-kun** [protocolbuffers/protobuf#16645]
Fatal error: Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected EOF inside fixed32. in /var/www/vhosts/clickfraudfree.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:313 Stack trace: #0 /var/www/vhosts/clickfraudfree.com/httpdocs/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(490):

**Comment by zhangskz** [comment]
Please provide more details on what resulted in this error, and ideally a repro to make this issue actionable.
