### ISSUE TITLE
Messy code when returning Chinese characters

### ISSUE THREAD

**Issue by Juice007** [protocolbuffers/protobuf#16657]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 
Language:GO、Objective-C

**What operating system (Linux, Windows, ...) and version?**
iOS

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1、When the request returns Chinese, iOS get a unicode code in the response header:
<img width="874" alt="image" src="https://github.com/protocolbuffers/protobuf/assets/16225027/67c42909-59f7-477c-b769-a9cc97e32567">
Decoding into Chinese is a mess
```
\U00e7\U0094\U00a8\U00e6\U0088\U00b7\U00e4\U00b8\U008d\U00e5\U00ad\U0098\U00e5\U009c\U00a8
```
mess code :
```
ç¨æ·ä¸å­å¨
```
expected Chinese:用户不存在

**Comment by puellanivis** [comment]
It looks like this has taken UTF-8 encoded text and turned the encoded bytes into individual code points. Instead of decoding to UTF-8 and then encoding those codepoints into `\U` codes. When converting this to the individual bytes, the proper Chinese text is produced.

**Comment by Juice007** [comment]
> It looks like this has taken UTF-8 encoded text and turned the encoded bytes into individual code points. Instead of decoding to UTF-8 and then encoding those codepoints into `\U` codes. When converting this to the individual bytes, the proper Chinese text is produced.

Sorry. I'm still a little confused about what you mean.

**Comment by Juice007** [comment]
@puellanivis Can you tell me in detail what I should do?

**Comment by Juice007** [comment]
Thanks @puellanivis !
Our final solution is that the resp returns the urlencoded Chinese string, and the client urldecode the string, which solves the problem
urlencoded string: `%E7%94%A8%E6%88%B7%E4%B8%8D%E5%AD%98%E5%9C%A8%0A`
urldecoded string:`用户不存在`
