### ISSUE TITLE
editions: compiler disallows extension to have default value when file sets default presence to implicit

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#16664]
Extensions [always have explicit presence](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.cc#L3927). If an attempt is made to set the `field_presence` feature to `IMPLICIT`, the result is an error: "Extensions can't specify field presence".

Unfortunately, if the file default is set to `IMPLICIT`, `protoc` is acting as if the extension's field presence inherits this and does not allow setting a default value.
```proto
// test.proto
edition = "2023";
option features.field_presence = IMPLICIT;
message Extendee {
  extensions 1 to 2;
}
extend Extendee {
  uint32 ext_with_default = 1 [default = 123];
}
```

```
test.proto:8:10: Implicit presence fields can't specify defaults.
```

**Comment by mkruskal-google** [comment]
Nice, thanks for the thoroughness here Josh :)

**Comment by mkruskal-google** [comment]
This turned up a related issue: repeated closed enum fields are an error condition when they "inherit" IMPLICIT presence

**Comment by mkruskal-google** [comment]
Yep, I'm changing the validation check to use `has_presence` (i.e. the actual computed behavior) instead of the resolved feature value
