### ISSUE TITLE
python: invalid uint32_t value convertion

### ISSUE THREAD

**Issue by alxn1** [protocolbuffers/protobuf#16674]
Version: 27.0-rc1 (and older versions, up to 624d29d commit, but maybe i'm wrong).
Language: Python
OS: Linux
Python 3.11, protobuf installed from pip with --cpp_implementation flag

Big uint32_t values from protobuf (encoded by C++ code) from python side is are negative
And problem is [here](https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/pyext/message.cc#L2051): PyLong_FromSsize_t should be replaced by PyLong_FromUnsignedLong (or PyLong_FromSize_t, i'm not sure).

**Comment by anandolee** [comment]
Thank you Alexander  to raise it up. Can you help to give an example code to show the bug?
