### ISSUE TITLE
WithPreserveProtoFieldNames and JsonParser

### ISSUE THREAD

**Issue by jamiewinder** [protocolbuffers/protobuf#16709]
In C# (and in general), if an `IMessage` is formatted as JSON with `PreserveProtoFieldNames` enabled, is there a way tell the `JsonParser` (or some other parse utility) to expect the fields in the same format?

**Comment by puellanivis** [comment]
As far as I understand it, parsers are required to accept both: (from the JSON mapping section of the standard)
> Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name.
