### ISSUE TITLE
CMake fails to find abslConfig.cmake/absl-config.cmake

### ISSUE THREAD

**Issue by suhani-goel** [protocolbuffers/protobuf#16732]
**What version of protobuf and what language are you using?**
Version: 4.25.3

**What operating system (Linux, Windows, ...) and version?**
RHEL7

Below error while trying to build protobuf. Tried including -DBUILD_DEPS:BOOL=ON but didn't work.

CMake Error at cmake/abseil-cpp.cmake:36 (find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:294 (include)

-- Configuring incomplete, errors occurred!

**Comment by PurpleVsGreen** [comment]
I have this exact same issue on Gentoo.

`dev-cpp/abseil-cpp` is installed, of course.

**Comment by PurpleVsGreen** [comment]
I think the funny bug is actually in abseil because when I build gtest, it gives the exact same error.

(Also, cmake is itself a bug.)
