### ISSUE TITLE
absl/base/attributes.h: No such file or directory

### ISSUE THREAD

**Issue by sgavathe** [protocolbuffers/protobuf#16755]
**What version of protobuf and what language are you using?**
Version: protobuf-25.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

I have compiled the protobuf using following commands and I have a dependency that is defined as well where it does not complain about dependencies any more. 

```
RUN cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=17 -DBUILD_DEPS=ON
# RUN mkdir build && cd build
RUN cmake -S . -B build
RUN cmake --build build && \
    cmake --install build --prefix .
```
    
**What did you expect to see**
build with no error

**What did you see instead?**
```
/usr/local/include/google/protobuf/port_def.inc:33:10: fatal error: absl/base/attributes.h: No such file or directory
   33 | #include "absl/base/attributes.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/model.dir/build.make:76: CMakeFiles/model.dir/src/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/model.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
Error running a cmake --build command: exit status 2
 ```

**Anything else we should know about your project / environment**
So I am not sure, where absl needs to be installed so protobuf can see it in it's path.

**Comment by tamaroning** [comment]
Has this been really fixed?
I installed version 28.2 and encountered the same issue.

**Comment by Aman-Surkar** [comment]
Can you pls paste the paths where did you install abseilcpp and how protobuf picked it up?
