### ISSUE TITLE
[C#] ByteString lacks ability to efficiently copy data in segments

### ISSUE THREAD

**Issue by warrenfalk** [protocolbuffers/protobuf#1682]
ByteString has the following method:

``` csharp
//  Copies all bytes of the byte array to dest at destOffset
void CopyTo(byte[] dest, int destOffset);
```

But lacks an overload like this

``` csharp
// Copies srcLength bytes from srcOffset of the byte array to dest at destOffset
void CopyTo(byte[] dest, int destOffset, int srcOffset, int srcLength);
```

Is there any way to efficiently grab a subset of the data in an efficient manner (other than a single byte at a time?)

Besides other uses, this would make it possible to construct a ByteStringStream that could be passed into functions looking for a Stream, without having to first copy all data to another buffer just so it can be wrapped in a MemoryStream.

**Comment by wanton7** [comment]
Just had this problem. I had to allocate temp byte array to copy ByteString to., then copy segment I needed from it.

**Comment by jskeet** [comment]
As now support viewing a `ByteString` as a `ReadOnlyMemory<byte>` (via the `Memory` property) or `ReadOnlySpan<byte>` (via the `Span` property) both of which support efficient slicing.

One scenario that *doesn't* help with is creating a stream, unless you take a dependency on `Microsoft.Toolkit.HighPerformance`. We could fairly easily add an `AsStream` method to create a read-only MemoryStream though, so I'll leave this issue open for now.

**Comment by jskeet** [comment]
> We could fairly easily add an AsStream method to create a read-only MemoryStream though

Urgh - no we can't, as MemoryStream doesn't have any overloads accepting anything other than an array either. We'd basically have to recreate the code from Microsoft.Toolkit.HighPerformance.
