### ISSUE TITLE
[Build] Failure to build with "no matching function for call to 'StrongPointer()'"

### ISSUE THREAD

**Issue by veblush** [protocolbuffers/protobuf#16868]
**What version of protobuf and what language are you using?**

Protobuf commit [9f40411](https://github.com/protocolbuffers/protobuf/commit/9f40411caf070c2848281a507529e4f5506dc22d)

**What operating system (Linux, Windows, ...) and version?**

Linux Debian 11 using Docker 

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc 12

**What did you do?**

Build protoc using cmake

**What did you expect to see**

Successful build

**What did you see instead?**

Build failure with [log](https://btx.cloud.google.com/invocations/9cdf3c94-812d-4b43-ab58-b3e38d0b1403/log)

```
[ 53%] Building CXX object third_party/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set_heavy.cc.o
In file included from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/extension_set.h:34,
                 from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/descriptor.h:56,
                 from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/parser.h:24,
                 from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/parser.cc:14:
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h: In instantiation of 'void google::protobuf::internal::StrongReferenceToType() [with T = google::protobuf::UninterpretedOption]':
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/message_lite.h:923:37:   required from 'const T* google::protobuf::DownCastToGenerated(const google::protobuf::MessageLite*) [with T = google::protobuf::UninterpretedOption]'
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/message_lite.h:933:29:   required from 'T* google::protobuf::DownCastToGenerated(google::protobuf::MessageLite*) [with T = google::protobuf::UninterpretedOption]'
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/parser.cc:1568:47:   required from here
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:72:43: error: no matching function for call to 'StrongPointer()'
   72 |   return StrongPointer();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:43:36: note: candidate: 'template void google::protobuf::internal::StrongPointer(T*)'
   43 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer(T* var) {
      |                                    ^~~~~~~~~~~~~
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:43:36: note:   template argument deduction/substitution failed:
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:72:43: error: wrong number of template arguments (2, should be 1)
   72 |   return StrongPointer();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:43:36: note: provided for 'template void google::protobuf::internal::StrongPointer(T*)'
   43 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer(T* var) {
      |                                    ^~~~~~~~~~~~~
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:54:36: note: candidate: 'template void google::protobuf::internal::StrongPointer()'
   54 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer() {
      |                                    ^~~~~~~~~~~~~
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:54:36: note:   template argument deduction/substitution failed:
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/port.h:72:43: error: could not convert template argument 'ptr' from 'const google::protobuf::UninterpretedOption& (* const)()' to 'const google::protobuf::UninterpretedOption& (* const)()'
   72 |   return StrongPointer();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```
**Anything else we should know about your project / environment**

- You can check the PR catching this issue; https://github.com/grpc/grpc/pull/36626
- This test is running under this docker image; `us-docker.pkg.dev/grpc-testing/testing-images-public/grpc_artifact_protoc_aarch64:be8fc962f6a27ce976abecbda3dd02be4be5683d@sha256:a0f6b544c1b2fa75f73b26cb28281917153304e9df2789e93de0732494e6b651`

**Comment by guldeMNI** [comment]
Seeing this same issue. Think before comiting to main a CI test would have caught.
system:
C++
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
seems like compiler template issue - saw some notes on fixing this const pointer issue.

ERRORS:
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/protobuf_lite/google/protobuf/message_lite.h:930:37:   required from 'const T* google::protobuf::DownCastToGenerated(const google::protobuf::MessageLite*) [with T = google::protobuf::UninterpretedOption]'
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/protobuf_lite/google/protobuf/message_lite.h:940:29:   required from 'T* google::protobuf::DownCastToGenerated(google::protobuf::MessageLite*) [with T = google::protobuf::UninterpretedOption]'
src/google/protobuf/compiler/parser.cc:1568:47:   required from here
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:72:43: error: no matching function for call to 'StrongPointer<const google::protobuf::UninterpretedOption& (* const)(), ptr>()'
   72 |   return StrongPointer<decltype(ptr), ptr>();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:43:36: note: candidate: 'template<class T> void google::protobuf::internal::StrongPointer(T*)'
   43 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer(T* var) {
      |                                    ^~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:43:36: note:   template argument deduction/substitution failed:
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:72:43: error: wrong number of template arguments (2, should be 1)
   72 |   return StrongPointer<decltype(ptr), ptr>();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:43:36: note: provided for 'template<class T> void google::protobuf::internal::StrongPointer(T*)'
   43 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer(T* var) {
      |                                    ^~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:54:36: note: candidate: 'template<class T, T ptr> void google::protobuf::internal::StrongPointer()'
   54 | inline PROTOBUF_ALWAYS_INLINE void StrongPointer() {
      |                                    ^~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:54:36: note:   template argument deduction/substitution failed:
bazel-out/k8-fastbuild/bin/src/google/protobuf/_virtual_includes/port/google/protobuf/port.h:72:43: error: could not convert template argument 'ptr' from 'const google::protobuf::UninterpretedOption& (* const)()' to 'const google::protobuf::UninterpretedOption& (* const)()'
   72 |   return StrongPointer<decltype(ptr), ptr>();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by Mizux** [comment]
For the record:
gcc `11.4.0`: Fail
gcc `13.2.0`: Pass

https://github.com/protocolbuffers/protobuf/blob/63def39e881afa496502d9c410f4ea948e59490d/src/google/protobuf/port.h#L66-L76
