### ISSUE TITLE
[Build] Failure to build with "could not convert"

### ISSUE THREAD

**Issue by veblush** [protocolbuffers/protobuf#16878]
**What version of protobuf and what language are you using?**

Protobuf commit [69a26b2](https://github.com/protocolbuffers/protobuf/commit/69a26b217d16fddba7458aabec35d552582440f8)

**What operating system (Linux, Windows, ...) and version?**

Linux Debian 11 using Docker 

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc 10

**What did you do?**

Build protobuf using cmake

**What did you expect to see**

Successful build

**What did you see instead?**

Build failure with [log](https://btx.cloud.google.com/invocations/6a8efacb-10d7-4425-82c9-bd3b416f4c68/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c%2B%2B_linux_noexcept_native_buildonly;config=default/log)

```
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/duration.pb.cc: In member function ‘virtual const google::protobuf::MessageLite::ClassData* google::protobuf::Duration::GetClassData() const’:
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/duration.pb.cc:159:7: error: could not convert ‘{{(& google::protobuf::Duration::_table_.google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2>::header), nullptr, nullptr, 28, false}, google::protobuf::Duration::MergeImpl, (& google::protobuf::Message::kDescriptorMethods), (& descriptor_table_google_2fprotobuf_2fduration_2eproto), nullptr}’ from ‘’ to ‘const google::protobuf::MessageLite::ClassDataFull’
  159 |       };
      |       ^
      |       |
      |       
```
**Anything else we should know about your project / environment**

- This test is running under this docker image; `us-docker.pkg.dev/grpc-testing/testing-images-public/cxx_debian11_x64:a9c5d062364adc836b4068cad93a3e448b25c37c@sha256:9f9285da21c1053ac715027e0cee66c20c70ebf016053328a4cee61ffd37e59b`

**Comment by zhangskz** [comment]
This is due to due to same error as https://github.com/protocolbuffers/protobuf/issues/16868 preventing our CI job to refresh staleness files from running successfully. Sam has a fix coming in shortly.

**Comment by sbenzaquen** [comment]
This should be fixed now that the bot updated the files. Please confirm.

**Comment by veblush** [comment]
Verified and thanks for the quick fix!
