### ISSUE TITLE
Issue while installing protobuf

### ISSUE THREAD

**Issue by Kanishkamahesh** [protocolbuffers/protobuf#16925]
While I tried to install SHOGUN v4.0.0 from source code, there occurred an error while executing make command.
The error is 
[ 76%] Building CXX object examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/balanced_conditional_probability_tree.cpp.o
[ 76%] Linking CXX executable balanced_conditional_probability_tree
../../../src/shogun/libshogun.so.17.1: undefined reference to `google::protobuf::internal::InternalMetadata::~InternalMetadata()'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/balanced_conditional_probability_tree] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/all] Error 2
make: *** [all] Error 2

How to sort out this error?

**Comment by deannagarcia** [comment]
Can you provide some more information here? What version of protobuf do you have? What language/operating system are you using?
