### ISSUE TITLE
Python Protobuf-5.27 fails to support map field.

### ISSUE THREAD

**Issue by dudupo** [protocolbuffers/protobuf#16948]
Dear Protobuf stuff. 
It seems that the `python`  api, version number `5.27`, fails to run the [basic example for using maps field 
](https://protobuf.dev/reference/python/python-generated/#map-fields). Checked on WSL-Ubuntu 22.04.4 LTS, using the python runtime version. 

**What did you do?**

The `.proto` file:
```proto
syntax = "proto3";
message AA {
    map<int32, int32> mapfield = 1;
}
``` 

The `.py` script: 
```py
from example_pb2 import AA
x = AA()
x.mapfield[1] = 2
```

Compiling the proto file via `protoc  -I=./ --python_out=./ ./example.proto`. 

I expected the program be ends successfully instead I got the error: 

```
Traceback (most recent call last):
  File "/home/davidponar/workspace/Protobuf/./main.py", line 7, in <module>
    x.mapfield[1] = 2
  File "/home/davidponar/.local/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 315, in __setitem__
    raise TypeError(
TypeError: RepeatedCompositeFieldContainer object does not support item assignment
```

The program behaves well when downgrading the python api to version number 4.21
==
![5 27VS4 21](https://github.com/protocolbuffers/protobuf/assets/7993083/117a5b86-ff0f-4c9a-99ca-2e034ee49aee)

**Comment by zhangskz** [comment]
@dudupo Can you confirm if this works in previous versions 25.x and 26.x, or if this only affects 27.x?

@anandolee Can you take a look and see if a fix is needed for 27.x?

**Comment by dudupo** [comment]
> @dudupo Can you confirm if this works in previous versions 25.x and 26.x, or if this only affects 27.x?
 
I checked for 26.x versions, and it doesn't work. I got a read-time-out error when installing the 25.x versions via pip.

**Comment by anandolee** [comment]
I checked on our head and it works correctly. 
From your error message `TypeError: RepeatedCompositeFieldContainer object does not support item assignment`, It seems like it may linked to another .proto file and the mapfield is a map<int32, message> instead of map<int32, int32>

**Comment by yoavweber** [comment]
I am facing the same issue, and I am using version `4.25.3`.
This is my map definition:

 `map<string, string> some_map = 4;`

I also use Ubuntu 22.04 if it makes any difference.
