### ISSUE TITLE
Build from main branch fail on macos 14.5 x86

### ISSUE THREAD

**Issue by qinghui-xu** [protocolbuffers/protobuf#16944]
**What version of protobuf and what language are you using?**
Version: main branch (commit 2f3242c57)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
MacOS Sonoma (14.5)
**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 15.0.0 (clang-1500.3.9.4)
**What did you do?**
Run `bazel build :protoc :protobuf`

**What did you see instead?**
```
ERROR: /Sources/thirdparty/protobuf/src/google/protobuf/io/BUILD.bazel:98:11: Compiling src/google/protobuf/io/printer.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //src/google/protobuf/io:printer) external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 42 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from src/google/protobuf/io/printer.cc:12:
bazel-out/darwin_x86_64-fastbuild/bin/src/google/protobuf/io/_virtual_includes/printer/google/protobuf/io/printer.h:904:19: error: 'get<std::function<bool ()>, std::string, std::function<bool ()>>' is unavailable: introduced in macOS 10.13
    value = absl::get<Callback>(that.value);
                  ^
bazel-out/darwin_x86_64-fastbuild/bin/src/google/protobuf/io/_virtual_includes/printer/google/protobuf/io/printer.h:849:11: note: in instantiation of function template specialization 'google::protobuf::io::Printer::ValueImpl<false>::operator=<true>' requested here
    *this = that;
          ^
bazel-out/darwin_x86_64-fastbuild/bin/src/google/protobuf/io/_virtual_includes/printer/google/protobuf/io/printer.h:1136:12: note: in instantiation of function template specialization 'google::protobuf::io::Printer::ValueImpl<false>::ValueImpl<true>' requested here
    return ValueView(it->second);
           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/variant:1581:22: note: 'get<std::function<bool ()>, std::string, std::function<bool ()>>' has been explicitly marked unavailable here
constexpr const _Tp& get(const variant<_Types...>& __v) {
                     ^
1 error generated.
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 197.283s, Critical Path: 14.57s
INFO: 590 processes: 350 internal, 240 darwin-sandbox.
ERROR: Build did NOT complete successfully
```

**Anything else we should know about your project / environment**

**Comment by simonberger** [comment]
This is an issue on ARM64 Macs as well.

**Comment by qinghui-xu** [comment]
Apparently it's related to c++17 features unsupported by MacOS Clang out of box. I can use `cmake` by setting c++14 feature flag to build it.

**Comment by deannagarcia** [comment]
This actually appears to be an issue with [abseil](https://github.com/abseil/abseil-cpp) and the macos library.

As a workaround, you can use the [abseil option](https://abseil.io/docs/cpp/guides/options) [`ABSL_OPTION_USE_STD_VARIANT`](https://github.com/abseil/abseil-cpp/blob/master/absl/base/options.h#L177) to ensure that you use absl types instead of std types.

You can also file a bug with abseil to see if they can help make this work by default.

**Comment by brycefisher** [comment]
Was there a fix merged for bazel projects consuming this repository? How can I apply this workaround from my bazel project?

**Comment by reimai** [comment]
> Was there a fix merged for bazel projects consuming this repository? How can I apply this workaround from my bazel project?

You could either add ```--host_cxxopt=-std=c++14 --cxxopt=-std=c++14``` flags for your builds or [patch abseil library](https://abseil.io/docs/cpp/guides/options#usage)

**Comment by jettcc** [comment]
today, after bazelisk upgraded to bazel 8.0, this problem also appeared on my computer. My solution is to add the following command to the .bazelrc file: `build --host_cxxopt=-std=c++14 --cxxopt=-std=c++14`, but I always think this is not a good solution. so, if there are better solutions, feel free to communicate
