### ISSUE TITLE
Linker errors when building project in Visual Studio

### ISSUE THREAD

**Issue by helloWorld199** [protocolbuffers/protobuf#17020]
**What version of protobuf and what language are you using?**
Version: v28.0-dev
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro

**What runtime / compiler are you using (e.g., python version or gcc version)**
Windows SDK Version: 10.0.22621.0
Platform toolset: Visual Studio 2022 (v143)
C++ Language standard: ISO C++17 Standard (/std:c++17)

**What did you do?**
Building my solution on visual studio

**What did you expect to see**
I expected to see it building properly

**What did you see instead?**
A series of linker errors, given both by protobuf and absl, even if the libraries are included into the build configuration. Do you have any idea about it?
[proto-errors.txt](https://github.com/user-attachments/files/15567891/proto-errors.txt)

**Comment by acozzette** [comment]
It looks like the linker is unable to find certain symbols from your protobuf generated code and from Abseil. It's hard to say why that is, but you might want to look at the linker command and verify that all the required libraries are being passed to the linker.
