### ISSUE TITLE
Compiling upb triggers C4789 errors on MSVC, if enabled

### ISSUE THREAD

**Issue by Rantanen** [protocolbuffers/protobuf#17032]
**What version of protobuf and what language are you using?**
Version: v26.1 I'm guessing. Whatever upb version gRPC v1.64.0 vendors in.
Language: C/C++

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC 14.40.33807 / CL 19.40.33811

**What did you do?**
Compiling gRPC with CMake:

```
cmake C:\git\build-sdks/libs/grpc 
    -G "Visual Studio 17 2022"
    -DCMAKE_CXX_STANDARD=17
    -DCMAKE_INSTALL_PREFIX=C:\git\build-sdks/output/debug/x64-windows-vc170
    -DCMAKE_FIND_ROOT_PATH=C:\git\build-sdks/output/debug/x64-windows-vc170
    -DCMAKE_BUILD_TYPE=Debug
    -DCMAKE_BUILD_SHARED_LIBS=ON
    -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebugDLL
    -DCMAKE_CXX_FLAGS_DEBUG="/MDd /D_DEBUG /Z7 /DGRPC_ARES=0 /wd4789"  # Note /wd4789 to disable C4789
    -DCMAKE_CXX_FLAGS_RELEASE="/MD /DNDEBUG /DGRPC_ARES=0 /wd4789"  # Note /wd4789 to disable C4789
    -DCMAKE_C_FLAGS_DEBUG="/MDd /D_DEBUG /Z7 /DGRPC_ARES=0 /wd4789"  # Note /wd4789 to disable C4789
    -DCMAKE_C_FLAGS_RELEASE="/MD /DNDEBUG /DGRPC_ARES=0 /wd4789"  # Note /wd4789 to disable C4789
    -T version=14.32.17.2
    -A x64
    -DgRPC_INSTALL=ON
    -DgRPC_BUILD_TESTS=OFF
    -DgRPC_STATIC_LINKING=OFF
    -DgRPC_MSVC_STATIC_RUNTIME=OFF
    -DgRPC_ZLIB_PROVIDER=package
    -DgRPC_SSL_PROVIDER=module
    -DgRPC_PROTOBUF_PROVIDER=package
    -DgRPC_PROTOBUF_PACKAGE_TYPE=CONFIG
    -DgRPC_ABSL_PROVIDER=package
    -DgRPC_CARES_PROVIDER=none
    -DgRPC_GFLAGS_PROVIDER=none
    -DgRPC_BENCHMARK_PROVIDER=none
    -DgRPC_BUILD_CODEGEN=ON
    -DgRPC_BUILD_GRPC_CPP_PLUGIN=ON
    -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=ON
    -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF
    -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF
    -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF
    -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF
    -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF
```

**What did you expect to see**
Compilation succeeds.

**What did you see instead?**
gRPC compilation fails to compile upb due to C4789 errors:

```
"C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\INSTALL.vcxproj" (default target) (1) ->
"C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\grpc++_alts.vcxproj" (default target) (18) ->
"C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj" (default target) (28) ->
  C:\git\build-sdks\libs\grpc\third_party\upb\upb\message\internal\accessors.h(158,1): error C4789: in function 'upb_Message_GetArray' buffer 'ret' of size 8 bytes will be overrun; 16 bytes will be wri
tten starting at offset 0 [C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj]
  C:\git\build-sdks\libs\grpc\third_party\upb\upb\message\internal\accessors.h(158,1): error C4789: in function 'upb_Message_GetArray' buffer 'ret' of size 8 bytes will be overrun; 16 bytes will be wri
tten starting at offset 0 [C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj]
  C:\git\build-sdks\libs\grpc\third_party\upb\upb\message\internal\accessors.h(158,1): error C4789: in function 'upb_Message_GetArray' buffer 'ret' of size 8 bytes will be overrun; 16 bytes will be wri
tten starting at offset 0 [C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj]
  C:\git\build-sdks\libs\grpc\third_party\upb\upb\message\internal\accessors.h(158,1): error C4789: in function 'upb_Message_GetArray' buffer 'ret' of size 8 bytes will be overrun; 16 bytes will be wri
tten starting at offset 0 [C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj]
  C:\git\build-sdks\libs\grpc\third_party\upb\upb\message\internal\accessors.h(158,1): error C4789: in function 'upb_Message_GetArray' buffer 'ret' of size 8 bytes will be overrun; 16 bytes will be wri
tten starting at offset 0 [C:\git\build-sdks\build\debug\x64-windows-vc170\grpc\upb_json_lib.vcxproj]
```

gRPC CMake build enables C4789 explicitly and I didn't find a way to disable it there. I've also opened a bug against gRPC (grpc/grpc#36815).

The error itself is somewhat interesting and is caused by somewhat deep static analysis/inlining.

The error references message/accessors.h `upb_Message_GetArray`, which is defined in message/accessors.h, line 381-388:

https://github.com/protocolbuffers/protobuf/blob/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5/upb/message/accessors.h#L381-L388

This function calls message/internal/accessors.h `_upb_Message_GetNonExtensionField`

https://github.com/protocolbuffers/protobuf/blob/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5/upb/message/internal/accessors.h#L246-L258

Which finally calls message/internal/accessors.h `_upb_MiniTableField_DataCopy`, which is the line 158 that the message references:

https://github.com/protocolbuffers/protobuf/blob/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5/upb/message/internal/accessors.h#L145-L163

So the original `ret` comes from the `upb_Message_GetArray` and is defind as a single `upb_Array*` pointer. The `DataCopy` conditionally (based on field representation) writes `sizeof(upb_StringView)` bytes into it and `upb_StringView` is a `char*, size_t` tuple.

Or that is what the compiler believes. In practice, the `GetArray` does check for `_upb_MiniTableField_CheckIsArray(field)`, which checks that the field representation is `kUpb_FieldRep_NativePointer`, which should then be safe to write to the `upb_Array* ret` variable:

https://github.com/protocolbuffers/protobuf/blob/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5/upb/mini_table/internal/field.h#L193-L199

----

I'm not sure what you'll want to do with this. The code itself seems correct, even if coming to that conclusion wasn't straight forward (to the extent that the static analysis fails to come to that conclusion), but I guess that's C for you. Mostly I reported the issue to have something to reference from grpc/grpc#36815 as well.

**Comment by acozzette** [comment]
Thank you for the bug report. Since it seems to be a false alarm from MSVC, I think we probably won't go out of our way to fix it. It would be nice to somehow restructure the code in a way that MSVC could be persuaded it's correct, but I have no idea what would be involved in doing that.
