### ISSUE TITLE
warning "attribute 'visibility' is ignored" when building shared libraries with CMake

### ISSUE THREAD

**Issue by kwaegel** [protocolbuffers/protobuf#17060]
**What version of protobuf and what language are you using?**
Version: v27.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 24.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
Clang 15.0.7

**What did you do?**
1. Download [v27.1 source release](https://github.com/protocolbuffers/protobuf/archive/refs/tags/v27.1.zip).
2. Run CMake build with:
```
cmake -Dprotobuf_BUILD_TESTS=OFF  -DABSL_ROOT_DIR=[local_dir] -Dprotobuf_BUILD_SHARED_LIBS=ON [path_to_proto_src]
ninja protoc
```

**What did you expect to see**
build log with a minimal number of warnings (no log spam).

**What did you see instead?**
A substantial number of warning messages following this pattern:
```
In file included from /c/dev/mp_vision/thirdparty/protobuf-27.1/src/google/protobuf/feature_resolver.cc:36:
/c/dev/mp_vision/thirdparty/protobuf-27.1/src/google/protobuf/text_format.h:57:1: warning: attribute 'visibility' is ignored, place it after "enum" to apply attribute to type declaration [-Wignored-attributes]
PROTOBUF_EXPORT enum class FieldReporterLevel {
^
/c/dev/mp_vision/thirdparty/protobuf-27.1/src/google/protobuf/port_def.inc:345:41: note: expanded from macro 'PROTOBUF_EXPORT'
# define PROTOBUF_EXPORT __attribute__((visibility("default")))
```

**Anything else we should know about your project / environment**
This did not happen with v24.3, but I have not tested other intermediate versions yet.

**Comment by acozzette** [comment]
Thank you for the bug report. I'm not familiar with exactly what this warning means, but we would be happy to accept a pull request fixing the issue.
