### ISSUE TITLE
Ruby gem fails to compile under x86_64-linux-gnux32 on bookworm

### ISSUE THREAD

**Issue by haileys** [protocolbuffers/protobuf#17068]
```
linking shared-object google/protobuf_c.so
/usr/bin/ld: protobuf_c.so: no symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'
collect2: error: ld returned 1 exit status
make: *** [Makefile:265: protobuf_c.so] Error 1
```

This is due to the [`wrap_memcpy.c`](https://github.com/protocolbuffers/protobuf/blob/08a6c36f5ace9c5d41eaa3df6d718e3f7acdcf47/ruby/ext/google/protobuf_c/wrap_memcpy.c), which appears to force the `memcpy` symbol to link against a specific version exported by glibc.

Removing the wrap_memcpy code fixes the issue.

**Comment by haileys** [comment]
It appears that Debian bookworm's [libc6-x32](https://packages.debian.org/bookworm/libc6-x32) only provides the `GLIBC_2.16` version of this symbol

```
$ objdump -T /usr/libx32/libc.so.6 | grep memcpy
000aae50  w   DF .text	00000008  GLIBC_2.16  wmemcpy
00110730 g    DF .text	00000018  GLIBC_2.16  __wmemcpy_chk
0010f470 g   iD  .text	00000107  GLIBC_2.16  __memcpy_chk
00095fc0 g   iD  .text	00000107  GLIBC_2.16  memcpy
```

**Comment by haileys** [comment]
This can also be fixed by adding `&& !defined(__ILP32__)` to the `#if defined(__x86_64__) && defined(__GNU_LIBRARY__)` preprocessor condition in `wrap_memcpy.c`

**Comment by acozzette** [comment]
Thank you for the bug report. Your suggested fix sounds good to me if you would like to send us a pull request.
