### ISSUE TITLE
Depending on @protobuf//:protobuf alone fails Bazel layering_check

### ISSUE THREAD

**Issue by davidzchen** [protocolbuffers/protobuf#17094]
**What version of protobuf and what language are you using?**
Version: 26.0

```
bazel_dep(name = "protobuf", version = "26.0")
```

Language: C++

**What operating system (Linux, Windows, ...) and version?**

macOS Sonoma 14.4.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

```
clang --version
Homebrew clang version 18.1.5
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**What did you do?**
1. Clone the repository https://github.com/davidzchen/abxl
2. Run the following command:

```sh
bazel build //abxl/proto:protobuf_matchers
```

**What did you expect to see**

Successful build

**What did you see instead?**

```
$ bazel build //abxl/proto:protobuf_matchers
INFO: Analyzed target //abxl/proto:protobuf_matchers (1 packages loaded, 3 targets configured).
ERROR: /Users/dzc/Projects/davidzchen/abxl/abxl/proto/BUILD:3:11: Compiling abxl/proto/protobuf_matchers.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //abxl/proto:protobuf_matchers) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 133 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
abxl/proto/protobuf_matchers.cc:28:10: error: module //abxl/proto:protobuf_matchers does not depend on a module exporting 'google/protobuf/io/tokenizer.h'
#include "google/protobuf/io/tokenizer.h"
         ^
abxl/proto/protobuf_matchers.cc:31:10: error: module //abxl/proto:protobuf_matchers does not depend on a module exporting 'google/protobuf/util/message_differencer.h'
#include "google/protobuf/util/message_differencer.h"
         ^
2 errors generated.
Target //abxl/proto:protobuf_matchers failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.894s, Critical Path: 1.78s
INFO: 6 processes: 6 internal.
ERROR: Build did NOT complete successfully
```

**Anything else we should know about your project / environment**

Bazel version:

```
$ bazel --version
bazel 7.2.0
```

Here is the BUILD rule used to build this target:

```
cc_library(
    name = "protobuf_matchers",
    testonly = 1,
    srcs = ["protobuf_matchers.cc"],
    hdrs = ["protobuf_matchers.h"],
    deps = [
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@protobuf",
        "@re2",
    ],
)
```

The problem is that just include `@protobuf` is not sufficient to satisfy Bazel's layering check. The fix would be to add the specific targets to `deps`. The `tokenizer.h` error goes away by adding `@protobuf//src/google/protobuf/io:tokenizer`. This is possible because the package is [public](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/io/BUILD.bazel#L8). However, it is not possible to include `@protobuf//src/google/protobuf/util:differencer` because that package is limited to protobuf [subpackages](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/util/BUILD.bazel#L51)

Would it be possible to the package visibility of `src/google/protobuf/util` public as well? This should fix the problem.

**Comment by davidzchen** [comment]
FYI I disabled the layering check in commit 8eede4e49e14afd3f13e2377e74f25228794888b, so to reproduce, please uncomment these lines: https://github.com/davidzchen/abxl/blob/8eede4e49e14afd3f13e2377e74f25228794888b/.bazelrc#L13-L15

**Comment by acozzette** [comment]
We have a convention of creating public aliases in our top-level BUILD file and keeping targets under `//src` private, but unfortunately we have not been consistent about this. I believe you will need to add dependencies on `@protobuf//src/google/protobuf/io:tokenizer` and `@protobuf//:differencer`, and that should solve the problem.
