### ISSUE TITLE
[C#] Large repeated field doesn't pre-allocate the array on deserialization

### ISSUE THREAD

**Issue by verdie-g** [protocolbuffers/protobuf#17111]
**What version of protobuf and what language are you using?**
Version: 3.27.0
Language: C#
.NET: 8.0

**What did you do?**

```proto
syntax = "proto2";

message Test {
  repeated float values = 1 [packed=true];
}
```

```csharp
using Google.Protobuf;

MemoryStream ms = new();
new Test { Values = { Enumerable.Range(0, 100_000).Select(x => (float)x) }}.WriteTo(ms);

ms.Position = 0;
var x = Test.Parser.ParseFrom(ms);
```

**What did you expect to see**

When deserializing the 100K values, I would expect the RepeatedField's array to be allocated once.

**What did you see instead?**

https://github.com/protocolbuffers/protobuf/blob/a6d482748271f36fff5afe1abea3889789d0e3b5/csharp/src/Google.Protobuf/Collections/RepeatedField.cs#L112-L131

In this case `codec.FixedSize > 0 && length % codec.FixedSize == 0` is true, but `ParsingPrimitives.IsDataAvailable(ref ctx.state, length)` is false. So the code branches to the variable size part which makes the array grow as the data is read. That doubles the amount of memory allocated and in production, my array is several MB large so most temporary arrays reach LOH :(

In both branches, the code seems to be almost the same, that is,
```csharp
while (!SegmentedBufferHelper.IsReachedLimit(ref ctx.state))
{
    var val = reader(ref ctx);
    // do something with val
}
```
Could you help me understand the purpose of `IsDataAvailable` here? :thinking:

**Comment by verdie-g** [comment]
I missed the comment just above the snippet

> Check that the supplied length doesn't exceed the underlying buffer. That prevents a malicious length from initializing a very large collection.

It seems like the underlying buffer doesn't contain the entire input but only 4096 bytes, so whenever `array size - array offset in buffer > 4096` the code will fallback on the "slow path". Would it make sense to compare the array size to the size of the input instead of the size of the current buffer?

**Comment by honglooker** [comment]
cc @jskeet

**Comment by jskeet** [comment]
This was code from @JamesNK  in #7412. James, any thoughts about the suggestion?

My suspicion is that the underlying buffer *will* contain all the data if it's all actually available to start with (e.g. if we've created a CodedInputStream from an array rather than a stream). If we've got an actual stream, then the length may not even be known ahead of time, making it impossible to use the "size of the input".

**Comment by JamesNK** [comment]
I don't remember. I'd need to debug what is going on.

**Comment by jskeet** [comment]
I think it's unlikely that we'd get to this feature request any time soon. If you want to implement it yourself and create a PR, I'll try to review it - but even finding time for that could be tricky if it's a large change or one which requires really careful review for security reasons etc.

**Comment by verdie-g** [comment]
Thanks for the heads up. Wdyt of https://github.com/protocolbuffers/protobuf/pull/17191?

**Comment by verdie-g** [comment]
I realize that in my case, even if the PR is merged, that won't fix my issue because my input stream is a zip and it has a Length but [it's not seekable](https://github.com/dotnet/runtime/blob/b0c4728305b98c0ae22d90f72c805aecb628ba8c/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipCustomStreams.cs#L268). Would it make sense to have a constructor that takes the length of the stream
```csharp
public CodedInputStream(Stream input, bool leaveOpen, long length)
```

The reason why this performance fix is important to me, is the LOH of one of our service identifies as a roller-coaster
![image](https://github.com/protocolbuffers/protobuf/assets/9092290/d6b1bf4b-0197-43e7-a6bf-0b0a5baca861)
And that's only one instance. We have 6K instances of that service :skull:

**Comment by jskeet** [comment]
It's worse than not knowing the length of the stream - we don't know whether the stream is even positioned at the start when we read from it. (The stream itself may have a length of 100 bytes, but if we're on the last byte when we construct the CodedInputStream, we don't have 100 bytes left to read...)

No doubt there are fairly tortuous ways of avoiding this, but I really don't want to go to extreme lengths (which will need to be maintained forever, and which may well impact how feasible it is to make *other* changes) for the sake of a single customer.

Would it be possible for you to unzip in memory using an array pool (so you can reuse the same huge array) and then use a CodedInputStream backed by a byte array instead?

**Comment by verdie-g** [comment]
> we don't know whether the stream is even positioned at the start when we read from it

Ah good catch, I missed that in my PR.

> Would it be possible for you to unzip in memory using an array pool (so you can reuse the same huge array)

It's tricky, the zips are prediction models, and we have a bunch of them to download and they get updated continuously. If I do a naive pool that would just allocate an array of Stream.Length and hope that the next stream is smaller. There is a big risk of filling the memory with useless pooled array.

Regarding the constructor I was suggesting, I don't like the idea you can discard it. Though, do you think the current PR could work if I include Stream Position?

Alternatively I could write my zip to a [RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) and the PR could do a `is MemoryStream` instead which is safer but supports less use-case.

**Comment by jskeet** [comment]
If you write your zip to a RecyclableMemoryStream you can access the buffer of the stream directly and pass that to CodedInoputStream. No need for a somewhat-convoluted change in Protobuf at all.

**Comment by verdie-g** [comment]
RecyclableMemoryStream.GetBuffer could work but setting the options right can be super trick
```csharp
var options = new RecyclableMemoryStreamManager.Options()
{
    BlockSize = 1024,
    LargeBufferMultiple = 1024 * 1024,
    MaximumBufferSize = 16 * 1024 * 1024,
    GenerateCallStacks = true,
    AggressiveBufferReturn = true,
    MaximumLargePoolFreeBytes = 16 * 1024 * 1024 * 4,
    MaximumSmallPoolFreeBytes = 100 * 1024,
};
```
As mentioned above, there is a big risk of filling the memory with useless pooled arrays.

It also means to refactor the code to pass a `byte[]` instead of a `Stream` between reading the zip and the proto deserialization. In my case, I'm not sure that will be doable.

Is there anything that you dislike in the current state of the PR?

**Comment by jskeet** [comment]
> Is there anything that you dislike in the current state of the PR?

Yes - it adds complexity. That's not a comment on correctness, or whether there's a better way of achieving the same outcome in the library. It's only a comment that every extra bit of code needs maintaining, and potentially constrains other feature implementation later. At the moment, I'm not convinced that it's worth the additional value - I'm sure it is *to you*, but that doesn't mean it's appropriate to accept the PR.

You've already said that your PR won't work as-is with the stream that you're passing in, and you suggested you might use `RecyclableMemoryStream`. You could then pass that stream through the code as a stream as normal, and *only at the point where you call `Parse`* would you do a check and say "if the stream is a MemoryStream, I'll use GetBuffer and pass the byte array (with offset and length) in instead".

If this were something that had come up from many other customers, the value proposition would be different - but while it's only a problem for one user (you in this case), and that user *can* work around it by absorbing the complexity in their code instead of in the library, I'd rather we did it that way round.

**Comment by verdie-g** [comment]
Got it thanks for the explanation. I'll work around it on my side. Feel free to close the PR and issue.

**Comment by jskeet** [comment]
Okay, thanks. Please don't let this put you off filing other issues or PRs - I just need to be mindful of trying to accommodate everyone and ending up in a bad situation :)
