### ISSUE TITLE
CLOUD SPANNER WITH PROTO BUFFER

### ISSUE THREAD

**Issue by suavelad** [protocolbuffers/protobuf#17189]
I get this error :

  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 122, in IsDone
    raise OperationError(operation.error.message)
googlecloudsdk.api_lib.util.waiter.OperationError: None
ERROR: (gcloud.spanner.databases.ddl.update) None

when I run

gcloud spanner databases ddl update new-db --instance=instance-spanner  \
	--ddl-file=./proto_bundle.sql \
	--proto-descriptors-file=./xxx.pb  --verbosity=debug

**Comment by zhangskz** [comment]
gcloud spanner has its own support page at https://cloud.google.com/sdk/docs/getting-support where you should likely reach out instead.

Please feel free to reopen if there's some indication this is due to an issue in protobuf itself, with steps for us to repro.
