### ISSUE TITLE
 why no set_allocated for Repeated messages (only for Embedded Message)?

### ISSUE THREAD

**Issue by Cwj1212** [protocolbuffers/protobuf#17245]
**What language does this apply to?**
C++ proto3

**Describe the problem you are trying to solve.**
Embedded Message Fields：we can use set_allocated_xxx() to takes ownership of the allocated object (avoid copy)
Repeated Embedded Message Fields：we can use mutable_xxx-> AddAllocated() to takes ownership of the allocated object (avoid copy)

It looks like we can use mutable_xxx-> Swap to avoid copy for Repeated messages？
But why no set_allocated for Repeated messages?

**Comment by sbenzaquen** [comment]
Are you trying to move the whole repeated field?
If so, you can just use move assignment.

```c++
*foo->mutable_xxx() = std::move(the_rep_field);
```

It will take ownership of the whole thing in the same way `AddAllocated` one by one would.
