### ISSUE TITLE
[C++] Segmentation fault when call ParseFromString with bad data

### ISSUE THREAD

**Issue by wcb33** [protocolbuffers/protobuf#17244]
**What version of protobuf and what language are you using?**
Version: v3.12, install by apt in Debian 12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Debian 12

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang

**What did you do?**
Run this code
```
int main(int argc, char** args)
{
    string v1("1");
    TestPackage p;
    //if (p.ParsePartialFromString(v1))
    if (p.ParseFromString(v1))
    {
        cout << "succeed" << endl;
    }
    else
    {
        cout << "error" << endl;
    }
    cout << "quit" << endl;
}
```

**What did you expect to see**
print "error"

**What did you see instead?**
Segmentation fault
![image](https://github.com/protocolbuffers/protobuf/assets/76732400/a58afd7a-aeb1-452e-b4cc-5df42e16d858)

**Anything else we should know about your project / environment**
The proto
```
syntax = "proto3";

option cc_enable_arenas = false;

package Base;
message TestPackage
{
    int32 Function = 1;
    fixed64 ID = 2;
}
```

**Comment by zhangskz** [comment]
Do you still hit this in a recent, supported version of protobuf e.g. 4.25.x, 5.27.x?  Protobuf v3.12 is very old and out of support. https://protobuf.dev/support/version-support/#cpp
