### ISSUE TITLE
生成不了，最新的protobuf27-2和cmake3.30-rc4。vs2022和2019都不行。

### ISSUE THREAD

**Issue by yangchunchong** [protocolbuffers/protobuf#17243]
CMake Error: The source directory "D:/UEProject/protobuf-27.2/cmake" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by zhangskz** [comment]
Can you provide more info on what you did here to ensure this is actionable / reproducible?
