### ISSUE TITLE
Cannot link due to abseil_dll

### ISSUE THREAD

**Issue by dpservis** [protocolbuffers/protobuf#17257]
**What version of protobuf and what language are you using?**
Version: 27.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 11
**What runtime / compiler are you using (e.g., python version or gcc version)**
VS2022 v143
**What did you do?**
1. Set cmake options
![image](https://github.com/protocolbuffers/protobuf/assets/7592829/74d46906-3ff2-4315-9cbe-6f5312107d40)

2. Build ALL_BUILD

**What did you expect to see**
Build
**What did you see instead?**
1>absl_base.lib(thread_identity.obj) : error LNK2005: "void __cdecl absl::lts_20240116::base_internal::SetCurrentThreadIdentity(struct absl::lts_20240116::base_internal::ThreadIdentity *,void (__cdecl*)(void *))" (?SetCurrentThreadIdentity@base_internal@lts_20240116@absl@@YAXPEAUThreadIdentity@123@P6AXPEAX@Z@Z) already defined in abseil_dll.lib(abseil_dll.dll)
1>absl_base.lib(thread_identity.obj) : error LNK2005: "void __cdecl absl::lts_20240116::base_internal::ClearCurrentThreadIdentity(void)" (?ClearCurrentThreadIdentity@base_internal@lts_20240116@absl@@YAXXZ) already defined in abseil_dll.lib(abseil_dll.dll)
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
@mkruskal-google Can you take a look at if this needs a patch?

**Comment by mkruskal-google** [comment]
Can you provide the following information:

- The complete cmake config command run (it's not 100% clear from your screenshot)
- More complete logs of the error
- If you have Abseil installed on your system, what version?

It looks like you're doing some kind of mix of static and dynamic linking, which is causing the conflicts.  It's hard to tell with the information provided though.

**Comment by dpservis** [comment]
- I use the Cmake GUI with these options. 
- Not sure where to get logs from
- No I do not have Abseil installed

**Comment by mkruskal-google** [comment]
I'm able to build just fine using the cmake settings you showed through VS 2022.  The thing I find strange is that the error you showed has references to `abseil_dll.dll`, which should not be built at all with those settings.  You don't set `BUILD_SHARED_LIBS` or `protobuf_BUILD_SHARED_LIBS`, so everything should be statically linked.  It could be leaking in through an earlier build with different settings or through a system installation of Abseil.

Without more complete logs there's not enough information here.  I'm just asking for the full output (ideally with --verbose) that you copied that error snippet from.

**Comment by dependon** [comment]
I seem to have encountered the same problem as him. I compiled it in the main branch without modifying any options. I used version 7.3.0 of mingw32 for g++and gcc compilation, as well as version 3.26.3 of cmake, but encountered the following issues.
![image](https://github.com/protocolbuffers/protobuf/assets/43714656/1bd45689-ac5d-4fef-916c-b5cdc74c0e1f)

**Comment by mkruskal-google** [comment]
That looks like a completely different problem, maybe file a separate issue?

**Comment by LarsLeferenz** [comment]
In case this still helps anyone, I've had a similar issue with redefinitions due to `abseil_dll.lib` where the problem was that my Conan CMake setup was consuming the `abseil_dll.dll` I've compiled through vcpkg previously instead of the static version I pulled through Conan. If anyone encounters a similar issue, be sure to check your environment and maybe search for an `abseil_dll.dll` on your computer it might be wrongly using.
