### ISSUE TITLE
I am having issues using Proto2 extensions with C#.

### ISSUE THREAD

**Issue by ByboyCn** [protocolbuffers/protobuf#17288]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
c#
**What operating system (Linux, Windows, ...) and version?**
all,version:3.27.2
**What runtime / compiler are you using (e.g., python version or gcc version)**
dotnet
**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
[protobuftest.zip](https://github.com/user-attachments/files/16048190/protobuftest.zip)

**Comment by zhangskz** [comment]
Could you provide more details on what the actual issue you are hitting and what you did in the issue description?

**Comment by jskeet** [comment]
You haven't specified an extension registry when parsing the serialized data. Change your code to:

```csharp
var registry = new ExtensionRegistry { Ww.InputExtensions.SPHFEEDMESSAGE };
var link = LinkMessage.Parser.WithExtensionRegistry(registry).ParseFrom(bytes1);
```

... and it works fine.

In future, please provide *much* more information in the issue - effectively there was very little other than the zip file here.
