### ISSUE TITLE
[C++/27.x] error: &_Variant_default_instance_is not a constant expression

### ISSUE THREAD

**Issue by jschueller** [protocolbuffers/protobuf#17303]
**What version of protobuf and what language are you using?**
Version: 27.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
archlinux

**What runtime / compiler are you using (e.g., python version or gcc version)**
mingw/gcc 14

**What did you do?**

vtkPVMessage.proto:
```
syntax = "proto2";

package paraview_protobuf;

message Variant {
  repeated double  float64         = 5;
}
```

```
$ protoc --cpp_out dllexport_decl=VTKREMOTINGSERVERMANAGER_EXPORT:/tmp vtkPVMessage.proto
```

main.cxx:
```
#define VTKREMOTINGSERVERMANAGER_EXPORT __declspec(dllimport)
#include "vtkPVMessage.pb.h"
```

```
$ x86_64-w64-mingw32-g++ -c main.cxx
In file included from main.cxx:3:
vtkPVMessage.pb.h:223:7: error: ‘(const void*)(& paraview_protobuf::_Variant_default_instance_)’ is not a constant expression
  223 |       &_Variant_default_instance_;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
vtkPVMessage.pb.h:299:1: warning: ‘const google::protobuf::RepeatedField<double>& paraview_protobuf::Variant::_internal_float64() const’ redeclared without dllimport attribute after being referenced with dll linkage
  299 | Variant::_internal_float64() const {
      | ^~~~~~~
vtkPVMessage.pb.h:303:51: warning: ‘google::protobuf::RepeatedField<double>* paraview_protobuf::Variant::_internal_mutable_float64()’ redeclared without dllimport attribute after being referenced with dll linkage
  303 | inline ::google::protobuf::RepeatedField<double>* Variant::_internal_mutable_float64() {
      |                                                   ^~~~~~~
The command '/bin/sh -c x86_64-w64-mingw32-g++ -c main.cxx' returned a non-zero code: 1
```

**Anything else we should know about your project / environment**
we encountered this building paraview: https://gitlab.kitware.com/paraview/paraview/-/issues/22629
with newer protobuf 27
it might look that this is since #16061 where protobuf adds a new line:
```
static constexpr const void* _raw_default_instance_ = &_Variant_default_instance_;
```

but the compiler seems not to treat it like a constexpr probably because of the visibility macro VTKREMOTINGSERVERMANAGER_EXPORT:
```
VTKREMOTINGSERVERMANAGER_EXPORT extern VariantDefaultTypeInternal _Variant_default_instance_;
```
which on mingw is set to `__declspec(dllimport)` and makes the build fail, unlike the native linux version where the macro is set to the default visibility

also confirmed on mingw/clang, I dont know if this affects msvc too

**Comment by zhangskz** [comment]
@sbenzaquen Can you take a look at if this needs a fix for next 27.x patch?

**Comment by jschueller** [comment]
yes that works

**Comment by jschueller** [comment]
yes that works, thanks a lots

**Comment by jschueller** [comment]
do you know if there is a patch release planned ?

**Comment by zhangskz** [comment]
This will be patched to 27.x branch for the next 27.3 patch release which will likely be in week or two.

**Comment by jschueller** [comment]
ok, thanks
