### ISSUE TITLE
README.txt does not align with the actual repositiroy. 

### ISSUE THREAD

**Issue by git00002** [protocolbuffers/protobuf#17350]
The markdown doesn't read accurately to the contents of the git repository. So and example would be the README.md  says 
```
# Download protobuf
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf

# Build protoc
./autogen.sh
./configure
make -j4

# Test native php
cd php
composer install
composer test
``` 
but autogen.sh and configure do not actually exist after cloning the repository.  

**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by esorot** [comment]
Can you point us to where in our documentation you're referring so we can get it correct?
