### ISSUE TITLE
Digitally Signed Executables

### ISSUE THREAD

**Issue by kisssadam** [protocolbuffers/protobuf#17571]
**What language does this apply to?**
Each language.

**Describe the problem you are trying to solve.**
I would like to be able to trust the executable file by looking at its digital signatures.

**Describe the solution you'd like**
I would like to use digitally signed Windows executables of protoc.exe.
The executables that Gradle tries to use with plugin `com.gradle.protobuf` are not digitally signed thus they are blocked by my company's protection system.

**Describe alternatives you've considered**
N/A

**Additional context**
Our firm wide app protection system blocks using protoc.exe, because it's not digitally signed and expects us to manually unblock it for each run.

**Comment by zhangskz** [comment]
While this is something we would like eventually, it is unlikely this is something we'll be able to get to this right now given staffing and priorities.

**Comment by kisssadam** [comment]
I think this should remain active or some notes left here when this will be prioritized.
