### ISSUE TITLE
[Ruby] Descriptor `to_proto` output is invalid UTF-8

### ISSUE THREAD

**Issue by cocoahero** [protocolbuffers/protobuf#17604]
I'm currently working on building a `protoc` plugin in ruby. As a learning case study, I'm attempting to reimplement the default Ruby plugin's behavior. An issue I am running into however is that the output of `to_proto` is encoded as `ASCII-8BIT`, which when eventually supplied as a `CodeGeneratorResponse::File.content` value, raises a `Encoding::UndefinedConversionError`.

When invoking the plugin as follows, I get the following output.
```
protoc --plugin=./protoc-gen-test --test_out=. test.proto

./protoc-gen-test:12:in `initialize': "\x85" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        from ./protoc-gen-test:12:in `new'
        from ./protoc-gen-test:12:in `block in <main>'
        from ./protoc-gen-test:11:in `each'
        from ./protoc-gen-test:11:in `<main>'
--test_out: protoc-gen-test: Plugin failed with status code 1.
```

`protoc-gen-test`
```ruby
#! /usr/bin/env ruby
# frozen_string_literal: true

require "google/protobuf"
require "google/protobuf/plugin_pb"

request = Google::Protobuf::Compiler::CodeGeneratorRequest.decode($stdin.read)

response = Google::Protobuf::Compiler::CodeGeneratorResponse.new

request.proto_file.each do |file|
  response.file << Google::Protobuf::Compiler::CodeGeneratorResponse::File.new(
    name: "#{file.name}.rb", content: file.to_proto,
  )
end

$stdout.write(response.to_proto)
```

`test.proto`
```proto
syntax = "proto3";

message Resource {
  uint64 id = 1;
  string name = 2;
}

service MyService {
  rpc GetResourceByID(GetResourceByIDRequest) returns (GetResourceByIDResponse);
}

message GetResourceByIDRequest {
  uint64 id = 1;
}

message GetResourceByIDResponse {
  Resource resource = 1;
}
```

**Comment by haberman** [comment]
This is working as intended.

The `msg#to_proto` method outputs protobuf wire format, which is supposed to be raw binary data.

The `CodeGeneratorResponse::File.content` field, on the other hand, is supposed to hold the source code output of your proto plugin. As source code, it should be valid UTF-8.

Your plugin should generate source code to put into the `content` field, rather that sending back binary data.
