### ISSUE TITLE
extension number for userver custom options

### ISSUE THREAD

**Issue by kpavlov00** [protocolbuffers/protobuf#17603]
We need an extension number for custom option in our project 

Project: userver

website: https://userver.tech/

github: https://github.com/userver-framework/userver

**Comment by shaod2** [comment]
lgtm. Can you create a PR so that I can approve?

**Comment by kpavlov00** [comment]
> lgtm. Can you create a PR so that I can approve?

Hello
PR:
https://github.com/protocolbuffers/protobuf/pull/17673

**Comment by kpavlov00** [comment]
Done
via https://github.com/protocolbuffers/protobuf/commit/f30b0a8390079e2d66983f4383375e50e7704582.
