### ISSUE TITLE
Use DebugString or MessageToJsonString  print  message has oneof keywords occur Segmentation fault!

### ISSUE THREAD

**Issue by mkzz115** [protocolbuffers/protobuf#17600]
Version:  libprotoc 3.21.12
Language: C++
operating system： Ubuntu 2204

When I defined a message like this:

`message ExceptionMsgNtf {
    protocol.ExceptionMsgType type  = 1;
    oneof msg {
      protocol.AException a_ec = 2;
      protocol.BException b_ec = 3;
      protocol.CException c_ec= 4;
      protocol.DException d_ec= 5;
    }`

I defined  msg_ptr = std::make_shared<XXX::ExceptionMsgNtf>(); and set some values with different type
then I print msg_ptr with DebugString or MessageToJsonString, occur Segmentation fault.
But I print a_ec/b_ec/c_ec/d_ec well when it was set like this: LOG("{}, {}", msg_ptr->type(), msg_ptr->a_ec().DebugString())

 Segmentation fault core:
`#0  0x00006126fbf99a90 in google::protobuf::EnumDescriptor::full_name[abi:cxx11]() const ()
#1  0x00006126fbf98bbf in google::protobuf::util::(anonymous namespace)::DescriptorPoolTypeResolver::GetTypeUrl(google::protobuf::EnumDescriptor const*)
    ()
#2  0x00006126fbf98811 in google::protobuf::util::(anonymous namespace)::DescriptorPoolTypeResolver::ConvertFieldDescriptor(google::protobuf::FieldDescriptor const*, google::protobuf::Field*) ()
#3  0x00006126fbf9797a in google::protobuf::util::(anonymous namespace)::DescriptorPoolTypeResolver::ConvertDescriptor(google::protobuf::Descriptor const*, google::protobuf::Type*) ()
#4  0x00006126fbf976c9 in google::protobuf::util::(anonymous namespace)::DescriptorPoolTypeResolver::ResolveMessageType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Type*) ()
#5  0x00006126fbf94535 in google::protobuf::util::BinaryToJsonStream(google::protobuf::util::TypeResolver*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::util::JsonPrintOptions const&) ()
#6  0x00006126fbf94895 in google::protobuf::util::BinaryToJsonString(google::protobuf::util::TypeResolver*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, google::protobuf::util::JsonPrintOptions const&) ()
#7  0x00006126fbf958d2 in google::protobuf::util::MessageToJsonString(google::protobuf::Message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, google::protobuf::util::JsonPrintOptions const&) ()
#8  0x00006126fbef56fb in google::protobuf::util::MessageToJsonString (message=..., output=0x786bd4027970)`

**Comment by tonyliaoss** [comment]
Hi mkzz115,

3.21.12 is considered EOL according to our "Version Support" page: https://protobuf.dev/support/version-support/#cpp

Can you try to see if you still see this issue with our latest version? Please file a new issue if this still happens in the latest protoc version.

**Comment by suguoqing** [comment]
@mkzz115 问题解决了吗？
