### ISSUE TITLE
Protoc generates non-working codes (ToString(), static constructors)

### ISSUE THREAD

**Issue by lyra95** [protocolbuffers/protobuf#17602]
When `--csharp_opt=experimental_strip_nonfunctional_codegen` is applied, protoc generates non-working code for `ToString()` method. It disturbs debugging experiences in IDE:

![image](https://github.com/user-attachments/assets/79aa3da1-6697-4f35-8406-62b95a9de8b7)

**What version of protobuf and what language are you using?**
Version: protoc-28.0-rc1
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
dotnet sdk 8.0.303

**What did you do?**

I've created small reproducible code as git repo.

[repo.zip](https://github.com/user-attachments/files/16375680/repo.zip)

1. download the archived git repo `repo.zip` and extract
2. build docker image (e.g. docker build -f Dockerfile . -t test)
3. docker run (e.g. docker run --rm --it test)
4. see 'System.TypeInitializationException' error logs

**What did you expect to see**

Unhandled exception should not happen, or non-working code (`ToString()`) should not be generated when `--csharp_opt=experimental_strip_nonfunctional_codegen` specified, or `[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]` should not be generated

**What did you see instead?**

Unhandled exception when `ToString()` called

**Comment by zhangskz** [comment]
Why are you setting `experimental_strip_nonfunctional_codegen`? I believe this is actually WAI -- this is an experimental flag that we added for internal tooling to remove nonfunctional codegen diffs when comparing gencode for legacy `proto2` / `proto3` and after migration to `editions` to ensure equivalent behavior.

I don't think gencode produced with this option is intended to be actually used.

**Comment by lyra95** [comment]
In our service we recently found that users easily restored original `.proto` files from gencode. We decide to use `experimental_strip_nonfunctional_codegen` to hide base64 encoded `.proto` content from users.
I understand this flag is not for our use case.
