### ISSUE TITLE
Mistake in Plugin Name "protoc-gen-go_grpc"

### ISSUE THREAD

**Issue by rei-smz** [protocolbuffers/protobuf#17637]
**What version of protobuf and what language are you using?**
Version: protoc-27.2-win64
Language: Golang

**What operating system (Linux, Windows, ...) and version?**
Windows 11
**What runtime / compiler are you using (e.g., python version or gcc version)**
go1.22.5 windows/amd64
protoc-gen-go-grpc v1.4.0
protoc-gen-go v1.34.2
**What did you do?**
1. Setup protoc-27.2-win64
2. Install protoc-gen-go and protoc-gen-go-grpc using `go install google.golang.org/protobuf/cmd/protoc-gen-go@latest` and `go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest` respectively
3. Try to generate Golang codes using `protoc --go_out=. --go_grpc_out=. [my .proto file]`
4. See error:
```
    'protoc-gen-go_grpc' is not recognized as an internal or external command, operable program or batch file.
    --go_grpc_out: protoc-gen-go_grpc: Plugin failed with status code 1.
```
5. Check the plugins in GOPATH and see the actual file name of protoc-gen-go-grpc is `protoc-gen-go-grpc`. It works after I changed the name to `protoc-gen-go_grpc`.
**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by shaod2** [comment]
Just double-checking if you pass the `--plugin=` flag to protoc, and the name of plugin file is irrelevant. For example, `protoc --plugin-gen-go_grpc=/path/to/my/go_grpc_plugin_binary --go_grpc_out=...`
