### ISSUE TITLE
[Python] Error when creating python protobuf object: MergeFrom() must be instance of same class 

### ISSUE THREAD

**Issue by maxnoe** [protocolbuffers/protobuf#17647]
**What version of protobuf and what language are you using?**

protobuf / libprotobuf 4.25.3 from conda-forge

**What operating system (Linux, Windows, ...) and version?**

Linux (Ubuntu 22.04)

**What runtime / compiler are you using (e.g., python version or gcc version)**

python, tested with multiple versions, 3.9, 3.10, 3.11

**What did you do?**

Minimal example:
```
from protozfits.CoreMessages_pb2 import AnyArray
from protozfits.R1v1_debug_pb2 import DebugCameraConfiguration

debug = DebugCameraConfiguration(
    tdp_type=AnyArray(type=AnyArray.U16, data=8 * b'\x00')
)
```

this fails using the latest protozfits from conda, which depends on protobuf 4.25.3, to reproduce:

```
$ mamba create -n proto-test python=3.11 protozfits=2.5.1
$ mamba activate proto-test
$ mamba list proto
# packages in environment at /home/mnoethe/.local/conda/envs/proto-test:
#
# Name                    Version                   Build  Channel
libprotobuf               4.25.3               h08a7969_0    conda-forge
protobuf                  4.25.3          py311h7b78aeb_0    conda-forge
protozfits                2.5.1           py311hcf1f2b2_0    conda-forge
$ python test_proto.py # contains the snippet posted above
Traceback (most recent call last):
  File "/home/mnoethe/Uni/CTA/test_protozfits.py", line 5, in <module>
    debug = DebugCameraConfiguration(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Parameter to MergeFrom() must be instance of same class: expected AnyArray got AnyArray.
```

**What did you expect to see**
No error, code works.

**What did you see instead?**
The error posted above.

**Anything else we should know about your project / environment**

This error happens with the conda package built using conda-forge. 

The python bindings code is generated using the protoc cmake integration as the project also interacts with C++ code.

This seems similar to https://github.com/protocolbuffers/protobuf/issues/10040, which was closed with unclear resolution.

**Comment by maxnoe** [comment]
For some reason I don't understand, the types are not identical in the conda package, but they are in the pip package:

```python
from protozfits.CoreMessages_pb2 import AnyArray
from protozfits.R1v1_pb2 import Event

event = Event()

print(event.waveform.__class__, id(event.waveform.__class__))
print(AnyArray, id(AnyArray))
print(id(AnyArray) == id(event.waveform.__class__))
```

Output in the conda env:
```
<class 'AnyArray'> 94075357242176
<class 'CoreMessages_pb2.AnyArray'> 94075364251936
False
```

Output using the PyPI package:
```
<class 'CoreMessages_pb2.AnyArray'> 94617635118128
<class 'CoreMessages_pb2.AnyArray'> 94617635118128
True
```

**Comment by shaod2** [comment]
I think there might be multiple messages out there with the same names but different path. Probably check if there're duplicates and import the correct one
