### ISSUE TITLE
Please address the google groups spam

### ISSUE THREAD

**Issue by mwpowellhtx** [protocolbuffers/protobuf#17659]
1. Consider enabling discussions area.
1. Less of a feature or even bug, more of a report on the mailing lists; the latest in a rash of spam flooding my inbox.
1. What are y'all doing about that issue? BTW, I'd be fine if y'all were to archive the thing, lock down new posts, etc. But up to you.

![image](https://github.com/user-attachments/assets/c5b2fdf5-cefb-49ba-b391-dc40810263e5)

Cheers, best... 🍻

**Comment by shaod2** [comment]
Yes we're handling them now.
