### ISSUE TITLE
In name of lazy "gnossen" I report bug "Incompability bug removed including_default_value_fields=False keyword without explanation (works in 1.62 but not in 1.64)"

### ISSUE THREAD

**Issue by ChameleonRed** [protocolbuffers/protobuf#17705]
https://github.com/gnossen thinks that is should reported here so I report in his name.
I have not Idea why I should report this bug here but you can explain me.

Tell me if it should be solved here?

https://github.com/grpc/grpc/issues/37184

https://github.com/grpc/grpc/issues/37184#issuecomment-2237646971

**What version of protobuf and what language are you using?**

I am using gRPC 1.64.

**What operating system (Linux, Windows, ...) and version?**

https://github.com/grpc/grpc/issues/37184

**What runtime / compiler are you using (e.g., python version or gcc version)**

https://github.com/grpc/grpc/issues/37184

**What did you do?**

https://github.com/grpc/grpc/issues/37184

**What did you see instead?**

https://github.com/grpc/grpc/issues/37184

**Anything else we should know about your project / environment**

I am using gRPC 1.64 which become incompatible.

**Comment by zhangskz** [comment]
This was an intentional breaking change in the protobuf v26.0 release that was pre-announced in https://engdoc.corp.google.com/eng/doc/devguide/proto/news/v26.md#JSON

Per the announcement, please use `always_print_fields_with_no_presence` instead which replaces this option.
