### ISSUE TITLE
Missing snapshot of 3rdparty submodules in release package

### ISSUE THREAD

**Issue by davidbolvansky** [protocolbuffers/protobuf#17715]
For example in latest release:
https://github.com/protocolbuffers/protobuf/releases/tag/v27.3

Folder third_party/abseil-cpp is empty.

**Comment by shaod2** [comment]
I think this links to [abseil-cpp](https://github.com/abseil/abseil-cpp/tree/4a2c63365eff8823a5221db86ef490e828306f9d) which has separate releases.
