### ISSUE TITLE
Allow setting gson instance of JsonFormat

### ISSUE THREAD

**Issue by nickrussler** [protocolbuffers/protobuf#17763]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
I want to be able to serialize into json without escaped special characters in strings.

**Describe the solution you'd like**
Allow passing the gson instance to JsonFormat, so the user can configure options.

**Describe alternatives you've considered**
Post processing to unescape the escaped characters.

**Additional context**
The need for this solutions has been voiced by multiple users including a closed PR:

https://github.com/protocolbuffers/protobuf/pull/9740

**Comment by shaod2** [comment]
Hi, as mentioned in https://github.com/protocolbuffers/protobuf/pull/9740#issuecomment-1088922308 we're not currently planning on it

**Comment by nickrussler** [comment]
I understand but I am not asking to add a zoo of options to the printer. Rather I am asking about the openness to pass the gson instance to the printer. This allows customization without overloading the interface of the printer.

**Comment by devinrsmith** [comment]
This would be a nice ergonomic option; I'm currently using Protobuf JSON in a context that doesn't involve HTML at all. I understand I _could_ re-parse and re-write the JSON however I wanted at the application layer, but given this functionality is possible with GSON, it would be nice to be able to not have to re-implement all of that functionality.
