### ISSUE TITLE
Maven central protoc prebuilts for riscv64

### ISSUE THREAD

**Issue by DingliZhang** [protocolbuffers/protobuf#17798]
**What version of protobuf and what language are you using?**
3.23.3 for Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 17

**What did you do?**
Go to https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.23.3/
Notice there's no protoc-3.23.3-linux-riscv64.exe or so.

RISC-V is an open source instruction set architecture whose instruction set is customizable, open, and extensible; it can be used in a variety of scenarios. It is becoming a popular architecture and is growing rapidly.

In popular distributions such as the ubuntu riscv port, protobuf is already included in the repositories, but there are currently no protoc prebuilts in the maven central repository, which makes it impossible to use protoc prebuilts directly for some packages (Hadoop, some plugins, etc.) that are built with maven.

Would it be possible to provide protoc prebuilts in the maven central repository and I could provide some tests on real hardware. Thanks a lot!

**What did you expect to see**
There's protoc prebuilts like other platform, e.g. protoc-3.23.3-linux-x86_64.exe

**What did you see instead?**

No protoc prebuilts

**Comment by googleberg** [comment]
@DingliZhang Unfortunately, riscv64 is not a platform supported by the protobuf project. 
https://github.com/protocolbuffers/protobuf/releases

For now, we are not staffed to add support for this platform. If things change, we can revisit.

**Comment by ankit-mh** [comment]
Hi @googleberg, 
I just wanted to check with you if the project open for external contribution for adding support for riscv64 platform.
If yes, then in your humble opinion what will be the required set of features that must be covered by the first PR.

**Comment by googleberg** [comment]
@ankit-mh we currently don't want to expand the release process to include the additional overhead of releasing a riscv64 version.  If the demand for this changes (i.e. for Cloud, Kubernetes, or something else) we will reconsider and accept PRs to add support.

**Comment by ankit-mh** [comment]
Sure @googleberg Thanks for your reply.

**Comment by DingliZhang** [comment]
@googleberg Thank you for the update.
