### ISSUE TITLE
Please add build instructions to the readme

### ISSUE THREAD

**Issue by sirus20x6** [protocolbuffers/protobuf#17848]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**
just add build instructions. I know it's cmake but doing mdkir build && cmake --build ./build doesn't work so I would love some build instructions here

**Describe alternatives you've considered**

**Additional context**

**Comment by Nickrader** [comment]
You have to follow a few links from the base README.
It is common in bigger projects to have multiple READMEs in different sections (in our case, folder 'cmake').
Cmake Linux:  https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#linux-builds

If that doesn't work, then you'll need to include, verbatim, the full error message.

**Comment by zhangskz** [comment]
Closing this, as we have documentation for this linked above in https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#linux-builds.

Of course, please feel free to suggest / contribute improvements to our cmake documentation!
