### ISSUE TITLE
datetime.utcnow, datetime.utcfromtimestamp(0) are deprecated in python 3.12.

### ISSUE THREAD

**Issue by ehiggs** [protocolbuffers/protobuf#17856]
**What version of protobuf and what language are you using?**

Version: 4.24.0

Language: Python

**What operating system (Linux, Windows, ...) and version?**

Mac, Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

python 3.12

**What did you do?**

Called GetCurrentTime.

**What did you expect to see**

A current time in UTC.

**What did you see instead?**

A current time in UTC provided by a deprecated method:

```
[...]venv/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:197: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self.FromDatetime(datetime.datetime.utcnow())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```

Re `datetime.datetime.utcfromtimestamp(0)`:

```
venv/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:93: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    _EPOCH_DATETIME_NAIVE = datetime.datetime.utcfromtimestamp(0)
```

**Anything else we should know about your project / environment**

Nope

**Comment by zhangskz** [comment]
Looks like this was already fixed in https://github.com/protocolbuffers/protobuf/commit/f0c56f9bc49b5015293eb5242a1982107b7c8b39 for v4.25.0+!

v4.24.x is out of support -- please upgrade to the latest version.

**Comment by ehiggs** [comment]
AFAICS, `GetCurrentTime` is still using the deprecated call on master: https://github.com/protocolbuffers/protobuf/blame/main/python/google/protobuf/internal/well_known_types.py#L178

I don't think this should have been closed. @zhangskz could you please reopen it? Thanks
