### ISSUE TITLE
Allow CodedInputStream extending

### ISSUE THREAD

**Issue by raipc** [protocolbuffers/protobuf#17853]
Allow CodedInputStream extending

**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
I want to be able to write optimized marshallers for sources other than JDK ByteBuffer and byte array (e.g. Netty ByteBuf, Chronicle Bytes, and Panama MemorySegment), to avoid overhead of adapter wrappers, and be able to customize the parsing, e.g. to return ByteString from a pool

**Describe the solution you'd like**
Remove private constructor in CodedInputStream and make the implementation classes protected and not final to allow extendibility

**Describe alternatives you've considered**
- Writing a separate class to implement all necessary operations on source stream and writing custom marshallers using it instead of CodedInputStream
- Accessing CodedInputStream internals using VarHandles and manipulating the state manually in marsallers

**Comment by googleberg** [comment]
Hi raipc,

There are a number of competing requirements for the future direction of the Java protobuf ecosystem. For several of those, expanding the implementation space for CodedInputStream would put more friction in our path.

So I'm sorry to say we won't be opening up CodedInputStream for extension at this time.
