### ISSUE TITLE
Create a Debian Package with each release

### ISSUE THREAD

**Issue by AndrewQuijano** [protocolbuffers/protobuf#17875]
**What language does this apply to?**
C and C++

If it's a proto syntax change, is it for proto2 or proto3?
proto3

**Describe the problem you are trying to solve.**
Rather than downloading the release and compiling it, it would be much easier to download a pre-compiled Debian package instead.

This became an issue because of this breaking change

https://github.com/protocolbuffers/protobuf/releases/tag/v21.0

The current versions of apt listed below will break when using later versions of Python Protobuffers. Ideally, the apt package would be updated.
![image](https://github.com/user-attachments/assets/02b41e76-7fda-4393-80c5-756b452d307d)

C++
protobuf-compiler

C (https://github.com/protobuf-c/protobuf-c/issues/736)
libprotobuf-c-dev
protobuf-c-compiler

**Describe the solution you'd like**
Each release, create a Debian package which can be used to install protobuf. This would also include updating apt repository ideally, but just getting from releases is sufficient too.

PANDA has a workflow to build Debian packages and store these on release
https://github.com/panda-re/panda/tree/dev/panda/debian
https://github.com/panda-re/panda/releases/tag/v1.8.39

**Describe alternatives you've considered**
I am not sure which other alternatives exist, but it would be helpful to also have the standard Debian package upgraded too
https://tracker.debian.org/pkg/protobuf

**Additional context**

This is the error message I get when using the versions of protobuf in apt

```text
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
````

**Comment by AndrewQuijano** [comment]
Might not be a bad idea to have CI to also generate an RPM package for any Fedora or Red Hat users too

**Comment by zhangskz** [comment]
Debian packages for protobuf are currently owned / maintained by Debian package maintainers. Unfortunately Protobuf is not currently staffed to directly own the creation and maintenance of Debian packages for each of our releases.

Precompiled artifacts for protoc are included in our Github releases.

**Comment by AndrewQuijano** [comment]
@zhangskz If I were to try submitting a PR to add a Debian package to each release, what would be the best way to do this?
