### ISSUE TITLE
Version 28.0 was not released in bazel central registry

### ISSUE THREAD

**Issue by joca-bt** [protocolbuffers/protobuf#17998]
Version 28.0 was not released in BCR (https://registry.bazel.build/modules/protobuf). Are there any plans to do so?

**Comment by googleberg** [comment]
Yes. We plan to. It appears that an automated process is broken. Hang tight.

**Comment by joca-bt** [comment]
@googleberg is the processed fixed? I see that 28.1 is not in BCR as well.

**Comment by zhangskz** [comment]
Confirming that automation for BCR release seems to be working again. Details in https://github.com/bazel-contrib/publish-to-bcr/issues/165

(Note v28.1 was manually added to BCR as well)

**Comment by joca-bt** [comment]
@zhangskz it's happening again with the latest version (31.0).
