### ISSUE TITLE
[Python] Support latest major version of numpy

### ISSUE THREAD

**Issue by AlexanderDokuchaev** [protocolbuffers/protobuf#18002]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
Current upper limit is [numpy<=1.26.1](https://github.com/protocolbuffers/protobuf/blob/807ecfd0faf20b8bb5246675d15ac952901cd5d1/python/requirements.txt#L1C1-L1C14) 

**Describe the solution you'd like**
Bump upper limit to <=2.1.0

**Describe alternatives you've considered**

**Additional context**
[numpy_2_0_migration_guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html)

**Comment by googleberg** [comment]
In what context are you running into the problem? As far as I know we only depend on numpy for 1 test. And in general our only involvement with numpy is to convert a numpy collection type.
