### ISSUE TITLE
Cross Compile ARM

### ISSUE THREAD

**Issue by mrManuel1983** [protocolbuffers/protobuf#18024]
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system: Linux**

**What runtime / compiler are you using: aarch64-linux-gnu-gcc**

Hi,
we would like to use protobuf to transfer data via tcp from our Xilinx Soc to a Windows system. We are trying to cross compile protobuf, but I get an issue and I don't find any information on the internet, and ChatGPT how to solve this.

Compiling protobuf results in an error while compiling the absl library.

[ 32%] Built target absl_random_internal_platform
[ 32%] Building CXX object third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/internal/randen_hwaes.cc.o
aarch64-xilinx-linux-g++.real: error: unrecognized command-line option '-maes'
aarch64-xilinx-linux-g++.real: error: unrecognized command-line option '-msse4.1'

I think somehow I have to set the architecture in the Cmake file so that the maes option won't be used. But I don't find any possiblity how to configure this. Is this a bug, or a lag of information.

Best regards
Manuel

**Comment by googleberg** [comment]
The '-maes' does seem to be x86 specific.
Unfortunately, this appears to be a fairly unique Xilinx environment situation that we don't officially support. If you find a solution that requires an update to CMake configuration, we would accept a PR to fix it.
