### ISSUE TITLE
Protobuf Python 5.28.0 crashes in __str__ on Windows x64

### ISSUE THREAD

**Issue by mtnpke** [protocolbuffers/protobuf#18045]
**What version of protobuf and what language are you using?**
Version: v5.28.0

Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 11 23H2 Build 22631.4037

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32

**What did you do?**
* Create Python venv
* Run `pip install protobuf` (as of today: installs protobuf 5.28.0)
* Create test.proto with this content:

```proto
syntax = "proto3";

message MyMessage {
    string test = 1;
}
```

* Run `protoc --python_out=. -I. test.proto`
* Create test.py with this content:

```python
import test_pb2
for i in range(100):
    print(i)
    m = test_pb2.MyMessage()
    print(m)
print("ok")
```

* Run `python test.py`

**What did you expect to see**
Counting from 0 to 99 and then "ok"

**What did you see instead?**
Crash at i = 1

![image](https://github.com/user-attachments/assets/a6ab4b4a-a28c-4122-825f-3a94fab41925)

![image](https://github.com/user-attachments/assets/0e2d1213-5001-4ea6-a685-f2286e64e6a3)

Note: There is no crash with protobuf Python package 5.27.4. Crashing starts with 5.28.0rc1.

Note: If you include an integer field instead of a string, it will not crash, but display random values for the field.

**Comment by aaltat** [comment]
I am seeing something similar within my project. Update to protobuf broke my test in Windows https://github.com/MarketSquare/robotframework-browser/actions/runs/10608698864/job/29403939266?pr=3765

**Comment by liqunfu** [comment]
We have same failure with windows build: https://github.com/onnx/onnx/actions/runs/10687189577/job/29624209865?pr=6327

**Comment by mkruskal-google** [comment]
I was able to reproduce this using x64 python 3.12.5.  I also tried x86 3.12.5 and x64 3.10.4 first and had no luck.  So this looks like something very tied to python version we likely missed in our test coverage

**Comment by mkruskal-google** [comment]
It looks like this is only reproducible under all of the conditions:
1) windows
2) 64-bit protobuf wheel
3) optimized build
4) python 3.12

4) is a little less clear, as our GHA show segfaults under all python versions when I switch to opt

**Comment by aaltat** [comment]
Hmmm, at least on my GotHub actions error is not tied to specific python version, example this uses 3.9 https://github.com/MarketSquare/robotframework-browser/actions/runs/10660730916/job/29545167895?pr=3765

But in the other I have pytest in the picture too

**Comment by mtnpke** [comment]
I have confirmed this on both 3.11 and 3.12; I did not test other versions.

**Comment by liqunfu** [comment]
The issue is not completely fixed. Please fix the wheel at: https://pypi.org/project/protobuf/5.28.0/ before close this issue - create a post release package to override the current one which has the original issue.
