### ISSUE TITLE
false positive in protoc same enum item name detection

### ISSUE THREAD

**Issue by andorpatho-dlubal** [protocolbuffers/protobuf#18149]
**What version of protobuf and what language are you using?**
Version: libprotoc 26.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.10.11

**What did you do?**
Got the following error when trying to compile a .proto file:

"Enum name WIND_PROFILE_LOAD_ZONE_E_LOAD_ZONE_TYPE_1_0 has the same name as WIND_PROFILE_LOAD_ZONE_E_LOAD_ZONE_TYPE_10 if you ignore case and strip out the enum name prefix (if any)."

As you can see, the enum item names are similar, but definitely not the same. While I know there is some prefix stripping going on in different protoc implementations for some languages, I see no reason why these two names should be considered the same, even if you ignore case and strip out the prefix (which is WindProfileLoadZone in this case).

**Comment by googleberg** [comment]
@andorpatho-dlubal I think that the actual prefix detected here is:
`WIND_PROFILE_LOAD_ZONE_E_LOAD_ZONE_TYPE_1` which would lead to the enum value names:
`0` and `_0` and I believe the escaping system would then escape `0` to `_0` making them equivalent. It is slightly unfortunate but it is unlikely to be worth the effort to make protoc distinguish between `_0` and `0` via `__0` or something.

**Comment by andorpatho-dlubal** [comment]
WIND_PROFILE_LOAD_ZONE_E_LOAD_ZONE_TYPE_1 cannot be the detected prefix, because the enum has other items which don't have that prefix, e.g. WIND_PROFILE_LOAD_ZONE_UNKNOWN or WIND_PROFILE_LOAD_ZONE_E_LOAD_ZONE_TYPE_GAMMA.

It seems to me that the check compares enum items with underscores completely stripped out, tested it on the enum items LOAD_ZONE_TYPE_A_101 and LOAD__ZONE__TYPE__A__1__0__1_ and got the same error (protoc says they're the same). Looks like an unnecessary limitation, which the error message doesn't even warn about.
