### ISSUE TITLE
`Plugin killed by signal 9.` when generating Python code from Ads protos

### ISSUE THREAD

**Issue by BenRKarl** [protocolbuffers/protobuf#18155]
**What version of protobuf and what language are you using?**
Version: `25.3`
Language: `Python`

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9

**What did you do?**
I'm running a Google-internal version of Bazel against internal WORKSPACE and BUILD files, can share details internally. The below likely won't net a full reproduction, but gives you an idea of what I'm trying to do.

1. Remove [this line](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v17/BUILD.bazel#L227) from the list of options passed to `protoc`
2. Run `bazel build --verbose_failures --sandbox_debug --experimental_convenience_symlinks=normal googleads-py` from [this directory](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v17)

**What did you expect to see**
This [option](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v17/BUILD.bazel#L227) tells the [gapic generator](https://github.com/googleapis/gapic-generator-python) to build Python code using [these ads-specific templates](https://github.com/googleapis/gapic-generator-python/tree/main/gapic/ads-templates). By removing that line, I expect the pipeline to generate Python code using the [default templates](https://github.com/googleapis/gapic-generator-python/tree/main/gapic/templates) instead.

**What did you see instead?**
An error that looks like this:

```
ERROR: /.../google/ads/googleads/v17/BUILD.bazel:218:17: @//google/ads/googleads/v17:googleads_py_gapic_srcjar: `bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional --plugin=protoc-gen-python_gapic=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin --python_gapic_out=metadata,retry-config=google/ads/googleads/v17/googleads_grpc_service_config.json,service-yaml=google/ads/googleads/v17/googleads_v17.yaml:bazel-out/k8-fastbuild/bin/google/ads/googleads/v17/googleads_py_gapic_srcjar.srcjar.zip --python_gapic_opt=old-naming,lazy-import,python-gapic-name=googleads,python-gapic-templates=templates,warehouse-package-name=google-ads ... failed: (Exit 1): protoc failed: error executing command (from target //google/ads/googleads/v17:googleads_py_gapic_srcjar) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional ... (remaining 1719 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
google/ads/googleads/v17/services/campaign_draft_service.proto:26:1: warning: Import google/protobuf/empty.proto is unused.
google/ads/googleads/v17/services/batch_job_service.proto:27:1: warning: Import google/protobuf/empty.proto is unused.
google/ads/googleads/v17/services/offline_user_data_job_service.proto:26:1: warning: Import google/protobuf/empty.proto is unused.
--python_gapic_out: protoc-gen-python_gapic: Plugin killed by signal 9.
Target //google/ads/googleads/v17/ads_assembly:googleads-v17-python-adslib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1942.364s, Critical Path: 1781.92s
INFO: 2586 processes: 281 internal, 2305 linux-sandbox.
FAILED: Build did NOT complete successfully
E0821 23:53:20 generate: log_fatal: 84] Error invoking Bazel build on targets: //google/ads/googleads/v17/ads_assembly:googleads-v17-python-adslib
```
The server logs from our internal version of Bazel point to this error `(Exit 1): linux-sandbox failed: error executing command`. The command it's executing is the call to `protoc`.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by googleberg** [comment]
@zhangskz Can you take a look at this one?

**Comment by zhangskz** [comment]
The [protoc error](https://github.com/protocolbuffers/protobuf/blob/3431016e91ef966edc2ddde084657c1970ae240c/src/google/protobuf/compiler/subprocess.cc#L460) is simply that the `protoc-gen-python_gapic` plugin subprocess was killed by signal 9, which seems to typically be due to memory issues.

It seems like this may be a problem with that particular plugin -- could you try filing an issue to https://github.com/googleapis/gapic-generator-python/issues instead?

**Comment by zhangskz** [comment]
Closing as inactionable, but please reopen if this seems to point at protoc rather than the plugin.
