### ISSUE TITLE
How can I get the protobuf==2.4.0？

### ISSUE THREAD

**Issue by Skylarking** [protocolbuffers/protobuf#18204]
I check the release list, and find that the oldest version is 2.4.1. Where do I get the 2.4.0 version?

**Comment by tonyliaoss** [comment]
Hi, why is it important for you to get 2.4.0? Even 2.4.1 was released in 2015.

**Comment by touchinglie** [comment]
> Hi, why is it important for you to get 2.4.0? Even 2.4.1 was released in 2015.嗨，为什么获得 2.4.0 对您来说很重要？甚至 2.4.1 也在 2015 年发布。

Maybe some old neural networks or models, such as ncnn required protobuf 2.4.0.
But my board only supported Debian bullseye, I can't install it by apt.

**Comment by tonyliaoss** [comment]
We don't actively remove old releases from GitHub, but we don't offer support beyond what is stated here:

https://protobuf.dev/support/version-support/
