### ISSUE TITLE
After build and install protobuf 3.22.2, why we get "Protobuf version required: 3.22.2, actual: 22.2"? how to match 3.22.2 with 22.2?

### ISSUE THREAD

**Issue by Naziburjec** [protocolbuffers/protobuf#18225]
We want upgrade protobuf 2.5.0 to 3.22.2 but we are not able to do because protoc version 22.2 instead of 3.22.2
**What version of protobuf and what language are you using?**
protobuf 3.22.2
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Sles15 sp4
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (SUSE Linux) 12.3.0
**What did you do?**
Cloned https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout v3.22.2
git submodule update --init --recursive
cmake . -DCMAKE_CXX_STANDARD=14 -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_CXX_FLAGS="-fPIC" && \
		cmake --build . && \
		cmake --install . 

**What did you expect to see**
I want protoc version 3.22.2 instead of 22.2
**What did you see instead?**
I see 22.2 instead of 3.22.2
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
attached log
[protobuf.log](https://github.com/user-attachments/files/16957906/protobuf.log)

**Anything else we should know about your project / environment**

**Comment by tonyliaoss** [comment]
Hi Nazibur,

I think this is WAI. We describe our versioning methodology over here: https://protobuf.dev/support/version-support/

Protoc and protobuf's language-specific releases have different versioning.

A C++ version of, say, 3.22.2, is packaged with protoc version 22.2.

We do this to allow every language to have its own major version that can be updated independently. This allows us to introduce changes that might break in one language (and therefore necessitate a major version bump) without a major version bump in another language.
