### ISSUE TITLE
Json Parser for Protobuf Java Lite

### ISSUE THREAD

**Issue by V-Abhilash-1999** [protocolbuffers/protobuf#18305]
**What language does this apply to?**
Proto3
Java

**Describe the problem you are trying to solve.**
I have recently moved from protobuf-java to protobuf-java-lite, since I faced **_Duplicate Class Exception_** beacuse a library I am using uses protobuf-java-lite and I am using protobuf-java. A major downside to this change is that I cannot parse JSON to Proto Objects like I used to.

**Describe the solution you'd like**
It would be better to provide something like protobuf-java-lite-util similar to protobuf-java-util for JsonParser in Java Lite Protobuf library.
Is there any library and/or workaround for me to achieve this?

**Comment by JasonLunn** [comment]
Unfortunately, Java Lite proto doesn't support JSON formats by design. JSON formats require proto descriptors to map between JSON keys and proto field names/type information, which are intentionally absent in Java Lite.
