### ISSUE TITLE
no such attribute 'output_files' in 'proto_lang_toolchain' rule

### ISSUE THREAD

**Issue by Chenrujie-85** [protocolbuffers/protobuf#18464]
I encountered an issue while compiling envoy release v1.31. The envoy of v1.31 depends on the protobuf of v26.1. I encountered an error while "make build": com_googlesprotobuf/unpb-generator/BILD: 279:21: @ com-googlesprotobuf//upc_generator: rotoc-gen-upc_toolchain: no such attribute 'outputting files' in' protogulang_toolchain 'rule
This error appears on lines 279, 338, and 371. Can someone explain the reason for the error or tell me how to solve it

protobuf version：v26.1

**Comment by KarloFab** [comment]
Hey @Chenrujie-85, could you please let me know how did you resolve this?
I am having the same issue using  envoy of v1.32.4 and protobuf of v.29.1.
Thank you

**Comment by rajukrishnamurthy** [comment]
@KarloFab I'm running into this too, are you on bazel < 7.x by any chance?  I'm wondering if the issue is an untested path [here](https://github.com/protocolbuffers/protobuf/blob/main/bazel/toolchains/proto_lang_toolchain.bzl#L34)
