### ISSUE TITLE
protoc.exe crash

### ISSUE THREAD

**Issue by LinusChen-yf** [protocolbuffers/protobuf#18497]
![image](https://github.com/user-attachments/assets/20a6da04-ba3c-4ab8-86c1-a6464dbc71fe)

I installed protocbuf using vcpkg, but when I execute `protoc.exe`, a folder named AppCrash_protoc.exe_XXX is generated and no output is given. It is expected that the help content will be printed.

I copied this protoc.exe and dll to another Windows computer, and it can output content normally.

The version of protoc printed on another machine is
```
PS C:\Users\crash> protoc --version
libprotoc 3.21.12
```

The Windows version that crashed is
```
Windows 11 Pro 23H2 22631.4169
```

[AppCrash_protoc.exe_e43c3dd82ba57b9e5e7ef8d063f75e8b7de35b9_3493a1a3_e52e5bf6-720a-4285-b9bf-a4b4e69652b7.zip](https://github.com/user-attachments/files/17127468/AppCrash_protoc.exe_e43c3dd82ba57b9e5e7ef8d063f75e8b7de35b9_3493a1a3_e52e5bf6-720a-4285-b9bf-a4b4e69652b7.zip)

**Comment by JasonLunn** [comment]
@LinusChen-yf - is this reproducible on the latest release? 3.21 is years old and [left the support window](https://protobuf.dev/support/version-support/#cpp) earlier this year.

**Comment by LinusChen-yf** [comment]
Thank you, I don't know why the default version of vcpkg installed before was older, I upgraded to the new version and it worked fine.
