### ISSUE TITLE
Python client reports obscure error message while calling a RPC with a type-incompatiable message

### ISSUE THREAD

**Issue by rpstw** [protocolbuffers/protobuf#18499]
**What version of protobuf and what language are you using?**
Version:  grpcio==1.58, ==1.66.1 tested 
Language: Python Client

**What operating system (Linux, Windows, ...) and version?**
Linux e0378c1caf34 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 GNU/Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.0

Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

**What did you do?**
1. Having a gRPC definition like this, notice that there's a single and batch version push
```protobuf
service Push {
  rpc Push(PushRequest) returns (google.protobuf.Empty);
  rpc BatchPush(BatchPushRequest) returns (google.protobuf.Empty);
}

message BatchPushRequest {
  repeated PushRequest tasks = 1;
}

message PushRequest {
  string chat_id = 1;
  string text = 2;
  repeated string at_people = 3;
}
```
2. call gRPC server using a python client, but having some typo that mix incompatible RPC and message type
```python
with grpc.insecure_channel('localhost:50051') as channel:

        stub = example_pb2_grpc.PushServiceStub(channel)

        # use the single version request
        request = example_pb2.BatchPushRequest(tasks=[example_pb2.PushRequest(.......)])
       
        # use the batch version RPC, BatchPushRequest is incompatible with Push
        response = stub.Push(request)
```
**What did you expect to see**
A clear error message telling me `BatchPushRequest` can not be used with `Push`

**What did you see instead?**
unhelpful error message

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "grpc: error unmarshalling request: string field contains invalid UTF-8"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"grpc: error unmarshalling request: string field contains invalid UTF-8", grpc_status:13, created_time:"2024-09-25T20:43:33.119612706+08:00"}"
>
```

**Comment by JasonLunn** [comment]
Hi @rpstw -

I recommend you refile this issue with https://github.com/grpc/grpc. Protobuf owns the underlying serialization library that gRPC uses, but the code here doesn't do networking.
