### ISSUE TITLE
Bazel warning: "source value 8 is obsolete and will be removed in a future release"

### ISSUE THREAD

**Issue by drigz** [protocolbuffers/protobuf#18545]
**What version of protobuf and what language are you using?**
Version: 26.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux + Bazel

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 21 via rules_java 7.x

**What did you do?**
```
bazel build -s @com_google_protobuf//java/core:lite_runtime_only
```

**What did you expect to see**
No warnings. If newer versions of protobuf are not expected to work with Java 11, maybe the source_version can be increased to 17? But I know nothing about the constraints on users, I'm just trying to stop our build printing non-actionable warnings.

**What did you see instead?**
```
INFO: From Building external/protobuf~26.0.bcr.2/java/core/liblite_runtime_only.jar (92 source files):
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
```

**Anything else we should know about your project / environment**

- https://github.com/bazelbuild/rules_java/issues/148 prevents me from working around this without downgrading rules_java to 6.x
- although I can work around it with `build --javacopt=-Xlint:-options` in .bazelrc, although that may suppress some other warnings too
- https://github.com/protocolbuffers/protobuf/issues/4220 is a previous iteration of this warning, where it was resolved by dropping support for the older Java version.

**Comment by zhangskz** [comment]
I believe we specify this in our JAVA_OPTS: https://github.com/protocolbuffers/protobuf/blob/77ee83b8da7d94bf5df6ca796f3ac66265879996/build_defs/java_opts.bzl#L8 so our maven artifacts created via `protobuf_java_export` work with java8. We still need to support Java 8 until 2026 per the foundational support policies: https://github.com/google/oss-policies-info/blob/main/foundational-java-support-matrix.md. In general, I think we only need this for creating our release artifacts which users should generally not need to build.

@deannagarcia Do you know if/why these javacopts were needed for `protobuf_java_library` which is where we hit this for `@com_google_protobuf//java/core:lite_runtime_only`? I think we could either remove this, or isolate these javacopts to release-only targets.

**Comment by deannagarcia** [comment]
I agree that we can make these options specific to release, working on a fix now.

**Comment by deannagarcia** [comment]
I believe this should be solved with https://github.com/protocolbuffers/protobuf/commit/59e469d5b090ac804317dc7a6201c556f438358d. Feel free to reopen if you see any more issues!

**Comment by Soliardi-Chyngyz** [comment]
I have same warning, how to fix? 
Does it affect the performance of the application?

**Comment by zhangskz** [comment]
This should get picked up in the next release. We should be able to backport this for the v29.0 release.
