### ISSUE TITLE
Please bump rules_rust version to avoid failures when `--incompatible_use_plus_in_repo_names` is on

### ISSUE THREAD

**Issue by tpasternak** [protocolbuffers/protobuf#18546]
https://github.com/bazelbuild/rules_rust/issues/2801

**Comment by JasonLunn** [comment]
To clarify - what version of `rules_rust` addresses the issue discussed in https://github.com/bazelbuild/rules_rust/issues/2801?

**Comment by tpasternak** [comment]
So I tried the newest one and it was ok

**Comment by JasonLunn** [comment]
Is that https://github.com/bazelbuild/rules_rust/releases/tag/0.51.0 @tpasternak ?

**Comment by tpasternak** [comment]
yeah, it's fine

**Comment by tpasternak** [comment]
it's easy to reproduce, just try `bazel mod dump_repo_mapping --incompatible_use_plus_in_repo_names`
