### ISSUE TITLE
com.google.protobuf.util.Timestamps deprecations refer to unavailable JavaTimeConversions type

### ISSUE THREAD

**Issue by SanjayVas** [protocolbuffers/protobuf#18925]
**What version of protobuf and what language are you using?**
Version: 4.27.4 via `com.google.protobuf:protobuf-java-util` Maven artifact
Language: Kotlin JVM

**What operating system (Linux, Windows, ...) and version?**
Linux (Debian Bookworm)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Kotlin 2 + JDK 17

**What did you do?**
1. Write code that references `com.google.protobuf.util.Timestamps.add`
2. Observe deprecation warning
3. Attempt to follow documented instructions for deprecation
4. Compilation error as referenced type is not available

**What did you expect to see**
Either
1. The referenced `JavaTimeConversions` type is available
2. No deprecation warning

**What did you see instead?**
A deprecation warning referencing an unavailable type.

**Anything else we should know about your project / environment**
There are some `MOE` comments that make it seem like the deprecation annotation and documentation were supposed to be stripped from the open source release.

**Comment by deannagarcia** [comment]
Thanks for reporting this issue! I submitted a change to remove those deprecation warnings.

**Comment by jazdw** [comment]
> Thanks for reporting this issue! I submitted a change to remove those deprecation warnings.

There are no methods available in `com.google.protobuf.util.Timestamps` to convert to/from a `java.time.Instant`. The method which is used internally to convert an instant `com.google.protobuf.util.Timestamps#normalizedTimestamp` is also not public.
