### ISSUE TITLE
Getting Verify Error Even after excluding Protobuf Lite

### ISSUE THREAD

**Issue by V-Abhilash-1999** [protocolbuffers/protobuf#19047]
**What version of protobuf and what language are you using?**
Version: 3.19.2
Language: Java

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What did you do?**
1. Take a Library that uses protobuf-javalite and has a proto definition containing Float Value
2. Add it to an application that has another library that use protobuf-java
3. Exclude protobuf-javalite from the first library.
4. See the below mentioned error
java.lang.VerifyError: Verifier rejected class CompanyName$ClassName: void className.mergeAll(com.google.protobuf.FloatValue) failed to verify: void className.mergeAll(com.google.protobuf.FloatValue): [0x13] register v3 has type Precise Reference: com.google.protobuf.FloatValue but expected Reference: com.google.protobuf.GeneratedMessageLite

**What did you see instead?**
I am getting the above error on the mentioned steps. Is there a way to fix this issue

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I have developed a library A and published it. My user uses it along with library B.

Library A
 - Uses Protobuf-javalite
 - Uses FloatValue
 
 Library B
 - Uses Protobuf-Java
 
 Initially it causes Duplicate Class exception. We have excluded the Protobuf-javalite from library A. Now App is built and everything seems to be working fine till that particular FloatValue is initialized. The app crashes with the mentioned error
`java.lang.VerifyError: Verifier rejected class CompanyName$ClassName: void className.mergeAll(com.google.protobuf.FloatValue) failed to verify: void className.mergeAll(com.google.protobuf.FloatValue): [0x13] register v3 has type Precise Reference: com.google.protobuf.FloatValue but expected Reference: com.google.protobuf.GeneratedMessageLite
`

**Comment by googleberg** [comment]
Hi @V-Abhilash-1999, unfortunately, protobuf 3.19 is no longer supported. Update to the latest 4.28.3 if you can. If you need compatibility with libraries that use 3.x gencode, then the latest supported release in the 3.x line is 3.25.5
[version support info](https://protobuf.dev/support/version-support/#java)
