### ISSUE TITLE
Getting Verify Error Even after excluding Protobuf Lite

### ISSUE THREAD

**Issue by V-Abhilash-1999** [protocolbuffers/protobuf#19130]
What version of protobuf and what language are you using?
Version: 3.25.5
Language: Java

What operating system (Linux, Windows, ...) and version?
MacOS

What did you do?

Take a Library that uses protobuf-javalite and has a proto definition containing Float Value
Add it to an application that has another library that use protobuf-java
Exclude protobuf-javalite from the first library.
See the below mentioned error
java.lang.VerifyError: Verifier rejected class CompanyName$ClassName: void className.mergeAll(com.google.protobuf.FloatValue) failed to verify: void className.mergeAll(com.google.protobuf.FloatValue): [0x13] register v3 has type Precise Reference: com.google.protobuf.FloatValue but expected Reference: com.google.protobuf.GeneratedMessageLite
What did you see instead?
I am getting the above error on the mentioned steps. Is there a way to fix this issue

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Anything else we should know about your project / environment
I have developed a library A and published it. My user uses it along with library B.

Library A

Uses Protobuf-javalite
Uses FloatValue
Library B

Uses Protobuf-Java
Initially it causes Duplicate Class exception. We have excluded the Protobuf-javalite from library A. Now App is built and everything seems to be working fine till that particular FloatValue is initialized. The app crashes with the mentioned error

`java.lang.VerifyError: Verifier rejected class CompanyName$ClassName: void className.mergeAll(com.google.protobuf.FloatValue) failed to verify: void className.mergeAll(com.google.protobuf.FloatValue): [0x13] register v3 has type Precise Reference: com.google.protobuf.FloatValue but expected Reference: com.google.protobuf.GeneratedMessageLite `

**Comment by V-Abhilash-1999** [comment]
I have also recreated the issue with 4.28.3 version

**Comment by esrauchg** [comment]
If I'm understanding the issue correct, unfortunately I think you just inherently can't do what you're asking about

With protobuf, java-lite versus java-full has a number of places where the APIs are _source_ compatible but not _jar/bytecode_ compatible, so if you compile against java-lite the resulting jar can't be swapped out to use java-full or vice versa.

To clarify the difference between the source compatible and bytecode compatible, consider a case like

```
class Base {}
class Sub { int x() { return 0; } }
```

And
```
class BaseClass { int x() { return 0; } }
class Sub extends Base { }
```

And caller code that does:
```
Sub s = new Sub();
s.x();
```

That 'caller code' is source compatible with both of the implementations, but when you compile it to a .class file it'll actually resolve and statically emit it as directly either a Base::x() or a Sub::x() call. So the two definitions of Base and Sub both can be compiled from source with that snippet, but if you compile from source with one of them and then swap out the implementation after and use a mismatched .class it will have in the .class file a reference to something that isn't there.

I think you'll unfortunately need to compile the two libraries from source with the same java protobuf version, _or_ resort to much more complicated tricks to get 2 copies of protobuf with different packages so you can ship both without a collision.

**Comment by V-Abhilash-1999** [comment]
Is there a way to get 2 copies of protobuf with different packages?
If so, how do I achieve that?

**Comment by esrauchg** [comment]
There's nothing special about protobuf in that regard, you may find information online about workarounds to have 2 different versions of the same Java library.

It is possible but a poorly supported topic in the JVM. I think its achievable by having explicit code that uses classloader APIs and loads/unloads the corresponding definitions before calling the libraries that need specific versions, or something that rewrites the .class files to make the two packages unique after they have already been compiled; there may be other hacky approaches that don't immediately occur to me.

**Comment by V-Abhilash-1999** [comment]
I apologize for the repeated follow-ups. But If I were to use Protobuf-Java 2.x.x and 3.x.x, as far as I have seen, android just takes latest version. 
But that is not the case for protobuf-java and protobuf-javalite, both library are not the same and yet they contain the class with the same package name and class name _(This entire issue and countless others could be avoided if they were to use different packages or to have a unified library for the duplicated class)_. This results in duplicate class exception, which forces us to exclude one or the other.
If we were to use Protobuf-java 3.x.x and our user were to use Protobuf-java 2.x.x, we could at least ask them to migrate to the latest version. But this is not that case. 
Including our library means they have to face duplicate class exception and even if they exclude the duplicated class, they are facing crash.

It might not be feasible for us to provide 2 different libraries with protobuf-java and protobuf-javalite, because if our users are themselves library developers, they also have to provide 2 different libraries to their users and this would grow like this.

Is there a way to create a class from proto using protobuf-javalite (or protobuf-java) that would not break even if we were to exclude the dependency that we provide?

**Comment by esrauchg** [comment]
Zooming out a little bit, we simply don't support having gencode that targets lite be used with the full runtime or vice versa. You must create the gencode for the matching corresponding runtime, and we unfortunately don't have good technical solution for supporting otherwise.

I understand that creates difficulty for a case like yours where you want to ship a .jar to someone else who also will use protobuf, but it's the reality of the design space.

> (This entire issue and countless others could be avoided if they were to use different packages or to have a unified library for the duplicated class)

This really relates to inherent constraints where we have to make a choice for what should work. Taking `com.google.protobuf.FloatValue` as a concrete example, if we had the lite vs full gencode of that type have different java package then you could have 2 definitions in the same binary like you're thinking of, but it in turn would mean you couldn't write a util function that operates on FloatValue and reuse that same util function in both an app that uses full and an app that uses Lite, because there would be 2 different FloatValue types that you want to import.

We find that usecase to be much more prevalent (eg, write some application logic and reuse it in your server where you use Full and on your client where you use Lite) rather than the usecase of trying to mix and match .jars that want to use both full and lite.
