### ISSUE TITLE
C++ errorLNK2001 libprotobuf.lib ?

### ISSUE THREAD

**Issue by dddd545r** [protocolbuffers/protobuf#19290]
Hello,

I am unable to integrate protobuf.lib into my project after adding the generated cpp and h files from protoc
I am encountering linker error LNK2001.
In my project, I’ve confirmed that the linker is correctly pointing to protobuf.lib, and for the includes, I’ve specified the path to src/google/....

Any Help?

**Comment by acozzette** [comment]
Could you post the full linker error you're getting?
