### ISSUE TITLE
Add 'multimap' as a keyword

### ISSUE THREAD

**Issue by robertmassaioli** [protocolbuffers/protobuf#1930]
It would be great to have:

```
multimap<A, B>
```

So that when we use the inbuilt merge functions we have a map implementation that concatenates the entries instead of picking one or the other.

**Comment by costimuraru** [comment]
👍

**Comment by haon4** [comment]
Multimap isn't a built-in data type in many languages. Unfortunately I don't think we will be able to support this in the foreseeable future.

**Comment by robertmassaioli** [comment]
> Multimap isn't a built-in data type in many languages. Unfortunately I don't think we will be able to support this in the foreseeable future.

This does not sound quite right. I think that most languages have a concept of a Map that contains a List. Let's run through the languages that Protobuf supports:

 * C++: https://en.cppreference.com/w/cpp/container/multimap
 * C#: `Dictionary<Key, IList<Value>>` in the simple case. More examples here: https://stackoverflow.com/q/380595/83446
 * DART: You can get this from the quiver library: https://api.flutter.dev/flutter/quiver.collection/Multimap-class.html
 * GO: Maybe this is the language that you have in mind? It does not seem to support multimaps natively and has poor library support. See https://stackoverflow.com/q/30529970/83446 and https://github.com/jwangsadinata/go-multimap
 * JAVA: This has support. Either via [Guava](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Multimap.html) or using a `Map<K, List<V>>`
 * PYTHON: Could use defaultDict: https://stackoverflow.com/a/1731989/83446

It seems like this should be possible and would be a powerful addition to Google Protocol buffers. It would indeed be unfortunate to see this marked as closed forever.

**Comment by haon4** [comment]
Problem with using anything that is not part of the language built-in is that some day, when the language does offer built-in support for them, then we will need to introduce breaking API changes to use that built-in one, which is something that we try very hard to avoid. Or we will need to live with our custom multimap being different from the built-in ones, which is also not ideal.

In may cases above, you can achieve similar results with `map<K, Message>` where Message contains a repeated field. It is slightly more verbose, but achieves almost the same result as `Dictionary<Key, IList<Value>>` or `Map<K, List<V>>`

Maybe some day all languages will have the multimap support built-in. Then maybe we can revisit this.

**Comment by robertmassaioli** [comment]
> In may cases above, you can achieve similar results with map<K, Message> where Message contains a repeated field. It is slightly more verbose, but achieves almost the same result as Dictionary<Key, IList<Value>> or Map<K, List<V>>

That's actually an excellent workaround. Thanks for suggesting it!
