### ISSUE TITLE
C++20 no member named 'derived_from' in namespace 'std'

### ISSUE THREAD

**Issue by Tradias** [protocolbuffers/protobuf#19364]
**What version of protobuf and what language are you using?**
Version: v28.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 20.04.6, Github runner (see https://github.com/actions/runner-images/blob/ubuntu20/20241117.1/images/ubuntu/Ubuntu2004-Readme.md)

**What runtime / compiler are you using (e.g., python version or gcc version)**

Clang 10 with `-stdlib=libc++`

**What did you do?**

Compile any program that includes `src/google/protobuf/port.h`.

Additionally, regardless of the compiler, the static_assertion inside `google::protobuf::internal::AssertDownCast` from `src/google/protobuf/port.h` will always fail.

**What did you expect to see**

Compiles cleanly

**What did you see instead?**

```
In file included from /home/runner/work/asio-grpc/vcpkg_installed/x64-linux-clang-release/include/google/protobuf/io/coded_stream.h:114:
Error: /home/runner/work/asio-grpc/vcpkg_installed/x64-linux-clang-release/include/google/protobuf/port.h:177:10: error: no member named 'derived_from' in namespace 'std'
    std::derived_from<std::remove_pointer_t<To>,
    ~~~~~^
Error: /home/runner/work/asio-grpc/vcpkg_installed/x64-linux-clang-release/include/google/protobuf/port.h:177:48: error: expected '(' for function-style cast or type construction
    std::derived_from<std::remove_pointer_t<To>,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Anything else we should know about your project / environment**

Suggested fixes:

**Either keep using C++20**

Add the following to the top of `src/google/protobuf/port.h`

```c++
#if __cpp_lib_concepts >= 202002L
#include <concepts>
#endif
```

Clean up this usage of concepts https://github.com/protocolbuffers/protobuf/blob/8476dbacb35dfb4b149256581467603cb005708c/src/google/protobuf/port.h#L184

Change

```c++
#if defined(__cpp_concepts)
  static_assert(!requires {
    std::derived_from<std::remove_pointer_t<To>,
                      typename std::remove_pointer_t<To>::MessageLite>;
  });
```

to 

```c++
#if __cpp_lib_concepts >= 202002L
  static_assert(!std::derived_from<std::remove_pointer_t<To>,
                      typename std::remove_pointer_t<To>::MessageLite>);
#endif
```

**Or switch to older C++ standard**

Replace `std::derived_from` with

```c++
template<class Derived, class Base>
struct DerivedFrom : std::integral_constant<bool, (std::is_base_of<Base, Derived>::value &&
    std::is_convertible<const volatile Derived*, const volatile Base*>::value)>
{};
```

**Comment by acozzette** [comment]
Thank you for the bug report. We would be happy to review a pull request if you would like to send us one, but if not then we will probably get around to this eventually.

**Comment by acozzette** [comment]
Unfortunately we do still use this `DownCast()` function in some internal-only code, so I wasn't able to submit your entire change.

**Comment by Tradias** [comment]
@acozzette that is surprising. I thought you guys are using C++20 internally. In that case just remove the `static_assert` seeing that OSS doesn't need it (function is never used) and you don't have C++20.
