### ISSUE TITLE
Python release for 5.29.0 has indent problem

### ISSUE THREAD

**Issue by thatch** [protocolbuffers/protobuf#19430]
If you run `python -m compileall` on any of the wheels for the latest release ~40 minutes ago, it will fail with:

```
Compiling 'google/protobuf/service.py'...
*** Sorry: IndentationError: unindent does not match any outer indentation level (service.py, line 78)
```

I can confirm there appears to be a missing space, but I don't see that file (under that name or contents) checked in.

**Comment by piotlinski** [comment]
Confirming that, it seems to be visible on the 29.x branch:
https://github.com/protocolbuffers/protobuf/blob/e0a3978b678be0f3aab8689770b64d1465d2479e/python/google/protobuf/service.py#L78

**Comment by ejona86** [comment]
That file [has been deleted on `main`](https://github.com/protocolbuffers/protobuf/commit/5ba74b11e8d2bd5e9b22e972beb572668bf6191c), but [it is in the 29.x branch](https://github.com/protocolbuffers/protobuf/blob/29.x/python/google/protobuf/service.py).

**Comment by SebKleiner** [comment]
Hi, I still face this issue while installing 5.29.0

**Comment by miguelgfierro** [comment]
Confirming as well, it's breaking all our tests: https://github.com/recommenders-team/recommenders/issues/2191

**Crazy idea: it world be nice to test your library before making a release.**

**Comment by miguelgfierro** [comment]
@anandolee @ejona86 you need to yank 5.29.0 https://pypi.org/project/protobuf/5.29.0/

**Comment by dionhaefner** [comment]
lmao @ the fact that this is still live 5 days later

```bash
$ pip install protobuf
$ python -c "import google.protobuf.service"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dion/.virtualenvs/tempenv-2d0a294330027/lib/python3.10/site-packages/google/protobuf/service.py", line 78
    raise NotImplementedError
                             ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by zhangskz** [comment]
This should be patched in v29.1 ~tomorrow. We are not planning on yanking v29.0 currently, since the issue is isolated to a long-deprecated API slated for removal. For now, we recommend not picking up v29.0 yet if you need `compileall` or if using the `service.py` (or ideally moving off of that since it'll be removed soon in v30.x).

Unfortunately the culprit change also removed the test that also would have caught it, as a side-effect of our removal of this API internally. We will consider adding tests with `compileall` to avoid similar test coverage problems in the future.

**Comment by zhangskz** [comment]
This should only impact users importing the deprecated `service.py` (or using`compileall`) which should be relatively rare. We believe this shouldn't warrant a yank since most users should be able to use v29.0 successfully, where a yank may be disruptive as well.

I see in https://github.com/recommenders-team/recommenders/issues/2191 that your project is indeed importing service.py. Apologies for the breakage, but would it suffice to simply pin to v28.x for now in the interim?

**Comment by nikhil-pandey** [comment]
Saw this issue with couple of projects using azure + mlflow

**Comment by miguelgfierro** [comment]
@zhangskz Recommenders doesn't have a dependency on protobuf, AzureML has. Basically, everybody doing machine learning with Microsoft products will have this error. What is that, 80% of the companies? I'm sure many other libraries will break.

I admire Google and Google engineers, but this is not the right way to operate. If you don't yank the release, you are hiding a major error, and everybody with a dependency in protobuf will get an error. In this end, this hurts your reputation as engineers and the reputation of Google.

Look, I've been coding for 20 years, and all of us have made mistakes. When I make a mistake, I fix it, I own the mistake and move on. I've been in your shoes many times, and I understand it's not nice to yank a release. But doing it fortifies your library. 

I hope you do the right thing.

**Comment by jkoessle** [comment]
> Saw this issue with couple of projects using azure + mlflow

Same for us. Its not possible to use 5.29.0 and mlflow in our ML pipelines.

**Comment by luisangelico** [comment]
Having this issue with Mlflow on Azure

**Comment by googleberg** [comment]
Hello all,

I know that issues like this can be frustrating. No one likes to have their work blocked by a breakage. Sorry about that.

It is also important to recognize that not every user's use case is the same as yours. As @zhangskz points out, while a yank might seem like an obvious solution, there are other users that may have already latched onto other working parts of 29.0 and yanking may break them.

When formulating your replies, keep in mind that protobuf has a [Code of Conduct](https://github.com/protocolbuffers/.github/blob/main/profile/CODE_OF_CONDUCT.md). We do want feedback and suggestions but we also expect civility and mutual respect.

We will be releasing a patch that resolves this issue shortly.
We will be adding additional release testing to ensure that even deprecated functionality like `service.py` is not broken in future releases.

Thank you for you patience.

**Comment by imatiach-msft** [comment]
+1 seeing this as well, this is breaking everything for me - great to see some familiar faces here 👋

**Comment by eltoder** [comment]
@zhangskz running `compileall` is not at all rare. It is a standard step when deploying your code.

**Comment by dionhaefner** [comment]
![image](https://github.com/user-attachments/assets/81f9260d-0fac-4147-9e34-a5af00fcd642)

**Comment by d8ahazard** [comment]
> Hello all,
> 
> I know that issues like this can be frustrating. No one likes to have their work blocked by a breakage. Sorry about that.
> 
> It is also important to recognize that not every user's use case is the same as yours. As @zhangskz points out, while a yank might seem like an obvious solution, there are other users that may have already latched onto other working parts of 29.0 and yanking may break them.
> 
> When formulating your replies, keep in mind that protobuf has a [Code of Conduct](https://github.com/protocolbuffers/.github/blob/main/profile/CODE_OF_CONDUCT.md). We do want feedback and suggestions but we also expect civility and mutual respect.
> 
> We will be releasing a patch that resolves this issue shortly. We will be adding additional release testing to ensure that even deprecated functionality like `service.py` is not broken in future releases.
> 
> Thank you for your patience.

Respectfully, you guys need to move NOW. 

Why is the broken package still published, and why have you not release a fix? 

Considering how many other packages use protobuf, this should have been addressed last week when it was reported...not "maybe some time today.".

**Comment by pberenyi** [comment]
Maybe you want to add something like `python -m compileall -q .` into your release verification process?

**Comment by karpikpl** [comment]
Looks like `5.29.1` was released

**Comment by jorenham** [comment]
> Looks like `5.29.1` was released

It's not yet on PyPI:
https://pypi.org/project/protobuf/

**Comment by jorenham** [comment]
I would suggest yanking the 5.29.0 PyPI release.

**Comment by jorenham** [comment]
> Respectfully, you guys need to move NOW.

I strongly agree. This causes major disruptions in a many CI/CD pipelines. 
Do not underestimate the damage you are causing by ignoring this.

**Comment by ericsalo** [comment]
We are not ignoring it. We are proceeding to release 29.1 as quickly as we
can, and once that is done we will yank 29.0.

**Comment by jorenham** [comment]
Protobuf 5.29.1 is on PyPI now:
https://pypi.org/project/protobuf/

**Comment by jorenham** [comment]
And Protobbuf 5.29.0 has indeed been yanked:
https://pypi.org/project/protobuf/5.29.0/

Thanks @ericsalo

**Comment by miguelgfierro** [comment]
Thanks for yanking @ericsalo @zhangskz @googleberg 
Respect 👏👏👏

**Comment by thatch** [comment]
Closing as fixed version is out.  Thanks for addressing, protobuf team.

**Comment by abusarimhindi** [comment]
The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 5.29.0 at https://files.pythonhosted.org/packages/ee/2e/cc46181ddce0940647d21a8341bf2eddad247a5d030e8c30c7a342793978/protobuf-5.29.0-cp38-abi3-manylinux2014_x86_64.whl (from https://pypi.org/simple/protobuf/) (requires-python:>=3.8))
