### ISSUE TITLE
Ruby fails some of the proto3 oneof conformance tests (JSON)

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#1946]
https://github.com/google/protobuf/blob/master/conformance/failure_list_ruby.txt#L106-L113

JsonInput.OneofZeroDouble.JsonOutput
JsonInput.OneofZeroDouble.ProtobufOutput
JsonInput.OneofZeroFloat.JsonOutput
JsonInput.OneofZeroFloat.ProtobufOutput
JsonInput.OneofZeroUint32.JsonOutput
JsonInput.OneofZeroUint32.ProtobufOutput
JsonInput.OneofZeroUint64.JsonOutput
JsonInput.OneofZeroUint64.ProtobufOutput

**Comment by haberman** [comment]
All of these conformance failures are fixed as of https://github.com/protocolbuffers/protobuf/pull/8184
