### ISSUE TITLE
`makeExtensionsImmutable()` disappeared in 4.26.0 from the supposedly backwards-compatible GeneratedMessageV3

### ISSUE THREAD

**Issue by FyiurAmron** [protocolbuffers/protobuf#19540]
**What version of protobuf and what language are you using?**
Version: v4.26.0+
Language: Java (probably all though)

**What operating system (Linux, Windows, ...) and version?**
N/A

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
1. Include a compiled proto file from pre-4
2. Try to integrate with 4+ with the aim of gradual transition still being able to use some of the deprecated methods/classes in the meantime and to handle pre-4 compiled protos
Example way to showcase/trigger the integration problem (assume `Query` was compiled with 3.x and integrated into project with 4.x):
`Query.QueryResponse.parseFrom(new byte[]{});`

**What did you expect to see**
Code using deprecated methods/classes should not break _yet_, just warn about them.

**What did you see instead?**
exception of the like is thrown:
```
java.lang.NoSuchMethodError: 'void Query$QueryResponse.makeExtensionsImmutable()'
```
due to the complete lack of the aforementioned in 4.x `GeneratedMessageV3` code.

Note 1: It was removed as well from the forward-compatible GeneratedMessage ; this is to be completely excepted here I guess.

Note 2: I am aware that 5 will probably remove GeneratedMessageV3 completely, and that it would be semantically valid for 4 to partially break compatibility here. However, both the deprecation messages and my intuition hint that in this case the backwards-compatible class should be retained as such - i.e. compatible with old code - if it's reasonably possible.

**Comment by zhangskz** [comment]
What version of 3.x.x gencode are you using? `makeExtensionsImmutable()` should have been removed during a refactor of the protobuf gencode in [~3.22.x](https://github.com/protocolbuffers/protobuf/commit/3b5301c114121d036efe77e2816c44876c258c89) as part of a [Java security patch](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2).

Our restoration of backwards-compatibility to GeneratedMessageV3 does not target the *full* 3.x.x major version, which contains vuln. fixes and predates our breaking changes policies (3.x.x has been around for a *long* time, and unfortunately likely contains several breaking changes throughout the years).

You may need to first update your 3.x.x gencode to a later version (ideally 3.25.x, though we expect compatibility with 3.22.x gencode as well) before receiving compatibility guarantees with the 4.x.x runtime.

**Comment by FyiurAmron** [comment]
@zhangskz you're completely right, the code in question is indeed using an ancient 3.x version (can't check it 100% tomorrow, but AFAIR it was 3.8.0), I couldn't make this happen for any of the more recent versions - latest 3.xes are definitely compatible as far as our usage goes, including things built with at least 3.23, which would completely confirm what you're saying, I'll pass on the info that it's ~3.22.x (with 21.7 etc.) that needs to be targeted first as a steping stone during the migrations.

I'm closing this since the info you provided should be enough for us to handle the case one way or another. Many thanks for the quick response BTW!

**Comment by yschimke** [comment]
Also seeing this on a release build when updating com.google.cloud libraries.  I'll report there.
