### ISSUE TITLE
macOS/iOS error: call to undeclared function 'utf8_range_IsValid'

### ISSUE THREAD

**Issue by JonasVautherin** [protocolbuffers/protobuf#19565]
[This](https://github.com/protocolbuffers/protobuf/blob/main/upb/wire/internal/decoder.h#L63) code in decoder.h results in an error when building both for macOS and iOS.

The code is:

```c++
bool _upb_Decoder_VerifyUtf8Inline(const char* ptr, int len) {
  return utf8_range_IsValid(ptr, len);
}
```

The compiler error is:

```
upb/wire/internal/decoder.h:62:10: error: call to undeclared function 'utf8_range_IsValid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
[  3%] Building CXX object CMakeFiles/grpc_plugin_support.dir/src/compiler/csharp_generator.cc.o
  return utf8_range_IsValid(ptr, len);
         ^
1 error generated.
```

It builds fine for many other platforms (including Android, Windows, Linux), so it feels like it is not a setup issue on my end. Could it be a problem in upb?

**Comment by shaod2** [comment]
Can you provide more details about the version of protoc and libprotobuf, and how to reproduce the error?

**Comment by JonasVautherin** [comment]
Actually updating protobuf to the latest release helped. It seems like it's conflicting with gRPC, but I can disable the build of upb in protobuf and then it works 🤷.

I haven't found a way to build upb separately and have both protobuf and grpc use it, though 😕. But I guess I'm not meant to build protobuf as a static library separately from grpc, so it will have to do with disabling upb in protobuf.
