### ISSUE TITLE
Can't find wire_format_verify.h

### ISSUE THREAD

**Issue by teub** [protocolbuffers/protobuf#19671]
**What version of protobuf and what language are you using?**
Version: main/v3.29.1
Language: C++

**What did you do?**
1. Open lazy_repeated_field.h
2. Notice there is an include #include "google/protobuf/wire_format_verify.h"
3. Search the repository for a file named wire_format_verify.h
4. Notice there is no file named wire_format_verify.h

**What did you expect to see**

I expected to find a file named wire_format_verify.h

**What did you see instead?**

I did not see a file named wire_format_verify.h

**Comment by zhangskz** [comment]
Thanks for the report! Looks like `lazy_repeated_field.h` was branched from an existing file that is internal only, and was included as part of a [change](https://github.com/protocolbuffers/protobuf/commit/4b230be0d004cb4b6c69bcc8ff994cbe949b1475) that was not meant to be open sourced.
