### ISSUE TITLE
'absl/log/absl_check.h' file not found when building protobuf as an external dependency using Bazel

### ISSUE THREAD

**Issue by davidzchen** [protocolbuffers/protobuf#19791]
**What version of protobuf and what language are you using?**
Version: 29.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS Sequoia 15.1.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

```
$ clang --version
Homebrew clang version 19.1.1
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/19.1.1/bin
```

**What did you do?**

```
git clone https://github.com/davidzchen/abxl
cd abxl
bazel build //abxl/file
```

**What did you expect to see**
Build succeeds

**What did you see instead?**

```
INFO: Analyzed target //abxl/file:file (98 packages loaded, 1125 targets configured).
ERROR: /Users/dzc/Projects/davidzchen/abxl/abxl/file/BUILD:25:11: Compiling abxl/file/file.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //abxl/file:file) external/rules_cc++cc_configure_extension+local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-
protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from abxl/file/file.cc:14:
In file included from ./abxl/file/file.h:25:
bazel-out/darwin_arm64-fastbuild/bin/external/protobuf+/src/google/protobuf/_virtual_includes/protobuf_headers/google/protobuf/message.h:100:10: fatal error: 'absl/log/absl_check.h' file not found
  100 | #include "absl/log/absl_check.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //abxl/file:file failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.519s, Critical Path: 1.15s
INFO: 149 processes: 170 action cache hit, 34 internal, 115 darwin-sandbox.
ERROR: Build did NOT complete successfully
```

**Anything else we should know about your project / environment**

None

**Comment by davidzchen** [comment]
Interesting. Changing the `dep` from `@protobuf//:protobuf_headers` to just `@protobuf` fixed the issue. Not sure why. I would expect depending on `@protobuf//:protobuf_headers` to not fail with this error either.

**Comment by zhangskz** [comment]
I think this is WAI per https://github.com/protocolbuffers/protobuf/blob/214a81465a1bbded383826f7a8d7d9fea1cf2dd4/src/google/protobuf/BUILD.bazel#L745-L748 which indicates this target *only* provides header files and notably doesn't include a dep on `"@com_google_absl//absl/log:absl_check"` like `@protobuf/:protobuf` does in https://github.com/protocolbuffers/protobuf/blob/214a81465a1bbded383826f7a8d7d9fea1cf2dd4/src/google/protobuf/BUILD.bazel#L677

**Comment by davidzchen** [comment]
Thanks for explaining.
