### ISSUE TITLE
[C#] Allow reuse of CodedInputStream and CodedOutputStream

### ISSUE THREAD

**Issue by yufeih** [protocolbuffers/protobuf#1988]
`CodedOutputStream` can take use flat array as the output. This is a great to just convert between object and bytes. Problem is an instance of `CodedOutputStream` can only be used once. 

Adding a Reset method allows you to reuse the same `CodedOutputStream` to serialize different objects.

Same is true for `CodedInputStream`.

See https://github.com/yufeih/protobuf/commit/d6ffc2f37cad8e85cbd71b1d144093250894aeb8

**Comment by prodigga** [comment]
Any reason why this was closed? We use protobuf for serialisation in our game's networking and CodedOutputStreams are generating a lot of garbage. It would be great if it could be reused.

**Comment by isbdnt** [comment]
You can use MemoryStream as the parameter in CodedOutputStream for this purpose.

**Comment by aamirmahmood28** [comment]
Any plan to implement it?
This issue is open for more than 7 years.

I also see a huge garbage collector pressure because CodedInputStream and CodedOutputStream are not reusable.  I have managed to reuse everything else that comes in the way.
