### ISSUE TITLE
3.0.0: FTBFS: "testMergeFrom" failure (unreliable test?)

### ISSUE THREAD

**Issue by onlyjob** [protocolbuffers/protobuf#1995]
Sometimes `testMergeFrom` spontaneously fails on x86_64:

```
====================================================================== 
FAIL: testMergeFrom (google.protobuf.internal.message_test.Proto3Test) 
---------------------------------------------------------------------- 
Traceback (most recent call last): 
  File "/build/protobuf-3.0.0/python/google/protobuf/internal/message_test.py", line 1450, in testMergeFrom 
    self.assertEqual(15, old_map_value.c) 
AssertionError: 15 != 10 
```

**Comment by CDLuminate** [comment]
I encountered definitely the same failure with Debian's protobuf_3.0.0-7 source package. Python3 is used for that test.

**Comment by CDLuminate** [comment]
I recompiled and this issue disappeared. It seems to happen randomly.

**Comment by onlyjob** [comment]
If problem happens randomly it means non-deterministic, unreliable test.
Why is this issue closed without comment?
@acozzette, are you sure this problem has been fixed?

**Comment by acozzette** [comment]
@onlyjob I assumed it has probably been fixed since there haven't been any further complaints about it for a couple years now. Do you think the test is still unreliable even with the current code on master?

**Comment by onlyjob** [comment]
I have seen no evidence for this problem to be fixed. Usually we have that kind of tests disabled downstream (in Debian) until the problem is resolved upstream... Usually it is not helpful to nag bug reports with reminders that the problem is still a problem...
I do not know if recent release has addressed the problem...

**Comment by acozzette** [comment]
OK, I see. Still, given that it's been two years and I can't reproduce the problem locally, I strongly suspect it has been fixed. Let me leave this issue closed but we can investigate further if there are any more reports of the problem on more recent versions.
