### ISSUE TITLE
tests fail for 3.1.0 with --cpp_implementation on Python 3.5 / Ubuntu 16.04

### ISSUE THREAD

**Issue by victor-shepardson** [protocolbuffers/protobuf#2183]
Using the Python release of 3.1.0 [here](https://github.com/google/protobuf/releases/tag/v3.1.0) I was able to build the C++ without errors as described [here](https://github.com/google/protobuf/blob/v3.1.0/src/README.md#c-installation---unix). I opted to install in the default location and add `/usr/local/lib/` to `LD_LIBRARY_PATH`. No complaints from `make check`.

`python3 steup.py build --cpp-implementation` ran without errors, but `python3 setup.py test --cpp_implementation` fails 36/38 tests with an error importing `_message`: https://gist.github.com/victor-shepardson/e5d012075be5afb29378d2d29d0c36ae

Everything works fine in python if I build without the `--cpp_implementation` flag.

For context, I'm trying to use the C++ implementation with tensorflow. The wheel provided by the tensorflow folks [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues) doesn't work on my system in the fashion described [here](http://stackoverflow.com/questions/39181861/tensorflow-using-a-c-protobuf-package-for-python-3-5). Before beginning the build process for protobuf 3.1.0 I did a `pip3 uninstall protobuf`.

**Comment by victor-shepardson** [comment]
It seems that python3.5m is being included when gcc is called even though python3 links to python3.5 on my system, e.g.
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g 
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time 
-D_FORTIFY_SOURCE=2 -fPIC -I. -I../src -I/usr/include/python3.5m 
-c google/protobuf/pyext/extension_dict.cc -o
```
But I don't understand whether that should be a problem or where the behavior comes from, yet.

**Comment by Michel2904** [comment]
I'm running into the same issue....was this ever resolved?

**Comment by anandolee** [comment]
Close it as we may not have time for 3.1.0 at this time.
