### ISSUE TITLE
Ruby protoc does not generate :packed => true

### ISSUE THREAD

**Issue by JelleHoffman** [protocolbuffers/protobuf#2294]
I'm working on a ruby application using google protocol buffers. When I try to generate my ruby files using a proto file with a repeated int32 array that has the packet = true option, it doesn't generate the ruby code `:packed => true` behind the specified array. For more info: http://stackoverflow.com/questions/40261773/packed-true-does-not-generate-packed-true-ruby-google-protocol-buffers

**Comment by xfxyjwf** [comment]
@haberman do you know if ruby supports packed fields?

**Comment by Peddz24** [comment]
@haberman Yes it supports packed fields. I manually add it to the generated ruby file and this does make the correct encoded messages where arrays are packed. Sorry for this late reply

**Comment by jtattermusch** [comment]
@haberman  can this be closes?

**Comment by haberman** [comment]
This is still a bug. It should be a trivial fix. Let me take a look at it.

**Comment by haberman** [comment]
This is still a bug, and is responsible for nearly all of the remaining conformance failures in Ruby.

We can parse packed and unpacked fields successfully. But we should be using `packed=true` to decide how to encode repeated fields, and currently we do not.

**Comment by fowles** [comment]
Is this still a bug?  If so, perhaps a good one for salo?

**Comment by haberman** [comment]
This was fixed in https://github.com/protocolbuffers/protobuf/pull/12319
