### ISSUE TITLE
BUILD file is missing -DHAVE_ZLIB

### ISSUE THREAD

**Issue by yasushi-saito** [protocolbuffers/protobuf#2365]
.. so it doesn't build GzipOutputStream and GzipInputStream. Is this omission intentional?

 COPTS = [
     "-DHAVE_PTHREAD",
+    "-DHAVE_ZLIB",
     "-Wall",
     "-Wwrite-strings",
     "-Woverloaded-virtual",
     "-Wno-sign-compare",

**Comment by xfxyjwf** [comment]
I think it's not omitted intentionally, though I guess there needs some work to add the zlib dependency after adding -DHAVE_ZLIB.

**Comment by yasushi-saito** [comment]
Yeah, we need to add -lz to LINK_OPTS. But I'm not sure about android and ios.. Can someone fix this? I don't have an environment to test, other than linux.

**Comment by xfxyjwf** [comment]
@pherl

**Comment by pherl** [comment]
Can you please file a PR for this? We don't use bazel for android build.

**Comment by alex-petrenko** [comment]
Are there any updates on this? What is the standard way to build protobuf with GZipOutputStream? Is it possible to do without modifying the BUILD file?

**Comment by pherl** [comment]
Are you using bazel? I think there's some command line flag to bazel that allows you to set the compile and link flags. I would add the -lz to LINK_OPS and -DHAVE_ZLIB locally if that works.

**Comment by alex-petrenko** [comment]
@pherl Sure, this actually makes sense. I am building protobuf as a part of tensorflow, with Bazel. I think if I add -lz and -DHAVE_ZLIB to "top leve" command line, it should propagate down to dependencies as well. I shall try that.

**Comment by creachadair** [comment]
Is there any sensible workaround for this? Kythe is trying to migrate away from a custom-hacked copy of protobuf to using an external repository, and this is blocking us as we need gzip I/O streams to work.

**Comment by alex-petrenko** [comment]
I think I ended up modifying one of the BUILD files in Tensorflow to force protobuf compilation with zlib. Something along the lines of adding a HAVE_ZLIB definition for the compiler.

**Comment by creachadair** [comment]
> I think I ended up modifying one of the BUILD files in Tensorflow to force protobuf compilation with zlib. 

Well, I can of course do that, but the point of this exercise was to _not_ have a custom build for protobuf. Or am I misunderstanding what you meant? 

I confirmed that adding these options in the external repo's BUILD file satisfies the compiler (COPTS) and linker (LINK_OPTS), but I haven't found a good way to wrapper the dependency to add those without pushing the change into the external repo directly.

**Comment by alex-petrenko** [comment]
Are you using git submodule to handle dependencies? If so, I don't know a good way to do this either.
CMake external project feature has the automatic patch applying feature, as well as Bazel (I think), maybe you can look at those.

**Comment by creachadair** [comment]
> Are you using git submodule to handle dependencies? If so, I don't know a good way to do this either.

We are not—except where not possible (notably LLVM), we have all our deps managed by Bazel as external repositories. However, I think I have a workaround for now: I have cloned the BUILD file from the protobuf repo, edited it, and replaced our `http_archive` workspace rule with a `new_http_archive` rule that points to our edited copy of the BUILD file.

This is likely to be brittle, but I'm hopeful that upstream changes will be relatively infrequent.

**Comment by creachadair** [comment]
Unfortunately, the modifications I made weren't quite sufficient: Including `-DHAVE_ZLIB` in copts and `-lz` in linkopts allowed it to build locally, but only because I happened to have an ambient `zlib.h` installed on my machine. We use Bazel to build our zlib, and I haven't yet worked out a good way to get protobuf to use it. Binding it under `//external` isn't quite sufficient—Bazel seems to bind `deps` paths via `-iquote` rather than `-I`, so `#include <zlib.h>` doesn't use them. I'm still puzzling at a workaround. 

It would be quite helpful if the protobuf build configuration had more explicit support for zlib, as it already does for (e.g.) guava and gson.

**Comment by rnburn** [comment]
Any updates on this? Is there any reason why zlib can't be added into WORKSPACE as an explicit dependency?

**Comment by creachadair** [comment]
zlib is indeed in the WORKSPACE, cf.

```
http_archive(
    name = "net_zlib",
    build_file = "@//third_party:zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = [
        "https://zlib.net/zlib-1.2.11.tar.gz",
    ],
)
```

I believe that was only changed within the past month or so, so you may need to pull again if you have not done so recently.

**Comment by rnburn** [comment]
@creachadair - I don't see that in master. Is it in a different branch?

**Comment by creachadair** [comment]
> I don't see that in master. Is it in a different branch?

Sorry, I was unclear. I meant that we have successfully added zlib to our WORKSPACE in Kythe, but I realize in retrospect you were addressing not my previous comments but the original thread. Apologies.

**Comment by haon4** [comment]
It seems like this is obsolete (https://github.com/protocolbuffers/protobuf/blob/master/BUILD#L51). Please reopen if that is not the case.
