### ISSUE TITLE
Make Linux downloads of protoc available as tarballs

### ISSUE THREAD

**Issue by lorenz** [protocolbuffers/protobuf#2397]
Currently the Linux downloads for protoc are only avaliable as zip files, which means that to use them in a container it is necessary to install unzip and download the file in the container itself instead of an add instruction which automatically decompresses the downloaded file.
Could you make the Linux releases available as tarballs too?

**Comment by taylorjacklespriggs** [comment]
It is also necessary to apply the required permissions to the files extracted from the zip (`chmod -R a+rx`) so that they can be used by other users and groups. A tarball with correct file permissions would be way easier to use.

**Comment by deannagarcia** [comment]
This was added, but is being removed for 22.x as documented [here](https://developers.google.com/protocol-buffers/docs/news/2022-08-03).
