### ISSUE TITLE
Enable support for java.util.Optional<T> in Java codegen

### ISSUE THREAD

**Issue by Joe-C-London** [protocolbuffers/protobuf#2553]
When specifying a field as `optional` in protobuf, the code generator for java should be able to generate an accessor method that returns a `java.util.Optional` of the specified type.

For example, given the following definition:
```
message Person {
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;
}
```
The interface generated should include:
```
// required string name = 1;
public boolean hasName();
public String getName();

// required int32 id = 2;
public boolean hasId();
public int getId();

// optional string email = 3;
public boolean hasEmail();
public String getEmail();
public java.util.Optional<String> getEmailOpt();
```

And the corresponding builder:
```
// required string name = 1;
public boolean hasName();
public java.lang.String getName();
public Builder setName(String value);
public Builder clearName();

// required int32 id = 2;
public boolean hasId();
public int getId();
public Builder setId(int value);
public Builder clearId();

// optional string email = 3;
public boolean hasEmail();
public String getEmail();
public java.util.Optional<String> getEmailOpt();
public Builder setEmail(String value);
public Builder clearEmail();
public Builder setEmail(java.util.Optional<String> optionalValue);
```

This would enable developers to easily perform operations such as:

`System.out.println(person.getEmailOpt().orElse("Not specified"));`

**Comment by xfxyjwf** [comment]
Since java.util.Optional is a Java 8 feature, we won't be able to support it until we can require all protobuf users to have Java 8+. That might take quite a while.

Also note this is proto2 specific as in proto3 field presence is not supported any more (i.e., no way to distinguish a field having the default value vs. a field not present). We might not want to extend a feature that we have knowingly dropped in proto3.

**Comment by mvh77** [comment]
This is a feature I've been missing too, and it has nothing to do with wire format. All non primitive fields should return Optional<T>. This is also how the Scala protobuf compiler works, and it generates getter methods that take a default value that's returned if the field is not present.

**Comment by lvitaly** [comment]
https://github.com/scalapb/ScalaPB has way better support for optional fields with scala's Option than the current Java implementation with has() method. And for setting an optional field, you should always use boilerplate util functions like this one
```
  static void setInt32Value(Consumer<Int32Value> setter, Integer value) {
    Optional.ofNullable(value).map(Int32Value::of).ifPresent(setter);
  }
```

**Comment by be-hase** [comment]
> Since java.util.Optional is a Java 8 feature, we won't be able to support it until we can require all protobuf users to have Java 8+. That might take quite a while.

Hi.
I don't think there will be any more non-java8+ users in 2023, but you don't want to deal with it?
The optional is now available in protobuf3, but unfortunately it is very difficult to use.

**Comment by donce** [comment]
It's 2025, AI is close to conquering the world, but protobuf-java still don't have `Optional<T>` to return optional values, which is idiomatic Java since Java 8, 2014? 🤔
