### ISSUE TITLE
Feature request: support field masks in the JsonFormat util

### ISSUE THREAD

**Issue by dminkovsky** [protocolbuffers/protobuf#2558]
Use case:

I am using the `JsonFormat.Printer` to print messages destined for a JSON database (Elasticsearch). The database supports [partial document updates](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_updates_with_a_partial_document). It would be nice to take advantage of this and send only fields that need to be updated.

However, with proto3 and optional fields all fields have default values. So when serializing a message to JSON, there's no way to specify whether a string has been set to empty or has not been set on the message at all. For example, suppose I have:

```
message Post {
  string title
  string body
}
```

Then the user updates the body and sets it to empty. I would like to send a partial update of the message to the database with `body` set to `""`:

```
{
  "body": ""
}
```

Using the current version of `JsonFormat.Printer`, there's no way to print a `Post` message and get this result. With `includingDefaultValueFields` enabled, you get:

```
{
  "title": ""
  "body": ""
}
```

Sending this to the database would result in emptying the `title` field too. And without `includingDefaultValueFields` you get:

```
{}
```

which leads to a no-op update. 

My solution right now is just to send full document updates. Which is fine, but obviously not optimal. So, **it would be great if one could specify `FieldMask`s when configuring the `JsonFormat.Printer`**. I am envisioning the a registry of `FieldMask`s like the `TypeRegistry`. As a message is printed, the field mask registry is consulted. If a field mask exists for the current type, it is used to determine which fields are printed. Otherwise, all fields are printed. I don't think this functionality is needed for the parser—just the printer.

**Comment by xfxyjwf** [comment]
It might be easier if you use the wrapper types defined in:
https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto

For example, you can define the Post message as:
```proto
message Post {
  google.protobuf.StringValue title = 1;
  google.protobuf.StringValue body = 2;
}
```
Then you will be able distinguish between an unset field and a field set to "".

**Comment by dminkovsky** [comment]
Ah, that's interesting @xfxyjwf. Thank you for the suggestion! Yes, that would work with `JsonFormat.Printer` because then `Message#hasField()` will distinguish set vs unset fields. 

However, doesn't it seem strange to deviate from the core protobuf paradigm just to accommodate the JSON printer? At this point, I think I would rather keep my messages the way they are and just send full updates, at least until I see a performance-based reason to change.

**Comment by dminkovsky** [comment]
>  at least until I see a performance-based reason to change.

at which point I will would PR this utility. Would this be a feature you're okay with?

**Comment by xfxyjwf** [comment]
@dminkovsky This new API will need to go through an API review process which is unfortunately Google internal only at the moment. I can help make a proposal for it to the review committee but I cannot accept your PR until the proposal is approved.

**Comment by dminkovsky** [comment]
Makes sense. And otherwise, I am guessing this will not be implemented internally? If not, what is needed for the proposal? A patch and tests?

**Comment by haon4** [comment]
It looks like what you want can now be achieved with https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L221
