### ISSUE TITLE
sudo: ldconfig: command not found for C++ installation on Mac OS X

### ISSUE THREAD

**Issue by tianqig** [protocolbuffers/protobuf#2570]
Hi,
I used the  following commands to install protobuf on my **MacBook Pro of Mac OS X, Sierra**
$ ./configure
$ make
$ make check
$ sudo make install
$ sudo ldconfig 
the first 4 commands were successful, but the last command got error message:
 **sudo: ldconfig: command not found**

Thanks

David

**Comment by xfxyjwf** [comment]
"sudo ldconfig" is used on Linux to update shared library cache so the newly installed protobuf library can be correctly found. Mac OS X doesn't seem to have this shared library cache problem and you can safely ignore it (protobuf is ready to use after "sudo make install").

**Comment by sebma** [comment]
@tianqig On Macos, try this instead of `sudo ldconfig` : 
`$ sudo update_dyld_shared_cache`

**Comment by elharo** [comment]
docs need to be updated to reflect this

**Comment by cyanxena** [comment]
> sudo update_dyld_shared_cache

Update on this solution: Currently says the tool is deprecated

**Comment by ankitsablok89** [comment]
Apple M1 MAC's also say that the tool is deprecated

**Comment by devjgm** [comment]
I believe this was fixed by #7392, where we no longer recommend `ldconfig`. If this was closed incorrectly, please feel free to reopen and explain why so we can try again.

**Comment by sebma** [comment]
Hi everyone, what is the replacement/equivalent of `update_dyld_shared_cache` on MacOS now ?

**Comment by devjgm** [comment]
I'm not sure if anything replaced `update_dyld_shared_cache`. It's been deprecated since Big Sur, I believe. Is there an issue about this that's related to protobuf that we should look into?
