### ISSUE TITLE
MessageLiteToString.toString() omits map<,> fields

### ISSUE THREAD

**Issue by mdusina** [protocolbuffers/protobuf#2641]
When calling .toString() on a generated lite class, map fields and everything within them are completely omitted.  This makes debugging issues harder than it should be.

I think [this TODO](https://github.com/google/protobuf/blob/39f9b43219bc5718b659ed72a2130a7b2ce66108/java/core/src/main/java/com/google/protobuf/MessageLiteToString.java#L44) is referring to this problem.

**Comment by elharo** [comment]
seems to have been fixed in cl/183286010 several years ago
