### ISSUE TITLE
Feature Request: option to ignore invalid values

### ISSUE THREAD

**Issue by the1plummie** [protocolbuffers/protobuf#2650]
When converting json to proto object,
`JsonFormat.parser().merge(json_string, builder);`

When a value is invalid (say proto is boolean, but json value is a string), is there a way to configure the parser to ignore that field or set that field to null, instead of throwing `com.google.protobuf.InvalidProtocolBufferException`?

**Comment by elharo** [comment]
No, there is no way to do that.
