### ISSUE TITLE
Installation instructions lacking key point

### ISSUE THREAD

**Issue by natefinch** [protocolbuffers/protobuf#2698]
I just spent 3 hours debugging my protobuf installation only to realize that the instructions in the readme are incomplete.  They say:

`To install, simply place this binary somewhere in your PATH.`

So, I did that.  Here's what I did:  

unzip the zip file to a random directory.
sudo mv protoc /usr/local/bin/

However, when I ran protoc I would get weird errors like this:

```
google/protobuf/timestamp.proto: File not found.
event.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.
```

This might be obvious to people who have used protobuffers a lot, but to a newbie, that is a mysterious error. My colleagues could run this line just fine, why couldn't I?

The readme needs to also say that you need to put the include directory near protoc.  I don't actually know the heuristics, but extracting to a directory and then symlinking from /usr/local/bin to that directory/bin/protoc seems to work.

But that's incredibly non-obvious.  Generally, binaries don't care where they are located.

Also, it would be nice if protoc had better error handling, so that it could tell that it doesn't have the include directory next to it, and could make complain that you've probably installed incorrectly.

**Comment by xfxyjwf** [comment]
Thanks for the report. Do you mind creating a pull request to help improve the documentation?
https://github.com/google/protobuf/blob/master/protoc-artifacts/build-zip.sh#L74

**Comment by corylanou** [comment]
To add to my comment, this is the slide that I use when installing for windows bases for go developers.

![screenshot 2018-04-19 10 29 03](https://user-images.githubusercontent.com/585100/39001727-8d63ec6a-43bc-11e8-9e93-87bd95ebb38f.png)

This seems to have worked so far, but if there is a better way please let me know.
