### ISSUE TITLE
java: generated code does not compile if top-level package is named `key`

### ISSUE THREAD

**Issue by thesamet** [protocolbuffers/protobuf#2738]
If a schema contains a map with an enum value type, where the enum resides in a top-level package named `key`, the generated code does not compile:

```
key/foo/bar/Foo.java:879: error: int cannot be dereferenced
        if (key.foo.bar.Foo.MyEnum.forNumber(value) == null) {
```

Source proto:
```
syntax = "proto3";

package key.foo.bar;

enum MyEnum {
  aaa = 0;
  bbb = 1;
}

message Msg {
  map<int32, MyEnum> bb = 1;
}
```

Tested with protoc 3.1.0 and 3.2.0

NOTE: Discovered this problem through trying to compile a randomly generated proto schema (there is no actual business use case).

**Comment by elharo** [comment]
not sure what's happening here, but it seems to be fixed now. Please comment if  you still observe this.
