### ISSUE TITLE
Unhelpful error message - PHP

### ISSUE THREAD

**Issue by tbillington** [protocolbuffers/protobuf#2742]
When giving a value of the wrong type to a protobuf message php gives the following error

```
PHP Fatal error:  Expect repeated field. in /Users/trent/src/github.com/myproject/phptest/vendor/google/protobuf/php/src/Google/Protobuf/Internal/GPBUtil.php on line 137
```

This doesn't give me any information about where the error occurred in my code.

**Comment by TeBoring** [comment]
Isn't there a stack trace?

**Comment by tbillington** [comment]
Nope, that's part of the issue. I make an exception at the error site in `Google\Protobuf\Internal\GPBUtil` and print the trace so I can debug the issue, but I don't get any more info by default other than what I posted initially.

Maybe for this issue it could print something like `expected array of type X, got element of type Y` ?

**Comment by TeBoring** [comment]
Will add more info in future release.

**Comment by lord2800** [comment]
Any update on this? It's still frustrating.

**Comment by deannagarcia** [comment]
I'm going to close this bug since it's so old. If you are still having this issue with new versions of protobuf, please reopen with reproduction instructions.
