### ISSUE TITLE
The installation guide make us confused

### ISSUE THREAD

**Issue by quantwizard** [protocolbuffers/protobuf#2749]
Hi googlers,
Your installation guide makes us feel confused.
For instance, I'm a python programmer, in fact, I only need to use 'pip install protobuf', but I can't find such thing in your guide. and also when I install protobuf compiler, I only need to use apt-get install.
So your guide seems outdated.

BR,
Eric

**Comment by xfxyjwf** [comment]
The guide in the README.md file is talking about how to install from source. I guess we should have a separate installation guide to cover installing distributed binary packages.

**Comment by mohawkTrail** [comment]
I second this bug report
