### ISSUE TITLE
Replace field-number int constants with enum, in generated java source.

### ISSUE THREAD

**Issue by joneepenk** [protocolbuffers/protobuf#2973]
## Benefits:
- Field variable can be restricted to specified message.
- Get field name conveniently.
- Iterate fields conveniently 

### Protobuf Message
```
message ExampleMessage {
  required string name     = 1;
  required string email     = 4;
  optional string address = 5;
}
```
### Generated Source
```
public static final class ExampleMessage extends GeneratedMessage
     implements ExampleMessage.ExampleMessageOrBuilder {
  public enum FieldEnum implements FieldEnumInterface<ExampleMessage> {
    NAME(1), EMAIL(4), ADDRESS(5)
  }
.....
}
```

**Comment by BSBandme** [comment]
Is there any special requirement for this? 
I think most of the use case can be replaced by using [FieldDescriptor](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/Descriptors.java#L949).

**Comment by haon4** [comment]
+1 to using [FieldDescriptor](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/Descriptors.java#L949).
