### ISSUE TITLE
RepeatedScalarFieldContainer cannot be cleared

### ISSUE THREAD

**Issue by vmax** [protocolbuffers/protobuf#2977]
Defined `repeated` field turns into a `list`-like object in Python. However, we cannot `.clear()` it other way than `.pop` until there are no more elements (=`len` returns 0).

Is it a design decision or it has been missed out by accident?

**Comment by BSBandme** [comment]
Can you describe a little more on this issue? Which language are you using?
I think for Java and C++ we has the way to clear all the the elements

**Comment by vmax** [comment]
@BSBandme I'm talking about Python

**Comment by moonlight16** [comment]
Any updates about this feature?  This would be really useful, especially if you have very large containers.
