### ISSUE TITLE
JsonFormat.Parser throws InvalidProtocolBufferException when parsing unknown enum constants

### ISSUE THREAD

**Issue by veerenmandalia** [protocolbuffers/protobuf#3012]
I am using [JsonFormat.Parser](https://developers.google.com/protocol-buffers/docs/reference/java/) to convert JSON to Java protobuf models.

When it encounters an enum constant it doesn't recognize, the parser throws an InvalidProtocolBufferException. I would expect it to serialize the `UNRECOGNIZED` enum constant defined by protobuf. This is seen in the [JsonFormat source](https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1670)

Example:

**Generated Java model**
```
public enum Vehicle implements com.google.protobuf.ProtocolMessageEnum {
  BICYCLE(0),
  CAR(1),
  UNRECOGNIZED(-1);
}
```

If server then sends the JSON `{ vehicle = "TRUCK" }` an exception is thrown rather than deserializing it as UNRECOGNIZED:
```
com.google.protobuf.InvalidProtocolBufferException: Invalid enum value: TRUCK for enum type: messages.company.Vehicle
```

**JSON parser configuration**
```
try {
    JsonFormat.parser()
        .ignoringUnknownFields()
        .merge(json, builder);
} catch (InvalidProtocolBufferException e) {
    throw new IOException(e);
}
```

**Comment by BSBandme** [comment]
Any updates on this? Will your PR be merged?

**Comment by veerenmandalia** [comment]
Thanks @vijay-bhatt for completing this in https://github.com/protocolbuffers/protobuf/pull/4825

The change did not make 3.6.1. This can be closed either now or once the change is released (not sure the process).

**Comment by BSBandme** [comment]
Closed as the change should have been released.
