### ISSUE TITLE
Ruby decode_json not handling timestamps and int64 per JSON Mapping spec

### ISSUE THREAD

**Issue by ryanbrainard** [protocolbuffers/protobuf#3013]
The Ruby `decode_json` method is not handling the `timestamp` and `int64` types per the [JSON Mapping spec](https://developers.google.com/protocol-buffers/docs/proto3#json). The spec says:

> Timestamp	string	`"1972-01-01T10:00:20.021Z"`	Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits.

and 

> int64, fixed64, uint64	string	`"1", "-10"`	JSON value will be a decimal string. Either numbers or strings are accepted.

However, when trying to decode messages including these types, it raises:

```
Google::Protobuf::ParseError: Error occurred during parsing: String specified for non-string/non-enum field
```

Decoding these same messages in native format works. Also, decoding these messages in JSON format works in Go.

To demonstrate the problem, I created an example [project](https://github.com/ryanbrainard/ruby-pb-example) with a [failing test](https://github.com/ryanbrainard/ruby-pb-example/blob/master/example_rb_test.rb).

**Comment by TeBoring** [comment]
Should have been fixed by #5533
