### ISSUE TITLE
Python: Add __doc__ to Message subclasses.

### ISSUE THREAD

**Issue by lukesneeringer** [protocolbuffers/protobuf#3052]
In our client libraries, we routinely return `google.protobuf.messages.Message` subclasses directly to our users.

These objects have the most amazing `__repr__` in the history of the known universe (yay), but they do not have docstrings. Please consider having protoc assign a meaningful `.__doc__` attribute to these classes that enumerates the public properties of the message and their types.

**Comment by zhangskz** [comment]
Thanks for the feature request! This seems like this may be useful, but closing since we're unlikely to be able to pick this up in the near future. However, we're happy to help with review if this is something you (or anyone else) would like to contribute.
