### ISSUE TITLE
PHP custom options not available

### ISSUE THREAD

**Issue by camuthig** [protocolbuffers/protobuf#3065]
Is there any way currently access custom option values using the generated PHP classes? It seems like when I add one to my proto file then my generated class lists having an `UninterpretedOption` however I currently see two problems:

1. The descriptor is private and there is no getter on the `Message` class
2. The value of the option isn't saved anywhere that I can find

Are there plans to support this feature for PHP?

**Comment by TeBoring** [comment]
Sorry that we don't support it currently. But it's on our plan.

**Comment by camuthig** [comment]
@TeBoring do you have any timeline for the functionality?

**Comment by TeBoring** [comment]
Probably end of this quarter.

**Comment by francislavoie** [comment]
Any chance this will be added in the near future? I'd like to use `EnumValueOptions` to associate a couple extra string fields with my enum.

**Comment by TeBoring** [comment]
I don't have time for this feature now. Maybe early next year.

**Comment by phphphphphp** [comment]
What is the status of this ticket? Is this on any roadmap, or is there any work in progress to implement this? Being able to use custom options in PHP would be huge for my team's use case, however it seems this ticket hasn't seen activity for almost 3 years now.

**Comment by haberman** [comment]
I think PHP support for custom options should be achievable within the next six months.

upb (the C library underlying PHP's extension) will soon be getting support for extensions, which is the last major hurdle to supporting custom options.

**Comment by esorot** [comment]
Update: This is now supported in upb. We would need to prioritize creating the glue code to make it work.

**Comment by calvin2021y** [comment]
@haberman  @esorot 

any update?

**Comment by haberman** [comment]
Custom options are supported in the "upb" C library that underlies that PECL extension, so all external blockers are removed.

But there are several things that would need to be implemented at the PHP layer to offer this feature.

1. We'd need to implement, both in pure-PHP and the PHP C extension, the code to expose options protos from the `*Descriptor` classes. A good model for this would be the Ruby support for descriptor options, which was added somewhat recently in https://github.com/protocolbuffers/protobuf/pull/14594.
2. We would need to make a decision how to handle immutability for those options protos. In other languages, the returned options are usually immutable, but PHP doesn't currently have any facility for making messages immutable. We would either need to add support for immutability, or have the accessors for options protos return a new copy of the options (ie. not shared).
3. To expose *custom* options, as opposed to built-in options, we'll also need to support extensions in PHP. PHP currently doesn't support extensions, so this would be a new feature in general for message objects.

We don't have anyone working on this currently.

**Comment by francislavoie** [comment]
> We would need to make a decision how to handle immutability for those options protos. In other languages, the returned options are usually immutable, but PHP doesn't currently have any facility for making messages immutable. 

PHP has the `readonly` keyword, which is effective immutability. It makes properties "write-once", and throws an error on any attempt to change the value thereafter.

**Comment by haberman** [comment]
To use `readonly` I think we'd need to have separate types. For example, given a message `Foo`, we currently generated a PHP class `Foo`. Would we also need to generate a separate class `ReadonlyFoo`? That would be a major change to the generated API.
