### ISSUE TITLE
Jruby no such file to load

### ISSUE THREAD

**Issue by amedeiros** [protocolbuffers/protobuf#3090]
Using the protobuf jruby gem I get the following error. This is not a problem with the MRI version of the gem.

Versions:
jruby-9.1.8.0 (fails to load)
ruby-2.4.0 (loads fine)
google-protobuf 3.3.0

`LoadError: no such file to load -- google/protobuf`

**Comment by haberman** [comment]
I am assuming that this bug is fixed in #7923.
