### ISSUE TITLE
Add flag that adds an underlying type to enums in generated C++ files

### ISSUE THREAD

**Issue by nico** [protocolbuffers/protobuf#3096]
C++11 offers and explicit enum types (enum Foo : int C++11 7.2 p5), both of which allow for forward declaration of enums. By allowing forward declaration, C++ applications can reduce the places that include the .pb.h with the enum definition.

It'd be cool if protoc had a flag to opt in to getting this behavior.

Spun off from #67.

**Comment by jorgbrown** [comment]
We use `int` as the underlying type now.
