### ISSUE TITLE
Split PHP directory into sub-repo for composer

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#3108]
As composer has a strict one-package-per-repository rule, the only way to avoid pulling in the entire `protobuf` repository instead of just the files relevant to PHP is to split this out into its own repository.

As a result, the package `google/protobuf` contains `32M` of data and `1912` files. The only files needed are in `php/src`, which contains 110 files which combined are less than a single megabyte. This means we are pulling down more than **30x the data** required when installing this package.

Additionally, platforms like App Engine [limit the number of files](https://cloud.google.com/appengine/quotas) that can be uploaded. Repositories like this consume a sizable chunk of that limit for no reason.

Can we make a subtree-split for php (`google/protobuf-php`)? This could be mirrored and versioned automatically, and is already being done for other composer packages for php (see [google-cloud-php](https://github.com/googlecloudplatform/google-cloud-php) vs [google-cloud-php-bigquery](https://github.com/googlecloudplatform/google-cloud-php-bigquery)). There is also an open ticket to do this for grpc (https://github.com/grpc/grpc/issues/10489)

**Comment by bshaffer** [comment]
We need to verify we can make this change w/o breaking composer compatibility.

**Comment by bshaffer** [comment]
Composer respects `.gitattributes`, and anything marked as `export-ignore` will not be installed by composer. We use this in [google/cloud](https://github.com/googleapis/google-cloud-php/blob/master/.gitattributes), and we could use it to ignore the `src` directory. However, this could have unintended effects with other tools using gitattributes.

**Comment by bshaffer** [comment]
This is a P1!

**Comment by wsamoht** [comment]
It looks like this happened recently as I did a `composer update` today and the package `google/protobuf` was updated to point to https://github.com/protocolbuffers/protobuf-php.git instead of https://github.com/protocolbuffers/protobuf.git. Only problem is that composer didn't update the autoload psr-4 section in the `composer.lock` file. I am going to guess this is an issue with composer?

I ended up having to manually update my `composer.lock` file (see below) and then remove my entire `vendor` folder and do a `composer install`. A `composer dump-autoload` didn't seem to work (it didn't update the autoload files).

**Previous**
```
"autoload": {
    "psr-4": {
        "Google\\Protobuf\\": "php/src/Google/Protobuf",
        "GPBMetadata\\Google\\Protobuf\\": "php/src/GPBMetadata/Google/Protobuf"
    }
},
```

**Should be**
```
"autoload": {
    "psr-4": {
        "Google\\Protobuf\\": "src/Google/Protobuf",
        "GPBMetadata\\Google\\Protobuf\\": "src/GPBMetadata/Google/Protobuf"
    }
},
```

**Comment by TeBoring** [comment]
In our new repo, we have already changed this:
https://github.com/protocolbuffers/protobuf-php/blob/master/composer.json

**Comment by TeBoring** [comment]
I think it's composer's work. We cannot do anything.

**Comment by bshaffer** [comment]
@wsamoht sorry for the inconvenience, we were under the impression this change would be transparent.

**Comment by wsamoht** [comment]
No prob :) Appreciate the response!
