### ISSUE TITLE
PHP: Using native types in place of proto types

### ISSUE THREAD

**Issue by michaelbausor** [protocolbuffers/protobuf#3119]
For example, using a `DateTime` object in place of a `Timestamp` protobuf message. So a `TimeInterval` message, which accepts a `Timestamp` object in its `start_time` field:
```
$timestamp = new Timestamp();
$timestamp->setSeconds(time()); 
$interval = new TimeInterval();
$interval->setStartTime($timestamp);
```
would also accept a `DateTime` object:
```
$datetime = new \DateTime();
$interval = new TimeInterval();
$interval->setStartTime($datetime);
```

**Comment by bshaffer** [comment]
See https://github.com/googleapis/toolkit/issues/1273

**Comment by bshaffer** [comment]
@michaelbausor this issue could (and maybe should be) be solved at the GAPIC layer

**Comment by michaelbausor** [comment]
This can certainly be solved in the GAPIC layer, as described in the toolkit issue you linked to above, and this may be the best option. (In fact, we already have similar functionality implemented in the google-cloud-php library which is used by logging, pubsub and spanner).

One reason to prefer implementing this in protobuf instead of the GAPIC layer (perhaps in the long term) is that we would implement this functionality in our GAX library (https://github.com/googleapis/gax-php), but if it is a real usability win then it makes sense to make it available to other users of protobuf.

**Comment by TeBoring** [comment]
Is Timestamp the only one needs to be taken care of?
For timestamp, I think it's ok to accept DateTime for setter.
We don't need to change the return value for getter, right?

**Comment by michaelbausor** [comment]
I don't think we should change the return type of the getter. I think Timestamp/DateTime is the only one, @bshaffer are there any others you know of?

The toolkit issue linked above (https://github.com/googleapis/toolkit/issues/1273) describes how the generated GAPIC layer could accept an associative array in place of a protobuf message, with keys matching the fields to be set. This is a change in our surface that can be done independently from protobuf, but if using an associative array is a good feature for users, then we may want to consider supporting it directly in protobuf. This could be one or both of:
- Accepting an associative array in the constructor
- Accepting an associative array in the setter methods for message fields

Maybe this should be split into a separate issue?

**Comment by haberman** [comment]
I agree that we shouldn't change the return type of the getter.

Is there still a desire for the setter to accept different types like DateTime?

**Comment by deannagarcia** [comment]
Going to close due to no response. If you still want this, please reopen with more information.
