### ISSUE TITLE
CXX_FOR_BUILD is set to g++ instead of $CXX

### ISSUE THREAD

**Issue by JaeseungYeom** [protocolbuffers/protobuf#3141]
Hi,
I am trying to compile using clang, but having an issue as described below.

I have set the environment variables CC and CXX to clang and clang++ respectively, and run configure script with CC=clang CXX=clang++ as well.
However, the Makefile generated under the project root and that under src directories have CXX_FOR_BUILD set to g++ regardless. There are more variables set to use gcc/g++ instead of clang/clang++ although I still see that CXX and CXXCPP are set to use clang++.

```
> ./configure CC=clang CXX=clang++
> grep g++ Makefile | grep -v clang
CXX_FOR_BUILD = g++ -std=gnu++11
ac_ct_CXX_FOR_BUILD = g++
> grep clang++ Makefile
CXX = clang++ -std=gnu++11 -std=gnu++11
CXXCPP = clang++ -std=gnu++11 -E
```
If I manually replace g++ with clang++, I can build successfully.
Is there something that I am missing to make this work without manual editing?

The version of clang is 4.0.
Thanks in advance.

**Comment by acozzette** [comment]
I think you may just need to pass `CXX_FOR_BUILD=clang++` when you call `./configure`. Could you try that and see if it works? The reason for `CXX_FOR_BUILD` is that it's supposed to be the compiler we would use for building code that runs on the host platform in a cross-compilation setup.

**Comment by JaeseungYeom** [comment]
That works! Thanks a lot.
One question I have is that if there is any reason to pick gcc over other compiler as the choice for CXX_FOR_BUILD.

**Comment by acozzette** [comment]
I don't think there's any particularly good reason why gcc is being picked instead of clang there; autoconf just tries to guess which compiler would work best to compile binaries that will run on the build machine.

**Comment by JaeseungYeom** [comment]
That make sense. Thanks a lot.

**Comment by jamie-arcc** [comment]
Can we reopen this? This is an ongoing issue.  Other software built with autoconf does not have this issue. If this is going to be a 'no fix', then at very least `./configure --help` should be updated to include these environment variables in the list at the bottom.

**Comment by acozzette** [comment]
@jamie-arcc We would be happy to accept a pull request if you have a fix for this.

**Comment by BSBandme** [comment]
Will close after some time as this is open for a long time.
And also I think passing CXX_FOR_BUILD to configure is a reasonable solution.
