### ISSUE TITLE
Cardinality (streaming versus non-streaming, and in each direction) information available from descriptors?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#3168]
If I define a service like
```proto
service MyService {
  rpc MyBidirectionallyStreamingMethod(stream MyRequestMessage) returns (stream MyResponseMessage) {}
}
```
and then generate a my_generated_module_pb2.py module, the module will contain a [FileDescriptor](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.FileDescriptor-class) from which I will be able to reach a [ServiceDescriptor](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.ServiceDescriptor-class) from which I will be able in turn to reach a [MethodDescriptor](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.MethodDescriptor-class) for MyBidirectionallyStreamingMethod. The cardinality (streaming or non-streaming of both requests and responses for the method) should be determinable from this method descriptor, right? I can't seem to figure out how. From the way that the `stream` keywords are syntactically prominent in the service definition I figured there would be something like `.request_streaming` and `.response_streaming` attributes on the method descriptor object itself, but there aren't and I can't seem to find the streaming semantics coded any other way either.

Are they there and I'm just missing them? If they're not there, should they be added?

**Comment by xfxyjwf** [comment]
I guess it's just not implemented in python protobuf yet. The MethodDescriptor in python should have a client_streaming and a server_streaming attribute just like in C++.

**Comment by andreycizov** [comment]
Neither CPP, Java or Python mention these at all: 
  - https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_service.cc
  - https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/java/java_service.cc
  - https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc

On the other hand, the grpc implementations use them.
  - https://github.com/grpc/grpc/blob/master/src/compiler/protobuf_plugin.h

Question is: is there a plan on implementing these at all?
