### ISSUE TITLE
In Java, shortDebugString is unfriendly with unicode, and printToUnicodeString it unfriendly with multiline.

### ISSUE THREAD

**Issue by ccl0326** [protocolbuffers/protobuf#3247]
Why not make shortDebugString compatible with unicode or add new helper function shortDebugUnicodeString?

**Comment by ccl0326** [comment]
Why not make shortDebugString compatible with unicode or add new helper function shortDebugUnicodeString?

**Comment by elharo** [comment]
We're not going to add shortDebugUnicodeString to avoid increasing code complexity. In what way is shortDebugString incompatible with Unicode?

**Comment by elharo** [comment]
Comment and I can reopen if there's more info. As is, I don't see a problem in the code though I could be missing something.
