### ISSUE TITLE
Python3: text_format.merge needs a check-and-decode step?

### ISSUE THREAD

**Issue by kesinger** [protocolbuffers/protobuf#3279]
text_format.Parse has a check to ensure that it's been passed a string:

    if not isinstance(text, str):
        text = text.decode('utf-8')

but text_format.Merge does not, so if it gets passes a bytes object, it will fail at 

    text.split('\n'),

with a TypeError:

    TypeError: a bytes-like object is required, not 'str'

Adding the same check as from text_format.Parse "fixes" the error.

**Comment by anandolee** [comment]
Thanks for raise it up. Will ad the support for Merge

**Comment by anandolee** [comment]
Looks like both Parse and Merge in text format have been changed. They are consistence now
