### ISSUE TITLE
Add capability to message Descriptor objects to instantiate, serialize, and deserialize?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#3283]
Given a [`google.protobuf.descriptor.Descriptor`](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.Descriptor-class) object `my_message_descriptor`, I'd like to be able to run code like
```python
my_test_integer = 5

my_message = my_message_descriptor.create(my_field=my_test_integer)

# Equivalent to "my_message.SerializeToString()".
# Possibly better named "to_bytes"?
my_serialized_message = my_message_descriptor.serialize(my_message)

# Duck-type-equivalent to "<message class>.FromString(my_serialized_message)".
# Possibly better named "from_bytes"?
my_serialized_then_deserialized_message = my_message_descriptor.deserialize(
    my_serialized_message)

# (Duck-type-equivalence.)
assert my_message == my_serialized_the_deserialized_message
assert my_message == my_generated_module_pb2.MyMessage.FromString(my_serialized_message)
assert my_message == my_generated_module_pb2.MyMessage(my_field=my_test_integer)
```
. Is there a reason [`Descriptor`](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.Descriptor-class) objects aren't so capable today?

Is message instantiation, serialization, and deserialization something I should be able to do today given only a [`Descriptor`](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.Descriptor-class)? If so, is it as straightforward as illustrated above and I'm just not seeing how?

**Comment by anandolee** [comment]
GetPrototype in Message factory can build a message class based on descriptor. Is it good for usage?

**Comment by haon4** [comment]
Closing since GetPrototype should be sufficient.
