### ISSUE TITLE
[gRPC] [C#] Hard to catch `NullReferenceExceptions` on sub-types, not initialized empty (should be structs?)

### ISSUE THREAD

**Issue by AlbinoGeek** [protocolbuffers/protobuf#3305]
**I could easily be doing something wrong.**

Using Protobuf frequently in C# I wonder why a message containing other messages doesn't unmarshal with default values, sometimes leading to `NullReferenceException`s that are hard to diagnose (as you do things in `async` sometimes... where Exceptions can't easily be linked back to the line that caused them.)

**Conditions:**
- I am using gRPC with a Service
- I am filling data on the Server in Golang
  - Standard signatures like `Login(ctx context.Context, in *TestProto.AuthRequest) (*TestProto.AuthResponse, error)`
- I am reading the data on the Client in C#
  - Connection handled by `new Channel("ip:port", ChannelCredentials.Insecure);`
  - I keep the Channel around for a while, and use it multiple times a second -- is that correct?  Should I be shutting down and creating new channels?  Is there connection pooling implemented somewhere I'm missing?

**What I have tried:**
- I have made sure to fill all fields on the server.. debug printing, etc.

**The Problem:**
- Sometimes the sub-fields come in as nulls

**Test Protocol:**

```protobuf
syntax = "proto3";

service Test {
  rpc Login (AuthRequest) returns (AuthResponse) {}
}

message AuthRequest {
  string username = 1;
  string password = 2;
}

message AuthResponse {
  bool ok = 1;
  uint16 identifier = 2;
  Account account = 3;
}

message User {
  uint16 identifier = 1;
  repeated Character characters = 8;
}

message Character {
  uint16 identifer = 1;
  uint16 padding = 2;
  string name = 3;
  Vec2 position = 6;
}

message Vec2 {
  float32 x = 1;
  float32 y = 2;
}
```

**Test Client Code:**

```csharp
    public async bool Login(string hashed) {
      AuthResposne response = await AuthRequest(hashed);
      // Attempt to do something with response.Account can sometimes cause an exception
      // Attempt to iterate a non-null response.Account.Characters to find null Position .....
      return Task.FromResult(response.ok);
    }
    
    private async Task<AuthResponse> AuthRequest(TestProto.Test.TestClient c, string hashed)
    {
        var async = c.LoginAsync(new AuthRequest {
            Login = Username,
            Password = hashed
        });

        return await async.ResponseAsync;
    }
    
    private async Task<bool> StartBackgroundTasl(Task t) {
      try {
        await t; // Always throws NullReferenceException, real exception in t.Exception
      } catch (Exception e) {
        AggregateException ae = null;
        try {
          ae = t.Exception; // Get the inner exception
        } catch (NullReferenceException e) {} // Inner exception might not exist
        if (ae != null) throw ae; // or ae.Flatten();
        throw e; // If t.Exception was null ...
      }
    }
    
    // Usage: StartBackgroundTask(Login(hashed));
    // Can be called in sync and goes background
```

I thought the Unmarshal was supposed to give me structs all the way down, with all their default values.

**Comment by roger-zhao** [comment]
@AlbinoGeek ,Hi, just curious, I see "uint16" in your .proto, seems that not supported in proto3?

**Comment by jskeet** [comment]
I don't expect this behavior to change. Protobuf messages are generated as classes, not structs, and `null` is used for "not set" rather than creating an "empty" message and users having to test for presence. IMO this is more idiomatic C#.

If you're using a field that might not be initialized, you can use the null-conditional operator (`?.`) in the "path" and then the null-coalescing operator at the end.

I'll close this now as I don't expect us to make any changes here.
