### ISSUE TITLE
import urls for well known types are undocumented

### ISSUE THREAD

**Issue by stub42** [protocolbuffers/protobuf#3307]
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf lists all the well known types, but the URLs needed to import them into your .proto file are a secret. The only one I can find any reference to is Any, import "google/protobuf/any.proto". Others like Empty or any of the wrappers are undocumented.

**Comment by otto-dev** [comment]
Still not fixed? I'm trying to import `ListValue` and can't find any reference of the `import`.

**Comment by fyaretskiy** [comment]
Just ran into the problem @otto-dev 


```
import "google/protobuf/struct.proto";

google.protobuf.ListValue foo = 1;
```

seems to work

**Comment by yoshiask** [comment]
Please reopen this issue. This information should be clearly documented.
