### ISSUE TITLE
PHP: Provide field name in exception message when parsing JSON

### ISSUE THREAD

**Issue by groganz** [protocolbuffers/protobuf#3326]
When there's a mismatch between the defined and the provided value, this is how an error message looks like:

`Error occurred during parsing: Invalid data type for int32 field`

It would be helpful to also include the name of the field, to more easily understand where the error occurred, e.g.:

`Error occurred during parsing: Invalid data type for int32 field 'my_field'`

The respective code could be something like this at https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L772

`
if (!is_numeric($value)) {
    throw new GPBDecodeException(
        "Invalid data type for int32 field '" . $field->getName() . "'");
    }
`

**Comment by haon4** [comment]
Thanks for filing this. Would you mind sending us a PR to fix this?

**Comment by deannagarcia** [comment]
I'm closing this issue to no response. If you still want this fix, feel free to reopen.
