### ISSUE TITLE
Make php c extension portable on windows

### ISSUE THREAD

**Issue by TeBoring** [protocolbuffers/protobuf#3342]

**Comment by zsxsoft** [comment]
https://github.com/zsxsoft/protobuf/commit/00160b1679ed05d89363e08c5909c06f31143016

Just made a commit to make it compilable in Windows. It's just compilable, not able to use(php-cgi crashed) and don't care about other OSs and PHP versions.
Compiled in PHP 7.1.7 in Windows 10 with msvc2015 with ``configure --disable-all --enable-cli=shared --enable-protobuf=shared --disable-zts`` with lots of warnings...
![image](https://user-images.githubusercontent.com/2398785/29257401-50759a60-80e4-11e7-8f84-0b31b751ae67.png)
![image](https://user-images.githubusercontent.com/2398785/29257436-92176a66-80e4-11e7-8416-f8b5fb8b46c7.png)

![image](https://user-images.githubusercontent.com/2398785/29257415-7050fd34-80e4-11e7-8e4c-5888a23b80d5.png)

**Comment by TeBoring** [comment]
This is very appreciated! Could you send a PR to us?

**Comment by zsxsoft** [comment]
No, because the changes I made are just for test, the coding style is too bad and have unknown side effect.

**Comment by TeBoring** [comment]
If you would like to fix the windows build, that will be very appropriated.

**Comment by zsxsoft** [comment]
Created

**Comment by fowles** [comment]
I suspect this is already done now

**Comment by deannagarcia** [comment]
Closing, reopen if there is still a problem.
