### ISSUE TITLE
Error compiling with VS 2017 Duplicate Attribute

### ISSUE THREAD

**Issue by kstubs** [protocolbuffers/protobuf#3384]
I have several messages complaining about Duplicate attributes from Google.Protobuf(net45) project.  I'm not sure how to build.  Here is one of the exceptions.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute	Google.Protobuf(net45), Google.Protobuf(netstandard1.0)	C:\Tools\protobuf-3.3.0\csharp\src\Google.Protobuf\obj\Debug\net45\Google.Protobuf.AssemblyInfo.cs	18	Active
```

Karl..

**Comment by jskeet** [comment]
Closing this as obsolete - there may have been a project file issue at one point, but it's certainly not a problem now.
