### ISSUE TITLE
compile and install python module failed

### ISSUE THREAD

**Issue by Catstyle** [protocolbuffers/protobuf#34]
download release packege from https://protobuf.googlecode.com/svn/rc/protobuf-2.6.0.tar.gz
yeah, for some all we known reasons i cannot build from git source because it need to download gtest from google site

`./configure && make && make install && ldconfig`
protoc installed successfully, then go to install python module

```
cd python
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
python setup.py build --cpp_implementation && python setup.py test --cpp_implementation && python setup.py install --cpp_implementation
```

indeed it said all goes well, but when i tried my app, it complained that missing pyext
ah... something wrong!
then i took a look at the protobuf egg,  **it DID HAVE NO pyext module**
am i doing wrong?

**Comment by foebu** [comment]
Hi, how did you fix it in the end? I didn't get it. Thank you.

**Comment by xfxyjwf** [comment]
@foebu, a file was missing from the setup.py script. We added that file in the fix.

**Comment by foebu** [comment]
I still get the error, though, and I downloaded the release 2.6.1.

**Comment by burner-** [comment]
yeah looks that 2.6.1 does not work wirh 2.7 or with 3.4.3

**Comment by foebu** [comment]
Now, that works. But if that is the standard test, then this readme needs to be changed: https://github.com/google/protobuf/tree/master/python
Thank you, though!

**Comment by xiaofeng-gg** [comment]
On Tue, Jun 2, 2015 at 1:44 AM, foebu <notifications@github.com> wrote:

> Now, that works. But if that is the standard test, then this readme needs
> to be changed: https://github.com/google/protobuf/tree/master/python
> Thank you, though!
>
Note that in 2.6.1 release, the readme does say using "google_test":
https://github.com/google/protobuf/tree/v2.6.1/python

This has been changed in recent releases though.

**Comment by foebu** [comment]
My bad then, I was reading a different readme :) Sorry.

**Comment by PlasmaSheep** [comment]
I'm having this issue as well. google_test passes, but I still get the error when I try to import an automatically compiled python protobuf file.
