### ISSUE TITLE
Incompatibility between json and binary decode in ruby

### ISSUE THREAD

**Issue by ramigluzman** [protocolbuffers/protobuf#3440]
Binary proto is decoded properly with a proto class which doesn't define all the fields, though an exception is thrown when doing the same with json decoding.
My encoding is done using `UserCreatedEvent` and the decoding is done using `BaseEvent` (which is a "subset" of `UserCreatedEvent` that contains only the `message_base` field)

**base.proto**
```
syntax = "proto3";

message BaseStateChangeEvent {
  string aggregate_id = 1;
  string aggregate_type = 2;
}

message BaseEvent{
  BaseStateChangeEvent message_base = 1;
}
```
**user.proto**
```
syntax = "proto3";

import "base/base.proto";

message UserCreatedEvent{
  BaseStateChangeEvent message_base = 1;
  string username = 2;
  string email = 3;
  string password = 4;
}
```
**Runtime example using `irb`:**
```
2.3.3 :001 > require './base/base_pb'
 => true
2.3.3 :002 > require './entities/user_pb'
 => true
2.3.3 :003 > u = UserCreatedEvent.new(username: 'ramzigl', password: '123456')
 => <UserCreatedEvent: message_base: nil, username: "ramzigl", email: "", password: "123456">
2.3.3 :004 > u.message_base = BaseStateChangeEvent.new(aggregate_id: '1', aggregate_type: 'User')
 => <BaseStateChangeEvent: aggregate_id: "1", aggregate_type: "User">
2.3.3 :005 > BaseEvent.decode(UserCreatedEvent.encode(u)) # works!!!
 => <BaseEvent: message_base: <BaseStateChangeEvent: aggregate_id: "1", aggregate_type: "User">>
2.3.3 :006 > BaseEvent.decode_json(UserCreatedEvent.encode_json(u)) # fails!
Google::Protobuf::ParseError: Error occurred during parsing: No such field: username

	from (irb):6:in `decode_json'
	from (irb):6
	from /Users/rami.gluzman/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```
(See the difference between line 5 and line 6)

I would expect both decoders to be coherent.

**Comment by tenderlove** [comment]
Seems like both should raise an exception.  Why are you asking `BaseEvent` to decode the contents generated by a `UserCreatedEvent`?  If you change to `UserCreatedEvent.decode_json` it seems to work.

**Comment by ramigluzman** [comment]
@tenderlove We're developing a micro-services event-sourced system. We have different services that consume different messages (proto messages).
When an encoded message is being consumed we can't distinguish its type, meaning that we can't explicitly decode it using the right proto class. Our current implementation is to encode the class type as part of a *common metadata* message (`BaseStateChangeEvent`), and then to decode the full message using reflection (but that's not the issue here 😉)

**Comment by acozzette** [comment]
For some languages (e.g. C++ and Java) you can pass a flag indicating that unknown fields should be ignored when parsing JSON. I don't think we support this for Ruby but we would probably welcome a pull request for this if anyone wants to add support for it.

**Comment by tenderlove** [comment]
@ramigluzman ah, I see. I'm not sure how you'd accomplish this without indicating the base type (like you're manually doing).  Wrapping the protobuf JSON in a container JSON seems like the only way to handle arbitrary protobuf messages.  It might be nice if that was explicitly supported.

@acozzette doesn't that mean those langs could lose data?  Personally, I'd rather get an exception. 😉

**Comment by acozzette** [comment]
@tenderlove That's true, unknown fields would be discarded and so that could be an unacceptable data loss depending on the situation. The binary format has an advantage here since it has the ability to preserve unknown fields. There's another issue (#2289) discussing the possibility of preserving unknown fields in the JSON format, but I suspect that this is not going to happen because it would be pretty difficult and complicated to implement.

**Comment by TeBoring** [comment]
For ruby, we already support ignore unknown in json decoding.
Preserving unknown in json will be too difficult.
