### ISSUE TITLE
Installing Google.Protobuf -Version 3.3.0 nuget to UWP project

### ISSUE THREAD

**Issue by NVgithub** [protocolbuffers/protobuf#3466]
Hello 

I was wondering if the Google.Protobuf nuget package is supported in UWP projects because when I try to add it to a UWP Class Library project the following exception is thrown:

`System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).`

I am trying to use a generated .cs file from a protoc.exe in a UWP project.

**Comment by haon4** [comment]
We don't have any experience building a UWP program so we probably can't help fix the issues you mentioned any time soon. I am hoping that someone with experience in building UWP program can help out on this.

**Comment by sureshbadagi** [comment]
Hi,
I am able to install Google.Protobuf in UWP classlibrary without any problem. 
I did nothing special to install.
