### ISSUE TITLE
Issues with Protobuf and Spark

### ISSUE THREAD

**Issue by jhaber** [protocolbuffers/protobuf#3474]
Hi, I wanted to get your thoughts on an issue we've run into with a few of our Spark jobs when they try to serialize protobufs using Java serialization (and it seems like others have run into [this](https://stackoverflow.com/questions/40885430/unable-to-find-proto-buffer-class-in-spark/40904420#40904420) [same](http://apache-spark-user-list.1001560.n3.nabble.com/Unable-to-find-proto-buffer-class-error-with-RDD-lt-protobuf-gt-td14529.html) [issue](http://permalink.gmane.org/gmane.comp.lang.scala.spark.user/4936)). I put an example stack trace [here](https://gist.github.com/jhaber/198bbb1f3a91378cfe4271655021b54f). The error was confusing at first, but looking at the relevant line in GeneratedMessageLite I think I see the problem: https://github.com/google/protobuf/blob/774d630bde574f5fcbb6dae6eaa0f91f7bc12967/java/src/main/java/com/google/protobuf/GeneratedMessageLite.java#L768

The call to `Class.forName` doesn't include a `ClassLoader` argument, so it will attempt to use whichever `ClassLoader` was used to load  `GeneratedMessageLite`. Since Spark itself uses protobuf-java, this ends up being a `ClassLoader` further up the chain that doesn't know anything about our protobuf classes. To confirm this is the issue, we ran this code in the Spark executor:
```java
// fails with ClassNotFoundException
Class.forName("com.hubspot.Protos$ExampleProto", true, GeneratedMessageLite.class.getClassLoader());
// works fine
Class.forName("com.hubspot.Protos$ExampleProto", true, Thread.currentThread().getContextClassLoader());
```

There are a few workarounds in the Spark case, but it seems like this is a more general issue that could crop up outside of Spark. Thoughts on switching all usages of `Class.forName` to include an explicit `ClassLoader` argument? This way, preference could be given to the thread's context class loader, similar to the strategy that's used by the [Resources class in Guava](https://github.com/google/guava/blob/6290373588ef914111f0896b8d0c86a15b7f0f6b/guava/src/com/google/common/io/Resources.java#L194-L195)

I'm interested to hear your thoughts on this issue, thanks

**Comment by jhaber** [comment]
I should also note, the call to `Class.forName` is inside of the `readResolve` method so it's only a problem if using Java serialization/deserialization

**Comment by xfxyjwf** [comment]
Thanks for the report. The proposed solution sounds good to me. Could you help make a pull request to fix it?

**Comment by xfxyjwf** [comment]
@jhaber If you don't mind, could you resend the pull request?

**Comment by jhaber** [comment]
Sure thing, pull request re-sent.

**Comment by ejona86** [comment]
It seems like the correct class loader would be available from `regularForm.getClass().getClassLoader()`.

**Comment by jhaber** [comment]
`regularForm` is available on the serialization side and is used to initialize the `SerializedForm` fields, but then `SerializedForm` is serialized using Java serialization. So at deserialization time, inside the `readResolve` method, the only information we have is the fields that were serialized (`messageClassName` and `asBytes`). We could add more fields to `SerializedForm`, but I don't think there's anything that would help with this particular problem (couldn't serialize the `ClassLoader` or anything)

**Comment by ejona86** [comment]
Oh, I see, it is serialization. Class is serializable, and including it here does make some sense as it requires Java to figure out how to handle it... If Java can re-constitute the Class, then the ClassLoader will be correct.

It looks like Collections.checkedCollection keeps the Class for serialization and has explicit serialization support.

It just is unclear how in some environments Java can re-constitute it... `ObjectInputStream.resolveClass` says it chooses the class loader via (null means "system class loader"; just jdk classes):
> if there is a method on the current thread's stack whose declaring class was defined by a user-defined class loader (and was not a generated to implement reflective invocations), then loader is class loader corresponding to the closest such method to the currently executing frame; otherwise, loader is null

It doesn't seem like that would work with RMI though, since I think it spawns its own thread for processing behind-the-scenes, so I guess RMI overrides `resolveClass()`. Yeah. The more I dig into this, the more appropriate "save a reference to the `Class`" looks. Also, it probably would be a good idea to save the Builder's Class, instead of the message's, but that probably doesn't matter too much.

**Comment by jhaber** [comment]
I sent a PR with that change, but I'm not actually sure it will fix the Spark issue. Based on my reading of that Javadoc, I'm afraid that the closest method on the stack will belong to `GeneratedMessageLite` in which case we're back where we started

**Comment by ejona86** [comment]
@jhaber, the closest method on the stack when _decoding_, so whatever is calling ObjectInputStream. `ObjectInputStream` would end up creating `SerializedForm` and reconstituting the `Class`, and then afterwards call `readResolve()`.

**Comment by elharo** [comment]
fixed by above PRs
