### ISSUE TITLE
How to use C++ based python protobuf on windows

### ISSUE THREAD

**Issue by Chenjunchao** [protocolbuffers/protobuf#3522]
Hi,

I'd like to use C++ based python protobuf on windows. When I tried to build the C++ extension of python protobuf, I found the python/setup.py is designed only for Linux. I was just wondering if there is any suggestion on how to use C++ based python protobuf on windows.

Thanks in advance.

**Comment by anandolee** [comment]
Python c++ was not supported in the past. I assume this should be fix. Feel free to reopen if it is still an issue
