### ISSUE TITLE
Lua Lua Lua , I want !!!

### ISSUE THREAD

**Issue by DengQunhao** [protocolbuffers/protobuf#3566]
When can support lua,I've been waiting a long time.

**Comment by AnotherEva** [comment]
I Agree！

**Comment by dkrikun** [comment]
Any official response on the matter? Given there is a support for lots of language in protobuf3, it would be only natural to also have a support for lua, IMO.

**Comment by BSBandme** [comment]
I guess in the near future we may not be able to support Lua. Assigned P3 label

**Comment by TeBoring** [comment]
We currently don't have time to implement that.
However, https://github.com/protocolbuffers/upb previously had some support for lua. @haberman for more info.
Close this for now.
