### ISSUE TITLE
ProtoV2 & V3 support PHP ? 

### ISSUE THREAD

**Issue by ghost** [protocolbuffers/protobuf#358]
Any official release ?

**Comment by fjjiaboming** [comment]
Need to handle the popular programming Language .

**Comment by helmo** [comment]
A quick search gave me an implementation https://github.com/drslump/Protobuf-PHP

**Comment by ronaldpeng** [comment]
up

**Comment by anandolee** [comment]
We are currently working on official support for Proto V3

**Comment by dhowden** [comment]
Do you have a timetable for this that you can share?

**Comment by mish15** [comment]
👍

**Comment by anandolee** [comment]
Bo is working on the runtime support, the code for major features except WKT are already under review. Bo, do you have a estimate time for the release?

**Comment by dinoxxx** [comment]
take attention for the extension

**Comment by lulyon** [comment]
looking forward for the official php support release

**Comment by dhowden** [comment]
Anything further on this?  There is mention of a code review, but I don't see anything in the pull requests.  Can you given any indication of when you expect this to be released?

**Comment by cruelbob** [comment]
@TeBoring, are you still working on this feature?

**Comment by barryvdh** [comment]
The latest release from https://github.com/allegro/php-protobuf by @hjagodzinski should have support for proto3, not sure if anyone tested that?

**Comment by thinkerou** [comment]
Now the version of proto3 is `GA`, when proto3 supports php? thanks.

**Comment by TeBoring** [comment]
The support for php is expected to included in our next release. ETA is about 2 weeks.

**Comment by graste** [comment]
Will there be support for the proto2 syntax for the php generation?

**Comment by anandolee** [comment]
Currently not support and no plan for proto2 yet

**Comment by TeBoring** [comment]
Duplicates of #3623

**Comment by haberman** [comment]
Closing in favor of https://github.com/protocolbuffers/protobuf/issues/3623.
