### ISSUE TITLE
Issues with Werror

### ISSUE THREAD

**Issue by pgera** [protocolbuffers/protobuf#3599]
version: 3.3.2
OS: RHEL 7.4

I have a project which uses cmake. The command that combines the pb.cc and pb.h files has the following flags: -std=c++11 -fPIC -Wall -Wextra -Werror -Wno-write-strings -Wno-unused-function -Wno-unused-variable -Wno-sign-compare -O2 -DNDEBUG

This throws a lot of errors, some of which are:
protobuf/map_entry.h:105:25: error: missing initializer for member ‘google::protobuf::internal::ReflectionSchema::weak_field_map_offset_’ [-Werror=missing-field-initializers]
protobuf/map_type_handler.h:680:15: error: unused parameter ‘value’ [-Werror=unused-parameter]
   inline void MapTypeHandler<WireFormatLite::TYPE_##FieldType
google/protobuf/map_type_handler.h:518:13: error: unused parameter ‘arena’ [-Werror=unused-parameter]

There are quite a few of these. However, there is a strange config issue as well. If I move the protobuf headers to /usr/include, these errors go away, despite the exact same command line. i.e., If my protobuf installation isn't at a standard location, and I pass the include location with -I, I see these errors, but if there is no -I flag, I don't see the errors.

Edit: I am able to build the project after adding -Wno-unused-parameter -Wno-missing-field-initializers. The other issue of /usr/include v/s different directory is still unclear to me.

**Comment by acozzette** [comment]
My guess is that the compiler avoids printing warnings for headers in `/usr/include` because it assumes that you probably don't want to be bothered with warnings that come from a system directory. If you want to fix up those other warnings then feel free to send us pull requests.
