### ISSUE TITLE
Lazy parsing for protobuf

### ISSUE THREAD

**Issue by patelprateek** [protocolbuffers/protobuf#3601]
Marking sub messages lazy in protobuf does not affect deserialization time. Is this feature implemented for java yet , i do see few LazyField.java and test cases , but marking nested fields (mostly maps) lazy , does not change any generated code or the deserialization performance.

**Comment by acozzette** [comment]
I'm not 100% sure for Java, but I believe laziness only works for singular submessage fields, not repeated fields or maps, so that may explain the performance you saw.

**Comment by patelprateek** [comment]
ahh i see. yes my message consists a bunch of maps and repeated fields and few singular/scalar fields like string.
Is this something that is available internally and will be a feature in future version ? Or are there some more fundamental issues limiting this behaviour ?
If this is indeed the case , are there any recommended or good practices when writing a proto schema , for example , always wrap my repeated fields or maps or scalar fields within another message and have the outermost message consists only few sub messages in order to achieve lazy decoding ?

**Comment by acozzette** [comment]
We haven't implemented this even internally, and as far as I know we don't have any plans to make laziness work with more field types. I'm not sure if there are any fundamental issues blocking it; it might just be that singular submessages were the most important use case for lazy fields. Using a wrapper message does sound like a reasonable idea if lazy parsing is important for you.

Could you explain some more about why you need to use lazy fields? If it turns out that you don't actually need to access the field at all but you just want to persist it, there are also some techniques you could try to avoid parsing the data but without relying on lazy fields.

**Comment by patelprateek** [comment]
My use case is : I have a huge protobuf with hundreds of nested sub messages/repeated fields/maps.  (actually i realized the most heavy weight objects are maps). When i receive these messages (about few hundred million) i want to filter them out based on some identifiers (which are small sub nested messages). So in order to filter quickly i only want to decode only the sub message within this giant protobuf and if that filter predicate evaluates to true i want to pass in and de serialize rest of the huge message. Another use case is I have to join these huge protobuf objects to another proto object , where my join in only based on a small string (or sub message) id field , so to improve the join speed i want to only decode the id sub message instead of the entire proto.

If you do have additional ideas please let me know. Right now the way i am working around this is having my id as a separate duplicated field in my schema  . Also would be good to know how can i just persist the data (that is my use case for the join , i just want to join huge protos and persist in some data storage , dont care about accessing other fields in that job itself )

**Comment by acozzette** [comment]
If you're using proto2, one thing you could try is replacing some of the huge fields that you don't always need to read with [extensions](https://developers.google.com/protocol-buffers/docs/proto#extensions). That way those parts of the message will only be parsed if you pass an extension registry including the extensions you want.

If that's not flexible enough, another thing you could try would be to create a separate schema that is effectively just a subset of your original schema containing only the fields you want to filter on--just make sure the field numbers match exactly. Then you could parse the message as this simpler schema and that would give you enough information to know whether you need to parse the whole thing with the full schema. This approach is kind of hacky but might be justified if you really need the performance.

**Comment by patelprateek** [comment]
i use proto3.
About the hacky solution (create another subset schema with same field numbers)  : seems like this will work with the repeated and map fields , is that true ? Not sure how lazy is actually implemented but hacky solution seems to be working in this case as well  ?

**Comment by acozzette** [comment]
The hacky solution should work for repeated and map fields, too, yes. Any fields that are not included in the smaller subset schema would just be treated as unknown fields.

**Comment by sclasen** [comment]
@acozzette  would you expect the following to generate java with LazyFields?  Here is the generated code https://gist.github.com/sclasen/5f1b4ce70e19612491154e843ebd420a, not seeing lazy anywhere except in the javadoc comments.

```
syntax = "proto3";

import "google/protobuf/any.proto";

option java_package = "com.example";
option java_outer_classname = "OuterExample";

message Example {
        string id = 1;
        google.protobuf.Any message = 2[lazy=true];
}
```

**Comment by acozzette** [comment]
@sclasen I'm guessing that we must have a special case somewhere that is preventing `lazy=true` from taking effect on an `Any` field. Do you really need the `Any` to be lazy, though? It seems to me like `Any` is already inherently lazy since its main payload doesn't get parsed until you explicitly unpack it.

**Comment by sclasen** [comment]
hey @acozzette I probably could have done a more straightforward example....

```
syntax = "proto3";


import "google/protobuf/any.proto";

option java_package = "com.example";
option java_outer_classname = "OuterExample";



message Example {
        string id = 1;
        google.protobuf.Any message = 2[lazy=true];
}

message SubExample {
        string id = 1;
}

message Example2 {
            SubExample message = 1[lazy=true];
}


```
generates https://gist.github.com/sclasen/02186dbbe2d976e9d48294e9e7633c76  where Example2 and SubExample dont seem (to my eye at least) to do anything lazy.

If I understand correctly, would it be expected that https://gist.github.com/sclasen/02186dbbe2d976e9d48294e9e7633c76#file-outerexample2-java-L1250 would have a LazyField wrapped around it?

**Comment by acozzette** [comment]
@sclasen Sorry for giving you the wrong answer before--I actually just learned that we disabled lazy fields for Java not too long ago, the one exception being that they're still used with MessageSet. The rationale as I understand is that lazy fields did not work well with hash and equals, and lazy parsing turns out to be bad for mobile since it can unexpectedly tie up the UI thread.

**Comment by sclasen** [comment]
Ah, gotcha, thanks @acozzette .  I suppose using Any could accomplish the same thing.  Do you have any background on why the following statement is in the

**Comment by acozzette** [comment]
@sclasen I think that statement is just referring to the fact that for some languages we have not yet finished implementing the helpers for packing and unpacking Any fields. Actually at this point that may be out of date, though; I'm not sure of the current status for all languages.

**Comment by TeBoring** [comment]
Close this as we have no plan to implement this for now.
