### ISSUE TITLE
PHP and well-known-types

### ISSUE THREAD

**Issue by mvdstam** [protocolbuffers/protobuf#3622]
Hi,

A lot of [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) aren't implemented in the PHP implementation as of this moment. Is this on the roadmap?

Thanks!

**Comment by TeBoring** [comment]
Working on that. ETA by end of year.

**Comment by mvdstam** [comment]
Thanks @TeBoring!

**Comment by bvisness** [comment]
It's 2018 - any updates?

**Comment by TeBoring** [comment]
Most of json support for well known type in c extension have been fixed.
There are some edge cases still broken. For details, see conformance/failure_list_php_c.txt.
