### ISSUE TITLE
provide Importer .proto from memory

### ISSUE THREAD

**Issue by IronsDu** [protocolbuffers/protobuf#3636]
Now, Importer .proto only from file, https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/importer.h#L167,

Can you provide dynamic compiler .proto from memory(.proto content string) ?

Like this:

`std::string protoContent = std::string("//here is proto file content")`

`DiskSourceTree sourceTree;`
`sourceTree.MapPath("", "./");`
`Importer importer(&sourceTree, NULL);`

**`importer.importFromString(protoContent);`**

**Comment by dluc** [comment]
Same would be useful for C# (.NET Core)

**Comment by TeBoring** [comment]
What's the content of the file? Definition with proto syntax? Serialized binary data of FileDescriptorProto?
For the former, maybe a memory mapped file can do it.

**Comment by dluc** [comment]
sorry to see this closed, it would have been a nice feature.

**Comment by IronsDu** [comment]
> What's the content of the file? Definition with proto syntax? Serialized binary data of FileDescriptorProto?
> For the former, maybe a memory mapped file can do it.
1. Can you provide dynamic compiler .proto from memory(`.proto content string`) 
2. I think memory mapped file can't do this work.
3. Whether  do this feature in library is better ? This is a naturally need.

**Comment by dluc** [comment]
@IronsDu please correct me if I'm wrong -- what we're asking is for a *runtime method* to translate a .proto file ([example](https://github.com/protocolbuffers/protobuf/blob/master/examples/addressbook.proto)) to a .NET protobuf interpreter, on the fly i.e. without the need to generate code, compile, build, deploy .NET assemblies everytime a new proto file is provided.

This would allow, for example, to create stream processors capable of parsing any protobuf data, without the need to rebuild and redeploy such processors.
