### ISSUE TITLE
[Python] linters should discover when you mistype a property 

### ISSUE THREAD

**Issue by ta32** [protocolbuffers/protobuf#3638]
I expected generated code from IDL, would allow python linters to generate warnings if you mistype a property or fill with the wrong type.

This would present an advantage over passing around JSON. Would it be possible to add type hints or do something to make static checking work with protobuf classes for python?

Is this an issue for the linters or is it something that can be improved in protobuf. 

People are complaining about this.
https://stackoverflow.com/questions/43674028/how-do-you-tell-pylint-what-the-members-of-a-protobuf-generated-object-are 

https://github.com/grpc/grpc/issues/10547

**Comment by pherl** [comment]
We'd happy to accept a PR for this.

**Comment by anandolee** [comment]
closing because duplicate with #2638 
We'd happy to accept a PR for this if anyone wants to make contribute
