### ISSUE TITLE
Problems with Python Layer: Protobuf Internal Error - Mutex Lock

### ISSUE THREAD

**Issue by paridhisrivastava** [protocolbuffers/protobuf#3671]
Hi, 
I am trying to run a Caffe model which includes a python layer. Initially, when I tried to run the model prototxt file, I got an error asking me to update the version of Protocol Buffer to 3.4.0. So I did that by building from the source code. I have also upgraded the protobuf package in python to version 3.4.0. After doing this and rebuilding caffe, I'm getting the following error on running a prototxt file containing the python layer. [Please note that this error does not generate when I run another model without Python layer.]

*** Aborted at 1506013588 (unix time) try "date -d @1506013588" if you are using GNU date ***
PC: @     0x7f7cb3719516 google::protobuf::internal::Mutex::Lock()
*** SIGSEGV (@0x0) received by PID 26314 (TID 0x7f7d9961e740) from PID 0; stack trace: ***
    @     0x7f7d961dc4b0 (unknown)
    @     0x7f7cb3719516 google::protobuf::internal::Mutex::Lock()
    @     0x7f7cb3719833 google::protobuf::internal::OnShutdown()
    @     0x7f7d994686ba (unknown)
    @     0x7f7d994687cb (unknown)
    @     0x7f7d9946d8e2 (unknown)
    @     0x7f7d99468564 (unknown)
    @     0x7f7d9946cda9 (unknown)
    @     0x7f7d8815ef09 (unknown)
    @     0x7f7d99468564 (unknown)
    @     0x7f7d8815f571 (unknown)
    @     0x7f7d8815efa1 dlopen
    @     0x7f7d969bda69 _PyImport_FindSharedFuncptr
    @     0x7f7d96976ea2 _PyImport_LoadDynamicModuleWithSpec
    @     0x7f7d9697a7e7 (unknown)
    @     0x7f7d96827199 PyCFunction_Call
    @     0x7f7d9694273e PyEval_EvalFrameEx
    @     0x7f7d969d1c0c (unknown)
    @     0x7f7d9693fe09 PyEval_EvalFrameEx
    @     0x7f7d96941509 PyEval_EvalFrameEx
    @     0x7f7d96941509 PyEval_EvalFrameEx
    @     0x7f7d96941509 PyEval_EvalFrameEx
    @     0x7f7d96941509 PyEval_EvalFrameEx
    @     0x7f7d969d1c0c (unknown)
    @     0x7f7d969d1ce3 PyEval_EvalCodeEx
    @     0x7f7d96859a98 (unknown)
    @     0x7f7d969008ee PyObject_Call
    @     0x7f7d968fbf0f _PyObject_CallMethodIdObjArgs
    @     0x7f7d96978824 PyImport_ImportModuleLevelObject
    @     0x7f7d96945588 (unknown)
    @     0x7f7d968271b9 PyCFunction_Call
    @     0x7f7d969008ee PyObject_Call

Also, I'm using Ubuntu 16.04. 

Any help/pointers would be appreciated. 
Thanks!

**Comment by AutoAuto** [comment]
Hi,

What is the status of this issue ? I have the same issue with protobuf and tensorflow.

**Comment by kodonnell** [comment]
[This](https://github.com/BVLC/caffe/issues/5282#issuecomment-296510181)?

**Comment by anandolee** [comment]
Sorry, I can't tell anything from the stack trace... @amauryfa, do you have any idea?

**Comment by catskul** [comment]
seeing the same in gazebo

**Comment by anandolee** [comment]
3.4 is too old, wondering if it still an issue for our new version?
