### ISSUE TITLE
Migrate protobuf to use Abseil: Google C++ common libraries.

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#3688]
For a long time protobuf has been keeping its own fork of Google C++ common libraries under the stubs directory:
https://github.com/google/protobuf/tree/master/src/google/protobuf/stubs

They have to be forked because Google never released these common libraries as an opensource project, util now:
https://opensource.googleblog.com/2017/09/introducing-abseil-new-common-libraries.html

With the release of Abseil, we should be able to deprecate code in the stubs directory and migrate protobuf to use Abseil instead.

**Comment by mcy** [comment]
This is already fixed in trunk, and will be part of our next major release!
