### ISSUE TITLE
Protobuf docker image

### ISSUE THREAD

**Issue by vaibhavsood** [protocolbuffers/protobuf#3726]
Hi,

Want to check if there is a docker image/Dockerfile for protobuf which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official protobuf image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by TeBoring** [comment]
What's your planned use of this image?

**Comment by vaibhavsood** [comment]
My interest right now is to first check if it makes sense to have protobuf as a docker official image (steps for doing the same are in the link posted in my previous comment)

If that happens, the image comes under Docker's "official" image program, they then take over the daily builds etc, it gets published under https://hub.docker.com/explore/ - however the maintainence is to be done by upstream

Also the image can also be made multi-arch (for platforms it supports) via Docker's multi-arch framework

**Comment by TeBoring** [comment]
If user want to use other software together with protobuf, do they write additional docker file based on the proposed protobuf image? Or there is some easy way to combine different docker image? (e.g., if user want to use both python and protobuf, he just combine python official image and protobuf official image)

**Comment by vaibhavsood** [comment]
I guess having a single dockerfile with compilers for the different languages installed may be a better option? I am not sure/aware of combining different docker images (the way you mentioned, kubernetes may be an option but not sure)

This is a github repo which dockerizes protobuf in a single dockerfile https://github.com/znly/docker-protobuf , maybe could do something similar

**Comment by yunspace** [comment]
@TeBoring if you want to use different software you can compose them together via docker-compose. So for your example it would look something like:

```
version: '3.4'
service
  python:
    image: python
    volumes:
...
  protobuf:
    image: google/protobuf
    volumes:
....
```

**Comment by xfxyjwf** [comment]
@yunspace What if the images are compatible?

**Comment by yunspace** [comment]
@xfxyjwf sorry I'm not sure what you mean. Not compatible with what? 

In the above example you use python to build python and you use protobuf to build protobuf. It's basic composition over inheritance. If the official images aren't sufficient, you can always create your own images, such as `xfxyjwf/protobuf`. I have a full example here: https://github.com/serverlesscloud/musketeers-lambda-go-sls/blob/master/docker-compose.yml

**Comment by TeBoring** [comment]
@lukebakken's proposal makes more sense to me. I think users should base on central repositories (e.g., apt-get or maven) to install protoc. Because Docker can only inherit from one base Dokerfile, if users have different combination of software to use, providing a Dock image for protoc alone doesn't work.
