### ISSUE TITLE
"missing-noescape" when building Objective-C library with latest clang

### ISSUE THREAD

**Issue by jyaif** [protocolbuffers/protobuf#3759]
Clang recently introduced the "missing-noescape" warning. This results in a new warning that prevents from building the Objective-C library:

/third_party/protobuf/objectivec/GPBArray.m:2540:82: error: parameter of overriding method should be annotated with __attribute__((noescape)) [-Werror,-Wmissing-noescape]
- (void)enumerateObjectsUsingBlock:(void (^)(id obj, NSUInteger idx, BOOL *stop))block {

**Comment by thomasvl** [comment]
Just confirming, which Xcode are you using?  9.0 or a prerelease?  Are you building from cocoapods or manually adding sources and enabling this warning?

**Comment by jyaif** [comment]
Hi,
The context is Chrome for iOS, which you might be familiar with :-)
Here's what we are doing special:
-We are manually adding the sources
-We are building with all warnings treated as errors
-We are using ToT clang ( which is newer than the clang that ships in Xcode 9.1 beta 2 ).

**Comment by sergiocampama** [comment]
Since this isn't in current release (9.0.1) or the latest beta (9.1b2), we will hold off on making changes.

Could you add the `-Wnomissing-noescape` flag in the mean time?

**Comment by jyaif** [comment]
Yes, that was the elected workaround.

**Comment by sergiocampama** [comment]
As of Xcode 9.2, clang does not understand this flag.

**Comment by jyaif** [comment]
Thanks for the update!

**Comment by thomasvl** [comment]
@sergiocampama do you want to double check this again with Xcode 9.4.x and 10? Assuming it is supported now, we might need some preprocessor shims to ensure we still build with older Xcodes.

**Comment by thomasvl** [comment]
#4729 added the missing annotation for this, and opening the Xcode project in Xcode 10.1 shows the warning defaults to on, so we should be covered going forward if any other block api is added to the library.
