### ISSUE TITLE
Using ~ in the path of a plugin fails with incorrect error message.

### ISSUE THREAD

**Issue by jcanizales** [protocolbuffers/protobuf#381]
When invoking protoc with the `--plugin` flag, the path apparently cannot use `~` (even if bash will autocomplete the command line without issue when typing it). The error message produced is:

`~/path/to/my/plugin: program not found or is not executable`

Using the absolute path works alright.

Protoc should either expand `~`, or detect it and inform in the error message that the user should expand it manually.

**Comment by elharo** [comment]
not high enough priority, workarounds available
