### ISSUE TITLE
[Python] Preserving dictionary order w/ json_format.ParseDict

### ISSUE THREAD

**Issue by MrSaints** [protocolbuffers/protobuf#3848]
When using `json_format.ParseDict(.., Value())`, the original order of a dictionary (even an `OrderedDict`) does not appear to be preserved. Calling `json_format.MessageToJson(..)` on the resulting protobuf message will return a result with undeterministic ordering. Calling `ListFields()` on the output returns the keys, and values in alphabetical order.

I was wondering if there was a way to "parse" a generic dictionary into a `Value` while preserving the order? 

> Wire format ordering and map iteration ordering of map values is undefined, so you cannot rely on your map items being in a particular order.

**Comment by MrSaints** [comment]
If anyone is interested, I managed to apply a quick monkey patching solution inspired by a [blog post](https://havoc.io/post/deterministic-protobuf/). 

1. Create a new `Value` message based on the [original one](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto#L63):

```
message Value {
    oneof kind {
        NullValue null_value = 1;
        double number_value = 2;
        string string_value = 3;
        bool bool_value = 4;
        StableStruct struct_value = 5;
        ListValue list_value = 6;
    }
}
```

But instead of a `Struct` message that uses a `map`...

2. Create the a message to store a list of messages containing a key, and value field:

```
message StableStruct {
    repeated StableStructValue fields = 1;
}

message StableStructValue {
    string key = 1;
    Value value = 2;
}
```

3. Generate the code

4. Extend `_WKTJSONMETHODS`, `_Parser`, and `_Printer`. For example:

```
class CustomParser(_Parser):
    def _ConvertStableStructMessage(self, value, message):
        if not isinstance(value, dict):
            raise ParseError(
                'StableStruct must be in a dict which is {0}.'.format(value))
        for key in value:
            stable_struct_value = message.fields.add()
            stable_struct_value.key = key
            self._ConvertValueMessageWithStableStruct(
                value[key], stable_struct_value.value)
        return

class CustomPrinter(_Printer):
    def _StableStructMessageToJsonObject(self, message):
        fields = message.fields
        ret = collections.OrderedDict()
        for v in fields:
            ret[v.key] = self._ValueMessageToJsonObject(v.value)
        return ret
```

You will have to add support for the custom `Value`, `StableStruct`, and potentially `ListValue` (if you choose to implement / use your own) in `_WKTJSONMETHODS`.

For example:

```
_WKTJSONMETHODS["elr.proto.StableStruct"] = [
    '_StableStructMessageToJsonObject', '_ConvertStableStructMessage'
]
```

For the custom `Value`, you can re-use the `_ValueMessageToJsonObject`, but you need to create a custom `_ConvertValueMessage`. For example:

```
    def _ConvertValueMessageWithStableStruct(self, value, message):
        if isinstance(value, dict):
            self._ConvertStableStructMessage(value, message.struct_value)
        elif isinstance(value, list):
            self._ConvertListValueMessageWithStableStruct(
                value, message.list_value)
        else:
            self._ConvertValueMessage(value, message)
```

5. Write your own `ParseDict`, and `MessageToDict` that uses your own parser.

**Comment by anandolee** [comment]
I think use a patch on your project make sense. To Preserving dictionary order may get a approval and implemented in all our supported languages.
