### ISSUE TITLE
protobuf 3.4 fails to deserialise StringValue (retains length in deserialized string)

### ISSUE THREAD

**Issue by calhamdower** [protocolbuffers/protobuf#3852]
When utilizing GRPC and sending a StringValue message inside a map(string, any) the StringValue result contains the length as a prefix to the resultant string.

The problem here is something to do with the FromString function of the compiled protobuf. 

 found this issue when utilizing TensorflowServing. Using the bazel built python protos to deserialize these grpc messages works fine. 
With the same server (same recieved message, as I checked the code proto binary) utilizing the pip package protobuf: the FromString function adds the length to the 

Raw Protobuf:
`\n\x0b\n\x05mnist\x12\x02\x08\x01\x12\xaa\x03\n\x16preprocessing_settings\x12\x8f\x03\n/type.googleapis.com/google.protobuf.StringValue\x12\xdb\x02\n\xd8\x02some crazyy lines....`

FromString good:
```
model_spec {
  name: "mnist"
  version {
    value: 1
  }
}
metadata {
  key: "preprocessing_settings"
  value {
    [type.googleapis.com/google.protobuf.StringValue] {
      value: "some crazyy lines
```
FromString bad: 
```
model_spec {
  name: "mnist"
  version {
    value: 1
  }
}
metadata {
  key: "preprocessing_settings"
  value {
    [type.googleapis.com/google.protobuf.StringValue] {
      value: "/n/330/02some crazyy lines
```

What seems to be happening is that the compiled protobuf for the messages is using a different version of _descriptor. The pip related version is not mapping in decoders properly (but I don't really know)

The version of protobuf that bazel pulls causes the compiled message to have decoder tags, whereas the pip pulled protobuf does not. 

I do not know what version of protobuf tensorflow pulls as it pulls it from some bazel mirror??

**Comment by pherl** [comment]
Hmm, but the descriptor of StringValue has been changed. It seems like a bug that we put the length as part of the string value. Is the broken implementation from pip or bazel?

**Comment by anandolee** [comment]
I am unable to reproduce the error. Tried to  Serialize and Deserialize an Any message, but result is correct:
    msg = any_test_pb2.TestAny()
    all_types = unittest_pb2.TestAllTypes()
    all_types.repeated_string.append("Add a string')
    msg.value.Pack(all_types)
    other_msg = any_test_pb2.TestAny()
    other_msg.ParseFromString(msg.SerializeToString())
    self.assertEqual(msg, other_msg)

Are you able to create a small test to reproduce the error?

**Comment by calhamdower** [comment]
Its quite difficult as it happens in a relatively niche scenario for me. Ill try to see if I can snip out some relevant components and attach them to the thread. 
the proto that it occurs with is:
[get model metadata response](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/get_model_metadata.proto) where the any in the response is the StringValue.

The problem is with the pip protobuf, as opposed to the bazel based compiled protobuf.

**Comment by calhamdower** [comment]
[protobuf_string_value.zip](https://github.com/google/protobuf/files/1455758/protobuf_string_value.zip)

1) run the test file. It should give the length. This is with the bazel protobuf libraries
2) rename the google folder so that it imports your pip installed protobuf 

1 should result in correct behavior
2 should (using 3.4) result in the message length being added to the string

I believe that its something to do with the way they parse the tags... but I'm really not sure. It could be something completely unrelated altogether.

**Comment by marko-fejzo** [comment]
Any updates on this? Recently ran into the same issue.

**Comment by fowles** [comment]
3.4 is a very old release.  Is this still an issue on 3.17?

**Comment by anandolee** [comment]
Close it as there's no response for a long time and 3.4 is too old.
Feel free to reopen if it is still an issue for our new versions
