### ISSUE TITLE
PHP: Notice when serializing to JSON, output stream doesn't have enough buffer

### ISSUE THREAD

**Issue by francislavoie** [protocolbuffers/protobuf#3855]
```
PHP Notice:  Output stream doesn't have enough buffer. in /vendor/google/protobuf/php/src/Google/Protobuf/Internal/CodedOutputStream.php on line 92
```

I'm serializing some binary data, i.e. result of `hash('sha256', $data, true)`. I think the `jsonByteSize()` helper might not be taking into account the translation to base64. That's my best guess. 

My `.proto` definition looks like this (where `Type` is an enum):

```proto
message List {
    uint32 version = 1;
    repeated Pair data = 2;
}

message Pair {
    Type type = 1;
    bytes hash = 2;
}
```

I fill this list up with a bunch of pairs, where the hashes are just `hash('sha256', $data, true)`, so 32 raw bytes, then just doing `echo $list->serializeToJsonString();` gets me the above notice.

The printed JSON is invalid as well, because the last hash being written into the JSON is just missing. Not even an empty string. The following is the ending portion of the JSON.

[...]`,"hash":"Fo+\/hPIjMw0MPhZHPNuCbcY61skNaXD6WrY8Fb7NApk="},{"type":"THREE","hash":}]}`

As you can see there's just a colon with no value.

**Comment by francislavoie** [comment]
@TeBoring I wanted to mention this was with 3.4.0, _not_ using C extension.

**Comment by TeBoring** [comment]
What's the content of ```$data```?

**Comment by francislavoie** [comment]
That shouldn't matter, the result is always a 32 byte binary string.

**Comment by francislavoie** [comment]
I'm no longer maintaining the code in which this was used, so I can't really help much more. Like I said above, this was on 3.4.0, maybe that code was changed since then to fix it?

**Comment by TeBoring** [comment]
I am not sure because I have never reproduced your bug. It would be best if there is a working test to reproduce the bug.

**Comment by jet6666** [comment]
sometimes this caused by illegal data.
such as :
PB description:
int32 coin =1 ;

But your data is :

array('coin' => 111111058676 ) ;

this will cause this error

**Comment by fowles** [comment]
Closing out old issues.  Please reopen if this still occurs on recent releases.
