### ISSUE TITLE
[Python] Incoherent behavior with and without the C++ implementation for bool fields

### ISSUE THREAD

**Issue by rsebille** [protocolbuffers/protobuf#3857]
Hello,

When reverting back from using the C++ implementation with found a discrepancy.
If the library is build with the flag then the value is properly cast, but without the flag there is no cast happening.

With the C++ implementation:
```
In [1]: from test import my_message_pb2

In [2]: msg = my_message_pb2.Message()

In [3]: msg.bool_field
Out[3]: False

In [4]: msg.bool_field = 1

In [5]: msg.bool_field
Out[5]: True
```

Without the implementation:
```
In [1]: from test import my_message_pb2

In [2]: msg = my_message_pb2.Message()

In [3]: msg.bool_field
Out[3]: False

In [4]: msg.bool_field = 1

In [5]: msg.bool_value
Out[5]: 1
```

The C++ implementation's behavior is the right and expected one but the Python implementation should behave identically.

What you're take on this?

**Comment by elharo** [comment]
Line 5 is different in the two cases, msg.bool_field vs msg.bool_value. I'm guessing that's why this looks different.
