### ISSUE TITLE
Escape argument/attribute name collides Python reserved keyword

### ISSUE THREAD

**Issue by iwaseyusuke** [protocolbuffers/protobuf#3871]
The similar to https://github.com/google/protobuf/issues/65;

I asked the same on "grpc/grpc" project and they recommended me to request on "protobuf" project side; https://github.com/grpc/grpc/issues/13318

---

Version of protoc and plugins;
```
$ protoc --version
libprotoc 3.4.0
$ pip show grpcio
Name: grpcio
Version: 1.7.0
...(snip)...
 $ pip show grpcio-tools
Name: grpcio-tools
Version: 1.7.0
...(snip)...
```

OS: Linux Ubuntu 16.04 LTS
 
Runtime and compiler:
 ```bash
$ python --version
Python 3.5.2
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 ```

I'm trying to send a message from gRPC client written in Python and the message is like:
```protobuf
message TestMessage {
  bool global = 1;
  uint32 as = 2;
}
```

The gRPC server is written in Go, `global` and `as` does not collides the reserved keywords, but on Python, these variable name clash with reserved keywords.
Then, I couldn't create the above message with keyword arguments and couldn't access these attributes:

```python
# couldn't create message with keyword arguments
msg = xxx_pb2.TestMessage(
    global=True,  # Here raises syntax error
    as=100,
)
# required to pass arguments like
kwargs = {
    'global': True,
    'as': 100,
}
msg= xxx_pb2.TestMessage(**kwargs)

# Also couldn't access these attributes
print(msg.global)  # Here raises syntax error
# required to use getattr() like
print(getattr(msg, 'global'))
```

### Request

[pep8](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) says "If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore", so I want to pass arguments appending "_" like:
```python
msg = xxx_pb2.TestMessage(
    global_=True,
    as_=100,
)
```
and also access attribute like:
```python
print(msg.global_)
```

What do think about it? Does anyone know better workaround?

---

The answer of "#65" recommended to rename the field, but ".proto" is defined on the server side (Go implemented and out of our project), so difficult to rename it.

**Comment by gpshead** [comment]
FWIW, people also hit this problem internally at Google with field names such as "import" or other keywords in an occasional message.  I believe `getattr` and `setattr` on your message instance should work for these field names.

```python
global_, as_ = getattr(msg, 'global'), getattr(msg, 'as')
```

Otherwise, agreed, surfacing them as trailing underscore attribute names seems desirable - though the implications on which names APIs such as `ListFields` returns and `HasField` requires need to not break existing users.

**Comment by iwaseyusuke** [comment]
Thanks for your reply!
I don't know the internal implementation though, I just guess it might be able to represent with trailing underscore by using `__getattr__` for example.
e.g., If user tries to access a field with trailing underscore and that name collides the reserved keyword, remove trailing underscore then use it as real-name of the protobuf field.
This approach does not take effect to the APIs such as `ListFields` and `HasField` because this does not changes the "real" field names in the descriptor.

**Comment by anandolee** [comment]
getattr() can work with field that have name conflict with keyword. We are also working on make messages, top level enum, top level extensions also work with getattr() for keyword conflict
