### ISSUE TITLE
Any plans to modularize (or add Automatic-Module-Name properties to) protobuf-java?

### ISSUE THREAD

**Issue by io7m** [protocolbuffers/protobuf#3903]
Hello.

In order to play nicely with programs/libraries that have been modularized, it would be good if `Automatic-Module-Name` properties could be added to the `protobuf-java` jar files. This would give a stable name that can be used in the `requires` directives of modules.

http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

> Do not release to Maven Central a modular jar file that depends on an automatic module, unless the automatic module has an "Automatic-Module-Name" MANIFEST.MF entry.

I'd submit a PR, but I'm not sure what module names you'd want to use. Presumably something like `com.google.protobuf.core` and `com.google.protobuf.lite`.

**Comment by DJViking** [comment]
This is a very much needed change. Currently google protobuf is the only dependency we use that still has not been modularized.

**Comment by io7m** [comment]
Thank you!

**Comment by DJViking** [comment]
Adding Automatic-Module-Name is a step in the right direction. Fully modularize protobuf-java would be the next step.
A drastic shift was recently done for C++ when it moved to C++11, why not also shift Java towards Java LTS 11.
