### ISSUE TITLE
Go output with grpc plugin in super-directory doesn't work

### ISSUE THREAD

**Issue by Xjs** [protocolbuffers/protobuf#3924]
On Windows 10, `protoc --go_out=plugins=grpc:../output input.proto` doesn't work (even if `../output` directory exists). Error message:

```plugins=grpc;..\output/: No such file or directory```

`protoc --go_out=plugins=grpc:output input.proto` and even `protoc --go_out=plugins=grpc:./output input.proto` do work (with existing `./output` directory of course).

I'm not sure if this issue is correctly placed here, or rather in https://github.com/grpc/grpc or in https://github.com/golang/protobuf.

**Comment by mkruskal-google** [comment]
Closing this since go has been split to its own repo
