### ISSUE TITLE
proto3 => json docs don't include a serialized oneof field

### ISSUE THREAD

**Issue by achew22** [protocolbuffers/protobuf#3928]
It would be nice if there was an example of a proto that had a oneof field being JSON serialized.

https://developers.google.com/protocol-buffers/docs/proto3

**Comment by tonicsoft** [comment]
+1

**Comment by TeBoring** [comment]
Why specifically ask for oneof field?
Isn't it just the same as an optional field?

**Comment by TeBoring** [comment]
Close this for cleanup. Free feel to reopen if this is still needed.

**Comment by jiuyangzhao** [comment]
People got confused because there are multiple ways to represent it in json. [ref](https://stackoverflow.com/questions/44069789/what-is-the-expected-json-serialization-of-oneof-protobuf-field)

**Comment by vnayar** [comment]
I would like this issue looked at as well. `optional` exists in proto2 but in proto3 it does not exist. If the documentation had a small example, it would speed things up for developers who essentially have to write a small program or go through parser code to figure out what happens.
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by dsmith-divisionsinc** [comment]
Can we *please* have this explicitly stated in the spec?  It would help to settle a lot of bike-shedding debates on my team over how JSON should be formatted.

**Comment by vnayar** [comment]
> Can we please have this explicitly stated in the spec? It would help to settle a lot of bike-shedding debates on my team over how JSON should be formatted.

Since this issue was last discussed, I noticed that there's a new website containing the protobuf documentation. It doesn't give an explicit example of `oneof` being serialized into JSON, however, it does give enough information to infer how it behaves.

https://protobuf.dev/programming-guides/proto3/#oneof

> Oneof fields are like regular fields except all the fields in a oneof share memory, and at most one field can be set at the same time.
> Move fields into or out of a oneof: You may lose some of your information (some fields will be cleared) after the message is serialized and parsed. However, you can safely move a single field into a new oneof and may be able to move multiple fields if it is known that only one is ever set. See [Updating A Message Type](https://protobuf.dev/programming-guides/proto3/#updating) for further details.

The fact that an existing field can safely be moved into a `oneof` without creating parsing errors implies that it must have the same JSON representation, e.g. the following two messages must have the same JSON format:

```
message A {
  string a = 1;
  int32 b = 2;
}

message B {
  string a = 1;
  oneof test_oneof {
    int32 b = 2;
  }
}
```
