### ISSUE TITLE
Attribute types are not always kept when serializing/deserializing

### ISSUE THREAD

**Issue by jleni** [protocolbuffers/protobuf#3954]
Protobuf validates that attributes with type `bytes` cannot be assigned `bytearray`, however, when parsing this is not respected and types change and are incorrect.

The following unit tests shows the problem. While it is correctly not accepting bytearray, if the value is restored from a buffer with type bytearray, the attribute adopts that type instead of the expected `bytes`

This bug results in inconsistent behavior and odd type exceptions when moving that between data between protobuf objects in python.

```
import unittest
from unittest import TestCase

from bug_pb2 import Foo

"""
syntax = "proto3";

package repro_bug;

message Foo
{
    bytes bar = 1;
}
"""


class TestBytearrayBug(TestCase):

    def test_stable_type(self):
        foo = Foo(bar=bytes(b'test'))
        self.assertIsInstance(foo.bar, bytes)

        with self.assertRaises(TypeError):
            invalid_foo = Foo(bar=bytearray(b'should_fail'))

        data = foo.SerializeToString()
        self.assertIsInstance(data, bytes)

        data_array = bytearray(data)
        foo.ParseFromString(data_array)
        self.assertIsInstance(foo.bar, bytes)


if __name__ == '__main__':
    unittest.main()
```

**Comment by jleni** [comment]
I have a working fix. I will submit a PR in the next hour.

**Comment by anandolee** [comment]
Close it because PR #3956 was closed. Feel free to reopen if still needed
