### ISSUE TITLE
[python] well known types lacks of rich comparison

### ISSUE THREAD

**Issue by cuonglm** [protocolbuffers/protobuf#3965]
Take a look at [well_known_types.py](https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types.py), most of them lacks of rich comparison method. So writing it the idiom way in Python can cause confusion. Example:

```
In [1]: from google.protobuf import timestamp_pb2

In [2]: bool(timestamp_pb2.Timestamp())
Out[2]: True
```

always give `True`, causing this code:
```
t = timestamp_pb2.Timestamp()
if not t:
    print 't is empty message'
```

does not print as expected.

While:

```
In [1]: from google.protobuf import struct_pb2

In [2]: bool(struct_pb2.Struct())
Out[2]: False
```

always give `False` (`Struct` has its own [\_\_len\_\_\(\)](https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types.py#L748)).

And also:

```
In [1]: from google.protobuf import timestamp_pb2

In [2]: t = timestamp_pb2.Timestamp()

In [3]: now = timestamp_pb2.Timestamp()

In [4]: now.GetCurrentTime()

In [5]: s = timestamp_pb2.Timestamp()

In [6]: now > t
Out[6]: False

In [7]: now > s
Out[7]: True
```

is not consistent, because `Timestamp` lacks all of rich comparison methods.

**Comment by anandolee** [comment]
Close it as the related PR #3965 is closed. Feel free to reopen if it is still needed
