### ISSUE TITLE
Allow specifying both --proto_path and --descriptor_set_in

### ISSUE THREAD

**Issue by djudd-stripe** [protocolbuffers/protobuf#3973]
Feature request: protoc should allow specifying both `--proto_path` and `--descriptor_set_in`. Two use cases: 
* A dependency provides a descriptor_set_in, but not .proto files, and I'd like to use that to compile some .proto files which import schemas from the descriptor set but also depend on each other. This arises, e.g., when using a Bazel `proto_library` output as a dependency, but in a project that itself doesn't use Bazel, so we can't rely on Bazel's dependency resolution.
* `proto_path` allows you to rename a .proto on import (by setting `--proto_path=foo.proto=my_prefix.foo.proto` etc). It would be great to have that capability when using descriptor set inputs, too.

**Comment by gerben-s** [comment]
On the scale of things this has low priority from our team. But we welcome patches.
