### ISSUE TITLE
PHP: json_name honored in pure-php impl, ignored in C extension

### ISSUE THREAD

**Issue by arnaud-lb** [protocolbuffers/protobuf#3974]
When using the `json_name` option to control the name of serialized attributes, the pure-PHP implementation of protobuf works as expected. However the C extension ignores the option completely.

``` protobuf
// test.prot

syntax="proto3";

message Foo {
    int32 foo = 1 [json_name="bar"];
}
```

``` php
<?php

// test.php

require "vendor/autoload.php";

$foo = new Foo();
$foo->setFoo(42);

echo $foo->serializeToJsonString(), "\n";
```

``` sh
$ protoc --php_out=. test.proto
$ php test.php
{"bar":42} # ok
$ php -dextension=protobuf.so test.php
{"foo":42} # not ok with extension
```

**Comment by TeBoring** [comment]
This is a known issue in c extension. Currently, we haven't fixed all conformance test for c extension. Will do it gradually.

**Comment by Mailerm** [comment]
whitch version will support?

**Comment by haberman** [comment]
This should be fixed, json name is properly supported in the C extension now.
