### ISSUE TITLE
[python] Add option to format Enums as integers in MessageToDict/MessageToJson

### ISSUE THREAD

**Issue by romannekhor** [protocolbuffers/protobuf#3983]
Hi,
JSON formatter for C# has option called `FormatEnumsAsIntegers` (pull request #2884 has added it). Golang's `jsonpb` also has a similar option, it's called `EnumsAsInts` (link: https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler).
C++ `JsonPrintOptions` has `always_print_enums_as_ints ` flag too.

**What do you think about adding a similar option for Python?**

Here is my proposal of how it might look like for users:
```python
# ... google/protobuf/json_format.py
def MessageToDict(message,
                  including_default_value_fields=False,
                  preserving_proto_field_name=False,
                  format_enums_as_integers=False):  # <--- new argument
```
```python
# ... google/protobuf/json_format.py
def MessageToJson(message,
                  including_default_value_fields=False,
                  preserving_proto_field_name=False,
                  format_enums_as_integers=False): # <--- new argument
```

I'll be glad to work on the implementation if you like the idea.

Thanks!

**Comment by sviterok** [comment]
@xfxyjwf hm.. I don't think that the label is right. We should probably change it from `c#` to `python`.

**Comment by saldin** [comment]
i meet same problem

**Comment by Faendrek** [comment]
This has been implemented: https://github.com/protocolbuffers/protobuf/blob/9e69594adfac8157917de97601343c48abb108bd/python/google/protobuf/json_format.py#L133
