### ISSUE TITLE
[Feature Request] Allow custom namespace to avoid protobuf version/linking conflicts

### ISSUE THREAD

**Issue by wonson** [protocolbuffers/protobuf#4004]
There are constantly some problems about linking multiple protobuf. 
For example, 
Using Qt shared lib (Having system protobuf dependency) in Ubuntu conflicts the specified linked protobuf binary in your own project (not working well neither same version or different version).

In my case with 2.6.1 version, i found that replacing the `namespace google ` and `google::` to a custom namespace can already solve this issue well, especially if the compiled binary is not intended to be shared but using only in your own lib/app.

So, maybe you guys can add a configure option to rename/add a layer of namespace to solve this perfectly, and also be able to remove the restriction of "Cannot link 2 protobuf in one app"?

**Comment by xfxyjwf** [comment]
We generally don't want to add new options especially those that can alter public APIs. For this case allowing multiple versions of protobuf in the same binary is not a supported use case of protobuf so that's even less reason to add an option for it.

My understanding is that linking multiple versions of the same shared lib is not a common practice and I would suggest you use the same version of protobuf as your dependencies use instead.

**Comment by wonson** [comment]
Okay, but we have reasons about not linking the same binary of the shared lib.

1. We have to ensure the backward compatibility of our app. I'm not sure if it is a wise decision to make protobuf version depends on other shared lib;
2. In fact, we are developing an app for a variety of linux distro. However, while we are linking the same binary of protobuf, we only encounter the linking-conflict related crash on Ubuntu with Qt or some other shared lib. Therefore, it seems the shared lib is already have different dependency of protobuf.

I guess it is okay to use another namespace, as if I change the namespace, the binary would be a different set of APIs and global vars of protobuf. I think that's the simplest way for the problem I encountered.

Anyway, it's okay for you guys not to add that option. I solved my problems anyway :P Just Let the issue for keeping a record and let others know there is a way for this headachy problem.

**Comment by swfxliyiyu** [comment]
I have the same problem. May I have your email address?

**Comment by TeBoring** [comment]
close this for clean up

**Comment by takacsd** [comment]
I would really love to reopen this issue.
I just tried to move our protobuf 3 dependent project to Android and it dies because some OpenGL related library using protobuf 2 internally. So using the same version is not really an option.

**Comment by wz19821124** [comment]
hi wonson:
may i have your email address? thanks
i also encounter this problem, then i rename the namespce from protobuf to protobuf3 (rename namespace google failed too) using follow command under src:
sed -i "s/google::protobuf/google::protobuf3/g" `grep google::protobuf -rl ./`
sed -i "s/google\.protobuf\./google\.protobuf3\./g" `grep google\.protobuf\. -rl ./`
sed -i "s/namespace protobuf /namespace protobuf3 /g" `grep "namespace protobuf " -rl ./`
sed -i "s/protobuf::/protobuf3::/g" `grep "protobuf::" -rl ./`
buf make failed, the error information as below:
libtool: link: ( cd ".libs" && rm -f "libprotoc.la" && ln -s "../libprotoc.la" "libprotoc.la" )
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -pthread -DHAVE_PTHREAD=1  -Wall -Wno-sign-compare -O2 -g -DNDEBUG -pthread  -o protoc google/protobuf/compiler/main.o -lpthread libprotobuf.la libprotoc.la
libtool: link: g++ -std=c++11 -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -pthread -o .libs/protoc google/protobuf/compiler/main.o  ./.libs/libprotobuf.so ./.libs/libprotoc.so /root/tools/protobuf_bak/protobuf-3.5.1/src/.libs/libprotobuf.so -lpthread -pthread -Wl,-rpath -Wl,/usr/local/lib
oldpwd=`pwd` && ( cd . && $oldpwd/protoc -I. --cpp_out=$oldpwd google/protobuf/any_test.proto google/protobuf/compiler/cpp/cpp_test_bad_identifiers.proto google/protobuf/map_lite_unittest.proto google/protobuf/map_proto2_unittest.proto google/protobuf/map_unittest.proto google/protobuf/unittest_arena.proto google/protobuf/unittest_custom_options.proto google/protobuf/unittest_drop_unknown_fields.proto google/protobuf/unittest_embed_optimize_for.proto google/protobuf/unittest_empty.proto google/protobuf/unittest_enormous_descriptor.proto google/protobuf/unittest_import_lite.proto google/protobuf/unittest_import.proto google/protobuf/unittest_import_public_lite.proto google/protobuf/unittest_import_public.proto google/protobuf/unittest_lazy_dependencies.proto google/protobuf/unittest_lazy_dependencies_custom_option.proto google/protobuf/unittest_lazy_dependencies_enum.proto google/protobuf/unittest_lite_imports_nonlite.proto google/protobuf/unittest_lite.proto google/protobuf/unittest_mset.proto google/protobuf/unittest_mset_wire_format.proto google/protobuf/unittest_no_arena_lite.proto google/protobuf/unittest_no_arena_import.proto google/protobuf/unittest_no_arena.proto google/protobuf/unittest_no_field_presence.proto google/protobuf/unittest_no_generic_services.proto google/protobuf/unittest_optimize_for.proto google/protobuf/unittest_preserve_unknown_enum2.proto google/protobuf/unittest_preserve_unknown_enum.proto google/protobuf/unittest.proto google/protobuf/unittest_proto3_arena.proto google/protobuf/unittest_proto3_arena_lite.proto google/protobuf/unittest_proto3_lite.proto google/protobuf/unittest_well_known_types.proto google/protobuf/util/internal/testdata/anys.proto google/protobuf/util/internal/testdata/books.proto google/protobuf/util/internal/testdata/default_value.proto google/protobuf/util/internal/testdata/default_value_test.proto google/protobuf/util/internal/testdata/field_mask.proto google/protobuf/util/internal/testdata/maps.proto google/protobuf/util/internal/testdata/oneofs.proto google/protobuf/util/internal/testdata/proto3.proto google/protobuf/util/internal/testdata/struct.proto google/protobuf/util/internal/testdata/timestamp_duration.proto google/protobuf/util/internal/testdata/wrappers.proto google/protobuf/util/json_format_proto3.proto google/protobuf/util/message_differencer_unittest.proto google/protobuf/compiler/cpp/cpp_test_large_enum_value.proto )
[libprotobuf ERROR google/protobuf/descriptor_database.cc:318] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1394] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf3::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):

**Comment by sighingnow** [comment]
Agree with @wonson, `s/namespace google/namespace googlepb/g` and `s/google::/googlepb::` could solve the issue, but it would be nice if we could have such options for users.

It also affects some realworld applications, e.g., https://github.com/tensorflow/tensorflow/issues/24976, https://github.com/protocolbuffers/protobuf/issues/6074, it is really bad.

As many python applications starts to link a protobuf shared library, and such conflict becomes common in nowdays. I would like to see if there any chance to implement such features.

Another similar case is, assume we have problem `A`, and shared library `B`, `A` and `B` both link protobuf (may different version, or same version but different `RPATH`), and `A` `dlopen` `B` at runtime, in such cases we have no way to resolve the conflicit.

**Comment by dudutudou** [comment]
> I would really love to reopen this issue. I just tried to move our protobuf 3 dependent project to Android and it dies because some OpenGL related library using protobuf 2 internally. So using the same version is not really an option.
> 
> EDIT: Solved the issue by not exporting the protobuf related symbols from my library (protobuf was statically linked) with ld linker script. Hope this helps others.

Hi Thanks for your information, I'm really intreasted in how do you remove the protobuf related sysbols from your library?

**Comment by wonson** [comment]
> > I would really love to reopen this issue. I just tried to move our protobuf 3 dependent project to Android and it dies because some OpenGL related library using protobuf 2 internally. So using the same version is not really an option.
> > EDIT: Solved the issue by not exporting the protobuf related symbols from my library (protobuf was statically linked) with ld linker script. Hope this helps others.
> 
> Hi Thanks for your information, I'm really intreasted in how do you remove the protobuf related sysbols from your library?

(My guess)
static link, which is something like build the linked library (aka protobuf in this case) into the binary of "your-library". 
If "your-library" did not intentionally export the symbols, those protobuf symbol would be internal inside "your-library", and not visible to other linked stuffs.

**Comment by jcooper-korg** [comment]
@TeBoring - this is another vote to reopen!
another case where this is an issue is in plugin environments, like music software.  e.g. Avid ProTools uses protobuf in their own software.  When a music plugin (like korg wavestate native, which also uses protobuf) ) is loaded into ProTools, there will be two versions of protubuf code live at the same time. This has resulted in crashes (observed on macOS), when their protobuf libs are at different versions.  I don't totally understand why, as wavestate native statically links protobuf, and I guess ProTools also does.
we are considering whether we will have to fork protobuf, just so we can search/replace the namespace throughout, to avoid these conflicts.
Please advise!

**Comment by jcooper-korg** [comment]
Meanwhile.... here's a total hack:
I added a definition to our cmake project, which builds the protobuf library and the rest of our project, like this:
`add_compile_definitions(google=my_google_protobuf_3_19_2)`

This is equivalent to putting a `#define google my_google_protobuf_3_19_2` at the top of the project, and it replaces all occurrences of the `google` symbol with `my_google_protobuf_3_19_2`.  

Now, looking at the mangled names of the symbols in our executable, they are like:
```
N22my_google_protobuf_3_19_28protobuf11MessageLiteE
N22my_google_protobuf_3_19_28protobuf24ZeroCopyCodedInputStreamE
N22my_google_protobuf_3_19_28protobuf2io19ZeroCopyInputStreamE
```
etc.   

Not pretty, but at least I didn't have to fork the repo and search/replace the symbol everywhere.
