### ISSUE TITLE
decode to json from command line

### ISSUE THREAD

**Issue by KantarBruceAdams** [protocolbuffers/protobuf#4024]
**Bug:** The man page does not state what format is used by the _--decode_ and _--encode_ options
**Feature request:** Add an option to decode directly to json.

Looking for a way to decode a message into json from the command line I stumbled upon:

https://stackoverflow.com/questions/34952811/is-there-a-definitive-nix-command-line-tool-for-inspecting-protocol-buffers

which mentions the _--decode_ option which at first sight appears to be just what I was looking for.
However the output format is not in fact json but something called "_text format_" which is undocumented (see https://github.com/google/protobuf/issues/3755).

My use case is that I am writing test cases to check the output of programs that send messages encoded using protocol buffers. I want to convert them to some format that can be analysed easily and add test assertions.
E.g.  

> ACTUAL=`protoc --decode .... | jq .getSomeField`      
> assertEqual "expected foo" "foo" "$ACTUAL"

**Comment by KantarBruceAdams** [comment]
note: I observed this on 3.5.0

**Comment by imranrazakhan** [comment]
Any update on this feature, is it available now? I couldn't find any option in 

```
#protoc --version
libprotoc 3.6.1
```
**Command:**
`protoc --decode=my.proto.PkgDiStatus controller.proto</tmp/di.bin`

Output:

output is not json

```
    ups_status {
      low_battery: false
      no_power_out: false
      replace_battery: false
      common_fault: false
    }
    testing_mode: false
```

**Comment by hq6** [comment]
Since this has been part of the API for a long time, but was never added to the `protoc` tool, I wrote my own wrapper for this functionality.

https://github.com/hq6/ProtobufJson

**Comment by sg-rs** [comment]
@hq6 Thank you very much. It works

**Comment by ChainSwordCS** [comment]
bump
