### ISSUE TITLE
Update developer guide C++/Java/Python tutorials to proto3

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#4035]
Right now the tutorials are still based on proto2. For example C++ tutorial:
https://developers.google.com/protocol-buffers/docs/cpptutorial

However the example code in the source code has been upgraded to proto3 already. We should migrate the docs to proto3 as well.

**Comment by alexmv** [comment]
I'd like to second this.  I'd happily contribute to updating it, but the documentation doesn't look to be on github currently -- do you have any way of taking pull requests or diffs for https://developers.google.com/protocol-buffers/docs/pythontutorial and similar docs?

**Comment by TeBoring** [comment]
@haon4 We probably need to separate this work?

**Comment by rolandcrosby-check** [comment]
@TeBoring or anyone else - just want to check if this is on anyone's radar. The docs on the Google Developers site (specifically the Python tutorial reference above) are not at all consistent with what's currently in this repo and will need significant rewrites to be of any use to Python developers hoping to learn about protocol buffers.

* The example `protoc` commands in the documentation are incomplete. The readme.txt file for `protoc` says to "copy the contents of the 'include' directory somewhere" to make the well known types like `google/protobuf/timestamp.proto` available. The protobuf compilation instructions in the documentation don't mention the requirement to specify this "somewhere" location when invoking `protoc`, so protobuf compilation using the example command will fail.
* Generated `_pb2.py` files can't be imported unless the `protobuf` Python package is installed, but there's no reference to this anywhere in the tutorial docs.
* Perhaps this is implied by the move from proto2 to proto3, but the description of the compiler output in the docs doesn't align with the current implementation. For example, [this section](https://developers.google.com/protocol-buffers/docs/pythontutorial#the-protocol-buffer-api) says that the generated `addressbook_pb2.py` file will contain some relatively human-readable classes using descriptors and so forth, but that's not at all what the output looks like if you use the protoc compiler today.

As far as I can tell there's not actually any documentation, at least for Python, that aligns with the examples in the `examples/` directory. Am I looking in the wrong place?
