### ISSUE TITLE
Build error using Intel compiler in generated_message_table_driven.h

### ISSUE THREAD

**Issue by neundorf** [protocolbuffers/protobuf#4069]
Hi, 
with the Intel C++ compiler (both versions 15.0 and 16.0.4) there is a compiler error in 
generated_message_table_driven.h:
generated_message_table_driven.h(186): error: static assertion failed with ""
      static_assert(std::is_pod<AuxillaryParseTableField>::value, "");

Commenting out that line makes it build, then the code looks like this:

```
if LANG_CXX11 && !defined(__NVCC__)
static_assert(sizeof(ParseTableField) <= 16, "ParseTableField is too large");
// The tables must be composed of POD components to ensure link-time
// initialization.
static_assert(std::is_pod<ParseTableField>::value, "");
//static_assert(std::is_pod<AuxillaryParseTableField>::value, "");     <---- this line is the problem
static_assert(std::is_pod<AuxillaryParseTableField::enum_aux>::value, "");
static_assert(std::is_pod<AuxillaryParseTableField::message_aux>::value, "");
static_assert(std::is_pod<AuxillaryParseTableField::string_aux>::value, "");
static_assert(std::is_pod<ParseTable>::value, "");
#endif

```

What's going wrong there ?

**Comment by neundorf** [comment]
The static_assert() does not fail if I comment out the additional ctors of AuxillaryParseTableField:

```
union AuxillaryParseTableField {

...

#if LANG_CXX11
  AuxillaryParseTableField() = default;
#else
  AuxillaryParseTableField() { }
#endif
/*   Commented out:
  PROTOBUF_CONSTEXPR AuxillaryParseTableField(
      AuxillaryParseTableField::enum_aux e) : enums(e) {}
  PROTOBUF_CONSTEXPR AuxillaryParseTableField(
      AuxillaryParseTableField::message_aux m) : messages(m) {}
  PROTOBUF_CONSTEXPR AuxillaryParseTableField(
      AuxillaryParseTableField::string_aux s) : strings(s) {}
  PROTOBUF_CONSTEXPR AuxillaryParseTableField(
      AuxillaryParseTableField::map_aux m)
      : maps(m) {}*/
};
```

**Comment by acozzette** [comment]
@neundorf It sounds like this is probably a bug with the Intel compiler, right? Do you want to send us a pull request that ifdefs out that static_assert when we are building with that compiler?

**Comment by neundorf** [comment]
I can create such a pull request tomorrow, but I'm quite new to C++11 stuff and so I don't know whether here is_pod() fails wrongly, or whether the fact that is_pod() is failing actually means that something won't work as it should.
What's a good way to verify everything is working correctly ?

**Comment by acozzette** [comment]
The table-driven code is an experimental feature that is not turned on by default, so I wouldn't worry about errors in that file. I can't remember offhand what the exact definition of POD is, but I'm guessing that the Intel compiler is wrong, because we've built this code with Clang and GCC without any problems. You could try commenting out that static_assert, and if all the tests pass then you could be reasonably sure that things are basically working.

**Comment by neundorf** [comment]
Ok.
Another stupid question: I'm used to projects with a cmake buildsystem, there I run "make test" and then the tests are executed.
How do I do that here ?

**Comment by neundorf** [comment]
One test failed:
```
[ RUN      ] DefaultFieldComparatorTest.FloatingPointComparisonTreatNaNsAsEqual
../../src/google/protobuf/util/field_comparator_test.cc:266: Failure
Value of: comparator_.Compare(message_1_, message_2_, field_float, -1, -1, __null)
  Actual: 0
Expected: FieldComparator::DIFFERENT
Which is: 1
../../src/google/protobuf/util/field_comparator_test.cc:269: Failure
Value of: comparator_.Compare(message_1_, message_2_, field_double, -1, -1, __null)
  Actual: 0
Expected: FieldComparator::DIFFERENT
Which is: 1
../../src/google/protobuf/util/field_comparator_test.cc:273: Failure
Value of: comparator_.Compare(message_1_, message_2_, field_float, -1, -1, __null)
  Actual: 0
Expected: FieldComparator::DIFFERENT
Which is: 1
../../src/google/protobuf/util/field_comparator_test.cc:276: Failure
Value of: comparator_.Compare(message_1_, message_2_, field_double, -1, -1, __null)
  Actual: 0
Expected: FieldComparator::DIFFERENT
Which is: 1
[  FAILED  ] DefaultFieldComparatorTest.FloatingPointComparisonTreatNaNsAsEqual (0 ms)
```

**Comment by acozzette** [comment]
About the inline and noinline error, I'm not sure what's going on but I would guess that the easiest solution would be to just disable the warning.

For the test failure, it seems that the Intel compiler treats NaNs as equal by default: https://stackoverflow.com/questions/32195949/why-does-nan-nan-0-0-with-the-intel-c-compiler According to that StackOverflow post, to get the more correct behavior you have to specify /fp:strict or /fp:precise. I'm not sure how to do that but I assume those are compiler options you can pass (I've never used the Intel compiler before).

**Comment by neundorf** [comment]
It's here:
https://github.com/google/protobuf/pull/4084

Do I really need a CLA for those two #ifdefs ?

**Comment by acozzette** [comment]
@neundorf Yes, we need the CLA even for small changes.

**Comment by neundorf** [comment]
This will take some time...

**Comment by BSBandme** [comment]
Closed for now for obsolete.
Feel free to reopen this if you still need to update this and feel free to send out a new PR with signed CLA.
