### ISSUE TITLE
Reading pbtxt in JavaScript

### ISSUE THREAD

**Issue by lutzroeder** [protocolbuffers/protobuf#4095]
Does the code produced with `--js_out` support reading `.pbtxt` files? 

If not, are there plans getting this added?

**Comment by acozzette** [comment]
No, we don't have support for the text format in Javascript and I don't believe we have any plans to implement it.

**Comment by acacio** [comment]
Text protos are an excellent way to write config files (built-in parser, type checking, etc...).

I would support the enabling of this feature for .js, if nothing else for compatibility with the rest of the other languages.

**Comment by xfxyjwf** [comment]
We probably will support JSON format in protobuf JS. For text format, there is no plan for it as Adam has already mentioned.

**Comment by kkweon** [comment]
is there an update on text format support or json support?

**Comment by jimblackler** [comment]
Would be very useful.

**Comment by jxiaof** [comment]
Can we convert pbtxt to json now?
