### ISSUE TITLE
Keep '_' in property name in C# generated code

### ISSUE THREAD

**Issue by VaronisDNMacClient** [protocolbuffers/protobuf#4120]
Hi,

From trial and error, the [style guide](https://developers.google.com/protocol-buffers/docs/style) and [source code](https://github.com/google/protobuf/blob/f39cf88a347767d25572f7344eab44359d872925/src/google/protobuf/compiler/csharp/csharp_helpers.cc) I see that all recurrences of the character '_' are eliminated from property name when generating C# code.

Can this be overridden or avoided in some way? I need my properties with underscore (or any other char that can be perceived as a separator).

**Comment by kunalspathak** [comment]
In addition to that, is there a way to specify "Keep property names as is" for the generated C# code? If not, is there an easy way to get property name for corresponding field name inside `.proto` file? 
I am generating `.proto` file on the fly, pass it through `protoc` to generate C# code and I generate some more C# code that populates the `protobuf ` objects to drive further business logic. My problem is that I don't have a mapping of field names that I generated within `.proto` file and the corresponding property names that `protoc` generated.

**Comment by anandolee** [comment]
Have you tried Descriptors? Sample usage:

https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs#L155

**Comment by kunalspathak** [comment]
Thanks @anandolee . I already tried that but it doesn't quite give what I want. Imagine protobuf message like this - 
```C++
    message FooMulInputType {
        repeated sint32 param1 = 1;
        repeated sint32 Param2 = 2;
        repeated sint32 p_aram3 = 3;
        repeated sint32 p_aram_4 = 4;
    }
```

If i do something like this, I don't get desired ouput:
```C#
FieldDescriptor par1 = FooApisType.Types.FooMulInputType.Descriptor.FindDescriptor<FieldDescriptor>("p_aram3");
Console.WriteLine(par1.Name); // "p_aram3"
```

But this is not the property names that are generated in C#. See below screenshot and I want a way to get these property names instead. Let me know if there is a way to do that.

![image](https://user-images.githubusercontent.com/12488060/38535260-8249c0f2-3c37-11e8-828f-cefceba3d1e3.png)

**Comment by anandolee** [comment]
I think it is in the FieldDescriptor.propertyName: https://github.com/google/protobuf/blob/047575f20cbdee8fb2f88d78a317ffe6133b93e6/csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs#L46

I think it is reasonable to make a public get API for the propertyName. Are you happy to make a PR for it?

**Comment by kunalspathak** [comment]
sure, will do it sometime.

**Comment by anandolee** [comment]
Friendly ping. @kunalspathak do you get time for it?

**Comment by quintenp** [comment]
Has anyone found or implemented a way to keep the _ in field names instead of forcing camelCase?

**Comment by deannagarcia** [comment]
Closing this due to the fix in https://github.com/protocolbuffers/protobuf/pull/7642.
