### ISSUE TITLE
Unreal Engine Integration failed:  unresolved external symbol __std_reverse_trivially_swappable_8

### ISSUE THREAD

**Issue by fweidner** [protocolbuffers/protobuf#4129]
Hey folks!

I'm using protobuf with Unreal Engine 4.18.2. 
Today, I wanted to upgrade to from 3.4.0 to 3.5.1

In my UE4 project, I'm linking against libprotobuf.lib

After having applied #4000 and commenting out "static_assert(std::is_pod<AuxillaryParseTableField>::value, "");" in generated_message_table_driven.h I'm stuck again.

When compiling the UE4 project in Visual Studio 2017, I get the following two errors:
...
1>libprotobuf.lib(text_format.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_8 referenced in function "void __cdecl std::_Buffered_inplace_merge_divide_and_conquer2<class google::protobuf::Message const * *,__int64,class google::protobuf::Message const *,class google::protobuf::DynamicMapSorter::MapEntryMessageComparator>(class google::protobuf::Message const * *,class google::protobuf::Message const * *,class google::protobuf::Message const * *,__int64,__int64,struct std::_Temporary_buffer<class google::protobuf::Message const *> &,class google::protobuf::DynamicMapSorter::MapEntryMessageComparator,class google::protobuf::Message const * *,class google::protobuf::Message const * *,__int64,__int64)" (??$_Buffered_inplace_merge_divide_and_conquer2@PEAPEBVMessage@protobuf@google@@_JPEBV123@VMapEntryMessageComparator@DynamicMapSorter@23@@std@@YAXPEAPEBVMessage@protobuf@google@@00_J1AEAU?$_Temporary_buffer@PEBVMessage@protobuf@google@@@0@VMapEntryMessageComparator@DynamicMapSorter@23@0011@Z)

1>libprotobuf.lib(wire_format.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8

1>F:\CloudStation\UE4\Plugin_C2IReceiver_cpp\Plugins\C2IReceiverPlugin\Binaries\Win64\UE4Editor-C2IReceiverPlugin.dll : fatal error LNK1120: 1 unresolved externals
...
`

With 3.4.0, I can compile it. 

Does anyone have encountered the same error or has any suggestions for a fix?

EDIT: Error starts appearing with 3.4.1

**Comment by weliveindetail** [comment]
Ok, in my case it happens when compiling with /MT (static runtime). So it's probably unrelated. Also with the Visual Studio 2015 toolchain (v140) I ended up having the same issue. As a hacky workaround I defined the symbols myself and throw exception("not implemented") on call. Didn't happen so far, maybe it's an unlikely code path..

Anyway, would be great to find an explanation.
Cheers

**Comment by snnn** [comment]
Hi @weliveindetail 

How did you build these two software(protobuf and the one depends it), with VS 2015 or with 2017? Do you have VS 2015 and VS  2017 both installed on the same machine?

**Comment by xfxyjwf** [comment]
Feel free to send us a PR if there is a reasonable workaround. We do not maintain binary compatibility in general though.

**Comment by Jamlee** [comment]
i got the error too, is there have any good approach to solve it ?
```

"E:\living\Paddle\build-vs2015\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\living\Paddle\build-vs2015\python\copy_paddle_pybind.vcxproj" (default target) (385) ->
"E:\living\Paddle\build-vs2015\paddle\fluid\pybind\paddle_pybind.vcxproj" (default target) (386) ->
(Link target) ->
  libprotobuf.lib(text_format.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_8 refe
renced in function "void __cdecl std::_Buffered_inplace_merge_divide_and_conquer2<class google::protobuf::Message const
 * *,class google::protobuf::MapEntryMessageComparator>(class google::protobuf::Message const * *,class google::protobu
f::Message const * *,class google::protobuf::Message const * *,__int64,__int64,class google::protobuf::Message const *
* const,__int64,class google::protobuf::MapEntryMessageComparator,class google::protobuf::Message const * *,class googl
e::protobuf::Message const * *,__int64,__int64)" (??$_Buffered_inplace_merge_divide_and_conquer2@PEAPEBVMessage@protobu
f@google@@VMapEntryMessageComparator@23@@std@@YAXPEAPEBVMessage@protobuf@google@@00_J1QEAPEBV123@_JVMapEntryMessageComp
arator@23@0011@Z) [E:\living\Paddle\build-vs2015\paddle\fluid\pybind\paddle_pybind.vcxproj]
  E:\living\Paddle\build-vs2015\paddle\fluid\pybind\Release\paddle_pybind.dll : fatal error LNK1120: 1 unresolved exter
nals [E:\living\Paddle\build-vs2015\paddle\fluid\pybind\paddle_pybind.vcxproj]


"E:\living\Paddle\build-vs2015\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\living\Paddle\build-vs2015\paddle\fluid\inference\paddle_fluid_shared.vcxproj" (default target) (427) ->
  libprotobuf.lib(text_format.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_8 refe
renced in function "void __cdecl std::_Buffered_inplace_merge_divide_and_conquer2<class google::protobuf::Message const
 * *,class google::protobuf::MapEntryMessageComparator>(class google::protobuf::Message const * *,class google::protobu
f::Message const * *,class google::protobuf::Message const * *,__int64,__int64,class google::protobuf::Message const *
* const,__int64,class google::protobuf::MapEntryMessageComparator,class google::protobuf::Message const * *,class googl
e::protobuf::Message const * *,__int64,__int64)" (??$_Buffered_inplace_merge_divide_and_conquer2@PEAPEBVMessage@protobu
f@google@@VMapEntryMessageComparator@23@@std@@YAXPEAPEBVMessage@protobuf@google@@00_J1QEAPEBV123@_JVMapEntryMessageComp
arator@23@0011@Z) [E:\living\Paddle\build-vs2015\paddle\fluid\inference\paddle_fluid_shared.vcxproj]
  E:\living\Paddle\build-vs2015\paddle\fluid\inference\Release\paddle_fluid.dll : fatal error LNK1120: 1 unresolved ext
ernals [E:\living\Paddle\build-vs2015\paddle\fluid\inference\paddle_fluid_shared.vcxproj]

```

**Comment by weliveindetail** [comment]
This bug has no relation to any of these projects and apparently there is no solution. It's just another mysterious hiccup in the Microsoft toolchain. Don't mix many versions on one machine and you may be lucky.

**Comment by Jamlee** [comment]
@snnn yes,  i have vs2015 and vs2017 installed together too, Do you have any approach to solve it ?

**Comment by snnn** [comment]
@[Jamlee](https://github.com/Jamlee) Use this https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html to replace your "external projects,".
