### ISSUE TITLE
protobuf-2.6.1 make eror

### ISSUE THREAD

**Issue by asemaniko** [protocolbuffers/protobuf#4149]
mingw32

$ make
make  all-recursive
make[1]: Entering directory `/c/deps/protobuf-2.6.1'
Making all in .
make[2]: Entering directory `/c/deps/protobuf-2.6.1'
make[2]: Leaving directory `/c/deps/protobuf-2.6.1'
Making all in src
make[2]: Entering directory `/c/deps/protobuf-2.6.1/src'
depbase=`echo google/protobuf/compiler/main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        g++ -DHAVE_CONFIG_H -I. -I..     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/compiler/main.o -MD -MP -MF $depbase.Tpo -c -o google/protobuf/compiler/main.o google/protobuf/compiler/main.cc &&\
        mv -f $depbase.Tpo $depbase.Po
In file included from ./google/protobuf/compiler/command_line_interface.h:41,
                 from google/protobuf/compiler/main.cc:33:
./google/protobuf/stubs/common.h:48:20: stdint.h: No such file or directory
In file included from ./google/protobuf/compiler/command_line_interface.h:41,
                 from google/protobuf/compiler/main.cc:33:
./google/protobuf/stubs/common.h:175: error: `uint8_t' does not name a type
./google/protobuf/stubs/common.h:176: error: `uint16_t' does not name a type
./google/protobuf/stubs/common.h:177: error: `uint32_t' does not name a type
./google/protobuf/stubs/common.h:178: error: `uint64_t' does not name a type
./google/protobuf/stubs/common.h:201: error: `uint32' does not name a type
./google/protobuf/stubs/common.h:202: error: `uint64' does not name a type
./google/protobuf/stubs/common.h:1172: error: `uint32' does not name a type
make[2]: *** [google/protobuf/compiler/main.o] Error 1
make[2]: Leaving directory `/c/deps/protobuf-2.6.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/c/deps/protobuf-2.6.1'
make: *** [all] Error 2

**Comment by TeBoring** [comment]
The problem is stdint.h is not found. You need to check whether your mingw installed proper standard library.
