### ISSUE TITLE
Protobuf PHP C extension is not escaping strings for JSON serialization

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#4151]
When calling `serializeToJsonString `, the Message object in the C Extension does not escape slashes, causing an error in the following code:

```php
   // add this to tests/encode_decode_test.php
    public function testJsonEncodeEscaping()
    {
        $string = 'this\\/should/be/escaped';
        $from = new TestMessage();
        $from->setOptionalString($string);
        $data = $from->serializeToJsonString();
        $to = new TestMessage();
        $to->mergeFromJsonString($data);
        $this->assertEquals(
            $from->getOptionalString(),
            $to->getOptionalString()
        );
    }
```

Another less important but still pressing issue can be seen in [this test](https://travis-ci.org/googleapis/gax-php/jobs/326584734#L2834), which shows that the native library escapes slashes but the C extension does not:

```php
   // add this to tests/encode_decode_test.php
    public function testJsonEncodeEscapeForwardSlash()
    {
        $string = 'this\\/should/be/escaped';
        $from = new TestMessage();
        $from->setOptionalString($string);
        $data = $from->serializeToJsonString();
        $this->assertContains(json_encode($string), $data);
    }
```

**Note**: Both of these tests pass when the `google/protobuf` composer package is used instead.

**Comment by bshaffer** [comment]
I've found a few more errors with escaping. Double quotes and newlines also break with the current implementation.

```php
   // add this to tests/encode_decode_test.php
    /** @dataProvider provideJsonEncodeEscaping **/
    public function testJsonEncodeEscaping($string)
    {
        $from = new TestMessage();
        $from->setOptionalString($string);
        $data = $from->serializeToJsonString();
        $to = new TestMessage();
        $to->mergeFromJsonString($data);
        $this->assertEquals(
            $from->getOptionalString(),
            $to->getOptionalString()
        );
        $this->assertContains(json_encode($string), $data);
    }

    public function provideJsonEncodeEscaping()
    {
        return [
            // these values fail
            ['escape/forward/slashes'],
            ['escape\\back\\slashes'],
            ["escape\nnewlines"],
            ['escape "double" quotes'],

            // these values pass
            ['escape \'single\' quotes'],
            ['escape {curly} braces'],
            ['escape [square] brackets'],
        ];
    }
```

All of these tests pass for the native implementation!

**Comment by jbq** [comment]
I could reproduce this bug with version 3.5.1 and indeed it is specific to the C extension.

Full testcase provided at https://github.com/jbq/protobuf-bug-4151

**Comment by haberman** [comment]
I just tried this, and the current version of PHP protobuf passes all tests except forward-slash.

JSON does not require escaping forward slash, and we don't currently do it.

I understand that PHP's JSON escapes forward slashes by default. I'm not sure whether this is a universal enough thing to make sense for protobuf to do.
