### ISSUE TITLE
Old versions of gcc give warnings for pragma diagnostic push and pop

### ISSUE THREAD

**Issue by teeks99** [protocolbuffers/protobuf#4156]
`#pragma GCC diagnostic push` and `#pragma GCC diagnostic pop` are only supported in gcc >= 4.6. 

A solution to this would be to change the guards from
```c++ 
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
```
and
```c++ 
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
```
To: 
```c++ 
#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
```
and
```c++ 
#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic pop
#endif  // __GNUC__
```

There are approximately a dozen header files that do this, as well as the cpp_file.cc codegen.  This could be applied to the 3.?.x branches, but might not be needed on master....if master is now c++11, gcc versions before 4.6 might not work with it anyway...I guess it depends on how good various gcc's -std=c++0x support was back then. Might not hurt to apply to master as well.

**Comment by xfxyjwf** [comment]
@teeks99 We no longer support old gcc versions on the master branch, but we will keep the 3.5.x branch for pre-C++11 support.

**Comment by mcy** [comment]
GCC versions older than 6.3 are not supported. See https://opensource.google/documentation/policies/cplusplus-support#2_compilers
