### ISSUE TITLE
Unable to use proto_h mode in cpp generator

### ISSUE THREAD

**Issue by diclogic** [protocolbuffers/protobuf#4157]
there's an option called proto_h defined in Options in compiler/cpp directory. it is used in many places and there're comments mentioning about as ".proto.h mode", but there's no way to turn this option on and there's no document about it. It has a feature useful to me, it generates enum with `int` enum base type, which means forward declarations become available for that kind of enums. I think that would be useful to anyone who want to hide the details of a enum from a header file, or simply making forward declaration file for a enum type generated by protobuf.
[cpp_generator.cc](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_generator.cc)
[cpp_options.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_options.h)

**Comment by rndrwz** [comment]
If this can reduce compile times of protobuf includes, I'm all for it.

**Comment by haberman** [comment]
proto_h mode was fully open-sourced in https://github.com/protocolbuffers/protobuf/pull/9482
