### ISSUE TITLE
Can not print out Message as string and save to prototxt

### ISSUE THREAD

**Issue by jinfagang** [protocolbuffers/protobuf#4175]
I just want to print out a message, I am using this codes:

```
string resultStr;
detectionResult.SerializeToString(&resultStr);
printf("%s", resultStr.c_str());
```
`detectionResult` is my message. But it just got some unicode binary outputs rather than strings and numbers, just not as prototxt beautiful json-like string was.

I also try to save my Message into a prototxt file which I believe more readable then binary.
```
char* saveTxtFile = "det.prototxt";
    int f = open(saveTxtFile, O_WRONLY|O_CREAT|O_TRUNC);
    auto outputTxtFile = new FileOutputStream(f);
    if (!google::protobuf::TextFormat::Print(detectionResult, outputTxtFile)) {
        cao::Log(kError, "error in save to prototxt");
    }
```

This gives me an error, I remove the file and try again, it saved blank message. What is the right way to do this? Forgive my ignorance on protobuf but it's really leak of examples on this.

**Comment by TeBoring** [comment]
SerializeToString is binary format.
Use DebugString instead.
