### ISSUE TITLE
Consider renaming the 'Status' variable, conflicts with Xlib and others.

### ISSUE THREAD

**Issue by acidtonic** [protocolbuffers/protobuf#4186]
Greetings,

I have spent a few hours trying to locate a bug that ended up resulting from a naming conflict. My project previously was fine but after moving from protobuf 2.x to 3.x suddenly the code failed to compile. A quick search indicated others hit the same issue, but no answers. Thus I decided to open this issue to both document the issue and attempt to fix this by renaming the "Status" declaration to something else. 

In my case this was a result of a variable conflict by including Xlib on a Gentoo Linux development machine. I was able to eventually resolve by carefully reordering includes such that all Xlib and various X11 headers were all before protobuf includes, followed by an #undef Status. 

Since Xlib vastly predates protobufs usage of the varible, I believe the bug is with protobuf for the sudden usage and not with Xlib... Also Linux is a supported platform of Protobuf and Xlib is rather widespread and well-known. If multiple includes of Xlib are present, it's also very difficult to properly place the #undef Status since all further includes of Xlib components or X11 extensions will also fail as they all rely on the "Status" variable existing and being defined as an int.

Sorry for the wordy report but hopefully this gets indexed and helps others who may run into this. I appreciate your time.

Error:
/usr/include/google/protobuf/stubs/logging.h:66:7: error: expected identifier before ‘int’
 class Status;       ^
/usr/include/google/protobuf/stubs/logging.h:66:7: error: multiple types in one declaration
In file included from /usr/include/google/protobuf/stubs/common.h:50:0,
                 from [snip]/protocol/SomeGeneratedProtocolUsing.pb.h:9,
/usr/include/google/protobuf/stubs/logging.h:90:32: error: expected ‘)’ before ‘::’ token
   LogMessage& operator<<(const ::google::protobuf::util::Status& status);
                                ^
/usr/include/google/protobuf/stubs/logging.h:90:32: error: ‘google::protobuf::internal::LogMessage& google::protobuf::internal::LogMessage::operator<<(...)’ must not have variable number of arguments
/usr/include/google/protobuf/stubs/logging.h:90:26: error: expected ‘;’ at end of member declaration
   LogMessage& operator<<(const ::google::protobuf::util::Status& status);
                          ^
In file included from [snip]/HeaderIncludingTheGeneratedProtocol.hpp:10:0,
/usr/include/google/protobuf/stubs/logging.h:90:58: error: expected unqualified-id before ‘int’
   LogMessage& operator<<(const ::google::protobuf::util::Status& status);

Fixed by something similar to below....

#include <X11/xlib.h>
#include All other X11 includes here
#undef Status
#include Protobuf here and all generated proto headers

**Comment by jhnnhgh** [comment]
I had the same problem. Luckily my project no longer relied on Xlib so the solution was to simply stop including the Xlib headers. A fix would be appreciated though.

**Comment by TeBoring** [comment]
I don't think this is a bug of protobuf.
Status seems a quite common name that could be used by any library. If Xlib uses it for its own implementation, it should clean it up after it's no longer used.
e.g., we have port_def.inc and port_undef.inc to address similar problem.

**Comment by fei4xu** [comment]
I'm having exactly the same error.
in `/usr/include/X11/Xlib.h`, 
```c
#define Status int
```

**Comment by gdshukla** [comment]
I faced the same problem. CImg.h was having following includes:
```
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
```
And I was getting errors in  protobuf include files.
I added `#undef Status` below it in CImg.h file and it worked fine.
As said in a comment above, its the issue with X11. It should clean up after it.

gdshukla
