### ISSUE TITLE
Is it possible to create own Python class and bind it with message?

### ISSUE THREAD

**Issue by alexpantyukhin** [protocolbuffers/protobuf#4194]
I have a message something like:
```
message Point {
  string x = 1;
  string y = 2;
}
```

But I want to have in the  pyhon code something like:
```python
class Point():
    def get_quare():
        return self.x * self.y

    @property
    def source(self):
        ...

    @source.setter
    def source(self, address):
        ...
    ...

p = new Point()
p.source = 'mysource'
p.x = 10
p.y = 20
print(p.get_square())
```

Is it possible to construct somehow such class with binding it with message `Point` ?
For example there https://github.com/ligato/vpp-agent/blob/master/vendor/github.com/gogo/protobuf/test/typedecl/typedecl.proto described how to avoid generating type with `typedecl` for go.

**Comment by anandolee** [comment]
Looks no good idea for it yet as no response for more than one year. Closing it for clean up. Feel free to reopen if anyone has proposal and willing to contribute on it.
