### ISSUE TITLE
generated enum for oneof fields don't have corresponding EnumCase_Name() function

### ISSUE THREAD

**Issue by xyzzyz** [protocolbuffers/protobuf#4215]
The [documentation says](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#oneof):

> Given a oneof definition like this:
> ```
> oneof oneof_name {
>     int32 foo_int = 4;
>     string foo_string = 9;
>     ...
> }
> ```
> The compiler will generate the following C++ enum type:
> 
> ```
> enum OneofNameCase {
>   kFooInt = 4,
>   kFooString = 9,
>   ONEOF_NAME_NOT_SET = 0
> }
> ```

And then, later, it says:

> Given an enum definition like:
> ```
> enum Foo {
>   VALUE_A = 0;
>   VALUE_B = 5;
>   VALUE_C = 1234;
> }
> ```
> (...) In addition, the compiler will generate the following functions:
> (...) 
> const string& Foo_Name(int value): Returns the name for given numeric value. Returns an empty string if no such value exists. If multiple values have this number, the first one defined is returned. In the above example, Foo_Name(5) would return "VALUE_B".
> (...)

As I understand it, the "generated enum for oneof" field, is a "C++" enum, not "proto" enum, so the latter doesn't apply to it -- and in fact, OneofNameCase_Name() function is not generated. I believe it should -- otherwise, how can I get the _name_ of the oneof case as a string? Or is it something that I shouldn't be doing, for some reason?

**Comment by xfxyjwf** [comment]
What is the "name of the oneof case" you are referring to? Do you want "oneof_name", or "foo_int", "foo_string"? Assuming it's the later, they are protobuf field names so you can get their names by field number:

```cpp
string name = ContainingMessage::descriptor()->FindFieldByNumber(kFooInt)->name();
```

**Comment by xfxyjwf** [comment]
Note that the Foo_Name() methods for enums are simple wrappers around the descriptor API. If we add a OneofNameCase_Name() method, it's likely implemented exactly as I suggested above. Due to binary size concerns we are unlikely to add new generated methods like this though.

**Comment by xyzzyz** [comment]
Thank you for providing workaround. This will make my CL significantly simpler.

I understand your concern about binary size. However, couldn't we just make the new method be inline? Then, existing binaries that don't use this new feature will not be affected by binary size increase (hopefully the users that care about binary size, like e.g. Chromium, already optimize out unused symbols during linking).

**Comment by xfxyjwf** [comment]
@xyzzyz It's not just the size of the end binary that we care about. Adding new C++ symbols will increase the size of intermediate object files and there are some really big binaries in Google that are sensitive to the size of intermediate object files because the linker can't handle it if they grow any bigger... So even adding inline functions can cause a problem for them (and they are constantly monitoring any size changes).

**Comment by xyzzyz** [comment]
If the new method is going to be as simple as what you have shown above, it shouldn't increase binary size by more than a few dozens of bytes per oneof field. As internal binaries don't use oneof that often, I'd estimate the binary size increase to be less than 10 KB even for the very large binaries. I would like to test it. Could you ping me internally and give me some candidate binary to test?

**Comment by xfxyjwf** [comment]
@xyzzyz If you are still interested, feel free to send us a CL. We should already have some presubmit checks that checks binary size increase.

**Comment by TeBoring** [comment]
Close this for cleanup. If this is still going on, feel free to reopn it.

**Comment by johncolvin-og** [comment]
As an alternative approach, you could generate macros instead of methods to avoid adding new symbols.

**Comment by johncolvin-og** [comment]
If the oneof int values are always equal to their corresponding field numbers, you could generate macros instead of methods to avoid adding new symbols. The FOO_CASE_NAME(enum_val) macro could static-cast the val to an int, which could be used as the field_number param needed to obtain the name.
