### ISSUE TITLE
when make,  make[2]: Nothing to be done for `all-am'

### ISSUE THREAD

**Issue by shikai2013** [protocolbuffers/protobuf#4217]
when i run make on my mac,this happened:
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in .
make[2]: Nothing to be done for `all-am'.
Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.

I think ,it is not friendly to install protobuf on mac

**Comment by zcc1234567** [comment]
help!!!

**Comment by acozzette** [comment]
What protobuf version are you using? Also, are you sure that it's not working? Sometimes `make` says "Nothing to be done" because everything has already been built.
