### ISSUE TITLE
Java version failed to build on Protobuf 3.5.1.1

### ISSUE THREAD

**Issue by KaoCC** [protocolbuffers/protobuf#4269]
Environment:

Java 9 (JDK 9.0.4) x64 on Windows 10
Protobuf 3.5.1.1

Error:
ExtensionRegistryFactoryTest.initializationError » ExceptionInInitializer

Details:

-------------------------------------------------------------------------------

Test set: com.google.protobuf.ExtensionRegistryFactoryTest

-------------------------------------------------------------------------------

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.google.protobuf.ExtensionRegistryFactoryTest
initializationError(com.google.protobuf.ExtensionRegistryFactoryTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.google.protobuf.ExtensionRegistryFactoryTest.getLiteOnlyClassLoader(ExtensionRegistryFactoryTest.java:253)
	at com.google.protobuf.ExtensionRegistryFactoryTest.<clinit>(ExtensionRegistryFactoryTest.java:59)

**Comment by languitar** [comment]
Same thing here on java 10

**Comment by fmauger** [comment]
Same issue on Ubuntu Linux 18.04 with protobuf 3.7.1, maven 3.6.0, openjdk-11:
```
[INFO] Running com.google.protobuf.MapTest
[INFO] Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s - in com.google.protobuf.MapTest
[INFO] Running com.google.protobuf.ExtensionRegistryFactoryTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.016 s <<< FAILURE! - in com.google.protobuf.ExtensionRegistryFactoryTest
[ERROR] initializationError(com.google.protobuf.ExtensionRegistryFactoryTest)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.google.protobuf.ExtensionRegistryFactoryTest.getLiteOnlyClassLoader(ExtensionRegistryFactoryTest.java:260)
	at com.google.protobuf.ExtensionRegistryFactoryTest.<clinit>(ExtensionRegistryFactoryTest.java:59)
```

**Comment by leebird** [comment]
Same issue on Ubuntu 18.04, protobuf 3.7.1, maven 3.6.0, openjdk 11.0.3

**Comment by leebird** [comment]
@KaoCC As it has been some time since you saw this bug, have you already solved it?

**Comment by KaoCC** [comment]
@leebird Unfortunately no. I remember at some point our project required Java + Protobuf drastically shifted to C++ and it just worked.

**Comment by haon4** [comment]
I believe this has already been fixed: https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/test/java/com/google/protobuf/ExtensionRegistryFactoryTest.java#L276.

**Comment by gricardo99** [comment]
I don't think that change addresses or fixes this error.  I'm hitting the same error with same JDK (9.04), but Protobuf 3.10.1, which has the above change, on Ubuntu 16.04.   The change also shows added catch for exception SecurityException, but that's not the reported error/exception.  The exception is ExceptionInInitializerError.   Any recommended workaround would be helpful.  Perhaps run with newer JDK?
