### ISSUE TITLE
Deserialization problem with Tensorflow DELF pre-trained model

### ISSUE THREAD

**Issue by vslomakin** [protocolbuffers/protobuf#4273]
Hello,

I'm trying to execute DEep Local Features Tensorflow model as described in that manual: https://github.com/tensorflow/models/blob/master/research/delf/EXTRACTION_MATCHING.md

For that I firstly install Tensorflow and DELF, which involves protobuf compiling:
https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md

Unfortunately resulting code works fine with python2.7 and breaks with python3+. It breaks exactly at the moment of protobuf deserialization. Some details at: https://github.com/tensorflow/models/issues/3289

The question is: may it be the problem of incorrect protobuf handling? May there be issues if protobuf was serialized in python2.7 and deserialized with python3? Is there any chance to debug the deserialization process?

**Comment by xfxyjwf** [comment]
I don't see any protobuf related code in the stack trace in https://github.com/tensorflow/models/issues/3289#issue-293356753 . Why do you think it's failing at protobuf deserialization?
