### ISSUE TITLE
Not all fields of JsonPrintOptions are documented

### ISSUE THREAD

**Issue by iulianR** [protocolbuffers/protobuf#4305]
The fields `always_print_enum_as_ints` and `preserve_proto_field_names` are missing. See code [1] and documentation [2].

[1] https://github.com/google/protobuf/blob/0a7120ac32e16d49a35abf18186c8c4db515dd02/src/google/protobuf/util/json_util.h#L68
[2] https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions

**Comment by jlisee** [comment]
We just hit this issue with thinking an option did not exist based on the docs.  Does the site just need the docs pushed again? It says:
> Last updated August 23, 2016.

Or is there a PR we can put up to fix this?

**Comment by fowles** [comment]
This ties into your upcoming focus on json I believe

**Comment by jskeet** [comment]
@fowles: I'm not sure it does - I think this is just a matter of whether or not the docs are up-to-date? (I seem to remember that's already being addressed.) Please let me know if I've misunderstood though :)
