### ISSUE TITLE
PHP - Nested structs do not appear to be handled correctly with the protobuf extension enabled

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#4339]
While reading entries from Stackdriver Logging with the protobuf extension enabled, entries with a `jsonPayload` which include  nested structs are not returning the correct data. I have detailed the steps taken to run into the issue below:

https://github.com/GoogleCloudPlatform/google-cloud-php/issues/906#issuecomment-368174482

**Comment by dwsupplee** [comment]
To follow up with a little more detail, this was using version 3.5.1.1 of the extension.

**Comment by TeBoring** [comment]
Right now, c extension hasn't passed protobuf's conformance test yet. After I finish the work on hand, I will start to fix it.

**Comment by jdpedrie** [comment]
Hi @TeBoring,

We had an issue[1] opened recently which is related to this problem. Do you have any idea yet as to when the C extension will be brought into conformance?

[1] https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1214

**Comment by TeBoring** [comment]
I am working on that. Maybe end of quarter.

**Comment by TeBoring** [comment]
Should have been fixed in #5106
