### ISSUE TITLE
PHP - Byte strings appear to come back as either 16 bit or 64 bit depending on whether or not the extension is enabled

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#4343]
While researching an issue that came up regarding Bigtable, I noticed varying return values when toggling the protobuf extension on/off.

```php
$rules = [];
$rowRule = new ReadModifyWriteRule();
$rowRule->setFamilyName('cf1');
$rowRule->setColumnQualifier('c1');
$rowRule->setIncrementAmount(1);
$rules[] = $rowRule;

$result = $client->readModifyWriteRow($table, 'key1', $rules);

foreach ($result->getRow()->getFamilies() as $families) {
    foreach ($families->getColumns() as $column) {
        foreach ($column->getCells() as $cell) {
            var_dump($cell->getValue()); // outputs "\000a" with the extension and "\000\000\000\000\000\000\000a" without
            var_dump(unpack('J', $_cell->getValue())[1]); // works without the extension
            // var_dump(unpack('n', $_cell->getValue())[1]); // works with the extension
        }
    }
}
```

This is using version 3.5.1.1 of the extension. For more context please see [here](https://github.com/GoogleCloudPlatform/google-cloud-php/issues/920#issuecomment-369276247).

**Comment by TeBoring** [comment]
Thanks for reporting this. Under the hood, how $rowRule becomes $cell?

**Comment by dwsupplee** [comment]
Of course! Thanks for touching base.

It is through executing the following RPC via our [Bigtable V2 GAPIC Client](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Bigtable/V2/Gapic/BigtableGapicClient.php#L692): [google.bigtable.v2.Bigtable.ReadModifyWriteRow](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.Bigtable.ReadModifyWriteRow-table)

**Comment by TeBoring** [comment]
FamilyName and ColumnQualifier specify the position of the cell to be changed and IncrementAmount is how to change the cell. Am I correct?

**Comment by TeBoring** [comment]
Does ```$cell->getValue()``` return a protobuf binary string?
If so, how was that created?

**Comment by TeBoring** [comment]
We have fixed a bunch of conformance tests this year. Could you try again if this issue is fixed?

**Comment by dwsupplee** [comment]
@TeBoring that's awesome news. Taking a look now, thanks!

**Comment by dwsupplee** [comment]
@TeBoring I've confirmed this is fixed. Nice work! :)
