### ISSUE TITLE
Protobuf generator: reserved keywords for php functions

### ISSUE THREAD

**Issue by ayenter** [protocolbuffers/protobuf#4363]
I have a method called "List", but in php 5.5, this is a reserved keyword. So when the generator creates a function called "List", running the code results in the error:
``Parse error: parse error, expecting `"identifier (T_STRING)"' in`` ...

Here is the snippet of my .proto:
```
service TheService {
    rpc List(ListRequest) returns (stream ListReply);
}
```

**Comment by pherl** [comment]
@TeBoring

**Comment by TeBoring** [comment]
I will fix it in a PR.

**Comment by fowles** [comment]
Pretty sure this got fixed somewhere along the line.  Please reopen if there are still issues.
