### ISSUE TITLE
[Python, C backend] String representation sometimes out of date with map field

### ISSUE THREAD

**Issue by arthur-tacca** [protocolbuffers/protobuf#4367]
If a message that is a value in a map field is changed at least twice, the string representation of the parent message (as obtained with `str(msg)`) is incorrect. The string representation becomes correct if the parent message is prodded a bit, for example using the `text_format` module. I'm guessing that the string representation of a message is not guaranteed to be anything in particular, but this can make debugging (and maybe log files) confusing.

I am using Python 3.5 on Ubuntu 16.04. I have tried with protobuf 3.5.1 and 3.5.2. It occurs only with the C backend i.e. I see the problem with `pip install protobuf==3.5.2` but NOT with `pip install --no-binary :all: protobuf==3.5.2`.

Here is the specifics of how to reproduce. First the schema:

    // test.proto
    syntax = "proto3";
    message Inner {
       string inner = 1;
    }
    message Outer {
       map<string, Inner> map_field = 1;
    }

Here is some Python code that shows the problem:

    import test_pb2
    from google.protobuf import text_format

    def my_print(msg):
        print(str(outer_msg).replace("\n", ""))
        print(text_format.MessageToString(outer_msg).replace("\n", ""))
        print(str(outer_msg).replace("\n", ""))

    outer_msg = test_pb2.Outer()

    print(" -- Initial change -- ")
    outer_msg.map_field["key"].str_field = "first"
    my_print(outer_msg)

    print(" -- Changed via lookup -- ")
    outer_msg.map_field["key"].str_field = "second"
    my_print(outer_msg)

    print(" -- Changed via another variable (first time) -- ")
    inner_msg = outer_msg.map_field["key"]
    inner_msg.str_field = "third"
    my_print(outer_msg)

    print(" -- Changed via another variable (second time) -- ")
    inner_msg.str_field = "fourth"
    my_print(outer_msg)

And here is the output:

     -- Initial change -- 
    map_field {  key: "key"  value {    str_field: "first"  }}
    map_field {  key: "key"  value {    str_field: "first"  }}
    map_field {  key: "key"  value {    str_field: "first"  }}
     -- Changed via lookup -- 
    map_field {  key: "key"  value {    str_field: "second"  }}
    map_field {  key: "key"  value {    str_field: "second"  }}
    map_field {  key: "key"  value {    str_field: "second"  }}
     -- Changed via another variable (first time) -- 
    map_field {  key: "key"  value {    str_field: "third"  }}
    map_field {  key: "key"  value {    str_field: "third"  }}
    map_field {  key: "key"  value {    str_field: "third"  }}
     -- Changed via another variable (second time) -- 
    map_field {  key: "key"  value {    str_field: "third"  }}
    map_field {  key: "key"  value {    str_field: "fourth"  }}
    map_field {  key: "key"  value {    str_field: "fourth"  }}

**Comment by anandolee** [comment]
This is an known issue that we should have fixed on 2016. However when I back to check the fix CL, it was rollback while the owner was on vacation.

@TeBoring will go forward the fix

**Comment by anandolee** [comment]
The fix has been fixed in internal code. Should be included in 3.7.0 release

**Comment by anandolee** [comment]
Closing it as 3.7.0 is already released
