### ISSUE TITLE
Efficiently filter repeated message fields in python

### ISSUE THREAD

**Issue by vitaminSP** [protocolbuffers/protobuf#4396]
I have a repeated message field and I would like to remove certain elements based on a predicate. Unfortunately, I cannot find documentation on how to do that and all approaches I can think of either don't work or are not optimal (involve copying memory) and not pythonic. 

I first tried 
```python
message.field[:] = [v for v in message.field if v.keep]
```
But it breaks since repeated message fields have no set items method (as opposed to repeated scalar fields).

I ended up doing
```python
new_fields = [v for v in message.field if v.keep]
del message.field[:]
message.field.extend(new_fields)
```
But this does one memory copy for each element in `new_fields`

**Comment by arthur-tacca** [comment]
This should work (untested):

    i = 0
    while i < len(message.field):
        if message.field[i].keep:
            i += 1
        else:
            del message.field[i]

I have no idea if it's actually efficient though (e.g. if `del message.field[i]` is performing copies to shuffle the later elements down then its performance is quadratic). And if you wanted to sort the elements I don't know what you could do (short of deleting and reinserting elements, which is probably less efficient than building a new list even if the implementation is just shuffling pointers around).

**Comment by Alleno** [comment]
Can we reopen this issue? Was this resolved?
