### ISSUE TITLE
Q: How to disable googletest and benchmark?

### ISSUE THREAD

**Issue by totszwai** [protocolbuffers/protobuf#4450]
Is there a way to just compile protobuf and not to deal with anything under third_party?
We have a build system that symlink pretty much link (yeah don't ask me why) everything into a build directory before building...

When running autogen.sh, it complains about the underlying modules (googletest and benchmark) is missing the m4 folder then just died there.

```
autoreconf -f -i -s
aclocal: couldn't open directory `m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
```

I don't need googletest nor benchmark, how to disable them?

**Comment by xfxyjwf** [comment]
It can't be disabled when using autotools. Right now I think you have two options:
1. Use cmake and do "cmake -Dprotobuf_BUILD_TESTS=OFF".
2. Download a .tar.gz or .zip package from the release page. For example: https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-all-3.5.1.tar.gz .
