### ISSUE TITLE
[PHP] Serialization error in C Extension on Message::mergeFromJsonString

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#4458]
This is related to #4457 

The special types that are checked for using `GPBUtil::hasSpecialJsonMapping` (and are being checked for [in the native implementation](https://github.com/google/protobuf/blob/c93174346149f259ebc85fdb46826fcf84abb07d/php/src/Google/Protobuf/Internal/Message.php#L984) are not being checked in the protobuf C extension for `Google\Protobuf\Internal\Message::mergeFromJsonString()`. As a result the following error is thrown if any of these types are included in the response:

```
  [Exception]                                                                                        
  Error occurred during parsing: String specified for bool or submessage field: last_heartbeat_time
```

**Comment by TeBoring** [comment]
This is strange. If you use c extension, this method shouldn’t be called.

**Comment by bshaffer** [comment]
The issue is that the string property `last_heartbeat_time` is being returned, and the library is expecting this to be a submessage (e.g. `Google\Protobuf\Timestamp`). This is handled [in the native library here](https://github.com/google/protobuf/blob/c93174346149f259ebc85fdb46826fcf84abb07d/php/src/Google/Protobuf/Internal/Message.php#L984), but it's not handled in the C extension.

**Comment by TeBoring** [comment]
Seems to me this is a missing feature for well known types in c extension.

**Comment by fly-studio** [comment]
Native `serialize` function made php crashed When used a C extension.

```
class SomeMessage extends \Google\Protobuf\Internal\Message {
.... string/int32/int64
}

$messge = new SomeMessage();

serialize($message); <---------------------------- PHP Crash
```

So I `implements \Serializable` to `SomeMessage` And add
```
public function serialize()
{
	return $this->serializeToString();
}
public function unserialize($data) {
	$this->mergeFromString($data);
}
```

It can works fine in `serialize($message);`

**BUT**, PHP crashed in 'unserialize()', I have no idea to fix `function unserialize($data)`, Because PHP crashed before call `unserialize($data)`

**Comment by glorens** [comment]
Hi there, 

I get back to that topic as it seems to be related to an issue we have. As far as I understand the c-extension is not properly handling json serialization of google's Timestamp object. Where other libs (at least java & php) turn it into a RFC 3339  string, looks like c extension is still expecting a `{seconds: ...}` object. This dirty hack `preg_match_all('/\d+-\d+-\d+T\d+:\d+:\d+Z/', $string, $matches);
        foreach ($matches[0] as $match) {
            $date = \DateTime::createFromFormat('Y-m-d\TH:i:s\Z', $match, new \DateTimeZone('UTC'));
            $rp = sprintf("{\"seconds\":%d}", $date->getTimestamp());
            $string = str_replace(sprintf("\"%s\"", $match), $rp, $string);
        }` seems to fix the issue. 
Do you know more about this topic. Is it the right channel to discuss a potential issue in c lib ?

**Comment by TeBoring** [comment]
I think this has been fixed in the master branch. Feel free to reopn if the issue still exist.
