### ISSUE TITLE
\Google\Protobuf\Any - no way to override TYPE_URL_PREFIX

### ISSUE THREAD

**Issue by atrauzzi** [protocolbuffers/protobuf#4463]
Looking at trying to reuse [the code already in `Any.php`](https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Any.php#L233-L255), specifically the `pack` method.

So, specifically what's nice is this bit:

![image](https://user-images.githubusercontent.com/115199/38179241-78ff30f6-35e6-11e8-8cc4-a98f31bd9275.png)

But the problem comes one line after, here:

![image](https://user-images.githubusercontent.com/115199/38179246-865120f2-35e6-11e8-9a99-1c37e13d9ee4.png)

This sources a constant from `GPBUtil`, which is outside of my control and no attempt is made to look at the local instance before going to the constant.

Also worth noting that phpstorm doesn't appear to think anything is using the same const found on `Any`.  Might be worth cleaning that up or moving over to using it from `GPBUtil`?

![image](https://user-images.githubusercontent.com/115199/38179267-d93bfa26-35e6-11e8-8040-31d65a9dd5b8.png)

**Comment by TeBoring** [comment]
PR is welcome

**Comment by deannagarcia** [comment]
Closing due to no response, if you still want this feature please reopen.
