### ISSUE TITLE
PHP - bcmath extension is required, but not typically installed by default

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#4465]
Certain bundles come with the [bcmath extension](http://php.net/manual/en/bc.installation.php), but it is not always included by default. It would be great if we either forced a requirement on this extension in the `composer.json`, or ideally had a fallback for the case where it is not installed.

An error is triggered with calls to [`Google\Protobuf\Internal\Message::mergeFromJsonString()`](https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L715) (due to [bccomp](https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L882) calls), and when using the protobuf C extension a segfault is triggered - making tracing the issue extremely difficult.

This was surfaced from a user reported issue at https://github.com/GoogleCloudPlatform/google-cloud-php/issues/950.

**Comment by TeBoring** [comment]
I'll add a requirement for bcmath

**Comment by TeBoring** [comment]
Using c extension should not meet this problem.

**Comment by TeBoring** [comment]
I am thinking whether reporting an error will be more reasonable. Some users are using c extension and others may not use mergeFromJsonString. For these uses, bcmath is not needed.

**Comment by dwsupplee** [comment]
@TeBoring that sounds fair and would be better than just a hard to trace segfault.

**Comment by dwsupplee** [comment]
@TeBoring friendly ping :) - is this something still on the radar? This issue can be confusing to our users.

**Comment by hackzilla** [comment]
I've just run into this problem with bcmath extension not being installed.

```
Call to undefined function Google\Protobuf\Internal\bccomp()" {"exception":"[object] (Error(code: 0): Call to undefined function Google\\Protobuf\\Internal\\bccomp() at .../vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1000
```

I can see that it was a suggestion but it feels like the extension is required.

```
composer info google/protobuf
name     : google/protobuf
descrip. : proto library for PHP
keywords : proto
versions : * v3.17.3
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : https://developers.google.com/protocol-buffers/
source   : [git] https://github.com/protocolbuffers/protobuf-php.git ae9282cf11dd2933b7e71a611f9590f07d53d3f3
dist     : [zip] https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/ae9282cf11dd2933b7e71a611f9590f07d53d3f3 ae9282cf11dd2933b7e71a611f9590f07d53d3f3
path     : /var/www/ukwm-feeds.ukwm.co.uk/vendor/google/protobuf
names    : google/protobuf
```

**Comment by cdcline** [comment]
This is a pretty annoying issue if you're trying to setup secrets on the google cloud. The docs don't mention any of this.

**Comment by keifgwinn** [comment]
We just ran into this using google secrets in google run
