### ISSUE TITLE
[docs] Language specification for options do not permit aggregates

### ISSUE THREAD

**Issue by dsnet** [protocolbuffers/protobuf#4480]
The syntax for an option is as such:
```
option = "option" optionName  "=" constant ";"
constant = fullIdent | ( [ "-" | "+" ] intLit ) | ( [ "-" | "+" ] floatLit ) | strLit | boolLit
```

Basically, the BNF claims that the option value can only be a `fullIdent`, `intLit`, `floatLit`, `strLit`, or `boolLit`. However, this contradicts the observed behavior of the protoc compiler where:
https://github.com/google/protobuf/blob/e7e6c6b8d1317aa315530024224bfb92e857daa0/src/google/protobuf/compiler/parser.cc#L1439-L1449

Functionally, the enables option values of the following form to be specified:
```
[(path.to.my.option).field = { arg1: "hello", arg2: 100 }]
```

The specification should be updated to cover this case.

**Comment by anandolee** [comment]
This should be added in to spec. Are you able to provide a  fix?
