### ISSUE TITLE
Support for scalar types in rpc methods

### ISSUE THREAD

**Issue by martinheidegger** [protocolbuffers/protobuf#4487]
I am trying to implement a rpc method that returns just an bytestream:

```protobuf
syntax = “proto3”;
service MyService {
  rpc loadData (DataQuery) returns (stream bytes)
}
```

however, according to the [specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#service_definition) the only supported types are `messageType`'s and that excludes scalar types, leaving me with the error: `no such type: bytes`.

I feel like it should be possible to get a regular byte-stream through the API.

**Comment by ObsidianMinor** [comment]
You could use the BytesValue message in google/protobuf/wrappers.proto

**Comment by martinheidegger** [comment]
I am doing that right now, but it has implications for the implementation (Node.js Streams are streams of bytes, not ByteWrappers).

**Comment by martinheidegger** [comment]
Protobuf4 & rpc2?

**Comment by haon4** [comment]
It has been >1 year, and I still don't see this being something that we would prioritize.
