### ISSUE TITLE
need a Warning on the usage of pure Python implementation

### ISSUE THREAD

**Issue by jizhilong** [protocolbuffers/protobuf#4489]
In some complexed circumstance like grpc services, a pure python implementation may dramatically take down the whole performance, if there was a message in the logs explicitly warning people this would be a bottleneck, the time costed for troubleshooting such issues would be decreased a lot.

**Comment by anandolee** [comment]
Cpp extension is not the default implementation yet and the major google internal projects are still using pure python. Add this warning will produce annoying message for lot of projects.

We are still working on fixing the behavior difference of pure python and cpp extension and planning to migrate the default implementation to cpp extension. I'd expect to see this warning added after that
