### ISSUE TITLE
Visual Studio 2017 wire_format_lite.h error c4146

### ISSUE THREAD

**Issue by giulatona** [protocolbuffers/protobuf#4494]
I am trying to compile the example add_person.cc. I compiled with protoc addressbook.proto and imported into my empty solution the files: add_person.cc, addressbook.pb.cc, addressbook.pb.h.

When i compile my solution i get the following errors:
`1>------ Build started: Project: Project1, Configuration: Debug Win32 ------
1>addressbook.pb.cc
1>d:\libs\protobuf-3.5.1\debug\x86\include\google\protobuf\wire_format_lite.h(863): error C4146: unary minus operator applied to unsigned type, result still unsigned
1>d:\libs\protobuf-3.5.1\debug\x86\include\google\protobuf\wire_format_lite.h(874): error C4146: unary minus operator applied to unsigned type, result still unsigned
1>add_person.cc
1>d:\libs\protobuf-3.5.1\debug\x86\include\google\protobuf\wire_format_lite.h(863): error C4146: unary minus operator applied to unsigned type, result still unsigned
1>d:\libs\protobuf-3.5.1\debug\x86\include\google\protobuf\wire_format_lite.h(874): error C4146: unary minus operator applied to unsigned type, result still unsigned
1>Generating Code...
1>Done building project "Project1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

If I remove the minus sign in the lines that cause the error, my project compiles correctely.

I know that C4146 should be just a warning, but i get an error. /WX is disabled.
I have Visual Studio 2017 Community 15.6.5

Command line options are:
>/permissive- /GS /analyze- /W3 /Zc:wchar_t /I"D:\libs\protobuf-3.5.1\debug\x86\include" /ZI /Gm- /Od /sdl /Fd"Debug\vc141.pdb" /Zc:inline /fp:precise /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /FC /Fa"Debug\" /EHsc /nologo /Fo"Debug\" /Fp"Debug\Project1.pch" /diagnostics:classic

**Comment by jozefizso** [comment]
Is it safe to patch 3.5.0 and 3.5.1 code with this patch to resolve this issue?

https://github.com/google/protobuf/commit/24493eef9395e5b832360e12efabf9c363c9cb15

**Comment by xfxyjwf** [comment]
@jozefizso We can patch it back to the 3.5.x branch. That won't affect 3.5.0 or 3.5.1 though. Feel free to send us a pull request if you need it in 3.5.x branch soon.

**Comment by jozefizso** [comment]
I've created pull request for the 3.5.x branch based on https://github.com/google/protobuf/commit/24493eef9395e5b832360e12efabf9c363c9cb15

As we use vcpkg, we can patch 3.5.0 and 3.5.1 in the probuf port definition. I just wanted to make sure it is a valid patch for this issue.
