### ISSUE TITLE
json_format in javascript

### ISSUE THREAD

**Issue by dilipvamsi** [protocolbuffers/protobuf#4497]
c++, python have a way to convert a message to json. 
Is there a way to get this done for javascript, as toObject function is not consistent with the json created from c++ or python.

**Comment by xfxyjwf** [comment]
It's not supported at the moment.

**Comment by liuweiming1997** [comment]
I also wanner know.
BTW, I am puzzle in how can i get protobuf if using `fetch` in frontend. it will return a readableStream in body? how can i parse it, does anybody did it before? thx a lot.

**Comment by liuweiming1997** [comment]
> I also wanner know.
> BTW, I am puzzle in how can i get protobuf if using `fetch` in frontend. it will return a readableStream in body? how can i parse it, does anybody did it before? thx a lot.

`response.bufferArray()`

**Comment by haon4** [comment]
Duping against #4309. Unfortunately we are not able to support json_format in JavaScript at the moment because we lack descriptor support in JS. Also see #1904.
