### ISSUE TITLE
[python] protobuf 3.5.2 - where's the generated doc?

### ISSUE THREAD

**Issue by chtseac** [protocolbuffers/protobuf#4498]
The [reference overview page][ref] links to the [generated documentation for version 3.0.0][ref-py]. This is an inconvenience for me as I was going to look at the documentation for `google.protobuf.json_format` to get the list of supported functions (which are not hard to get using either `help()` or just looking at [the source][src], but still.).

Is there a pipeline for generating that documentation or is it all done manually?

[ref]: https://developers.google.com/protocol-buffers/docs/reference/overview
[ref-py]: https://developers.google.com/protocol-buffers/docs/reference/python/
[src]: https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py

**Comment by xfxyjwf** [comment]
Right now all the documentation updates, pypi releases, etc are done manually...

**Comment by chtseac** [comment]
It's just a suggestion, but I think it would be beneficial to have a release checklist including documentation updates. Thank you for the quick response.

**Comment by nathanielmanistaatgoogle** [comment]
[A recent message on the discussion group](https://groups.google.com/forum/#!msg/protobuf/a5c_t8qcE8U/zhN53SFpBAAJ) points out a typo that [was fixed in source the day after the docs were last built](https://github.com/protocolbuffers/protobuf/commit/3886860aa46f6b8b7013f77baf7daeed9b7647c3).

**Comment by tswast** [comment]
I attempted to trigger a build of the Google internal `cloud-devrel/client-libraries/protobuf/docs/python` Kokoro job, but encountered an error at the `build_py` step.

```
Generating google/protobuf/internal/test_proto3_optional_pb2.py...
google/protobuf/internal/test_proto3_optional.proto:40:14: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

Possibly need to update the `protoc` version here: https://github.com/protocolbuffers/protobuf/blob/c777ade07bb5d64308a751ef17a9a33c7e94f301/kokoro/docs/publish-python.sh#L17

**Comment by tswast** [comment]
Note: There's a couple of CI things to do before closing out this issue:

1. Add docs presubmit check to ensure the docs always build.
2. Make the docs build a child job of the release build so that it's automatically triggered at release time.

**Comment by acozzette** [comment]
We are now updating the generated documentation regularly.
