### ISSUE TITLE
JSON: 'Any' message should serialize to/from bytes when the message type is not well known.

### ISSUE THREAD

**Issue by charlie430** [protocolbuffers/protobuf#4511]
## Problem
The [Any](https://developers.google.com/protocol-buffers/docs/proto3#any) message type specifies that in JSON the properties of the message serialized within an Any message should be serialized as properties.

> The JSON representation of an Any value uses the regular representation of the deserialized, embedded message, with an additional field `@type` which contains the type URL. Example:
>
> 
> ```
> package google.profile;
> message Person {
>   string first_name = 1;
>   string last_name = 2;
> }
> 
> {
>   "@type": "type.googleapis.com/google.profile.Person",
>   "firstName": <string>,
>   "lastName": <string>
> }
> ```
> [Reference](
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any)

This forces a system that serializes using JSON with unregistered types to either throw an error because it does not know how to parse an unregistered type ([code ref](https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/JsonParser.cs#L527)), or to gracefully skip the type and lose information ([pull request #4505](https://github.com/google/protobuf/pull/4505)). If the latter is chosen, then when serializing or deserializing the message, information is lost.

## Suggestion
When serializing to and from JSON, messages within an 'Any' message should serialize to and from bytes when the message type is not well known.

_Figure 1: Example of serializing an 'Any' message with not well known type to bytes_
```
{
  "@type": "type.googleapis.com/MyCustomType",
  "value": "eyAiZm9vIjogImJhciIgfQ==" // Base64 encoded bytes
}
```

## Use Case
I have many systems that use common message types, but do not have all message types registered in all systems. They only register the message types that are relevant to them.

If system X requests data from system Y and system Z, system X should not have to know what the message types are in order to pack them into an 'Any'.

## Thoughts
From my limited experience with Protocol Buffers, it seems like all message types have to be registered in the type registry in order to serialize and deserialize fully. This does not seem scalable when an organization shares thousands of message types, and messages are being sent to and from systems that need to modify message types that only they know how to modify, or add message types that only they know about. 

This does not seem to be a problem with binary serialization, as in practice, it uses the `@value` property. However, I don't see the `@value` property documented, so I don't know if this was intentional or not.

_Figure 2: Binary serialization uses the `@value` property when deserializing an unregistered type_
![image](https://user-images.githubusercontent.com/3875827/38760950-1f09337e-3f4d-11e8-9c7a-9b1f153bfbdc.png)

_Thank you for taking the time to read through this issue._

**Comment by charlie430** [comment]
I found this issue which may be discussing an alternate solution: https://github.com/google/protobuf/issues/658

**Comment by emcfarlane** [comment]
This issue is affecting a middleware gRPC proxy that translates messages from Proto to JSON. On RPC errors, details commonly contain `Any` and if unable to resolve the type we are forced to either: 1. drop the error and raise a resolver error, or 2. convert the error into a message type we understand which upstream then must be able to decode.

Would be great to have support for `Any` to be encoded in JSON as `{"@type": "<url>", "@value": "<bytes>"}`. Then the fallback is well defined and the client can handle it gracefully.
