### ISSUE TITLE
c++17 template warning

### ISSUE THREAD

**Issue by wony-zheng** [protocolbuffers/protobuf#4539]
when i compile in vs2017 use c++17, it show this warning:

warning C4996: 'std::iterator<std::random_access_iterator_tag,Element,ptrdiff_t,_Ty*,_Ty&>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by jeffreylindsey** [comment]
I also encountered this warning as an error.

Pull request #5014 fixes this issue.

**Comment by haon4** [comment]
#5014 was merged. Closing this.
