### ISSUE TITLE
protobuf fatal exception in tensorrt mnist model example

### ISSUE THREAD

**Issue by Arihe12th** [protocolbuffers/protobuf#4547]
I am trying to run tensorrt python API code which given in this link https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/topics/topics/workflows/caffe_to_tensorrt.html

that code is example of optimizing MNIST model using tensorrt in caffe I don"t find predefined mnist inside caffe/data/mnist folder so i used mnist.caffe,mnist.prototxt,mean.binaryproto form this github link https://github.com/DigitalGlobe/gbdx-caffe/tree/master/work/input/model.

while running the code I am getting this protobyf error

[libprotobuf FATAL /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/externals/protobuf/x86_64/10.0/include/google/protobuf/repeated_field.h:1078] CHECK failed: (index) < (current_size_):
terminate called after throwing an instance of 'google_private::protobuf::FatalException'
what(): CHECK failed: (index) < (current_size_):
Aborted (core dumped)

can anyone help me to solve this. and it will more be help full is there demo on optimizing mnist build using caffe in tensorrt .

**Comment by anandolee** [comment]
Can you try to come up with a example which contains protobuf related code only? It is too hard for us to navigate through tensorrt and the link you provided

**Comment by elharo** [comment]
Likely a tensorsort bug.
