### ISSUE TITLE
enumField grammar doesn't allow negative values

### ISSUE THREAD

**Issue by stepancheg** [protocolbuffers/protobuf#4561]
[Grammar](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec) of `enumField`:

```
enumField = ident "=" intLit [ "[" enumValueOption { ","  enumValueOption } "]" ]";"
intLit     = decimalLit | octalLit | hexLit
decimalLit = ( "1" … "9" ) { decimalDigit }
octalLit   = "0" { octalDigit }
hexLit     = "0" ( "x" | "X" ) hexDigit { hexDigit } 
```

So this should be invalid enum field declaration because negative values are not allowed.

```
SPARSE_D = -15;
```

However, this declaration exists in [protobuf unittest](https://github.com/google/protobuf/blob/a21f225824e994ebd35e8447382ea4e0cd165b3c/src/google/protobuf/unittest.proto#L533).

**Comment by jhump** [comment]
This appears to have been fixed. The grammars for both proto2 and proto3 both now have the following production, explicitly allowing a minus sign:

```
enumField = ident "=" [ "-" ] intLit [ "[" enumValueOption { ","  enumValueOption } "]" ]";"
```
