### ISSUE TITLE
ruby: encode - decode fails on map_string_enum case

### ISSUE THREAD

**Issue by marvin5064** [protocolbuffers/protobuf#4580]
I m experience some encode - decode fails on map_string_enum case for **ruby**

taking example from https://github.com/google/protobuf/blob/fc922d16ed7ae3c19defe82228a9760f3d8d1073/ruby/tests/generated_code.proto
(current latest commit)

test code, _please ignore absent of further assertion_
```
    # decode - encode on map_string_enum
    known_msg = A::B::C::TestMessage.new(
      map_string_enum: {'a' => A::B::C::TestEnum::A}
    )
    from = A::B::C::TestMessage.encode(known_msg)
    m = A::B::C::TestMessage.decode(from)
```

and the error message:
```
    35:       map_string_enum: {'a' => A::B::C::TestEnum::A}
     36:       )
     37:     from = A::B::C::TestMessage.encode(known_msg)
  => 38:     m = A::B::C::TestMessage.decode(from)

/Users/<censorship>/protobuf/ruby/tests/encode_decode_test.rb:38:in `decode'
Error: test_discard_unknown(EncodeDecodeTest): TypeError: wrong argument type nil (expected Google::Protobuf::EnumDescriptor)
```

extra info
```
➜  ruby git:(master) ✗ gem list | grep protobuf
google-protobuf (3.5.2, 3.4.1.1 universal-darwin, 3.4.0.2 universal-darwin, 3.3.0 universal-darwin)
protobuf (3.8.1, 3.7.5)
➜  ruby git:(master) ✗ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
➜  ruby git:(master) ✗ protoc --version
libprotoc 3.5.1
```

**Comment by TeBoring** [comment]
I'll fix it.

**Comment by raroman** [comment]
ping on this bug, also experiencing and blocked – do you know when we can expect a fix? thanks @TeBoring for consideration!

**Comment by marvin5064** [comment]
any update?

**Comment by sorah** [comment]
just sent PR #6262. As deeply looking into Ruby binding code base, I imagined you might be thinking refactoring stuff to fix the issues more appropriately, but letting this bug unfixed for a year is terrible. Hope my PR helps.
