### ISSUE TITLE
please provide separate tar balls for language bindings

### ISSUE THREAD

**Issue by pravi** [protocolbuffers/protobuf#4588]
Even though the release page lists different tarballs per languages, all of them has all source code. This means we have to manually separate the ruby binding for every release when making a debian package.

**Comment by xfxyjwf** [comment]
@pravi Every package has C++ source code because the protocol compiler is in C++ only. Are you asking for a release package that contains ruby source code only? How are you going to use it without the protoc?

**Comment by pravi** [comment]
@xfxyjwf we have a separate package in debian that provides protocol-compiler https://tracker.debian.org/pkg/protobuf

yes, a ruby only release tarball, corresponding to the google-protobuf rubygem, would be good.

**Comment by haberman** [comment]
Can't a single source package correspond to multiple binary packages in Debian?

I would think that the protobuf source package should generate binary packages for each separate language.

Our per-language tarballs get very few downloads, and we are planning to deprecate/remove them.
