### ISSUE TITLE
Syntax statement specification inconsistency?

### ISSUE THREAD

**Issue by austinbes** [protocolbuffers/protobuf#4589]
The [proto3 language spec](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#syntax) specifies a syntax statement as being of the form:

```
syntax = "syntax" "=" quote "proto3" quote ";
```

where a [`quote` literal](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#string_literals) is specified as

```
quote = "'" | '"'
```

This seems like it leaves room for syntax statements of the form

```
syntax = 'proto3";
syntax = "proto3';
```

However, `protoc` rejects either of these forms -- as I would expect it to. This seems like an inconsistency (though a quite minor one) between the specification and the compiler behavior.

**Comment by wvxvw** [comment]
This is basically an extension of  #4286
