### ISSUE TITLE
Generated protolite code triggers errorprone

### ISSUE THREAD

**Issue by kurtisnelson** [protocolbuffers/protobuf#4597]
When using Gradle + ErrorProne, the generated protolite code triggers the case fall through check.
I can workaround by turning generated code errors into warnings.

**Comment by kurtisnelson** [comment]
/Users/kurt/workspace/hopthru-android/app/build/generated/source/proto/devFlavorDebug/javalite/com/hopthru/ticketing/PurchasedTicket.java:1581: warning: [MissingOverride] dynamicMethod implements method in GeneratedMessageLite; expected @Override
  protected final Object dynamicMethod(
                         ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override protected final Object dynamicMethod('?
/Users/kurt/workspace/hopthru-android/app/build/generated/source/proto/devFlavorDebug/javalite/com/hopthru/ticketing/PurchasedTicket.java:1781: warning: [FallThrough] Execution may fall through from the previous case; add a `// fall through` comment before this line if it was deliberate
      case GET_DEFAULT_INSTANCE: {
      ^
    (see http://errorprone.info/bugpattern/FallThrough)

**Comment by xfxyjwf** [comment]
Can you follow these instructions to regenerate your code?
https://github.com/google/protobuf/blob/master/java/lite.md

**Comment by googleberg** [comment]
This seems to have been addressed in recent versions please reopen if there are remaining issues.
