### ISSUE TITLE
RepeatedScalarFieldContainer does not implement "index"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#4599]
[The documentation says "Repeated fields are represented as an object that acts like a Python sequence"](https://developers.google.com/protocol-buffers/docs/reference/python-generated#fields), but [the class of that object, RepeatedScalarFieldContainer](https://github.com/google/protobuf/blob/92898e9e9cb2f1c006fcc5099c9c96eafce63dc8/python/google/protobuf/internal/containers.py#L230-L338), does not implement [the `.index` method](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) of [the Sequence type](https://docs.python.org/3/library/typing.html#typing.Sequence).

It should be possible to call `.index` on such an object.

**Comment by nathanielmanistaatgoogle** [comment]
Any way to push forward on this? It smells easy enough to implement and would make a big difference in usability.

**Comment by xfxyjwf** [comment]
@nathanielmanistaatgoogle Probably send a CL to Jie? This seems a noncontroversial change.

**Comment by zhangskz** [comment]
Closing since Protobuf team is unlikely to get to this. Please reopen if this is still important.

Unfortunately while this may make sense for Python the pattern doesn't necessarily make sense for other languages, and this would warrant further review to decide whether this should be supported.
