### ISSUE TITLE
\x00 or \000 in string literals when red from text representation

### ISSUE THREAD

**Issue by wvxvw** [protocolbuffers/protobuf#4621]
If using text representation of a message I try to provide value as `"\x00"` or `"\000"` or `"\0"`, the lexer (seems so) breaks (doesn't accept input) with 

```
E           input:6:43: Invalid control characters encountered in text.
E           input:6:44: Expected ",", found "foo".
```

(foo in the message above just happened to be the next token, not related to the problem).  Other sequences seem to work, eg. `"\x01"` does work as well as `"\001"`.  What is so special about `\x00`?

**Comment by acozzette** [comment]
@wvxvw Could you post an example of the input that is not being parsed successfully?

**Comment by wvxvw** [comment]
Suppose you have a definition:

``` protobuf
message Test {
    string test = 1;
}
```
Then you call `protoc` like this:

```
echo 'test: "foo\x00bar"' | protoc --encode=Test -I. 
```
it will break.

**Comment by acozzette** [comment]
Which version are you using? I gave this a try using protoc built from master and it seemed to do the right thing:
```
$ echo 'test: "foo\x00bar"' | protoc --encode=Test test.proto | xxd
00000000: 0a07 666f 6f00 6261 72                   ..foo.bar
```

**Comment by wvxvw** [comment]
I'm using 3.0.0

**Comment by wvxvw** [comment]
The test above wasn't actually done the way I wrote. Monday, I'll give you the exact way to reproduce it. Sorry, I'm not on my work machine right now.

**Comment by haon4** [comment]
Closing as not reproducible.
