### ISSUE TITLE
Warning message when build protobuf lite

### ISSUE THREAD

**Issue by yejw5** [protocolbuffers/protobuf#4628]
*Version: Ubuntu 16.0.4, bazel 0.12.0, protobuf v3.4.0/v3.5.1* 

When add protobuf lite C++ as deps of my project and build with bazel tools, there are some `-Wunused-parameter` warnings. We hope to build our project with `--copt=-Werror`, these warnings will report as errors and terminate building process. Is there any plan to fix this situation?

The total warning log as follows:
```
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:325:37: warning: unused parameter 'cached_s
ize' [-Wunused-parameter]
                               int32 cached_size, ArrayOutput* output) {
                                     ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:690:73: warning: unused parameter 'tag' [-W
unused-parameter]
 void UnknownFieldSerializerLite(const uint8* ptr, uint32 offset, uint32 tag,
                                                                         ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:691:40: warning: unused parameter 'has_offs
et' [-Wunused-parameter]
                                 uint32 has_offset,
                                        ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc: In instantiation of 'static void google::p
rotobuf::internal::PackedFieldHelper<9>::Serialize(const void*, const google::protobuf::internal::FieldMetadata&, O*) 
[with O = google::protobuf::io::CodedOutputStream]':
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:610:7:   required from here
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:508:37: warning: unused parameter 'field' [
-Wunused-parameter]
   static void Serialize(const void* field, const FieldMetadata& md, O* output) {
                                     ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:508:72: warning: unused parameter 'output' 
[-Wunused-parameter]
   static void Serialize(const void* field, const FieldMetadata& md, O* output) {
                                                                        ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc: In instantiation of 'static void google::p
rotobuf::internal::PackedFieldHelper<9>::Serialize(const void*, const google::protobuf::internal::FieldMetadata&, O*) 
[with O = google::protobuf::internal::ArrayOutput]':
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:653:7:   required from here
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:508:37: warning: unused parameter 'field' [
-Wunused-parameter]
   static void Serialize(const void* field, const FieldMetadata& md, O* output) {
                                     ^
external/com_google_protobuf/src/google/protobuf/generated_message_util.cc:508:72: warning: unused parameter 'output' 
[-Wunused-parameter]
   static void Serialize(const void* field, const FieldMetadata& md, O* output) {
```

**Comment by acozzette** [comment]
I would recommend avoiding using `-Werror` and strict warnings for protobuf generated code. Since it's machine-generated code, it often has an un-idiomatic style and it would require extra complexity to try to make the code generator smart enough to avoid all warnings.

**Comment by hlopko** [comment]
Hello all,

we discussed this internally in the context of [this Bazel pull request](https://github.com/bazelbuild/bazel/pull/5467) and we reached the conclusion that protoc should to the best of its efforts not produce warning-triggering code. I expect that protobuf team will reopen this issue (or reference a new tracking issue for this effort) soon.

Thank you!

**Comment by yejw5** [comment]
@hlopko @acozzette Many thanks！

**Comment by logankaser** [comment]
Any updates?, these warnings are make it very hard to see the warnings in my local code by producing so many errors.

**Comment by keith** [comment]
These warnings are fixed, and warnings as errors are enabled on CI now. The current RC release should show no warnings.

**Comment by logankaser** [comment]
I'm getting error from: https://github.com/protocolbuffers/protobuf/blob/b4f193788c9f0f05d7e0879ea96cd738630e5d51/src/google/protobuf/map_type_handler.h#L531
(ctx is unused)
and
https://github.com/protocolbuffers/protobuf/blob/b4f193788c9f0f05d7e0879ea96cd738630e5d51/src/google/protobuf/arena.h#L690
(value is unused)
Maybe this is a seperate issue?

**Comment by keith** [comment]
Here's the CI command being run https://github.com/protocolbuffers/protobuf/blob/fcfc47d405113b59bd43c2e54daf5d9fe5c44593/kokoro/linux/bazel/build.sh#L9-L10 so it depends if you can reproduce it building this specific target. If not maybe we should add these flags elsewhere too

**Comment by BSBandme** [comment]
Deprioritize to p3 as this may not happen in the near future.
