### ISSUE TITLE
option optimize_for = SPEED; shouldn't parse

### ISSUE THREAD

**Issue by wvxvw** [protocolbuffers/protobuf#4640]
If you look at `goolge/protobuf/descriptor.proto`, it contains this:

```
option optimize_for = SPEED;
```

This should **not** parse according to both proto2 and proto3 language spec, but `protoc` accepts this w/o even a warning...

To clarify: my understanding was that identifiers may only be introduced using keywords s.a. `message`, `enum`, `option` etc.  Having and identifier that doesn't identify anything looks wrong.  In this case the intentions seems like it would have been better expressed by having an enumeration with members such as `SPEED`, `CODE_SIZE` and whatever other options are available, and use that instead.

**Comment by xfxyjwf** [comment]
@wvxvw Can you explain your use case? As far as I know the language spec is for documentation purpose only and does not define how protoc actually behaves (i.e., the protoc is not implemented to the spec). If you want to parse .proto files, using protoc is the only way and we do not support parsers in any other language.

**Comment by wvxvw** [comment]
My use-case: I'm writing my own implementation of the parser.  I worked under assumption that identifiers must resolve to definitions (this is what normally happens in programming languages, this is the basic difference between an identifier and a keyword), but `SPEED` in the example above doesn't resolve to anything.  It is treated as self-evaluating symbol (eg. like a number or a boolean).

> As far as I know the language spec is for documentation purpose only

This is kind of... frustrating to say the least.  If it's an open-source technology, which is meant for being implementable by multiple independent parties, that's, well, not a good approach.

----

In practical terms, I'd prefer if in the future versions `protoc` disallowed the use of identifiers that haven't been introduced through language mechanisms, or at least warn about such use.  The code above could have easily being a mistake, s.a. typo.

Better yet: disallow the use of identifiers in options definition altogether.  Just use string literals instead.

**Comment by xfxyjwf** [comment]
Protobuf is an opensource technology but there are use cases that we protobuf-team support and there are use cases that we don't support. Implementing your own parser is one use case that we don't support.
