### ISSUE TITLE
//:python_srcs doesn't play nice with other Google libraries

### ISSUE THREAD

**Issue by calder** [protocolbuffers/protobuf#4658]
`//:python_srcs` doesn't include [`python/google/__init__.py`](https://github.com/google/protobuf/blob/master/python/google/__init__.py) in its `srcs` glob. Without it, protobuf exclusively defines a top-level `google` namespace which breaks other packages like [google-auth](https://google-auth.readthedocs.io/en/latest/) that expect to share the `google` namespace.

**Comment by mishas** [comment]
Is there any expectation to when this will get released? (I don't want to use the master branch in my project, if possible).
This is already merged for more than 2 months...
There were 2 major releases since this got merged (3.6.0 and 3.6.1), and 3 additional minor once (3.6.0rc1,3.6.0rc2 and 3.6.0.1), and none of them had this fix in them.

**Comment by xfxyjwf** [comment]
@mishas 3.6.x branch will not have this fix unless someone cherry-picks the change to that branch.

@anandolee Jie, can you evaluate whether we should cherry-pick the fix for this issue and include it in another 3.6.x patch release?

**Comment by anandolee** [comment]
If we are going to have another 3.6.x release, I can do the cherrypick. But not worth to do another 3.6.X release only for this change.
@xfxyjwf I guess there's no plan for another 3.6.x release so far?

**Comment by Flamefire** [comment]
Do I understand this correct, that this will install an `__init__.py` in the `google` folder? If so, then please don't! It will break using different folders with google.* packages and is completely unnecessary for Python >= 3.3 (2.7 will drop out of support by the end of the year, and 3.3 and below already are)

See http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-init-py-trap for details.
