### ISSUE TITLE
String field contains invalid UTF-8 data when parsing a protocol buffer

### ISSUE THREAD

**Issue by zhengchengbin610** [protocolbuffers/protobuf#4691]
Hi  all,
I  use java client send a  pb buffer data to c++ server ,but when parse the pb buffer appear exception,
I  find the java use a unicode string code default . how and where to set the java protobuf use UTF8 encode?  

the  log ：
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:629] String field 'MqttPayload.header' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Comment by acozzette** [comment]
@zhengchengbin610 As long as it's a `string` field, the Java side should already be encoding it as UTF-8. Java internally uses UTF-16 for strings but the protobuf implementation will serialize strings to UTF-8. Could you provide some more details of the message schema and maybe an example of a serialized message that has a non-UTF8 string?

**Comment by wli600** [comment]
We are seeing similar issue, and we are using proto3, with java on message_lite API and C++ with full message API. 

More details, in Java, the serialization is done via `toByteArray` method, and I have tried to use different methods calling from C++, `ParseFromCodedStream` vs. `CopyFromArray`, and they both gave the same error.

versions: java:   3.6.0 and c++ is 3.6.1

error message:
protobuf/src/src/google/protobuf/wire_format_lite.cc:626] String field '######' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Comment by rxreyn3** [comment]
I am also seeing the same issue with java, running a curl command and piping directly to protoc installed on my mac from brew. ex.:  

`#!/bin/bash

curl -s -X \
	POST "http://localhost:8080/cheat/battle/v1/spawnSkirmishesCheat?difficulty=1&spawnCount=1" \
	-H "accept: application/x-protobuf" \
	-H "X-Client-Version: 5.0" \
	-H "X-Config-Id: local" \
	-H "EADP-PERSONA-ID: 282fb17ea42a293724b58dbda676ac37789f9d87-2018-11-14T16:11Z" \
	-H "EADP-AUTH-TOKEN: EditorUseOnly" \
	-H "X-EADP-Client-Id: pvz3-swagger" 2>&1 | \
	protoc --decode SkirmishDefinition ./shared/meta/SkirmishConfig.proto`

results in: 

`[libprotobuf ERROR google/protobuf/wire_format_lite.cc:626] String field 'SkirmishDefinition.InstanceId' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
Failed to parse input.`

**Comment by ml232528** [comment]
protobuf 3.6.1
same issue with c++

**Comment by jaikrishnak9** [comment]
Hi All,
I also have the similar problem, but it is in C++. Could you please helm me how to resolve this kind of errors .
Thanks
JK

**Comment by joshgi** [comment]
I have a 100% repo of this. It seem that if you serialize a string that is not strictly utf8 compliant in c++ and attempt to deserialize it in java. Java will throw an exception. My current work around is to base64 strings in c++ and decode it in java.

**Comment by joshgi** [comment]
@r4nd0m6uy We use the absl library in c++ and call "Base64Escape" to encode the string then on the receiving end of the proto we decode it.

c++
https://github.com/abseil/abseil-cpp/blob/12bc53e0318d80569270a5b26ccbc62b52022b89/absl/strings/escaping.h

java
https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Decoder.html

**Comment by jaggernaut007** [comment]
same issue converting saved model to tflite.
Any updates?

**Comment by so1ov** [comment]
Same here. What confuses me the most is a mismatch between standard C++ string type, autogenerated mutators taking that type, and an actual constraint you cannot store vanilla strings in protobuf.

**Comment by elharo** [comment]
There's an open issue about this for Java too. In some edge cases, strings that contain invalid Unicode sequences — for instance because of mismatched surrogates — get written into the proto as invalid UTF-8. We should fail earlier when the bad string is first written.

**Comment by jorgbrown** [comment]
Closing this as user error.
