### ISSUE TITLE
protoc has issues with output paths and plugin paths with Windows 10

### ISSUE THREAD

**Issue by tnavda** [protocolbuffers/protobuf#4708]
Both issues in command_line_interface.cc version 3.5.1
Both issues were replicated by running the project in Visual Studio.
Command line arguments used in VS
`"--cpp_out=blah" "--grpc_out=blah" "--plugin=protoc-gen-grpc=grpc_cpp_plugin.exe" --proto_path=C:\code\grpc\grpc\examples\protos\ helloworld.proto`

1.  This keeps relative paths for out directories from working.  At line 904
`if (HasSuffixString(location, "/")) {`

I think should be `if (HasSuffixString(location, "\\") || HasSuffixString(location, "/")) {` to handle Windows path separator.  Otherwise it will fall into the write to Zip at line 914: `if (!directory->WriteAllToZip(location)) {`

2.  In 3.5.1 at line 1937, below code never fires in ::SEARCH_PATH when the command line arguments are declared as:  "--plugin=protoc-gen-grpc=grpc_cpp_plugin.exe"

The only way I could get it to work is by specifying the full path to the plugin.

`  if (plugins_.count(plugin_name) > 0) {
    subprocess.Start(plugins_[plugin_name], Subprocess::EXACT_NAME);
  } else {
    subprocess.Start(plugin_name, Subprocess::SEARCH_PATH);
  }`

**Comment by acozzette** [comment]
@tnavda Do you want to send us a pull request with these fixes?

**Comment by tnavda** [comment]
acozzette,

I moved on from this, and I'd have to get back into it to do a pull request.  I just wanted to share the issues I found and what I thought were the root cause.

**Comment by acozzette** [comment]
Ok, no problem, thanks for the bug report!

**Comment by fowles** [comment]
Closing out old issues.  Please reopen if this still occurs on recent releases.
