### ISSUE TITLE
NDK-build compile protocol-cpp-3.5.1 failed

### ISSUE THREAD

**Issue by zhengchengbin610** [protocolbuffers/protobuf#4722]
Hello everyone, we plan to use protocol buffer, but during the verification process we found that the java version used between Android and cpp doesn't work well with the string type, and there will be coding problems. So now we plan to change the cpp version to write jni for communication, but when porting cpp source code, it has been reported incorrectly and cannot be solved. It has been bothering me for days. I hope someone can help me. I will put my Android.mk and Application.mk is issued. Thank you first.

--------------------------------------------Application.mk---------------------------------------
Application.mk
    STLPORT_FORCE_REBUILD := false
   APP_STL := c++_static
   APP_PLATFORM := android-9
   APP_ABI := armeabi-v7a
--------------------------------------------Android.mk-------------------------------------------
Android.mk
  LOCAL_PATH := $(call my-dir)
  include $(CLEAR_VARS)

  LOCAL_MODULE    := libprotobuf

   LOCAL_C_INCLUDES += \
	$(LOCAL_PATH)/ \
	$(LOCAL_PATH)/src/ \
	$(LOCAL_PATH)/src/google/protobuf/ \
	$(LOCAL_PATH)/src/google/protobuf/io/ \
	$(LOCAL_PATH)/src/google/protobuf/stubs/ \
	$(LOCAL_PATH)/src/google/protobuf/util/ \
	$(LOCAL_PATH)/src/google/protobuf/util/internal 
	
lite_SOURCES =                                  \
 $(LOCAL_PATH)/src/google/protobuf/stubs/bytestream.cc                          \
 $(LOCAL_PATH)/src/google/protobuf/stubs/bytestream.h                           \
 $(LOCAL_PATH)/src/google/protobuf/stubs/common.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/stubs/hash.h                                 \
 $(LOCAL_PATH)/src/google/protobuf/stubs/int128.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/stubs/int128.h                               \
 $(LOCAL_PATH)/src/google/protobuf/stubs/io_win32.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/stubs/io_win32.h                             \
 $(LOCAL_PATH)/src/google/protobuf/stubs/map_util.h                             \
 $(LOCAL_PATH)/src/google/protobuf/stubs/mathutil.h                             \
 $(LOCAL_PATH)/src/google/protobuf/stubs/once.cc                                \
 $(LOCAL_PATH)/src/google/protobuf/stubs/shared_ptr.h                           \
 $(LOCAL_PATH)/src/google/protobuf/stubs/status.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/stubs/status.h                               \
 $(LOCAL_PATH)/src/google/protobuf/stubs/status_macros.h                        \
 $(LOCAL_PATH)/src/google/protobuf/stubs/statusor.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/stubs/statusor.h                             \
 $(LOCAL_PATH)/src/google/protobuf/stubs/stringpiece.cc                         \
 $(LOCAL_PATH)/src/google/protobuf/stubs/stringpiece.h                          \
 $(LOCAL_PATH)/src/google/protobuf/stubs/stringprintf.cc                        \
 $(LOCAL_PATH)/src/google/protobuf/stubs/stringprintf.h                         \
 $(LOCAL_PATH)/src/google/protobuf/stubs/structurally_valid.cc                  \
 $(LOCAL_PATH)/src/google/protobuf/stubs/strutil.cc                             \
 $(LOCAL_PATH)/src/google/protobuf/stubs/strutil.h                              \
 $(LOCAL_PATH)/src/google/protobuf/stubs/time.cc                                \
 $(LOCAL_PATH)/src/google/protobuf/stubs/time.h                                 \
 $(LOCAL_PATH)/src/google/protobuf/arena.cc                                     \
 $(LOCAL_PATH)/src/google/protobuf/arenastring.cc                               \
 $(LOCAL_PATH)/src/google/protobuf/extension_set.cc                             \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_util.cc                    \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_table_driven_lite.h        \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_table_driven_lite.cc       \
 $(LOCAL_PATH)/src/google/protobuf/message_lite.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/repeated_field.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/wire_format_lite.cc                          \
 $(LOCAL_PATH)/src/google/protobuf/io/coded_stream.cc                           \
 $(LOCAL_PATH)/src/google/protobuf/io/coded_stream_inl.h                        \
 $(LOCAL_PATH)/src/google/protobuf/io/zero_copy_stream.cc                       \
 $(LOCAL_PATH)/src/google/protobuf/io/zero_copy_stream_impl_lite.cc

libprotobuf_SOURCES =                                       \
  $(lite_SOURCES)                               \
 $(LOCAL_PATH)/src/google/protobuf/any.pb.cc                                    \
 $(LOCAL_PATH)/src/google/protobuf/api.pb.cc                                    \
 $(LOCAL_PATH)/src/google/protobuf/stubs/mathlimits.cc                          \
 $(LOCAL_PATH)/src/google/protobuf/stubs/mathlimits.h                           \
 $(LOCAL_PATH)/src/google/protobuf/any.cc                                       \
 $(LOCAL_PATH)/src/google/protobuf/descriptor.cc                                \
 $(LOCAL_PATH)/src/google/protobuf/descriptor_database.cc                       \
 $(LOCAL_PATH)/src/google/protobuf/descriptor.pb.cc                             \
 $(LOCAL_PATH)/src/google/protobuf/duration.pb.cc                               \
 $(LOCAL_PATH)/src/google/protobuf/dynamic_message.cc                           \
 $(LOCAL_PATH)/src/google/protobuf/empty.pb.cc                                  \
 $(LOCAL_PATH)/src/google/protobuf/extension_set_heavy.cc                       \
 $(LOCAL_PATH)/src/google/protobuf/field_mask.pb.cc                             \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_reflection.cc              \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_table_driven_lite.h        \
 $(LOCAL_PATH)/src/google/protobuf/generated_message_table_driven.cc            \
 $(LOCAL_PATH)/src/google/protobuf/map_field.cc                                 \
 $(LOCAL_PATH)/src/google/protobuf/message.cc                                   \
 $(LOCAL_PATH)/src/google/protobuf/reflection_internal.h                        \
 $(LOCAL_PATH)/src/google/protobuf/reflection_ops.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/service.cc                                   \
 $(LOCAL_PATH)/src/google/protobuf/source_context.pb.cc                         \
 $(LOCAL_PATH)/src/google/protobuf/struct.pb.cc                                 \
 $(LOCAL_PATH)/src/google/protobuf/stubs/substitute.cc                          \
 $(LOCAL_PATH)/src/google/protobuf/stubs/substitute.h                           \
 $(LOCAL_PATH)/src/google/protobuf/text_format.cc                               \
 $(LOCAL_PATH)/src/google/protobuf/timestamp.pb.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/type.pb.cc                                   \
 $(LOCAL_PATH)/src/google/protobuf/unknown_field_set.cc                         \
 $(LOCAL_PATH)/src/google/protobuf/wire_format.cc                               \
 $(LOCAL_PATH)/src/google/protobuf/wrappers.pb.cc                               \
 $(LOCAL_PATH)/src/google/protobuf/io/gzip_stream.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/io/printer.cc                                \
 $(LOCAL_PATH)/src/google/protobuf/io/strtod.cc                                 \
 $(LOCAL_PATH)/src/google/protobuf/io/tokenizer.cc                              \
 $(LOCAL_PATH)/src/google/protobuf/io/zero_copy_stream_impl.cc                  \
 $(LOCAL_PATH)/src/google/protobuf/compiler/importer.cc                         \
 $(LOCAL_PATH)/src/google/protobuf/compiler/parser.cc                           \
 $(LOCAL_PATH)/src/google/protobuf/util/delimited_message_util.cc               \
 $(LOCAL_PATH)/src/google/protobuf/util/field_comparator.cc                     \
 $(LOCAL_PATH)/src/google/protobuf/util/field_mask_util.cc                      \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/constants.h                    \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/datapiece.cc                   \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/datapiece.h                    \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/default_value_objectwriter.cc  \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/default_value_objectwriter.h   \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/error_listener.cc              \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/error_listener.h               \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/expecting_objectwriter.h       \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/field_mask_utility.cc          \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/field_mask_utility.h           \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_escaping.cc               \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_escaping.h                \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_objectwriter.cc           \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_objectwriter.h            \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_stream_parser.cc          \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/json_stream_parser.h           \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/location_tracker.h             \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/mock_error_listener.h          \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/object_location_tracker.h      \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/object_source.h                \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/object_writer.cc               \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/object_writer.h                \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/protostream_objectsource.cc    \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/protostream_objectsource.h     \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/protostream_objectwriter.cc    \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/protostream_objectwriter.h     \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/proto_writer.cc                \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/proto_writer.h                 \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/structured_objectwriter.h      \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/type_info.cc                   \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/type_info.h                    \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/type_info_test_helper.cc       \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/type_info_test_helper.h        \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/utility.cc                     \
 $(LOCAL_PATH)/src/google/protobuf/util/internal/utility.h                      \
 $(LOCAL_PATH)/src/google/protobuf/util/json_util.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/util/message_differencer.cc                  \
 $(LOCAL_PATH)/src/google/protobuf/util/time_util.cc                            \
 $(LOCAL_PATH)/src/google/protobuf/util/type_resolver_util.cc

$(warning $(TARGET_ARCH))
LOCAL_SRC_FILES := $(lite_SOURCES)
ifeq ($(TARGET_ARCH),x86)
	LOCAL_SRC_FILES := $(LOCAL_SRC_FILES) \
										 src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc
endif
ifeq ($(TARGET_ARCH),x86_64)
	LOCAL_SRC_FILES := $(LOCAL_SRC_FILES) \
										 src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc
endif

LOCAL_CFLAGS += -DGOOGLE_PROTOBUF_NO_RTTI -DHAVE_PTHREAD
LOCAL_CPPFLAGS += #-std=c++11 #-fexceptions -frtti
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/stubs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/io
LOCAL_C_INCLUDES += $(LOCAL_PATH)

LOCAL_EXPORT_LDLIBS := -lz 
LOCAL_EXPORT_CFLAGS := $(LOCAL_CFLAGS)
LOCAL_EXPORT_CPPFLAGS := $(LOCAL_CPPFLAGS)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(BUILD_STATIC_LIBRARY)

--------------------------------- error  log -----------------------------------------------------
 Android NDK: android-9 is unsupported. Using minimum supported version android-14.    
/mnt/hgfs/ubuntu_e/protobuf-android-master/jni/Android.mk:143: arm
Android NDK: WARNING: Unsupported source file extensions in /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/Android.mk for module protobuf    
Android NDK:   /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/hash.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/int128.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/io_win32.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/map_util.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/mathutil.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/shared_ptr.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/status.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/status_macros.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/statusor.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/stringpiece.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/stringprintf.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/strutil.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/time.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/generated_message_table_driven_lite.h /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/io/coded_stream_inl.h    
[armeabi-v7a] Compile++ thumb: protobuf <= bytestream.cc
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.cc:31:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.h:54:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string:470:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string_view:169:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__string:56:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/algorithm:643:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/memory:650:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iterator:426:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iosfwd:90:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/wchar.h:119:
In file included from /home/zcb/soft/android-ndk-r17/sources/android/support/include/wchar.h:32:
In file included from /home/zcb/soft/android-ndk-r17/sysroot/usr/include/wchar.h:37:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/time.h:33:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/common.h:39:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iostream:38:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ios:216:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__locale:18:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/mutex:191:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__mutex_base:15:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/chrono:303:
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:59:9: error: no member named 'tm' in the global namespace
using ::tm;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:60:9: error: no member named 'clock' in the global namespace
using ::clock;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:61:9: error: no member named 'difftime' in the global namespace
using ::difftime;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:62:9: error: no member named 'mktime' in the global namespace; did you mean 'mktemp'?
using ::mktime;
      ~~^
/home/zcb/soft/android-ndk-r17/sysroot/usr/include/stdlib.h:68:7: note: 'mktemp' declared here
char* mktemp(char* __template) __attribute__((deprecated("mktemp is unsafe, use mkstemp or tmpfile instead")));
      ^
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.cc:31:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.h:54:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string:470:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string_view:169:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__string:56:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/algorithm:643:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/memory:650:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iterator:426:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iosfwd:90:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/wchar.h:119:
In file included from /home/zcb/soft/android-ndk-r17/sources/android/support/include/wchar.h:32:
In file included from /home/zcb/soft/android-ndk-r17/sysroot/usr/include/wchar.h:37:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/time.h:33:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/common.h:39:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iostream:38:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ios:216:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__locale:18:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/mutex:191:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__mutex_base:15:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/chrono:303:
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:63:9: error: no member named 'time' in the global namespace
using ::time;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:65:9: error: no member named 'asctime' in the global namespace
using ::asctime;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:66:9: error: no member named 'ctime' in the global namespace
using ::ctime;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:67:9: error: no member named 'gmtime' in the global namespace
using ::gmtime;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:68:9: error: no member named 'localtime' in the global namespace
using ::localtime;
      ~~^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ctime:70:9: error: no member named 'strftime' in the global namespace
using ::strftime;
      ~~^
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.cc:31:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.h:54:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string:470:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/string_view:169:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__string:56:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/algorithm:643:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/memory:650:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iterator:426:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iosfwd:90:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/wchar.h:119:
In file included from /home/zcb/soft/android-ndk-r17/sources/android/support/include/wchar.h:32:
In file included from /home/zcb/soft/android-ndk-r17/sysroot/usr/include/wchar.h:37:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/time.h:33:
In file included from /mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/common.h:39:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/iostream:38:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/ios:216:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__locale:18:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/mutex:191:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/__mutex_base:16:
In file included from /home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/system_error:231:
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:83:32: error: unknown type name 'string'
    explicit logic_error(const string&);
                               ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:100:34: error: unknown type name 'string'
    explicit runtime_error(const string&);
                                 ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:115:59: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit domain_error(const string& __s) : logic_error(__s) {}
                                                          ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:125:63: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit invalid_argument(const string& __s) : logic_error(__s) {}
                                                              ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:135:59: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit length_error(const string& __s) : logic_error(__s) {}
                                                          ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:145:59: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit out_of_range(const string& __s) : logic_error(__s) {}
                                                          ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:155:58: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit range_error(const string& __s) : runtime_error(__s) {}
                                                         ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:165:61: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit overflow_error(const string& __s) : runtime_error(__s) {}
                                                            ^
/home/zcb/soft/android-ndk-r17/sources/cxx-stl/llvm-libc++/include/stdexcept:175:62: error: unknown type name 'string'
    _LIBCPP_INLINE_VISIBILITY explicit underflow_error(const string& __s) : runtime_error(__s) {}
                                                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [/mnt/hgfs/ubuntu_e/protobuf-android-master/obj/local/armeabi-v7a/objs/protobuf//mnt/hgfs/ubuntu_e/protobuf-android-master/jni/src/google/protobuf/stubs/bytestream.o] Error 1
zcb@zcb-virtual-machine:/mnt/hgfs/ubuntu_e/protobuf-android-master/jni$

**Comment by haon4** [comment]
Closing due to lack of response. Please reopen if needed.
