### ISSUE TITLE
Undocumented options syntax

### ISSUE THREAD

**Issue by wvxvw** [protocolbuffers/protobuf#4726]
``` protobuf
syntax = "proto3";

service SomeService {
    rpc SomeMethod (Whatever) returns (Whatever) {
        option (google.api.http) = {
            delete : "/some/url"
            additional_bindings {
                delete: "/another/url"
            }
        };
    }
}
```
This shouldn't parse neither as v2 nor as v3, and yet it does, and some code apparently relies on this being possible.  It is really frustrating to discover all these "gotchas" after few months of having written a parser to the specification...

Not only `option (foo.bar) = { }` is invalid as of v3 language specification, but `additional_bindings { }` is invalid in principle, in any specification.  Having seen this, I cannot even begin to imagine what the actual grammar should look like: why is there no colon after `additional_bindings`?  Why isn't this written as `additional_bindings.delete: "/another/url"`?  How many sub-fields like this are allowed?  How deeply nested?  Do same rules apply to top-level blocks as the inner blocks?

**Comment by gonzojive** [comment]
Clues:

The code that does the parsing of options is "ParseOption" here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/parser.cc

These complex option values are put into UninterprettedOption's aggregate_value field: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/parser.cc#L1388

parser.ParseFromString is used to parse the aggregated_value here:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.cc#L7067
