### ISSUE TITLE
Missing mojo in Method and ServiceDescriptors

### ISSUE THREAD

**Issue by zunger-humu** [protocolbuffers/protobuf#4731]
I'm spinning up gRPC servers, and have discovered some unpleasant surprises in both MethodDescriptor (across the board) and in the stub classes which the Python protoc generates:

- MethodDescriptor has no information about whether the method is input- or output-streaming! (And from reading the protoc code, it doesn't seem to be stored anywhere in the descriptors)

- Python-specific issue: The generated FooStub and FooServicer classes have no links back to the ServiceDescriptor, nor vice-versa. You can't get to either of these classes from the symbol_database, and if you have these classes, the only way to get the corresponding descriptor is to string-mangle their names and look that up. Likewise, there's no programmatic way to find the `add_FooServiceServicer_to_server` method.

These both feel highly suboptimal for no good reason. I propose the following fixes:

- Cross-language: Add two boolean fields, `input_streaming` and `output_streaming`, to `MethodDescriptor`. (Or if people really prefer, encode this in `MethodOptions`, but that seems unnecessarily opaque given that these parameters are required for interpreting so many things about the method) Populate them in protoc.
- Python only: Extend the Python `SymbolDatabase` to have methods which can return the Stub and Servicer classes given a service name. (These would be populated in `RegisterServiceDescriptor` in much the same way they currently are for message types)
- Python only: In the generated Python Stub and Servicer classes, add an instance method returning the service descriptor. Move the brains of `add_ServiceNameServicer_to_server` to be a class method of the Servicer, and leave the existing function name as a pointer to that for backwards-compatibility.

This would make services and methods lookupable in basically the same way messages are today.

**Comment by xfxyjwf** [comment]
I think the existing client_streaming/server_streaming field in MethodDescriptorProto is used for exactly this purpose:
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L278-L281

For the missing descriptors in generated FooStub/FooService classes, I think that's a grpc issue and needs to be addressed to the grpc repo?

**Comment by zunger-humu** [comment]
For MethodDescriptor, it looks like you're right -- but the Python
MethodDescriptor class doesn't expose those fields! So this is py bug, not
a cross-language issue, and a much simpler one.

For the lack of generated descriptors, I think this overlaps the grpc and
proto repositories -- in particular, a key step would be to have
SymbolDatabase be aware of stubs. Is this part of the mainline proto code,
or would it be part of the "special" protoc etc. which lives in grpc?

**Comment by JoeStaines** [comment]
FYI i've also been hit by missing client_/server_streaming options within MethodDescriptor when creating plugins. It's a bit frustrating as i wanted to make use of input_type and output_type of MethodDescriptor (as opposed to MethodDescriptorProto, where i would have to re-do the work of gluing together the the Descriptors from the input and output type names), but it doesn't include the streaming options.

Even someway of getting the MethodDescriptorProto from a MethodDescriptor would have been nice, but doesn't look like thats an option

**Comment by JavaScriptBach** [comment]
> FYI i've also been hit by missing client_/server_streaming options within MethodDescriptor when creating plugins. It's a bit frustrating as i wanted to make use of input_type and output_type of MethodDescriptor (as opposed to MethodDescriptorProto, where i would have to re-do the work of gluing together the the Descriptors from the input and output type names), but it doesn't include the streaming options.
> 
> Even someway of getting the MethodDescriptorProto from a MethodDescriptor would have been nice, but doesn't look like thats an option

You can try doing this (obviously pretty hacky):

```
method_descriptor_proto = MethodDescriptorProto()
method_descriptor.CopyToProto(method_descriptor_proto)
server_streaming = method_descriptor_proto.server_streaming
...
```

**Comment by anandolee** [comment]
Sorry that but this may not an issue that protobuf team can help, gRPC might be a better place for this issue.
Closing it for clean up.
