### ISSUE TITLE
PHP FieldMasks json serialization is inconsistent for empty object

### ISSUE THREAD

**Issue by michaelbausor** [protocolbuffers/protobuf#4734]
An empty FieldMask is serialized to `""`, but this does not deserialize to an empty FieldMask object. This PHPUnit test fails:

```php
public function testJsonEquality()
{
  $fm = new FieldMask();
  $json = $fm->serializeToJsonString();
  $fm2 = new FieldMask();
  $fm2->mergeFromJsonString($json);
  $this->assertEquals($fm, $fm2);
}
```

**Comment by TeBoring** [comment]
I'll fix it.

**Comment by TeBoring** [comment]
There is an ambiguity in FieldMask: both {} and {"path":""} (in text format) have the json representation of "".
Because {"path":""} is actually an invalid FieldMask, we have decided the decoded result of "" should be {} (in text format).
