### ISSUE TITLE
Base64Unescape and Base64Escape do not inverse one-another on Android devices

### ISSUE THREAD

**Issue by chukrum47** [protocolbuffers/protobuf#4735]
Hello,

It appears that the `google::protobuf::Base64Unescape` and `google::protobuf::Base64Escape` methods do not correctly inverse each other when run on an Android device. I've included a minimal example below. 

```
std::string initial = "abcdefghijkl";
std::string temp1;
google::protobuf::Base64Unescape(initial.c_str(), &temp1);   
std::string final;
google::protobuf::Base64Escape(temp1.c_str(), &final);
//final = "eR23iiH4iiU5" 
```

Other information:
Device: Samsung Galaxy S7, Android version 7.0 (arm64-v8a architecture) 
Protobuf: v3.5.1
NDK: r15c

**Comment by acozzette** [comment]
@chukrum47 Thanks for the bug report. Would you be interested in sending out a pull request with a fix?

**Comment by BSBandme** [comment]
I tested on server side, the final field equals "abcdefghijkl" as expect. 
@acozzette do you have any idea of the difference between server and android side for this?

**Comment by acozzette** [comment]
The only thing I can think of is that in `stubs/strutil.cc` in `Base64EscapeInternal` there is some endianness logic and perhaps we're somehow getting the endianness wrong on Android but not Linux server builds. It would help to find out what the unescaped data looks like, so that we could tell if the problem is in `Base64Escape` or `Base64Unescape`.

**Comment by BSBandme** [comment]
@chukrum47 would you please provide the temp1 value on your device as well?

**Comment by chukrum47** [comment]
Sure thing! Note that all values were gathered with Android Studio's debugger, and I recently upgraded to Android version 8.0.0. 

I also tried running the same series of commands in reverse; so, Escaping then Unescaping. The result was also incorrect.

```
std::string initial = "abcdefghijkl";
std::string temp1; 
google::protobuf::Base64Unescape(initial.c_str(), &temp1); // temp1 = "i\xb7\x1dy�!\x8a9%" [note: the � is \xf8 according to the debugger]
std::string final; 
google::protobuf::Base64Escape(temp1.c_str(), &final);     // final = "eR23iiH4iiU5"

initial = "abcdefghijkl";
std::string temp2;
google::protobuf::Base64Escape(initial.c_str(), &temp2);   // temp2 = "ZGNiZ2Zlamloamxr"
std::string final2;
google::protobuf::Base64Unescape(temp2.c_str(), &final2);  // final2 = "dcbgfejihjlk"
```

Also, I've included the values when using my own minimal base64 encoder/decoder:
```
std::string initial = "abcdefghijkl";
std::string temp1;
temp1 = base64Unescape(initial.c_str()); // temp1 = "i\xb7\x1dy�!\x8a9%" 
std::string final;
final = base64Escape(temp1.c_str()); // final = "abcdefghijkl"

initial = "abcdefghijkl";
std::string temp2;
temp2 = base64Escape(initial.c_str()); // temp2 = "YWJjZGVmZ2hpamts"
std::string final2;
final2 = base64Unescape(temp2.c_str()); //final2 = "abcdefghijkl'
```

It appears the problem is with Base64Escape.

I haven't had a chance to dig into why this is happening yet, but for what it's worth I had encountered some similarly odd behavior as I was writing my own minimal base64 encoder/decoder. The cause for my problem had been that during the creation of the 24-bit intermediate pattern (3 octets/4 encoded characters), I had been assuming that there were 8 bits in each of the values that were being bitwise or'd together, but there were not and some bits were being overwritten. I fixed it by casting them to unsigned chars before or'ing.

**Comment by acozzette** [comment]
Hmm, that is interesting. The example of encoding and decoding `abcdefghijkl` shows that we get a string which is almost (but not quite) a permutation of the original: `dcbgfejihjlk` The first four bytes are almost reversed, which could hint at an endianness issue.

**Comment by chukrum47** [comment]
Also, that same code was tested on a physical iPhone 6 and on an iPhone 7 simulator, and in both cases it functioned correctly.

**Comment by BSBandme** [comment]
Thank you @chukrum47 for the detailed reporting! But I think this bug is limit to specific device that we don't have in hand. I just downgraded the priority for this bug and feel free to aug the priority when you want to. Or would you be interested in sending out a fixing PR?

**Comment by fowles** [comment]
Closing out old issues.  Please reopen if this still occurs on recent releases.
