### ISSUE TITLE
[PHP] Custom default value and JSON serialization

### ISSUE THREAD

**Issue by rok-povsic** [protocolbuffers/protobuf#4746]
Hello,

We have a proto message that has a float with custom default value (set with `utils.cl_default_float`) of 1.0.

The problem is that `serializeToJsonString` won't serialize a float that has a value of 0.0, because serialization skips all floats with a default 0.0 value,which is done here: https://github.com/google/protobuf/blob/00d32539c6aa0c4efe9577561a00f443edd9a417/php/src/Google/Protobuf/Internal/Message.php#L1408 

Could it be added to the library that either:
- we can set a custom default field value, so in our case we, at serialization, we skip floats 1.0 but not 0.0,
- default values are JSON serialized in any case, so we'd serialize 1.0 and 0.0.

Is any of these two things already possible? I've checked the code but haven't been able to come up with a solution without modifying the library code.

Thank you 

EDIT:
My current solution works without modifying the library code but is rough one: after protobuf serialization, I parse JSON back to an associative array structure with `json_decode`, recursively iterate it add the default 0.0 values wherever they're missing, and serialize back to JSON using `json_encode`.

**Comment by TeBoring** [comment]
This can be done in proto2 support. Unfortunately, I don't have time to implement that.

**Comment by haberman** [comment]
If you mark fields as `optional`, they will always serialize when you explicitly set them. You can use this to explicitly serialize `0.0` values.  This is a new feature introduced in 3.15.0 (Feb 2021).

There is also a feature currently in review that will allow to you serialize defaults for *all* fields: https://github.com/protocolbuffers/protobuf/pull/9124
