### ISSUE TITLE
travis fixes

### ISSUE THREAD

**Issue by grooverdan** [protocolbuffers/protobuf#4764]
I noticed that the travis builds seem to have stopped. 

Thanks for adding ppc64le support in #4401. Travis has a os: linux-ppc64le target that could be used if the CI within Google doesn't have one. I can provide PR.

I also notice the releases on github no-longer use a full set of binaries. Would you be interested in a PR that re-adds those when a tag is pushed? (https://docs.travis-ci.com/user/deployment/releases/)?

**Comment by xfxyjwf** [comment]
Thanks for offering help! Feel free to send us a pull request. We are abandoning travis for testing (to slow to finish) but using it for release still makes sense to me.

**Comment by grooverdan** [comment]
Ok, I see the maven repos are also missing deployment by looking at http://repo1.maven.org/maven2/com/google/protobuf/protoc/ https://oss.sonatype.org/#nexus-search;gav~com.google.protobuf~protobuf-java

Do you want this restored with travis too? If the internal CI is (meant to be) pushing to maven this would in a bit of a race with travis to use build-zip.sh (pulls from maven) to create zip files.

To push to maven from travis would require the encrypted gpg key to be in the travis repository (https://docs.travis-ci.com/user/encrypting-files/). Is this something that you are comfortable with?

Pushing to github just requires a ```public_repo``` token as a travis encrypted variable.

WIP: https://travis-ci.org/grooverdan/protobuf/builds/392558746 , few cross compile problems and OSX.
Please forgive any Maven stupidity, fairly new to it and the protobuf code.

**Comment by xfxyjwf** [comment]
@grooverdan I don't think we want travis to automatically push anything to maven. We just need it to build the artifacts.

**Comment by elharo** [comment]
no longer using travis
