### ISSUE TITLE
Undefined behavior in google::protobuf::io::CodedInputStream::ReadStringFallback

### ISSUE THREAD

**Issue by csharrison** [protocolbuffers/protobuf#4778]
See Chromium issue at https://crbug.com/853565 for more details. This was generated from passing fuzzed data into google::protobuf::MessageLite::ParseFromCodedStream.

As mentioned in the bug, looks like it could be integer underflow due to a large limit set in PushLimit. Please see the attached bug for input data.

**Comment by haberman** [comment]
Is there any way you can create a repro that doesn't require building Chromium? I started trying to reproduce this, but wasn't able to get the build working.

**Comment by csharrison** [comment]
Sorry I should have been clearer about how to reproduce in the bug. Reproducing does not require building all of Chromium, just a libfuzzer testcase that needs a piece of Chromium functionality. I don't have a more minimized test case at this time, but I'll give some clearer instructions.

Steps:
1. Follow the [build instructions](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md) for linux

2. Use the following GN args to configure your build:
enable_nacl = false
is_debug = false
is_ubsan_security = true
optimize_for_fuzzing = true
use_libfuzzer = true

3. autoninja -C out/<build dir> indexed_ruleset_fuzzer
4. ./out/<build dir>/indexed_ruleset_fuzzer <path/to/testcase_file>

**Comment by PeterWangNavisens** [comment]
The prefixLenLimit returns  2147483647

std::ifstream infile ("xxx.log",std::ifstream::binary);
google::protobuf::io::IstreamInputStream * istreamInputStream = new google::protobuf::io::IstreamInputStream(&infile);
google::protobuf::io::CodedInputStream* coded_input = new google::protobuf::io::CodedInputStream(istreamInputStream);

auto prefixLenLimit = coded_input->PushLimit(4);

**Comment by haberman** [comment]
Closing as obsolete. If this is still reproducible please reopen.
