### ISSUE TITLE
StringIntLabelMap causes issues for Tensorflow when I try to train (python v3.5).

### ISSUE THREAD

**Issue by amin-codes** [protocolbuffers/protobuf#4795]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python

**What did you do?**
1. I run the command `python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config` from command prompt from within the "object_detection" folder.
2. See error

**What did you expect to see**
I expected Tensorflow to successfully train using my images.

**What did you see instead?**
An error log.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Half of error: https://i.stack.imgur.com/AspmT.png
Second half of error: https://i.stack.imgur.com/6HbR0.png

**Anything else we should know about your project / environment**
I have tried uninstalling and reinstalling tensorflow, protobuf, and all dependents of tensorflow using pip3, but I have had no success. I even tried deleting the "models" (from the object detection API) folder and downloading and setting up a new one, but that didn't work either.

I am using Pycharm.

**Comment by anandolee** [comment]
Is StringIntLabelMap defined by your project or tensorflow? Do you know what data you are trying to parse in text format?
The error message is clear that StringIntLabelMap message does not have filename field.

**Comment by AKZOMBIE74** [comment]
It is defined by tensorflow, to be more specific the object detection API. As for the rest of your questions, sorry I don't know. I was just told that running the command would be enough to train the model. I don't know how tensorflow does its training. (Here is the object detection api: https://github.com/tensorflow/models/tree/master/research/object_detection)

**Comment by AKZOMBIE74** [comment]
@anandolee

**Comment by anandolee** [comment]
I'd say this is more like a question for tensorflow usage. I suggest you to file an issue with tensorflow

**Comment by elharo** [comment]
Agreed, not a bug in protobuf
