### ISSUE TITLE
Move protobuf to its own github organization.

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#4796]
Dear Protobuf users,

Since 3.0.0 release, we have brought official support for several new languages into protobuf. Due to that growth, we are considering moving the project to its own github organization. This can help us better manage the project and improve the support we provide to the community.

An organization will allow us to add support for more languages outside the main repo. We can include repos for helpful tools/utilities that are not suitable to bundled with the protobuf core library. Having them all under a single organization can help make them more discoverable.

The github organization we are considering moving to is:
https://github.com/protocolbuffers

After the move, the main protobuf repository will be: https://github.com/protocolbuffers/protobuf.

While we believe this move will be seamless for us and the users as everything will be redirected, we want to make sure we have considered all corner cases. Please help us with that by filling up this survey:

https://docs.google.com/forms/d/e/1FAIpQLSeH1ckwm6ZrSfmtrOjRwmF3yCSWQbbO5pTPqPb6_rUppgvBqA/viewform

Suggestions on how we should structure the organization are welcome.

- Google Protobuf Team

**Comment by ObsidianMinor** [comment]
> add support for more languages outside the main repo

So will you allow other developers to move their language implementations to the organization like [golang/protobuf](https://github.com/golang/protobuf) or [apple/swift-protobuf](https://github.com/apple/swift-protobuf/) if they desire?

**Comment by xfxyjwf** [comment]
> So will you allow other developers to move their language implementations to the organization like golang/protobuf or apple/swift-protobuf if they desire?

I would hope so, but it's not protobuf-team's call and I'll need to consult the management/legal team about this. I'm not very optimistic about it though.

**Comment by lukesneeringer** [comment]
One thing I would love to see in the future would be the built-in "plugins" (e.g. `--cpp_out`, `--python_out` become separate executables with their own repositories and separate contributors.

**Comment by xfxyjwf** [comment]
Thanks to everyone who has participated in the survey! Here is the overview of the survey result:

![screenshot from 2018-08-17 14-28-00](https://user-images.githubusercontent.com/8551050/44289606-e25e7480-a229-11e8-91e6-dc243b43e515.png)

A few people have concerns about whether the move will make it harder to find Google official implementations, but we believe this issue be addressed with proper documentations.

Some questions that have been brought up:
1. Can you use the shorter name "protobuf" for the organization? We would very much like to, but unfortunately no. [The "protobuf" github account has been taken by someone else](https://github.com/protobuf), and we cannot convince either github or the owner of that account to transfer it to us. With that option unavailable to us, "protocolbuffers" seems the best one among the alternatives.
2. Are other protobuf projects (e.g., golang/protobuf) also moving to this organization? Maybe. For different languages the best location to host the protobuf repository may differ. If the owners believe moving it to our protocolbuffers organization will help make it more discoverable, we will work with them to coordinate the move. Right now only this protobuf main repository will be moved to the organization.
3. Will you accept unofficial community projects into this organization? We are willing to accept community contributed projects but the exact process hasn't been determined yet. We will announce the process when it's decided.

I'm starting the move for this repo right now.

**Comment by xfxyjwf** [comment]
The repo is now at its new location:
https://github.com/protocolbuffers/protobuf

Everything should just work as it is before. I will update all references in our code base to the new location.

**Comment by xfxyjwf** [comment]
All references have been updated. Closing.
