### ISSUE TITLE
[PHP] Mapping a Struct object to a plain array object

### ISSUE THREAD

**Issue by rok-povsic** [protocolbuffers/protobuf#4802]
Hello, I'd like to map an array (associative or sequential) to a `Google\Protobuf\Struct` object, and vice versa. Ideally, the mapping would be able to handle objects of arbitrary depth (i.e. `['a' => ['b' => 3]]`).

Is there an existing way of doing that or must I write a mapper by hand (with taking into account the mapping of all the key/value types)?

Any help is appreciated.

**Comment by TeBoring** [comment]
Sorry, currently no.

**Comment by hscspring** [comment]
i got the same issue.

what i know is using `json.dumps()` or turn array to a string.  
is there anyone who can give some advice? 
many thanks.

**Comment by TeBoring** [comment]
Pull request is welcome.

**Comment by TeBoring** [comment]
I think this should have been fixed in master (#5106). Could you check that?
