### ISSUE TITLE
Protobuf CMake Variables are empty

### ISSUE THREAD

**Issue by raspies** [protocolbuffers/protobuf#4806]
I have just compiled protobuf by using the CMake procedure.
I cloned it from git and did the steps as described in the readme and everything goes fine so far:

1. git clone --branch v3.6.0.1 https://github.com/google/protobuf.git
2. git submodule update --init --recursive
3. ./autogen.sh 
4. cd cmake/
5. mkdir _build
6. cd _build/
7. mkdir release
8. cd release/
9. cmake -DCMAKE_INSTALL_PREFIX=/opt/protobuf/3.6.0.1 ../..
10. make -j4 install 

Now I have correct folders "bin", "include" and "lib" in my destination folder. When I want to use them in my own project and I do this as follows:
```
if(UNIX)	
	FIND_PACKAGE(Protobuf 3.5.0 REQUIRED PATHS "/opt/protobuf/3.6.0.1/lib/cmake")

	if (Protobuf_FOUND)
		message(STATUS "Found Protobuf ${Protobuf_VERSION}, libs are: ${Protobuf_LIBRARY}; Include Dir is ${Protobuf_INCLUDE_DIRS}")
	else (Protobuf_FOUND)
		message(FATAL_ERROR "Protobuf lib not found")
	endif (Protobuf_FOUND)
endif(UNIX)
```
Protobuf is found but the variables for libs and include dirs are always empty. The output from the snippet above is: 

`Found Protobuf 3.5.0, libs are: ; Include Dir is `

I use CMake 3.11.0 and ubuntu 16.04.

**Comment by mellery451** [comment]
since the finder claims to find 3.5.0 but you built/installed 3.6.0 - that's a mismatch.  Most likely it is finding a system package of some kind, possibly via package config. I would try adding `NO_DEFAULT_PATH` to see if that helps.

**Comment by raspies** [comment]
Oh, there I copied the wrong line. I tried both releases 3.6.0.1 and 3.5.0 in each case the correct and corresponding version is shown but the variables are empty in both cases.
In windows its no problem. My suggestion is that it might have something to do with the new CMake Version?

**Comment by raspies** [comment]
I also had a little deeper look in cmake protobuf files and found out that the issue was with the variable "protobuf_MODULE_COMPATIBLE". When I set this to TRUE in my CMake Project the variables are correctly set:

`Found Protobuf 3.6.0, libs are: /opt/protobuf/3.6.0/lib/libprotobuf.a; Include Dir is /opt/protobuf/3.6.0/include`

This feature is a little bit strange and is also not documented in https://cmake.org/cmake/help/v3.11/module/FindProtobuf.html

**Comment by bach001** [comment]
Five years later, I am still facing the same issue. Here is my weird fix before reaching here.

# double calls to find_package
find_package(Protobuf CONFIG)
find_package(Protobuf REQUIRED)

I don't know why it works in my case. :)

**Comment by darkdragon-001** [comment]
You should not need any of these variables. Just link against `protobuf::libprotobuf` target, it will also find the headers correctly!
