### ISSUE TITLE
Generated pb2.py files should contain `from __future__ import absolute_import` 

### ISSUE THREAD

**Issue by KerstinKeller** [protocolbuffers/protobuf#4810]
I am using protoc 3.5.1 to generate *_pb2.py files.
My Python version is Python 2.7.12 running on Ubuntu 16.04.

I organize my files in a hierarchical structure:

```
my_package
  pb
    my_lib.proto
    sys
      service.proto
```

After generation of pb2.py files and placing `__init__.py` files there, my structure looks like this:

```
my_package
  __init__.py
  pb
    __init__.py
    my_lib_pb2.py
    sys
      __init__.py
      service_pb2.py
``` 

If I now try and import from python:

```
import my_package.pb.my_lib_pb2
```
it fails with the following output:
```
File "/home/my_user/.local/lib/python2.7/site-packages/my_package-py2.7.egg/my_package/pb/my_lib_pb2.py", line 6, in <module>
    _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
AttributeError: 'module' object has no attribute 'version_info'
```

The following pb2.py was generated by protoc:
```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_package/pb/my_lib.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))

...
```

However, using Python 2.7, it now imports the `sys` module inside `my_package\pb` folder instead of the module which comes with Python. Using Python 3.5, everything works as expected, because absolute imports are the default policy in Python > 3.0
If protoc generated a line
```
from __future__ import absolute_import
```
right before the `import sys` statement, the issue would be solved.

I'm not sure if this line could break anything, but since it is the default behaviour for Python > 3.0, I would doubt it.

**Comment by tvalentyn** [comment]
You can consider running `futurize` on the output as a workaround: https://github.com/apache/beam/blob/7a65ef2b1f1d3f1f66a76b9b2ed9f8cac066c2bc/sdks/python/gen_protos.py#L114

**Comment by elharo** [comment]
Python 2 is no longer supported.
