### ISSUE TITLE
compile pb.h file error in chromium project

### ISSUE THREAD

**Issue by coding-pandaren** [protocolbuffers/protobuf#4823]
i add pb.h and pb.cc file to gn and build
but the compiler psot error message like this
virtual methods with non-empty bodies shouldn't be declared inline
'virtual' will be redundant; 'override' implies 'virtual'.
Overriding method must be marked with 'override' or 'final'

**Comment by xfxyjwf** [comment]
It seems some cleanup is needed to the C++ code to make proper use of "virtual"/"override"/"final". Could you help make a fix? We don't see such errors in our own tests.

**Comment by batradhruv** [comment]
Could I pick this up? If you have any pointers for starting on this please do let me know..

**Comment by xfxyjwf** [comment]
@batradhruv Feel free to send us pull requests.
