### ISSUE TITLE
Python reserved word 'None' is not considered in code generation

### ISSUE THREAD

**Issue by FlowerCode** [protocolbuffers/protobuf#4833]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.5

**What did you do?**
1. Define Enum

```
enum NotificationType {
    None = 0;
    Type1 = 1;
    Type2 = 2;
    Type3 = 3;
}
```

2. Compile to Python

`protoc.exe -I=.\pb --python_out=.\pb_python .\pb\test.proto`

3. Run it in Python

**What did you expect to see**
No Error

**What did you see instead?**
```
  File "test.py", line 10
    None = 0
SyntaxError: cannot assign to None
```

**Comment by anandolee** [comment]
Update:

None is considered in Python keywords. 
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc#L113

The error is not only for None. Message, enum, enum value, extension all have issues with keywords conflict. There's an ongoing fix in internal which will make getattr() work with keyword conflict.

**Comment by FlowerCode** [comment]
@anandolee 
That's great news. Thanks!

**Comment by zhangskz** [comment]
Closing since 3.8.0 has long been released.
