### ISSUE TITLE
(Minor) Unnecessary integer conversion compilation warning in arena_impl.h

### ISSUE THREAD

**Issue by dncliss** [protocolbuffers/protobuf#4865]
Version: v3.6.0 (present in master as well)
Language: C++
Operating System: RHEL 7.5 (but issue isn't OS-specific) on Power
Compiler: "NVCC" (via cuda-nvcc-9-2-9.2.88-1.ppc64le)

Recreation:
You can see the error when building BVLC's caffe using protobuf with the CUDA nvcc compiler,
although it is easy to understand how this can be seen with other project builds and possibly other
compilers.

The build results in multiple repeated lines of warnings that look like this:
/opt/DL/protobuf/include/google/protobuf/arena_impl.h(55): warning: integer conversion resulted in a change of sign
/opt/DL/protobuf/include/google/protobuf/arena_impl.h(309): warning: integer conversion resulted in a change of sign
/opt/DL/protobuf/include/google/protobuf/arena_impl.h(310): warning: integer conversion resulted in a change of sign

It's a minor issue, but it is a nuisance for the 'caffe' project as the build output is flooded with literally hundreds of repeats of this warning.

Output will vary depending on where the header is installed, of course, but the warning is self-explanatory.  Investigation shows that a negative integer is being used as a mask for an unsigned type of size_t.

It appears this could be avoided via a cast, for example (lines 309-310):
-  static const size_t kBlockHeaderSize = (sizeof(Block) + 7) & -8;
-  static const size_t kSerialArenaSize = (sizeof(SerialArena) + 7) & -8;
+  static const size_t kBlockHeaderSize = (sizeof(Block) + 7) & (size_t)-8;
+  static const size_t kSerialArenaSize = (sizeof(SerialArena) + 7) & (size_t)-8;

**Comment by dncliss** [comment]
My suggested patch is this:

diff --git a/src/google/protobuf/arena_impl.h b/src/google/protobuf/arena_impl.h
index f648f16..dbb3634 100644
--- a/src/google/protobuf/arena_impl.h
+++ b/src/google/protobuf/arena_impl.h
@@ -52,7 +52,7 @@ namespace internal {
 
 inline size_t AlignUpTo8(size_t n) {
   // Align n to next multiple of 8 (from Hacker's Delight, Chapter 3.)
-  return (n + 7) & -8;
+  return ((n + 7) & (size_t)-8);
 }
 
 // This class provides the core Arena memory allocation library. Different
@@ -306,8 +306,8 @@ class LIBPROTOBUF_EXPORT ArenaImpl {
  public:
   // kBlockHeaderSize is sizeof(Block), aligned up to the nearest multiple of 8
   // to protect the invariant that pos is always at a multiple of 8.
-  static const size_t kBlockHeaderSize = (sizeof(Block) + 7) & -8;
-  static const size_t kSerialArenaSize = (sizeof(SerialArena) + 7) & -8;
+  static const size_t kBlockHeaderSize = (sizeof(Block) + 7) & (size_t)-8;
+  static const size_t kSerialArenaSize = (sizeof(SerialArena) + 7) & (size_t)-8;
   static_assert(kBlockHeaderSize % 8 == 0,
                 "kBlockHeaderSize must be a multiple of 8.");
   static_assert(kSerialArenaSize % 8 == 0,

**Comment by dncliss** [comment]
[arena_impl_patch.txt](https://github.com/google/protobuf/files/2178097/arena_impl_patch.txt)

My suggested patch

**Comment by xfxyjwf** [comment]
@dncliss Could you send the patch as a pull request?

**Comment by dncliss** [comment]
Housekeeping.....

Given that this was fixed via #5193 (several months ago), there's no reason for this issue to remain open.   Closing.
