### ISSUE TITLE
C# Slow first deserialization

### ISSUE THREAD

**Issue by dmytrodiachenko** [protocolbuffers/protobuf#4866]
Perhaps someone is also faced with this problem.
When I try to deserialize the model for the first time, it takes a lot of time, but secondly, the third one ... looks good. These are happens every time when you try to deserialize the model for the first time.
I almost understand why this is happening, but maybe there is a solution to this problem?

First deserialization = 3.119ms.
Second deserialization = 0.186ms.

For the first deserialization in iOS this time can up to 200ms

C# Code

```
                FileDescriptor.ForceReflectionInitialization<Person.Types.PhoneType>();

		AddressBook addressBook = new AddressBook();
		Person person = new Person();
		person.Name = "Test";
		person.Id = 1;
		person.Email = "test@test.com";

		person.Phone.Add(new Person.Types.PhoneNumber()
		{
			Number = "+1234567890",
			Type = Person.Types.PhoneType.Home
		});

		for (int i = 0; i < 20; i ++)
		{
			addressBook.Person.Add(person);
		}

		byte[] bytes = addressBook.ToByteArray();

		DateTime time = DateTime.Now;

		addressBook = AddressBook.Parser.ParseFrom(bytes);
        
		Debug.Log((DateTime.Now - time).TotalMilliseconds);
		Debug.Log(addressBook.ToString());
```

.proto
```
syntax = "proto3";
package tutorial; 

message Person {
    string name = 1;
    uint32 id = 2;
    string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phone = 4;
}

message AddressBook {
    repeated Person person = 1;
}
```

**Comment by xfxyjwf** [comment]
I bet it's the class loading/JIT stuff that makes the first parsing much slower. That's what happens in Java and users usually workaround it using a warmup step.

**Comment by elharo** [comment]
seems like a general C# question.
