### ISSUE TITLE
goog.asserts.AssertionError

### ISSUE THREAD

**Issue by keep2iron** [protocolbuffers/protobuf#4871]
I have encountered some difficulties.

goog.asserts.AssertionError {message: "Failure: Invalid wire type", reportErrorToServer: true, messagePattern: "Failure: Invalid wire type", stack: "AssertionError: Failure: Invalid wire type↵    at …81/50a1c93a-aa23-44f1-8147-ea869bc10bee:62641:93)"}

I use protobuf on react-native。

```
        fetch(api.user.create_my_address,fetchOption)
            .then(async (response)=>{

                let value = await response.text()
                let buffer = Buffer.from(value);
                console.log(buffer);

               //Execute here to throw a exception
                let resp = protos.RecommendMainPageResponse.deserializeBinary(buffer)
                console.log(resp.getPostinfoList());
       
            })
            .catch((error)=>{
                console.log(error)
            })
            .done();
```

**Comment by TeBoring** [comment]
what's the buffer you passed to deserializeBinary?

**Comment by sean3112** [comment]
maybe you should sync .proto file with backend

**Comment by sean3112** [comment]
maybe you should sync .proto file with the backend.
