### ISSUE TITLE
Option definition allows no value

### ISSUE THREAD

**Issue by wvxvw** [protocolbuffers/protobuf#4902]
**What did you do?**
Created a Proto definition:
```
syntax = "proto3";

service Foo {
    rpc Bar (google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (google.api.http) = {};
    }
}
```

**What did you expect to see**

Syntax error.

**What did you see instead?**

`protoc` accepts this definition.

I understand the value of leniency, but here `protoc` ignores a genuine error.  I'm going to argue that it is never valid to specify option without a value, and thus should not be allowed.

BTW. The "formal" language spec doesn't allow this either.

**Comment by xfxyjwf** [comment]
We probably can't reject it out right because it will be a breaking change. Generating warning for such empty definitions seems appropriate.

**Comment by wvxvw** [comment]
I'd suggest a different plan: disallow by default and add extra flag to do the wrong thing.

I don't believe there are that many cases of this in the wild, but when there are, they are genuine bugs: nobody wants an option with no value. This was also the case when I discovered this behavior: a programmer mistakenly commented out the value inside the curly block, but the compiler didn't catch the error.
