### ISSUE TITLE
Clarify documentation on behaviour of oneofs with default values

### ISSUE THREAD

**Issue by jskeet** [protocolbuffers/protobuf#491]
The proto3 docs state:

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

Then for oneof:

> Oneof fields are like regular fields except all the fields in a oneof share memory, and at most one field can be set at the same time. Setting any member of the oneof automatically clears all the other members.

As oneof fields are like regular fields, I'd _expect_ that setting a scalar oneof field to the default value would effectively clear it - and the value wouldn't be serialized.

I gather that's not the case, and that the actual _and intended_ behaviour is that oneofs are different in those terms - that setting an int32 oneof field to 0 will end up with that being the "case" of the oneof and the 0 being serialized on the wire.

Assuming that's correct, it would be good to indicate this clearly in the documentation.

**Comment by haberman** [comment]
I think this is worth clarifying.

**Comment by haon4** [comment]
Documentation updated.
