### ISSUE TITLE
Ship the Python wheel with the Python compiler 

### ISSUE THREAD

**Issue by pfreixes** [protocolbuffers/protobuf#4918]
**What language does this apply to?**

Python

**Describe the problem you are trying to solve.**

I would like to compile the protobuf files related to a specific repository when the CI step is gonna be executed - TravisCI, etc, .. - or when the project is being packaged  - Docker image, etc, .. - to make it ready to be used in production.

**Describe the solution you'd like**
I would like to see how the Python compiler - already shipped with the `protoc` command - is also provided by the Python wheel [1].

So, making the protobuf wheel a requirement of a specific project that uses the protobuf files will allow us to compile the proto files, besides using them.

The compiler might be shipped as an entry point [2] of the setup.py, for example with the name `protoc_python` that would use under the hood the same code as `protoc` but shipped as a library. 

**Additional context**

We, our organization, are considering to ignore the protocol buffer files that are generated from the protobuf files, so not adding them as regular files that are being tracked by the CVS - GIT, etc - system, generating them when they are needed.

Why? Basically, because we do believe that the files generated by the compiler should be none opinionated not being under discussion. Having them as regular CSV files, as other Python files, is a prone error system that can end up with some of the following errors:

- Update the proto files but not generating again the python output file related to that proto files
- Modify the python output files
- etc.

So definitely, we do believe that the python output files that are generated from proto files must be immutables and making them not regular CSV files allow us to get rid of most of the mistakes.

**Aditional advantages**

Also, its worth considers as an additional advantage of compiling the proto files when they are gonna be used as a way of aligning the protobuf version used by the compiler and the runtime library. Right now, this can not be assured.

[1] https://pypi.org/project/protobuf/
[2] https://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by xfxyjwf** [comment]
@anandolee was already working on this in https://github.com/google/protobuf/pull/1796

**Comment by zhangskz** [comment]
I believe this is fixed already.
