### ISSUE TITLE
Field options do not work with DLL protobuf

### ISSUE THREAD

**Issue by arthur-tacca** [protocolbuffers/protobuf#4925]
If you attempt to use a field option, like the example in the tutorial:

    import "google/protobuf/descriptor.proto";
    extend google.protobuf.MessageOptions {
        optional string my_option = 51234;
    }
    message MyMessage {
        option (my_option) = "Hello world!";
    }

But use the dynamic version of protobuf, installed using [vcpkg](https://github.com/Microsoft/vcpkg) (which is by far the easiest way to build protobuf on Windows):

    vcpkg install protobuf:x64-windows

Then the application will compile and link, but the field option will not be found:

    // Should be true, but is set to false
    bool isFound = MyMessage::descriptor()->options().HasExtension(my_option)

When doing the same thing with the static version of protobuf, the field is found correctly:

    vcpkg install protobuf:x64-windows-static

Here "static" and "dynamic" refers to both which version of the Microsoft CRT is used and what type of linkage is used for protobuf itself (and other vcpkg-built libraries). I also tried static library linkage with the dynamic CRT (using a custom vcpkg triplet) and this worked correctly, like the wholly static version.

Whilst building an application with protobuf using dynamic linkage there are a lot of warnings about dllexport/dllimport. Presumably these are related.

**Comment by xfxyjwf** [comment]
We have protobuf tests built against the DLL version of protobuf runtime. Could you try to reproduce the error you are seeing by adding a test to our existing test code?

**Comment by davetopia** [comment]
In my particular case, I was able to debug this and find that my Visual Studio project was linking to both `libprotobuf.lib` and `libprotobuf-lite.lib` simultaneously.  Registration of enum options into extension_set.cc was occuring within `libprotobuf.lib` and the extension list was being accessed via `libprotobuf-lite.dll`.

I think this is due to vcpkg attempting to link `*.lib`.  The vcpkg port probably needs to be altered such that lite and full are separately installable or require manual linking.

**Comment by ras0219-msft** [comment]
@davetopia I've pushed a fix for this issue in vcpkg master by suppressing the installation of the `lite` runtime.

**Comment by davetopia** [comment]
@ras0219-msft Thanks, this is exactly what I need.

**Comment by arthur-tacca** [comment]
Amazing detective work @davetopia ! I'm not sure I would have ever figured that one out. I can confirm that the fix by @ras0219-msft works for me. Thanks to you both.

**Comment by leohilbert** [comment]
@davetopia Oh my god, this fixed my problem as well! Thank you!!
