### ISSUE TITLE
Python3.7: MergeFrom() throws when trying to extend list of SInt32 with int 

### ISSUE THREAD

**Issue by kunalspathak** [protocolbuffers/protobuf#4928]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.7

**What did you do?**

I have a protobuf message 
```protobuf
message List_sint32 {
    repeated sint32 Value = 1;
}
```
I generate the python code using `protoc.exe`. Here is how i use from Python

```python
my_list = [1,2,3]
a = List_sint32 ()
a.Value.extend(my_list)
```

**What did you expect to see**

With `python 3.6` this passes and expect to pass on `python 3.7` as well.

**What did you see instead?**
See below failure
```cmd
File "/a.py", line 30, in _convert_to_pb_2
protobuf_object.Value.extend(python_object)
File "/Users/prose/Library/Python/3.7/lib/python/site-packages/google/protobuf/internal/containers.py", line 389, in extend
new_element.MergeFrom(message)
File "/Users/prose/Library/Python/3.7/lib/python/site-packages/google/protobuf/internal/python_message.py", line 1230, in MergeFrom
'expected %s got %s.' % (cls.__name__, msg.__class__.__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected SInt32 got int.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
```
File "/a.py", line 30, in _convert_to_pb_2
protobuf_object.Value.extend(python_object)
```
Do you know why it is not a.Value.extend(my_list) as in your example code?


```
File "/Users/prose/Library/Python/3.7/lib/python/site-packages/google/protobuf/internal/containers.py", line 389, in extend new_element.MergeFrom(message)   
```
It is complaining for repeated composite field, but 'repeated sint32 Value = 1;' is a repeated scalar field.


```
expected SInt32
```
Seems like there's a message named SInt32, and 'repeated SInt32 Value = 1;"  is used in .proto file somewhere instead of sint32. Can you double check that.
Or protobuf with Python 3.7 wrongly recognize sint32 with message type of SInt32

**Comment by kunalspathak** [comment]
> Do you know why it is not a.Value.extend(my_list) as in your example code?

I just pasted formatted output from a function call, but `a` is passed as parameter to a function that receives it in `protobuf_object` variable. So `a` and `protobuf_object` are same. Sorry about the confusion.

I do have `SInt32` message defined and I will verify and confirm if that is causing the problem or not. What surprises me is different results in python 3.6 vs 3.7.

```protobuf
message SInt32 {
    sint32 Value = 1;
    bool IsNullValue = 2;
}
```

**Comment by anandolee** [comment]
It is an issue if python 3.6 vs 3.7 behaves different. We may need more info to identify the reason. Let me know after you verified message SInt32

**Comment by kunalspathak** [comment]
Quick update -

If I change the above message, it works fine. So instead of `SInt32` if i have `ABC32` or `_SInt32`, it works fine. I will see on my end if I am doing something wrong, but could you also double check if the generator is getting confused with the name of message and making wrong assumptions?

**Comment by kunalspathak** [comment]
Alright, seems to find the short repro is below `a.proto` file:
```protobuf
syntax = "proto3";
message SInt32 {
    sint32 Value = 1;
    bool IsNullValue = 2;
}
message List_sint32 {
    repeated sint32 Value = 1;
    bool IsNullValue = 2;
}
// Note that the message name is different in casing, so it refers to the defined SInt32 and not sint32
message List_SInt32 {
    repeated SInt32 Value = 1;
    bool IsNullValue = 2;
}

message TopMessage {
    List_sint32 a = 1;
}
```

The run this
```cmd
C:\google.protobuf.tools\3.6.0\tools\windows_x64\protoc.exe --python_out=. a.proto
```

And the test case is `a.py` file:

```py
import a_pb2

def foo(pb_object, py_object):
    pb_object.Value.extend(py_object)

top_message = a_pb2.TopMessage()
top_message.a.Value.extend([1, 2])
```

On python36 it works fine, but on python37 I get error I mentioned earlier. Note that this also repros if i use `3.5.1` version of protobuf. So definitely something to do with recent changes in python3.7 + how the language feature is used inside protobuf to discover messages. But hope that helps for further investigation on your end.

**Comment by anandolee** [comment]
What is the generated descriptors for the repeated fields? Are they:
```
    _descriptor.FieldDescriptor(
      name='Value', full_name='proto2.python.internal.List_sint32.Value', index=0,
      number=1, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
```
and 
```
    _descriptor.FieldDescriptor(
      name='Value', full_name='proto2.python.internal.List_SInt32.Value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
```

**Comment by anandolee** [comment]
Just checked with the generated code, both "message List_sint32" and "message List_SInt32" are generated as "_LIST_SINT32", so the second one overwrites the first one. 

I can make a fix for it but need to take some time because such changes may breaks some of our internal users.

**Comment by anandolee** [comment]
Update: can't change the internal generated "_UPPERCASE_NAME" directly which breaks backward compatibility. Use alias may solve it but not sure it worth to do so. I am marking it as P3 as there are workaround

**Comment by anandolee** [comment]
Update:
It is a known issue and there's a FIXME in code generator:
  // FIXME(robinson):
  // We currently don't worry about collisions with underscores in the type
  // names, so these would collide in nasty ways if found in the same file:
  //   OuterProto.ProtoA.ProtoB
  //   OuterProto_ProtoA.ProtoB  # Underscore instead of period.
  // As would these:
  //   OuterProto.ProtoA_.ProtoB
  //   OuterProto.ProtoA._ProtoB  # Leading vs. trailing underscore.
  // (Contrived, but certainly possible).
  //
  // The C++ implementation doesn't guard against this either.  Leaving
  // it for now...

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc#L1216

It is unable for fix now because it breaks backward compatibility. Will close it for clean up
