### ISSUE TITLE
Incorrect processing of parent directory element in io_win32.cc

### ISSUE THREAD

**Issue by arthur-tacca** [protocolbuffers/protobuf#4931]
Version: v3.5.1
OS: Windows 7 64-bit
Runtime: C++

**In short:** The functions in `io_win32.cc` misinterpret paths like `C:\foo\..\..` as being `C:\` rather than an invalid path. Similarly `C:\foo\..\..\..\bar` will be misinterpreted as `C:\bar`. One concrete bug resulting from this is that the unit test program will loop forever if run from the wrong working directory. But I suspect there may be other implications.

**More details:** The functions in `io_win32.cc` mostly (all?) call the internal `as_windows_path()` function, which in turn calls `normalize()`. This works by breaking the path apart into a vector of path segments, then joining them back together again. The segment splitting code contains this code section:

    if (segment == dotdot) {
      if (!segments.empty() &&
          (!has_drive_letter(segments[0].c_str()) || segments.size() > 1)) {
        segments.pop_back();
      }
    }

Note that if the condition of the inner clause is false then the segment is just discarded. I would argue that the function should immediately `return false` at this point, indicating an invalid path.

**Observable(ish) consequence:** Here is one effect this has, which is how I discovered the problem (while researching #4925): The unit tests require that they are run in a directory where `src/` contains the protobuf source code; in particular `src/google/protobuf` should exist. It is acceptable to be in a child directory instead, as `../src/` and `../../src/` etc. are also checked. However, if run from the wrong directory, this check just loops forever in `googletest.cc`:

    while (!File::Exists(prefix + "/src/google/protobuf")) {
      if (!File::Exists(prefix)) {
        GOOGLE_LOG(FATAL)
          << "Could not find protobuf source code.  Please run tests from "
             "somewhere within the protobuf source package.";
      }
      prefix += "/..";
    }

This loop assumes that `File::Exists(prefix)` will `return false` for invalid paths such as `C:\..` in order to terminate the loop. But `File::Exists(prefix)` calls `access()`, which calls `normalize()`, so it ends up checking whether `C:\` exists, which of course it does. After an hour in this loop, `prefix` was 1.4 million characters long :-)

**Comment by gerben-s** [comment]
I'm not very familiar with the windows environment. Feng what do you think should happen here?

**Comment by xfxyjwf** [comment]
I suspect the way how io_win32.cc works is intentional, i.e., `C:\foo\..\..\bar` do get interpreted as `C:\bar` on windows... Just a guess. I haven't verified this on a windows machine.

It seems to me the way we locate the src directory can be improved by getting the absolute path of the  current working directory and start from there. That way we can avoid the current "append /.. and check" approach.
