### ISSUE TITLE
Broken with PHP 7.3.0alpha4

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#4933]
Build ok since pr #4898 is merged but extension dosn't load (since 7.3.0alpha4, was OK with alpha3)

`$ php --no-php-ini --define extension=modules/protobuf.so --modules | grep protobuf`

Output is empty. No error message.

P.S. as I can't sign your CLA, I don't plan to work on this issue to propose a fix, so, do it yourself.

**Comment by TeBoring** [comment]
Where can I get source for 7.3.0alpha4?

**Comment by TeBoring** [comment]
@remicollet I found the problem is that, in the ```main``` function, ```zend_startup_modules``` is called before ```do_cli``` (where ```EG(objects_store)``` is initialized).

Because protobuf needs to register well known type messages (which transitively calls ```zend_class_implements``` and ```zend_objects_store_put```), it requires ```EG(objects_store)``` is initialized first. Is this a bug of php?

**Comment by remicollet** [comment]
> Is this a bug of php?

Don't know... better to ask on internals

**Comment by TeBoring** [comment]
Sorry, what do you mean by "internals"?

**Comment by TeBoring** [comment]
@remicollet how to contact with internals?

**Comment by remicollet** [comment]
> @remicollet how to contact with internals?

See http://php.net/mailing-lists.php

**Comment by remicollet** [comment]
Perhaps @dstogov or @nikic can answer ?

**Comment by remicollet** [comment]
thanks @dstogov

**Comment by TeBoring** [comment]
@dstogov, thanks for the clarification. Actually, I didn't intentionally create object during MINIT stage.
The code flow is: module init => register class => zend_class_implements => message_create (custom creator of parent class) => zend_object_std_init

I don't quite understand why zend_class_implements will call message_create. In previous versions of php, we never saw such problem.

**Comment by dstogov** [comment]
@TeBoring When PHP implements interface, it calls zend_class_entry->interface_gets_implemented() callback. In PHP-7.3 interface_gets_implemented shares the same location with create_object. First one makes sense only for interfaces, second only for regular classes.

I suspect, you set zend_class_entry->create_object for interface.

**Comment by TeBoring** [comment]
Looks like so. Do you know how I can avoiding php thinking the Message (parent class) as interface?

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/message.c#L1234
I let any implements message (message is a base class). If message is a regular class, can it be implemented?

**Comment by TeBoring** [comment]
Actually, I just want any to inherit message. Is there way to do that? Is so, could that fix this issue?

**Comment by nikic** [comment]
@TeBoring You can inherit from a class by passing the parent class entry as the second parameter to `zend_register_internal_class_ex()`. You'll have to adjust this macro: https://github.com/protocolbuffers/protobuf/blob/704037f23a9ede00ec4fcf40d568712ce6200934/php/ext/google/protobuf/protobuf.h#L134 Also the explicit zend_do_inheritance call will no longer be necessary (this is an internal method, not intended for direct consumption by extensions).

**Comment by TeBoring** [comment]
Thanks @nikic. It works.
Now I meet a new problem.
https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/storage.c#L183
The value for zend_string_dup sometimes is interned string.
Then I got: Zend/zend_variables.c:71: zend_string_destroy: Assertion `!(zval_gc_flags((str)->gc.u.type_info) & (1<<6))' failed.

**Comment by TeBoring** [comment]
Changing to ```zend_string_init``` seems fixing the problem.
