### ISSUE TITLE
Why don't you support lua language, now lua is widely used.

### ISSUE THREAD

**Issue by imilli** [protocolbuffers/protobuf#4937]

**Comment by xfxyjwf** [comment]
@imilli Could you post some data showing lua is used as much as one of the existing supported languages? That will help us prioritize the support.

**Comment by imilli** [comment]
There are some projects that use lua :

**Comment by imilli** [comment]
There are some projects that use lua :
https://github.com/cloudwu/skynet
https://github.com/openresty/openresty
you can know how many people use by watching the stars.
and the lua is also used by a large number of game companies, include wow.

**Comment by sdrees** [comment]
@xfxyjwf: Maybe https://www.lua.org/uses.html is a good point to trigger impact analysis 😉

**Comment by imilli** [comment]
@sdrees  You are right.

**Comment by sloong** [comment]
+1

**Comment by LouisSong** [comment]
+1

**Comment by perezd** [comment]
There are some lua bindings being developed over here:
https://github.com/protocolbuffers/upb#lua-bindings
