### ISSUE TITLE
MessageToJsonString discards extensions

### ISSUE THREAD

**Issue by psalvaggio** [protocolbuffers/protobuf#4971]
**What version of protobuf and what language are you using?**
3.5.0

Language: C++

**What operating system (Linux, Windows, ...) and version?**
Fedora 28

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 8.1.1

**What did you do?**
I set up a simple test case:
```
syntax = "proto2";

message ExternalEmbedded {
  optional uint32 foo = 1;
}

message TestProto {
  enum Foo {
    A = 0;
    B = 1;
  }

  message Bar {
    optional string foo = 1;
  }

  optional uint32 foo1 = 1;
  optional bool foo2 = 2;
  optional double foo3 = 3 [default = 1];
  optional ExternalEmbedded embed1 = 4;
  optional Foo enum1 = 5;
  optional Bar embed2 = 6;

  extensions 1000 to max;
}

message TestExtension {
  optional uint32 foo = 1;
}

extend TestProto {
  optional TestExtension extend1 = 1000;
}
```
I then populated a message with:
```
  TestProto test;
  test.set_foo1(5);
  test.set_enum1(TestProto::B);

  auto* embed1 = test.mutable_embed1();
  embed1->set_foo(2);

  auto* embed2 = test.mutable_embed2();
  embed2->set_foo("Hello there!");
  auto* extend = test.MutableExtension(extend1);
  extend->set_foo(7);
```
and serialized this to JSON with `MessageToJsonString()`.

**What did you expect to see**
JSON with the extension in there.

**What did you see instead?**
```
{
  "foo1": 5,
  "embed1": {"foo": 2},
  "enum1": "B",
  "embed2": {"foo":"Hello there!"}
}
```

Is it possible to get extension support in the JSON serialization? Proto3 isn't really an option for me since it dropped support for default values.

**Comment by xfxyjwf** [comment]
MessageToJsonString only supports proto3 features at the moment. Extension is a proto2-only feature. Currently we don't have a plan to support it in proto3 JSON implementations.

**Comment by mcy** [comment]
As stated above, we do not implement extensions in C++. I have recently rewritten the C++ JSON codec, which we can hopefully land in a future release externally, which implements extensions, so this will be fixed "soon"; it is just a matter of waiting for our next major release.
