### ISSUE TITLE
Omit serialization of specific field

### ISSUE THREAD

**Issue by m-peko** [protocolbuffers/protobuf#4975]
I have a message defined as following:

```
syntax = "proto3";

message Data {
    string messageType = 1;
    string sender = 2;
    bytes payload = 3;
}
```

I am given the payload part already serialized, appended with header (with some special characters) and prepared for transmission over socket. Therefore, additional serializing of a payload field creates some special characters (like `\000`) that cannot be parsed on the C++ side (I think because of escape sequences in C). Serialization is done with Python.

Is there something I can do to solve this problem?

Thanks in advance

**Comment by jschultz410** [comment]
@m-peko Just for the serialization operation, can't you temporarily set the protobuf's object payload to default, so that it won't serialize?

**Comment by m-peko** [comment]
@jschultz410 I bypassed this problem and not working anymore on this.
