### ISSUE TITLE
Error Installing Omnet++ 

### ISSUE THREAD

**Issue by prithvishenoy7** [protocolbuffers/protobuf#4978]
make[1]: Leaving directory '/mnt/c/Users/prith/Desktop/kth/y2/THesis/vsimrti-allinone/vsimrti/bin/fed/omnetpp/inet/src'
Building OMNeT++ federate...
cd src && make all
make[1]: Entering directory '/mnt/c/Users/prith/Desktop/kth/y2/THesis/vsimrti-allinone/vsimrti/bin/fed/omnetpp/omnetpp-federate/src'
MSGC: mgmt/VSimRTICommunicationCmd.msg
MSGC: mgmt/VSimRTIConfigurationCmd.msg
MSGC: mgmt/VSimRTIMobilityCmd.msg
MSGC: msg/VSimRTIAppPacket.msg
evt/VSimRTIEventScheduler.cc
In file included from util/ClientServerChannel.h:5:0,
                 from evt/VSimRTIEventScheduler.h:6,
                 from evt/VSimRTIEventScheduler.cc:6:
util/ClientServerChannelMessages.pb.h:9:10: fatal error: /usr/include/google/protobuf/stubs/common.h: Permission denied
 #include <google/protobuf/stubs/common.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:121: recipe for target '../out/gcc-debug/src/evt/VSimRTIEventScheduler.o' failed
make[1]: *** [../out/gcc-debug/src/evt/VSimRTIEventScheduler.o] Error 1
make[1]: Leaving directory '/mnt/c/Users/prith/Desktop/kth/y2/THesis/vsimrti-allinone/vsimrti/bin/fed/omnetpp/omnetpp-federate/src'
Makefile:61: recipe for target 'src_dir' failed
make: *** [src_dir] Error 2

**Comment by vaibhavrajput** [comment]
prrr

**Comment by elharo** [comment]
doesn't look like a protobuf problem
