### ISSUE TITLE
myriad type conversion warnings during `make check`

### ISSUE THREAD

**Issue by JeffAbrahamson** [protocolbuffers/protobuf#4984]
**What version of protobuf and what language are you using?**
Version: master (3d62db3ecd5377025a458bca827ab4ca12d5c1f0)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

```
vagrant@ubuntu-xenial:~/src/protobuf$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

vagrant@ubuntu-xenial:~/src/protobuf$ 
```

**What did you do?**

    make check

**What did you expect to see**

No compiler warnings

**What did you see instead?**

Lots of compiler warnings.  In particular, I see quite a lot of type conversion errors.  Here is a typical example, converting false to pointer type:

```
g++ -DHAVE_CONFIG_H -I. -I..  -I./../third_party/googletest/googlemock/include -I./../third_party/googletest/googletest/include -DPROTOBUF_TEST_NO_DESCRIPTORS  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -g -std=c++11 -DNDEBUG -MT google/protobuf/protobuf_lazy_descriptor_test-map_test_util.o -MD -MP -MF google/protobuf/.deps/protobuf_lazy_descriptor_test-map_test_util.Tpo -c -o google/protobuf/protobuf_lazy_descriptor_test-map_test_util.o `test -f 'google/protobuf/map_test_util.cc' || echo './'`google/protobuf/map_test_util.cc
In file included from ./../third_party/googletest/googletest/include/gtest/gtest.h:1872:0,
                 from ./google/protobuf/map_test_util_impl.h:36,
                 from google/protobuf/map_test_util.cc:32:
google/protobuf/map_test_util.cc: In member function ‘void google::protobuf::MapReflectionTester::ExpectMapEntryClearViaReflection(google::protobuf::Message*)’:
./../third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:133:55: warning: converting ‘false’ to pointer type for argument 1 of ‘char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)’ [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
...
```

**Comment by xfxyjwf** [comment]
This is more of a gtest issue than a protobuf one.

**Comment by JeffAbrahamson** [comment]
Well, it's gtest that's emitting the warnings, but wouldn't it be better to do the appropriate casts so that the warnings don't happen?  One of the reasons for such warnings is that comparisons between types that don't match can lead to unexpected equality.  It makes it more clear in the protobuf code that the particular projection in question is intended and safe.

**Comment by mcy** [comment]
Unfortunately, although cleaning this up is great, early Google style recommended `int` as the type for lengths. Unwinding this bit of tech debt completely would be a somewhat large effort that would be difficult to backstop; I am closing this as "not planned", since we do not have the bandwidth for it.
