### ISSUE TITLE
Filenames starting with number will result in invalid Java generated code

### ISSUE THREAD

**Issue by skinkie** [protocolbuffers/protobuf#4999]
**What version of protobuf and what language are you using?**
Version: v3.5.2.
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
java 1.8.0_162

**What did you do?**
https://github.com/grpc/grpc-java/issues/4690#issuecomment-408578075

**Comment by perlun** [comment]
Hi @skinkie, I think there is a greater chance for this being investigated if you copy-paste in (the relevant parts) from your original issue (in `grpc-java`). This will make the information more easily accessible => lowers the threshold for people to dig deeper into this.

**Comment by elharo** [comment]
This should only be an issue for the wrapper class. It can be worked around by setting the `java_outer_classname` option to override the class name derived from the file:

```
option java_outer_classname = "MyProtos";
```

I'm not sure how much we want to fix this. There are a lot of file names that are not legal Java class names. Possibly we need a general solution for this problem.

**Comment by elharo** [comment]
I don't think we're going to change protoc to make this work. The one thing we perhaps should do is error out sooner in protoc itself rather than letting javac find and report the error.

**Comment by googleberg** [comment]
Please set the java_outer_classname to solve this if your filename results in invalid generated names.
