### ISSUE TITLE
FromDatetime does not work with timezone aware datettime objects

### ISSUE THREAD

**Issue by mitar** [protocolbuffers/protobuf#5003]
**What language does this apply to?**

Python.

**Describe the problem you are trying to solve.**

The following does not work:

```python
import datetime
from google.protobuf import timestamp_pb2

timestamp = timestamp_pb2.Timestamp()
timestamp.FromDatetime(datetime.datetime.now(datetime.timezone.utc))
```

```
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/well_known_types.py", line 236, in FromDatetime
    td = dt - datetime(1970, 1, 1)
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Describe the solution you'd like**

That `FromDatetime` would just work with timezone aware objects.

**Describe alternatives you've considered**

I could convert datettime to non-timezone aware object before calling `FromDatetime`.

**Comment by anandolee** [comment]
Thanks for reporting this issue.
We have received a same issue in google internal, and are working on this

**Comment by anandolee** [comment]
Update: we have added the support in internal code. Wait for 3.7.0 release
