### ISSUE TITLE
Issue removing items in RepeatedCompositeContainer

### ISSUE THREAD

**Issue by cstranex** [protocolbuffers/protobuf#5006]
Version: v3.6.0
Language: Python
OS: Linux
Python 3.6.5

```
# test.proto
syntax = "proto3";
    
message TestItems {
    int32 id = 1;
    string name = 2;
}

message Test {
   repeated TestItems items = 1;
}
```

    $ pipenv --python 3.6
    $ pipenv install protobuf==3.6.0
    $ python
    Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
    [GCC 7.3.0] on linux
    >>> import test_pb2
    >>> from copy import deepcopy
    >>> z = test_pb2.Test()
    >>> z.items.add(id=1)
    >>> z.items.add(id=2)
    >>> z.items.add(id=3)
    >>> z.items.add(id=4)
    >>> x = deepcopy(z.items)
    >>> x.remove(x[0])
    >>> x
    [id: 2
    , id: 3
    , id: 4
    , id: 4
    ]
    >>> z.items.remove(z.items[0])
    >>> z
    [id: 2
    , id: 3
    , id: 4
    ]

 The result of `x` above should be the same as the result of `z`. Using deepcopy it appears that if I remove an item in a container it will duplicate the last item in the list while doing the same operation on the original object will produce the correct result.

**Comment by anandolee** [comment]
Are you using a pure python or cpp extension?

**Comment by anandolee** [comment]
Thanks for reporting it.
I can reproduce the error in pyext, pure python works fine. Repeated message container duplicates the last item after remove in the deep copied container. Repeated scalar container is even worse that the program crashes. 
I've created a fixing change in internal code and is waiting for review.

**Comment by cstranex** [comment]
Thanks

**Comment by anandolee** [comment]
Update: The fix has been approved and submitted in internal code base. Expect to see in 3.7.0 release

**Comment by anandolee** [comment]
Closing it as 3.7.0 is already released
