### ISSUE TITLE
[Docs]: Documentation comments should be language agnostic

### ISSUE THREAD

**Issue by dsnet** [protocolbuffers/protobuf#5022]
The following `.proto` files are well-known and generated in every language:
```
descriptor.proto
any.proto
duration.proto
timestamp.proto
wrappers.proto
empty.proto
field_mask.proto
struct.proto
api.proto
type.proto
source_context.proto
```

However, the comments in each file are often formatted with some syntax that causes the output to be mangled when viewed using some other documentation tool native to the target language. Instead, the comments should be written to make as little assumptions about what documentation tool is used to interpret it.

Example usage of pre-formatted text syntax:
https://github.com/google/protobuf/blob/c9a30c2c279431466e30541ac7c2cd9776c93b9c/src/google/protobuf/field_mask.proto#L47

Example usage of header syntax:
https://github.com/google/protobuf/blob/c9a30c2c279431466e30541ac7c2cd9776c93b9c/src/google/protobuf/any.proto#L94-L95

Example usage of hyperlink syntax:
https://github.com/google/protobuf/blob/c9a30c2c279431466e30541ac7c2cd9776c93b9c/src/google/protobuf/timestamp.proto#L53

Of all the special syntaxes used, the hyperlink syntax is the most disruptive.

**Comment by xfxyjwf** [comment]
How does the hyperlink look up in Go? I think the comments are written assumed markdown format.

**Comment by dsnet** [comment]
https://godoc.org/github.com/golang/protobuf/ptypes/timestamp#Timestamp

Go's documentation tool, [godoc](https://godoc.org/golang.org/x/tools/cmd/godoc) has very minimal syntax. As such, it doesn't handle the markdown headers nor hyperlinks.
