### ISSUE TITLE
Ruby gem 3.6.1 fails on windows

### ISSUE THREAD

**Issue by taylanisikdemir** [protocolbuffers/protobuf#5025]
Hi,

I am seeing issues with protobuf ruby gem 3.6.1 on windows. Here is my repro:

`ret = Google::Protobuf::Struct.new`
`val = Google::Protobuf::Value.new`
`val.string_value = "some string"`
`ret.fields[“key”] ||= val`

After executing above I get the error below:
Assertion failed!
Program: C:\Ruby24-x64\bin\ruby.exe
File: ../../../../ext/google/protobuf_c/upb.c, Line 6331
Expression: val.ctype == t->ctype

My environment:
OS: Windows Server 2016 version 1607 (build 14393.2363)
Ruby: 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
Gem: google-protobuf (3.6.1 x64-mingw32)

I don't see any problem with below environment:
OS: Windows Server 2016 version 1607 (build 14393.2363)
Ruby: 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
Gem: google-protobuf (3.0.2 x86-mingw32, 3.0.0 x86-mingw32)

Can someone help me debug this further?

**Comment by TeBoring** [comment]
Could you gdb to check what’s val.ctype and what’s t->ctype?

**Comment by pbasl** [comment]
Hi I am having the same issue. Any update on this??

**Comment by TeBoring** [comment]
@taylanisikdemir did you get any progress?
BTW, does the same problem exist in previous versions?

**Comment by pbasl** [comment]
@TeBoring I have the same issue in my rails app in development. It's almost impossible for me to determine what action exactly causes the error. I explicitly used the 3.5.1.2 version of the gem and the error doesn't show up anymore.

**Comment by taylanisikdemir** [comment]
I also switched to an older version for now . It would be great if you guys take a look and identify the issue because apparently there's a regression.

**Comment by TeBoring** [comment]
@haberman, is there any suggestion for debugging on windows?

**Comment by TeBoring** [comment]
help needed to debug on windows. Anyone has experience to gdb a ruby c extension on windows?

**Comment by micw523** [comment]
Checked to see that before assert:
val.ctype is 6352080
t->ctype is 4 (UPB_CTYPE_UINT64)

**Comment by haberman** [comment]
I have a suspicion that the Windows compile is mixing flags. It appears this source file was compiled in debug mode, but I suspect other parts of the code were built with `NDEBUG`.

**Comment by micw523** [comment]
@haberman I think your suspicion is correct - I removed the unless statement for Windows in extconf.rb and the there is no more error. In Windows / mingw it is indeed built in DEBUG mode. I'll go ahead and create a pull request.

**Comment by TeBoring** [comment]
Wait for next release to have the fix. Close this for now.

**Comment by igorpeshansky** [comment]
@TeBoring, has this been released? If so, in what gem version? Thanks.

**Comment by TeBoring** [comment]
You can try 3.7.0.rc.3
