### ISSUE TITLE
A zero field number on the wire is invalid  Exception in Objective-C

### ISSUE THREAD

**Issue by jonz-tech** [protocolbuffers/protobuf#5043]
Hi,
we had use protoBuf for a long time!
recently,we create a new protocol. after we request the api. we got an exception: A zero field number on the wire is invalid. which set PBMessage  as nil.
But we check the response message on server, it 's the same data send  to client. and i check the data in iOS client. in this method `- (void)mergeFromCodedInputStream:(GPBCodedInputStream *)input
                extensionRegistry:(GPBExtensionRegistry *)extensionRegistry`
we got correct numFields,
but when it enter this code ` tag = GPBCodedInputStreamReadTag(state);` we got an exception. 
and the state->lastTag is 1.  set the GPBmessage as nil in this code 
`- (instancetype)initWithData:(NSData *)data
           extensionRegistry:(GPBExtensionRegistry *)extensionRegistry
                       error:(NSError **)errorPtr {
  if ((self = [self init])) {
    @try {
      [self mergeFromData:data extensionRegistry:extensionRegistry];
      if (errorPtr) {
        *errorPtr = nil;
      }
    }
    @catch (NSException *exception) {
      [self release];
      self = nil;
      if (errorPtr) {
        *errorPtr = ErrorFromException(exception);
      }
    }`
 how can i know  which field is zero num make this happen?

**Comment by thomasvl** [comment]
Zero is a invalid field number; the error is because the binary data you are trying to parse appears to have a zero as a field number.

Can you create a repo and/or provide the binary data so someone can try to see what exactly is trying to be parse?

**Comment by jonz-tech** [comment]
@thomasvl but in the  *.proto structure, we do not define a zero num field.where is the zero field from?
how can i get the binary data?

**Comment by thomasvl** [comment]
The data you provided appears to be valid:

```
$ xxd -r -p < hex_data.txt | protoc --decode_raw
2: "123456"
3: "http://emyms.bs2dl.yy.com/ZTc4MDRiNjctMmQ0MC00NzgwLWI0ODktYzg0ZTgwMjIyNmE0.jpg"
4: 3
5: "test"
6 {
  1: 535
  2: "\345\224\261\346\255\214\344\274\230\346\203\240\345\210\270"
  3: 1
  4: "\345\224\261\346\255\214"
  5: "\346\211\276\344\272\272\351\231\252\346\210\221\345\224\261\351\246\226\346\255\214"
  6: 100
  7: 90
  8: "\351\246\226"
  9: 500
  11: "http://emyfs.bs2cdn.yy.com/MDlhYTNmMDgtM2Y4OS00NjhiLTlmMGQtMzRkMWY5MmRmMGVl.png"
}
```

Which would seem to say the problem is likely how you are trying to parse the data, so if you can provide a code snippet showing the problem that would help, otherwise, I'm not really sure what you are doing that is causing the problem.

As to the _tag zero_ part, you can't have a field number that is zero.  So if you are getting that error, it means the way in which you are feeding your data to the library to be decoded is causing it to see a zero in the binary data itself, and that is why it is reporting an error, as the data appears to be malformed.

**Comment by thomasvl** [comment]
fyi - pulled this in to ObjC code also, without issue:

```objective-c
  unsigned char input[] = {
    0x12, 0x06, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x1a, 0x4e, 0x68, 0x74, 0x74, 0x70, 0x3a,
    0x2f, 0x2f, 0x65, 0x6d, 0x79, 0x6d, 0x73, 0x2e, 0x62, 0x73, 0x32, 0x64, 0x6c, 0x2e, 0x79,
    0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x5a, 0x54, 0x63, 0x34, 0x4d, 0x44, 0x52, 0x69, 0x4e,
    0x6a, 0x63, 0x74, 0x4d, 0x6d, 0x51, 0x30, 0x4d, 0x43, 0x30, 0x30, 0x4e, 0x7a, 0x67, 0x77,
    0x4c, 0x57, 0x49, 0x30, 0x4f, 0x44, 0x6b, 0x74, 0x59, 0x7a, 0x67, 0x30, 0x5a, 0x54, 0x67,
    0x77, 0x4d, 0x6a, 0x49, 0x79, 0x4e, 0x6d, 0x45, 0x30, 0x2e, 0x6a, 0x70, 0x67, 0x20, 0x03,
    0x2a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x32, 0x92, 0x01, 0x08, 0x97, 0x04, 0x12, 0x0f, 0xe5,
    0x94, 0xb1, 0xe6, 0xad, 0x8c, 0xe4, 0xbc, 0x98, 0xe6, 0x83, 0xa0, 0xe5, 0x88, 0xb8, 0x18,
    0x01, 0x22, 0x06, 0xe5, 0x94, 0xb1, 0xe6, 0xad, 0x8c, 0x2a, 0x15, 0xe6, 0x89, 0xbe, 0xe4,
    0xba, 0xba, 0xe9, 0x99, 0xaa, 0xe6, 0x88, 0x91, 0xe5, 0x94, 0xb1, 0xe9, 0xa6, 0x96, 0xe6,
    0xad, 0x8c, 0x30, 0x64, 0x38, 0x5a, 0x42, 0x03, 0xe9, 0xa6, 0x96, 0x48, 0xf4, 0x03, 0x5a,
    0x4f, 0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x65, 0x6d, 0x79, 0x66, 0x73, 0x2e, 0x62,
    0x73, 0x32, 0x63, 0x64, 0x6e, 0x2e, 0x79, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x44,
    0x6c, 0x68, 0x59, 0x54, 0x4e, 0x6d, 0x4d, 0x44, 0x67, 0x74, 0x4d, 0x32, 0x59, 0x34, 0x4f,
    0x53, 0x30, 0x30, 0x4e, 0x6a, 0x68, 0x69, 0x4c, 0x54, 0x6c, 0x6d, 0x4d, 0x47, 0x51, 0x74,
    0x4d, 0x7a, 0x52, 0x6b, 0x4d, 0x57, 0x59, 0x35, 0x4d, 0x6d, 0x52, 0x6d, 0x4d, 0x47, 0x56,
    0x6c, 0x2e, 0x70, 0x6e, 0x67,
  };

  NSData *data = [NSData dataWithBytes:input length:sizeof(input)];

  NSError *err = nil;
  // TestEmptyMessage is just an empty message in a proto file.
  TestEmptyMessage *msg = [TestEmptyMessage parseFromData:data error:&err];
  NSLog(@"err: %@", err);
  NSLog(@"msg: %@", msg);
```

It logs:

```
2018-08-20 12:13:01.620506-0400 testapp[84782:1148980] err: (null)
2018-08-20 12:13:01.621954-0400 testapp[84782:1148980] msg: <TestEmptyMessage 0x104a0dfe0>: {
    # --- Unknown fields ---
    2: "123456"
    3: "http://emyms.bs2dl.yy.com/ZTc4MDRiNjctMmQ0MC00NzgwLWI0ODktYzg0ZTgwMjIyNmE0.jpg"
    4: 3
    5: "test"
    6: "\010\227\004\022\017\345\224\261\346\255\214\344\274\230\346\203\240\345\210\270\030\001\"\006\345\224\261\346\255\214*\025\346\211\276\344\272\272\351\231\252\346\210\221\345\224\261\351\246\226\346\255\2140d8ZB\003\351\246\226H\364\003ZOhttp://emyfs.bs2cdn.yy.com/MDlhYTNmMDgtM2Y4OS00NjhiLTlmMGQtMzRkMWY5MmRmMGVl.png"
}
```

The objc doesn't try to recursively dump the unknown field 6, that is what the output differs slightly, but the library does succeed at parsing it.

**Comment by jonz-tech** [comment]
because field 6 is an defined fied num, it's a repeated message . you means repeated message encode  
not correct make the field 6 can not be recognize?

**Comment by thomasvl** [comment]
Unless there is somehow a bug in the library (which would sorta surprise me given how many message it is used with), it should be able to parse it just fine.

Can you rewrite your .proto with dummy field names and see if it repeats?  Then could you post the .proto and snippet of code you are using?

**Comment by thomasvl** [comment]
Per spec, [field numbers are 0 - 2^29 - 1 (or 536,870,911)](https://developers.google.com/protocol-buffers/docs/proto#assigning-field-numbers).  Some older versions of the library didn't fully catch this error and would attempt to parse an otherwise corrupt buffer silently appearing to work when the real results were undefined.

The data your mentioned:

> <0000004c 00000320 00000006 08321202 32300000 004d0000 03200000 00060832 12023230>

Starts with a zero, so that ends up being filed type zero.  Given those first few bytes, I'm not really sure what your data actually is encoded as, the first 4 bytes converted to an int is 76, so that doesn't appear to be the length of a message either (incase that was your custom framing).

**Comment by OneWang** [comment]
Do you mean that because of the data format problem we defined before, only because the previous version did not fully catch these errors, so this exception will be thrown after the upgrade?

**Comment by OneWang** [comment]
Is this the exception that was thrown that can be ignored? And the data can be parsed as before;

**Comment by thomasvl** [comment]
The data can't be parsed, it is invalid.  Old versions of the library could let this error slip through in some cases and what you got as a result wasn't actually correct since the input was invalid.

**Comment by thomasvl** [comment]
As to if the error can be ignored, that's entirely up to you.  The data isn't parsed, so it is up to your application for what you want to do in that case.

**Comment by OneWang** [comment]
ok,thank you very much!
