### ISSUE TITLE
MessageFields is not printable in Python

### ISSUE THREAD

**Issue by wvxvw** [protocolbuffers/protobuf#5047]
When I get an error like this:

```
google.protobuf.json_format.ParseError: Message type "mdrates.api.v1.MarketData" has no field named "meta_data".
 Available Fields(except extensions): <MessageFields sequence>
```

I can see that you wanted to print available fields, but it didn't work, because MessageFields is not printed they way you might have expected.  You need to define `__str__` for this class.

**Comment by anandolee** [comment]
It should have been fixed:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py#L507

**Comment by anandolee** [comment]
in this PR
https://github.com/protocolbuffers/protobuf/commit/6bbe197e9c1b6fc38cbdc45e3bf83fa7ced792a3
