### ISSUE TITLE
Is the protoc binary available in the GitHub Releases zip files statically compiled? If not, can we get statically compiled binaries?

### ISSUE THREAD

**Issue by peter-edge** [protocolbuffers/protobuf#5053]
See https://github.com/uber/prototool/issues/194 for the issue and https://github.com/uber/prototool/issues/193 for reproduction. If you do `make run` there, you get:

```
docker run -it uber/prototool-protoc-issue /protoc --version
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

If you drop into a shell via `make shell`, you get:

```
/ # /protoc
/bin/sh: /protoc: not found
```

The binary is there and executable:

```
/ # ls -l /protoc
-rwxr-xr-x    1 root     root       4539800 Aug 16 08:22 /protoc
```

This appears to be similar to https://github.com/gin-gonic/gin/issues/1178 in some way, in that it appears protoc needs additional assets to run.

I searched the GitHub issues but did not immediately see something similar filed. There may be an easy answer to this, but at the least I thought we'd have a conversation about it - being able to easily download `protoc` to an Alpine image and run it would be something I could see many people using.

**Comment by johanbrandhorst** [comment]
My `protoc` binary (3.6.1) has a number of shared library dependencies:
```
$ ldd /usr/bin/protoc
    linux-vdso.so.1 (0x00007ffe34fda000)
    libprotoc.so.16 => /usr/lib/libprotoc.so.16 (0x00007f8286e0b000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f8286c7c000)
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f8286c62000)
    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8286c41000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007f8286a7d000)
    libprotobuf.so.16 => /usr/lib/libprotobuf.so.16 (0x00007f8286594000)
    libz.so.1 => /usr/lib/libz.so.1 (0x00007f828637b000)
    libm.so.6 => /usr/lib/libm.so.6 (0x00007f82861f6000)
    /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f828748d000)
```

**Comment by peter-edge** [comment]
Well I guess I've been out of the linking game for a while, heh. There we go:

```
/ # ldd /protoc
	/lib64/ld-linux-x86-64.so.2 (0x7f27ec2b0000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f27ec2b0000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f27ec2b0000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f27ec2b0000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /protoc)
```

Can we have a release on GitHub Releases that accomplishes this?

**Comment by peter-edge** [comment]
If I install `libc6-compat`, it works:

```
RUN \
  apk update && \
  apk add libc6-compat && \
  rm -rf /var/cache/apk/*
```

So maybe this isn't that necessary, but still worth a discussion.

**Comment by xfxyjwf** [comment]
@peter-edge The list you are getting is expected:
```
xiaofeng@xiaofeng-mtv:~/Downloads$ ldd bin/protoc
        linux-vdso.so.1 (0x00007ffd3976b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f49d6ed9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f49d6cbc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f49d691d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f49d71dd000)
```

I checked some older potoc binaries and the list is the same. It seems alpine has fewer installed shared libraries than most other linux systems do. Updating our protoc release process to target alpine can be an option, but it's not something we had planned.

**Comment by peter-edge** [comment]
We can close this as I don't think it's a major issue.
