### ISSUE TITLE
Repeated enum field in C++ : Cannot iterate field without casts

### ISSUE THREAD

**Issue by rainerschoe** [protocolbuffers/protobuf#5054]
Hi,
When using a repeated enum field, For example:

    enum Bar {
        BAR_VALUE = 0;
        OTHER_VALUE = 1;
    }

    message test {
        repeated Bar foo = 1;
    }

I will get c++ accessor methods like this (see here).

    Bar foo(int index) const
    const RepeatedField<int>& foo() const

However I am wondering why the `RepeatedField` template is instantiated with `int` and not the enum type `Bar`.
This prevents me from using interators to iterate through the fields (I try to avoid enum casting).

1. Why is the generated interface like this?
2. What is the recommended way for iterating through repeated enum fields?

I also posted the same question into the google group [here](https://groups.google.com/forum/#!topic/protobuf/9Yqh9LXcACk), but it seems this discussion group is quite inactive. Could you advise me on which communication channel with the ProtocolBuffers community is the official one? GitHub or Google Groups?

**Comment by xfxyjwf** [comment]
If you want to reach the protobuf team, creating a github issue and posting on the google groups both work. However, our primary focus is resolving bugs and handling pull requests. Right now we are not investing time on answering general user questions and most of them likely will not get a response from protobuf team.

**Comment by rainer-ibm** [comment]
Thanks for helping :)

I think this is not a question, but a bug report. Repeated Enums contain enum values and should not implicitly cast to integer.

**Comment by acozzette** [comment]
For better or worse, I think the API is going to have to stay the way it is. If we could start over from scratch we might use the enum type instead of int, but unfortunately we can't make that change now without breaking lots of code.

**Comment by dfreese** [comment]
Could the docs be updated to indicate that this is probably different than expected, but is maintained for historical reasons?

https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#repeated_enum
