### ISSUE TITLE
PHP generated classes missing argument description

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#5055]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP

**What did you expect to see**

Given a protocol buffer message with a nested message, ([example](https://github.com/googleapis/googleapis/blob/master/google/privacy/dlp/v2/storage.proto#L264)), the compiler should assign the related message description to the proper constructor argument and property.

**What did you see instead?**

The property and argument descriptions are empty. See for example [here](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/da01a939d32c81e3843e53b85a8662d9b807af7a/Dlp/src/V2/CloudStorageOptions.php#L67) and [here](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/da01a939d32c81e3843e53b85a8662d9b807af7a/Dlp/src/V2/CloudStorageOptions.php#L19).

The expected result should be:

```
     *     @type \Google\Cloud\Dlp\V2\CloudStorageOptions\FileSet $file_set
     *           Set of files to scan.
```

**Comment by deannagarcia** [comment]
Going to close this due to age, if this is still a problem with newer versions of protobuf please reopen.
