### ISSUE TITLE
Specifying a message field "string descriptor" breaks generated Java: duplicate getDescriptor()

### ISSUE THREAD

**Issue by elodotwe** [protocolbuffers/protobuf#5056]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
jdk1.8.0_102

**What did you do?**
1. Create protofile with a string field named `descriptor` inside a message, like this:
   ```
   syntax = "proto3";
   option java_package = "com.helloworld";
   
   message Hello {
       string descriptor = 1;
   }
   ```
2. Compile with `protoc`.
3. Attempt to compile the generated source into a project. (detail on how I did this + source for rest of my project is below)

**What did you expect to see**
Generated Java should compile.

**What did you see instead?**
Generated Java fails to compile, with messages like `error: method getDescriptor() is already defined in class Builder`.

Renaming the field from `descriptor` makes it compile as it should.

A full SSCCE [can be gotten from here](https://github.com/elodotwe/protoc_descriptor_issue_repro).

The full output from the compiler (via Gradle) is here:
```
$ gradle run
:extractIncludeProto
:extractProto
:generateProto
:compileJavaC:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:129: error: method getDescriptor() is already defined in class Hello
    public java.lang.String getDescriptor() {
                            ^
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:475: error: method getDescriptor() is already defined in class Builder
      public java.lang.String getDescriptor() {
                              ^
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:44: error: Hello is not abstract and does not override abstract method getDescriptor() in HelloOrBuilder
  public  static final class Hello extends
                       ^
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:107: error: getDescriptor() in Hello cannot implement getDescriptor() in HelloOrBuilder
        getDescriptor() {
        ^
  overriding method is static
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:321: error: Builder is not abstract and does not override abstract method getDescriptor() in HelloOrBuilder
    public static final class Builder extends
                        ^
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:326: error: getDescriptor() in Builder cannot implement getDescriptor() in HelloOrBuilder
          getDescriptor() {
          ^
  overriding method is static
C:\project_files\protoc_bad_java_generation\build\generated\source\proto\main\java\com\helloworld\Test.java:433: error: cannot find symbol
        if (!other.getDescriptor().isEmpty()) {
                                  ^
  symbol:   method isEmpty()
  location: class Descriptor
7 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
4 actionable tasks: 4 executed
```

**Comment by xfxyjwf** [comment]
Rename the field to something else if you could. The only fix we can implement in protoc is to rename the field from "descriptor" to "descriptor_" and you will get something like "getDescriptor_" or "getDescriptor1" in the public API.

**Comment by elharo** [comment]
I think this is no longer an issue. Please comment if you can still reproduce this.

**Comment by davix** [comment]
@elharo does "not an issue" mean protoc has fixed it by renaming it internally, or protobuf writer need to avoid this name?

**Comment by elharo** [comment]
If I recall, it means I tried to reproduce this and couldn't, but that was 2 years ago and I'm no longer on this team, or at this company, :-)
