### ISSUE TITLE
coded_stream.h CodedInputStream example [bug]

### ISSUE THREAD

**Issue by SummonY** [protocolbuffers/protobuf#5060]
**What version of protobuf and what language are you using?**
Version: master 
Language: C++

in protobuf/src/google/protobuf/io/coded_stream.h

CodedInputStream example: 

**What did you expect to see**
CodedInputStream* coded_input = new CodedInputStream(raw_input);

**What did you see instead?**
CodedInputStream coded_input = new CodedInputStream(raw_input);

**Comment by acozzette** [comment]
@wangkirin Thanks for fixing this!
