### ISSUE TITLE
C#: Add method for Any.Is

### ISSUE THREAD

**Issue by jbe2277** [protocolbuffers/protobuf#5066]
C#: Please provide an **Is** method within the [Any](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/WellKnownTypes/AnyPartial.cs) class:

``` C#
public bool Is(DescriptorBase descriptor) 
{
    ProtoPreconditions.CheckNotNull(descriptor, nameof(descriptor));
    return GetTypeName(TypeUrl) == descriptor.FullName;
}
```

**Comment by anandolee** [comment]
Can you  help to create a PR and send me to review?

**Comment by jbe2277** [comment]
Unfortunately, I have no time to do that. Maybe someone else could create the PR?
