### ISSUE TITLE
Unable to Parse Protobuf parameters from Dialogflow V2 into strings/integers or useful information

### ISSUE THREAD

**Issue by ctrlaltdylan** [protocolbuffers/protobuf#5080]
**What version of protobuf and what language are you using?**

Language: PHP

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 16.06

**What runtime / compiler are you using (e.g., python version or gcc version)**

PHP 7.1

**What did you do?**
1. Sent a query request to the Dialogflow V2 API with the official PHP SDK
2. Inspected the response

**What did you expect to see**

The ability to parse the parameters of a Dialogflow's response in Protobuf format into a string value

**What did you see instead?**

`MapField` object that doesn't include string values of the parameters

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by TeBoring** [comment]
Could you provide more detailed test to reproduce the bug?

**Comment by TeBoring** [comment]
Feel free to reopen if there is way to reproduce the bug.
