### ISSUE TITLE
Search for .bat plugins as well as .exe on windows

### ISSUE THREAD

**Issue by sigurdm** [protocolbuffers/protobuf#5084]
The dart protoc plugin is less convenient to invoke on windows (https://github.com/grpc/grpc-dart/issues/74) because the executable is called `protoc-gen-dart.bat` and that is not found on the path.

So this is a feature request to make protoc on windows search for `protoc-gen-x.bat` as well as `protoc-gen-dart.exe`.

Why not just have a protoc-gen-dart.exe:

The dart protoc plugin is implemented in dart.

The way the dart protoc plugin currently is distributed is via pub.
Pub installs an executable to the path that invokes the right dart program.
On unixy systems this executable is a shell script. On windows it is a `.bat` file. (https://github.com/dart-lang/pub/blob/9f00679ef47bc79cadc18e143720ade6c06c0100/lib/src/global_packages.dart#L657)

Creating an exe would require either a change of pub, or a different way of distributing the dart protoc plugin plus a way creating the exe file. Not impossible but quite inconvenient.

https://github.com/grpc/grpc-dart/issues/74#issuecomment-415949609 has some details on how this could possibly be solved.

**Comment by jtattermusch** [comment]
CC @jtattermusch @xfxyjwf 

Additional question:  do things work fine on unix (when `.sh` plugin is used)?

**Comment by sigurdm** [comment]
Yes - on unix there is no suffix. The file is just marked as executable and starts with a `#!/usr/bin/env sh` line.

**Comment by xfxyjwf** [comment]
@sigurdm It seems you already know of a fix to the issue. Do you mind sending us a pull request?

**Comment by sigurdm** [comment]
I am in the process of getting access to a windows machine. Then I'll try to write something.

**Comment by sigurdm** [comment]
I have made a pull request #5105
