### ISSUE TITLE
Error "Cannot find field" when using "ignore_unknown_fields" with 'Any' messages serialized as JSON

### ISSUE THREAD

**Issue by brandoncole** [protocolbuffers/protobuf#5086]
**What version of protobuf and what language are you using?**
Version: v3.5.0+
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux (Alpine, Ubuntu, etc.)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
We're using the Golang, Python and C++ toolchains for Protobufs.  The Golang and Python toolchains work just fine in the following scenario, however the C++ toolchain emits an error when encountering unknown fields combined with JSON Deserialization.

1. Define a simple Protobuf message such as this:

```
syntax = "proto3";

package example;

import "google/protobuf/any.proto";

message Child {
   string name = 1;
}

message Parent {
  google.protobuf.Any child = 1;
}
```

2. Prepare some JSON that contains some unknown fields.  This happens when the version the C++ code is compiled against is an older version and fields are added in the future that the C++ code doesn't know about.  Here is an example:

```json
{
  "child": {
    "@type":"example.Child",
    "name": "Jane Doe",
    "age": 42
  }
}
```

3. In the C++ library set the `ignore_unknown_fields` field to `true` when loading the JSON

4. Loading the JSON fails with the error: `Cannot find field.`

**What did you expect to see**
Similar to the Golang and Python libraries, the JSON should load fine even though it contains fields the C++ client doesn't know about

**What did you see instead?**
Loading the JSON fails with the error: `Cannot find field.`

**Anything else we should know about your project / environment**
N/A

**Analysis**
After investigating it a bit, @mercret and I believe the issue stems from https://github.com/protocolbuffers/protobuf/blob/45d03a977193d1dcce5251e4bffe17bf0ba738ec/src/google/protobuf/util/internal/protostream_objectwriter.cc#L344-L345 approximately, where the options on the parent writer are not properly propagated to the child writer.  We believe the fix is relatively straight forward and would be happy to submit a PR

**Comment by xfxyjwf** [comment]
Thanks for the report. Feel free to send us a PR.
