### ISSUE TITLE
PHP: well known types in C extension do not extend Message class in PHP 7.2

### ISSUE THREAD

**Issue by michaelbausor** [protocolbuffers/protobuf#5090]
This makes it impossible to reliably use type hints in functions that accept a protobuf message, because passing a well known type to such a function with the protobuf extension enabled will cause a TypeError.

**What version of protobuf and what language are you using?**
Version: composer version v3.6.1, c extension version 3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Tested on Ubuntu Travis instance. Details:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.2.4, 5.6.37

**What did you do?**
Run the following script using PHP cli. See below for composer.json file.
```
<?php

use Google\Protobuf\FloatValue;
use Google\Protobuf\Internal\Message;

require __DIR__ . '/vendor/autoload.php';

$floatValue = new FloatValue();
echo get_parent_class($floatValue) . PHP_EOL;
echo (($floatValue instanceof Message) ? 'True' : 'False') . PHP_EOL;
```

**What did you expect to see**
```
# php test.php
Google\Protobuf\Internal\Message
True
```

**What did you see instead?**
Running under PHP 7.2.4, *without* protobuf c extension:
```
# php test.php
Google\Protobuf\Internal\Message
True
```
Running under PHP 7.2.4, *with* protobuf c extension:
```
# php test.php

False
```
Running under PHP 5.6.37, *without* protobuf c extension:
```
# php test.php
Google\Protobuf\Internal\Message
True
```
Running under PHP 5.6.37, *with* protobuf c extension:
```
# php test.php

True
```

Composer.json file used:
```
{
    "name": "root/test",
    "require": {
        "google/protobuf": "^3.6"
    }
}
```

cc @TeBoring @bshaffer @tmatsuo @dwsupplee @jdpedrie

**Comment by TeBoring** [comment]
Please take a look of #5095
