### ISSUE TITLE
[PHP] "Given value cannot be converted to string" when setting RepeatedField value.

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#5091]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP 7.2 (observed in all 7-series of PHP)

**What runtime / compiler are you using (e.g., python version or gcc version)**

PHP C extension

**What did you do?**

Created an array of strings, accessed the values by reference, then assigned it to a protocol buffer value.

**What did you expect to see**

Successful assignment

**What did you see instead?**

"PHP Fatal error:  Given value cannot be converted to string."

This error does not appear to affect the protobuf pure PHP implementation. The error also does not seem to affect fields of type `string`.

A sample to reproduce this error using Cloud Firestore:

```php
<?php

use Google\Cloud\Firestore\V1beta1\BatchGetDocumentsRequest;

$documents = [
    'a', 'b', 'c'
];

function doThing(&$val) {}

// Either of these two lines cause the error. If they are removed, the error goes away.
doThing($documents[2]);
array_walk($documents, function (&$document) {});

$b = new BatchGetDocumentsRequest;
$b->setDocuments($documents);
```

**Comment by TeBoring** [comment]
What do you do in doThing

**Comment by jdpedrie** [comment]
Nothing. The point of that was just to demonstrate that simply accessing a member of the array by reference causes the error.

**Comment by TeBoring** [comment]
What's the type of ```$documents```?

**Comment by jdpedrie** [comment]
`string[]`
