### ISSUE TITLE
Auto-Generated C# Code has wrong namespace casing that breaks the build

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#5097]
Originally filed as https://github.com/grpc/grpc/issues/16514, but if confirmed, it's probably an issue in protobuf codebase.

Summary:
on windows, if you define .proto file named `MyProtoFile.proto` (case matters), you can still import it from a different .proto file as `myprotofile.proto`  as on windows the case in file names doesn't matter (and MyProtoFile.proto will be imported).
This can then break the C# generated code  (and possibly in other languages) as references to the imported file will have wrong casing.
(In our example `global::Contracts.Grpc.Alpha.ContractalphaReflection.Descriptor` will be generated, but the referenced class will be named `ContractAlphaReflection` and the build will fail.

**Comment by xfxyjwf** [comment]
This is not generated code breaking the build. It's the incorrect imports breaking the build. If we are to do anything, I would like to update protocol compiler to make the build break even earlier.
