### ISSUE TITLE
undefined reference to google::protobuf::***

### ISSUE THREAD

**Issue by PlutusCN** [protocolbuffers/protobuf#5098]
I am compiling my project with protobuf v3.1.0 as the third party on aarch64/arm by GCC5.4, but the following errors I got that is a huge trouble for me. I don't why and how to fix them. Can anybody help me? Thanks a lot and very much !!!

proto/***.pb.cc.o: In function `***::protobuf_AssignDesc_***_2eproto()':
***.pb.cc:(.text+0x5c): undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
proto/***.pb.cc.o: In function `***::protobuf_AddDesc_***_2eproto_impl()':
***.pb.cc:(.text+0x1ee8): undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
proto/***.pb.cc.o: In function `***::Ctrl::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0x2b88): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
***.pb.cc:(.text+0x2bf8): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::Ctrl::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0x2d7c): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
***.pb.cc:(.text+0x2e44): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::Ctrl::UnsafeMergeFrom(***::Ctrl const&)':
***.pb.cc:(.text+0x3114): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
***.pb.cc:(.text+0x3154): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::Err::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0x3edc): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::Err::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0x4060): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::Err::UnsafeMergeFrom(***::Err const&)':
***.pb.cc:(.text+0x42f4): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::Attr_Label::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0xa8a8): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::Attr_Label::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0xa9c4): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::Attr_Label::UnsafeMergeFrom(***::Attr_Label const&)':
***.pb.cc:(.text+0xacb4): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::Attr::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0xbd58): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::Attr::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0xbec8): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::Attr::UnsafeMergeFrom(***::Attr const&)':
***.pb.cc:(.text+0xc318): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::Face::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
***.pb.cc:(.text+0xd3ec): undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
proto/***.pb.cc.o: In function `***::Face::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0xd8e0): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::Face::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0xdbe0): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::Face::UnsafeMergeFrom(***::Face const&)':
***.pb.cc:(.text+0xe088): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::ImgInfo::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0xfce0): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
***.pb.cc:(.text+0xfd50): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
***.pb.cc:(.text+0xfdc0): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::ImgInfo::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0x10034): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
***.pb.cc:(.text+0x100fc): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
***.pb.cc:(.text+0x101c4): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::ImgInfo::UnsafeMergeFrom(***::ImgInfo const&)':
***.pb.cc:(.text+0x1088c): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
***.pb.cc:(.text+0x108cc): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
***.pb.cc:(.text+0x1090c): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `***::UnloadModelReq::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
***.pb.cc:(.text+0x14aac): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
proto/***.pb.cc.o: In function `***::UnloadModelReq::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
***.pb.cc:(.text+0x14c44): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
proto/***.pb.cc.o: In function `***::UnloadModelReq::UnsafeMergeFrom(***::UnloadModelReq const&)':
***.pb.cc:(.text+0x14ed4): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
proto/***.pb.cc.o: In function `google::protobuf::internal::GetEmptyStringAlreadyInited()':
***.pb.cc:(.text._ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv[_ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv]+0x8): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
***.pb.cc:(.text._ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv[_ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv]+0xc): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
proto/***.pb.cc.o: In function `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)':
***.pb.cc:(.text._ZN6google8protobuf8internal14WireFormatLite10ReadStringEPNS0_2io16CodedInputStreamEPSs[_ZN6google8protobuf8internal14WireFormatLite10ReadStringEPNS0_2io16CodedInputStreamEPSs]+0x18): undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoRspE[_ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoRspE[_ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoReqE[_ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoReqE[_ZTVN3com9***14verify_service14feature_engine21FeatureGetHeadInfoReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine17FeatureCompareRspE[_ZTVN3com9***14verify_service14feature_engine17FeatureCompareRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine17FeatureCompareRspE[_ZTVN3com9***14verify_service14feature_engine17FeatureCompareRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine17FeatureCompareReqE[_ZTVN3com9***14verify_service14feature_engine17FeatureCompareReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine17FeatureCompareReqE[_ZTVN3com9***14verify_service14feature_engine17FeatureCompareReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine15ImageCompareRspE[_ZTVN3com9***14verify_service14feature_engine15ImageCompareRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine15ImageCompareRspE[_ZTVN3com9***14verify_service14feature_engine15ImageCompareRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine15ImageCompareReqE[_ZTVN3com9***14verify_service14feature_engine15ImageCompareReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine15ImageCompareReqE[_ZTVN3com9***14verify_service14feature_engine15ImageCompareReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrRspE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrRspE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrReqE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrReqE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectAttrReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureRspE[_ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureRspE[_ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureReqE[_ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureReqE[_ZTVN3com9***14verify_service14feature_engine22ImageExtractFeatureReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityRspE[_ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityRspE[_ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityReqE[_ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityReqE[_ZTVN3com9***14verify_service14feature_engine20ImageAlignQualityReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceRspE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceRspE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceReqE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceReqE[_ZTVN3com9***14verify_service14feature_engine18ImageDetectFaceReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine14UnloadModelRspE[_ZTVN3com9***14verify_service14feature_engine14UnloadModelRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine14UnloadModelRspE[_ZTVN3com9***14verify_service14feature_engine14UnloadModelRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine14UnloadModelReqE[_ZTVN3com9***14verify_service14feature_engine14UnloadModelReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine14UnloadModelReqE[_ZTVN3com9***14verify_service14feature_engine14UnloadModelReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine12LoadModelRspE[_ZTVN3com9***14verify_service14feature_engine12LoadModelRspE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine12LoadModelRspE[_ZTVN3com9***14verify_service14feature_engine12LoadModelRspE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine12LoadModelReqE[_ZTVN3com9***14verify_service14feature_engine12LoadModelReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine12LoadModelReqE[_ZTVN3com9***14verify_service14feature_engine12LoadModelReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18WorkerHeartbeatReqE[_ZTVN3com9***14verify_service14feature_engine18WorkerHeartbeatReqE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine18WorkerHeartbeatReqE[_ZTVN3com9***14verify_service14feature_engine18WorkerHeartbeatReqE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine7ImgInfoE[_ZTVN3com9***14verify_service14feature_engine7ImgInfoE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine7ImgInfoE[_ZTVN3com9***14verify_service14feature_engine7ImgInfoE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4FaceE[_ZTVN3com9***14verify_service14feature_engine4FaceE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4FaceE[_ZTVN3com9***14verify_service14feature_engine4FaceE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4AttrE[_ZTVN3com9***14verify_service14feature_engine4AttrE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4AttrE[_ZTVN3com9***14verify_service14feature_engine4AttrE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine10Attr_LabelE[_ZTVN3com9***14verify_service14feature_engine10Attr_LabelE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine10Attr_LabelE[_ZTVN3com9***14verify_service14feature_engine10Attr_LabelE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine8LandmarkE[_ZTVN3com9***14verify_service14feature_engine8LandmarkE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine8LandmarkE[_ZTVN3com9***14verify_service14feature_engine8LandmarkE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine7QualityE[_ZTVN3com9***14verify_service14feature_engine7QualityE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine7QualityE[_ZTVN3com9***14verify_service14feature_engine7QualityE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4RectE[_ZTVN3com9***14verify_service14feature_engine4RectE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4RectE[_ZTVN3com9***14verify_service14feature_engine4RectE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine5PointE[_ZTVN3com9***14verify_service14feature_engine5PointE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine5PointE[_ZTVN3com9***14verify_service14feature_engine5PointE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine3ErrE[_ZTVN3com9***14verify_service14feature_engine3ErrE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine3ErrE[_ZTVN3com9***14verify_service14feature_engine3ErrE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4CtrlE[_ZTVN3com9***14verify_service14feature_engine4CtrlE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
proto/***.pb.cc.o:(.rodata._ZTVN3com9***14verify_service14feature_engine4CtrlE[_ZTVN3com9***14verify_service14feature_engine4CtrlE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `CWorker::HandleReq(stsys::proto::SStsysHead&, ***::FeatureCompareReq&)':
CWorker.cpp:(.text+0x2a28): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `CWorker::HandleReq(stsys::proto::SStsysHead&, ***::FeatureGetHeadInfoReq&)':
CWorker.cpp:(.text+0x37ac): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `CWorker::Send2Master(stsys::proto::SStsysHead&, google::protobuf::Message&)':
CWorker.cpp:(.text+0xd320): undefined reference to `google::protobuf::Message::DebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `CWorker::RecvTaskFromQ(std::string&)':
CWorker.cpp:(.text+0xd97c): undefined reference to `cpp_redis::future_client::brpop(std::vector<std::string, std::allocator<std::string> > const&, int)'
CWorker.cpp:(.text+0xda64): undefined reference to `cpp_redis::reply::as_string() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `CWorker::SendTaskToQ(stsys::proto::SStsysHead&, google::protobuf::Message&)':
CWorker.cpp:(.text+0xe028): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CWorker.cpp:(.text+0xe148): undefined reference to `cpp_redis::future_client::lpush(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `int CWorker::HandleReq<***::ImageDetectFaceReq>(stsys::proto::SStsysHead&, ***::ImageDetectFaceReq&)':
CWorker.cpp:(.text._ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine18ImageDetectFaceReqEEEiRN5stsys5proto10SStsysHeadERT_[_ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine18ImageDetectFaceReqEEEiRN5stsys5proto10SStsysHeadERT_]+0x120): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `int CWorker::HandleReq<***::ImageAlignQualityReq>(stsys::proto::SStsysHead&, ***::ImageAlignQualityReq&)':
CWorker.cpp:(.text._ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine20ImageAlignQualityReqEEEiRN5stsys5proto10SStsysHeadERT_[_ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine20ImageAlignQualityReqEEEiRN5stsys5proto10SStsysHeadERT_]+0x120): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `int CWorker::HandleReq<***::ImageExtractFeatureReq>(stsys::proto::SStsysHead&, ***::ImageExtractFeatureReq&)':
CWorker.cpp:(.text._ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine22ImageExtractFeatureReqEEEiRN5stsys5proto10SStsysHeadERT_[_ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine22ImageExtractFeatureReqEEEiRN5stsys5proto10SStsysHeadERT_]+0x120): undefined reference to `google::protobuf::Message::ShortDebugString() const'
CMakeFiles/verify_algo_worker.dir/CWorker.cpp.o: In function `int CWorker::HandleReq<***::ImageDetectAttrReq>(stsys::proto::SStsysHead&, ***::ImageDetectAttrReq&)':
CWorker.cpp:(.text._ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine18ImageDetectAttrReqEEEiRN5stsys5proto10SStsysHeadERT_[_ZN7CWorker9HandleReqIN3com9***14verify_service14feature_engine18ImageDetectAttrReqEEEiRN5stsys5proto10SStsysHeadERT_]+0x120): undefined reference to `google::protobuf::Message::ShortDebugString() const'

**Comment by acozzette** [comment]
How are you building the code? I would guess that the linker command is not being passed `-lprotobuf` or that `-lprotobuf` appears in the wrong order relative to the other arguments.

**Comment by PlutusCN** [comment]
I am using protobuf library in CMakeLists.txt:

TARGET_LINK_LIBRARIES(
... 
opencv_core opencv_highgui
stlog stproperties stutil
protobuf
cpp_redis tacopie
mongocxx mongoc-1.0 bsoncxx bson-1.0 pthread)

**Comment by spinkernel** [comment]
I'm having same issues. However I'm just building with c++/g++. 

```
$ c++ pb_test_client.cc test.pb.cc -o pb_test_client `pkg-config --cflags protobuf`                                                                                                                                                                                                                  /tmp/cczCk713.o: In function `main':      
                                                                                                                                                                                                           
pb_test_client.cc:(.text+0x5c): undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'                                                                                                                                                                             
pb_test_client.cc:(.text+0x29a): undefined reference to `google::protobuf::Message::SerializeToFileDescriptor(int) const'                                                                                                                            
pb_test_client.cc:(.text+0x2c0): undefined reference to `google::protobuf::Message::ParseFromFileDescriptor(int)'                                                                                                                                                                                     
pb_test_client.cc:(.text+0x366): undefined reference to `google::protobuf::ShutdownProtobufLibrary()'
```

```
$ pkg-config --libs protobuf                                                       
-L/usr/local/lib -lprotobuf -pthread
```

The example protobuf code compiles no problem, i've looked at their make file and i'm executing the the same g++ flags they are, so not sure why mine is failing and that isn't.
