### ISSUE TITLE
GeneratedMessageLite visitMessage incompatible with non-GeneratedMessageLite components

### ISSUE THREAD

**Issue by SattaiLanfear** [protocolbuffers/protobuf#5110]
**What version of protobuf and what language are you using?**
Version: 3.5.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
OSX 10.13.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 1.8.0_131

**What did you do?**
Attempt to use a standard (default) optimize_for = SPEED type message in a optimize_for LITE_RUNTIME message, eg the standard "Empty" message from well known types.

Run a .equals comparing the GeneratedMessageLite against another instance.

**What did you expect to see**

Successful comparison returning true or false.

**What did you see instead?**

It compiles successfully, but upon trying to use it in an equality check, it created the following error message:

```console
java.lang.ClassCastException: com.google.protobuf.Empty cannot be cast to com.google.protobuf.GeneratedMessageLite

	at com.google.protobuf.GeneratedMessageLite$EqualsVisitor.visitMessage(GeneratedMessageLite.java:1961)
	at testpackage.TestMessage.dynamicMethod(TestMessage.java:834)
	at com.google.protobuf.GeneratedMessageLite.visit(GeneratedMessageLite.java:337)
	at com.google.protobuf.GeneratedMessageLite.equals(GeneratedMessageLite.java:162)
```

The specific line that's failing is: `((GeneratedMessageLite<?, ?>) mine).equals(this, other);`

Ultimately it looks like it assumes all nested messages must be lite messages.

**Anything else we should know about your project / environment**

My project is expected to have a lot of message types, and while I don't need the full runtime most of the time I do occasionally (JSON output) so I'd intended to allow the messages to mix within a single application, optimized depending on if they needed the JSON I/O ability or not.

**Comment by xfxyjwf** [comment]
Mixing lite and non-lite in a single application is no longer supported. You will either need to use lite everywhere, or non-lite everywhere. The "optimize_for" option will be ignored in a future release. To use lite, you need to follow instructions here:
https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md

Generally we recommend server applications to use non-lite and mobile applications to use lite. We are considering adding JSON support to lite as well and that will help if JSON is the only reason you are using non-lite.

**Comment by SattaiLanfear** [comment]
Ah, I wish that was documented on https://developers.google.com/protocol-buffers/docs/reference/java-generated . Will the references to lite in the core version be vanishing (eg MessageLite)?

The javalite binary downloads linked to at that markdown page you linked don't look to have been touched in 2 years, is it still in active development?

The reason why I was mixing the lite and non-lite versions is because while I am designing a server, there look to possibly be more than 100 message types, and I'm concerned about the classload overhead for features we mostly don't use, considering even an empty message is around 40k on disk compiled.
