### ISSUE TITLE
cmake .proto with multiple extensions (+patch proposal)

### ISSUE THREAD

**Issue by djobet** [protocolbuffers/protobuf#5112]
Hello,

I have already reported this issue on cmake's bugtracker and have been asked to report it here.
See https://gitlab.kitware.com/cmake/cmake/issues/18329 for reference.

Here's a summary of the issue.

the following does not work :
```
protobuf_generate_cpp(PROTO_SRCS PROTO_HRDS PROTO_PATH ${CMAKE_SOURCE_DIR} service.requests.proto)
add_library(proto STATIC ${PROTO_SRCS} ${PROTO_HRDS})
target_include_directories(proto PUBLIC ${CMAKE_BINARY_DIR})
target_link_libraries(proto PUBLIC protobuf::libprotobuf)
```
as FindProtobuf.cmake will use
`get_filename_component(FIL_WE ${FIL} NAME_WE)`
to extract the name without extension which in that case will return "service" instead of "service.requests".
protoc will generate files service.requests.pb.cc and service.requests.pb.h while PROTO_SRCS will contain service.pb.cc and PROTO_HRDS will contain service.pb.h
The following patch will resolve the issue
```
$ diff -bup cmake-3.10/Modules/FindProtobuf.cmake.orig cmake-3.10/Modules/FindProtobuf.cmake
--- cmake-3.10/Modules/FindProtobuf.cmake.orig      2018-08-29 09:04:57.119432067 +0100
+++ cmake-3.10/Modules/FindProtobuf.cmake   2018-09-05 10:42:24.054659476 +0100
@@ -168,7 +168,11 @@ function(PROTOBUF_GENERATE_CPP SRCS HDRS
 
   foreach(FIL ${PROTO_FILES})
     get_filename_component(ABS_FIL ${FIL} ABSOLUTE)
-    get_filename_component(FIL_WE ${FIL} NAME_WE)
+    #get_filename_component(FIL_WE ${FIL} NAME_WE)
+    # NAME_WE is longest extension, we want shortest extension, so need to recode it
+    get_filename_component(FIL_NAME ${FIL} NAME)
+    string(REGEX REPLACE "\\.[^.]*$" "" FIL_NAME_WE ${FIL_NAME})
+    set(FIL_WE "${FIL_NAME_WE}")
     if(NOT PROTOBUF_GENERATE_CPP_APPEND_PATH)
       get_filename_component(FIL_DIR ${FIL} DIRECTORY)
       if(FIL_DIR)
```

**Comment by xfxyjwf** [comment]
So cmake get_filename_component considers ".requests.proto" as the extension but protoc thinks ".proto" is the extension. I would agree with protoc in this case. This seems like a bug in get_filename_component and your patch is a workaround for the bug. It looks acceptable to me but maybe the better solution is to avoid multiple "." in the file names?

**Comment by djobet** [comment]
Well no, get_filename_component has no bug, it's just the way it works. Cmake guys asked me to provide a new component to get_filename_component to extract the longest extension.
As for changing the filename and avoid multiple ".", I cannot do that. I'm porting an existing project from premake to cmake, and although it could be acceptable to rename them, I've been asked to make the lowest number of changes to the source tree.
To me, there is a discrepancy in the way protoc handles file names and how FindProtobuf handles  file names. It is clearly a bug.

**Comment by djobet** [comment]
@xfxyjwf any news ?

**Comment by djobet** [comment]
FYI, it looks like cmake added a new get_filename_component here : https://gitlab.kitware.com/cmake/cmake/issues/18329

protobuf's cmake could be fixed easily now

**Comment by BSBandme** [comment]
Got it. I think we can do nothing on our side for this issue.
Since it has been fixed in FindProtobuf.cmake, will close for now.
If you still have any questions, feel free to reopen this.
