### ISSUE TITLE
File-backed support for ByteString

### ISSUE THREAD

**Issue by atorr0** [protocolbuffers/protobuf#5120]
**What language does this apply to?**
The primary language is (but not limited to) Java.

**If it's a proto syntax change, is it for proto2 or proto3?**
No proto syntax change required (in advance), but it could be interesting to be it hinted somehow.

**If it's about generated code change, what programming language?**
Currently Java, but C# seems to lack it too.

**Describe the problem you are trying to solve.**
The `bytes` type is generated into ByteString, but all the implementations store the data in memory.

**Describe the solution you'd like**
This featrue requests to store such data in a (temporary) file if some criteria are met.

**Describe alternatives you've considered**
Create a new implementation of ByteString delegating most of the logic, but those methods dealing with byte[] and Input/OutputStream.

**Comment by BSBandme** [comment]
Put into P3 requests as this may not be in our main road map.

**Comment by haon4** [comment]
ByteString implementation needs to live in memory to enforce immutability. If it is file-backed, there is no guarantee if data may changed, making it very difficult for validation. I don't think we will be able to support this safely.
