### ISSUE TITLE
protoc --encode is incompatible with --descriptor_set_in

### ISSUE THREAD

**Issue by stepancheg** [protocolbuffers/protobuf#5128]
**Describe the problem you are trying to solve.**

```
protoc --encode=MyMessageType --descriptor_set_in=mydescriptors.bin
```

doesn't work, error is: `Missing input file.`

**Describe the solution you'd like**

Command above should behave like

```
protoc --encode=MyMessageType mydescriptor.proto
```

**Describe alternatives you've considered**

Keep `mydescriptor.proto` even if data is already compiled to `FileDescriptorSet`

**Additional context**

```
% protoc --version
libprotoc 3.6.0
```

**Comment by BSBandme** [comment]
Deprioritized this feature request.

**Comment by haberman** [comment]
Fixed in https://github.com/protocolbuffers/protobuf/pull/7698.
