### ISSUE TITLE
missing definition of PROTOBUF_MIN_PROTOC_VERSION

### ISSUE THREAD

**Issue by peiworld** [protocolbuffers/protobuf#5129]
missing PROTOBUF_MIN_PROTOC_VERSION defined

**Comment by xfxyjwf** [comment]
Can you provide more context? What are you doing, what you expect to happen and what happened?

**Comment by peiworld** [comment]
Basically, some .h files are checking PROTOBUF_MIN_PROTOC_VERSION, but this is not defined in other project files.

Regards,

Peizhao Hu

**Comment by mikelui** [comment]
This is a silent error in most cases.

As of version `3.7.0` : 

```
// foo.proto
syntax = "proto3";
message Foo {
}
```

```sh
$ protoc --cpp_out . foo.proto
$ g++ -Werror=undef -c foo.pb.cc
In file included from foo.pb.cc:4:
foo.pb.h:16:15: error: "PROTOBUF_MIN_PROTOC_VERSION" is not defined, evaluates to 0 [-Werror=undef]
 #if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
```

`PROTOBUF_MIN_PROTOC_VERSION` doesn't exist in any protobuf headers. Without `-Werror-undef`, it'll just assume the minimum version is `0`.

There's two probable alternatives: 
- `PROTOBUF_MIN_HEADER_VERSION_FOR_PROTOC` in `google/protobuf/port_def.inc`
- `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION` in `google/protobuf/stubs/common.h`.

I'm guessing an update in the headers wasn't reflected in protoc at some point.
