### ISSUE TITLE
error: parse proto error, format: json, error: Error occurred during parsing: No such field: @type

### ISSUE THREAD

**Issue by sisishiliu** [protocolbuffers/protobuf#5130]
**What version of protobuf and what language are you using?**
Version: master.
Language: PHP, extension

**What operating system (Linux, Windows, ...) and version?**
macosx

**What runtime / compiler are you using (e.g., python version or gcc version)**

osx

**What did you do?**

original json:

```
{"action":"api.friend.profile","body":{"@type":"type.googleapis.com/site.ApiFriendProfileRequest","userId":"6de4e68cbe516e0dbf30996b2128d1e9062a2907"},"header":{"_3":"df7573cc-2bd3-43f6-ac93-9ae998400c4c","_4":"http://192.168.3.20:8080/","_8":"1"},"packageId":621}
```

error: error: parse proto error, format: json, error: Error occurred during parsing: No such field: @type

but the field "@type" is exists.

**Comment by TeBoring** [comment]
Currently, php c extension's json parsing doesn't work for Any. Working on the fix.
