### ISSUE TITLE
google/protobuf/timestamp.proto not found

### ISSUE THREAD

**Issue by baqquan** [protocolbuffers/protobuf#5131]
I was going through the examples to installing protobuf and I am always getting

```addressbook.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.```
```addressbook.proto:44:3: "google.protobuf.timestamp" is not defined.```

This always happens whenever i do a ```make go```, a ```make python```, and I'm sure its going to be the same with the other languages as well. 

I checked my /usr/local/include/ and it has the right timestamp.proto package. I'm guessing I am missing something but through lots of googling i haven't seen an explicit answer. Can anyone guide me to the right spot?

**Comment by xfxyjwf** [comment]
How did you install protoc? Can you check if the protoc you are running is in /usr/local/bin?
```
which protoc
```
?

**Comment by xfxyjwf** [comment]
Also check the protoc version. You may have an older version of protoc preinstalled.
```
protoc --version
```

**Comment by baqquan** [comment]
I installed by using the link https://github.com/protocolbuffers/protobuf/releases. I have 3.6.1 version installed. I am currently using the protoc in my goworkspace bin folder. Should it be using the /usr/local/bin?

**Comment by ervinb** [comment]
@baqquan No, it doesn't have to be in `/usr/local/bin`, but the path where it's installed has to be included in the `PATH`. Example of a working setup:

```
$ which protoc
/opt/protobuf/bin/protoc

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/protobuf/bin:/Users/baer/go/bin
```

The included `.proto` files are then in `/opt/protobuf/include/`, so `timestamp.proto` is at `/opt/protobuf/include/google/protobuf/timestamp.proto`.


Lastly, it's included it with: `import "google/protobuf/timestamp.proto";`

**Comment by lucas1993ch** [comment]
osx
$ which protoc
/Users/Macbook/go/bin/protoc
and then you put `include` under /Users/Macbook/go/
other platform(windows,linux) are the same too.

**Comment by amazingandyyy** [comment]
any updates???

**Comment by baqquan** [comment]
I apologize for not getting to this sooner. This has been resolved. I had
brew installed which had its own instance of protoc and it was causing
conflicts.

**Comment by chaitan94** [comment]
@amazingandyyy if you are doing this inside an alpine image, make sure you do `apk add protobuf-dev` before generating your files using `protoc`.

**Comment by amazingandyyy** [comment]
@chaitan94  ok and may I ask what are they different? thanks

**Comment by chaitan94** [comment]
@amazingandyyy do you mean what's the difference between `protobuf` and `protobuf-dev`? If so, it's as simple as the fact that the original package has the bare minimum files needed for `protoc` to function. This also includes the file relevant to this issue, `/usr/include/google/protobuf/timestamp.proto`.

For more datails check out the pages on alpinelinux.org for [protobuf](https://pkgs.alpinelinux.org/contents?branch=edge&name=protobuf&arch=x86_64&repo=main) and [protobuf-dev](https://pkgs.alpinelinux.org/contents?branch=edge&name=protobuf-dev&arch=x86_64&repo=main)

**Comment by BSBandme** [comment]
Close for now as correct answer has been provided :)
