### ISSUE TITLE
declaration of variable hides previous local declaration

### ISSUE THREAD

**Issue by l33ds** [protocolbuffers/protobuf#5132]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 7
**What runtime / compiler are you using (e.g., python version or gcc version)**
VS 2017
**What did you do?**
1. Compile my project while linking to protobuff

**What did you expect to see**
Clean Compilation

**What did you see instead?**
...google/protobuf/map_entry_lite.h(357): warning C4456: declaration of 'size' hides previous local declaration...

It's here:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/map_entry_lite.h#L362

**Comment by BSBandme** [comment]
Close as it has been fixed in af3813cd7337c622df067914cfa22732c08d6067
