### ISSUE TITLE
Static Code Analysis Findings

### ISSUE THREAD

**Issue by codeanalysis9876** [protocolbuffers/protobuf#5133]
Poor Style:   Redundant Initialization - At Line: 390 of File:   opt/buildtools-network/gcc-4.8.2/protobuf-2.3.0/include/google/protobuf/wire_format_lite_inl.h
--

**Comment by moreal** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wire_format_lite_inl.h

Did you mean this?

**Comment by BSBandme** [comment]
Close for obsolete for newest version.
