### ISSUE TITLE
Repeated field is empty on the client side even though it is set on the server side

### ISSUE THREAD

**Issue by jiongjiongli** [protocolbuffers/protobuf#5134]
The repeated field of protobuf message is always empty on the gRPC client side even though I set it on the gRPC server side.
Is there any way to fix this issue?

# helloworld.proto file:

    syntax = "proto3";

    package helloworld;

    // The greeting service definition.
    service Greeter {
      // Sends a greeting.
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

    // The request message containing the user's name.
    message HelloRequest {
      string name = 1;
    }

    // The response message containing the greetings.
    message HelloReply {
      string message = 1;
      repeated string snippets = 2;
    }

# server.py

    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function

    from concurrent import futures
    import time

    import grpc

    import grpc_demo.lib.protos.helloworld_pb2 as helloworld_pb2
    import grpc_demo.lib.protos.helloworld_pb2_grpc as helloworld_pb2_grpc

    _ONE_DAY_IN_SECONDS = 60 * 60 * 24

    class Greeter(helloworld_pb2_grpc.GreeterServicer):

        def SayHello(self, request, context):
            reply = helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
            reply.snippets.append('test-snippets')
            # print('reply:' + reply)
            return reply

    def main():
        """Main entrance."""

        server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
        helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
        server.add_insecure_port('[::]:50051')
        server.start()
        try:
            while True:
                time.sleep(_ONE_DAY_IN_SECONDS)
        except KeyboardInterrupt:
            server.stop(0)

    if __name__ == '__main__':
        main()

# client.py

    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function

    import grpc

    import grpc_demo.lib.protos.helloworld_pb2 as helloworld_pb2
    import grpc_demo.lib.protos.helloworld_pb2_grpc as helloworld_pb2_grpc

    def main():
        """Main entrance."""

        # NOTE(gRPC Python Team): .close() is possible on a channel and should be
        # used in circumstances in which the with statement does not fit the needs
        # of the code.
        with grpc.insecure_channel('localhost:50051') as channel:
            stub = helloworld_pb2_grpc.GreeterStub(channel)
            response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
        print("Greeter client received: " + response.message + ', '.join(response.snippets) 
            + str(len(response.snippets)))

    if __name__ == '__main__':
        main()

# Expected Result:

`Greeter client received: Hello, you!test-snippets1`

# Actual Result:

`Greeter client received: Hello, you!0` 

Thanks!

**Comment by BSBandme** [comment]
Close for now as seems it is not reproducible stably.
Feel free to reopen if the problem still exists

**Comment by Taigar2000** [comment]
This problem reproducing in this case:

Proto file
```
syntax = "proto3";
    message ItemsBySkuResponse {
    message Item {
        int64 sku = 1;
        int64 variant_id = 2 [deprecated = true];
        int64 external_variant_id = 3 [deprecated = true];
        int64 seller_id = 4;
        int64 seller_contractor_id = 5 [deprecated = true];
        string delivery_schema = 6;
        int64 item_type_id = 7;
        int64 commercial_type_id = 8 [deprecated = true];
        double vat = 9;
        bool is_enabled = 10 [deprecated = true];
        int64 metazon_item_type_id = 11 [deprecated = true];
        string serial_number = 12 [deprecated = true];
        double weight = 13;
        int64 width = 14;
        int64 height = 15;
        int64 depth = 16;
    }
    message Error {
        int64 sku = 1;
        string code = 2;
        string message = 3;
    }
    repeated Item items = 1;
    repeated Error errors = 2;
}
```

File
```
from isfs_itemBySku_pb2 import ItemsBySkuResponse

if __name__ == '__main__':

    x = b'\x1a8\x08\xd8\x8f\xfb\x82\x02\x12\x0eitem_not_found\x1a invalid id or item is not exists'
    value_pb = ItemsBySkuResponse()
    print("Value: ", value_pb.FromString(x))
```

Output:
`Value:  `
