### ISSUE TITLE
[python] deprecated collections usage

### ISSUE THREAD

**Issue by TheKevJames** [protocolbuffers/protobuf#5135]
The `Python` module has a deprecated usage pattern for `collections.abc`. Here's the warning I'm getting:

```
/usr/local/lib/python3.7/site-packages/google/protobuf/internal/containers.py:340: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  collections.MutableSequence.register(BaseContainer)
```

Any references to `collections.MutableSequence` should instead become `collections.abc.MutableSequence` in any Python >= 3.3. The same thing applies to `collections.Mapping` (eg. `collections.Mapping` -> `collections.abc.Mapping`).

**Comment by anandolee** [comment]
Are you happy to help create a PR for this?

**Comment by tseaver** [comment]
Note that `collections.abc` was added in Python 3.3.  You will need a compatibility import to support older Pythons (2.7 in particular), e.g.:

```python
try:
    from collections import abc as collections_abc
except ImportError:
    import collections as collections_abc
```

And then refer to `collections_abc.MutableMapping`, etc.

**Comment by tseaver** [comment]
@anandolee I'm afraid #5195 only addressed the `google.protobuf.internal.containers` module.  There are others which need the same treatment:

```bash
$ git grep -l "collections\.[A-Z]"  python/
python/google/protobuf/internal/_parameterized.py
python/google/protobuf/internal/message_test.py
python/google/protobuf/internal/well_known_types.py
python/google/protobuf/internal/well_known_types_test.py
```
