### ISSUE TITLE
Default instance of WellKnownTypes.Empty

### ISSUE THREAD

**Issue by cactuaroid** [protocolbuffers/protobuf#5138]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
`Google.Protobuf.WellKnownTypes.Empty` redundantly requires to be `new`. `Empty` is just empty.

**Describe the solution you'd like**
Add static readonly field `Empty.Default` to provide default instance.
https://github.com/cactuaroid/protobuf/commit/df3776305b8e81e35aef3319875c0a620f4df746

This is a same approach as [EventArgs.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.eventargs.empty?view=netframework-4.7.2). Probably default instance should be named `Default`.

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by jskeet** [comment]
This implies that it's completely immutable - which isn't quite the case, given that unknown fields can be present. It would be possible for someone to merge a `CodedInputStream` into `Empty.Default` and then a completely different piece of code within the same application would see that change if they ever serialized `Empty.Default`.

I think this would be better done on a per-application basis, where there's more knowledge of the code. (It's trivial for any application to do.)

**Comment by cactuaroid** [comment]
I didn't know the case `Empty` can be nonempty. I understood.
