### ISSUE TITLE
Protobuf uses std::call_once

### ISSUE THREAD

**Issue by noloader** [protocolbuffers/protobuf#5140]
`std::call_once` is mostly broken and it should not be used. There are some bad interactions among GCC, glibc and pthreads. About the only platform you can count on  `std::call_once` to work as expected is Intel IA-32 platforms.

Another project I work with is C++ and we hit some nasty unexplained crashes on AIX, Aarch64, and Solaris when using it. We did not hit the bug on ppc64-le like reported below, however.

Also see [call_once not C++11-compliant on ppc64le](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66146).

(Microsoft is another can of worms with their magic statics, dynamic initialization and call once. Don't believe a damn thing that company publishes. They use MSDN and C++ Feature matrices as marketing bullshit).

**Comment by gerben-s** [comment]
We use google::protobuf::internal::call_once which is implemented as std::call_once in once.h. This is on purpose to allow a custom implementation. MSVC is severely bad with global atomics and initialization, that I have no good advice on a good custom implementation.

**Comment by snnn** [comment]
What do you mean "Don't believe a damn thing that company publishes" ?

Even you don't like, Microsoft eats his own dog food. magic statics and std::call_once are widely used in all MS products, including Windows. magic statics, constexpr and std::call_once are new language features, therefore when they were added, they were kind of broken in all compilers and all platforms.  But there are stable now. If you are using the latest Visual Studio, you'll be fine.  If you need to compatible with the older compiler version, then you should use the InitOnceExecuteOnce Windows API.

**Comment by mux** [comment]
I am currently experiencing issues with code crashing with Ubuntu 20.04 that seems to be related to the usage of std::call_once. The protobuf version used is 3.6.1.3. The only solution I have found so far is to use the custom implementation that can be found at this URL:
https://github.com/google/sentencepiece/blob/master/python/once.h

This implementation was written for a completely unrelated python project that seemed to experience the exact same kind of crashes.

I understand from previous comments that using atomics may not be a viable option for MSVC. My questions are, is this issue still on the radar and being worked on? Is the above implementation suitable for protobuf? Could these crashes actually be a symptom of other underlying issues that I should look into on my side?

Thanks in advance!

**Comment by snnn** [comment]
> I understand from previous comments that using atomics may not be a viable option for MSVC. My questions are, is this issue still on the radar and being worked on? 

You don't need to worry it. For people who have concerns on MSVC: std::call_once works perfectly with it. At first, there were some bugs. Later on they were fixed.  Compiler is a software too. Compiler always has bugs. Nobody is perfect. 

(I'm a Microsoft employee)

**Comment by snnn** [comment]
@mux, I can't answer you question. I'm not a protobuf maintainer. 

There are several ways to implement call once:

1. Use InitOnceExecuteOnce function. It doesn't require a decent C++ compiler since it is C. But it doesn't support Windows XP.
2. Use std::call_once. Read this: https://devblogs.microsoft.com/cppblog/stl-fixes-in-vs-2015-part-2/. But the bug has been fixed many many years ago. 
3. Use magic statics. The constructor of a function local static variable will only be called once. It requires C++11.

For me, they are enough. I don't think there is a need to "roll your own". 

constexpr doesn't mean the variable must be initialized statically. Before C++20, there is no way put such an ask. That's why constinit was added.  Without constinit, all custom implementations are risky.

**Comment by mux** [comment]
I wanted to share with others who might be having the same issue that changing the TLS model at compilation time fixed this issue for me. The code was using the most efficient, but also the most restrictive TLS model: local-exec. Using initial-exec works fine, and local-dynamic and global-dynamic should be too. This suggests that the protobuf library has some __thread variables, explaining why local-exec wouldn't work - although I have not tried to verify this theory.
