### ISSUE TITLE
Add py_proto_library example to examples/BUILD

### ISSUE THREAD

**Issue by haikalpribadi** [protocolbuffers/protobuf#5147]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
It is currently a struggle to find a reliable source of information and tools to compile proto files into Python. Our use case is for GRPC.

**Describe the solution you'd like**
I found the examples for `java_proto_library` in [examples/WORKSPACE](https://github.com/protocolbuffers/protobuf/blob/master/examples/WORKSPACE) and [examples/BUILD](https://github.com/protocolbuffers/protobuf/blob/master/examples/BUILD) to be very useful, and very easy to follow.

I struggled to find any guide for doing the same thing in python. Then I found that the method `py_proto_library` is actually available in [protobuf.bzl:364](https://github.com/protocolbuffers/protobuf/blob/ff3891dab1b1f462d90a68666d14f57eb5fea34f/protobuf.bzl#L364)

Would it be possible to extend the examples to show how to build proto files for Python? Thank you!

**Describe alternatives you've considered**

I've tried the following two options without any luck.
https://github.com/pubref/rules_protobuf/tree/master/python
https://stackoverflow.com/questions/50930301/bazel-py-proto-library-is-not-defined

I also tried to integrate `protobuf.bzl:py_proto_library` to our repository directly and did not succeed.

**Additional context**
none.

**Comment by anandolee** [comment]
Is  gRPC tools good for your case? 
https://grpc.io/docs/quickstart/python.html#install-grpc-tools
