### ISSUE TITLE
Add `Serializable` attribute to generated C# classes

### ISSUE THREAD

**Issue by Danl2620** [protocolbuffers/protobuf#5148]
**What language does this apply to?**

Just the generated C#.

**Describe the problem you are trying to solve.**

Generated C# classes should be serializable by default. The official method of implementing this is to use the `Serializable` attribute on class declarations.

The specific use case I have is to make the instances of the generated classes visible in the inspector in Unity3d, which relies on the `Serializable` attribute.

**Describe the solution you'd like**

The C# code generator should add the `[System.Serializable]` attribute before every class declaration. Putting this behavior behind a command-line option is also reasonable, but not necessary.

**Describe alternatives you've considered**

I considered an automated tool to rewrite the generated `.cs` files to add the attribute.

**Additional context**

[Documentation for the Serializable attribute.](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netcore-2.1)

**Comment by ObsidianMinor** [comment]
Putting this behind an option will likely be necessary as System.Serializable is not available in any .NET Standard before 2.0

**Comment by Danl2620** [comment]
Are you interested in a pull request to fix this?

**Comment by ObsidianMinor** [comment]
Sure.
