### ISSUE TITLE
PHP extension  ,    empty value will be ignored  in repeated string 

### ISSUE THREAD

**Issue by jet6666** [protocolbuffers/protobuf#5152]
**What version of protobuf and what language are you using?**
Version: master/v3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
 php extension :3.6.1

**proto
message TestResponse {
	repeated string test3=3;
}

**Code:
`
//encode
$p =  new TestResponse ();
//there is an empty value in array
$p->setTest3(array('a','','c'));
$packed=$p->serializeToString();

//decode
$p2 = new TestResponse();
$p2->mergeFromString($packed);

 var_export($p2->getTest3()[0]); // 'a'
 var_export($p2->getTest3()[1]); // 'c'
 var_export($p2->getTest3()[2]); //wrong
`

**Comment by TeBoring** [comment]
Are you using c extension or php implementation?

**Comment by haberman** [comment]
I have verified that this bug no longer exists in the current version.
