### ISSUE TITLE
 what factors decide if cpp _message for python will be build

### ISSUE THREAD

**Issue by matibens** [protocolbuffers/protobuf#5154]
i have hard time understanding what factors decide if cpp _message for python will be build when installing by pip.
i have machine_1 (centos6) with python2.7 +python3.6 and machine_2 (centos7) with python3.7. Only python3.6 on machine_1 uses cpp_message. All versions are installed inside virtualenv. 

When i try to change PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp it fails because of missing _message shared object. 

Traceback (most recent call last):
  File "perf.py", line 1, in <module>
    import addressbook_pb2 as book
  File "/home/vacica/perf/3.6/addressbook_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/vacica/Envs/experimental/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/home/vacica/Envs/experimental/lib/python3.7/site-packages/google/protobuf/pyext/__init__.py)

Any clues what should i look for?

machine_2 centos7 python3.7
python -c "from google.protobuf.internal import api_implementation;import sys;print(api_implementation._default_implementation_type);print(sys.version_info)"
python
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

machine_1  centos6 python2.7
python -c "from google.protobuf.internal import api_implementation;import sys;print(api_implementation._default_implementation_type);print(sys.version_info)"
python
sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)

machine_1 centos6 python3.6
 python -c "from google.protobuf.internal import api_implementation;import sys;print(api_implementation._default_implementation_type);print(sys.version_info)"
cpp
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

Thank you

**Comment by JamesOldfield** [comment]
When you installed protobuf with Python 3.6, it got a prebuilt binary version of protobuf including the C++ implementation. These binary Python packages are called "wheels", and you can see the wheels available for protobuf over at the [PyPI page for protobuf](https://pypi.org/project/protobuf/#files). In particular, that list includes `protobuf-3.6.1-cp36-cp36m-manylinux1_x86_64.whl`, which is the Python 3.6 binary wheel for Linux. (The Linux distribution must satisfy the "manylinux1" spec, which almost all modern Linux installations do so long as you install a few basic packages [listed in the spec](https://www.python.org/dev/peps/pep-0513/#id40)).

If you install protobuf and there is no matching binary wheel, then the pure-Python source distribution will be installed instead: `protobuf-3.6.1.tar.gz` in that list. This is the case for Python 3.7, which does not have a binary wheel listed on that page. This explains the difference in behaviour.

If you are determined to use the C++ implementation of protobuf with Python 3.7 then you will have to build it yourself. This requires more than setting an environment variable before running pip. The process is quite involved and I'm not sure it's documented anywhere. At the very least, I believe you need to download and build the overall protobuf library (at least it did when I last did it, but that was over a year ago). It is unlikely to be worth the hassle unless you have specific performance requirements.

**Comment by arthur-tacca** [comment]
Sorry, I didn't notice that you had got a non-C++ implementation for 2.7 too. The only reason I can think of is that there is a mismatch in the [Unicode wideness](https://www.python.org/dev/peps/pep-0513/#ucs-2-vs-ucs-4-builds) of the wheel vs the Python distribution, which is a problem that cannot occur as of Python 3.3. But I'm really not sure if it's that or what else it could be.

**Comment by JamesOldfield** [comment]
Sorry, I didn't notice that you had got a non-C++ implementation for 2.7 too. The only reason I can think of is that there is a mismatch in the [Unicode wideness](https://www.python.org/dev/peps/pep-0513/#ucs-2-vs-ucs-4-builds) of the wheel vs the Python distribution, which is a problem that cannot occur as of Python 3.3. But I'm really not sure if it's that or what else it could be.

**Comment by christian-storm** [comment]
Any idea when a wheel for python 3.7 on Mac will be available given that 3.7 has been out now for a few months?  I've tried to compile myself but as noted by @JamesOldfield  it is quite involved and not documented.

**Comment by haberman** [comment]
This question is obsolete; newer versions of protobuf use `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb`. The old backend `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp` is deprecated/removed: https://github.com/protocolbuffers/protobuf/tree/main/python#implementation-backends
