### ISSUE TITLE
Javascript: stream listeners call order inside `onEnd`

### ISSUE THREAD

**Issue by Revinand** [protocolbuffers/protobuf#5155]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Linux (Ubuntu 18.04)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**What did you do?**
I compiled my proto files with the following command

```
protoc --plugin=protoc-gen-ts=<path> --js_out=import_style=commonjs,binary:<path> --ts_out=service=true:<path> --proto_path=<path>
```

In a compiled `_service.js` file with stream methods, streams have `onEnd` method. I have an issue with an order of listeners call inside this method

**What did you expect to see**
I expected to see `listeners.stats` loop to be called before `listeners.end`

```
onEnd: function (status, statusMessage, trailers) {      
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler();
      });
      listeners = null;
}
```

**What did you see instead?**
```
onEnd: function (status, statusMessage, trailers) {      
      listeners.end.forEach(function (handler) {
        handler();
      });
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
}
```

**Anything else we should know about your project / environment**

I use streams inside Redux Saga channels. When some error is returned from the server I close that Saga channel inside an `end` event listener. The channel close command calls `stream.cancel()` and I got an error `Cannot read property 'status' of null`. Maybe the order of these loops should be changed? For me it looks more reasonable to show status before the end.

**Comment by xfxyjwf** [comment]
Protobuf doesn't generate service code. If the service code is generated by protoc-gen-ts, you probably want to ask on the issue tracker for that project instead.
