### ISSUE TITLE
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly! - Protocol Buffer installation

### ISSUE THREAD

**Issue by deji04** [protocolbuffers/protobuf#5159]
Hi everyone,

I am installing the Java Protocolbuffer compiler and a warning was prompting during the Build Process of installation of Maven

_com.google.protobuf.CodedOutputStream writeStringNoTag
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly!_

![image](https://user-images.githubusercontent.com/43259911/45611893-b4bc5380-ba93-11e8-88e8-d1173e74cc3b.png)
It's been running for 7hrs already. And I cant proceed any further. 

The previous command i ran was: **mvn install** t

Please help!!!

**Comment by deji04** [comment]
Hi Feng @xfxyjwf 

Can you please help me on this one? Thanks!

**Comment by congyulu** [comment]
你传输的编码用的啥呀？

**Comment by xfxyjwf** [comment]
these warnings are expected in the tests. You can safely ignore them as long as the tests pass.

**Comment by deji04** [comment]
Hi Feng @xfxyjwf, 

Thank you for the response. As I look back today on the process, it went ahead with no errors. However, I find this confusing since after the method (testBytes) ended, it went back to the same process. Is this normal? 

![image](https://user-images.githubusercontent.com/43259911/45659528-956f0600-bb27-11e8-9d35-3cee9045ab40.png)

Again, thank you for the time and patience!

**Comment by deji04** [comment]
Hi everyone,

Just to let you know that the Build just finished after 30hrs.
![image](https://user-images.githubusercontent.com/43259911/45669707-74bca580-bb53-11e8-8507-ce80f1ea53ee.png)

My only question is that is this the normal installation time? Or it depends on the memory or what machine the Java Protoc is ran? 

Thank you for your response!

**Comment by acozzette** [comment]
There are a couple of tests that can be a bit slow because they iterate over all possible 3-byte UTF-8 symbols. I'm a bit surprised that they would cause the full test run to take 30 hours, but still maybe there is something we could do to speed them up.

**Comment by deji04** [comment]
Hi Adam,

Thanks for clarifying!

Or does memory or disk space affects the run of installation?

**Comment by acozzette** [comment]
I don't know for sure because I am not too familiar with those tests, but my impression was that it was just an issue of CPU, since there are some tests iterating over all 2^24 3-byte UTF-8 characters and performing a check on each one.

**Comment by deji04** [comment]
Thanks Adam for the responses!

I am going to close this now. But if ever I have questions regarding Protobuf again, I might raise questions here again.

Thank you!
