### ISSUE TITLE
Messages with wrappers throw an error at jspb.Message.setWrapperField when making client requests

### ISSUE THREAD

**Issue by sadief** [protocolbuffers/protobuf#5162]
Hi there,
We are trying to make a request to our gRPC service from a React Client. The Unary request works fine with normal message fields, however on message fields that have wrappers around them, we get this error: 
```
TypeError: c.toArray is not a function
Function../node_modules/google-protobuf/google-protobuf.js.jspb.Message.setWrapperField
```

Relating to this function:

```
 /** @param {?proto.google.protobuf.Int64Value|undefined} value */
 proto.api.ListRequest.prototype.setLimit = function(value) {
   jspb.Message.setWrapperField(this, 1, value);
};

jspb.Message.wrapRepeatedField_=function(a,b,c){a.wrappers_||(a.wrappers_={});if(!a.wrappers_[c]){for(var d=jspb.Message.getRepeatedField(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.wrappers_[c]=e}};jspb.Message.setWrapperField=function(a,b,c){a.wrappers_||(a.wrappers_={});var d=c?c.toArray():c;a.wrappers_[b]=c;jspb.Message.setField(a,b,d)};

```

Our gRPC service and request messages are set up like so:
```
  rpc List(ListRequest) returns (ListResponse) {
     option (google.api.http) = {
      get: "/v3/items"
    };
  }

message ListRequest {
  google.protobuf.Int64Value limit = 1;
  google.protobuf.StringValue name = 2;
  google.protobuf.BoolValue isActive = 3;
  QueryMeta Meta = 100;
}

message QueryMeta {
  string cursor = 1;
}

```

And we are sending the request from the client like this:

```
    const query = new ListRequest();
    query.setLimit(4);
    query.setName("Test address");
    query.setAddress("test address");
    query.setIsactive(false);

    const c = new TestClient("https://testurl.com");
    var md = { authorization: "Bearer " + JWT };
    c.list(query.serializeBinary(), md, function(err, response) {
      if (err) {
        console.log("Error Code:", err.code);
        console.log("Error Message:", err.message);
      } else {
        console.log("Response:", response);
      }
    });
```
But as soon as it hits the first 'query.set..' it throws the above error. 

Versions being used are:
 "google-protobuf": "^3.6.1",
 "ts-protoc-gen": "^0.7.7-pre.5959599",

Running on the latest version of Google Chrome.

Thanks!

**Comment by rnovosad** [comment]
Have the same problem!!

**Comment by TeBoring** [comment]
I think we haven't had the convenient method set up for wrapper type yet. Therefore, you cannot simply call setLimit(1). You can try ```query.setLimit(new Int32Value(4))```

**Comment by rnovosad** [comment]
thanx for the reply
But this combination `request.setLimit(new Int32Value(args.limit))` doesn't work and throws error
`TS2554: Expected 0 arguments, but got 1.`
So I wrote a wrapper for it 
```const toInt32Value = (value?: number) => {
  const num = new Int32Value()
  if (value) {
    num.setValue(value)
    return num
  }
  return
}

**Comment by TeBoring** [comment]
Any more info about the error: ```Expected 0 arguments, but got 1```? 
What's the error referring to?

**Comment by Jobberd** [comment]
+1

**Comment by rnovosad** [comment]
@TeBoring it can't instantiate new object. so the `new Int32Value()` constructor doesn't accept arguments

**Comment by codepearlex** [comment]
+1

**Comment by e1337us3r** [comment]
You must use the setter for the wrappers.

```
const wrapper = new Int64Value();
wrapper.setValue(4);
query.setLimit(wrapper);
```

Same thing goes with other wrappers such as StringValue, BoolValue etc.

**Comment by SanthoshBanavath** [comment]
I am unable to set the repeated field with uint32 as keys.
here are my messages
```proto
message DataUpdate {
  uint32 source = 1;
  uint32 destination = 2;
}

message DataUpdateRequest
{
  string filepath = 1;
  repeated DataUpdate updates = 2;
}
```

and I am assigning the values as 
```ts
// this is method from the generated function using setRepeatedWrapperField(this, 1, value)
req.setUpdatesList([{
        source: 1,
        destination: 2
      }]);
```
I also tried assigning using the new UInt32Value() to set the destination and source but I am seeing the same following error
```
TypeError: c[e].toArray is not a function
    at Function.push.../../node_modules/google-protobuf/google-protobuf.js.jspb.Message.setRepeatedWrapperField (google-protobuf.js:511:1)
```

Is there any known issue around setting repeated field with wrappers? please attach here if there is better documentation to read about details like these.
