### ISSUE TITLE
A question about the difference between uint64 and long in Java

### ISSUE THREAD

**Issue by GuoqingCai** [protocolbuffers/protobuf#5163]
I use protoc.exe to convert xx.proto to xx.java ;
```
message FriendSns
{
	required int32 tag1   	        =1;
	required string tag2         	=2;
	optional string tag3		=3;
	optional uint64 tag4		=4;
	optional int32 tag5			=5;
}
```
The parameter "tag4",data type in proto is uint64,scope of it is [0,2^64),but the convertion in Java is long,and scope of long in Java is [-2^63, 2^63).

**My question is how to set data between 2^63 and 2^64-1 into tag4？**

**Comment by BSBandme** [comment]
Well, unfortunately Java has no unsigned type, which is out of our scope. You need to deal with long carefully to meet your requirement. e.g. Long.toUnsignedString or using BigInt
