### ISSUE TITLE
Class 'GPBMetadata\ProtocGenSwagger\Options\Annotations' not found

### ISSUE THREAD

**Issue by vsaveliev** [protocolbuffers/protobuf#5169]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP 5.6.38

**What operating system (Linux, Windows, ...) and version?**
CentOS Linux release 7.5.1804 (Core) 

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 5.6.38 (cli) (built: Sep 12 2018 08:52:18) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**What did you do?**
I use GRPC Gateway (https://github.com/grpc-ecosystem/grpc-gateway), generate code for Go and PHP. Go code works well. But I get the error for PHP:
```
PHP Fatal error:  Class 'GPBMetadata\ProtocGenSwagger\Options\Annotations' not found
```

My *.proto file:
```
syntax = "proto3";

package foo;

import "request/request.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "protoc-gen-swagger/options/annotations.proto";

service Bar {
  rpc GetBar (request.ByID) returns (Bar) {
    option (google.api.http).get = "/v1alpha/bar/id/{ID}";
  }

  ...
}

...
```

Generated php file with metadata:
```
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo/bar.proto

namespace Foo\GPBMetadata;

class Bar
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\ProtocGenSwagger\Options\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
        ...
    }

    ...
}
```

My composer.json:
```
...
    "require": {
        "grpc/grpc": "v1.15.0",
        "google/protobuf": "v3.6.1",
        "google/gax": "0.37.0"
    },
    "repositories": [
      {
          "type": "vcs",
          "url":  "git@github.com:googleapis/gax-php.git"
      }
    ],
...
```

**What did you expect to see**
I expect to have working generated code and to have GPBMetadata\ProtocGenSwagger\Options\Annotations on any of my composer packages but I don't have it.

**What did you see instead?**
I see the fatal error and I really couldn't find this class anywhere on Github. Maybe I didn't add some additional composer package? If yes, I don't see any docs about this point.

If you need more info, please ask.

**Comment by TeBoring** [comment]
```\GPBMetadata\ProtocGenSwagger\Options\Annotations``` should be provided by the php library which uses protobuf. Could you check with the owner of that library (grpc-gateway maybe)?
