### ISSUE TITLE
[Java] Json utils: add array serialization support for protobuf messages

### ISSUE THREAD

**Issue by bullet-tooth** [protocolbuffers/protobuf#5176]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
Currently, it's not possible to serialize and deserialize an array of protobuf messages.

**Describe the solution you'd like**
To extend `JsonFormat.Parser` and `JsonFormat.Printer` with new methods.

**Comment by BSBandme** [comment]
Deprioritized to p3 feature request.
Would you please elaborate on why that API for JsonFormat is necessary?

**Comment by haon4** [comment]
You can simply put your array inside message with a repeated field. No need to extend JsonFormat class.

**Comment by bullet-tooth** [comment]
For example, I have a service that returns `List<ProtobufEntity>` and I would like to create an API endpoint that returns the data in JSON format. 
In the way you suggested it brings:
1) Additional Protobuf entity with repeated field to use as a wrapper
2) Conversion from `List` to this wrapper
3) A redundant object in the final Json:
```
{
  "entities": [ { ...}, {...} ]
}
```
instead of:
```
[ { ...}, {...} ]
```
