### ISSUE TITLE
Unable to load package for '@bazel_skylib//:lib.bzl'

### ISSUE THREAD

**Issue by bstriner** [protocolbuffers/protobuf#5178]
**What version of protobuf and what language are you using?**
Version: master
Language: Python

**What operating system (Linux, Windows, ...) and version?** 
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)** 
Python 3.7, VC2017

**What did you do?**
Build tensorflow against current protobuf releases.

**What did you expect to see**
TF includes protobuf, protobuf includes skylib, and everything should work fine. Works correctly on older versions of protobuf. No definition of skylib libraries required in tensorflow workspace.

**What did you see instead?**
If all you do is update the version of protobuf, you get the below error. Workaround is to copy the skylib definition from protobuf to tensorflow, and then the build works fine.

> ERROR: D:/projects/tensorflow/tensorflow/tools/pip_package/BUILD:218:1: error loading package 'tensorflow': Extension file not found. Unable to load package for '@bazel_skylib//:lib.bzl': The repository could not be resolved and referenced by '//tensorflow/tools/pip_package:build_pip_package'
> ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: error loading package 'tensorflow': Extension file not found. Unable to load package for '@bazel_skylib//:lib.bzl': The repository could not be resolved
> INFO: Elapsed time: 34.460s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (4 packages loaded)
>     currently loading: tensorflow

**Anything else we should know about your project / environment**

See some related discussion https://github.com/tensorflow/tensorflow/pull/21202

Thanks!

**Comment by mickeyouyou** [comment]
anything update ?

**Comment by elharo** [comment]
sounds like something that needs to be addressed in tensorflow
