### ISSUE TITLE
python timestamp objects sort "randomly"

### ISSUE THREAD

**Issue by TassoKarkanis** [protocolbuffers/protobuf#5184]
Version: v3.6.0
Language: Python
OS: Mac OS 10.13.6
Runtime: python-2.7 from conda

I have a message with a `google.protobuf.Timestamp` field:

message File {
    google.protobuf.Timestamp time_created = 1;
}

I created a bunch of objects using the corresponding generated Python classes and put them in a python list.  I set the `time_created` field to different values in different objects.  Then I called the python `sorted` function on my list:

  sorted_list = sorted(my_list, key=lambda f: f.time_created)

I expected the resulting list to be sorted in chronological order.  Instead, the list is in "random" (ie. different every time) order.  I assume this is because the Python Timestamp objects don't implement comparison operators, and my list is being sorted by object pointer.

My program worked as expected when I changed my code to this:

  sorted_list = sorted(my_list, key=lambda f: f.time_created.ToDatetime())

I think the Timestamp objects should implement chronological comparison, like the python `datetime` objects.  A similar argument can be made for Duration objects.

**Comment by TeBoring** [comment]
We probably don't have time to implement it now. Do you mind sending a PR to us?

**Comment by anandolee** [comment]
#5168 is working on Timestamp comparison
