### ISSUE TITLE
Protobuf CMake: PROTOBUF_LIBRARIES, PROTOBUF_INCLUDE_DIRS remains empty

### ISSUE THREAD

**Issue by gismo07** [protocolbuffers/protobuf#5185]
Version: master/v3.5.1 
Language: C++
OS: Ubuntu 16.04 LTS

CMake: 3.5.1 ==> restricted, so I cannot update

I'm trying to build a protobuf project on Ubuntu using CMake. Protobuf version 3.5.1 was builded on the same machine successfully. To use this specific version, the flag `NO_DEFAULT_PATH` is passed to `find_package ` and the new location of the protobuf related cmake files is passed as well.

My current CMakeLists.txt:
```
set (Protobuf_DIR "/home/ubuntu/Projects/Protobuf/build-host/lib/cmake/protobuf")
find_package(Protobuf REQUIRED NO_DEFAULT_PATH)
message("   --> PROTOBUF LIB: ${PROTOBUF_LIBRARIES}")
message("   --> PROTOBUF INCLUDE: ${PROTOBUF_INCLUDE_DIRS}")
message("   --> PROTOBUF VERSION: ${Protobuf_VERSION}")
message("   --> PROTOBUF Found: ${Protobuf_FOUND}")
```

CMake output:
```
--> PROTOBUF LIB: 
--> PROTOBUF INCLUDE: 
--> PROTOBUF VERSION: 3.5.1
--> PROTOBUF Found: 1
```

How can I solve this issue?

**Comment by haberman** [comment]
Closing as obsolete, our CMake files have undergone large changes since this bug was filed.
