### ISSUE TITLE
"make cpp" throw errors -Protobuf cpp

### ISSUE THREAD

**Issue by deji04** [protocolbuffers/protobuf#5187]
Hi,

I have an issue where when I link my cpp code file and the 2 generated files when compiling (pb.h & pb.cc), I encounter an issue.

![image](https://user-images.githubusercontent.com/43259911/46070730-16c23a80-c1b1-11e8-8494-5a8de78b4833.png)

This is my code below:
testCar.cpp
#include<iostream>
#include<string>
using namespace std;

int main(void) {
        string model;
        int capacity;
        int doors;

        cout << "Model of the car?" << endl;
        cin >> model;
        cout << "What is the capacity?" << endl;
        cin >> capacity;
        cout << "How many doors?" << endl;
        cin >> doors;

        cout << "Model is " << model << "."<< endl;
        cout << "Capacity is " << capacity << "."<< endl;
        cout << "Number of doors is " << doors << "."<< endl;

        return 0;
}

This is the command I ran when linking:
g++ -I /usr/local/include /usr/local/lib -lprotobuf testCar.cpp Car.pb.cc

Am I doing this wrong?
And can you please explain to me the how to test my cpp file and the generated classes?

Thank you!

**Comment by deji04** [comment]
Hi @xfxyjwf and @acozzette can you please help me on this one again? Thank you!

**Comment by deji04** [comment]
I saw a tutorial on how to use Protobuf.
http://simplestcodings.blogspot.com/2010/11/serialization-using-google-protobuf.html

I'll try this first and update if there is something I can't figure out.

**Comment by deji04** [comment]
Hi, 

still got the same error after following tutorial and this one: https://www.hottaro.com/index.php?mid=Linux&document_srl=8046&m=0

![image](https://user-images.githubusercontent.com/43259911/46075635-ae2d8a80-c1bd-11e8-8dcb-60640ca82637.png)

Any help is appreciated. Thank you

**Comment by acozzette** [comment]
@deji04 Could you post the full list of error messages you're seeing?

**Comment by deji04** [comment]
It's all good now. I updated my gcc version 4.8.5 to 6.3.1.

Thanks!

**Comment by deji04** [comment]
Hi @acozzette, it is regarding c++11 standard support. And what I have is the experimental support. Adding -std=c++11 to Makefile throws me another error. That's why I installed 6.3.1v of gcc. And it compiled without any errors.

Thanks!
