### ISSUE TITLE
Custom Serilization layout

### ISSUE THREAD

**Issue by MaxHayman** [protocolbuffers/protobuf#5188]
Hello,

I am currently working with a protocol which i have control over the client but not the server. Currently we are writing structures to a stream in a specific way. However different sections of the messages store things in completly different ways (e.g. numbers can be stored in seeminly random ways such as a uint64 or bitpacked, same with strings). Is it possible to define exactly how the protocol buffer serializes and deserializes the message to match this existing protocol.

**Comment by acozzette** [comment]
@MaxHayman No, protocol buffers have their own binary wire format and it's not really possible to make them match a different wire format defined somewhere else. If you have to conform to this other wire format then unfortunately protobuf probably won't be of much help.
