### ISSUE TITLE
Unspecified/Undefined behavior in enum in wire_format_lite.cc

### ISSUE THREAD

**Issue by zamazan4ik** [protocolbuffers/protobuf#5189]
Hello. In file [wire_format_lite.cc](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wire_format_lite.cc#L101) there is undefined behavior - casting to an unexistent enum value. It's prohibited by C++ standard (before C++17 behavior is unspecified, C++17 and after - undefined) - https://en.cppreference.com/w/cpp/language/enum

**Comment by sbenzaquen** [comment]
It is undefined to cast outside the range, but the range can include values that have no labels.
In any case, the enum now specifies an underlying type.
