### ISSUE TITLE
[PHP] Error serializing empty Struct to JSON

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#5192]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP (PHP runtime, not PHP extension)

```php
use Google\Cloud\Dialogflow\V2\QueryResult;
use Google\Protobuf\Struct;

$queryResult = new QueryResult;
$queryResult->setParameters(new Struct);
echo $queryResult->serializeToJsonString();
```

Output:
```
{"parameters":}
```

This JSON string cannot be decoded.

When the Protobuf PHP extension is enabled, this issue is not present.

For context, see https://github.com/googleapis/google-cloud-php/issues/1320

This issue has been confirmed with different messages also containing Struct messages.

**Comment by TeBoring** [comment]
Could you try the master branch? Recently, I have serval fixes for json encoding/decoding in c extension.

**Comment by jdpedrie** [comment]
Hi @TeBoring, thanks for the reply. I tried the master branch, and get the same output as v3.6.1.
