### ISSUE TITLE
How to specify python headers location?

### ISSUE THREAD

**Issue by 29x10** [protocolbuffers/protobuf#5199]
Hi,

We install python in a specific path,

When build envoy, it fails with `no such target '//external:python_headers'`

I didn't get this one `https://github.com/protocolbuffers/protobuf/blob/master/util/python/BUILD`

Anyone know how to specify python headers?

Best,

**Comment by 29x10** [comment]
Any update?

**Comment by anandolee** [comment]
It looks like a general python question instead of protobuf. Are you using a third library like tensorflow? I saw a similar issue here: https://github.com/tensorflow/tensorboard/issues/719

**Comment by 29x10** [comment]
Fixed by
https://github.com/envoyproxy/envoy/commit/902e20cf9024dd25ad2b307b9d7701e5851feb59
