### ISSUE TITLE
Google_protobuf failed to run the RubyGeneratorTest.Proto2GeneratorTest with release configuration and debug configuration

### ISSUE THREAD

**Issue by spacelg** [protocolbuffers/protobuf#5202]
Environment:
 Windows Server 2016 + VS2017  Google_protobuf master branch latest srouce code

Google_protobuf failed to run the RubyGeneratorTest.Proto2GeneratorTest with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance!

 1.git clone https://github.com/google/protobuf.git D:\Google-Protobuf\src
 2.Open a VS 2017 command prompt and browse to D:\Google-Protobuf
 3.mkdir build_x64_ltcg && pushd build_x64_ltcg 
 4.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\src\cmake
 5.popd
 6.msbuild /p:Configuration=Debug;Platform=x64 build_x64_ltcg\protobuf.sln /t:Rebuild
 7.pushd src
 8. ..\build_x64_ltcg\Debug\tests.exe --gtest_filter=RubyGeneratorTest.Proto2GeneratorTest

Actual result:
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RubyGeneratorTest.Proto2GeneratorTest
[log_x64_ltcg_test_1.log](https://github.com/protocolbuffers/protobuf/files/2430473/log_x64_ltcg_test_1.log)

TestErrorMessage:
[----------] Global test environment tear-down
[==========] 2003 tests from 189 test cases ran. (13537 ms total)
[  PASSED  ] 2002 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RubyGeneratorTest.Proto2GeneratorTest
 1 FAILED TEST
[command took 13 seconds]

**Comment by fowles** [comment]
Closing out old issues.  Please reopen if this still occurs on recent releases.
