### ISSUE TITLE
Calling T::descriptor() fails on Debug but works on Release in v3.6.1

### ISSUE THREAD

**Issue by alex4814** [protocolbuffers/protobuf#5204]
**What version of protobuf and what language are you using?**
Version: v3.6.1 (vcpkg)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10, 17134

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2015

    > C:\Program Files (x86)\Microsoft Visual Studio 14.0>cl /?
    Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

**What did you do?**
1. Wrote a template member function in class `Handler` like
```cpp
  template <typename T>
  void Register(void (Handler::*handler)(T*))
  {
    auto desc = T::descriptor();  // <-----

    ...
  }
```
2. Dynamically links with the protobuf library,
3. Compile and run in **Debug/x64**.

**What did you expect to see**
No crash.

**What did you see instead?**
Crash on the line in the template function above.

**Anything else we should know about your project / environment**
1. It happily runs on `Release` configuration but failed on `Debug` with exactly the same code.
2. Error message:
`Exception thrown at 0x00007FFEE03FC210 (ucrtbased.dll) in whatever.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`
3. It seems that it is still the `std::call_once` thing discussed  in #4773 and #4950.

[call_stack.txt](https://github.com/protocolbuffers/protobuf/files/2431176/call_stack.txt)

**Comment by acozzette** [comment]
@alex4814 Are you calling `T::descriptor()` before `main()` starts or is it after `main()` starts?

**Comment by dibyendumajumdar** [comment]
Hi, I am using protobuf 3.6.1 with Visual Studio 2017. The protobuf library is built using vcpkg.

In the debug version of my app, a call to `ShortDebugString();` results in an exception. I see that this occurs in the call to `message.GetDescriptor();`. 

This problem occurs in debug build only.
I don't get the error in release build.

It makes me think this might be related to the std::once problem?

**Comment by ShadowTeolog** [comment]
possible this result of using release ptrotobuf dll under debug build. For some reason I had this bug, and it disappeared after I manually link debug proto dll. Dozen of link warnings tells what somebody exposes std::string in export class, and also some functions not exported but compiled in calling program. So if program and library uses different debug/release runtime, this result crash.
This affectiong also string deserilaization and destructors
