### ISSUE TITLE
Bad parent pom for Java

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#5213]
Not sure how deep this one goes or who owns it but let's start here. In java/pom.xml I noticed this:

```
  <parent>
    <groupId>com.google</groupId>
    <artifactId>google</artifactId>
    <version>1</version>
  </parent>
```

I never saw that artifact before so I looked it up in Maven central. There are several later versions of com.google:google but none later than 2010. All reference googlecode.com as scm which is now dead.

Since I haven't seen this artifact anywhere except here, I think the answer is that we should just delete this parent element in pom.xml. However, if there's something there we need, then we need to figure out who owns this and push a long-overdue update.

**Comment by BSBandme** [comment]
Is there any policy restriction for removing \<parent\>?

In fact there are still some others use this parent, like [Guice](https://github.com/google/guice/blob/master/pom.xml#L20-L24)
You may found more by searching in internal piper maven repository central.
