### ISSUE TITLE
Linking fails on armv6l due to missing libatomic

### ISSUE THREAD

**Issue by lopsided98** [protocolbuffers/protobuf#5219]
**What version of protobuf and what language are you using?**
Version: v3.6.1

**What operating system (Linux, Windows, ...) and version?**
Linux (NixOS)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 7.3.0

**What did you do?**
When I attempted to build protobuf for armv6l, I ran into the following linker error:
```
./.libs/libprotobuf.so: undefined reference to `__atomic_fetch_add_8'
```

On armv6l, protobuf needs to be linked to `libatomic` to provide this symbol. Manually adding `-latomic` to `LDFLAGS` fixes the issue.

**Comment by acozzette** [comment]
@lopsided98 Do you want to send us a pull request with the fix?

**Comment by acozzette** [comment]
Updating just the autotools build sounds fine to me, though we are thinking about deprecating it in favor of CMake some time soon so you might want to keep that in mind. By the way, do you have any more details on why we have to explicitly link against `libatomic`? Is that just a quirk of NixOS or armv6l?

**Comment by lopsided98** [comment]
I think protobuf uses atomic intrinsics (maybe indirectly though `std::atomic`) that gcc cannot generate directly on armv6l, and instead needs to use a helper function in `libatomic` to implement them. Other architectures have instructions to implement them without `libatomic`.

I think this became a problem when protobuf stopped using its own implementations of atomic operations (`src/google/protobuf/stubs/atomicops_internals_*`) and switched to using `std::atomic` between 3.5 and 3.6.

**Comment by acozzette** [comment]
Ok, that makes sense. I wonder if it's harmless to always link explicitly against libatomic or if we need a way to do that only for certain platforms.

**Comment by lopsided98** [comment]
See #5227.

**Comment by martinblech** [comment]
Looks like there's been a regression on this issue somewhere between v3.11.4 and v3.12.2. I'm getting the same link error compiling "@com_google_protobuf//:protoc" v3.12.2 on a Raspberry Pi. v3.11.4 compiles just fine.

**Comment by FGasper** [comment]
I know this is an old issue, but does anyone know _why_ this happens on armv6l specifically?

**Comment by lopsided98** [comment]
ARMv6 lacks byte and half-word and double word atomic instructions (`LDREXB`, `LDREXH`, `LDREXD`, `STREXB`, `STREXH`, `STREXD`), so they need to be implemented with libatomic instead. See: https://developer.arm.com/documentation/dht0008/a/ch01s02s01

These instructions were actually added to the ARMv6K architecture, which appears to be supported by the ARM1176JZF-S CPU used in the BCM2835, but the compiler is not configured to target this architecture version. See: https://developer.arm.com/documentation/ddi0301/h/summary-of-arm1136jf-s-and-arm1176jzf-s-processor-differences/summary-of-differences/armv6k-extensions-support
