### ISSUE TITLE
Package names clash with the option names

### ISSUE THREAD

**Issue by dmdashenkov** [protocolbuffers/protobuf#5223]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: Java 8

**What operating system (Linux, Windows, ...) and version?**
MacOS High Sierra (10.13.6)

**What runtime / compiler are you using (e.g., python version or gcc version)**
`java` and `javac` of version 1.8.0_121.
`protoc` of version 3.6.1.
Protobuf Gradle plugin of version 0.8.5.

**What did you do?**
1. Declare a custom message option called `entity`:
```proto
// --- options.proto ---

syntax = "proto3";

// This file defines no package, since we want the option names to be short.

extend google.protobuf.MessageOptions {
    // ...
    EntityOption entity = 73903;
    // ...
}

message EntityOption {
    // ...
}
```
2. The `options.proto` file is included into a JAR artifact an published into a Maven repository.
3. A module depends on that artifact and includes the following file:
```proto
syntax = "proto3";

package spine.server.entity.groups;

import "spine/options.proto";

option java_package = "io.spine.server.entity.groups";
option java_outer_classname = "GroupProto";
option java_multiple_files = true;

import "spine/core/user_id.proto";

message Group {
    option (entity).kind = AGGREGATE;

    string name = 1;

    // ...
}
```

**What did you expect to see**
The `Group` message compiles successfully.

**What did you see instead?**
The compiler error:
`protoc: stdout: . stderr: spine/test/entity/groups/group.proto:15:12: Option "(entity)" unknown.`

In order to compile the message, one of two actions must be done:
 - remove the `(entity)` option;
 - remove "`entity`" from the package name.

**Comment by BSBandme** [comment]
Sorry but I can't repro your bug. I tried that but the code can be generated by protoc correctly.
What the command did you used for protoc?

**Comment by BSBandme** [comment]
Closed for long time no reply
