### ISSUE TITLE
Protoc version 2.7

### ISSUE THREAD

**Issue by abhijit-inge** [protocolbuffers/protobuf#5224]
This might be a naive question, But I can't seem to find the protoc version 2.7 but I do see a branch for google-protobuffers 2.7 (https://github.com/protocolbuffers/protobuf/tree/2.7.0) which I do require for my project. Could you provide the link to the protoc(MAC OSX) version 2.7 which I could download?.

**Comment by acozzette** [comment]
I believe we started a 2.7.0 branch but never actually made a 2.7 release--instead we went directly to 3.0.
