### ISSUE TITLE
Allow deferred JSON-decoding of unknown google.protobuf.Any messages

### ISSUE THREAD

**Issue by creachadair** [protocolbuffers/protobuf#5226]
## Abstract

When a JSON object representing a proto3 message is decoded, the generated API for many (most?) languages yields an error when decoding a JSON-encoded `google.protobuf.Any` field whose generated code is not linked in to the program doing the decoding. This is problematic, because an unexpected type for an `Any` field breaks forward-compatibility in JSON encoding, even though it is fine in wire encoding. I propose herewith a modest extension to the rules for decoding `google.protobuf.Any`, that could allow generated code to defer JSON decoding of unknown extensions.

## Background

The `value` field of the `google.protobuf.Any` encodes the wire format of the message. For the JSON decoder, this means the message schema specified by the `type_url` field _must_ be available to decode the JSON value. Most (maybe all) existing per-language JSON decoders will fail with an error if the indicated message schema is not linked. This makes it difficult to use `Any` messages as an extension point with JSON encoding: If a message arrives with a hitherto-unknown `Any` URL attached anywhere, the decoder fails and the message is unusable.

## Proposal

To address the issue described above, I propose that a JSON decoder be allowed to _defer_ decoding of unknown message fields, in the following wise: 

1. Introduce a new well-known message type, `google.protobuf.RawAny` (name for discussion purposes) with the following structure:
    ```
    message RawAny {
       string type_url = 1;  // the type URL of the un-decoded JSON.
       string json = 2;      // the raw JSON (encoded as required, UTF-8).
    }
    ```

2. When a JSON decoder encounters the encoding of a `google.protobuf.Any` message whose structure is unknown, it MAY populate the corresponding field with a `google.protobuf.Any` with the wire-encoding of a `google.protobuf.RawAny` message carrying the un-decoded JSON.

For example, suppose the decoder receives a JSON-encoded `Any` value like:
```
{"@type":"type.googleapis.com/some.unknown.Message","x":"value","y":23}
```
This would be encoded as the following `RawAny` message:
```
type_url: "type.googleapis.com/some.unknown.Message"
json: "{\"@type\":\"type.googleapis.com/some.unknown.Message\",\"x\":\"value\",\"y\":23}"
```
which in turn becomes an `Any` message similar to:
```
type_url: "type.googleapis.com/google.protobuf.RawAny"
value: "\x28\x0a\x79\x74\x65\x70\x67\x2e\x6f\x6f\x6c\x67\x61\x65\x69\x70\x2e\x73\x6f\x63\x2f\x6d\x6f\x73\x65\x6d\x75\x2e\x6b\x6e\x6f\x6e\x6e\x77\x4d\x2e\x73\x65\x61\x73\x65\x67\x47\x12\x22\x7b\x74\x40\x70\x79\x22\x65\x22\x3a\x79\x74\x65\x70\x67\x2e\x6f\x6f\x6c\x67\x61\x65\x69\x70\x2e\x73\x6f\x63\x2f\x6d\x6f\x73\x65\x6d\x75\x2e\x6b\x6e\x6f\x6e\x6e\x77\x4d\x2e\x73\x65\x61\x73\x65\x67\x2c\x22\x78\x22\x3a\x22\x76\x22\x6c\x61\x65\x75\x2c\x22\x79\x22\x3a\x22\x33\x32\x00\x7d"
```
where the `value` is the wire encoding of the `RawAny` message.

## Discussion

* Deferred decoding does not eliminate the need for the message schema: It will still be needed to re-encode the message to wire format, for example.

* This proposal aims for minimality: It does not require changes to `protoc`. It requires one small new well-known message type (the one described as `google.protobuf.RawAny` above), and some documentation about its intended use for language-API authors.

* Per-language JSON decoding libraries could be updated incrementally: Existing decoders will continue to work as they do now, producing an error for unlinked messages.
  - If the new behaviour is added unconditionally, the only user-visible change is that some decodings that previously failed will now succeed.
  - If the new behaviour is added optionally (default off), there should be no user-visible changes until the caller explicitly requests the new behaviour.

**Context:** This request arose from https://github.com/golang/protobuf/issues/723. It affects the Kythe project, which makes use of JSON-encoded proto messages in multiple contexts where `Any` extensions are needed.

**Comment by TeBoring** [comment]
What language are you using? In many languages, we support ignore unknown option in many languages.

**Comment by TeBoring** [comment]
Or are you talking about type url cannot be resolved?

**Comment by creachadair** [comment]
> [W]e support ignore unknown option in many languages.
> Or are you talking about type url cannot be resolved?

I'm referring specifically to instances of the `google.protobuf.Any` message whose type URL cannot be resolved. "Ordinary" unknown fields (e.g., fields with unknown field numbers) seem to work fine in the languages I've tried.

**Comment by TeBoring** [comment]
Is json a requirement in your case? Can you use binary format?

**Comment by TeBoring** [comment]
And if we simply drop the un-parsable Any wrapped value, does it work for
your case?

**Comment by creachadair** [comment]
> Is json a requirement in your case? Can you use binary format?

Yes, JSON is a requirement for us. We get input from tools with poor or absent protobuf support, running in environments where taking a dependency on our proto definitions (or indeed protobuf at all) often isn't desirable or practical. We use protobuf ourselves to define the wrapper, but clients don't necessarily use protobuf.

> [I]f we simply drop the un-parsable Any wrapped value, does it work for your case?

In some instances we could probably reuse the original JSON (pre-decoding), but in others the environment will need to make changes and re-encode (to JSON). That was the motivation for allowing the decoder to preserve the un-decoded field in the above proposal.

Perhaps it will help for me to give more context:

Basically the problem we have is that we have some "generic" plumbing tools that consume JSON-encoded messages from a variety of sources, and dispatch them to other tools. The wrapper messages carry metadata in `Any` extensions. The dispatcher doesn't need to decode the metadata, but does need to pass it along to other tools need them preserved.  (Some tools require protobuf, others operate directly on the JSON; that's an implementation detail for our clients).

Right now anytime anyone adds a new metadata type, we wind up having to build and release new versions of the plumbing. That complicates updates quite a bit.  We use protobuf internally in our indexing infrastructure, so I'm hoping for a solution that allows us to continue doing so. This proposal was motivated by symmetry with field-preservation in the wire-decoding case: Ideally `json-encode(modify(json-decode(X)))` would preserve unknown `Any` values as `wire-encode(modify(wire-decode(X)))` does for unknown field indices.

I hope that helps clarify things, but please let me know if not.

**Comment by TeBoring** [comment]
1) Is it possible, in the API you provided, to add a way to let client register the proto type to be wrapped in Any? (e.g., another service to register type , the API also takes the wrapped type as a parameter). In this way, your service always knows the type of wrapped message.
2) We have struct.proto to dynamically create generic json object: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto

**Comment by creachadair** [comment]
Re (1): That would be tricky. Inputs often come from an offline process, not necessarily live RPCs. The dispatcher decodes the message in order to discover which analyzer should receive it—so if the analyzer has to advertise its message formats in advance, we're basically in the situation we have now, where we have to re-bake the dispatching-driver for each new message type that exists.

Re (2): We could replace the typed messages with untyped structs. That loses much of the benefit of using protobuf in the first place, though, which was to have static message types in the code that needs them (e.g., the analyzers). It's fine for our purposes to require an _analyzer_ to bake in the message types it cares about; what we're trying to avoid is having to revise the intermediate plumbing (e.g., dispatching driver, storage libraries, etc.). Switching to structs would help the plumbing, but would hurt the analyzers.

**Comment by TeBoring** [comment]
Your client can work on normal message which has the type checking. The json encoding of the normal message can be parsed as Struct.

**Comment by TeBoring** [comment]
```Struct``` is one option. You may also use string field.
For ```Struct``` to ```M```, m.parseFromJson(s.serializeToJson()).
Does that work?

**Comment by creachadair** [comment]
> For Struct to M, m.parseFromJson(s.serializeToJson()).
> Does that work?

Functionally it looks like it should work, but I would describe that as a workaround rather than a solution. To use this, we would have not only to migrate all our existing protos from `Any` to `Struct` but we would also have to (manually) update all the current users of the message to include this decode logic, for each message type they support. As I said above: This makes things better for our plumbing, but worse for our analyzers. That's a poor trade, since the analyzers are often contributed/supported by third parties.

Much of the benefit we get from using protobuf is that the schema defines the layout, and the decoder "just works", whether for wire-format or JSON, and gracefully adapts to forward-compatible changes in the message format. In principle, a new `Any` message _should_ be forward-compatible. Rather than work around the fact that it's currently not for JSON, I think it would be better to provide a deferral mechanism.

It's worth noting that the proposal above also extends to other encoding schemes like textpb, and although our project doesn't rely on textpb, I'm aware of others that do. Having a standard way to express deferred parsing would have very little down-side I can see.

**Comment by TeBoring** [comment]
The purpose of ```Any``` is to replace extension in proto2. For extension, you do need to link every related message in order to make it work. I think same requirement for Any seems reasonable. In order to make Any work, you have to link the related messages.

I also feel type checking is also part of the semantic of Any. Any is used for polymorphism for known types not for any random type. And because the type checking is part of the semantic of Any, if a server sends an undeclared Any to client (like in your case), that is considered as a security attack vector. For clients that assumes the type checking semantic of Any, that would be unacceptable.

**Comment by TeBoring** [comment]
The other approach I can think of is to provide a way to let client tell sever the type of wrapped message.

**Comment by creachadair** [comment]
> I also feel type checking is also part of the semantic of Any. Any is used for polymorphism for known types not for any random type.

Agreed—but the situation I'm describing isn't one where we want to _discard_ type-checking, only defer it. The end-consumer of the message still has to know the type, and that's appropriate.  The goal is not to allow arbitrary messages, but to allow the channel to inspect known parts of the message structure without forcing a full decode of the unknown parts. This works for wire-format, but not for JSON. Given that the cost to protobuf itself is small (i.e., no functional changes are required to the compiler), I'm not clear on the objection.

**Comment by creachadair** [comment]
> The other approach I can think of is to provide a way to let client tell sever the type of wrapped message.

That doesn't work for our case, because we don't know which client we're talking to until _after_ we've inspected the wrapper message. The dispatcher examines the message, figures out which analyzer to invoke, and does so (note too that this isn't necessarily "client-server" interaction in the Stubby/gRPC sense—in some cases these are pipes or stored files).

**Comment by TeBoring** [comment]
"Defer" may mean never. If we allow some decoder to defer parsing unknown Any, how can we guarantee the type checking will be done in the end?

**Comment by creachadair** [comment]
> "Defer" may mean never. If we allow some decoder to defer parsing unknown Any, how can we guarantee the type checking will be done in the end?

The same question applies to unknown fields: Nothing can guarantee that type-checking will be done. Similarly, nothing can guaranteed that for `Any` messages in wire format: The reader can always grab the bytes and do whatever. 

For our case, as in the case you're describing, either (a) we won't use the field at all, or (b) it will be decoded with the proper descriptor.  The question of whether the message is decoded and used is outside the scope of the protobuf language's concern: The language doesn't define how wire-types are mapped to language types, for example. 

This proposal doesn't, as far as I can see, contradict any of the protobuf language goals: A decoder with the descriptor in-harness will still decode the message structure correctly. A decoder without the descriptor in-harness will treat it as an unknown-but-preserved field. Either way, a program in possession of the raw message format _could_ choose to decode and use it some other way—this doesn't make that any easier (or harder).

**Comment by TeBoring** [comment]
Actually, for json unknown fields, the default behavior is fail and the optional behavior is discard. So the json Any behavior still seems consistent to me.

**Comment by creachadair** [comment]
> Actually, for json unknown fields, the default behavior is fail and the optional behavior is discard.

Indeed, that is the default, but as the spec says: “Proto3 JSON parser should reject unknown fields by default but may provide an option to ignore unknown fields in parsing.” That option is available for _unknown_ fields, but not (currently) for `Any`. This proposal is one way to allow such an option to exist for `Any`.

Certainly some different proposal could also work: @shahms suggested an alternative above, which I think would also be fine. Even if the default behaviour remains as it is now, I think there should be a standard way for decoders to implement deferred decoding.

**Comment by TeBoring** [comment]
The ignoring unknown for json unknown field actually means discard in our implementations, which is not what you want.

**Comment by TeBoring** [comment]
For the above Struct solution, could you only update the component which handles the Any parsing to use Struct.

**Comment by creachadair** [comment]
I feel that I am perhaps missing some aspect of your disagreement with this proposal. You've proposed several work-arounds that are functionally actionable but do not address the fundamental issue, viz., that we'd like to use the standard protobuf machinery where it's available, and interoperate cleanly with the JSON encoding rules. I do not disagree that we can hack around the problem, but would like to find a solution that doesn't require hacking. 

Leaving aside the workarounds, is there any particular concern you have about the proposal itself?

**Comment by TeBoring** [comment]
For your proposal, 
1) How do I know the format of the value string? is it json or binary?
2) How do I know RawAny is from the client or from some proxy that modifies Any payload?
3) In the end, do you need to covert the json data to binary data?

**Comment by TeBoring** [comment]
2) Suppose there are three components: producer, proxy and consumer. If the consumer get data with RawAny, how does consumer decide it should decode it as RawAny or wrapped message?
4) Could you be more specific about to which path you want to apply your proposal? json-json, binary-json, binary-binary, json-binary?

**Comment by creachadair** [comment]
Re: Proxy vs. producer. The consumer has no way to know, but that's no more or less the case here than with a wire-format message: A proxy _could_ decode a wire-format message and modify the `Any` fields either way. For our use-case this isn't relevant, though: We don't want to _modify_ the contents of unknown `Any` fields, only to preserve them across `encodeJSON(update(decodeJSON(input)))` where `update` may modify the contents of _known_ fields and extensions but will ignore the unknown ones.

Re: Decoding paths. We would like to support a couple of different usage patterns for a given JSON `input` value:

1. On the proxy, the workflow is approximately as follows:
   ```
    let m = decodeJSON(input) in
      let analyze = dispatch(m) in 
         analyze(encodeJSON(update(m)))
   ```
   that is, the proxy decodes JSON, inspects some of its fields to find the analyzer to dispatch to, possibly modifies some of the decoded fields (not the unknowns), then re-encodes the (possibly-modified) message as JSON in a request to the analyzer.

2. An analyzer receives `input` and may either use the raw JSON directly, or may decode it into a generated protobuf type. The latter is preferred where possible. We expect most analyzers to do something like `let m = decodeJSON(input) in analyze(m)`.

Of these, (1) is the focus of this proposal: The analyzer is expected to know the descriptors for the inputs it knows how to handle. The proxy/dispatcher needs only to preserve them.

**Comment by TeBoring** [comment]
> Yes, the consumer does need to know. But the proxy does not.

Then, from the data that proxy produces, there is no information about whether it's actual RawAny or an unknown Any converted to RawAny. How does the consumer figure out?

> However, we'd rather not have to maintain that synchronization.

Can proxy parser the whole json input as Struct? Then there is no need for such sync.

> The wrapper message carries analyzer-specific metadata in Any instances. The producer and the analyzer share knowledge of the Any values, but we want the proxy not to have to. As I mentioned above, the need to do so greatly complicates updates and rollouts to our pipeline plumbing.

Why the analyzer-specific metadata cannot be generalized so that the proxy can also understand it?

**Comment by creachadair** [comment]
> [F]rom the data that proxy produces, there is no information about whether it's actual RawAny or an unknown Any converted to RawAny. How does the consumer figure out?

Why would the consumer care? The consumer doesn't receive a RawAny message in the scenario I've described: The proxy decodes JSON to get a message with some RawAny field values. Encoding that message back to JSON (perhaps with alterations of the known fields) should restore the same JSON that was originally received. No information is lost in this proposal, because the original type URL is preserved.

Our programs don't have a dynamic lookup mechanism (we don't have the internal protodb in our open-source project), but a program that does could decode a RawAny by extracting the type URL, fetching the descriptor, and using that descriptor to decode the saved JSON. That aspect of my proposal is intended to allow that workflow without breaking compatibility: Existing decoders without the schema already can't decode those messages and return an error eagerly. Under the proposed option, the decoder would still get an error if it tries to decode the RawAny explicitly, sans descriptor.

> Can proxy parser the whole json input as Struct? Then there is no need for such sync.

It can, but again that loses us the type structure: The proxy doesn't need to know the contents of the Any fields, but _does_ care about the contents of other fields.

> Why the analyzer-specific metadata cannot be generalized so that the proxy can also understand it?

There is no generic metadata format: Each analyzer (potentially) has its own idiosyncratic message type. We could, of course, just convert it to a bag of key/value pairs, i.e., a `Struct` message, but then we lose the format- and type-checks enforced by the decoder.

**Comment by creachadair** [comment]
Revisiting one of your previous points:
> [F]rom the data that proxy produces, there is no information about whether it's actual RawAny or an unknown Any converted to RawAny. How does the consumer figure out?

The intent of the above proposal is that RawAny messages be handled as a well-known type by the encoder and decoder logic. The rules for introducing and eliminating them would be, more or less:

* **Introduction:** When the JSON decoder attempts to decode a JSON object into an `Any` field whose type URL is unresolved, it produces a `RawAny` message instead.
  - Today it cannot do this, because the Any message requires wire-format, and the JSON decoder can't produce wire format without a descriptor.
  - No type information is discarded, so type-checking is still possible for every field, as before.
* **Elimination:** Given an `Any` field carrying a `RawAny` message:
  - If encoding as JSON, the encoder uses the saved JSON value directly.
  - If encoding as wire-format:
    * If the type URL for the saved `RawAny` message is unknown, an error is returned (this is the deferral).
    * Otherwise, the descriptor is used to convert the message to wire format.

Any `RawAny` value can also be explicitly decoded whenever its type descriptor is available, by unpacking the JSON and decoding it in the usual fashion. The only real change is that the error for an _unresolved_ descriptor is delayed until the caller explicitly requests it.

**Comment by zrlk** [comment]
https://github.com/kythe/kythe/pull/3293 updates a tool to process JSON-encoded
proto data. This data contains Any messages that may in turn wrap protos
of unconstrained type. The tool does not need to decode these messages, *but*
it should be able to round-trip them. One possible way this might go is
JSON-encoded Any -> a protobuf Any message with the JSON data base64'd ->
JSON-encoded Any, but the important thing is that the data doesn't get lost.

Despite the tool not needing to decode the Any-encoded data, I still had to
add two dummy protos (https://github.com/kythe/kythe/blob/2be0c1f0d1519d24903572b32c42de593eb80449/kythe/cxx/tools/kindex_tool_main.cc#L237)
to make sure that their types would be linked in. This isn't actually a complete
solution, since we may add other Any-encoded messages in the future, at which
point the tool will break.

We need a way to be able to treat Any messages as opaque when serializing or
deserializing JSON-encoded protos.

**Comment by zrlk** [comment]
Looks like #4511 is related.

**Comment by i9** [comment]
/shameless plug
https://github.com/i9/bar BetterAnyResolver
minimal code to support unknown Any marshal/unmarshal
