### ISSUE TITLE
[Ruby] latest `well_known_types.rb` is not included in the Gem

### ISSUE THREAD

**Issue by yasyf** [protocolbuffers/protobuf#5239]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

macOS 10.13.6

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 2.5.1

**What did you do?**

We are still seeing the error that was solved in #3847. Upon inspecting the file `lib/google/protobuf/well_known_types.rb`, it looks like this file, packaged in the gem, does not have over a year's worth of changes that are shown on GitHub, despite there being multiple releases since then, and the fact that we are on the latest release. We could use `master` here but the bug remains: this file seems to be not updated with gem releases.

I've included a copy of the file from gem version 3.6.1 [here](https://gist.github.com/yasyf/8b916a68edceef3779d5901075167f44).

We are seeing this on our production linux box as well.

**Comment by TeBoring** [comment]
Actually, there is only one commit missed: https://github.com/protocolbuffers/protobuf/commit/8695997eb5adb3c504c3615f0e6f3891a9b7ebde#diff-76a04fa397e158ffdf87c6f0f1cf366d

We will include that in our next release.

**Comment by TeBoring** [comment]
ok, I found out the PR was actually merged after we created 3.6.x branch: https://github.com/protocolbuffers/protobuf/pull/3847
That's why it was not included in 3.6.1 release.

That change will be available in 3.7 release.
