### ISSUE TITLE
google.protobuf.json_format.ParseDict modifies input JSON

### ISSUE THREAD

**Issue by giokara** [protocolbuffers/protobuf#5243]
**What version of protobuf and what language are you using?**
Version: v3.5.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux (Alpine, Ubuntu, etc.)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.5

**What did you do?**
1. Define a protobuf message, e.g.:

```
syntax = "proto3";

package tutorial;

message Person {
  string name = 1;
  int32 id = 2;
  string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;
}

message AddressBook {
  repeated Person people = 1;
}
```

2. Prepare a JSON that adheres to one of the defined messages, e.g.:

```
{
  "name": "John Doe",
  "id": 1234,
  "email": "jdoe@example.com",
  "phones": [
    {
      "number": "555-4321",
      "type": "HOME"
    }
  ],
  "@type": "type.googleapis.com/tutorial.Person"
}
```

3. Use the `google.protobuf.json_format.ParseDict` twice on the same JSON. This could happen when the JSON dict is part of a class and is parsed in differents parts of the code. e.g.:

```
from google.protobuf import any_pb2
import google.protobuf.json_format as json_format
import addressbook_pb2

my_dict = {
  "name": "John Doe",
  "id": 1234,
  "email": "jdoe@example.com",
  "phones": [
    {
      "number": "555-4321",
      "type": "HOME"
    }
  ],
  "@type": "type.googleapis.com/tutorial.Person"
}

my_message = json_format.ParseDict(my_dict, any_pb2.Any())
my_message = json_format.ParseDict(my_dict, any_pb2.Any())
```

4. Second `ParseDict` call fails with `google.protobuf.json_format.ParseError: @type is missing when parsing any message.`

**What did you expect to see**
The second `ParseDict` call should exit successfully.

**What did you see instead?**
Second `ParseDict` call fails with `google.protobuf.json_format.ParseError: @type is missing when parsing any message.`

**Analysis**
After looking into the code, the issue seems to come from this line:
https://github.com/google/proto-quic/blob/1694fa55a19d7e03103f65d69360bd7ff05389c8/src/third_party/protobuf/python/google/protobuf/json_format.py#L527
The delete of the `value[@type]` should be undone after the call to the `_ConvertFieldValuePair` function.

**Comment by anandolee** [comment]
Thanks for reporting it. Are you happy to create a PR and send me for review?
