### ISSUE TITLE
Is there a way to include a manifest file when generating a jar using protoc?

### ISSUE THREAD

**Issue by vivekragunathan** [protocolbuffers/protobuf#5253]
```
protoc --java_out="my.jar" *.proto
```

Is there a way to specify a manifest file like in the `jar` command?

```
jar cfm "my.jar" "manifest.txt" "src/java"
```

**Comment by elharo** [comment]
Does the Maven protoc plugin enable something like this?

**Comment by googleberg** [comment]
We are not planning to add the ability to specify a manifest.txt file to be included.
