### ISSUE TITLE
implement Merge_from_string in google.protobuf.message in python

### ISSUE THREAD

**Issue by thangvip4321** [protocolbuffers/protobuf#5255]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anandolee** [comment]
There is MergeFromString() in google.protobuf.message:
https://github.com/protocolbuffers/protobuf/blob/f50a1f843e8c2599a92e9d6bd5324462a5233367/python/google/protobuf/message.py#L148
