### ISSUE TITLE
Use a builded dll on Windows MSVC2015 on protobuf 3.6.1

### ISSUE THREAD

**Issue by antenuccialessio** [protocolbuffers/protobuf#5258]
Hi, I have a project that include some generated protoc messages on c++ MSVC2015. I want to build a dll library and use it in another project.
I am on Qt  framework.
1) I generate the c++ code with the command:
 protoc --cpp_out=dllexport_decl=Q_DECL_EXPORT:. .\my_message.proto

2) Inside my project I define the MACROS:
#define PROTOBUF_USE_DLLS
#define LIBPROTOBUF_EXPORT

visible also form my_message.pb.h (I added it into the header file)

3) I compile it succesfully and I generate the file:   my_library.dll

4) I have an application, that use my_library.dll but I get this error:
first error) LINK2019: unresolved external symbol "class MyMessageDefaultTypeInternal_MyMessage_default_instance_"...
second error) LINK2019: unresolved external symbol "const MyMessage::'vftable'".....

I read many forum about it, but I can't find a solution. Can you help me please ? Thanks

Ale

**Comment by micw523** [comment]
I think for VS linker to work with a DLL you might want to compile your protobuf code into a .lib file so that the linker knows?
