### ISSUE TITLE
Error including pb.h headers in a MSVC CLR project

### ISSUE THREAD

**Issue by aaron-bray** [protocolbuffers/protobuf#5259]
Version: v3.6.0.rc1
Language: C++ integrated into a managed C++ CLR project
Using Visual Studio 2017

I have a C++ library using protobufs.
I have enums defined in proto files and use them in my C++ interface
(Say Enums.proto)

I am wrapping my C++ library in a CLR project for access by C#
The CLR based cpp file will need include the Enums.pb.h to use C++ interfaces with enums

The generated Enums.ph.h includes the stubs/common.h

which has this include block:
// TODO(liujisi): Remove the following includes after the include clean-up.
#include <google/protobuf/stubs/logging.h>
#include <google/protobuf/stubs/mutex.h>
#include <google/protobuf/stubs/callback.h>

And stubs/mutex.h includes std [mutex](https://github.com/protocolbuffers/protobuf/blob/v3.6.0rc1/src/google/protobuf/stubs/mutex.h#L33) (as of 3.6.0.rc1) which is not allowed to be included when building a CLR project.

Error received:

fatal error C1189: #error:  mutex is not supported when compiling with /clr or /clr:pure.

Maybe the include clean-up will fix this if stubs/mutex is not part of common.h
(also once.h includes mutex too)

Maybe a pimpl pattern could be used in WrappedMutex so it does not include std mutex (?)

**Comment by acozzette** [comment]
I just sent out #5260 which should help by removing those includes from stubs/common.h. But are you saying that stubs/once.h is also a problem? We have heard some complaints that `std::once` is not very portable, so we may end up needing to rethink that "once" initialization functionality anyway.

**Comment by aaron-bray** [comment]
Yes stubs/once.h also [includes mutex](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/once.h#L81)
 to gain access to std::call_once, to get CLR compatibility, we would need to move those inline functions using std::call_once out of the header

There are still other headers that include stubs/mutex.h (such as descriptor.h)
and stubs/mutex.h still includes the std mutex header.
For CLR compatibility, we would need to take the std mutex include out of stubs/mutex.h 

Those 2 files are the only ones I see including the std mutex header

I will see if I can possibly remove that include from those files and see how things act

On a side note...
 
Your branch has a few oddities I am working out.
For some reason one of my enums in one of my pb.h files is throwing this error when one of my regular cpp files includes it.
(All my other enums are working fine, so I suppose some generated header chain is broken?)

`
 error C2589: '(': illegal token on right side of '::'
 error C2062: type 'unknown-type' unexpected
 error C3805: 'type': unexpected token, expected either '}' or a ','
 warning C4003: not enough arguments for function-like macro invocation 'max'
`

due to this code

`
enum eHeartRhythm {
  NormalSinus = 0,
  Asystole = 1,
  eHeartRhythm_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  eHeartRhythm_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
`

**Comment by aaron-bray** [comment]
Here is what I was talking about in making the WrappedMutex use a pimpl pattern so we can remove the std::mutex include in stubs/mutex.h, it works well!

I did this change on master, but the errors I mentioned before happens a lot, so I assume master is not ready for prime time yet. So I created a new branch based on 3.6.x and that works great with my project.

https://github.com/aaron-bray/protobuf/commits/3.6.x-mutex
(Note, I also am trying to remove once.h from where I can)
once.h is pretty embedded in descriptor.h and extension_set.h
I will try to implement the pimpl patter in descriptor classes to see if that helps.
extension_set has an extern'd variable I am not sure what to do with yet...

**Comment by acozzette** [comment]
@aaron-bray I think in some environments `min` and `max` can be defined as macros--maybe that could explain the errors you saw?

Before getting too far into this, I should mention that we will probably not be able to officially support CLR. We can accept pull requests for it, but if we manage to remove `std::mutex` from the necessary headers, there's no guarantee that it won't slip back into those headers over time, so it might require some ongoing fixes if you want to keep it working.

**Comment by aaron-bray** [comment]
You are right.
I probably need to look into encapsulating the protobuf enum classes for a cleaner interface
They are so convenient to just use as generated though!

The min/max errors I am seeing is also probably an include order/collision for particular file. 
More reason to fully and cleanly encapsulate generated classes
