### ISSUE TITLE
wheel for python3.7

### ISSUE THREAD

**Issue by davidszotten** [protocolbuffers/protobuf#5266]
Hi,

would it be possible to publish a python wheel for python 3.7 (at least for the currently most recent version of protobuf)? thanks!

**Comment by nmishra** [comment]
This will be really helpful.

**Comment by alanpurple** [comment]
protocol buffer doesn't support python 3.7, that's the only reason tensorflow aren't moving to python 3.7 and so I can't move to python 3.7

**Comment by alanpurple** [comment]
protocol buffer doesn't support python 3.7, that's the only reason tensorflow aren't moving to python 3.7 and so I can't move to python 3.7

**Comment by alanpurple** [comment]
protocol buffer doesn't support python 3.7, that's the only reason tensorflow aren't moving to python 3.7 and so I can't move to python 3.7

**Comment by TeBoring** [comment]
Could you use our source distribution for now?

**Comment by davidszotten** [comment]
i'm having issues getting the `cpp_implementation` built with the source distribution. is there anything i can do to help with getting 3.7 wheels on pypi?

**Comment by TeBoring** [comment]
@alanpurple, tensorflow perhaps depends on our c++ header in their code. Simply releasing wheel may not solve the problem. You probably need to wait for our next release.

**Comment by TeBoring** [comment]
@alanpurple, are you referring to https://github.com/tensorflow/tensorflow/issues/21441?
For that issue, I don't known why building tensorflow depends on building our source file?
Besides, the error of protobuf in https://github.com/tensorflow/tensorflow/issues/21441 should be easily turn off by ```-Wno-incompatible-pointer-types```

**Comment by TeBoring** [comment]
https://pypi.org/project/protobuf/#files

**Comment by alanpurple** [comment]
@TeBoring 

Thank you for that new whl file!! I'll test again

**Comment by alanpurple** [comment]
@TeBoring 
`
protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 1)
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc: In function âbool google::protobuf::python::descriptor::_GetItemByKey(google::protobuf::python::PyContainer*, PyObject*, const void**)â:
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:69:45: error: invalid conversion from âconst char*â to âchar*â [-fpermissive]
        ((*(charpp) = PyUnicode_AsUTF8AndSize(ob, (sizep))) == NULL? -1: 0): \
                                             ^
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:172:13: note: in expansion of macro âPyString_AsStringAndSizeâ
         if (PyString_AsStringAndSize(key, &name, &name_size) < 0) {
             ^
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:69:45: error: invalid conversion from âconst char*â to âchar*â [-fpermissive]
        ((*(charpp) = PyUnicode_AsUTF8AndSize(ob, (sizep))) == NULL? -1: 0): \
                                             ^
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:189:13: note: in expansion of macro âPyString_AsStringAndSizeâ
         if (PyString_AsStringAndSize(key, &camelcase_name, &name_size) < 0) {
             ^
At global scope:
cc1plus: warning: unrecognized command line option â-Wno-writable-stringsâ
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

**Comment by TeBoring** [comment]
Are u sure you are using the wheel package? Our wheel is binary package.
It’s strange you need to compile it.

**Comment by alanpurple** [comment]
@TeBoring 

my bad, what i meant was compiling tensorflow after install new protobuf wheel

**Comment by TeBoring** [comment]
Then you should figure out why building tensorflow needs building our
source code. It’s a unrelated to this issue.
