### ISSUE TITLE
google.protobuf not found when installed with pip --prefix='.'

### ISSUE THREAD

**Issue by karthikeyann** [protocolbuffers/protobuf#5269]
Version: v3.5.1 
Language: Python
Linux: CentOS
Python 2.7.14 :: Anaconda, Inc.

1. pip install protobuf --upgrade --prefix='./' -I 
2. setenv PYTHONPATH`` `pwd`/lib/python2.7/site-packages/``
3. python
4. from google.protobuf import descriptor as _descriptor

I am seeing
```
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor as _descriptor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named google.protobuf
```

**Comment by lxkarthi** [comment]
Found a fix.  Creating empty file in google directory makes it work. (solution given in [issues/6341](https://github.com/tensorflow/tensorflow/issues/6341#issuecomment-377804376))
```touch lib/python2.7/site-packages/google/__init__.py```

Note that, when installing using `pip --user`, this issue does not arise. 
Can this be fixed while installing protobuf itself with `pip --prefix=` option?

**Comment by Flamefire** [comment]
This is an issue with Python < 3.3. Placing the init file in the google folder will make all other google packages installed somewhere else unusable: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-init-py-trap

Solution: Do not place the init file there. Switch to Python >= 3.3 (2.7 will drop out of support by the end of the year)

**Comment by ThoenigAdrian** [comment]
My request to the maintainers: 

Could you add the ```__init__.py``` file to the python2 package ?  This would mean both versions would work.

**OR**

If don't want to support python2 anymore:

Don't upload the python2 versions to pypi anymore and delete the old ones with this ```ImportError``` issue ? Because then pip would automatically get the latest version which is still working for python2.


Both of this options would be better(imo) than the current situation:  providing a broken python2 package.

**Comment by Flamefire** [comment]
> Could you add the __init__.py file to the python2 package ? This would mean both versions would work.

As I wrote in https://github.com/protocolbuffers/protobuf/issues/5269#issuecomment-546242515 make sure to NOT add that for Python 3.3 and up. I guess this can be easily achieved via the setup call.

**Comment by zhangskz** [comment]
I believe we don't support python 2 anymore, closing as obsolete.
