### ISSUE TITLE
--ccp_out flag does not properly handle --proto_path=../

### ISSUE THREAD

**Issue by kingjeffrey** [protocolbuffers/protobuf#5271]
Version: 3.6.0
Language: C++
OS: Mac 10.14
Runtime: gcc 4.2.1

**Steps to reproduce the behavior:**

run `protoc --proto_path=../ --cpp_out=cpp/ foo/bar.proto`

**What did you expect to see**

I expected to see the compiled code stored to:

- `foo/cpp/bar.pb.cc`
- `foo/cpp/bar.pb.h`

**What did you see instead?**

The compiled code is saved to:

- `foo/cpp/foo/bar.pb.cc`
- `foo/cpp/foo/bar.pb.h`

**Anything else we should know about your project / environment**

This seems to occur in some, but not all language out flags. A small sampling, `--php_out` behaves as expected. `--python_out` and `--go_out` behave unexpectedly (like `--cpp_out`).

**Comment by acozzette** [comment]
I think this is working as intended, though it may initially seem surprising. The idea is that if the path to your proto file is `foo/bar.proto`, then you should be able to include `"foo/bar.pb.h"` to access the header. There is supposed to be a simple correlation between .proto file paths and the generated file paths.
