### ISSUE TITLE
Looking for a way to overcome python `isinstance` discrepancy in message fields copy

### ISSUE THREAD

**Issue by pdonorio** [protocolbuffers/protobuf#5272]
Hello there,
I'm working with a Python gRPC client for the `RChain` blockchain.

Trying to update my client to latest specs I've been encountering a tricky problem.
As from their Proto message definition [here](http://j.mp/2ysXPNv), I need to define a `DataAtNameQuery` to call `listenForDataAtName`.

After generating the protobuf base, I've found out that it's currently impossible to define a `Par` for the name of `DataAtNameQuery`, because:

```python
In [1]: from rchain_grpc.generated.CasperMessage_pb2 import DataAtNameQuery
   ...: x = DataAtNameQuery()
   ...: x.name.__class__
Out[1]: RhoTypes_pb2.Par

In [2]: from rchain_grpc.generated.RhoTypes_pb2 import Par
   ...: print(Par, x.name.__class__)
   ...: print(Par.__name__, x.name.__class__.__name__)
<class 'RhoTypes_pb2.Par'> <class 'RhoTypes_pb2.Par'>
Par Par

In [3]: isinstance(Par(), x.name.__class__)
Out[3]: False
```

So Python fails on considering the `Par` class for the name as the same one I can import.
This seems due to a "different layout" 🤔 even thought that's kinda the first time I see something like that.

```python
In [4]: x.name.__class__ = Par
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7ea34be87679> in <module>
----> 1 x.name.__class__ = Par

TypeError: __class__ assignment: 'Par' object layout differs from 'Par'
```

Now this difference breaks the current code in:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L1316

And I get to see:
```
TypeError: Parameter to MergeFrom() must be instance of same class: expected Par got Par. for field DataAtNameQuery.name
```

Can you give some guidance / suggestions on how should I proceed?

Regards,
Paolo

**Comment by pdonorio** [comment]
Someone suggested me today that `ids` are not the same and indeed:
```python
In [4]: id(Par)
Out[4]: 93855718334552

In [5]: id(x.name.__class__)
Out[5]: 93855717482088
```

I can't say for sure why that is possible. 
But for what I can understand the way the `Par` class is obtained for the `name` parameter at `__init__` time when creating an instance of `DataAtNameQuery` is making this happening.

Hope to get some feedback, thanks a lot

**Comment by anandolee** [comment]
How do you use MergeFrom() and get the Error?

**Comment by pdonorio** [comment]
Sorry for not writing it before, but here are the detailed steps to reproduce the issue.

```bash
# prepare the docker container
git clone https://github.com/proof-media/rchain-grpc.git
cd rchain-grpc
git checkout update/rnode-0.7
docker-compose run --rm --entrypoint /bin/bash tests
python setup.py develop \
  && pip install -r requirements_dev.txt \
  && pip install ipython && ipython

# now you have an ipython shell all set-up
```

```python
# run the code that breaks
from rchain_grpc.generated.RhoTypes_pb2 import Par, Expr
from rchain_grpc.generated.CasperMessage_pb2 import DataAtNameQuery

par = Par()
par.exprs.extend([Expr(g_string='myname')])
channel = DataAtNameQuery(depth=1, name=par)

[...]
/usr/local/lib/python3.7/site-packages/protobuf-3.6.1-py3.7.egg/google/protobuf/internal/python_message.py in MergeFrom(self, msg)
   1228       raise TypeError(
   1229           "Parameter to MergeFrom() must be instance of same class: "
-> 1230           'expected %s got %s.' % (cls.__name__, msg.__class__.__name__))
   1231
   1232     assert msg is not self

TypeError: Parameter to MergeFrom() must be instance of same class: expected Par got Par. for field DataAtNameQuery.name
```

**Comment by pdonorio** [comment]
Bump, sorry for bothering, would you help me find out here? 
It is blocking a release of our python library.

Can I provide more info or do something else?

**Comment by anandolee** [comment]
Sorry. I'd like to help but this reproduce steps involves too much other libraries. Still can't see how the MergeFrom() is used directly. We do not have time to dig into other libraries. Are you able try to isolate this issue to a protobuf only question?

**Comment by pdonorio** [comment]
Ok, I'll try to get to the heart of it and isolate, 
thanks for the prompt reply.

**Comment by pdonorio** [comment]
After many (many) tries and sometimes not getting the error I've found out that if the 
culprit is `python setup.py develop`. I can't understand exactly the differences but using `pip install -e .` instead, it works with no error. 
Pip freeze in the two cases shows same packages version.

I've read this thread about setup.py vs pip
https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop
but not clear still.

Since people will install with pip I think I can close here for now and report if I can find out more of the cause.
