### ISSUE TITLE
Newest version read text based proto txt.

### ISSUE THREAD

**Issue by jinfagang** [protocolbuffers/protobuf#5273]
I think the old docs are nolonger work.
I wanna read the info from a proto txt which is the labelmap of VOC label and it's index.
problem is using C++ to load that.

```
LabelMap labelMap;
    int fd = open(labelmap_f, O_RDONLY);
    google::protobuf::io::ZeroCopyInputStream fstream(fd);
    google::protobuf::TextFormat::Parse(&fstream, &labelMap);
```
Just got some error

```
 error: cannot convert ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’ for argument ‘1’ to ‘int open(const char*, int, ...)’
     int fd = open(labelmap_f, O_RDONLY);
                                       ^: error: invalid conversion from ‘int’ to ‘google::protobuf::io::ZeroCopyInputStream*’ [-fpermissive]

```

I know previous usage is using `google::protobuf::io::FileInputStream`, but in 3.6 there is no such member function anymore.

What should I do?

**Comment by acozzette** [comment]
`FileInputStream` still exists [here](https://github.com/protocolbuffers/protobuf/blob/333b3ceab6b6d4b65ea7465b87321b805f838b36/src/google/protobuf/io/zero_copy_stream_impl.h#L65). Is it not working for some reason?

**Comment by jinfagang** [comment]
Sorry, that is my mistake, I should include it from another file but the ide failed to indicates me.
