### ISSUE TITLE
SerializeToString is  slow  when message is big 

### ISSUE THREAD

**Issue by ly82882592** [protocolbuffers/protobuf#5286]
Hi 
I  encounter a problem ，SerializeToString is  too slow when message is too big .
the message has  a repeated field ,the field size may be  more than 1000 .  
can I do  Serialize By thread pool and then merge them . I don`t kone Whether or not easy to do .
and  then I want try arena  at the protobuf version 3.6.1
so what is a good idea about big message .  
Thank you !!
@acozzette

**Comment by ly82882592** [comment]
sorry , I reply late.
I try to test it , now the pack size 100kb .  in the message has a repeated list ,the list size roughly 90 item .
and then we may be growth the list size to 1500.  maybe I can cut many sub package?

**Comment by acozzette** [comment]
OK, that's not huge or anything so I'm not sure why it would be slow. What language are you using by the way? I was assuming C++ but I realized that you might be using Python.

**Comment by ly82882592** [comment]
Yes , I use C++ ,and I try to replace 3.6 newly feature "arena" , when qps  increase  , the cpu 、tp and avg time cost become better. 
thank you ...

**Comment by acozzette** [comment]
Arenas are a good idea and I am glad they helped in your case. Let me close this issue but feel free to reopen it if you have more questions.
