### ISSUE TITLE
Python protobuf hash changed in pypi?

### ISSUE THREAD

**Issue by togakangaroo** [protocolbuffers/protobuf#5287]
The last few days I've started seeing this error popping up when doing `pipenv install` on fresh installs or in CI

```
24-Oct-2018 15:00:15 | THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
-- | --
24-Oct-2018 15:00:15 | protobuf==3.6.1 from https://files.pythonhosted.org/packages/3a/30/289ead101f94998d88e8961a3548aea29417ae0057be23972483cddebf4f/protobuf-3.6.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=4b92e235a3afd42e7493b281c8b80c0c65cbef45de30f43d571d1ee40a1f77ef (from -r /tmp/pipenv-eo2meuvr-requirements/pipenv-3_sqan5q-requirement.txt (line 1)):
24-Oct-2018 15:00:15 | Expected sha256 10394a4d03af7060fa8a6e1cbf38cea44be1467053b0aea5bbfcb4b13c4b88c4
24-Oct-2018 15:00:15 | Expected     or 1489b376b0f364bcc6f89519718c057eb191d7ad6f1b395ffd93d1aa45587811
24-Oct-2018 15:00:15 | Expected     or 1931d8efce896981fe410c802fd66df14f9f429c32a72dd9cfeeac9815ec6444
24-Oct-2018 15:00:15 | Expected     or 196d3a80f93c537f27d2a19a4fafb826fb4c331b0b99110f985119391d170f96
24-Oct-2018 15:00:15 | Expected     or 46e34fdcc2b1f2620172d3a4885128705a4e658b9b62355ae5e98f9ea19f42c2
24-Oct-2018 15:00:15 | Expected     or 59cd75ded98094d3cf2d79e84cdb38a46e33e7441b2826f3838dcc7c07f82995
24-Oct-2018 15:00:15 | Expected     or 5ee0522eed6680bb5bac5b6d738f7b0923b3cafce8c4b1a039a6107f0841d7ed
24-Oct-2018 15:00:15 | Expected     or 65917cfd5da9dfc993d5684643063318a2e875f798047911a9dd71ca066641c9
24-Oct-2018 15:00:15 | Expected     or 685bc4ec61a50f7360c9fd18e277b65db90105adbf9c79938bd315435e526b90
24-Oct-2018 15:00:15 | Expected     or 92e8418976e52201364a3174e40dc31f5fd8c147186d72380cbda54e0464ee19
24-Oct-2018 15:00:15 | Expected     or 9335f79d1940dfb9bcaf8ec881fb8ab47d7a2c721fb8b02949aab8bbf8b68625
24-Oct-2018 15:00:15 | Expected     or a7ee3bb6de78185e5411487bef8bc1c59ebd97e47713cba3c460ef44e99b3db9
24-Oct-2018 15:00:15 | Expected     or ceec283da2323e2431c49de58f80e1718986b79be59c266bb0509cbf90ca5b9e
24-Oct-2018 15:00:15 | Expected     or fcfc907746ec22716f05ea96b7f41597dfe1a1c088f861efb8a0d4f4196a6f10
24-Oct-2018 15:00:15 | Got        4b92e235a3afd42e7493b281c8b80c0c65cbef45de30f43d571d1ee40a1f77ef

```

Now I can always be wrong, but the only way I can think of that happening is if there was a change to the packages stored in PyPi but the version was not incremented.

Is this what happened?

Are these changes authorized by the team? Should I just update my lockfile and move on?

**Comment by TeBoring** [comment]
I recently uploaded wheel package for python 3.7. The difference is it has
a fix for compiler warning.

**Comment by TeBoring** [comment]
Sorry, I didn’t make a subrelease for that. Is there work around on your
side?

**Comment by togakangaroo** [comment]
Yup, thats fine, I just needed to know that someone hadn't hacked your Pypi and injected malicious code.

In the future, yeah, versioning...

**Comment by TeBoring** [comment]
Btw, it’s the first time we provide wheel for python3.7. I am not sure why
you have a pre-existing hash for that

**Comment by togakangaroo** [comment]
So I'm no python expert and this is the first time I'm even hearing about wheel so I can't answer that. I can tell you my workflow though.

I have a pipfile which pulls in grpcio 

```
grpcio = "*"
googleapis-common-protos = "*"
```

which in turn pulls in protobuf

```
googleapis-common-protos==1.5.3
  - protobuf [required: >=3.0.0, installed: 3.6.1]
    - setuptools [required: Any, installed: 40.4.3]
    - six [required: >=1.9, installed: 1.11.0]
grpcio-tools==1.15.0
  - grpcio [required: >=1.15.0, installed: 1.15.0]
    - six [required: >=1.5.2, installed: 1.11.0]
  - protobuf [required: >=3.5.0.post1, installed: 3.6.1]
    - setuptools [required: Any, installed: 40.4.3]
    - six [required: >=1.9, installed: 1.11.0]
```

protobuf [has been on pypi for a long time](https://pypi.org/project/protobuf/#history) so that's where the hash comes from - whenever you use `pipenv install` it will resolve versions and generate the lockfile with hashes same as in other platforms like npm.

My guess is that the changes you made got pushed out to pypi under the same version (I don't know the process which does that, sorry) - this results in the above warning in everyone who had been following the prescribed pipenv process (I assume this happens for pip too, don't know).

I think if yall bump the patch version now that will fix the issue for anyone who hasn't run into it yet.

**Comment by TeBoring** [comment]
My guess is previously you got our source distribution but now you have
wheel distribution. Even we don’t have the fix in code you would have the
same situation.

**Comment by grischa** [comment]
Thanks all! I ran into the same issue and I'm glad it's been reported here that protobuf wasn't hacked :)
Pypi should probably have caught this though
