### ISSUE TITLE
protoc 3.6.1 not support javanano any longer?

### ISSUE THREAD

**Issue by dss886** [protocolbuffers/protobuf#5288]
**What version of protobuf and what language are you using?**
Version: 3.6.1 (macOS, from Homebrew)
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS Mojave 10.14

**Question**
I usually used the old version (3.5.1)  support javanano compiler (--javanano_out=OUT_DIR), but when I change to a new computer and install the newest version (3.6.1) of protoc (using `brew install protoc` by Homebrew), javanano is not working any more.
When executing `protoc --javanano_out=enum_style=java,ignore_services=true:. *.proto`, error tip shows:

```
protoc-gen-javanano: program not found or is not executable
--javanano_out: protoc-gen-javanano: Plugin failed with status code 1.
```

**Comment by dss886** [comment]
protoc 3.5.1 help info:
![image](https://user-images.githubusercontent.com/5170950/47490586-99571c00-d87b-11e8-8888-db8bb6001295.png)

protoc 3.6.1 help info:
![image](https://user-images.githubusercontent.com/5170950/47490609-a8d66500-d87b-11e8-8e78-9b59cc4e24e5.png)

**Comment by acozzette** [comment]
@dss886 We dropped support for Javanano in favor of [Java lite](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md). I am not that familiar with nano and lite but my understanding is that it's not too difficult to migrate. Let us know if you have trouble switching to Java lite.

**Comment by dss886** [comment]
@acozzette I will try Java Lite，Thank you!
