### ISSUE TITLE
 How does the front end assign values ​​to variables with underscores in protocol2?

### ISSUE THREAD

**Issue by MingyueSun** [protocolbuffers/protobuf#5294]
I have tried the following methods, I use javascript, ask for advice.

in proto file

message user {
  optional string old_password = 1
}

in javascript file
const user = new messages.user()

- user.setOldpassword('aaa') // throw error

- user.setOldPassword('aaa') // throw error

- user.set_old_password('aaa') // throw error

**Comment by TeBoring** [comment]
My impression is ```user.setOldPassword('aaa')``` should be correct.
What error does it throw?

**Comment by MingyueSun** [comment]
> My impression is `user.setOldPassword('aaa')` should be correct.
> What error does it throw?

 it work , but after calling the method user.toObject() , the user change to {‘oldPassword':’aaa’}, but I need data like this {‘old_password': ‘aaa'}.
 Because it is defined like this in the proto file:

```javascript
 message user {
optional string old_password = 1
}
```

 when sending the request data, it will give me an error saying that the old_password field was not found. So, what should i do?

**Comment by TeBoring** [comment]
The problem is toObject has some bug. Could you avoid that?

**Comment by MingyueSun** [comment]
> The problem is toObject has some bug. Could you avoid that?


What can I do to avoid it?Or what can I do to get the data format I want?

**Comment by TeBoring** [comment]
Could you write your custom toObject which calls protobuf's accessors?
