### ISSUE TITLE
Warning msg from building Bazel

### ISSUE THREAD

**Issue by s50600822** [protocolbuffers/protobuf#5304]
I keep getting this msg when building Bazel from source, it seems to point me here:

> [1,542 / 2,012] SkylarkAction external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class [for host]
> INFO: From SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar [for host]:
> warning: could not find a JDK 8 bootclasspath in external/embedded_jdk, falling back to --release
> INFO: Created new non-sandboxed Javac worker (id 0), logging to /private/var/tmp/_bazel_hoaphan/35741574e6d63c2862008caa11c19b42/bazel-workers/worker-0-Javac.log
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib:resource_usage:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/windows/runfiles:runfiles:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/actions:commandline_item:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/skyframe/serialization/autocodec:registered-singleton:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/skyframe/serialization:constants:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/windows/jni:processes:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/common/options:invocation_policy:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/hoaphan/Library/Application%20Support/IntelliJIdea2018.2/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> INFO: From Parsing java package strings for //src/main/java/com/google/devtools/build/lib/windows/jni:file:
> WARNING: An illegal reflective access operation has occurred
...

**Comment by BSBandme** [comment]
Closed this for duplicating with #3781

**Comment by s50600822** [comment]
> Closed this for duplicating with #3781

somehow your avatar works perfectly fine with the comment XD
