### ISSUE TITLE
cross compiling for sh4 - sched_yield was not found on your system

### ISSUE THREAD

**Issue by MZDN** [protocolbuffers/protobuf#5305]
I am trying to compile this for sh4 target. Unfortunately I am facing this issue. Any idea, what could be the issue?

checking whether the linker supports version scripts... no
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... no
checking fcntl.h presence... yes
configure: WARNING: fcntl.h: present but cannot be compiled
configure: WARNING: fcntl.h:     check for missing prerequisite headers?
configure: WARNING: fcntl.h: see the Autoconf documentation
configure: WARNING: fcntl.h:     section "Present But Cannot Be Compiled"
configure: WARNING: fcntl.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------- ##
configure: WARNING:     ## Report this to protobuf@googlegroups.com ##
configure: WARNING:     ## ---------------------------------------- ##
checking for fcntl.h... no
checking for inttypes.h... (cached) yes
checking limits.h usability... no
checking limits.h presence... yes
configure: WARNING: limits.h: present but cannot be compiled
configure: WARNING: limits.h:     check for missing prerequisite headers?
configure: WARNING: limits.h: see the Autoconf documentation
configure: WARNING: limits.h:     section "Present But Cannot Be Compiled"
configure: WARNING: limits.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------- ##
configure: WARNING:     ## Report this to protobuf@googlegroups.com ##
configure: WARNING:     ## ---------------------------------------- ##
checking for limits.h... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for working memcmp... no
checking for working strtod... no
checking for pow... no
checking for pow in -lm... no
configure: WARNING: cannot find library containing definition of pow
checking for ftruncate... no
checking for memset... no
checking for mkdir... no
checking for strchr... no
checking for strerror... no
checking for strtol... no
checking zlib version... headers missing or too old (requires 1.2.0.4)
checking whether sh-linux-gnu-gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking the location of hash_map... 
configure: WARNING: could not find an STL hash_map
checking for library containing sched_yield... no
configure: error: in `BUILDDIR/protobuf-3.6.1':
configure: error: sched_yield was not found on your system
See `config.log' for more details

Thanks in advance and kind regards
@MZDN

**Comment by TeBoring** [comment]
Sorry that we don't currently support sh4. If you have a fix, we are happy to merge.
