### ISSUE TITLE
Is msg serialized by version3.X compatible with 2.6.1?

### ISSUE THREAD

**Issue by happyxgang** [protocolbuffers/protobuf#5307]
we are using pb2.6.1 to transfer msg from server to client.
now we want to upgrade pb to newly released 3.X version.
if i add syntax="proto2" in proto files and regenerate new pb file for server .but client code remains the same. 
is the binary stream compatible?

**Comment by acozzette** [comment]
@happyxgang Yes, absolutely--we put a great deal of effort into keeping the wire format compatible with every change we make. Just make sure to set `syntax = "proto2";` like you mentioned.
