### ISSUE TITLE
Publish proto3 via IETF or similar industry body

### ISSUE THREAD

**Issue by sandersaares** [protocolbuffers/protobuf#5311]
It would be desirable to reference protocol buffers in published specifications. However, it can be seen as "risky" by some to reference a specification that is essentially controlled by one company.

I request that proto3 be published via some industry body to eliminate this risk and to encourage protocol buffer usage in other industry specifications. IETF might be a good venue for this now that protocol buffers are becoming ever mode widely used on the web thanks to gRPC.

**Comment by beriberikix** [comment]
There was an earlier [MIME](https://tools.ietf.org/html/draft-rfernando-protocol-buffers-00) submission that has since expired. Any updates on it?

**Comment by haberman** [comment]
There are no plans to standardize protobuf through a standards body.
