### ISSUE TITLE
How to add message objects to existing nested message objects (TensorFlow related)?

### ISSUE THREAD

**Issue by pwyq** [protocolbuffers/protobuf#5327]
__Note__: This question relates to [TensorFlow](https://github.com/tensorflow/tensorflow).

- __Language__: Python
- __OS__: Ubuntu 18.04 (Developing), Windows/Mac/Linux (Shipping)

---

### `message` object definition in TensorFlow
Following in descending orders (e.g, `GraphDef` contains `NodeDef`):
- [GraphDef][1]
- [NodeDef][3]
- [OpDef][2] (An `Operation` is a `node` in a TensorFlow `Graph`) 
- [AttrValue][4] (A `node` can have multiple attributes)

### Background statement
I have a frozen TensorFlow graph, which stores in `.pb` format. I wish to update the graph by adding new attributes to some nodes in the graph. Now, I can load the graph and access the information of every node, but I failed to add custom attributes to nodes.

My plan is to:   
1. load the `Graph` object from `.pb` file;
2. find nodes that need to modify;
3. add new attributes to old attribute dictionary;
4. create updated `Attribute` object;
5. create updated `Node` object;
6. create updated `Graph` object;
7. generate the new `.pb` file.

## Problem
I cannot add/append custom attributes message objects (`AttrValue`) to existing `NodeDef` message object. 
- Since _the number of nodes that need modify may up to millions_, I need to automate this process as much as possible.
- Since the product could be used in various OSes, I want to avoid any extra compile step. It would be ideal to address the problem using native APIs.

### 1. Generate a completely new `op` using C++
[Adding a New Op][5], this method is inefficient and infeasible. It requires to create/compiler c++ files for every node that modified.

### 2. Use TensorFlow APIs
I essentially want to use [create_op()][8] to finish step 5 in my plan, but I am stuck in getting `attr` and `op_def` object. I tried some methods like:
- `MyOperation.op_def.attr.extend(......)`
- `MyOperation._set_attr(......)` [_set_attr() definition][7]

I don't know the proper format to add custom attributes, so I couldn't get these methods work.

### 3. Use Protobuf APIs
[google.protobuf.json_format - MessageToJson/Parse][6]. I attempted to first convert to JSON, then directly manipulate the JSON string, then convert back to message object. However, the jsonified string `NHWC` becomes `TkhXQw==` (random string??). Through my observation, I found this only happens to double-quoted upper-case string in the message object. Example output below:

Before converting to JSON:
```
attr {
  name: "T"
  type: "type"
  default_value {
    type: DT_FLOAT
  }
  allowed_values {
    list {
      type: DT_HALF
      ......
      type: DT_QINT8
    }
  }
}
attr {
  name: "padding"
  type: "string"
  allowed_values {
    list {
      s: "SAME"
      s: "VALID"
    }
  }
}
```

After converting to JSON:
```
    {
      "defaultValue": {
        "type": "DT_FLOAT"
      }, 
      "type": "type", 
      "name": "T", 
      "allowedValues": {
        "list": {
          "type": [
            "DT_HALF", 
             ......
            "DT_QINT8"
          ]
        }
      }
    }, 
    {
      "defaultValue": {
        "s": "TkhXQw=="
      }, 
      "type": "string", 
      "name": "data_format", 
      "allowedValues": {
        "list": {
          "s": [
            "TkhXQw==", 
            "TkNIVw==", 
            "TkNIV19WRUNUX0M="
          ]
        }
      }
    }
```

## Questions
1. Is there any useful Protobuf/TensorFlow API that could address my problem that I might missing?
    - While writing this issue, I just found `get_or_create_list()`/`get_or_create_struct()`/`add_list()`/`add_struct()` from protobuf. I will try these later and update.
2. Why the protobuf `MessageToJson()` introduces random string?
3. What is the proper format/way to add attributes using aforementioned APIs? Suppose I'd like to add an `attr` message object in the nodes, e.g:
```
attr {
  name: "my_custom_attr"
  type: "string"
  default_value {
    s: "VAL1"
  }
  allowed_values {
    list {
      s: "VAL1"
      s: "VAL2"
    }
  }
}
```

This is my first time to use `protobuf`, so I might miss some trivial tricks to do the task.  
It would be very much appreciated if anyone could help me addressing my questions. Thank you in advance!

[1]:https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/graph.proto
[2]:https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_def.proto
[3]:https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/node_def.proto
[4]:https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/core/framework/attr_value.proto
[5]:https://www.tensorflow.org/guide/extend/op
[6]:https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.json_format-module
[7]:https://github.com/tensorflow/tensorflow/blob/df48eafe91edb18fdb5199d35aa2cad02d3728e5/tensorflow/python/framework/ops.py#L2326
[8]:https://github.com/tensorflow/tensorflow/blob/df48eafe91edb18fdb5199d35aa2cad02d3728e5/tensorflow/python/framework/ops.py#L3225

**Comment by acozzette** [comment]
I think the issue with that random-looking string is that it's a `bytes` field and not a `string` field. String fields are required to store UTF8-encoded data, but a bytes field can store arbitrary bytes. As a result, the JSON format is defined to store bytes fields in base64-encoded form.
