### ISSUE TITLE
Valgrind report: "Mismatched free() / delete / delete []"

### ISSUE THREAD

**Issue by meierfra-ergon** [protocolbuffers/protobuf#5331]
we do automated Valgrind testing with our code. After upgrading to protobuf-3.6.1 (from 2.6.1). We saw a lot of "Mismatched free() / delete / delete []" Valgrind errors.

see: [valgrind.log](https://github.com/protocolbuffers/protobuf/files/2566167/valgrind.log)

We did not experience any problems so far, but I thought I post it here since it could be a bug in Protobuf.

BTW we compile the protobuf library ourselfs with gcc-7.3.0

Regards,

**Comment by paulfloyd** [comment]
Check the disassembly for google::protobuf::FileDescriptorProto::~FileDescriptorProto()
It's likelyh to be using TCO to jump to operator delete rather than calling it.
