### ISSUE TITLE
readme file contains incorrect downloads info

### ISSUE THREAD

**Issue by Stokestack** [protocolbuffers/protobuf#5333]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
3.6.1

Language: Swift

**What operating system (Linux, Windows, ...) and version?**
Mac OS 10.14.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Go to https://github.com/protocolbuffers/protobuf/releases and look for a binary for your platform (as directed in the readme file).

**What did you expect to see**
The readme file says:
"In the downloads section of each release, you can find pre-built binaries in
zip packages: protoc-$VERSION-$PLATFORM.zip"

**What did you see instead?**
No platforms specified anywhere. Instead, the downloads look like:
protobuf-csharp-3.6.1.zip

So the names are not as expected, and there's no distinction of what platform it's for.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
I just checked and they seem to be there, near the bottom of the list of assets. For example, I see `protoc-3.6.1-linux-aarch_64.zip`, `protoc-3.6.1-linux-x86_32.zip` etc. Let me close this for now but feel free to comment again if I misunderstood something or if there's still a problem.
