### ISSUE TITLE
[python] deprecated collections usage (redux)

### ISSUE THREAD

**Issue by tseaver** [protocolbuffers/protobuf#5335]
**What version of protobuf and what language are you using?**
Version: master
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Any

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.1

#5195 purported to fix #5135, but did so only for the deprecated usage in the `google.protobuf.internal.containers` module.  Further changes are needed:

```bash
$ git grep -l "collections\.[A-Z]" "*.py"
python/google/protobuf/internal/_parameterized.py
python/google/protobuf/internal/message_test.py
python/google/protobuf/internal/well_known_types.py
python/google/protobuf/internal/well_known_types_test.py
```

**Comment by Evpok** [comment]
The alphas of 3.8 are getting out, any news on this?

**Comment by rok-povsic** [comment]
I'm seeing this in the logs:
```
/Users/travis/.pyenv/versions/3.7.2/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from google.protobuf.pyext import _message
```

Looking forward to the fix.

**Comment by anandolee** [comment]
A fix has been submitted in internal code with:
```
try:
  import collections.abc as collections_abc
except ImportError:
  import collections as collections_abc
```
Expect to see the fix in next release

**Comment by cclauss** [comment]
Python 3.8 release candidate 1 is available: https://www.python.org/download/pre-releases

**Comment by cclauss** [comment]
Python 3.8 was released yesterday https://www.python.org/downloads/release/python-380/

**Comment by yuvadm** [comment]
A fix is pending, why isn't it being merged? https://github.com/protocolbuffers/protobuf/pull/6272
