### ISSUE TITLE
Full oneof support

### ISSUE THREAD

**Issue by Alfus** [protocolbuffers/protobuf#5336]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
Oneof has several issues:
- "None of" is not 'safe' to use as there is no way to distinguish between no value set, and an 'unknown' value set. For example, if a new field was added to a oneof, code that lacks knowledge of that new field will see no value set in the oneof (and an unknown field value). In contrast a normal proto3 enum will show an 'unrecognized' value set, in a similar situation.
- Repeated and map fields not supported in oneof. I suspect this is due to the fact there is no encoded form of 'set, but empty' for these types of fields. 

**Describe the solution you'd like**
The ability to assign a field number to the oneof field:

    message Foo {
      oneof value_type = 1 {
        map<string, Bar> map_value = 2;
        repeated<Bar> list_value = 3;
      }
    }

In this case, 'value_type' would be a full fledged enum field, and this message would be ~equivalent to:

    message Foo {
      enum ValueTypeCase {
        // (BTW I regret making the standard for OnePlatform UNSPECIFIED, given that oneof uses NOT_SET).
        VALUE_TYPE_NOT_SET = 0;
        kMapValue = 2;
        kListValue = 3;
      }

      ValueTypeCase value_type = 1;
      map<string,  Bar> map_value = 2;
      repeated<Bar> list_value = 3;
    }
  
**Describe alternatives you've considered**
The current workarounds are:
For the first problem (no safe way to do 'none of'), you have to add a special oneof value to represent 'none of', and reject messages that don't have a value in the oneof set. Most often `google.protobuf.NullValue` is used for this (which is a bit awkward in code gen). This is actually why the `NullValue` enum was added in the first place. An enum with a single value is the only way to have a binary option in a oneof (vs trinary which is what you get with a bool in a oneof). Every usage of `NullValue` in google apis, is to solve this problem:
https://github.com/googleapis/googleapis/search?q=google.protobuf.NullValue&unscoped_q=google.protobuf.NullValue

For the second issue (no support for repeated/map fields), you have to wrap such fields in an additional message before including them in the oneof. There are also many such examples in the google apis protos:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto#L77
https://github.com/googleapis/googleapis/blob/master/google/firestore/v1beta1/document.proto#L131
https://github.com/googleapis/googleapis/blob/master/google/api/expr/v1beta1/value.proto#L64

**Additional context**

**Comment by acozzette** [comment]
Unfortunately I think this would be pretty hard to implement. I'm not sure how we would encode this in a way that is compatible with existing code and serialized messages. The best solution is probably just to use caution when modifying the schema of a `oneof`.

**Comment by Alfus** [comment]
The only difference in the wire format is an extra optional varint field. 

'new' writer -> 'old' reader: This field would end up in the unknown fields. The oneof case value would follow current semantics.
'old' writer -> 'new' reader: No value would be present, so the oneof case value would follow existing semantics.

The 'tough' question is what should happen when the value and the set fields disagree. For example, if an 'old' reader sets a value in the oneof, while also passing on the explicit value set in UnknownFieldSet.

@jgeewax,@wrwg: Curious what you guys think of this idea.

**Comment by Alfus** [comment]
I had another "interesting" idea on how to improve oneof for map and repeated fields.  I believe a 'packed' repeated field can represent an empty list on the wire. Assuming this, it should be possible to:
- Allow packed repeated fields in oneof where "empty but set" would use an empty packed wire representation (a length delimited tag and a zero length)
- Add support for any repeated field to be packed (I believe only numeric types are supported currently, but it should be possible to support all types).

With this any repeated field can be packed, and any packed repeated field (including maps) could be included in a oneof. It also makes skipping past repeated fields in a serialized byte stream much more efficient, as a packed representation includes byte length offset of (ideally) all its values. This doesn't solve the 'none of' problem, but that is definitely the lesser of the two issues.
