### ISSUE TITLE
Generated 'zero' Value for Enums

### ISSUE THREAD

**Issue by Alfus** [protocolbuffers/protobuf#5337]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
proto3 requires that a zero-value be present in all enums. This zero-value is almost always ENUM_NAME_UNSPECIFIED as specified in the [google style guide](https://cloud.google.com/apis/design/design_patterns#enum_default_value) (btw, sorry I picked UNSPECIFIED instead of NOT_SET, which is what is used for the oneof case enum, though I was trying to be consistent with UNRECOGNIZED as described below).

**Describe the solution you'd like**
Just as the special enum value, UNRECOGNIZED, is created in closed enum languages, the zero value should be auto generated when not specified. For example:

    enum Foo {
      BAR = 1;
    }

in java could generate:

    enum Foo {
      UNSPECIFIED(0),
      BAR(1),
      UNRECOGNIZED(-1)
    }

in c++ it could generate:

    enum Foo {
      FOO_UNSPECIFIED = 0,
      BAR = 1,
      // c++ supports open enums, so no unrecognized value needed.
    };

If a zero value is specified (currently required by proto3), code gen is unchanged. Such a value supposed to be an idiomatic version of 'UNSPECIFIED', for example'OK=0;' in code.proto represents that lack of an error. 

**Describe alternatives you've considered**
Live with *_UNSPECIFIED in almost every enum forever.

**Additional context**

**Comment by acozzette** [comment]
I can see the appeal of having the zero value auto-generated, but I'm afraid it's unlikely that we would make this change. One could argue that the explicitness of having the zero value spelled out is actually a good thing, and even if everyone agreed that the feature is a good idea, it seems like lot of work for a pretty small benefit.
