### ISSUE TITLE
Can reserved be used in oneof?

### ISSUE THREAD

**Issue by bobjobob** [protocolbuffers/protobuf#5338]
Is it possible to use "reserved" inside "oneof"?  The proto3 language guide does not specify anything about this.  It seems like something that logically would be supported, but it does not work in the version I'm using (3.1.0) and I don't see anything in the change log that would indicate it has since been added.  

Assuming the answer is "no", is there a reason this support hasn't been or can't be added?

**Comment by acozzette** [comment]
It seems to me that there's not that much value to supporting `reserved` inside a oneof, because you can just as well reserve the same field number outside the oneof (it doesn't really make any difference whether the reserved field appears inside the oneof or not).

**Comment by bobjobob** [comment]
That's a fair point.  My thought was that it seemed more intuitive to have the fields reserved inside the oneof, especially if it is deprecating a field that used to be inside the oneof.  Otherwise you have to look elsewhere in the message definition to see what fields numbers and names are no longer allowed.  It's really just a mild aesthetic annoyance more than anything.

If there isn't enough value to add this support, can the proto3 Developer's Guide be updated to note that this isn't supported?  It might save the next person a bit of time.

**Comment by anandolee** [comment]
If deprecate a field that used to be inside the oneof, all the message should avoid the field number not just oneof, put inside oneof will confuse people.

I don't think we want to list all the non support in human words, however we have a spec which shows reserve is not supported in oneof:
https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#oneof_and_oneof_field

**Comment by ajakaja** [comment]
It's not particularly important to me, but I want to flag that 

> all the message should avoid the field number not just oneof, put inside oneof will confuse people.

Isn't correct, IMO. What confused me is that `reserved` _isn't_ allowed inside a `oneof` field. `oneof` already lists numbers that should be avoided, it's not weird for it to also include reserved ones. It's nice to be able to deprecate fields exactly where they were used.
