### ISSUE TITLE
how to use cross compile version protobuf

### ISSUE THREAD

**Issue by darbee** [protocolbuffers/protobuf#5340]
When we cross compile a project that depend protobuf such ROS.

first we cross compile protobuf for arm. then we get arm version libprotobuf* and a arm version tool named protoc( which can convert proto to .h .cc )
second we cross compile ROS on x86. ROS contain some file like a.proto and b.proto ..
So, which version protoc should we use to convert those *.proto to *.h and .cc?
I think we should use x86 version protoc instead of arm version protoc.
But when we include headers and link dynamic libraries , we should use arm version, such as libprotobuf(arm)
These steps puzzled me，How should we use protobuf

**Comment by acozzette** [comment]
`protoc` needs to run as part of the build, so I think you're right that you want to use an `x86` version of `protoc`. But `libprotobuf` needs to run on the target platform, so you will want to build that for ARM.

**Comment by darbee** [comment]
thanks for your relpy @acozzette . So we should take two steps: first build proto files use x86's version protoc and second link with arm's version libprotobuf?
