### ISSUE TITLE
Minor Typo in Message.php and maybe others

### ISSUE THREAD

**Issue by Allmoz** [protocolbuffers/protobuf#5345]
Hi, where it says:
@throws Exception Invalid data.

it should be :
@throws \Exception Invalid data.

or perhaps:
@throws GPBDecodeException Invalid data.

:) keep the great work

**Comment by TeBoring** [comment]
Could you help send a fix to us?

**Comment by Allmoz** [comment]
ok, i will try

**Comment by Allmoz** [comment]
Done :) i found some ErrorException too.
https://github.com/protocolbuffers/protobuf/pull/5381
