### ISSUE TITLE
sched_yield was not found on your system.

### ISSUE THREAD

**Issue by techoner** [protocolbuffers/protobuf#5351]
Compile failed in CentOS release 6.9

**Comment by TeBoring** [comment]
If you have a fix, we are happy to accept it.

**Comment by acozzette** [comment]
Feel free to send us a pull request if you can come up with a fix.

**Comment by romgille** [comment]
Same problem for me when running configure from protobuf 3.6.1

**Comment by acozzette** [comment]
I fixed this recently on #5435. For now the fix is only on the 3.7.x branch, but that will get merged to master soon.
