### ISSUE TITLE
v3.6.0 crashes on Ubuntu 14.04 when compiling gRPC v1.15.0

### ISSUE THREAD

**Issue by mpoullet** [protocolbuffers/protobuf#5353]
**What version of protobuf and what language are you using?**
Version: **v3.6.0** (this issue does not happen with v3.5.2)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu **14.04** (this issue does not happen on 16.04 and 18.04)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Default versions provided by Ubuntu 14.04 like `g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`

**What did you do?**
I build `gRPC` v1.15.0 on Ubuntu 14.04 in Travis CI ([log](https://travis-ci.org/mpoullet/grpc/builds/451877490)) using this [script](https://github.com/mpoullet/grpc/blob/travis-1.15.0/.travis.yml). It builds `protobuf` v3.6.0 in the `third_party/protobuf`directory. Then it uses it.

**What did you expect to see**
`gRPC` v1.15.0 build using `protobuf` v3.6.0 works.

**What did you see instead?**
```
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/channelz/channelz.proto
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [/home/travis/build/mpoullet/grpc/gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1
```

**Anything else we should know about your project / environment**
- it started with this [PR](https://github.com/googlesamples/assistant-sdk-cpp/pull/54).
- then I've opened an issue in https://github.com/grpc/grpc/issues/17136
- then I've done a `git bisect` in `gRPC` to find out that https://github.com/grpc/grpc/commit/894745dfe39185620cf644508fd6fe was responsible for breaking the build on Ubuntu 14.04.
- so now I open this issue here and hope someone (@Fleker / @jtattermusch / @acozzette) could help me fix the dependency chain [assistant-sdk-cpp](https://github.com/googlesamples/assistant-sdk-cpp) -> [gRPC](https://github.com/grpc/grpc) -> [protobuf](https://github.com/protocolbuffers/protobuf)
- I've tried to bisect `protobuf` too and I can see that e436ee0aa179340832281b7d90885e9ff15b3748 is [good](https://travis-ci.org/mpoullet/grpc/builds/454881150) and fcde518699fb4d9cc27bff3f34c3a85e21d54a67 is [bad](https://travis-ci.org/mpoullet/grpc/builds/454893405) which leaves 14 commits in between to inspect. As I'm totally new to `protobuf` that is the most i can report by myself.

**Comment by aduskett** [comment]
I am going to bump this, as Buildroot is also having this issue when trying to cross-compile grpc with protobuf. We have tried the latest two versions, and I have personally tried with 4.0-rc2 as well.

We are receiving the exact same error as @mpoullet and it's kind of sad that this bug has been ignored. :(

**Comment by yann-morin-1998** [comment]
> I am going to bump this, as Buildroot is also having this issue when trying to cross-compile grpc with protobuf.

Nit: we are having the problem when building the *native* variant, i.e. a native build, not a cross-build.

The cross-build *is* OK in Buildroot.

**Comment by aduskett** [comment]
> > I am going to bump this, as Buildroot is also having this issue when trying to cross-compile grpc with protobuf.
> 
> Nit: we are having the problem when building the _native_ variant, i.e. a native build, not a cross-build.
> 
> The cross-build _is_ OK in Buildroot.

Sorry, yeah, this is the issue.

**Comment by heinemml** [comment]
In https://github.com/protocolbuffers/protobuf/issues/5923 @snnn gave a good explanation what's going wrong.

To fix the grpc build (when upgrading the toolchain is not an option) pass this to the initial cmake command when building grpc:
```
cmake -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-as-needed" ../..
```

I submitted a patch to the buildroot Mailinglist.

Related issue: 
 * https://github.com/grpc/grpc/issues/19265

**Comment by gt945** [comment]
@heinemml thanks
I post your link here for someone who meet same issue
http://buildroot-busybox.2317881.n4.nabble.com/git-commit-branch-2020-02-x-package-grpc-fix-build-on-ubuntu-gcc-4-8-td268725.html

**Comment by elharo** [comment]
grpc issue, and probably fixed there
