### ISSUE TITLE
generated_message_table_driven.h causes 4647 warning on MSVC

### ISSUE THREAD

**Issue by nikitamiroshnichenko** [protocolbuffers/protobuf#5354]
Hi!
I using protoc from protobuf v3.6.1 for wrappers generation from proto. Generated code have include of `google/protobuf/generated_message_table_driven.h`

In this file on line 173 located `static_assert(std::is_pod<AuxillaryParseTableField>::value, "");` this code cause 
C4647 level 3 warning: 
`C4647: behavior change: __is_pod(google::protobuf::internal::AuxillaryParseTableField) has different value in previous versions`

In our project - this warning marked as error (we doesn't have any chance to supress this warning and we don't want to change protobuf sources), as result - build fails.

My question is: Can we somehow avoid this warning?

**Comment by acozzette** [comment]
It's hard to tell what the warning is saying, but feel free to send us a pull request if you can figure out a fix.

**Comment by sbenzaquen** [comment]
This code no longer exists at head.
