### ISSUE TITLE
Grpc compilation failing due to "grpc_cpp_plugin: program not found or is not executable"

### ISSUE THREAD

**Issue by vprasad** [protocolbuffers/protobuf#5356]
Hi,
I am trying to compile grpc for qnx ppc with gcc 5.2.0.
i did the cmake and generated Makefile and whle doing the compilation using make getting the below error:-

/home/viprasad/grpc-master/build/grpc_cpp_plugin: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
make[2]: *** [CMakeFiles/grpcpp_channelz.dir/build.make:64: gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/grpcpp_channelz.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
in-mvlb46:build[ppc-qnx-viprasad_in-mvlb46_6461-main]$vim ../CMakeLists.txt 

However the executable grpc_cpp_plugin is present in the path /home/viprasad/grpc-master/build but it still tells an error .

Note:-before compiling grpc i had compiled the protobuf for qnx ppc .

Can anyone please guide me regarding the above error on how to further proceed .
Will Appreciate any help. 

Thanks,

**Comment by acozzette** [comment]
@vprasad This sounds like more of a gRPC issue than a protobuf issue, so you may want to ask the gRPC folks about this.
