### ISSUE TITLE
Linking Windows Cross Compiled library, results in mutex errors

### ISSUE THREAD

**Issue by TheCharlatan** [protocolbuffers/protobuf#5358]
Protobuf v3.6.0
Language: C++
Ubuntu 18.04
Cross compiling with x86_64-w64-mingw32-g++, native toolchain x86_64-linux-gnu

I run my builds in an environment, where I compile all dependencies from scratch. In this instance, I am cross compiling an application on linux to windows that links with protobuf. The application compiles fine when I cross compile from on x86 host to a aarch64 target. But for mingw it reaches the following line and then spits out a bunch of mutex related errors. The compiler is run with the following arguments:

    /usr/bin/x86_64-w64-mingw32-g++  -DZMQ_STATIC -maes -march=native -fno-strict-aliasing 
    -std=c++11 -D_GNU_SOURCE  -DWIN32_LEAN_AND_MEAN  -Wall -Wextra -Wpointer-arith 
    -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-
    unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-
    error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Wno-
    error=unused-value -Wno-error=unused-but-set-variable -Wno-reorder -Wno-missing-field-
    initializers  -fPIC  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security 
    -mmitigate-rop -fno-strict-aliasing -DNDEBUG -O2    -Wl,--stack,10485760  -Wl,--dynamicbase 
    -Wl,--nxcompat -static  -Wl,--whole-archive CMakeFiles/wallet_rpc_server.dir/objects.a -Wl,--no-
    whole-archive  -o ../../bin/rpc.exe -Wl,--out-implib,../../lib/librpc.dll.a -Wl,--major-image-version,0,--
    minor-image-version,0 @CMakeFiles/wallet_rpc_server.dir/linklibs.rsp

And then returns a bunch of these errors:

    ../device_trezor/libdevice_trezor.a(messages.pb.cc.obj):messages.pb.cc:
    (.text$_ZSt9call_onceIRFvvEJEEvRSt9once_flagOT_DpOT0_[_ZSt9call_onceIRFv
    vEJEEvRSt9once_flagOT_DpOT0_]+0x10): undefined reference to `std::__get_once_mutex()'
    ../../../contrib/depends/x86_64-w64-mingw32/lib/libprotobuf.a(common.o):common.cc:
    (.text$_ZSt9call_onceIRPFvvEJEEvRSt9once_flagOT_DpOT0_[_ZSt9call_onceIRPFvv
    EJEEvRSt9once_flagOT_DpOT0_]+0x1f): undefined reference to `std::__get_once_mutex()'

Beforehand I generated the messages with a different version of protoc, that is separately compiled on the host toolchain. When configuring the cross compiled protobuf library, I do not pass in the location of the host compiled protoc binary. The application built fine on all toolchains before adding the protobuf library.

**Comment by ph4r05** [comment]
We managed to fix it by using posix versions of mingw32-w64 for both g++ and gcc:

```bash
update-alternatives --set x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++-posix)
update-alternatives --set x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc-posix)
```
