### ISSUE TITLE
Recent change in message_lite.h breaks build of generated code

### ISSUE THREAD

**Issue by decibelcooper** [protocolbuffers/protobuf#5361]
**What version of protobuf and what language are you using?**
Version: 8dadfda1e3c270458dbff0a2aff3218632890882
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
GNU 7.3.0

**What did you do?**
1. Build protobuf with default options in above commit
2. Generate message code with `protoc`
3. Compile message code

**What did you expect to see**
Successful compilation

**What did you see instead?**
```shell
In file included from /usr/local/include/google/protobuf/wire_format_lite_inl.h:45:0,
                 from /usr/local/include/google/protobuf/map_type_handler.h:35,
                 from /usr/local/include/google/protobuf/map.h:49,
                 from /usr/local/include/google/protobuf/generated_message_table_driven.h:34,
                 from /home/travis/build/proio-org/cpp-proio/build/proio/model/eic/eic.pb.h:26,
                 from /home/travis/build/proio-org/cpp-proio/build/proio/model/eic/eic.pb.cc:4:
/usr/local/include/google/protobuf/message_lite.h:49:10: fatal error: google/protobuf/stubs/strutil.h: No such file or directory
```

I see that strutil.h is indeed not installed.  In googling around I see people saying that it is not supposed to be installed.  However, a very recent commit (0894e07536af88065d462cdc9d8e807c0723ef4d) has added a dependency to it in installed header `message_lite.h`:
https://github.com/protocolbuffers/protobuf/blob/8dadfda1e3c270458dbff0a2aff3218632890882/src/google/protobuf/message_lite.h#L49

**Anything else we should know about your project / environment**
It is a standard, clean environment in a container, with protobuf built from the master branch.

**Comment by acozzette** [comment]
@decibelcooper Thanks for reporting this. I changed things to make sure we install strutil.h, so this should now be fixed.

**Comment by ayounes-nviso** [comment]
https://github.com/protocolbuffers/protobuf/pull/5442
