### ISSUE TITLE
protobuf/src/google/protobuf/stubs/common.h

### ISSUE THREAD

**Issue by mqqq1024** [protocolbuffers/protobuf#5370]
protobuf/src/google/protobuf/stubs/common.h

on the line 74：    namespace std {}
is a bug？or not？

**Comment by acozzette** [comment]
It looks like that line was added in the first commit more than 10 years ago. I think you're right that it's not necessary, so feel free to send a pull request to remove it.

**Comment by mqqq1024** [comment]
@acozzette I think that line should be " using namespace std; ",because when i include the file "protobuf/src/google/protobuf/stubs/stringprintf.h "（and other files which use ‘vector’ ）, the compiler will gives me an error “/usr/include/google/protobuf/stubs/stringprintf.h:71:79: error: ‘vector’ does not name a type
 LIBPROTOBUF_EXPORT extern string StringPrintfVector(const char* format, const vector<string>& v);”.

**Comment by mqqq1024** [comment]
@acozzette Thanks. I'll try.
