### ISSUE TITLE
 I'm getting an error about the gnuc version.

### ISSUE THREAD

**Issue by jihyeon92** [protocolbuffers/protobuf#5371]
protobuffer version : 3.4.1
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
./google/protobuf/stubs/atomicops.h:231: error: #error GOOGLE_PROTOBUF_ATOMICOPS_ERROR

This error has occurred. so I tried to open the file.
I have seen the following conditional statement.

 #elif (((__GNUC__ == 4) && (__GNUC_MINOR__ >= 7)) || (__GNUC__ > 4))

But my gnuc version is 4.4 and I can not change this version.
Is there a way to solve this problem by simply upgrading the version?

**Comment by acozzette** [comment]
You could try changing that logic to allow version 4.4 and see if it builds, but GCC 4.4 might not be supported. Upgrading the protobuf version probably won't help unfortunately, and starting from 3.6 we require C++11, which likely means an even newer version of GCC.
