### ISSUE TITLE
Python3 import issues

### ISSUE THREAD

**Issue by cromefire** [protocolbuffers/protobuf#5374]
## What language does this apply to?
python (3)

## Describe the problem you are trying to solve.
See #1491 

### Structure
```
proto/ <-- git module
    test1.proto
    test2.proto
src/ <-- in PYTHONPATH
    proto_test/
        proto/
            test1_pb2.py
            test2_pb2.py
test_it.py
```

### Files
`test1.proto`:
```
syntax = "proto3";
```

`test2.proto`:
```
syntax = "proto3";
import public "test1.proto"
```

`test_it.py`:
```python3
import "proto_test.proto.test1_pb2"
```

### Run
CMD:
`protoc "--proto_path=$(pwd)/proto" "--python_out=$(pwd)/src/proto_test/proto"`

Run the python file:
```bash
export PYTHONPATH="$(pwd)/src"
python3 test_it.py
```

### Result
`ModuleNotFoundError: No module named 'student_pb2'`

## Describe the solution you'd like
There are 4 proposed solutions that do not prevent parallelism:
1. Just output them relatively:
    ```
    import public "test1.proto";
    ```
    gets:
    ```python3
    from .test1_pb2 import *
    ```
    ```
    import public "../test1.proto";
    ```
    gets:
    ```python3
    from ..test1_pb2 import *
    ```
    There may be some other cases that need more lookups on how these imports work
2. Use import by file path:
    https://stackoverflow.com/a/67692
    ```
    import public "test1.proto";
    ```
    gets:
    ```python3
    import importlib.util
    from os.path import join, dirname
    test1__pb2_spec = importlib.util.spec_from_file_location("test1_pb2", join(dirname(__file__), "test1_pb2.py"))
    test1__pb2 = importlib.util.module_from_spec(test1__pb2_spec)
    test1__pb2_spec.loader.exec_module(test1__pb2)
    ```
    (could live in a helper function)
3. Implement `python_package` similar to `java_package`
3. Do `python_package` as a CLI flag

Additionally I think for method 1 and 2 it should be optionally triggered by a commandline flag, like `--python3_relative`

## Describe alternatives you've considered
You could do:
```
proto/ <-- git module
    proto_test/
        proto/
            test1.proto
            test2.proto
src/ <-- in PYTHONPATH
    proto_test/
        proto/
            test1_pb2.py
            test2_pb2.py
test_it.py
```
Which would break other things, if you build for multiple languages (which is a core principle of protobuf)

## Additional context
I can create a github repo with an example on request.

**Comment by anandolee** [comment]
We are doing experiments on relative imports. 
The results show relative imports breaks some of our internal projects and we are still working on it.

**Comment by cromefire** [comment]
That should work:

https://gist.github.com/cromefire/1677b4944458c83cbe566653232eaac9

**Comment by cromefire** [comment]
That's the only place, where some more work might be required:
```python3
some_pb2 = import_from(__file__, "some_pb2", "../../some_pb2.py")
#                                 ^^^^^^^^
```

**Comment by cromefire** [comment]
Method 4 (and 3) would work out of the box with no additional work required

**Comment by erwindassen** [comment]
Any update on this?
