### ISSUE TITLE
build protoc with Link error 2005 in vs2017

### ISSUE THREAD

**Issue by lingerer** [protocolbuffers/protobuf#5384]
**What version of protobuf and what language are you using?**
Version: master/v3.61
**What operating system (Linux, Windows, ...) and version?**
windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
vs 2017
**What did you do?**
using cmake to build,and the protoc will end with link error 2005
this will be solve by switch libprotoc and libprotobuf in link position.
So my suggestion is :
Change protoc.cmake line 6 
target_link_libraries(protoc libprotobuf libprotoc)
to 
target_link_libraries(protoc libprotoc libprotobuf)
**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
@lingerer Do you want to send us a pull request with this fix?

**Comment by lingerer** [comment]
sorry,github is block here.I can't send a fix through clone

**Comment by acozzette** [comment]
This has now been fixed with #5648.
