### ISSUE TITLE
Is protobuf serialized data the same when using different language client and protobuf version?

### ISSUE THREAD

**Issue by xs233** [protocolbuffers/protobuf#5385]
I am working for a http server and it accept a http request which contians the protobuf serialized data in the body. In my mind, I want to use redis as a cache server and the redis key is the protobuf serialized data. So when the new request coming, fiststly, I will search the redis using the protobuf serialized data to check whether it existed. So I want to know whether the protobuf serialized data is the same when the request context is same. Of course,  the protobuf serialized data is also same when using different language client and different protobuf version. I hope someone can help me. Thank you!(My english is poor, hope you can understand it!)

**Comment by acozzette** [comment]
@xs233 As far as I know, implementations are fairly consistent between different languages with respect to their serialized output. However, for other reasons I think it would probably not be a good idea to use serialized protos as cache keys. The main one is that map fields are serialized in an arbitrary order, so even with the same language and the same protobuf message, you can get different serialized outputs. Another problem is that unknown fields are serialized at the end (after all the "known" fields), so you can end up with different results depending on whether a particular field is known to the binary serializing it.

**Comment by xs233** [comment]
@acozzette Thank you for your answer. There is no map field. The reason that I want to use serialized protos as cache keys is because I wanto to reduce the response time without unserializing. The proto I used is in the below.
```
message RequestMsg {
	required int32 fzy = 1; 
	required int32 lang = 2; 
	required int32 mth = 3; 
	required string input = 4; 

	optional int32 length = 5; 
	optional string context = 6; 
}
```

**Comment by acozzette** [comment]
OK, if you're going to use a very simple message like that one then it is probably safe to use as a cache key if you're careful. I would recommend writing your own tests to verify that all the implementations you're using are producing consistent output. And the other thing is that you have to be very careful if you ever add or remove any fields, since that could cause problems with unknown fields being serialized differently.

**Comment by xs233** [comment]
OK. I will do that. Thank you!
