### ISSUE TITLE
python3 protobuf could not work with chinese chars

### ISSUE THREAD

**Issue by chengmengli06** [protocolbuffers/protobuf#5387]
prototxt:
class_map {
  label_name: "驾驶证反面"
}

class_map {
  label_name: "驾驶证正面"
}

proto define:
message DataConfig {
  message ClassMap {
    // marked class
    required string label_name = 1;
    // the class used in tf record
    optional string class_name = 2;
  }
  repeated ClassMap class_map = 4; 
}                

code:
  data_config = DataConfig()
  with open(config_path, 'r') as fin:
    proto_str = fin.read()
    if type('') == type(u''):
      proto_str = proto_str.encode('utf-8')
    text_format.Merge(proto_str, data_config)

**Comment by chengmengli06** [comment]
I test with python3.5 and protobuf 3.6.1

**Comment by chengmengli06** [comment]
python2.7 and protobuf 2.7 could work without any problem. I think protobuf does not take into account the changes in python3.5

**Comment by anandolee** [comment]
Closing it for no response and clean up. Feel free to reopen if needed
