### ISSUE TITLE
AddressBook sample java generated code function with annotation @java.lang.Override

### ISSUE THREAD

**Issue by winnieryl** [protocolbuffers/protobuf#5393]
In the genreated code, there are many functions have annotation @java.lang.Override. However, using the code in eclipse, some of them report error: the method must override a superclass method. Remove the override line would fix the issue and I could run the code successfully. Did I do anything wrong?

**Comment by winnieryl** [comment]
Update: I can compile and run the code using maven. but not in eclipse.

**Comment by BSBandme** [comment]
I guess some of the library is not in the eclipse project library or source.
Are you using maven plugin in eclipse? Can you upload a screenshot for your project files layout?

**Comment by ilhammhdd** [comment]
All my generated java code have this problem too, although i can build it fine using maven

![image](https://user-images.githubusercontent.com/24963809/51970283-1a403800-24a9-11e9-9fd3-c169c824409f.png)
![image](https://user-images.githubusercontent.com/24963809/51970317-317f2580-24a9-11e9-98b4-cfa63207d3b7.png)

**Comment by BSBandme** [comment]
You must included the generated java file from [Descriptors.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto) into your project for your IDE can index your code. 

The maven project generated this file [here](https://github.com/protocolbuffers/protobuf/blob/master/java/core/generate-sources-build.xml#L9) but I think this may not be executed by your IDE. I suggested you generate the jar file from the proto by hand and add the jar into your library path.
