### ISSUE TITLE
Install protoc from a dotnet global tool

### ISSUE THREAD

**Issue by lazarofl** [protocolbuffers/protobuf#5394]
**What language does this apply to?**
dotnet code generation

**Describe the problem you are trying to solve.**

protoc is available on [protoc-version_number-win32.zip](https://github.com/protocolbuffers/protobuf/releases) file
at [releases](https://github.com/protocolbuffers/protobuf/releases), so, I have to download it from github, unzip it on a local directory and add path to environment variables to use it.

So, download and install it without a CLI is a pain in the neck.

**Describe the solution you'd like**

1. protoc could be called from a dotnet global tool, maintaining it's same syntax.
2. Package version could be published based on protoc releases.
3. dotnet global tools works on Windows/Linux/Mac.
4. Include dotnet global tools as an option on [C# tutorial page](https://developers.google.com/protocol-buffers/docs/csharptutorial)

**Describe alternatives you've considered**

Create a script do download the latest version from github using, for example, wget and tar commands and register path on environment variables.
Create a wrapper, as [protobuf-net](https://www.nuget.org/packages/protobuf-net.Protogen/) did, with have older versions of protoc.exe on it`s latest release 👎

**Comment by lazarofl** [comment]
I've created a dotnet global tool that uses the latest `protoc.exe` version as a suggestion for this issue https://github.com/lazarofl/dotnetglobal-protoc

**Comment by lazarofl** [comment]
A good alternative to this approach are chocolatey packages that some friends told me, like https://chocolatey.org/packages/protoc, just run `choco install protoc`, latest versions are available. 👍

**Comment by BSBandme** [comment]
Jie, feel free to reassign to others as I'm not sure who is the right guy to take this.
