### ISSUE TITLE
pedantic compiler error

### ISSUE THREAD

**Issue by bansalnvn** [protocolbuffers/protobuf#5395]
**What version of protobuf and what language are you using?**
Version: master.
Language: C++

**Linux centos7**

**gcc-7**

** C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
external/com_google_protobuf/src/google/protobuf/stubs/common.cc:299:2: error: extra ';' [-Werror=pedantic]
 };
**

**Comment by BSBandme** [comment]
For Josh, I'm not sure but maybe are this two functions:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/common.cc#L285-L291

**Comment by haberman** [comment]
Please feel free to send a PR to delete the extra semicolons.
