### ISSUE TITLE
reload a proto file

### ISSUE THREAD

**Issue by chenfeng345** [protocolbuffers/protobuf#5399]
Loading a proto，how to reload this proto file after a hot update

**Comment by chenfeng345** [comment]
version 2.5.0，please let me know，thanks

**Comment by acozzette** [comment]
@chenfeng345 There's no built-in support for rebuilding the generated code from a proto file when it changes.

**Comment by chenfeng345** [comment]
@acozzette Thank you for your answer, I think I have a little thought.

**Comment by chenfeng345** [comment]
> @chenfeng345 There's no built-in support for rebuilding the generated code from a proto file when it changes.

Thank you for your answer, I think I have a little thought.
But，how can memory be overloaded, what interface can be called?

**Comment by BSBandme** [comment]
Sorry but I didn't fully get your question. Are you referring to regenerating the code after proto file changed?

**Comment by chenfeng345** [comment]
Yes，I mean what interface can be called to regenerate the code and reload after the original file is changed.

**Comment by chenfeng345** [comment]
> Sorry but I didn't fully get your question. Are you referring to regenerating the code after proto file changed?

Yes，I mean what interface can be called to regenerate the code and reload after the original file is changed.

**Comment by chenfeng345** [comment]
I am using the C++ version. Is there any way to deal with it?
