### ISSUE TITLE
C++ send float or double data to nodejs not correct

### ISSUE THREAD

**Issue by webbery** [protocolbuffers/protobuf#5400]
Hi,
I use following proto file:  
```
syntax = "proto3";

enum MsgType{
    NoneType = 0;
    SlamResult = 1;
}
message SlamPos{
    double x = 1;
    double y = 2;
    double z = 3;
}

message LogInfo{
    MsgType type = 1;
    SlamPos pos = 2;
}
```
In C++ I set `pos` value is:  
```
SlamPos* pos = logInfo.mutable_pos();
pos->set_x(1); pos->set_y(3); pos->set_z(2);
```
But in electron I recieve like this:  
![default](https://user-images.githubusercontent.com/5257853/49060155-358f8c80-f247-11e8-9298-ec43fe2360f4.png)
So the value is different bettewn C++ and js. Is it a bug?  I use electron 2.0.7 and os is window10 64bit

**Comment by BSBandme** [comment]
Would you please provide more information on electron side? Like how did you parse the message in electron?

**Comment by webbery** [comment]
Well, I know how this problem occours. I use nanomsg to recieve data. But the socket is set `sock.setEncoding('utf8');`. So when I remove it all works right.  
But I'm not sure it works if I pass utf8 string.
