### ISSUE TITLE
Why isn't Java's Any.class an inner class of AnyProto.class?

### ISSUE THREAD

**Issue by mulho** [protocolbuffers/protobuf#5405]
Inspecting `any.proto`, one can see the following option: 
`option java_outer_classname = "AnyProto";`
Why then isn't `Any.class` an inner class of `AnyProto` in protobuf-java-x.x.x.jar (This is true at least for versions 3.2.0 and 3.6.1)?

Context:
The reason of this question is that I'm using `avro-protobuf` to convert an avro message into Protobuf, and this library looks at the Protobuf schema FileDescriptor to find out the Protobuf class that it needs to instantiate. When looking for Any's file descriptor, this library tries to instantiate com.google.protobuf.AnyProto$Any, because of the java_outer_classname mentioned above. And it looks to me the library is doing the right thing. Here is the code that relies on this metadata to instantiate the class: https://github.com/apache/avro/blob/2bbb99602e9e925058ead86fc8ac4e27055b05d6/lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java#L225

**Comment by BSBandme** [comment]
Please refer to [the guide](https://developers.google.com/protocol-buffers/docs/proto3#options) for java_multiple_files option:
> **java_multiple_files** (file option): Causes top-level messages, enums, and services to be defined at the package level, rather than inside an outer class named after the .proto file.

So the **Any** message is just under the package level.

**Comment by mulho** [comment]
Thanks @BSBandme for the prompt response. 
In this case, what's the point of defining a **java_outer_classname**? If there's no outer class when **java_multiple_files** is used, then probably we shouldn't have **java_outer_classname** if the former is used, right?
Thanks
