### ISSUE TITLE
Is protobuf support mips

### ISSUE THREAD

**Issue by wananhsn** [protocolbuffers/protobuf#5408]
when I was cross-compiling for mips-openwrt-linux，I encounter an error showing below.   It seems that protobuf  using an opcode which was not supported by my compiler with mips1 opcode.  Could I add some configurations to fix this or it just means I can't use protobuf with mips device ? 

Error:
libtool: compile:  /home/wangyao/lw1301/chaos_calmer/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -I/home/wangyao/lw1301/chaos_calmer/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/stubs/common.lo -MD -MP -MF google/protobuf/stubs/.deps/common.Tpo -c google/protobuf/stubs/common.cc  -fPIC -DPIC -o google/protobuf/stubs/.libs/common.o
/tmp/ccFggNXK.s: Assembler messages:
/tmp/ccFggNXK.s:1236: Error: opcode not supported on this processor: mips1 (mips1) `sync'
/tmp/ccFggNXK.s:5978: Error: opcode not supported on this processor: mips1 (mips1) `sync'
/tmp/ccFggNXK.s:7005: Error: opcode not supported on this processor: mips1 (mips1) `sync'
/tmp/ccFggNXK.s:7765: Error: opcode not supported on this processor: mips1 (mips1) `sync'
/tmp/ccFggNXK.s:8409: Error: opcode not supported on this processor: mips1 (mips1) `sync'
make[2]: *** [google/protobuf/stubs/common.lo] Error 1
make[2]: Leaving directory `/usr/local/protobuf/protobuf-3.4.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/protobuf/protobuf-3.4.0'
make: *** [all] Error 2

**Comment by wananhsn** [comment]
fix by add  CXXFLAGS="-D__MIPSEL__ -march=mips32" ，thanks at all

**Comment by vudinhlong4** [comment]
> fix by add CXXFLAGS="-D__MIPSEL__ -march=mips32" ，thanks at all
add to file??
you make it more clear??
