### ISSUE TITLE
Unable to extract protobuf-all-3.6.1.tar.gz 

### ISSUE THREAD

**Issue by hammer43** [protocolbuffers/protobuf#5411]
Hi, there I tried to install protobuf version 3.6.1 as I needed math/bits in the go protobuf version. When I used tar- I have the following message: 

test:~$  tar -xvzf protobuf-all-3.6.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
test:~$

thanks in anticipation,

**Comment by tim401** [comment]
the file was probably corrupted, perhaps while downloading.
I don't quickly see a hash file to verify the download, but the easiest way is to try downloading the file again. If that doesn't work, give some more details on your system.
