### ISSUE TITLE
ParsePartialFromArray  Chinese cannot be parsed

### ISSUE THREAD

**Issue by bitxx** [protocolbuffers/protobuf#5413]
Some doubts about the failure of "ParsePartialFromArray" Chinese unpacking?

My file is written like this.

```
Syntax = "proto3";

Package SocketData;

Message CmdRequest
{
string Content = 1;
}

Message CmdResponse
{
Bool state = 1;
}
```

Only non-Chinese characters can now be sent.

Parsing fails for Chinese characters.

**Comment by BSBandme** [comment]
Would you please provide programming languages used for parsing and serialization?

**Comment by X-Crack** [comment]
类型  string 不支持中文发送

只有bytes 才支持中文发送。

**Comment by acozzette** [comment]
@X-Crack What encoding are you using? `string` fields are required to be valid UTF-8, so that could be the problem if your text is in a different encoding.

**Comment by deannagarcia** [comment]
Closing due to no response, feel free to reopen if you still have this issue.
