### ISSUE TITLE
JsonStringToMessage incorrectly rejects lowerCamelCase field names

### ISSUE THREAD

**Issue by wd40bomber7** [protocolbuffers/protobuf#5414]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2017, x86 and x64 toolchains

**What did you do?**
1. Create a .proto file with an object with PascalCase fields
2. Build .proto file into C++
3. In C++ call JsonStringToMessage with a snippet of JSON which uses lowerCamelCase fields instead of PascalCase
4. Protobuf fails with "Cannot find field" error after failing to match the lowerCamelCase field in the JSON to the pascal case in the type descriptor.

**What did you expect to see**

The JSON mapping section on the protobuf guide [here](https://developers.google.com/protocol-buffers/docs/proto3#json) states **"Message field names are mapped to lowerCamelCase and become JSON object keys. ... Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name."**

**What did you see instead?**

The C++ parser does not accept the lowerCamelCase name in fields as it should.

**Comment by wd40bomber7** [comment]
Its been a long time and looking at the change list it looks like a lot of C++ changes have gone in. Does anyone know if this was fixed at some point?

**Comment by wd40bomber7** [comment]
It has been a couple years and a huge number of major versions and this issue still happens in 3.12.2 will anyone ever actually fix this?

**Comment by acozzette** [comment]
@wd40bomber7 Could you post an example .proto file where you have this problem? We have some tests (e.g. [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/json_util_test.cc#L207)) verifying that lowerCamelCase is accepted, so it appears to be working at least in that case.

**Comment by wd40bomber7** [comment]
@acozzette You have only to look at Yury's pull request above to see a test that causes this issue to happen (without his accompanying fix).

See his changes to json_util_test.cc here: https://github.com/protocolbuffers/protobuf/pull/5473/files

If you added that test today it would fail because Protobuf's implementation of casing is not to spec in C++. 

I quoted this in the original issue but I'll quote the passage again here. This is taken directly from the docs: **"Message field names are mapped to lowerCamelCase and become JSON object keys. ... Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name."** 

The problem is that if your message fields are defined in PascalCase the fields are not correctly mapped to lowerCamelCase and do not accept lowerCamelCase message fields.

**Comment by acozzette** [comment]
I think part of the problem here is that we always use `snake_case` field names as per the .proto file style [guide](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names) and therefore don't have any test coverage for how the JSON mapping works with `PascalCase` field names. I talked to some other protobuf team members and learned that using non-`snake_case` field names causes other problems including not working with `FieldMask`. So unfortunately I'm afraid there may be no good solution to this other than to stick with `snake_case` field names.

**Comment by wd40bomber7** [comment]
I don't think that makes sense. I have no idea why a style guide would trump the language spec. Especially since the behavior I'm describing is called out multiple times in the official protobuf 3 documentation.

No where does it mention that you must use snake_case to get correct protobuf behavior. In fact snake case isn't mentioned anywhere. "lowerCamelCase" is mentioned but only to explain that all fields are mapped to lowerCamelCase before serialize/deserialize which isn't true.

Why isn't the right answer just to merge the provided fix? It has some conflicts but they should be easily resolved. **I am willing to do it if the change will actually be merged in.**

As for the documentation please read these sections from [here.](https://developers.google.com/protocol-buffers/docs/proto3)

Under "JSON Mapping":

> Generates JSON objects. Message field names are mapped to lowerCamelCase and become JSON object keys. If the `json_name` field option is specified, the specified value will be used as the key instead. Parsers accept both the lowerCamelCase name (or the one specified by the `json_name` option) and the original proto field name

Under "JSON Options":

> Use proto field name instead of lowerCamelCase name: By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name. An implementation may provide an option to use proto field name as the JSON name instead. Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.

**Comment by acozzette** [comment]
This is a tricky situation because the behavior is determined by the `json_name` option, which is automatically generated by `protoc` if it is not explicitly set. Currently when protoc is given an `UpperCamelCase` field name it will just generate a `json_name` of `UpperCamelCase`. If we changed this behavior then it would affect essentially all implementations at once, since they all rely on `json_name`. But it is hard to know if that would be a safe change. If pretty all much implementations disagree with the spec, then it may make more sense to update the spec than to update every implementation.

**Comment by wd40bomber7** [comment]
The implementations should not rely on json_name alone. 
The spec says:

> By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name.

> Proto3 JSON parsers are required to accept **both** the converted lowerCamelCase name and the proto field name.

So json_name should be the lowerCamelCase of the proto field name, and when mapping a key both the field name and the json_name should be checked. Implementations which aren't checking both are clearly wrong and should be corrected. Do we know what implementations this actually affects?

**Comment by acozzette** [comment]
I think the problem is that json_name is generated by protoc (unless it's specified explicitly), and the way protoc's logic is written, it works correctly for `snake_case` names but leaves `CamelCase` names unchanged. So protoc will produce these incorrect json_name values and then all implementations will rely on those.

From what I understand, the problem is not that implementations are ignoring `json_name`. They are respecting `json_name` but they're being fed an incorrect value from protoc.

**Comment by wd40bomber7** [comment]
1+ year later and this bug still exists. The official protobuf 3 documentation still has this incorrect line in it:
". Message field names are mapped to lowerCamelCase and become JSON object keys. If the json_name field option is specified, the specified value will be used as the key instead. Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name. null is an accepted value for all field types and treated as the default value of the corresponding field type."

This is not true because if your original field is named in PascalCase, the parser will not accept lowerCamelCase. Can we really not accept the PR (after adjustment to the current codebase)?

**Comment by oceanliketheocean** [comment]
We ran into this problem on our pubsub push subscriptions after migrating to Google Cloud Run. [Others are having the same issue](https://stackoverflow.com/questions/68490891/google-cloud-platform-push-subscription-sending-duplicate-message-id-fields). I understand not wanting to disrupt existing implementations by changing default behavior, but the solution proposed seems it would help resolve issues like this.

**Comment by thxkiwi** [comment]
Looking for any update on this topic. Not that I've run into the problem, but I don't want to run into the problem and am currently specifying work to be in a project that utilizes JsonStringToMessage for deserialization of JSON (on disk) to protobuf message (in memory).
