### ISSUE TITLE
Inconsistent behaviour when FileDescriptorProto is missing custom extensions dependencies 

### ISSUE THREAD

**Issue by vishen** [protocolbuffers/protobuf#5415]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Java
**What operating system (Linux, Windows, ...) and version?**
Linux jonathan 4.15.0-39-generic 42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
We have a tool where we create a [FileDescriptorProto](https://github.com/protocolbuffers/protobuf/blob/704037f23a9ede00ec4fcf40d568712ce6200934/src/google/protobuf/descriptor.proto#L61) manually and then pass that to `protoc --python_out=. --descriptor_set_in=/dev/stdin all.proto` via stdin.

When using the google api annotations as custom extensions on the `MethodOptions` which are options for `MethodDescriptorProto`, we were not adding the `google/api/annotations.proto` dependency.

When running the protoc generator for Python, or any language other than Java, protoc succeeds. However, when we run it for the Java generator `--java_out=`, it generates this error:

```
[libprotobuf FATAL ../../../../../src/google/protobuf/compiler/java/java_file.cc:129] CHECK failed: file_proto_desc: Find unknown fields in FileDescriptorProto when building all.proto. It's likely that those fields are custom options, however, descriptor.proto is not in the transitive dependencies. This normally should not happen. Please report a bug.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file_proto_desc: Find unknown fields in FileDescriptorProto when building all.proto. It's likely that those fields are custom options, however, descriptor.proto is not in the transitive dependencies. This normally should not happen. Please report a bug.
```

Then when I add the missing dependency, everything works fine.

I realise that this was an error on our behalf, but there seems to be some inconsistency between Java and the other generators in protoc when it comes to missing dependencies for custom extensions / options. I am just curious as to what the expected behaviour should be; 

1) should protoc error if custom extensions dependencies are missing
2) protoc should ignore custom extensions when generating code

**Comment by BSBandme** [comment]
Hi Would you please provide a concrete example that shows the behavior difference between java and other languages?

**Comment by vishen** [comment]
This is the best example I can give at the moment sorry. This a `FileDescriptorProto` that has been encoded into the wire format. It has custom extensions attached to the `MethodOptions` but it is missing the actual dependency of those custom extensions:

```
 $ cat proto_file_descriptor 


        all.protoutiloogle/protobuf/empty.proto"O
Message
Msg (   B
(0PRmsg
Code (B
(0PRcode"e
CheckStatusResponse(
Status (2
         .util.StatusB
(0P
OldField (B
(0P*8
Status
Unknown
Error

O2
Util?
:*/v1/echoXge"

CheckStatus.google.protobuf.Empty.util.CheckStatusResponse"
/v1/echoBHPZutilJ
essage is a Echo message.


Msg holds a message.

(
"Status is a server health status.


Status_

Status_

Status_
>
8CheckStatusResponse is the response for a check status.

%
+gunk field.Deprecated(true)


Echo echoes a message.
3
+CheckStatus sends the server health status.bproto3

#github.com/gunk/opt/field/all.protofieldB HPZfieldJs
#
Packed is the packed option.


Lazy is the lazy option.

+
%Deprecated is the deprecated option.
bproto3

"github.com/gunk/opt/http/all.protohttp"_
Match
Method (        B
(0P
Path (  B
(0P
Body (  B
(0PBHPZhttpJl
?
:Package http provides the http matching options for gunk.

)
#Match is the http matching option.
bproto3

%github.com/gunk/opt/service/all.protoserviceB"HPZserviceJ-
+
%Deprecated is the deprecated option.
bproto3

oogle/protobuf/empty.protogoogle.protobuf"
EmptyBv
com.google.protobufB
EmptyProtoPZ'github.com/golang/protobuf/ptypes/emptyGPBGoogle.Protobuf.WellKnownTypesbproto3
$ protoc --descriptor_set_in=proto_file_descriptor --python_out=. all.proto
$ protoc --descriptor_set_in=proto_file_descriptor --java_out=. all.proto
[libprotobuf FATAL ../../../../../src/google/protobuf/compiler/java/java_file.cc:129] CHECK failed: file_proto_desc: Find unknown fields in FileDescriptorProto when building all.proto. It's likely that those fields are custom options, however, descriptor.proto is not in the transitive dependencies. This normally should not happen. Please report a bug.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file_proto_desc: Find unknown fields in FileDescriptorProto when building all.proto. It's likely that those fields are custom options, however, descriptor.proto is not in the transitive dependencies. This normally should not happen. Please report a bug.
fish: “protoc --descriptor_set_in=prot…” terminated by signal SIGABRT (Abort)
$ protoc --descriptor_set_in=proto_file_descriptor --csharp_out=. all.proto
```

**Comment by Tauta2** [comment]
_Sent from my Pixel 3 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vishen** [comment]
I have created a test repo in Go that reproduces this. I am not sure if that helps, but the repo is https://github.com/vishen/protoc-break-java

**Comment by mkruskal-google** [comment]
I'm going to close this given how much has changed since 2018.  If this is still an issue in 21.x or later please reopen this bug
