### ISSUE TITLE
vs2017 15.9.3 c++ 17 标准编译不通过

### ISSUE THREAD

**Issue by X-Crack** [protocolbuffers/protobuf#5416]
protobuf 版本：3.6.1

错误提示： C4996: 'std::iterator<std::random_access_iterator_tag,Element,ptrdiff_t,_Ty*,_Ty&>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by acozzette** [comment]
@X-Crack Thanks for reporting this, would you be interested in sending us a pull request to replace `std::iterator`?

**Comment by X-Crack** [comment]
> @X-Crack Thanks for reporting this, would you be interested in sending us a pull request to replace `std::iterator`?

什么意思？

帮你们修复bug吗？
