### ISSUE TITLE
What is the proper way to clean memory in python

### ISSUE THREAD

**Issue by senhui-guo** [protocolbuffers/protobuf#5417]
I use protobuf as a data structure, and I have a class containing a list of protobuf message. However when I delete the instance of the class, the memory won't be released, deleting the message in list won't help either, gc.collect() doesn't do much. The interesting thing is that when I reconstruct an instance, the memory won't go up, looks like the protobuf is reusing the memory. So I was wondering what is the proper way to release the memory?

My test code:
```python
class DataInterface():
    def __init__(self):
        self.data = [DataStructure_pb2.Data() for idx in range(10000)]

di = DataInterface() # memory went up
del di                         # memory won't release
di = DataInterface() # memory didn't go up
```

Thanks a lot

**Comment by anandolee** [comment]
Are you using pure python or cpp extension?

**Comment by senhui-guo** [comment]
Looks like I'm using cpp extension.
I installed protobuf through anaconda, does it come as cpp by default?

**Comment by senhui-guo** [comment]
On the other hand, I figured protobuf should be used as a portal to serialize/parse the messages, so currently I implement another python class to build the message from the protobuf object, and the memory won't be a problem anymore. I guess that's what protobuf is intended to do.
