### ISSUE TITLE
Latest release broken when building with Bazel at HEAD

### ISSUE THREAD

**Issue by allevato** [protocolbuffers/protobuf#5418]
**What version of protobuf and what language are you using?**
Version: v3.6.1.1

**What operating system (Linux, Windows, ...) and version?**
Any

Bazel at HEAD has removed the deprecated `REPOSITORY_NAME` and `PACKAGE_NAME` globals, but v3.6.1.1 still refers to them despite [this change in May (4fcb36c51c1c0355c2a23b1f06ec583f2428cd30)](https://github.com/protocolbuffers/protobuf/commit/4fcb36c51c1c0355c2a23b1f06ec583f2428cd30#diff-14e64c3c0a0449ceb162062b8291fa19) that migrated to the new APIs. Thus, `protobuf.bzl` fails with an error when trying to import protobuf into a workspace.

Here's an example of a failure this is causing: https://travis-ci.org/bazelbuild/rules_swift/jobs/458163286

Can we please have a new release that includes 4fcb36c51c1c0355c2a23b1f06ec583f2428cd30?

**Comment by acozzette** [comment]
This issue should now be fixed in the 3.6.1.2 patch release and the fix will also be included in the upcoming 3.7 release.

**Comment by allevato** [comment]
Thank you! I've verified that v3.6.1.2 resolved the issue for us.
