### ISSUE TITLE
osx build configure: could not determine ar interface

### ISSUE THREAD

**Issue by ph4r05** [protocolbuffers/protobuf#5426]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
OSX 10.14.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**What did you do?**
unpack
`./configure`

**What did you expect to see**
Success

**What did you see instead?**
```
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ar... ar
checking the archiver (ar) interface... unknown
configure: error: could not determine ar interface
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
-

**Comment by acozzette** [comment]
That error makes it sound like there must be something wrong with your build environment. You could also try building with CMake and see if that makes a difference.

**Comment by acozzette** [comment]
I'm going to close this issue since it sounds like an unusual occurrence and since the CMake build exists as a workaround. If we get any other similar reports then we can reopen it and try to figure out what's going on.

**Comment by anwarhahjjeffersongeorge** [comment]
In 2019 on OS X 10.15 (Catalina), this still seems to happen using brew-installed GNU linker tools, although. A workaround to use the Apple tools is to run

    ./configure AR=/usr/bin/ar RANLIB=/usr/bin/ranlib

This fix made it possible to get a working `protoc` installed as well as build other libraries dependent on this one. 

However, also bear in mind that it was stated above:

> That error makes it sound like there must be something wrong with your build environment. 

...so this solution might only apply to corrupted build environments.
