### ISSUE TITLE
Are the 3.6.1.x patch releases real release?

### ISSUE THREAD

**Issue by xhochy** [protocolbuffers/protobuf#5439]
Possibly the same as https://github.com/protocolbuffers/protobuf/issues/3302 but as the visuals are a bit confusing, I'm asking for clarity again. 

Are those patch releases considered real releases? They are only tags on GitHub and not marked as arelease. Also there are no packages on PyPI for it. We want to update the `conda-forge` package but unsure whether we should really do this.

**Comment by acozzette** [comment]
No, these are not exactly real releases, but we just cherry-picked some fixes primarily to unblock the Bazel 0.20 release. We are working on a 3.7 release, though, and that will be a real release with all the usual published build artifacts.
