### ISSUE TITLE
Segfault in Python protos using map

### ISSUE THREAD

**Issue by robertwb** [protocolbuffers/protobuf#5443]
**What version of protobuf and what language are you using?**

protobuf==3.6.1 (though I've seen it in 3.5.x as well). 

Language: Python

**What operating system (Linux, Windows, ...) and version?**

Linux, Debian. (Doesn't happen on mac.)

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 2.7.13

**What did you do?**

--- simple.proto ---

```
syntax = "proto3";

message Simple {
  string value = 1;
  string data = 2;
  map<string, string> more_data = 3;
  map<string, string> even_more_data = 4;
}

message SimpleMap {
  map<string, Simple> values = 1;
}

// Yes, this seems to be needed.
message SimpleMapHolder {
  SimpleMap map = 1;
}

```
--- run_test.py --- 

```
import logging

import simple_pb2

logging.warn('start')
proto_map = simple_pb2.SimpleMap()
proto_map.values['a'].value = 'aaa'
value = proto_map.values['a']
proto_map.values.clear()
proto_map.values['a'].CopyFrom(value)
logging.warn('done')
print(proto_map)

# Yes, this makes it more likely. Heap curruption?
for _ in range(1000, 1100):
  pass

```

--- now run ---

```
python -m grpc_tools.protoc -I. --python_out=. simple.proto
python run_test.py
python run_test.py
python run_test.py  # may take three tries, but usually exactly two

```

**Comment by anandolee** [comment]
For python c extension, looks like we are missing clear() method for map reflection and is using repeated field to sync and then do the clear:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/generated_message_reflection.cc#L869

I will add clear method in map refletion.
