### ISSUE TITLE
Add compiler plugin for Maven

### ISSUE THREAD

**Issue by kevinhwang** [protocolbuffers/protobuf#5444]
Currently there's no official Maven plugin for compiling protobuf files. There appears to be one for Gradle. Could you guys add one for Maven?

**Comment by BSBandme** [comment]
Currently protoc only have cpp version, I think this improvement need to create a java version protoc which may not be done in the near future.

**Comment by BSBandme** [comment]
Sorry that I just learnt that we already have protoc artifacts in maven central distinguished by different platforms classifiers:
https://search.maven.org/artifact/com.google.protobuf/protoc/3.6.1/pom

I'm not sure whether this works for you. If not, would you please give more details on your case?

**Comment by panchenko** [comment]
http://os72.github.io/protoc-jar-maven-plugin/ ?

**Comment by kevinhwang** [comment]
> I'm not sure whether this works for you. If not, would you please give more details on your case?

Ah we recently decided not to use Protocol Buffers in our project, so never got a chance to try out that plugin.
