### ISSUE TITLE
version v3.6.1.3 fails to compile on Linux, version.rc issue

### ISSUE THREAD

**Issue by shardator** [protocolbuffers/protobuf#5448]
**What version of protobuf and what language are you using?**
Version: v3.6.1.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10)

**What did you do?**

Simply ran CMake build.

**What did you expect to see**

Build successful. :)

**What did you see instead?**

Build fail:

```
==> Processing plain cmake package: 'protobuf-dev'
==> Building with env: '/home/odroid/cscsatho/catkin_ws/install_isolated/env.sh'
==> cmake /home/odroid/cscsatho/catkin_ws/src/protobuf-dev -DCMAKE_INSTALL_PREFIX=/home/odroid/cscsatho/catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release -G Ninja in '/home/odroid/cscsatho/catkin_ws/build_isolated/protobuf-dev/install'
-- Configuring done
CMake Error at cmake/protoc.cmake:9 (add_executable):
  Cannot find source file:

    /home/user/catkin_ws/build_isolated/protobuf-dev/install/cmake/version.rc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/CMakeLists.txt:210 (include)


-- Generating done
-- Build files have been written to: /home/odroid/cscsatho/catkin_ws/build_isolated/protobuf-dev/install
<== Failed to process package 'protobuf-dev': 
  Command '['/home/odroid/cscsatho/catkin_ws/install_isolated/env.sh', 'cmake', '/home/odroid/cscsatho/catkin_ws/src/protobuf-dev', '-DCMAKE_INSTALL_PREFIX=/home/odroid/cscsatho/catkin_ws/install_isolated', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Ninja']' returned non-zero exit status 1
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**NOTE**: I successfully fixed it by cherry-picking the commit `291d9a0ab0b452537d22a81b551eaea53fd157a8` (*Fix issue with version.rc*) from the `master` branch.

**Comment by davido** [comment]
May be it worth upload a PR and ask to merge it and release v3.6.1.4?

**Comment by shardator** [comment]
Hi David,

I've never created a pull request before. So should I create some hotfix branch, push it, and create the pull req?

Thanks,
   Gergely

**Comment by davido** [comment]
@shardator Yeah, check my recent PR https://github.com/protocolbuffers/protobuf/pull/5433. You want to push it to protocolbuffers:3.6.x branch.

**Comment by shardator** [comment]
@davido: but how do you push the new branch to github to create a pull request? I created a branch locally on my computer, added my ssh keys and tried to push the new branch, but failed:

```
git push github fixed-version.rc-v3.6.1.4:fixed-version.rc-v3.6.1.4
ERROR: Permission to protocolbuffers/protobuf.git denied to shardator.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

while the remote I'm trying is `git@github.com:protocolbuffers/protobuf.git`

**Comment by shardator** [comment]
@davido Thanks. Sent pull request.

**Comment by dtarakanov1** [comment]
It's half a year since the PR was sent, but I still cannot find v3.6.1.4.
Can anybody add the tag?

**Comment by elharo** [comment]
3.6.1.3 not supported, reopen/comment if this is till an issue at head
