### ISSUE TITLE
How can I turn google struct to javascript?

### ISSUE THREAD

**Issue by wzkun** [protocolbuffers/protobuf#5458]
I send message to golang with google protobuf ,like: 'let response = await this.cli.addMultiAsync(req, this.cli.meta);'.
And I usually use response.toObject() to get value. But the value is like 'filedmaps[string, any][]'.
So, how can I turn the response to simple javascript'

**Comment by BSBandme** [comment]
Would you please provide the response's type schema?  
And would you please elaborate on "simple javascript"?

**Comment by wzkun** [comment]
I use getmulti api to get multi from golang by grpc,and the original response, And I usually use response.toObject() to get value.
The value is like :
{ fieldsMap:
        [ [ 'createTime',
            { nullValue: 0,
              numberValue: 0,
              stringValue: '2018-12-12T17:54:30.723+08:00',
              boolValue: false,
              structValue: undefined,
              listValue: undefined } ],
          [ 'region',
            { nullValue: 0,
              numberValue: 0,
              stringValue: '',
              boolValue: false,
              structValue:
               { fieldsMap:
                  [ [ 'cnName',
                      { nullValue: 0,
                        numberValue: 0,
                        stringValue: 'name',
                        boolValue: false,
                        structValue: undefined,
                        listValue: undefined } ] ] },
              listValue: undefined } ]          
           ] }.
What I want is like :
          { 
			'createTime':'2018-12-12T17:54:30.723+08:00',
			'region':
            { 'cnName':'name'}
		}

**Comment by BSBandme** [comment]
Sorry but I can't figure out the main details without response proto definition. What's the response proto message looks like? I think that would be simiple for just get the createTime's string value to fulfill your requirement.
