### ISSUE TITLE
Proposal: Allow text format parser to accept unknown fields

### ISSUE THREAD

**Issue by zunger-humu** [protocolbuffers/protobuf#5465]
**What language does this apply to?**
All languages. There is already an existing issue (https://github.com/protocolbuffers/protobuf/issues/4821) for doing this just in C++, but it's just as useful everywhere else. (My personal interest is primarily in Python right now)

**Describe the problem you are trying to solve.**
Handling unknown fields is an important part of the proto deserializer, and occasionally it's useful to apply the same behavior to text-serialized protos. (For example, I have one data store which stored protos as text to aid debuggability, but since certain fields no longer exist, it's no longer possible to parse them at all!)

**Describe the solution you'd like**
Add an option to the text-format merge function in each language to ignore unknown fields, which would simply skip those instead of failing with a parse error.

**Describe alternatives you've considered**
Short of copying and forking all of the text format logic, there's not much else to do. I can't even read the old files, modify them, and write them back easily, since I can't use the proto parser to parse the old files at all.

**Additional context**
I'd be happy to submit a pull request for the Python version of this change, if the API is agreed upon.

**Comment by zunger-humu** [comment]
(I can't tell from @xfxyjwf 's comment on #4821 whether this already exists in all languages in the internal codebase and just awaits exposure, or if it only exists in C++. But that issue has been idle since June, and the proposed PR to do it in C++ seems to have been abandoned in favor of the internal codebase change at Feng's request. So maybe we can resurrect this issue now?)

**Comment by zunger-humu** [comment]
Thus my suggestion that this be an option, rather than default behavior. :)
'allow_unknown_fields' could (and should) have a clear warning on it, but
there are legit reasons to use this for storage. (At least in my case, it's
because I'm working with people who came from a JSON world and are very
leery of having a core config file not be instantly readable from the GCP
UI without tools. Which isn't a terrible thing, really; I've found it handy
in debugging more than once, myself)

**Comment by SumitVijay** [comment]
One use case:
we persist proto objects on disks and use them to build state upon restart of the app.
In case we need to rollback app version to old version, then we can not build the state back.

**Comment by zunger-humu** [comment]
This issue just came up for me again, and it's no less relevant than it was before. Can we please do this? It's increasingly difficult to work around this lack of a feature.

**Comment by acozzette** [comment]
Starting from 3.8 this is now supported in Python and C++.

**Comment by nareddyt** [comment]
@acozzette could you clarify if this is supported by default in `TextFormat::Parse`, or do we have to use `Merge`? I took at the release notes for 3.8.0, but did not see any mention of this.

**Comment by acozzette** [comment]
@nareddyt For C++ you can create a `TextFormat::Parser` and call `AllowUnknownField(true)` on it before using it. Check out text_format_unittest.cc for an example.
