### ISSUE TITLE
New zlib dependency breaks protobuf as an external bazel repository

### ISSUE THREAD

**Issue by mumbleskates** [protocolbuffers/protobuf#5472]
**What version of protobuf and what language are you using?**
Version: master
Language: Bazel/any

**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
bazel 0.20.0

**What did you do?**
Have the following rule in another repository's WORKSPACE file:

    local_repository(
        name = "com_google_protobuf"
        path = "path/to/protobuf"
    )

...then run `bazel build` on a target that depends upon anything in `com_google_protobuf//...`

**What did you expect to see**
Expected to see it work as it did before the inclusion of the zlib http_archive.

**What did you see instead?**
`ERROR: /home/mumbleskates/.cache/bazel/_bazel_mumbleskates/0123456789abcdef0123456789abcdef/external/com_google_protobuf/BUILD:132:1: no such target '//external:zlib': target 'zlib' not declared in package 'external' defined by /home/mumbleskates/repos/projectname/WORKSPACE and referenced by '@com_google_protobuf//:protobuf'`

Essentially, protobuf can no longer be used as an external dep e.g. as a submodule unless we make a fragile copy of the zlib http_archive repo in our own WORKSPACE file.

**Anything else we should know about your project / environment**
This was working at 81c3e0cf, for example, but now that protobuf has an external dependency on another bazel repo, rather than including the dependencies in its own files or cloned into a submodule, this becomes difficult and frustrating.

I feel that a good fix to this issue might be to clone zlib at a desired commit into a submodule and reference it as a package instead of a separate bazel repository. This avoids the requirement that everyone who references _this_ repository needs to know about, and maintain the correct version of in their own rules, every dependency so declared.

**Comment by acozzette** [comment]
@mumbleskates Thanks for filing this issue. I was wondering if we would run into problems like this when we added the zlib dependency. I can see the rationale for cloning zlib into a submodule, but on the other hand that would make life harder for projects that use protobuf and also independently use zlib. Those projects would then have ODR violations from linking against two copies of zlib.

I have heard that some projects get around these issues by providing a Starlark function that returns all the necessary dependencies. Would it solve your problem if we provided a function like this that you could call?

**Comment by mumbleskates** [comment]
Yes, that'd probably be an ideal solution, I'd appreciate it!

**Comment by vgrippa** [comment]
Im hitting the same issue:

`[root@node1 mysql-ripple]# bazel build :all
INFO: Invocation ID: 04db38db-7d93-4dea-85f1-8a5692155398
ERROR: /root/.cache/bazel/_bazel_root/f72efea5e38ade09d769d0401ec2ea17/external/com_google_protobuf/BUILD:130:1: no such target '//external:zlib': target 'zlib' not declared in package 'external' defined by /git/mysql-ripple/WORKSPACE and referenced by '@com_google_protobuf//:protobuf'
ERROR: Analysis of target '//:management_proto' failed; build aborted: Analysis failed`

**Comment by mumbleskates** [comment]
This is now fixed in master branch; you can load @com_google_protobuf//:protobuf_deps.bzl and call the function there to create the zlib dependency in another workspace.

**Comment by Vincent-M** [comment]
Thanks! The `protobuf_deps.bzl` file seems to be missing from Protocol Buffers v3.7.1 (https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-all-3.7.1.zip), is it going to be part of the next release?

**Comment by mumbleskates** [comment]
I hope so, too

**Comment by mumbleskates** [comment]
Looks like it's arriving in 3.8, it's in the RC branch right now.
