### ISSUE TITLE
Where is the pre-built binary for 3.6.1 java protoc compiler?

### ISSUE THREAD

**Issue by khteh** [protocolbuffers/protobuf#5476]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
JAVA
**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.10
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc-8.2.0
**What did you do?**

**What did you expect to see**
protoc pre-built binary in the downloaded release protobuf-java-3.6.1.tgz
**What did you see instead?**
Nothing. Just a bunch of source codes.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by MarcoH1986** [comment]
Separate download, at the bottom of each release 

https://github.com/protocolbuffers/protobuf/releases

![image](https://user-images.githubusercontent.com/10659875/50093942-444bdc80-0212-11e9-9daa-596faf721bf0.png)

**Comment by TeBoring** [comment]
https://mvnrepository.com/artifact/com.google.protobuf/protoc/3.6.1
I think we had released it.
