### ISSUE TITLE
Why download needs a moma account

### ISSUE THREAD

**Issue by weisy11** [protocolbuffers/protobuf#5483]
I clicked Ubuntu C++ installation, and it leads me to a login webpage. which says
Use your SSO username and password
Seems like it is a google inside account. How to access to it?

**Comment by weishy-xun** [comment]
https://login.corp.google.com/request?s=fusion.corp.google.com:443/uberproxy/&d=https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:protobuf%252Fgithub%252Fmaster%252Fubuntu%252Fcpp_distcheck%252Fcontinuous%3Fupxsrf%3DAEkf9sBXogkBa0sjAGb74ioEAAr3sUaga8aURjbm633QN6tgIg:1545103057004&maxAge=1200&authLevel=2000000&keyIds=X-q,k02

**Comment by TeBoring** [comment]
Where is the link of Ubuntu C++ Installation?

**Comment by elharo** [comment]
can't reproduce, reopen if requested info is supplied
