### ISSUE TITLE
CMake support for plugins in generate_protobuf

### ISSUE THREAD

**Issue by pgoodman** [protocolbuffers/protobuf#5493]
**What language does this apply to?**
All languages.

**Describe the problem you are trying to solve.**
Using CMake to build a project that uses gRPC, I'd like to be able to provide a plugin command to `generate_protobuf`. Partial support is there in the form of `LANGUAGE grpc` and `GENERATE_EXTENSIONS .grpc.pb.h .grpc.pb.cc` but there's no way to pass in the plugin information.

**Describe the solution you'd like**
A way to pass in the plugin name and path.

**Describe alternatives you've considered**
Trying to force it through the `LANGUAGE`; it doesn't work.

**Comment by faaxm** [comment]
@pgoodman @acozzette Only found this issue after creating PR #7249 that fixes this. Please have a look. :)
