### ISSUE TITLE
PHP library CodedOutputStream.php buffer

### ISSUE THREAD

**Issue by yqbaa** [protocolbuffers/protobuf#5499]
public function __construct($size)
{
$this->current = 0;
$this->buffer_size = $size;
$this->buffer = str_repeat(chr(0), $this->buffer_size);
}
why you create this buffer , it weel course memory double. #

**Comment by TeBoring** [comment]
The buffer is used to store serialized result.
Why do you think it doubles the memory? What's your baseline?
