### ISSUE TITLE
Request: implement/add isEmpty() on AbstractMessage, DynamicMessage, and GeneratedMessage 

### ISSUE THREAD

**Issue by protobufel** [protocolbuffers/protobuf#55]
At present, to find whether the MessageOrBuilder is empty one needs to call the following:

``` java
  messageOrBuilder.getUnknownFields().asMap().isEmpty() 
          && messageOrBuilder.getAllFields().isEmpty();
```

It is cumbersome and expensive ( getAllFields() in many cases would recreate the fields' map!).
However, to implement it from within the MessageOrBuilder, all needed is to just call internal map.isEmpty() or such.

There are so many valid and common cases for emptiness check, the are done often and in many places, so this API and performance optimization is crucial, IMHO. 

There are two implementation alternatives:
1. with minimal/zero impact on compatibility - implement isEmpty() on basic classes AbstractMessage, DynamicMessage, and GeneratedMessage and their Builders.
2. more complete and consistent API, but could be impact on pure Message/Builder implementations, is implement option 1 plus add isEmpty() to (Lite)MessageOrBuilder interface.

Any implementation alternative will also solve the "is MessageOrBuilder default?" question, which currently resolved differently for GeneratedMessage and DynamicMessage.

The alternative 1 will require casting to these basic classes, so it is not  w/o cons.

This request is not extremely urgent, so it could be implemented anytime after 2.6.1.

**Comment by elharo** [comment]
decided not to do this to avoid complexifying the API and adding extra surface to test and support
