### ISSUE TITLE
Make RepeatedField's EnsureSize() a public method in C#

### ISSUE THREAD

**Issue by prat0088** [protocolbuffers/protobuf#5501]
**What language does this apply to?**

C#

**Describe the problem you are trying to solve.**

I need to quickly process a large number of primitives in one array, filter some, and insert them into a repeated field.  I know the size of my output before I begin processing the array.

**Describe the solution you'd like**

I would like to preallocate my output RepeatedField, then loop over the large input array only a single time, processing, filtering, and writing out the data to a RepeatedField in a single pass.

_If EnsureSize() were public instead of private, I could accomplish this._

**Describe alternatives you've considered**

- Adding a RepatedField constructor that takes a capacity parameter, but users don't typically create their own RepeatedFields, and you also couldn't grow the array this way.
- I could process and filter from arrayA to tempArray, then call AddRange(tempArray) on the output RepeatedField, but that would require traversing the large array twice, although it wouldn't be calling EnsureSize() as often.
- I could call Add() for each element.  This would be the most inefficient of all choices.

**Comment by anandolee** [comment]
Make sense to me. The c++ has this public API as well:
https://github.com/protocolbuffers/protobuf/blob/f9d8138376765d229a32635c9209061e4e4aed8c/src/google/protobuf/repeated_field.h#L162

Are you happy to create a PR(including test) and assign to me. I'd prefer to change the naming of EnsureSize() to Reserve() same with C++.
