### ISSUE TITLE
version-3.6.1 fails to compile on Windows 10

### ISSUE THREAD

**Issue by Shwetago** [protocolbuffers/protobuf#5508]

**Comment by BSBandme** [comment]
Would you please provide more details about this?

**Comment by Shwetago** [comment]
I am using Windows10. I tried to compile this:
`protoc object_detection/protos/*.proto --python_out=.`
but this gave me an error.

**Comment by BSBandme** [comment]
Would you please provide any compiling log for this?

**Comment by deannagarcia** [comment]
Closing due to no response, if you are still seeing an error please reopen and provide more details.
