### ISSUE TITLE
Problems encountered in trying out examples

### ISSUE THREAD

**Issue by daoqiang** [protocolbuffers/protobuf#5515]
Failed to initialize  "google::protobuf::internal::ExtensionSet::kMaximumFlatCapacity"	
Failed to initialize  "google::protobuf::Timestamp::kIndexInFileMessages"

**Comment by daoqiang** [comment]
Protobuf is installed through vcpkg.
Version: 3.6.1-4

**Comment by daoqiang** [comment]
can you help me?

**Comment by BSBandme** [comment]
Would you please provide the full log?

**Comment by BSBandme** [comment]
Closed as long time no response.
Feel free to reopen this when you still have issues.
