### ISSUE TITLE
C# Reflection methods for google/protobuf/wrappers.proto return inner types

### ISSUE THREAD

**Issue by mdkess** [protocolbuffers/protobuf#5517]
**What version of protobuf and what language are you using?**
Version: v3.6.1.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Mac OS X 10.14.2 (but through Docker)

**What runtime / compiler are you using (e.g., python version or gcc version)**
C# - .NET Core 2.1

**What did you do?**
For the types in https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto (i.e. `BoolValue`, `StringValue`, etc), it seems that `fieldDescriptor.Accessor.GetValue(msg)` returns a value of the inner type (`bool`, `string`, etc.) rather than the `BoolValue` or `StringValue` type as I would have expected. However if I check `fieldDescriptor.FieldType`, it's a `Message`.

If I say `fieldDescriptor.MessageType.ClrType`, I get a `BoolValue` or `StringValue` as I would expect.

I'm working on a reflection utility to make it easier for us to work with field masks and this is making it a bit tricky to deal with, since the type of the field and the type of the field's value that the accessor returns are different.

I've managed to work around it by checking `fieldDescriptor.MessageType.FullName` and comparing with the wrapper types, however this feels pretty janky, so I'm wondering if I am doing something wrong here or misunderstanding.

Is there a better way to do this? And is there some documentation about whether there are other special types like these?

What I would like or expect is that the type of a field and the type of the _value_ of that field match, or at least some general way to get a value with the same type as the field.

I've seen a few similar issues: https://github.com/protocolbuffers/protobuf/issues/2574 and https://github.com/protocolbuffers/protobuf/issues/2575 - perhaps this is related?

**Comment by mdkess** [comment]
I found this comment: https://github.com/protocolbuffers/protobuf/blob/47d33e752e5256bec315e5867b940ca33d66e8a2/csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs#L171

```
        /// For wrapper types (<see cref="Google.Protobuf.WellKnownTypes.StringValue"/> and the like), the parser returned here
        /// will be the generated message type, not the native type used by reflection for fields of those types. Code
        /// using reflection should call <see cref="IsWrapperType"/> to determine whether a message descriptor represents
        /// a wrapper type, and handle the result appropriately.
```

however the `IsWrapperType` method is marked internal:

```
        internal bool IsWrapperType => File.Package == "google.protobuf" && File.Name == "google/protobuf/wrappers.proto";
```

I wonder if part of the fix here would be to make `IsWrapperType` public. Then maybe just a utility method somewhere `ToWrappedType` that would convert a `bool` to a `BoolValue` and so on? I implemented my own for these, but perhaps others would find them useful.

**Comment by anandolee** [comment]
Well Known Types(WKT) do have different behaviors/APIs. 
The WKT in C# code:
https://github.com/protocolbuffers/protobuf/tree/master/csharp/src/Google.Protobuf/WellKnownTypes

Document is not updated but has included most WKT:
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf

**Comment by mdkess** [comment]
Hey - I think this issue is still valid. In particular, I don't have any way to tell if something is a well known type, which makes it really hard to write reflection routines against them since the type of the field, and the type of the *value* of the field are different.

I think at least we should make `IsWrapperType` - if you agree, I'm happy to make that change. Let me know.
