### ISSUE TITLE
README links to corporate Google pages

### ISSUE THREAD

**Issue by riking** [protocolbuffers/protobuf#5520]
**What did you do?**
1. Go to the repository's README page at https://github.com/protocolbuffers/protobuf
2. Click on the first "build passing" badge under Java, which links to `https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:protobuf%2Fgithub%2Fmaster%2Fubuntu%2Fjava_compatibility%2Fcontinuous`
3. Asked to enter my Google corporate login & password

**What did you expect to see**
Something that looks closer to this [IMAGE REMOVED]

**What did you see instead?**
![image](https://user-images.githubusercontent.com/627891/50544759-83384580-0bb5-11e9-9345-b2e064529efb.png)

**Comment by BSBandme** [comment]
Sorry but this link is internally only. It has some confidential information in the building log.
