### ISSUE TITLE
CUDA issue with static constexpr in dllexport class: kMaximumFlatCapacity may not be initialized

### ISSUE THREAD

**Issue by xkszltl** [protocolbuffers/protobuf#5521]
**What version of protobuf and what language are you using?**
Version: master/v3.6.1.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Win10

**What runtime / compiler are you using (e.g., python version or gcc version)**
VS 2017 (15.9.4) + CUDA 10.0

**What did you do?**
Build as DLL for CUDA libraries (e.g. caffe2).

**What did you see instead?**

Error message like `member "XXX" may not be initialized`.

Seems NVCC do not allow static constexpr in dllexport class:
https://github.com/protocolbuffers/protobuf/blob/be1716a6d0346de7a990b60f4afc9aebe2e06f36/src/google/protobuf/extension_set.h#L659
https://github.com/protocolbuffers/protobuf/blob/66dc42d891a4fc8e9190c524fd67961688a37bbe/src/google/protobuf/compiler/cpp/cpp_message.cc#L950

**Comment by xkszltl** [comment]
Suggestion: Simply move it out of the class, or make it as `static const` instead.

**Comment by xkszltl** [comment]
No replied since the issue creation.
@BSBandme @acozzette Any updates?

**Comment by acozzette** [comment]
We would be happy to review a PR if you would like to send one with a fix. Changing to `static const` sounds like it might be a good option if it doesn't break anything.

**Comment by xkszltl** [comment]
@acozzette You closed that PR.....
- https://github.com/protocolbuffers/protobuf/pull/5522

**Comment by xkszltl** [comment]
active

**Comment by xkszltl** [comment]
Is this fixed?
Didn't see any recent change yet.
Or is it because new nvcc doesn't have that restriction?
