### ISSUE TITLE
Iterate messages in the order of appearance in file with Python API

### ISSUE THREAD

**Issue by uraj** [protocolbuffers/protobuf#5525]
I'm writing a plugin for protoc and I'm using Python. I'm having trouble with iterating messages in a file, given a `FileDescriptor` object. The class provides an attribute `message_types_by_name`. When iterating this dictionary, the messages are no longer in the order of their original appearance in the proto file.

Since message definitions have dependencies, being able to iterate them in topological order has certain advantages. Is there any canonical way to do this? I scanned the related APIs but didn't find a nice solution.

**Comment by BSBandme** [comment]
I'm not very familiar with python protobuf but I guess there's no public API for that. You may do the topologyical sorting manually by searching all dependency messages.

**Comment by uraj** [comment]
Based on my research, elements in `message_types_by_name` are actually inserted in order when `FileDescriptor` objects are created and initialized. It's just that Python `dict` does not preserve insertion order. Switching to `collections.OrderedDict` seems an easy enough solution to me, it the team is interested in fixing this.

This applies to `enum_types_by_name` too, but as far as I know there are no dependency problems for enums so it's probably not a big deal anyway.
