### ISSUE TITLE
Add CMake option to define GOOGLE_PROTOBUF_NO_RTTI

### ISSUE THREAD

**Issue by thomasgt** [protocolbuffers/protobuf#5541]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
I am integrating Protobuf into a C++ project that does not use RTTI. I am building Protobuf from source (with CMake) and I'd like to be able to set the `GOOGLE_PROTOBUF_NO_RTTI` flag when I configure the build.

**Describe the solution you'd like**
I would like a CMake option to control whether or not `GOOGLE_PROTOBUF_NO_RTTI` gets defined.

**Comment by acozzette** [comment]
That sounds like a good option to have; do you want to send a pull request with that change?

**Comment by thomasgt** [comment]
Sure!
