### ISSUE TITLE
Open-source .proto.h codegen that avoids transitive includes

### ISSUE THREAD

**Issue by Alfus** [protocolbuffers/protobuf#5542]
**What language does this apply to?**
c++ code gen

**Describe the problem you are trying to solve.**
We have a couple proto files that include a lot of other proto files (similar to gwslog :-)). This causes a lot of needless recompiling when any of the included proto files change. These files have grown large enough to be problematic.

**Describe the solution you'd like**
This problem can be solved by using forward declarations instead of including the headers of the other proto files. There appears to be an option in the c++ code gen library to do this:
https://github.com/protocolbuffers/protobuf/blob/de9e1a04a68af0c8c5f49121ebd7dd1a2fed37af/src/google/protobuf/compiler/cpp/cpp_options.h#L55

However it is not exposed:
https://github.com/protocolbuffers/protobuf/blob/de9e1a04a68af0c8c5f49121ebd7dd1a2fed37af/src/google/protobuf/compiler/cpp/cpp_generator.cc#L84

**Describe alternatives you've considered**
We 'hacked' around this by adding proto message option, custom bazel build rules and a protoc plug-in that generates a header file that forward declares all needed messages and defines a wrapper class that owns a pointer to the problematic message, which is also forward declared (it also generates a .cc file that forwards all the accessors to the real accessors on the owned message).

**Additional context**

**Comment by haberman** [comment]
This was completed in https://github.com/protocolbuffers/protobuf/pull/9482.
