### ISSUE TITLE
Is it possible to override existing instance instead of creating new instance when deserializing?

### ISSUE THREAD

**Issue by pnarimani** [protocolbuffers/protobuf#5545]
Every time that we want to deserialize a protobuf message, it creates a new instance. Is it possible to have only one instance and override its values?

It's what we are doing now:
```
player = Player.Parser.ParseFrom(receivedBytes);
```

I'm looking for something like this:
```
player.OverrideFrom(receivedBytes);
```
Which overrides `player` properties with received values and doesn't allocate a new instance.

**Comment by TeBoring** [comment]
Can you use clear and mergeFrom?
BTW, what language are you using?

**Comment by TeBoring** [comment]
@anandolee does c# provide method to clear the whole message? Is c#'s ParseFrom provided on message instead of class?

**Comment by ObsidianMinor** [comment]
@sorencoder There isn't an automatic way of doing this that's included in the library, however you can make your own using an extension method and reflection.

```csharp
public static class MessageExtensions
{
    public static void Clear(this IMessage message)
    {
        foreach (var field in message.Descriptor.Fields.InDeclarationOrder())
        {
            if (field.MessageType != null)
            {
                (field.Accessor.GetValue(message) as IMessage).Clear();
            }
            else
            {
                field.Accessor.Clear(message);
            }
        }
    }
}
```

**Comment by sorencoder** [comment]
@ObsidianMinor I tried to use that code, but I'm receiving this error:
`InvalidOperationException: MessageType is only valid for message fields.`
on the line
`if (field.MessageType != null && !field.IsRepeated)`

How can I fix it?

**Comment by ObsidianMinor** [comment]
Oh right, I forgot they don't just make it `null`. Change it to

```cs
if (field.FieldType == FieldType.Message && !field.IsRepeated)
```
