### ISSUE TITLE
protoc proto2 ruby support

### ISSUE THREAD

**Issue by cherubrock** [protocolbuffers/protobuf#5548]
google-protobuf Ruby gem seems to support proto2 for a while:
[https://github.com/protocolbuffers/protobuf/commit/d0535cc09e6eac1bddddd51c20b5738c0e841765](url)
But latest protoc still complains:
`--ruby_out: ams.proto: Can only generate Ruby code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.
`

**Comment by TeBoring** [comment]
We will release the feature in 3.7.0 release.

**Comment by cherubrock** [comment]
thats great news

**Comment by sutharsentio** [comment]
Still facing the same issue

```
rm -f lib/google/protobuf/any_pb.rb lib/google/protobuf/api_pb.rb lib/google/protobuf/descriptor_pb.rb lib/google/protobuf/duration_pb.rb lib/google/protobuf/empty_pb.rb lib/google/protobuf/field_mask_pb.rb lib/google/protobuf/source_context_pb.rb lib/google/protobuf/struct_pb.rb lib/google/protobuf/timestamp_pb.rb lib/google/protobuf/type_pb.rb lib/google/protobuf/wrappers_pb.rb
protoc -I../src --ruby_out=lib ../src/google/protobuf/any.proto
protoc -I../src --ruby_out=lib ../src/google/protobuf/api.proto
protoc -I../src --ruby_out=lib ../src/google/protobuf/descriptor.proto
--ruby_out: google/protobuf/descriptor.proto: Can only generate Ruby code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.

rake aborted!
Command failed with status (1): [protoc -I../src --ruby_out=lib ../src/goog...]
```
What can I do to solve this problem?

**Comment by haberman** [comment]
@sutharsentio I think you must be using a very old version of protoc.

The message you pasted was removed from the source code in https://github.com/protocolbuffers/protobuf/pull/4816, three and a half years ago.

**Comment by sutharsentio** [comment]
Thanks, updating the protobuf-compiler solved it for me. You can close the ticket.
