### ISSUE TITLE
Import "google/protobuf/empty.proto" was not found or had errors.

### ISSUE THREAD

**Issue by harini2191** [protocolbuffers/protobuf#5556]
Hi,
I am facing the following error,
C:\protobuf-3.6.1\java\protoc.exe --java_out=H:\GRPC\helloworld\app\build\generated\source\proto\debug\javalite\io\grpc\examples\helloworld mst_sevice.proto google/protobuf/timestamp.proto: File not found.google/protobuf/any.proto: File not found.google/protobuf/empty.proto: File not found.mst_sevice.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.mst_sevice.proto: Import "google/protobuf/any.proto" was not found or had errors.mst_sevice.proto: Import "google/protobuf/empty.proto" was not found or had errors.

My app dependencies are,

apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "io.grpc.helloworldexample"
        // API level 14+ is required for TLS since Google Play Services v10.2
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        disable 'GoogleAppIndexingWarning', 'HardcodedText', 'InvalidPackage'
        textReport true
        textOutput "stdout"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.6.1'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.0.0-pre2'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            javalite {}
        }
        ofNonTest()*.plugins {
            grpc {
                // Options added to --grpc_out
                option 'lite'
            }
        }
    }
}
dependencies {
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:multidex:1.0.3'
    //  GRPC dependencies
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'io.grpc:grpc-protobuf-lite:1.14.0'
    implementation 'io.grpc:grpc-okhttp:1.14.0'
    implementation 'io.grpc:grpc-stub:1.14.0'
    implementation files('libs/protobuf-java-3.6.1.jar')
    implementation files('libs/protobuf-java-util-3.6.1.jar')
    implementation 'com.android.support:multidex:1.0.3'
}
configurations {
    compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}

I am compiling the .proto file in two ways;
**First Way:**
I have installed two plugin namely generate protobuf from repository i have searched with the word protoc and i have got this plugin,Hence i have installed and a two options are available namely,
*configure generate protobuf plugin
*Generate all protobufs
while using this i can generate the java classes without using any imports in the .proto file, if i am using the imports i am getting the following error.

**C:\protobuf-3.6.1\java\protoc.exe --java_out=H:\GRPC\helloworld\app\build\generated\source\proto\debug\javalite\io\grpc\examples\helloworld mst_sevice.proto google/protobuf/timestamp.proto: File not found.google/protobuf/any.proto: File not found.google/protobuf/empty.proto: File not found.mst_sevice.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.mst_sevice.proto: Import "google/protobuf/any.proto" was not found or had errors.mst_sevice.proto: Import "google/protobuf/empty.proto" was not found or had errors.**

This line executed while i am using a Generate all protobufs tool from tools in android studio,I have got this by installing a repository in android studio.

**Second way**

while using Generate Protobuf there is option available while i am right clicking on the .proto file.After selecting plugin and the language, i am getting the folloein error,

Cannot run program "protoc": CreateProcess error=2, The system cannot find the file specified protoc --proto_path=H:/GRPC/helloworld/app/src/main/proto --java_out=plugins=grpc:H:/GRPC/helloworld/app/src/main/proto H:/GRPC/helloworld/app/src/main/proto/mst_sevice.proto

I don't which way to follow, one way i can generate the java file in another way i am unable to generate the java file.
Please help me.

The following is my .proto file.

syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option go_package = "google_protobuf_imports";
option java_outer_classname = "MstHandlerProto";
option objc_class_prefix = "HLW";

package helloworld;
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
// The greeting service definition.
service MstHandler {
    // Sends a greeting
    rpc   GetMstDeptByName        (MstDeptNameRequest)                	returns     (MstServiceResponse);
}

message MstDeptNameRequest{
    string                              DeptName          = 1;
}

message MstServiceResponse{
    string                            Status         = 1;
    int32                             Code           = 2;
    string                            CodeType       = 3;
    string                            Message        = 4;
    google.protobuf.Any               AnyData        = 5;
}

**Comment by BSBandme** [comment]
For the first one you need to declare the include path e.g. `-I=/some/path/can/found/proto_files`
But remember this generated file can't be used in javalite, since it's not generated using javalite plugin.

For the second I didn't quite get what are your repro steps.

Generally I recommend not mixing latest java with javalite, since last non-minor updates for javalite is long time ago.

**Comment by harini2191** [comment]
Thanks for your reply,Now i am getting "java.lang.UnsupportedOperationException",While debugging the code from the GeneratedMessageLite.java class i am getting the "GET_MEMOIZED_IS_INITIALIZED" exception in the dynamic method.The above same app gradle only i am using.

**Comment by harini2191** [comment]
> For the first one you need to declare the include path e.g. `-I=/some/path/can/found/proto_files`
> But remember this generated file can't be used in javalite, since it's not generated using javalite plugin.
> 
> For the second I didn't quite get what are your repro steps.
> 
> Generally I recommend not mixing latest java with javalite, since last non-minor updates for javalite is long time ago.

Thanks for your reply,Now i am getting "java.lang.UnsupportedOperationException",While debugging the code from the GeneratedMessageLite.java class i am getting the "GET_MEMOIZED_IS_INITIALIZED" exception in the dynamic method.The above same app gradle only i am using.

**Comment by mmarashan** [comment]
I had the same issue in Android studio project.
Just comment section in app's build.gradle:
```
protobuf {
//    protoc {
//        artifact = 'com.google.protobuf:protoc:3.9.0'
//    }
...
}
```
It helps me, proto has built.
