### ISSUE TITLE
Can I change the .cc suffix to .cpp suffix which created by .proto file?

### ISSUE THREAD

**Issue by swxEmily** [protocolbuffers/protobuf#5557]
my code is in a provided compile rule, it just support .cpp files, but .proto create .cc, I'm afraid I can change the suffix or not.

**Comment by acozzette** [comment]
`protoc` will always create files ending in `pb.cc`, but you can definitely rename those if you prefer. Renaming the header files (`pb.h`) would cause problems, but renaming the `pb.cc` files is fine.
