### ISSUE TITLE
How do I define proto using the same name in different packages  in some language doesnt have a package like oc

### ISSUE THREAD

**Issue by Args** [protocolbuffers/protobuf#5561]

**Comment by thomasvl** [comment]
There are file level options for some of the languages to control naming.  ObjC support a prefix to for all the types the file will define:

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L398-L400

Usage looks like:
```protobuf
// ...
option objc_class_prefix = "MyPrefix";
// ...
```

**Comment by Args** [comment]
> There are file level options for some of the languages to control naming. ObjC support a prefix to for all the types the file will define:
> 
> https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L398-L400
> 
> Usage looks like:
> 
> ```protobuf
> // ...
> option objc_class_prefix = "MyPrefix";
> // ...
> ```

That's it!Thank you!
And one more question,when I add a prefix,class name has changed,but filename not.and code to import is full path,i don't know how to recognize full path when import

**Comment by Args** [comment]
@thomasvl thank u !
