### ISSUE TITLE
Java ByteString.copyFrom(ByteBuffer bytes) bug

### ISSUE THREAD

**Issue by dougsatch** [protocolbuffers/protobuf#5563]
**What version of protobuf and what language are you using?**
Version: 3.5.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows 

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 8

**What did you do?**
ByteString.copyFrom(ByteBuffer bytes) should be copying the bytes from 0 to bytes.position()

**What did you see instead?**
ByteString.copyFrom(ByteBuffer bytes) is copying the bytes from 0 to bytes.remaining()
So if you have a ByteBuffer of size 16, and fill the first 4 bytes, then Protobufs is copying 12 bytes, rather than the expected 4.

**Anything else we should know about your project / environment**

**Comment by BSBandme** [comment]
I have to say this is the intended behavior, maybe a little weird to you.
We can't simple change the API behavior directly since it already has many callers from dependents.
