### ISSUE TITLE
use 'switch' for 'oneof' in  Serialize and IsInitialized

### ISSUE THREAD

**Issue by niuys** [protocolbuffers/protobuf#557]
In generated cpp code, is it ok to use 'switch' for 'oneof' in  method 'SerializeWithCachedSizes',  'SerializeWithCachedSizesToArray' and 'IsInitialized '? If the field num is too many in a 'oneof',this can reduce  time cost.

**Comment by haon4** [comment]
Seems like this was already implemented. Closing.
