### ISSUE TITLE
Python: Segmentation fault on deleting an attribute

### ISSUE THREAD

**Issue by tomlinford** [protocolbuffers/protobuf#5570]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
macOS High Sierra (also tested with ubuntu:trusty docker image)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Tested with python 2.7 and 3.6.

**What did you do?**
```
$ python -c 'from google.protobuf.timestamp_pb2 import Timestamp; del Timestamp().seconds'
```

**What did you expect to see**
Some kind of python exception or for the field to be reset to its default value.

**What did you see instead?**
Segmentation fault.

**Anything else we should know about your project / environment**
n/a

**Comment by anandolee** [comment]
Closing it for clean up. Feel free to reopen if needed
