### ISSUE TITLE
Ability to hide some sensitive fields in JsonFormat.Printer

### ISSUE THREAD

**Issue by wangjunwei87** [protocolbuffers/protobuf#5577]
**What language does this apply to?**

proto3 with java

**Describe the problem you are trying to solve.**

Some messages include sensitive data, eg: LoginRequest may contains a password.

**Describe the solution you'd like**

```
{
"password": "****"
}
```
instead of 

```
{
"password": "actual use input"
}
```

**Comment by haon4** [comment]
Today, JsonFormat.parser().parse(JsonFormat.printer().print(message)) would return an equivalent proto. However, this feature request would cause the parse() to return a different proto. I don't think we would want to introduce such behavior into JsonFormat. Furthermore, obfuscation logics is application specific. Some may want to completely obfuscate a field, while others may want to show some hints.

I think it is better to do this at the application level. Here is what you can do:

1. Define a proto field option like this:
```
message ObfuscationMode {
  bool obfuscate = 1;
}

extend proto2.FieldOptions {
  ObfuscationMode obfuscation_mode = 123456789;
}
```

2. Use proto reflection to determine to obfuscate a field based on the option:
```
  public void obfuscate(Builder builder) {
    for (FieldDescriptor field : builder.getAllFields().keySet()) {
      if (field.isRepeated()) {
        if (field.getJavaType() == JavaType.MESSAGE) {
          for (int i = 0; i < builder.getRepeatedFieldCount(field); ++i) {
            obfuscate(builder.getRepeatedFieldBuilder(field, i));
          }
        } else if (shouldObfuscate(field)) {
          for (int i = 0; i < builder.getRepeatedFieldCount(field); ++i) {
            // Actually obfuscating the field.
            builder.setRepeatedField(field, i, "****");
          }
        }
      } else if (builder.hasField(field)) {
        if (field.getJavaType() == JavaType.MESSAGE) {
          obfuscate(builder.getFieldBuilder(field));
        } else if (shouldObfuscate(field)) {
          // Actually obfuscating the field.
          builder.setField(field, "****");
        }
      }
    }
  }

  private static boolean shouldObfuscate(FieldDescriptor field) {
    // Determine whether to obfuscate a field. Change this as needed.
    if (field.getJavaType() != JavaType.STRING) {
      return false;
    }
    ObfuscationMode obfuscationMode =
        field.getOptions().getExtension(ObfuscationModeOuterClass.obfuscationMode);
    if (obfuscationMode == null) {
      return false;
    }
    return obfuscationMode.getObfuscate();
  }
```

3. Set the option on the field that you would like to obfuscate:
```
message TestMessage {
  string username = 1;
  string password = 2 [(obfuscation_mode).obfuscate = true];
}
```

With this, the application can customize the obfuscation logics in whatever way it wants.

**Comment by wangjunwei87** [comment]
@haon4 Thanks for your advice, it really helps.
