### ISSUE TITLE
vs2013 build error

### ISSUE THREAD

**Issue by yufeixuan** [protocolbuffers/protobuf#5579]
F:\OpenSource\protobuf-3.6.1\cmake\build\release>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../../install ../..
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: F:/OpenSource/protobuf-3.6.1/cmake/build/release

F:\OpenSource\protobuf-3.6.1\cmake\build\release>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../../../install ../..
-- Found ZLIB: F:/OpenSource/install/lib/zlib.lib (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: F:/OpenSource/protobuf-3.6.1/cmake/build/release

F:\OpenSource\protobuf-3.6.1\cmake\build\release>nmake

Microsoft (R) 程序维护实用工具 12.00.21005.1 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

Scanning dependencies of target libprotobuf-lite
[  0%] Building CXX object CMakeFiles/libprotobuf-lite.dir/F_/OpenSource/protobuf-3.6.1/src/google/protobuf/arena.cc.obj
arena.cc
[  0%] Building CXX object CMakeFiles/libprotobuf-lite.dir/F_/OpenSource/protobuf-3.6.1/src/google/protobuf/arenastring.cc.obj
arenastring.cc
[  0%] Building CXX object CMakeFiles/libprotobuf-lite.dir/F_/OpenSource/protobuf-3.6.1/src/google/protobuf/extension_set.cc.obj
extension_set.cc
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/message_lite.h(117) : error C2143: 语法错误 : 缺少“;”(在“const”的前面)
        F:\OpenSource\protobuf-3.6.1\src\google/protobuf/message_lite.h(127): 参见对正在编译的类 模板 实例化“google::protobuf::internal::ExplicitlyConstructed<T>”的引用
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/message_lite.h(117) : error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(123) : error C3646: “noexcept”: 未知重写说明符
        F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(335): 参见对正在编译的类 模板 实例化“google::protobuf::RepeatedField<Element>”的引用
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(124) : error C3646: “noexcept”: 未知重写说明符
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(778) : error C3646: “noexcept”: 未知重写说明符
        F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1025): 参见对正在编译的类 模板 实例化“google::protobuf::RepeatedPtrField<T>”的引用
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(779) : error C3646: “noexcept”: 未知重写说明符
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1099) : warning C4346: “google::protobuf::RepeatedField<Element>::{ctor}”: 依赖名称不是类型
        用“typename”为前缀来表示类型
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1099) : error C3646: “noexcept”: 未知重写说明符
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1114) : warning C4346: “google::protobuf::RepeatedField<Element>::operator =”: 依赖名称不是类型
        用“typename”为前缀来表示类型
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1114) : error C3646: “noexcept”: 未知重写说明符
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1937) : warning C4346: “google::protobuf::RepeatedPtrField<T>::{ctor}”: 依赖名称不是类型
        用“typename”为前缀来表示类型
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1937) : error C3646: “noexcept”: 未知重写说明符
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1952) : warning C4346: “google::protobuf::RepeatedPtrField<T>::operator =”: 依赖名称不是类型
        用“typename”为前缀来表示类型
F:\OpenSource\protobuf-3.6.1\src\google/protobuf/repeated_field.h(1952) : error C3646: “noexcept”: 未知重写说明符

**Comment by yufeixuan** [comment]
？？？

**Comment by acozzette** [comment]
@yufeixuan Does your compiler support C++11? If `noexcept` is causing errors then that makes me suspect the compiler does not have C++11 support, which protobuf requires starting from version 3.6.

**Comment by micw523** [comment]
VS13 does not support ```noexcept```. Try a higher version instead

**Comment by yufeixuan** [comment]
thanks
