### ISSUE TITLE
[C#] Support snake_case keys in JsonFormatter

### ISSUE THREAD

**Issue by rok-povsic** [protocolbuffers/protobuf#5583]
**What language does this apply to?**
proto3, C#.

**Describe the problem you are trying to solve.**

I'd like to serialize a Protobuf message to JSON using `JsonFormatter`, where keys named using snake_case are kept, instead of being converted into camelCase.

**Describe the solution you'd like**

I would like the keys to be kept as snake_case.

**Describe alternatives you've considered**

The alternative I have is taking the output string, parse the JSON, and recursively iterate through all the keys to convert camelCase back to snake_case.

**Additional context**

In Protobuf Python, for example, this is already possible using the `preserving_proto_field_name` field.

**Comment by anandolee** [comment]
We could add an option is json fotmat setting and a method
public Settings WithPreservFieldName(bool perservFieldName) =>
    new Settings(formatDefaultValues, TypeRegistry, FormatEnumsAsIntegers, perservFieldName)

https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/JsonFormatter.cs#L781

Are you happy to create a PR and assign to me for review?

**Comment by rok-povsic** [comment]
@anandolee It seems like it's not trivial to add this option because [ToJsonName](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/JsonFormatter.cs#L252) is static and cannot access the `JsonFormatter.Settings` object. 

From what I understand, `ToJsonName` gets called in [the FieldDescriptor](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs#L99) constructor and adding this option would require changing multiple classes' constructors, outside of `JsonFormatter`.

Do you see some other, easier solution?

**Comment by anandolee** [comment]
ToJsonName() is called in some helper APIs or generated code.

Users can create their own JsonFormatter with settings and then call formatter.Format(message). For example:
https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf.Test/JsonFormatterTest.cs#L90
