### ISSUE TITLE
Option ruby_package causes inconsistent code generation

### ISSUE THREAD

**Issue by jbolinger** [protocolbuffers/protobuf#5584]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.14

**What runtime / compiler are you using (e.g., python version or gcc version)**
Ruby 2.4.1

**What did you do?**
1. Compile the following proto: `protoc --proto_path=. --ruby_out=. example.proto`
```
syntax = "proto3";

package google.example;

option java_multiple_files = true;
//option ruby_package = "Google::Example";

service HelloService {
     rpc HiThere (HiRequest) returns (HiResponse);
}

message HiRequest {
    string query = 1;
}

message HiResponse {
    string result = 1;
}
```
2. Repeat step 1 after uncommenting the `ruby_package` line.

**What did you expect to see**
The generated Ruby code should be the same.

**What did you see instead?**
When the `ruby_package` options is specified the generated code is:
```ruby
module Google::Example
  HiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.example.HiRequest").msgclass
  HiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.example.HiResponse").msgclass
end
```

Without the `ruby_package` option it is:
```ruby
module Google
  module Example
    HiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.example.HiRequest").msgclass
    HiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.example.HiResponse").msgclass
  end
end
```

This inconsistency causes issues because the module must already be defined if the `ruby_package` option is used (example: https://github.com/googleapis/google-cloud-ruby/pull/2782).

**Anything else we should know about your project / environment**

**Comment by TeBoring** [comment]
Does the title of this issue correctly reflect the problem?
It seems to me the inconsistency is expected. The real issue is if the outer module is not defined. Is that correct?

**Comment by jbolinger** [comment]
Why is the inconsistency expected?

The module not being defined is what can cause problems at runtime, but it's not clear to me why it should be different.
