### ISSUE TITLE
Protobuf works via conda but not via pip. Trouble with $PATH.

### ISSUE THREAD

**Issue by mrc-rius** [protocolbuffers/protobuf#5586]
I have a conda environment with some packages installed via Conda, and other via Pip. All of them work well.

Now I want to add to my stack protobuff and first I run pip install protobuf. Then if I run protoc --version it returns that command does not exists.

On the other hand, the same command works and returns libprotoc 3.2.0 after running conda install protobuf.

I do not know and even understand why conda install seems to works, and pip install not.
Could be the package it self? Or maybe some problem with the $PATH variable setter?

**Comment by TeBoring** [comment]
@anandolee could you take a look?

**Comment by rito-sixt** [comment]
@TeBoring @anandolee This issue still seems to persist. Can you folks please take a look?
