### ISSUE TITLE
protobuf Any DebugString() not found specified Proto type

### ISSUE THREAD

**Issue by larrymeng** [protocolbuffers/protobuf#5593]
Protobuf defined such as:

> message ServiceReq {
>     session.Common       common     = 1; 
>     ModuleIdx                 module_idx = 2; 
>     google.protobuf.Any req              = 3; 
> }

In the course of use, some disgusting logs appeared.
For example:

> [libprotobuf WARNING google/protobuf/text_format.cc:1874] Proto type type.googleapis.com/com.xxx.proto.topic.QuerySubTopicsReq not found

**Comment by larrymeng** [comment]
How to fix it?

**Comment by acozzette** [comment]
That error message indicates that your code is trying to encode a particular message in text format, but it is coming across an Any field storing a type that it doesn't recognize. Either (a) that type URL is somehow incorrect, or (b) the type can't be found because it wasn't linked into the binary.

**Comment by larrymeng** [comment]
Thanks for your response.
The URL is correct, maybe the type can't be found.
