### ISSUE TITLE
Update dependency com.google.guava:guava of com.google.protobuf:protobuf-java-util

### ISSUE THREAD

**Issue by dawinter** [protocolbuffers/protobuf#5596]
Please update the dependency com.google.guava:guava of com.google.protobuf:protobuf-java-util due to open security vulnerability of the used com.google.guava:guava 20.0 [(including) 11.0 up to (excluding) 24.1.1]. Please upgrade to 24.1.1+. If you need the CVE number, let me know.

Thanks.

**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: Java

**What operating system (Linux, Windows, ...) and version?** Linux

**What runtime / compiler are you using (e.g., python version or gcc version)** no compiler, use compiled version

**What did you do?**
Read the security vulnerability reports and scan reports of used  com.google.protobuf:protobuf-java-util

**What did you expect to see**
Update of dependency

**What did you see instead?**
com.google.guava:guava 20.0

**Comment by BSBandme** [comment]
Some reference: [5150](https://github.com/protocolbuffers/protobuf/pull/5150)

**Comment by haon4** [comment]
Fixed with #5630
