### ISSUE TITLE
MacOS java generated files have unmatched file name and class name

### ISSUE THREAD

**Issue by dapengzhang0** [protocolbuffers/protobuf#5598]
**What version of protobuf and what language are you using?**
Version: v3.5.0 
Language:Java

**What operating system (Linux, Windows, ...) and version?**
MacOS

Basically if a proto message name is not in CamelCase, it is possible that the generated java code has unmatched file name and class name. This was only observed in MacOS so far.

See the description here:
https://github.com/envoyproxy/java-control-plane/issues/87
The change https://github.com/envoyproxy/envoy/commit/02659d4 to [envoyproxy/java-control-plane](https://github.com/envoyproxy/java-control-plane) triggered the error.

**Comment by dapengzhang0** [comment]
This is the same issue as #3308. If the proto file can be modified, adding `option java_outer_classname` can work around the issue. It's best practice to always add `option java_outer_classname` in the first place. https://developers.google.com/protocol-buffers/docs/reference/java-generated

 If such proto file cannot be modified, then on MacOS or windows, java codegen will fail.

**Comment by haon4** [comment]
Discussed this with Dapeng offline. It is ill-advised to generate different java files on different platform. If we automatically rename the outer class, then it is a breaking API change. The best we can do is to spit out a warning when this may cause conflict.

**Comment by haon4** [comment]
I have made a change at head to start warning users when name collision may be happening. Closing this issue.
