### ISSUE TITLE
Support for subtype in ruby

### ISSUE THREAD

**Issue by darkpssngr** [protocolbuffers/protobuf#5600]
I have a rails app which connects to another microservice through GRPC. I take the params I get from the web request and pass it on to the GRPC microservice. When the input is processed by the webserver all string fields are converted to ActiveSupport::SafeBuffer which is a subtype of string.
When I try to assign this value to a string field in the GRPC object, I get an error saying `"Invalid argument for string field."` 
This is happening because the type check against the concrete class in (https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/storage.c#L152). Does it make sense to check if one of the classes of the object matches the type we expect it to be.

I'm not sure if thats the best way to do it. But it would really help if we don't have to convert each object to string when we assign it. please let me know your thoughts on this.

**Comment by TeBoring** [comment]
Does ruby c API for string work for subtypes?

**Comment by TeBoring** [comment]
I am afraid we cannot support this. The current ruby c APIs only work for ruby string (no subtype).
