### ISSUE TITLE
make check FAIL: protobuf-test on openSuse Leap 15.0

### ISSUE THREAD

**Issue by Rohan0993** [protocolbuffers/protobuf#5601]
I am building the protobuf manually and while running the make check I am getting the following error.

> FAIL: protobuf-test
> PASS: protobuf-lazy-descriptor-test
> PASS: protobuf-lite-test
> PASS: google/protobuf/compiler/zip_output_unittest.sh
> PASS: google/protobuf/io/gzip_stream_unittest.sh
> PASS: protobuf-lite-arena-test
> PASS: no-warning-test

I am unable to see what went wrong. I am adding the test-suite.log for ready reference
[test-suite.log](https://github.com/protocolbuffers/protobuf/files/2773144/test-suite.log)

**Comment by TeBoring** [comment]
I think you happened to download our code when we had a broken test. Could you try downloading again?

**Comment by Rohan0993** [comment]
@TeBoring Yes It worked. Thanks

**Comment by matbillo** [comment]
I get the same fail, what should I do?
thanks

**Comment by Luke1962** [comment]
The same here , but with ARMBIAN 10.
Downloaded today and built on ARM platform (RockPi4B)


```
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.14.0
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

By the way several warnings  during  _make check_ of this type:
```
google/protobuf/util/message_differencer_unittest.cc:3138:22: warning: ‘protobuf_unittest::TestField* protobuf_unittest::TestDiffMessage::add_rm()’ is deprecated [-Wdeprecated-declarations]
   proto2diff_.add_rm()->set_c(3);

```
