### ISSUE TITLE
Google Protocol Buffer 3.6 “Derived” template parameter

### ISSUE THREAD

**Issue by Jointos** [protocolbuffers/protobuf#5607]
template parameters (and the base class) had changed for MapEntryLite (and for many others) since gpb 3.0 to gpb 3.6.x from
```cpp
template <typename Key, typename Value,
          WireFormatLite::FieldType kKeyFieldType,
          WireFormatLite::FieldType kValueFieldType,
          int default_enum_value>
class MapEntryLite : public MessageLite
```
to

```cpp
template <typename T, typename Key, typename Value,
          WireFormatLite::FieldType kKeyFieldType,
          WireFormatLite::FieldType kValueFieldType, int default_enum_value>
class MapEntryLite
    : public MapEntryImpl<T, MessageLite, Key, Value, kKeyFieldType,
                          kValueFieldType, default_enum_value>
```
Could someone explain what that typename "T" wants? MapEntryImpl's first template parameter is called "Derived", but what type am i supposed to insert there? Thanks

**Comment by sbenzaquen** [comment]
This code is in the `internal` namespace and it is related to internal implementation details. The API is not guaranteed to be stable.
In any case, I believe this is used for [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern).
