### ISSUE TITLE
Why java classes have outer classes?

### ISSUE THREAD

**Issue by sorencoder** [protocolbuffers/protobuf#5608]
Hi, 
We are using different languages for server and client. Client is C# and Server is Java.
In C#, protobuf simply generates a simple class. But in Java, we are getting another OuterClass that contains our main data model. 
I have two questions:  
First, Why there is an OuterClass?  
Second, Can we disable OuterClass generation and get a simple class like C#?

Best Regards.

**Comment by BSBandme** [comment]
I'm not sure about c# implementation but in Java we have to generate descriptor information in OuterClass, which is necessary for some public API.
