### ISSUE TITLE
Coverity Static Code Analyzer resource leak warning

### ISSUE THREAD

**Issue by skg-net** [protocolbuffers/protobuf#5621]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
v3.6.0
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
C++
**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime/compiler are you using (e.g., python version or gcc version)**
gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**What did you do?**
Run static Coverity static code analyzer.

**What did you expect to see**
No High Impact issue reported.

**What did you see instead?**
Saw 2 High Impact issues reported.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Attached is Coverity error report.

**Anything else we should know about your project / environment**
I can try and get the report again once a fix is available or we can enable include this project as part of coverity community scan.
[Proto Buff Coverity Issue.pdf](https://github.com/protocolbuffers/protobuf/files/2789469/Proto.Buff.Coverity.Issue.pdf)

**Comment by acozzette** [comment]
@skg-net Thanks for reporting this. It's not clear to me if there is a real issue here, though. Do you have a reproducible test case for the memory leak by any chance?

**Comment by skg-net** [comment]
@acozzette I went thru the code and found it to be a false positive. Since I'm not the author, I wanted the community to take a look at it and respond. No, I haven't faced any real memory leak. Please note we haven't covered all the test scenarios yet. I will keep the thread posted if we find anything.

**Comment by acozzette** [comment]
@skg-net OK, thanks for checking! Let me close this issue for now but we can reopen it if you find another problem.
