### ISSUE TITLE
Fix release packaging

### ISSUE THREAD

**Issue by jhihn** [protocolbuffers/protobuf#5625]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
Archive contents are extracted into the current directory.
$ unzip protoc-3.6.1-linux-x86_64.zip
Archive:  protoc-3.6.1-linux-x86_64.zip
   creating: include/
   creating: include/google/
   creating: include/google/protobuf/
  inflating: include/google/protobuf/wrappers.proto
  inflating: include/google/protobuf/field_mask.proto
  inflating: include/google/protobuf/api.proto
  inflating: include/google/protobuf/struct.proto
  inflating: include/google/protobuf/descriptor.proto
  inflating: include/google/protobuf/timestamp.proto
   creating: include/google/protobuf/compiler/
  inflating: include/google/protobuf/compiler/plugin.proto
  inflating: include/google/protobuf/empty.proto
  inflating: include/google/protobuf/any.proto
  inflating: include/google/protobuf/source_context.proto
  inflating: include/google/protobuf/type.proto
  inflating: include/google/protobuf/duration.proto
   creating: bin/
  inflating: bin/protoc
  inflating: readme.txt
**Describe the solution you'd like**
$unzip protoc-3.6.1-linux-x86_64.zip
Archive:  protoc-3.6.1-linux-x86_64.zip
   creating: protoc/include/
   creating: protoc/include/google/
   creating: protoc/include/google/protobuf/
  inflating: protoc/include/google/protobuf/wrappers.proto
  inflating: protoc/include/google/protobuf/field_mask.proto
  inflating: protoc/include/google/protobuf/api.proto
  inflating: protoc/include/google/protobuf/struct.proto
  inflating: protoc/include/google/protobuf/descriptor.proto
  inflating: protoc/include/google/protobuf/timestamp.proto
   creating: protoc/include/google/protobuf/compiler/
  inflating: protoc/include/google/protobuf/compiler/plugin.proto
  inflating: protoc/include/google/protobuf/empty.proto
  inflating: protoc/include/google/protobuf/any.proto
  inflating: protoc/include/google/protobuf/source_context.proto
  inflating: protoc/include/google/protobuf/type.proto
  inflating: protoc/include/google/protobuf/duration.proto
   creating: protoc/bin/
  inflating: protoc/bin/protoc
  inflating: protoc/readme.txt

**Additional context**
It's considered bad form to not prefix the archive content in it's own folder. This is because if I have an existing include or bin directory, the archive will dump it's on content into it, making an amalgamation that potentially overwrites files.

**Comment by TeBoring** [comment]
maybe put into the protoc dir and then use unzip?

**Comment by jhihn** [comment]
I mean sure, but there is no warning that it'll unzip the way it does. 

It does not confirm to standard practice.
