### ISSUE TITLE
GOOGLE_LOG - where is the log to inspect protobuf errors etc.

### ISSUE THREAD

**Issue by hesingh** [protocolbuffers/protobuf#5641]
In protobuf/src/google/protobuf/text_format..cc on line 299, I see a GOOGLE_LOG used.

I am using protobuf with c++ on Ubuntu 18.04.

In several gdb debugging tries, once I could see this message in my debugging.  By, default, where are these messages going so that I could see all GOOGLE_LOG messages?

I am using a P4Runtime application that uses gRPC and protobuf.

**Comment by acozzette** [comment]
The [default log handler](https://github.com/protocolbuffers/protobuf/blob/a21caa237a92b21d9af7e9aba2ea3600885ae5f9/src/google/protobuf/stubs/common.cc#L163) just sends messages to `stderr`, but you might need to check that `GOOGLE_PROTOBUF_MIN_LOG_LEVEL` was set to an appropriate level  (should be set to `LOGLEVEL_INFO` if you want to see all log messages.)

**Comment by hesingh** [comment]
Thanks much!
