### ISSUE TITLE
Protobuf is really missing inheritance

### ISSUE THREAD

**Issue by zatziky** [protocolbuffers/protobuf#5645]
**What language does this apply to?**
proto3 OR proto-future

**Describe the problem you are trying to solve.**
Lot's of DRY code in statically typed languages.

**Describe the solution you'd like**
I'd like you to add inheritance to current **proto3** or at least the future protobuf versions. An example is:
```
message Parent { }

message ChildA extends Parent { }
message ChildB extends Parent { }
message ChildC extends Parent { }
```

**Alternatives you've considered**
I know about **composition** and it's really not a cure. 

**Additional context**
I know that **protobuf favors composition over inheritance** but it's really not a cure to remove inheritance completely. Statically typed languages like Java or C# suffer from composition only approach. These languages cannot use polymorphism because all the messages have the same parent `GeneratedMessageV3`. If inheritance was available, we could use polymorphism. Instead of having to write:
```
void method(ChildA arg)
void method(ChildB arg)
void method(ChildC arg)
``` 
we could simply write `void method(Parent arg)`. Consequently, the **missing inheritance generates a lot of DRY code is hardly or not at all DRYable**. It leads to wider test suites that take more time to execute. I could go on but I hope I explained myself. (If not, just ask and I'll clarify it.)

**Comment by perezd** [comment]
FWIW

To quote the [Protocol Buffers tutorial](https://developers.google.com/protocol-buffers/docs/javatutorial):
"Don't go looking for facilities similar to class inheritance, though – protocol buffers don't do that."

Instead of inheritance, Protocol Buffers tends to favor [composition](https://en.wikipedia.org/wiki/Composition_over_inheritance) as a pattern.

**Comment by zatziky** [comment]
@perezd 

GRPC is not doing "favor composition over inheritance" pattern, it's applied **"remove inheritance" pattern**. :D

**Comment by ObsidianMinor** [comment]
How do you supposed you implement inheritance in a language that doesn't support inheritance like Rust or Go which only support struct-like data types?

**Comment by TeBoring** [comment]
For proto3, use Any.
For proto2, user extension.

**Comment by weitzhandler** [comment]
I want to have a base type for all server messages, request and response, then I want to have different types of requests/responses.
Anyone has experimented with this idea and found any adequate way to implement that?

**Comment by fer-marino** [comment]
totally agree with this. Lacking inheritance in my case is generating a TON of boilerplate code that I really don't want to. You are moving complexity (and performances bottleneck) from the protocol to the application.

**Comment by igalnassi** [comment]
Also agree - we have various base classes to represent our request and response objects and composition will be a huge lift.

Why is this issue closed as “completed” by the way? Are we saying this is implemented or that it will never be implemented?

**Comment by fawzibazari** [comment]
+1

**Comment by weitzhandler** [comment]
I've been using complex inheritance with protobuf and it works without issues. 
Alas I've been using Protobuf code-first in .NET, so there's no really proto files, but it take it this is possible.
