### ISSUE TITLE
System protobuf 3.0.0 overrides the python3 protobuf 3.6.1 

### ISSUE THREAD

**Issue by swiss-knight** [protocolbuffers/protobuf#5649]
From here: https://github.com/tensorflow/tensorflow/issues/25016 

I see something strange with protobuf. 
When I load protobuf in python3 as: `from google import protobuf` the manually installed version in "/usr/local/lib/" is not loaded. It is the system wide package in "/usr/lib/" which is loaded instead.

Output from python3:
```
>>> from google import protobuf
>>> protobuf.__version__
'3.0.0'
>>> protobuf.__file__
'/usr/lib/python3/dist-packages/google/protobuf/__init__.py'
```

But I guess it should be protobuf version 3.6.1 because:
```
$ pip3 list | grep proto
protobuf                      3.6.1 
```

But this system library is probably in conflict (or taking the priority of the pip package):
```
$ apt-cache policy libprotobuf10 
libprotobuf10:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://ch.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

and:
```
$ protoc --version
libprotoc 3.0.0
```

Anyway, protobuf 3.6.1 (not 3.0.0!) seems installed properly in "/usr/local/lib/": 
```
$ find /usr/local/lib/python3.6/dist-packages -iname "*protobuf*"
/usr/local/lib/python3.6/dist-packages/torch/share/cmake/Caffe2/public/protobuf.cmake
/usr/local/lib/python3.6/dist-packages/protobuf-3.6.1.dist-info
/usr/local/lib/python3.6/dist-packages/protobuf-3.6.1-py3.6-nspkg.pth
/usr/local/lib/python3.6/dist-packages/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive/python/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive/src/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf_internal.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf_compiler.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/default/protobuf.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/default/protobuf_compiler.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/protobuf
```
I'm not sure it is a "bug" but normally, the "/usr/local/lib/" package should override the one in "/usr/lib/" (if it exists) when we load protobuf in python3, but there is nothing in the system wide "/usr/lib/" place:
```
$ find /usr/lib/python3.6/ -iname "*proto*"
$
```

If anyone can say what's wrong here, I would be happy to hear it.

I'm using Ubuntu 18.04 64 bits with Python 3.6.7.
And I didn't compile anything from sources here; I only used packages in the official repositories (Ubuntu and PyPi).

**Comment by TeBoring** [comment]
I think this is an issue for ubuntu maintainer. They should include our latest release.
However, you should be able to uninstall the 3.0.0

**Comment by swiss-knight** [comment]
As protobuf from the official repositories is needed by several system packages like the "unity"-ones, uninstalling it will lead to system issues.

**Comment by artemiialessandrini** [comment]
Have someone solved an issue?

**Comment by duqiu** [comment]
https://github.com/protocolbuffers/protobuf/releases

#tar -xf  protobuf-all-3.6.1.tar.gz
#cd protobuf-3.6.1
#./configure 
#make 
#make check 
#make install


continue install protobuf for python
#cd ./python 
#python setup.py build 
#python setup.py test 
#python setup.py install

check it

#python3
>>> from google import protobuf
>>> protobuf.__version__
'3.6.1'
>>> protobuf.__file__
'/usr/local/lib/python3.6/dist-packages/protobuf-3.6.1-py3.6.egg/google/protobuf/__init__.py'
