### ISSUE TITLE
More descriptive error messages in Ruby

### ISSUE THREAD

**Issue by jbolinger** [protocolbuffers/protobuf#5655]
**What language does this apply to?**
Ruby

**Describe the problem you are trying to solve.**
If a proto message type is created with the wrong arguments an error message is thrown, but it is vague. For example if a number is given for a string field the error is something like:
`'initialize': Invalid argument for string field. (TypeError)`

**Describe the solution you'd like**
It would be helpful if the error message mentioned the name of the field and the expected/given types. For example, something like `TypeError: my_field expects a string but was given 12345.`

**Describe alternatives you've considered**

**Additional context**

**Comment by TeBoring** [comment]
Would you mind sending a PR to us?

**Comment by jbolinger** [comment]
Sure, took a shot at it in #5659

**Comment by jbolinger** [comment]
This was added in #5659, closing.
