### ISSUE TITLE
Better handling of wrapper types in Ruby

### ISSUE THREAD

**Issue by jbolinger** [protocolbuffers/protobuf#5656]
**What language does this apply to?**
Ruby

**Describe the problem you are trying to solve.**
Using wrapper types, such as `google.protobuf.StringValue` can be useful when field presence is important, but they are difficult to work with. For example, to assign a new value one has to write: 

`message.a_string = Google::Protobuf::StringValue.new(value: "some thing")`
instead of
`message.a_string = "some thing"`

**Describe the solution you'd like**
Additional getters / setters that accept strings and transparently handle the wrapper types would be more concise. 

**Describe alternatives you've considered**
Helper methods for creating the wrapper types can help, but still aren't great. Example: https://github.com/googleads/google-ads-ruby/issues/5

**Additional context**

**Comment by TeBoring** [comment]
For field foo, besides the previous ```a.foo```, can we provide ```a.foo_as_string```?
One problem is, how to distinguish no wrapper message and no value in wrapper message?

**Comment by jbolinger** [comment]
Yeah, I think `a.foo_as_string` would work. It's way shorter than the alternative. I don't think the `a.has_foo` method is really needed since the value is `nil` if the wrapper type is not set.

@mcloonan - any thoughts?

**Comment by mcloonan** [comment]
This sounds fine for strings, but one complication is that we'd need it for more value types than just strings. This is particularly painful with int32 and int64 where the user has to either remember or look up the right number of bits each time they want to use the field. If they still need to write out the type-name in the method call, that doesn't solve this tangential problem.

**Comment by TeBoring** [comment]
foo_as_sting is just an example. We could have foo_as_int32 as well.

**Comment by jbolinger** [comment]
That's a good point. Maybe we could just use `foo_as_int` and `foo_as_float` for all the variants?

**Comment by TeBoring** [comment]
Actually, I would like foo_as_value for all wrapper types.

**Comment by jbolinger** [comment]
I like the idea of using a consistent name for all types. I'm not sure if `as_value` is the best name though because `a.foo` would be for the wrapper type, i.e `StringValue`, and those types all end with `Value`. I can't come up with a better idea though. `as_object` comes to mind but it's an overloaded term too so I think `value` is probably better.
