### ISSUE TITLE
pb(fp16) ParseFromString and SerializeToString is very slow in arm

### ISSUE THREAD

**Issue by SmokerX** [protocolbuffers/protobuf#5662]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
python
**What operating system (Linux, Windows, ...) and version?**
Linux aarch64
**What runtime / compiler are you using (e.g., python version or gcc version)**
python3.5.2
**What did you do?**
run this code
```
pb_path='model/yolo_freeze.pb'
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(pb_path, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')
```

**What did you expect to see**
I expect to see this code will finish quickly
**What did you see instead?**
But I saw it is very slowly
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
The data type of this PB file is FP16.
I have tested other situations：
FP32 in CPU(X86) : quick
FP16 in CPU(X86) : quick
FP32 in ARM : quick
FP16 in ARM : ver slow ，It’s about a hundred times more time

**Comment by TeBoring** [comment]
I guess we didn't optimized it for c++ either. @acozzette

**Comment by acozzette** [comment]
@SmokerX What are FP16 and FP32?

**Comment by SmokerX** [comment]
Attributes of operations in PB files, such as T or Dtype

**Comment by SmokerX** [comment]
I have been researching this problem lately. I found that the reason for the very slow speed is because the data type in the "const" OP is np.float16, which is the reason for the very slow speed, not the dtype attribute of this op. (whether it is dt_float or dt_half)

**Comment by acozzette** [comment]
This sounds like it may be a TensorFlow-specific problem. Protobuf only has 32-bit and 64-bit floating-point types so I'm not even sure how TensorFlow represents 16-bit floats.

**Comment by SmokerX** [comment]
This problem is far beyond my ability. My current solution is based on my current needs, reimplementing the tf.import_graph_def method, and avoiding the use of SerializeToString and ParseFromString.

**Comment by acozzette** [comment]
OK, since there's a workaround let me close this for now.
