### ISSUE TITLE
PHP Extension: int64 serialize as Number instead of String type

### ISSUE THREAD

**Issue by omihaz** [protocolbuffers/protobuf#5663]
**Info**
Version: 3.6.1
Language: PHP, C++ (C PHP Extension)
Operating system: Linux, OSX

**What did you do?**
If I do not install the "protobuf php extension" and use an only php library by composer - all works fine as expected. int64 serialize to json as String by documentation:
https://developers.google.com/protocol-buffers/docs/proto3#json

But, if I install the "protobuf php extension", C extension override php implementation and int64 serialize as int, this is wrong. If I disable protobuf.so from php.ini all works fine with php implementation only.

This problem with php extension int64 serializer. 

I cannot find any workaround to fix this problem if the extension installed. I am a developer of a php library which use protobuf, if a user of library install it to an environment with protobuf extension than serializer works incorrectly.

Please fix this very annoying bug and make all implementations work in the same way as documented.

**What did you expect to see**
If protobuf extension installed, int64 serialize to json as String by the documentation

**What did you see instead?**
If protobuf extension installed, int64 serialize to json as Number without quotes

**Comment by TeBoring** [comment]
I think our parser can handle both sting and number int64

**Comment by omihaz** [comment]
Thanks for the answer.

For example, our application has a security layer with JSON payload signature check. All implementation server and client in C# work fine because it both use quotes for int64, but php implementation with extension is failed because of payload different on the server (java) and on the client (php with C extension).

For me and for this case very important to have the same JSON with a different implementation of protobuf.

**Comment by TeBoring** [comment]
Should have been fixed in #6251
