### ISSUE TITLE
JsonFormat.printer().print() don't accept my Message

### ISSUE THREAD

**Issue by Victor-Morel** [protocolbuffers/protobuf#5664]
Hello,
I'm developing an app using AndroidStudio, and I'm using protobuf to transmit data over Bluetooth Low Energy.  
But I also need to be able to represent this data in Json, due to environment constraints.   
I found [JsonFormat](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.Printer) to do the job, but unfortunately I'm having trouble with it.  
If I want to apply JsonFormat.printer().print() to one of my Message, the project doesn't compile and the method is underlined in red: `print(com.google.protobuf.MessageOrBuilder) in Printer cannot be applied to MyMessage`.  
I have the same problem if I pass a builder instead of a message.  
Everything else is working smoothly.  
My build.gradle contains  
`classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.7"`  
        `classpath 'com.google.protobuf:protobuf-java:3.4.0'`
        `classpath 'com.google.protobuf:protoc:3.0.0'`  
        `classpath 'com.google.protobuf:protobuf-java-util:3.4.0'`   
and  
 `    implementation 'com.google.protobuf:protobuf-lite:3.0.0'`
   ` implementation 'com.google.protobuf:protoc:3.0.0'`
   ` implementation 'com.google.protobuf:protobuf-java:3.4.0'`
  `  implementation 'com.google.protobuf:protobuf-java-util:3.4.0'`

Does anyone has any idea of what can be the issue?
Thanks

**Comment by acozzette** [comment]
I'm just taking a wild guess but it could be a problem with protobuf-lite. If that is a lite proto then it will not work with `JsonFormat` because the lite implementation omits features like descriptors and reflection to save on code size.

**Comment by Victor-Morel** [comment]
The issue was indeed caused by protobuf-lite, I had to recompile a java-only version, that is know working smoothly (albeit less adequate for mobile environment). Thanks!
