### ISSUE TITLE
PHP extension: please clarify stability state

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#5672]
Hi,

Latest release on PECL is 3.7.0RC2 but package.xml states

Stability = stable (should be "beta" for a RC version)

More the changelog only have "GA Release" (for all releases... which is obviously not valuable)

**Comment by TeBoring** [comment]
I see. Thanks for the catch. We will fix it in 3.7.0rc3.

**Comment by TeBoring** [comment]
Fixed in https://github.com/protocolbuffers/protobuf/pull/5695/files

**Comment by remicollet** [comment]
Notice that the problem is with the version available in PECL

`pecl install protobuf`

will download the latest **stable** version, so **3.7.0RC2** which is not expected


There is exactly the case where removing an uploaded version and replace it with a properly fixed archive make sense... BTW... should be done "quickly"...
