### ISSUE TITLE
JavaScript and int64 values

### ISSUE THREAD

**Issue by dimitarcl** [protocolbuffers/protobuf#5674]
JavaScript doesn't support 64-bit numbers, while protocol buffers allows using them.
How is one supposed to set or get int64 field inside a message?

Settings

Version: 3.6.1 .
Language:  JavaScript
OS: Windows 10

The official release from GitHub.

1. Create a message with int64 field
2. Compile to JavaScript
3. set the field to `4611686018427387928` or `'4611686018427387928'` (string)
4. serialize the message to a buffer
5. deserialize the message back
6. Check the value of the field - it will not be 4611686018427387928 neither as a number nor as a string.

- I am using protoc 3.6.1, with proto2 syntax

**Comment by TeBoring** [comment]
In your field, have you specified the js_type? ```jstype=JS_STRING```?

**Comment by dimitarcl** [comment]
Hi,
 
No, I haven't use that.
Will it still generate the same binary protocol?

**Comment by nhooyr** [comment]
@TeBoring how do you do that? Where do you specify the js_type?

**Comment by nhooyr** [comment]
Ah, its a field option.

**Comment by TeBoring** [comment]
Yes, same binary wire format.
