### ISSUE TITLE
Separate serialization and data types in generated classes

### ISSUE THREAD

**Issue by mmoeckel** [protocolbuffers/protobuf#5690]
I am currently using Protocol Buffers in a C++ client/server application to send commands to a server and retrieve complex calculated results. Both the client and the server talk to other libraries that generate and receive the information stored in the protocol buffers. These libraries are used in other contexts as well which is why I would like to limit protobuf dependency to the client and the server. Unfortunately, this means that I can't use the generated classes in the client's or the server's interface. Right now I have to write structs or classes that contain all the information the client needs and manually translate them to the protobuf-generated format.

Consider the following simple example:
```
message Example {
  double x = 1;
}
```
This currently generates a C++ class that looks somewhat like this:
```
#include "google/protobuf/[...].h"
class Example {
  double get_x();
  void set_x(double value);
  bool ParseFromString(const string& data);
  bool SerializeToString(string* output) const;
};
```
In order to use this class without a dependency on the protobuf library I would like a solution that looks something like this:
```
class Example {
  double get_x();
  void set_x(double value);
};

#include "google/protobuf/[...].h
class ExampleSerializer {
  Example ParseFromString(const string& data);
  bool SerializeToString(Example* input, string* output) const;
};
```
This would allow me to use the Example class (or struct) independently - for example, to pass an instance of it to the client via its interface and then serialize it before sending. Is that possible somehow?

**Comment by acozzette** [comment]
There's no special support for this in protoc, so you could do something like this but you would have to implement it all yourself. I think there are two variations on this. The first is to create your own `Example` class independent of protobuf and copy fields back and forth between that and the generated protobuf class. The second possibility would be to make `Example` just a pure interface, and code can be written against that interface without depending on protobuf. You could then provide an implementation of that interface which is just a thin wrapper around the generated proto.

**Comment by mmoeckel** [comment]
Thanks Adam!
The solution I came up with is a [small python script](https://github.com/mmoeckel/cdm_protobuf/blob/master/proto2h.py) that generates a protobuf-independent C++ header containing the same data and an adapter class that converts between it and the protobuf-generated types. For example,

```
package CDM;
enum CovarianceMethod
{
    DEFAULT = 0;
    CALCULATED = 1;
}
```
in the .proto file becomes
```
namespace CDM_C {
enum CovarianceMethod
{
    DEFAULT = 0,
    CALCULATED = 1
};
}
```
in the independent C++ header and
```
static inline CDM_C::CovarianceMethod CovarianceMethod(const CDM::CovarianceMethod in)
{
    if (in == CDM::DEFAULT) return CDM_C::DEFAULT;
    if (in == CDM::CALCULATED) return CDM_C::CALCULATED;
    return CDM_C::DEFAULT;
}
static inline CDM::CovarianceMethod CovarianceMethod(const CDM_C::CovarianceMethod in)
{
    if (in == CDM_C::DEFAULT) return CDM::DEFAULT;
    if (in == CDM_C::CALCULATED) return CDM::CALCULATED;
    return CDM::DEFAULT;
}
```
in the adapter class. This is far from complete and only covers the small subset of the protobuf specification that I am currently using myself but maybe it's useful to someone who has the same problem.

**Comment by acozzette** [comment]
Nice, I'm glad you found a solution. One thing to consider if you need to add more functionality is that you can let `protoc` do the work of parsing the `.proto` file for you. You can use the `--descriptor_set_out` flag to make `protoc` write a `FileDescriptorSet` proto to a file, and then your Python script can read in that `FileDescriptorSet` to get all the important information from the .proto file.

**Comment by mmoeckel** [comment]
That's a good idea, I'll look into it. Thanks!
