### ISSUE TITLE
3.7.0-rc2: Unable to load file '@com_google_protobuf_javalite//:compiler_config_setting.bzl': file doesn't exist

### ISSUE THREAD

**Issue by jin** [protocolbuffers/protobuf#5696]
**What version of protobuf and what language are you using?**
Version: 3.7.0-rc2
Language: All

**What operating system (Linux, Windows, ...) and version?**

Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

n/a

**What did you do?**

1. In a Bazel project, add `com_google_protobuf` external repository pointing to a 3.7.0 release candidate.
2. `$ bazel build @com_google_protobuf//:all`

```
ERROR: Skipping '@com_google_protobuf//:all': while parsing '@com_google_protobuf//:all': error loading package '@com_google_protobuf//': Unable to load file '@com_google_protobuf//:compiler_config_setting.bzl': file doesn't exist
WARNING: Target pattern parsing failed.
ERROR: while parsing '@com_google_protobuf//:all': error loading package '@com_google_protobuf//': Unable to load file '@com_google_protobuf//:compiler_config_setting.bzl': file doesn't exist
```

**What did you expect to see**

Build succeed.

**What did you see instead?**

Build failed due to missing `compiler_config_setting.bzl`.

**Anything else we should know about your project / environment**

The `compiler_config_setting.bzl` file exists in the source tree, but not in the release tarball. 

https://github.com/protocolbuffers/protobuf/blob/master/compiler_config_setting.bzl

cc @acozzette

**Comment by luxe** [comment]
fwiw, I have the same issue.

**Comment by jin** [comment]
When's the expected rc3 release date?

**Comment by acozzette** [comment]
We will most likely release rc3 tomorrow and then we'll try to get 3.7.0 released soon after that.
