### ISSUE TITLE
singleton.h listed in extract_includes.bat.in but does not exist

### ISSUE THREAD

**Issue by mxmlnkn** [protocolbuffers/protobuf#5699]
**What version of protobuf and what language are you using?**
Version: master de3be6c225cdb92548648cb899391ef5368051fa

**What operating system (Linux, Windows, ...) and version?**
Linux 4.5.0-1-amd64 #1 SMP Debian 4.5.1-1 (2016-04-14) x86_64 GNU/Linux

**What did you do?**

    cd protobuf-repo/cmake && mkdir build && cd build && cmake ..

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

    CMake Warning (dev) at install.cmake:60 (message):
      The file "/media/f/lbann/protobuf/src/google/protobuf/stubs/singleton.h" is
      listed in "/media/f/lbann/protobuf/cmake/cmake/extract_includes.bat.in" but
      there not exists.  The file will not be installed.
    Call Stack (most recent call first):
      CMakeLists.txt:226 (include)
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /media/f/lbann/protobuf/cmake

Probably introduced by #5348 Already seems to be fixed (line is deleted in `extract_includes.bat.in`) in [3.7.0rc2](https://github.com/protocolbuffers/protobuf/blob/3.7.x/cmake/extract_includes.bat.in)

**Comment by anandolee** [comment]
Closing it as 3.7.0 is already released
