### ISSUE TITLE
ByteCount() returns 0

### ISSUE THREAD

**Issue by PeterWangNavisens** [protocolbuffers/protobuf#5704]
**What version of protobuf and what language are you using?**
Version: master/v3.6.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Mac
**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
**What did you do?**
call ByteCount() on ArrayOutputStream  returns 0

**What did you expect to see**
return the byte count
**What did you see instead?**
ByteSizeLong?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
it returns 0, no error.
**Anything else we should know about your project / environment**
no

**Comment by acozzette** [comment]
I think this is working as intended. `ByteCount()` is supposed to return the number of bytes written, so if you create a fresh `ArrayOutputStream` then `ByteCount()` will return 0 since nothing has been written yet.

**Comment by PeterWangNavisens** [comment]
Lol, it's something was written, additional info: CFLAGS='GOOGLE_PROTOBUF_ARCH_IA32=1 GOOGLE_PROTOBUF_ARCH_32_BIT=1'

**Comment by acozzette** [comment]
Could you provide a reproducible example?

**Comment by PeterWangNavisens** [comment]
It's been cached in the browser, it works now, thank you for your time.
Additional question: for ZeroCopyInputStream, the ExpectAtEnd always returns false?

**Comment by acozzette** [comment]
I'm not sure offhand how `ExpectAtEnd()` is implemented, but it's documented like this: "Usually returns true if no more bytes can be read.  Always returns false if more bytes can be read."
