### ISSUE TITLE
Missing output directives

### ISSUE THREAD

**Issue by ersps25** [protocolbuffers/protobuf#5706]
Hi Team, the details of protobuf I am using are as follows  
Version: protoc-3.7.0-rc-2-win64.zip
Language: Python
Operating System : Windows 10
Runtime : Python

I am following this https://www.edureka.co/blog/tensorflow-object-detection-tutorial/ link to develop object detection demo.

I ran following command:

> protoc object_detection/protos/

But it showed me following message 

> Missing output directives.

Please suggest me, How should I proceed to resolve this issue?

**Comment by TeBoring** [comment]
protoc --python_out=. object_detection/protos/*

**Comment by ersps25** [comment]
Yes, it worked but in the tutorial, it is mentioned wrong.

**Comment by ramithuh** [comment]
@ersps25 did the tutorial work out afterwards? I'm getting an error with 'detection_masks'

**Comment by ersps25** [comment]
Yes, It worked for me.

**Comment by surya568** [comment]
i am showing this error what can i do?
'protoc' is not recognized as an internal or external command,
operable program or batch file.
I am running the command on ananconda prompt.

**Comment by vatsal522** [comment]
> 
> 
> protoc --python_out=. object_detection/protos/*

Not working

**Comment by hiwaveSupport** [comment]
I ran and it worked. You have to get to the folder that has protoc file, after you have extracted it.
I also see multiple buffs in the protos folder but got the following output, not sure if these are issues or not?
`(base) vibhu@pop-os:~/src/models$ protoc --python_out=. ./research/object_detection/protos/*
object_detection/protos/flexible_grid_anchor_generator.proto: File not found.
object_detection/protos/grid_anchor_generator.proto: File not found.
object_detection/protos/multiscale_anchor_generator.proto: File not found.
object_detection/protos/ssd_anchor_generator.proto: File not found.
research/object_detection/protos/anchor_generator.proto:5:1: Import "object_detection/protos/flexible_grid_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:6:1: Import "object_detection/protos/grid_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:7:1: Import "object_detection/protos/multiscale_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:8:1: Import "object_detection/protos/ssd_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:14:5: "GridAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:15:5: "SsdAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:16:5: "MultiscaleAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:17:5: "FlexibleGridAnchorGenerator" is not defined.
`

**Comment by WhiteWolf47** [comment]
use this -
protoc --python_out=. object_detection/protos/*.proto

**Comment by dkorni** [comment]
> use this -
> protoc --python_out=. object_detection/protos/*.proto

Thanks

**Comment by Dashenboy** [comment]
> ridAnchorGenerator" is not defined. research/object_detection/protos/anchor_generator.proto:15:5: "SsdAnchorGenerator

did u find the fix for this? im getting the same error
