### ISSUE TITLE
Protoc python compiler error: more than 255 arguments

### ISSUE THREAD

**Issue by Jinmo** [protocolbuffers/protobuf#5707]
**What version of protobuf and what language are you using?**
Version: master
Language: Python

**What operating system (Linux, Windows, ...) and version?**
All

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 2.7

**What did you do?**
Compile proto file with 256 nested message types to python script (_pb2.py)

```
message A {
  message B1 {}
  ...
  message B256 {}
}
```

**What did you expect to see**
No errors.

**What did you see instead?**
Syntax error:

```
SyntaxError: more than 255 arguments
```

It only occurs in python 2.7, not 3.x.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
Do you know which line in protobuf raises the error?

As I searched: Python did not allow for more than 255 function arguments. This arbitrary restriction has been removed in Python 3.7 (see https://bugs.python.org/issue12844).

It surprise me that this error "only occurs in python 2.7, not 3.x."

**Comment by Jinmo** [comment]
I attached the errored proto file and _pb2.py file below:
https://gist.github.com/Jinmo/523f8407660d0719e6bd7eec90a5cbe1

The error occurs in line 6200, in `dict(B0=GeneratedProtocolMessageType, B1=...)`:
```
  File "poc_pb2.py", line 6200
    B0 = _reflection.GeneratedProtocolMessageType('B0', (_message.Message,), dict(
SyntaxError: more than 255 arguments
```

**Comment by anandolee** [comment]
Sounds a reasonable solution. I will do the experimental in internal to make sure it does not break anything.
Thanks for raise it up

**Comment by anandolee** [comment]
Experiment shows good result. Already fixed in internal code and expect to see the fix in future down integrate.

Thanks for the proposal
