### ISSUE TITLE
Protobuf Gradle plugin cannot generate C# code

### ISSUE THREAD

**Issue by xaviarias** [protocolbuffers/protobuf#5711]
**What version of protobuf and what language are you using?**

Version: master/v3.6.1 and later
Language: C#

**What operating system (Linux, Windows, ...) and version?**

MacOS 10.14.3

**What runtime / compiler are you using (e.g., python version or gcc version)**
Not sure, I am using the `com.google.protobuf:protoc` Maven artifact.

**What did you do?**
1. Configure a project with the [Gradle Protobuf plugin](https://github.com/google/protobuf-gradle-plugin) activating C# compilation.
2. Declare a `protobuf` dependency, eg. 
```
dependencies {
    protobuf "org.hyperledger.fabric-chaincode-java:fabric-chaincode-protos:$fabricVersion"
}
```
3. Run the task `generateProto`

**What did you expect to see**

The protobuf files in the dependencies compiled in C#.

**What did you see instead?**

```org.gradle.api.GradleException: protoc: stdout: . stderr: peer/transaction.proto: warning: Import google/protobuf/timestamp.proto but not used.
--csharp_out: google/protobuf/compiler/plugin.proto: C# code generation only supports proto3 syntax```

**Comment by TeBoring** [comment]
@anandolee It seems we haven't uploaded protoc for c# for 3.7.0rc2. Could you help with that?

**Comment by TeBoring** [comment]
Should have been fixed.

**Comment by TeBoring** [comment]
Seems the real issue is c# doesn't support proto2. You need to add ```syntax = "proto3";``` on top of your proto file.

**Comment by xaviarias** [comment]
Yeah but is not my file which doesn't have proto3 syntax.

Check [google/protobuf/compiler/plugin.proto](https://github.com/protocolbuffers/protobuf/blob/3.7.x/src/google/protobuf/compiler/plugin.proto)

Please do not close this issue.

**Comment by xaviarias** [comment]
Hi, what is going on with this issue ? Can you please explain why it has been closed without any prior discussion ?

**Comment by TeBoring** [comment]
We uploaded new protoc tool on nuget?
Does it work now?

**Comment by xaviarias** [comment]
Hi, I still get the same error.

I believe that until `google/protobuf/compiler/plugin.proto` does not change its syntax version to 3 the error will continue.

Is there a stopper that prevents changing this file?

**Comment by xaviarias** [comment]
Hi @anandolee, @TeBoring any update on this?
