### ISSUE TITLE
[PHP] Setting oneof field to nested message using constructor args causes segfault

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#5714]
**What version of protobuf and what language are you using?**
Version: 3.7.0-RC2
Language: PHP

See this issue: https://github.com/googleapis/google-cloud-php/issues/1624

It appears that setting the value of a `oneof` field to a nested message using constructor args causes a segmentation fault.

Illustrations using Cloud Spanner messages of a segmentation fault on a oneof field:

```php
use Google\Protobuf\Timestamp;
use Google\Cloud\Spanner\V1\TransactionOptions\ReadOnly;

new ReadOnly([
    'read_timestamp' => new Timestamp
]);

// segfault
```

```php
use Google\Cloud\Spanner\V1\TransactionOptions\ReadOnly;

new ReadOnly([
    'strong' => true
]);

// no error
```

Setting values of a field which is not a oneof works as expected:

```php
use Google\Cloud\Spanner\V1\Type;

new Type([
    'code' => 10,
    'array_element_type' => new Type([
        'code' => 10
    ])
]);

// no error
```

cc @dwsupplee @ajaaym

**Comment by TeBoring** [comment]
Are you using php c extension or pure php?

**Comment by jdpedrie** [comment]
Apologies. This error only occurs when using the extension.

**Comment by dwsupplee** [comment]
Do you still see the error when regenerating the protobuf classes with the 3.7 branch of protoc?

**Comment by jdpedrie** [comment]
Yes.

https://github.com/jdpedrie/oneof-issue

I generated the classes for this repo using `protoc` compiled from the latest `master` branch of protobuf.

**Comment by TeBoring** [comment]
could you try 3.7.x branch?

**Comment by jdpedrie** [comment]
Done; same result.
