### ISSUE TITLE
Insertion points and their future

### ISSUE THREAD

**Issue by yuri-sergiichuk** [protocolbuffers/protobuf#5721]
I've noticed in several other issues (e.g. #3292, #3291, #2684) Protobuf contributors are standing that insertion points should not be used, does this actually mean that in some time custom Protobuf plugins won't be supported at all? 
It's that I'm looking at customizing Protobuf Java output with some extra stuff and e.g. I've noticed an insertion point `@@protoc_insertion_point(message_implements:NAME)` that is actually present in the generated sources but is not documented at the [website](https://developers.google.com/protocol-buffers/docs/reference/java-generated#plugins). 

Could you please provide some statement about the insertion points support and usage at all and about `message_implements` insertion point in particular, is it safe to use it?

**Comment by BSBandme** [comment]
I'm not sure about the plan for that but I think we're trying to deprecate insertion point and we may break you in the future.

**Comment by yuri-sergiichuk** [comment]
@BSBandme thank you for your attention to the question. Is there any change to announce any actual "plans" or "dates" if the functionality is gonna be deprecated?
Any plans to discuss this with the community?

**Comment by marcoferrer** [comment]
I’m also interested in the discussion around this feature. I currently author a library that tags the builder interfaces with a Kotlin specific annotation. It’s purpose is to allow composition of proto message in a type safe dsl like manner, but doesn’t modify the interface in any way. It’s purely meant to provide hints to the ide and compile time safety. 

Is this not an acceptable usage of the insertions api?

**Comment by haon4** [comment]
@@protoc_insertion_point(message_implements:NAME) is inserted at the following point:
```
public final class Foo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:package.name.Foo)
    FooOrBuilder {
...
}
```

We have found that some insertion points are too fine grained and allow developers to get into the way of our implementation details, while others are fine to have. e.g., we have a number of insertion points in C++ for serialize/parse, which isn't something that we would like developers to change. We are reevaluating the values of some of these insertion points to see if they should be removed.

Our stand is not to completely kill _all_ insertion points, but to eliminate certain insertion points that are problematic and likely to cause more harms. Most other insertion points at class scope / builder scope are acceptable to have.

**Comment by yuri-sergiichuk** [comment]
@haon4 we are now using `@@protoc_insertion_point(message_implements:NAME)` and `@@protoc_insertion_point(class_scope:NAME)`.

The first one is very useful when you want to group different message under one particular interface.

**Comment by haon4** [comment]
Thanks, Yuri. Sounds good to continue using them. We don't have any plan to remove those as far as I can tell.

**Comment by klaudeew** [comment]
@yuri-sergiichuk 
Can you please provide an example on how you implemented and used protocol buffer plugins? 
I'm currently looking for a way to have multiple generated classes to be grouped under a common interface (java) which sounds like something you achieved with @@protoc_insertion_point(message_implements:NAME.
However, the documentation is very limited, I can't find any examples anywhere and I'm not sure where to start.

**Comment by yuri-sergiichuk** [comment]
@klaudeew you can take a look at our [Spine](https://github.com/SpineEventEngine)'s plugin [here](https://github.com/SpineEventEngine/base/tree/master/tools/protoc-plugin).
