### ISSUE TITLE
protobuf.pc.in does not reflect CXXFLAGS

### ISSUE THREAD

**Issue by dickmao** [protocolbuffers/protobuf#5725]
Currently, downstream libraries such as RProtoBuf fail because `-std=c++11` is required via `configure.ac`, but RProtobuf has no way of knowing this by consulting `pkg-config --cflags protobuf`.

Perhaps `protobuf.pc.in` needs to mention `@CXXFLAGS@` in Cflags.

**Comment by BSBandme** [comment]
Feel free to send a PR for updating the pkg-config input file.
