### ISSUE TITLE
python installation (c++ implementation) with already a existing libprotobuf.so

### ISSUE THREAD

**Issue by dilipvamsi** [protocolbuffers/protobuf#5728]
Hi,

While installing the python version of protobuf with the help of [Readme](https://github.com/protocolbuffers/protobuf/blob/master/python/README.md). 

1. I have faced an issue regarding the installation of python (c++ implementation) with existing **llibprotobuf.so**
2. I have exported **LD_LIBRARY_PATH** to the path of **libprotobuf.so** as explained in [Readme](https://github.com/protocolbuffers/protobuf/blob/master/python/README.md). 
3. But the installation requires the **LIBRARY_PATH** (not **LD_LIBRARY_PATH**) to be set so that the **gcc** knows the location of **libprotobuf.so** (as code is compiled with **-lprotobuf** flag)
``` shell
#  for installing c++ implementation of python protobuf
$ export LIBRARY_PATH=/path_to_dir_which_has_libprotobuf.so
# for import in google.protobuf in python 
$ export LD_LIBRARY_PATH=/path_to_dir_which_has_libprotobuf.so
```
So, it would suggest this to be included in [Readme](https://github.com/protocolbuffers/protobuf/blob/master/python/README.md). 

Regards,
Dilip Vamsi.

**Comment by BSBandme** [comment]
Feel free to send a PR for improving documentation.
