### ISSUE TITLE
Objc full_mac_build.sh build error

### ISSUE THREAD

**Issue by Link913** [protocolbuffers/protobuf#5732]
### environment
- macOS 10.14.2
- XCode 10.1
- autoconf 2.69
- automake 1.16.1_1
- libtool 2.4.6_1
- make 4.2.1_1
- unzip 6.0_3

Running https://github.com/google/protobuf/blob/master/objectivec/DevTools/full_mac_build.sh on Mac

    git clone https://github.com/google/protobuf.git
    /Users/fanyang/Desktop/mypb/protobuf/objectivec/DevTools/full_mac_build.sh 

-----

    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-local
    Making lib/libgmock.a lib/libgmock_main.a in gmock
    /bin/sh: line 0: cd: third_party/googletest/googletest: No such file or directory
    make[2]: *** [check-local] Error 1
    make[1]: *** [check-am] Error 2
    make: *** [check-recursive] Error 1
    Error: 'make -j 4 check' exited with status 2

**Comment by thomasvl** [comment]
`git submodule update --init --recursive`

The ObjC README points to the C++ directions on what is needed for cloning and requirements to build so there is only one place to be updated.

**Comment by Link913** [comment]
@thomasvl Thank you for your help

**Comment by edjust** [comment]
I'm having the same issue when I'm installing Protobuf in my Mac. In the step I have to make check appears:

Edgars-MacBook-Pro-152:protobuf-3.6.1 edjust$ make check 
Making check in .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-local
Making lib/libgmock.a lib/libgmock_main.a in gmock
/bin/sh: line 0: cd: third_party/googletest/googletest: No such file or directory
make[2]: *** [check-local] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by edjust** [comment]
I'm having the same issue when I'm installing Protobuf in my Mac. In the step "make check" happens:

Edgars-MacBook-Pro-152:protobuf-3.6.1 edjust$ make check
Making check in .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-local
Making lib/libgmock.a lib/libgmock_main.a in gmock
/bin/sh: line 0: cd: third_party/googletest/googletest: No such file or directory
make[2]: *** [check-local] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by thomasvl** [comment]
Did you do the recursive close?  If not, do the submodule update mentioned before to get submodules.

**Comment by GE-GAO-ZHAO** [comment]
Installing new or old protobuf version than current version to . It belong to developer error. please download release tag .
