### ISSUE TITLE
Please publish pre-built Debian packages

### ISSUE THREAD

**Issue by rgov** [protocolbuffers/protobuf#5741]
Debian stable (stretch) and Ubuntu LTS (18.04, Bionic) both offer very outdated packages of Protobuf, going back to version 3.0.0 released almost 3 years ago.

While newer releases can be built from source and installed, apt does not recognize the manually-built version and will overwrite it with the old release if the `libprotobuf` or `protobuf-compiler` packages are installed (including if one is a dependency of another package you install).

Here is a StackOverflow discussion about that: https://stackoverflow.com/questions/54699030/prevent-apt-from-overwriting-a-package-manually-installed

Note that Google already has an official software repository where this could be published so the package can be installed with `apt-get`: https://www.google.com/linuxrepositories/

Otherwise, if you released a package on GitHub, it could be installed with `dpkg -i`.

**Comment by haon4** [comment]
The newer versions are making their way into Debian testing (e.g., https://packages.debian.org/search?keywords=protobuf-compiler). They have no SLO so we don't know when it will land in stable.
