### ISSUE TITLE
How to suppress runtime warning

### ISSUE THREAD

**Issue by junhyeokahn** [protocolbuffers/protobuf#5744]
Hello, 
I am using protobuf in python and I am getting a warning sometime
```
RuntimeWarning: Unexpected end-group tag: Not all data was converted
```
when I get empty messages and try to parse my message with
```
ParseFromString
```
I want to suppress it. Is there any flag I could pass to protobuf so I could suppress this warning when I parse protomsg?

**Comment by BSBandme** [comment]
I'm not sure but I guess there's no way for doing that. 
From the warning information it seems your input  raw data is truncated, which has un matched group tag.

**Comment by anandolee** [comment]
The warning can't be suppressed. It should be an error instead of warning indeed. In pure python, it is an error, but in c extension we are currently raise warning because change to error breaks some of google's internal projects. There is also a TODO to change the warning into error:
https://github.com/protocolbuffers/protobuf/blob/46a48e49aa8357bbeee8040819a35e59880e329a/python/google/protobuf/internal/message_test.py#L155

**Comment by xloem** [comment]
hey =) I'm looking through the code and it's kind of hard to figure out how this warning is generated.

It looks like the only way to reliably detect if a message is a valid protobuf message, is to risk this warning being output and then validate the result.  It would be nice if there were _some_ way to hack it away, even if it means closing the stdout file descriptor.

Where in the source is this warning generated?

**Comment by xloem** [comment]
@junhyeokahn ( @illbebach ) this workaround disables the warning:
```
import warnings
with warnings.simplefilter('ignore'):
    message.ParseFromString(data)
if not message.IsInitialized():
    raise Exception('invalid data')
```

**Comment by tlifschitz** [comment]
> hey =) I'm looking through the code and it's kind of hard to figure out how this warning is generated.
> 
> It looks like the only way to reliably detect if a message is a valid protobuf message, is to risk this warning being output and then validate the result. It would be nice if there were _some_ way to hack it away, even if it means closing the stdout file descriptor.
> 
> Where in the source is this warning generated?

Hi @xloem I am having a similar issue. I rely on that exception being risen to check if it is a well-formed message, but I only get that runtime warning. Could you find any workaround?

**Comment by tabletenniser** [comment]
> hey =) I'm looking through the code and it's kind of hard to figure out how this warning is generated.
> 
> It looks like the only way to reliably detect if a message is a valid protobuf message, is to risk this warning being output and then validate the result. It would be nice if there were _some_ way to hack it away, even if it means closing the stdout file descriptor.
> 
> Where in the source is this warning generated?

I think it comes from this line: https://github.com/protocolbuffers/protobuf/blob/b141bf9b1ea19272fde0cfbbdc7888d3f16526ac/python/google/protobuf/pyext/message.cc#L1928  Maybe we need to ask jieluo@ to prioritize b/27494216 ?
