### ISSUE TITLE
VS 2013 build unseccessfull

### ISSUE THREAD

**Issue by heretic13** [protocolbuffers/protobuf#5748]
**What version of protobuf and what language are you using?**
Version: 3bf05b88eaf938526f7daee85ab6fb1efb0e809c.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 x64

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2013 Update 5

**What did you do?**
1. download latest protobuf sources from git repository.
2. Run Cmake-gui & config solution for Visual Studio 2013.
3. Open protobuf solution in VS & start building.
4. See errors
5.  Open https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md & see "Something for VS 2013". I do not see marks on the minimum available version of Visual Studio to compile protobuf in official documentation.

**What did you expect to see**
Successfull build. **Marks** for the minimally supported version of Visual Studio in the official protobuf documentation.
**Notes** about the latest successful protobuf build (git id or version number) supported by Visual Studio 2013 in the official protobuf documentation.
Reason: VS 2013 is the latest version of VS, which has no problem with Windows XP support.

**What did you see instead?**
11k errors. :). No marks & notes in documentation.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by BSBandme** [comment]
Would you please provide some error log?

**Comment by heretic13** [comment]
[output.zip](https://github.com/protocolbuffers/protobuf/files/2886825/output.zip)
all 11k errors.

looks like C++11/14/17 features in your code that VS 2013 does not support

**Comment by acozzette** [comment]
@heretic13 Starting from version 3.6.0 we now require C++11, so if VS 2013 doesn't have C++11 support then I don't think there is much we can do. You can try building the 3.5.x branch of protobuf, which is the most up-to-date protobuf code that doesn't depend on C++11.

**Comment by heretic13** [comment]
Thanks for the explanation.
How about putting this information in the documentation section?

**Comment by Terry-Qin** [comment]
That's right! I have built protobuf 3.5.1 successfully on VS 2013.
