### ISSUE TITLE
How can I convert ByteString in protobuf to String in java?

### ISSUE THREAD

**Issue by wangjunbao2018** [protocolbuffers/protobuf#5753]
Hi,there

I use a server to push data to client in Go lang, The protocol is protobuf. There's a field typed bytes, which type is ByteString in generated java class. but when I convert it to String, it occured errors. The result I got is not right?  What's the problem?

**Comment by BSBandme** [comment]
You may use [this function](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/ByteString.java#L800) if your bytes are Utf8 encoded. 

Or you can use [this one](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/ByteString.java#L780) by providing Charset
