### ISSUE TITLE
Authenticode sign assemblies and NuGet sign package

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#5756]
**What language does this apply to?**
.NET

**Describe the problem you are trying to solve.**
We want to use Google.Protobuf but there are company policies that require third-party assemblies be Authenticode signed and the NuGet package to be signed.

**Describe the solution you'd like**
Authenicode sign assemblies in Google.Protobuf and NuGet sign the Google.Protobuf package.

**Comment by TeBoring** [comment]
We had an issue with nuget. Has that been fixed? @anandolee

**Comment by JamesNK** [comment]
cc @jtattermusch

**Comment by jtattermusch** [comment]
gRPC already has a solution for this and it's something that protobuf can reuse relatively easily I think.
I can facilitate this.

@TeBoring  I know the 3.7.0 release has been in progress for a while now - what's the ETA for 3.7.0 nugets to be built? Perhaps we could push signed nugets already for the 3.7.0 version.

**Comment by jtattermusch** [comment]
The just-released 3.7.0 nugets are signed (and files inside are authenticode-signed).
