### ISSUE TITLE
FR: C# allow the reading of repeated custom options

### ISSUE THREAD

**Issue by chrisdunelm** [protocolbuffers/protobuf#5759]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
Read repeated custom options

**Describe the solution you'd like**
Methods in the [`CustomOptions`](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Reflection/CustomOptions.cs) class to allow reading of repeated custom options.

**Describe alternatives you've considered**
Currently using reflection to achieve this ;)

**Additional context**

**Comment by RoarkeRandall** [comment]
I'm trying to pull a repeated EnumValueOption and I'm not sure how to do it. I'm able to do this in go and it appears it's possible in c#. W

I see in a few issue discussions it was decided to not support generics and also to not support repeated options. Why was this decided? 

https://github.com/protocolbuffers/protobuf/pull/2317

Is there any other way to pull repeated options? I can see in my debugger that the data is all there in the descriptor, but there is no method overload to retrieve it on the `CustomOptions` class.

**Comment by jtattermusch** [comment]
Currently it's not possible because proto2 is not fully supported. #5936 should fix that.

**Comment by RoarkeRandall** [comment]
I keep reading comments that it's a proto2 feature, and not proto3, but that isn't the case:

> Custom Options
> Protocol Buffers also allows you to define and use your own options. This is an advanced feature which most people don't need. If you do think you need to create your own options, see the Proto2 Language Guide for details. *Note that creating custom options uses extensions, which are permitted only for custom options in proto3*.
