### ISSUE TITLE
Support the .srcjar suffix for archived generated code

### ISSUE THREAD

**Issue by shahms** [protocolbuffers/protobuf#576]
This is specifically to simplify compatibility with Bazel, which expects .jar files to contain compiled code and .srcjar to contain source code.  When using bazel to generate Java code from a protocol buffer, some minor-but-annoying workarounds are required to use the requisite '.srcjar' suffix.  Adding support to protoc seems like it would be pretty straightforward.

**Comment by simuons** [comment]
I think this is resolved by https://github.com/protocolbuffers/protobuf/pull/7190 at https://github.com/protocolbuffers/protobuf/pull/7190/files#diff-5f83a7f49398fa05465b00c6ec8e7477R890 and released in 3.12.0

**Comment by elharo** [comment]
fixed
