### ISSUE TITLE
Mapping typeUrl of Any message to Java class name

### ISSUE THREAD

**Issue by yxu-valleytider** [protocolbuffers/protobuf#5761]
I am looking for a generic way to deserialize an `Any` message in Java. In my use case, the Java app performing the deserialization may receive a variety of message types,  but does not know the exact message name a-priori.  

As is suggested by [this article](https://stackoverflow.com/questions/32613667/protobuf-3-0-any-type-pack-unpack), this is possible through the Java reflection. However, it appears the `typeUrl` is not an exact match to the Java class name -- it corresponds to the descriptor name but does not contain the outer class name.  Ideally, there should be a way for a Java app to derive the exact message class name based on `typeUrl`. 

Is there any plan on supporting looking up Java class name given `typeUrl` (fullname of the message descriptor).  Without such capability, the only mechanism I could think of is load all the subclasses of `google.protobuf.Message` at runtime, and check for equality to a given `typeUrl` one-by-one.   Or, perhaps the Java app could query the outer class name (or .proto file name) from another service, but this adds complexity.

Any suggestion is welcome. Many thanks!

**Comment by yxu-valleytider** [comment]
Bump it up.  Note similar support of [DynamicAny](https://godoc.org/github.com/golang/protobuf/ptypes#DynamicAny) inside GO.

**Comment by BSBandme** [comment]
For java, Descriptors are not static loaded, which means we can't load all involved message eagerly like C++ (this is constrained by java class loading), which means we can't automatic build some map like this : descriptor name -> (descriptor or message class).

However you may build the map by hand at the beginning of the your program, you may build a [DescriptorPool by declaring all the proto dependencies](https://cs.corp.google.com/piper///depot/google3/java/com/google/protobuf/Descriptors.java?q=Descriptors.java&dr=C&l=2203), then after get the typeUrl, you may get the descriptor name and find the descriptor from the pool. Then you may either use DynamicMessage or just guess the message class name from the Descriptor's name and Descriptor's file's java related options.

**Comment by yxu-valleytider** [comment]
HI @BSBandme  Thanks for the answer.   I assume this is [the link](https://github.com/protocolbuffers/protobuf/blob/791b86368778e21fd4936f0f8674daff44046dff/java/core/src/main/java/com/google/protobuf/Descriptors.java#L2184-L2188) you mentioned. 

Do you mind clarifying a bit regarding `declaring all the proto dependencies` ?  How do you suggest to retrieve the set of file descriptors used when [constructing the descriptor pool](https://github.com/protocolbuffers/protobuf/blob/791b86368778e21fd4936f0f8674daff44046dff/java/core/src/main/java/com/google/protobuf/Descriptors.java#L2197).  Does one need to do it by scanning the java package ? 

Thanks again.

**Comment by GeTOUO** [comment]
`AnyAuto.java`:
```
public static Optional<? extends GeneratedMessageV3> unpack(Any pack) {
    return ProtobufTypeCache.findClass(pack.getTypeUrl()).filter(c -> pack.is(c))
            .map(ThrowingFun.unchecked(clz -> pack.unpack(clz)));
}
```

then :

`ProtobufTypeCache.java`:

```
private static final Map<String, Set<Class<? extends GeneratedMessageV3>>> reflectionBuf = new ConcurrentHashMap<>();

private static final Map<String, Class<? extends GeneratedMessageV3>> mapping = new ConcurrentHashMap<>();

private static final BiFunction<Class<? extends GeneratedMessageV3>, String, Boolean> classPredicate = ProtobufUtils::isClassTypeUrl;

public static Optional<Class<? extends GeneratedMessageV3>> findClass(final String protoTypeUrl) {
    if (StringUtils.isBlank(protoTypeUrl)) return Optional.empty();
    String noPrefixTypeUrl = ProtobufUtils.removeGooglePrefix(protoTypeUrl);
    if (mapping.containsKey(noPrefixTypeUrl)) return Optional.of(mapping.get(noPrefixTypeUrl));

    return OtherUtil.getPackageFromTypeUrl(noPrefixTypeUrl)
            .map(pkg -> reflectionBuf.computeIfAbsent(pkg, k -> ReflectionsUtils.scan(pkg, GeneratedMessageV3.class)))
            .flatMap(classSet -> classSet.stream()
                    .filter(c -> classPredicate.apply(c, noPrefixTypeUrl))
                    .peek(mc -> mapping.put(noPrefixTypeUrl, mc))
                    .findFirst());
}
```
