### ISSUE TITLE
Google_protobuf failed to run the MapSerializationTest.Deterministic with release configuration and debug configuration

### ISSUE THREAD

**Issue by spacelg** [protocolbuffers/protobuf#5763]
Environment:
 Windows Server 2016 + VS2017 Update 5 + Google_protobuf master branch latest srouce code

Google_protobuf failed to run the MapSerializationTest.Deterministic with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance!

 1.git clone https://github.com/google/protobuf.git D:\Google-Protobuf\src
 2.Open a VS 2017 command prompt and browse to D:\Google-Protobuf
 3.mkdir build_x64_ltcg && pushd build_x64_ltcg
 4.cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCMAKE_EXE_LINKER_FLAGS="/LTCG" -DCMAKE_C_FLAGS="/GL" -DCMAKE_CXX_FLAGS="/GL" ..\src\cmake
 5.popd
 6.msbuild /p:Configuration=Release;Platform=x64 build_x64_ltcg\protobuf.sln /t:Rebuild 
 7.pushd src
 8. ..\build_x64_ltcg\Release\tests.exe --gtest_filter=MapSerializationTest.Deterministic

Actual result:
[  FAILED  ] MapSerializationTest.Deterministic (35 ms)
[ RUN      ] MapSerializationTest.DeterministicSubmessage
[       OK ] MapSerializationTest.DeterministicSubmessage (2 ms)
[----------] 2 tests from MapSerializationTest (37 ms total)

[----------] 4 tests from TextFormatMapTest
[ RUN      ] TextFormatMapTest.SerializeAndParse
[       OK ] TextFormatMapTest.SerializeAndParse (0 ms)
[ RUN      ] TextFormatMapTest.ParseCorruptedString
[libprotobuf FATAL D:\Google-Protobuf\src\src\google\protobuf\map_test.cc:3299] CHECK failed: message.ParseFromString(serialized_message): 
[command took 14 seconds] 

[log_x64_ltcg_test_1.log](https://github.com/protocolbuffers/protobuf/files/2892579/log_x64_ltcg_test_1.log)

**Comment by BSBandme** [comment]
Sorry that we had some bugs in testing golden files for previous several days.
Re clone the repo should solve the problem.
