### ISSUE TITLE
Generated C++ filenames are .cc but protoc flag is named cpp_out

### ISSUE THREAD

**Issue by smlehbleh** [protocolbuffers/protobuf#5782]
Is there a flag to protoc to output c++ filenames as .cpp instead of .cc?
It seems inconsistent to name the flag cpp_out but then output .cc.
From my own experiences, I've encountered .cpp extension far more often than .cc
Either way, as it is generated code, it should be configurable to integrate into however existing codebases are configured.

**Comment by TeBoring** [comment]
You can probably rename it easily.
