### ISSUE TITLE
Support optional data object for JavaScript generated Message constructor

### ISSUE THREAD

**Issue by javoire** [protocolbuffers/protobuf#5783]
**What language does this apply to?**
Generated JavaScript

**Describe the problem you are trying to solve.**
The current way of creating a new message in JavaScript is a bit unnatural and awkward, since setters and getters is not a common pattern in JavaScript. This makes spreading adoption for things like [grpc-web](https://github.com/grpc/grpc-web) in web communities harder.

Example of current state:
```js
// set value using setter
const request = new EchoRequest();
request.setMessage('hello');

// set value using data array
const request = new EchoRequest(['hello']);
```

The former is unnatural for JavaScript and the latter is not very useful as you'd need to look up the order of fields in the proto schema.

**Describe the solution you'd like**

My suggestion is to support an object being passed to the constructor, like:

```js
const request = new EchoRequest({ message: 'hello' });
```

This is both natural and useful for JS devs. And it's similar to existing ways of sending JSON encoded data using e.g. `fetch` or `axios`:

```js
axios.post('https://site.com/', {
  message: 'hello'
})

fetch('https://site.com/', {
  method: 'POST',
  body: JSON.stringify({ message: 'hello' })
});
```

**Describe alternatives you've considered**

I haven't been able to come up with any alternatives.

**Additional context**

My understanding from looking at the Message type in protobuf is that it concerns itself not really with what fields are named but rather how they are numbered (ordered?). So I'm assuming that the change would be somewhere high up in the generated JS code. For example:

```js
/**
 * Generated by JsPbCodeGenerator.
 * @param {Object=} opt_data Optional initial data object, 
 * <.....>
 */
proto.some.service.EchoRequest = function(opt_data_obj) {
  const opt_data = optDataObjToArray(opt_data_obj);
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
```
What do you think?

I tried to search if this had been discussed before but couldn't find anything so apologies if it's been asked before.

Cheers!

**Comment by TeBoring** [comment]
This forces us to eagerly verify schema which would be problematic for code size.

**Comment by javoire** [comment]
@TeBoring could you elaborate on that? Cheers

**Comment by TeBoring** [comment]
The approach you mentioned will need field name, which will hurt code size.

**Comment by javoire** [comment]
I understand! How much difference do you think it would be? If you had to make a guess. And also, how important do you think code size is for JS clients?
