### ISSUE TITLE
Publish symbol package

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#5785]
Symbol packages contain debug files (*.pdb). There is a new snupkg package format and NuGet.org hosts a server for them.

More info:
[docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages)

It should involve changing the the arguments to `dotnet pack` so that a snupkg is also output, and then publishing it to NuGet.org.

**Comment by anandolee** [comment]
Jan, can you help to take a look at this issue?

**Comment by jtattermusch** [comment]
Sure, I can take a look. I'll discuss offline with Microsoft why the sourcelink integration that's already in place is not sufficient.

I don't think we can publish the symbol packages retroactively (the concern is if we rebuild from the same tag, the newly created pdb might not work well with already-uploaded assemblies), can we?

**Comment by JamesNK** [comment]
Source Link adds metadata about the source code to a package. It allows source code files to be downloaded as you debug through a .NET application.

A symbol package is a way of packaging and disturbing symbol files. Symbol files map instructions in a program (create an object, begin a for loop, etc) to specific lines in a source code file.

You need both of them for a good debugging experience.

**Comment by JamesNK** [comment]
You could retro-actively publish a source package if you have the same source code and SDK version (I think changes in the compiler could introduce problems).

But I think to be safe you should wait and start publish a symbol package next version. There is no urgency.

**Comment by JamesNK** [comment]
I downloaded the Google.Protobuf package and I noticed you're including the pdb file in the primary NuGet package. If you're happy with that approach then you don't need a symbol package.

**Comment by jtattermusch** [comment]
To be honest, despite including PDBs directly in the nuget package is currently not recommended in the source link documentation (https://github.com/dotnet/sourcelink/#alternative-pdb-distribution), it seems to be the safest and simplest solution at this point. The whole machinery around sourcelink and the new symbol packages seems a bit too complex and it's easy to break things unknowingly (and I can only test the changes manually) - so if things currently work, I'd be leaning towards not changing.

**Comment by JamesNK** [comment]
Ok! I agree that each has their own pros and cons.
