### ISSUE TITLE
Version of protobuf being used?

### ISSUE THREAD

**Issue by hesingh** [protocolbuffers/protobuf#5790]
I have installed protobuf on my Ubuntu 18.04 machine.  I am clueless what version of protobuf it is.  How do I find out?  Do I look at a file in source code or look at any installed libs?  The install used git clone from the github repo.

**Comment by ObsidianMinor** [comment]
The version of protoc and the protobuf libs should match so calling `protoc --version` should give you the correct library version.

**Comment by hesingh** [comment]
Got it - thanks so much!
