### ISSUE TITLE
Can't Serialization

### ISSUE THREAD

**Issue by jsonseng** [protocolbuffers/protobuf#5797]
**What version of protobuf and what language are you using?**
Version: v3.5.0 etc.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Mac

**What runtime / compiler are you using (e.g., python version or gcc version)**
Xcode

**What did you do?**
1. I have a model with 4 ints.
2. If all the fields are 0, it can't be serialization.
3. The `ByteSizeLong` will be 0.

**What did you expect to see**
I want it can serial something out about the default value.

**What did you see instead?**
I can't get any byte by calling serializing operation.

**Comment by TeBoring** [comment]
In proto3, fields with default value are not serialized.
If you want to serialize 0, you need to change from proto3 to proto2.
