### ISSUE TITLE
Protobuf 3.7.0 not published to CocoaPods

### ISSUE THREAD

**Issue by richardtop** [protocolbuffers/protobuf#5798]
**What version of protobuf and what language are you using?**
Version: v3.7.0
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
iOS

**What did you do?**
1. Go to [Protobuf on CocoaPods](https://cocoapods.org/pods/Protobuf)
2. Click 'See Podspec'
3. Scroll down to '"tag": "v3.7.0-rc.3"'
4. See error - The latest version hasn't been released, only release candidate (RC) is available.

**What did you expect to see**
`v3.7.0`
**What did you see instead?**
'v3.7.0-rc.3'
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
```Shell
[!] CocoaPods could not find compatible versions for pod "Protobuf":
  In Podfile:
    Protobuf (= 3.7.0)

None of your spec sources contain a spec satisfying the dependency: `Protobuf (= 3.7.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by cilki** [comment]
Same for Maven Central: [https://search.maven.org/artifact/com.google.protobuf/protobuf-java/3.7.0-rc1/bundle](https://search.maven.org/artifact/com.google.protobuf/protobuf-java/3.7.0-rc1/bundle).

**Comment by TeBoring** [comment]
@acozzette is working a maven. cocoapods has been release.

**Comment by TeBoring** [comment]
Duplicated of #5812

**Comment by chandniKkpl** [comment]
-Delete the podfile.lock 
-Move to ios folder in project. 
cd ios 
-then run the command 
pod install 
Everything is working fine.
