### ISSUE TITLE
Objective-C builder pattern - syntax change

### ISSUE THREAD

**Issue by richardtop** [protocolbuffers/protobuf#5799]
I'm migrating an ObjC project running Protobuf 2.x to Protobuf 3.x and changing the runtime to the latest available.

In the project using the old version, a builder pattern is used extensively:
```Objective-C
MyModelName_Builder * myModelName_Builder = [MyModelName builder];
[myModelName_Builder setParameter: @"asjakjsdak"];
[myModelName_Builder setDamageLevel: @123];
```

In the newer versions calls to create a builder fail. I'm guessing, the builder pattern is no longer used. How should I refactor that code? How to create an object using Protobuf 3.x syntax?

**Comment by richardtop** [comment]
Isn't it working by simply using the object itself as a builder?, e.g.:
```Objective-C
    Model *data = [Model new];
    data.value = @"12345678";
    NSLog(@"%@", data);
```
```Shell
2019-03-01 13:42:34.750693+0200 ProtoTest[34731:785214] <Model 0x60000145b480>: {
    value: "12345678"
}
```

**Comment by thomasvl** [comment]
This library has never had _builders_ for Objective C support.  So it sounds like you were using some other library before and not this one.  So you will need to adapt your code accordingly.

**Comment by richardtop** [comment]
Thanks for clarifying.

I found a plenty of similar libraries, e.g. [minyushov/Protobuf-ObjC](https://github.com/minyushov/Protobuf-ObjC.git) and [booyah/protobuf-objc](https://github.com/booyah/protobuf-objc) which seems to be the base fork for all of those modifications.

Could you please clarify on where do these libraries originate from and how are they related to the Protobuf? I got an impression that it was either an older version of Protobuf or a port of Protobuf to Obj-C before it was available officially. Sorry for such simple questions, I'm new to using Protobuf in ObjC environment.

**Comment by thomasvl** [comment]
I don't have any experience with the other libraries, so I can't really say where they came from.  Internally Google had an objc library, and a few years ago we started including it in the official releases here.

The [reference section](https://developers.google.com/protocol-buffers/docs/reference/overview) has more languages than some other parts of the docs site.  But I don't have much knowledge of the state of docs updates.

**Comment by richardtop** [comment]
Thanks a lot. It seems that the libraries I've mentioned were developed before the release of the internal ObjC library from Google.

The reference section has quite thorough overview, just what I needed.
