### ISSUE TITLE
protobuf-java 3.7.0 was not published to Maven Central

### ISSUE THREAD

**Issue by clehene** [protocolbuffers/protobuf#5812]
As of now the latest version is `3.7.0-rc1`
https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

**Comment by perlun** [comment]
Also noted this. It would be great to get the official `.jar` published to Maven Central.

**Comment by perlun** [comment]
@acozzette Keep us posted, strongly anticipating this one to get rid of the noise when building our software (fixed in #5139).

**Comment by acozzette** [comment]
Let me reassign this to @haon4 who is working on this now.

**Comment by perlun** [comment]
@haon4 Any updates? It would be great to be able to start using the new version ASAP.

**Comment by ejona86** [comment]
3.7.0 builds now appear available on Maven Central.

**Comment by haon4** [comment]
I released it from the staging repository this morning. It is still not showing up for me, but maybe there is some replication delay?

**Comment by ejona86** [comment]
It's on search.maven.org, which is normally the last place for it to show up: https://search.maven.org/search?q=g:com.google.protobuf

It's also on repo1:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/

**Comment by haon4** [comment]
Yea, but it is not on https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java yet. Any idea why?

**Comment by clehene** [comment]
@haon4 great, thank you! They may have not pulled latest changes I suppose, I'm assuming it will come up soon, though.

**Comment by ejona86** [comment]
@haon4, mvnrepository is a random website that has no affiliation with Maven Central, to my understanding. Sort of like JCenter. In no way is it a source of truth and it shouldn't matter if it is out-of-date.

**Comment by haon4** [comment]
Sounds good. Closing this issue then.
