### ISSUE TITLE
Help loading structure specification from `protocol.meta` file in APK

### ISSUE THREAD

**Issue by TheElementalOfCreation** [protocolbuffers/protobuf#5813]
Language: Python

Hi. I'm trying to de-serialize some .protobin files from an APK. However, every time I try, I always get a Unicode error. As the APK itself can load the file without any problems, it stands to reason that the file is using a custom version of the Protobuf format. 

As far as I can tell, the only place for it to store the custom information is inside of the APK's `protobuf.meta` file. However, Even after looking through the Protobuf Python Language Specification, I cannot figure out how I am supposed to load the `protobuf.meta` file so I can use the information in it to de-serialize the .protobin files in the APK. 

Does anyone know how to do this? Perhaps I am actually looking at the wrong file and should be loading a different one? Thanks for any help you guys can give.

**Comment by anandolee** [comment]
Or are you talking about Meta-Protocol? Meta-Protocol is not developed by protocol buffer team, I guess you should ask Meta-Protocol developers instead of here?

**Comment by TheElementalOfCreation** [comment]
The apk has no *.proto files. The only thing inside (other than the *.protobin files) that references protobuf is "protobuf.meta" and brief mentions of it inside the compiled code.

**Comment by TheElementalOfCreation** [comment]
The code SPECIFICALLY references the protobuf format. Let me poke around for mentions of the meta format though.

**Comment by anandolee** [comment]
I am closing it for not a protobuf issue (looks like a Meta-Protocol issue) and clean up. Feel free to reopen if needed

**Comment by TheElementalOfCreation** [comment]
Can someone give me a link to meta protocol? I keep getting a bunch of results that don't seem to be what you are talking about.

By the way, here is the protobin file I am trying to read. It keeps giving me a Unicode error so I know I need something else to help in loading it.
[config.zip](https://github.com/protocolbuffers/protobuf/files/2968778/config.zip)

**Comment by TheElementalOfCreation** [comment]
@anandolee can you give me a link to Meta-Protocol? I can't seem to find the Meta-Protocol project.
