### ISSUE TITLE
Convert PBArray to NSArray

### ISSUE THREAD

**Issue by richardtop** [protocolbuffers/protobuf#5817]
In newer version of Protobuf the array type changed from `NSArray` to `PBArray` and they have incompatible method signatures.

A lot of code has already been written expecting the `NSArray` type.

Given an instance of `PBArray`, how is it possible to convert it to the standard Objective-C `NSArray`?

**Comment by thomasvl** [comment]
This library has never had a PBArray type for Objective C, it sounds like you are using another library instead of this library.  `NSArray`s and boxing aren't used because of the overhead for large arrays.
