### ISSUE TITLE
[Ruby] `Google::Protobuf::ListValue.new(values: []).to_json` is an empty string

### ISSUE THREAD

**Issue by yasyf** [protocolbuffers/protobuf#5824]
**What version of protobuf and what language are you using?**
Version: 3.7.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Any

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 2.6.0

**What did you do?**

```
2.6.0 :044 > Google::Protobuf::ListValue.new(values: []).to_json
 => ""
```

This causes calling `to_json` on a Struct with an empty array as a value for some key to output invalid json (e.g. you get `{key:}`)

```
2.6.0 :061 > Google::Protobuf::Struct.new(fields: { 'key' => Google::Protobuf::Value.new(list_value: Google::Protobuf::ListValue.new(values: [])) }).to_json
 => "{\"key\":}"
```

**What did you expect to see**

`{key: []}` (the output of `Google::Protobuf::ListValue.new(values: []).to_json` should be `"[]"`.

e.g. the above should be:

```
2.6.0 :061 > Google::Protobuf::Struct.new(fields: { 'key' => Google::Protobuf::Value.new(list_value: Google::Protobuf::ListValue.new(values: [])) }).to_json
 => "{\"key\":[]}"
```

**Comment by TeBoring** [comment]
Fixed in #5857. PTAL
