### ISSUE TITLE
Can I re-use object instances to avoid allocations with protobuf-java?

### ISSUE THREAD

**Issue by wangshifeng** [protocolbuffers/protobuf#5825]
I have high volume of message to parse,I found GC becoming very frequently.

<img width="1420" alt="2" src="https://user-images.githubusercontent.com/8359690/53771438-820cf700-3f1d-11e9-9583-91f9b603454e.png">

How to avoid allocations memory? Object pool? How to implement?

**Comment by haon4** [comment]
We do a lot of memory allocation in Java. One thing you can try is to use an object pool for the Builder, and only pass the Builder around without building it into a Message. That may be able to reduce some memory allocation, but obviously the Builder is mutable and not thread-safe, so use that at your own risk. Other than that I cannot think of any other way to reduce memory allocation in Java.
