### ISSUE TITLE
blade protobuf error

### ISSUE THREAD

**Issue by sddi** [protocolbuffers/protobuf#5832]
I am using blade build the project(v3.4.0), but I get the error:

~/typhoon-blade/src/blade/load_build_files.py", line 172, in _load_build_file
    execfile(build_file, __current_globles, None)
  File "thirdparty/protobuf/BUILD", line 3, in <module>
    licenses(["notice"])
NameError: name 'licenses' is not defined

my python version: 2.7.5
protobuf version: 3.4.0

**Comment by acozzette** [comment]
We have not tried to support the Blade build system and I actually I had not heard of Blade until just now. Is Blade intended to be compatible with Bazel?

**Comment by TeBoring** [comment]
Welcome to send us a fix.
