### ISSUE TITLE
Create repository to host community-contributed TextMate grammar for .proto language

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#5833]
We discussed this offline.

The repository would live under https://github.com/protocolbuffers/ organization,
the textMate grammar would be contributed by community first and at some point (given enough adoption and confirmation that it's useful) it could be promoted to "official" grammar.

Some other ideas around this:
- gRPC has a separate "grpc-ecosystem" organization for vetted project that the gRPC team doesn't necessarily control. Maybe protobuf could use a similar concept?  see https://github.com/grpc-ecosystem/
- to reduce the barrier to entry, we could also consider adding protobuf textmate grammar as a repo under grpc-ecosystem first (and promote it later).

**Comment by jtattermusch** [comment]
CC @anandolee 
CC @JunTaoLuo  @JamesNK @davidfowl @shirhatti

**Comment by ObsidianMinor** [comment]
Could a [tree-sitter](https://tree-sitter.github.io/tree-sitter/) grammar for Atom (and possibly other editors that add support) also be included?

**Comment by haon4** [comment]
Thanks for filing this request. I have a chat with Jayant (my manager) who is an admin to the protocolbuffers Org. He is fine with creating the repository, but he would like the following to be provided to him first so he can bootstrap the repo:
1) A good name for the repo :)
2) A README.md file describing the repo
3) A LICENSE file (similar to https://github.com/protocolbuffers/protobuf/blob/master/LICENSE)
4) A CONTRIBUTING.md file, similar to https://github.com/protocolbuffers/protobuf/blob/master/CONTRIBUTING.md, which requires contributors to sign the CLA.

Thanks!

**Comment by jtattermusch** [comment]
> Thanks for filing this request. I have a chat with Jayant (my manager) who is an admin to the protocolbuffers Org. He is fine with creating the repository, but he would like the following to be provided to him first so he can bootstrap the repo:
> 
> 1. A good name for the repo :)

how about protocolbuffers/protobuf-grammar ?

> 2. A README.md file describing the repo
> 3. A LICENSE file (similar to https://github.com/protocolbuffers/protobuf/blob/master/LICENSE)

Unless they are specific requirements, should this be Apache2?

> 4. A CONTRIBUTING.md file, similar to https://github.com/protocolbuffers/protobuf/blob/master/CONTRIBUTING.md, which requires contributors to sign the CLA.
> 
> Thanks!

**Comment by haon4** [comment]
@Jan, would you mind bundling all of required files and send them to Jayant? He can then create the repo.

**Comment by jtattermusch** [comment]
@haon4  let's create a private repository first, populate it with all needed files and then we can make it public once we are happy with it.

**Comment by jan** [comment]
@haon4 hello world!

**Comment by haon4** [comment]
Oh, sorry I cc-ed the wrong jan!

@jtattermusch, SG. Let's follow up with Jayant offline.

**Comment by haon4** [comment]
Jayant has created the repo. Passing on to jtattermusch to populate it and hand off to the relevant folks.

**Comment by jtattermusch** [comment]
@JunTaoLuo @JamesNK @davidfowl @shirhatti   the repository has been created

https://github.com/protocolbuffers/protobuf-grammar
