### ISSUE TITLE
Unable to find protobuf version 2.2

### ISSUE THREAD

**Issue by richardtop** [protocolbuffers/protobuf#5834]
**What version of protobuf and what language are you using?**
Version: v2.2

**What did you do?**
1. Go to '[Download Protocol Buffers](https://developers.google.com/protocol-buffers/docs/downloads).'
2. Click on 'If you still need an old version for some reason, you can find our historical releases here.'
3. Get redirected to this repository
4. Unable to find protobuf v2.2. The oldest release available is v2.4.1

**What did you expect to see**
protobuf v2.2 source

**What did you see instead?**
protobuf v2.4.1 source

Where is it possible to download even older versions of protobuf?

**Comment by acozzette** [comment]
I don't think we have kept the releases going back that far. Version 2.2 is almost 10 years old now so ideally it would really be much better to upgrade to a newer version. But if you really want to use 2.2, probably your best bet is to check out an old Git commit and build from there. Based on the history of the `CHANGES.txt` file, it appears that commit 201b9be95d86f79ec8beb46a556975292af880e0 is version 2.2.
