### ISSUE TITLE
Generated protobuf classes segfault with PHP5 when using C extension

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#5837]
Version: v3.7.0
Language: PHP5
OS: macOS 10.13.6

```sh
# Build protoc
$ git clone https://github.com/protocolbuffers/protobuf.git
$ cd protobuf
$ git submodule update --init --recursive
$ ./autogen.sh
$ ./configure
$ make
$ make check

# Generate test files
$ pushd php/tests
$ mkdir generated
$ ../../src/protoc --php_out=generated         \
    -I../../src -I.                            \
    proto/empty/echo.proto                     \
    proto/test.proto                           \
    proto/test_include.proto                   \
    proto/test_no_namespace.proto              \
    proto/test_prefix.proto                    \
    proto/test_php_namespace.proto             \
    proto/test_empty_php_namespace.proto       \
    proto/test_reserved_enum_lower.proto       \
    proto/test_reserved_enum_upper.proto       \
    proto/test_reserved_enum_value_lower.proto \
    proto/test_reserved_enum_value_upper.proto \
    proto/test_reserved_message_lower.proto    \
    proto/test_reserved_message_upper.proto    \
    proto/test_service.proto                   \
    proto/test_service_namespace.proto         \
    proto/test_wrapper_type_setters.proto      \
    proto/test_descriptors.proto
$ pushd ../../src
$ ./protoc --php_out=../php/tests/generated -I../php/tests -I. \
    ../php/tests/proto/test_import_descriptor_proto.proto
$ popd
$ popd

# Install protobuf extension and run tests
$ pecl install protobuf-3.7.0
$ cd php
$ composer install
$ vendor/bin/phpunit
```

Output:

```sh
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...............PHP Fatal error:  Generated message class Bar\TestLegacyMessage hasn't been defined in /Users/dsupplee/dev/protobuf/php/tests/generated/GPBMetadata/Proto/TestInclude.php on line 27

Fatal error: Generated message class Bar\TestLegacyMessage hasn't been defined in /Users/dsupplee/dev/protobuf/php/tests/generated/GPBMetadata/Proto/TestInclude.php on line 27
[1]    75861 segmentation fault  /Users/dsupplee/homebrew/Cellar/php@5.6/5.6.40/bin/php vendor/bin/phpunit
```

The error bubbles up from [here](https://github.com/protocolbuffers/protobuf/blob/59cc6d01ac0916258e68359f6f062532a85966ae/php/ext/google/protobuf/def.c#L961) and will require some more research to understand what is going on.

**Comment by TeBoring** [comment]
Do this happen for user? Or just you are running our test repo?

**Comment by dwsupplee** [comment]
Hi @TeBoring. Yes, this appears to occurs for users as well. For example:

```sh
$ composer require google/cloud
```

```php
<?php

require 'vendor/autoload.php';

use Google\Cloud\Spanner\V1\SpannerClient;

$client = new SpannerClient;
$client->getSession(
    'projects/my-project/instances/my-instance/databases/my-database/sessions/my-session'
);
```

Output:

```
Fatal error: Generated message class Grpc\Gcp\ChannelPoolConfigg hasn't been defined in /Users/dsupplee/dev/google-cloud-php/vendor/google/grpc-gcp/src/generated/GPBMetadata/GrpcGcp.php on line 35
[1]    39373 segmentation fault  /Users/dsupplee/homebrew/Cellar/php@5.6/5.6.40/bin/php ex.php
```

**Comment by TeBoring** [comment]
One work around is, when using c extension, remove protobuf from composer.json and do ```composer update```

**Comment by TeBoring** [comment]
I think before 3.7.0, the issue already exists.
The issue is, when c extension is enabled, ```class_exists(TestLegacyMessage\NestedEnum::class)``` in the file ```TestLegacyMessage_NestedEnum.php``` cannot trigger loading ```TestLegacyMessage\NestedEnum.php```.
The way to solve it is explicitly import the generated file of ```TestLegacyMessage\NestedEnum```

**Comment by TeBoring** [comment]
I tried to run the same test in v3.6.1 repo. Also got segmentation fault.

**Comment by dwsupplee** [comment]
I got a segfault with v3.6.1 when running this repo's tests as well, but it appears to be for an unrelated issue:

```sh
Fatal error: Call to undefined method Google\Protobuf\Internal\DescriptorPool::addMessage() in /Users/dsupplee/dev/protobuf/php/src/GPBMetadata/Google/Protobuf/Internal/Descriptor.php on line 17
[1]    11741 segmentation fault  /Users/dsupplee/homebrew/Cellar/php@5.6/5.6.40/bin/php vendor/bin/phpunit
```

It is worth noting using the v3.6.1 extension in userland code as demonstrated [here](https://github.com/protocolbuffers/protobuf/issues/5837#issuecomment-469968930) worked just fine for me, though. I think this may be isolated to v3.7.0, unfortunately 😢.

**Comment by dwsupplee** [comment]
Quick update: I isolated the point at which the issue was introduced. When compiling the extension with the commit prior to https://github.com/protocolbuffers/protobuf/commit/53a1d49633f1e4396c11d1fe593268793a118fc3 PHP5 works fine.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/DescriptorPool.php#L58

Is it because the signature for ```internalAddGeneratedFile``` is different between php and c extension?

**Comment by TeBoring** [comment]
Add the boolean in ```internalAddGeneratedFile``` in php implementation may work.

**Comment by dwsupplee** [comment]
Good eye - but would that be causing the issue as the native PHP implementation's codepath isn't executed when the extension is enabled?

**Comment by dwsupplee** [comment]
I might have found a fix, please let me know what you think.

While debugging the output of `namesink.ptr` [here](https://github.com/protocolbuffers/protobuf/blob/59284450fa2a85f9f355b4de5a733323af094dcf/php/ext/google/protobuf/def.c#L858) I noticed in PHP7 I was getting garbled output such as `Google\Cloud\AutoMl\V1beta1\InputConfignfig` when it should be `Google\Cloud\AutoMl\V1beta1\InputConfig`, for example. This lead me to looking into `stringsink_string`:

https://github.com/protocolbuffers/protobuf/blob/59284450fa2a85f9f355b4de5a733323af094dcf/php/ext/google/protobuf/encode_decode.c#L45-L66

To fix this while using `memcpy` I needed to add a terminating character, for example:

```c
memcpy(sink->ptr + sink->len, ptr, len);
sink->len += len;
sink->ptr[sink->len] = '\0';
```

Alternatively, we could replace line 62 with `strcpy(sink->ptr + sink->len, ptr);`, but I defer to your expertise in this area. With either of these changes in place, the extension now works correctly with PHP5.

It still isn't clear to me why PHP7 was performing no problem with the garbled classnames whereas PHP5 was failing, but at least this is progress :).

Let me know if either of these solutions sound reasonable to you and I'm happy to get a PR in.

**Comment by TeBoring** [comment]
I think I made a mistake.
stringsink creates non-null terminated string. However, in php5, zend_lookup_class expect null-terminated string.
I guess master has fixed this. Could you try master branch?

**Comment by dwsupplee** [comment]
`master` is still broken on PHP5 for me.

**Comment by TeBoring** [comment]
The correct way to append a null should be calling ```stringsink_string(classname, NULL, "\0", 1, NULL);``` at the end of ```fill_qualified_classname```

**Comment by dwsupplee** [comment]
🤔  I get a segfault on PHP5/7 with that approach (see my addition [here](https://github.com/dwsupplee/protobuf/commit/d17d118f5c272553098d6f68ab6df290d02897c6)).

The output:

```sh
Fatal error: Generated message class Google\Api\Http hasn't been defined (google.api.Http, google.api, (null), (null)) in /Users/dsupplee/dev/google-cloud-php/vendor/google/common-protos/metadata/Api/Http.php on line 37
[1]    79894 segmentation fault 
```

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/3.7.x/php/ext/google/protobuf/def.c#L959
When you call php_proto_zend_lookup_class, should you use ```namesink.len - 1```

**Comment by dwsupplee** [comment]
That did the trick, thanks @TeBoring :).

**Comment by TeBoring** [comment]
Could you send a PR to reproduce the bug first?

**Comment by dwsupplee** [comment]
I believe [this test case](https://github.com/protocolbuffers/protobuf/blob/master/tests.sh#L491-L498) and other similar ones would expose the issue - but they're commented out. Since you added the note commenting them out, is there anything blocking them from being added back in? I'd be happy to help get them back into a working state.

**Comment by TeBoring** [comment]
Oh, previously I commented it out because it has a different failure list compared with php7.
You can try to add it back (probably need to create another failure list for php5 c).
I doubt it shows the issue. I think the way to reproduce this issue should be using composer and c extension together to run the test.

**Comment by TeBoring** [comment]
I think you can try ```php -dextension=./ext/google/protobuf/modules/protobuf.so ./vendor/bin/phpunit``` in the php dir.
