### ISSUE TITLE
[Java] When is a release pushed to Maven Repository/JCenter?

### ISSUE THREAD

**Issue by hpuac** [protocolbuffers/protobuf#5845]
Hello folks,

I just wanted to ask when a release is pushed to Maven Repository/JCenter?
For example the version 3.7.0 was released here on Github 6 days ago and it's not available yet in the other repositories.
Is there any review process ongoing or is there a special workflow or was it just forgotten?
Thank you in advance!

Cheers
  Hans

**Comment by julesjacobsen** [comment]
see #5812

**Comment by hpuac** [comment]
@julesjacobsen perfect, thank you!
