### ISSUE TITLE
Conflict when using same proto files in two java libraries

### ISSUE THREAD

**Issue by JonasVautherin** [protocolbuffers/protobuf#5847]
Say I have a proto file, `my_proto_file.proto`.

I create a java "client" library `libClient` based on `my_proto_file.proto`. I create a java "server" library `libServer` based on `my_proto_file.proto`.

That works well, and I can use the resulting `com.package.MyProtoFile` class in both libraries independently. They can communicate with each other because they implement the same protocol.

Now say I decide to write one java app (e.g. and Android app) that will use both `libClient` and `libServer`. Because `com.package.MyProtoFile` is defined in both libraries, it ends up in an error like:

```
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.package.MyProtoFile$1
```

However, my libraries don't need to expose `MyProtoFile` at all (say the server only needs to be run by the java application).

Is there a way to fix that, e.g. by telling `libServer` to not expose `MyProtoFile`, or by making sure that they end up being the same file in my app?

**Comment by BSBandme** [comment]
How did you create the android app? I'm afraid in protobuf layer there's no way to resolve this diamond dependencies issue. Usually you should split `libClient` and `libServer` into `libClient + protoLib` and  `libServer + protoLib`, then depend on all in your android app to solve this kind of issue.
