### ISSUE TITLE
Update Source Link package

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#5850]
**What language does this apply to?**
C#

Google.Protobuf is using `SourceLink.Create.CommandLine` for Source Link. That is an old package that has been replaced with `Microsoft.SourceLink.*` packages.

More info: https://github.com/ctaggart/SourceLink

This is the modern package: https://www.nuget.org/packages/Microsoft.SourceLink.GitHub

**Comment by jtattermusch** [comment]
Related bug: https://github.com/grpc/grpc/issues/18287

**Comment by jtattermusch** [comment]
Can you confirm that stepping into the code when debugging is currently broken for you?

**Comment by jtattermusch** [comment]
I just tried source stepping with Google.Protobuf 3.7.0  and it wasn't working for me (with VS2017).
