### ISSUE TITLE
MessageMapContainer.GetEntryClass Segmentation Fault

### ISSUE THREAD

**Issue by chazmead** [protocolbuffers/protobuf#5851]
**What version of protobuf and what language are you using?**
```
$ python --version
Python 3.7.0
$ pip freeze | grep proto
googleapis-common-protos==1.5.6
protobuf==3.6.1
```

**What operating system (Linux, Windows, ...) and version?**
```
$ uname -a
Linux debian 4.10.12debian-rbs #1 SMP Thu Apr 27 00:02:08 BST 2017 x86_64 GNU/Linux
```

**What runtime / compiler are you using (e.g., python version or gcc version)**
```
$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
```

**What did you do?**
1. Create a protocol buffer file:
test_message.proto
```
message MessageA {
    map<string,MessageB> test_composite_map = 1;
}

message MessageB {
    string test_field = 1;
}
```
2. Compile this to a `_pb2.py` file
3. Attempt to access the `.GetEntryClass()` method of the MessageA class:
```
$ python
Python 3.7.0 (default, Oct 15 2018, 11:04:53) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pb.test_message_pb2 import MessageA
>>> MessageA().test_composite_map
<google.protobuf.pyext._message.MessageMapContainer object at 0x7f3e68182b10>
>>> _.GetEntryClass  
<built-in method GetEntryClass of google.protobuf.pyext._message.MessageMapContainer object at 0x7f3e68182b10>
>>> MessageA().test_composite_map.GetEntryClass()
Segmentation fault
$ 
```

**What did you expect to see**
I assume this is meant to return the buffer class for the Map value?  at least thats what I was looking for when I came across this.

**What did you see instead?**
`Segmenation fault`

**Comment by anandolee** [comment]
Looks like the reason is map container keeps week reference of message. Python GC which can deal with reference cycle may able to solve it. Before this issue is fixed, you can use:
msg = MessageA()
msg.test_composite_map.GetEntryClass()

**Comment by anandolee** [comment]
Update: a new strategy to manage memory of Message objects has been submitted in google internal.  In next release, sub-objects will have strong references to their parents. This issue will be fixed by the new memory strategy.
