### ISSUE TITLE
Is protobuf2.4.1 support python3?

### ISSUE THREAD

**Issue by topxxuki** [protocolbuffers/protobuf#5856]
i can install protobuf-3.7.0 on my Ubuntu 4.8.4 (gcc 4.8.2 python 3.6.2)

BUT WHEN I try to download protobuf 2.4.1, it says:
![image](https://user-images.githubusercontent.com/18697846/54005632-2482df80-4195-11e9-9ba3-32eeb4fe1863.png)

**Comment by anandolee** [comment]
protobuf2.4.1 was release on 2011 Aug, none of our current team members have joined protobuf team at that time. But from the error message, python 3 is not supported in protobuf 2.4.1
