### ISSUE TITLE
'google/protobuf/port_def.inc' file not found

### ISSUE THREAD

**Issue by luyuekai** [protocolbuffers/protobuf#5868]
I receive the following error when compiling my source code while linking protobuf and including the generated header file:

```cpp
****.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
#include <google/protobuf/port_def.inc>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I have tried re-installing protobuf but can't seem to resolve the issue.
Then, I have tried 
```shell
cd /usr/local/include && ll

```
there is not  `protobuf/lib` in output.  And I tried everything that I can , but it didn't help.  I think it has to do with the include library。I can't solve this problem for the time being.  Please give me some solutions, thanks a lot.

OS_VERSION: macOS Mojace 10.14.1
IDE ： CLion
```shell
protoc --version
libprotoc  3.7.0
```

**Comment by pacaletx** [comment]
I have the same issue, is it possible to have a solution ? Is it solved for you ?

**Comment by luyuekai** [comment]
> I have the same issue, is it possible to have a solution ? Is it solved for you ?
 Finally, I learned that this problem had nothing to do with protobuf. I compile C++ with cmake。 And the CMakeLists.txt doesn't contain protobuf configuration。 When I add protobuf configuration , it works.

**Comment by pacaletx** [comment]
OK, I'm with make so problem is different :/ thanks.

**Comment by yosry95** [comment]
> > I have the same issue, is it possible to have a solution ? Is it solved for you ?
> 
> Finally, I learned that this problem had nothing to do with protobuf. I compile C++ with cmake。 And the CMakeLists.txt doesn't contain protobuf configuration。 When I add protobuf configuration , it works.

How did you added the protobuf configuration. I am using the CMakeLists.txt provided by the latest version of protobuf and I am facing the same problem.

**Comment by bidai541** [comment]
hi, I met  this problem too with protobuf 3.6.
I found nothing by <find  . -name "*.inc">  in the path of protobuf(/usr/local/opt/protobuf@3.6/).
Share your details please.

**Comment by MiguelAlgaba** [comment]
@luyuekai could you share which configuration you used to solve this issue?

**Comment by entn-at** [comment]
I had the same problem when building a project with cmake version 3.13. Using cmake 3.10 there were no errors. I wonder if there's a problem with the FindProtobuf cmake module in more recent versions.

**Comment by dongpil** [comment]
add this to your `CMakeLists.txt`
```include_directories(${Protobuf_INCLUDE_DIRS})```

**Comment by Glavnokoman** [comment]
@bidai541
`google/protobuf/port_def.inc` is included in headers generated by protoc version >= 3.7.0 (please correct my if I am wrong). So the protoc used to compile the messages is different from protobuf library you are using. Hope this helps.

**Comment by PaulZhangIsing** [comment]
The problem is this:
When I use protoc --version, it shows my system has version 3.7.1.
However, my piped protobuf tells me it hasa version 2.6.1
What should I do in this case???

**Comment by tglanz** [comment]
I had a similar scenario as explained below, hope it'll help

Scenario
1. generate the cpp-client code through a maven project, which used protobuf-compiler plugin - version __3.11.0__
2. had a protobuf-complier __3.0.0__ installed on my machine (installed through apt)
3. got the same error when trying to compile

@Glavnokoman made me check the versions and notice they are different - one above 3.7.0 one below

My solution was to download a matching protobuf-compiler source from the [available releases](https://github.com/protocolbuffers/protobuf/releases), and adding the source directory as additional include path.

**Comment by qcarver** [comment]
Hello, 
As per the MSVC++ build instructions I installed vcpkg.
So that my project could find the file in question, I simply included:
   `vcpkg\buildtrees\protobuf\src\a5c431386a-c9deea9e31.clean\src`
in my project.
V/R-QC

**Comment by fertakis** [comment]
For anyone still interested in this, I was facing the same issue. In order to make it work, I had to configure my `CMakeList.txt` to include the following: 

`find_package(Protobuf REQUIRED)

include_directories(${PROTOBUF_INCLUDE_DIRS})`

**Comment by ivanovaleksey** [comment]
@fertakis I have this in my CMakeList.txt but it still doesn't work.
Also in generated header file I have
```
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
```
which gets printed. Though I don't understand why this `if` statement equals to `true`.

I got the only protobuf installed via Homebrew.

**Comment by ivanovaleksey** [comment]
Also my generated `*.ph.h` file contains two `#include <google/protobuf/port_def.inc>` directives.
But this `port_def.inc` says that it should be included only once in the very end.

**Comment by Coxhuang** [comment]
find_package(Protobuf REQUIRED)
include_directories(
        ${Protobuf_INCLUDE_DIRS}
)

**Comment by warminn** [comment]
Cannot use  https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip to install, because port_def.inc is not included in that package.
Should use source code to compile and install, then you can find port_def.inc
It may be a bug!
![image](https://user-images.githubusercontent.com/5452836/100817878-ef97df80-3483-11eb-87cb-14ac86f59e71.png)

**Comment by aardvarkk** [comment]
In my case, I run Debian and was using `libprotobuf-dev` as installed via the `buster` (stable) repo. Unfortunately, that left me with version 3.6.1.3 of protobuf, which *does not include* port_def.inc. I added the `buster-backports` repo to be able to upgrade to version 3.12.3-2 which contained the required file.
