### ISSUE TITLE
protoc marking generated C++ classes final as of 3.7

### ISSUE THREAD

**Issue by JoshDreamland** [protocolbuffers/protobuf#5869]
**What version of protobuf and what language are you using?**
Version: 3.6.1, 3.7
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, various (Arch Linux, Ubuntu, Debian)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Various; this system uses GCC 8.2.1 20181127

**What did you do?**
Run protoc to generate C++ for a given proto message.

**What did you expect to see**
Prior to version 3.7, classes generated for proto messages were not final. My project has code extending proto messages to add helper functions which index and operate on field values. The code in question builds successfully through protoc 3.6.1. I expected this to continue to be the case.

**What did you see instead?**
The build fails in 3.7 because protoc now tags `final` onto codegen. This change isn't mentioned anywhere that I can find (release notes, documentation) and there doesn't seem to be a flag to control this behavior. To my knowledge, there is also no flag to control the target C++ standard, so we cannot work around this issue by targeting C++03 (before `final` was introduced).

**Anything else we should know about your project / environment**
This issue does not seem specific to any environment.

**Comment by BSBandme** [comment]
I think starting from 3.6 we require C++11 (see #2780).

**Comment by JoshDreamland** [comment]
I certainly wouldn't complain about most of the features that came with C++11. But `final` doesn't seem to add anything to the code, and it breaks our project's build (and probably others, who I expect to chime in after a couple more months as 3.7 rolls out).

**Comment by acozzette** [comment]
The documentation [here](https://developers.google.com/protocol-buffers/docs/cpptutorial#parsing-and-serialization) does officially warn against inheriting from generated message types. However, it's still true that we made this change without giving it much of an announcement at all. It is beneficial because it allows the compiler to take advantage of more optimizations, but maybe we need to introduce a temporary opt-out mechanism to give projects time to refactor.

**Comment by rchav** [comment]
This is a huge problem for us, would def appreciate an option to disable.

**Comment by Arfrever** [comment]
This change also breaks building of Google Mozc project. An option to avoid `final` (at least per-class) would be nice.

**Comment by Plegsd** [comment]
> **What version of protobuf and what language are you using?**
> Version: 3.6.1, 3.7
> Language: C++
> 
> **What operating system (Linux, Windows, ...) and version?**
> Linux, various (Arch Linux, Ubuntu, Debian)
> 
> **What runtime / compiler are you using (e.g., python version or gcc version)**
> Various; this system uses GCC 8.2.1 20181127
> 
> **What did you do?**
> Run protoc to generate C++ for a given proto message.
> 
> **What did you expect to see**
> Prior to version 3.7, classes generated for proto messages were not final. My project has code extending proto messages to add helper functions which index and operate on field values. The code in question builds successfully through protoc 3.6.1. I expected this to continue to be the case.
> 
> **What did you see instead?**
> The build fails in 3.7 because protoc now tags `final` onto codegen. This change isn't mentioned anywhere that I can find (release notes, documentation) and there doesn't seem to be a flag to control this behavior. To my knowledge, there is also no flag to control the target C++ standard, so we cannot work around this issue by targeting C++03 (before `final` was introduced).
> 
> **Anything else we should know about your project / environment**
> This issue does not seem specific to any environment.

**Comment by JoshDreamland** [comment]
I can appreciate compiler optimizations. But this eliminates a solution to another issue with proto that I know has been discussed a lot in the past: adding more accessors. For instance, an `Area()` routine on a `Rectangle` message. Has there been any progress on formalizing that feature request?

**Comment by Expurple** [comment]
The C++ project that I'm working on also broke because of this. In case anyone still needs it, here's the hack that I've come up with. Add a build step that calls

>`sed --in-place 's \bfinal\b /*final*/ ' <AUTOGENERATED_FILE>`

on files generated by `protoc`.

**Comment by emenchen** [comment]
@acozzette Add me to the list of people that would like an opt-out mechanism. I have a fair bit of existing code that subclasses a protobuf generated class, and many clients of that code which will have to be changed without an opt-out. I will likely employ a hack like @Expurple.

You commented that subclassing has been discouraged and pointed to the documentation which states, "You should never add behavior to the generated classes by inheriting from them. This will break internal mechanisms and is not good object-oriented practice anyway." I question this and wonder if you can provide additional insight as to why this might not be good practice, and what would break given the following:
`package MyPackage
message Rectangle {
  int32 x1 = 1;
  int32 x2 = 2;
  int32 y1 = 3;
  int32 y2 = 4;
  int32 line_width = 5;
}`
with a subclass like:
`class RectHelper : public MyPackage::Rectangle {
  RectHelper& set_coordinates(::google::protobuf::int32 x1, ::google::protobuf::int32 x2,
    ::google::protobuf::int32 y1, ::google::protobuf::int32 y2) {
    set_x1(x1);
    set_x2(x2);
    set_y1(y1);
    set_y2(y2);
    return *this;
  }
};`
Here I've added a helper, without adding new data or anything that needs to be serialized. This helper (or other code like it) may eliminate a lot of repetitive lines of code elsewhere. Yes, I could make a wrapper class, but I still want to expose all of the original functionality of the original protobuf class. To do this would require repeating all of those methods, or exposing the contained object, neither of which seem desirable or better than this. I could make a standalone function, and that might be the route I explore in the future, but that also takes away a lot of the convenience of the subclass in other situations.

**Comment by emenchen** [comment]
@acozzette Thanks for the quick reply. Of course my rectangle example was perhaps too simple. My current derived classes have other methods that implement something of a "builder" interface to allow chaining and simple code on the client side, but not always so simple in the derived class. I'm thinking of how to implement something with a set of standalone functions, but it isn't as straightforward as this simple case.

**Comment by XplicitComputing** [comment]
It is not okay to artificially constrain the library by implementing `final`, because it precludes downstream (advanced automation) implementations to specialize. For this reason, Xplicit Computing Inc is internally constrained to version `3.7` for building its code-generated `libxccommon` libraries, which provide `server-client` functionalities. Luckily, my understanding is that customer can still us any Protoc 3 compiler... but we're stuck on this old version that works -- and frankly are starting to assess alternative serialization techniques. Google Protobuf team, please revert this feature back and re-assess such design constraints.

**Comment by XplicitComputing** [comment]
at least give us the option `--no-final`

**Comment by fowles** [comment]
This change was made quite deliberately and provides a meaningful performance improvement when applied at scale.  The classes themselves have always been documented as not being suitable for derivation.  I would encourage you to consider containment over inheritance as a more efficient paradigm.

**Comment by XplicitComputing** [comment]
Significant investments have been made applying the Protobuf3 infrastructure. A better paradigm as library maintainers would be to not functionally change the spec after it has been deployed... and if so, allow the option for `--no-final`. I will discuss with our meta-programming experts, but as mentioned there are implications of a class being of a type, verses containing or having said type. There may literally not be a computer science opportunity for containment.

From a science and engineering professional perspective, it is generally not acceptable to do what has been done here. This may force us to migrate to Cern::Root sooner than initially planned.

**Comment by XplicitComputing** [comment]
At ICCFD11 two days ago, I just presented protobuf as a viable method for communicating messages between science and engineering teams. Perhaps I was wrong.

**Comment by XplicitComputing** [comment]
Thank you for the info.
I've heard back from our protocol library lead and apparently we were able to sidestep this issue. 
We are now tracking what appears to be a separate issue that appeared in v3.8 but nothing concrete yet. Likely unrelated and probably not your problem
