### ISSUE TITLE
Consider adding `Interval` as a well known type

### ISSUE THREAD

**Issue by mkobit** [protocolbuffers/protobuf#5870]
**Describe the problem you are trying to solve.**

Representing time is a fairly common pattern, so being able to use a built-in protobuf types is desirable for us to avoid inventing our own (if possible). Today, there exists the `Duration` and `Timestamp` types, so building on top of those and introducing additional time types could be useful.

Some services we have have built their own `Interval` types similar to the ones mentioned below. This means that each type is essentially the same, but require different imports and generation techniques. This can be especially annoying when dealing with multiple services that have identical `Interval` definitions but they are generated with different `package`s.

**Describe the solution you'd like**

A built-in protobuf type that might look like:

```
import "google/protobuf/timestamp.proto";

message Interval {
    google.protobuf.Timestamp start_inclusive = 1;
    google.protobuf.Timestamp end_exclusive = 2;
}
```

or

```
import "google/protobuf/timestamp.proto";

message Interval {
    google.protobuf.Timestamp start = 1;
    google.protobuf.Timestamp end = 2;
    bool is_end_inclusive = 3;
}
```

Or

```
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

message Interval {
    google.protobuf.Timestamp start = 1;
    google.protobuf.Duration duration = 2;
}
```

(I've seen a few different versions here)

**Describe alternatives you've considered**

We have been considering implementing our own common protobuf types package but that might introduce more overhead to users.

**Additional context**

**Comment by haon4** [comment]
Thanks for the suggestions! This sounds reasonable. I'll try to bring this up to the team and see if everyone is okay with this proposal.

**Comment by haon4** [comment]
Hi Mike. I brought this up to the team. One of the criteria we have for introducing new well known type is check if it is also offered as a basic building block at the language level. While there are many applications for a time interval type, it is not in the standard library for C++, Java, Python, etc. As such, we are unwilling to commit to a "well known" Interval type at the Protobuf level. Thank you for your suggestion, though.

**Comment by palladius** [comment]
I would humbly ask to reconsider the decision. 
This has recently made it to the "standard Google collection of basic types" (Googlers, see //google/type).
I've been actually bashed for saying it is *not* standard :)
