### ISSUE TITLE
PHP: GPBWrapperUtils not found in Google\Protobuf\Internal

### ISSUE THREAD

**Issue by AxiosCros** [protocolbuffers/protobuf#5874]
Version： protoc v3.7.0
Language: PHP

not found "`GPBWrapperUtils`" in [`php/src/Google/Protobuf/Internal`](https://github.com/protocolbuffers/protobuf/tree/master/php/src/Google/Protobuf/Internal), 
when use Google\Protobuf\Internal\GPBWrapperUtils in php code.

**Comment by TeBoring** [comment]
I think we never provided that class.

**Comment by AxiosCros** [comment]
> I think we never provided that class.

so, why use that in here [php/src/Google/Protobuf/Internal/DescriptorProto.php](https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/DescriptorProto.php) 


``` php
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto
namespace Google\Protobuf\Internal;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBWire;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\InputStream;
use Google\Protobuf\Internal\GPBUtil;

use Google\Protobuf\Internal\GPBWrapperUtils;  // <====== where is it?
```
