### ISSUE TITLE
DebugString  enum type

### ISSUE THREAD

**Issue by clsgg** [protocolbuffers/protobuf#5883]
When I use the DebugString() function to print a message with an enum type, why is the first element of the enum type not printed, but other elements can?
![DeepinScrot-1155](https://user-images.githubusercontent.com/29628624/54281424-b004d200-45d4-11e9-9fbd-3117417f24f1.png)
![DeepinScrot-1307](https://user-images.githubusercontent.com/29628624/54281502-d4f94500-45d4-11e9-832d-dac6e5341711.png)

**Comment by acozzette** [comment]
With proto3 there is no difference between a singular primitive field being empty and being set to its default value (see [here](https://developers.google.com/protocol-buffers/docs/proto3#default)). As a result E1 is not printed out because it is just the default value for that field.

**Comment by nejcgalof** [comment]
@acozzette Is there any option to print default values?

**Comment by clsgg** [comment]
> 
> 
> @acozzette Is there any option to print default values?
I add an invalid element as the default to circumvent this problem，for example:
enum ProjectionType{
  ProjectionTypeUnspecified=0;
  Gauss_3=1;
  Gauss_6=2;
  UTM=3;
}

**Comment by acozzette** [comment]
No, as far as I know there is no option to print default values in text format.
