### ISSUE TITLE
[Ruby] Decoding JSON raises ParseError on Windows

### ISSUE THREAD

**Issue by blowmage** [protocolbuffers/protobuf#5884]
**What version of protobuf and what language are you using?**

Version: v3.7.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 2.6.1

**What did you do?**

Install latest google-cloud-pubsub and google-protobuf gems, and run this code:

```ruby
require "google/cloud/pubsub/v1"

now = Time.now
now_ts = Google::Protobuf::Timestamp.new seconds: now.to_i, nanos: now.nsec
msg = Google::Cloud::PubSub::V1::PubsubMessage.new publish_time: now_ts

msg.to_json #=> "{\"attributes\":{},\"publishTime\":\"2019-03-13T15:40:43.729054800Z\"}"

decoded_msg = Google::Cloud::PubSub::V1::PubsubMessage.decode_json msg.to_json
#=> Traceback (most recent call last):
#           1: from pubsub.rb:9:in `<main>'
#   pubsub.rb:9:in `decode_json': Error occurred during parsing: error parsing timestamp: mingw doesn't support strptime (Google::Protobuf::ParseError)
```

**What did you expect to see**

The ability to create a new protobuf resource object by decoding JSON that contains a timestamp.

**What did you see instead?**

A `Google::Protobuf::ParseError` error.

**Anything else we should know about your project / environment**

This appears to only happen on Windows, and [it looks intentional](https://github.com/protocolbuffers/protobuf/blob/v3.7.0/ruby/ext/google/protobuf_c/upb.c#L14125-L14129). But Ruby will parse the timestamp string without issue, so I don't see why Windows couldn't use `Time.parse` instead of `strptime`.

```ruby
require "time"

time_obj = Time.parse "2019-03-13T15:40:43.729054800Z"
timestamp_obj = Google::Protobuf::Timestamp.new seconds: time_obj.to_i, nanos: time_obj.nsec
```

**Comment by TeBoring** [comment]
Like the error message shows, there is difficulty to make Timestamp work on windows.
There is no working c library to support printing timestamp.
Fixing this issue may require refactoring the whole code base to c++, which provides library to print timestamp.

**Comment by TeBoring** [comment]
Is Time.parse a c function?

**Comment by TeBoring** [comment]
Does it support the timestamp format of protobuf?

**Comment by blowmage** [comment]
> There is no working c library to support printing timestamp.

AFAICT, the Ruby code prints the Timestamp just fine. The problem is parsing the printed timestamp value.

> Is Time.parse a c function?

It is a Ruby method.

> Does it support the timestamp format of protobuf?

It does. See the last example in the issue description.

**Comment by blowmage** [comment]
You may want to look at Ruby's [`date_s__parse` c function](https://github.com/ruby/ruby/blob/21d99677f6351d632d413198f0df7c9558de7e2f/ext/date/date_core.c#L4323-L4341). It looks like it hasn't changed in 8 years.
