### ISSUE TITLE
Release 3.7.1

### ISSUE THREAD

**Issue by TeBoring** [protocolbuffers/protobuf#5887]
For tracking progress

**Comment by jtattermusch** [comment]
We might want to backport https://github.com/protocolbuffers/protobuf/pull/5891 once merged.

**Comment by acozzette** [comment]
Let's also make sure to cherrypick #5815 and #5864.

**Comment by acozzette** [comment]
Never mind about #5815, I see the fix for that is already on 3.7.x.
