### ISSUE TITLE
use ndk build

### ISSUE THREAD

**Issue by blueberryCoder** [protocolbuffers/protobuf#5893]
Version: 3.7.x
Language:Cpp
Android ndk use

export NDK_ROOT=~/Library/Android/sdk/ndk-bundle
export PREFIX=~/tools/android/protobuf-3.7.x
export PATH=~/tools/ndk16-toolchain/bin:$PATH
export SYSROOT=~/tools/ndk16-toolchain/sysroot
export CC="arm-linux-androideabi-gcc --sysroot $SYSROOT"
export CXX="arm-linux-androideabi-g++ --sysroot $SYSROOT"
export CXXSTL=$NDK_ROOT/sources/cxx-stl/gnu-libstdc++/4.9

../configure \
--prefix=$PREFIX \
--host=arm-linux-androideabi \
--with-sysroot="${SYSROOT}" \
--enable-shared \
--enable-cross-compile \
--with-protoc=protoc \
CFLAGS="-march=armv7-a -D__ANDROID_API__=21" \
CXXFLAGS="-frtti -fexceptions -march=armv7-a \
-I${NDK_ROOT}/sources/android/support/include \
-I${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/include \
-I${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -D__ANDROID_API__=21" \
LDFLAGS="-L${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" \
LIBS="-llog -lz -lgnustl_static"

make -j2

make install

log:

./.libs/libprotoc.so: error: undefined reference to 'scc_info_FileDescriptorProto_google_2fprotobuf_2fdescriptor_2eproto'

**Comment by boegel** [comment]
I'm seeing the exact same problem, but with a regular `./configure --prefix /tmp/ && make && make install` on Intel x86_64, using GCC 8.2 as compiler (+ binutils 2.13.1)..

**Comment by blueberryCoder** [comment]
i fix it with set ld.

this is my script:

export NDK_ROOT=~/Library/Android/sdk/ndk-bundle
export PREFIX=~/tools/android/protobuf-3.7.x-ndk
export PATH=~/tools/ndk16-toolchain/bin:$PATH
export SYSROOT=~/tools/ndk16-toolchain/sysroot
export CC="arm-linux-androideabi-gcc --sysroot $SYSROOT"
export CXX="arm-linux-androideabi-g++ --sysroot $SYSROOT"
export CXXSTL=$NDK_ROOT/sources/cxx-stl/gnu-libstdc++/4.9
export LD=~/tools/ndk16-toolchain/bin/arm-linux-androideabi-ld

../configure \
--prefix=$PREFIX \
--host=arm-linux-androideabi \
--with-sysroot="${SYSROOT}" \
--disable-shared \
--enable-cross-compile \
--with-protoc=protoc \
CFLAGS="-march=armv7-a -D__ANDROID_API__=21" \
CXXFLAGS="-frtti -fexceptions -march=armv7-a \
-I${NDK_ROOT}/sources/android/support/include \
-I${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/include \
-I${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -D__ANDROID_API__=21" \
LDFLAGS="-L${NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" \
LD=${LD} \
LIBS="-llog -lz -lgnustl_static"

make -j2

make install
