### ISSUE TITLE
Why does GOOGLE_PROTOBUF_MIN_LIBRARY_VERSION change for a patch release?

### ISSUE THREAD

**Issue by dave-xnor** [protocolbuffers/protobuf#5895]
When going from 3.6.0 to 3.6.1 - a patch release - `GOOGLE_PROTOBUF_MIN_LIBRARY_VERSION` was bumped from 3006000 to 3006001 [as seen here](https://github.com/protocolbuffers/protobuf/commit/9e1286b949adc40b450a0097c6ffd4dd491506c0#diff-cbd31ea2a5761cd281396b4277c36887) (and this happens at other patch releases too but I'm interested in 3.6.1).

I think it should have remained at 3.6.0 for a patch release.  Surely binary compatibility was maintained?  Why is it bumped up?

(And bonus question: If I just stomp on that value in `common.h` with `3006000` I'm not going to run into any problems, right?  I'm only interested in a C++/Linux environment, and having checked the [3.6.0->3.6.1 diff](https://github.com/protocolbuffers/protobuf/compare/v3.6.1...3.6.x) the only things which is problematic to my (inexperienced) eyes are the additional symbol exports from `io/gzip_stream.h` and `repeated_field.h` - but I don't see that the C++ generated code would have changed to reference those symbols...)

(This is causing problems where we're delivering a plugin - compiled against protobuf 3.6.1 - to a product which is compiled against 3.6.0 and thus the protobuf shared library is 3.6.0 and the version check fails.  But any 3.6.x should work.)

**Comment by acozzette** [comment]
I would guess that in this case you could probably safely interoperate 3.6.1 generated code with a 3.6.0 runtime library, but in general we don't really make any attempt to maintain ABI compatibility this way. Usually we require that for C++ the generated code and the runtime library are the exact same version.
