### ISSUE TITLE
cross compilation failing with gold linker:

### ISSUE THREAD

**Issue by Allen-Webb** [protocolbuffers/protobuf#5902]
**What version of protobuf and what language are you using?**
Version: v3.7.0
Language: all

**What operating system (Linux, Windows, ...) and version?**
Chrome OS m75

**What runtime / compiler are you using (e.g., python version or gcc version)**
Chromium OS 8.0_pre349610_p20190109-r11 clang version 8.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/clang.git a1a49a7b666a6a9d9b55b52602f9773a9e00b4f5) (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm.git 331ffd31b3dd49b3f02a27556938b836b679f564) (based on LLVM 8.0.0svn)
Target: x86_64-cros-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**What did you do?**
1. Setup Chrome OS build environment
2. checkout https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/1526361/1
Note that this is patchset 1 (a work around is used in a later patch set)
3. ./build_packages --board=hana
4. wait for protobuf compilation to fail

**What did you expect to see**

**What did you see instead?**
protobuf-3.7.0-r1: /bin/sh ../libtool  --tag=CXX   --mode=link armv7a-cros-linux-gnueabihf-clang++ -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare  -O2 -pipe  -march=armv8-a+crc -mtune=cortex-a57.cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -pthread -Wl,-O2 -Wl,--as-needed  -o protoc google/protobuf/compiler/main.o  libprotobuf.la libprotoc.la -lz 
protobuf-3.7.0-r1: libtool: link: armv7a-cros-linux-gnueabihf-clang++ -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -march=armv8-a+crc -mtune=cortex-a57.cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -pthread -Wl,-O2 -o .libs/protoc google/protobuf/compiler/main.o  -Wl,--as-needed ./.libs/libprotobuf.so ./.libs/libprotoc.so /build/hana/tmp/portage/dev-libs/protobuf-3.7.0-r1/work/protobuf-3.7.0-.arm/src/.libs/libprotobuf.so -lz -pthread
protobuf-3.7.0-r1: ./.libs/libprotoc.so: error: undefined reference to 'scc_info_FileDescriptorProto_google_2fprotobuf_2fdescriptor_2eproto'
protobuf-3.7.0-r1: clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
If I disable the gold linker and instead use bfd, protobuf compiles as expected.

**Comment by Arfrever** [comment]
Normal (non-cross) building also fails with GOLD linker in the same way.

**Comment by Arfrever** [comment]
This is bug in GOLD:
https://sourceware.org/bugzilla/show_bug.cgi?id=24527

**Comment by elharo** [comment]
not our bug
