### ISSUE TITLE
Unable to provide WORKSPACE dependencies when protobuf is depended on in Bazel

### ISSUE THREAD

**Issue by perezd** [protocolbuffers/protobuf#5905]
I'm trying to address this issue in another repo: https://github.com/google/bazel-common/issues/51
Currently I'm blocked because I'm unable to provide the necessary dependency on `//external:error_prone_annotations` defined in WORKSPACE here:
https://github.com/protocolbuffers/protobuf/blob/master/WORKSPACE#L74

FWIW, Bazel recommends to avoid bind:
https://docs.bazel.build/versions/master/external.html#best-practices

This is might be especially worth noting in a Google open source project.

Any suggestions on how provide that dependency from bazel-common? Ironically, we are already loading the annotations over there, I just need a way to provide them to com_google_protobuf when it builds `protobuf_java_util`

**Comment by haon4** [comment]
Sorry for the late reply, looking into this now.

**Comment by haon4** [comment]
@perezd, would you mind pointing me to a repo where I can easily reproduce this?

**Comment by perezd** [comment]
This may have been a misunderstanding, I found in the 3.7.x branch that
this does work as expected.

**Comment by haon4** [comment]
ok. I will close this issue, then.
