### ISSUE TITLE
Error detail when parsing length-delimited stream

### ISSUE THREAD

**Issue by smbz** [protocolbuffers/protobuf#5907]
**What language does this apply to?**
C++ and C#; possibly others

**Describe the problem you are trying to solve.**
I have a network stream of protobuf messages, each preceded by a varint length field.  If there is an error parsing the length field then the parser needs to terminate.  However if there is an error parsing the message content then the parser should ignore that message and continue with the next.

There are therefore four possibilities each time the parser receives somes data from the network:

 1. The message is incomplete and the parser needs to wait for more data
 2. Error parsing the length field (i.e. the varint is too long)
 3. Error parsing the message itself
 4. The message is complete and successfully received

**Describe the solution you'd like**
I'd like google::protobuf::util::ParseDelimitedFromCodedStream (C++) and Google.Protobuf.MessageParser<>.ParseDelimitedFrom (C#) to return an error code or throw a typed exception which distinguishes between these cases.

**Describe alternatives you've considered**
The C++ ParseDelimitedFromCodedStream outputs success and 'clean EOF' flags but, from what I can tell, the 'clean EOF' flag doesn't help here.  The C# ParseDelimitedFrom either throws an InvalidProtocolBufferException (which doesn't contain any further machine-readable information) or returns successfully.

I've worked around this by reading the varint length directly.  The varint read methods don't distinguish between an unexpected EOF (case 1) and an error parsing the length field (case 2), so I'm detecting this manually by checking the number of bytes available in the stream: anything over 10 bytes is assumed to be an error parsing the length field.  This is not a clean or elegant solution though, as protobuf should be the authority on whether or not there's a parse error.

#4303 is related but doesn't go quite as far.

**Comment by elharo** [comment]
"However if there is an error parsing the message content then the parser should ignore that message and continue with the next." Hard no. That's not how protobuf is designed to work.
