### ISSUE TITLE
JSON conversion of FieldMask may not round-trip but does not produce error

### ISSUE THREAD

**Issue by cybrcodr** [protocolbuffers/protobuf#5913]
**What version of protobuf and what language are you using?**  v3.7.0

Language: C++

It is possible to have FieldMask.paths contain string values are may not round-trip correctly.  I'd expect that MessageToJsonString should return an error if it is unable to do the conversion.

```c++
  FieldMask m;
  m.add_paths("Foo");
  m.add_paths("foo_Bar");
  m.add_paths("foo_");
  m.add_paths("_bar");
  cout << "Before JSON conversion: " << endl << m.DebugString() << endl;

  string out;
  JsonPrintOptions print_opts;
  Status s = MessageToJsonString(m, &out, print_opts);
  if (s.ok()) {
    cout << "JSON output: " << out << endl;
  } else {
    cout << "Error in writing JSON: " << s.error_message() << endl;
  }

  m.Clear();
  JsonParseOptions parse_opts;
  s = JsonStringToMessage(out, &m, parse_opts);
  if (s.ok()) {
    cout << m.DebugString() << endl;
  } else {
    cout << "Error in reading JSON: " << s.error_message() << endl;
  }
```

Output shows ...
```
Before JSON conversion:
paths: "Foo"
paths: "foo_Bar"
paths: "foo_"
paths: "_bar"

JSON output: "foo,fooBar,foo,bar"
paths: "foo"
paths: "foo_bar"
paths: "foo"
paths: "bar"
```

**Comment by cybrcodr** [comment]
Fyi.  Interesting enough, I noticed there's `FieldMaskUtil::ToJsonString` and somehow that function call returns false.  So, I'm guessing that MessageToJsonString does not use the same function to encode FieldMask.

**Comment by anandolee** [comment]
MessageToJsonString is calling another function FieldMaskUtil::ToJsonString:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/internal/protostream_objectsource.cc#L700
