### ISSUE TITLE
Release 3.7.0 doesn't contain protobuf_deps.bzl

### ISSUE THREAD

**Issue by hlopko** [protocolbuffers/protobuf#5918]
**What version of protobuf and what language are you using?**
Version: [v3.7.0](https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protobuf-all-3.7.0.tar.gz)
Language: C++/Python

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Create a new Bazel workspace identical with the one from [examples](https://github.com/protocolbuffers/protobuf/blob/master/examples/WORKSPACE)
2. Change the example to use released protobuf:

Instead of:

	http_archive(
	    name = "com_google_protobuf",
	    strip_prefix = "protobuf-master",
	    urls = ["https://github.com/protocolbuffers/protobuf/archive/master.zip"],
	)

use

	http_archive(
	    name = "com_google_protobuf",
	    sha256 = "3e933375ecc58d01e52705479b82f155aea2d02cc55d833f8773213e74f88363",
	    strip_prefix = "protobuf-3.7.0",
	    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protobuf-all-3.7.0.tar.gz"],
	)

3. Run Bazel `bazel build @com_google_protobuf//:protobuf`

**What did you expect to see**
Green build.

**What did you see instead?**

`ERROR: error loading package '': Unable to load file '@com_google_protobuf//:protobuf_deps.bzl': file doesn't exist
`

**Comment by TeBoring** [comment]
@acozzette has this been fixed in 3.7.x branch?

**Comment by hlopko** [comment]
If I'm not mistaken, protobuf_deps.bzl is not a part of 3.8, is it? Is it a bug or 3.8 is still cut before introduction of protobuf_deps.bzl?

Thank you!

**Comment by hlopko** [comment]
@acozzette friendly ping, should we reopen and make sure protobuf_deps.bzl makes it into the release archive?

**Comment by acozzette** [comment]
I think this is probably just a matter of updating our script to include the file in the generated archive, let me send out a pull request for it.

**Comment by acozzette** [comment]
I just sent out #6281 which will make sure this fix gets included in the 3.9 release.

**Comment by hlopko** [comment]
Thank you Adam!
