### ISSUE TITLE
Why not print Bytes to String(default in utf-8 ecoding) instead of  based-64 coding string in JsonFormat.java

### ISSUE THREAD

**Issue by wustrong** [protocolbuffers/protobuf#5919]
(https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1157)

When we want to print the message to a readable string, the Bytes field will be printed as based-64 coding string. Then we need to decode the characters to understand what does it mean. 

like this:
`{
      "UniqueId": "MjkyMTU1Mjg5MzkwNTc2Ng==",
      "VideoId": "aTA4NTBxandmZjI=",
      "Time": "NzE=",
      "Location": ""
}`

Maybe the Bytes is not encoding by utf-8, but it is possible to provide  a optional method to print all (or parts of ) Bytes to String.

And, json with utf-8 encoding Bytes field to Message?

**Comment by haon4** [comment]
JsonFormat is designed to round-trip correctly (no data loss with decode(encode(Message))), and it is meant to be transferable to the web browser, so we use base64 encoding on bytes to make sure that all the data can be transferred.

If your fields can be represented as a String, please consider using string fields instead.
