### ISSUE TITLE
protoc crashes when gcc LTO is enabled

### ISSUE THREAD

**Issue by snnn** [protocolbuffers/protobuf#5923]
**What version of protobuf and what language are you using?**
v3.7.0
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
c++
**What operating system (Linux, Windows, ...) and version?**
Linux, ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

**What did you do?**
0. apt-get install g++ curl make
1. curl -O -L 'https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz'
2. tar -zxvf cmake-3.14.0-Linux-x86_64.tar.gz
3. mv cmake-3.14.0-Linux-x86_64 /opt/cmake
4. curl -O -L 'https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protobuf-all-3.7.0.tar.gz'
5. tar -zxvf protobuf-all-3.7.0.tar.gz
6. cd protobuf-3.7.0/
7. Open CMakeLists.txt, Change the second line to 'cmake_minimum_required(VERSION 3.14)', then add
```
cmake_policy(SET CMP0069 NEW)
set(CMAKE_POLICY_DEFAULT_CMP0069 NEW)

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO ON)
```
After the line of 'project(protobuf C CXX)'

8. mkdir b
9. cd b
10. cmake .. -DCMAKE_BUILD_TYPE=Release
11. make -j8 protoc
12. ./protoc

**What did you expect to see**
protoc should run and show a help message

**What did you see instead?**
```
[libprotobuf FATAL /tmp/protobuf-3.7.0/src/google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
Aborted (core dumped)
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I can't reproduce the error on Fedora 29, which has gcc 8.3. Therefore, maybe this is a compiler bug.

**Comment by jobdeadss** [comment]
I have the same issue on Android.

Description:
I have two dynamic libs.  Each of them linked with static "protobuf" library and with compiled proto files.
Android application uses these dynamic libs and at the moment when application loads then it crashes.

Configuration:
```
os.api_level=24
arch=x86_64
compiler=clang
compiler.libcxx=libc++
compiler.version=7.0
cppstd=17
build_type=Release
android_ndk_toolchain=r18b
```

```
2019-03-22 12:49:52.722 16905-16905/example.myapplication A/libprotobuf-native: [libprotobuf FATAL /Users/user/.conan/data/protobuf/3.7.0/user/stable/build/743423d9e0d3e2860b131184076f3c9a279c9658/sources/src/google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
2019-03-22 12:49:52.722 16905-16905/example.myapplication A/libprotobuf-native: terminating.
2019-03-22 12:49:52.724 16905-16905/example.myapplication E/libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
```

**Comment by snnn** [comment]
Hi @jobdeadss, your case is different. You should either let your dynamic libs dynamically linked to protobuf, or, you should hide the protobuf symbols from your dynamic libs, by using a [linker version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html). If these two protobuf libs are not visible to each other, they won't be in conflict.

**Comment by snnn** [comment]
I found the reason.

Need to insert '--no-as-needed' before the '-pthread' arg in the link command args of protoc.

**Comment by marxin** [comment]
> I found the reason.
> 
> Need to insert '--no-as-needed' before the '-pthread' arg in the link command args of protoc.

Good. Can you please make a submit request for it?

**Comment by sarbjit-longia** [comment]
--no-as-needed is not supported in clang, any other solution to this. What is the root cause of this issue. Its blocker for me, if anyone can help its appreciated.

**Comment by snnn** [comment]
Glibc uses a stub implementation of various pthread functions, so that single threaded programs do not have to waste cycles doing things like locking and unlocking mutexes, and yet do not have to link to a different C library. (from https://stackoverflow.com/questions/21092601/is-pthread-in-glibc-so-implemented-by-weak-symbol-to-provide-pthread-stub-functi )

But protobuf need a real one, not the stub. Even protoc is mostly single threaded,  it still need libpthread. 

I believe protobuf has done everything correctly. It added the pthread lib to its linker flags, however, when LTO is enabled, the linker may wrongly think the pthread lib is not needed, and may throw it away. And if it does that,  the final protoc executable won't be usable, it always crashes.  The "--no-as-needed" flag is a workaround for this. 

I would think it is more a bug of the compiler, because it can be solved by upgrading the compiler. The latest one should work fine. If it is not possible for you to make an update on your toolchain,  then please step back from the problem. Is LTO a must? Can you turn it off? 

Another possibility is: protobuf may allow user building it in a purely single threaded way, without all the pthread function calls.  From my experience, it is often needed because not every system supports multiple threading. For example, the symbolic execution engines, trusted execution environments. they prefer to have things as simple as possible.

**Comment by sarbjit-singh** [comment]
Thanks for the reply, appreciate it. Seems like i moved away from this after spending too much time on this issue. I will try again after updating the compiler.

**Comment by snnn** [comment]
I'll close this issue as it is not quite a problem of protobuf,  and solutions are clear.
