### ISSUE TITLE
Compatibility of protobuf 3.7.0 with Spark - Hadoop

### ISSUE THREAD

**Issue by kevinmat** [protocolbuffers/protobuf#5925]
Hi, I want to make use of latest com.google.protobuf.protobuf version 3.7.0 , Is this compatible with hdp 2.5 and spark version = 1.6.2.2.5.0.0-1245? Will I need to regenerate In spark-assembly jar ?

Question here is i want to make use of this feature in version 3.7 , what changes are needed in spark assembly , would i need to upgrade to a later version of Spark and HDP as well?

Thanks,
Kevin

**Comment by acozzette** [comment]
Hi Kevin, among the protobuf maintainers I don't think any of us have much familiarity with Spark or Hadoop so your best bet would probably be to ask the maintainers of those projects about upgrading your protobuf version. I would guess the difficulty of upgrading depends on: (a) how old is the current protobuf version being used and (b) do those projects run `protoc` as part of their build or rely on checked-in generated code from `protoc`.
