### ISSUE TITLE
Which versions are still supported

### ISSUE THREAD

**Issue by SMillerDev** [protocolbuffers/protobuf#5926]
Homebrew ships a couple of old versions for protobuf but as a policy only ships versions that are still supported by upstream. Are all versions of protobuf still supported? Or is only the newest version supported? Or somewhere in between?

https://github.com/Homebrew/homebrew-core/pull/37648

**Comment by haon4** [comment]
We generally only maintain the master branch + the latest version branch. While the latest version is being released, we may still maintain the second latest version. The wire format, though, is still backward compatible to pretty much all the older version.

**Comment by SMillerDev** [comment]
Thanks for the response!
