### ISSUE TITLE
google-protobuf does not define Message.getFloatingPointFieldWithDefault

### ISSUE THREAD

**Issue by malcolmwhite** [protocolbuffers/protobuf#5930]
**What version of protobuf and what language are you using?**
Version: 3.7.0
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc 3.7, ts-protoc-gen 0.9.0, npm/google-protobuf@3.7.0

**What did you do?**
1. Start from totally fresh git clone to avoid stale caches from version upgrades
2. Build message MyMessage { float foo = 1; }
3. Run code that uses MyMessage

**What did you expect to see**
No errors

**What did you see instead?**
TypeError: jspb.Message.getFloatingPointFieldWithDefault is not a function

From looking at the git and npm histories, it seems that npm/google-protobuf@3.7.0 was published before the release was open-sourced in #5839. Looking at the google-protobuf.js in google-protobuf@3.7.0, I do not see the fields added to the protubuf compiler in 3.7.0 (such as getFloatingPointFieldWithDefault). Is it possible that npm/google-protobuf@3.7.0 is behind protoc@3.7.0?

**Comment by malcolmwhite** [comment]
I am also seeing this issue with the recently released npm/google-protobuf@3.7.1

**Comment by RomainNotilo** [comment]
This bug has been fixed in https://github.com/protocolbuffers/protobuf/commit/d0f91c863ae0fbb75b41460c8bbb786ade197a0f but not yet released.

**Comment by elharo** [comment]
fixed
