### ISSUE TITLE
proposal: Comparable structs

### ISSUE THREAD

**Issue by hewenyang** [protocolbuffers/protobuf#5938]
**What language does this apply to?**
Both proto2 and proto3.

**Describe the problem you are trying to solve.**
* Alias for scalar types. Currently, all of my database primary keys are strings. But even though they are of the same type, they have different meanings. A User key cannot be used to look up an Item. So I want to define a type UserKey for User and a ItemKey for Item.
* User-defined scalar types. It might be useful to define 16 bytes as GUID, 12 bytes as ObjectID, a pair of integers as a Point2D, etc. Such types often need comparability. Timestamps and durations may be implemented as structs instead of messages so they can be compared or sorted.
* Comparability. A comparable type can be used as map keys or perform set union/intersection. Currently, messages are usually not comparable and require special handling. I can understand that because there are many edge cases. For example, messages might have unknown fields because we need to be able to add and remove fields from messages. But primitives alone are not useful enough. For example, pairs and triples might be useful.
* A better way to get around the weirdness of proto3 messages. In proto3, the zero value of each primitive is the default value, and it's not possible for a client to distinguish zero values and nonexistent values. In cases when the zero value has a real meaning, it's effectively no versioning at all. The struct drops versioning to make things clearer. It's effectively proto3 messages that consist of primitives only and no fields of message type.

**Describe the solution you'd like**
I propose a new type called structs with the following properties:
* Structs consist of multiple fields, and each field must be a scalar type, an enum type or a struct.
* Struct fields do not have a field number. It's determined by the order of the fields.
* Every field must be "required". It might be useful to allow fields to be "repeated" or "optional" too, but how that would be implemented needs more thought, since not every language supports comparable arrays. Oneof is also tricky but it might be possible. For proto3, every field has the zero value as the default value. For proto2 every field has a type-specific default value that can be overridden.
* Structs are fixed and if a struct is changed in any way, by adding/removing fields or reordering them, the new struct and the old struct will no longer be binary compatible with each other.
* Structs cannot be cyclic by traversing "required" fields (such structs don't make any sense).
* Structs can be used like any other primitive in a message and can be encoded/decoded on their own.
* Structs cannot be wrapped in Any.
* For each language, the generated type for the structs should be comparable and can be used as map keys in that language.
* Two structs are equal if and only if each of their corresponding fields are equal.
* Preferably two structs may also be ordered. Struct A is strictly less than struct B if an index i exists such that ith field in struct A is strictly less than ith field in struct B and for index 1..i-1 the field in struct A equals to the corresponding field in struct B.
* The binary representation for a struct is deterministic. Two structs are equal if and only if they marshal to the same sequence of bytes. It might be possible to make their binary representation ordered too.

A dedicated syntax for representing struct values might be necessary so messages can specify default values for struct fields.

**Describe alternatives you've considered**
I use Go language.  For the first problem, I created a plugin that replaces the field type in generated code with a custom alias. But it doesn't work across languages. Thus I thought about a generalized struct type that might have other uses too.

**Additional context**

**Comment by haon4** [comment]
Hi, thank you for proposing this. What you describes sound very similar to FlatBuffers (https://google.github.io/flatbuffers/). Perhaps it is closer to what you want?
