### ISSUE TITLE
Make check failed with Python 2.7.13 and protobuf 3.7.0

### ISSUE THREAD

**Issue by Neeharanshu** [protocolbuffers/protobuf#5940]
**What version of protobuf and what language are you using?**
Version: master/v3.7.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Debian

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 2.7.13
GCC: (Debian 6.3.0-18) 6.3.0 20170516

**What did you do?**
1. Go to https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0
2. Click on protobuf-python-3.7.0.tar.gz
3. Followed steps as mentioned here: http://osdevlab.blogspot.com/2016/03/how-to-install-google-protocol-buffers.html but replace protobuf-2.6.1 with 3.7.0
4. See error in make check

**What did you expect to see**
Well, I was expecting to see a log result with pass but it terminated pre-maturely.

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Please find attached image
![image](https://user-images.githubusercontent.com/32780382/54826544-64ae8b80-4c86-11e9-9dc5-838f896607b4.png)

**Anything else we should know about your project / environment**
Working on a BeagleBone

**Comment by elharo** [comment]
python 2 no longer supported
