### ISSUE TITLE
ld: 617 duplicate symbols for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by BigMarco254** [protocolbuffers/protobuf#5941]
Version: master
Language: Objective-C
OS: Mac OS X 10.14

1. Added files to my project
2. Got errors when trying to compile

The error was too long to insert here so here is the Pastebin:
https://pastebin.com/mLSgVZLN

**Comment by thomasvl** [comment]
See https://github.com/protocolbuffers/protobuf/tree/master/objectivec#building.

Looks like you added all the individual files and the `GPBProtocolBuffers.m` file, leave off `GPBProtocolBuffers.m` since you added the other files.
