### ISSUE TITLE
json_format.py is converting fixed64 to string

### ISSUE THREAD

**Issue by rohitsaboo** [protocolbuffers/protobuf#5942]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
master

Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
Python

**What operating system (Linux, Windows, ...) and version?**
doesn't matter

**What runtime / compiler are you using (e.g., python version or gcc version)**
doesn't matter

**What did you do?**
See https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py#L68

**What did you expect to see**
fixed64 and sfixed64 types are also converted to json numbers when we run json_format.

**What did you see instead?**
They are converted to strings.

**Comment by anandolee** [comment]
It is by design. for int64, fixed64 and uint64, protobuf JSON printer will print a string. Both numbers and strings are accepted in parser:
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by rohitsaboo** [comment]
Hi Jie, do you mind elaborating a bit on why this design choice was made?
