### ISSUE TITLE
protobuf Version verification failed

### ISSUE THREAD

**Issue by TouchDeeper** [protocolbuffers/protobuf#5943]
Hi,
I want to run a launch file in ros, error about protobuf version occur:
```
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.131
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[Wrn] [Event.cc:87] Warning: Deleteing a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/wang/ridgeback_cartographer_ws/protobuf/src/google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/wang/ridgeback_cartographer_ws/protobuf/src/google/protobuf/descriptor.pb.cc".)
Aborted (core dumped)
```
What confuse me is  `Version verification failed in "/home/wang/ridgeback_cartographer_ws/protobuf/src/google/protobuf/descriptor.pb.cc".)`, the workspace mentioned here is not the workspace include the launch file, and if I delete the `/home/wang/ridgeback_cartographer_ws`, the error still be the same. How can I delete the link between the protobuf and `/home/wang/ridgeback_cartographer_ws`?

**Comment by lengnuanzihi** [comment]
i still have this problem.can you tell me how to solve this?Thanks

**Comment by acozzette** [comment]
This kind of error indicates a mismatch between the versions of the generated code (i.e. the pb.cc and pb.h files) and the runtime library (i.e. `libprotobuf` or `libprotobuf-lite`). The protoc binary used to generate the pb.h and pb.cc files must be the same version as the runtime library.

**Comment by TouchDeeper** [comment]
The error occur because I have changed a file installed in my computer. The problem is easier to solve by just reinstall the protobuf.
