### ISSUE TITLE
Generated code compilation error  repeated int32 (or int64) 

### ISSUE THREAD

**Issue by eregg** [protocolbuffers/protobuf#5945]
**What version of protobuf and what language are you using?**
Version: Protocol Buffers v3.7.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.14.1 
**What runtime / compiler are you using (e.g., python version or gcc version)**
https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0
**What did you do?**
1. Make a file Bug.proto:
```
syntax = "proto3";

package protobuf;

message MyMessage {
    repeated int32 data = 1;
}
```
2. Generate Java code:
protoc --java_out=./ Bug.proto
3. Try to compile Java code
copy Java code file to idea
![image](https://user-images.githubusercontent.com/14013106/54914799-cdb92c00-4f30-11e9-905c-8270770ed893.png)

**What did you expect to see**

**What did you see instead?**
![image](https://user-images.githubusercontent.com/14013106/54914269-8bdbb600-4f2f-11e9-809c-d374981b8b9a.png)

**Anything else we should know about your project / environment**
1. GeneratedMessageLite.java
```
    protected static IntList emptyIntList() {
        return IntArrayList.emptyList();
    }
```
2. GeneratedMessageV3.java
No emptyIntList method

3.  Protoc Generate Java code
```
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      data_ = emptyIntList();
    }
}
}
```

**Comment by haon4** [comment]
Hi, are you also using version 3.7.0 of the runtime library? https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

**Comment by eregg** [comment]
> Hi, are you also using version 3.7.0 of the runtime library? https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

yes

**Comment by haon4** [comment]
I just tried this and couldn't reproduce. GeneratedMessageV3 correctly contains emptyIntList() method in 3.7.0 and 3.7.1. Please make sure that you add the protobuf-java dependency correctly in your IDE.

**Comment by vsrikrishna32** [comment]
Has this been resolved?  I am running into the same issues again.
