### ISSUE TITLE
Are Reflections available for PHP protobuffers?

### ISSUE THREAD

**Issue by mejarrett** [protocolbuffers/protobuf#5949]
We used to use DrSlump for PHP protobuffers and heavily use reflections to see what fields are available. Is there a way to get a reflection?

**Comment by john-gress** [comment]
You can use the build-in php ReflectionClass. See https://www.php.net/manual/en/class.reflectionclass.php

A nice example is provided here: https://www.php.net/manual/en/class.reflection.php
