### ISSUE TITLE
release 3.7.1: make check failed

### ISSUE THREAD

**Issue by swiss-knight** [protocolbuffers/protobuf#5959]
**What version of protobuf and what language are you using?**
Version: zip file of Release 3.7.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04 64 bits

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**What did you do?**
1. Downloaded release 3.7.1 from https://github.com/protocolbuffers/protobuf/releases in `/opt`
2. unzip it in `/opt/protobuf-3.7.1` and cd into that folder
3. `./autogen.sh`
4. `./configure`
5. `make -j4`    
6.     
```
$ make check
Making check in .
make[1]: Entering directory '/opt/protobuf-3.7.1'
make  check-local
make[2]: Entering directory '/opt/protobuf-3.7.1'
Making lib/libgmock.a lib/libgmock_main.a in gmock
/bin/bash: line 0: cd: third_party/googletest/googletest: No such file or directory
Makefile:2024: recipe for target 'check-local' failed
make[2]: *** [check-local] Error 1
make[2]: Leaving directory '/opt/protobuf-3.7.1'
Makefile:1886: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/opt/protobuf-3.7.1'
Makefile:1598: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by acozzette** [comment]
Sorry about that, we are still working on uploading all the artifacts for the 3.7.1 release. The `tar.gz` file generated by GitHub does not work, but the packages we generate ourselves should work, and I just now uploaded them to the release page for 3.7.1.

**Comment by smuniraj2018** [comment]
I have the same issue as @swiss-knight

**Comment by kamathhrishi** [comment]
@acozzette I have the same problem but for protobuf 3.6.3. Should I ignore it or there some way to go about it?

**Comment by Gabit07** [comment]
reboot and try again

**Comment by rcalandr** [comment]
Same issue for me

**Comment by griffin-warrior** [comment]
I've tried several versions, including the latest. All of them have the same issue in this thread.

**Comment by griffin-warrior** [comment]
Problem solved. `protobuf-cpp-[VERSION].tar.gz` can pass `make check` while `Source code
(tar.gz)` can't.
