### ISSUE TITLE
how to quick add namespace for libprotobu-lite souce files in case conflict with others

### ISSUE THREAD

**Issue by aimsgmiss** [protocolbuffers/protobuf#5960]
hello :
    when i worked with libprotobuf-lite of c++  in mobile platform for sdk  develope ,want know how to add namespace for these source files in case conflict with other sdk,because others maybe use same libprotobuf-lite,if that occur there is no need to remove libprotobuf-lite souce file because of namespace ever added,the example below like this:
 
// such as add nesting namespace new_namespace  for message_lite.h
namespace new_namespace {  
namespace google {
namespace protobuf {​

.......

}  // namespace protobuf
}  // namespace google
}  // namespace new_namespace

//also add  nesting namespace new_namespace  for message_lite.c
namespace new_namespace {
namespace google {
namespace protobuf {

.......

}  // namespace protobuf
}  // namespace google
}  // namespace new_namespace

so this will not conflict with others because of we add  new_namespace for this source file.

is there any quick method to add all these files namespace,but some build error was happend with me if add like that.

 any idea will help me,thanks in advance!

**Comment by acozzette** [comment]
There is no built-in quick way to do this, but you could probably do it by hand without too much trouble. It is also important to update `protoc` (the protobuf compiler) so that it uses your new namespace in the `pb.h` and `pb.cc` files it generates.
