### ISSUE TITLE
Need latest version for protobuf-lite with fixes in protobuf-java

### ISSUE THREAD

**Issue by muthuraj57** [protocolbuffers/protobuf#5961]
Specifically I need the fix in this file landed on this commit
https://github.com/protocolbuffers/protobuf/blob/0400cca3236de1ca303af38bf81eab332d042b7c/java/core/src/main/java/com/google/protobuf/MessageLiteToString.java#L95

I see that **protobuf-java** is updated frequently but last update of **protobuf-lite** was 3 years ago. Any plan on updating protobuf-lite? I see two other related (old) issues regarding new versions ([1](https://github.com/protocolbuffers/protobuf/issues/2935), [2](https://github.com/protocolbuffers/protobuf/issues/1804)), but I would like to know current status of this.

**Comment by BSBandme** [comment]
We are planning to release a new java lite library, probably it will happen in the new future

**Comment by haon4** [comment]
Yea, I am trying to release the new JavaLite. We actually have a new runtime for JavaLite and requires different setup than before. Looking into release them all + update documentation for JavaLite in the next few weeks.

**Comment by nikolowry** [comment]
I do monthly builds of Chromium for Android on Arch Linux, today when attempting to build v73.0.3683.88 I got the following error message:

```
protoc-gen-javalite: program not found or is not executable
--javalite_out: protoc-gen-javalite: Plugin failed with status code 1.
```

I don't incorporate these libs into my daily development stack, so if anyone might have a suggestion here I can avoid opening a new issue?

**Comment by haon4** [comment]
I have added the latest java lite to the master branch. Some instructions on how to use it can be found here: https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md. We should have an updated javalite jar file in maven in the upcoming 3.8.0 release.

**Comment by haon4** [comment]
3.8.0-rc1 is out: https://github.com/protocolbuffers/protobuf/releases, runtime is available in maven: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-javalite. This requires a slightly different setup than the old JavaLite: https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md. Please give it a try. Thanks!

**Comment by haon4** [comment]
3.8.0 is out.
