### ISSUE TITLE
Please update for Swift 5 support.

### ISSUE THREAD

**Issue by OkiRules** [protocolbuffers/protobuf#5963]
Please update for Swift 5 support.

Thanks!

**Comment by thomasvl** [comment]
Can you expand on what issues you are specifically hitting?  Since the code here is ObjC, and the only Swift is a unittest to ensure calling from Swift works, what are the problems you are seeing with Swift 5?

**Comment by OkiRules** [comment]
<img width="576" alt="Screen Shot 2019-04-02 at 8 23 37 am" src="https://user-images.githubusercontent.com/18746541/55360635-bd044980-5520-11e9-8d2f-2687ed79c819.png">
<img width="587" alt="Screen Shot 2019-04-02 at 8 23 31 am" src="https://user-images.githubusercontent.com/18746541/55360658-ca213880-5520-11e9-91f1-11ab80782644.png">

**Comment by thomasvl** [comment]
Just so I'm following, what do those messages have to do with Swift 5?

**Comment by thomasvl** [comment]
And as far as the errors, this would appear to be related to CocoaPods and it's symlinks and some of Xcode/clangs following on links in some but not all cases, see #3218 for that existing issue.
