### ISSUE TITLE
Report use of unknown fields

### ISSUE THREAD

**Issue by htuch** [protocolbuffers/protobuf#5967]
**What language does this apply to?**

C++ (possibly others)

**Describe the problem you are trying to solve.**

We would like to allow unknown fields during proto parsing from wire (and formats such as JSON/YAML), but to report the details for the purposes of logging. Our use case is Envoy (https://github.com/envoyproxy/envoy), where configuration with unknown fields can fall into two categories:

1. Intentional delivery of a newer field from a server with a newer API proto than the client. Client should just ignore.

2. Accidental misconfiguration of protos (typically the JSON/YAML representation, but also text proto) by users.

We would be confident enabling unknown fields if we could track their use to support (1) and still detect (2).

**Describe the solution you'd like**

A callback during proto parsing when an unknown field is encountered.

**Describe alternatives you've considered**

Today, we only allow a binary choice by the user. We encourage them to allow unknown fields if the protos are machine generated and to disallow them if not. This is often too coarse, with a mixture of configuration proto provenance not uncommon.

CC @mattklein123

**Comment by BSBandme** [comment]
What are the inputs and return value for the callback you would like to proposal? I think it's some kind of hard to just providing one callback to fully support all users concerns.

**Comment by htuch** [comment]
It would really depend on what is most idiomatic for protobuf, but the effect that we want is for C++ code calling into functions like `JsonStringToMessage()` or `message.ParseFromString()` to be able to learn which unknown fields were encountered during the parsing operations. Any thoughts?

Also CC @lizan

**Comment by haon4** [comment]
JsonStringToMessage has an option for ignore_unknown_fields. If you set it to false for (1) and set it to true for (2), would that give you what you need? The parse failure message should inform you approximately where the error occurs in JSON.

**Comment by htuch** [comment]
We need to programatically obtain a list of unknown fields to use for more detailed logging and stats. We want to accept the unknown fields, but provide an indicator in our own access logs of all accepted unknown fields, and scraping error strings for this seems a bit fragile.

**Comment by lizan** [comment]
The [converter::ErrorListener] is for this purpose, though it is in internal header so ideally we want to make it as a part of public API.

**Comment by haon4** [comment]
What kind of information would you like to log? Do you need to know the JSON key that is unknown + the full hierarchy to get there? Do you need to know the line number + column number of that unknown field?

Random idea: if I give you a traverser that can traverse the entire JSON, and for each JSON field that I visit, I'll give invoke your visitor with the JSON key + JSON value + the corresponding FieldDescriptor for that JSON (or absent of FieldDescriptor for unknown field), would that be sufficient for your logging/stats purpose?

**Comment by htuch** [comment]
I think we just want to know the field names for JSON and the field number for proto, that should be sufficient for logging.

The idea you present would definitely work for JSON, is there a way of also tackling this for proto?

**Comment by haon4** [comment]
For regular proto message, you can do access unknown fields using:
  const proto2::Reflection* reflection = message.GetReflection();
  reflection->GetUnknownFields(message);

**Comment by htuch** [comment]
@haon4 ack; in that case, what you suggest in https://github.com/protocolbuffers/protobuf/issues/5967#issuecomment-481056877 sounds great. Do you think this can be added to the protobuf C++ libs?

**Comment by haon4** [comment]
I had a chat with Yilun about this. We have some ideas, but not enough free cycles :( Once Yilun finishes up his current project he might be able to look designing this.

**Comment by htuch** [comment]
Great. Meanwhile, we will add support in Envoy for handling the proto3 ingestion path using reflection and then we can consume the JSON support for that path as it becomes available.
