### ISSUE TITLE
It's doesn't generate properly a property of a message 

### ISSUE THREAD

**Issue by donutloop** [protocolbuffers/protobuf#5969]
### What version of protobuf and what language are you using?
Version: libprotoc 3.7.0
Language: GOLANG

### What version of Go are you using (`go version`)?

go version go1.12 darwin/amd64

### What operating system (Linux, Windows, …) and version?

MacOS Mojave 10.14.1 (18B75)

### What did you do?

i had defined a message in Protobuffer this message contains a property called  "last_12_months_profit" if i generate the code for this message then i don't get a property called "last12MonthsProfit".

Input:

```go
message Company {
    Last12MonthsProfit last_12_months_profit = 1;
}
```

or 

```go
message Company {
    Last12MonthsProfit last_12_months_profit = 1 [(gogoproto.customname) = "last_12_months_profit "];
}
```

### What did you expect to see?

Output:

```go
type Company struct {
	Last12MonthsProfit   *Last12MonthsProfit   `protobuf:"bytes,1,opt,name=last_12_months_profit,json=last12MonthsProfit,proto3" json:"last_12_months_profit,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}
```
### What did you see instead?

Output:

```go
type Company struct {
	Last_12MonthsProfit   *Last12MonthsProfit   `protobuf:"bytes,1,opt,name=last_12_months_profit,json=last12MonthsProfit,proto3" json:"last_12_months_profit,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}
```

**Comment by BSBandme** [comment]
Please re-post the issue in [golang repo](https://github.com/golang/protobuf)
