### ISSUE TITLE
DescriptorProtos.java not contained in com.google.protobuf package

### ISSUE THREAD

**Issue by astrolamb-gaming** [protocolbuffers/protobuf#5971]
For whatever reason the file just isn't there.

EDIT: I found a fix here: https://stackoverflow.com/a/11697573/6872372 But it seems logical to include that file along with the others in the java source code.

**Comment by BSBandme** [comment]
I think after `mvn package` under java directory, you should build a jar library with the generated descriptors and all the other library files inside.
