### ISSUE TITLE
protobuf-java is not yet released for 3.7.1

### ISSUE THREAD

**Issue by andreamlin** [protocolbuffers/protobuf#5972]
All of our tooling, across 7 different languages, uses the same protobuf version. It would be very nice to have a 3.7.1 release for [protobuf-java](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/).

**Comment by acozzette** [comment]
I just now published the 3.7.1 Java artifacts, so they should appear on Maven Central soon.

**Comment by andreamlin** [comment]
Thank you!
