### ISSUE TITLE
Variables in generated code can't start from digit

### ISSUE THREAD

**Issue by telezhnaya** [protocolbuffers/protobuf#5973]
**What version of protobuf and what language are you using?**

master + Python 3.5

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 18.04.1 LTS

**What did you do?**

Just created `1.proto` file. (That was my random name) And generated the code.

**What did you expect to see**

Correct generated code.

**What did you see instead?**

Incorrect syntax: some variable names start from digit (1). I compared my code with official GRPC example, and yes: these variables are using filename for naming. I guess you need to make checks if the variable name is correct for chosen language. I also suppose that it's not only Python issue, digits at the beginning of variable names are prohibited in most of the programming languages.

Generated code (incorrect):

```
rpc_method_handlers = {
      'GetMode': grpc.unary_unary_rpc_method_handler(
          servicer.GetMode,
          request_deserializer=1__pb2.Empty.FromString,
          response_serializer=1__pb2.SystemMode.SerializeToString,
      ),
  }
```

It's not hard to guess that the problem is wider. Try also `%.proto` or `a b.proto` (with space). These examples are synthetic, but the first one (with digit) was just my real attempt to try GRPC.

**Comment by anandolee** [comment]
We have changed our generated code a lot. Can you help verify if it is still an issue?
Close it for clean up. Feel free to reopen if it is still an issue
