### ISSUE TITLE
Why use UnsafeUtil to write message to byte array instead of directly array assignment operation?

### ISSUE THREAD

**Issue by wenjuanhenxing** [protocolbuffers/protobuf#5974]
In CodedOutputStream, it use UnsafeUtil to write message to byte array default,  instead of array assignment operation. I want to know why? May be improve performance?

My protobuf-java version is 3.6.1, and I run test case of unsafe operation and directly array assignment operation locally, the performance basically the same, even unsafe operation slower.

There's the code:
![image](https://user-images.githubusercontent.com/20475077/55287477-dcde2500-53db-11e9-864b-54cbbeaeba46.png)

**Comment by BSBandme** [comment]
There are different encoding ways, including using array.
Some downstream library may use the directly allocated memory for encoding, e.g. GRPC. Some  reasons like not being affected by gc, skipping the auto generated native array boundary check and some other reason.

**Comment by wenjuanhenxing** [comment]
> There are different encoding ways, including using array.
> Some downstream library may use the directly allocated memory for encoding, e.g. GRPC. Some reasons like not being affected by gc, skipping the auto generated native array boundary check and some other reason.

 I still don't understand "Some reasons like not being affected by gc, skipping the auto generated native array boundary check", can you explain it？
