### ISSUE TITLE
missing version 2.5.0in repository

### ISSUE THREAD

**Issue by domaniqs** [protocolbuffers/protobuf#5986]
Hi,
I need version 2.5.0 in order to make PLINK/SEQ genetics library work properly according to this document:
[https://atgu.mgh.harvard.edu/plinkseq/install.shtml#source](url)
Can you point me into the right direction where I can get it from?
Thanks
Maciej

**Comment by acozzette** [comment]
I don't think we have kept published releases going back that far, but you can just clone the Git repo and check out the v2.5.0 tag.

**Comment by domaniqs** [comment]
it is here:
[https://github.com/protocolbuffers/protobuf/releases/tag/v2.5.0](url)
 thanks!
