### ISSUE TITLE
Using Empty message in oneof fields

### ISSUE THREAD

**Issue by dilipvamsi** [protocolbuffers/protobuf#5987]
https://github.com/protocolbuffers/protobuf/blob/8e5b2f1b821c1f42b28db4c276f71e50ff1bf0e7/src/google/protobuf/empty.proto#L52

```protobuf
message Sample {
  oneof SampleOneof {
    // any boolean value works, as it is just about the oneof should be presence.
    bool presence = 1;
    int int_val = 2;
  }
}
```

Is there a away to use `Empty` instead of `bool` to check whether presence is the actual oneof used.

Regards,
Dilip Vamsi.

**Comment by acozzette** [comment]
With a `oneof` you can already tell which field is set or if it's empty, so I don't think you need an additional `presence` field unless I'm misunderstanding something.
