### ISSUE TITLE
crash in multi-thread

### ISSUE THREAD

**Issue by leeqx** [protocolbuffers/protobuf#5989]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
linux centos 6.3

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 4.8

**What did you do?**

use protobuf in multi-thread.

log  and crash:
CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may in        dicate a bug in protocol buffers or it may be caused by concurrent modification of the message.

**Comment by echoht** [comment]
hi @leeqx 
I have the same crash. how to fix this problem?
