### ISSUE TITLE
Reference the original externally defined class into .proto file

### ISSUE THREAD

**Issue by AngusMonroe** [protocolbuffers/protobuf#5990]
Hi, I've some problems when writing .proto file.

Protocol Buffer requires to define protocol format by creating a .proto file. It contains the data structure that needs to be serialized. And then the .proto file will be converted to a .cs file. But if I define the externally defined classes in the .proto file, it will conflict with the original definition.

In other words, I can't reference the original externally defined class into the class generated by Protobuf. I tried to combine the code generated by it into the original classes but Protobuf could not generate code if there is undefined class.

It would be helpful if someone could give me some suggestions.

Thanks and best regards!

**Comment by BSBandme** [comment]
Do you mean generating one proto with some dependencies proto file missing?
Sorry but I think this can't be done since protoc has to build the whole transitive closure of the top proto file.

**Comment by AngusMonroe** [comment]
In fact, I want to import externally defined C# class to the proto file. Fortunately, I solve this problem by using protobuf-net.
Anyway, thanks for your response.

**Comment by elharo** [comment]
WAI. You can't do that.
