### ISSUE TITLE
Provide an option to remove __FILE__ in generated C++ header

### ISSUE THREAD

**Issue by xhwang-chromium** [protocolbuffers/protobuf#5995]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
All

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
Check strings exposed by release build of Chrome on Linux.
$ strings /opt/google/chrome/chrome | grep pb.cc

**What did you expect to see**
No paths of pb.cc files

**What did you see instead?**
...
gen/components/policy/proto/cloud_policy.pb.cc
gen/components/dom_distiller/core/proto/adaboost.pb.cc
gen/components/download/internal/background_service/proto/request.pb.cc
gen/third_party/metrics_proto/memory_leak_report.pb.cc
gen/third_party/metrics_proto/ukm/report.pb.cc
...

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
This is caused by the __FILE__ in GOOGLE_PROTOBUF_VERIFY_VERSION in src/google/protobuf/stubs/common.h, which is in every generated pb.cc file. As a result, it increased Chrome binary size by 12kB without obvious user benefit.

It would be great not to include __FILE__ in release builds, or at least provide an option to disable it.

**Comment by nico** [comment]
(The background is that we control which version of protoc and libprotobuf is used in chrome builds, so the version check doesn't do anything for us.)

**Comment by xhwang-chromium** [comment]
Kindly ping! Or shall I just upload a pull request to solve it? Thanks!

**Comment by acozzette** [comment]
Maybe a good solution would be that we only define `GOOGLE_PROTOBUF_VERIFY_VERSION` in `stubs/common.h` if it's not already defined. That way you could define it to do nothing by passing `-DGOOGLE_PROTOBUF_VERIFY_VERSION`. Do you want to send a pull request to make that change?

**Comment by xhwang-chromium** [comment]
The plan sgtm. I've not worked on this code base before, so if you could quickly fix it it'll be great. Otherwise I can give it a try. Please let me know what you think! Thanks!

**Comment by acozzette** [comment]
If you could give it a try that would be great because I have my hands full with other things right now.

**Comment by xhwang-chromium** [comment]
Sure, I'll give it a try. Thanks for letting me know!

**Comment by acozzette** [comment]
I don't think this is an issue anymore, because we no longer generate a call to `GOOGLE_PROTOBUF_VERIFY_VERSION` in `pb.cc` files.
