### ISSUE TITLE
Java: Message to Message.Builder Relationship

### ISSUE THREAD

**Issue by Fleshgrinder** [protocolbuffers/protobuf#5996]
**What language does this apply to?** 
Java

**Describe the problem you are trying to solve.**
Writing type-safe extension functions in Kotlin.

**Describe the solution you'd like**
Generic `Message` and `Builder` classes that ensure type-safety.

**Describe alternatives you've considered**
Unchecked casting…

**Additional context**
Both the `com.google.protobuf.Message` and `com.google.protobuf.Message.Builder` interfaces are defined without any relation to each other. This makes it hard to write type-safe extensions in Kotlin. Consider the following:

```kotlin
import com.google.protobuf.Message
import com.google.protobuf.Message.Builder
import com.google.protobuf.Timestamp

fun <M : Message, B : Builder> M.copy(action: B.() -> Unit): M =
    (toBuilder() as B).apply(action).build() as M

fun f(t: Timestamp) {
    t.copy<Timestamp, Timestamp.Builder> { /*…*/ }
}
```

In theory this looks good, however, in practice it is not nice to use because there is no relation between `Message` and `Builder` and thus the caller has to provide the necessary type information; which might be wrong.

Defining `Message` and `Message.Builder` in a clear relationship to each other would solve the problem.

```java
import org.jetbrains.annotations.NotNull;

interface Message<Self extends Message<Self, B>, B extends Message.Builder<Self, B>> {
    @NotNull B toBuilder();
    
    interface Builder<M extends Message<M, Self>, Self extends Builder<M, Self>> {
        @NotNull M build();
    }
}
```

```kotlin
fun <M : Message<M, B>, B : Message.Builder<M, B>> M.copy(action: B.() -> Unit): M =
    toBuilder().apply(action).build()

class Timestamp : Message<Timestamp, Timestamp.Builder> {
    override fun toBuilder(): Builder = TODO()

    class Builder : Message.Builder<Timestamp, Timestamp.Builder> {
        override fun build(): Timestamp = TODO()
    }
}

fun f(t: Timestamp) {
    t.copy { /*…*/ }
}
```

Notice I can call _copy_ without providing any additional type information.

**Comment by BSBandme** [comment]
Sorry but I have very little background in Kotlin. We have a generic interface of [MessageOrBuilder](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/MessageOrBuilder.java) which both Message and Message.Builder will implements. And for each generated message we will also generate a MessageOrBuilder which contains message and builder's shared methods, e.g. `message Foo` will generate a FooOrBuilder interface. Is this what you need?

**Comment by Fleshgrinder** [comment]
Sadly that does not help because the interface does not expose functions like `toBuilder` which returns the builder of the right type. Note that you don’t need experience in Kotlin to benefit from a proper relationship. Almost everything that Kotlin can do can be done in Java too, it usually just requires more typing.

```java
import org.jetbrains.annotations.NotNull;

import java.util.function.Consumer;

interface Message<Self extends Message<Self, B>, B extends Message.Builder<Self, B>> {
    @NotNull B toBuilder();

    interface Builder<M extends Message<M, Self>, Self extends Builder<M, Self>> {
        @NotNull M build();
    }
}

final class Timestamp implements Message<Timestamp, Timestamp.Builder> {
    @Override
    public @NotNull Builder toBuilder() {
        return new Builder();
    }

    final static class Builder implements Message.Builder<Timestamp, Builder> {
        @NotNull Builder setSeconds(final long seconds) {
            return this;
        }
        
        @NotNull Builder setNanos(final int nanos) {
            return this;
        }
        
        @Override
        public @NotNull Timestamp build() {
            return new Timestamp();
        }
    }
}

public class Main {
    static <M extends Message<M, B>, B extends Message.Builder<M, B>> @NotNull M copy(
        final @NotNull M message,
        final @NotNull Consumer<B> action
    ) {
        final B builder = message.toBuilder();
        action.accept(builder);
        return builder.build();
    }

    public static void main(String[] args) {
        final Timestamp ts1 = new Timestamp();

        final Timestamp ts2 = copy(ts1, builder -> {
            builder.setSeconds(1);
            builder.setNanos(1);
        });
    }
}
```

Of course, the functionality is not as useful in Java as it is in Kotlin, but it should clarify what this request is about. Basically we create a true relationship between a message and its builder. Note that this also enables us to add true covariant return methods to parents (with a safe unchecked cast):

```java
@SuppressWarnings("unchecked")
interface Message<Self extends Message<Self, B>, B extends Message.Builder<Self, B>> {
    default @NotNull Self covariance() {
        return (Self) this;
    }

    interface Builder<M extends Message<M, Self>, Self extends Builder<M, Self>> {
        default @NotNull Self covariance() {
            return (Self) this;
        }
    }
}
```

**Comment by BSBandme** [comment]
OK, just got what you mean here.

I think changing interface directly is some kind of hard since it's a breaking change. Maybe it can be solved by adding a new class layer between generated class and GeneratedMessageV3 but it also need to regenerate all the protos to make it work.

@haon4 for acknowledgement, do you have any ideas here?

**Comment by Fleshgrinder** [comment]
Simply adding additional interfaces shouldn’t be a big deal. They can be empty at first and just be markers for the relationship. Regeneration is necessary, yes, but users who wish to use it won’t have a problem with that.

**Comment by haon4** [comment]
You can do this in your use-case with Plugin Insertion Points: (https://developers.google.com/protocol-buffers/docs/reference/java-generated#plugins). Look for @@protoc_insertion_point(message_implements:NAME) and insert your own implementation there. There is also builder_implements that you can use.

**Comment by Fleshgrinder** [comment]
Not really helpful because that code is confined to a single repo and cannot be shared easily unless the generated code is shared too, or a special plugin is created. As illustrated, this relationship would also be helpful for the Protobuf codebase because of real covariance. I'm certain that various constructs could be simplified.

**Comment by bahtiyarkaba** [comment]
@Fleshgrinder I'm having a similar problem. I was just wondering if you'd found a good way around this other than downcasting to the actual message type.

**Comment by Fleshgrinder** [comment]
@bahtiyarkaba The easiest workaround is to define your own interfaces and let each generated message implement them. However, this does not work for the built in types if I remember correctly because they are shipped with the Java library and never generated. It's very sad that this issue was directly closed. 😞 

One way to go about this is to add a very simple Gradle task that runs after the code generation and iterates over all generated files doing a simple string search and replace for the insertion markers. Let me know if you need more support. I could cook up a quick demo repo for you if you need it.

**Comment by bahtiyarkaba** [comment]
Thanks you for your prompt response. I looked up to the insertion points but I think it's not well documented. I'm having a hard time translating what I have in mind to a way . 
What I would want is a way for Message.Builder to be like Message.Builder<T> so that parametrized types of Message.Builder

**Comment by bahtiyarkaba** [comment]
@Fleshgrinder  Thank you for your quick reply!!
I looked up to insertion points but I have a hard time translating what I have in my mind to a way that I can achieve it with those. 
What I would need is a way to have `Message.Builder<? extends Message>` so that I can use the builder in a generic context with proper type checking. 
Does your suggestion mean that I should define a builder type myself and modify the generated code to implement that interface? This will require considerable effort I expect. Maybe I'm missing something.

**Comment by Fleshgrinder** [comment]
The Protobuf generated code contains insertion points in form of comments. The are standardized and you can just filter for them. The allow you to insert arbitrary code. What you can do is to create a task in Gradle that finalizes the Protobuf code generation by going through the generated files looking for those insertion points. Now you can simply replace the comment with your interface.

And, yes, you need to define those interfaces yourself.
