### ISSUE TITLE
Unable to compile proto files on versions greater than 3.4.0

### ISSUE THREAD

**Issue by ranjanbinwani** [protocolbuffers/protobuf#5997]
When I type this command in the prompt all the proto files are compiled successfully.
This is when I have protoc-3.4.0-win32 installed.

 C:\TensorFlow\models\research>"C:\protoc-3.4.0-win32\bin\protoc.exe" object_detection/protos/*.proto --python_out=.

When I have protoc-3.7.1-win64 installed and on running the command 
"C:\protoc-3.7.1-win64\bin\protoc.exe" object_detection/protos/*.proto --python_out=.

I get the following error
object_detection/protos/*.proto: No such file or directory

I get the above error for all versions above 3.4.0
Please help me with this...

**Comment by BSBandme** [comment]
Maybe you may try to use dir and pipe to specify all the files with a filename pattern.
