### ISSUE TITLE
HasField() returns False on oneof fields if nothing is set, but ValueError if one of the fields in the oneof is

### ISSUE THREAD

**Issue by tamias65** [protocolbuffers/protobuf#6008]
Version: v3.7.0
Language: Python

MacOS 10.14

Python 2.7

Given a message

```
message Foo {
    oneof test_oneof {
        int32 value = 1;
        google.protobuf.Int32Value value_2 = 2;
    }
}
```
Currently
```
Foo.value_2.value = 10
Foo.HasField('test_oneof')  # Raises ValueError:Can't test field "Foo.test_oneof" for presence in proto3, use WhichOneof instead.
```
But if `value` and `value_2` are not set,
```
Foo.ClearField('test_oneof')
Foo.HasField('test_oneof')  # Returns False
```
Seems inconsistent that one could actually test the presence of a oneof field depending on the values of the fields within. I would expect that `Foo.HasField("test_oneof")` always raises ValueError.

**Comment by anandolee** [comment]
Close it because we believe this should has been fixed. We did lot of changes for oneof and proto3 has presence these two years. 
Feel free to reopen if it is still an issue
