### ISSUE TITLE
C++ linker "multiple definition" errors caused by messages with same name in different protobuf packages

### ISSUE THREAD

**Issue by feedhandler** [protocolbuffers/protobuf#6010]
Hi, I'm trying to build a C++ linux app which uses protobuf files from two different protobuf packages. The build is failing because of "multiple definition" errors from the linker. These seem to be caused because there is a message with the same name in both packages.

I've put a minimal example in https://github.com/feedhandler/stuff/tree/master/protobuf/clash 
In that example there are two packages, A and B, and there is a message Foo in both packages. The linker errors are like this:
```
multiple definition of `InitDefaults_Foo_2eproto()'
multiple definition of `file_level_metadata_Foo_2eproto'
multiple definition of `TableStruct_Foo_2eproto::offsets'
multiple definition of `assign_descriptors_table_Foo_2eproto'
multiple definition of `AddDescriptors_Foo_2eproto()'
```
Any ideas how I can fix this problem?

(Note: I'm not allowed to edit the *.proto files in my real app, so I can't do things like change the "import" statement in Foo.proto)

Environment:

- protobuf C++ 3.7.1
- g++ 5.4.1
- Ubuntu 16.04 64-bit

Thanks

**Comment by acozzette** [comment]
I think the problem is your `protoc` commands:
```
protoc --proto_path=A --cpp_out=a Foo.proto Bar.proto
protoc --proto_path=B --cpp_out=b Foo.proto Baz.proto
```

Protoc likes to have its own notion of a unique logical path to each .proto file, and so in this case both versions of Foo.proto have the same path, which causes a conflict (likewise for Bar.proto). If you change your protoc commands to something like this then each file will get a different logical path.
```
protoc --proto_path=. --cpp_out=a A/Foo.proto A/Bar.proto
protoc --proto_path=. --cpp_out=b B/Foo.proto B/Baz.proto
```

**Comment by feedhandler** [comment]
That doesn't work because it breaks the `import` statement:
```
dmsdev@dmsdev-VirtualBox> make
pkg-config --cflags protobuf  # fails if protobuf is not installed
-pthread -I/usr/local/include
mkdir -p a b
protoc --proto_path=. --cpp_out=a A/Foo.proto A/Bar.proto
Bar.proto: File not found.
A/Foo.proto: Import "Bar.proto" was not found or had errors.
A/Foo.proto:9:3: "Bar" is not defined.
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
dmsdev@dmsdev-VirtualBox>
```
Could you reopen this issue please?

**Comment by acozzette** [comment]
Your import statements need to be updated to reference the full paths, e.g. `A/Foo.proto` instead of just `Foo.proto`.

**Comment by feedhandler** [comment]
Unfortunately in the real app I'm not able to edit the *.proto files, so I can't update the import statements

**Comment by acozzette** [comment]
How did the .proto files end up having the same name? That sounds like a strange coincidence. It might be worth asking the upstream maintainers if they could choose more descriptive file names for their .proto files.

**Comment by feedhandler** [comment]
The app is intended to be a kind of universal decoder for viewing messages on a message bus. There are many systems using this message bus, and the different systems encode their messages in different ways. The decoder knows what kind of encoding is used in a specific message by looking at the message topic. Some systems encode using protobuf, others use different forms of binary encoding (non-protobuf). And of the protobuf-encoded messages, some use protobuf package "A" and some use protobuf package "B"
In packages A and B there are around 10 to 15 proto files in each package, and it just happens that one of them has the same name in both packages. I guess it's just coincidence that they have the same name. 

It's unlikely that the upstream maintainer would agree to rename the files as there are many systems already using these protobufs without problem, it's only in this app that we are having the problem.

**Comment by acozzette** [comment]
OK, I see. I'm afraid there is no good workaround except to tweak the `.proto` files and build setup so that each `.proto` file has a unique path. Protobuf is just not set up to accommodate multiple `.proto` files with the same path (and by path I mean the logical path to the file, including the file name). For example you can look up the descriptor for a file by calling `DescriptorPool::generated_pool()::FindFileByName("path/to/my/file.proto")`, and this wouldn't make any sense if there were more than one `.proto` file at that logical path.
