### ISSUE TITLE
Enable -Werror when building protobuf itself

### ISSUE THREAD

**Issue by keith** [protocolbuffers/protobuf#6015]
**What language does this apply to?**

None

**Describe the problem you are trying to solve.**

Currently building protobuf itself for bazel related tools can produce some warnings like the ones fixed here:

- https://github.com/protocolbuffers/protobuf/pull/6011
- https://github.com/protocolbuffers/protobuf/pull/6014

This produces noisy output for users, and makes it impossible to enable `--host_copt=-Werror` for other tools.

**Describe the solution you'd like**

To make sure new warnings aren't introduced, it would be great to enable `-Werror` on protobuf's CI.

**Describe alternatives you've considered**

Alternatively we can force all users to disable all warnings produced by protobuf (which also will work if https://github.com/protocolbuffers/protobuf/pull/6013 is merged) but that doesn't seem ideal.

**Additional context**

There are some other issues about using `-Werror` with proto generated code, but those are unrelated since this is about when building protobuf itself.

**Comment by acozzette** [comment]
This is probably doable if we can find a good solution for #6014.

**Comment by keith** [comment]
@acozzette is it feasible for me to make the changes for the CI setup for this, or is this something a Googler has to do?

**Comment by acozzette** [comment]
@keith I think it might be easiest to just edit the BUILD file and then there's no need to worry about the CI config.

**Comment by keith** [comment]
One worry I had about that is that it would apply to all consumers too, which could end up creating difficult issues to workaround like the ones caused by https://github.com/protocolbuffers/protobuf/pull/6013

**Comment by acozzette** [comment]
Ah OK, I see. I guess if consumers pass stricter warning flags then those would turn into errors.

I think updating the CI should just be a matter of adding additional Bazel flags in this file: https://github.com/protocolbuffers/protobuf/blob/master/kokoro/linux/bazel/build.sh

**Comment by keith** [comment]
I've submitted https://github.com/protocolbuffers/protobuf/pull/6022 for this

**Comment by keith** [comment]
Here's another PR with some more warning fixes https://github.com/protocolbuffers/protobuf/pull/6025

**Comment by keith** [comment]
Thanks for all the help @acozzette !
