### ISSUE TITLE
Unable to load dynamic library 'protobuf.so' with PHP-ZTS

### ISSUE THREAD

**Issue by nonenullnil** [protocolbuffers/protobuf#6017]
**What version of protobuf and what language are you using?**
Version: 3.7.0
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux Centos7

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.2.16 (cli) (built: Mar 10 2019 21:32:28) ( ZTS )

**What did you do?**
Install protobuf for PHP-ZTS (Zend Thread Safety)

**What did you expect to see**
It works fine in PHP non-thread safe version, so i expect it works with PHP-ZTS

**What did you see instead?**
However, I got the follow error message when ZTS (Zend Thread Safety) is enabled : 
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'protobuf.so' (tried: /usr/lib64/php-zts/modules/protobuf.so (/usr/lib64/php-zts/modules/protobuf.so: undefined symbol: executor_globals), /usr/lib64/php-zts/modules/protobuf.so.so (/usr/lib64/php-zts/modules/protobuf.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

The following are the steps that produce the protobuf.so:
```
[root@799cd62cfcee ext]# wget https://pecl.php.net/get/protobuf-3.7.0.tgz
[root@799cd62cfcee ext]# tar -xvf protobuf-3.7.0.tgz
[root@799cd62cfcee ext]# cd protobuf-3.7.0
[root@799cd62cfcee protobuf-3.7.0]# zts-phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
[root@799cd62cfcee protobuf-3.7.0]# ./configure --with-php-config=/usr/bin/zts-php-config
[root@799cd62cfcee protobuf-3.7.0]# make

...

[root@799cd62cfcee protobuf-3.7.0] cp ../modules/protobuf.so /usr/lib64/php-zts/modules/
```
Could someone please let me know if i got something wrong? Thank you very much.

**Comment by TeBoring** [comment]
When you are building, are you sure you have used the correct php header?
It seems to me you are using non-zts header when building protobuf.so

**Comment by TeBoring** [comment]
Could you try ```php --version``` and paste the result?

**Comment by TeBoring** [comment]
And how did you install zts-php?
