### ISSUE TITLE
Enum values not defined in enum class

### ISSUE THREAD

**Issue by plannigan** [protocolbuffers/protobuf#6028]
The [documentation for enum](https://developers.google.com/protocol-buffers/docs/reference/python-generated#enum) says:

> For example, you can access the values in the three following ways for the following enum in a proto:

```protobuf
enum SomeEnum {
    VALUE_A = 0;
    VALUE_B = 5;
    VALUE_C = 1234;
}
```

```python
value-a = myproto_pb2.SomeEnum.VALUE_A
# or
myproto_pb2.VALUE_A
# or
myproto_pb2.SomeEnum.Value('VALUE_A')
```
But `value-a = myproto_pb2.SomeEnum.VALUE_A` fails.

**What version of protobuf and what language are you using?**
Version: v3.7.1/v3.6.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Xubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
1. Save the proto definition from the documentation to a file name `myproto.proto`.
2. Generate the python code:
```
./protoc --python_out=. --proto_path=. myproto.proto 
```
3. Attempt to access the value in the ways the documentation demonstrates.
```
python -c "import myproto_pb2; print(myproto_pb2.SomeEnum.Value('VALUE_A')); print(myproto_pb2.VALUE_A); print(myproto_pb2.SomeEnum.VALUE_A);"
```

**What did you expect to see**
```
0
0
0
```

**What did you see instead?**
```
0
0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'EnumTypeWrapper' object has no attribute 'VALUE_A'
```

**Comment by anandolee** [comment]
The __getattr__ is added in this PR which is not release in v3.7.1 I think:
https://github.com/protocolbuffers/protobuf/commit/0de6577b7d5702a133f0eade4ddf6b94893e975a#diff-abebaaaa517a7cbc213cb3d39c6e444b

**Comment by pkalebu** [comment]
what's the correct way to get the value of an enum then?

**Comment by markisus** [comment]
@pkalebu It looks like you have to do `myproto_pb2.SomeEnum.Value('VALUE_A')`

**Comment by timgrossmann** [comment]
@markisus Thanks for this, looks like the documentation needs quite some updates to conform to Proto3 😅 

Would've needed to read the actual commit changes to get the answer to read the enum values.
Unfortunately due to this changes, even the most downloaded VS-Code plugin will show errors for valid code...
