### ISSUE TITLE
Convert bytestream from nanopb to a string that can be parsed in python

### ISSUE THREAD

**Issue by ocraml** [protocolbuffers/protobuf#6030]
In my.proto I defined a message:

```
message ProtoCommandResponse {
	required uint32 command = 1;
	required bool status = 2 [default = true];
	optional uint32 data = 3 [default = 0];
}
```

In my C Project I encode a message with
```
testproto()
{
   proto_command_response_t test_responsemsg = {.command = 123,.data=0x123};
    uint8 buffer[10];
    pb_ostream_t stream = pb_ostream_from_buffer(buffer, sizeof(buffer));
    pb_encode(&stream, proto_command_response_fields, &test_responsemsg);
    send(buffer, stream.bytes_written);
}
```

in Python I want to parse this back into the protbuf message:
cmdresponse = my_pb2.ProtoCommandResponse

I receive the message in python as a list of integer values that correspond with the char array in c:
```
datain = [8, 123, 16, 0]
datastr = ''.join(str(i) for i in datain)
datastr = 8123160
```

How can I parse It back to a protobuf message?

I tried with ParseFromString, but both times got an error:

cmdresponse.ParseFromString(datain)
descriptor 'ParseFromString' requires a 'google.protobuf.pyext._message.CMessage' object but received a 'list'

cmdresponse.ParseFromString(datastr)
descriptor 'ParseFromString' requires a 'google.protobuf.pyext._message.CMessage' object but received a 'str'

**Comment by ocraml** [comment]
Answering my onwn question:
First I missed the brackets at the end of 
`cmdresponse = my_pb2.ProtoCommandResponse**()**`

then it asks for bytes rather than for CMessage, which thinking of it makes a lot more sense. Consequently straight foward to solve. In the following confirmed that it is read in correct.

```
mycmd = my_pb2.ProtoCommandResponse()
#fill the message in python
mycmd.command = 123
mycmd.status = False
mycmd.data = 0x123
mystr = mycmd.SerializeToString()
print(mystr)

#the char values from the nanopb
datain = [8, 123, 16, 0]
databytes = bytes(datain) #convert to format SerializeToString() can eat
print(databytes)

#read in the databytes and confirm that serialized is equal
newcmd = mytest_pb2.ProtoCommandResponse()
newcmd.ParseFromString(databytes)
newstr = mycmd.SerializeToString()
print(newstr)
```

Maybe worth noticing that this c-code line
`proto_command_response_t test_responsemsg = {.command = 123,.data=0x123};`
 I missed to init the required field status expecing it to have the default value. Since in C it's jus a structure it take the value I initialized it with and that is for a partly initialized struct just 0 for the uninitialized values.

**Comment by hldfxh** [comment]
Thanks, I've made the same mistake - -b

**Comment by thepretenderlee** [comment]
Thx. The same brackets issue confused me for some days
