### ISSUE TITLE
Weird string behaviour on MacOS (all string ptrs seem to refer to/modify the same char buffer)

### ISSUE THREAD

**Issue by DanVorobiev** [protocolbuffers/protobuf#6031]
Version: v3.7.0 (v3.6.1 shows same behavior for me)
Language: C++ 
MacOS Mojave 10.14.2
XCode 10.1 (tried all compiler options, C++11..17, Gnu11..17, same problem)

1. Starting with trivial api.proto:
``` 
syntax = "proto3";
message RegisterRequest {
    string device_id = 1;
    string device_type = 2;
}
```

2. Trivial main.cpp:
```
#include "api.pb.h"
#include <iostream>

int main(int argc, const char * argv[])
{
    RegisterRequest* Request = new RegisterRequest();
    Request->set_device_type("123");
    Request->set_device_id("456789");

    std::cout << "DeviceType:" << Request->device_type() << ", DeviceID:" << Request->device_id() << "\n";
    return 0;
}
```

3. After compiling and linking against libprotobuf.a, I see same text for both string fields:
```
DeviceType:456789, DeviceID:456789
```

Adding more string fields to message reproduces the pattern, all string ptrs seem to point to the same char buffer.

My impression is that all setter-methods (tried every kind, including mutable and set_allocated) just modify the same static "default-value buffer" instead of allocating new values for each field.

Maybe I miss some preprocessor definitions necessary for MacOS? 
(Win libraries work fine; I even managed to do Android/iOS builds without major problems; but currently out of clues for this MacOS behavior).

Please advise :)

**Comment by acozzette** [comment]
I don't see any obvious reason for why that would happen. Maybe if you step through it with a debugger that could give you some clues to what's happening. I would also be curious to know if `Request->mutable_device_type()` and `Request->mutable_device_id()` are returning the same pointer. If you could run your program under a tool like ASan (AddressSanitizer) that might give some useful information, too.

**Comment by DanVorobiev** [comment]
Thanks for sharing your thoughts :)

In that small isolated example - actually mutable_xxx() return different ptrs, and after those calls situation seems to be magically normalized:
```int main(int argc, const char * argv[])
{
    RegisterRequest* Request = new RegisterRequest();

    Request->set_device_type("123");
    Request->set_device_id("456789");
    std::cout << "DeviceType:" << Request->device_type() << ", DeviceID:" << Request->device_id() << "\n";
 
    std::string* device_id = Request->mutable_device_id();
    std::string* device_type = Request->mutable_device_type();
    std::cout << "mutable device_type:" << device_type << ", mutable device_id:" << device_id << "\n";
    
    *device_id = "1234";
    *device_type = "56789";
    std::cout << "DeviceType:" << Request->device_type() << ", DeviceID:" << Request->device_id() << "\n";

    Request->set_device_type("12345");
    Request->set_device_id("6789");
    std::cout << "DeviceType:" << Request->device_type() << ", DeviceID:" << Request->device_id() << "\n";

    return 0;
}```

yielding:
```
DeviceType:456789, DeviceID:456789
mutable device_type:0x100667470, mutable device_id:0x10066e880
DeviceType:56789, DeviceID:1234
DeviceType:12345, DeviceID:6789
```

Pity that in a bigger, original situation (which is, sadly, inside Unreal4 build chain) - all returned mutable pointers appear to be the very same address, even for different message instances :-\
```
LogTemp: Warning: (Req1) Mutable PTRS DeviceType: 0x695f8848, DeviceID: 0x695f8848
LogTemp: Warning: (Req2) Mutable PTRS DeviceType: 0x695f8848, DeviceID: 0x695f8848
```
That is while building against the same 3.7.0 protobuf library/includes (but most probably with lots of different compiler/linker options and somewhat different toolchain :-\

Alas, seems necessary to dig into ArenaStringPtr implementation with debugger, with all the extra fun of Unreal memory allocation/garbage collection... :-\

**Comment by acozzette** [comment]
You might want to double check that the version of `protoc` you're using to generate code exactly matches the `libprotobuf` version you link against and the headers you include. We have some compile-time checks to help enforce that but we got some reports recently making it sound like that enforcement stopped working (I need to look into that more but haven't had a chance yet).

**Comment by DanVorobiev** [comment]
Thank you, acozzette; protoc version was fine, 
but the actual problem traced down to the linkage of PB "default string object".

As it turns out, in our Unreal packaging two different code bodies (transport DLL and main process code) ended up with different values of &::google::protobuf::internal::GetEmptyStringAlreadyInited().
That caused havoc with assigning and releasing all string values in protobuf structures.

Apparent fix is moving all write-access to protobuf messages to one code package;
I wonder, however, what was the original design idea? (for not using flat nullptr value as "default", that absolutely would not depend on linkage mode).

Also, maybe it would be a good idea to note this behaviour somewhere in top-level C++ usage 
documentation? (as the side-effects seem to be pretty strange and not immediately understandable :)

**Comment by acozzette** [comment]
Ah OK, that explanation makes sense. That is ultimately just an ODR (one definition rule) violation, so I think the correct fix is to make sure there is only one copy of `libprotobuf`.

**Comment by chrisikerobotics** [comment]
Hi, we've run into the same issue occurring in a Linux environment (But not on Windows) with Unreal. Could you share what you mean by your different code bodies, were those modules on Unreal?
