### ISSUE TITLE
How to set JSON options to emit fields with default values in proto3

### ISSUE THREAD

**Issue by ganl** [protocolbuffers/protobuf#6035]
**PHP**

https://developers.google.cn/protocol-buffers/docs/proto3#json

> JSON options
> A proto3 JSON implementation may provide the following options:
> 
> Emit fields with default values: Fields with default values are omitted by default in proto3 JSON output. An implementation may provide an option to override this behavior and output fields with their default values.

how to set ？like：`EmitDefaults` or `defaults_json`

```
\Google\Protobuf\Internal\Message::existField 
……
            return $values !== $this->defaultValue($field);
```
Fields with default values are always omitted

**Comment by ganl** [comment]
@TeBoring

**Comment by TeBoring** [comment]
We haven't implemented that option yet. Would you like to contribute a PR? Thanks!

**Comment by patramsey** [comment]
@TeBoring could you point me in the right direction where to hook this in? I'm assuming 
`Google/Protobuf/Internal/Message.php` ?

This would be a great addition in my implementation and I'm happy to help.

**Comment by csuntrane** [comment]
Any idea when this might be implemented. It seems proto2 doesn't have this issue.

**Comment by panol** [comment]
plus one

**Comment by deannagarcia** [comment]
While this is a reasonable request, the protobuf team will not be prioritizing this in the near future. If you send us a PR to add it, we would love to help get it merged!

**Comment by maciek-szn** [comment]
Well, this is great. Google's GTFS-RT specification [requires field `incrementality` in the output file](https://gtfs.org/realtime/reference/#message-feedheader), with its default value (FULL_DATASET). Google's Protobuf compiler cuts off the default values 🤷‍♂️

**Comment by SpencerMalone** [comment]
@deannagarcia I opened a PR for y'all when you have time!
