### ISSUE TITLE
json_format.py in python3.7

### ISSUE THREAD

**Issue by plutodom** [protocolbuffers/protobuf#6038]
OrderedDict([('@type', 'type.googleapis.com/resourcecenter.Subject'), ('id', 101), ('subjectName', 'elementary mathematics')])
As a reponse，I don't need `OrderedDict'and `('@type',`type.googleapis.com/resourcecenter.Subject')
So I modified the code for the _AnyMessageToJsonObject method.
```
    js = OrderedDict()
    type_url = message.type_url
    js['@type'] = type_url
```
to
```
    js = dict()
    type_url = message.type_url
    #js['@type'] = type_url
```
then,the reponse becomes{'id': 101, 'subjectName': 'elementary mathematics'}，That's what I want.

**Comment by anandolee** [comment]
Have '@type' is followed by our json spec:
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any

Missing '@type' will make the json message unable to parse back.

This is expected behavior and we will not change
