### ISSUE TITLE
Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by shifefiei** [protocolbuffers/protobuf#6041]
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence

\n\tat io.grpc.Status.asRuntimeException(Status.java:534)
\n\tat io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:173)
\n\tat io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:94)
\n\tat io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:293)
\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:243)
\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:555)
\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
\n\tat io.grpc.internal.SerializingExecutor.runSerializingExecutor.java:117)
\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
\n\tat java.lang.Thread.run(Thread.java:748)

\nCaused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
\n\tat com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
\n\tat com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:692)
\n\tat com.yxbj.service.grpc.payment.ITunesNotificationRequest.<init>(ITunesNotificationRequest.java:53)
\n\tat com.yxbj.service.grpc.payment.ITunesNotificationRequest.<init>(ITunesNotificationRequest.java:9)
\n\tat com.yxbj.service.grpc.payment.ITunesNotificationRequest$1.parsePartialFrom(ITunesNotificationRequest.java:2000)
\n\tat com.yxbj.service.grpc.payment.ITunesNotificationRequest$1.parsePartialFrom(ITunesNotificationRequest.java:1995)
\n\tat com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
\n\tat com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
\n\tat io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:178)
\n\tat io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:170)
\n\t... 9 more\n"},
"threadContext":{}}

**Comment by haon4** [comment]
It seems like you are trying to parse invalid input. With just a stack-trace, it is impossible for us to debug this. I would suggest double-checking you are parsing the correct proto message.
