### ISSUE TITLE
Repeated Enum is serialized differently in PHP serializeToString() as compared to other languages.

### ISSUE THREAD

**Issue by Prateek-Gupta1** [protocolbuffers/protobuf#6045]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Mac OS Mojave, version: 10.14.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP5.6 runtime

**What did you do?**
I was trying to serialize a message containing "repeated enum type" field using the serializeToString() method and it gave me a different encoding in PHP when compared to other languages like Java and C#.

Example 

```
message Example {
   repeated Filed field = 1
   enum Field {
       Value1 = 1;
       Value2 = 2;
   }
} 
```
Now if I use the protobuf message generated class

```
$example = new Example();
$fields =array();
$fields[] = Example/Field::Value1;
$fields[] = Example/Field::Value2;
$example->setField($fields);
echo $example->serializeToString();

```
**What did you expect to see**
`10 2 1 2 `
For C# and Java it was serialized this way.

**What did you see instead?**
`8 1 8 2`
For PHP

**Comment by TeBoring** [comment]
Seems like enum in php was not serialized as packed by default. This should be fixed.
However, even though it's not packed, our decoder can still handle it.

**Comment by Prateek-Gupta1** [comment]
Hey @TeBoring, we are relying on the serializations to work consistently across different languages. Decoding is working fine.

**Comment by sibinlu** [comment]
@TeBoring is there any update?

**Comment by TeBoring** [comment]
A little confused. In example, only two values added to the list. Why in
encoding there are 4 values?

**Comment by Prateek-Gupta1** [comment]
@TeBoring ,

the encoding in the example can be interpreted as below.

10 2 1 2 -> 10 is the identifier of Field, 2 -> number of entities, 1,2 -> are the values
8 1 8 2 -> 8 is the identifier of Field, 1 -> value1, 8 -> identifier again, 2 -> value2
Hence 4 values.

We encode-decode across different languages, and this bug is causing problems to our cross-platform signing.

**Comment by sibinlu** [comment]
Hey @TeBoring,

The bytes encoding is different from PHP and other SDKs.
Here is some example code you can try out. Here the message is any grpc message contains an enum array. The one Prateek provides is a good example,

In Java, we use 
message.toByteArray()

In PHP, we use
$message -> serializeToString()

However, the bytes are different from the two different ways. We tried C# and Objective-C as well and PHP is the only one different.
We use the message bytes for signing, therefore the bytes need to be exactly the same cross-platform. 

This ticket is created for more than 1 year and I think it is a critical defect that we should resolve. If you are still confused about it, let me know or we can have a short call.

**Comment by TeBoring** [comment]
oh, I see. php didn't by default use packed encoding for repeated enum.
Are you using our pure pure implementation or php c extension?

**Comment by sibinlu** [comment]
I guess PHP pure implementation. 
"grpc/grpc": "^1.20.0",
"google/protobuf": "^3.6.1",

Is there a way to enable `use packed encoding for repeated enum`?

**Comment by sibinlu** [comment]
Thanks TeBoring and I think you are right about the packed encoding. I tested with the [packed=true] option and it works.

**Comment by haberman** [comment]
This was fixed in https://github.com/protocolbuffers/protobuf/pull/7740.
