### ISSUE TITLE
Protobuf message field order in generated classes in PHP is not sorted based on tags as compared to other languages. 

### ISSUE THREAD

**Issue by Prateek-Gupta1** [protocolbuffers/protobuf#6047]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Mac OS Mojave, version: 10.14.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP5.6

**What did you do?**
Noticed one anomaly in the PHP protobuf generated classes. It seems like the generated classes maintains the same order of the fields as they are declared inside the message for PHP as compared to the sorted order (based on the "tag") generated for other languages like Java. 

_**This leads to serialization differences with generated classes for other languages like Java and C#.**_

For example
```
message Example {
  required int32 f = 2;
  required sting ff = 1;
}
```

**What did you expect to see**
```
class Example {
  private $ff = '';
  private f;
}
```
In Java and C# it is generated in this order.

**What did you see instead?**
```
class Example {
   private $f;
   private $ff = '';
}
```
In Php it is generated in above way.

_**This causes inconsistency with other languages when binary encoding the classes to be sent over the grpc channel.**_

**Comment by TeBoring** [comment]
I think this is not required. Any reason you need this feature?

**Comment by Prateek-Gupta1** [comment]
Hey @TeBoring, In my company, we rely on Protobuf serializations to work consistently across all languages as we provide our services in different languages. This PHP inconsistency caused some subtle bugs in our PHP solutions, which we discovered recently. 
Our work around was to manually rearrange the fields in ascending order of their tags. We try to write proto files in this way now, but it gets difficult as we grow and remove/add new fields for some reason. It gets difficult for someone new to the technology as well.

**Comment by TeBoring** [comment]
We can make it ordered in php (for proto3 only).
However, I think you are depending on an undefined behavior of protobuf.
Protobuf's field can come in any order. And there will be other inconsistencies in serialization. e.g., each implementation may choose different hash function for map fields.
You will still meet similar problem in the future.
My suggestion is to not depending on protobuf to be encoded consistently.
