### ISSUE TITLE
py_protobuf_library "directory does not exist" warnings

### ISSUE THREAD

**Issue by KeithMoyer** [protocolbuffers/protobuf#6049]
**What version of protobuf and what language are you using?**
Version: 3.7.1.
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Debian Buster

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 2.7.16
GCC 8.3.0
Bazel 0.24.1

**What did you do?**

1. Build any py_proto_library target with Bazel

**What did you expect to see**

No warnings

**What did you see instead?**

INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/wrappers_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/api_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/duration_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/struct_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/empty_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/timestamp_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/type_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/field_mask_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/compiler/plugin_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/descriptor_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/source_context_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.

**Anything else we should know about your project / environment**

This appears to be related to the backward-compatibility Bazel workaround from 4e7ecde15c0ca8f2efa1e6b85e86469fe54559dc. The source_dir computed does not exist.

That commit indicates it is for compatibility with Bazel 0.4.4 (February 2017) and older, while protobuf's examples/WORKSPACE file already indicates a minimum Bazel version of 0.5.4 (August 2017).

Can this workaround simply be removed?

Simple reproducer:
BUILD
```
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "example",
    srcs = ["example.proto"],
)
```

example.proto
```
syntax = "proto2";

message ExampleProto {
  optional bool foo = 1;
}
```

WORKSPACE
```
workspace(name = "py_proto_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    sha256 = "f1748989842b46fa208b2a6e4e2785133cfcc3e4d43c17fecb023733f0f5443f",
    strip_prefix = "protobuf-3.7.1",
    urls = ["https://github.com/google/protobuf/archive/v3.7.1.tar.gz"],
)

http_archive(
    name = "bazel_skylib",
    sha256 = "bbccf674aa441c266df9894182d80de104cabd19be98be002f6d478aaa31574d",
    strip_prefix = "bazel-skylib-2169ae1c374aab4a09aa90e65efe1a3aad4e279b",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz"],
)

http_archive(
    name = "six_archive",
    build_file = "@com_google_protobuf//:six.BUILD",
    sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
    urls = ["https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz"],
)

bind(
    name = "six",
    actual = "@six_archive//:six",
)

http_archive(
    name = "net_zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)

bind(
    name = "zlib",
    actual = "@net_zlib//:zlib",
)
```

**Comment by dapirian** [comment]
Yes this is very annoying, please fix.

**Comment by smolkaj** [comment]
+1

**Comment by joshburkart** [comment]
Major +1 -- this generates a huge amount of noise in my team's Bazel builds. Are PRs welcome? I'd propose to just remove the warning since its SNR seems extremely low, from this

```c++
      // Make sure disk path exists, warn otherwise.
      if (access(disk_path.c_str(), F_OK) < 0) {
        // Try the original path; it may have just happened to have a '=' in it.
        if (access(parts[i].c_str(), F_OK) < 0) {
          std::cerr << disk_path << ": warning: directory does not exist."
                    << std::endl;
        } else {
          virtual_path = "";
          disk_path = parts[i];
        }
      }
```

to this

```c++
      // Make sure disk path exists.
      if (access(disk_path.c_str(), F_OK) < 0) {
        // Try the original path; it may have just happened to have a '=' in it.
        if (access(parts[i].c_str(), F_OK) >= 0) {
          virtual_path = "";
          disk_path = parts[i];
        }
      }
```

**Comment by habib-farr** [comment]
+1

**Comment by mrheinen** [comment]
+1

**Comment by ben-remedy-ai** [comment]
+1

**Comment by alyssawilk** [comment]
I'm unsure of what the release cadence is on proto but any chance we can get a release build with this fix?  We're eagerly anticipating cleaner builds :-)

**Comment by alyssawilk** [comment]
@acozzette thoughts?

**Comment by acozzette** [comment]
We're hoping to do a release some time this week or next week.

**Comment by alyssawilk** [comment]
Fantastic, thanks!

**Comment by rfan-debug** [comment]
+1

**Comment by xuj8** [comment]
this isn't solved it just got moved to the protobuf library which still has this issue!

**Comment by armandomontanez** [comment]
This problem comes and goes because nothing prevents this warning from slipping back into the build. We really need a flag to make this warning an error, or not be emitted at all.
