### ISSUE TITLE
fix attribute in GPBDescriptor

### ISSUE THREAD

**Issue by kudocc** [protocolbuffers/protobuf#6052]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: Objective-C

In file GPBDescriptor.h, this property is an object but its attribute is `assgin`.

/** Descriptor for the file where the message was defined. */
@property(nonatomic, readonly, assign) GPBFileDescriptor *file;

**Comment by thomasvl** [comment]
That is actually correct, the Descriptor doesn't retain it because if the library ever exposes all the Descriptors off of the FileDescriptor, it would end up being a retain cycle.

**Comment by kudocc** [comment]
@thomasvl why not use `weak` attribute to avoid retain cycle?

**Comment by thomasvl** [comment]
Just likely because things predated when the attribute got added and it hasn't been updated.
