### ISSUE TITLE
google protobuf for JavaScript : type error jspb.Message.getFloatingPointFieldWithDefault 

### ISSUE THREAD

**Issue by DarrenWong** [protocolbuffers/protobuf#6057]
proto 
```
syntax = "proto3";

package message;

message Message {
    int32 id = 1;
    repeated int32 number = 2;
}

message Point3D {
   int32 x = 1; 
   int32 y = 2; 
   int32 z = 3;  
}
```
works goods with following
```
point.setX(1);
console.log(point.getX());
```
but if i change to double type, it throws error 
TypeError: jspb.Message.getFloatingPointFieldWithDefault is not a function

```
message Point3D {
   double x = 1;  
   double y = 2;  
   double z = 3; 
```
A little similar to issue #5930, seems double or float is not supported in the release?
My question is that the PR #5839 is already fix this? If so, can anyone help to provide the docs how to use the latest master in the js folder instead of js version 3.7.1(I got it using npm install)

Thanks a lot

**Comment by BSBandme** [comment]
For jspb.Message.getFloatingPointFieldWithDefault we have some rollback and roll forward changes internally, I'm not sure whether 3.7.1 has cut the CL to a rollback CL.

Now we have a release with 3.8.0, which should have fixed this problem.

**Comment by DarrenWong** [comment]
cool, 3.8.0 in npm solved my problems. Thanks a lot
