### ISSUE TITLE
C# and proto2 + GTFS Realltime

### ISSUE THREAD

**Issue by wirthandras** [protocolbuffers/protobuf#6067]
Hi!

I am started to working with GTFS Realtime which proto file written in proto2 syntax.
https://github.com/google/transit/blob/master/gtfs-realtime/proto/gtfs-realtime.proto

My company works with C# code base, So I installed the latest version of protoc (v3.7.1). And I tried to generate C# classes based on this proto file, but I got a message the proto3 syntax supported only with C# programming language. Note: Our contractor has own extension for GTFS Realtime. This is the reason why I need to generate. (instead of using existing nuget packages)

What are my possibilities?

In my mind I see few way:
1. To ask Google to upgrade proto2 to proto3 (may be impossible)
2. Find an older version of protoc which may be support C# + proto2
3. https://github.com/jskeet/protobuf-csharp-port
4. Change programming language

As I see according to the gathered information the best way is the change programming language.

Can anybody give me a little guidance, maybe something was hidden for me?

Thanks!

**Comment by ObsidianMinor** [comment]
Option 5: Wait and follow #5350 and #5936. It might take some time but proto2 features are being reviewed as we speak. If you can't wait this option doesn't work.

**Comment by wirthandras** [comment]
@ObsidianMinor Thanks, I am following these tickets now. I made a JAVA concept to handle our current needs but as soon as possible we want to migrate to C#.
