### ISSUE TITLE
Segfault if at least one php thread (pthreads) was started

### ISSUE THREAD

**Issue by ultralamer** [protocolbuffers/protobuf#6071]
**Protobuf version**: 3.7.1
**Language**: PHP
**OS**: Linux, Ubuntu 16.04
**Environment**:
- PHP 7.2.4 with zts
- Pthreads: https://github.com/krakjoe/pthreads
- Protobuf extension

**Steps to reproduce the behavior**:
1. Start thread
2. Create Message object
3. See error

**Code example to reproduce:**
```
<?php
require './vendor/autoload.php';

$task = new class extends \Thread {
    public function run() { }
};
$task->start();

$cmd = new \TestProto\Msg();

echo 'successful'.PHP_EOL;
```

**gdb output:**
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee4ad700 (LWP 11890)]
[Thread 0x7fffee4ad700 (LWP 11890) exited]

Thread 1 "php" received signal SIGSEGV, Segmentation fault.
add_def_obj (def=def@entry=0x1600910, value=value@entry=0x7fffef27d7a0) at /home/alex/tmp/protobuf/php/ext/google/protobuf/protobuf.c:109
109       add_to_table(upb_def_to_php_obj_map, def, value);
```

**Code and Dockerfile**: https://github.com/ultralamer/pthreads_protobuf

**Comment by TeBoring** [comment]
what command did you run gdb?

**Comment by TeBoring** [comment]
BTW, should you call ```$task->join()``` after ```$task->start()```?

**Comment by ultralamer** [comment]
> what command did you run gdb?
```
gdb php
run test.php
```


> BTW, should you call $task->join() after $task->start()?

It is not important in this case. The process crash  immediately after start() even if i use join()

**Comment by haberman** [comment]
The PHP pthreads library is unmaintained (even stronger, its author [has disavowed it](https://github.com/krakjoe/pthreads/issues/929), calling it "broken by design.")

So I don't think we can support running protobuf under the pthreads package.
