### ISSUE TITLE
how do I set field value other than english

### ISSUE THREAD

**Issue by sujit420** [protocolbuffers/protobuf#6076]
when I set a string which is a mix of multiple languages e.g. 'it is called सियार' to grpc response, then 4th token gets converted to something else while sending response i.e. "it is called \340\244\270\340\244\277\340\244\257\340\244\276\340\244\260".

Please help someone. Thanks in advance

**Comment by haon4** [comment]
Hi, which language did you use to encode the original string, and which language did you use to decode it? Was the data transferred using protobuf binary format or JSON format?

**Comment by sujit420** [comment]
> Hi, which language did you use to encode the original string, and which language did you use to decode it? Was the data transferred using protobuf binary format or JSON format?

I am not encoding and decoding explicitly. Data was transferred using protobuf binary format (I guess it happens in grpc response).
Above problem only arises when a protobuf(which contains non english string field) is displayed.

**Comment by BSBandme** [comment]
What's your problem with it? When protobuf serialize the string to binary, it will use UTF8 encoding to encode the string.

Are you having a hard time for get the string from deserialized message?

**Comment by sujit420** [comment]
I missed updating the proto at one end. That solved the issue.
Thanks anyway. Will close the issue.
