### ISSUE TITLE
[Ruby] It got Parse error at Timestamp decode_json

### ISSUE THREAD

**Issue by KWkyle** [protocolbuffers/protobuf#6079]
**What version of protobuf and what language are you using?**

Version: v3.7.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 2.6.3

**What did you do?**
After I upgrade ruby version to 2.6.3 and protobuf version to 3.7.1, I got below error while did decord_json for Timestamp.
```
   Google::Protobuf::Timestamp.decode_json("{\"seconds\":1556272746,\"nanos\":910983000}")
   # => Google::Protobuf::ParseError: Error occurred during parsing: Parse error at 'seconds":1556272746,"nanos":910983000}'
```

**Comment by TeBoring** [comment]
https://developers.google.com/protocol-buffers/docs/proto3#json
Timestamp's json format should be something like: "1972-01-01T10:00:20.021Z"
Previously, we support the wrong format like "{\"seconds\":1556272746,\"nanos\":910983000}".
In 3.7.0+, we fixed it. You need to change your json string to corresponding timestamp string.

**Comment by mariogintili** [comment]
@TeBoring Changes like this should be documented in the [release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0)  I just bumped the library to run into this  as well
