### ISSUE TITLE
Generated CC files are different, between protoc.exe executions

### ISSUE THREAD

**Issue by zhenkas** [protocolbuffers/protobuf#6080]
Version: 3.1.0
Language: C++
OS: Windows
Compiler: protoc.exe

**Steps to reproduce the behavior:**
1. Compile a set of proto files
2. Example of protoc.exe command line(obfuscated names):

> protoc.exe --error_format=msvs --csharp_out="M:\Agt\Sources\DOTNET" --cpp_out="dllexport_decl=PROTO_EXPORT_MODULENAME1:M:\Agt\Sources\CPP" --proto_path="M:\Agt\" "M:\Agt\Proto1.proto" "M:\Agt\Proto2.proto" "M:\Agt\Proto3.proto"
3. Save generated CC files
4. Repeat steps 1,2,3 on same proto files and compare generated CC files, till you find inequality

**Expected result:**
The generated CC files should not be changed between iterations

**Actual result:**
The following code line is randomly added and removed between proto compilations
**::google::protobuf::internal::GetEmptyString();**
Also this line appeared more than once, which is meaningless

Example of generated code(read comments!):

```
void protobuf_InitDefaults_2eCore_2eConfiguration_2fCfgFiler_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString(); //any next line similar to this, may appear and disappear randomly between proto compilations, of same proto files
  CfgMountPoint_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();  //here it (randomly) again
  CfgProxy_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString(); //here it (randomly) again
  CfgFiler_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString(); //here it (randomly) again
  CfgMountPoint_default_instance_.get_mutable()->InitAsDefaultInstance();
  CfgProxy_default_instance_.get_mutable()->InitAsDefaultInstance();
  CfgFiler_default_instance_.get_mutable()->InitAsDefaultInstance();
}
```
**Note:**
We do check-in generated code to source control automatically from build, and every small change to single proto file generates a lot of "garbage changes". We have tens of packages containing hundreds of proto files.

**Comment by BSBandme** [comment]
Please try to upgrade your protobuf. It seems there's no such generated code for current version
