### ISSUE TITLE
Use a reasonable standard for zlib in bazel

### ISSUE THREAD

**Issue by ronshapiro** [protocolbuffers/protobuf#6084]
**What version of protobuf and what language are you using?**
Version: 57b6597f467c2b614a458051f60ba467c5d697ae
Language: Bazel (0.24.1)

**What operating system (Linux, Windows, ...) and version?**
Linux

https://github.com/protocolbuffers/protobuf/pull/5389 added support for zlib and made it configurable with the `//external:zlib` label. Unfortunately, this requires all downstream users of protobuf+bazel to need to `bind()` a value for zlib, and given how core proto is, that's a lot of users.

I think there's work that we can do to give this a very reasonable default without requiring any configuration by users.

I think if the default condition [here](https://github.com/protocolbuffers/protobuf/blob/1c5e8cbb8fedafbb45f62d28d9d4ff2362168601/BUILD#L145) could be updated to include `@bazel_tools//third_party/zlib`, every regular user will get zlib and msvc users will continue without. We can add another value to the config so that users can specify a custom zlib if they choose to bring their own, bound to `//external:protobuf_zlib` or some other canonical name. (I'm just seeing https://github.com/protocolbuffers/protobuf/commit/f313b9ccf7434e04d233ad2f519affc78a9e26a8#diff-7f9ad3c5854d19e307639e89857e646e now, so perhaps @nicmcd you have suggestions about a better way to achieve this. Maybe keep the `@zlib//:zlib` name)

I'm impartial to the solution, so if my suggestion doesn't make sense I'm definitely open to others. My main goal is to be able to depend on proto without any extra configuration that may already be available.

**Comment by nicmcd** [comment]
I think the WORKSPACE style of Bazel forces users to know the dependencies of their dependencies. Without extensive Skylark hacking, in general a user of library A needs to know that library A depends on library B. The user should have library A and library B declared in their WORKSPACE file. I don't see why protobuf should be any different. Do you?

Instead of having zlib declared in the default Bazel configuration, I suggest just making an example bazel project with a BUILD and WORKSPACE file that shows that the user needs to have zilb in their WORKSPACE file.

**Comment by ronshapiro** [comment]
If there was a necessary dependency that didn't have an alternative, I'd agree with you. But given that Bazel packages a zlib already, it seems reasonable to use it.

You could have the same argument with a build tool like a compiler. Bazel packages a few (`clang`, `javac`, etc). There's nothing stopping you from configuring a different platform, but these are sane defaults that most of the world wants. It would be a significant hurdle if every user had to define their own compiler just to start a new project.

**Comment by nicmcd** [comment]
Ok, that makes sense. My biased view is that if the user declares `@zlib//:zlib`, then protobuf should use it. If not, then use the default provided by bazel.

**Comment by ronshapiro** [comment]
I don't know if there's a way to do that. Open to suggestions.

Is there any benefit of `@zlib//:zlib` over the `@bazel_tools` version? I don't actually know anything about it. Are there in general lots of different implementations that differ greatly? And do those affect proto?

**Comment by nicmcd** [comment]
I don't think it really matters either way. zlib doesn't change very much. The one thing to be most aware of is braking someone's build that is already using zlib for their own purposes. That is how I got on this. If you can find a way to use the zlib in bazel_tools without affecting the user's use of zlib, then do that.
