### ISSUE TITLE
Many unused variable build warnings in protobuf 3.7.1

### ISSUE THREAD

**Issue by wjywbs** [protocolbuffers/protobuf#6091]
`src/google/protobuf/duration.pb.cc:94:13: warning: 'dynamic_init_dummy_google_2fprotobuf_2fduration_2eproto' defined but not used [-Wunused-variable]`
`static bool dynamic_init_dummy_google_2fprotobuf_2fduration_2eproto = []() { AddDescriptors_google_2fprotobuf_2fduration_2eproto(); return true; }();`

All generated pb.cc files have this build warning.

**Comment by minyang** [comment]
Dear protobuf team, is there any update on this issue by any chance?  I'm looking for the minimal patch that could be cherry picked and applied to my local setup. @acozzette

**Comment by peirong-Z** [comment]
Dear protobuf team, is there any update on this issue by any chance? I'm looking for the minimal patch that could be cherry picked and applied to my local setup. @acozzette

**Comment by fowles** [comment]
this variable is not actually unused in the way you think.  It is used to do dynamic registration of descriptor data in the global pool.  No one reads from this variable, but its existence is load bearing.
