### ISSUE TITLE
Avira Antivir detects Bitcoin Maleware in Protobuf

### ISSUE THREAD

**Issue by mijosch** [protocolbuffers/protobuf#6093]
Version: master/v3.7.1
Language: Python
Windows10
Python 3.7

Install tensorflow -> pip install tensorflow

Avira detects PUA/BitcoinMiner.Gen7(cloud)
in file _message.cp37-win_amd64.pyd

**Comment by anandolee** [comment]
I don't think it is a protobuf related question. It may related to tensorflow or more looks like a  machine virus...
