### ISSUE TITLE
Warning in protobuf header on windows

### ISSUE THREAD

**Issue by Parean** [protocolbuffers/protobuf#6095]
Version: Protocol Buffers v3.8.0-rc1
Language: C++
OS: Windows 10
Compiler: MSVC 19.16.27026.1
`
protobuf-cpp-3.8.0-rc-1\install\release\include\google/protobuf/parse_context.h(127): warning C4244: '+=': conversion from '__int64' to 'int', possible loss of data`

**Comment by Cadovvl** [comment]
I still have this warning. 
C++.
Windows 10.
Microsoft Visual Studio Enterprise 2019
Version 16.4.14

same file, lines 211 and 350,
