### ISSUE TITLE
CMake can not handle package name returned by protoc.exe --version 

### ISSUE THREAD

**Issue by DeepSeeBee** [protocolbuffers/protobuf#6099]
Hi,

it's about the change:
7c76ac173 (Adam Cozzette       2017-04-25 17:01:28 -0700 1587)     std::cout << "libprotoc "

in protobuf/compiler/command_line_interface.cc

The code was changed to include the package name in front of the version number. This causes the following windows-CMake file can no more detect the version:

C:\Program Files\CMake\share\cmake-3.14\Modules\FindProtobuf.cmake

Because it expects only the version number. I removed the "libprotoc" string in front of the version number and it works.

Can some of you experienced guys decide, if CMake should be changed or the protobuf code?

Or is there another solution i don't see?

**Comment by BSBandme** [comment]
Sorry but I didn't quite get. It seems the previous change is just some trivial change, which shouldn't have any side effect.

Would you please elaborate?

**Comment by DeepSeeBee** [comment]
the submit number i stated above is not the correct one, sorry. 

it's trivial:

expected by cmakescript: "protoc.exe --version" returns "1.2.3" 
actual "protoc.exe --version" returns "**protolib** 1.2.3"
where "1.2.3" is just an example for a version number.

so the build script can no more detect the right protoc version and aborts the build.
so i assume some older version did not return the "protolib" part of the string since the build script is developed to rely on this.

it is not clear to me how to deal with this. i think there is no convention for a component to return a defined string as "--version" but the build script relies on it. 

maybe it's better to close this issue here and leave it up to the build script developers?

**Comment by BSBandme** [comment]
OK, then close for now.
Feel free to send us an PR for fixing if you think there's any bug in our cmake configuration.
