### ISSUE TITLE
Print loaded Protobuf version in phpinfo()

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#6109]
**What language does this apply to?**
PHP (extension)

**Describe the problem you are trying to solve.**

It is difficult to determine which version of protobuf is loaded.

**Describe the solution you'd like**

Exposing the version in `phpinfo()` would solve this.

**Describe alternatives you've considered**

**Additional context**

* [example of grpc printing version](https://github.com/grpc/grpc/blob/59ccf3f12b7fe8f2adba25a5a74ba91bbc29a31e/src/php/ext/grpc/php_grpc.c#L380-L386).

**Comment by esorot** [comment]
Seems like a reasonable request, we would love to accept a PR. 
Closing for now, but please do re-open if this is still a priority
