### ISSUE TITLE
Is protobuf v2.4.1 compatible with later v2.x release?

### ISSUE THREAD

**Issue by zzbairen** [protocolbuffers/protobuf#6120]
Now we would like to use protobuf 2.4.1 version at the server side, but client may use both v2.4.1 and v2.5.0. Is this usage make sense? Does v2.4.1 version have the compatibility with later with later 2.x version.
Is the wire-format generated by v2.4.1 the same with v2.x? If yes, should we say v2.4.1 must be compatible with v2.x version?

**Comment by acozzette** [comment]
Yes, that will work. We are always careful to maintain wire compatibility as we make changes and release new versions. But actually 2.4 and 2.5 and both pretty old at this point, so I would recommend updating to a recent release like 3.7 if possible.
