### ISSUE TITLE
Java protobuf empty constructor

### ISSUE THREAD

**Issue by RaAleks** [protocolbuffers/protobuf#6136]
Can you pls add ability to generate java classes with empty(default) constructor?

**Comment by BSBandme** [comment]
Are you proposing construct message without using builder?
I think we can't do that since we need to keep the immutability to make the message safe in java

**Comment by RaAleks** [comment]
Ok, thanks for response. Yes my proposal was to add constructor without builder. The reason of this was problem to build Mapstruct mappers, they are fails without default constructor.
