### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by simahao** [protocolbuffers/protobuf#6141]
**What version of protobuf and what language are you using?**
Version: master/v3.7.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
windows10

**What runtime / compiler are you using (e.g., python version or gcc version)**
java8_202

**What did you do?**
1. Run protoc --proto_path=xxx --java_out=xxx @{file}
2. There are some unused variable in generated java source.

**What did you expect to see**
There is no unused variable.

![image](https://user-images.githubusercontent.com/4537287/57753989-0a7af580-7720-11e9-9c6e-ba305a1cac7a.png)

**Comment by elharo** [comment]
Do you have a reproducible test case?

**Comment by elharo** [comment]
comment and we'll reopen
