### ISSUE TITLE
Golang function parameter names

### ISSUE THREAD

**Issue by MaxStgs** [protocolbuffers/protobuf#6142]
Earlier I got support from Goland with method implementation and I got names by automatic. 
![изображение](https://user-images.githubusercontent.com/10531103/57802284-09bd8000-776f-11e9-82bc-7a4359559048.png) from this 
![изображение](https://user-images.githubusercontent.com/10531103/57802353-2e195c80-776f-11e9-88dd-2737d29aa274.png)
But now I can't reproduce this, because I have
![изображение](https://user-images.githubusercontent.com/10531103/57802511-8fd9c680-776f-11e9-80b8-420ea9c47fb1.png)
How I can repeat it again?

**Comment by BSBandme** [comment]
@dsnet 

Would you please provide more information on why you can't get the same generated code?

**Comment by dsnet** [comment]
This seems like an issue with either your setup or how Goland is interpreting the Go source files. Presuming that the code builds by the go toolchain, there is nothing on our end to do. Perhaps file an issue with Goland instead?

**Comment by MaxStgs** [comment]
I did it, before i found this
![изображение](https://user-images.githubusercontent.com/10531103/57829159-89773900-77c7-11e9-92ed-c12f766bfb0c.png)
When I make this
![изображение](https://user-images.githubusercontent.com/10531103/57829193-a14ebd00-77c7-11e9-857f-96ce5cf8ed47.png)
I can have by auto
![изображение](https://user-images.githubusercontent.com/10531103/57829283-e2df6800-77c7-11e9-88d2-90b135056347.png)

I use this for generate: 
protoc ProtoServer.proto --go_out=plugins=grpc:..\Proto
