### ISSUE TITLE
 Not able to decode google::protobuf::Any Reflection GetString returns empty whitespace

### ISSUE THREAD

**Issue by ramarkandasamy** [protocolbuffers/protobuf#6144]
Using Protobuffer for GoBGP communication. 
Trying to decode using C++ GoBGP Client. 
One of the fields is in the message is "google::protobuf::Any".

Communities: type_url: "type.googleapis.com/gobgpapi.CommunitiesAttribute"
value: "\n\005\377\312\314\337\001"

But str = reflection->GetString(any, value); return empty string.

Communities:

Due to this issue, I am not able to decode google::protobuf::Any
Could you please help me on this? 
Please let me know if there is any better way to decode google::protobuf::Any ?

Thanks,
Ramar

```
                google::protobuf::Any any = path.pattrs(i);
                const google::protobuf::Reflection* reflection = any.GetReflection();
                const google::protobuf::Descriptor* desc = any.GetDescriptor();
                const google::protobuf::FieldDescriptor* url = desc->FindFieldByName("type_url");
                const google::protobuf::FieldDescriptor* value = desc->FindFieldByName("value");
                if (reflection->GetString(any, url).find("CommunitiesAttribute") != std::string::npos) {
                    google::protobuf::TextFormat::PrintToString(any, &str);
                    std::cout << "Communities: " << str << std::endl;
                    str = reflection->GetString(any, value);
                    std::cout << "Communities: " << str << std::endl;
                }
```

**Comment by acozzette** [comment]
I don't think there is any need to use reflection here, so you can simplify things a lot by avoiding reflection. You can just call `any.type_url()` to access the type URL. To unpack the contents you can do `any.UnpackTo(&dest)` and that will return a bool indicating whether it was successful.

**Comment by ramarkandasamy** [comment]
Thanks for the information. What is the type of dest? Is it message or simple string? how do I print dest ?

**Comment by acozzette** [comment]
`dest` would be the type stored in the Any, so in your case it would be a `CommunitiesAttribute` message. You can call `DebugString()` on it to get a human-readable string.

**Comment by ramarkandasamy** [comment]
Thank you so much Adam. You saved my day.

Thanks,
Ramar

**Comment by kruti11** [comment]
Hey @acozzette Although I'm late here can you  tell  how to resolve the issue for type_url not having any "/" or (prefix_url)
for field type google.protobuf.any   using c++ 
I m getting 
type_url: "io.containerd.cgroups.v1.Metrics"
value: "\n\005\"\0031GB\n\005\"\0032MB\022\003\010\226\002\032\262\001\n\242\001\010\347\352\227\264\340\016\020\200\266\350\233\230\003\030\200\203\232\225\333\010\"\212\001\340\252\221\271\253\007\207\300\206\373\264\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0\200\300\254\0048\341\267\001@\341\221\001H\203\263\002P\201\001X\200\340\206\001`\200@h\200\200\362\001p\200\0\200\300\374\375\005\232\002\024\010\200\340\377\377\377\377\377\377\177\020\200\300\247\033\030\200\240"
