### ISSUE TITLE
Generated PHP code fails to compile if using wrappers and _value

### ISSUE THREAD

**Issue by lukesneeringer** [protocolbuffers/protobuf#6150]
**What version of protobuf and what language are you using?**
Version: 3.7.1
Language: PHP

**What did you do?**

Given a proto using wrapper types and similar fields differing only by a `_value` suffix:

```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";

message Foo {
  google.protobuf.StringValue bar = 1;
  google.protobuf.StringValue bar_value = 2;
}
```

The generated PHP code generates two `getFooValue` methods, and fails to compile.

**Comment by TeBoring** [comment]
We have changed the additional getter to getXXXUnwrapped, which is less likely to have conflict.
Users still need to pay attention to their field naming to avoid foo_unwrapped.
