### ISSUE TITLE
I have encountered some problems, protobuf can not be used normally, can anyone help me?

### ISSUE THREAD

**Issue by gowcage** [protocolbuffers/protobuf#6154]
I have encountered some problems, protobuf can not be used normally, can anyone help me?

The following is part of the error message：
[libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 3.0.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrm/android_arm_armv7-a-neon_cortex-a15_shared_core/gen/proto/frameworks/av/drm/libmediadrm/protos/plugin_metrics.pb.cc".)terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.0.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrm/android_arm_armv7-a-neon_cortex-a15_shared_core/gen/proto/frameworks/av/drm/libmediadrm/protos/plugin_metrics.pb.cc".)
Aborted

**Comment by BSBandme** [comment]
Please update your runtime library (you can download the binary [here](https://github.com/protocolbuffers/protobuf/releases) and regenerate you protobuf files.
