### ISSUE TITLE
Reduce the code size of Java Lite

### ISSUE THREAD

**Issue by snapsam** [protocolbuffers/protobuf#6156]
Apologies if this is the wrong place, between [these](https://github.com/protocolbuffers/protobuf/issues/4769#issuecomment-397702062) [two](https://github.com/protocolbuffers/protobuf/issues/5961#issuecomment-481516065) issues, it's not clear 
where Java Lite issues belong

**What language does this apply to?**
proto3, Java, Java Lite

**Describe the problem you are trying to solve.**

We've been using Java Nano since September 2015 with much success.  It
continues to generate the correct wiremodels to interoperate with our backend
service while minimizing the size of our Android runtime (and important thing
for Android development).

Unfortunately, Java Nano support appears to be discontinued starting in the [3.6](https://github.com/protocolbuffers/protobuf/compare/b5fbb742af122b565925987e65c08957739976a7..449e532b087e43a45ca6d8eae640a6019e547aca#diff-96239ee297e0a92ac6ff96a6bc434ef0L340)
release.  While direction forward for the library as a whole makes sense, there
are concerns which are preventing us from shifting from Java Nano to Java Lite.
Primarily, the size of the code.

Taking a simplistic example:
```
message LocalizedStringSet {
  message LocalizedString {
    string locale = 1;  // IETF language tag (eg "en")
    string text = 2;
  }
  repeated LocalizedString strings = 2;
  string fallback = 1;
}
```

Using the 3.0.2 version to generate Java Nano vs Java Lite produces 271 (in
nano) vs 751 (in lite) Lines of Code after removing whitespace and comments
(obviously the java byte code is smaller).

We also use tools like Proguard to provide dead code elimination that further
reduce this difference (though with some of the calling patterns in the
generated Protos it's been difficult for us to be precise here).  However, it's
still a non-trivial difference and given our heavy adoption of protobuf we're
understandably hesitant to switch.

**Describe the solution you'd like**

Brief inspection of the class seems to indicate that a significant portion of
the size difference is due to the builder patterns adopted in Java Lite.  We
can probably do some work on our end to prevent their usage and eliminating
them, but it would be preferable if there was an option in the Java Lite plugin
to disable builder patterns.

**Describe alternatives you've considered**

Dead code elimination could also be made more reasonable, in which case we
could simply enforce no-builders in our linting rules.  Having used Proguard (
and tools like it) in the past they can be difficult to make sure that they
produce the expected result in non-trivial cases.  It would seem that modifying
Java Lite to not produce builders is a more simple, and more maintainable,
solution than attempting to redesign the code it generates to be more
accessible to a tool like Proguard.

**Additional context**

**Comment by BSBandme** [comment]
There's an [new open sourced version of Java lite](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md), which doesn't have backwards compatibility with old Java lite. The new one can largely save the binary size after proguard.

If you would like to, you may give a try on that.

**Comment by xapienz** [comment]
Unfortunately, new version of Java lite uses reflection (#6463), so it won't work well with Proguard/R8 now.
