### ISSUE TITLE
[Java] Need a method which I can insert byte[] before toByteArray in AbstractMessageLite

### ISSUE THREAD

**Issue by humiao8sz** [protocolbuffers/protobuf#6168]
**What language does this apply to?**

Java proto3

**Describe the problem you are trying to solve.**

with java ,we use AbstractMessageLite.toByteArray() to get the Message's byte array,
in my project,I need to send the length of this  byte array to others,I want to put the length into
the byte array with out array copy.

**Describe the solution you'd like**

A method like this will resolve my problem.

	public byte[] toByteArray(byte[] beforeArray) {
		try{
			final byte[] result = new byte[getSerializedSize()+beforeArray.length];
			final CodedOutputStream output = CodedOutputStream.newInstance(result);
			for(byte beforeByte : beforeArray){
				output.write(beforeByte);
			}
			writeTo(output);
			output.checkNoSpaceLeft();
			return result;
		}catch(IOException e){
			throw new RuntimeException(getSerializingExceptionMessage("byte array"), e);
		}
	}

,can you add a method like this into AbstractMessageLite in the future?Or can any other way to
solve my problem?

**Comment by BSBandme** [comment]
Sorry but I think there's not too many usages of this...
Close for now and if you would like to add an API like this feel free to send us a PR.
