### ISSUE TITLE
How to get Class<E> enumType from com.google.protobuf.Descriptors.FieldDescriptor in Java

### ISSUE THREAD

**Issue by Myracle** [protocolbuffers/protobuf#6170]
My aim is to generate AddressBook's type in a Tree type like json, including nested structure. All other fields are transfered to Java's type except Protobuf's Enum.

Now I have a fieldDescriptor which type is Descriptors.FieldDescriptor.JavaType.ENUM. I want to get EnumTypeInfo from it.

For simply, I have AddressBook.java generated by .proto3 file. The fieldDescriptor is got by AddressBook.newBuilder().getDescriptorForType().getFields().get(0).

switch (fieldDescriptor.getType()) {
    case ENUM:
    // The param is wrong. What's the right way?
    return Types.ENUM(fieldDescriptor.getEnumType().getClass());
}

// This method is written by others and I can not change it.
public static <E extends Enum<E>> TypeInformation<E> ENUM(Class<E> enumType) {
    return new EnumTypeInfo<>(enumType);
}
The return EnumTypeInfo should contain the info of all the value in the Enum. By fieldDescriptor.getEnumType().getValues(), I can get all the values in the Enum. If I simply use Types.ENUM(java.lang.Enum.class), enumClass.getEnumConstants() will return null that is not what I expect. Thank you.

**Comment by Myracle** [comment]
The stackoverflow url is: https://stackoverflow.com/questions/56272994/how-to-get-classe-enumtype-from-com-google-protobuf-descriptors-fielddescripto

**Comment by BSBandme** [comment]
You may infer the enum class's name by the enum's fullname and options of `java_package` `java_outer_class`.
