### ISSUE TITLE
std::min() conflict

### ISSUE THREAD

**Issue by RPG3D** [protocolbuffers/protobuf#6174]
Version: master
Language: C++
Windows

protobuf-lite
 
generated enum using std::min, but conflict with windows macro, I have to modify the generated code.
![QQ图片20190524121014](https://user-images.githubusercontent.com/7828382/58302324-19972d00-7e1d-11e9-8673-e65a70220acc.png)

**Comment by BSBandme** [comment]
Sorry but where the windows macro is defined?

Feel free to send us a PR for fixing that.

**Comment by RPG3D** [comment]
![QQ图片20190620113040](https://user-images.githubusercontent.com/7828382/59816493-e928ad00-934e-11e9-9de5-bee69018d4e2.png)

**Comment by IronsDu** [comment]
you can define `NOMINMAX` macro in windows.

**Comment by mcy** [comment]
Is you use our build systems, we already set `/DNOMINMAX` for you. If not, you'll need to pass that flag to MSVC.
