### ISSUE TITLE
descriptor_table_proto_2fcommon_2eproto

### ISSUE THREAD

**Issue by serg666** [protocolbuffers/protobuf#6179]
Hi!
I have the following:
```
protoc --version
libprotoc 3.7.1
```

I install protobuff as described at https://github.com/protocolbuffers/protobuf/blob/master/src/README.md

Then I clone https://github.com/google/tink library and I need to generate cc and h files from *.proto files

I run something like this:
```
protoc --proto_path=. -I. --cpp_out=/root/libtink/src/proto rsa_ssa_pss.proto
```

and I got file /root/libtink/src/proto/rsa_ssa_pss.pb.cc in which I see something like this

```
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_rsa_5fssa_5fpss_2eproto_deps[1] = {
  &::descriptor_table_proto_2fcommon_2eproto,
};

```

and when I try to compile it I got 
```
src/proto/rsa_ssa_pss.pb.cc:180:4: error: ‘::descriptor_table_proto_2fcommon_2eproto’ has not been declared

   &::descriptor_table_proto_2fcommon_2eproto,

    ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

What should I add to include dir to get descriptor_table_proto_2fcommon_2eproto declaration?

**Comment by acozzette** [comment]
It looks like there is another file called `common.proto` which is a dependency of `rsa_ssa_pss.proto` and also needs to be built. There might be an old version of `common.pb.h` and `common.pb.cc` lying around but they need to rebuilt so that the `protoc` version is consistent. Let me know if that fixes the problem.

**Comment by serg666** [comment]
There is no problem on 3.6.1 If I install 3.6.1 the problem disappear

```
root@testing:~# protoc --version
libprotoc 3.6.1
root@testing:~#
```

**Comment by hoangtrucit** [comment]
i have same issue with version 3.8.0

**Comment by KaimingGao** [comment]
i have same issue with version 3.8.0.
