### ISSUE TITLE
LNK1241	resource file libprotobufd.lib(version.res) already specified	libprotobuf-lited.lib(version.res)	

### ISSUE THREAD

**Issue by duribega** [protocolbuffers/protobuf#6181]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++

**What operating system**
Windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC
**What did you do?**
1. Compile my library project in visual studio that contains a version resource
2. LNK1241	resource file libprotobufd.lib(version.res) already specified	libprotobuf-lited.lib(version.res)	

**What did you expect to see**
My nice project compiled.
**What did you see instead?**
Debug does not compile. link error 1241. Release version compiles fine. Google says this is "normal" behavior using 2 non-binary matching resources.
 
**Anything else we should know about your project / environment**
Maybe using "version" in a library is kind of dangerous. Maybe rename it to protoversion?

**Comment by WilliamKappler** [comment]
I am experiencing this as well, with 3.8.0 and VS2017. Are there any workarounds?

**Comment by acozzette** [comment]
I am not familiar with these version resource files, but it sounds like the problem might be coming from linking together both `libprotobuf` and `libprotobuf-lite`. It makes sense to link against one library or the other but not both. Unless you're using `option optimize_for = LITE_RUNTIME;` in every .proto file, you probably want to link against only `libprotobuf`.

**Comment by WilliamKappler** [comment]
That's a good guess, but I checked and I'm not linking both the normal and the lite. I tried renaming the resource output file to be different for every project, but I still got errors about the files already being specified, despite it clearly stating they had different names. 

I'm nowhere near enough of a VS wizard to know what is actually going on, but I did find a suggestion to remove the output filename and the "culture" on the project properties resources. That seemed to fix the problem.

**Comment by duribega** [comment]
Hi. I found a solution for my problem. First, you have to disable compiling with precompiled headers for your protobuf files. Second, the windows api has it's own definition of min (in case you are using windows libs), so std::min fails. You have to temporarily change the definition of min (I think also max) whenever you include the protobuf header in your source.

**Comment by kwcheights** [comment]
For me, the same problem was solved setting "Link Time Code Generation" to "Yes(/LTCG)" in the project settings (configuration build type is Static Library)
