### ISSUE TITLE
repeated field functional improvement

### ISSUE THREAD

**Issue by guopenglun** [protocolbuffers/protobuf#6182]
**What language does this apply to?**
proto3
c#

**Describe the problem you are trying to solve.**
repeated Functional improvement

**Describe the solution you'd like**
by Default generate
`

        private readonly pbc::RepeatedField<MList> mlist_ = new pbc::RepeatedField<MList>();

        public pbc::RepeatedField<MList> Mlist {
            get { return mlist_; }
        }

`
I expect
`

        private readonly pbc::RepeatedField<MList> mlist_ = new pbc::RepeatedField<MList>();

        public pbc::RepeatedField<MList> Mlist {
            get { return mlist_; }
            set {
                mlist_.Clear();
                if (value != null)
                    mlist_.AddRange(value);
            }

        }

`
**Describe alternatives you've considered**
Can set the generate set option
**Additional context**

**Comment by jtattermusch** [comment]
Closing for this reason: https://github.com/protocolbuffers/protobuf/pull/6549#issuecomment-526198163
