### ISSUE TITLE
[python] ParseError disappeared from google.protobuf.internal.well_known_types

### ISSUE THREAD

**Issue by PhilippSelenium** [protocolbuffers/protobuf#6187]
from version [3.7.1](https://github.com/protocolbuffers/protobuf/blob/v3.7.1/python/google/protobuf/internal/well_known_types.py) to version [3.8.0](https://github.com/protocolbuffers/protobuf/blob/v3.8.0/python/google/protobuf/internal/well_known_types.py)

What confuses me is that I cannot see where it went since it does not show up in the history:
https://github.com/protocolbuffers/protobuf/commits/v3.8.0/python/google/protobuf/internal/well_known_types.py
where the latest commit is from Mar 20, 2019 (before the 3.7.1 release)

**Comment by rgmenon** [comment]
We ran into the same issue. Looking at the rest of the code, it appears that ParseError has simply been replaced by ValueError.
Does anyone know where to find the release notes? There's no link from pypi.org.

**Comment by Arfrever** [comment]
https://github.com/protocolbuffers/protobuf/commit/d8c2501b43c1b56e3efa74048a18f8ce06ba07fe#diff-79a29d050e84ff410293a63e1a1551d6
(Development of 3.8.* already started before release of 3.7.0.)

**Comment by PhilippSelenium** [comment]
Thanks
