### ISSUE TITLE
CI blocks on missing un-addable labels

### ISSUE THREAD

**Issue by paulb777** [protocolbuffers/protobuf#6191]
**What version of protobuf and what language are you using?**
Version: master.
Language: Objective-C

**What did you do?**
Made a [PR](https://github.com/protocolbuffers/protobuf/pull/6190) 
Saw that [CI failed](https://github.com/protocolbuffers/protobuf/pull/6190/checks?check_run_id=138299156)
Tried to add [requested labels ](https://github.com/protocolbuffers/protobuf/commit/9e620595d4422d0640863b61285f886766777c7a#diff-6a3371457528722a734f3c51d9238c13) but discovered non-committers don't have access to do so.

**What did you expect to see**
Successful C/I and/or permissions to update labels.

**What did you see instead?**
Blocked PR.

**Comment by haon4** [comment]
Updated https://github.com/protocolbuffers/protobuf/blob/master/CONTRIBUTING.md. It is meant for the reviewers to set rather than the contributors.
