### ISSUE TITLE
F-secure detects malware in _message.cp37-win_amd64.pyd

### ISSUE THREAD

**Issue by thirsima** [protocolbuffers/protobuf#6194]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7 (Anaconda)

**What did you do?**
1. Install Anaconda for Windows (Python 3.7)
2. Create a fresh Python 3.7 environment in Anaconda
3. pip install protobuf
4. python
5. from google.protobuf.pyext import _message

**What did you expect to see**
Successful import

**What did you see instead?**
>>> from google.protobuf.pyext import _message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Anything else we should know about your project / environment**

Running F-secure manual malware scan on `C:\Users\teemu.hirsimaki\AppData\Local\Continuum\anaconda3\envs\protobuf\Lib\site-packages\google\protobuf\pyext\_message.cp37-win_amd64.pyd` reports BitCoinMiner malware: https://www.f-secure.com/sw-desc/application_bitcoinminer.shtml

**Comment by thirsima** [comment]
If I create a fresh environment for Python 3.6, the import seems works fine. The problem is only in version 3.7 of the pyd file.

**Comment by feature-engineer** [comment]
Firefox 67 says it detected virus/malware when downloading protobuf-3.8.0-cp37-cp37m-win_amd64.whl from pypi.

**Comment by haberman** [comment]
Closing as obsolete.
