### ISSUE TITLE
PHP messages generate segfault when cloned and using c extension

### ISSUE THREAD

**Issue by michaelbausor** [protocolbuffers/protobuf#6195]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: PHP (with c extension 3.8)

**What operating system (Linux, Windows, ...) and version?**
Debian 9.9
PHP 7.1.29

**What did you do?**
Run this script with c extension enabled:
```php
<?php
require __DIR__ . '/vendor/autoload.php';

$f = new \Google\Protobuf\GPBEmpty();
echo $f->serializeToJsonString() . "\n";

$g = clone $f;
echo $g->serializeToJsonString() . "\n";
```

**What did you expect to see**
```bash
$ php clonetest.php
{}
{}
```

**What did you see instead?**
```bash
$ php clonetest.php
{}
Segmentation fault (core dumped)
```

cc @TeBoring

**Comment by TeBoring** [comment]
I don't think clone previously works. How urgent is this?

**Comment by michaelbausor** [comment]
No, I don't think clone worked previously. This is not urgent, but it is a difference between c extension and pure PHP code so would be good to resolve (and also is potentially difficult to debug because of segfault)

**Comment by foamzou** [comment]
How is it going now? I also have the problem while use clone pb object, although update c extension to 3.11.4 (the latest)
