### ISSUE TITLE
Ruby proto2 support breaks proto3 extension support

### ISSUE THREAD

**Issue by mdehoog** [protocolbuffers/protobuf#6209]
**What version of protobuf and what language are you using?**
Version: 3.7.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
MacOS X 10.14.5.

**What runtime / compiler are you using (e.g., python version or gcc version)**
Using precompiled libprotoc 3.7.1 installed by Homebrew.

**What did you do?**

1. Create a `test.proto` file with the following contents:
```protobuf
syntax = "proto3";

package test;

import "google/protobuf/descriptor.proto";

extend google.protobuf.ServiceOptions {
  bool custom_option = 12345;
}
```
2. Compile using ruby_out: `protoc test.proto --ruby_out=.`
3. The following error occurs:
```
--ruby_out: test.proto: Extensions are not yet supported for proto2 .proto files.
```

**What did you expect to see**
`3.6.1` would compile the proto without error.

**What did you see instead?**
`3.7.1` and later cannot compile the proto.

**Anything else we should know about your project / environment**
Both versions output the following warning, but this doesn't cause the compilation to fail:
```
[libprotobuf WARNING google/protobuf/compiler/ruby/ruby_generator.cc:512] Omitting proto2 dependency 'google/protobuf/descriptor.proto' from proto3 output file 'options_pb.rb' because we don't support proto2 and no proto2 types from that file are being used.
```

I believe this was broken with #4816: https://github.com/protocolbuffers/protobuf/pull/4816/files#diff-504ebaed0c05c4ffcc9224cc4358115bR252. Should the proto2 implementation affect the compilation of proto3 files?

**Comment by cbenning** [comment]
I am also experiencing this. Other language stubs are successfully generated.

**Comment by TeBoring** [comment]
Seems like the code didn't consider extend Descriptor in proto3. Could you help send a fix?

**Comment by Parad0X** [comment]
@TeBoring is this all that's needed? https://github.com/protocolbuffers/protobuf/pull/6369

**Comment by TeBoring** [comment]
Will release it in 3.10 release

**Comment by pechorin** [comment]
✗ protoc --version
libprotoc 3.11.0

✗ protoc --include_imports --ruby_out=/Users/vorobey/work/dredd/lib/proto/ --proto_path=. ./galaxy.proto
--ruby_out: galaxy.proto: Extensions are not yet supported for proto2 .proto files.

**Comment by krak3n** [comment]
I'm hitting this issue in `3.15.8` with the following proto when trying to generate ruby code:

```
extend google.protobuf.EnumValueOptions {
  string name = 12345;
}

enum SomeType {
  FOO = 0 [(name) = "some value"];
  BAR = 1 [(name) = "some value"];
}
```

I get the following message and the code is not generated:

```
libprotobuf WARNING ../../third_party/protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc:512] Omitting proto2 dependency 'google/protobuf/descriptor.proto' from proto3 output file 'proto_pb.rb' because we don't support proto2 and no proto2 types from that file are being used.
```
