### ISSUE TITLE
MSAN failure in descriptor_database.cc:253:24

### ISSUE THREAD

**Issue by Warchant** [protocolbuffers/protobuf#6211]
**What version of protobuf and what language are you using?**
Version: v3.7.1.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.14.5

**What runtime / compiler are you using (e.g., python version or gcc version)**
```bash
$ clang-8 -v
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/8.0.0_1/bin
```

**What did you do?**
1. Build protoc with MSAN enabled (`-fsanitize=memory  -fsanitize-memory-track-origins -g`)
2. Run protoc on this proto file: https://github.com/soramitsu/kagome/blob/master/core/libp2p/crypto/proto/keys.proto
3. See this: 
Short: https://hastebin.com/iloloqacal.sql
Full: https://travis-ci.org/soramitsu/kagome/jobs/541633863

**What did you expect to see**
No error from MSAN.

**What did you see instead?**
Specified above.

**Comment by Omcsesz** [comment]
I recommend the addition of "iOS" label.
