### ISSUE TITLE
failed install: have unmet dependencies

### ISSUE THREAD

**Issue by rainy1798** [protocolbuffers/protobuf#6212]
![image](https://user-images.githubusercontent.com/22868335/58953136-29712280-87c8-11e9-956d-bbed1c8f8646.png)

**Comment by rainy1798** [comment]
What happened was that I had installed caffe, but found that protobuf version was 2.6.1 and I needed version 3.7, so I used apt-get to uninstall version 2.6.1 and uninstall a dependency package. Now this error occurred when I used apt-get to reload

**Comment by acozzette** [comment]
We are not involved with packaging protobuf for Linux distros, so this is not really something we can fix. It sounds like you might want to file a bug with Ubuntu or Debian, or it could also be an issue with a third-party PPA if you're using one.
