### ISSUE TITLE
finished with non-zero exit value -1

### ISSUE THREAD

**Issue by AlejandroPerezArteaga** [protocolbuffers/protobuf#6215]
Hi,

I am new with protocol buffers, I am trying to do the "addressbook" exercise, but I am gettin this error, I have seted up all my dependencies and everything looks ok, but when I run it I get this error, seems like is missing the file path.
by the way the:
 public static void main(String[] args) throws Exception
does not ask the user for the string args.

Thank you!!

**Comment by acozzette** [comment]
What is the error you're getting?

**Comment by AlejandroPerezArteaga** [comment]
hello, you know, I souldn´t not call this as "error", it is a message from the same system that is telling me that there were no input from the user, so I get my "args" empty when I run it... but as I understand when the running process is executed the "void main" sould ask for that input... rigth?, well i don´t get any request to give that input (that input sould be the path of the file that contains the address book)

so, the message I am getting is "finished with non-zero exit value -1"... what is that mean?

Thank you in advance... and remember I am just a beginer!

**Comment by acozzette** [comment]
You have to pass the `.proto` file on the command line (it won't ask you to input it interactively).
