### ISSUE TITLE
Proposal: C# RepeatedField.AsSpan() for more efficient access

### ISSUE THREAD

**Issue by prat0088** [protocolbuffers/protobuf#6217]
**What language does this apply to?**

c# protobuf 3

**Describe the problem you are trying to solve.**

Efficient lookups and assignments of RepeatedField<> (10s of millions )

It currently performs bounds and null checks inside an indexer method.  Indexing into a span is essentially the same as a ref return and the JIT compiler can optimize that even further to the point it is almost identical to operating on the array itself.  

I haven't yet benchmarked this proposal, but I expect it to perform similarly to ref returns, which are 1.25-10x faster than RepeatedField's current indexer method.

**Describe the solution you'd like**

```
public Span<T> AsSpan(int start, int length) {
    // Bounds check...

    return this.array.AsSpan(start, length);
}

```

Some might say this bypasses the null checks of the indexer method, but the C++ implementation allows you to memcpy entire memory chunks into RepeatedFields from what I understand.  While I feel a good library prevents the developer from using it incorrectly, I also feel it should be possible to squeeze extra performance out of a library if the developer accepts the risks.

**Describe alternatives you've considered**

- Adding a preprocessor variable that exposes a ref readonly indexer to access the array directly, without bounds or null checks.  I saw a 1.25 - 10x speedup in reads and writes.  I don't like this because the developer can no longer simply use the copy of Nuget.  
- I'm using a fork of Protobuf now that exposes the array directly.  

**Additional context**

I'm serving up ~30MB messages that contain millions of integers in RepeatedField<>s.  I need to make it as fast and efficient as possible while still using Protobuf.

Code-wise it's a small addition.  I'm happy to submit a PR if the above looks ok.

**Comment by prat0088** [comment]
@acozzette 

This requires netstandard 2.1.  It looks like Protobuf currently targets netstandard 1.0 and 2.0.  

Is it ok if I add a new target for netstandard2.1?

**Comment by prat0088** [comment]
One more point to bring up now: Returning a Span will allow the user to potentially write null values to the RepeatedField because it bypasses the null value check.  It's possible to write null values to RepeatedField in C++, too.  This gives such a great boost to performance (1-10x).  I think it is sufficient to add a note to the documentation that the user is responsible for null checks when using this method.

**Comment by ObsidianMinor** [comment]
We have a .NET Standard 2.0 target for System.Memory. You should use that.

**Comment by Falco20019** [comment]
I would also like to see this feature. Using `ReadOnlySpan` to avoid manipulation.

```csharp
public ReadOnlySpan<T> this[Range range]
{
	get
	{
		(int start, int length) = range.GetOffsetAndLength(array.Length);
		return new ReadOnlySpan<T>(array, start, length);
	}
}
```

I assume that should also be possible using `ReadOnlyMemory` if that's prefered.

**Comment by jtattermusch** [comment]
See the discussion here: https://github.com/protocolbuffers/protobuf/pull/6538#issuecomment-630105124
