### ISSUE TITLE
Error Installing Protobuf 3.6.0 

### ISSUE THREAD

**Issue by kamathhrishi** [protocolbuffers/protobuf#6227]
I am trying to install protobuf 3.6.0 on Ubuntu 16.04. 

I ran the following commands 
```
wget https://github.com/protocolbuffers/protobuf/archive/v3.6.0.tar.gz
tar zxvf v3.6.0.tar.gz
cd protobuf-3.6.0

#install protobuf 3.6.0
sudo ./autogen.sh
````
I ended up getting an error 

`+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 32: ./autogen.sh: autoreconf: not found
`

**Comment by kamathhrishi** [comment]
Turns out autoreconf dependency was not installed.

**Comment by Gyudong-Han** [comment]
The command
`
sudo apt-get install autoconf
`
