### ISSUE TITLE
GPG Signing and Verification of GitHub Release Artifacts

### ISSUE THREAD

**Issue by kenshaw** [protocolbuffers/protobuf#6232]
**What language does this apply to?**

Any language.

**If it's a proto syntax change, is it for proto2 or proto3?**

Not applicable.

**If it's about generated code change, what programming language?**

Not applicable.

**Describe the problem you are trying to solve.**

Ability to verify release artifacts retrieved from GitHub.

**Describe the solution you'd like**

An accompanying `*.asc` file for each platform's `protoc-*.zip` release artifact, containing the `.zip`'s GPG signature. The `*.asc` would be verifiable using `gpg --verify protoc-*.zip.asc protoc-*.zip`, as is commonly done with other projects.

Alternately, a single, intermediate, signed manifest file containing the SHA256 of all the published `protoc-*.zip` release artifacts.

**Describe alternatives you've considered**

Manually generating a SHA256 for each release, and embedding it wherever necessary (ie, in tools, or CI/CD pipelines). This is an imperfect solution as it is not published by the Protocol Buffers team, and requires manual updating for each release and for each platform variant.

**Additional context**

It would be helpful if the Protocol Buffers team signed release artifacts so future `protobuf` releases can be validated as originating from the Protocol Buffers team in an automated fashion. Other comparable projects published on GitHub make available signed manifests for published release artifacts as part of their release.

The primary use case is to automate downloading and verification of the `protoc` tool from within various continuous integration or deployment pipelines, or wherever verification is needed.

Specifically, the [Gunk](https://github.com/gunk/) team would like to validate the version of the `protoc` release the [`gunk`](https://github.com/gunk/gunk/) tool retrieves from GitHub.

**Comment by mathjeff** [comment]
The AndroidX team would like this too.
It seems to me that in the time since this issue was opened, protobuf is publishing .asc files but that the keys used in those files aren't consistent across releases so it doesn't allow us to validate releases "as originating from the Protocol Buffers team in an automated fashion".

In particular:

```
$ gpg ./3.19.0/protobuf-bom-3.19.0.pom.asc 2>&1 | head -n 4 | tail -n 1gpg:                using RSA key F1A51E051F527E0C8E24D54D4B1E11D5A4B91E89
$ gpg ./3.11.1/protobuf-bom-3.11.1.pom.asc 2>&1 | head -n 4 | tail -n 1gpg:                using RSA key 3D11126EA77E4E07FBABB38614A84C976D265B25
```

**Comment by liutikas** [comment]
Any updates here? Pretty much every new release of protobuf is signed with a new key, so far we've seen the following keys used:
- 0x187366a3ffe6bf8f94b9136a9987b20c8f6a3064
- 0x1dbb44e80f61493d6369b5fb95c15058a5eda4f1
- 0x22b79f456b06f4e75b8b579db57bd58ef6d0a713
- 0x3d11126ea77e4e07fbabb38614a84c976d265b25
- 0x4896f7312a5ace4d
- 0x696b6199a2a9d8c29ce78cc0d041cad2e452550f
- 0x95c15058a5eda4f1
- 0xa7764f502a938c99
- 0xae2b18e836c5f30687f37efdcc6346f2ce3872d9
- 0xb57bd58ef6d0a713
- 0xcc6346f2ce3872d9
- 0xd041cad2e452550f
- 0xd75e25b78ebb19e47c0a99bca7764f502a938c99
- 0xf1a51e051f527e0c8e24d54d4b1e11d5a4b91e89

And now when trying to upgrade to `3.21.9`, we just got a new key `f9acd39310b477b691f4e3f9971248996df82053`

This key rotation defeats the purpose of validation of this binary being from the same author as the previous binaries.

**Comment by deannagarcia** [comment]
We finally got a certificate that we plan to sign our artifacts with, but we still need to put development time into properly using it. We are aiming to use that certificate to make more consistent signing in the next minor release (22.x). I'm sorry it's taken so long.

**Comment by rnorth** [comment]
I'd just like to check - is this effort also tackling MacOS codesigning of binaries, or is it purely focused on GPG signing? 

I ask because #10880 was closed, but unless I'm missing something these look like distinct issues. GPG signatures alone would not be sufficient to satisfy MacOS that the _aarch_64_ (specifically) binaries are safe to execute.

**Comment by deannagarcia** [comment]
Starting in 23.0 (and newer patches of 22.x), MacOS binaries will be signed! 

We decided to prioritize that work over GPG signing, but I will look into that next.

**Comment by justfalter** [comment]
Can this be re-opened? GPG-signing would protect the integrity of release assets for this very important project.
