### ISSUE TITLE
protobuf-global-extension-registry: issue new ID for TwirpQL

### ISSUE THREAD

**Issue by marwan-at-work** [protocolbuffers/protobuf#6235]
I'd like to create a new public extension of `google.protobuf.MethodOptions` inside `descriptor.proto` and I would love for it to not clash with other public extensions by adding it to the public registry as described [here](https://github.com/protocolbuffers/protobuf/blob/master/docs/options.md). 

The application is a GraphQL generator on top of Twirp services. 
The website is: https://twirpql.dev
The option extension is defined here: https://github.com/marwan-at-work/protoc-gen-twirpql/blob/master/twirpql/twirpql.proto#L8

Notice that the unique number is currently `1991` but I'd be happy to change it once a unique ID is issued. 

Thanks

**Comment by acozzette** [comment]
@marwan-at-work Sounds good, you can just send me a pull request to update `options.md`.
