### ISSUE TITLE
 The enumeration of Objective-C will be automatically hump-named！

### ISSUE THREAD

**Issue by mythkiven** [protocolbuffers/protobuf#6239]
We use protobuf as the data encoding method for the App and BLE device communication protocol.
In an update, I created an enumeration with "BLE" in messages.proto, and then there was a problem that the communication content could not be resolved in Objective-C. The problem was found to be enumerated naming problem: there is an enumeration named "MKBLEFirmware", using `protoc --proto_path=. --objc_out=./oc messages.proto ` After conversion, the enumeration name becomes "MKBleFirmware".
PS: java does not have this problem, Objective-C class name does not appear this problem, only the Objective-C enumeration will be automatically hump-named.

**Comment by thomasvl** [comment]
That is by design.  The generation attempt to remap from the [style guide](https://developers.google.com/protocol-buffers/docs/style) to the Apple conventions to provide names more like what Apple developers will expect.
