### ISSUE TITLE
Migrate Ruby to use upb_msg in its C extension

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/protobuf#6241]
`upb_msg` is a new data structure in upb that provides a language-agnostic message representation.

Once it is ready in upb, we should migrate the Ruby implementation to use it. This will greatly simplify the code, and should also improve performance. Some profiles show GC using 80% of CPU when parsing large messages. In the upb_msg model, Ruby wrapper objects are only created when accessed.

**Comment by sprql** [comment]
Related: #8184

**Comment by haberman** [comment]
Yes, this is fixed in https://github.com/protocolbuffers/protobuf/pull/8184.
