### ISSUE TITLE
Protobuf 3.8.0 is failing to build on Mac OS 10.14.5

### ISSUE THREAD

**Issue by davido** [protocolbuffers/protobuf#6247]
After upgrading rules_closure to Protobuf 3.8.0 and after upgrading Gerrit Code Review to this rules_closure version, a user reported this build failure for Gerrit: https://pastebin.com/hdHeRF4h.

Reverting [Protobuf upgrade to 3.8.0](https://gerrit-review.googlesource.com/c/gerrit/+/227174) and downgrading it to 3.7.1 fixed the breakage.

Is this a known issue?

//CC @acozzette @meteorcloudy

**Comment by meteorcloudy** [comment]
That looks strange, I tested on mac, I'm able to build `//:protobuf` without any problem. Is there a branch of rules_closure or Gerrit where we can reproduce this problem?

**Comment by davido** [comment]
@meteorcloudy Thanks for looking into it. The problem was reported on Gerrit@HEAD.

@msohn Can you provide any details about your environment?

**Comment by dandrino** [comment]
I'm getting the same problem. 

Repro steps:
```
git clone --branch v3.8.0 https://github.com/protocolbuffers/protobuf.git
cd protobuf
bazel build //:protobuf
```

Bazel version:
```
Build label: 0.25.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 10 20:50:40 2019 (1557521440)
Build timestamp: 1557521440
Build timestamp as int: 1557521440
```

Running on macOS Mojave Version 10.14.5
I did install updates recently, not sure if that's relevant.

**Comment by dandrino** [comment]
Also, downgrading to 3.7.1 doesn't work for me because I need `protobuf_deps.bzl`  which wasn't added until 3.8.0. I chosen an intermediate commit as a temporary solution until this gets fixed.

My WORKSPACE file:

```bzl
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "bazel_skylib",
  remote = "https://github.com/bazelbuild/bazel-skylib",
  branch = "master",
)

git_repository(
  name = "com_google_protobuf",
  remote = "https://github.com/google/protobuf",
  commit = "b6375e03aa80274dae89410efdf46346413b2247",
  init_submodules = 1,
)

git_repository(
  name = "com_google_absl",
  remote = "https://github.com/abseil/abseil-cpp.git",
  branch = "master",
  init_submodules = 1,
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

**Comment by davido** [comment]
I am not able to reproduce the problem. I am also on Mac OS 10.14.5. `clang` version here is:

```
 $ clang --version
\Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dandrino** [comment]
My clang version:
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I'll try to pinpoint the earliest commit that breaks for me.

**Comment by dandrino** [comment]
Okay, I've binary searched to this commit as the one that breaks for me: https://github.com/protocolbuffers/protobuf/commit/429d2ae19f56a495b4bddbd664bfb76d2dc225f2

The previous commit compiles: https://github.com/protocolbuffers/protobuf/commit/e4e5bc49d7cd9fa1cc7e352da3289711fedcea18

**Comment by dandrino** [comment]
I've found the problem: the "protobuf" homebrew package installs is headers at `/usr/local/include/**` which takes precedence over the local include paths in the protobuf repo when building, and the inconsistency in declarations is causing the build failure.

New repro steps:
```
brew install protobuf
git clone --branch v3.8.0 https://github.com/protocolbuffers/protobuf.git
cd protobuf
bazel build //:protobuf  # Unhappiness ensues here

brew uninstall protobuf
bazel clean --expunge
bazel build //:protobuf  # Happiness resumes
```

**Comment by meteorcloudy** [comment]
This looks like protobuf issue. @acozzette.
Which version of protobuf did you install with homebrew? Is it 3.8.0?

**Comment by dandrino** [comment]
The latest version from homebrew appears to be 3.7.1
