### ISSUE TITLE
Generated code break compilation on GCC with -Wzero-as-null-pointer-constant

### ISSUE THREAD

**Issue by adambadura** [protocolbuffers/protobuf#6252]
Generated code uses `NULL` a lot. Possibly also there are cases where `0` is used with pointers.

If C++11 can be now already assumed as a minimum requirement then `nullptr` could be used directly instead. If not, then some extra abstraction would be needed, like a `PB_NULL` which is defined as `NULL` or as `nullptr` depending on settings.

**Comment by BSBandme** [comment]
Feel free to send us a  PR for cleaning up this.

**Comment by wangkirin** [comment]
Hi @adambadura ,   I did not encounter a similar situation in  `v3.8.0` ,the generated code uses `nullptr` instead of `NULL` or `0` . When I look through the commit history, I found that @aconchillo had already fix  this issue in `v3.7.0rc1`

The PR address is : https://github.com/protocolbuffers/protobuf/pull/5323

**Comment by adambadura** [comment]
> Hi @adambadura , I did not encounter a similar situation in `v3.8.0` ,the generated code uses `nullptr` instead of `NULL` or `0` . When I look through the commit history, I found that @aconchillo had already fix this issue in `v3.7.0rc1`
> 
> The PR address is : #5323

Oh! We are using `v3.6.x`. I also checked on http://protobuf-compiler.herokuapp.com/, but I guess they must be prior to the fix as well - sadly I don't see version anywhere there. (Should generated files have a comment with compiler version?) While I failed to build `master` version (#6381 and #6382).

So, I guess this should be closed then as a duplicate. I'm not closing it myself yet in case some labels should be applied (like a duplication marker or something).

**Comment by wangkirin** [comment]
Hi, @adambadura I look through the source code of `http://protobuf-compiler.herokuapp.com/`,   it seems it use protobuf 3.2.0 
 https://github.com/xuwei-k/protobuf-compiler/blob/bd5b6528c75fab4f754b3c34996b64d5646c56df/build.sbt#L69
so it  also use an old version 

about close this PR,  May be @BSBandme can help to deal with these lables

**Comment by jorgbrown** [comment]
If you look at https://developers.google.com/protocol-buffers/docs/news/2022-08-03 , the official support matrix is currently at https://github.com/google/oss-policies-info/blob/8067c719150dfec6a836dd82230c5eb0ba11acd7/foundational-cxx-support-matrix.md , and it currently says the lowest supported gcc is 7.3.1
