### ISSUE TITLE
protoc - Adding Java sources from JAR

### ISSUE THREAD

**Issue by timon-langlotz** [protocolbuffers/protobuf#6253]
protoc has a feature to output directly to a JAR. While using that feature, I realized that the JAR contains .java files, and not .class files. This is also documented [here](https://developers.google.com/protocol-buffers/docs/reference/java-generated).

Is the purpose of this only to have a sources JAR for debugging purposes? Or to actually bundle the code in a more structured way?

The documentation mentioned above also mentions that 
> ... many Java tools are able to read source code directly from JAR files.

If the purpose is for documentation only, is there a reason why there is no way to generate a JAR with .class files?

Cheers,
Timon

**Comment by BSBandme** [comment]
protoc won't invoke java compiler but just compile the proto file and write to file.
