### ISSUE TITLE
VS2005: Include file atomic.h not found. C++11 required?

### ISSUE THREAD

**Issue by NoWHereRepo** [protocolbuffers/protobuf#6254]
What is the minimum C++ compiler need on Windows to use protobuffer?

The generated file includes google/protobuf/io/coded_stream.h which itself includes atomic.h
Is it not possible to use the generated classes with Visual Studio 2005?

Cheers,
Thorsten

**Comment by acozzette** [comment]
C++11 is required starting from version 3.6. If you need to use a pre-C++11 compiler then you can try using protobuf 3.5.

**Comment by NoWHereRepo** [comment]
I had no luck with 3.6 but didn't spent too much time trying to get it running. 
Version 2.6.1 is working in combination with VS 2005

Thanks :)
