### ISSUE TITLE
Test against current cuda version, to ensure c++ feature compatibility

### ISSUE THREAD

**Issue by Fleischner** [protocolbuffers/protobuf#6271]
Currently cuda (10.1) compiler nvcc still has problems with constexpr. We get errors when building pytorch with the current protobuf master. Pytorch uses therefore an older version with some patches, but the version inconsistency generates other problems.

It would be great if protobuf could hide newer c++ construcs behind an #define until cuda nvcc compiler gets compatible.

Currently there are two places:

cpp_message.cc
static constexpr int kIndexInFileMessages =\n"
==> static int const kIndexInFileMessages =\n"

extension_set.h
static constexpr uint16 kMaximumFlatCapacity = 256;
==> static uint16 const kMaximumFlatCapacity = 256;

**Comment by haon4** [comment]
Feel free to send us a PR for this. We don't have much experience with the cude compiler so it is difficult to verify our changes.
