### ISSUE TITLE
How can I set custom validator for protobuf java class?

### ISSUE THREAD

**Issue by DoneSpeak** [protocolbuffers/protobuf#6273]
I am trying to find a way to set validator for proto as what I do with hibernate.validator.

![image](https://user-images.githubusercontent.com/16522248/59652909-565b0780-91c2-11e9-8cfd-c23dfac655d5.png)

**Comment by JanecekPetr** [comment]
You cannot do that in core protobuf (#3256). There are a couple of projects offering protobuf validation as an add-on, though:

- https://github.com/envoyproxy/protoc-gen-validate
- https://github.com/SeriousMa/grpc-protobuf-validation
- https://github.com/entur/protobuf-validation
- and maybe others?

**Comment by DoneSpeak** [comment]
@JanecekPetr Thanks.  I also found these items the day before yesterday. And I found the following message in the mail list.
> Sorry, but validation of this sort is not part of protocol buffers.  You'll need to write validation routines separately.  We made a conscious decision not to try to support validation in the .proto language itself because it seemed like it would require a turing-complete language to express arbitrary validators, and we wanted to keep things simple.
> 
> -- Kenton Varda 2008/7/8 - [How can i validate the protocol buffer data?](https://groups.google.com/forum/#!topic/protobuf/ncE0GZbslao)

So I decide to use Customer Option to implement my functions.

**Comment by BSBandme** [comment]
Close for now.
If you still have any questions feel free to reopen the issue
