### ISSUE TITLE
Can custom option be accessed at runtime for protobuf 3.5.1?

### ISSUE THREAD

**Issue by AlanYiNew** [protocolbuffers/protobuf#6275]
I am using protobuf 3.5.1 and try to access the custom option I made but found out the unknown_fields().field_count() of the fieldDescriptor is always zero though I can find that it does has the option there by printing the DebugString of FieldDescriptor. Once again, is it possible to get the custom option's value at runtime? I am using C++.

**Comment by acozzette** [comment]
The custom option will appear as an extension and not in the unknown field set, so to access it you can do something like: `descriptor->options().GetExtension(option_name)`.
