### ISSUE TITLE
unreachable issue of a branch in  cpp_generator.cc 

### ISSUE THREAD

**Issue by wangkirin** [protocolbuffers/protobuf#6285]
**What version of protobuf and what language are you using?**
- Version: master
- Language: C++
 
**What did I do?**

when I go through the source code of cpp, i think the following code after the **` if (file_options.proto_h)`**  branch(line 138 of `/src/google/protobuf/compiler/cpp/cpp_generator.cc`) may cannot be reached ,

https://github.com/protocolbuffers/protobuf/blob/5b232b8ecbce13286be09e703997e887ae0d464d/src/google/protobuf/compiler/cpp/cpp_generator.cc#L138-L155

**Following is my analysis:**

- `file_options` is instantiated in line 80 of `cpp_generator.cc`
https://github.com/protocolbuffers/protobuf/blob/5b232b8ecbce13286be09e703997e887ae0d464d/src/google/protobuf/compiler/cpp/cpp_generator.cc#L80

- `file_options.proto_h` default  value is **`false`** in the `cpp_options.h`
https://github.com/protocolbuffers/protobuf/blob/54288a01cebfd0bfa62ca581dd07ffd6f9c77f2c/src/google/protobuf/compiler/cpp/cpp_options.h#L55

- and  `file_options.proto_h`  have not be reassigned in `cpp_generator.cc`,  even in the whole project

**This makes me a bit confused， Could someone give me a help about it ?**

**Comment by wangkirin** [comment]
Hi , @acozzette , could you help me take a look?

**Comment by acozzette** [comment]
The `proto_h` feature is one we haven't yet open sourced because it still needs to be cleaned up, so that is why it appears to be unreachable there.

**Comment by wangkirin** [comment]
- when I go through the source code of cpp, i think the following code after the if (file_options.num_cc_files > 0) branch(line 193 of /src/google/protobuf/compiler/cpp/cpp_generator.cc) may cannot be reached
#### Following is my analysis:
- file_options is instantiated in line 80 of cpp_generator.cc
https://github.com/protocolbuffers/protobuf/blob/7e276a329353180757c63037b05859b9b49b60a9/src/google/protobuf/compiler/cpp/cpp_generator.cc#L80

- file_options.num_cc_files value is 0 in the cpp_options.h
https://github.com/protocolbuffers/protobuf/blob/7e276a329353180757c63037b05859b9b49b60a9/src/google/protobuf/compiler/cpp/cpp_options.h#L65

- the value of file_options.num_cc_files can be modified on line 104
https://github.com/protocolbuffers/protobuf/blob/7e276a329353180757c63037b05859b9b49b60a9/src/google/protobuf/compiler/cpp/cpp_generator.cc#L85-L115

- the options come from const string& parameter.when *error is returned to be NULL,so the value of options [i] .second can only be "dllexport_decl" / "annotate_headers" / "annotation_pragma_name" / "annotation_guard_name" / "lite" / "lite_implicit_weak_fields" / "Table_driven_parsing" / "table_driven_serialization" / "speed"
- i try to make strto32(options[i].second.c_str(),NULL, 10)>0 but false,so file_options.num_cc_files > 0 can't be true
- is my usage correct ? or is it caused by the same cause(same code has not yet open sourced)?
