### ISSUE TITLE
ARM support packages did not in the sub-release, which tags like “v3.7.0-rc.2”， “v3.6.1.3”

### ISSUE THREAD

**Issue by bzhaoopenstack** [protocolbuffers/protobuf#6287]
I found some tags releases which the name format like “v3.7.0-rc.2”， “v3.6.1.3”, they didn't have a ARM release, even just a source tar/zip package.

I'm not sure why we did that. When I try to build a project(such as apache/hbase) which have a dependancy with protobuf, it uses the release version 3.5.1-1, which  just contains a source tar/zip package. Then, if I want to build it on different ARCH, x86/ARM, I need to compile and build protobuf first. 

So I guess protobuf team could help to do this, provides the packages in the some way with the official release, like "v3.8.0"(Big-release version). Then, once we release a new release whatever "vA.B.C" "vA.B.C-D" or "vA.B.C-rc.D", we can keep the same in the future. This is my thought, please forgive me that not sure how much works it could be. ;-), But I still think that's a valuable thing to be done.

Also, the oldest release like v2.5.0, could we add aarch64 packages for support ARM. I found so may apache projects depends on 2.5.0, but lacks ARM support. Thank you very much.

For 2.5.0, this seems a old issue[1] [2] [3] [4], which with a long story, it still makes us headache.  We found not only Hbase depends on protobuf 2.5.0, there is a certain amount of apache projects still using it. In Big data area at lease.  Please help to add a arm release for it also. Thank you

[1] https://www.dropbox.com/s/713wql5cw9dfxhx/protobuf-2.5.0-arm64.patch?dl=0
[2] https://issues.apache.org/jira/browse/HBASE-19146
[3] https://github.com/protocolbuffers/protobuf/issues/5115
[4] https://github.com/protocolbuffers/protobuf/issues/3844#issuecomment-343355946

**Comment by bzhaoopenstack** [comment]
Any updates? Team?

**Comment by bzhaoopenstack** [comment]
Hi

**Comment by liu-sheng** [comment]
Hi I am also trying to build the Apache Hive project on ARM64 server,  which depends on the `protobuff 2.5.0`, see [here](https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/pom.xml#L453-L458), but there isn't protobuff-2.5.0 package for ARM platform in [Maven central repository](http://central.maven.org/maven2/com/google/protobuf/protoc/), so I have to build the `protobuff-2.5.0` manually, but I have met the following error when I was trying to build:
```
root@ubuntu:/usr/local/src/protobuf-2.5.0# make
make  all-recursive
make[1]: Entering directory '/usr/local/src/protobuf-2.5.0'
Making all in .
make[2]: Entering directory '/usr/local/src/protobuf-2.5.0'
make[2]: Leaving directory '/usr/local/src/protobuf-2.5.0'
Making all in src
make[2]: Entering directory '/usr/local/src/protobuf-2.5.0/src'
g++ -DHAVE_CONFIG_H -I. -I..    -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o `test -f 'google/protobuf/compiler/main.cc' || echo './'`google/protobuf/compiler/main.cc
mv -f .deps/main.Tpo .deps/main.Po
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..    -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT atomicops_internals_x86_gcc.lo -MD -MP -MF .deps/atomicops_internals_x86_gcc.Tpo -c -o atomicops_internals_x86_gcc.lo `test -f 'google/protobuf/stubs/atomicops_internals_x86_gcc.cc' || echo './'`google/protobuf/stubs/atomicops_internals_x86_gcc.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT atomicops_internals_x86_gcc.lo -MD -MP -MF .deps/atomicops_internals_x86_gcc.Tpo -c google/protobuf/stubs/atomicops_internals_x86_gcc.cc  -fPIC -DPIC -o .libs/atomicops_internals_x86_gcc.o
In file included from ./google/protobuf/stubs/atomicops.h:59:0,
                 from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
./google/protobuf/stubs/platform_macros.h:61:2: error: #error Host architecture was not detected as supported by protobuf
 #error Host architecture was not detected as supported by protobuf
  ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:0:
./google/protobuf/stubs/atomicops.h:161:1: error: stray ‘#’ in program
 #error "Atomic operations are not supported on your platform"
 ^
./google/protobuf/stubs/atomicops.h:188:1: note: in expansion of macro ‘GOOGLE_PROTOBUF_ATOMICOPS_ERROR’
 GOOGLE_PROTOBUF_ATOMICOPS_ERROR
 ^
./google/protobuf/stubs/atomicops.h:161:2: error: ‘error’ does not name a type
 #error "Atomic operations are not supported on your platform"
  ^
./google/protobuf/stubs/atomicops.h:188:1: note: in expansion of macro ‘GOOGLE_PROTOBUF_ATOMICOPS_ERROR’
 GOOGLE_PROTOBUF_ATOMICOPS_ERROR
 ^
Makefile:1481: recipe for target 'atomicops_internals_x86_gcc.lo' failed
make[2]: *** [atomicops_internals_x86_gcc.lo] Error 1
make[2]: Leaving directory '/usr/local/src/protobuf-2.5.0/src'
Makefile:669: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/protobuf-2.5.0'
Makefile:576: recipe for target 'all' failed
make: *** [all] Error 2
```
After I applied the [patch ](https://www.dropbox.com/s/713wql5cw9dfxhx/protobuf-2.5.0-arm64.patch?dl=0) to protobuff of v2.5.0 source code, I can sucessfully build `protobuff-2.5.0` binary on ARM64 server.

**Comment by bzhaoopenstack** [comment]
Sorry for disturb you guys. But could you please give some advices or help about this? Thank you very much. We really need your kind help.
@acozzette @TeBoring @haon4

**Comment by haon4** [comment]
To build for arm, I think we will need to update the configurations in [protoc-artifacts](https://github.com/protocolbuffers/protobuf/tree/master/protoc-artifacts) and [build.sh](https://github.com/protocolbuffers/protobuf/blob/master/kokoro/release/protoc/linux/build.sh). I haven't tried building with arm myself, so I am not sure how much work that would be though. If anything, the complication would probably be around setting up the environment such that we can build for arm.

**Comment by bzhaoopenstack** [comment]
@haon4 Hi, thanks very much for reply. I think so, to change https://github.com/protocolbuffers/protobuf/tree/master/protoc-artifacts and https://github.com/protocolbuffers/protobuf/blob/master/kokoro/release/protoc/linux/build.sh is necessary. But for example, for build protobuf 2.5.0, we need to back port the patch https://www.dropbox.com/s/713wql5cw9dfxhx/protobuf-2.5.0-arm64.patch?dl=0 . Then it(2.5.0) can be built success and work well. So I think there may be some adaptation works. 

Another questions, hope you could let us know, please. That's I found Linux aarch_64 using Cross compiled tools and aarch_64 build by X86 or other ARCH platforms in https://github.com/protocolbuffers/protobuf/blob/master/protoc-artifacts/README.md. So that means we(protobuf team) are not sure whether the released ARM packages can works well on ARM. Am I right? All the release versions which including a ARM binary/src download link are the same? If that is true, Woo, that may be a very large work for support ARM eco-system. But it's really valuable work to do.

Thank you @haon4 , wish you could help us and give some kind advices to how to make it work, or any helps you want from us. Please feel free to raise and discuss. 

Best Regards,

ZhaoBo

**Comment by bzhaoopenstack** [comment]
Hi Team, any updates about this? 
Thanks

**Comment by haon4** [comment]
Looking around on how to make this work, I found https://assil.me/2017/10/21/cross-compile-protobuf-arm-zynq.html. Have you tried that and doesn't it work for you? If it does, I think we may have a way to move forward.

**Comment by bzhaoopenstack** [comment]
@haon4 , Thanks very much for reply. When we using the cross-compile version(or directly compile/build a binary on ARM machines), we test failed on ARM, but the tests success on X86, so we still not sure whether cross-compile version on ARM have enough tests, even we success build a ARM release.. So could you please give some advices about how to make it work on ARM?

**Comment by haon4** [comment]
Yea, that is my worry too. Even if we manage to cross-compile it and include it in our release, there is no guarantee that everything will work correctly. I am also not sure how we will fix future bugs if we can't run on ARM machines. Passing on to Adam who has looked into ARM and may know more about how to solve this.

**Comment by acozzette** [comment]
It sounds like there are a few different issues here:
1. Some projects are still using version 2.5.0. That was released in February 2013 so it's quite old at this point and ideally we should help those projects upgrade to a more recent version.
2. Patch releases not including ARM artifacts. Usually when we create a patch release like 3.6.1.3 it just contains a fix for a very specific language or platform, so we often don't rebuild every artifact and it's fine to keep using artifacts from the earlier release.
3. Tests failing on ARM. If someone could post details on the test failures then we could help fix them.

**Comment by bzhaoopenstack** [comment]
@haon4  Thanks very much. As our team is trying to open up the ARM eco-system, but found so many apache projects using the old 2.5.0 version, and seems they are very hard and so much work to upgrade to the new version of protobuf, such as hadoop, they said that's a very huge work[1] .

[1] https://issues.apache.org/jira/browse/HADOOP-13363

@acozzette Thanks for clean up. 
For issue 1, correct, but for some projects(apache community), looks very difficult and so much work about upgrading the protobuf version, whatever from the human resources or code change, such as hadoop [1] .
For issue 2, Understood, but some projects which we are trying to concern are using the sub-release version, like hbase [2] . So I want to say, we can not control the "users", they can choose any version. ;-) .
If we need to test the hbase on ARM, we also need to compile the sub-version. This may be a valuable suggest to protocbuf community/team. And I know that may be a addition work to do. ;-)
For issue 3, OK, I'm so glad to hear that, thank you very much. I will tell our team members to post the failure details during our work process.

[1]  https://issues.apache.org/jira/browse/HADOOP-13363
[2] https://github.com/apache/hbase/blob/master/hbase-protocol-shaded/pom.xml#L39

Thanks again you guys.

Best Regards,

ZhaoBo

**Comment by jtattermusch** [comment]
FYI  protobuf now officially support ARM64 (and is being continuously tested).
Details are in the blogpost: https://grpc.io/blog/grpc-on-arm64/ 

I think this issue can be closed since there haven't been any updates for the last 2 years and some of the concerns (such as lack of ARM support for protobuf 2.5) are now even more out-of-date than they were before.
