### ISSUE TITLE
Anyway to have #include without sub directory when .proto is in a sub directory?

### ISSUE THREAD

**Issue by guifran001** [protocolbuffers/protobuf#6290]
Having this directory layout:
```
base
 +--- a.proto
 + subdir
         \--- b.proto
```
if I call:
protoc -I base -cpp_out out a.proto subdir\b.proto

it will generate in out directory:
```
out
 +-- a.pb.h
 +-- a.pb.cc
 + subdir
       +--- b.pb.h
        \--- b.pb.cc
```

As intended. But the include of b.pb.h  in b.bp.cc will be:
`#include "subdir/b.pb.h"`
instead of simply:
`#include "b.pb.h"`

Is that intended or is it a bug ?

Since protoc can only generate .h and .cc side by side, adding this extra path in the #include preprocessor macro seems superfluous. It affects the developer experience (require to add an extra include path for compiling or to replace #include in generated file or to call protoc for each sub folder) and does not seem to bring any benefits. Am I right ?

Are there some good practices to circumvent this ?

**Comment by haon4** [comment]
This seems to be intentional per https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#invocation. If you want b.pb.h to be generated at the top level, why not put b.proto side by side with a.proto?

**Comment by BSBandme** [comment]
Close for now as it is an intended behavior.

**Comment by guifran001** [comment]
@haon4 : I don't want to use b.ph.h at top level. I want the hierarchy.
I want to include in my code by specifying the subdir:
`#include "myprotos/generated/subdir/b.pb.h"`

The problem that is happening is that when I compile my code, myprotos/generated/subdir/b.pb.cc won't compile unless I have "myprotos/generated" in my include path, because myprotos/generated/subdir/b.pb.cc  contains an include with the subdir in it:
`#include "subdir/b.pb.h"`
Which seems cumbersome since `b.pb.cc` is already in `subdir`. Adding `subdir` in the include seems to me to only add complexity while not resolving any. Hence my question.
