### ISSUE TITLE
Is there a tool to convert proto Builder to java Constructor?

### ISSUE THREAD

**Issue by singgel** [protocolbuffers/protobuf#6291]
- question：

> I want to convert proto deserialized Builder into java Constructor, which needs to deal with the wrappers class. When it encounters no assignment, it changes to NULL.

eg:
proto
`syntax = "proto3";

import "google/protobuf/wrappers.proto";
option java_outer_classname = "PeopleProto";

message People {
    int32 personId = 1;
    string personName = 2;
    google.protobuf.StringValue  sex = 3;
    repeated string address = 4;
}`

java
`public class People {

    private int personId;

    private String personName;

    private String sex;

    List<String> address;
   
    ...
}`

- I have tried two ways:

1. use reflection（problem：poor reflection performance）
https://github.com/singgel/protobuf-converter

2. Use constructors one by one set（problem：too much repetitive coding） #

**Comment by haon4** [comment]
Sorry I don't quite understand the question. Do you have a Message.Builder that you would like to convert to a Message? Or do you have a Message.Builder that you would like to convert to a plain old Java object?

**Comment by singgel** [comment]
In my limited experience with protobuf!

**Comment by singgel** [comment]
In my limited experience with proto!
Yes, I have a lot of Message.Builder need to convert to a plain old Java object.

**Comment by singgel** [comment]
Thank you for your answer sincerely!

Yes, I have a lot of Message.Builder need to convert to a plain old Java object.
But I need to write a lot of SET and GET for filed conversion.
I have tried using reflection, but the problem is that the efficiency of reflection is very low.
So I want to have a way to assign value to old java object directly in binary decode.

Please forgive me for my poor English. Thanks！

**Comment by singgel** [comment]
Thank you for your answer sincerely!

Yes, I have a lot of Message.Builder need to convert to a plain old Java object.
But I need to write a lot of SET and GET for filed conversion.
I have tried using reflection, but the problem is that the efficiency of reflection is very low.
So I want to have a way to assign value to old java object directly in binary decode. But I don't know the decoding process of the binary stream.
Or is there any other better idea? Thanks！

Please forgive me for my poor English.

**Comment by haon4** [comment]
I don't quite understand your use-case, but I don't think we support directly converting from Message.Builder to a plain-old Java object. You can use message reflection, but like you said, the efficiency may be low. Do you really need to use a plain old Java object though? Can't you just build the Message from Message.Builder and use the Message?

**Comment by singgel** [comment]
thank you for your help. I will try other paths to solve this problem, or build the Message from Message.Builder and use it directly as you said.
