### ISSUE TITLE
protoc: inconsistent name resolution behavior

### ISSUE THREAD

**Issue by dsnet** [protocolbuffers/protobuf#6296]
Consider the following proto file:
```proto
package foo.bar;
message M {    // declared as .foo.bar.M
    enum E {   // declared as .foo.bar.M.E
        M = 0; // declared as .foo.bar.M.M
    }
    optional M F1 = 1;
    extend M { optional string F2 = 2; }
    extensions 2 to 2;
}
```
There are two relative `M` references:
* `optional M ...`
* `extend M { ... }`

Both relative `M` references occur within the `.foo.bar.M` namespace.

Per the [C++ scoping rules](https://github.com/protocolbuffers/protobuf/blob/b7a5772caf08d62a20fd1bca258f501fa4db022c/src/google/protobuf/descriptor.proto#L186-L191), the following absolute names should be tried in the following order:
* `.foo.bar.M.M`
* `.foo.bar.M`
* `.foo.M`
* `.M`

In our situation, both `.foo.bar.M.M` and `.foo.bar.M` are legal declarations.

However, the way resolution is handled is odd:
* For the case of `optional M ...`,  it first finds `.foo.bar.M.M`, which is an enum value type. Since it's looking for an enum or message type, it ignore this. It continues on to then find `.foo.bar.M`. Since this is a message type, it returns that declaration.
* For the case of `extend M ...`, it first finds `.foo.bar.M.M`, which is an enum value type. Since it's looking for a message type, it throws an error complaining that it found the wrong type.

This is inconsistent. The relative name resolution logic should either:
* always ignore the declaration of the wrong type and keep searching
* always error when finding a declaration of the wrong type

What is the right behavior?

**Comment by haon4** [comment]
"always error when finding a declaration of the wrong type" seems like the more desirable behavior. At the minimum, it would highlight that there are some confusing types there, instead of magically resolve to some random type.

If we make it to always error, how many things will break?

**Comment by jhump** [comment]
FWIW, method input and output names behave the same as extendee -- resolution of these names does not skip over non-type elements as is done for field types.

**Comment by jhump** [comment]
Same goes for extension name resolution, when resolving option names. Though there is no "ResolveMode" that would work for this (i.e. there is no "LOOKUP_EXTENSIONS" value).

**Comment by jhump** [comment]
This is sort of related to #9550. Different root cause and symptom, but also about inconsistent behavior when it comes to resolving names from different contexts.
