### ISSUE TITLE
Ruby cannot decode the big protobuf generated by Golang

### ISSUE THREAD

**Issue by aristotll** [protocolbuffers/protobuf#6297]
I use the Message#decode method to decode the big pb file generated by Golang pb lib, about 10mb.

It throws:

```
        1: from (irb):18:in `decode'
Google::Protobuf::ParseError (Error occurred during parsing: Nesting too deep.)
```

But use go pb lib the decode is ok, any option can be provided to make the nesting ok?

**Comment by TeBoring** [comment]
Could you try making the proto smaller?

**Comment by aristotll** [comment]
Finally， I find a workaround by build a golang shared library for Ruby.
