### ISSUE TITLE
[C++] GetDescriptor() method crash

### ISSUE THREAD

**Issue by noeat** [protocolbuffers/protobuf#6311]
protobuf version : master
os: ubuntu 18.04 lts
gcc version: 8.3.0

proto define:
syntax = "proto3";

package test;
 
message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}

use protoc  generate cpp code。
this is me code:
```
test::SearchRequest request;
auto desc = request.GetDescriptor();
```

it will crash on auto desc = request.GetDescriptor() line.
but i run this code on windows, it cant crash.

**Comment by haon4** [comment]
That is weird. Are you able to access anything else on the `request`? Which compiler did you use to build your program? Can you reproduce this in a small stand-alone program?

**Comment by noeat** [comment]
compiler is gcc 8.3.0, 
`
int main(int argc, char **argv) {	
	test::SearchRequest request;
        auto desc = request.GetDescriptor();
        return 0;
}`

crash on request.GetDescriptor(); line, gdb debug descriptor is null
 ```
p ::descriptor_table_pb_2eproto.file_level_metadata[kIndexInFileMessages]
  $3 = {descriptor = 0x0, reflection = 0x0}

```

**Comment by noeat** [comment]
Has been resolved， it need link pthread.  
http://www.itkeyword.com/doc/7552176368809279x868/building-c11-threadable-translation-units-in-linux

if not link pthread, Compile normal
