### ISSUE TITLE
Running protoc.exe in Azure - exitcode -1073740791

### ISSUE THREAD

**Issue by cbbrsc** [protocolbuffers/protobuf#6312]
I'm trying to generate C# classes from a proto file using protoc.exe tool started as a process from an azure web app.
I receive a exit code = -1073740791 and no output.
 Any idea about possible causes?
Thanks.

**Comment by haon4** [comment]
I think -1073740791 is an error code from Azure, not protoc. You may need to ask this question on the Azure forum. Maybe there are security restrictions on running .exe file on their server.

**Comment by cbbrsc** [comment]
Indeed is an azure issue. I've solve it.  
Thanks.

**Comment by imrichardcole** [comment]
I'm aware this is an old issue/version - but what was the cause of this return code?  We're seeing it sporadically on Windows.
