### ISSUE TITLE
Dockerfile cannot build

### ISSUE THREAD

**Issue by suztomo** [protocolbuffers/protobuf#6314]
@TeBoring and I found kokoro/linux/64-bit/Dockerfile does not work. I'm thinking to fix this situation.

**What version of protobuf and what language are you using?**
HEAD

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

suztomo@suxtomo24:~/protobuf$ docker -v
Docker version 18.09.3, build 774a1f4

**What did you do?**

suztomo@suxtomo24:~/protobuf$ docker build ./kokoro/linux/64-bit

**What did you expect to see**

docker builds a docker image successfully.

**What did you see instead?**

E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

**Anything else we should know about your project / environment**

```
suztomo@suxtomo24:~/protobuf$ docker build ./kokoro/linux/64-bit
Sending build context to Docker daemon  10.24kB
Step 1/59 : FROM debian:latest
 ---> e1de74e67cc7
Step 2/59 : RUN echo 'deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main' > /etc/apt/sources.list.d/deadsnakes.list &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DB82666C
 ---> Running in 7753cc467b2b
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c echo 'deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main' > /etc/apt/sources.list.d/deadsnakes.list &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DB82666C' returned a non-zero code: 255
suztomo@suxtomo24:~/protobuf$ 

```

**Comment by TeBoring** [comment]
Instead of fixing that Dockerfile file, we prefer separating its functionality into several small Dockerfiles.
Feel free to open another issue if you are still interested.
