### ISSUE TITLE
ruby & unknown fields

### ISSUE THREAD

**Issue by djudd-stripe** [protocolbuffers/protobuf#6315]
Is there a way to get the values of unknown fields from a message decoded with the Ruby client? I see some evidence in the source that we store them in an `unknown_fields` value in C but I can't find a Ruby API to access it.

**Comment by haon4** [comment]
@TeBoring who may know more.

**Comment by TeBoring** [comment]
We haven't provided any API to access it. However, it will be kept in the encoding result.
