### ISSUE TITLE
Allow ParseDict bools to be (0, 1)

### ISSUE THREAD

**Issue by jlabarbera11** [protocolbuffers/protobuf#6328]
**What language does this apply to?**
language: python
version: 3.6.1

**Describe the problem you are trying to solve.**
The [_convertBool](https://github.com/protocolbuffers/protobuf/blob/61301f01552dd84d744a05c88af95833c600a1a7/python/google/protobuf/json_format.py#L775) method defined in json_format.py expects a true/false value, either as a string or boolean. However, [flask-restful](https://github.com/flask-restful/flask-restful/blob/f6921bbcc3a392cd92a1381357b5efa069cc55ea/flask_restful/inputs.py#L237-L254) also accepts 0/1 values for boolean fields.

**Describe the solution you'd like**
We would like to expand the functionality of _convertBool to include 0/1 strings/ints as valid inputs.

**Describe alternatives you've considered**

**Additional context**

**Comment by anandolee** [comment]
Thanks for the suggestion, not sure if you still need this feature?
 Are you happy to contribute and send me a PR for review. Close it for now for clean up. Feel free to reopen if still needed

**Comment by zhangskz** [comment]
(FYI, I believe we're unlikely to approve this type of request -- our json parsers already overly-accepts these types of inputs and we are actively looking into reducing some of these odd behaviors).
