### ISSUE TITLE
Compiler errors trying to use parse delimited methods

### ISSUE THREAD

**Issue by ArjunNarayan2066** [protocolbuffers/protobuf#6329]
I am trying to write a routine to receive an encoded size delimited message (created with `SerializeDelimitedToOstream`). It first reads in data into some buffer, then loads that buffer into a `std::stringstream` object. It then loads this into a `IstreamInputStream` object (wrapping a `ZeroCopyStream`). I am trying to implement the functionality to first verify the size is complete in the chunk of data we read, then validate after reading the size that we have enough bytes remaining in the data (else I wait till the next read cycle to get more), and if all good I parse the message. 

I am new to protobufs and am having trouble using the various streams and APIs to implement this. As far as I can tell the only object with a function for `Varint32` parsing is `CodedInputStream`, but reading so pushes the buffer index forward. I tried then using the `ParseDelimitedFrom` methods, but these give nasty compiler errors.

I was wondering what are people's general approach to this kind of design? Ive attached a brief code snippet of what im trying to do.
```cpp
  char buffer[32] = {0};
  size_t bytes = client.read(buffer, 32);

  stringstream ss;
  ss.write(buffer, bytes);
  IstreamInputStream raw(&ss);
  CodedInputStream coded(&raw);

  uint32_t msgsize = 0;
  coded.ReadVarint32(&msgsize);

  SomeMessageType msg;
  bool clean_eof = false;
  ParseDelimitedFromZeroCopyStream(&msg, &raw, &clean_eof);
```
The parse delimited method not only has the incremented index, but also doesn't compile, giving the following error:
```cpp
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/io/zero_copy_stream_impl_lite.cc:252] CHECK failed: backup_bytes_ == 0 && buffer_.get() != NULL:  BackUp() can only be called after Next().
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: backup_bytes_ == 0 && buffer_.get() != NULL:  BackUp() can only be called after Next().
```

Thanks for your help!

**Comment by acozzette** [comment]
I think the proper solution is to implement your own `ZeroCopyInputStream` which contains the logic for reading in chunks of data. That way you won't have to worry about making sure you have enough data before beginning to parse a message.
