### ISSUE TITLE
Non-team members can't apply labels to PRs

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#6332]
CONTIBUTING.md says:

Apply the "release notes: yes" label if the pull request's description should be included in the next release (e.g., any new feature / bug fix). Apply the "release notes: no" label if the pull request's description should not be included in the next release (e.g., refactoring changes that does not change behavior, integration from Google internal, updating tests, etc.)

However as a non-team member I don't seem to have permissions to apply labels.

**Comment by elharo** [comment]
Ping. This is bloxking multiple contribtuions.

**Comment by elharo** [comment]
OK, reread. Looks like the reviewer is supposed to apply the labels. That said, the check seems to block all other checks until the labels are applied.

**Comment by BSBandme** [comment]
Close for now.

Feel free to ping us in the PR if no one respond :)
