### ISSUE TITLE
How to write again to same instance of `CodedInputStream`

### ISSUE THREAD

**Issue by ArjunNarayan2066** [protocolbuffers/protobuf#6334]
I have a `std::stringstream` object I use as an `istream` to init a `ZeroCopyStream` and `CodedInputStream`. The question I have is that I can write to the `std::stringstream` once before I set up the `Stream` objects. However, if I write to it afterwards the stream objects do not update. Is there meant to be a way to do this right?

The context is that I am reading from a TCP socket every few seconds or so, and my class has member instances of the `Stream` objects. Thus I want to read from the socket & update my streams to continue parsing as the class goes along.

I have a simpler (non class) example below that similarly highlights my issue:
```cpp
void test2() {
  stringstream ss;
  ss.write("1234", 4);

  int size = 0;
  const void* buff = NULL;

  IstreamInputStream raw(&ss);
  CodedInputStream coded(&raw);

  if (!coded.GetDirectBufferPointer(&buff, &size)) {
    cout << "1 Failed to get ptr" << endl;
    return;
  }

  cout << "First Write: Size: " << size << endl;

  size = 0;
  buff = NULL;
  ss.write("56789", 5);

  if (!coded.GetDirectBufferPointer(&buff, &size)) {
      cout << "2 Failed to get ptr" << endl;
    return;
  }

  cout << "Second Write: Size: " << size << endl;
}
```

Output:
```
First Write: Size: 4
Second Write: Size: 4
```
The second size should be 9 as the first is 4 and second is 5.

**Comment by ArjunNarayan2066** [comment]
if this is not considered a valid use of this API, how else would you structure it?

**Comment by acozzette** [comment]
The `ZeroCopyInputStream` is the abstraction that is supposed to handle fetching more data for parsing, so I think the proper approach here is to provide your own implementation of `ZeroCopyInputStream` that reads from your TCP socket. See `src/google/protobuf/io/zero_copy_stream_impl.h` for a few examples of `ZeroCopyInputStream` implementations.
