### ISSUE TITLE
segFault when attempting to mock request and response objects.

### ISSUE THREAD

**Issue by paquettg** [protocolbuffers/protobuf#6340]
**What version of protobuf and what language are you using?**
Version: 3.7.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**

Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

Proto-c: libprotoc 3.7.1

I attempted to use Mockery to mock the request and response objects generated by protobuf so that I can implement proper testing. 

**What did you expect to see**

A mocked object which can be used for testing.

**What did you see instead?**

This always leads to a segfault and breaks all tests.

I think this issue is similar (but not the same) as the issue in https://github.com/protocolbuffers/protobuf/issues/4107 but this issue appears to be closed. I attempted to look at the solutions they mentioned, like initialize metadata. but I can't find this option in 3.7.1

**Comment by BSBandme** [comment]
I'm not sure but I think we are not going to make protobuf message mockable.

**Comment by TeBoring** [comment]
We have decided to not support mocking for protobuf message.
Later, we will explicitly make protobuf message final.
If you are currently using mock for protobuf message, please change your code ASAP.

**Comment by paquettg** [comment]
Hey @TeBoring ,

kk, none of the code use mocks for the functional aspect of the code. I would like to know, though, how do you expect people to implement unit tests if we can not create fake messages? The mocks are not for the actual code base, but for testing purposes, if that makes sense.

**Comment by TeBoring** [comment]
Because protobuf messages are simply data object, you can easily create real messages for test.
