### ISSUE TITLE
memory leak in MFC

### ISSUE THREAD

**Issue by playgithub** [protocolbuffers/protobuf#6342]
For a new created dialog based MFC app, it simplely leaks.
But it doesn't leak for a console app without MFC.
What's the problem?

Leak case:

1.  person.proto
```
syntax = "proto3";

message Person
{
    int32 id = 1;
    string name = 2;  
}
```
2. Generates `person.h` and `person.cc`
3. Add the 2 generated files to a project, build, run, functions well, but memory leaks
5. Remove the 2 files from the project, build, run, no memory leaks

> protobuf 3.8.0
> BUILD INFO: MSVC2019 x64 debug

MSVC2019 solution:
[TestProtoBufWithMFC.zip](https://github.com/protocolbuffers/protobuf/files/3359940/TestProtoBufWithMFC.zip)
PS: ReConfig for the dependency of protobuf is needed

**Comment by playgithub** [comment]
`google::protobuf::ShutdownProtobufLibrary();` **NOT HELP**

**Comment by playgithub** [comment]
In version 3.9.0, the bug still exists

**Comment by acozzette** [comment]
@playgithub Feel free to send us a pull request if you have a fix. I suspect this is a case of a global object which is still reachable at program exit, so it is probably nothing to worry about unless you are extra strict about deleting everything created with `new`.

**Comment by playgithub** [comment]
@acozzette I'm new to protobuf. I found the problem in 4th July, protobuf is famous, so I think it might be my problem, and tried to solve it,failed. Now it's August. Though the problem is nothing to worry about, the time can be saved if this problem doesn't exist.

**Comment by MelodyD** [comment]
i have the same problem.

**Comment by zhengw060024** [comment]
I have the same problem.

**Comment by playgithub** [comment]
Wait long enough, it is still not fixed. I'll try Microsoft Bond.
Thanks

**Comment by playgithub** [comment]
@TeBoring @acozzette 
One more reason to fix the memory leak:
Every time I debugging done, the are a lot of leaks (70892 lines in my small project),
the problem is it has become hard to find out if there are other memory leaks other than protobuf.
Thanks
```
Detected memory leaks!
Dumping objects ->
{93267} normal block at 0x000001FF250EC090, 449 bytes long.
 Data: <                > 03 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
......
{5446} normal block at 0x000001FF2339C620, 16 bytes long.
 Data: <  s             > A0 A6 73 F1 FB 7F 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
```

**Comment by playgithub** [comment]
@TeBoring @acozzette
`google::protobuf::ShutdownProtobufLibrary` solves memory leak in the case,
but when debugging, the memory leak infomations still mess up other debug informations.

Thanks

**Comment by playgithub** [comment]
@TeBoring @acozzette 
Another related problem,
I have a common tool lib, call it a.lib, supports somthing like log / string format / ...
When I add probobuf in the lib, then all the projects using a.lib show memory leak infos when debugging, it's disturbing.

Thanks.

**Comment by playgithub** [comment]
Call `google::protobuf::ShutdownProtobufLibrary()` when `DLL_PROCESS_DETACH` solves the problem.

**Comment by harshr094** [comment]
I am also facing the same issue. I have been calling google::protobuf::ShutdownProtobufLibrary() in my code but it ain't working. What is DLL_PROCESS_DETACH here?

**Comment by playgithub** [comment]
> What is DLL_PROCESS_DETACH here?

It's for Windows DLL, it's the place to do things when a dll is being detached from a process.
