### ISSUE TITLE
Add exception handling for gRPC service

### ISSUE THREAD

**Issue by saturnism** [protocolbuffers/protobuf#6347]
**What language does this apply to?**
proto3, java

**Describe the problem you are trying to solve.**
Currently, there is a list of exception handled by
[GrpcStatus](https://github.com/line/armeria/blob/957ecd7b5be9f458aad123ac8ec8283e6331647c/grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java#L63). It would be great to have ability add custom exception mappers, so that we can handle exception like Spring Security's `AccessDeniedException`.

**Describe the solution you'd like**
Something similar too annotated service
https://line.github.io/armeria/server-annotated-service.html#using-serverbuilder-to-configure-converters-and-exception-handlers

**Describe alternatives you've considered**

**Additional context**

**Comment by ST-DDT** [comment]
A) I think this is more of a grpc-java issue than a protobuf issue.
B) You can use `ServerInterceptor`s for this usecase

But it sounds like a useful feature nevertheless.
