### ISSUE TITLE
Dockerfile for openjdk-7-jdk

### ISSUE THREAD

**Issue by suztomo** [protocolbuffers/protobuf#6353]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
The docker file for Java build cannot run because of #6314

**Describe the solution you'd like**
I'll create a Dockerfile for Java 7

**Comment by TeBoring** [comment]
@BSBandme shall we drop support for java7?

**Comment by suztomo** [comment]
I don’t need Java 7 support any more.
