### ISSUE TITLE
Genrated by th protocol buffer Compiler java file doesn't rule Google java Coding Standard

### ISSUE THREAD

**Issue by ghanIn** [protocolbuffers/protobuf#6356]
Why google doesn't rule Google Coding standard?

I love Google Standard!

**Comment by BSBandme** [comment]
We have some pre process before open sourcing the code generator. 
The process may makes code looks a little weird. e.g. indentation may keep after deleting a block..

For making generator to be simple, we didn't spend too much time on that. Feel free to send a PR for cleaning up the generated code, we'll really appreciate it :)
