### ISSUE TITLE
js-field genereted by protoc NOT respect definition in .proto file && always lowercase.

### ISSUE THREAD

**Issue by jmzwcn** [protocolbuffers/protobuf#6357]
Look at "groupId"

message Topic {
  string groupId = 1;
  Message message = 2;
}

-->>
proto.dawn.Topic.toObject = function(includeInstance, msg) {
  var f, obj = {
    groupid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    message: (f = msg.getMessage()) && proto.dawn.Message.toObject(includeInstance, f)
};

this will result in "groupId" always "groupid", being ugly and bad coding practice.

**Comment by TeBoring** [comment]
Sorry, the spec of toObject is not defined yet. We would like to keep the current implementation as is for now.

**Comment by jmzwcn** [comment]
Current implementation is ugly and don't follow camel specification.

**Comment by sorenhoyer** [comment]
I agree. It makes little sense that it does not respect things as defined in the proto.
