### ISSUE TITLE
Enconde a list of maps in protobuf?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [protocolbuffers/protobuf#6359]
Background
-----

I am trying to use protobuff for one of our apps, but I am having trouble understanding the protocol and I need help creating a `.proto` file.

Data
---

The data I need to encode is a list of maps, with the following structure:

    [
      {
        "AwayTeam": "Osasuna",
        "Date": "2017-05-07",
        "Div": "SP1",
        "FTAG": 1,
        "FTHG": 4,
        "FTR": "H",
        "HTAG": 0,
        "HTHG": 2,
        "HTR": "H",
        "HomeTeam": "Valencia",
        "Season": 201617
      },
      {
        "AwayTeam": "Osasuna",
        "Date": "2016-02-27",
        "Div": "SP2",
        "FTAG": 1,
        "FTHG": 0,
        "FTR": "A",
        "HTAG": 0,
        "HTHG": 0,
        "HTR": "D",
        "HomeTeam": "Cordoba",
        "Season": 201516
      }
    ]

Each map has the following structure:

    {
      "AwayTeam": string,  required: true
      "Date":     string,  required: true
      "Div":      string,  required: true
      "FTAG":     integer, required: true
      "FTHG":     integer, required: true
      "FTR":      string,  required: true
      "HTAG":     integer, required: true
      "HTHG":     integer, required: true
      "HTR":      string,  required: true
      "HomeTeam": string,  required: true
      "Season":   integer, required: true
    }

Research
----

My goal is to create .proto file using `proto3`. So I decided to read the documentation for .proto3 files:

https://developers.google.com/protocol-buffers/docs/proto3#maps

But I was even more confused. According to the docs, I cannot have a map holding values of different types: 

- https://developers.google.com/protocol-buffers/docs/proto3#maps

For that I would need the equivalent of the JSON `object` type and check the docs for `.struct.proto` but that page doesn't mention anything about it.

Question
---

So I am rather lost here. How do I represent the mentioned data structure in a `.proto`?

**Comment by acozzette** [comment]
It sounds like you don't actually need the protobuf `map` feature, just a list of messages. I would try something like this:

```
message Game {
  string AwayTeam = 1;
  string HomeTeam = 2;
  ...
}

message GameList {
  repeated Game games = 1;
}
```

**Comment by Fl4m3Ph03n1x** [comment]
I see now, thanks for the feedback!

**Comment by zanderwong** [comment]
what if the map doesnot have a permanent key?  
such as: 

```json
{
  "attrs": [
    {
      "2a23d34af1": "11",
      "1b235b33f1": "tempr"
    },
    {
      "2a23d34af1": "25",
      "1b235b33f1": "tempr"
    },
    {
      "fa23d34ad1": "mark",
      "5b235b33e1": "name"
    },
    {
      "76f3d34aa1": "21.005",
      "1b235b33c1": "lat"
    },
    {
      "25c1d34ab1": "true",
      "552f5c33c1": "sat"
    }
  ]
}

```

I tried edit it like blow, but it's invalid: 

```proto
message Attrs {
	repeated map<string,string> vals = 1;
}
```

**Comment by soaggarwal** [comment]
If map doesn't have fixed key names, you should use -

```
message Attrs {
	ListValue vals = 1;
}
```
