### ISSUE TITLE
Where is the full git log (commit history)?

### ISSUE THREAD

**Issue by ollieparanoid** [protocolbuffers/protobuf#6362]
Hello,

I was debugging a regression with a package that did not build anymore against a more recent protobuf version. A class could not be found anymore. After a quick online search without useful results, I did my usual workflow for investigating these kinds of issues: I've cloned the git repository in question (protobuf), and tried to figure out where the missing code went by looking at the git log of the relevant file.

To my surprise, the git log mostly consists of version bumps, some pull request merges, and then these big, squashed "Down integrate to GitHub" commits like https://github.com/protocolbuffers/protobuf/commit/51026d922970e06475f005b39287963594134b96. This makes the changes in such a squashed commit impossible to understand without investing a huge amount of effort. I was hoping to find some kind of "filename: move class xy to newfilename" commit, with reasoning why this was done. But this kind of commit is probably only available on Google's servers.

My particular issue is resolved now, I've found the file. Nevertheless, this leaves me wondering why development is handled like this, and if there are plans to fix this in the future.

Thanks,
Oliver

**Comment by TeBoring** [comment]
Changes like "Down integrate to GitHub" are integration of our internal code.
AFAIK, those internal changes's description are not mapped to github PR.
@haberman may know better.

**Comment by haberman** [comment]
Yes, unfortunately our current process batches many Google-internal changes into a single GitHub change. We are evaluating alternatives to this, but it may take a while to implement.
