### ISSUE TITLE
OBJC - Converting from GPBMessage to a known message type

### ISSUE THREAD

**Issue by VerTiGoEtrex** [protocolbuffers/protobuf#6364]
I'm an objective-c newb, and trying to understand how I can upcast/convert from a GPBMessage to a user-defined type class. I suppose I could do something like `[MyType parseFromData:gpbMessage.data ...]`, but I'm guessing there's a more "proper" or efficient way to accomplish this.

**Comment by thomasvl** [comment]
Assuming `MyType` is the generated message class, then calling `+parseFromData:...` is exactly the right way to do it.

**Comment by luangaolei** [comment]
Hi, @thomasvl 
How about writing a uniform method?
At this time, we don't know whether the data of the server is MyType or not. How can we know that the data returned by the server can be automatically deserialized into MyType or something else.

**Comment by thomasvl** [comment]
As mentioned in #6429, the binary format does not capture the type.  So you need something beyond the raw binary to know the type.
