### ISSUE TITLE
Cannot get file option extension

### ISSUE THREAD

**Issue by ST-DDT** [protocolbuffers/protobuf#6373]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc embedded as maven plugin / read a proto code generation request from the inputstream

**What did you do?**

* Define a FileOption extion:

````proto
syntax = "proto3";
package example.protobuf;

import "google/protobuf/descriptor.proto";

extend google.protobuf.FileOptions {
	string data_version = 50123;
}

option java_multiple_files = true;
option java_outer_classname = "DataVersionProto";

option (data_version) = "1.0.0";
````

* (Import this file from a different file and) define such an option.
* Run the protoc plugin to get the code generation request
* Parse the input into `PluginProtos.CodeGeneratorRequest`
* Extract the `DescriptorProtos.FileDescriptorProto`
* Extract the `FileOptions`
* Try to access the extension `DataVersionProto.dataVersion`
* Always returns null //<- Unexpected
* `options.getUnknownFields()` contains the extensions.

**What did you expect to see**

`protoFile.getOptions().getExtension(DataVersionProto.dataVersion)` returing the value from the proto file.

**What did you see instead?**

Null. Saving the parsed request back to a file will remove the extension value entirely.

**Comment by ST-DDT** [comment]
This is probably an issue with me not initializing the extension registry properly.

How can I do that correctly?

**Comment by BSBandme** [comment]
I think you need to set an `ExtensionRegistryLite` during parsing input into `CodeGeneratorRequest`
