### ISSUE TITLE
google::protobuf::util::MessageToJsonString generates malformed json string

### ISSUE THREAD

**Issue by xiaoxiuzhe** [protocolbuffers/protobuf#6375]
google::protobuf::util::MessageToJsonString generates malformed json string when message contains google::protobuf::Map and use jsonOptions

example:

google::protobuf::util::JsonOptions jsonOptions;
jsonOptions.always_print_primitive_fields = true;
std::string outputString;
//myMessage contains google::protobuf::Map
google::protobuf::util::MessageToJsonString(myMessage, &outputString, jsonOptions);

**Comment by elharo** [comment]
Language?
