### ISSUE TITLE
go to JSON to c# compatibility issue 

### ISSUE THREAD

**Issue by kzeitz** [protocolbuffers/protobuf#6387]
Version: master/v3.9
Language: go/C#

Linux Ubuntu 18.04.1 LTS, Windows 10 Pro (1809)

Steps...
generated go binding with protoc
generated c# binding with protoc
serialized to JSON using the go binding
attempted to deserialize json file with c# binding (Failed!)
modified json file until deserialization succeeded (diff view included)

I expect this to work without modifying the json.
Deserialization errors caused by the key'ed value used to map fields isn't matching the field name as written out.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

[json_issue.zip](https://github.com/protocolbuffers/protobuf/files/3394547/json_issue.zip)

**Comment by briansorahan** [comment]
More specifically, we have a field named "decl_3mo_liq" in one of our message types.
jsonpb serializes this as "decl3moLiq", but the C# deserializer seems to expect "decl3MoLiq" (capital M).
I tried using [this package](https://github.com/iancoleman/strcase) to convert "decl_3mo_liq" to lower camel case and got "decl3moLiq".
Is this a bug in the C# codegen? It seems like it is converting snake to lower camel incorrectly...

**Comment by anandolee** [comment]
As our style guide says:
"If your field name contains a number, the number should appear after the letter instead of after the underscore. e.g., use song_name1 instead of song_name_1"
https://developers.google.com/protocol-buffers/docs/style#message-and-field-names
