### ISSUE TITLE
AttributeError: 'Timestamp' object has no attribute 'seconds' (well_known_types.py, introduced v3.9.0)

### ISSUE THREAD

**Issue by dhendry** [protocolbuffers/protobuf#6395]
**What version of protobuf and what language are you using?**
Version: v3.9.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Mac 10.14.5

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.7.4

**What did you do?**

This code worked as of protobuf v3.8.0:

```
from datetime import datetime
from google.protobuf.internal.well_known_types import Timestamp

# Datetime str formatter used by google proto Timestamp library
DATETIME_FMT = "%Y-%m-%dT%H:%M:%S.%fZ"

def to_protobuf_timestamp_str(date):
    # The Timestamp does specialized padding on the microseconds when
    # serializeing to strings, so use it in order to match test values
    timestamp = Timestamp()
    timestamp.FromJsonString(date.strftime(DATETIME_FMT))
    return timestamp.ToJsonString()

print(to_protobuf_timestamp_str(datetime.now()))
```

**What did you expect to see**

Printed timestamp, ex: `2019-07-17T09:56:56.601774Z`

**What did you see instead?**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in to_protobuf_timestamp_str
  File "/Users/.../.local/share/virtualenvs/..../lib/python3.7/site-packages/google/protobuf/internal/well_known_types.py", line 190, in FromJsonString
    self.seconds = int(seconds)
AttributeError: 'Timestamp' object has no attribute 'seconds'
```

**Anything else we should know about your project / environment**

* After doing some digging it seems like this problem was caused by the introduction for the `__slots__` attribute (https://github.com/protocolbuffers/protobuf/commit/a1c886834425abb64a966231dd2c9dd84fb289b3#diff-79a29d050e84ff410293a63e1a1551d6R105)
* It seems like I can fix our above code by changing 
  * `from google.protobuf.internal.well_known_types import Timestamp` 
  * to `from google.protobuf.timestamp_pb2 import Timestamp`
* Arguably this is a bug in our code, **however I believe the protobuf bug here is the fact its not at all clear the classes in `well_known_types.py` are actually mixins**, this code worked before and no longer does now, and its not clear what the right thing to do is.
* At a minimum, I suggest: 
  1. Adding comments to these classes to indicate they are mixins and should not be used directly. 
  2. Even better (but possibly more disruptive) would be to explicitly add `Mixin` to their names (eg: `TimestampMixin`) to avoid confusion. Having the mixin classes named exactly the same as the message classes is super confusing.

For those that are curious, it looks like this is the code which does the mixing in: https://github.com/protocolbuffers/protobuf/blob/744e799bdaad748a6069a1f3fe8a25c708317c25/python/google/protobuf/internal/python_message.py#L144-L150

**Comment by anandolee** [comment]
Hi Dan, all classes under internal does not intend to be used directly. Users should not import any module under google.protobuf.internal

**Comment by dhendry** [comment]
@anandolee Feels like adding these comments is an extremely simple way to help others avoid the pain I went through after updating to the most recent protobuf version. Due to the way python imports work, it was not clear from reading our code which broke we were importing the "wrong" thing. I find it unexpected and not user friendly that a library would have identically named classes and not highlight the fact one is not intended to be used directly.

This problem, and my confusion, was exacerbated by the fact protobuf classes are generated dynamically (an unused pattern in our internal codebases, and a generally uncommon pattern in many popular python libraries). Its entirely unclear when looking at timestamp_pb2.py that additional methods get mixed into the class (particularly when this capability is explicitly unavailable for user generated messages).
