### ISSUE TITLE
CSharp Tutorial has typo

### ISSUE THREAD

**Issue by NTaylorMullen** [protocolbuffers/protobuf#6398]
**What version of protobuf and what language are you using?**
Version: v3.9.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
3.9.0 compiler and runtime

**What did you do?**
1. Followed C# tutorial [here](https://developers.google.com/protocol-buffers/docs/csharptutorial).
2. Got to the `The addressbook classes` section
3. Pasted in the first code sample

**What did you expect to see**
No C# runtime compiler error

**What did you see instead?**
C# compiler error:
![image](https://user-images.githubusercontent.com/2008729/61429951-0cf2fa80-a8dd-11e9-850a-120fffc3024a.png)

**Extra**
Investigated why. The generated C# has a Pascal cased `Home` instead of `HOME`. Changing the casing fixes the issue. 
![image](https://user-images.githubusercontent.com/2008729/61430035-7410af00-a8dd-11e9-865b-9efddac839f1.png)

Thought I'd log an issue since it seems to be a tutorial typo 😄 **Also**, looks like the second code snippet has the problem as well.

**Comment by anandolee** [comment]
Thanks to point this out. We will fix the typo
