### ISSUE TITLE
Support extensions for proto2 in Ruby?

### ISSUE THREAD

**Issue by elad-maimon** [protocolbuffers/protobuf#6420]
Hello,

I'm trying to compile proto2 file to Ruby (using "protoc --ruby_out=...") and get this error:
Extensions are not yet supported for proto2 .proto files.

I've found this [issue](https://github.com/protocolbuffers/protobuf/issues/1198) that seems to be related but it's still open (from 2016).

Few questions:
1. Are there any plans to support extensions for proto2 in Ruby?

2. I'm not very familiar with protobuf, but I read that the challenge is to support it in the DSL. Assuming that I don't use these fields of the extensions, is it an option to support telling the compiler to skip it in the generated Ruby models but support encoding to bytes with those fields as empty?

3. More than that, I'm actually only interested in encoding. Is there any way to encode Ruby hash to bytes based on proto definition without having the model in the middle? E.g, something like:
    ```
    encode_to_bytes('Proto.MyTestMessage', { field1: 42 })
    ```
    Instead of:
    ```
    msg = Proto::MyTestMessage.new(field1: 42)
    Proto::MyTestMessage.encode(msg)
    ```

    There's actually a JS tool called [protobuf.js](https://github.com/protobufjs/protobuf.js) that generates a JSON descriptors file from proto file and allows exactly that, so if someone knows of a tool that can encode Ruby hashes to bytes based on JSON descriptors I'd love to hear.

Thanks!

**Comment by TeBoring** [comment]
Sorry that we don't have time to add support for proto2 in ruby now. Is it possible for you to use proto3?

**Comment by elad-maimon** [comment]
No, we have thousands of proto2 files in our company...

Any idea what can be done? Is some of the alternatives I suggested (bullets #2 and #3) viable?

Thanks!

**Comment by TeBoring** [comment]
Sorry for the inconvenience.
For us, we do want to encourage users to use proto3 instead.
Proto3 provide all functions in proto2. Supporting both is an unnecessary burden to us.
Considering our resources, maybe two options are feasible:
1) Migrate proto2 to proto3.
2) Help us to implement proto2.
BTW, proto2 is partially support for ruby. You can check if it's already enough for you.

**Comment by elad-maimon** [comment]
Hi,

As I wrote above, my only problem is with supporting extensions in proto2.

**Comment by krak3n** [comment]
@TeBoring so the current recommendation for "constants" is to use extensions (see #3520). However since this isn't supported by ruby this results in an inconsistent language implementation.
