### ISSUE TITLE
How _should_ source code info look for `default` and `json_name` pseudo-options?

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#6421]
It isn't well-specified exactly how options should look in the source code info for a file.

Prior to #4342, `protoc` emitted fully-structured source code info that mapped back to the AST for uninterpreted options. But interpreted options won't have `path` info that maps to the full AST. In that pull request, it was decided to just emit a single location for the option whose span encompasses the entire option declaration.

However, I've recently discovered that the two pseudo-options for `FieldDescriptorProto` -- `default` and `json_name` -- do not behave this way. Even worse, they are not consistent _with one another_:
* The source code info for `default` emits a span that only encompasses the _actual value_ and omits the `default = ` tokens.
* The source code info for `json_name` emits _two_ locations. The first span encompasses the entire option declaration (including the `json_name = ` tokens). The second span includes only the value.
This is particularly confusing since, for fields, all three of these use the same syntax. So, ideally, they would all be handled consistently.

I'm personally partial to the way options are handled, since I think this best attributes to the path to the span in source code that most logically represents that path. I also believe that would be a trivial patch. And, just from perusing `descriptor.proto`'s doc comments for source code info (which admittedly aren't at all specific for cases like this), I'd sort of guess that this is how it would behave.

However, I can see value in having span information that is only for the value. So I can kind of see why `json_name` is handled the way it is; I just think it's confusing to have two locations with the same path where one span is a sub-span of the other.

I'm happy to contribute a patch to make these consistent. I'd just like some input on what is the _right_ way they should be handled.

**Comment by TeBoring** [comment]
> I'm personally partial to the way options are handled, since I think this best attributes to the path to the span in source code that most logically represents that path.
Sorry, don't understand. Which do you prefer? interpreted option? uninterpreted option?

Also, can you point to me to the context where spanning the whole scope for interpreted option was decided?

**Comment by jhump** [comment]
> Sorry, don't understand. Which do you prefer? interpreted option? uninterpreted option?

Interpreted options. (Uninterpreted options are nice due to the additional AST and location information, but they are not that helpful since they are referring to elements of the descriptor -- e.g. the 999 uninterpreted option tag -- that are not actually present since the act of interpreting options removes them from the descriptor and replaces them with interpreted option fields.)

> Also, can you point to me to the context where spanning the whole scope for interpreted option was decided?

I guess it wasn't really explicit. When I filed the bug and then made the patch, I didn't realize that `default` and `json_name` were handled differently. The only context I can provide is my bug report (#3819) and my patch (#4342).

A downside to only referencing the value, vs. the whole declaration, is that leading and trailing comments are more likely to be for the whole declaration, _not_ just around the value. So I think it's better fidelity and more intuitive to interpret that way, rather than having a span that points only to the value but then comment information that corresponds to more than that (e.g. comments before the `option opt_name =` tokens and those after the `;` token).

**Comment by TeBoring** [comment]
> A downside to only referencing the value, vs. the whole declaration, is that leading and trailing comments are more likely to be for the whole declaration, not just around the value. So I think it's better fidelity and more intuitive to interpret that way, rather than having a span that points only to the value but then comment information that corresponds to more than that (e.g. comments before the option opt_name = tokens and those after the ; token).

But you are talking about interpreted options. Those options are usually well defined in our descriptor.proto. I think comments for those options are more for the value.

**Comment by jhump** [comment]
> I think comments for those options are more for the value.

Right, but having a location whose span start is the position of the _value_ implies (at least to me, from my understanding of the source code info doc comments) that it is the span in source that has the leading and trailing comments. As if it were written like so:

```proto
message Foo {
  option (some.custom.string) = /* leading comment */ "value" /* trailing comment */;

  string bar = 1 [(some.custom.field_string) = /* leading comment */ "value" /* trailing comment */];
}
```

In my mind, the comments should be associated with the correct span in the source file. So I'd expect comments on options to be associated with a span for the whole option, not just the value:

```proto
message Foo {
  // this comment looks to be associated with the span
  // that is line 5, column 3 -> line 5, column 41 due to
  // its location relative to the declaration below.
  option (some.custom.string) = "value";
  // same goes for this trailing comment -- having a
  // span of just columns 33 -> 40 would appear to
  // misattribute this comment
}
```
