### ISSUE TITLE
Add ArraySegment<byte> support on ByteString

### ISSUE THREAD

**Issue by yingnanl** [protocolbuffers/protobuf#6427]
**What language does this apply to? c#
If it's a proto syntax change, is it for proto2 or proto3? no
If it's about generated code change, what programming language? C#

**Describe the problem you are trying to solve.**
Currently ByteString is immuatable. At the same time, 
it introduces memory allocation/copy by ByteString.CopyFrom and ByteString.ToByteArray. I wonder whether ByteString can be constructed by ArraySegment<byte> (without copy) and expose internal data by a ArrarySegment<byte> property or not.

**Describe the solution you'd like**
Instead of private data member bytes, use ArraySegment<byte> instead. In this way, it's up to user to take care of the life-cycle of underlying data. In the case of high performance scenario, users can maintain their own byte array pool since only user knows when to put byte array back to the pool.

public sealed class ByteString : IEnumerable<byte>, IEquatable<ByteString>
{
private readonly ArraySegment<byte> data;

public ByteString(ArraySegment<byte> data)
{
    this.data = data;
}

public ByteString(byte[] bytes)
{
    this.data = new ArraySegment<byte>(bytes);
}

public ArraySegment<byte> Data => this.data;
}

**Describe alternatives you've considered**

**Additional context**

**Comment by yingnanl** [comment]
attached with my draft suggestion for code changes. Please change .txt to .cs.

[ByteString.txt](https://github.com/protocolbuffers/protobuf/files/3419868/ByteString.txt)

**Comment by yingnanl** [comment]
@anandolee , could you please tell me the status of this feature request? Does it make sense to you?

**Comment by soiferj** [comment]
I am also interested in this feature. @anandolee or @TeBoring, is there any progress?
