### ISSUE TITLE
Why the `scratch` argument is here?

### ISSUE THREAD

**Issue by cooljacket** [protocolbuffers/protobuf#6446]
This function's implementation code shows that `scratch` is never used. And I pass in a `nullptr`, the function also works right. So what is the necessity for this argument?

```C++
const std::string& Reflection::GetStringReference(const Message& message,
                                                  const FieldDescriptor* field,
                                                  std::string* scratch)const {
  USAGE_CHECK_ALL(GetStringReference, SINGULAR, STRING);
  if (field->is_extension()) {
    return GetExtensionSet(message).GetString(field->number(),
                                              field->default_value_string());
  } else {
    switch (field->options().ctype()) {
      default:  // TODO(kenton):  Support other string reps.
      case FieldOptions::STRING: {
        if (IsInlined(field)) {
          return GetField<InlinedStringField>(message, field).GetNoArena();
        }

        return GetField<ArenaStringPtr>(message, field).Get();
      }
    }
  }
}
```

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/generated_message_reflection.cc#L1171

**Comment by acozzette** [comment]
In Google's internal version of the codebase we have a couple other ways of storing the string data that we haven't gotten around to open sourcing yet. We can't return those other string formats directly, so we store them in the scratch string and return a reference to that. Sorry about the confusion around this. I think you're right that passing `nullptr` will technically work, but I would recommend passing a real string just be safe--that way if/when we open-source new string types your code will still work properly.
