### ISSUE TITLE
Wrong warning when top-level module name is used in ruby_package option

### ISSUE THREAD

**Issue by south37** [protocolbuffers/protobuf#6450]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: Ruby

```console
$ protoc --version
libprotoc 3.8.0
```

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave 10.14.5

**What runtime / compiler are you using (e.g., python version or gcc version)**

```console
$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

**What did you do?**
1. Write a proto file `messages.proto` with `option ruby_package = "MessagesPb";` as below.

```proto
syntax = "proto3";
package my_company.messages;

option ruby_package = "MessagesPb";

message Message {
  string text = 1;
}
```

2. Run `protoc -I./ --ruby_out=./ messages.proto`.

```console
$ protoc -I./ --ruby_out=./ messages.proto
[libprotobuf WARNING ../../src/google/protobuf/compiler/ruby/ruby_generator.cc:417] ruby_package option should be in the form of: 'A::B::C' and not 'A.B.C'
```

3. Then, You will see a warning message `[libprotobuf WARNING ../../src/google/protobuf/compiler/ruby/ruby_generator.cc:417] ruby_package option should be in the form of: 'A::B::C' and not 'A.B.C'` as above.

**What did you expect to see**
Since `MessagesPb` is a valid module name in Ruby, `protoc` should not output warning messages.

**What did you see instead?**
I saw a warning message such as `[libprotobuf WARNING ../../src/google/protobuf/compiler/ruby/ruby_generator.cc:417] ruby_package option should be in the form of: 'A::B::C' and not 'A.B.C'` .

**Anything else we should know about your project / environment**
This behavior was not seen when I used `protoc v3.7.1`.

```console
$ protoc --version
libprotoc 3.7.1
$ protoc -I./ --ruby_out=./ messages.proto  # No warning
```

I think this behavior was added in [Fix Ruby module name generation when the ruby_package option is used (again) #5794](https://github.com/protocolbuffers/protobuf/pull/5794).

In ruby_generator.cc, the presence of `::` is checked. This is an invalid behavior, because the top-level module name does not contain `::` in Ruby.

https://github.com/protocolbuffers/protobuf/blob/09745575a923640154bcf307fba8aedff47f240a/src/google/protobuf/compiler/ruby/ruby_generator.cc#L410-L419

**Comment by haberman** [comment]
This was fixed in https://github.com/protocolbuffers/protobuf/pull/7276.
