### ISSUE TITLE
Protocol buffers undefined reference

### ISSUE THREAD

**Issue by Rikkard29** [protocolbuffers/protobuf#6452]
Hello,

I am developing a game server in C++ using Ubuntu 18.04 LTS and I decided to use Protocol buffers for serialization however I am not able to build my project.

I am using CMake and protobuf version 3.9.0. Here is what my CMakeLists.txt looks like.

`cmake_minimum_required(VERSION 3.5)

set (CMAKE_CXX_STANDARD 11)

project(testik)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake")

file(GLOB SOURCES "src/*.cpp")
file(GLOB PROTOSOURCES "src/protos/*.cc")

add_executable(testik ${SOURCES} ${PROTOSOURCES})

include_directories ("${CMAKE_SOURCE_DIR}/include")
include_directories ("${CMAKE_SOURCE_DIR}/src/protos")

add_definitions(-DBOOST_ALL_NO_LIB)

find_package(Boost COMPONENTS system filesystem REQUIRED)
find_package(ENet REQUIRED)
find_package(Protobuf REQUIRED)
find_package(LibWebRTC REQUIRED)

include_directories(${Boost_INCLUDE_DIRS})
include_directories(${ENET_INCLUDE_DIRS})
include_directories(${Protobuf_INCLUDE_DIRS})

link_directories(${Boost_LIBRARY_DIRS})

target_link_libraries(testik
    ${Boost_FILESYSTEM_LIBRARY}
    ${Boost_SYSTEM_LIBRARY}
    ${ENET_LIBRARIES}
    ${Protobuf_LIBRARIES}
    ${LIBWEBRTC_LIBRARIES}
)

include(${LIBWEBRTC_USE_FILE})

install(TARGETS testik DESTINATION bin)
`
I am using WebRTC for networking. There is maybe some sort of conflict between WebRTC and Protocol buffers but I don't know how to solve it.

I have tried removing libprotobuf from system and reinstalling but no success.

I would really appreciate your help guys. Thanks.

Build log:
`[ 74%] Linking CXX executable testik
CMakeFiles/testik.dir/src/EntitySerializer.cpp.o: In function `google::protobuf::internal::GetEmptyStringAlreadyInited()':
/usr/local/include/google/protobuf/message_lite.h:154: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
CMakeFiles/testik.dir/src/protos/InitMsg.pb.cc.o: In function `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliased(unsigned int, std::string const&, unsigned char*)':
/usr/local/include/google/protobuf/io/coded_stream.h:717: undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::string const&, unsigned char*)'
collect2: error: ld returned 1 exit status
CMakeFiles/testik.dir/build.make:1112: recipe for target 'testik' failed
make[3]: *** [testik] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/testik.dir/all' failed
make[2]: *** [CMakeFiles/testik.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/testik.dir/rule' failed
make[1]: *** [CMakeFiles/testik.dir/rule] Error 2
Makefile:164: recipe for target 'testik' failed
make: *** [testik] Error 2
`

**Comment by acozzette** [comment]
Could you post the linker command that 's failing?

**Comment by Rikkard29** [comment]
I typed "make" in to the terminal.

**Comment by acozzette** [comment]
But make is ultimately calling the linker. What linker command is failing?

**Comment by Rikkard29** [comment]
What do you mean by that?

Here is the full log. It fails after saying linking executable:

`Scanning dependencies of target testik
[  1%] Building CXX object CMakeFiles/testik.dir/src/Bullet.cpp.o
[  2%] Building CXX object CMakeFiles/testik.dir/src/CharacterBehaviour.cpp.o
[  4%] Building CXX object CMakeFiles/testik.dir/src/Circle.cpp.o
[  5%] Building CXX object CMakeFiles/testik.dir/src/ClientConnection.cpp.o
[  7%] Building CXX object CMakeFiles/testik.dir/src/Collider.cpp.o
[  8%] Building CXX object CMakeFiles/testik.dir/src/CollisionDetector.cpp.o
[ 10%] Building CXX object CMakeFiles/testik.dir/src/Config.cpp.o
[ 11%] Building CXX object CMakeFiles/testik.dir/src/Container.cpp.o
[ 12%] Building CXX object CMakeFiles/testik.dir/src/DamageBehaviour.cpp.o
[ 14%] Building CXX object CMakeFiles/testik.dir/src/Damageable.cpp.o
[ 15%] Building CXX object CMakeFiles/testik.dir/src/EnetClientConnection.cpp.o
[ 17%] Building CXX object CMakeFiles/testik.dir/src/EnetServer.cpp.o
[ 18%] Building CXX object CMakeFiles/testik.dir/src/Entity.cpp.o
[ 20%] Building CXX object CMakeFiles/testik.dir/src/EntityFactory.cpp.o
[ 21%] Building CXX object CMakeFiles/testik.dir/src/EntitySerializer.cpp.o
[ 22%] Building CXX object CMakeFiles/testik.dir/src/EntitySpawner.cpp.o
[ 24%] Building CXX object CMakeFiles/testik.dir/src/Food.cpp.o
[ 25%] Building CXX object CMakeFiles/testik.dir/src/GameArena.cpp.o
[ 27%] Building CXX object CMakeFiles/testik.dir/src/GameMasterServer.cpp.o
[ 28%] Building CXX object CMakeFiles/testik.dir/src/Guardian1.cpp.o
[ 30%] Building CXX object CMakeFiles/testik.dir/src/Guardian2.cpp.o
[ 31%] Building CXX object CMakeFiles/testik.dir/src/GuardianHouse.cpp.o
[ 32%] Building CXX object CMakeFiles/testik.dir/src/HedgehogBehaviour.cpp.o
[ 34%] Building CXX object CMakeFiles/testik.dir/src/LizardBehaviour.cpp.o
[ 35%] Building CXX object CMakeFiles/testik.dir/src/LizardBullet.cpp.o
[ 37%] Building CXX object CMakeFiles/testik.dir/src/Log.cpp.o
[ 38%] Building CXX object CMakeFiles/testik.dir/src/MasterServer.cpp.o
[ 40%] Building CXX object CMakeFiles/testik.dir/src/Math2.cpp.o
[ 41%] Building CXX object CMakeFiles/testik.dir/src/MoveToPointBehaviour.cpp.o
[ 42%] Building CXX object CMakeFiles/testik.dir/src/MoveWithDeltaBehaviour.cpp.o
[ 44%] Building CXX object CMakeFiles/testik.dir/src/MovingBehaviour.cpp.o
[ 45%] Building CXX object CMakeFiles/testik.dir/src/Mutagen.cpp.o
[ 47%] Building CXX object CMakeFiles/testik.dir/src/NetConnection.cpp.o
[ 48%] Building CXX object CMakeFiles/testik.dir/src/NetworkEventManager.cpp.o
[ 50%] Building CXX object CMakeFiles/testik.dir/src/Obstacle.cpp.o
[ 51%] Building CXX object CMakeFiles/testik.dir/src/Player.cpp.o
[ 52%] Building CXX object CMakeFiles/testik.dir/src/RandomNumberGenerator.cpp.o
[ 54%] Building CXX object CMakeFiles/testik.dir/src/Rect.cpp.o
[ 55%] Building CXX object CMakeFiles/testik.dir/src/ScaleEditor.cpp.o
[ 57%] Building CXX object CMakeFiles/testik.dir/src/SharedConfig.cpp.o
[ 58%] Building CXX object CMakeFiles/testik.dir/src/SnakeBehaviour.cpp.o
[ 60%] Building CXX object CMakeFiles/testik.dir/src/TurtleBehaviour.cpp.o
[ 61%] Building CXX object CMakeFiles/testik.dir/src/Vector2.cpp.o
[ 62%] Building CXX object CMakeFiles/testik.dir/src/WebRTCClientConnection.cpp.o
[ 64%] Building CXX object CMakeFiles/testik.dir/src/WebRTCServer.cpp.o
[ 65%] Building CXX object CMakeFiles/testik.dir/src/main.cpp.o
[ 67%] Building CXX object CMakeFiles/testik.dir/src/protos/BulletSpawnMsg.pb.cc.o
[ 68%] Building CXX object CMakeFiles/testik.dir/src/protos/BulletUpdateMsg.pb.cc.o
[ 70%] Building CXX object CMakeFiles/testik.dir/src/protos/ColliderMsg.pb.cc.o
[ 71%] Building CXX object CMakeFiles/testik.dir/src/protos/DespawnMsg.pb.cc.o
[ 72%] Building CXX object CMakeFiles/testik.dir/src/protos/EntityMsg.pb.cc.o
[ 74%] Building CXX object CMakeFiles/testik.dir/src/protos/FoodSpawnMsg.pb.cc.o
[ 75%] Building CXX object CMakeFiles/testik.dir/src/protos/Guardian1SpawnMsg.pb.cc.o
[ 77%] Building CXX object CMakeFiles/testik.dir/src/protos/Guardian2SpawnMsg.pb.cc.o
[ 78%] Building CXX object CMakeFiles/testik.dir/src/protos/GuardianHouseSpawnMsg.pb.cc.o
[ 80%] Building CXX object CMakeFiles/testik.dir/src/protos/GuardianHouseUpdateMsg.pb.cc.o
[ 81%] Building CXX object CMakeFiles/testik.dir/src/protos/HealthStateMsg.pb.cc.o
[ 82%] Building CXX object CMakeFiles/testik.dir/src/protos/InitMsg.pb.cc.o
[ 84%] Building CXX object CMakeFiles/testik.dir/src/protos/InitResponseMsg.pb.cc.o
[ 85%] Building CXX object CMakeFiles/testik.dir/src/protos/InputMsg.pb.cc.o
[ 87%] Building CXX object CMakeFiles/testik.dir/src/protos/MutagenSpawnMsg.pb.cc.o
[ 88%] Building CXX object CMakeFiles/testik.dir/src/protos/ObstacleSpawnMsg.pb.cc.o
[ 90%] Building CXX object CMakeFiles/testik.dir/src/protos/PlayerMsg.pb.cc.o
[ 91%] Building CXX object CMakeFiles/testik.dir/src/protos/PlayerSpawnMsg.pb.cc.o
[ 92%] Building CXX object CMakeFiles/testik.dir/src/protos/PlayerUpdateMsg.pb.cc.o
[ 94%] Building CXX object CMakeFiles/testik.dir/src/protos/SimpleEventMsg.pb.cc.o
[ 95%] Building CXX object CMakeFiles/testik.dir/src/protos/SpawnMsg.pb.cc.o
[ 97%] Building CXX object CMakeFiles/testik.dir/src/protos/UpdateMsg.pb.cc.o
[ 98%] Building CXX object CMakeFiles/testik.dir/src/protos/WrapperMsg.pb.cc.o
[100%] Linking CXX executable testik
CMakeFiles/testik.dir/src/EntitySerializer.cpp.o: In function `google::protobuf::internal::GetEmptyStringAlreadyInited()':
EntitySerializer.cpp:(.text._ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv[_ZN6google8protobuf8internal27GetEmptyStringAlreadyInitedEv]+0x7): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
CMakeFiles/testik.dir/src/protos/InitMsg.pb.cc.o: In function `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliased(unsigned int, std::string const&, unsigned char*)':
InitMsg.pb.cc:(.text._ZN6google8protobuf2io19EpsCopyOutputStream23WriteStringMaybeAliasedEjRKSsPh[_ZN6google8protobuf2io19EpsCopyOutputStream23WriteStringMaybeAliasedEjRKSsPh]+0x9b): undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::string const&, unsigned char*)'
collect2: error: ld returned 1 exit status
CMakeFiles/testik.dir/build.make:1871: recipe for target 'testik' failed
make[2]: *** [testik] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/testik.dir/all' failed
make[1]: *** [CMakeFiles/testik.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by acozzette** [comment]
If you run `make VERBOSE=1` it should print out all the commands being executed.

**Comment by Rikkard29** [comment]
It was conflict between protobuf and libwebrtc. It is solved. Thanks
