### ISSUE TITLE
compiling libprotobuf.so with different name to avoid name collison with protobuf2

### ISSUE THREAD

**Issue by vnagineni** [protocolbuffers/protobuf#6456]
In my system I have protobuf2 already built, which is named as libprotobuf.so file. While compiling the latest one (version 3.6), it is also generating the libprotobuf.so file and I wanted to use both the old one and the new one. So while compiling the new library I wanted to have the SO file named as libprotobuf3.so. What setting should I change in configure.ac to get libprotobuf3.so (instead of libprotobuf.so)?

Thank you,
Venkata

**Comment by acozzette** [comment]
Unfortunately that will not work. Linking against two copies of libprotobuf.so will result in ODR (one-definition rule) violations and cause problems. Instead I would recommend rebuilding your .proto files with protoc 3.6 and then linking against libprotobuf 3.6 only. For C++ we require the protoc version to match the libprotobuf version.

**Comment by vnagineni** [comment]
But I see that there are no symbol collisons in libprotobuf.so file built with protobuf 2 and protobuf 3. So we can compile a binary with both libraries. right?

**Comment by acozzette** [comment]
I would expect there to be symbol collisions for sure. When we bumped the version to 3.0 we didn't make any effort to rename symbols. Why do you want to link against two versions anyway?

**Comment by vnagineni** [comment]
I have one question Adam. 
1. If we have messages which are encoded with protobuf2 (libprotobuf.so), and if we try to use protobuf3 in decoder, does it work?
2. Similarly if we encode with protobuf3 and if we decode with protobuf2 in decoder does it work?

**Comment by acozzette** [comment]
There are two completely separate things here: the protobuf version (e.g. 3.6) and the syntax line in the .proto file (i.e. `syntax = "proto2"` or `syntax = "proto3"`. Upgrading to newer protobuf versions is completely safe and wire-compatible and is a good idea because it will include new features, bug fixes, etc. Changing the `syntax` line is more complicated and I wouldn't recommend doing it if you don't need to.

**Comment by vnagineni** [comment]
Hi Adam,

you are saying protobuf3 is wore-compatible. Is it both forward and backward compatible? (If we encode in protobuf3, can we decode with protobuf2 libprotobuf.so files)?

Thanks
Venkata

**Comment by acozzette** [comment]
When you upgrade your protobuf version, everything is forward and backward compatible. But don't change from `syntax = "proto2"` to `syntax = "proto3"` unless you know what you're doing, because that is not entirely compatible.
