### ISSUE TITLE
Add C# option to generate constructor for messages

### ISSUE THREAD

**Issue by pnarimani** [protocolbuffers/protobuf#6457]
Currently all C# messages are generated without constructors. If you want to initialize a message, you can use object initialization pattern in C#. 

What I'm suggesting is an option to generate constructors for messages.
Take a look at this message (It's from a shooter game):
```
syntax = "proto3";
package ProtoMessages;

message Vec3
{
	float x = 1;
	float y = 2;
	float z = 3;
}

message Raycast
{
    Vec3 origin = 1;
    Vec3 hitPoint = 2;
    int32 hitPlayerID = 5;
    float interpolationTime = 6;
}
```

Currently you have to initialize this like this:
```
var raycast = new Raycast
{
    Origin = new Vec3 { X = 10, Y = 20, Z = 30 },
    HitPoint = new Vec3 { X = 20, Y = 10, Z = 5 },
    HitPlayerID = 5,
    InterpolationTime = 100
}
```

But if `Raycast` and `Vec3` messages had constructors, it was possible to do it like this:
```
var raycast = new Raycast(new Vec3(10, 20, 30), new Vec3(20, 10, 5), 5, 100);
```
Which is much shorter. 

You might think that the current version (without constructors) is better because it is clear and explicit which value is assigned to which field. But in real scenarios, we are not using literals to assign values. So that's not a problem.

Also, this must be an option. No one wants a constructor for a message that contains 10+ fields. 

Best Regards.

**Comment by ObsidianMinor** [comment]
You can also define your own constructors by adding onto the partial class.

ProtoMessages.cs
```cs
public partial class Raycast
{
    // generated code
}
```
ProtoMessages.partial.cs
```cs
public partial class Raycast
{
    public Raycast(/* define constructor manually */) { }
}
```

**Comment by mnarimani** [comment]
Yes but maintaining these constructors will be a pain. Specially if you have a lot of messages.

**Comment by colotiline** [comment]
@pnarimani same here, but proto3 made all fields optional. 

How can you generate a constructor when you can't know which fields are required?
