### ISSUE TITLE
Is there has great performance improve from version 3.7.0 to 3.9.0 about php c extension?

### ISSUE THREAD

**Issue by foamzou** [protocolbuffers/protobuf#6459]
I make an Apache Benchmark test. 
`ab -n100000000 -c20 "http://test"`
php env: 7.3.0

Will be serialize and unserialize protobuf object per http request
Code:
```
class TestProto
{
    public function run()
    {
        $response = new \ProtoEntity\GetUserInfoResponse();
        $text = file_get_contents(__DIR__ . '/data/proto_response_small.txt');
        $response->mergeFromString($text);
        $response = $response->serializeToString();
        echo $response;
    }
}
```
Use protobuf.so(3.7.0): QPS is 600+
Use protobuf.so(3.9.0): QPS is 1100+

I stat cost time in `new obj`, `merge` and `serialize`. Found cost time is less in `new object`
3.7.0
```
[new object]	 cost:1.971960067749ms
[merge to obj]	 cost:0.05793571472168ms
[serialize]	 cost:0.042915344238281ms
```
3.9.0
```
[new object]	 cost:1.2741088867188ms
[merge to obj]	 cost:0.066995620727539ms
[serialize]	 cost:0.036954879760742ms
```

The performance improve is so large after upgrade to 3.9.0.

Is there has great improve? I does not found the change log about performance improve.

Thanks for any reply.

**Comment by TeBoring** [comment]
@haberman 
We had a refactoring for upb underlying.
