### ISSUE TITLE
[C++] MessageToJsonString discards the fields containing 0th enum element in proto3, works fine in proto2..

### ISSUE THREAD

**Issue by gozdekos** [protocolbuffers/protobuf#6462]
**What version of protobuf and what language are you using?**
Version: libprotobuf-dev 3.0.0-9.1ubuntu1 amd64
Language: C++
**What operating system (Linux, Windows, ...) and version?**
Ubuntu Bionic Beaver 18.04
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 7.4.0
**What did you do?**
MessageToJsonString function does not convert the fields that contain an enum's 0th element for proto3 messages. It works fine for proto2.

For example, this code block,
MyMessage msg;

msg.set_angle1(MyMessage_Angle_FRONT);
msg.set_angle2(MyMessage_Angle_REAR);
msg.set_angle3(MyMessage_Angle_FRONT);

std::string jsonstr;
google::protobuf::util::MessageToJsonString(msg, &jsonstr);
std::cout << jsonstr;

outputs {"angle1":"FRONT","angle2":"REAR","angle3":"FRONT"} for this proto2 message:
syntax = "proto2";
message MyMessage {
	enum Angle{
		FRONT	= 0;
		REAR	= 1;
	}
	required Angle angle1 = 1;
	required Angle angle2 = 2;
	required Angle angle3 = 3;
}

and outputs {"angle2":"REAR"} for this proto3 message:
syntax = "proto3";
message MyMessage {
	enum Angle{
		FRONT	= 0;
		REAR	= 1;
	}
	Angle angle1 = 1;
	Angle angle2 = 2;
	Angle angle3 = 3;
}
**What did you expect to see**
{"angle1":"FRONT","angle2":"REAR","angle3":"FRONT"}
**What did you see instead?**
{"angle2":"REAR"}
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
This is actually the intended behavior. In proto3 there is no distinction between a field being set to its default value (i.e. 0 in this case) and not being set at all. An enum field set to 0 is the same thing as an unset enum field. If you do want to print out zero-valued fields, you can set `always_print_primitive_fields` [here](https://github.com/protocolbuffers/protobuf/blob/d1eeb852fcbe46b29a3bc47001e997d79358d9f8/src/google/protobuf/util/json_util.h#L75).
