### ISSUE TITLE
protoc doesn't generate custom message options in Ruby

### ISSUE THREAD

**Issue by kleinron** [protocolbuffers/protobuf#6475]
**What version of protobuf and what language are you using?**
Version: master
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
```
Linux a9123c5e218c 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**What runtime / compiler are you using (e.g., python version or gcc version)**
not relevant to this issue

**What did you do?**
1. Create a file named `service.proto`, with the following contents:
```
syntax = "proto3";

package foo.bar.v1;

option objc_class_prefix = "WBI";

import "google/protobuf/timestamp.proto";
import "google/protobuf/descriptor.proto";

message MyMeta {
    string msg_schema_name = 1;
}

extend google.protobuf.MessageOptions {
    MyMeta meta = 1234;
}

message Something {
    option (meta) = { msg_schema_name: "seat-belt" };
    string dog_name = 1;
    string cat_name = 2;
    google.protobuf.Timestamp created_at = 3;
}

message Person {
    option (meta) = { msg_schema_name: "pencil-case" };
    string first_name = 1;
    string last_name = 2;
    google.protobuf.Timestamp created_at = 3;
}
```
2. create a directory named `out/python` (`mkdir -p out/python`)
3. run the following:
```
protoc service.proto --proto_path=./ --python_out=./out/python
```
4. The generated code includes the descriptor (look for "seat-belt" and "pencil-case" in the generated code).
5. create a directory named `out/ruby` (`mkdir -p out/ruby`)
6. run the following:
```
protoc service.proto --proto_path=./ --ruby_out=./out/ruby
```
7. The generated code **does not** include the descriptor (look for "seat-belt" and "pencil-case" in the generated code).

**What did you expect to see**
I expected to see Ruby generated code with the equivalent functionality as the one provided in Python generated.

**What did you see instead?**
missing functionality.

**Anything else we should know about your project / environment**
There has been a recent fix for a related issue: #6369

**Comment by TeBoring** [comment]
Custom option is still not supported. Fix in #6369 only avoid the compiling error.
