### ISSUE TITLE
Parse my rpc request costs a lot of time

### ISSUE THREAD

**Issue by gxkevin** [protocolbuffers/protobuf#6476]
Hi, I am using the protobuf 3 in the brpc, but the google::protobuf::MessageLite::ParseFromCodedStream cost a lot of time. I did't know why, the request is not very large, almost 200-300k.

The attachment is the Flamegraph.
[perf-kernel.zip](https://github.com/protocolbuffers/protobuf/files/3465854/perf-kernel.zip)

**Comment by gxkevin** [comment]
the protobuf version is 3.5.1

**Comment by gxkevin** [comment]
I  have tried the Arena, but it did't work.

**Comment by gxkevin** [comment]
@TeBoring @acozzette  @thomasvl

**Comment by acozzette** [comment]
I don't think there is any easy answer to this question--you will have to spend some time profiling brpc and look for optimization opportunities. On the protobuf team we have never worked with brpc and so we don't really have any specific advice for it. I would expect arenas to help, but you have to be careful to make your code arena-friendly (e.g. make sure you're not copying data on and off the arena unnecessarily).
