### ISSUE TITLE
MessageToJsonString outputs result is random when message contains map.

### ISSUE THREAD

**Issue by wangkirin** [protocolbuffers/protobuf#6478]
**What version of protobuf and what language are you using?**
Version: v3.9.0.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux (Ubuntu)
**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 
**What did you do?**
test.proto
```
syntax = "proto3";

message MyMessage {
  map<string,sint32> myMap = 1;
}
```
Compile with ```protoc   -I=./    --cpp_out=./     test.proto.```

main.cc
```C++
#include <iostream>
#include "test.pb.h"
#include <google/protobuf/util/json_util.h>

int main()
{
  MyMessage msg;

  msg.mutable_mymap()->insert({"aa",1});
  msg.mutable_mymap()->insert({"bb",2});
  msg.mutable_mymap()->insert({"cc",3});
  msg.mutable_mymap()->insert({"dd",4});
  msg.mutable_mymap()->insert({"ee",5});

  std::string jsonstr;
  google::protobuf::util::MessageToJsonString(msg, &jsonstr);

  std::cout<< jsonstr <<std::endl;

  return 0;
}
```
Compile with  ```g++ -std=c++11 test.pb.cc main.cc -o test  `pkg-config --cflags --libs protobuf` ```.
**What did you expect to see**
A fixed result like STL's map:  ``` {"myMap":{"aa":1,"bb":2,"cc":3,"dd":4,"ee":5}}  ```
**What did you see instead?**
The results of each run are different :  
``` 
first run:  {"myMap":{"ee":5,"aa":1,"dd":4,"cc":3,"bb":2}}
second run:  {"myMap":{"cc":3,"bb":2,"ee":5,"aa":1,"dd":4}}
third run:  {"myMap":{"bb":2,"ee":5,"aa":1,"dd":4,"cc":3}}
...
```
It seems that the map's order is random.  Is there any methods to let it works like STL's map ? 
**Anything else we should know about your project / environment**
nothing special.

**Comment by acozzette** [comment]
This is actually working as intended, because protobuf map fields are logically unordered, similar to `std::unordered_map` in C++. There is no option to produce sorted output in JSON, though if you really need it to be sorted then you could potentially sort map fields in the JSON afterward.
