### ISSUE TITLE
Release v3.9.1 broke Bazel builds due to workspace-level `@//:six.BUILD` label

### ISSUE THREAD

**Issue by jmillikin-stripe** [protocolbuffers/protobuf#6485]
PR https://github.com/protocolbuffers/protobuf/pull/6438 backported some Bazel dependency fixes to the 3.9 branch, but in doing so it broke the build for workspaces that consume Protobuf as a dependency.

The dependency definition for `@six`:
```python
        http_archive(
            name = "six",
            build_file = "@//:six.BUILD",
            sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
            urls = ["https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55"],
        )
```

references a `build_file` target relative to the top-level workspace. It probably should have been `build_file = "@com_google_protobuf//:six.BUILD",` instead.

**Comment by TeBoring** [comment]
We will have a 3.10.0 release next week

**Comment by rohansingh** [comment]
Just a bump, this is still broken. I'm also wondering if there's a meta-issue here, since a few releases have broken downstream projects that use Bazel as a dependency. Would it be possible to add an integration test to prevent this from happening in the future?

**Comment by elharo** [comment]
assume this is fixed now
