### ISSUE TITLE
Binaries for s390x architecture

### ISSUE THREAD

**Issue by Nayana-ibm** [protocolbuffers/protobuf#6486]
We could see there are binaries available Intel and ppc.  Will it be possible to provide binary for s390x?
Please let us know if you need any assistance.

**Comment by TeBoring** [comment]
We need to set up a automated toolchain using docker.
https://github.com/protocolbuffers/protobuf/tree/master/kokoro/release/protoc
@acozzette do we want to provide that?

**Comment by acozzette** [comment]
Sure, while we don't have any experience with s390x, we could probably release binaries for it if someone provided us with the Docker setup. We would need a Docker image with the proper toolchain and a script for building protoc with that toolchain. @Nayana-ibm Let us know if you are interested in contributing that.

**Comment by Nayana-ibm** [comment]
@acozzette Sure . Will work on toochain. 
Thanks for inputs.

**Comment by salamaniibm** [comment]
@acozzette Thanks for reviewing and merging #6558
Any information on when I can get the s390x binary?

**Comment by acozzette** [comment]
I believe this should make it into the 3.10 release which is in progress.

**Comment by Nayana-ibm** [comment]
The binary is available for s390x: https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc1/protoc-3.10.0-rc-1-linux-s390x_64.zip. 

However it fails with an error : `./protoc: cannot execute binary file: Exec format error`

Tracking through https://github.com/protocolbuffers/protobuf/issues/6625. Closing this one.
