### ISSUE TITLE
PHP C Extension Segfaults

### ISSUE THREAD

**Issue by notian** [protocolbuffers/protobuf#6488]
**What version of protobuf and what language are you using?**
PHP 7.2.21 (cli)
protobuf (C Extension)
Version => 3.9.0

**What operating system (Linux, Windows, ...) and version?**
CentOS 6

**What runtime / compiler are you using (e.g., python version or gcc version)**
php 7.2.21

**What did you do?**
```
pecl install protobuf

$ php -a
Interactive shell

php > $test = new Google\Protobuf\StringValue(['test']);
Segmentation fault (core dumped)

$ php -a
Interactive shell

php > $test = new Google\Protobuf\StringValue();
php > $test->setValue('test');
php > var_dump( $test );
Segmentation fault (core dumped)
```

**What did you expect to see**
Not a segfault

**What did you see instead?**
A segfault

**Comment by TeBoring** [comment]
1) you syntax is incorrect: ```new Google\Protobuf\StringValue(['value' => 'test']);```
2) this should have been fixed in https://github.com/protocolbuffers/protobuf/pull/6483. Will be released in 3.10.0
3) var_dump didn't work with c extension. Although it doesn't cause segfault now, but it still print nothing.
