### ISSUE TITLE
Cannot find protobuf runtime installation instructions for Java

### ISSUE THREAD

**Issue by JFan2016** [protocolbuffers/protobuf#6494]
Hi I am following the instructions to install protobuff to use with Java. The readme points me to the corresponding source directory about how to install protobuf for Java. This new readme then points me back to the previous readme for installation instructions. How do I install for Java?

**Comment by acozzette** [comment]
The Java readme refers to the top-level readme for instructions on building or downloading `protoc`, the protocol compiler. So the idea is to first get ahold of `protoc` and then continue with the Java-specific instructions.
