### ISSUE TITLE
Ruby JSON deserialization fails for Int64Value and UInt64Value

### ISSUE THREAD

**Issue by martinxsliu** [protocolbuffers/protobuf#6498]
**What version of protobuf and what language are you using?**
Version: 3.9.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
OS X

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

**What did you do?**
Decode a JSON encoded message with an Int64Value or an UInt64Value field. The canonical JSON encoding for wrapper types is the same as the wrapped primitive, which in the case of int64 and uint64 is a string.
```rb
> MyMessage.decode_json('{"int64value": "123"}')
```

**What did you expect to see**
A decoded protobuf object with the `int64value` field set:
```rb
<MyMessage: int64value: <Google::Protobuf::Int64Value: value: 123>>
```

**What did you see instead?**
```
Google::Protobuf::ParseError: Error occurred during parsing: String specified for bool or submessage field: int64value
```

**Anything else we should know about your project / environment**
1. Decoding will work if the JSON value is a number instead of a string. e.g.
```rb
> MyMessage.decode_json('{"int64value": 123}')
```
2. Decoding a JSON string where the wrappers are represented as a nested object instead of a nullable primitive works. (See: https://github.com/protocolbuffers/protobuf/issues/3013) e.g.
```rb
> MyMessage.decode_json('{"int64value": {"value": "123"}}')
```
3. Decoding Int32Value and UInt32Value works because 32bit ints' JSON representations are numbers.

**Comment by carsol** [comment]
Hello! 👋 
I'm having this issue also. Has there been progress on this?

**Comment by gabetax** [comment]
I expect this is intentional behavior.

JSON spec doesn't set limits on the range of its numeric types. It's common to default to what's supported by Javascript. Javascript surprisingly doesn't have an integer type, only a Float type, and it loses precision after 2^53 (for fun, open a web console and try `2 ** 53 == 2 ** 53 +1`. Because of this, it's pretty common to use strings when encoding int64. For example, see twitter's documentation on its ids: https://developer.twitter.com/en/docs/basics/twitter-ids

https://tools.ietf.org/html/rfc7159#section-6 says

>    This specification allows implementations to set limits on the range
>    and precision of numbers accepted.  Since software that implements
>    IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
>    generally available and widely used, good interoperability can be
>    achieved by implementations that expect no more precision or range
>    than these provide, in the sense that implementations will
>    approximate JSON numbers within the expected precision.  A JSON
>    number such as 1E400 or 3.141592653589793238462643383279 may indicate
>    potential interoperability problems, since it suggests that the
>    software that created it expects receiving software to have greater
>    capabilities for numeric magnitude and precision than is widely
>    available.
> 
>    Note that when such software is used, numbers that are integers and
>    are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
>    sense that implementations will agree exactly on their numeric
>    values.
> 
>

**Comment by vitorrd** [comment]
Hello.

This issue is still ongoing. Protobuf fails to decode large numbers, which in JSON are encoded as strings, back into numbers. This is a rather serious problem as languages like Ruby make extensive use of non-JSON-compliant numbers.

Thanks in advance.

**Comment by haberman** [comment]
This should be fixed by https://github.com/protocolbuffers/protobuf/pull/8184, which is part of the v3.15.0-rc1 pre-release.

Please try it out and let us know if it doesn't work for you.
