### ISSUE TITLE
How to generate any.proto

### ISSUE THREAD

**Issue by MLDPEngineer** [protocolbuffers/protobuf#6501]
I need to 
`import "google/protobuf/any.proto";`
but when i install protobuf by:
`pip install protobuf`
it doesn't generate any proto files defined in setup.py
when i install protobuf by setup.py i give the error: issue[#6500](https://github.com/protocolbuffers/protobuf/issues/6500)

How can i install protobuf in true way, or generate setup protos?

**Comment by WangShaoRu** [comment]
You did not install associated protobuf header and lib, which is independent from protobuf-compiler. 
Run: sudo apt install libprotobuf-dev
