### ISSUE TITLE
Support for using clang on Windows

### ISSUE THREAD

**Issue by laudrup** [protocolbuffers/protobuf#6503]
Are there plans for supporting clang on Windows?

It seems like the Ninja generator is already supported, so running:

`cmake -G Ninja -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl ..\cmake`

Works just fine and compiles/links with `cmake --build .`.

But changing `cl` to `clang-cl` results in errors (as well as a few warnings) when compiling the resource files (.rc):

> "C:/Program Files/CMake/bin/cmcldeps.exe" RC C:\Temp\protobuf\ninja_build\version.rc CMakeFiles\libprotobuf-lite.dir\version.rc.res.d CMakeFiles\libprotobuf-lite.dir\version.rc.res "Note: including file: " "C:/Program Files/LLVM/bin/clang-cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe /l0x409 -DGOOGLE_PROTOBUF_CMAKE_BUILD /foCMakeFiles\libprotobuf-lite.dir\version.rc.res C:\Temp\protobuf\ninja_build\version.rc
> clang-cl: error: no such file or directory: '/l0x409'
> clang-cl: error: no such file or directory: '/foCMakeFiles\libprotobuf-lite.dir\version.rc.res.dep.obj'

It seems like it is almost supported although I'm very puzzled by the error message. I'll try to dig more into it if that is any help.

Thanks a lot.

**Comment by acozzette** [comment]
We haven't attempted to build with Clang on Windows, but I would expect that it should be doable. Feel free to send a pull request if you find some tweaks that are necessary to get it to build.

**Comment by emmenlau** [comment]
I would be interested in this too. clang-cl provides often faster code, and provides a more uniform development experience across platforms. Sadly I'm not able to provide a PR.

**Comment by tobq** [comment]
@emmenlau @laudrup did you ever get anywhere with this?

**Comment by emmenlau** [comment]
I did not, I just use the Microsoft compiler again.
