### ISSUE TITLE
Parsing Performance issue:Why no parsing performance improvement after upgrading from protobuf-3.0.2 to protobuf-3.8.0?

### ISSUE THREAD

**Issue by binghan0703** [protocolbuffers/protobuf#6507]
I saw "Improve the parser." in the C++ release notes, Protocol Buffer v3.8.0.
I tested ParseArray function on demo project for 10000 times together on version 3.8.0 and 3.0.2 with an encoded array whose size is 1510 bytes.
The average cost time of 10000 tests is 105 us for 3.8.0, while 135 us for 3.0.2.
So I upgraded protobuf version on my product project from 3.0.2 to 3.8.0. But with my product project, there is no any cost-time improvement comparing with 3.0.2 while I also tested for more than 10000 times.
The only difference between demo project and product project as I think is that ParseArray on demo project is called in a loop, but on product project is not directly called in a loop. 
Could anyone pls explain the reason? Thanks in advance.

**Comment by acozzette** [comment]
I believe the parser improvements are guarded by a flag and actually not yet enabled by default. We are going to unconditionally enable the new parser soon, but for now if you want to try it you will have to pass `-DPROTOBUF_ENABLE_EXPERIMENTAL_PARSER=1`. I'm not sure if this works out-of-the-box yet as we have only been testing it with out internal version of the codebase, but feel free to give it a try.
