### ISSUE TITLE
How to parse text PB files in Ruby

### ISSUE THREAD

**Issue by njt1982** [protocolbuffers/protobuf#6508]
Hi,

I'm trying to parse file like this:
https://github.com/google/fonts/blob/master/apache/aclonica/METADATA.pb

Using the Ruby Gem. I have generated the classes from the .proto file:
`protoc --proto_path=app/messages/ --ruby_out=app/messages/ app/messages/fonts_public.proto`

And I have read through: https://developers.google.com/protocol-buffers/docs/reference/ruby-generated

```
irb(main):004:0> file = File.open('fonts/apache/aclonica/METADATA.pb', 'r')
=> #<File:fonts/apache/aclonica/METADATA.pb>
irb(main):005:0> Google::Fonts::FamilyProto.decode(file.read)
Traceback (most recent call last):
        2: from (irb):5
        1: from (irb):5:in `decode'
Google::Protobuf::ParseError (Error occurred during parsing: Invalid wire type)
```

I get *slightly* more success with `decode_json`...
```
irb(main):009:0> Google::Fonts::FamilyProto.decode_json(file.read)
Traceback (most recent call last):
        2: from (irb):9
        1: from (irb):9:in `decode_json'
Google::Protobuf::ParseError (Error occurred during parsing: Parse error at 'ame: "Aclonica")
designer: "Astigmatic"
license: "APACHE2"
category: "SANS_SERIF"
date_added: "2011-04-27"
fon...
```

Python examples I have seen seem to import a "text_format"... https://github.com/googlefonts/gftools/blob/master/Lib/gftools/util/google_fonts.py#L53 - but I dont see an equivalent class/method in the Gem ?

**Comment by TeBoring** [comment]
Text format is not supported by ruby.

**Comment by njt1982** [comment]
Thanks @TeBoring - is this documented anywhere? (I may have missed it).
