### ISSUE TITLE
UB when protobuf static library linked more than one time

### ISSUE THREAD

**Issue by ctin** [protocolbuffers/protobuf#6517]
**What version of protobuf and what language are you using?**
Version: v3.7.1 - v3.9.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**What did you do?**
1) For some reason I linked static protobuf library to my other libraries, which are shared;
2) then I created message
```
syntax = "proto3";

message Packet {
  bytes data1 = 1;
  bytes data2 = 2;
}
```
3) then I generated c++ class Packet using protoc v 3.7.1 (then I reproduced it using 3.9.1);
4) then I launched some function foo() in my code, which is doing something like this:
```
Packet packet;
packet.set_data1("data1");
packet.set_data2("data2");
```
**What did you expect to see**
data1 value is "data1"
data2 value is "data2"

**What did you see instead?**
data1 value is "data2"
data2 value is "data2"

**Anything else we should know about your project / environment**
1) https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/message_lite.h#L149 have global variable `fixed_address_empty_string`;
2) `bytes` converts into ArenaStringPtr, which is wrapper around std::string* ;
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/arenastring.h#L366 ;
3) by default ArenaStringPtr referencing to the `fixed_address_empty_string` variable;
4) when I am calling "set_data2" (see above) it calls ArenaStringPtr::SetNoArena ;
5) SetNoArena checks is pointer value was allocated. It compares current pointer value with given default value, which is referencing to the `fixed_address_empty_string` ;
6) while I am linking protobuf library more than once, `fixed_address_empty_string` at step (2) is different then `fixed_address_empty_string` on step (5)
7) https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/arenastring.h#L279 line invokes instead of allocation call, because `IsDefault` false for me. 
So my `bytes` fields sometimes pointing to the `fixed_address_empty_string` even after being set.

Proposal: transform `fixed_address_empty_string` from global variable to the local static variable and obtain it via `GetEmptyStringAlreadyInited` function call.

**Comment by acozzette** [comment]
@ctin The only way to avoid this problem is to make sure to only link `libprotobuf` once. Even if we implemented your proposal of changing `fixed_address_empty_string`, a bunch of other code would get duplicated and would violate the C++ one-definition rule (ODR).
