### ISSUE TITLE
How to obtain a FileDescriptorProto protobuf from a .proto file?

### ISSUE THREAD

**Issue by yzhao1012** [protocolbuffers/protobuf#6518]
This is for C++.

We are trying to use reflection to build an in-memory parser from a list of .proto file. The idea is to convert a .proto file into a FileDescriptorProto protobuf as defined in [1].

I know that we can get the proto from a actual object of the Message type. But we do not want to fully rebuild a proto and its import. We'd like to do that in runtime, with custom lookup mechanism to import protos.

Is there an API for that? I suppose it's already embedded somewhere inside the protobuf compiler, but an independent API or tools would be necessary to enable our use case.

Thanks in advance!

[1] https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor.pb

**Comment by TeBoring** [comment]
I guess you will need https://github.com/protocolbuffers/protobuf/blob/5b232b8ecbce13286be09e703997e887ae0d464d/src/google/protobuf/compiler/importer.h#L80
