### ISSUE TITLE
Inconsistent handling of repeated field by generated message code and dynamic message

### ISSUE THREAD

**Issue by yzhao1012** [protocolbuffers/protobuf#6523]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux 
$ uname -a
Linux ... 4.15.0-1045-oem #50-Ubuntu SMP Wed Jun 26 11:16:36 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
// cat test.proto
message RepeatedInt32 {
  repeated int32 ri32s = 1;
}

message String {
  string str = 1;
}

// cat test.cc
TEST(ProtobufsAliasingTest, StringAndPackedRepeated) {
  RepeatedInt32 ri32;
  ri32.add_ri32s(100);
  ri32.add_ri32s(101);
  ri32.add_ri32s(102);

  String str;
  EXPECT_TRUE(str.ParseFromString(ri32.SerializeAsString()));
  EXPECT_THAT(GetUnknownFieldsType(str), IsEmpty());

  DescriptorProto desc_pb;
  ri32.GetDescriptor()->CopyTo(&desc_pb);
  EXPECT_THAT(desc_pb, EqualsProto(R"proto(
      name: "RepeatedInt32"
      field {
        name: "ri32s"
        number: 1
        label: LABEL_REPEATED
        type: TYPE_INT32
      }
  )proto"));

  // 100-102 happens to corresponding to ASCII def. Also because repeated field is packed, allows it
  // to be parsed as string.
  EXPECT_THAT(str, EqualsProto("str: 'def'"));

  auto db = CreateServiceDescDB(R"proto(
      message_type {
        name: "RepeatedInt32"
        field {
          name: "ri32"
          number: 1
          label: LABEL_REPEATED
          type: TYPE_INT32
          // This would allow dynamic message behavior identically as above generated one.
          // options { packed: true }
        }
      }
      message_type {
        name: "String"
        field {
          name: "str"
          number: 1
          type: TYPE_STRING
        }
      }
  )proto");

  auto ri322 = db->GetMessage("RepeatedInt32");
  ASSERT_NE(nullptr, ri322);
  EXPECT_TRUE(TextFormat::ParseFromString("ri32: 100 ri32: 101 ri32: 102", ri322.get()));
  EXPECT_THAT(GetUnknownFieldsType(*ri322), IsEmpty());

  auto str2 = db->GetMessage("String");
  ASSERT_NE(nullptr, str2);
  EXPECT_TRUE(str2->ParseFromString(ri322->SerializeAsString()));
  EXPECT_THAT(GetUnknownFieldsType(*str2), ElementsAre(UnknownField::Type::TYPE_VARINT,
                                                       UnknownField::Type::TYPE_VARINT,
                                                       UnknownField::Type::TYPE_VARINT));
  EXPECT_THAT(*str2, Not(EqualsProto("str: 'def'")));
}

The test.cc is a snippet from an internal test file.

You can see from the test.cc that for a predefined proto message, the repeated field will be serialized as packed==true, and parsed as such. While for the dynamic message generated from the exactly same DescriptorProto protobuf, the repeated field would assume package==false, which is the default value of an proto file bool field.

And by explicitly adding options { packed = true }, that would make dynamic message behave same as the generated message.

**What did you expect to see**
I expect dynamic message produced from proto3 syntax follow the same default behavior as generated message.

**What did you see instead?**
I see dynamic message assumes the default value of the packed field, which is false, so it serialized repeated field non-packed.

**Anything else we should know about your project / environment**
The test uses some internal code, so you might not be able to run it directly.

**Comment by acozzette** [comment]
That sounds like it should be a fairly straightforward fix in DynamicMessage. Feel free to send a pull request if you can fix it.

**Comment by yzhao1012** [comment]
I'd like to but needs guidance. Where should I start? Consider myself a complete novice in protobuf internals.

**Comment by acozzette** [comment]
@yzhao1012 Actually I just took a look and I'm not sure if there is a bug here. I suspect that when you're creating a DynamicMessage you're creating a proto2 message, which unlike proto3 defaults to no packing. Can you confirm whether your code is creating a proto2 or proto3 DynamicMessage?

**Comment by yzhao1012** [comment]
Thanks Adam!

I tried the following:
// cat test.proto
message RepeatedInt32 {
  repeated int32 ri32s = 1;
}
// cat test.cc
RepeatedInt32 ri32;
ri32.add_ri32s(100);
ri32.GetDescriptor()->CopyTo(&desc_pb);
LOG(INFO) << desc_pb.DebugString();  // This prints name: "RepeatedInt32"
field {
  name: "ri32s"
  number: 1
  label: LABEL_REPEATED
  type: TYPE_INT32
}
LOG(INFO) << Repr(ri32.SerializeAsString());  // \x0A\x03\x64\x65\x66

You can see that proto3 serialize repeated primitive field as packed, as indicated in \x0A which is field number 1 wire type 2 (length prefixed field).

But the descriptor is missing the packed option. Which will result into the dynamic message not having packed encoding.

Here there is no proto2 involved.

Unless I am missing something, I believe the GetDescriptor()->CopyTo() should have packed set to true if it's behaving as it's true.

**Comment by acozzette** [comment]
I think this is working as intended actually. `desc_pb` doesn't specify `packed` because it wasn't explicitly set in the proto file. Since it's unset, we rely on the default of false for proto2 and true for proto3. When you call `CreateServiceDescDB`, it looks like you're not setting it to proto3, so it's defaulting to proto2.

**Comment by yzhao1012** [comment]
> When you call CreateServiceDescDB, it looks like you're not setting it to proto3, so it's defaulting to proto2.

I do not follow.

In my previous message, note the descriptorproto from the c++ message object:
// This prints name: "RepeatedInt32"
field {
name: "ri32s"
number: 1
label: LABEL_REPEATED
type: TYPE_INT32
}

**Note the packed option is not set**
**This seems wrong, as the message clearly behaves in a way that the packed is set**

CreateServiceDescDB is using the DescriptorDatabase API from our protocol runtime, we do not use proto2.

If there is a way to change how packed default work in DescriptorDatabase, please let me know.

**Comment by acozzette** [comment]
This is just how the packed option works. If it's unset, we treat it as true in proto3 but false in proto2. And since it is unset, it is not copied into the `DescriptorProto`. If you want it to be explicitly set to true then you would have to set `packed = true` in the .proto file.

I suspect that in `CreateServiceDescDB` you're using proto2 without realizing it. Unless you explicitly set `FileDescriptorProto.syntax` to "proto3", it will default to proto2.

**Comment by yzhao1012** [comment]
> I suspect that in CreateServiceDescDB you're using proto2 without realizing it. Unless you explicitly set FileDescriptorProto.syntax to "proto3", it will default to proto2.

I am not sure how that could happen. But I checked again my test, syntax: proto3 is explicit set the FileDescriptorProto:

....
    field {
      name: "f643"
      number: 12
      label: LABEL_OPTIONAL
      type: TYPE_FIXED64
    }
  }
  syntax: "proto3"
}
