### ISSUE TITLE
Backwards incompatible change from 3.8.x -> 3.9.x

### ISSUE THREAD

**Issue by mikestanley** [protocolbuffers/protobuf#6526]
**What version of protobuf and what language are you using?**
Version: 3.8.1 & 3.9.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
N/A

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**

Upgrading from 3.8.1 to 3.9.1 Ruby library breaks compatibility.
Specifically this commit - https://github.com/protocolbuffers/protobuf/commit/565154af78c01c0424833022179dbfbe43fb081c

to_hash was dropped (since it really is a duplicate of the more common to_h) .  However, there are implications to removing this method.

For example, Rails as_json method looks for to_hash (not to_h).  
https://apidock.com/rails/Object/as_json

I consider this a backwards incompatible API change in a minor version upgrade.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/pull/6166
Seems the removal was intentional. And they were aware of the breakage.

**Comment by haberman** [comment]
Sorry for the breakage, the existing behavior was arguably broken and I think it should be easy to simulate the old behavior with something like:

```ruby
# Add to_hash to MessageExts, which is included in every message instance.
module Google
  module Protobuf
    module MessageExts
      def to_hash
        self.to_h
      end
    end
  end
end
```
