### ISSUE TITLE
Seeking guidance for adding large RepeatedFields benchmark

### ISSUE THREAD

**Issue by prat0088** [protocolbuffers/protobuf#6528]
My primary use cases are messages with large repeated fields.  1-100MB.  I would like to contribute a few PRs to improve C#'s RepeatedField performance, but first it would be useful to add a benchmark to prove the effectiveness of my changes.

1. I'm looking for guidance on what proto files to use.  Should I attempt to re-use an existing proto?  If so, which one would be best?  I haven't been able to decipher the naming of the proto files.
2. I'm looking for guidance on where to store the message.  I see `curl -O https://storage.googleapis.com/protobuf_opensource_benchmark_data/datasets.tar.gz` that is downloaded by `download_data.sh`, but I'm not sure how to add serialized messages to it.

I plan to add a new benchmark to the C# suite.  I would like to add it to the cpp benchmark suite  as well as sort of a baseline.

I would appreciate any advice on how to go about this in a way so that my PR is accepted.

Thanks

**Comment by acozzette** [comment]
@jonskeet Do you have any thoughts on this?

**Comment by dfreese** [comment]
#8283 was also opened about the missing benchmark data.

**Comment by elharo** [comment]
For questions like this, please see the protobuf mailing list: https://groups.google.com/forum/#!forum/protobuf
