### ISSUE TITLE
Incorrect json serialization of empty StringValue

### ISSUE THREAD

**Issue by serhiikushch** [protocolbuffers/protobuf#6531]
**What version of protobuf and what language are you using?**
Version: v3.9.1.
Language: PHP 7.3

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
I have a message defined as following:
```
syntax = "proto3";
message MyMessage {
    google.protobuf.StringValue field = 1;
}
```
**What did you expect to see**
When converting this message to json string like:
```php
$message = new MyMessage()
echo $message->serializeToJsonString();
```
should return:
```
{"field":""}
```
**What did you see instead?**
```
{"field":}
```
that results in `Syntax error` after applying `json_decode`

**Anything else we should know about your project / environment**
I'm using c extension

**Comment by TeBoring** [comment]
I think you code should return empty string. You didn't set the ```field``` at all.

**Comment by TeBoring** [comment]
Also, be setting ```field``` to emptry string, I got ```"{"field":""}"```.
I remember your issue was fixed long ago. Have you installed the latest protobuf pecl c extension?

**Comment by serhiikushch** [comment]
@TeBoring I'm using latest extension `v3.9.1`
I'm fine with any variant, just need valid JSON string

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/conformance/binary_json_conformance_suite.cc#L2029

We have tests to ensure that doesn't happen. I still doubt you haven't installed the c extension correctly. Could you provide a docker image?

**Comment by TeBoring** [comment]
Feel free to reopen when you can provide a docker image to reproduce this error.

**Comment by serhiikushch** [comment]
Hi @TeBoring 
I've just reopened it with detailed example and tests https://github.com/protocolbuffers/protobuf/issues/6667
