### ISSUE TITLE
ParseFromString raises DecodeError for the nested struct field

### ISSUE THREAD

**Issue by AlekzanderDee** [protocolbuffers/protobuf#6537]
**What version of protobuf and what language are you using?**
Version: protobuf==3.7.1.
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux (Ubuntu 16.04.4 LTS), MacOS Mojave (10.14.6)
 
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.0 

**What did you do?**
I have a gRPC service that has an endpoint that accepts a message with a single field of type **Struct**. I have discovered, that at the certain level of nesting the serialization on the server side stops working and raises exception. After some investigations I was able to reproduce the exception without gRPC being envolved.

The following code allows to reproduce the issue:

```proto
message ImportDataRequest {
    google.protobuf.Struct request_data = 1;
}
```
```python
depth_limit = 34
data = {}
node = data
for _ in range(depth_limit):
    node['a'] = {}
    node = node['a']

payload = ParseDict(data, struct_pb2.Struct())
request = ImportDataRequest(request_data=payload)
request_str = request.SerializeToString()

message = ImportDataRequest()
message.ParseFromString(request_str)
```

This raises exception:
```
Traceback (most recent call last):
  File "/Users/alexander.dultsev/Library/Preferences/PyCharm2019.2/scratches/scratch.py", line 17 in <module>
    message.ParseFromString(request_str)
google.protobuf.message.DecodeError: Error parsing message
```

However, if you set ***depth_limit*** to anything less than **34**, it works fine.

**What did you expect to see**
A message created without any exception being raised.

**What did you see instead?**
google.protobuf.message.DecodeError: Error parsing message

**Comment by AlekzanderDee** [comment]
any progress on this?

**Comment by anandolee** [comment]
I believe you are using protobuf cpp extension, the cpp extension has a recursive limit 100 as default:
https://github.com/protocolbuffers/protobuf/blob/763c3588740b97e8e80b1b1a1a2dc4f417647133/src/google/protobuf/io/coded_stream.cc#L89

The struct message has map entry, value message which means 34 depth_limit is 34 * 3 = 102 depth in protobuf.

To change this, you can SetAllowOversizeProtos():
https://github.com/protocolbuffers/protobuf/blob/4e93585e8bb234efeacb7737b8d080968c5ab91e/python/google/protobuf/pyext/message.cc#L1941

**Comment by AlekzanderDee** [comment]
Two questions:
1. Does it mean that it is not possible to serialize any JSON object into a Struct (if you don't know for sure the depth of the nesting)?
2. Could you mention this limitation somewhere in the documentation so other developers don't experience the same issues? I'm happy to open a PR, but struggled to find the place.
