### ISSUE TITLE
NULL pointer checks are needed after allocating memory(encode_decode.c)

### ISSUE THREAD

**Issue by leo960** [protocolbuffers/protobuf#6548]
When I go through the source code, I found that there's no failure check after using malloc() and which may lead to crash.
So I suggest that the following cases should add some checks for NULL:
1. https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L135
2. https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L157
3. https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L170
4. https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L193
5. https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L654

**Comment by TeBoring** [comment]
Would you mind sending us a fix?

**Comment by wangkirin** [comment]
Besides @leo960  listed above, I think there are also some other code should be fix 
https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L76
https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L248
https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L359
https://github.com/protocolbuffers/protobuf/blob/63e4a3ecc956cbab6714b25e8b868765ea7e6fe5/php/ext/google/protobuf/encode_decode.c#L768

And Adding assertion after ```malloc```   may make the code more strong.

**Comment by wangkirin** [comment]
Hi, @TeBoring 
It seems  @leo960 doesn't have enough time to fix this issue. I am happy to give this issue a shot~~

**Comment by TeBoring** [comment]
Thanks for your help!
