### ISSUE TITLE
Missing descriptor for type registry.

### ISSUE THREAD

**Issue by katsuragi545** [protocolbuffers/protobuf#6562]
I have some Google Protobuf json with an '@type' field whose value is an URI that will tell someone the type of Protobuf message it is e.g.  "@type": "type.googleapis.com/llcore.ModemDataAtlas". From my understanding, these json strings should be serialized into an 'Any' type first. whenever I do this though, I get the following error:

`System.InvalidOperationException: Type registry has no descriptor for type name ''llcore.ModemMessage'`

Here is my code:

```
string jsonString = "";
string jsonPath = @"C:\Users\user\Documents\TestRepos\ExampleProto\protoType.json";
using (StreamReader reader = new StreamReader(jsonPath))
{
    jsonString = reader.ReadToEnd();
}

Any anyProto = Any.Parser.ParseJson(msg); // Exception occurs here
```

Does anyone know how to properly deserialize into a Protobuf Any class? How do I go about creating a type registry and adding a descriptor for it?

**Comment by ObsidianMinor** [comment]
You need to provide custom settings using a `TypeRegistry` that contains the descriptor.

```cs
Any anyProto;
string jsonPath = @"C:\Users\user\Documents\TestRepos\ExampleProto\protoType.json";
using (StreamReader reader = new StreamReader(jsonPath))
{
    var registry = TypeRegistry.FromFiles(/* insert file descriptors */);
    var settings = JsonParser.Settings.Default.WithTypeRegistry(registry);
    anyProto = new JsonParser(settings).Parse(reader);
}
```
