### ISSUE TITLE
Fix Binary Conformance Test for Packe/Unpacked Repeated Fields

### ISSUE THREAD

**Issue by TeBoring** [protocolbuffers/protobuf#6571]
https://github.com/protocolbuffers/protobuf/pull/6447
https://github.com/protocolbuffers/protobuf/pull/6440

- Both packed/unpacked data should be accepted during parsing
- Without specifying, encoding should follow the default behavior (unpacked for proto2 and packed for proto3)
- When specified in field option, encoding should respect that.

**Comment by haberman** [comment]
This is fixed for php.

For Ruby this is a dupe of https://github.com/protocolbuffers/protobuf/issues/2294
