### ISSUE TITLE
Java MergeFrom will never reset values to default

### ISSUE THREAD

**Issue by mpnewcomb** [protocolbuffers/protobuf#6582]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows 10 1809
**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 11+28
**What did you do?**
Test.proto:
```
syntax = "proto3";

import "google/protobuf/wrappers.proto";

message Test
{
  google.protobuf.Int32Value int32_value = 1;
  google.protobuf.BoolValue bool_value = 2;
}
```
MergeFromTest.java:
```
public class MergeFromTest
{
  public static void main(String... args)
  {
    var testBuilder = TestOuterClass.Test.newBuilder();
    testBuilder.getInt32ValueBuilder().setValue(15);
    testBuilder.getBoolValueBuilder().setValue(true);
    var test = testBuilder.build();

    var updateBuilder = TestOuterClass.Test.newBuilder();
    updateBuilder.getBoolValueBuilder().setValue(false);
    var update = updateBuilder.build();

    var mergedTestBuilder = test.toBuilder();
    mergedTestBuilder.mergeFrom(update);
    var merged = mergedTestBuilder.build();

    System.out.printf("test:\n%s\n", test);
    System.out.printf("update:\n%s\n", update);
    System.out.printf("merged:\n%s", merged);

    assert test.hasInt32Value();
    assert test.getInt32Value().getValue() == 15;
    assert test.hasBoolValue();
    assert test.getBoolValue().getValue();

    assert update.hasBoolValue();
    assert !update.getBoolValue().getValue();

    assert merged.hasBoolValue();
    assert !merged.getBoolValue().getValue(); // fails
  }
}
```
**What did you expect to see**
```
test:
int32_value {
  value: 15
}
bool_value {
  value: true
}

update:
bool_value {
}

merged:
int32_value {
  value: 15
}
bool_value {
}

``` 
**What did you see instead?**
```
test:
int32_value {
  value: 15
}
bool_value {
  value: true
}

update:
bool_value {
}

merged:
int32_value {
  value: 15
}
bool_value {
  value: true
}
```

I believe the problem lies with the the Wrapper (StringValue, BoolValue, Int32Value, etc.) classes mergeFrom methods. They should not test for the default instance when merging. They should always reset themselves to what is passed into mergeFrom. Otherwise, as this test demonstrates, once a boolean has been set to true, it can never be changed to false via mergeFrom. The same is true for all of the wrapper classes... they can never be merged back to the default values (0, "", false, etc.).

**Anything else we should know about your project / environment**
N/A

**Comment by elharo** [comment]
Not sure if this is WAI or not. Worth investigating further.

**Comment by perezd** [comment]
proto3 recently gained explicit optional keyword back from proto2, I wonder if an interesting solution here is to mark all the internal fields of wrappers as explicitly optional: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto
