### ISSUE TITLE
Include optional type URL in protobuf wire format

### ISSUE THREAD

**Issue by yzhao1012** [protocolbuffers/protobuf#6586]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
Proto3

If it's about generated code change, what programming language?
All languages

**Describe the problem you are trying to solve.**
A serialized protobuf has no type URL.

In certain cases, for example, examining serialized protobufs without knowing its original type, becomes extremely unreliable.

If type URL is embedded in the serialized message, it would be straightforward to figure out the right message type; assuming the .proto files are available, we can then use the right message to interpret the data, either through maintaining runtime type mapping, or reflection.

A noticeable use case of this, is a reflection-based data inspection tool, which can be very powerful for exploratory data analysis. Before building more specific and performant solutions, someone can depend on a commonly-built tool that uses type-url to interpret data, that can be used for ad-hoc query, debugging, etc, which links in the protobuf messages commonly used by a group of engineers.

A somewhat less useful thing is that, a dynamic message, which is produced using protobuf reflection facilities, can optional set a type URL for identification; making it more informative. This case benefits from a type URL in similar manner as the above.

**Describe the solution you'd like**
I'd like the serialization format to include an optional type URL field. Its field number can be 0 to distinguish from other fields.

Dynamic message of course would not be able to produce this information. But it could provide an optional API to set its type URL.

**Describe alternatives you've considered**
We can include a type url field with field number 1 in the message. But that seems too much work; and it requires manually maintain the code to set the field.

Also, in some cases, it's not reliable. I.e., if I do not know the type information in the first place, I cannot reliably conclude the field number 1 is the type URL. Unless I mandate all protobuf message define a type_url field as the first field, which is not difficult to do, but does incur considerable toil.

**Additional context**

This option would make our work of dynamically examine customer's protobuf much easier to implement. As we need to deal with the problem of aliasing serialized protobuf messages, i.e., because we do not know who generate the protobuf messages, when we get them, the customer do not want to annotate the messages themselves; they expect us to figure out the right type.

But because some wire types can be parsed as different fields, this makes our detection unreliable.

**Comment by acozzette** [comment]
Thank you for the idea, but I don't think we will be able to implement this change. This kind of change is very difficult to implement because it has to be done in a backward-compatible way and implemented across all 10 or so languages we support. I can see some value in the idea but I just don't think it is enough to justify all the work required. Also, we already have some basic support for this in the google.protobuf.Any type, which includes a type URL and has helper code for populating it.

**Comment by yzhao1012** [comment]
Just to explore a bit for future reference, such that readers do not find it confusing as to the concrete trade-offs involved for the decision.

> it has to be done in a backward-compatible way and implemented
Naively speaking, if I set the field number for this special type URL field to 0, as protobuf does not allow user specified field number to be smaller than 1, this should be immediately make a few compatibility scenarios easier to handle:

Lets say new message being ones that support embedded type URL.

1. old message parsing a serialized new message: old message recognize a field number 0, and then fail the parsing, as I experimented with this string "\x0A\x03\x64\x65\x66" (field number 0, length prefixed field).
2. new message parse new serialized message: obviously fine
3. new message parse old serialized message: obviously fine

#1 can be resolved set this feature as default disabled, such that new message by default does not produce type URL.

> across all 10 or so languages we support.
This is certainly a killer.

I suppose the work is mostly manual repetition. I am guessing each language will take a few hours of work to code, and a few days for review & land.
