### ISSUE TITLE
Imported files are generated repeatedly

### ISSUE THREAD

**Issue by zhiwangyan** [protocolbuffers/protobuf#6593]
I have defined some structures in the A.proto file.
Then import A.proto in the B.proto file
The js file generated by B.proto generates the content of A.proto again.
I just want to reference the contents of A.js in B.js.
Instead of generating 2 copies of the same content
What should I do? ? ?
Thank you

Ps: Translation from Google, may not be accurate

我在A.proto文件定义了一些结构
然后在B.proto文件import了A.proto
B.proto生成的js文件把A.proto的内容又生成了一遍
我只想在B.js引用A.js的内容
而不是生成2份同样的内容
我该怎么做呢？？？
谢谢

**Comment by wangkirin** [comment]
请问你用的是哪个版本？我在3.9.1版本上没遇到你说的情况。

**Comment by zhiwangyan** [comment]
> 请问你用的是哪个版本？我在3.9.1版本上没遇到你说的情况。

晕~发错地方了。。。我用的不是谷歌的。。。用的是另外一个叫protobuf.js的库，不好意思
