### ISSUE TITLE
make check failed 

### ISSUE THREAD

**Issue by edjust** [protocolbuffers/protobuf#6599]
**What version of protobuf and what language are you using?**
Version: Zip file of release 3.6.1 but I have tried 3.9.1 (the last update) too
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS 10.14.4
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc
**What did you do?**
Downloaded release 3.6.1 from https://github.com/google/protobuf/releases in Downloads.

Unzip the folder
Enter the folder and run ./autogen.sh && ./configure && make
Then run the command "make check" and occurs this:

Edgars-MacBook-Pro-152:protobuf-3.6.1 edjust$ make check
Making check in .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-local
Making lib/libgmock.a lib/libgmock_main.a in gmock
/bin/sh: line 0: cd: third_party/googletest/googletest: No such file or directory
make[2]: *** [check-local] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by wangkirin** [comment]
May be you should download the **protobuf-all-3.x.x.zip** rather than the **Source code(zip)**.
If you download the **Source code(zip)** ,you should copy the googletest package to the 
third_party directory manually.

**Comment by acozzette** [comment]
Yes, @wangkirin is right. Sorry about the confusion but the "Source code" archives auto-generated by GitHub don't include Git submodules and so they won't have the googletest package necessary for running tests. The "protobuf-all-*" packages should work, though.

**Comment by Penny7088** [comment]
penny@penny:~/protobuf-3.11.3$ make check
Making check in .
make[1]: Entering directory '/home/penny/protobuf-3.11.3'
make  check-local
make[2]: Entering directory '/home/penny/protobuf-3.11.3'
Making lib/libgmock.a lib/libgmock_main.a in gmock
make[3]: Entering directory '/home/penny/protobuf-3.11.3/third_party/googletest/googletest'
make[3]: *** No rule to make target 'lib/libgtest.la'。 停止。
make[3]: Leaving directory '/home/penny/protobuf-3.11.3/third_party/googletest/googletest'
Makefile:2161: recipe for target 'check-local' failed
make[2]: *** [check-local] Error 2
make[2]: Leaving directory '/home/penny/protobuf-3.11.3'
Makefile:2023: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/penny/protobuf-3.11.3'
Makefile:1735: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

I copied googletest to the third_party folder

**Comment by cihancalli** [comment]
pi@raspberrypi:~/tf/protobuf-3.17.2 $ make check
Making check in .
make[1]: Entering directory '/home/pi/tf/protobuf-3.17.2'
make  check-local
make[2]: Entering directory '/home/pi/tf/protobuf-3.17.2'
Making lib/libgmock.a lib/libgmock_main.a in gmock
make[3]: Entering directory '/home/pi/tf/protobuf-3.17.2/third_party/googletest/googletest'
make[3]: 'lib/libgtest.la' is up to date.
make[3]: 'lib/libgtest_main.la' is up to date.
make[3]: Leaving directory '/home/pi/tf/protobuf-3.17.2/third_party/googletest/googletest'
make[3]: Entering directory '/home/pi/tf/protobuf-3.17.2/third_party/googletest/googlemock'
make[3]: 'lib/libgmock.la' is up to date.
make[3]: 'lib/libgmock_main.la' is up to date.
make[3]: Leaving directory '/home/pi/tf/protobuf-3.17.2/third_party/googletest/googlemock'
make[2]: Leaving directory '/home/pi/tf/protobuf-3.17.2'
make[1]: Leaving directory '/home/pi/tf/protobuf-3.17.2'
Making check in src
make[1]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
make  protoc protobuf-test protobuf-lazy-descriptor-test protobuf-lite-test test_plugin protobuf-lite-arena-test no-warning-test zcgzip zcgunzip
make[2]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
make[2]: 'protoc' is up to date.
make[2]: 'protobuf-test' is up to date.
make[2]: 'protobuf-lazy-descriptor-test' is up to date.
make[2]: 'protobuf-lite-test' is up to date.
make[2]: 'test_plugin' is up to date.
make[2]: 'protobuf-lite-arena-test' is up to date.
make[2]: 'no-warning-test' is up to date.
make[2]: 'zcgzip' is up to date.
make[2]: 'zcgunzip' is up to date.
make[2]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make  check-TESTS
make[2]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
make[3]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.17.2
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
make[3]: *** [Makefile:7997: test-suite.log] Error 1
make[3]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make[2]: *** [Makefile:8105: check-TESTS] Error 2
make[2]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make[1]: *** [Makefile:8221: check-am] Error 2
make[1]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make: *** [Makefile:1906: check-recursive] Error 1

**Comment by SC-One** [comment]
I have same error and can't be fixed with any solution that suggested in this page,
my error:
```
  ...
  CXX      google/protobuf/compiler/objectivec/objectivec_helpers.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_map_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_oneof.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_primitive_field.lo
  CXX      google/protobuf/compiler/php/php_generator.lo
  CXX      google/protobuf/compiler/python/python_generator.lo
  CXX      google/protobuf/compiler/python/python_helpers.lo
  CXX      google/protobuf/compiler/python/python_pyi_generator.lo
  CXX      google/protobuf/compiler/ruby/ruby_generator.lo
  CXXLD    libprotobuf-lite.la
  CXXLD    libprotobuf.la
  CXXLD    libprotoc.la
  CXXLD    protoc
make[2]: Leaving directory '/tmp/protobuf/protobuf/src'
make[1]: Leaving directory '/tmp/protobuf/protobuf'
```

this error occured when executed the following commands:

```
git clone -b v3.20.0 https://github.com/protocolbuffers/protobuf.git
cd protobuf
git submodule update --init --recursive
./autogen.sh
./configure
make -j8
```

**Comment by SC-One** [comment]
and after these I executed "make check" too, the following errors occured:
```
  CXXLD    zcgunzip
make[2]: Leaving directory '/tmp/protobuf/protobuf/src'
make  check-TESTS
make[2]: Entering directory '/tmp/protobuf/protobuf/src'
make[3]: Entering directory '/tmp/protobuf/protobuf/src'
../test-driver: line 107: 63565 Killed                  "$@" > $log_file 2>&1
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.20.0-rc-2
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
make[3]: *** [Makefile:8232: test-suite.log] Error 1
make[3]: Leaving directory '/tmp/protobuf/protobuf/src'
make[2]: *** [Makefile:8340: check-TESTS] Error 2
make[2]: Leaving directory '/tmp/protobuf/protobuf/src'
make[1]: *** [Makefile:8456: check-am] Error 2
make[1]: Leaving directory '/tmp/protobuf/protobuf/src'
make: *** [Makefile:1927: check-recursive] Error 1

```

**Comment by liujf69** [comment]
I have the same question, any solution?
