### ISSUE TITLE
ProtocolMessageEnum should have a toString() that returns the name

### ISSUE THREAD

**Issue by daveyostcom** [protocolbuffers/protobuf#6600]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
While debugging it would be nice to see the names of enum values.

**Describe the solution you'd like**
a toString() method that returns the name à la [java.lang.Enum](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Enum.html#toString()).

**as of Protobuf version**
3.9.1

**Comment by googleberg** [comment]
Please use:
value.getValueDescriptor().getName()
