### ISSUE TITLE
Python: Issue with json_format

### ISSUE THREAD

**Issue by popzxc** [protocolbuffers/protobuf#6602]
## Metadata:
Version: protobuf v3.9.1
Language: Python
Python version: 3.6.8

## Main topic

Attempt to parse Protobuf Message from json with bytes object doesn't seem to behave right.

If Protobuf Message has a bytes field, and in json it's encoded as a list of bytes (e.g. `[0xDE, 0xAD, 0xBE, 0xEF]`), parsing fails with `ParseError`:

```python
  File "/home/user/workspace/project/project/file.py", line 10, in func
    return json_format.Parse(data_json, protobuf_obj, True).SerializeToString()
  File "/home/user/workspace/project/project_venv/lib/python3.6/site-packages/google/protobuf/json_format.py", line 415, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "/home/user/workspace/project/project_venv/lib/python3.6/site-packages/google/protobuf/json_format.py", line 435, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/home/user/workspace/project/project_venv/lib/python3.6/site-packages/google/protobuf/json_format.py", line 466, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/home/user/workspace/project/project_venv/lib/python3.6/site-packages/google/protobuf/json_format.py", line 575, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse pub_key field: Failed to parse data field: argument should be a bytes-like object or ASCII string, not 'list'..
```

The issue here is that json doesn't have `bytes` type, and encoding to `base64` is not what you want to do just to make parser happy.

Fictional reproducing example:
```python
from google.protobuf import json_format

json_data = '{ "data": [12, 34, 56, 78] }'
message = Message()  # .proto for Message is "messasge Message { bytes data = 1 }"
json_format.Parse(json_data, message)

```

## Expected behavior

I think that lists should be attempted to be parsed into bytes in that case, and only if list contains unappropriate values, exception should be rised.

**Comment by popzxc** [comment]
I don't mind creating a pull request fixing that issue, if this behavior will be considered to be a bug.

**Comment by NiNiyethawe** [comment]
{
string query = 1;
int32 page_number = 2;
int32 result_per_page = 3;
}

**Comment by popzxc** [comment]
Just kindly reminding about this issue. Will there be any feedback on that?

**Comment by popzxc** [comment]
@TeBoring I'm sorry, but can you comment this?

**Comment by anandolee** [comment]
Please see protobuf json mapping

JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.

https://developers.google.com/protocol-buffers/docs/proto3#json

List is not accepted for bytes field

**Comment by popzxc** [comment]
Yeah, but error message doesn't explain it. Instead of "argument should be a bytes-like object or ASCII string" I'd expect to see something like "For JSON, bytes fields should be encoded as base64 string", which will be much more helpful.

**Comment by anandolee** [comment]
Thanks for the suggestion, but we may not have enough time for it. Are you happy to contribute and send me a PR for review?
Close it for clean up. Feel free to reopen if still need this error message and a PR is ready 

Thanks

**Comment by popzxc** [comment]
Well, I guess not after 3 years :)
I already forgot what's this issue is about, to be honest.
