### ISSUE TITLE
If message name has the dash sigbal, it can't compile

### ISSUE THREAD

**Issue by moranxy** [protocolbuffers/protobuf#6603]
I have define a message,but when I try to convert to c++, the error has occured.
message Search-Request {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}

the error is :
test.proto:3:15: Expected "{"

I want to know how to add that "-"symbol in the message name and is that lowerCamelCase is required for the "SearchRequest". Can I define it as "searchrequest" ?

**Comment by NiNiyethawe** [comment]
{
string query = 1;
int32 page_number = 2;
int32 result_per_page = 3;
}[](url)

**Comment by NiNiyethawe** [comment]
{
string query = 1;
int32 page_number = 2;
int32 result_per_page = 3;
}

**Comment by moranxy** [comment]
> {
> string query = 1;
> int32 page_number = 2;
> int32 result_per_page = 3;
> }

where is the message name ?

**Comment by acozzette** [comment]
Names can't have a dash in them because that would cause problems in many languages--e.g. in C++ `Search-Request` would turn into three separate tokens. The protobuf [style guide](https://developers.google.com/protocol-buffers/docs/style) would recommend `SearchRequest`, though you could in principle also do `searchrequest`.

**Comment by moranxy** [comment]
> Names can't have a dash in them because that would cause problems in many languages--e.g. in C++ `Search-Request` would turn into three separate tokens. The protobuf [style guide](https://developers.google.com/protocol-buffers/docs/style) would recommend `SearchRequest`, though you could in principle also do `searchrequest`.
Thank you for your reply, but the problem we are now experiencing is due to the problem of yang and proto. In the yang file, the dash is allowed to be named, but we will support the data table of yang to support protobuf. Encountered such a problem. In rfc7950 The YANG 1.1 Data Modeling Language, the modulename of yang is specified as follows.such as：
module <module-name> {
[https://tools.ietf.org/html/rfc7950](url)

Hope for your reply，thanks
