### ISSUE TITLE
Can ParseFromString() and other parse function fail when parse repeated fields as optional field?

### ISSUE THREAD

**Issue by yzhao1012** [protocolbuffers/protobuf#6604]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
Proto3

If it's about generated code change, what programming language?
All language

**Describe the problem you are trying to solve.**
message RepeatedString {
  repeated string strs = 1;
}
message OptionalString {
  string str = 1;
}
RepeatedString rep_str;
rep_str.add_strs("a");
rep_str.add_strs("b");

OptionalString opt_str;
opt_str.ParseFromString(rep_str.SerializeAsString());
ASSERT(opt_str.str == "b");

Note that str will become "b", and no error is raised.

**Describe the solution you'd like**
ParseFromString() should return false.

**Describe alternatives you've considered**
No idea

**Additional context**

We unfortunately ran into this when parsing old data after changing type from repeated to optional. We want to avoid running into such situation by failing the parse.

**Comment by acozzette** [comment]
Sorry but we can't change this because that would be a breaking change to the wire format. If a singular field appears more than once, the last one wins. This can actually be a useful feature sometimes because it allows you to change a serialized message by appending onto it.
