### ISSUE TITLE
s390x protoc v3.10.0-rc1 failed with exec format error

### ISSUE THREAD

**Issue by salamaniibm** [protocolbuffers/protobuf#6625]
**What version of protobuf and what language are you using?**
Version:  v3.10.0-rc1
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**What did you do?**
On s390x system
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc1/protoc-3.10.0-rc-1-linux-s390x_64.zip
unzip protoc-3.10.0-rc-1-linux-s390x_64.zip
copied the content of include to /usr/local/include/
./bin/./protoc --version
```
bash: ./protoc: cannot execute binary file: Exec format error
```

**What did you expect to see**
./bin/protoc --version
```
libprotoc 30.10.0
```
**What did you see instead?**

./bin/./protoc --version
```
bash: ./protoc: cannot execute binary file: Exec format error
```

**Anything else we should know about your project / environment**

Here is information x86_64 machine I used
uname -a
```
Linux salamani 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 
x86_64 x86_64 x86_64 GNU/Linux
```

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

I cross-compiled the binary on Intel and s390x binary worked for me. 
Steps to reproduce:
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf && git checkout v3.10.0-rc1
cd kokoro/release/protoc/linux/
./build.sh
[log build_cmd.txt](https://github.com/protocolbuffers/protobuf/files/3582672/build_cmd.txt)

ls -lah protobuf/protoc-artifacts/target/linux/s390x_64/
```
-rwx------ 1 root root 7.6M Sep  6 02:36 protoc.exe
```

On s390x machine:
./protoc.exe --version
```
libprotoc 30.10.0
```

ldd ./protoc.exe
 ```
        libm.so.6 => /lib/s390x-linux-gnu/libm.so.6 (0x000003ff9a300000)
        libpthread.so.0 => /lib/s390x-linux-gnu/libpthread.so.0 (0x000003ff9a280000)
        libc.so.6 => /lib/s390x-linux-gnu/libc.so.6 (0x000003ff9a080000)
        /lib/ld64.so.1 (0x000003ff9ac80000)
```

**Comment by salamaniibm** [comment]
Any updates here?

**Comment by salamaniibm** [comment]
Any updates? Any information on your environment to reproduce and check the issue will be useful.

**Comment by acozzette** [comment]
@rafi-kamal Do you have any ideas on what the problem is?

**Comment by rafi-kamal** [comment]
Sorry, I am not familiar with s390x. Looking at the error, I think it means that the platform doesn't support s390x binaries or the binary itself might be corrupt?

**Comment by acozzette** [comment]
I think this is the prebuilt binary we published.

**Comment by salamaniibm** [comment]
@rafi-kamal s390x support(#6558) for protobuf is already added.  We are facing issue with pre-built r3.10.0-rc1 binary.

**Comment by salamaniibm** [comment]
@rafi-kamal any updates here?

**Comment by rafi-kamal** [comment]
Sorry, as I mentioned earlier we don't have any experience with s390x. Perhaps you would be able to help us debug what the issue is?

**Comment by salamaniibm** [comment]
I cross-compiled the binary on x86 linux ubuntu 16.04
Steps to reproduce:
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf && git checkout v3.10.0-rc1
cd kokoro/release/protoc/linux/
./build.sh

ls -lah protobuf/protoc-artifacts/target/linux/s390x_64/
```
-rwx------ 1 root root 7.6M Sep  6 02:36 protoc.exe
```

I am able to use this cross-compiled binary on s390x machine. 

Pre-build 3.10.0-rc1 binary ([link](https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc1/protoc-3.10.0-rc-1-linux-s390x_64.zip)) is not working for me. pre-built binary having a size of 4.8M only compared to 7.6MB(which I got it after cross-compile)

**Comment by acozzette** [comment]
The prebuilt binary came from the script from #6558. I'm not sure if we have time debug it unfortunately.

**Comment by salamaniibm** [comment]
Can you please share information about your environment so that I can try to reproduce the issue.
Currently the  script from #6558  is able to generate s390x binary as tried on x86 ub16.04 system.

**Comment by salamaniibm** [comment]
Any updates here!

**Comment by acozzette** [comment]
I believe we are using Ubuntu 16.04.6 LTS on x86, so I'm not sure why it's not working.

**Comment by guirish** [comment]
@salamaniibm @acozzette 
To reproduce above issue I worked on said ARCH `Linux e7cf29d38856 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`  - Ubuntu 16.04

We might be observing above issue as the mentioned dependency library package i.e `g++-s390x-linux-gnu` is not available on the CI/host machine while building the protoc.exe Linux binary specific to s390x_64. 

Without said dependency the protoc.exe binary get created but its file format is as below:
`$ file target/linux/s390x_64/protoc.exe     
target/linux/s390x_64/protoc.exe: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=287559850f999d3c5c1b5d0fa7b132d3f21035d8, stripped`

Subsequently this built binary is pushed onto the Maven repository and is later pulled from Maven repo and is packaged as zip file(Release).  

After installing  `g++-s390x-linux-gnu` the respective protoc.exe binaries get created and it's file format is as desired.

**SOLUTION**
Below steps were performed on a fresh ubuntu:16.04 container:

- apt-get update
- apt-get install -y autoconf automake libtool gzip make wget g++ vim  g++-powerpc64le-linux-gnu g++-s390x-linux-gnu git
- git clone https://github.com/protocolbuffers/protobuf.git
- cd protobuf
- ./autogen.sh
- cd protoc-artifacts/
- ./build-protoc.sh linux ppcle_64 protoc
- ./build-protoc.sh linux s390x_64 protoc
- ./build-protoc.sh linux x86_64 protoc

The file formats of respective cross built binaries were 
`
root@197933a2acf5:/protobuf/protoc-artifacts# file target/linux/s390x_64/protoc.exe
target/linux/s390x_64/protoc.exe: ELF 64-bit MSB shared object, IBM S/390, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld6, for GNU/Linux 3.2.0, BuildID[sha1]=27b10b218dc8c66e40407839b250a2c8d3752422, stripped`

`root@197933a2acf5:/protobuf/protoc-artifacts# file target/linux/ppcle_64/protoc.exe
target/linux/ppcle_64/protoc.exe: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=221a48e5a5d33e6fb2803c50e927699e322a6a16, stripped`
`

If any other specific details are required, do let me know. Thanks.

**Comment by salamaniibm** [comment]
@acozzette any update?

**Comment by salamaniibm** [comment]
@here any update?

**Comment by acozzette** [comment]
Sorry for taking so long to get back to this. From looking at the logs I think @guirish is right that for some reason the `g++-s390x-linux-gnu` package is failing to install. Unfortunately I don't think anyone on the protobuf has free cycles to debug further, though.

**Comment by huxd-ibm** [comment]
@acozzette would you post what are problems installing the g++-s390x-linux-gnu package?
I can use @guirish instructions to build correct binary for s390x correctly from my pure x86 laptop environment, which is quite simple and straight forward.
appreciate if this can be incorporated in the CI environment to fix this issue!

**Comment by salamaniibm** [comment]
@acozzette  @rafi-kamal 
We checked the protobuf Kokoro CI and it is redirecting to ‘grpc-testing’ project, In any manner is grpc CI is connected to Protobuf?

Do we need to update grpc cross scripts(if protobuf is using grpc cross build tools) to release correct s390x binary for Protobuf?

Could you please give more information about binary release process?

**Comment by acozzette** [comment]
I'm sorry but I am afraid we are not going to be able to take on the support for building these binaries. Unfortunately we just don't have the free cycles to dig into this. We used to share some of the CI setup with the gRPC project but I am not sure if that is still true.

**Comment by ravigumm** [comment]
It seems the protoc binary available in s390x zip file is x86 binary instead of s390x binary. Not sure if the build steps has some issue OR the PR https://github.com/protocolbuffers/protobuf/pull/6558 is incomplete.

**Comment by salamani** [comment]
@ravigumm Steps and #6558 looks good for me. 
I verified master branch on x86 machine,  s390x binary generated at `target/linux/s390x/protoc.exe` works fine for s390x system.
As mentioned by @guirish and @rafi-kamal, I assume  `g++-s390x-linux-gnu` not yet present in CI environment. 
@acozzette  Any update here?

**Comment by ravigumm** [comment]
I downloaded zip files of s390x (from https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-s390x.zip and also from https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-s390x.zip) and saw that the binary of protoc is of x86 instead of s390x. Not sure where/how the zip file got generated.

**Comment by guirish** [comment]
@ravigumm could you please try the steps which I have mentioned earlier, you can try with and without `g++-s390x-linux-gnu` in new containers.

**Comment by guirish** [comment]
@acozzette @rafi-kamal 

We are still observing corrupt protoc binaries of s390x getting released in latest releases. Any updates on the earlier proposed solution to fix this issue. It would be great if you could point us to the build script of respective CI (taking reference from #https://github.com/grpc/grpc-node/issues/296).

/cc @salamani

**Comment by acozzette** [comment]
The build script is here: https://github.com/protocolbuffers/protobuf/blob/master/protoc-artifacts/build-protoc.sh And it is invoked by this script: https://github.com/protocolbuffers/protobuf/blob/master/kokoro/release/protoc/linux/build.sh

**Comment by salamani** [comment]
@acozzette New releases of v3.15.x are working fine.

**Comment by salamaniibm** [comment]
Closing it. As releases after v3.15.x  are not facing this  issue.
