### ISSUE TITLE
Fix Binary Conformance Test for Oneof Field

### ISSUE THREAD

**Issue by TeBoring** [protocolbuffers/protobuf#6630]
https://github.com/protocolbuffers/protobuf/pull/6622

**Comment by haberman** [comment]
It looks like the C extension is fixed. But the following test is still failing for pure PHP:

```
Recommended.Proto3.ProtobufInput.ValidDataOneofBinary.MESSAGE.Merge.ProtobufOutput
```

**Comment by elharo** [comment]
I expect this is fixed since the CI passes. Reopen if not.
