### ISSUE TITLE
How to delete a repeated member?

### ISSUE THREAD

**Issue by jinfeihan57** [protocolbuffers/protobuf#6636]
**What language does this apply to?**
c++
If it's a proto syntax change, is it for proto2 or proto3?
proto3
If it's about generated code change, what programming language?
is's about generated code.

**Describe the problem you are trying to solve.**
when a member is repeated ,it has some Methods like ：
        inline int AddressBook::people_size() const；
        inline void AddressBook::clear_people() ；
        inline ::tutorial::Person* AddressBook::mutable_people(int index) ；
        inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Person >*
            AddressBook::mutable_people()；
        inline const ::tutorial::Person& AddressBook::people(int index) const ；
        inline ::tutorial::Person* AddressBook::add_people() ；
        inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tutorial::Person >&
            AddressBook::people() const ；
but if i want to delete one ,how should i do it?
for example if there is 3 people already in the addressbook.but some reasons i want to delete the second one . i have to make a new addressbook copy the first and thrid people to it ,then delete the old addresbook .,but if i already have 10000 people ,if i want to delete one what should i do?? 
**Describe the solution you'd like**
if there is any chance i can use somekind delete(int index) FUNC to do it ?
**Describe alternatives you've considered**

**Additional context**

**Comment by acozzette** [comment]
You can call `erase()` on the `RepeatedField<T>` and pass it an iterator pointing to the element you want to remove.

**Comment by jinfeihan57** [comment]
Thank you！
