### ISSUE TITLE
Java util for conversions between Timestamp/Duration and java.time.Instant/Duration

### ISSUE THREAD

**Issue by sulume** [protocolbuffers/protobuf#6641]
It's not a big deal but tedious to every time exchange between the types while remembering its internal representations (seconds + nanos). It's nice if the utility methods for the official utility messages are given with the official package to avoid other users have their own versions of the same logic.

**Comment by elharo** [comment]
This can't really be addressed until we drop support for Java 7. That might happen in 2022 but no promises.

**Comment by elharo** [comment]
This amounts to a request to open source google3/java/com/google/protobuf/util/JavaTimeConversions.java, which is completely reasonable. However it does require us to drop Java 7.

**Comment by googleberg** [comment]
Requires Java 8 support.
Can't do at the moment due to internal limitations.

**Comment by desh-woes** [comment]
Any updates as to when this is planned to happen?

**Comment by googleberg** [comment]
As @elharo noted, we have an internal utility that we'd like to open source. However, we are currently constrained by needing to support Android API level 21 as a minimum. `java.time.Instant` was added to Android in API level 26.
