### ISSUE TITLE
How to add any custom metadata for .proto file, protobuf message and protobuf fields

### ISSUE THREAD

**Issue by janejoseph** [protocolbuffers/protobuf#6648]
Hi,

May i know if we have a way to add one or more custom metadata for .proto file, protobuf message and fields in protobuf message ? Also is there an API which can be used to get the metadata for each of the scenario ?

Thanks
Jane

**Comment by janejoseph** [comment]
Hi,

Forgot to mention, I would like to know the options available in proto3 and proto2 and any known limitations.

Thanks
Jane

**Comment by acozzette** [comment]
I think the feature you're looking for is [custom options](https://developers.google.com/protocol-buffers/docs/proto#customoptions), which you can use with both proto2 and proto3. It depends on what language you're using but most languages give you a way to read these custom options from the descriptors.

**Comment by janejoseph** [comment]
Hi Adam, 

Thank you for the response. I tried the following:
foo.proto
======

// foo.proto
syntax = "proto2";
import "google/protobuf/descriptor.proto";
package foo;

extend google.protobuf.FileOptions {
  optional string my_file_option = 50000;
}

extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

extend google.protobuf.FieldOptions {
  optional float my_field_option = 50002;
}

bar.proto
======
// bar.proto
syntax = "proto2";
import "foo.proto";
package bar;

option (foo.my_file_option) = "Hello File!";

message MyMessage {
  option (foo.my_option) = "Hello world!";
  optional int32 foo = 1 [(foo.my_field_option) = 4.5];
}

But I am not able to find what API to use for getting the my options for file, msg or field ?
Also I am looking for defining some metadata of each file , msg and field. Could you please confirm custom options is the one to be used here ? I only need to define them once in proto and this info needs to be retrieved per file, msg or field using some API.

Thanks
Jane

**Comment by acozzette** [comment]
The details of accessing custom options depends on the language. Which language are you using? It sounds like custom options are indeed the right solution if you want to store per-file, per-msg, and per-field metadata.

**Comment by janejoseph** [comment]
We are using C++ ...

**Comment by acozzette** [comment]
In that case you just have to get ahold of the descriptor for your message/file/field and do `descriptor->options.GetExtension(...)`. See this [test](https://github.com/protocolbuffers/protobuf/blob/b9f405ae46036860a4e73e167bee3800dfe53a9e/src/google/protobuf/descriptor_unittest.cc#L2976) for some more examples.

**Comment by janejoseph** [comment]
Thank you for the details. Could you please confirm if protobufc support custom options with ProtobufCMessageDescriptor, ProtobufCFieldDescriptor ? I could not find one of File Descriptor in https://sjiang1.github.io/autoiodocu/protobuf-c_doc/group__api.html
