### ISSUE TITLE
[Crash Bug] PHTFlatFilePhenotype

### ISSUE THREAD

**Issue by fangyuxi** [protocolbuffers/protobuf#6653]
**I'm using firebase 6.8.1, Admob 7.49.0.**
**When new App is released at Appstore, I found more crashs appear in firebase dashboard. I do not use ProtoBuf directly**

Crashed: PHTFlatFilePhenotype
0  Protobuf                       0x160efd8 GPBCodedInputStreamReadDouble + 88 (GPBUtilities_PackagePrivate.h:88)
1  Protobuf                       0x160efd1 GPBCodedInputStreamReadDouble + 103 (GPBCodedInputStream.m:103)
2  Protobuf                       0x1639fd1 -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2143 (GPBMessage.m:2143)
3  Protobuf                       0x160f9c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
4  Protobuf                       0x163a47f MergeRepeatedNotPackedFieldFromCodedInputStream + 2294 (GPBMessage.m:2294)
5  Protobuf                       0x1639f6b -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2393 (GPBMessage.m:2393)
6  Protobuf                       0x160f9c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
7  Protobuf                       0x163a47f MergeRepeatedNotPackedFieldFromCodedInputStream + 2294 (GPBMessage.m:2294)
8  Protobuf                       0x1639f6b -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2393 (GPBMessage.m:2393)
9  Protobuf                       0x160f9c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
10 Protobuf                       0x163a47f MergeRepeatedNotPackedFieldFromCodedInputStream + 2294 (GPBMessage.m:2294)
11 Protobuf                       0x1639f6b -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2393 (GPBMessage.m:2393)
12 Protobuf                       0x1639647 -[GPBMessage mergeFromData:extensionRegistry:] + 1928 (GPBMessage.m:1928)
13 Protobuf                       0x1636d55 -[GPBMessage initWithData:extensionRegistry:error:] + 868 (GPBMessage.m:868)
14 Protobuf                       0x163971b +[GPBMessage parseFromData:extensionRegistry:error:] + 1957 (GPBMessage.m:1957)
15 Protobuf                       0x16396e5 +[GPBMessage parseFromData:error:] + 1951 (GPBMessage.m:1951)
16 SparkMusic                     0x526773 __69-[PHTHeterodyneSyncer syncAccount:syncedScopes:fetchReason:callback:]_block_invoke_2 + 4831091
17 libdispatch.dylib              0x1b461797 _dispatch_call_block_and_release + 10
18 libdispatch.dylib              0x1b46e59d _dispatch_queue_serial_drain + 854
19 libdispatch.dylib              0x1b464b71 _dispatch_queue_invoke + 886
20 libdispatch.dylib              0x1b46ea1f _dispatch_queue_override_invoke + 282
21 libdispatch.dylib              0x1b4701b5 _dispatch_root_queue_drain + 326
22 libdispatch.dylib              0x1b47000f _dispatch_worker_thread3 + 106
23 libsystem_pthread.dylib        0x1b61687d _pthread_wqthread + 1040
24 libsystem_pthread.dylib        0x1b61645c start_wqthread + 8

**Comment by ashokbhakharios** [comment]
have you got any solution for it?, we also facing this issue from last 2-3 days.

**Comment by simonbengtsson** [comment]
Also facing this since 6.8.1

**Comment by fangyuxi** [comment]
@ashokbhakharios 
@simonbengtsson 

It seems that there is no direct relationship with Protobuf, please discuss it here.

[https://github.com/firebase/firebase-ios-sdk/issues/3851](url)

Also, do you have this Crash after the release of the new version? I have rolled back to version 6.7.0, but this Crash still appears.
