### ISSUE TITLE
When will support for python2 be dropped?

### ISSUE THREAD

**Issue by thisch** [protocolbuffers/protobuf#6657]
When is it planned to drop support for cpython releases that are no longer maintained?

Python 3.5 will reach its EOL at the end of this month https://www.python.org/dev/peps/pep-0478/
Python 2.7 will reach its EOL on January 1st, 2020. https://pythonclock.org

**Comment by thisch** [comment]
Is it better to ask/discuss such a question on google.groups?

**Comment by anandolee** [comment]
We haven't make any plan to drop it yet. 
For python 2.6, its EOL was on 29 October 2013. Protobuf team drop python 2.6 support on Aug 22, 2017

I do not think we will continue support python 2.7 for 4 years after EOL like python 2.6, but a few months to 1 year after EOL seems reasonable.

**Comment by hugovk** [comment]
We're now one year after Python 2.7 EOL, any plans yet?
