### ISSUE TITLE
error: expected primary-expression before '__attribute__' when expand macro in port_def.inc

### ISSUE THREAD

**Issue by Haffon** [protocolbuffers/protobuf#6659]
**What version of protobuf and what language are you using?**
Version: master/v3.9.1.0, v3.9.1.0 is reported by CMake script.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 8.1.0 in mingw-w64
**What did you do?**
1. download tensorflow 1.13.2 source code
2. generate codeblocks project with cmake under tensorflow/contrib/cmake/_build_mingw64 directory
3. open the tensorflow.cbp project with codeblocks svn 11825
4. codeblocks already configured with mingw-w64, so select GNU GCC Compiler (x64) from the build options dialog.
5. Click the "Build" button
6. Then cmake script start to call git clone to download zlib, protobuf, etc. source code.
7. Click the "Build" button again if failed by cmake find sh, the second time seems ignored this error.
8. the "expected primary-expression before '__attribute__'" error occurred when compiling protobuf.

**What did you expect to see**
protobuf been compiled.
**What did you see instead?**
tensorflow-1.13.2/tensorflow/contrib/cmake/_build_mingw64/protobuf/src/protobuf/src/google/protobuf/port_def.inc:516:42: error: expected primary-expression before '__attribute__'
 PROTOBUF_EXPORT_TEMPLATE_TEST(MSVC_HACK, __declspec(dllexport));

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I'm trying compile tensorflow C++ library with mingw-w64 toolchain, as I need a little cross-compile to set -march= for some special cpu. the make file is generated by cmake. If bazel support setting -march= flags, let me know.

**Comment by Haffon** [comment]
I cloned the protobuf source alone and tried to compile with cmake+mingw, then duplicated the issue.

**Comment by erenkeskin** [comment]
I have the same issue after make command for compiling protobuf.

**Comment by lingme** [comment]
I use mingw32-make, too
