### ISSUE TITLE
Unable to read message options from descriptor file using Python

### ISSUE THREAD

**Issue by garo** [protocolbuffers/protobuf#6662]
**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: Python

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.3

**What did you do?**
Assuming we have this test.proto file:
```
syntax = "proto3";

import "google/protobuf/descriptor.proto";
extend google.protobuf.MessageOptions {
  string MyOption = 50001;
}

message MyMessage {
  option (MyOption) = "Hello, World!";
  int32 value = 1;
}
```
And that we compile it to both descriptor file and python file as `protoc test.proto -o test.protoset --python_out=.`

Then if you run this test.py application:
```
from google.protobuf.descriptor_pb2 import FileDescriptorSet

with open('test.protoset', mode='rb') as f:
  data = f.read()

fd = FileDescriptorSet.FromString(data)
# Try to print out the options but will not print anything
print("Options: " + str(fd.file[0].message_type[0].options))

import test_pb2
fd = FileDescriptorSet.FromString(data)
# This will work and prints out: [MyOption]: "Hello, World!"
print("Options: " + str(fd.file[0].message_type[0].options))
```

**What did you expect to see**
I was expecting to see both print() calls to print out the option.

I would expect that I can load the test.protoset file and be able to read the options set to the MyMessage. However this doesn't seem to be work unless I also import the generated test_pb2.py code.

If I look on the generated test.protoset file I can see that there is the "Hello, World!" string embedded, so the descriptor file does contain the options, but for some reason I cannot read it back.

**Comment by anandolee** [comment]
The test.protoset has embedded "Hello, World!" with extension number 50001 as wire format, to parse it into a known option (named MyOption in your case), the related info should be put into descriptor pool which import test_pb2.py does for protobuf pure python version. Without the import, this will be parsed into unknown fields and you can also see "Hello, Whorld!" but "MyOption" info is missing

**Comment by kalvdans** [comment]
@anandolee Could you please give a reason for closing the bug? (motivation / link to pull request etc)
