### ISSUE TITLE
py_proto_library target fails to build

### ISSUE THREAD

**Issue by beugley** [protocolbuffers/protobuf#6666]
**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.4

EXAMPLE 1:
Using the following BUILD file:
```
proto_library(
    name = "api_request_proto",
    srcs = [":api_request.proto"],
    deps = ["@com_google_protobuf//:any_proto"],
)

py_proto_library(
    name = "api_request_py_proto",
    srcs = [":api_request.proto"],
)
```
and the following proto file (note that it includes any.proto):
```
syntax = "proto3";
import "google/protobuf/any.proto";
package src.apis;

message ApiRequest {
    string path = 1;
    string method = 2;
    map<string, string> headers = 3;
    map<string, string> parameters = 4;
    google.protobuf.Any body = 5;
}
```

when I build the target with "bazel build //src/apis:api_request_py_proto", the build fails with the following error messages:
```
ERROR: /Users/beugley/unity/src/apis/BUILD:24:1: ProtoCompile src/apis/api_request_pb2.py failed (Exit 1) protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/darwin-fastbuild/bin' -I. src/apis/api_request.proto

Use --sandbox_debug to see verbose messages from the sandbox
google/protobuf/any.proto: File not found.
src/apis/api_request.proto:3:1: Import "google/protobuf/any.proto" was not found or had errors.
src/apis/api_request.proto:15:5: "google.protobuf.Any" is not defined.
Target //src/apis:api_request_py_proto failed to build
```

EXAMPLE 2:
Now trying the build with a slightly different BUILD file:
The "examples/BUILD" file shows examples in Java and C++.  In both cases, the <lang>_proto_library target includes a "deps" attribute that contains the label of the proto_library target.  If I try that same method using Python, I create this BUILD file:
```
proto_library(
    name = "api_request_proto",
    srcs = [":api_request.proto"],
    deps = ["@com_google_protobuf//:any_proto"],
)

py_proto_library(
    name = "api_request_py_proto",
    deps = [":api_request_proto"],
)
```

Then, when I build the target with "bazel build //src/apis:api_request_py_proto", the build fails with the following error messages:
```
ERROR: /Users/beugley/unity/src/apis/BUILD:24:1: in deps attribute of py_library rule //src/apis:api_request_py_proto: '//src/apis:api_request_proto' does not have mandatory providers: 'py' or 'PyInfo'. Since this rule was created by the macro 'py_proto_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_beugley/fe93a3bf08c8828f4818fde34e6c890e/external/com_google_protobuf/protobuf.bzl:441:16
ERROR: Analysis of target '//src/apis:api_request_py_proto' failed; build aborted: Analysis of target '//src/apis:api_request_py_proto' failed; build aborted
```

So, the dependent target of a py_proto_library can only be a py_proto_library, not a proto_library as it can be with the C++ and Java implementations.  Instead, I have to specify a "srcs" attribute for the actual proto file (as shown in example 1), and the build of that target fails because it can't find the any.proto dependency.

EXAMPLE 3
Furthermore, if I add a dependency for the any.proto file, I then have this BUILD file:
```
proto_library(
    name = "api_request_proto",
    srcs = [":api_request.proto"],
    deps = ["@com_google_protobuf//:any_proto"],
)

py_proto_library(
    name = "api_request_py_proto",
    srcs = [":api_request.proto"],
    deps = ["@com_google_protobuf//:any_proto"],
)
```

Then, when I build the target with "bazel build //src/apis:api_request_py_proto", the build fails with the following error messages:
```
ERROR: /Users/beugley/unity/src/apis/BUILD:24:1: no such target '@com_google_protobuf//:any_proto_genproto': target 'any_proto_genproto' not declared in package '' defined by /private/var/tmp/_bazel_beugley/fe93a3bf08c8828f4818fde34e6c890e/external/com_google_protobuf/BUILD and referenced by '//src/apis:api_request_py_proto_genproto'
ERROR: Analysis of target '//src/apis:api_request_py_proto' failed; build aborted: Analysis failed
```

So the py_proto_library can't have either the proto_library or any_proto as dependencies (examples 2 and 3), but it fails to build without them (example 1).

What is the correct way to build a py_proto_library target, with dependencies, for a proto file that imports any.proto?

**Comment by QiJune** [comment]
Any update on this? Thanks!

**Comment by dayfine** [comment]
This particular `py_proto_library`works very weird for whatever reason, maybe use github.com/stackb/rules_proto or https://github.com/grpc/grpc

**Comment by rogerhub** [comment]
I ran into this with another well-known type (WKT) and fixed it by adding `@com_google_protobuf//:protobuf_python` to dependencies.
