### ISSUE TITLE
Weird Errors from protoc while running on RHEL5_64

### ISSUE THREAD

**Issue by ronak2121** [protocolbuffers/protobuf#6668]
**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: C++/Java/JS

**What operating system (Linux, Windows, ...) and version?**
Red Hat Enterprise Linux 5, 64 bit

**What runtime / compiler are you using (e.g., python version or gcc version)**
Clang 8

**What did you do?**
I'm trying to compile a simple protobuf schema:

`syntax = "proto3";
package com.mycompany.protobufs;
option java_outer_classname = "SomeMessage";

message AssetDetails {
    string abc = 1;
    string def = 2;
    int32 ghi = 3;
    int32 jkl = 4;
    int32 mno = 5;
    double pqr = 6;
    double stu = 7;
}
`

**What did you expect to see**
Compilation Succeeds and code is generated

**What did you see instead?**

myFile.proto:16:5: "string" is not defined.
myFile.proto:18:5: "int32" is not defined.
myFile.proto:19:5: "int32" is not defined.
myFile.proto:20:5: "int32" is not defined.
myFile.proto:21:5: "double" is not defined.
myFile.proto:22:5: "double" is not defined.
myFile.proto:26:5: "int32" is not defined.
myFile.proto:27:5: "int32" is not defined.
myFile.proto:33:14: "int64" is not defined.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by ronak2121** [comment]
I built protobuf manually on my Linux host using cmake. The prebuilt binary works fine.

Is there some compilation step that’s missing here?

**Comment by ronak2121** [comment]
From my debugging of your source code; it looks like these data types are not registered to be built in types; and it's interpreting them to be custom data types that I've defined.

Still trying to find out how you've registered the base types and what is being skipped...

**Comment by ronak2121** [comment]
I figured out the issue is this constant initializer:

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/parser.cc#L88

which does not execute with clang.

**Comment by ronak2121** [comment]
Is there a particular option or something I have to specify to get this working with clang? If you move the const initialization into the constructor; then protoc works just fine.

**Comment by acozzette** [comment]
That is strange; we use Clang all the time and haven't run into any problems with that initializer.

**Comment by ronak2121** [comment]
What would you recommend we do? Is there a reason that we can't move the initialization into the constructor()? I understand you would lose the constant declaration if you did that...

**Comment by acozzette** [comment]
I think we first need to understand what's going wrong. If that initialization is not executing then it seems like something is wrong with the build.

**Comment by ronak2121** [comment]
I'd agree; hence I was wondering if you were aware of any particular clang parameters that would be needed here? Which version of clang have you used this successfully with?

**Comment by acozzette** [comment]
There shouldn't be any special Clang parameters necessary. I don't think we use a released Clang version, we just update very frequently to track ongoing Clang development.

The code for generating that table has been there almost unchanged for over 10 years and it isn't doing anything complicated, so I am guessing the problem has more to do with the build environment. For example your Linux distro might have its own protobuf package installed and perhaps your protoc binary is linking against that instead of the locally-built library.

**Comment by ronak2121** [comment]
I’ve checked and we only have these libs. I’ve been able to debug this problem with tons of cout statements tracing through; so I know it’s linking against the right binaries.

**Comment by ronak2121** [comment]
Compiling this code on RHEL5_64 with gcc fixed the problem. Using clang on linux didn't work.
