### ISSUE TITLE
Request for move only types for C++

### ISSUE THREAD

**Issue by DanielJamesCollier** [protocolbuffers/protobuf#6670]
Protobuf types in C++ have move constructors which is great! however It would be nice if we could markup a a type to be move only.

Maybe something like 
`option cc_move_only = true;`

Best
Daniel

**Comment by jorgbrown** [comment]
Matt -

Feature request for the editions proposal?

**Comment by fowles** [comment]
While we could add that as a feature, I don't think it is something we actually want to do.
