### ISSUE TITLE
Google::Protobuf::Any #pack and #unpack not implemented in any_pb.rb

### ISSUE THREAD

**Issue by ajaleelp** [protocolbuffers/protobuf#6677]
From what I could figure, `protoc` spits out the implementation of `pack` and `unpack` for select languages (such as PHP) but not for Ruby (and maybe others?). For Ruby, I can see this implemented in `google/protobuf/well_known_types.rb` instead. Can someone please clarify the reasoning behind this _differential treatment_? :) Or am I missing something here? Pretty new to this.

**Comment by TeBoring** [comment]
I think this is just implementation detail.
The way ruby does is easier for us to maintain.
