### ISSUE TITLE
min/max namespace collision with Winsock2.h

### ISSUE THREAD

**Issue by dkonik** [protocolbuffers/protobuf#6683]
Version: 3.9.1 etc.
Language: C++
OS: Windows 18932
Compiler: VS 2019 (c++ 2017, if that helps at all)
Output Type: Static Library

Issue Description:
If you have an enum defined in your proto file, and you include `winsock2.h` prior to including the generated `.h` file, you will get an error during compilation since `WinDef.h` defines a min and max macro. There are a few ways to get around this, but I won't be the one to make any suggestions.

Repro Steps:
1) Create a simple dummy proto file with an enum (I'll include an example that I can use to repro at the bottom)
**What did you expect to see**
2) Generate it
3) Create a simple new static library project which includes the protobuf lib (statically linked), the protobuf headers, and the generated files
4) If, in one of the files of the project, you do something like:
``` cpp
#include "test.pb.h"
#include <WinSock2.h>
``` 
It compiles fine. If, however, you reverse the order and do:
``` cpp
#include <WinSock2.h>
#include "test.pb.h"
```
It fails to compile.

Example Proto:
```
syntax = "proto3";

enum MessageType {
        // Reserved
	InvalidMessage = 0;
	// A header for stream, including the height, width, etc
	StreamHeaderMessage = 1;
}

// The header for a stream
message StreamHeader {
    uint32 Width = 1;
    uint32 Height = 2;
    uint32 FrameRate = 3;
}
```
I've verified that if I remove the enum, there are no errors.

Compiler output (reduced to the errors):
```
1>test.pb.h(68,99): error C2589:  '(': illegal token on right side of '::'
1>test.pb.h(68,99): error C2062:  type 'unknown-type' unexpected
1>test.pb.h(68,99): error C3805:  'type': unexpected token, expected either '}' or a ','
```
Where line 68 is the third line in the enum (the line with `min`):
```
enum MessageType : int {
  InvalidMessage = 0,
  StreamHeaderMessage = 1,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
```

**Comment by automotiveUser** [comment]
Hi @dkonik,

I am new on Google ProtoBuffers and I have the same issue. I found, that in the file `minwindef.h` (in C:\Program Files (x86)\Windows Kits\10\Include\<`version`>\shared\) there is a macro definition of `min` and `max` in a **global** scope.
Because of there are member functions `min` and `max` in `std::numeric_limits` too, this causes the fault. Of course the compilation succeeds, if the `*.pb.h` is include **before** including `minwindef.h` (or `WinSock2.h`, which implicitly includes `minwindef.h`).
I think the best choice would be, to change the implementation of ProtoBuffers to do not use min/max from `std::numeric_limits`.

**Comment by dkonik** [comment]
I feel like that's a pretty unreasonable ask. But maybe there is some change that can be made to ensure that they won't collide. FWIW, you can get around this issue by defined NOMINMAX before including winsock2.

**Comment by Mirko-von-Leipzig** [comment]
I have run into this issue as well, albeit in a more round-about fashion. I have inherited a project that uses both Thrift and Protobuf (don't ask).

Thrift includes Winsock2 so having any transient include chain reference the Thrift file first breaks the protobuffers.

**Comment by LeeClarkSystechOne** [comment]
I found adding '#undef' for min/max prior to including the protoc generated files removed a large set of compile errors, which started with the errors mentioned above. I used the following at the end of stdafx.h:

#include "grpc/grpc.h"
#include "grpcpp/channel.h"
#include "grpcpp/client_context.h"
#include "grpcpp/create_channel.h"
#include "grpcpp/security/credentials.h"

**#undef min
#undef max**
#include "test.pb.h"
#include "test.grpc.pb.h"

**Comment by acozzette** [comment]
Let me close this issue since it has been fixed by some logic in port_def.inc which temporarily undefines these min and max macros: https://github.com/protocolbuffers/protobuf/blob/f57ae5eac31d5322c8fcb350a6cdc13647e5ca53/src/google/protobuf/port_def.inc#L406

**Comment by go1001** [comment]
add_compile_definitions( NOMINMAX)
I add the above  im CmakefileList.txt,then It solved.
