### ISSUE TITLE
Provide C# support for garbage free parsing

### ISSUE THREAD

**Issue by dkonik** [protocolbuffers/protobuf#6686]
Language: C#

Problem: Protobuf creates new objects when parsing. As far as I can tell, there is no way to get around this if you have a "nested" type, or something like a `oneof`. It would be great if it supported parsing *into* an already existing object, or somehow taking in a factory that it would use to create objects.

**Comment by MaximGurschi** [comment]
If you use nested messages at least (so a field of a custom message type) then the generated code does not allocate if the reference is not null. However for oneof it does allocate.

One workaround for oneof is to modify the generated code behind yourself.
Or not use oneof and achieve oneof semantics using your own code.

**Comment by jtattermusch** [comment]
I acknowledge that being able to parse without needing allocations would be nice and it would be useful for some users (e.g. those who are super performance/latency sensitive), but making that happen would be a big undertaking and would require a lot of design work first.
I think at some point in the future Google.Protobuf might allow allocation free parsing, but there would need to be a clear plan for what needs to be done and how (and how to achieve that without breaking backwards compatibility).
Currently I don't have the bandwidth to work on such (highly complex, as there is a large number of cases that need to be taken into account) design and frankly it seems that the demand for such feature is quite low.
I don't think we are interested in solving this by a half baked approach of randomly adjusting things in different places (e.g. adjusting oneofs) without first investigating whether this whole "allocation free parsing" concept is feasible at all. Without a plan, we will likely make a few smaller changes (that don't really have much performance impact but make our codebase more complex) and then hit the wall after we discover that there's a blocker we didn't think of.
