### ISSUE TITLE
Data parsing crash

### ISSUE THREAD

**Issue by WZBbiao** [protocolbuffers/protobuf#6698]
**What version of protobuf and what language are you using?**
Version: master/v3.5.0 ++.
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
system:iOS13/iOS13.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
iOS13/iOS13.1

**What did you do?**
1. Receive server data for parsing
2. crash
3. error is "-[IMMessage mergeFromCodedInputStream:extensionRegistry:]: unrecognized selector sent to instance 0x11f109340"(ps:IMMessage is a Object inheritance GPBMessage)

**What did you expect to see**
fix

**What did you see instead?**

None of the other classes that inherit GPBMessage have a problem, except this one
The definition of this class in protobuf is：
message IMMessage {
    string msgId = 1;
    int32 priority = 2;
    int32 conversationType = 3;
    int32 contentType = 4;
    SimpleUser sender = 5;
    string peer = 6;
    int64 timestamp = 7;
    google.protobuf.Any content = 8;
}

**Anything else we should know about your project / environment**
It's ok under iOS13

**Comment by thomasvl** [comment]
There isn't much to go on here, so it is hard to guess what it might be.  If this reliably happens, I'm guessing there is a second `IMMessage` class that is getting loaded into the ObjC runtime that isn't a `GPBMessage` subclass, and that one is the one the ObjC runtime is picking, hence the failure.  You can check the console logs as the ObjC runtime does kick out some messages about duplicate ObjC classes being loaded.  You can use [objc_class_prefix](https://github.com/protocolbuffers/protobuf/tree/master/objectivec#objective-c-generator-proto-file-options) file option to put a prefix on the classes to avoid the collision if that is what is happening.

**Comment by WZBbiao** [comment]
Thanks for your reply, the problem has been solved because the ‘IMMessage’ class conflicts with ‘SafariServices.framework’, and IMMessage works after adding the prefix.
