### ISSUE TITLE
Outdated Utf8Decoder for Java?

### ISSUE THREAD

**Issue by gjajoo** [protocolbuffers/protobuf#6704]
**Java 9+**
java.lang.String now internally stores byte[] (i.e. encoded) and a coder directly instead of the char array it used to. Utf8.java has all kinds of decoders that read byte[] or ByteBuffer etc... to convert them to char[]. Then it calls public String(char value[], int offset, int count), which internally converts the char[] array back to a byte[] by encoding it!

**Proposed solution**
For Java 9+, with most common cases of LATIN1 strings, I think the idiomatic java calls to String constructor with byte[] and Charset - public String(byte bytes[], int offset, int length, Charset charset) should suffice. There's no need to decode+encode.

**Comment by elharo** [comment]
What changes are you proposing?
