### ISSUE TITLE
protoc usage is outdated, does not include go and dart options

### ISSUE THREAD

**Issue by manueltellez** [protocolbuffers/protobuf#6706]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: go version go1.12.9 windows/amd64

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. the usage does not mention the --go_out

**What did you expect to see**
all the available options for output in the usage

**What did you see instead?**
a non extensive list, it is missing both go and dart

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Current output is as follows:
…
 --cpp_out=OUT_DIR           Generate C++ header and source.
  --csharp_out=OUT_DIR        Generate C# source file.
  --java_out=OUT_DIR          Generate Java source file.
  --js_out=OUT_DIR            Generate JavaScript source.
  --objc_out=OUT_DIR          Generate Objective C header and source.
  --php_out=OUT_DIR           Generate PHP source file.
  --python_out=OUT_DIR        Generate Python source file.
  --ruby_out=OUT_DIR          Generate Ruby source file.
…

**Anything else we should know about your project / environment**

**Comment by manueltellez** [comment]
it appears that the registration for outputs and the usage generation happens here:

https://github.com/protocolbuffers/protobuf/blob/d0f91c863ae0fbb75b41460c8bbb786ade197a0f/src/google/protobuf/compiler/main.cc#L50-L58

**Comment by haberman** [comment]
I think this is working as intended. This usage information only shows information about code generators that are linked into `protoc` itself. Both Go and Dart are distributed separately and implemented as plugins, so they do not appear in this list.
