### ISSUE TITLE
identifier "GOOGLE_DCHECK" is undefined

### ISSUE THREAD

**Issue by automotiveUser** [protocolbuffers/protobuf#6710]
Hi,

I am using Visual Studio 2017 Professional and Protocol Buffers V 3.9.1.
I generated the header and source files depending on my proto files. I have multiple proto files but one of them is my "main" proto file which imports the other ones. In the pb.h of my "main" proto file I get the error, that the macro `GOOGLE_DCHECK` is undefined. I detected the definition of this macro in `google\protobuf\stubs\logging.h`. The header `logging.h` is included in my "main" pb.h file implicitly by including `google\protobuf\arenastring.h`

I detected, that after including `google\protobuf\port_def.inc` the macro `GOOGLE_DCHECK` is undefined. Is this a bug or is it my own mistake?

**Comment by iwita** [comment]
I also experience the same issue after generating my  `%.pb.h`  file from protoc.

**Comment by axmeyer** [comment]
Getting the same error!

I installed grpc and protobuf via vcpkg, if this makes any difference.

**Comment by jlipponen** [comment]
Same problem. First I installed protobuf from gRPC repository's master branch targeting protobuf 3.11.2, then from tag v1.26.0 targeting protobuf 3.8.0. I also tried installing the protobuf 3.11.3 from https://github.com/protocolbuffers/protobuf/releases/tag/v3.11.3

Every time I get the `identifier "GOOGLE_DCHECK" is undefined` error.

**Comment by axmeyer** [comment]
As I said here https://stackoverflow.com/questions/60043400/linking-grpc-on-windows-for-visualc/60073170#60073170 I solved it by linking to WS2_32.lib

But it seems it does not solve the problem for everyone.

**Comment by ShengHow95** [comment]
I hadthe same problem but **Disabling Precompiled Header** works for me.

**Project Properties** > **C/C++** > **Precompiled Headers** > **Not Using Precompiled Headers**

**Comment by GerwazyMiod** [comment]
> I had the same problem but **Disabling Precompiled Header** works for me.
> 
> **Project Properties** > **C/C++** > **Precompiled Headers** > **Not Using Precompiled Headers**

Worked like a charm, thank you !

**Comment by HiceS** [comment]
Disabling the pre-compiled headers does not in fact do it for me, 

Seems like I can build and compile the generated code but the grpcc/ includes generate this error for me no matter what I try to do.

**Comment by deepanshnagaria** [comment]
> I had the same problem but **Disabling Precompiled Header** works for me.
> 
> **Project Properties** > **C/C++** > **Precompiled Headers** > **Not Using Precompiled Headers**

this does not work for me... Is there any solution to it yet?

**Comment by axmeyer** [comment]
As said here: https://github.com/protocolbuffers/protobuf/issues/6710#issuecomment-582342753
I needed to link to WS2_32.lib in addition to disabling precompiled headers.

**Comment by matttm** [comment]
Neither of these seem to be resolving the issue for me.

**Comment by ajwhite-git** [comment]
I'm using 3.13 and VS17 and I'm getting this GOOGLE_DCHECK is undefined.  I've tried turning off precompiled headers and linking to WS2_32.lib but these solutions haven't worked for me.

**Comment by K4kTyC** [comment]
I tried to comment lines from first `#include <google/protobuf/port_def.inc>` to `#include <google/protobuf/port_undef.inc>` in generated header file. 

Error dissapeared and my app seems to work fine, but I'm not sure that this is a good solution. 

<img src ="https://user-images.githubusercontent.com/47088033/99889005-520e0600-2c62-11eb-877e-a12c4087924b.png" width="600">

**Comment by abdulwahabamin** [comment]
Has there been a solution to this problem? I am getting this on 3.14

**Comment by AaronViviano** [comment]
I've unfortunately run into the same problem. As mentioned previously turning off precompiled headers and linking to WS2_32.lib did not resolve the issue.

**Comment by AaronViviano** [comment]
After a few hours of investigation I found this post on [stackoverflow](https://stackoverflow.com/questions/44307127/how-to-use-google-protobuf-in-a-project-with-precompiled-headers/44471355#44471355). Here is a copy of the post in case it goes away:

> I resolved my problem by creating a static library called proto-objects (without PCH) and including all my *pb.h(cpp) files there. After it I link that library to every project where I need my protobuf objects. Profit! 
> <img width="290" alt="image2" src="https://user-images.githubusercontent.com/5307593/106369923-14d98a80-631b-11eb-9a94-1e119f42fd4f.png">
> Author: [Arman Oganesyan](https://stackoverflow.com/users/6232365/arman-oganesyan) via [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/#)

Then in my core .h file I linked to the proto_objects static library and included the file:
```
#include "..\proto_objects\proto\messaging.pb.h"
```

Note: Visual studio will still generate errors if the "*.pb.h" or "*.pb.cc" files are open in the editor, but the code compiles:

<img width="490" alt="image3" src="https://user-images.githubusercontent.com/5307593/106369995-d1cbe700-631b-11eb-8dae-71eed3ca5fc9.PNG">

**Comment by TengQinglong** [comment]
Has there been a solution to this problem? I have met this problem when I use VS2019 and I installed grpc by vcpkg
