### ISSUE TITLE
Failed update to version 3.10

### ISSUE THREAD

**Issue by puripurii** [protocolbuffers/protobuf#6712]
**What version of protobuf and what language are you using?**
Version: master/v3.10.0.rc-0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
For us to solve this issue #3120 I need to update the gem version to 3.10.0.rc-0. However I'm getting this error when I tried updating the gem.
```You have requested:
  google-protobuf = 3.10.0.rc.0

The bundle currently has google-protobuf locked at 3.9.2.
Try running `bundle update google-protobuf````

**Comment by rafi-kamal** [comment]
I've updated the Ruby Gem version to 3.10.0. Please let me know if that fixes the problem.
