### ISSUE TITLE
Generated C++: Maps with String keys will not compile with 64-bit MSVC with /WX 

### ISSUE THREAD

**Issue by jquesnelle** [protocolbuffers/protobuf#6723]
**What version of protobuf and what language are you using?**
Version: 3.8.0 (gRPC 1.23 submodule)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC x64 (Visual Studio 2019)

**What did you do?**
Generate from a protobuf with a map entry, e.g.
```protobuf
message Msg {
   map<string, Something> Dummy = 1;
}
```
Then, compile with `/WX` (equivalent to `-Werror`)

**What did you expect to see**
Generated C++ code compiles.

**What did you see instead?**
The generated C++ code will fail to compile. In the `ValidateKey` function:

```c++
 static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Dummy.key");
 }
```

The second parameter to `VerifyUtf8String` is an `int`, and MSVC produces the following error: 
`warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`

The solution is probably just to cast to `int` from `s->size()`, although this does technically mean that only strings up to 2 GB are supported.

**Comment by acozzette** [comment]
This is perfect timing because I just recently merged #6661 which should fix this. I don't think it made it into the 3.10 release but it will be in 3.11.
