### ISSUE TITLE
Changed PATH causes several targets to be rebuilt

### ISSUE THREAD

**Issue by prestonvanloon** [protocolbuffers/protobuf#6726]
**What version of protobuf and what language are you using?**
```
git_repository(
    name = "com_google_protobuf",
    commit = "09745575a923640154bcf307fba8aedff47f240a",
    remote = "https://github.com/protocolbuffers/protobuf",
    shallow_since = "1558721209 -0700",
)
```
For use with golang, but this bug seems language agnostic.

**What operating system (Linux, Windows, ...) and version?**

Linux amd64

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0  

**What did you do?**

Hermetic builds.

Changing paths in a local environment causes protobuf to rebuild. The specific use case is to run `bazel build` in terminal, then sync in Intellij which runs another bazel build with different PATH. Perhaps a minimal reproduction would be `PATH=$PATH:/bogus/bin bazel build //:some_target_with_proto_deps` 

[explanation.txt](https://github.com/protocolbuffers/protobuf/files/3688118/explanation2.txt)

See more context:
https://github.com/bazelbuild/intellij/issues/789

**What did you expect to see**

Nothing, targets already built.

**What did you see instead?**

Bazel rebuilds ~700 targets.

**Anything else we should know about your project / environment**

bazel verison  0.29.1

**Comment by jasonprado** [comment]
This repros for me on 29.3.
