### ISSUE TITLE
Conflicting documentation as to whether null values are permitted in a map

### ISSUE THREAD

**Issue by cosborne83** [protocolbuffers/protobuf#6730]
**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 7 x64

**What runtime / compiler are you using (e.g., python version or gcc version)**
.NET 4.7.2/VS 2017 (15.9.16)

**What did you do?**

Per the documentation here: https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#map

> Keys in the map are not permitted to be null; values may be if the corresponding singular field type would support null values.

However per the documentation here: https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/collections/map-field-t-key-t-value-

> Null values are not permitted in the map, either for wrapper types or regular messages.

**What did you expect to see**

Null values appear to be prohibited in a map, so the former reference should state that null values are not permitted.

**What did you see instead?**

Conflicting documentation.

**Comment by elharo** [comment]
null values are not permitted. Not sure where to edit this though.
