### ISSUE TITLE
Missing Input File

### ISSUE THREAD

**Issue by Widunder** [protocolbuffers/protobuf#6738]
Hello,
Trying to use protoc, but getting "Missing Input File" error message. The file is not missing, because I can navigate to it through Windows Explorer and it finds it. I've tried with "--proto_path" parameter and without like Google suggests, neither of these work.

`protoc -I=D:\myProject\myProject --csharp_out=D:\AnotherProject\AnotherProject --proto_path=D:\myProject\myProject\Common\folder\MyProto.proto`

Also tried
`protoc --proto_path=D:\myProject\myProject\Common\folder\MyProto.proto --csharp_out=D:\AnotherProject\AnotherProject`

How do I call this command?!

**Comment by acozzette** [comment]
The `--proto_path` flag is not for specifying the .proto file to generate code for, instead it's for specifying the top-level directory to search for .proto files. I think in your case the right command should be something like this: `protoc -I D:\myProject\myProject --csharp_out=D:\AnotherProject\AnotherProject Common\folder\MyProto.proto`

**Comment by Widunder** [comment]
I tried, this but it didn't work:
 `File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think)`

What I'm actually trying to achieve is to generate C# classes from .proto file. Not other way around.
Cheers

**Comment by Widunder** [comment]
Since this got closed and no one is going to come back to look at this again, I've opened a ticket in Stackoverflow, with much more description:
https://stackoverflow.com/questions/58278335/descriptor-proto-file-not-found-protoc-3-10-windows

**Comment by novas1r1** [comment]
Hi,
I ran into the same problem. Stackoverflow question is not there anymore. What did you do to fix it?
Best regards

**Comment by Widunder** [comment]
novas1r1 I never managed to solve it unfortunately, after spending hours and hours of researching solution for it, only to see error after error; I communicated it back to my colleagues, it was then decided that priority on it was low enough to ditch it altogether. But yeah, basically now we never ever use it

**Comment by novas1r1** [comment]
:( ohoh... hope I can figure it out because I really need it.

**Comment by deniplech** [comment]
I had the same problem and I solved it a little clumsily:

I opened the installation folder of protobuf with binary protoc.exe (C:\protoc-3.19.2-win64\bin) and copied there the .proto file from that I wanted to generate c# classes. Then I opened cmd there and insert this command: 
`protoc --csharp_out=. MyProto.proto`

MyProto.cs was generated in the same folder as MyProto.proto.

I hope that this helps somebody. :)

**Comment by Fras999** [comment]
I have the same exact problem but for golang not c# and it been like three days and while looking for solution and I didn't find til now so if there is any one can help me that's will be soooo helpful .

**Comment by Fras999** [comment]
> I had the same problem and I solved it a little clumsily:
> 
> I opened the installation folder of protobuf with binary protoc.exe (C:\protoc-3.19.2-win64\bin) and copied there the .proto file from that I wanted to generate c# classes. Then I opened cmd there and insert this command: `protoc --csharp_out=. MyProto.proto`
> 
> MyProto.cs was generated in the same folder as MyProto.proto.
> 
> I hope that this helps somebody. :)

I tried it the same way but in linux and it didn't work ...

**Comment by sparicharn-denaliai** [comment]
Ok I stuck on this problem for a loooong time. So if you're like me who love to copy and paste command from IDE/notepad/etc checked to see if you accidentally copy invisible characters... Or just try to type the command manually. I hope it help the next guy.

**Comment by Rahulc0789** [comment]
> I have the same exact problem but for golang not c# and it been like three days and while looking for solution and I didn't find til now so if there is any one can help me that's will be soooo helpful .
Hey man did you got any solution for this?

**Comment by Rahulc0789** [comment]
Feas999 Did you got any solution for the same.

**Comment by l-uuz** [comment]
Had the same issue on Windows. Solution was one of the following

```
protoc --proto_path="C:\path\to\protobuf\\" --java_out="C:\path\to\output" "C:\path\to\protobuf\filename.proto"
protoc --proto_path="C:/path/to/protobuf/" --java_out="C:/path/to/output" "C:/path/to/protobuf/filename.proto"
protoc --proto_path="C:/path/to/protobuf/" --java_out="C:/path/to/output" "filename.proto"
```

This was very horrible to find out. Relative paths are not working on Windows, I think.
