### ISSUE TITLE
Make the C# `FileDescriptor.Proto` property more accessible

### ISSUE THREAD

**Issue by nagytech** [protocolbuffers/protobuf#6741]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
I'm trying to access the `Proto` property on the `FileDescriptor` class in order to perform some reflective operations.  However, the property is currently internal and cannot be accessed.  

https://github.com/protocolbuffers/protobuf/blob/378231756f5290554b56aebb36f88eb31a0f4b21/csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs#L250

I have noticed that the _same property_ on the Java API is public.

https://github.com/protocolbuffers/protobuf/blob/166652fc6f4f44e47153d96d7c790a06a65a2617/java/core/src/main/java/com/google/protobuf/Descriptors.java#L90

**Describe the solution you'd like**
Change the modifier from 'internal' to 'public'.

**Describe alternatives you've considered**
I've currently checked out and built my own version of the C# protobuf API and plugins, but it's not sustainable.

**Additional context**
None.

**Comment by ObsidianMinor** [comment]
It's public in the Java API because it's immutable.  The C# lib doesn't have that same guarantee and didn't support proto2 before the next release, so the original proto can't be exposed. What reflection are you doing that you can't do with the provided API?

**Comment by nagytech** [comment]
I'm serialising the `FileDescriptorProto` object in order to send it to a remote host that may or may not have the corresponding .proto file locally.  If there is any other way I can do this safely without using the internal `Proto` property, please let me know.

**Comment by nagytech** [comment]
Sorry, I didn't look very hard -`SerializedData` might actually be what I'm looking for.
