### ISSUE TITLE
python: Using python dict to construct message with map to complex type raises an error

### ISSUE THREAD

**Issue by software-dov** [protocolbuffers/protobuf#6746]
Version: libprotoc 3.8.0 from pkg manager 
Language: Python 3.6.8 on Linux

All of the examples, existing code, and documentation for protobuf in Python that I've seen indicates that it's possible to construct instances of complex message types just using built-in lists and dicts. This is really useful since it removes a lot of the constructing-intermediate-objects boilerplate.
I'm running into a scenario where this automatic conversion doesn't work, though. It involves constructing a message with a field that is a map to a message type.

Minimal proto file for the examples below:
```proto
// mollusc.proto
syntax = "proto3";

package mollusc.map.example;

message Mollusc {
  map<string, Cephalopod> cephalopods = 1;
};

message Coleoid {
  Cephalopod cephalopod = 1;
};

message Gastropod {
  map<string, string> gastropods = 1;
};

message Cephalopod {
  string common_name = 1;
};
```

Generating the py library works fine:
```shell
$ protoc mollusc.proto --python_out=.
```

In an interactive python session (and in non-interactive code as well) the following works fine:
```py
import mollusc_pb2

squid = mollusc_pb2.Cephalopod(common_name="squid")
mollusc_pb2.Mollusc(cephalopods={"teuthida":squid})
```
and it generates a proto message with the following representation:

```shell
cephalopods {
  key: "teuthida"
  value {
    common_name: "squid"
  }
}
```

So far so good. The problem occurs when I try to bypass the temporary object by passing in a dict to the higher-level type's keyword param:
```py
mollusc_pb2.Mollusc(cephalopods={"teuthida":{"common_name":"squid"}})
```
generates the following error:
```shell
TypeError: Parameter to MergeFrom() must be instance of same class: expected mollusc.map.example.Cephalopod got dict.
```

Passing in a dictionary as a keyword param works to create a singleton attribute (i.e. constructing a `Coleoid` from a dictionary works fine), and passing in a dictionary works for a message attribute that's a map from a primitive type to a primitive type (i.e. constructing a `Gastropod` from a dictionary also works fine).
The problem seems to be the map construction when the value type is not a primitive.

Is this a known limitation of protobuf in Python? Is there a workaround that means I don't have to construct an intermediate object? I haven't seen anything in the mailing list or issues that seems to match this particular problem.

My particular use case involves auto-generated code that constructs protobuf messages; being forced to use intermediate objects would severely complicate generation due to naming and message type awareness

**Comment by anandolee** [comment]
It is not limit for message map, this is limit for nested messages, repeated message field and message map field. The correct way to do the construction should give the message instead like:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/reflection_test.py#L165

For map field you can take this test as an example:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/message_test.py#L2278
