### ISSUE TITLE
yang and proto3，yang allow dash signbol，but the proto3 doesn't allow it as the message name

### ISSUE THREAD

**Issue by moranxy** [protocolbuffers/protobuf#6763]
For the message names can't have a dash in them because that would cause problems in many languages--e.g. in C++ Search-Request would turn into three separate tokens. The protobuf style guide would recommend SearchRequest, though you could in principle also do searchrequest.
But the problem we are now experiencing is due to the problem of yang and proto3. In the yang file, the dash is allowed to be named, but we will support the data table of yang to support protobuf. Encountered such a problem. In rfc7950 The YANG 1.1 Data Modeling Language, the modulename of yang is specified as follows.such as：
module {
https://tools.ietf.org/html/rfc7950
If it's a proto syntax change, is it for proto2 or proto3? proto3
If it's about generated code change, what programming language? C++

**Comment by acozzette** [comment]
Can you just replace the dash with an underscore when converting YANG names to protobuf names?

**Comment by moranxy** [comment]
I can replace the dash with an underscore in my project, but it causes the yang differents with the proto. The output data in gpb will be different with the yang in xml encoding, although  the data content is same. Therefore, the user has different names of the data columns caused by the same data but different coding modes, and the difficulty of data analysis by the data collector is increased.
I hope I can have some other solutions.thanks

**Comment by moranxy** [comment]
> Can you just replace the dash with an underscore when converting YANG names to protobuf names?

I can replace the dash with an underscore in my project, but it causes the yang differents with the proto. The output data in gpb will be different with the yang in xml encoding, although the data content is same. Therefore, the user has different names of the data columns caused by the same data but different coding modes, and the difficulty of data analysis by the data collector is increased.
I hope I can have some other solutions.thanks

**Comment by acozzette** [comment]
Sorry but I don't think we can easily add support for dashes in message or field names. I think the best workarounds would be either converting the dashes to underscores when going from yang to protobuf, or else just avoiding dashes altogether in yang.
