### ISSUE TITLE
Need notarization in macOS Catalina

### ISSUE THREAD

**Issue by onmyway133** [protocolbuffers/protobuf#6764]
When running protoc in macOS Catalina, I get `macOS cannot verify the developer of “protoc”.` I think this executable needs to be notarized

**Comment by thomasvl** [comment]
This is likely from the download getting tagged by the OS/browser - so you can probably just strip off the attribute via: `xattr -d com.apple.quarantine path/to/protoc`.

(or download source and build protoc to avoid it getting quarantine)

**Comment by deannagarcia** [comment]
We are aware of this issue and are working to fix it but unfortunately it's requiring more work than we hoped to properly get certification. Closing this bug since it's similar to #9397 and will update progress there.
