### ISSUE TITLE
GCC compilation warnings regarding implicit conversions

### ISSUE THREAD

**Issue by bahm-lgs** [protocolbuffers/protobuf#6781]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux/aarch64

**What runtime / compiler are you using (e.g., python version or gcc version)**
aarch64-linux-gnu-gcc (Linaro GCC 7.2-2017.11-rc1) 7.2.1 20171011

**What did you do?**
1) compile the proto file with --cpp_out to c++ sources
2) compile the generated code with aarch64-linux-gnu-gcc with -Wall switch

**What did you expect to see**
No compiler warnings

**What did you see instead?**
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(91,27): warning : conversion to 'char' from 'int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(95,27): warning : conversion to 'char' from 'int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(181,36): warning : conversion to 'char' from 'int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(181,36): warning :      if ('A' <= *i && *i <= 'Z') *i += 'a' - 'A';
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(181,36): warning :                                  ~~~^~~~~~~~~~~~
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(189,36): warning : conversion to 'char' from 'int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(189,36): warning :      if ('a' <= *i && *i <= 'z') *i += 'A' - 'a';
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(189,36): warning :                                  ~~~^~~~~~~~~~~~
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(360,18): warning : conversion to 'google::protobuf::int32 {aka int}' from 'long int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(360,18): warning :      return strtol(nptr, endptr, base);
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(360,18): warning :             ~~~~~~^~~~~~~~~~~~~~~~~~~~
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(367,19): warning : conversion to 'google::protobuf::uint32 {aka unsigned int}' from 'long unsigned int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(367,19): warning :      return strtoul(nptr, endptr, base);
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\stubs\strutil.h(367,19): warning :             ~~~~~~~^~~~~~~~~~~~~~~~~~~~
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\parse_context.h(127,11): warning : conversion to 'int' from 'long int' may alter its value [-Wconversion]
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\parse_context.h(127,11): warning :      limit += ptr - buffer_end_;
Google.Protobuf.Aarch64.Lib.3.8.0\build\native\include\google\protobuf\parse_context.h(127,11): warning :      ~~~~~~^~~~~~~~~~~~~~~~~~~~

**Anything else we should know about your project / environment**
The c++ sources are generated with MSVC compiler on Windows.
The generated sources are then cross-compiled for aarch64 using x86/64 Linux gcc

**Comment by cculianu** [comment]
LOL. Does not surprise me one bit.  It seems google does  C++ as if it were C... and it shows.

**Comment by jorgbrown** [comment]
We do not support -Wall because it is designed to be overeager.  Adding 'a' - 'A' to a char in order to make it lowercase is a common idiom and uglifying it with a bunch of static_cast doesn't improve the code, IMO.
