### ISSUE TITLE
Compile warning when built with thread sanitizer

### ISSUE THREAD

**Issue by wesleyw72** [protocolbuffers/protobuf#6789]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
`gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) `

**What did you do?**
1. `bazel build //:protoc_lib --copt="-fsanitize=thread"`

**What did you expect to see**
No warnings, as seen when run without thread sanitizer.

**What did you see instead?**
```
INFO: From Compiling src/google/protobuf/util/field_comparator.cc:
src/google/protobuf/util/field_comparator.cc: In member function 'virtual google::protobuf::util::FieldComparator::ComparisonResult google::protobuf::util::DefaultFieldComparator::Compare(const google::protobuf::Message&, const google::protobuf::Message&, const google::protobuf::FieldDescriptor*, int, int, const google::protobuf::util::FieldContext*)':
src/google/protobuf/util/field_comparator.cc:128:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```

**Anything else we should know about your project / environment**
Interestingly, trying the same thing on macOS with clang doesn't give the same warning. It could well be a `gcc` bug. We depend on protobuf and have `-Wall, -Werror` set so this actually breaks our build when running thread sanitizer. We've had to specifically disable these warnings to get around this.

**Comment by jorgbrown** [comment]
We don't support -Wall, and we especially don't support a compiler that shows a warning that is incorrect.
