### ISSUE TITLE
Integer overflow : zero_copy_stream_impl_lite.cc :196 

### ISSUE THREAD

**Issue by mulamalla** [protocolbuffers/protobuf#6796]
int CopyingInputStream::Skip(int count) {
  int skipped = 0;

  skipped is signed integer and can overflow in line 196 and signed integer overflow is undefined behavior. Suggess change skipped to unsigned integer.
  skipped += bytes;

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/io/zero_copy_stream_impl_lite.cc#L196

**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
C++17

**Comment by haberman** [comment]
Changing signed to unsigned wouldn't really help. If overflow is actually possible (which I'm not sure it is) then unsigned might avoid UB, but the code would still be incorrect.
