### ISSUE TITLE
What is the LICENSE of protobuf?

### ISSUE THREAD

**Issue by bssung** [protocolbuffers/protobuf#6798]
Is all modules and all files of protobuf under BSD LICENSE ?

**Comment by ST-DDT** [comment]
Text: https://github.com/protocolbuffers/protobuf/blob/master/LICENSE

````xml
<name>3-Clause BSD License</name>
<url>https://opensource.org/licenses/BSD-3-Clause</url>
<distribution>repo</distribution>
````

Source: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.10.0/protoc-3.10.0.pom
