### ISSUE TITLE
Unused parameter warning (with fix).

### ISSUE THREAD

**Issue by AustinSchuh** [protocolbuffers/protobuf#68]
I'm seeing the following warning when building code with all the warnings enabled.  The diff at the end of the file fixes it.

command is In file included from test.pb.cc:5:
In file included from test.pb.h:23:
In file included from google/protobuf/message.h:120:
google/protobuf/descriptor.h:1283:21: error: unused parameter 'filename' [-Werror,-Wunused-parameter]
      const string& filename,      // File name in which the error occurred.
                    ^
google/protobuf/descriptor.h:1284:21: error: unused parameter 'element_name' [-Werror,-Wunused-parameter]
      const string& element_name,  // Full name of the erroneous element.
                    ^
google/protobuf/descriptor.h:1285:22: error: unused parameter 'descriptor' [-Werror,-Wunused-parameter]
      const Message\* descriptor,   // Descriptor of the erroneous element.
                     ^
google/protobuf/descriptor.h:1286:21: error: unused parameter 'location' [-Werror,-Wunused-parameter]
      ErrorLocation location,      // One of the location constants, above.
                    ^
google/protobuf/descriptor.h:1287:21: error: unused parameter 'message' [-Werror,-Wunused-parameter]
      const string& message        // Human-readable error message.
                    ^

diff src/google/protobuf/message.h /tmp/protobuf/src/google/protobuf/message.h 
392,393c392,393
<   virtual bool HasOneof(const Message& /_message_/,
## <                         const OneofDescriptor\* /_oneof_descriptor_/) const {

>   virtual bool HasOneof(const Message& message,
>                         const OneofDescriptor\* oneof_descriptor) const {
> 397,398c397,398
> <   virtual void ClearOneof(Message\* /_message_/,
> ## <                           const OneofDescriptor\* /_oneof_descriptor_/) const {}
> 
>   virtual void ClearOneof(Message\* message,
>                           const OneofDescriptor\* oneof_descriptor) const {}
> 403,404c403,404
> <       const Message& /_message_/,
> ## <       const OneofDescriptor\* /_oneof_descriptor_/) const {
> 
> ```
>   const Message& message,
>   const OneofDescriptor* oneof_descriptor) const {
> ```

**Comment by arhuaco** [comment]
This makes the build fail when you treat warnings as errors. It happened with clang++, not with gcc.

**Comment by arhuaco** [comment]
Hi. I'm trying to build treating warnings as errors and this is blocking this move. Thanks.

**Comment by AustinSchuh** [comment]
https://github.com/google/protobuf/pull/70 was merged, closing this bug.  There may be more.  Feng has been very open to pull requests in the past for these fixups, so please put one together to help!
