### ISSUE TITLE
libprotoc.so.22 file not found but the installation of protobuf-all-3.10.0 installed libprotoc.so.21 !!!

### ISSUE THREAD

**Issue by marcoippolito** [protocolbuffers/protobuf#6800]
In Ubuntu 18.04.02 Server Edition I downloaded from here [https://github.com/protocolbuffers/protobuf/releases/tag/v3.10.0](url) the protobuf-all-3.10.0.zip and, following the indications here [https://github.com/protocolbuffers/protobuf/blob/master/src/README.md](url) I installed in /usr/local/lib/ the libraries:

    (base) marco@pc:/usr/local/lib$ ls -lah | grep "libproto*"
    -rw-r--r--  1 root root   14M Oct 25 11:27 libprotobuf-lite.a
    -rwxr-xr-x  1 root root  1011 Oct 25 11:27 libprotobuf-lite.la
    lrwxrwxrwx  1 root root    26 Oct 25 11:27 libprotobuf-lite.so -> libprotobuf-lite.so.21.0.0
    lrwxrwxrwx  1 root root    26 Oct 25 11:27 libprotobuf-lite.so.21 -> libprotobuf-lite.so.21.0.0
    -rwxr-xr-x  1 root root  5.3M Oct 25 11:27 libprotobuf-lite.so.21.0.0
    -rw-r--r--  1 root root   88M Oct 25 11:27 libprotobuf.a
    -rwxr-xr-x  1 root root   976 Oct 25 11:27 libprotobuf.la
    lrwxrwxrwx  1 root root    21 Oct 25 11:27 libprotobuf.so -> libprotobuf.so.21.0.0
    lrwxrwxrwx  1 root root    21 Oct 25 11:27 libprotobuf.so.21 -> libprotobuf.so.21.0.0
    -rwxr-xr-x  1 root root   34M Oct 25 11:27 libprotobuf.so.21.0.0
    -rw-r--r--  1 root root  136M Oct 25 11:27 libprotoc.a
    -rwxr-xr-x  1 root root   992 Oct 25 11:27 libprotoc.la
    lrwxrwxrwx  1 root root    19 Oct 25 11:27 libprotoc.so -> libprotoc.so.21.0.0
    lrwxrwxrwx  1 root root    19 Oct 25 11:27 libprotoc.so.21 -> libprotoc.so.21.0.0
    -rwxr-xr-x  1 root root   45M Oct 25 11:27 libprotoc.so.21.0.0
    (base) marco@pc:/usr/local/lib$ 

Following these indications: [https://developers.google.com/protocol-buffers/docs/cpptutorial](url) I tried to compile the protobuffer of the example:

    (base) marco@pc:~/protobuf-3.10.0/examples$ protoc -I=/usr/local/include -cpp_out=. 
    $SRC_DIR/addressbook.proto
    protoc: error while loading shared libraries: libprotoc.so.22: cannot open shared object file: No 
    such file or directory

How to solve the problem?

Marco

**Comment by marcoippolito** [comment]
Solved. It was a problem of duplicate protoc

**Comment by kkz003** [comment]
> Solved. It was a problem of duplicate protoc
Dear marco ippolito
I have same problem with yours.
Could you tell me your way to solve this issue?
