### ISSUE TITLE
CodedOutputStream was writing to a flat byte array and ran out of space.

### ISSUE THREAD

**Issue by daveyostcom** [protocolbuffers/protobuf#6806]
**What version of protobuf and what language are you using?**
Version: master/v3.10.0
Language: C#
OS: macOS 10.14.6
Runtime: dotnetcore 3.0 / C# 8.0

1. I ran my server, which writes a small protobuf every few seconds to a bidi stream
2. Wait for a dozen or so of these writes.

**What did you expect to see**
no errors from grpc or protobuf

**What did you see instead?**
```
Google.Protobuf.CodedOutputStream+OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
  at at Google.Protobuf.CodedOutputStream.RefreshBuffer()
  at at Google.Protobuf.CodedOutputStream.WriteRawByte(Byte value)
  at at Google.Protobuf.CodedOutputStream.WriteRawVarint32(UInt32 value)
  at at Google.Protobuf.CodedOutputStream.WriteInt32(Int32 value)
  at Protobuf.PortData.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:4814
  at at Google.Protobuf.CodedOutputStream.WriteMessage(IMessage value)
  at Protobuf.UpdatesProto.Types.Update.Types.Value.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:3770
  at at Google.Protobuf.CodedOutputStream.WriteMessage(IMessage value)
  at Protobuf.UpdatesProto.Types.Update.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:3581
  at at Google.Protobuf.CodedOutputStream.WriteMessage(IMessage value)
  at at Google.Protobuf.FieldCodec.<>c__32`1.<ForMessage>b__32_1(CodedOutputStream output, T value)
  at at Google.Protobuf.Collections.RepeatedField`1.WriteTo(CodedOutputStream output, FieldCodec`1 codec)
  at Protobuf.UpdatesProto.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:3378
  at at Google.Protobuf.CodedOutputStream.WriteMessage(IMessage value)
  at Protobuf.RpcCommandEvent.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:904
  at at Google.Protobuf.CodedOutputStream.WriteMessage(IMessage value)
  at Protobuf.RpcCommandEventToClient.WriteTo(CodedOutputStream output) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/Fs.cs:437
  at at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
  at Protobuf.FS.<>c.<.cctor>b__10_1(RpcCommandEventToClient arg) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcProtobuf/obj/Debug/netstandard2.1/FsGrpc.cs:18
  at at Grpc.Core.Marshaller`1.EmulateContextualSerializer(T message, SerializationContext context)
  at at Grpc.Core.Internal.AsyncCallBase`2.UnsafeSerialize(TWrite msg)
  at at Grpc.Core.Internal.AsyncCallBase`2.SendMessageInternalAsync(TWrite msg, WriteFlags writeFlags)
  at at Grpc.Core.Internal.AsyncCallServer`2.SendMessageAsync(TResponse msg, WriteFlags writeFlags)
  at at Grpc.Core.Internal.ServerResponseStream`2.WriteAsync(TResponse message)
  at GrpcServer.GrpcService.<serviceRpcCommandEventsToClientQueue>g__writeToClient|13_0(IServerStreamWriter`1 streamToClient, RpcCommandEventToClient e) in /Volumes/dyd38-240gb/Users/yost/Desktop/SMC/Cascade 2.0/fs/csharp/GrpcServer/GrpcService.cs:165
```

My server has only a minuscule amount of activity and is not crashing for any other reason, so I can't see how it would be running out of space.

btw, if "out of space" means something local to protobuf and doesn't mean running out of heap space, I think the message should be worded differently.

**Comment by daveyostcom** [comment]
Also happens with 3.9.1 and 3.9.2, each of which I used until the next rev was released.
This started happening to me recently, so it seems not to be a recent regression in protobuf.

**Comment by ObsidianMinor** [comment]
What is the definition of the message you're writing? Out of space in this instance likely means the message is misreporting it's length which means some code-gen is miscalculating how long it is.

**Comment by daveyostcom** [comment]
I should have said that runs fail after a different number of messages and in different places within the message. 
[x.proto.txt](https://github.com/protocolbuffers/protobuf/files/3776914/x.proto.txt)

**Comment by ObsidianMinor** [comment]
`ToByteArray` should always make the same output with the same message value as it's pure (for the sake of this discussion). So that means something in the message is misreporting it's length which could be a problem with code-gen or the library.

Either that or the message is being used on multiple threads and is being modified after the size calculation has been performed, which means when it's written to the array, it may have a different size.

**Comment by daveyostcom** [comment]
My server always calls TryWrite from the same thread. The rationale for using a bounded channel is this: there are two classes of message the server might send: essential messages and nonessential messages. What to do if TryWrite fails? Discard a nonessential message but retry an essential message until it is accepted. 10,000 is a wild guess at this stage for the bounded size of the channel.

BTW, in my current test case, every few times the server sends a nonessential message, it sends another within microseconds.
```
           ...
           sendCommandToClientsChannel = Channel.CreateBounded<RpcCommandJob>(10_000);
           ...

    public void sendToClient(IServerStreamWriter<RpcCommandEventToClient> streamToClient,
                                                 RpcCommandEventToClient message) {
      var job = new RpcCommandJob(message, streamToClient);
      if (!sendCommandToClientsChannel.Writer.TryWrite(job)) {
        // todo should notify client(s) when nonessential messages have been dropped.
        Console.WriteLine("gRPC buffer full");  // So far, in testing, this has never been called.
      }
    }
```
I put in a trace to print
`   "WriteMessage " + Thread.CurrentThread.ManagedThreadId`
at CodedOutputStream:303
```
300        public void WriteMessage(IMessage value)
301        {
302            WriteLength(value.CalculateSize());
303            value.WriteTo(this);                <--- tracepoint here
304        }
```
and I get
```
...
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 4
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 14
WriteMessage 14
WriteMessage 14
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 13
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
WriteMessage 5
Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Diagnostics.StackTrace.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Diagnostics.StackTrace.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Diagnostics.StackTrace.dll was not found or failed to read
Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Metadata.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Metadata.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Metadata.dll was not found or failed to read
Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Collections.Immutable.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Collections.Immutable.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Collections.Immutable.dll was not found or failed to read
Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.IO.MemoryMappedFiles.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.IO.MemoryMappedFiles.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.IO.MemoryMappedFiles.dll was not found or failed to read
```

**Comment by ObsidianMinor** [comment]
The issue with multithreading isn't writing messages on multiple threads, it's writing a message on one thread *while another thread* is mutating it.

For example we have on one thread:
```cs
void ToByteArray(this IMessage message)
{
    var length = message.CalculateSize();
```
but on another thread with the same message passed to `ToByteArray`:
```cs
message.Int32Value = 128; // if this was <127, the size of the message is increased by 1
```
and continuing on the first thread:
```cs
var array = new byte[length]; // the original length before the 2nd thread mutated the message and increased it's size
var output = new CodedOutputStream(array);
message.WriteTo(output);
```

Again this could just be an issue caused by code-gen / library changes so I'll continue checking for any possible mistakes made to code-gen recently. But if it's only been happening recently then we can't rule out accidental thread-unsafety.

**Comment by daveyostcom** [comment]
> The issue with multithreading is writing a message on one thread while another thread is mutating it.

You're talking about gRPC's threads, right? I am certain that my TryWrite calls happen serially, from the same thread.

BTW, I changed my test case so it doesn't do two writes in quick succession. It's been 30 minutes, and it hasn't failed yet.

**Comment by ObsidianMinor** [comment]
Just any threads or async code, since I doubt gRPC is mutating your specific message.

**Comment by daveyostcom** [comment]
So is it my problem or gRPC's problem?

**Comment by ObsidianMinor** [comment]
Could be yours is what I'm saying.

**Comment by daveyostcom** [comment]
The streaming example (RouteGuide) uses WriteAsync(). I use TryWrite() on a bounded channel. Is there an example that uses TryWrite()? Is there an automated test that does two TryWrite() calls in rapid succession? Is that not supposed to work?

**Comment by daveyostcom** [comment]
Silly me. I am in fact writing with `await stream.WriteAsync()`. The message is created, put into a queue with `TryWrite()`, taken from the queue, then written to gRPC with `WriteAsync()`, then discarded, so nothing is touching the message after it's handed to `WriteAsync()`. Sorry I was confused about this code, which I wrote quite a while ago. (The queue I'm using is a System.Threading.Channels.Channel<>. I was fuzzily thinking that this channel was a gRPC channel.) I'll see if I can reproduce the problem in the RouteGuide example code.

**Comment by daveyostcom** [comment]
Silly me. Yes, turns out the code is trying to reuse the message in an attempt to avoid GC. Thanks for your patience!

**Comment by radityagumay** [comment]
> Silly me. Yes, turns out the code is trying to reuse the message in an attempt to avoid GC. Thanks for your patience!

I am currently trying to achieve the same thing. At the moment, I am attempting to reuse the message and mutate certain fields at runtime. The main reason for this is to avoid excessive object allocation.

**Comment by somePeopleFireAndWood** [comment]
> The issue with multithreading isn't writing messages on multiple threads, it's writing a message on one thread _while another thread_ is mutating it.
> 
> For example we have on one thread:
> 
> ```cs
> void ToByteArray(this IMessage message)
> {
>     var length = message.CalculateSize();
> ```
> 
> but on another thread with the same message passed to `ToByteArray`:
> 
> ```cs
> message.Int32Value = 128; // if this was <127, the size of the message is increased by 1
> ```
> 
> and continuing on the first thread:
> 
> ```cs
> var array = new byte[length]; // the original length before the 2nd thread mutated the message and increased it's size
> var output = new CodedOutputStream(array);
> message.WriteTo(output);
> ```
> 
> Again this could just be an issue caused by code-gen / library changes so I'll continue checking for any possible mistakes made to code-gen recently. But if it's only been happening recently then we can't rule out accidental thread-unsafety.

I use message.toByteArray() in a concurrent environment, and this problem does occur. But what I don't understand is that even if multiple threads calculate getSerializedSize() concurrently, the result should be the same value. Why is there a calculation error?

**Comment by somePeopleFireAndWood** [comment]
> > The issue with multithreading isn't writing messages on multiple threads, it's writing a message on one thread _while another thread_ is mutating it.
> > For example we have on one thread:
> > ```cs
> > void ToByteArray(this IMessage message)
> > {
> >     var length = message.CalculateSize();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but on another thread with the same message passed to `ToByteArray`:
> > ```cs
> > message.Int32Value = 128; // if this was <127, the size of the message is increased by 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and continuing on the first thread:
> > ```cs
> > var array = new byte[length]; // the original length before the 2nd thread mutated the message and increased it's size
> > var output = new CodedOutputStream(array);
> > message.WriteTo(output);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Again this could just be an issue caused by code-gen / library changes so I'll continue checking for any possible mistakes made to code-gen recently. But if it's only been happening recently then we can't rule out accidental thread-unsafety.
> 
> I use message.toByteArray() in a concurrent environment, and this problem does occur. But what I don't understand is that even if multiple threads calculate getSerializedSize() concurrently, the result should be the same value. Why is there a calculation error?

In a concurrent environment, I will set a new value for the builder's field in one thread, call the build() method of the same builder object, and call the toByteArray method of the same mesaage object in several other threads.
It is worth emphasizing that 1. I will not add to the collection of builders that have been placed in the concurrent environment. All collections are created in a single thread to create a builder object, fill the collection, and after the filling is completed, assign this builder object to other builders. ;2. All builder objects will not be set filed in multiple threads. For a builder object, field will only be set in one thread.
I can't understand why this exception occurs.
The probability of this exception occurring in my program is very low, probably one in hundreds of millions.

**Comment by somePeopleFireAndWood** [comment]
> ```cs
> the original length before the 2nd thread mutated the message and increased it's size
> ```

I read your statement again and I don't understand it. The field on the message should be can not mutating.
