### ISSUE TITLE
CodedOutputStream :GC is generated when encoding

### ISSUE THREAD

**Issue by sunrui19941128** [protocolbuffers/protobuf#6814]
public byte[] Encode(int id,IMessage msg)
        {
            using (MemoryStream rawOutput = new MemoryStream())
            {
                using (CodedOutputStream output = new CodedOutputStream(rawOutput))
                {
                    output.WriteEnum(id);
                    output.WriteMessage(msg);
                    output.Flush();
                    return rawOutput.ToArray();
                }
            }
        }

In Unity, every time this code is encoded, a considerable amount of GC will be generated, which is about 5k per call, or more than 200 k per frame

**Comment by sunrui19941128** [comment]
Thanks,And that's what I've done since then. I've done dynamic computation of size and then I've optimized a lot of memory by opening up a little bit.

**Comment by jtattermusch** [comment]
In addition to what @ObsidianMinor  has said, we are also planning a new serialization/deserialization API that can avoid allocations completely (at least in some cases).
The WIP is here (but it's probably going to take a bit until it lands as the change is not trivial) https://github.com/protocolbuffers/protobuf/pull/5888
