### ISSUE TITLE
python keyword Error

### ISSUE THREAD

**Issue by damingupup** [protocolbuffers/protobuf#6815]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.7.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Mac/Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
python3.6.5
**What did you do?**
If I write this:
`enum MailStatus {
    None = 0;  
}`
 The None is keyword in python.
`can't assign to keyword`

**Comment by anandolee** [comment]
Protobuf Python keywords are working with getattr and setattr, see this test as an example:

https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/keywords_test.py

related .proto file is defined in:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/more_messages.proto#L57
