### ISSUE TITLE
Property named isNull conflicts with NSObject's category method with same name 

### ISSUE THREAD

**Issue by jaankoi** [protocolbuffers/protobuf#6825]
**What version of protobuf and what language are you using?**
Version: 3.8.0
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
macOS Mojave 10.14.6

**What did you do?**
We have a proto file containing following definition

message TypedValue {

	//!< Data type.
	Datatype type = 1;

	//!< Is the value NULL.
	bool is_null = 2;

	//!< The value data as a union, if not NULL.
	TypedValueUnion data = 3;
}

Now the "is_null" gets compiled so that the property name is isNull. But isNull is defined in NSObject's private categories:

https://github.com/xybp888/iOS-Header/blob/master/13.0/PrivateFrameworks/CalendarFoundation.framework/NSObject-CalClassAdditions.h

https://github.com/xybp888/iOS-Header/blob/master/13.0/PrivateFrameworks/CalDAV.framework/NSObject-CALExtensions.h

The code compiles fine, but when running and using the isNull property, one of the implementations in those categories gets executed causing wrong behaviour.

**What did you expect to see**
The property name for "is_null" should be escaped in the compilation so that it doesn't conflict with the method defined in NSObject's categories.

A related change that has been merged already:
https://github.com/protocolbuffers/protobuf/pull/5289

**Comment by thomasvl** [comment]
Since those are private to the frameworks, they aren't actually documented api, so basically those private frameworks are in the wrong if they get loaded into user space because they could conflict with what an app has done.  They should be prefixing them to not take part of the developers namespace.  I'd suggest you file a radar/feedback against Apple since they are being exposed in user processes and can then conflict.

And if we did add a remapping for this, it would break any existing code using isNull that works just fine because they don't load those frameworks.

**Comment by thomasvl** [comment]
ps - we did write a script to help datamine the public selectors: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/objectivec/method_dump.sh, that's how we generally try to avoid this.  But a private framework doing something like this is just about impossible to avoid.

**Comment by jaankoi** [comment]
I agree that this is more a bug on Apple's side. They definitely should prefix methods added to base classes via categories.

**Comment by thomasvl** [comment]
Can you include the feedback/radar number you got for filing this with them for anyone else that happens to come across this issue?

**Comment by jaankoi** [comment]
Here is the feedback number FB7457130.

**Comment by thomasvl** [comment]
Thanks. I'm going to close this since there isn't something to be done on this side.
