### ISSUE TITLE
Add varargs variant of addAllFoo to generated Java code

### ISSUE THREAD

**Issue by TzviPM** [protocolbuffers/protobuf#6827]
**What language does this apply to?**
Java (generated code change)

**Describe the problem you are trying to solve.**
For the java proto builder, the method `Builder addAllFoo(Iterable<? extends $type$> values)` requires an `Iterable` argument. I have found myself invoking this via:

```java
builder.addAllFoo(
    Arrays.asList(foo1, foo2, ... fooN)
)
```

I feel that it would be more ergonomic to provide a varargs override of `Builder addAllFoo($type$... values)`

**Describe the solution you'd like**

`Builder addAllFoo($type$... values)`

**Describe alternatives you've considered**

```java
builder.addAllFoo(
    Arrays.asList(foo1, foo2, ... fooN)
)
```

**Additional context**
N/A

**Comment by googleberg** [comment]
This requires adding a new generated method, please use Arrays.asList or call .add() multiple times.
