### ISSUE TITLE
Time to update the simulator targets for Xcode 11.1

### ISSUE THREAD

**Issue by vbonluk** [protocolbuffers/protobuf#6830]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
Mac OS 10.15
Xcode 11.1
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7
**What did you do?**

$ ./autogen.sh
$ ./configure
$ make
$ make check
$ sudo make install

stop in this line

Time to update the simulator targets for Xcode 11.1

**Comment by vbonluk** [comment]
![](http://tc.kaopuyu.com/1572529287.png?imageMogr2/thumbnail/!70p)

![](http://tc.kaopuyu.com/1572529310.png?imageMogr2/thumbnail/!70p)

**Comment by thomasvl** [comment]
Your screen shot doesn't appear to show the line you mention, and your repo steps don't seem like they should try to run anything under the simulator.

**Comment by thomasvl** [comment]
#6840 will fix the objectivec/DevTools/full_mac_build.sh script with general support for Xcode 11.x versions.
