### ISSUE TITLE
[Java] implement java.io.Externalizable

### ISSUE THREAD

**Issue by bmarwell** [protocolbuffers/protobuf#6834]
**What language does this apply to?**
proto3, Java

**Describe the problem you are trying to solve.**

Caches like hazelcast, Apache Ignite, EHCache and others rely on the `java.io.Externalizable` interface for binary conversion.

If `implements java.io.Externalizable` is not not seen on an object, you'd have to provide a wrapper, a marshaller or Serializer for each class on your own.

**Describe the solution you'd like**

Option to have generated java classes implement `java.io.Externalizable`.

Changes:
`AbstractMessageLite implements MessageLite, Externalizable`
or
`MessageLite extends MessageLiteOrBuilder, Externalizable`

Then
```java
abstract class AbstractMessageLite {

  @Override
  public void writeExternal(ObjectOutput out) throws IOException {
    // just call this.writeTo(…);
  }

  @Override
  public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
    // just call this.parseFrom(…);
  }

}
```

**Describe alternatives you've considered**

1. Writing mappers for EACH CLASS, which might break.
   Disadvantage: You'd have to keep everything in sync. Very tight coupling.
2. Extending the class with a delegator pattern.
   Disadvantage: But the documentation says to not do this. Also, you'd have to keep the methods in sync. Very tight coupling.
3. Use your own value beans / immutables from your application and make those externalizable.
   Disadvantage: The'd have to know the mapper class  to the suitable Protobuf class. Tight coupling to a specific mapper.

I cannot think of an alternative without tight coupling, wheras a protobuf class implementing Externalizable seems easy to do. Also, this was  also done for C# in https://github.com/protocolbuffers/protobuf/issues/5148, see PR https://github.com/protocolbuffers/protobuf/pull/5208.

**Additional context**

* Apache ignite documentation: https://apacheignite.readme.io/docs/binary-marshaller
* Hazelcast docs: https://docs.hazelcast.org/docs/3.0/manual/html/ch03.html
* EHcache docs https://www.ehcache.org/documentation/3.0/serializers-copiers.html
  (can be extended)

**Comment by elharo** [comment]
Google Java eschews object serialization for reasons I vaguely recall are outlined in Effective Java by Bloch. Protobufs are an alternative to object serialization, not a way of implementing it.

**Comment by bmarwell** [comment]
Hey @elharo, thanks for letting me know.
I can see the idea behind it and I don't even recall why I opened this issue in the first place.

But what I see now is a difference in implementations which do not seem logical.

Also, the Externalizable method could just have used the existing ProtoBuf format, not java object serialisation. My idea was not too serialize the object, but instead to alias  the methods which output the wire format and the externalized form. I think you might have missed that idea.
