### ISSUE TITLE
protoc: Incorrect compiled python output file name.

### ISSUE THREAD

**Issue by PfunnyGuy** [protocolbuffers/protobuf#6849]
The output compilation of my proto3 syntax file into python creates myFile_pb2.py instead of myFile_pb3.py.

I don't know if this is by design or not.  I noticed that the output into my C++ file is just myFile_pb.cpp and myFile_pb.h.

Thank you for this great tool!

**Comment by anandolee** [comment]
Yes it is be design, so users not not need to change the current import.
