### ISSUE TITLE
C#: UnknownFieldSet not marked as serializable

### ISSUE THREAD

**Issue by NoWHereRepo** [protocolbuffers/protobuf#6850]
Version: 3.10.1
I need to send a protobuf C# DTO to another process via .NET remoting.
.Net fails to serialize the DTO since UnknownFieldSet not marked as serializable.

I already needed to add the (undocumented) cmd option --csharp_opt=serializable to get started. This worked for the generated class but obviously not for the UnknowFieldSet class of Protobuf.

I think protobuf should compile the UnknownFieldSet class with the [Serializable] attribute,
I took a quick look at the Protobuf sources but I didn't found a way to add the expected behaviour.

Any idea/workaround?

**Comment by ObsidianMinor** [comment]
That option was a mistake, since end users like you can do it better than the compiler can and it should probably be removed (@jtattermusch can we do this, it's undocumented and was never in any release notes).

If you need `Serializable` support in a message, you can implement it manually via a partial class definition like so:

For `foo.proto`
```proto
syntax = "proto3";

message Foo {
    int64 id = 1;
    int32 value = 2;
}
```
In another `.cs` file
```cs
[Serializable]
public partial sealed class Foo : ISerializable
{
    public Foo(SerializationInfo info, StreamingContext context)
    {
        Id = (long)info.GetValue(nameof(Id), typeof(long));
        Value = (int)info.GetValue(nameof(Value), typeof(int));
    }
    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue(nameof(Id), Id);
        info.AddValue(nameof(Value), Value);
    }
}

**Comment by jtattermusch** [comment]
It looks like it was added in https://github.com/protocolbuffers/protobuf/pull/5208

I think I agree with the opinion that adding [Serializable] support was a mistake and in general I'm in favor of removing it - but we should look into what is its value currently and whether we can safely remove.
