### ISSUE TITLE
Name collision in generated C++ because of underscores

### ISSUE THREAD

**Issue by ktul** [protocolbuffers/protobuf#6851]
Version 3.10.1, C++, gcc 9.2 on Debian 9

When compiling the following valid protocol buffer to C++:
```
syntax = "proto3";

message Foo_Bar {
    message Blubb {
    }
}

message Foo {
    message Bar_Blubb {
    }
}
```
the sub messages `Foo_Bar.Blubb` and `Foo.Bar_Blubb` are compiled into two separate classes with the same name `Foo_Bar_Blubb`. This will cause `error: redefinition of ´class Foo_Bar_Blubb´`.

This could be prevented by not using a simple underscore for the nesting but for example

-  using namespaces/nested classes: --> `Foo_Bar::Blubb` and `Foo::Bar_Blubb`,
-  escaping underscores through duplication: --> `Foo__Bar_Blubb` and `Foo_Bar__Blubb` or
-  using enumeration: --> `Foo_Bar_Blubb0` and `Foo_Bar_Blubb1` (though new name collisions might arise).

The first option is probably the cleanest and most C++-like. However, none of them is backwards-compatible.

**Comment by rafi-kamal** [comment]
@gerben-s @haberman is this WAI?

**Comment by haberman** [comment]
There are several ways to create conflicts of this type. Unfortunately we can't fix them all.

> using namespaces/nested classes:

This unfortunately makes the nested class impossible to forward-declare.

> escaping underscores through duplication:

It would still be possible to produce a conflict if you just add an extra underscore to the conflicting symbol.
