### ISSUE TITLE
Question: How to parse .proto file into a FileDescriptor in C#

### ISSUE THREAD

**Issue by RicoSuter** [protocolbuffers/protobuf#6853]
**What version of protobuf and what language are you using?**
C#

After trying for a long time I cannot figure out how to read an existing `.proto` file and get a `FileDescriptor` from it (i.e. I need to process the proto metadata in C#). `FileDescriptor.BuildFromByteStrings` seems to take a different binary format and not the plaintext .proto contents as UTF8 byte array. I think this must be super simple to do but I can't find the API to do so.

**Comment by ObsidianMinor** [comment]
There is no API to do so since it's done by `protoc`. Why do you need to parse a `.proto` file in the first place?

**Comment by RicoSuter** [comment]
Because I want to read .proto files (mainly grpc service description files) into a C# model and then do analysis on it, render a UI (like Swagger UI) etc. 

So if I understand it correctly, if i want to do that in C# I need to write my own .proto file parser?

**Comment by ObsidianMinor** [comment]
That *or* you could jump into C++/CLI and use the compiler API from libprotobuf. Then after parsing the files you can serialize them (as FileDescriptor byte strings), send them to C#, and deserialize the byte strings in the normal `FileDescriptor.BuildFromByteStrings` API.

**Comment by RicoSuter** [comment]
Do you know an article/docs describing how to do that? Or at least show what C++/CLI methods/commands to use?

**Comment by KinNeko-De** [comment]
I think that #6799 solves your problem @RicoSuter.
But it was not released yet.

I want to write code that generates UML xmi files from a proto file.
I need to parse the files too and then get the metadata.
So i downloaded the google.protobuf csharp sln and tried out some code that i found there.

I have two code snippets that seams to work in the solution. In 3.10.x of google.protobuf the classes are still internal
For both you have to generate a descriptorset with protoc
`protoc "C:\Directory\mymodel.proto" --proto_path="C:\Directory" --descriptor_set_out="mymodel"`

Then you can open the descriptorset with the following two snippets.
I think they both work for me
```
using (var stream = File.OpenRead(@"C:\Directory\protoc-3.9.1-win64\bin\mymodel"))
{
  FileDescriptorSet descriptorSet = FileDescriptorSet.Parser.ParseFrom(stream);
  Collections.RepeatedField<FileDescriptorProto> descriptorsProto = descriptorSet.File;
}
```
```
using (var stream = File.OpenRead(@"C:\Directory\protoc-3.9.1-win64\bin\mymodel"))
{ 
   FileDescriptorSet descriptorSet = FileDescriptorSet.Parser.ParseFrom(stream);
   var byteStrings = descriptorSet.File.Select(f => f.ToByteString()).ToList();
   System.Collections.Generic.IReadOnlyList<FileDescriptor> descriptors = FileDescriptor.BuildFromByteStrings(byteStrings);
}
```

Maybe this solution works for you too..

**Comment by RicoSuter** [comment]
I’ve decided to use this F# library to parse .proto files in c#:
https://github.com/ctaggart/froto

Seems to be working for my use case but still investigating.

**Comment by mgravell** [comment]
A bit late now, but protobuf-net.Reflection can do this for you (100% managed code - it does *not* wrap `protoc`) - a full example is shown here: https://stackoverflow.com/questions/62575156/how-to-parse-proto-file-into-a-filedescriptor-in-c/62579246#62579246

(this is actually the parser that I use on https://protogen.marcgravell.com, which now runs in the browser via Blazor)

**Comment by elharo** [comment]
seems answered
