### ISSUE TITLE
PHP Fatal error: Generated message class InterfaceProto hasn't been defined (InterfaceProto, (null), (null), (null)) in /home/nesingh/web/qpl-meta-all/QPL/mvc.qpl/mvc/vmsrp/GPBMetadata/InterfaceProto.php on line 2

### ISSUE THREAD

**Issue by neerajchandel1985** [protocolbuffers/protobuf#6859]
**What version of protobuf and what language are you using?**
Version: protobuf-php-3.10.1.zip.
Language: PHP(5.6)

**What operating system (Linux) and version?**
CentOS release 6.8

**What runtime / compiler are you using (e.g., python version or gcc version)**
 PHP(5.6)

**What did you do?**
1. I have download **protobuf-php-3.10.1.zip** from this link <https://github.com/protocolbuffers/protobuf/releases>
2. As per instruction install
3. I have generated the PHP class from a proto file
4. Once i have create instance of the generated class, It throwing error 

PHP Fatal error: Generated message class InterfaceProto hasn't been defined (InterfaceProto, (null), (null), (null)) in /home/nesingh/web/qpl-meta-all/QPL/mvc.qpl/mvc/vmsrp/GPBMetadata/InterfaceProto.php on line 2

**Comment by TeBoring** [comment]
Have you set up your composer.json to find GPBMetadata dir?
https://github.com/protocolbuffers/protobuf/blob/master/php/composer.json#L17

**Comment by neerajchandel1985** [comment]
I have installed through pcel using the below command and also enabled the extension. So i think that we don't need to set up the composer.

sudo pecl install protobuf-{VERSION}

**Comment by TeBoring** [comment]
Actually, to use protobuf, you have to setup composer.
