### ISSUE TITLE
JS: message class should allow all fields to be populated in one statement

### ISSUE THREAD

**Issue by roziscoding** [protocolbuffers/protobuf#6860]
**What language does this apply to?**
Javascript

**Describe the problem you are trying to solve.**
Whenever I need to create and populate a new message, I need to do something like this:

```js
const result = new OperationResult()
result.setOk(true)
result.setStatus(201)
result.setMessage('TODO created successfully')
result.setInfo(todo.getId())
```

This is annoying as it makes code less readable and harder to write.

**Describe the solution you'd like**
There should be a way to populate a new message without having to make each call individually

**Describe alternatives you've considered**
1) Return the instance of the message from `set` methods, allowing chaining like this:

```js
const result = new OperationResult()
  .setOk(true)
  .setStatus(201)
  .setMessage('TODO created successfully')
  .setInfo(todo.getId())
```
2) Have a constructor wich receives the values and populates them into the message like so:
```js
const result = new OperationResult(true, 201, 'TODO created successfully', todo.getId())
```
3) Have a `.populate()` or `.setFields()` method wich receives an object and populates the message as follows:
```js
const result = new OperationResult().populate({
  ok: true,
  status: 201,
  message: 'TODO created successfully',
  info: todo.getId()
})
```

**Additional context**
There's been a short discussion about this kind of thing for generated C++  code on [#562](https://github.com/protocolbuffers/protobuf/issues/562), but it was closed. I believe the reason for closing that issue does not apply here, since chaining is a very common pattern for Javascript, and, even if it wasn't, there are other ways of solving the problem.

I would love to make a PR for this, but I'd need for someone to point me on the right direction, since I couldn't quite get how stuff work just by reading the code and comments.

**Comment by VitorLuizC** [comment]
`.populate` method would be awesome!

**Comment by rwillians** [comment]
Alternative 1 -- fluent interface -- is a common patter across languages and should be interesting having it on JS as well.

I'm not in favor of Alternative 2 since it goes against the common sense pattern that we should avoid too many arguments on constructors (or any function for that mater). Also it's terrible for legibility and clarity of code.

But if you combine Alternative 2 with Alternative 3, IMO seems to be a sweet spot for JS:

```js
const result = new OperationResult({
  ok: true,
  status: 201,
  message: 'TODO created successfully',
  info: todo.getId()
})
```

**Comment by nickpresta** [comment]
We upgraded to package `3.11.1` today and the ability to chain setters is apparently supported:

```
> const Currency = require('path/to/our/protobufs/currency_pb').Currency;
undefined
> new Currency().setCode("CAD").setName("Canadian")
{ wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [ 'CAD', 'Canadian' ],
  pivot_: 1.7976931348623157e+308,
  convertedPrimitiveFields_: {} }
>
```

I can confirm this didn't work with `3.9.2` but am not sure if it was added in `3.10`. I don't see anything in the release notes for this feature, but I'm happy none-the-less.

**Comment by rjmunhoz** [comment]
> I upgraded to package `3.11.1` today and the ability to chain setters is apparently supported:
> 
> ```
> > const Currency = require('path/to/our/protobufs/currency_pb').Currency;
> undefined
> > new Currency().setCode("CAD").setName("Canadian")
> { wrappers_: null,
>   messageId_: undefined,
>   arrayIndexOffset_: -1,
>   array: [ 'CAD', 'Canadian' ],
>   pivot_: 1.7976931348623157e+308,
>   convertedPrimitiveFields_: {} }
> >
> ```
> 
> I can confirm this didn't work with `3.9.2` but am not sure if it was added in `3.10`. I don't see anything in the release notes for this feature, but I'm happy none-the-less.

Who doesn't love zero-doc features, huh? 😅

**Comment by atreya2011** [comment]
I concur with @rwillians of combining Alternative 2 with Alternative 3 as it is indeed a sweet spot. 👍🏼

**Comment by elharo** [comment]
fixed
