### ISSUE TITLE
Conformance Test Failures for Objective-C

### ISSUE THREAD

**Issue by rafi-kamal** [protocolbuffers/protobuf#6863]
Down integration of Google3 changes (https://github.com/protocolbuffers/protobuf/pull/6858) is breaking the [Objective-C tests](https://source.cloud.google.com/results/invocations/a8b3630c-de2b-44ed-91cb-900185681384/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fobjectivec_osx%2Fpresubmit/log).

The broken tests have been added recently in cl/276783306. Should I add those to the failure list for now to move forward?

**Comment by thomasvl** [comment]
Go ahead and add them to the excludes, but keep this this open so I look at them.

**Comment by thomasvl** [comment]
I think I have a fix, but I'll wait for the PR to land so I can easily validate it.

**Comment by thomasvl** [comment]
Patched your change in locally, fix is right, #6866 out for testing on kokoro.

**Comment by rafi-kamal** [comment]
Thank you!

**Comment by thomasvl** [comment]
Landed the fix.
