### ISSUE TITLE
Conformance Test Failures for C# 

### ISSUE THREAD

**Issue by rafi-kamal** [protocolbuffers/protobuf#6865]
Down integration of Google3 changes (https://github.com/protocolbuffers/protobuf/pull/6858) is breaking [C# tests](https://source.cloud.google.com/results/invocations/05b870c9-ee14-4945-b46b-988d7e0ea250/targets/protobuf%2Fgithub%2Fmaster%2Fubuntu%2Fcsharp%2Fpresubmit/log).

The broken tests have been added recently in cl/276783306. Should I add those to the failure list for now to move forward?

**Comment by rafi-kamal** [comment]
I've whitelisted the failures for now in https://github.com/protocolbuffers/protobuf/pull/6869/files#diff-d4091de53e9f9136bd14511368ac0624 to move forward with the integration.

**Comment by jtattermusch** [comment]
CC @ObsidianMinor

**Comment by ObsidianMinor** [comment]
`ReadBool` is discarding the top 32 bits of varint values. So any varint values with no bits set in the bottom 32 will return false even if they have some bits set in the top 32.
