### ISSUE TITLE
Upgrade PyPI version to 3.10.1

### ISSUE THREAD

**Issue by ShadowTemplate** [protocolbuffers/protobuf#6870]
Hi all,
I noticed version 3.10.1 was not released on PyPI. Is there any particular reason for it?
The previous version (3.10.0) was released the same day both on GitHub and PyPI.

Thank you very much!

**Comment by rafi-kamal** [comment]
There hasn't been any Python related changes in 3.10.1. I'm happy to release one if you want, but essentially it will be the same as 3.10.0.

**Comment by rafi-kamal** [comment]
Also, 3.11 is coming soon - hopefully next week :)

**Comment by ShadowTemplate** [comment]
Thank you very much for quick response.
Have a great day. ;)
