### ISSUE TITLE
[PHP] provide enum mapping from value to key in addition to from key to value

### ISSUE THREAD

**Issue by stanley-cheung** [protocolbuffers/protobuf#6875]
Parent issue: https://github.com/grpc/grpc/issues/21081

### Is your feature request related to a problem? Please describe.
If I define an enum like this in a proto file:

```proto
enum Animals {
  CATS = 0;
  DOGS = 1;
}
```

When I generate code in Go I end up with mappings from the key to the value and from the value to the key like this:

```go
var Animals_name = map[int32]string{
    0: "CATS",
    1: "DOGS",
}

var Animals_value = map[string]int32{
    "CATS": 0,
    "DOGS":  1,
}
```

But when I generate code in PHP, I only get mappings from the key to the value and not the other way around:
```php
class Animals
{
    /**
     * Generated from protobuf enum <code>CATS = 0;</code>
     */
    const CATS = 0;
    /**
     * Generated from protobuf enum <code>DOGS = 1;</code>
     */
    const DOGS = 1;
}
```

### Describe the solution you'd like
I'd like to be able to get the key from the value as well, like I can in Go.

Something like this would work:
```php
class Animals
{
    const VALUES = [
        "CATS" => 0,
        "DOGS" => 1,
    ];

    const NAMES = [
        0 => "CATS",
        1 => "DOGS",
    ];
}
```
### Describe alternatives you've considered
The only alternative is for me to create something like the "values" mapping manually, which will quickly get out of date.

### Additional context
Add any other context about the feature request here.

**Comment by lauren** [comment]
Thanks @stanley-cheung!

**Comment by haberman** [comment]
I think the best option here is to use reflection. For any enum type you can easily build your own mapping at runtime:

```
  $enumDesc = $pool->getEnumDescriptorByClassName(get_class(new Animals()));
  $names = [];
  for ($i = 0; $i < $enumDesc->getValueCount(); $i++) {
    $value = $enumDesc->getValue($i);
    $names[$value->getNumber()] = $value->getName();
  }
```

The only thing to watch out for is that multiple names can have the same number.

This could be slightly simplified if `$enumDesc->findValueByNumber($number)` was supported like it is in C++. Then you wouldn't need to build your own map.

Please feel free to re-open if this enhancement (`$enumDesc->findValueByNumber($number)`) would be helpful for you. Sorry this issue went so long without an answer.
