### ISSUE TITLE
[question] what exactly is the license of protobuf.el?

### ISSUE THREAD

**Issue by Asalle** [protocolbuffers/protobuf#6876]
Hey guys,

I hacked up a [flatbuffers](https://github.com/Asalle/flatbuffers-mode) mode, that is very much inspired ( :smirk:  ) by `protobuf.el` from your repo. I read the license clause in the `protobuf.el` but I don't get which license is that. 
I just wanted to add a `LICENSE` file to my repo and also I don't want to break the law.
Please let me know which licenses are compliant with the one you have in `protbuf.el`!

Thanks Alexandre Vassalotti, you are mentioned as one of the authors of the mode I just made :)

**Comment by rafi-kamal** [comment]
Do you mean https://github.com/protocolbuffers/protobuf/blob/master/editors/protobuf-mode.el? There is a BSD 3-clauses license header on top of that file :)

**Comment by Asalle** [comment]
Thank you!
