### ISSUE TITLE
MSVC warning C4065: switch statement contains 'default' but no 'case' labels

### ISSUE THREAD

**Issue by pitrou** [protocolbuffers/protobuf#6885]
**What version of protobuf and what language are you using?**
Version: v3.10.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows.

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC 19.0.24241.7

**What did you do?**

Compiling the protobuf-generated C++ source code fails on the above compiler:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/28855501/job/9f2cb9b34a0q53fc#L1368
```
src\arrow/flight/Flight.pb.cc(1320): error C2220: warning treated as error - no 'object' file generated
src\arrow/flight/Flight.pb.cc(1320): warning C4065: switch statement contains 'default' but no 'case' labels
```

This seems to be because we have the following protobuf definition:
```protobuf
message Empty {}
```

which generates the following C++ code:
```c++
const char* Empty::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

```

**Comment by pitrou** [comment]
This is using the gRPC plugin, by the way.

**Comment by fowles** [comment]
Unfortunately, we do not support setting arbitrary compiler warnings.  Because of its interaction with generated code this one is especially finicky to fix.

**Comment by pitrou** [comment]
@fowles Understood, thanks for the reply!
