### ISSUE TITLE
JavaScript: some float values are serialized into IEEE 754 binary representation incorrectly

### ISSUE THREAD

**Issue by IhorDarkov** [protocolbuffers/protobuf#6887]
**What version of protobuf and what language are you using?**
Version: v3.9.0 (also reproduces on master).
Language: Javascript / Typescript

**What operating system (Linux, Windows, ...) and version?**
Windows 10 (1709).

**What runtime / compiler are you using (e.g., python version or gcc version)**
Typescript 3.6.2, Python 3.7.2 

**What did you do?**
1. Create a message with a float field:
```
message Test
{
  float a = 1;
}
```
2. Generate Javascript code for the message definition.
3. Create an instance of the message, set a value to 0.9999999762949594.
4. Serialize message into buffer - IEEE 754 binary representation of the value will be wrong.

In actual application I experienced this issue as value 0.9999999762949594 was first serialized and then deserialized as 0.5 (!).

**What did you expect to see**
The value is serialized as 0x00, 0x00, 0x80, 0x3F

**What did you see instead?**
The value is serialized as 0x00, 0x00, **0x00**, 0x3F

**Anything else we should know about your project / environment**
I made investigation of the issue and seems that there is a bug with values close to power of 2.
Function with the bug: [jspb.utils.splitFloat32](https://github.com/protocolbuffers/protobuf/blob/master/js/binary/utils.js#L159).
Line of code with the bug: `mant = Math.round(mant * jspb.BinaryConstants.TWO_TO_23) & 0x7FFFFF` [LoC](https://github.com/protocolbuffers/protobuf/blob/master/js/binary/utils.js#L204)

Several test cases were added by me into protobuf/js/binary/utils_test.js and tests started failing.
Reason: for some input values mantissa is rounded to a value 0x1000000 and then truncated with a mask 0x7FFFFF => resulting in zero mantissa. In this case we probably have to increase exponent value by 1.

I tried two potential fixes - first is based on the current implementation, second is based on ArrayBuffer/DataView to check my first implementation.

Diff with my tests & suggested fix is attached to this issue: [Fix.zip](https://github.com/protocolbuffers/protobuf/files/3847232/Fix.zip)

**Comment by rafi-kamal** [comment]
@TeBoring @dankurka

**Comment by IgorDarkov** [comment]
Any news about this bug?
Update from me: it reproduces for repeated floats as well.

**Comment by buildist** [comment]
I ran into this in production today, 7.99999999999999 is deserialized to 4!

**Comment by perezd** [comment]
@IhorDarkov I'd like to get your patch into our project, are you willing to sign the CLA and submit a PR for the fix that doesn't use ArrayBuffer/DataView?

**Comment by zakhenry** [comment]
I hit this today `0.49999999999999994` (`sin(30°)`) serialized to `0.25`. I note that if I map floats with `Math.fround` I get the expected results, so it might be a simple patch wrap `value` arg in `jspb.utils.splitFloat32` with `Math.fround`. 

Unsure of browser compatibility issues etc.

**Comment by zakhenry** [comment]
I can't say I understand the boolean logic going on in @IhorDarkov's fix, but I can confirm that it does work. I'd be happy to raise a PR with the required patch
