### ISSUE TITLE
input proto file is not found if --descriptor_set_in is given

### ISSUE THREAD

**Issue by wiktortomczak** [protocolbuffers/protobuf#6897]
**What version of protobuf and what language are you using?**
Version: v3.10.1
Language: any/none

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ 7.4.0

**What did you do?**

```
$ protoc --descriptor_set_out=base.descriptor base.proto   # works fine
$ protoc --descriptor_set_in=base.descriptor --descriptor_set_out=derived.descriptor derived.proto  # fails: derived.proto: No such file or directory
```

Context:

I have two `.proto` files: `base.proto` and `derived.proto`. `base.proto` is self-contained. `derived.proto` imports `base.proto`. When compiling `derived.proto`, I'm trying to provide `base.proto` as a precompiled `FileDescriptorSet` via `--descriptor_set_in`, but then the source `derived.proto` is not found. I believe this is incorrect? (I'm guessing that if `--descriptor_set_in` is given, all inputs are resolved in the given `FileDescriptorSet`s, which I believe is incorrect)

Note that without `--descriptor_set_in`, the source `derived.proto` is found (as is the dependency `base.proto`, imported from source from current directory).

```
$ protoc --descriptor_set_out=derived.descriptor derived.proto   # works fine
```

**What did you expect to see**

`derived.descriptor` -  the result of compiling `derived.proto` to `FileDescriptorSet` binary proto

**What did you see instead?**

```
derived.proto: No such file or directory
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by jschaf** [comment]
As I understand it, `--descriptor_set_in` must contain a colon delimited list of **all** descriptors for the transitive closure of the proto files you wish to generate, including `derived.proto` in your example.

For your example, I'm guessing that `base.descriptor` doesn't contain the descriptor for `derived.proto`.

Said another way, if you use `--descriptor_set_in`, protoc will only lookup descriptors from the `--descriptor_set_in` flag. protoc will not build descriptors from the target proto files to generate. The target proto, `derived.proto`, is only used to decide which proto files to generate from the set of descriptors.

To fix your example (untested):

    protoc --descriptor_set_in=base.descriptor:derived.descriptor \
        --descriptor_set_out=derived.descriptor \
        derived.proto
