### ISSUE TITLE
generate code of header only for C/C++

### ISSUE THREAD

**Issue by IronsDu** [protocolbuffers/protobuf#6900]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

Because protobuf genarate code not header only, so my library can't be header only.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fowles** [comment]
This is not a feature we plan to implement, nor one we would be likely accept if offered a patch
