### ISSUE TITLE
[C++]Why don't you implement "void RepeatedField<Element>::Add(Iter begin, Iter end)"

### ISSUE THREAD

**Issue by fishpenguin** [protocolbuffers/protobuf#6901]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
I think it's faster if you implement this api

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jorgbrown** [comment]
We do.  In fact, the change to add this API was made 6 months before your question, according to https://github.com/protocolbuffers/protobuf/commit/a1c886834425abb64a966231dd2c9dd84fb289b3
