### ISSUE TITLE
[Ruby] Encoding JSON produces invalid JSON with empty StringValue wrapper.

### ISSUE THREAD

**Issue by Mihail-K** [protocolbuffers/protobuf#6903]
**What version of protobuf and what language are you using?**
Version: google-protobuf (3.9.2)
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.2 LTS inside of WSL 2 (Windows Built 19018)

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**What did you do?**
1. Define message containing `StringValue` field (defined by `wrappers.proto`).
2. Construct message object with `StringValue` wrapper containing empty String.
3. Encode message into JSON.

Example message type:
```protobuf
import "google/protobuf/wrappers.proto";

message User {
  google.protobuf.StringValue email = 1;
}
```

Example serialization:
```ruby
user = User.new(email: Google::Protobuf::StringValue.new(value: ''))

User.encode_json(user)
```

**What did you expect to see**
Valid JSON string with empty key omitted:
```json
{}
```
Or key containing empty wrapper object:
```json
{"email": {}}
```

**What did you see instead?**
Invalid JSON string containing key with no value:
```json
{"email":}
```

**Comment by sandlerben** [comment]
Also have this issue. Could you add a ruby tag to this issue?
