### ISSUE TITLE
Someone has pushed 3.11.0-RC1 to central and metadata now broken

### ISSUE THREAD

**Issue by craigday** [protocolbuffers/protobuf#6919]
Currently

https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java/maven-metadata.xml

is serving this:
```
<metadata>
<script/>
<groupId>com.google.protobuf</groupId>
<artifactId>protobuf-java</artifactId>
<versioning>
<latest>3.11.0-rc-1</latest>
<release>3.11.0-rc-1</release>
<versions>
<version>3.11.0-rc-1</version>
</versions>
<lastUpdated>20191120195303</lastUpdated>
</versioning>
</metadata>
```
So no versions exist except for 3.11.0-rc-1.

I'm no maven expert, but I think this is VERY BAD :)

It broke all our builds.

**Comment by rafi-kamal** [comment]
@craigday thanks for reporting the issue. I'm also not a maven expert and I'm not sure what caused this issue, but I'll look into fixing it as soon as possible. Any help or pointers will be appreciated!

**Comment by rafi-kamal** [comment]
I have just rebuilt everything with `mvn clean deploy -P release`, but after uploading to Sonatype I still don't see any old versions in the metadata: https://oss.sonatype.org/service/local/repositories/comgoogleprotobuf-1006/content/com/google/protobuf/protobuf-java/maven-metadata.xml

**Comment by rafi-kamal** [comment]
I've created a issue in Sonaytype: https://issues.sonatype.org/browse/OSSRH-53287

Meanwhile if anyone has any ideas, please let me know.

**Comment by rafi-kamal** [comment]
I think the google-release mirror has still the old metadata: https://oss.sonatype.org/content/repositories/google-releases/com/google/protobuf/protobuf-java/maven-metadata.xml

**Comment by craigday** [comment]
This bad data has now propagated out to https://maven-central.storage.googleapis.com/repos/central/data/com/google/protobuf/protobuf-java/maven-metadata.xml so our workaround (using this alternate) no longer works.

**Comment by craigday** [comment]
Maybe the question you should be asking is why are you pushing a release candidate to central?

**Comment by craigday** [comment]
Just in case you aren't aware, this has affected all subprojects of com/google/protobuf.

**Comment by rafi-kamal** [comment]
Maven folks fixed the issue: https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java/maven-metadata.xml
