### ISSUE TITLE
PHP - Access a raw record in array format

### ISSUE THREAD

**Issue by williamjulianvicary** [protocolbuffers/protobuf#6921]
**What language does this apply to?**
PHP - Non-C extension but may relate to this too.

**Describe the problem you are trying to solve.**
I am using the [Google Ads PHP API](https://github.com/googleads/google-ads-php) to build a report, the schema for the report is flexible. Currently the only way to pull the relevant data from a request is to use getters on the individual rows.

This is the row I'm describing: https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V2/Services/GoogleAdsRow.php

There are hundreds of properties, which then have sub-propeties as part of the proto, which makes it very challenging to determine which getters contain data, and which are not a part of the request response.

**Describe the solution you'd like**
I'd like the ability to run something like this to get a basic keyed array of the data returned:
$message->toArray();

In addition, some values are not appropriately typed, and, for example, Enum's just return the INT value - it is not possible to detect whether a return value (example $googleAdsRow->getCampaign()->getStatus()->getValue()) is an Enum or not.

**Describe alternatives you've considered**
I considered using Google\Protobuf\Internal\Message::serializeToJsonString() to serialize the row, however the performance is incredibly slow (0.5 seconds for ~400 rows of data, vs. 0.004 seconds when manually using getters).

**Comment by haberman** [comment]
I don't understand the motivation here. Do you want a compact debug string for manually viewing what is in the row? Or do you want to programmatically iterate over the response, field by field?

**Comment by williamjulianvicary** [comment]
I want the data in a PHP array format (or JSON would be fine, if the overhead was reduced) - essentially the full record in a format that can then be used with typical array access methods. Essentially my use case (back in September) was to output the data response from the Google Ads API, for each row to allow for non-defined schema to be output to the end user.

For example, if I create a report in Google Ads, and receive a response there is (was, things may have changed since I wrote this message) currently no (efficient) method to expose that data to the end user without utilising the getters to pull the information - but that requires knowing, in advance, the data that you want to extract - if that makes sense.

**Comment by deannagarcia** [comment]
I think this request is pretty specific to the use case and can't be solved generally. I would recommend that you look into writing this yourself and reach out if there's any specific help you need.
