### ISSUE TITLE
Extension number request in options.md

### ISSUE THREAD

**Issue by ashleylgeorge** [protocolbuffers/protobuf#6924]
We would like to have an extension number registered in https://github.com/protocolbuffers/protobuf/blob/master/docs/options.md so we can use custom options in our project.

Company: Analyze Re
Project Name: Analyze Re Graphene
Website: https://analyzere.com

Thank you!

**Comment by ashleylgeorge** [comment]
Might we have this extension number added?  Thanks again.

**Comment by acozzette** [comment]
@ashleylgeorge I just submitted a pull request that allocates number 1075 for your project.

**Comment by ashleylgeorge** [comment]
Thank you!  :+1:
