### ISSUE TITLE
What is the reason for not allow setting null to string field in proto2?

### ISSUE THREAD

**Issue by lostindark** [protocolbuffers/protobuf#6928]
Currently, if a field is string type, the setXXX method doesn't take null.

For C generated code, it has the following check in setXXX(const char* value) method:
`   GOOGLE_DCHECK(value != nullptr);`

For Java, it has 
`         if (value == null) { throw new NullPointerException(); } `

For C#, it has
`         name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");`

This is very annoying, as I need to check if a string is null or not, before assign to protobuf object. Failed to do so will result runtime exception.

C# example to handle this:
` if (name == null) { obj.ClearName(); } else { obj.Name = name; }`

Why don't we just treat it similar to message type, set it to null is the same as calling ClearXX method?
I don't see any downside of this approach. Easier for developer (no need to handle null) and doesn't cause any confusion.

**Comment by mbonness** [comment]
Agree 100%, there is no good reason to throw NullPointerException.  Either get rid of newBuilder() and stop pretending to support the Fluent Builder pattern or implement a simple one line fix.  This issue is a major reason for me not to use Protobufs and go back to using JSON.

**Comment by arthurvaverko-kaltura** [comment]
Also agree with this! happens in proto 3 as well..

**Comment by pablocg** [comment]
So far I haven't found any reason why this should behave this way, nonsense...

**Comment by perezd** [comment]
Is there any reason you couldn't use clear_*()?
```
void clear_foo(): Clears the value of the field. After calling this, has_foo() will return false and foo() will return the default value.
```
source: https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#string

If you have more questions, please open a thread at our mailing list. Thanks!
