### ISSUE TITLE
python `json_format.MessageToDict()` instead of converting the uint64 field to int, it is converted to str

### ISSUE THREAD

**Issue by Leosocy** [protocolbuffers/protobuf#6933]
**What version of protobuf and what language are you using?**
Version: 3.9.2
Language: Python

**What operating system (Linux, Windows, ...) and version?**

MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**

python 3.6.5

**What did you do?**

```python
message User {
    uint64 id=1;
}

s = User(id=1).SerializeToString

json_format.MessageToDict(User.FromString(s))
```

**What did you expect to see**

{"id": 1}

**What did you see instead?**

{"id": "1"}

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by HughKu** [comment]
@Leosocy 
This behavior is specified in [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#json) and here is another [thread](https://github.com/protocolbuffers/protobuf/issues/2954) discussing about this as well.

**Comment by anandolee** [comment]
{"id": "1"} is the expected behavior as described in proto3 spec
