### ISSUE TITLE
3.11.0-RC2: C# throws ArgumentException when retrieving descriptors with nested extensions

### ISSUE THREAD

**Issue by daniel-munch-cko** [protocolbuffers/protobuf#6936]
**What version of protobuf and what language are you using?**
Version: 3.11.0-RC2
Language: C#

**What operating system (Linux, Windows, ...) and version?**

MacOSX 

**What runtime / compiler are you using (e.g., python version or gcc version)**

Protoc 3.11.0-RC2

**What did you do?**

Proto file custom_options.proto

```protobuf
syntax = "proto3";
package package1;

import "google/protobuf/descriptor.proto";
extend google.protobuf.MessageOptions
{
    string my_msg_opt = 50000;
}
```

Proto file message_with_custom_options.proto

```protobuf
syntax = "proto3";
package package1;

import "custom_options.proto";

message MessageWithCustomOption
{
    option (my_msg_opt) = "testing";
    string field1 = 1;
}
```

Proto file message_with_custom_option_nested.proto

```protobuf
syntax = "proto3";
package package1;

import "message_with_custom_options.proto";
import "custom_options.proto";

message MessageWithCustomOptionNested
{
    option (my_msg_opt) = "testing_nested";
    MessageWithCustomOption message = 1;
}
```
Generate code:

```bash
protoc -I. -Ipath/to/tools custom_options.proto message_with_custom_options.proto message_with_custom_options_nested.proto --csharp_out=.
```

C# code:
```csharp
using System;

namespace example
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Package1.MessageWithCustomOption.Descriptor.CustomOptions.TryGetString(50000, out string my_msg_opt);
            Console.WriteLine($"my_msg_opt: {my_msg_opt}");

            Package1.MessageWithCustomOptionNested.Descriptor.CustomOptions.TryGetString(50000, out my_msg_opt);
            Console.WriteLine($"my_msg_opt: {my_msg_opt}");
        }
    }
}
```
**What did you expect to see**

```
my_msg_opt: testing
my_msg_opt: testing_nested
```

This is the verified output using Protobuf 3.8. On 3.9 this code doesn't compile (#6510), on 3.10.1 it reproduces issue #6935.

**What did you see instead?**

The following output
```
my_msg_opt: testing
````

Followed by the following exception - full paths removed for simplicity.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Package1.MessageWithCustomOptionsNestedReflection' threw an exception.
 ---> System.ArgumentException: An item with the same key has already been added. Key: Google.Protobuf.ObjectIntPair`1[System.Type]
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Google.Protobuf.ExtensionRegistry.Add(Extension extension)
   at Google.Protobuf.ExtensionRegistry.AddRange(IEnumerable`1 extensions)
   at Google.Protobuf.Reflection.FileDescriptor.AddAllExtensions(FileDescriptor[] dependencies, GeneratedClrTypeInfo generatedInfo, ExtensionRegistry registry)
   at Google.Protobuf.Reflection.FileDescriptor.FromGeneratedCode(Byte[] descriptorData, FileDescriptor[] dependencies, GeneratedClrTypeInfo generatedCodeInfo)
   at Package1.MessageWithCustomOptionsNestedReflection..cctor() in MessageWithCustomOptionsNested.cs:line 32
   --- End of inner exception stack trace ---
   at Package1.MessageWithCustomOptionsNestedReflection.get_Descriptor() in MessageWithCustomOptionsNested.cs:line 20
   at Package1.MessageWithCustomOptionNested.get_Descriptor() in MessageWithCustomOptionsNested.cs:line 50
   at example.Program.Main(String[] args) in Program.cs:line 12
```
Note the first line which is printed like expected, most likely due to the fix of this issue: #6822 

**Anything else we should know about your project / environment**

This is a minimal example reproducing an issue with real code out of the wild. The code in question compiles and works as expected with Protobuf 3.8, doesn't compile with 3.9, has the above mentioned issue with 3.10 and the described issue with 3.11-RC2.

**Comment by rafi-kamal** [comment]
@jtattermusch @ObsidianMinor could you please take a look?

**Comment by vadimi** [comment]
I've came across this one as well. But my understanding is that other language protobuf implementations do not allow adding duplicate extensions for a specific type:

- python: https://github.com/protocolbuffers/protobuf/blob/2228af689f5ff4d929c85079025c49f6945b136a/python/google/protobuf/descriptor_pool.py#L319

- go: https://github.com/golang/protobuf/blob/e91709a02e0e8ff8b86b7aa913fdc9ae9498e825/proto/extensions.go#L549

which means that proto files acceptable in c# will not work in python/go/etc

**Comment by jtattermusch** [comment]
> I've came across this one as well. But my understanding is that other language protobuf implementations do not allow adding duplicate extensions for a specific type:
> 
> * python: https://github.com/protocolbuffers/protobuf/blob/2228af689f5ff4d929c85079025c49f6945b136a/python/google/protobuf/descriptor_pool.py#L319
> * go: https://github.com/golang/protobuf/blob/e91709a02e0e8ff8b86b7aa913fdc9ae9498e825/proto/extensions.go#L549
> 
> which means that proto files acceptable in c# will not work in python/go/etc

Correct me if I'm wrong but this issue is not about trying to add an extension to the same type twice. It's about adding an extension with the same field number to two different types
(e.g. message1 adds extension with field number 123 and message2 adds extension with field number 123 - which AFAIK is allowed).

**Comment by vadimi** [comment]
@jtattermusch yes, you're right. I've experienced both issues in the same set of proto files, my apologies for mixing up the two. I can create a separate issue for the duplicated extensions.
