### ISSUE TITLE
[C#] Import proto without having the proto in the project

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#6937]
I want to write a gRPC library that uses the `google.api.http` option. For developers to use the option they have to have `import "google/api/annotations.proto";` in their proto files, and have `google/api/annotations.proto` and `google/api/http.proto` on disk beneath the project.

I would like to configure my library to automatically provide `annotations.proto` and `http.proto` to protoc compiler so developers don't need to worry about these files. I would like it to be as simple as when developers reference `import "google/protobuf/empty.proto";` and use `google.protobuf.Empty` without having to add `empty.proto` to their project.

How can I do this?

**Comment by ObsidianMinor** [comment]
All users need to do to use your generated code is to not generate the code themselves by listing the files as files to generate when calling protoc.

file.proto
```proto
syntax = "proto3";

import "google/api/annotations.proto";

// ...
```
```
protoc --proto_path=external_protos file.proto
```

All you need to do is make users add the protos directory you provide (like "external_protos" in this case) to the proto_path list. Then they don't need to generate the files themselves.

**Comment by jtattermusch** [comment]
I don't know a good way of doing this.
The reason why it works for the Well-known-types (such as empty.proto) is that they get special handling in both Google.Protobuf (some ifs in the codebase) and Grpc.Tools (which ships a copy of .proto files for WKT).
