### ISSUE TITLE
PHP：The output data cannot be deserialized by javascript, Java or swift

### ISSUE THREAD

**Issue by jpgith2019** [protocolbuffers/protobuf#6940]
**What version of protobuf and what language are you using?**
Version: master/v3.10.1.
Language: PHP

**What operating system (Linux、Windows) and version**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Go to 'serializeToString()，Gibberish in PHP serialization (unrecognized special symbol)'.
2. The output data cannot be deserialized by javascript, Java or swift.
3. Unable to interface with android, ios and JavaScript.

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by jpgith2019** [comment]
@TeBoring

**Comment by jpgith2019** [comment]
请为我解答一下，谢谢！
Please answer for me, thank you!
@TeBoring

**Comment by jpgith2019** [comment]
@rafi-kamal 
请为我解答一下，谢谢！
Please answer for me, thank you!

**Comment by TeBoring** [comment]
Could you provide more detail about the output of php? What's in that?

**Comment by jpgith2019** [comment]
hello！This is a screenshot of the output：

![image](https://user-images.githubusercontent.com/58164381/69698880-7273b500-1121-11ea-970a-84a718f36468.png)

@TeBoring

**Comment by jpgith2019** [comment]
This is the message definition：

![image](https://user-images.githubusercontent.com/58164381/69699006-d4ccb580-1121-11ea-8352-021e02858983.png)

**Comment by TeBoring** [comment]
Sorry, the screenshot of the output is unreadable. Could you transform it into hex?

**Comment by jpgith2019** [comment]
@TeBoring 
Hello, is that right

echo bin2hex($data);

2201312a740a10323031392d30332d32382031323a3230120ae9ad94e696b94d5037301a06e79585504f5322063138382e30302a1e687474703a2f2f7777772e62642e636f6d2f617364696173646d2f787878320f3939393831313132333739303030353a10323031392d31312d32332031323a3230420132

**Comment by jpgith2019** [comment]
Hopefully the official PHP version will provide a method like serializeToByte(). I want to transfer bytes of data to JavaScript, swift, Java, etc., so I can deserialize them directly

**Comment by jpgith2019** [comment]
Problem solved! Thank you for your attention and help. @TeBoring 

I will describe the solution here. If you encounter the same problem, you can learn from it.

Solutions:
I serialized it with the method `serializeToString()`, and then converted the string to bytes as I output the data. Other languages can deserialize it directly with protobuf.

Custom function:

```

/**
 * Convert a String String to bytes
 * @param $string               The string to convert
 * @param string $sep           The separator
 * @param bool $return_string   Whether string：true string、false An array of
 * @return string|array         “11 25  57 45 48 51 45 50”
 */
function strToBytes($string, $sep = ' ', $return_string = true)
{
    $bytes_array = array();
    for ($i = 0; $i < strlen($string); $i++) {
        $bytes_array[] = ord($string[$i]);
    }
    $bytes = $bytes_array;
    if ($return_string == true) {
        $bytes = implode($sep, $bytes_array);
    }
    return $bytes;
}
/**
 * Byte array to string
 * @param string|array $bytes       Bytes to convert：“11 25  57 45 48 51 45 50 56 32 49 50 58 50 48 18”
 * @param string $sep               The separator
 * @return string
 */
function bytesToStr($bytes, $sep = ' ')
{
    $str = '';
    if (is_string($bytes)) {
        $bytes = explode($sep, $bytes);
    }
    foreach ($bytes as $ch) {
        $str .= chr($ch);
    }
    return $str;
}
```
