### ISSUE TITLE
There is no wheel with compiled libraries for Python 3.8

### ISSUE THREAD

**Issue by nevmerzhitsky** [protocolbuffers/protobuf#6958]
**What language does this apply to?**

Python 3.8

**Describe the problem you are trying to solve.**

The wheels on PyPI doesn't have `google/protobuf/pyext/_message.???.so` file if I install the package with `pip` of Python 3.8. In this case pip use `protobuf-X.Y.Z-py2.py3-none-any.whl`. Thus python module `google.protobuf.pyext.cpp_message` is broken to import. In fact, I don't use the latter, but I need to import classes from `google.protobuf.pyext._message` (sorry).

**Describe the solution you'd like**

We need wheels with compiled libraries for Python 3.8.

**Describe alternatives you've considered**

Downgrade my project to 3.7.

**Comment by alexprengere** [comment]
Duplicate of #6214, unfortunately this issue has been brought up 6 months ago during the first beta release of Python3.8, and even after 3 releases of protobuf done since then, this is still not fixed in the latest version (3.11 deployed on Nov. 26).

**Comment by alexprengere** [comment]
It works now with version `3.11.2`. Thanks a lot!

**Comment by nevmerzhitsky** [comment]
Thanks!

I've tested it with a docker image `python:3.8`:
```
cd /usr/local/lib/python3.8/site-packages/
pip install protobuf
cd google/protobuf/pyext/
ls -la
```

**Comment by rschwiebert** [comment]
Does the platform make a difference? I've tried versions 3.10.0-3.14.0 on python3.8 in an alpine 3.12.0 container, all with no luck. I would have thought it was only the wheel that mattered but I could very well be wrong.
