### ISSUE TITLE
MutexLock inside OnShutdownRun crashing.

### ISSUE THREAD

**Issue by pranavsharma** [protocolbuffers/protobuf#6959]
**What version of protobuf and what language are you using?**
Version: Commit id: 48cb18e5c419ddd23d9badcfe4e9df7bde1979b2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10, 19h1

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 15 2017

**What did you do?**
Seen in production.

**What did you expect to see**
Normal operation. No crashes.

**What did you see instead?**
Crash here
```
# Child-SP          RetAddr           Call Site
00 0000001e`b69fc178 00007ffa`5f82f99f ntdll!LdrpICallHandler+0xf [minkernel\ntos\rtl\amd64\cfgcheck.asm @ 363] 
01 0000001e`b69fc180 00007ffa`5f7ddf34 ntdll!RtlpExecuteHandlerForException+0xf [minkernel\ntos\rtl\amd64\xcptmisc.asm @ 132] 
02 0000001e`b69fc1b0 00007ffa`5f82e4ce ntdll!RtlDispatchException+0x244 [minkernel\ntos\rtl\amd64\exdsptch.c @ 595] 
03 0000001e`b69fc8c0 00007ffa`5f81af1e ntdll!KiUserExceptionDispatch+0x2e [minkernel\ntos\rtl\amd64\trampoln.asm @ 749] 
04 0000001e`b69fcfe8 00007ffa`150b3549 ntdll!LdrpDispatchUserCallTarget+0xe [minkernel\ntos\rtl\amd64\cfgcheck.asm @ 633] 
05 0000001e`b69fcff0 00007ffa`150a0a9d onnxruntime!mtx_do_lock+0x7d [d:\agent\_work\2\s\src\vctools\crt\crtw32\stdcpp\thr\mutex.c @ 100] 
06 (Inline Function) --------`-------- onnxruntime!std::_Mtx_lockX+0x8 [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\thr\xthread @ 72] 
07 (Inline Function) --------`-------- onnxruntime!std::_Mutex_base::lock+0x8 [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\mutex @ 49] 
08 (Inline Function) --------`-------- onnxruntime!google::protobuf::internal::WrappedMutex::Lock+0x8 [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\stubs\mutex.h @ 51] 
09 (Inline Function) --------`-------- onnxruntime!google::protobuf::internal::MutexLock::{ctor}+0x8 [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\stubs\mutex.h @ 66] 
0a 0000001e`b69fd050 00007ffa`150a3c62 onnxruntime!google::protobuf::internal::OnShutdownRun+0x3d [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\stubs\common.cc @ 365] 
0b 0000001e`b69fd0a0 00007ffa`150a3c4d onnxruntime!google::protobuf::internal::`anonymous namespace'::InitSCC_DFS+0x52 [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\generated_message_util.cc @ 784] 
0c 0000001e`b69fd0d0 00007ffa`150a3d6e onnxruntime!google::protobuf::internal::`anonymous namespace'::InitSCC_DFS+0x3d [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\generated_message_util.cc @ 777] 
0d 0000001e`b69fd100 00007ffa`15092ef6 onnxruntime!google::protobuf::internal::InitSCCImpl+0xee [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\generated_message_util.cc @ 808] 
0e (Inline Function) --------`-------- onnxruntime!google::protobuf::internal::InitSCC+0x16 [c:\agent\_work\36\s\cmake\external\protobuf\src\google\protobuf\generated_message_util.h @ 373] 
0f 0000001e`b69fd180 00007ffa`1502f623 onnxruntime!onnx::ModelProto::ModelProto+0x66 [c:\agent\_work\36\b\relwithdebinfo\onnx\onnx-ml.pb.cc @ 1966] 
10 (Inline Function) --------`-------- onnxruntime!std::make_unique+0x17 [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\memory @ 2539] 
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
The main binary dynamically links with onnxruntime.dll. Protobuf is statically linked to onnxruntime.dll. This DLL also links the CRT statically.

**Comment by pranavsharma** [comment]
cc @RafaelCintron

**Comment by catskul** [comment]
I'm pretty sure this is related to to: https://github.com/protocolbuffers/protobuf/issues/206

**Comment by snnn** [comment]
@[pranavsharma](https://github.com/pranavsharma) , do you still remember how to produce it(or how it was resolved)? Do you mean statically link to CRT was the key point? 

@catskul , I think #206 is quite different.   Here it crashed when using protobuf, instead of shutting down it.

**Comment by pranavsharma** [comment]
> @[pranavsharma](https://github.com/pranavsharma) , do you still remember how to produce it(or how it was resolved)? Do you mean statically link to CRT was the key point?
> 
> @catskul , I think #206 is quite different. Here it crashed when using protobuf, instead of shutting down it.

@snnn - fwded you an email. This was observed by the Edge browser. They use statically linked CRT.

**Comment by catskul** [comment]
> @[pranavsharma](https://github.com/pranavsharma) , do you still remember how to produce it(or how it was resolved)? Do you mean statically link to CRT was the key point?
> 
> @catskul , I think #206 is quite different. Here it crashed when using protobuf, instead of shutting down it.

IIRC the problem involved here is a global variable accidentally shared between protobuf and protobuf lite which is insufficiently protected with modification hotspots during loading and shutdown.
