### ISSUE TITLE
Add GeneratedCodeAttribute to generated classes in C#

### ISSUE THREAD

**Issue by Thieum** [protocolbuffers/protobuf#6960]
**What language does this apply to?**

Generated code in C#

**Describe the problem you are trying to solve.**

Code analysis tools use different ways to tell if they need or not to analyse the code. At the moment there is no metadata that would allow such tool to detect that the code is generated instead of user typed. This could lead to auto fixes applied to the generated files.

**Describe the solution you'd like**

Tagging the generated classes with [GeneratedCodeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=netframework-4.8) should help telling VS Code analysis and third party tools to ignore the generated code.

**Describe alternatives you've considered**

At first, I considered the attribute [CompilerGeneratedAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.compilergeneratedattribute?view=netframework-4.8) , but this one is reserved by the .NET compiler as far as I understand.

**Additional context**

[Visual Studio docs](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#generated-code) suggests to use this Attribute for generated code.

**Comment by jskeet** [comment]
This was implemented in #8594.

**Comment by alrz** [comment]
@jskeet 

> This was implemented in #8594.

Is there a reason the the class itself is not marked with Generated?

**Comment by jskeet** [comment]
> @jskeet
> 
> > This was implemented in #8594.
> 
> Is there a reason the the class itself is not marked with Generated?

That would imply that the whole class is generated - which may not be the case, due to partial classes.

**Comment by alrz** [comment]
The reason I'm asking is that currently the only was to implement (type => descriptor) mapping is to check the interface and `GetProperty("Descriptor")` either on the type using reflection or `((IMessage)CreateInstance(type)).Descriptor`. Ideally the type could be annotated with something like `[ProtoTypeName("proto fullname")]` so that we could use TypeRegistry to do that.

**Comment by jskeet** [comment]
@alrz: That sounds like a somewhat-unrelated feature request (it wouldn't be using the same attribute). I'd be happy to consider it, but please file it as a new issue.

**Comment by alrz** [comment]
@jskeet Yeah I was just looking for a way to avoid IsAssignableFrom but a built-in helper for this would be super helpful. https://github.com/protocolbuffers/protobuf/issues/16253

**Comment by fuzzykiller** [comment]
Several code parts are not decorated with `GeneratedCodeAttribute`:

* The `Descriptor` property in a GRPC service “Reflection” class
* The static constructor in a GRPC service “Reflection” class
* The `_parser` field in message classes

This causes lots and lots of “uncovered” code. Is this just an oversight or is there some good reason for that?

**Comment by jskeet** [comment]
@fuzzykiller: Not that I'm aware of. If it's causing you problems, please feel free to create a new PR.

**Comment by fuzzykiller** [comment]
Turns out this is pretty much impossible. Bummer. :(

The reflection class is easy, but the `_parser` field, not so much. 

    private static readonly MessageParser<FakeMessage> _parser = 
        new MessageParser<FakeMessage>(() => new FakeMessage());

There’s two components that would have to be excluded from coverage: The `Func<T>` parameter is doable, but the `new MessageParser()` call ends up in the generated static constructor.
