### ISSUE TITLE
protoc 3.10 fails to load plugins on Windows if path to a plugin longer than 255 chars

### ISSUE THREAD

**Issue by tandr** [protocolbuffers/protobuf#6962]
**What version of protobuf and what language are you using?**
3.10

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
-- none

**What did you do?**
1. Gradle build downloads protoc from mavencentral
2. Any plugin gets downloaded (from local artifactory) under deep tree - longer than 255 chars for  a  path.
3. try to invoke it with said plugin
4. See error "cannot find plugin"
protoc: stdout: . stderr: --go_out: protoc-gen-go: The system cannot find the path specified.

In our case path to protoc-gen-go became
`C:\builds_home\workspace\NEW-DESKTOP\MM\proto-interfaces-release-2020.1.0\gradle-cache\caches\modules-2\files-2.1\github.golang.protobuf\protoc-gen-go\v1.3.2-4-ged6926b3\28b27e5b3703441ca8ba913eecbbafa30b609462\protoc-gen-go-v1.3.2-4-ged6926b3-windows-x86_64.exe`

(263 chars long)

Invocation from gradle could be distilled down to

`
protoc --go_out=plugins=grpc --plugin=protoc-gen-go=C:\builds_home\workspace\NEW-DESKTOP\MM\proto-interfaces-release-2020.1.0\gradle-cache\caches\modules-2\files-2.1\github.golang.protobuf\protoc-gen-go\v1.3.2-4-ged6926b3\28b27e5b3703441ca8ba913eecbbafa30b609462\protoc-gen-go-v1.3.2-4-ged6926b3-windows-x86_64.exe somefile.proto
`

**What did you expect to see**
successful build

**What did you see instead?**
An error

**Anything else we should know about your project / environment**
The long path is constructed by a gradle when it downloads items into a cache, which in itself has quite a long paths.

**Comment by elharo** [comment]
Not surprising. I've encountered this same problem in completely different projects that sometimes generate long paths. Windows really needs to join the 21st century Meanwhile we'll need to think about what, if anything, we can do about this.

**Comment by elharo** [comment]
partial workaround is to move your project to a short named path near the root. That gives you a little more room before encountering this.
