### ISSUE TITLE
TypeScript Supports

### ISSUE THREAD

**Issue by chenxyzl** [protocolbuffers/protobuf#6963]
Thanks for this great tool！
Are there plans to support typescript？
More and more frameworks support typescript，such as vue3.0，react，Angular，deno。
Want to export typescript directly instead of using a third party tool into .d.ts。
thanks for your work。

**Comment by thesayyn** [comment]
@chenxyzl 

Check this out: https://github.com/thesayyn/protoc-gen-ts

**Comment by chenxyzl** [comment]
> @chenxyzl
> 
> Check this out: https://github.com/thesayyn/protoc-gen-ts

thanks，Is it still under maintenance？

**Comment by thesayyn** [comment]
Yes, I maintain it

**Comment by chenxyzl** [comment]
> Yes, I maintain it

thanks for your work。I'm going to try it
