### ISSUE TITLE
Allow printing messages to an Appendable in single-line format

### ISSUE THREAD

**Issue by adoroszlai** [protocolbuffers/protobuf#6965]
**What language does this apply to?**

Java.

**Describe the problem you are trying to solve.**

I would like to print message objects to a user-supplied `StringBuilder` in the [single-line format](https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/java/core/src/main/java/com/google/protobuf/TextFormat.java#L727-L729).

Currently only [multi-line format](https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/java/core/src/main/java/com/google/protobuf/TextFormat.java#L723-L725) is available if I want to supply the `StringBuilder`:

https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/java/core/src/main/java/com/google/protobuf/TextFormat.java#L328-L335

The single-line format is only available in methods that return `String` and use new `StringBuilder`:

https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/java/core/src/main/java/com/google/protobuf/TextFormat.java#L536-L548

I would like to avoid the memory allocations for this internal `StringBuilder`, as well as the returned `String`.

**Describe the solution you'd like**

Add `print`-like method(s) to `Printer` that take `Appendable` and use the single-line format, along the lines of:

```
public void printShortDebug(final MessageOrBuilder message, final Appendable output) throws IOException {
  print(message, singleLineOutput(output));
}

public void printShortDebug(final UnknownFieldSet fields, final Appendable output) throws IOException {
  printUnknownFields(fields, singleLineOutput(output));
}
```

**Describe alternatives you've considered**

Printing to `StringBuilder` and replacing newlines/indents achieves the same effect at a performance penalty.

**Comment by googleberg** [comment]
This not planned but would accept a PR for it.
