### ISSUE TITLE
Ruby precision wrong in Float fields

### ISSUE THREAD

**Issue by pedroswat** [protocolbuffers/protobuf#6966]
**What version of protobuf and what language are you using?**
Version: google-protobuf (3.11.0 universal-darwin, 3.6.1 universal-darwin)
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave 10.14.6 (18G103)

**What did you do?**

```ruby
require 'google/protobuf'
  
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.test.Float" do
    optional :floating_value, :float, 1
  end
end

Float = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.test.Float").msgclass

f = Float.new
f.floating_value = 2.3
p f.floating_value #=> 2.299999952316284
```

I've seen that ruby float precision is a recurring issue of protobuf:
* https://github.com/protocolbuffers/protobuf/issues/4406
* https://github.com/protocolbuffers/protobuf/issues/4569
* https://github.com/protocolbuffers/protobuf/issues/2881

This error renders the `float` type useless in ruby.
We're going to change all the floats to strings. 

Wondering if anyone else had issues with the ruby or any other language implementation.

**Comment by haberman** [comment]
This is working as intended.

A `float` field in protobuf is a single-precision floating point value. The Ruby `Float` type uses double-precision floating point. When you convert a double-precision floating point value to single precision, there is going to be some loss of precision.

If you want to preserve the full precision of a Ruby `Float`, use `double` in protobuf, not `float`.
