### ISSUE TITLE
Java Performance regression since 3.8.0

### ISSUE THREAD

**Issue by thesamet** [protocolbuffers/protobuf#6977]
**What version of protobuf and what language are you using?**
Version: 3.8.0-3.11.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc and jvm 1.8

Between version 3.7.1 and version 3.8.0, the implementation of `CodedOutputStream.writeInt32NoTag` (and possibly other functions) has changed. The new implementation is 6x slower according to two microbenchmarks:

| Function     | 3.5.1    | 3.7.1    | 3.8.0     | 3.9.2     | 3.10.0      | 3.11.0      |
| :----------- | -------: |-------:  | --------: | --------: | ----------: | ----------: |
| message3     | 15.48 ns | 15.55 ns | 30.91 ns  | 30.81 ns  | 30.95 ns    | 30.97 ns    |
| int32s       | 46.23 ns | 46.32 ns | 298.87 ns | 299.07 ns | 299.27ns    | 299.05 ns   |

The function `message3` calls `toByteArray` on a message with 3 `int32s`. It becomes 2x slower after 3.7.1

The function `int32s`  serializes 100 integers into a CodedOutputStream. It exercises directly the impacted code path and therefore gets ~6.5 times slower after 3.7.1.

Benchmarks project: https://github.com/thesamet/protobuf-issue-6977
Code: https://github.com/thesamet/protobuf-issue-6977/blob/master/src/main/scala/Test.scala

**Comment by ennerf** [comment]
I only had a few minutes to look at this, but it seems like there is a problem with the unrolled unsafe loop in [CodedOutputStream#L1340-L1364](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1340-L1364).

I tried changing `position` to be a local variable, and that made the performance match the in-loop case (`290ns -> 40ns` for the int32s benchmark), i.e.,

```Java
int position = this.position;
try {
  // unrolled-loop
} finally {
  this.position = position;
}
```

There is probably an optimization that it's not picking up on. I haven't had a chance to look at the assembly or confirm it for other cases though.

**Comment by elharo** [comment]
Thanks for the benchmark. We don't use or support Scala. I'm experimenting with reimplementing this in Java so our build system can run it.

The big question here is, as with all optimizations, does it matter? That is, suppose CodedOutputStream.writeInt32NoTag is ten times slower. Does this have any noticeable impact on the performance of anything? E.g. does an app take five seconds longer to start up? Does a batch job complete in a day instead of an hour? Or does a BigQuery cost twice as much to run? Can any significant impact be shown that justifies the effort of improving this? 

Any evidence you have along these lines would be helpful.

**Comment by elharo** [comment]
Confirmed this still exists as of 3.19.4:

     [java] Serialized size: 2, writes: 2
     [java] Serialized size: 9, writes: 2
     [java] Serialized size: 11, writes: 3

**Comment by ennerf** [comment]
I created a PR with the changes that fixed it for me back when I tested it. I don't have the setup anymore to run the benchmarks myself, but maybe it helps as a starting point in your debugging.

**Comment by elharo** [comment]
FYI unscientifically t head:

Duplicate Google agent found - skipping google3agentlib.
# Warmup Iteration   1: 2899135.718 ops/s
# Warmup Iteration   2: 2934886.162 ops/s
# Warmup Iteration   3: 2982520.198 ops/s
# Warmup Iteration   4: 2991318.314 ops/s
# Warmup Iteration   5: 3008988.838 ops/s
Iteration   1: 2989268.288 ops/s
Iteration   2: 3002545.609 ops/s
Iteration   3: 2969387.879 ops/s
Iteration   4: 2985162.467 ops/s
Iteration   5: 3007993.176 ops/s

**Comment by elharo** [comment]
Here;'s what I got on the same system after making the change in the comment above:

```
# Warmup Iteration   1: 2907538.241 ops/s
# Warmup Iteration   2: 2985055.209 ops/s
# Warmup Iteration   3: 2939278.483 ops/s
# Warmup Iteration   4: 2983655.846 ops/s
# Warmup Iteration   5: 3006452.144 ops/s
Iteration   1: 3007651.866 ops/s
Iteration   2: 3007436.751 ops/s
Iteration   3: 2981863.484 ops/s
Iteration   4: 2978247.371 ops/s
Iteration   5: 3009019.190 ops/s
```

These measures aren't perfect, but I'd expect to see more difference than this if this still matters. I'm certainly not  seeing a factor of five. This is all from google3 on gLinux openjdk 11.0.12 2022-02-11. It's possible this makes more difference in open source or on different systems or VMs.

**Comment by elharo** [comment]
Whether and where to copy a field to a local variable is exactly the sort of optimization that different JDK versions might vary on. I may try dumping the JIT'd code to see what it's up to.

**Comment by ennerf** [comment]
As mentioned in the PR, I wasn't able to get a noticeable benefit with the above change anymore. I'm not sure what changed between the comment and now, but it's probably not worth pursuing it further.

The result gets noticeably better after reverting to the 3.7.0 version, and even better when the optimized path is removed entirely.

```Java
/**
 * === 3.7.0
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10  29,559 ± 0,499  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  71,854 ± 0,623  ops/us
 *
 * === 3.8.0
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,178 ± 0,016  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  33,218 ± 0,285  ops/us
 *
 * === 3.19.4 (unmodified)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,164 ± 0,027  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  32,970 ± 0,217  ops/us
 *
 * === 3.19.4  (reverted to 3.7.0 code)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10  29,605 ± 0,501  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  44,623 ± 1,239  ops/us
 *
 * === 3.19.4 (removed optimized path)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10  30,740 ± 0,287  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  74,092 ± 0,785  ops/us
 */
```

**Comment by elharo** [comment]
What's tricky here is that this is likely extremely sensitive to the exact JDK. Android performance is also very important to us and can demonstrate completely different speed versus the server.

**Comment by ennerf** [comment]
I understand that this is a sensitive part of the code, so it makes sense to be careful.

FWIW I got similar results on OpenJDK 8, 11, 17, but I didn't test any non-Hotspot VMs. The Android version is not impacted at all because Android is excluded from ever taking the problematic path.

**Comment by ennerf** [comment]
Here are some results for different versions of various VMs. The behavior of stock 3.19.4 is the same across Hotspot and OpenJ9. Only Graal seems to be able to optimize it:

```Java
* === 3.19.4 (Zulu 1.8 - Hotspot)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,167 ± 0,029  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  33,069 ± 0,259  ops/us
 *
 * === 3.19.4 (Zulu 11 - Hotspot)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,145 ± 0,027  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  33,125 ± 0,396  ops/us
 *
 * === 3.19.4 (Zulu 17 - Hotspot)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,603 ± 0,114  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  33,221 ± 0,433  ops/us
 *
 * === 3.19.4 (IBM Semeru 1.8 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   3,168 ± 0,027  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  23,607 ± 0,517  ops/us
 *
 * === 3.19.4 (IBM Semeru 11 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   2,747 ± 0,471  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  23,053 ± 0,371  ops/us
 *
 * == 3.19.4 (IBM Semeru 17 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   3,052 ± 0,056  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  23,341 ± 0,526  ops/us
 *
 * == 3.19.4 (Graal 17 v22 CE)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10  30,300 ± 1,755  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  64,162 ± 3,061  ops/us
```

Adding a `false` to the if statement 

![image](https://user-images.githubusercontent.com/5491587/156880741-0ca67275-aca4-41c4-a093-cd9ab99cc3e1.png)

improves the results of every tested version and JVM. Android remains unchanged because that section is disabled regardless.

```Java
 * === 3.19.4 - w/o main path (Zulu 1.8 - Hotspot)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10  30,519 ± 1,438  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  75,816 ± 0,410  ops/us
 *
 * === 3.19.4 - w/o main path (Zulu 11 - Hotspot)
 * Benchmark                              Mode  Cnt    Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   31,747 ± 0,662  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  132,609 ± 0,993  ops/us
 *
 * === 3.19.4 - w/o main path (Zulu 17 - Hotspot)
 * Benchmark                              Mode  Cnt    Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   31,331 ± 0,479  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  138,394 ± 1,933  ops/us
 *
 * === 3.19.4 - w/o main path (IBM Semeru 1.8 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   8,732 ± 0,182  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  26,527 ± 2,117  ops/us
 *
 * === 3.19.4 - w/o main path (IBM Semeru 11 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   8,891 ± 0,098  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  29,003 ± 3,290  ops/us
 *
 * == 3.19.4 - w/o main path (IBM Semeru 17 - OpenJ9)
 * Benchmark                              Mode  Cnt   Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   8,866 ± 0,112  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  27,589 ± 2,277  ops/us
 *
 * == 3.19.4 - w/o main path (Graal 17 v22 CE)
 * Benchmark                              Mode  Cnt    Score   Error   Units
 * WriteUint32Bench.testWriteInt32NoTag  thrpt   10   32,001 ± 0,661  ops/us
 * WriteUint32Bench.testWriteMessage     thrpt   10  146,126 ± 3,125  ops/us
```

**Comment by elharo** [comment]
This change is rolling out in google3. The good news is we don't see any bugs or performance regressions from this change. The bad news is we're not noticing any performance gains either.
