### ISSUE TITLE
[C#] JSON Formatter - Support omitting unnecessary whitespace 

### ISSUE THREAD

**Issue by jason-gt** [protocolbuffers/protobuf#6979]
**What language does this apply to?**
proto3, C#

**Describe the problem you are trying to solve.**
Whitespace in JSON is often undesirable and not being able to format the JSON in this way is causing issues.

**Describe the solution you'd like**
Add a bool to the Settings class for omitUnnecessaryWhitespace.

**Describe alternatives you've considered**
Performing regex replace operations on the result which is hacky

**Additional context**
This seems possible already in most other languages like [Java](https://github.com/protocolbuffers/protobuf/blob/ef210164aac9a2d462873ac3d31e3559b3a62889/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L116)

**Comment by pgt502** [comment]
looks like the separators are adding the extra space
```
private const string NameValueSeparator = ": ";
private const string PropertySeparator = ", ";
```
[line 65](https://github.com/protocolbuffers/protobuf/blob/ef210164aac9a2d462873ac3d31e3559b3a62889/csharp/src/Google.Protobuf/JsonFormatter.cs#L65)
It would be good to be able to override that behaviour

**Comment by elharo** [comment]
IMHO, not a good idea. Other languages shouldn't have this.
