### ISSUE TITLE
PHP 7.4 zend_mm_heap corrupted

### ISSUE THREAD

**Issue by camry** [protocolbuffers/protobuf#6985]
PHP Protobuf Version: 3.11.1
PHP Version: PHP 7.4.0
Linux: 3.10.0-1062.4.1.el7.x86_64
gcc Version: 8.3.0-r0 

build fails: 
`
too few arguments to function 'zend_assign_to_variable'
         zend_assign_to_variable(cached_zval, value, IS_CV);
         ^~~~~~~~~~~~~~~~~~~~~~~
`

Change the `zend_assign_to_variable (cached_zval, value, IS_CV);` of the storage.c file to `zend_assign_to_variable (cached_zval, value, IS_CV, 0);`.

But I get the following error:
`
zend_mm_heap corrupted
`

**Comment by DRoet** [comment]
see https://github.com/protocolbuffers/protobuf/pull/6968

**Comment by TeBoring** [comment]
Should have been fixed by #6968
