### ISSUE TITLE
MSVC compiler warnings - unknown pragma

### ISSUE THREAD

**Issue by VemundH** [protocolbuffers/protobuf#6989]
**What version of protobuf and what language are you using?**
Version: 3.11.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2019

**What did you do?**
compile

**What did you expect to see**
no warnings

**What did you see instead?**
...\src\google\protobuf\testing\googletest.cc(122,9): warning C4068: unknown pragma
...\src\google\protobuf\testing\googletest.cc(123,9): warning C4068: unknown pragma
...\src\google\protobuf\testing\googletest.cc(125,9): warning C4068: unknown pragma

the pragmas were added in #6025

**Comment by linquize** [comment]
Add `#ifdef __GNUC__` around these `#pragma GCC`
