### ISSUE TITLE
Support unknown Any types in JSON serialization

### ISSUE THREAD

**Issue by lizan** [protocolbuffers/protobuf#6994]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
Having an unknown type in Any (including cases embedded Any in other message) will result MessageToJsonString fail with unknown type.

**Describe the solution you'd like**
Have an option in JsonPrintOptions, to serialize unknown Any as `{"type_url": "type.googleapis.com/FQTypeName", "value": "<base64 encoded binary serialized proto>"}`, similar to what text format does.

**Describe alternatives you've considered**

**Additional context**
This is useful in Envoy (https://github.com/envoyproxy/envoy) context we might have Any in logging object which is serialized by WebAssembly. Also to make sure Envoy can dump config with unknown typed config for extensions.

**Comment by elharo** [comment]
We don't want options. Serialize it always, or always don't. There is no option.
