### ISSUE TITLE
installing protobuf (3.11.1-2) breaks dependency 'protobuf=3.10.1' required by python2-protobuf

### ISSUE THREAD

**Issue by pfeifferj** [protocolbuffers/protobuf#7023]
**What version of protobuf and what language are you using?**
Version: 3.10.1 -- updating to 3.11.1-2
Language:  Python

**What operating system (Linux, Windows, ...) and version?**
Arch Linux (x86_64 Linux 5.4.2-arch1-1)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.0

**What did you do?**
`yay -Syyu` or `sudo pacman -Syyu`

**What did you expect to see**
Update system without errors

**What did you see instead?**
Update aborted:

```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing protobuf (3.11.1-2) breaks dependency 'protobuf=3.10.1' required
Error installing repo packages
```

**Anything else we should know about your project / environment**
At first, I thought this might be an issue with yay. I have uninstalled and rebuilt yay from git, but the error still persists.

**Comment by pfeifferj** [comment]
**Workaround:** Add `IgnorePkg   = protobuf` to `pacman.conf`

**Comment by anandolee** [comment]
What is  3.11.1-2?

We have release protobuf 3.11.1 for python 3.5 3.6 3.7. No release for protobuf 3.11.1 python 3.8 yet.

We are working on python3.8 for protobuf 3.11.2 release
