### ISSUE TITLE
Protobuf ignores empty string on encoding [Ruby]

### ISSUE THREAD

**Issue by lambdadelta34** [protocolbuffers/protobuf#7036]
Not sure if this is even a bug or intended behaviour.

**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave

**What runtime / compiler are you using (e.g., python version or gcc version)**
mri/Ruby2.6.3

**What did you do?**
1. Create protobuf request with empty string value
2. Encode message to protobuf

**What did you expect to see**
Empty string is properly represented in protobuf.

**What did you see instead?**
Empty string is ignored in request encoding.

**Comment by albertferras** [comment]
The default value of a string is an empty string. Default values are not explicitly stored/part of the message, because that's the value you will get if it's not in the binary data.

**Comment by lambdadelta34** [comment]
@albertferras I though it might be the case. So if i want to implement nullify updates i should do it explicitly in a different procedure?

**Comment by albertferras** [comment]
If you want explicit `null` values you can take a look at the wrapper values, which let you differentiate between 'default value' and 'null/not-defined' -> https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/string-value

**Comment by jschultz410** [comment]
You can use the wrapper classes:

```
message Foo
{
    google.protobuf.StringValue bar = 1;
}
```
or you can wrap your scalars in a singleton oneof:

```
message Foo
{
    oneof bar_opt { string bar = 1; }
}
```
Either way, you are looking to see if the field is set or not and then you can interpret that as meaning null in some contexts.  For example, on an update operation you use a FieldMask to specify that you are updating Foo.bar, but Foo.bar is absent / unset.  In that situation, you can interpret this to mean "set Foo.bar to null."

The generated code for some languages (e.g. - Java) are not as friendly with oneofs and their scalar members as others (e.g. - Python).  If you use the [well known wrapper types](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto), then you will more likely get similar treatment across all languages.
