### ISSUE TITLE
Ruby: Build on Alpine/musl

### ISSUE THREAD

**Issue by blowmage** [protocolbuffers/protobuf#7040]
The Alpine Linux distribution is very popular for running Ruby applications, and uses musl instead of gcc. There are reports that newer ruby packages raise when being compiled by musl. (See https://github.com/protocolbuffers/protobuf/issues/3509#issuecomment-567167282) Adding musl to CI would help avoid issues like this.

**Comment by jkomyno** [comment]
Same, but for Node.js as well would be much appreciated.

**Comment by dibenede** [comment]
Greetings from protobuf-javascript. Any updates on supporting musl?

**Comment by haberman** [comment]
per https://github.com/protocolbuffers/protobuf/issues/12904#issuecomment-1589718935 the binary gems do not support musl. Workarounds for this are listed in that link.
