### ISSUE TITLE
C#: CustomOptions broken and deprecated without working alternatives

### ISSUE THREAD

**Issue by ptr1120** [protocolbuffers/protobuf#7043]
**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Win

**What runtime / compiler are you using (e.g., python version or gcc version)**
Generated C# classes from proto files using Grpc.Tools v2.26.0

**What did you do?**

ServiceName.proto
```
syntax = "proto3";
import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
    string service_name = 50001; 
}
```
SumRequestDto.proto
```
syntax = "proto3";
import "ServiceName.proto";

message SumRequestDto {
   option (service_name) = "Producer";
}
```
Program.cs
```
nternal class Program
    {
        private static void Main(string[] args)
        {
            SumRequestDto.Descriptor.CustomOptions.TryGetString(50001, out var messageName);
        }
    }
```

Until Google.Protobuf 3.8.0 everything worked fine with the above code. 

I also tried the suggestion to use  `SumRequestDtoV1Reflection.Descriptor.GetOption()` which requires a `Extension<FileOptions, T> extension` argument.

My Questions:
- How can I generate these required Extensions in order the get my custom option value again?
- Will there ever be a working version with custom options?

**What did you expect to see**
The variable `messageName` assigned to  "Producer".

**What did you see instead?**
The variable `messageName` assigned to null.

**Comment by ObsidianMinor** [comment]
Options currently: 

* Downgrade back to 3.8.0 since protoc in `Grpc.Tools` v2.26.0 is 3.8.0
* Wait for #7005
* Generate code manually without Grpc.Tools until Grpc.Tools updates to 3.11

**Comment by zeinali0** [comment]
I have same issue too.
And the problem is if we downgrade to 3.8.0 then we should downgrade Grpc.AspNetCore to 0.1.22-pre3 which broke many things

**Comment by jtattermusch** [comment]
@ObsidianMinor    Grpc.Tools 2.28.x are already using protobuf 3.11.  Does that mean the problem is solved now?

**Comment by ObsidianMinor** [comment]
Should be solved, yes.
