### ISSUE TITLE
protoc.zip can't be unpacked using gunzip

### ISSUE THREAD

**Issue by gattytto** [protocolbuffers/protobuf#7044]
please include .tar.gz versions of the protoc releases. Just that would be enough to fix this

docker base_images golang (debian flavour) image fails when trying to unpack the protoc zip downloaded from the releases section. This affects cloud development environments that use a non-root golang-buster container when one tries to download and unpack protoc binary zip.

when working in ephemereal dev-envs non-root minimal containers we can only rely on build-scripts to set up the environment. This case presents the issue that apt-get can not be used to install the unzip package and gunzip fails with an error when trying to unpack the zip. 

https://github.com/docker-library/golang/pull/312

**Comment by gattytto** [comment]
https://github.com/eclipse/che/issues/15533

**Comment by linquize** [comment]
Invalid issue. Please close.
You should use unzip to decompress *.zip file, but not gunzip

**Comment by gattytto** [comment]
> Invalid issue. Please close.
> You should use unzip to decompress *.zip file, but not gunzip

I'll close it, thanks for the reminder, the issue is about docker base image for golang (doesn't come with unzip).

**Comment by linquize** [comment]
`apt-get update && apt-get install -y unzip`
