### ISSUE TITLE
[PHP] google.protobuf.Empty should be mapped to \Google\Protobuf\GPBEmpty

### ISSUE THREAD

**Issue by OmarElGabry** [protocolbuffers/protobuf#7057]
If in the proto file we have a method like this:

```proto
rpc DeleteUser (DeleteUserRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            delete: "/users/{user_id=*}"
        };
    }
```

The (actual) generated php looks like this 
```php
public function DeleteUser(\Proto\User\DeleteUserRequest $argument,
      $metadata = [], $options = []) {
        return $this->_simpleRequest('/api.user.UserService/DeleteUser',
        $argument,
        ['\Google\Protobuf\Empty', 'decode'],
        $metadata, $options);
    }
```

The (expected) generated php looks like this 
```php
public function DeleteUser(\Proto\User\DeleteUserRequest $argument,
      $metadata = [], $options = []) {
        return $this->_simpleRequest('/api.user.UserService/DeleteUser',
        $argument,
        ['\Google\Protobuf\GPBEmpty', 'decode'],
        $metadata, $options);
    }
```

So, in summary, In case the class name is of type `\Google\Protobuf\Empty`, that should be mapped to [\Google\Protobuf\GPBEmpty](https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/GPBEmpty.php) instead. That's due to the fact that there is no "Empty" class in PHP (Empty is a reserved word in PHP), it is called "GPBEmpty". But that's how it is called in other languages like golang.

**Comment by TeBoring** [comment]
Code generated for service is not from our code. Please send issues to the rpc (grpc?).
