### ISSUE TITLE
3.2.0版本   ，make check

### ISSUE THREAD

**Issue by qindeer** [protocolbuffers/protobuf#7060]
**What version of protobuf and what language are you using?**
Version:v3.2.0.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc
**What did you do?**
make check时，提示FAIL: protobuf-test。
[test-suite.log](https://github.com/protocolbuffers/protobuf/files/4024473/test-suite.log)

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by linquize** [comment]
I tested but it says
```
============================================================================
Testsuite summary for Protocol Buffers 3.2.0
============================================================================
# TOTAL: 6
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
instead of 7 tests

**Comment by haberman** [comment]
Protobuf 3.2.0 is very old now. Please try a newer version of protobuf.
