### ISSUE TITLE
Error in StringPrintfTest.Multibyte with Visual Studio 2019 16.4.1 x64

### ISSUE THREAD

**Issue by emmenlau** [protocolbuffers/protobuf#7074]
When running the tests I get a reproducible assertion in StringPrintfTest.Multibyte on a  Visual Studio 2019 16.4.1 x64 build. All other platforms (Ubuntu 18.04, CentOS 7.7, macOS XCode 9, Windows Visual Studio 2017.9) work fine with the same build instructions.

Version: v3.11.2
Windows 10, Visual Studio 2019 16.4.1 x64
CMake 3.16.1, Google Test 1.10.0

```
[...]
[ RUN      ] StringPrintfTest.Multibyte
1067 minkernel\crts\ucrt\src\appcrt\convert\mbstowcs.cpp(246) : Assertion failed: (pwcs == nullptr && sizeInWords == 0) || (pwcs != nullptr && sizeInWords > 0)
```

**Comment by emmenlau** [comment]
Anyone?

**Comment by MCESoftwareLT** [comment]
I get the same Assertion. 
protobuf-3.11.4
Visual Studio 2019 16.5.2 x86
CMake 3.17

**Comment by NouberNou** [comment]
I get the same assertion in VS 2015 on 3.2.0 and 3.3.0.

Did not get it in 2017.

**Comment by emmenlau** [comment]
I can still reproduce this issue with protobuf 3.13.0 in Visual Studio 2019 16.8 x64:
```

 [ RUN      ] StringPrintfTest.Multibyte
 minkernel\crts\ucrt\src\appcrt\convert\mbstowcs.cpp(246) : Assertion failed: (pwcs == nullptr && sizeInWords == 0) || (pwcs != nullptr && sizeInWords > 0)
```

Could this be looked at? It seems a bit scary if multi-byte character conversions are potentially broken...
