### ISSUE TITLE
private cocoapods

### ISSUE THREAD

**Issue by wanglelewang** [protocolbuffers/protobuf#7084]
Which way is right ?

sepc.resources = '**/*.proto'   or   spec.source_files = '**/*.proto' ??

**Comment by thomasvl** [comment]
I'm not sure what you are asking.

You need to invoke the proto compiler (protoc) on a .proto file to generate sources, and I don't believe cocoapods has a way to build a tool and invoke that on some set of sources.

**Comment by wanglelewang** [comment]
I want to create my private cocopods repository,  but  this files (xxx.proto)  , I do not known that are resources or source_files when I am editing the xxx.podsepc.  this is my question?

我想搭建自己的私有仓库，但是使用Protobuf的 XXX.proto 文件 ，我不知道他属于资源文件(eg: png)还是属于类文件(eg: h, m ,hpp,cpp,c)

**Comment by thomasvl** [comment]
They are neither.  The .proto files are inputs that have to be run through the protobuf compiler to generate sources for your desired language.

**Comment by wanglelewang** [comment]
ok  , so  The xx.proto are do not add to My peoject files,  I only need xx.proto generate Object-C .h .m , This is right?
