### ISSUE TITLE
mergeFrom in javascript?

### ISSUE THREAD

**Issue by pcj** [protocolbuffers/protobuf#7097]
Is the mergeFrom feature available in javascript (jspb)?  Any plans to implement it?

**Comment by VirusRC** [comment]
I am currently validating the usage of protobuf for C++ <-> JS/TS communication using ts-protoc-gen plugin to create .d.ts files.
MergeFrom is available for the C++ dtos but is missing for the JS/TS dtos.
Would be nice to have this feature provided for JS/TS as well. Alternative would be to implement it using the spread operator but seems unsatisfying for me.

Anyone any updates on this?

**Comment by john-livelyvideo** [comment]
Any updates?

**Comment by perezd** [comment]
Hi, we have no current roadmap plan to add this functionality to the JS implementation of Protobuf. I'll reopen this if that changes.

**Comment by john-livelyvideo** [comment]
For event source'ing, using binary serde, this is really nice to have @perezd

What's required to get it on the roadmap?

**Comment by perezd** [comment]
I understand that'd be useful, it's largely all of our competing interests (internal and external) vs available resources, hope you understand the position we're in.
