### ISSUE TITLE
How to format all keys in an unified naming way in json string by using JsonFormat

### ISSUE THREAD

**Issue by BoyuanYan** [protocolbuffers/protobuf#7098]
**What language does this apply to?**
proto syntax version: proto3
I suggest this feature applied for all programming languages.

**Describe the problem you are trying to solve.**
When I use some tools to analyze the data defined by proto, I need to convert the data into JSON format. However, the ways of naming from different .proto files are different (camel-case, underscore-case, etc.), which make the regex-related analysis difficult. I realized that there is already an option to decide whether to preserve the default key values (`alwaysOutputDefaultValueFields`). However, it's not enough, and I didn't find a way to choose the naming way in protobuf.

**Describe the solution you'd like**
maybe add an input parameter `NamingWay nw` in `JsonFormat.printer()`.

**Comment by elharo** [comment]
IMHO customizing JSON output is an anti-feature for reasons of compatibility. We specifically want to not do this.
