### ISSUE TITLE
missing ReadVariant

### ISSUE THREAD

**Issue by ycdtosa** [protocolbuffers/protobuf#7107]
**What version of protobuf and what language are you using?**
Version: master at one machine, and headers 3.11.2 in a different machine.

Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux / Windows, but i don't think it is relevant.

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang / gcc

**What did you do?**
I had a complete mess of a setup, and tried to compile pd.cc files from a machine with a different version of protobuffers ( so far my fault )

I built the files with protoc in one machine using the tagged 3.11.2 repository.

When tried to compile the resulting files in a machine with the files from the master repository
the include headers did not have the ReadVarint() but ReadVarint32() and ReadVarint64() instead.

**What did you expect to see**

A compiler error saying something like:

      << "This program was compiled against version "
      << VersionString(headerVersion) << " of the Protocol Buffer runtime "
         "library, which is not compatible with the installed version ("
      << VersionString(GOOGLE_PROTOBUF_VERSION) <<  ").  Contact the program "
         "author for an update.  If you compiled the program yourself, make "
         "sure that your headers are from the same version of Protocol Buffers "
         "as your link-time library.  (Version verification failed in \""
      << filename << "\".)";

**What did you see instead?**

A compiler error saying that ReadVarint was not found.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I thing the change that made the headers not compatible was introduced there at this commit 91ed6dcb5b3b44dbca3f468444f74b4b048bab23, but there might be others as well.

Thanks.

**Comment by ycdtosa** [comment]
of course the "incompatible" header is parse_context.h around line 582..
https://github.com/protocolbuffers/protobuf/blob/v3.11.2/src/google/protobuf/parse_context.h#L582
vs
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/parse_context.h#L582

**Comment by gerben-s** [comment]
The protection against mismatched versions of runtime library/runtime headers and compiled protos only works when pulling from release branches and not from master.

If you use master then building clean from source is recommended
