### ISSUE TITLE
MSVC C6387 warning

### ISSUE THREAD

**Issue by linquize** [protocolbuffers/protobuf#7108]
**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 x64

**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC 2019

**What did you do?**
1. create a proto3 message with a string field called `String1`
2. use protoc to compile to C++
3. compile the generated source using MSVC

**What did you expect to see**
No C6387 warning

**What did you see instead?**
C6387 warning
'value' could be '0':  this does not adhere to the specification for the function 'std::basic_string<char,std::char_traits<char>,std::allocator<char> >::{ctor}'

The generated source is
```cpp
inline void Proto1::set_string1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  string1_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto1.String1)
}
```

It seems MSVC does not understand
`GOOGLE_DCHECK(value != nullptr);`

If use `::std::string(value ? value : "")`, the warning goes away.

**Comment by linquize** [comment]
ping

**Comment by fowles** [comment]
We don't support compiling with arbitrary warnings.  The exact state of this macro in particular will change very soon because of the release of abseil logging.  As such, I am going to close this.
