### ISSUE TITLE
[FeatureRequest] Could you treat Messages with empty fields as namespaces?

### ISSUE THREAD

**Issue by lolgear** [protocolbuffers/protobuf#7113]
Consider following description.

```protobuf
// Abc doesn't have fields. We can treat it as namespace.
message Abc {
  message MyStructure {
    string myValue = 1;
  }
}
```

`Abc` message doesn't contain any field and can be treated as namespace.

**Comment by WarriorXK** [comment]
This would be amazing, or at least another method of being able to define multiple packages/namespaces per file.

**Comment by elharo** [comment]
Doubtful this will happen. In any case, this repo is not where pro0posals like this start.
