### ISSUE TITLE
3.11.2: src/solaris/libstdc++.la in dist tar ball

### ISSUE THREAD

**Issue by kloczek** [protocolbuffers/protobuf#7117]
Looks like dist tar ball has not been generated using dist or distcheck targets and some leftover Solaris build files are included in dist tar ball.

**Comment by elharo** [comment]
location/URL of this tarball?

**Comment by kloczek** [comment]
I'vce switched to github autogenerated tar ball from git tag.
Closing

**Comment by kloczek** [comment]
This .la file still is in git repo https://github.com/protocolbuffers/protobuf/tree/main/src/solaris
