### ISSUE TITLE
C#: MethodDescriptor.GetOption throws NullReferenceException

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#7127]
`MethodDescriptor.GetOption<T>(Extension<MethodOptions, T> extension)` throws `NullReferenceException` when the method descriptor does not have the option on it. I would expect it to return null.

My code:

```csharp
private bool TryGetHttpRule(MethodDescriptor methodDescriptor, out HttpRule httpRule)
{
    var extension = AnnotationsExtensions.Http;
    httpRule = methodDescriptor.GetOption(extension);

    return httpRule != null;
}
```

Google.Protobuf 3.11.2
Google.Api.CommonProtos 2.0.0-beta01

**Comment by JamesNK** [comment]
Proto:

```proto
service HttpApiGreeter {
  rpc NoOption (HelloRequest) returns (HelloReply);
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

MethodDescriptor is NoOption

**Comment by jtattermusch** [comment]
This is fixed by introducing a new GetOptions() API and deprecating the "GetOption" API https://github.com/protocolbuffers/protobuf/pull/7434.
