### ISSUE TITLE
Java: cannot use "package = other.pkg"

### ISSUE THREAD

**Issue by dlazerka** [protocolbuffers/protobuf#7128]
**What version of protobuf and what language are you using?**
Version: v3.11.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux Mint 18.3

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java Gradle plugin (Kotlin DSL)

**What did you do?**
1. Message:
```
syntax = "proto3";
package other.pkg;
message MyOtherMessage {
  string type = 1;
}
```
2. Compile

**What did you expect to see**
Generated code is compilable

**What did you see instead?**
```
./build/generated/source/proto/main/java/other/pkg/OtherMessages.java:598: error: cannot find symbol
        if (other == other.pkg.OtherMessages.MyOtherMessage.getDefaultInstance()) return this;
                          ^
  symbol:   variable pkg
  location: variable other of type MyOtherMessage
```

**Anything else we should know about your project / environment**
It seems that java compiler uses variable name "other" that clashes with package name "other.pkg".

**Comment by googleberg** [comment]
Set the java_package option explicitly as a workaround.
