### ISSUE TITLE
Allow for message reuse in the Java API

### ISSUE THREAD

**Issue by tomerz90** [protocolbuffers/protobuf#7138]
Im using proto3 in a Java application.
In my application Im parsing a lot of protobuf messages (~1B).
However I only have 16 threads doing the parsing and so there are only 16 messages in the memory in any given time.
The fact that I cant reuse these messages has a significant impact on performance (allocation + GC times) and I see no reason to not have an API that allows for reuse of the messages that the user uses "at his own risk".
If you dont want to add a new API, I think the impl of the `mergeFrom` API of the builder class can be modified for this purpose and it will make more sense since, IMHO, its misleading and its not clear that even though its a "merge" it still creates a new Message and merges from that.
WDYT?
If you are OK with that, I can also open a PR with the suggested changes.

**Comment by elharo** [comment]
Do you mean mutable protos? That's a hard no. We used to do that inside google, and it proved to be a very bad idea.
