### ISSUE TITLE
Ruby YAML encoding a `Google::Protobuf::RepeatedField` drops the values

### ISSUE THREAD

**Issue by alexlaj** [protocolbuffers/protobuf#7163]
**What version of protobuf and what language are you using?**
Version: google-protobuf (3.11.2).
Language: Ruby 2.6.5

**What operating system (Linux, Windows, ...) and version?**
macOS 10.15.2

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Create a new `Google::Protobuf::RepeatedField` with a value in it.
2. Encode it as YAML using `.to_yaml`
3. Decode it using `YAML.load(...)`
4. See that the value that was originally there has been dropped and you are left with an empty `Google::Protobuf::RepeatedField`.

```
[1] pry(main)> repeated_field = Google::Protobuf::RepeatedField.new(:string) << 'test'
=> ["test"]
[2] pry(main)> repeated_field.class
=> Google::Protobuf::RepeatedField
[3] pry(main)> yaml = repeated_field.to_yaml
=> "--- !ruby/object:Google::Protobuf::RepeatedField {}\n"
[4] pry(main)> empty_repeated_field = YAML.load(yaml)
=> []
[5] pry(main)> empty_repeated_field.class
=> Google::Protobuf::RepeatedField
[6] pry(main)> empty_repeated_field.length
=> 0
```

**What did you expect to see**
After doing `YAML.load(...)` we should end up with a `Google::Protobuf::RepeatedField` with the same values as when we encoded it.

**What did you see instead?**
A `Google::Protobuf::RepeatedField` with no values. In my case an easy workaround is to transform the `Google::Protobuf::RepeatedField` to an array before encoding.

**Anything else we should know about your project / environment**
Came across this when using https://github.com/collectiveidea/delayed_job, which encodes ruby objects as YAML to store in the database for asynchronous processing. When the job was picked up and decoded we ended up with no values in our `Google::Protobuf::RepeatedField` which was a surprise.

**Comment by haberman** [comment]
Since protobuf is not implementing the YAML functionality here, there is not much we can do to fix it.

If you can point to a specific part of the `RepeatedField` interface is that is behaving incorrectly, please let us know.
