### ISSUE TITLE
Exclude fields from JSON mapping

### ISSUE THREAD

**Issue by andrewjlawrence** [protocolbuffers/protobuf#7172]
**What language does this apply to?**
I would like to add a proto3 field option to exclude a field from any JSON mapping.

**If it's about generated code change, what programming language?**
I assume the above would impact the generate code. I am using C++ and would like the solution implemented there.

**Describe the problem you are trying to solve.**
I am sending protobuf messages internally within my application which are then exposed over a REST interface as JSON. I would like to hide particular fields in the protobuf messages from being exposed on the REST interface.

**Describe the solution you'd like**
Something like:
string  examplefield = 1 [exclude_from_json=true];

**Describe alternatives you've considered**
I considered writing some code to hide these fields in my application and decided it was not the cleanest solution.

**Comment by andrewjlawrence** [comment]
I would be interested in contributing a patch for this if it is desired functionality.

**Comment by elharo** [comment]
seems this would break interoperability in multiple ways.
