### ISSUE TITLE
Make compiled ruby source use frozen string literals

### ISSUE THREAD

**Issue by ledhed2222** [protocolbuffers/protobuf#7177]
**What language does this apply to?** 
Applies to ruby generated code

**Describe the problem you are trying to solve.**
In ruby, string literals are (unfortunately) mutable. This comes with a memory penalty. There is a magic comment you can use at the top of any ruby file to opt-out of this for the file only:

```ruby
# frozen_string_literal: true

....
```

I think it would be cool if `protoc` output ruby in this manner, albeit _mostly_ because this is a best practice. I'd be shocked if this had any real-world performance gains.

As far as I can tell, the `protoc` compiler never makes use of the theoretical mutability of ruby strings, as it ought not to. Therefore it should not even be an option; all compiled ruby should have mutable strings turned off.

**Describe the solution you'd like**
Every ruby compiled source file (`*_pb.rb`) should have the magic comment described above at the top.

**Describe alternatives you've considered**
N/A

**Additional context**
I'd be happy to do this if you guys agree :)

**Comment by noahmatisoff** [comment]
I made the change in https://github.com/protocolbuffers/protobuf/pull/7888, curious if the protobuf team will want it to be an option when doing codegen however.
