### ISSUE TITLE
Cannot build protobuf/examples with cmake

### ISSUE THREAD

**Issue by wilderfield** [protocolbuffers/protobuf#7178]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
cmake version 3.10.2
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**What did you do?**
1. Go to protobuf/examples
2. cmake .
3. see error 
**What did you expect to see**
Successful build of add_person_cpp

**What did you see instead?**
CMake Error at CMakeLists.txt:8 (find_package):
  Could not find a package configuration file provided by "protobuf" with any
  of the following names:

    protobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
  "protobuf_DIR" to a directory containing one of the above files.  If
  "protobuf" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by wilderfield** [comment]
Seems like protobuf/examples/CmakeLists.txt may have gone stale...

It was never documented per this dead issue:

https://github.com/protocolbuffers/protobuf/issues/1657

**Comment by wilderfield** [comment]
Found this wonderful SO post: https://stackoverflow.com/questions/41573702/cant-use-protobuf-in-cmakelists-txt

This person's CMakeLists.txt file works

**Comment by mraduldubey** [comment]
Great. Thanks @wilderfield. 
The issue is mainly with `FIND_PACKAGE(Protobuf CONFIG REQUIRED)` .
-  `P` should be capitalized. 
- Get rid of `CONFIG` since no config file is present. 
This followed by usual `cmake .` and `cmake --build .` works.

**Comment by mraduldubey** [comment]
@wilderfield Did you by any chance try to build the same on windows ?

**Comment by mraduldubey** [comment]
[This is how you build on windows.](https://stackoverflow.com/a/70000357/4984822)
