### ISSUE TITLE
Question about file name for objective-c code generation

### ISSUE THREAD

**Issue by codingrhythm** [protocolbuffers/protobuf#7184]
I understand the similar issue had been discussed before: https://github.com/protocolbuffers/protobuf/issues/1372

I would like to ask for some information/advise about generated objective file names as it's currently giving me issues.

we have proto files organised in following structure:

```
common/foo.proto
foo/v1/foo.proto
```

The objc-out will create header files

```
common/Foo.pbobjc.h
foo/v1/Foo.pbobjc.h
```

If `generate_for_named_framework ` is used as option of `protoc`, the import statement for both header files will be same `#import <XFramework/Foo.pbobjc.h>` and Xcode complains about duplicate output as it tries to copy the header files with same name.

I can get away by not using `generate_for_named_framework `, but the generated files are used in an iOS framework project and linked by other projects. Referencing random header files on the disk is not ideal, and if we import the public headers in the umbrella header, the build fails with try to include none-modular header in framework.

I would like to know what's the best option here to address issue like this. Ideally, it would be good to generate the file with the folder structure as part of the name. I do understand the point mentioned in https://github.com/protocolbuffers/protobuf/issues/1372 . I may not aware other alternatives which are better than changing file names.

**Comment by thomasvl** [comment]
First - I'm not sure what the reference to #7106 is for, how do you see it related to the header names?

Frameworks don't generally play great with nested headers.  If you only need your headers to be in one framework, you might be able to no use framework imports style, and instead just let them generate normally, so they should have the paths as part of the generated imports.  Within the framework, I think clang will get things right and see a plain `#include "..."` to also be scoped within the framework.  Code consuming the framework could then do `#import <XFramework/common/Foo.pbobjc.h>`.

If something like that doesn't work, then it sounds like we'd need a way to generate framework imports that keep the paths from the generation. 🙁

**Comment by codingrhythm** [comment]
@thomasvl thanks for your reply. Sorry I messed up with the link. I've updated the link to https://github.com/protocolbuffers/protobuf/issues/1372 . I think that's related now.

I can make the framework work with plain `#import "..."` (compiler doesn't like the `#include "..."` for objc headers) with header search path set. But that's not ideal to reference headers outside our the framework project source. If I add all headers to the framework project, Xcode tries to copy all header files to the same output folder without respecting the path, e.g. "common/Foo.pbobjc.h" and "foo/v1/Foo.pbobjc.h" are all copied to "/usr/include/Foo.pbobjc.h"  which generates build time error.

**Comment by thomasvl** [comment]
1372 is just an issue about controlling the `pbobj` part in the generated names.

Are you trying to _install_ the framework?  is that's why you are trying to write into `/usr/include`?  In general, Apple development doesn't really do that.  Apple's been trying to lock down those directories more and more with each OS update.

As far as Xcode flattening things when it copies the files into the Framework - I haven't looked at that in a long time, and I'm not to surprised if it does try to do that; that was some what I was referencing when I mentioned frameworks not always doing well with nested paths.

As far as what to do to try and support this, I'm open to suggestions, the things Xcode imposing is always going to be the gating factor.  The limited support we have at the moment is what some folks needed to get things like CocoaPods working where it constructs the framework projects and wires them together.

**Comment by codingrhythm** [comment]
Sorry, I was playing around with different build options (framework, static/dynamic library) and got mixed. You are right, framework just copies all headers to the `Headers` folder of output bundle, not `/usr/include` like static library.

Current what I am doing is to have a work around script renames the generated files to include the path, e.g. foo_v1_Foo.objc.h and updates all header imports inside the code.

There are a few options I can think of
1. As file options similar to objective c header prefix, e.g. `objc_file_prefix` so the generator takes the value to prefix all the files
1. As a code generation argument similar to `generate_for_named_framework `, which enables the ability to prefix the filename with folder structure, basically what I am doing with the script

I am not too sure how CocoaPods can help here, are you saying each module/package can be grouped by different framework projects in order to avoid the filename conflicts?

I am fine with any solution as long as this one can be solved in a better way than modifying the generated code.

**Comment by thomasvl** [comment]
CocoaPods doesn't always use real frameworks, so it seems to make the directory structures itself; like so it can support the `header_mappings_dir` attribute it has to keep structure.

I don't think we'd need this to be an option in the proto files because it doesn't change the generate types.  If there is something needed, it likely can just be a generator option; but I'm still not completely clear what it would end up being.

**Comment by codingrhythm** [comment]
Looks like someone else did same renaming approach for this issue as well https://github.com/CocoaPods/CocoaPods/issues/1437#issuecomment-111794301 .

May I suggest something like this:

```
--objc_opt=prefix_file_name=path \
```

will output `path/to/path_to_File.pbobjc.h` instead of `path/to/File.pbobjc.h`

```
--objc_opt=prefix_file_name=class_prefix \
```

will output `path/to/XYZFile.pbobjc.h`

Let me know what you think. I can make a PR if you like.

**Comment by thomasvl** [comment]
Sorry, still debating the ups/downs of adding this, and if it fully fixes things or if something else is likely to come up.  Once we add it we have to support it, so I'd like to ensure nothing else is going to come up because of it (or in the space it is trying to address).

**Comment by thomasvl** [comment]
Quick update - what you call the _path_ case is the one I'm stumbling on. I'm not sure if `path/to/path_to_File.pbobjc.h` makes sense vs. also not recreating the path hierarchy.  For your Framework case, it doesn't matter, but if someone isn't using frameworks, then they don't face the same collisions issues unless for some reason they want a generally _flat_ output directory. So I'm not sure if the option should also impact the creation of the sub directories in general.  Or maybe we have to have two options, one for the prefix (like you mention) and then a second knob to turn off the directory structure part.  But having two options when the usage would seem to be tied also doesn't seem great.

**Comment by codingrhythm** [comment]
Thanks for the update. Correct me if I am wrong, I cannot see how it will affect non-framework users as this option is opt-in only. If users are not using framework or don't need flat output directory, they won't need to provide any options, and everything should just behave as it is. Only when users run into this situation would need to change the output behaviour by providing this option.

**Comment by thomasvl** [comment]
Yes, it is the hierarchy that I'm not sure about.

One thing I've learned over the years is the moment there is an option, some subset of folks will use it for cases you didn't expect; and in this case, having the hierarchy and the name include the transformed hierarchy seems redundant.  I can see someone wanting a flat output directory, so they want the path based filenames to avoid collisions.
