### ISSUE TITLE
Using Protobuf-java and Firebase SDK on Android have a problem

### ISSUE THREAD

**Issue by ChinhQT** [protocolbuffers/protobuf#7185]
Hi Google,

I can't build app when applying the Protobuf-java and Firebase SDK on the project. I've met a lot of problems.

Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-java-3.10.0.jar (com.google.protobuf:protobuf-java:3.10.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
..

How to resolve the problems. I have to use protobuf-java because of creating the proto file which has MessageV3. Thank you.

**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by FZambia** [comment]
+1 to this question. From Lite runtime documentation:

> we will NOT guarantee API/ABI stability for Java Lite. If this is not acceptable for your use-case, please use the full Java runtime instead.

I have a library that uses protobuf-java - i.e. full runtime, but other dependencies like Firebase use lite runtime. Having both as dependencies in project result into conflict described by @ChinhQT. 

I am not an experienced Java developer, hope there is a solution to this situation.

**Comment by elharo** [comment]
This smells like a classic diamond dependency problem. Try using [libraries-bom](https://cloud.google.com/java/docs/bom) to set the versions of everything.
