### ISSUE TITLE
Compiler v3.11.2 and v3.11.4 generate Java Lite code that doesn't compile

### ISSUE THREAD

**Issue by rocboronat** [protocolbuffers/protobuf#7193]
**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: Java Lite

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
The precompiled binary version for osx x86_64

**What did you do?**
1. Depend on `'com.google.protobuf:protobuf-javalite:3.9.1'` in my `build.gradle`file.

2. Have a proto like this one:
```
syntax = "proto3";
package com.fewlaps.quitnow.protobuffer.message;

message PublicProfile {
    string nick = 1;
    string avatar = 2;
    string location = 3;
    string bio = 4;
    bool pro = 5;
}
```
3. Compile it with
`protoc --java_out=lite:"../../src/main/java/" "PublicProfile.proto"`

4. Check that the generated `PublicProfile` class doesn't compile:
<img width="883" alt="Screenshot 2020-02-10 at 00 32 30" src="https://user-images.githubusercontent.com/456499/74112432-e0fed580-4b9c-11ea-9aae-0f144dc7c295.png">

**What did you expect to see**
A flawless generated file.

**What did you see instead?**
A generated file that doesn't compile.

Thanks for your great work!

**Comment by rafi-kamal** [comment]
You are depending on 3.9.1 in your Gradle file. What happens if you depend on 3.11.2 instead?

**Comment by rocboronat** [comment]
I'll try :)

**Comment by rocboronat** [comment]
It doesn't find the dependency:

```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.google.protobuf:protobuf-javalite:3.11.2.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.pom
       - https://jcenter.bintray.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.jar
       - https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.pom
       - https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.jar
       - https://jcenter.bintray.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.pom
       - https://jcenter.bintray.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.jar
       - https://maven.google.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.pom
       - https://maven.google.com/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.jar
       - https://dl.bintray.com/fewlaps/maven/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.pom
       - https://dl.bintray.com/fewlaps/maven/com/google/protobuf/protobuf-javalite/3.11.2/protobuf-javalite-3.11.2.jar
```

**Comment by rafi-kamal** [comment]
My bad, I think v3.11.2 wasn't uploaded to Maven. Can you please try with 3.11.1/3.11.3/3.11.4?

**Comment by rocboronat** [comment]
Now the dependency works, but as the generated file doesn't import anything from it, we're exactly at the same point than before. It seems that the generated file lacks some methods that should be there.

**Comment by rocboronat** [comment]
I've also tried to compile the proto files with 3.11.4, just to try, but it generates exactly the same result.

**Comment by rocboronat** [comment]
Hello @rafi-kamal ! Can I help you in some way? Tell me whatever you need and I will do it asap :·)

Thanks!

**Comment by rocboronat** [comment]
Same with 3.12.3...

It's a big issue because now our Android app can't use the latest Google libraries, because they use protobuffer lite, and it conflicts with the full protobuffer version our app has.

In addition, Google libraries use version 3.0.1 of lite. I tried to get it from [the releases page in the repo](https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.1-javalite) and it doesn't include the protoc binaries, so I can't create the Java OuterClass of my proto files in the server side... 😢 Or should I create them with [version 3.0.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0)?

Now we're forced to move our app from using protobuffers to sad JSON files.

**Comment by elharo** [comment]
This smells like a build config issue involving diamond dependencies. If you have a fully reproducible test case, we can look at it. Short of that, I don't think there's a bug here.

**Comment by rocboronat** [comment]
We didn't spend the time filling the bug, describing the issue, and keeping it updated to be closed like this.

Very bad support, Protobuf.
