### ISSUE TITLE
C# GetOption: throws NullReferenceException

### ISSUE THREAD

**Issue by zhxymh** [protocolbuffers/protobuf#7222]
**What version of protobuf and what language are you using?**
Version: v3.11.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
mac 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
.NET Core 3.1.0

**What did you do?**
Use method FileDescriptor.GetOption.

If the proto file sets the options, it works. But if it is not set, throws NullReferenceException
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Google.Protobuf.Reflection.FileDescriptor.GetOption[T](Extension`2 extension)
   at AElf.FileDescriptorExtensions.GetIdentity(FileDescriptor descriptor) in /Users/zhangxin/code/AElf/src/AElf.Types/Protobuf/FileDescriptorExtensions.cs:line 9
```
I think we should check if **this.Proto.Options** is null. If null, the default value is returned.

Google.Protobuf.Reflection.FileDescriptor.cs
![image](https://user-images.githubusercontent.com/12838970/74634868-c1207080-519f-11ea-887d-5548bda3c6b9.png)

**Comment by xtroncode** [comment]
#7130  Solves this but it hasn't been merged yet.

**Comment by zhxymh** [comment]
> #7130 Solves this but it hasn't been merged yet.

Thx!
