### ISSUE TITLE
Consider implementing INotifyPropertyChanged

### ISSUE THREAD

**Issue by uecasm** [protocolbuffers/protobuf#7225]
**What language does this apply to?**
C# generated code

**Describe the problem you are trying to solve.**
Both for UI data-binding and for other back-end automatic data recalculation, it can be useful to know when a property of an object has been changed.  This includes Protobuf objects, especially as these can end up embedded in larger model objects if held onto for a while (rather than copying to a nearly-identical other class).

**Describe the solution you'd like**
The generated classes should implement the standard `INotifyPropertyChanged` pattern.  (Ideally, the [variant](https://stackoverflow.com/a/35582811/43534) that only raises the change when non-equal.)

**Comment by MrDeej** [comment]
Yeah, pr now we are converting our generated proto classes to ordinary classes to implement NotifyPropertyChanged for them. Please let the generator create this instead, it would save us a lot of boilerplate.
