### ISSUE TITLE
C++ erroneously encodes repeated float fields 

### ISSUE THREAD

**Issue by timarandras** [protocolbuffers/protobuf#7229]
**What version of protobuf and what language are you using?**
Version: master [83b47e4](https://github.com/protocolbuffers/protobuf/commit/83b47e4c65def035a958a4ecdb8f757185f34d79)
Language: C++ and Javascript

**What operating system (Linux, Windows, ...) and version?**
Linux, OpenSuse Tumbleweed

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc -v = 9.2.1
node -v = v12.14.1

**What did you do?**
1. $> git clone git@github.com:timarandras/protobuf-error.git
2. $> cd protobuf-error
3. $> ./compile && (cd generated/cpp && ./compile) && (cd generated/js && npm install)
4. $> generated/cpp/main
5. $> node generated/js/index.js

### .proto file
```
syntax = "proto3";

message Floats {
  repeated float samples = 1;
}
```

### C++ source:
```c++
#include <iostream>
#include <string>
#include <iomanip>
#include "floats.pb.h"

std::string ToHex(const std::string& s, bool upper_case = false)
{
    std::ostringstream ret;

    for (std::string::size_type i = 0; i < s.length(); ++i)
        ret << std::hex << std::setfill('0') << std::setw(2) << (upper_case ? std::uppercase : std::nouppercase) << (int)s[i];

    return ret.str();
}

int main() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  Floats floats;
  
  floats.add_samples(1.5);
  floats.add_samples(2.5);
  floats.add_samples(3.5);

  auto msg = floats.SerializeAsString();

  std::cout << ToHex(msg) << std::endl;  
  return 0;
}
```

### JS source:
```javascript
const {Floats} = require('./floats_pb');

const floats = new Floats();

floats.addSamples(1.5);
floats.addSamples(2.5);
floats.addSamples(3.5);

console.log(Buffer.from(floats.serializeBinary()).toString('hex')); // 0a0c0000c03f0000204000006040

const decodeOk = Floats.deserializeBinary(Buffer.from('0a0c0000c03f0000204000006040','hex')).getSamplesList(); // [ 1.5, 2.5, 3.5 ]
const decodeFromCpp = Floats.deserializeBinary(Buffer.from('0a0c0000ffffffc03f0000204000006040','hex')); // Failure: Decoder hit an error
```

**What did you expect to see**
I expected the C++-encoded message and the JS-encoded message were the same, or at least the JS decoder could decode the binary message string from C++.

**What did you see instead?**
C++ encoded message in hex: `0a0c0000ffffffc03f0000204000006040`
JS encoded message in hex: `0a0c0000c03f0000204000006040`

The C++ encoded message has an inserted `ffffff` in the middle. Removing those `ffffff`s the C++ and JS encoded messages become the same. (And JS can correctly decode it).

JS error:
```
...protobuf-error/generated/js/node_modules/google-protobuf/google-protobuf.js:81
jspb.BinaryConstants.TWO_TO_32=4294967296;jspb.BinaryConstants.TWO_TO_52=4503599627370496;jspb.BinaryConstants.TWO_TO_63=0x7fffffffffffffff;jspb.BinaryConstants.TWO_TO_64=1.8446744073709552E19;jspb.BinaryConstants.ZERO_HASH="\x00\x00\x00\x00\x00\x00\x00\x00";goog.dom={};goog.dom.NodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};goog.debug={};goog.debug.Error=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,goog.debug.Error);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.reportErrorToServer=!0};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){goog.debug.Error.call(this,goog.asserts.subs_(a,b));this.messagePatt
Error [AssertionError]: Failure: Decoder hit an error
    at new goog.asserts.AssertionError (/home/timar/x/ff/protobuf-error/generated/js/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.fail (/home/timar/x/ff/protobuf-error/generated/js/node_modules/google-protobuf/google-protobuf.js:84:89)
    at jspb.BinaryReader.nextField (/home/timar/x/ff/protobuf-error/generated/js/node_modules/google-protobuf/google-protobuf.js:375:123)
    at Function.proto.Floats.deserializeBinaryFromReader (/home/timar/x/ff/protobuf-error/generated/js/floats_pb.js:107:17)
    at Function.proto.Floats.deserializeBinary (/home/timar/x/ff/protobuf-error/generated/js/floats_pb.js:95:23)
    at Object.<anonymous> (/home/timar/x/ff/protobuf-error/generated/js/index.js:12:30)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
  message: 'Failure: Decoder hit an error',
  reportErrorToServer: true,
  messagePattern: 'Failure: Decoder hit an error'
}
```

**Anything else we should know about your project / environment**

**Comment by For-thewin** [comment]
I meet the same problem. So do you solve it?

**Comment by timarandras** [comment]
Unfortunately no. I ditched protobuf and solved the problem elsehow.

**Comment by For-thewin** [comment]
All right. Thank you all the same.

**Comment by junekhan** [comment]
Hi, there's something incorrect when your function turns binary messages into readable hexadecimal messages. It introduces signed integers by accident in your case which is undesirable.
I changed it a little bit for your reference.

`
std::string ToHex(const std::string &s, bool upper_case = false)
{
  std::ostringstream ret;
  auto t = (uint8_t *)&s[0];

  for (std::string::size_type i = 0; i < s.length(); ++i)
    ret << std::hex << std::setfill('0') << std::setw(2) << (upper_case ? std::uppercase : std::nouppercase) << (int)t[i];

  return ret.str();
}
`

**Comment by timarandras** [comment]
> Hi, there's something incorrect when your function turns binary messages into readable hexadecimal messages. It introduces signed integers by accident in your case which is undesirable.
> I changed it a little bit for your reference.
> 
> ```c++
> std::string ToHex(const std::string &s, bool upper_case = false)
> {
>   std::ostringstream ret;
>   auto t = (uint8_t *)&s[0];
> 
>   for (std::string::size_type i = 0; i < s.length(); ++i)
>     ret << std::hex << std::setfill('0') << std::setw(2) << (upper_case ? std::uppercase : std::nouppercase) << (int)t[i];
> 
>   return ret.str();
> }
> ```

This is just the printing, the data differs in memory in JS and C++. Checked with the debugger.

**Comment by junekhan** [comment]
![image](https://user-images.githubusercontent.com/3932094/83011228-1e07ae80-a04c-11ea-8b45-8c2483af91a0.png)
@timarandras I showed the first 4 bytes one by one in the debugger, and here's the image.
The 3rd byte is indeed displayed with 6 leading 'f', however, I think it won't affect how the data really is. You can tell from the unfolded part beneath the field with a value of '\xc0'.
I'd like to know whether you send data encoded from ToHex.

**Comment by gerhard-pretorius** [comment]
Remove the ToHex function:

```
 Floats floats;

  floats.add_samples(1.5);
  floats.add_samples(2.5);
  floats.add_samples(3.5);

  auto msg = floats.SerializeAsString();
  std::cout << msg;
```

And then run like this to display the output in hex:
```
./a.out | od -x -An --endian=big
 0a0c 0000 c03f 0000 2040 0000 6040
```
This matches exactly what was expected - so the issue lies in the `ToHex` function, as @junekhan noted.

You can also verify it by using `protoc` to decode the msg:

```
./a.out | protoc --decode=Floats msg.proto
samples: 1.5
samples: 2.5
samples: 3.5
```
