### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by palsivertsen** [protocolbuffers/protobuf#7236]
**Describe the problem you are trying to solve.**
Is there an official Docker image for protobuf? Having a ready made Docker image for use in CI pipelines would save a lot of time when generating code from proto files.

**Describe the solution you'd like**
Versioned docker images with protoc installed for use in CI or from the command line. Example from command line:
```
docker run --rm -it -v /src:/src protobuf:3 protoc --proto_path=/src ... some.proto
```

**Describe alternatives you've considered**
Creating private images or direct downloads, but that adds maintenance overhead.

**Comment by Dominik-K** [comment]
You can use the package of an operating-system Docker image. 

E.g. Alpine Linux has a pure [`protoc`](https://pkgs.alpinelinux.org/packages?name=protoc&branch=v3.13) package and a [`protobuf`](https://pkgs.alpinelinux.org/packages?name=protobuf&branch=v3.13) package.
