### ISSUE TITLE
is_pod is deprecated

### ISSUE THREAD

**Issue by NN---** [protocolbuffers/protobuf#7243]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC 16.5 Preview 3

**What did you expect to see**
No warnings during compilation

**What did you see instead?**
std::is_pod is deprecated

std::is_pod should be replaced with std::is_standard_layout or std::is_trivial to avoid warnings during compilation with newer standard support.

Here you can find more details on its deprecation:
https://stackoverflow.com/questions/48225673/why-is-stdis-pod-deprecated-in-c20

**Comment by elelel** [comment]
This is also a problem on GCC if the headers are included in a project with strict warnings treatment. And related issue with Intel CC : #7200

**Comment by aestuans** [comment]
This seems to have been solved in `3.15.0`: https://github.com/protocolbuffers/protobuf/blob/80df7760aac37e8ad87c358d8a797a514701134a/CHANGES.txt#L211
