### ISSUE TITLE
google::protobuf::compiler::cpp::CppGenerator memory leaks

### ISSUE THREAD

**Issue by playgithub** [protocolbuffers/protobuf#7247]
OS: Win10Pro
IDE: VS2019community
protobuf: 3.11.2

just define a local variable, like:
```
google::protobuf::compiler::cpp::CppGenerator cpp_generator
```
leads to memory leaking.

google::protobuf::ShutdownProtobufLibrary is called, still leak.

Thanks

**Comment by linquize** [comment]
How do you tell there is memory leak with Visual Studio?

**Comment by playgithub** [comment]
Testing environment is VS2019 on Windows 10.

**Comment by linquize** [comment]
Where do you find memory leak in VS2019?

**Comment by playgithub** [comment]
VS2019 will report memory leak when you run the problem.
sample code:
```
#include ...

int main()
{
    google::protobuf::compiler::cpp::CppGenerator cpp_generator;
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}
```
