### ISSUE TITLE
'protobuf/GPBProtocolBuffers_RuntimeSupport.h' file not found

### ISSUE THREAD

**Issue by adkaushik** [protocolbuffers/protobuf#7250]
**What version of protobuf and what language are you using?**
Version:  Protobuf (3.11.4)
Language: Objective-C/Javascript (react-native iOS)

**What operating system (Linux, Windows, ...) and version?*MacOS Catalina version 10.15.1 (19B88)* 

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. pod install @react-native-firebase/messaging
2. This installs FIrebaseMessaging and Protobuf as dependency pods

*App should build*

*'protobuf/GPBProtocolBuffers_RuntimeSupport.h' file not found*
When the Protobuf pod gets installed, there is no GPBProtocolBuffers_RuntimeSupport.h file, however I can see a file in the github repo.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by thomasvl** [comment]
Is the volume you are using formatted to be case sensitive?

Can you provide more details about where this is coming?  I would have expected some other error before trying import that file.

@paulb777 fyi

**Comment by adkaushik** [comment]
The installed pod is Protobuf. It gets installed when the firebase messaging pod is installed, that is when I am getting this error. Not sure why the file is missing after the pod is installed

**Comment by thomasvl** [comment]
Understood.  But it still isn't clear where the error is coming from?  What is being compiled, etc.  Without more context, it is sorta hard to guess what the problem is.

**Comment by adkaushik** [comment]
Wrappers.pbobjc.m, Any.pbobjc.m, Api.pbobjc.m, FieldMask.pbobjc.m, GPBCodedInputStream.m, Empty.pbobjc.m. These are the files in which the error shows up.

**Comment by thomasvl** [comment]
And the question from before - are you on a case sensitive volume?

**Comment by adkaushik** [comment]
Not sure what you meant . I am using a MacBook Air (13-inch, Early 2015) with MacOS Catalina version 10.15.1

**Comment by paulb777** [comment]
Something might be overriding the Xcode Build Settings.  Perhaps something to do with the react-native configuration?  This might be more of an issue for the react-native project.

**Comment by adkaushik** [comment]
Downgrading to Protobuf ~> 3.11.3 solved the issue.
