### ISSUE TITLE
Unity Compatability

### ISSUE THREAD

**Issue by imankha** [protocolbuffers/protobuf#7252]
Version: master/v3.6.0/v3.5.0 etc.
Language: C#
**Windows**
**Unity**

1. Added C# DLL for Google Protobuf 3.11.3 "Googe.Protobuf.dll" to unity folder inside Assets\Plugins

2. Opened a project in Unity that uses Protobuff C# files made with protoc 3.11.3
3. Observed errors in console:

Error: Could not load signature of Google.Protobuf.ByteString:get_Span due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>

Assembly 'Assets/Plugins/Google.Protobuf.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Memory'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

**Comment by JohnManna** [comment]
This means Unity cannot find System.Memory.  Adding the library to Unity will resolve it.  https://www.nuget.org/packages/System.Memory/  You will probably need a few other libraries in Unity too, just grab them based off of the errors the log gives you.

**Comment by louis030195** [comment]
Using Google Protobuf 3.10.0 solve the problem in my case.

**Comment by ianmarmour** [comment]
This issue is still ongoing I'm effected as well using latest development builds and 4.x C# support in Unity.

**Comment by liaozb** [comment]
`  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.3"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" Version="1.0.0"/>
    
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="All" Version="1.0.0"/>
  </ItemGroup>`
Change 4.5.2 to 4.5.3

**Comment by warrenjayv** [comment]
just want to add input for anyone having this issue. 

you have to go to the package's **nuget page** (nuget.org) then on the package page, click **Dependencies**
![image](https://github.com/protocolbuffers/protobuf/assets/40836157/b2bbc818-1301-4a43-8a83-8e86a0ed3814)

you will have to move all these packages into a asset folder in Unity, for instance, the **plugin** folder
