### ISSUE TITLE
Security best practice violation

### ISSUE THREAD

**Issue by szegedim** [protocolbuffers/protobuf#7257]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Go

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
golang

**What did you do?**
Just use protobuf generated code

**What did you expect to see**
Human readable code

**What did you see instead?**
Machine generated code like https://github.com/apache/incubator-yunikorn-scheduler-interface/blob/fa2b455be9a17338f8f03be3c7c21bb9827a3a3f/lib/go/si/si.pb.go#L2424
```
var fileDescriptor_bcd2636ebca16c8c = []byte{
	// 2176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4f, 0x73, 0xdb, 0xc6,
	0x15, 0x17, 0x48, 0x4a, 0x26, 0x9f, 0x24, 0x8a, 0x5a, 0xca, 0x36, 0x43, 0x3b, 0xb6, 0x82, 0xb1,
	0x3d, 0xee, 0x64, 0x4c, 0x27, 0xea, 0xa1, 0xb1, 0x9d, 0x36, 0x43, 0x49, 0x74, 0xc4, 0x89, 0x49,
	0x2a, 0x4b, 0x2a, 0x6d, 0x32, 0x9d, 0xd1, 0xc0, 0xe0, 0x8a, 0xde, 0x88, 0x04, 0xe0, 0x5d, 0xc0,
	0xb6, 0xda, 0x5b, 0x2f, 0xed, 0x07, 0xe8, 0x4c, 0x3f, 0x40, 0x4f, 0x9d, 0x5e, 0x7a, 0xe8, 0x47,
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
This is super dangerous. Protobuf is at the first line of defense at the API boundary of every server. If a malicious player changes this, it is very expensive to find any security issues in generated stuff like this. It is easy for malicious players to bypass security code reviews by making understanding the dependency expensive. Please generate human readable code.

**Comment by codemaker** [comment]
This thread is open for a year! 
What are security issues might occur? Could you explain with real time example?

**Comment by szegedim** [comment]
Imagine an example, when the blob changes. The security auditor either creates a tool to merge it into a gzip, unzip, and then verify, or they just accidentally accept the change with malicious intent. Stuff like this is best to be in source code and the build engine builds into a zip using a construct like `go:generate`. That is what it is for. `FileDescriptor` is typically something that is meant to store read/write permissions, etc., is not it?

**Comment by znkr** [comment]
Hi, thanks for sharing your concern and sorry for the late reply.

Protobuf file descriptors describe the types in a proto file. It is itself a proto message of the type `FileDescriptorProto` and it's used for proto reflection. It's usually not used to store read write permissions. You can find the source of it here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto

That being said, I can imagine use cases where security relevant data is stored in this proto, for example using custom options: https://developers.google.com/protocol-buffers/docs/proto#customoptions. Should that be the case, I think checking in the generated code should be avoided. Instead, the build system should be used to generate the code on the fly. 

Generating protocol buffers code on the fly as part of the build system has other advantages, so it's a good idea in general: It reduces the cost for reviewing the code as only the .proto file needs to be reviewed and not the generated code, potentially for different languages and it makes certain that the `.proto` file is always in sync with the generated code.

If you want or need to rely on checked in or pre-generated code, it might be worth considering signing the generated file in a similar   way as other build artifiacts: https://slsa.dev/ is an effort that tries to make that easier, but there are other ways to do that.

**Comment by szegedim** [comment]
Thank you for reiterating on this. I understand your point for this **specific case**.

I still have a concern in **general**. If only the generated file is signed, a malicious build machine can still inject harm into the generated opaque bytes before signing. Build machines are usually dedicated and third parties may ignore differences as versions of golang change **very** often limiting its creditworthiness. It is better not to submit byte code into code repositories but regenerate them every time. The integrity of the build system will be the only factor in this case, and the auditors can do their job properly signing only text and not binary information. The risk is that a second compiler ignores the regeneration seeing the compiled code checked in.

**Comment by szegedim** [comment]
I realized it is better to explain it briefly. Binary data is expected to be signed and tracked. Text and code is designed to be human readable for a reason. I think it is better not to mix to save time and costs.

**Comment by znkr** [comment]
I agree. I think that's one more advantage of regenerating the generated file on the fly from the `.proto` file and not checking it in.
