### ISSUE TITLE
Wrong libs version is belt

### ISSUE THREAD

**Issue by kvishnivetsky** [protocolbuffers/protobuf#7258]
Version: 3.11.x
Language: C++

OS: CentOS Linux release 7.7.1908 (Core) x86_64 

GCC Version: 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

Steps to reproduce:
1. Chckout GIT repo
2. Switch to branch 3.11.x
3. .Init submodules
4. Run: ./autogen.sh
5. Run: ./configure --enable-all --enable-openmp --prefix=/usr/local
6. Run: make && make check && sudo make install && sudo ldconfig
7. Build plain C++ code: gcc -std=c++11 -I/usr/local/include -lstdc++ -pthread -fPIC -o exmaple1 -lprotobuf -lprotoc main.cc

```
#include <fstream>
#include <iostream>
#include <string>

#include "example1.pb.h"

using namespace std;

int main(int argcm, char **argv) {

    GOOGLE_PROTOBUF_VERIFY_VERSION;

    google::protobuf::ShutdownProtobufLibrary();

    return 0;
}

```
8. Run my plain application

It was expected to see no errors in output.

By i see:
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.11.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "main.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.11.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "main.cc".)
Aborted

```
So, problem is that libprotobuf* shared objects are belt v.2.x instead of v.3.x

**Comment by NiceBlueChai** [comment]
Maybe there's something wrong with the version of your include files.
Are your shared lib and headers files download together? Or  compiled it by yourself?

**Comment by kvishnivetsky** [comment]
> 
> 
> Maybe there's something wrong with the version of your include files.
> Are your shared lib and headers files download together? Or compiled it by yourself?

Right. I found out, that long time ago I installed DEV package from REPO.
Now I removed it and it's Ok with build process.
Thnx anyway!
Closing a ticket.
