### ISSUE TITLE
Possible makefile issue on master

### ISSUE THREAD

**Issue by frozaken** [protocolbuffers/protobuf#7262]
**What version of protobuf and what language are you using?**
Version: master/
Language: Python

**What operating system (Linux, Windows, ...) and version?**
ubuntu 18.04 server
**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
git clone https://github.com/google/protobuf.git && \
cd protobuf && \
./autogen.sh && \
./configure && \
make -j4
**What did you expect to see**
standard protobuf build
**What did you see instead?**
 *** missing separator.  Stop.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
an AWS EC2 instance. It worked when i cloned the latest release tag instead.

**Comment by elharo** [comment]
still happening at head?
