### ISSUE TITLE
proto3 C# deserialize issue for int64 from angular client (number|Long)

### ISSUE THREAD

**Issue by yunusemregl** [protocolbuffers/protobuf#7264]
**What version of protobuf and what language are you using?**
Version: 6.9.0.
Language: C# Core Api / Angular9

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
Create Proto Type as follow then send it as parameter to c# core api from angular client via http post then C# could not deserialize int64 type when sending number more then 3 digit.

Proto Definition as follow : 
```
message Proto_DataSetRelationResponseTable
{
	repeated int64 ParentReferenceID = 1;
}
```

Above proto creating js type as follow
```
{
    /** Proto_RelationParent ParentReferenceID. */
    public ParentReferenceID: (number|Long)[];
}
```

Example Cases to reproduce this exception : 
**Success Case:**
If send ParentReferenceID array item  123 as 3 digit then c# can serialize type , 

**Failure Case:** 
if send ParentReferenceID  array item number like 1234 which has more then 3 digit, then c# InputFormatter could not be serialize type  and throw exception : While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

**What did you expect to see**
My angular app needs to send long type values like 126649089 number as proto parameter to core api . There should be way or bug solution to accept deserialization for these cases.

**What did you see instead?**
Now I am sending proto from angular as follow code : 
```

 const reqArrFinish = Proto_DataSetRequest.encode(reqObj).finish();
    const reqByteString = String.fromCharCode.apply(null, new Uint8Array(reqArrFinish));
    return super.httpPostRequestProto(endpoint, reqByteString).then((data: Proto_ReplyValue) => {
      const dataSource: RelationResponse = this.parseProtoResponseToDataSourceObject(data);
      return dataSource;
    }, catchError(error => {
      return throwError('Something went wrong!');
    }));
```

If I will send parameter which has ParentReferenceID array item les then 4 digit number , then Api can deserialize parameter then working properly. But If I will use 4 and more digit in number in parameter then c# could not deserialize request.body as I mentioned above.

**Anything else we should know about your project / environment**
The project has angular9 client project and c# core api server project wich is working with protobuff type.

**Comment by jskeet** [comment]
To diagnose this, we should try to work out first whether it's an Angular9 problem or a C# protobuf problem - I *suspect* it's the former.

If you can provide the binary data that you're trying to parse (e.g. as hex within a comment) then we should be able to analyze it and see whether C# *should* be able to parse it, or whether it's ill-formed.

**Comment by jskeet** [comment]
I'm going to close this as it's been nearly 3 months with no further information (and over 2 years since being raised).
