### ISSUE TITLE
The description of CMake generation for VS2019 is not detailed enough

### ISSUE THREAD

**Issue by Parean** [protocolbuffers/protobuf#7274]
In the build [instruction](https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md#cmake-configuration) for windows there is a fragment:

> To make a Visual Studio file for Visual Studio 16 2019, create the Visual Studio solution file above and edit the CMakeCache file.
> 
> C:Path\to\protobuf\cmake\build\solution\CMakeCache
> Then create the Visual Studio solution file again

I think this is quite incomprehensible. What exactly should I edit and why?

**Comment by linquize** [comment]
Use Windows Explorer, in protobuf source code, go to `cmake` directory, right click -> **Open in Visual Studio**.
It will automatically create configuration `x64-Debug`. If you need x64-Release, click Manage Configuration and add a configuration `x64-Release`
Wait until CMake configure complete
Build -> Build All
