### ISSUE TITLE
jsonToMessage could not parse "Integer like" double value;

### ISSUE THREAD

**Issue by chriszzt** [protocolbuffers/protobuf#7285]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
C++
**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 4.8.5
**What did you do?**
1. Create a protobuf Message
```
message Test {
    double LargeEnough = 1;
}
```
2. Create jsonString, 
{"LargeEnough": 18446744073709552000}
3. Try  JsonStringToMessage method to parse it to Test instance
`
Unable to parse number.
`
**What did you expect to see**
Since `18446744073709552000` is a valid double value, it should parse without error
**What did you see instead?**
`
Unable to parse number.
`
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

After some digging into the source code, I found out the problem is in 
https://github.com/protocolbuffers/protobuf/blob/f130827371fc73ab6e24d44313af6577cc2f9d57/src/google/protobuf/util/internal/json_stream_parser.cc#L553
It doesn't use schema to check the float/double type. 

And in my case, since my jsonString is marshalled by golang jsonpb, and passed to c++ to unmarshal. Golang jsonpb marshalls the above proto.Message object as 
`
{"LargeEnough": 18446744073709552000}
`
I also tried MessageToJson function in c++ protobuf library, the result is 
{"LargeEnough": 1.8446744073709552e+19}, which is ok.

Therefore, the question is, whether you require external to handle double type to be the format as '.' 'E' or 'e', or you will support internally.

Thank you.

**Comment by haberman** [comment]
Sorry for the very slow reply. I just tried your test case on the current C++ parser and it worked, so I think this bug is obsolete. The JSON parser was completely rewritten for Protobuf v22 (https://github.com/protocolbuffers/protobuf/releases/tag/v22.0).
