### ISSUE TITLE
Hello，A question need your to confirm. Can i compiler protobuf2(version) to C# sourcecode through protoc 3.11.4?

### ISSUE THREAD

**Issue by WZH70246** [protocolbuffers/protobuf#7290]
Hello，A question need your to confirm. Can i compiler protobuf2(version) to C# sourcecode through protoc 3.11.4?

**Comment by linquize** [comment]
You can compile `*.proto` with header `syntax = "proto2";` using protoc 3.11.4

**Comment by WZH70246** [comment]
ok，thanks

**Comment by linquize** [comment]
If this can answer your question, please close issue
