### ISSUE TITLE
C++: documentation formatting broken

### ISSUE THREAD

**Issue by pdknsk** [protocolbuffers/protobuf#7298]
In serveral places in the _C++ Reference_, code formatting is broken. Search for `@code`.

[message.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message)
[text_format.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.text_format)
[coded_stream.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream)
[zero_copy_stream.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.zero_copy_stream)
[message_differencer.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.message_differencer)
[time_util.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.time_util)
[command_line_interface.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.command_line_interface)
[csharp_names.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.csharp_names)
[java_names.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.java_names)

Plus an erroneous line-break in [RepeatedPtrField::DeleteSubrange](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.repeated_field#RepeatedPtrField.DeleteSubrange.details). And perhaps `[]` as well.

It has been like that for at least a few months now.

**Comment by bendanon** [comment]
Hi, could you provide a link explaining how to build the docs from sources?
I see the problem but I don't really know how to test my fix.
Thanks!
