### ISSUE TITLE
[PHP] Int32 overflow bug on 64-bit systems

### ISSUE THREAD

**Issue by HelmiRifai** [protocolbuffers/protobuf#7299]
**What version of protobuf and what language are you using?**
Version: v3.11.*
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
64-bit Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.2.16

**What did you do?**
Pass a number larger than 2,147,483,647 (MAX_INT_32) to a set{Field}() method on an int32 field

**What did you expect to see**
An exception that it's overflowing

**What did you see instead?**
Kept the value at the number larger than MAX_INT_32

This causes the wire format to get messed up and makes decoding the message break.

According to PHP documentation the "intval()" method being used in GBPUtil::checkInt32() produces a max int output when overflowed, but the max int depends on the system architecture, on on 64-bit machines it remains larger than MAX_INT_32

**Comment by esorot** [comment]
duplicate: https://github.com/protocolbuffers/protobuf/issues/10335
