### ISSUE TITLE
C++ can Swap(NULL)？

### ISSUE THREAD

**Issue by klarkxy** [protocolbuffers/protobuf#7300]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++: 

**What operating system (Linux, Windows, ...) and version?**
CentOS release 6.10 (Final)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)
clang version 3.4.2

** What's my problem**
look at this, a protobuf message called "CSFreeBuyBuyReq"
```protobuf
message CSFreeBuyBuyReq
{
    optional int32 PageID = 1;
}
```
Then I generated this by the protocol buffer compiler
```C++
void CSFreeBuyBuyReq::Swap(CSFreeBuyBuyReq* other) {
  if (other != this) {
    std::swap(pageid_, other->pageid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}
```
It means, I can Swap with a Null ptr!
It‘s going to crashing!

**Comment by gerhard-pretorius** [comment]
It's not possible to guard against an invalid ptr.
In this case, nullptr is just one of many possible invalid ptrs.
 
swap using references instead.

v3.13.0 generates the following code for gcc7.5 on Ubuntu:
```
friend void swap(CSFreeBuyBuyReq& a, CSFreeBuyBuyReq& b) {
    a.Swap(&b);
  }
void CSFreeBuyBuyReq::InternalSwap(CSFreeBuyBuyReq* other) {
...
```

Which can be used like this:

```
  CSFreeBuyBuyReq foo, bar;
  foo.set_pageid(42);
  bar.set_pageid(69);
  swap(bar, foo);
```
