### ISSUE TITLE
Extension number request in my project of grpc-graphql-gateway

### ISSUE THREAD

**Issue by ysugimoto** [protocolbuffers/protobuf#7302]
Hi,

I'd like to have custom option numbers for project of grpc-graphql-gateway to `docs/options.md`.
The project has three of FieldOptions, MethodOptions, and ServiceOptions.

A number of 1079 seems vacant, but please allocate appropriate number for us.
The project website is https://github.com/ysugimoto/grpc-graphql-gateway 

Thanks!

**Comment by acozzette** [comment]
I set aside number 1079 for your project.
