### ISSUE TITLE
Importing Protos without declaring full package name

### ISSUE THREAD

**Issue by ncioj10** [protocolbuffers/protobuf#7304]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
Proto3

**Describe the problem you are trying to solve.**
It is very tedious to import other proto files as it is needed to specify the full package name every time message types of the other files are used. 
For example the use of google.protobuf.Timestamp results in code like:

```
import "google/protobuf/timestamp.proto";
message Application {
    google.protobuf.Timestamp date1 = 1;
    google.protobuf.Timestamp date2 = 2;
    google.protobuf.Timestamp date3 = 3;

}

```

**Describe the solution you'd like**
Either access to the imported types directly with overloading mechanism, or alternatively a renaming scheme for the imported namespaces.

**Comment by elharo** [comment]
language changes are not accepted here
