### ISSUE TITLE
Integration between PHP and Java/NodeJs

### ISSUE THREAD

**Issue by dtiziani** [protocolbuffers/protobuf#7312]
Right now we have some integrations between node and PHP.
We could not find any implementation in PHP that used the binary serialization that we use in NodeJs and Java.

The (de)serialization in PHP uses this class CodedOutputStream that does not a binary serialization, instead it serializes in string format. The PHP support that we could check is only for JSON, and the nodeJs implementation does not support deserializing from a JSON, just the other way around.

Are we missing something?

**Comment by Alex-David-Hu** [comment]
OK






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tizi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 下午3:28
收件人:&nbsp;"protocolbuffers/protobuf"<protobuf@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[protocolbuffers/protobuf] Integration between PHP and Java/NodeJs (#7312)





 
Right now we have some integrations between node and PHP.
 We could not find any implementation in PHP that used the binary serialization that we use in NodeJs and Java.
 
The (de)serialization in PHP uses this class CodedOutputStream that does not a binary serialization, instead it serializes in string format. The PHP support that we could check is only for JSON, and the nodeJs implementation does not support deserializing from a JSON, just the other way around.
 
Are we missing something?

**Comment by haberman** [comment]
The PHP, Java, and JavaScript protobuf libraries owned by Google all support protobuf binary format.

In PHP you can serialize to binary format using `$msg->serializeToString();`. The resulting string can be passed to any other protobuf library. For more info see: https://developers.google.com/protocol-buffers/docs/reference/php-generated#message
