### ISSUE TITLE
mvn package failed for when building protobuf-java-3.11.4

### ISSUE THREAD

**Issue by EliotCao** [protocolbuffers/protobuf#7313]
OS: windows 7
maven: Apache Maven 3.6.3
java: 1.8.0_181
protobuf: 3.11.4

logs as below

>mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Protocol Buffers [BOM]                                             [pom]
[INFO] Protocol Buffers [Parent]                                          [pom]
[INFO] Protocol Buffers [Lite]                                         [bundle]
[INFO] Protocol Buffers [Core]                                         [bundle]
[INFO] Protocol Buffers [Util]                                         [bundle]
[INFO]
[INFO] ------------------< com.google.protobuf:protobuf-bom >------------------
[INFO] Building Protocol Buffers [BOM] 3.11.4                             [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] ----------------< com.google.protobuf:protobuf-parent >-----------------
[INFO] Building Protocol Buffers [Parent] 3.11.4                          [2/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] ---------------< com.google.protobuf:protobuf-javalite >----------------
[INFO] Building Protocol Buffers [Lite] 3.11.4                            [3/5]
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-source-files) @ protobuf-javalite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 86 resources
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (generate-sources) @ protobuf-javalite ---
[INFO] Executing tasks

main:
     [echo] Running protoc ...
[INFO] Executed tasks
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:add-source (add-generated-sources) @ protobuf-javalite ---
[INFO] Source directory: V:\DevTools\Protobuf\protobuf-java-3.11.4\protobuf-3.11.4\java\lite\target\generated-sources added.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ protobuf-javalite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ protobuf-javalite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 150 source files to V:\DevTools\Protobuf\protobuf-java-3.11.4\protobuf-3.11.4\java\lite\target\classes
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[45,32] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[290,18] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[291,13] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[295,53] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[297,32] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[298,33] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[298,54] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[539,13] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[541,28] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[618,31] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[710,37] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/UnsafeUtil.java:[830,37] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[101,32] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[399,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[1416,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[1982,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[2554,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[4657,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[4689,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[4869,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/MessageSchema.java:[5177,19] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[INFO] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/AbstractMessageLite.java: Some input files use or override a deprecated API.
[INFO] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/AbstractMessageLite.java: Recompile with -Xlint:deprecation for details.
[INFO] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/AbstractMessageLite.java: Some input files use unchecked or unsafe operations.
[INFO] /V:/DevTools/Protobuf/protobuf-java-3.11.4/protobuf-3.11.4/java/lite/target/generated-sources/com/google/protobuf/AbstractMessageLite.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-test-source-files) @ protobuf-javalite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 58 resources
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (generate-test-sources) @ protobuf-javalite ---
[INFO] Executing tasks

main:
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.int32_field" is conflicting with another field: both repeated field "int32_fie
ld" and singular field "int32_field_list" generate the method "getInt32FieldList()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.enum_field" is conflicting with another field: capitalized name of field "enum
_field" conflicts with field "EnumField"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.string_field" is conflicting with another field: capitalized name of field "st
ring_field" conflicts with field "StringField"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.bytes_field" is conflicting with another field: capitalized name of field "byt
es_field" conflicts with field "BytesField"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.message_field" is conflicting with another field: capitalized name of field "m
essage_field" conflicts with field "MessageField"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.int32_field_count" is conflicting with another field: both repeated field "Int
32Field" and singular field "int32_field_count" generate the method "getInt32FieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.enum_field_count" is conflicting with another field: both repeated field "Enum
Field" and singular field "enum_field_count" generate the method "getEnumFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.string_field_count" is conflicting with another field: both repeated field "St
ringField" and singular field "string_field_count" generate the method "getStringFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.bytes_field_count" is conflicting with another field: both repeated field "Byt
esField" and singular field "bytes_field_count" generate the method "getBytesFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.message_field_count" is conflicting with another field: both repeated field "M
essageField" and singular field "message_field_count" generate the method "getMessageFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.Int32Field" is conflicting with another field: both repeated field "Int32Field
" and singular field "int32_field_list" generate the method "getInt32FieldList()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.EnumField" is conflicting with another field: both repeated field "EnumField"
and singular field "enum_field_count" generate the method "getEnumFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.StringField" is conflicting with another field: both repeated field "StringFie
ld" and singular field "string_field_count" generate the method "getStringFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.BytesField" is conflicting with another field: both repeated field "BytesField
" and singular field "bytes_field_count" generate the method "getBytesFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.MessageField" is conflicting with another field: both repeated field "MessageF
ield" and singular field "message_field_count" generate the method "getMessageFieldCount()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.int32_field_list" is conflicting with another field: both repeated field "Int3
2Field" and singular field "int32_field_list" generate the method "getInt32FieldList()"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.field_name" is conflicting with another field: capitalized name of field "fiel
d_name" conflicts with field "field__name"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.field__name" is conflicting with another field: capitalized name of field "fie
ld_name" conflicts with field "field__name"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames._2conflict" is conflicting with another field: capitalized name of field "_2co
nflict" conflicts with field "__2conflict"
     [exec] [libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_context.cc:149] field "io_protocol_tests.TestConflictingFieldNames.__2conflict" is conflicting with another field: capitalized name of field "_2c
onflict" conflicts with field "__2conflict"
[INFO] Executed tasks
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (process-lite-sources) @ protobuf-javalite ---
[INFO] Executing tasks

main:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Protocol Buffers [Parent] 3.11.4:
[INFO]
[INFO] Protocol Buffers [BOM] ............................. SUCCESS [  0.014 s]
[INFO] Protocol Buffers [Parent] .......................... SUCCESS [  0.014 s]
[INFO] Protocol Buffers [Lite] ............................ FAILURE [  7.061 s]
[INFO] Protocol Buffers [Core] ............................ SKIPPED
[INFO] Protocol Buffers [Util] ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.132 s
[INFO] Finished at: 2020-03-18T17:48:55+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (process-lite-sources) on project protobuf-javalite: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] V:\DevTools\Protobuf\protobuf-java-3.11.4\protobuf-3.11.4\java\lite\process-lite-sources-build.xml:2: Execute failed: java.io.IOException: Cannot run program "awk" (in directory "V:\DevTools\Protobuf\protobuf-java-3.11.4\protobuf-3.
11.4\java\lite"): CreateProcess error=2, The system cannot find the file specified
[ERROR] around Ant part ...<ant antfile="process-lite-sources-build.xml"/>... @ 4:50 in V:\DevTools\Protobuf\protobuf-java-3.11.4\protobuf-3.11.4\java\lite\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :protobuf-javalite

**Comment by hexin46373** [comment]
I have the same problem.who can help us?

**Comment by hexin46373** [comment]
> I have the same problem.who can help us?

OS: windows 10
maven: Apache Maven 3.6.3
java: 1.7.0_80
protobuf: 3.11.4

**Comment by TianLing2020** [comment]
I have the same problem.
Win10 x64
jdk11
protobuf: 3.11.4
maven: 3.6.3
can't bulid lite

**Comment by Sion2015** [comment]
same problem on 
windows10 x64
jdk 11
protobuf 3.12.3
maven 3.6.3

**Comment by RandomYe** [comment]
awk tool not found on Windows platform. you can use https://sourceforge.net/projects/gnuwin32/files/gawk/3.1.6-1/gawk-3.1.6-1-bin.zip/download to resolve this issue.

**Comment by zhouhui0802** [comment]
You need to put the corresponding version of protoc.exe under your src directory

**Comment by kennywgx** [comment]
> awk tool not found on Windows platform. you can use https://sourceforge.net/projects/gnuwin32/files/gawk/3.1.6-1/gawk-3.1.6-1-bin.zip/download to resolve this issue.

it works, thank u ~
