### ISSUE TITLE
Protobuf accesses Non SDK Interfaces marked hidden by Android

### ISSUE THREAD

**Issue by ramanpreetSinghKhinda** [protocolbuffers/protobuf#7337]
**What version of protobuf and what language are you using?**
Version: master
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Android

**What runtime / compiler are you using (e.g., python version or gcc version)**
Test on Android device running 9 or above.

**What did you do?**

1. Integrate [Firebase Performance](https://firebase.google.com/docs/perf-mon/get-started-android) Android SDK on a Sample App (refer [quickstart app](https://github.com/firebase/quickstart-android/tree/master/perf))

2. Launch the app

3. Any action (app startup, moving between screens, etc.) causes the following log spam on Android 9.0 or above:

```
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/com.foo.bar: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
```

This happens very frequently and pollutes customer logcat (see [original issue](https://github.com/firebase/firebase-android-sdk/issues/1128)). 

See [documentation](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces) details.

**Note:** Issue might happen with any Firebase SDK integrating with protobuf but I haven't tested it. It could also be more broad (means not just Firebase SDKs).

**What did you expect to see**
From the [docs](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#list-names), while you can currently use some non-SDK interfaces that are part of the greylist (depending on your app's [target API level](https://developer.android.com/distribute/best-practices/develop/target-sdk)), using any non-SDK method or field always carries a high risk of breaking your app.

So we expect to have protobuf migrate to SDK interfaces.
> Also see [requesting](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#feature-request) a new public API from Android.

**What did you see instead?**
APIs marked hidden (Non SDK Interfaces) by Android are being accessed by protobuf.

**Anything else we should know about your project / environment**
Per analysis performed using the [veridex tool](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#veridex-macos), all of the accessed hidden APIs for Firebase Performance are from `com.google.protobuf` library.

```
49 hidden API(s) used: 24 linked against, 25 through reflection
       44 in greylist (all usages for Firebase Performance are from Protobuf)
       0 in blacklist
       0 in greylist-max-o
       5 in greylist-max-p
```
> Note: Run the tool on a sample app that integrates "com.google.firebase:firebase-perf:19.0.5".

Refer internal ticket b/152073447#comment3 for full veridex report.

**Comment by ramanpreetSinghKhinda** [comment]
Issue is being tracked internally at b/154851649. The patch is planned to go into the runtime for R release.

**Comment by cubuspl42** [comment]
What's the status of this issue?

I'm just reminding that half the world has their console output spammed because of this little thingy. ;)

**Comment by ramanpreetSinghKhinda** [comment]
Based on my discussion with the team Protobuf uses some of the greylisted APIs, and there is no plan to remove those APIs from a greylist for now. But given the widespread usage the platform team have added exemption list for hidden api warnings so as to avoid spamming logcat on access to these methods.

The fix has been released in Android R (11) release of the Android OS.
