### ISSUE TITLE
Segmentation fault in upb_fielddef_index at upb.c:3346

### ISSUE THREAD

**Issue by jbq** [protocolbuffers/protobuf#7341]
**What version of protobuf and what language are you using?**

Version: 3.11.4
Language: PHP

**What operating system (Linux, Windows, ...) and version?**

GNU/Linux Debian 9

**What runtime / compiler are you using (e.g., python version or gcc version)**

- Python 2.7.13
- gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**What did you do?**

Random crash on my PHP application with Protobuf native extension, cannot find a way to reproduce reliably

**What did you expect to see**

No crash

**What did you see instead?**

Server crash, see https://gist.github.com/jbq/0a13c8b2f5b4aa5f7cdcd97e32d800f5

**Anything else we should know about your project / environment**

I set `protobuf.keep_descriptor_pool_after_request=1` in `php.ini`

**Comment by haberman** [comment]
The PHP extension has been extensively rewritten since 3.11.x, and the crashing stack trace calls code that no longer exists.

If you are still getting crashes with the current extension, please feel free to reopen.

**Comment by hakimio** [comment]
@haberman 
The extension `v3.19.1` is randomly crashing a lot on Windows with PHP v7.4 (php-cgi) as well. The PHP library, on the other hand, seems to work fine.
Let me know if I could help debugging it.

**Comment by haberman** [comment]
@hakimio could you open a new issue for this? Any info you can provide (especially a repro or a stack trace) would be helpful for debugging.

**Comment by hakimio** [comment]
@haberman any idea how I could generate stack trace on Windows?
