### ISSUE TITLE
Documentation formatting error in Message

### ISSUE THREAD

**Issue by gregcoombe** [protocolbuffers/protobuf#7354]
URL: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message

There appears to be an errant markup text in the code example at the top of the page. This is how it renders for me in Chrome 80 on Ubuntu 16.04:
![Screenshot from 2020-04-02 12-57-58](https://user-images.githubusercontent.com/5033372/78296011-dcda9e80-74e1-11ea-906a-b0959c5e2498.png)

**Comment by bendanon** [comment]
Hi, could you provide a link explaining how to build the docs from sources?
I see the problem but I don't really know how to test my fix.
Thanks!

**Comment by gregcoombe** [comment]
I assume that Google builds these internally using their own tools.
