### ISSUE TITLE
Error on Arena.MaybeAllocateAligned() because of skipping GOOGLE_DCHECK_GE(limit_, ptr_)

### ISSUE THREAD

**Issue by tianxingyang** [protocolbuffers/protobuf#7362]
**What version of protobuf and what language are you using?**
Version: 3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.4 LTS
**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
**What did you do?**
```
syntax = "proto3";

option cc_enable_arenas = true;

message Foo
{
    int32 x = 1;
    string y = 2;
}

message Bar
{
    Foo x = 1;
}
```

```
static const int kMaxSize = 30;

int main()
{
    char* a = new char[kMaxSize];

    cout << "a begin: " << (void*)a << endl;
    cout << "a end:" << (void*)(a + kMaxSize - 1) << endl;

    ArenaOptions optional;
    optional.initial_block = a;
    optional.initial_block_size = kMaxSize - 1;

    Arena arena(optional);
    auto bar0 = Arena::CreateMessage<Bar>(&arena);
    auto foo = bar0->mutable_x();
    foo->set_y("abc");
    cout << "bar: " << (void*)bar0 << endl;
    cout << "foo: " << (void*)foo << endl;
    cout << "foo->y: " << (void*)foo->mutable_y() << endl;

    return 0;
}
```
1. As we can see, the initial size of arena can't put a Bar inside it.
2. After debug using gdb, I found it failed here in arena_impl.h:179 in HasSpace() where limit_ is less than ptr_.
3. For some reason I don't know, GOOGLE_DCHECK_GE(limit_, ptr_) was skipped.

**Comment by mkruskal-google** [comment]
All DCHECKs only execute in debug builds (i.e. NDEBUG is *not* defined).  I can't tell how you built your repro steps, but if you ran using release/optimized builds these checks will be skipped
