### ISSUE TITLE
Custom options are not exposed in the Python protoc plugin interface

### ISSUE THREAD

**Issue by JonasVautherin** [protocolbuffers/protobuf#7363]
It seems to me that custom options are not being exposed in python plugins. I am creating my own protoc plugin in python, which gets a `request` like so:

```python
def generate_reactive(request):
```

This request object contains fields like `file_to_generate`, `parameter`, `compiler_version`, `proto_file`. Basically this exposes everything that is being parsed from my proto file. Except that my custom option is not appearing there, even though it appears in the `*.pb.h` and `*.pb.cc` files, meaning that those plugins get access to it.

Is that a missing feature in the python plugin interface?

I am extending the options with:

```proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

package my.extensions;

extend google.protobuf.FieldOptions {
    string myopt = 1000;
}
```

and trying on one of my fields with:

```proto
    double a_double = 1 [(my.extensions.myopt)="Is this the real life? Is this just fantasy?"];
```

As said above, the string clearly appears in `*.pb.h` and `*.pb.cc`, but doesn't seem exposed to the python plugin.

**Comment by JonasVautherin** [comment]
Oh, I finally got it. One thing that was not clear to me at all, from the [documentation](https://developers.google.com/protocol-buffers/docs/proto#customoptions), was that I need to generate the `_pb2` file corresponding to my extension file, and import it in my protoc plugin.

It's working now!

**Comment by windameister** [comment]
@JonasVautherin I'm struggling with the exact same issue. Wondering how did you finally get it worked.

**Comment by JonasVautherin** [comment]
Honestly it's been a while, but from my comment above, I would say that I just import the extension file in my plugin. That's [here](https://github.com/mavlink/MAVSDK-Proto/blob/1.1.0/pb_plugins/protoc_gen_mavsdk/autogen.py#L15).

**Comment by windameister** [comment]
Thank you for your response. I found this solution the same as you mentioned. I tried and it worked.
https://stackoverflow.com/questions/44931816/custom-protoc-plugin-parsing-not-working-for-custom-options
