### ISSUE TITLE
UTF8 validation error is not returned during message creation

### ISSUE THREAD

**Issue by artemyarulin** [protocolbuffers/protobuf#7364]
Using C++ it's currently possible to create a message with non valid UTF8 strings as UTF8 validation errors are only reported via logs. But then it is not possible to parse such message back as during parsing UTF8 validation errors are actually treated as errors.

My expectation is that `SerializeToString` should return `false` and UTF8 validation should be treated as error for both decoding and encoding of a message.

And wonder if this line is exactly about it? https://github.com/protocolbuffers/protobuf/blob/e667bf6eaaa2fb1ba2987c6538df81f88500d030/src/google/protobuf/generated_message_table_driven_lite.h#L289

**Comment by haberman** [comment]
> My expectation is that SerializeToString should return false and UTF8 validation should be treated as error for both decoding and encoding of a message.

I think it might be better to verify UTF-8 in the setters (with a possible "unsafe" API where the caller can claim that UTF-8 has already been validated). Then the serializer can assume that all fields contain valid UTF-8.

I think we may want to move in this direction in the coming years, but this would be a substantial migration, and there are currently no plans for it.
