### ISSUE TITLE
generated java code using InternalOneOfEnum should reference AbstractMessageLite instead of AbstractMessage

### ISSUE THREAD

**Issue by scaphe** [protocolbuffers/protobuf#7373]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

Code appears to be "wrong" in master, generation of Java code, file java_message.cc:427 references the class InternalOneOfEnum as being in AbstractMessage but it is actually in AbstractMessageLite (super class).  This then generates a java compiler error of: 
type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage\n\t com.google.protobuf.AbstractMessage.InternalOnceOfEnum

**What operating system (Linux, Windows, ...) and version?**
Windows, gradle

**What runtime / compiler are you using (e.g., python version or gcc version)**
Using java/scala runtime with gradle.

**What did you do?**
Have a simple oneof message in a proto3 file, e.g. 
  message IntOrString {
    oneof ios {
      int32 intV = 1;
      string strV = 2;
    }
  }
generate java protobuf source and try to build/compile it.

**What did you expect to see**
Generated java protobuf code compiles

**What did you see instead?**
Compilation error: type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage\n\t com.google.protobuf.AbstractMessage.InternalOnceOfEnum

This can be fixed by hand-editing the generated code and changing the class reference
from:
  com.google.protobuf.AbstractMessage.InternalOneOfEnum
to:
  com.google.protobuf.AbstractMessageLite.InternalOneOfEnum

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by perezd** [comment]
@darly would you mind taking a look at this one?

**Comment by darly** [comment]
Yep I can take this one

**Comment by ygots** [comment]
What is the status of the issue? I'm observing `type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage` with 3.19.3

**Comment by darly** [comment]
This one slipped through the cracks. I will move it up in my list of priorities.

**Comment by ygots** [comment]
> This one slipped through the cracks. I will move it up in my list of priorities.

@darly Thanks! Could you advise how to workaround it? I'm using

`<groupId>com.google.protobuf</groupId>
 <artifactId>protobuf-java</artifactId>`

`<groupId>com.github.os72</groupId>
 <artifactId>protoc-jar-maven-plugin</artifactId>`

**Comment by darly** [comment]
I am trying to reproduce this issue but I am having no luck. Can you provide further reproduction steps

**Comment by ygots** [comment]
Here is the code snippet (file `AbstractMessageBug.proto`):

`syntax = "proto2";

package bug;

message Buggy {
     oneof bug_is_here {
        SingleUse singleUse = 1;
        MultipleUse multipleUse = 2;
     }
}

message SingleUse {
}

message MultipleUse {
}`

Try `protoc-3.19.3-linux-x86_64.exe --java_out=. AbstractMessageBug.proto`. Notice in generated java file this fragment: `public enum BugIsHereCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum`

**Comment by ygots** [comment]
Here is my fix https://github.com/protocolbuffers/protobuf/pull/9439

**Comment by elharo** [comment]
I can't immediately reproduce this either. Though I can generate the same code, I do not see a compiler error. Is this some weird Java version issue? That is, InternalOneOfEnum is protected in AbstractMessageLite so perhaps some compilers are OK with AbstractMessage.InternalOneOfEnum and some aren't? 

You mention scala. That might be the problem here. We need a full, reproducible test case.

**Comment by elharo** [comment]
The following class, which only uses JDK classes and uses a subclass to reference a superclass inner type, compiles:

```
package com.hello;

import java.util.Collection;
import java.util.Map;
import java.util.Set;

final class Main implements Map {
  
  private Main.Entry x;

  @Override
  public int size() {
    // TODO Auto-generated method stub
    return 0;
  }

  @Override
  public boolean isEmpty() {
    // TODO Auto-generated method stub
    return false;
  }

  @Override
  public boolean containsKey(Object key) {
    // TODO Auto-generated method stub
    return false;
  }

  @Override
  public boolean containsValue(Object value) {
    // TODO Auto-generated method stub
    return false;
  }

  @Override
  public Object get(Object key) {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public Object put(Object key, Object value) {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public Object remove(Object key) {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public void putAll(Map m) {
    // TODO Auto-generated method stub
    
  }

  @Override
  public void clear() {
    // TODO Auto-generated method stub
    
  }

  @Override
  public Set keySet() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public Collection values() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public Set entrySet() {
    // TODO Auto-generated method stub
    return null;
  }

}
```

If anyone sees it not compiling, please provide details of your environment, especially the compiler version.

**Comment by elharo** [comment]
Also worth noting. I'm. not sure where `InternalOnceOfEnum` is coming from. It's `InternalOneOfEnum` in all the code I see so I'm skeptical about the error message. Is something (the Scala compiler?) mangling type names for some reason?

**Comment by elharo** [comment]
Occurred to me maybe the problem is only in the lite runtime? Checking now.

**Comment by elharo** [comment]
Doesn't seem so. I  can't reproduce this in the lite runtime either.

**Comment by ygots** [comment]
@elharo I was able to compile your java code, but actually the original issue were in versions for scala 2.12.x and for `scala-maven-plugin` as well. So i agree to close it.

**Comment by richardtsai** [comment]
Just observed exactly the same compilation error. After trying various combination, I notice it only occurs when you have `msg.getXyzCase` in your code and you are on Scala 2.11.X. Upgrading to Scala 2.12.15 seems to fix it.
