### ISSUE TITLE
generated C++ code has clang-tidy warnings: bugprone-unhandled-self-assignment and google-explicit-constructor

### ISSUE THREAD

**Issue by chih-hung** [protocolbuffers/protobuf#7374]
**What version of protobuf and what language are you using?**
Version: latest ported to Android
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

clang-tidy

**What did you do?**

Compile Android Open Source frameworks source files with aprotoc and clang-tidy.

compiler/cpp/cpp_message.cc emits assignment operators like:

  inline DrmFrameworkMetrics_Attributes& operator=(const DrmFrameworkMetrics_Attributes& from) {
    CopyFrom(from);
    return *this;
  }
  inline DrmFrameworkMetrics_Attributes& operator=(DrmFrameworkMetrics_Attributes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

When the above code is compiled with clang-tidy, the first operator gets the following warning:
   warning: operator=() does not handle self-assignment properly [bugprone-unhandled-self-assignment]

Although CopyFrom does compare 'from' with this before assignment,
it is not inlined and invisible to clang-tidy.

To suppress this warning, could you change compiler/cpp/cpp_message.cc to emit a NOLINTNEXTLINE like the following?

  // NOLINTNEXTLINE(bugprone-unhandled-self-assignment)
  inline DrmFrameworkMetrics_Attributes& operator=(const DrmFrameworkMetrics_Attributes& from) {
    CopyFrom(from);
    return *this;
  }

In MessageGenerator::GenerateClassDefinition, it needs to emit
     "// NOLINTNEXTLINE(bugprone-unhandled-self-assignment)\n"
before the assignment operator.

Another clang-tidy warning is google-explicit-constructor for constructors with one argument like this:

 DrmFrameworkMetrics_SessionLifetimesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);

warning: single-argument constructors must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor]

Could you add another NOLINTNEXTLINE output in MessageGenerator::GenerateClassDefinition:

        "  // NOLINTNEXTLINE(google-explicit-constructor)\n"
        "  $classname$(::$proto_ns$::Arena* arena);\n"
        "  void MergeFrom(const $classname$& other);\n"

Thanks.

**Comment by fowles** [comment]
`CopyFrom` handles self assignment so this is a false positive.  We do not support compiler with arbitrary clang-tidy warnings.

We would accept a patch for no-lint-nextline, but are unlikely to do this ourselves right now.
