### ISSUE TITLE
Python protobuf: returning None on Timestamp

### ISSUE THREAD

**Issue by DHofs** [protocolbuffers/protobuf#7375]
The FromDateTime() function from python's protobuf returns None instead of a TimeStamp on my gRPC application.

This is how I have it set up.

```
from google.protobuf.timestamp_pb2 import Timestamp

self.forecastDate = []
ts = Timestamp()
for qty in self.forecastData:
        i = 0
        self.forecastDate.append(
                ts.FromDatetime(datetime.datetime.now() + datetime.timedelta(days=i))
        )
        i += 1
```
I really don't know what I am missing because documentation asks for a datetime as a parameter for that function.

**Comment by anandolee** [comment]
Try:

i = 0
for qty in self.forecastData:
        ts.FromDatetime(datetime.datetime.now() + datetime.timedelta(days=i))
        self.forecastDate.append(ts)
        i += 1
