### ISSUE TITLE
Google protobuf package deprecated

### ISSUE THREAD

**Issue by GlenDC** [protocolbuffers/protobuf#7383]
**What version of protobuf and what language are you using?**
Version: v3.4.0 (but still seems to be the case in latest master)
Language: Golang

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc

**What did you do?**
Compile golang code from a protobuf schema.

**What did you expect to see**
Pretty much the same, except that it uses  google.golang.org/protobuf/proto instead of github.com/golang/protobuf/proto, given that the latter is deprecated by the first. This is also triggering linting (staticcheck) tools in our CI pipelines.

**What did you see instead?**
That it uses `github.com/golang/protobuf/proto` import.

**Comment by GlenDC** [comment]
Feel free to point me to where in the codebase I can fix it and I gladly make a PR if that helps in the process.

**Comment by deannagarcia** [comment]
Sorry for the long delay. We no longer directly support go protos, so you should file an issue in the go-specific repository here: https://github.com/golang/protobuf
