### ISSUE TITLE
'protoc' is not recognized as an internal or external command, operable program or batch file....protobuf..3.4.0

### ISSUE THREAD

**Issue by prathyusha995912** [protocolbuffers/protobuf#7391]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by haberman** [comment]
Can you give some more details about what you were trying to do when you got this error? The error alone isn't enough information to figure out what is wrong.

**Comment by TuushBag** [comment]
I also had the same error using Node.js (Javascript)
Using a windows OS 64bit 
I used cmd to run `protoc.exe -I=. .\proto\dummy.proto --js_out=import_style=commonjs,binary:.\server --grpc_out=.\server --plugin=protoc-gen-grpc=`where grpc_tools_node_protoc_plugin``
Expecting a code to be generated in my server directory
Saying 'protoc.exe' is not recognized as an internal or external command 
I was trying to generate a code with protobuf my version of protobuf is 3.15.8
If that code should run successfully I should be able to see a generated code in my server directory

Any help? Thanks

**Comment by alirezainallo** [comment]
i want to install <b>protoc</b> and use win-64 but after i do this steps, tell me:
'protoc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alirezainallo** [comment]
> i want to install protoc and use win-64 but after i do [this steps](https://www.geeksforgeeks.org/how-to-install-protocol-buffers-on-windows/), tell me: `'protoc' is not recognized as an internal or external command, operable program or batch file.`

i got it. thanks.

**Comment by Rajcr2** [comment]
> > i want to install protoc and use win-64 but after i do [this steps](https://www.geeksforgeeks.org/how-to-install-protocol-buffers-on-windows/), tell me: `'protoc' is not recognized as an internal or external command, operable program or batch file.`
> 
> I got it. I just forgot open a new command prompt after add PATH to my system environment.

Thanks Mate.
