### ISSUE TITLE
PHP with native extension: mergeFromJsonString() crashes when parsing malformed int32 array

### ISSUE THREAD

**Issue by jbq** [protocolbuffers/protobuf#7394]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: PHP

**What operating system (Linux, Windows, ...) and version?**

Debian GNU/Linux 9

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 2.7.13
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 

**What did you do?**

Protobuf message looks like this:

```
message ShippingBatch {
  int32 id = 1;
  google.protobuf.Timestamp modificationDate = 2;
  google.protobuf.Timestamp creationDate = 3;
  repeated int32 participationId = 4;
}
```

When passing the following JSON value to `mergeFromJsonString()` protobuf crashes:

```
{
	"participationId": 12,
}
```

**What did you expect to see**

An error message, like `Expecting array for participationId`

**What did you see instead?**

Crash at https://gist.github.com/jbq/858199254448abb0e803eb31998d1f0d

**Comment by haberman** [comment]
The JSON parser for PHP has been completely rewritten since 3.11.x. I expect that you will no longer see this crash.
