### ISSUE TITLE
Google.Protobuf.JsonParser throws exception if Protobuf contains an enum

### ISSUE THREAD

**Issue by jeffdod** [protocolbuffers/protobuf#7398]
I'm using Proto3 in C# on Windows 10 in a Visual Studio 2019 ASP.NET Core 3.1 application. I'm using the Google.Protobuf NuGet package, version 3.11.2.

I've got the following Protos:

```
syntax = "proto3";

// All C# auto-generated code will have this namespace around gRPC classes
option csharp_namespace = "Protobuf.Authentication";
option optimize_for = SPEED;

enum AuthenticationType {

	Platform = 0;
	OS = 1;
}
```
and
```
syntax = "proto3";

// All C# auto-generated code will have this namespace around gRPC classes
option csharp_namespace = "Protobuf.Authentication";
option optimize_for = SPEED;

import "Authentication/AuthenticationType.proto";

message AuthenticationRequest {

	AuthenticationType authenticationType = 1;
	string user = 2; 
	bytes password = 3;
}
```
and both Protos are in the same folder in my project structure called "Authentication".

When I run the following C# code:

```
var text = [Json representation of AuthenticationRequest here];
IMessage message = (IMessage)Activator.CreateInstance(typeof(AuthenticationRequest));
var parsed = Google.Protobuf.JsonParser.Default.Parse(text, message.Descriptor);

```
I expect to get back a C# object that contains my de-serialized AuthenticationRequest. However, what happens instead is that the .Parse call throws exception:

Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: AuthenticationType'

I try this code with my other Protobufs and what I find is that the code works for all Protobuf message types as long as they do not contain enums. So basically, whenever a Protobuf contains enums, the code throws.

This seems like a bug to me, especially considering that when you debug and look at the message.Descriptor in the code above, you can see that the "EnumTypes" field has a count of zero, even though there are enum types in AuthenticationRequest.

**Comment by jeffdod** [comment]
To answer my own question, it looks like the Protobuf enum was not the issue. It was because the AuthenticationRequest message in the Profobuf file used lower-case letters to begin the field names.

**Comment by yinzara** [comment]
Proto files should generally use snake case (i.e. lower case with _ separating words) for all field names.  They will be properly translated to camelCase depending on the language being generated and the configuration.
