### ISSUE TITLE
Google Protobuf MessageParser throws exception on Protobuf type "bytes"

### ISSUE THREAD

**Issue by jeffdod** [protocolbuffers/protobuf#7400]
**What version of protobuf and what language are you using?**
I'm using Proto3 with C# and Google.Protobuf NuGet Package 3.11.2.

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2019

**What did you do?**

I built an ASP.NET Core 3.1 project which includes .proto files, and at various times I serialize/deserialize the C# versions of the Proto classes.

I've got these protos:

```
syntax = "proto3";
option csharp_namespace = "Protobuf.Authentication";
option optimize_for = SPEED;

enum AuthenticationType {

	PLATFORM = 0;
	OS = 1;
}
```

and

```
syntax = "proto3";
option csharp_namespace = "Protobuf.Authentication";
option optimize_for = SPEED;

import "Authentication/AuthenticationType.proto";

message AuthenticationRequest {

	AuthenticationType AuthenticationType = 1;
	string User = 2; 
	bytes Password = 3;
}
```

both of which are in the same folder in my application called "Authentication".

I have the following C# code:

```
        var text = @"{""AuthenticationType"":0,""User"":""demo"",""Password"":[100,0,101,0,109,0,111,0]}";
        IMessage message = (IMessage)Activator.CreateInstance(typeof(AuthenticationRequest));
        var parsed = message.Descriptor.Parser.ParseJson(text);
```

**What did you expect to see**
I would expect to see the Json text deserialized into an instance of my object.

**What did you see instead?**
The ParseJson method throws the exception:
Google.Protobuf.InvalidProtocolBufferException: 'Unsupported JSON token type StartArray for field type Bytes'

All other IMessage types that I pass through this code works, but if the Protobuf "bytes" type is included anywhere in a message, this exception is thrown.

**Comment by ObsidianMinor** [comment]
`bytes` are represented in the proto3-json mapping as a base64 string. So valid code for that message would be

```cs
var text = @"{""AuthenticationType"":0,""User"":""demo"",""Password"":""ZABlAG0AbwA=""}";
var parsed = AuthenticationRequest.Parser.ParseJson(text);

**Comment by jeffdod** [comment]
Ah, thank you for that information.

I'm actually not generating the Json representation manually...I'm taking the C# object and serializing it. However, every serializer I use seems to serialize the ByteString (C# representation of Protobuf-bytes) as a Json array of numeric objects, not as a base64 string.

Do you have any suggestions as to which serializer would work with a ByteString object?

**Comment by jeffdod** [comment]
Thank you!
