### ISSUE TITLE
Cannot compile protobuf libraries from external repositories

### ISSUE THREAD

**Issue by sooneecheah** [protocolbuffers/protobuf#7401]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.7

**What did you do?**
1. Create a `WORKSPACE` file with a link to an external repo:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name= "some_repo_with_proto_files",
    ...
)
```

2. In a `BUILD` file, attempt to compile a protobuf library using the rules in `protobuf` and the `.proto` files in the external repo as `srcs`:
```
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library( # note using cc_proto_library doesn't fix it either
    name = "some_proto",
    srcs = ["@some_repo_with_proto_files//src:external.proto"],
    ...
)
```

**What did you expect to see**
The `.proto` file to be compiled to a `_pb2.py` file.

**What did you see instead?**
Error message:
`label '@some_repo_with_proto_files//src:external_pb2.py' is not in the current package`

**Anything else we should know about your project / environment**
It would be ideal to be able to keep `.proto` files in a separate repo that defines interfaces to services, and import/compile them into projects as needed. This bug prevents this from being possible in python at least.

**Comment by deannagarcia** [comment]
Sorry for the late response.

This is most likely an error in the upstream repository. You need whatever rule you want to use the `external_pb2.py` file to depend on your `py_proto_library` rule. Right now your `py_proto_library` rule just creates the file but doesn't ever use it anywhere else.

I'm going to go ahead and close this, but if you still can't make it work feel free to reopen.
