### ISSUE TITLE
Protobuf go benchmark build failed

### ISSUE THREAD

**Issue by pvautee** [protocolbuffers/protobuf#7404]
**What version of protobuf and what language are you using?**
Version: master.
Language: go

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
go version go1.14.1 linux/amd64

**What did you do?**
I was trying to run protobuf benchmark and steps metioned here: https://github.com/protocolbuffers/protobuf/tree/master/benchmarks
I am building benchmark for go language. so when I do 
"make go" i see below error.

```ERROR````
mkdir -p 'tmp/java/src/main/java'
touch make_tmp_dir
oldpwd=`pwd` && ( cd . && $oldpwd/../src/protoc -I. -I../src --go_out=$oldpwd/tmp datasets/google_message1/proto3/benchmark_message1_proto3.proto )
2020/04/21 01:40:41 WARNING: Missing 'go_package' option in "datasets/google_message1/proto3/benchmark_message1_proto3.proto", please specify:
        option go_package = "datasets/google_message1/proto3;benchmarks_proto3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

oldpwd=`pwd` && ( cd . && $oldpwd/../src/protoc -I. -I../src --go_out=$oldpwd/tmp benchmarks.proto )
2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "benchmarks.proto", please specify:
        option go_package = ".;benchmarks";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

oldpwd=`pwd` && ( cd . && $oldpwd/../src/protoc -I. -I../src --go_out=$oldpwd/tmp datasets/google_message1/proto2/benchmark_message1_proto2.proto )
2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message1/proto2/benchmark_message1_proto2.proto", please specify:
        option go_package = "datasets/google_message1/proto2;benchmarks_proto2";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

oldpwd=`pwd` && ( cd . && $oldpwd/../src/protoc -I. -I../src --go_out=$oldpwd/tmp datasets/google_message2/benchmark_message2.proto )
2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message2/benchmark_message2.proto", please specify:
        option go_package = "datasets/google_message2;benchmarks_proto2";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

oldpwd=`pwd` && ( cd . && $oldpwd/../src/protoc -I. -I../src --go_out=$oldpwd/tmp datasets/google_message3/benchmark_message3.proto datasets/google_message3/benchmark_message3_1.proto datasets/google_message3/benchmark_message3_2.proto datasets/google_message3/benchmark_message3_3.proto datasets/google_message3/benchmark_message3_4.proto datasets/google_message3/benchmark_message3_5.proto datasets/google_message3/benchmark_message3_6.proto datasets/google_message3/benchmark_message3_7.proto datasets/google_message3/benchmark_message3_8.proto )
2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_7.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_8.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_6.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_5.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_4.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_3.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_2.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3_1.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/04/21 01:40:42 WARNING: Missing 'go_package' option in "datasets/google_message3/benchmark_message3.proto", please specify:
        option go_package = "datasets/google_message3;benchmarks_google_message3";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

protoc-gen-go: invalid FileDescriptorProto "datasets/google_message3/benchmark_message3_5.proto": proto: message "benchmarks.google_message3.Message0" is a MessageSet, which is a legacy proto1 feature that is no longer supported
--go_out: protoc-gen-go: Plugin failed with status code 1.
Makefile:2977: recipe for target 'go_protoc_middleman' failed
make: *** [go_protoc_middleman] Error 1

**What did you expect to see**
I was expecting benchmark run to completion.  I think all datasets proto message is missing "option go_package" for proto3. Could you please telll me how to fix it? 

**What did you see instead?**
ERROR as above. I have also tried using option go_package as suggested in an error but it did not make that error go away. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by daixiang0** [comment]
Still fail refer to doc, please help /cc @TeBoring @xfxyjwf @haberman

**Comment by deannagarcia** [comment]
Sorry for the long response time. We no longer support go protos directly, you should file your issue in the go specific repository: https://github.com/golang/protobuf.
