### ISSUE TITLE
Protobuf Bytes parser (meanings)

### ISSUE THREAD

**Issue by M-Tonin** [protocolbuffers/protobuf#7405]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3? proto2
If it's about generated code change, what programming language? python

**Describe the problem you are trying to solve.**
I have been studying the format of the protobuf, but at the level of bytes I cannot identify what signals the end of one field and the beginning of another, or what shows me that it is a new type of data. I can see the strings, see the floating points. But I don't know what a new field is, when a new field starts or ends.

**Describe the solution you'd like**
Sine description about this. About how to interpret the protobuf bytes. What is the stop and start bytes.
**Describe alternatives you've considered**

**Additional context**

**Comment by jtattermusch** [comment]
Here's the wire format documentation https://developers.google.com/protocol-buffers/docs/encoding

Closing because this is not actionable and it's not an issue.
