### ISSUE TITLE
add 'Date' and 'DateTime' well known types

### ISSUE THREAD

**Issue by yinzara** [protocolbuffers/protobuf#7411]
**Reasoning**
The current Timestamp well known type represents an instant in time (i.e. a specific number of seconds and nanoseconds from the epoch) in UTC.  While this is useful for marking a specific point in time, almost all modern programming languages have some representation of a date without a time and a date and time with a timezone offset (or timezone identifier).   

**New Well Known Types**
I propose moving the following google APIs types to become well known types and adding proper support in languages that support these types. 

https://github.com/googleapis/googleapis/blob/master/google/type/datetime.proto
https://github.com/googleapis/googleapis/blob/master/google/type/date.proto

Moving them to well known types should make their serialized wire protocol identical so conversion between them should be trivial.

I may suggest changing the datetime.proto to remove the OneOf that permits IANA timezone codes and only allow an offset to ensure maximum compatibility with all language representations. Since the IANA timezone field is the last numerically, it could be removed without changing the wire protocol.  However since all languages could calculate this offset if they had an appropriate timezone database, the argument could be made to keep it.  I also suggest that the "year" field be required but could be convinced otherwise.

**JSON Support**
We already use RFC 3339 (and extension of ISO 8601) to format and parse a timestamp in UTC.  I propose we use RFC 3339 (full-date) for Date and RFC 3339 (date-time) for DateTime.
https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

I also propose we update the JSON canonical representation to support the RFC 3339 string representations of those types as well.

Using the existing "js_type" option, the "string" type could imply the RFC 3339 representation, while the "numeric" type could represent the object form with fields for each of the numeric parts (i.e. { "year": 2008, "month": 10, "day": 9 } ).  Both could be interpreted automatically (just as the other types that support the same option) and converted into either representation without specifying a parsing behavior or loss of data.

This is inline with the OpenAPI specifications handling for 'date' and 'date-time' formatted strings: 
https://swagger.io/specification/#dataTypes

And the JSONSchema representation:
https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times

**Language Support**
I have done a high level survey of each language (though I'm not an expert in most) and their built in support of the proposed constructs.  

Like Timestamp, we can provide the appropriate conversions methods between the WKT and the language specific representation.  For the languages that don't support all or part of one constructs, the WKT itself can provide enough details to be useful and agnostic for most use cases.  

For languages that have implementation options, we can add new MessageOptions or FieldOptions to descriptor.proto to determine the generation behavior for the new constructs.

Python - Full support for Date and DateTime
https://docs.python.org/2/library/datetime.html (datetime.date and datetime.datetime)

Ruby - Full Support for Date and DateTIme
https://ruby-doc.org/stdlib-2.4.1/libdoc/date/rdoc/DateTime.html
https://ruby-doc.org/stdlib-2.4.1/libdoc/date/rdoc/Date.html

Java - Full Support of both Date and DateTime as of Java 1.8 (released March 2014).
Full support for DateTime (using java.util.Calendar) before 1.8. No support for Date before 1.8.
https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html
https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html
https://community.oracle.com/docs/DOC-983209

Objective-C - Full Support for DateTime and Date - some implementation details
https://developer.apple.com/documentation/foundation/nsdate
https://developer.apple.com/documentation/foundation/nsdatecomponents

Golang - Full support for DateTime, no support for Date
https://golang.org/pkg/time
https://github.com/golang/go/issues/19700
https://godoc.org/cloud.google.com/go/civil

C Sharp .NET - Full support for DateTime, limited support for Date until .NET 6 and DateOnly when full support was added
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.date
https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset
https://docs.microsoft.com/en-us/dotnet/api/system.dateonly?view=net-6.0

C++ - Full Support for Date, limited support for DateTime
https://en.cppreference.com/w/cpp/chrono/year_month_day

Dart - Full support for DateTime, limited support for Date
https://api.dart.dev/stable/2.7.2/dart-core/DateTime-class.html
https://github.com/dart-lang/sdk/issues/1424
https://github.com/dart-lang/sdk/issues/5627

JavaScript - Full Support for DateTime, limited support for Date however I suggest using the js_type suggestion above to allow for a RFC 3339 based 'string' representation
https://www.w3schools.com/jsref/jsref_obj_date.asp
https://www.w3schools.com/jsref/jsref_gettimezoneoffset.asp
https://www.w3schools.com/jsref/jsref_todatestring.asp
https://www.w3schools.com/jsref/jsref_parse.asp

PHP - Full Support for DateTime, no support for Date
https://www.php.net/manual/en/class.datetime.php

**Comment by yinzara** [comment]
@haberman I know this is a huge ask, but is there a chance you guys might consider this?  I haven't gotten any response from maintainers.

**Comment by haberman** [comment]
Hi @yinzara. I think the idea of having Date and/or DateTime as a well-known type makes sense. There are a lot of things to consider and coordinate for a proposal like this, and we are spread a bit thin at the moment unfortunately. So we probably won't be able to act on this very soon.

The precedent we have with other well-known types is to always use their special string form in JSON. I don't think we'd want to switch this on/off with `js_type`. However that would also make it more difficult to migrate the existing googleapis types to a well-known type, since it would change the JSON representation.

**Comment by yinzara** [comment]
Been a little over a year since our last comment. Was curious if there was any possible changes.

**Comment by perezd** [comment]
We haven't had time to propose this, and it doesn't seem like a thing we're likely to get to soon.

**Comment by elharo** [comment]
On the Java side we still need to support Java 1.7. That is unlikely to change before 2022.

**Comment by yinzara** [comment]
dotnet 6 now supports the `DateOnly` type out of the box so C# would now be a fully supported language if using .NET 6

**Comment by gregtzar** [comment]
+1 Would be nice to map to go [civil.Date](https://pkg.go.dev/cloud.google.com/go/civil) for the non-timestamp variant.

**Comment by benguild** [comment]
Just wanted to +1 this as it seems (as Google is linked) that this is a known limitation— https://github.com/googleapis/googleapis/blob/master/google/type/date.proto

There are definitely instances where you don't want to associate a time with a calendar date, for risk of the date "flipping" between timezones the user may be in.

For now, basically bundling your own version of what Google includes themselves is necessary: https://github.com/googleapis/googleapis/blob/1c4f24e66d8559a680e472eab70ccfb1e6fbd685/google/type/date.proto#L39-L52

**Comment by yinzara** [comment]
Still valid.  Please don't mark inactive

**Comment by yinzara** [comment]
Nearly 4 years from proposal and multiple comments and +1s.  Would really love to see this get some love by maintainers

**Comment by benguild** [comment]
Perhaps relevant: https://engineering.hardfin.com/2024/02/date-the-missing-type/

**Comment by majelbstoat** [comment]
Google’s Civil Date seems appropriate, and is what for example Spanner uses
for its Date columns.

https://pkg.go.dev/cloud.google.com/go/civil

**Comment by benguild** [comment]
@haberman @acozzette @thomasvl @ericsalo any thoughts here potentially? would be great to see it as a "built in" but if it's a "won't fix" then we'll stop bumping it to keep it open.

**Comment by haberman** [comment]
Realistically I think this is unlikely to happen anytime soon. We have never added a well-known type since the initial set of well-known types launched in 2016. That means we don't have any precedent for how to introduce a new well-known type without breaking compatibility. Well-known types are special-cased in multiple parts of the stack (JSON parser/serializer, generated APIs), which means a change of this sort would need to be coordinated across all languages. That's a lot of work that would need to pull in a lot of people. We'd also probably need to coordinate with non-Google-owned implementations somehow.

Google APIs are using the versions from https://github.com/googleapis/googleapis/blob/master/google/type and this seems to be working for them. I can see the appeal of having these types in the core protobuf library, but given the scope of this project there would need to be a very large benefit to justify deprioritizing other projects in favor of this.

**Comment by benguild** [comment]
Thanks for the thoughtful and thorough reply back, Joshua!
