### ISSUE TITLE
No longer needed call to AC_PROG_CXX_FOR_BUILD in configure.ac

### ISSUE THREAD

**Issue by Arfrever** [protocolbuffers/protobuf#7413]
https://github.com/protocolbuffers/protobuf/blob/c74057267d64d0b5b8a48feeab2d5b015590aca0/configure.ac#L78

This was introduced in commit b40d318650ccde8893400c32814df6f4cdd24fe5 (by @acozzette) on 2017-01-03 along with  `m4/ax_prog_cc_for_build.m4` and `m4/ax_prog_cxx_for_build.m4` files (copied from GNU Autoconf Archive project).

However commit b3e4e3abe0d2f79ec9f1e4e24e12dc642d662546 (by @xfxyjwf) on 2018-06-01 deleted usage of `CXX_FOR_BUILD` variable in `src/Makefile.am`. No other usage of `*_FOR_BUILD` variables remains.

So call to `AC_PROG_CXX_FOR_BUILD` macro in `configure.ac` and `m4/ax_prog_cc_for_build.m4` and `m4/ax_prog_cxx_for_build.m4` files are now useless and should be deleted.

**Comment by Arfrever** [comment]
Also issue #3141 will become obsolete afterwards.

**Comment by Arfrever** [comment]
@acozzette: Ping.
```
--- a/configure.ac
+++ b/configure.ac
@@ -75,7 +75,6 @@
 # Checks for programs.
 AC_PROG_CC
 AC_PROG_CXX
-AC_PROG_CXX_FOR_BUILD
 AC_LANG([C++])
 ACX_USE_SYSTEM_EXTENSIONS
 m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
```
Followed by `git rm m4/ax_prog_cc_for_build.m4 m4/ax_prog_cxx_for_build.m4`.

**Comment by xen0n** [comment]
Drive-by triage (while trying to bump the Gentoo package): this is no longer relevant since #10132 removed the autotools machinery.
