### ISSUE TITLE
Add `emit_defaults = true` option for JSON serializer in PHP

### ISSUE THREAD

**Issue by lihjgamer** [protocolbuffers/protobuf#7419]
for example:   
 message Request {
        string name = 1;
        string pwd = 2;
        string capid = 3;
        string udid = 4;
        int32 error = 5;
    }

when message Request all fields are default value,I get json string "{}"

I expected the result who is json string with all message struct!

**Comment by haberman** [comment]
By default protobuf JSON serialization only outputs fields that have been explicitly set. This is like pure JSON where you have to set a field to make it present in the output.

Some protobuf libraries such as Protobuf Ruby let you specify a `emit_defaults = true` option for JSON serializing. This will emit zeros for unset fields that don't have presence. So you would get:

```
{"name":"", "pwd":"", "capid":"", "udid": "", "error": 0}
```

We could add such a feature to PHP also.

Another option is to use `optional` fields and set them explicitly to 0/empty. For more info see: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by deannagarcia** [comment]
Closing this since it is consistent with JSON serialization and isn't a priority for the team.
