### ISSUE TITLE
Use MessageToJsonString() convert Message into Json crash. Segment fault.

### ISSUE THREAD

**Issue by MelodyD** [protocolbuffers/protobuf#7420]
**What version of protobuf and what language are you using?**
Version: v3.11.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 5.4.0

**What did you do?**
1. I have a.out link b.so and b.so link libprotobuf.a .
2. I was write code in b.so as below
```
	std::string json;
        cicv::routing::RoutingResponse response;
	google::protobuf::util::MessageToJsonString(response,&json);
```
3. When i debug a.out , it will always crash at code **google::protobuf::util::MessageToJsonString(response,&json);**.
4. Here is the gdb info.
```
Breakpoint 3, cicv::routing::ResultGenerator::GeneratePassageRegion (this=0x7fffffffe45e, map_version=..., start_param=..., nodes=..., arc_dataset=0x6b08c0) at /home/cicv/projects/GD_RouteEngine/api/src/NET/result_generator.cc:46
46		google::protobuf::util::MessageToJsonString(response,&json);

Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xffffdd5800000000) at malloc.c:3103
3103	malloc.c: 没有那个文件或目录.
```

**Comment by MelodyD** [comment]
![image](https://user-images.githubusercontent.com/15688795/80218377-b092e780-8673-11ea-8538-43ff16d11e09.png)
why?

**Comment by saai63** [comment]
Hello @MelodyD,
Why was this issue closed?
What was the fix?
