### ISSUE TITLE
UInt32 represented as int in java

### ISSUE THREAD

**Issue by simPod** [protocolbuffers/protobuf#7426]
**What version of protobuf and what language are you using?**
Version: v3.9.+
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Macos Catalina

Values for `uint32` fields are represented as `int` java primitive type in generated code. That type is capable of holding max value 2^32-1. `uint32` max value overflows the capacity of java `int`. 

Eg. `3 936 623 488` is returned as `-358 343 808` from protobuf generated `uint32` getter.

How to work with it properly then? Currently I have to do this to get correct value but that does not seem to be good DX.

```java
if (value >= 0) {
    return value;
} else {
    return value & 0x00000000FFFFFFFFL;
}

-------------

Integer::toUnsignedLong(value)
```

I thought of two solutions:

1) document the behaviour
2) introduce a new type of getter that returns instance of `Number` so user does not need to do conversion manually. Except current `getUInt32Field()` there would have been `getUInt32FieldAsNumber()` introduced.

Would MR with any such fix be accepted?

**Comment by haberman** [comment]
The mapping of unsigned integers in Java is documented here: 
- https://developers.google.com/protocol-buffers/docs/proto3?hl=en#scalar
- https://developers.google.com/protocol-buffers/docs/proto?hl=en#scalar

I don't think we can introduce a new getter for this. Also the solution you gave would not solve the problem for uint64.
