### ISSUE TITLE
Import "gogoproto/gogo.proto" was not found or had errors

### ISSUE THREAD

**Issue by ighack** [protocolbuffers/protobuf#7427]
```
protoc -I=./ --python_out=./ ./binlog.proto

gogoproto/gogo.proto: File not found.
binlog.proto:3:1: Import "gogoproto/gogo.proto" was not found or had errors.
```
libprotoc 3.11.4

what should I do?

**Comment by jontroncoso** [comment]
@ighack 2 things:
- You need to include the protos that are imported in the CLI command. 
- (I think) You need to include all the paths that all the protos are importing from. 

I think this should work:

```
protoc -I=./ -I=./gogoproto --python_out=./ gogoproto/gogo.proto ./binlog.proto
```

**Comment by BMWE30** [comment]
> @ighack 2 things:
> 
> * You need to include the protos that are imported in the CLI command.
> * (I think) You need to include all the paths that all the protos are importing from.
> 
> I think this should work:
> 
> ```
> protoc -I=./ -I=./gogoproto --python_out=./ gogoproto/gogo.proto ./binlog.proto
> ```

literally saved my life

**Comment by jontroncoso** [comment]
@BMWE30 I think you can close this ticket since it is working as expected. 

Maybe this should be documented somewhere?

**Comment by themartto** [comment]
yo what if the files comes from go package?
