### ISSUE TITLE
PHP: Passing data to generated message on instantiation results in Segmentation Fault.

### ISSUE THREAD

**Issue by jontroncoso** [protocolbuffers/protobuf#7431]
**What version of protobuf and what language are you using?**

```
# protoc --version
libprotoc 3.11.4
# pecl list
Installed packages, channel pecl.php.net:
=========================================
Package  Version State
grpc     1.27.0  stable
protobuf 3.11.4  stable
```
Version: 

- libprotoc 3.11.4
- grpc 1.27.0
- protobuf 3.11.4

Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Mac (`ubuntu:18.04` in docker)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc I think?

**What did you do?**
```
<?php 
$test = new MyNamespace\MyMessage([
    'foo' => 'bar',
]);
```

**What did you expect to see**
a `MyNamespace\MyMessage` object with data loaded into it.

**What did you see instead?**
```
Segmentation fault
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Unfortunately the only error I get is `Segmentation fault`.

**Anything else we should know about your project / environment**

This is what I run to generate the messages/client
```
protoc \
    -I shared \
    --grpc_out ivr/src/Proto \
    --php_out ivr/src/Proto \
    --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin \
    shared/messages.proto  \
    shared/services.proto
```

**Comment by haberman** [comment]
The protobuf PHP implementation has been largely rewritten since 3.11.4. If you can still reproduce this SEGV with the current code, please include a repro and I will take a look.
