### ISSUE TITLE
powerpc environment ，load or read prtobuf Transform libraries  ,received SIGSEGV, Illegal instruction

### ISSUE THREAD

**Issue by zzb2019** [protocolbuffers/protobuf#7432]
1. I cross-compiled the powerpc version of protobuf in the ubuntu environment, but the protoc under running bin cannot be executed, and Illegal instruction appears
Power environment, uname -a is printed as follows:
Linux KEDACOM 3.8.13-rt9-g609aea3 #1 Thu Apr 2 18:07:05 UTC 2020 PPC GNU/Linux

2. Later, I compiled the libprotobuf. A static library generated by cross compilation into my protobuf conversion library. It's OK to complete the demo test, but I will report an illegal instruction when I load the conversion library through another library, and the SIGSEGV signal will be received when I call the stack.

How to deal with this problem?

**Comment by haberman** [comment]
It sounds like something is likely wrong with your cross-compilation setup. If you think this might be a bug in protobuf, I think you should be able to replicate it in a native compile.

There isn't enough information here to suggest a bug in protobuf. If you are able to reproduce with more info, feel free to reopen.

**Comment by zzb2019** [comment]
The following is the version I compiled the environment and cross-compiled, as well as the target version:
Powerpc version :Linux 3.8.13-rt9-g609aea3 #1 PPC GNU/Linux
Ubuntu version:
Linux 4.4.0-177-generic # 207-ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
Powerpc-linux-gnus-gcc version: GCC version 4.5.1 (Sourcery G++ Lite 2010.09-55)
GCC version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
First, compile the Linux version normally,
Compile steps:
1. / configure -- prefix = / usr/local/protobuf /
2 make
3 make install
4. Modify /etc/ld.so.conf to add the installation path /usr/local/protobuf
Build the powerpc-linux version
1. Export PATH=$PATH:/opt//freescale-2010.09/bin // import powerpc-linux installation environment
2 make the clean (distclean)
3./configure --prefix=/opt/freescale -- 2010.09/protobuf --build =i686-linux --host=powerpc-linux-gnu CC=powerpc-linux-gnu GCC
CXX = powerpc Linux - gnu g + + - with - protoc = protoc
4 the make
5 make install
# make clean up the previous compile information
#./configure --prefix= compile library output path
# --build=i686-linux current Linux running environment, do not know the input gcc-v, you can see
# --host=powerpc-linux-gnu specifies the host running environment
# CXX= cross-compile g++ paths
# CC= cross-compile the GCC path
If a gmock or gtest error occurs during./configure, you can comment out the corresponding code by looking at confg.log.
You get the libprotobuf.a library file, import the library file and the Google /protobuf folder of the installation path into our powerpc environment directory, and modify the Makefile file.
