### ISSUE TITLE
java_multiple_files for csharp

### ISSUE THREAD

**Issue by cyberb** [protocolbuffers/protobuf#7445]
Could you please implement java_multiple_files for csharp files?

We have a generated proto with 7k messages.
It generates 7k java classes (java_multiple_files = true) but only one csharp file (65MB).

Single huge file is a problem for IDEs and even runtimes.

**Comment by jskeet** [comment]
I'd expect 7000 files to be a problem for IDEs as well. The number of source files shouldn't be relevant at execution time at all.

Given that this request is over two years old without any other community support (and I haven't seen similar requests elsewhere) I'd suggest closing this, @mcy.

**Comment by hlopko** [comment]
Closing as recommended by @jskeet
