### ISSUE TITLE
PHP messages should not use deprecated message types for internal checks

### ISSUE THREAD

**Issue by jdpedrie** [protocolbuffers/protobuf#7447]
For historical reasons, nested messages generate two files in PHP.

For instance, given the following proto:

```
message foo {
	message bar {}
}
```

Protoc will generate the following files, the last of which contains a deprecation warning and alias for backwards compatibility. Users are directed to use `\Foo\Bar`.

```
./Foo.php
./Foo/Bar.php
./Foo_Bar.php
```

Messages internally still use the deprecated class name for type checking (see [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/php/php_generator.cc#L745-L751) for template source).

For instance, given the example above, the method `Foo::setBar($var)` would contain the following:

```php
public function setBar($var)
{
	GPBUtil::checkMessage($var, \Foo_Bar::class);
	$this->bar = $var;

	return $this;
}
```

This means that users have no means of preventing the library from raising `E_USER_DEPRECATED` errors. When users have a custom error handler configured, unless `E_USER_DEPRECATED` is explicitly excluded, those deprecation warnings are transformed to exceptions. This has proven to be a point of friction for a large number of users.

Since `\Foo_Bar` and `\Foo\Bar` are interchangable, there should be no regression or user impact in replacing the deprecated message name in type check calls with the new name.

**Comment by haberman** [comment]
This was fixed in https://github.com/protocolbuffers/protobuf/pull/7695/commits/77edcb3f3d0a1a7fa57fc293b1b91a2435981b95 as part of https://github.com/protocolbuffers/protobuf/pull/7695.
