### ISSUE TITLE
This issue was closed AND THEN there is a few great ideas after it is closed...

### ISSUE THREAD

**Issue by deanorderly** [protocolbuffers/protobuf#7450]
This is a plea to reconsider a previous request.  Please read all the comments 'after' the issue was closed please...

https://github.com/protocolbuffers/protobuf/issues/1451

Temporarily, we are going to implement one of those solutions however, why would protobuf not do one of those for us?

I have had 3 developers already deploy bugs to production on well tested code that then nullpointered when it hit a large prod data set with very few 'null' values.  This is really a nightmare.

I think the one addition of adding setSafelyXXXXX fields in the generated code is decent or some of the others.  ie. to set Methods. setName(name) and setNameSafely(name) and most developers will wonder and read the code as they will think wtf is setNameSafely(IMHO, that's a good thing).

I mean the other option is protobuf force everyone to go implement their own solution from that list however why would this not be part of the library so everyone could benefit instead.

**Comment by deanorderly** [comment]
related as well actually and perhaps you have an answer https://stackoverflow.com/questions/61541583/does-protobuf-support-json-properly-for-nulls-since-null-support-is-odd

**Comment by deanorderly** [comment]
and related as well as square built their own too(do we really all have to build our own to solve this issue?) https://groups.google.com/forum/#!topic/protobuf/d51mjUf_w7g

**Comment by deanorderly** [comment]
and another related one where people doing their own solutions (and I am struggling in trying to find out 'how to do the same')...

https://groups.google.com/forum/#!topic/protobuf/KcLoxlJGVMY

**Comment by deanorderly** [comment]
on other question that keeps bothering me is how much of the protobuf market is using C++, etc. (ie. no null type languages)....and why it caters to the minor piece of the market.  Why instead does protobuf not 'flip the problem'....  support default values on the wire and then in C++, the generation would be such that it would have some methods for existence or not.  Instead, the java code, the C# code, scala code(list goes on and on and on) is made to be much more complex.

EVEN more important is that 'many' databases support null for was it set or not.  (in some "" == null, but then there is integer types and such too that can exist as null or a value.  These go through our languages and then fail in protobuf.

So, I wonder why protobuf is catering to a minor piece of the market here?  Or perhaps google protobuf's internal market in their company is dominated by C++ making it hard for the rest of the market external to google(which makes sense.....I mean, if I am coding a project, I make it easiest for all 'my' developers first and everyone else second).  I am just curious here.

**Comment by elharo** [comment]
I'm looking into some nullability issues now. However as written this bug doesn't help. If there are specific issues that should be considered such as `@NonNull` annotations please file them individually so each one can be triaged and prioritized in isolation.

That said, don't expect major changes in null behavior ion this library. Backwards compatibility is paramount.
