### ISSUE TITLE
Use jdk classes instead of protobuf libraries

### ISSUE THREAD

**Issue by mmpataki** [protocolbuffers/protobuf#7457]
**What language does this apply to?**
Java

If it's a proto syntax change, is it for proto2 or proto3?
No

If it's about generated code change, what programming language?
Java

**Describe the problem you are trying to solve.**
The generated Java code uses the `com.google.protobuf` library classes (for builders, parsing) and this creates a dependency for the project and can cause some conflicts if multiple versions of protobuf is used by different components.

**Eg.**   
While writing a metrics sink plugin for the hadoop components, we can't use (haven't tried) whatever protobuf library version we want to use as hadoop components already use some version of protobuf.
***Why can't we use the same protobuf lib shipped with the Hadoop?***  
The plugin can be used on other version of hadoop or products like HBase, if they are using different version of protobuf, it may cause problems (again these problems are guessed, never occured)

**Describe the solution you'd like**
We can generate java code just the [de]serializer which uses just the JDK/generated classes.

**Describe alternatives you've considered**
Shading can be done for the protobuf libs and used

**Comment by elharo** [comment]
I think this is a hadoop issue.
