### ISSUE TITLE
use protobuf dll for c++ project

### ISSUE THREAD

**Issue by Eyal-Elbaz** [protocolbuffers/protobuf#7467]
Hi there,
I'm using the latest  protobuf  version on visual studio 2019, windows 10, c++ 
I have a project and I'm using protobuf but I can't send my code with a request to download certain lib so I decided to use all in downloaded libprotobuf.dll and added it to my project but I get this error:
LNK1107: invalid or corrupt file: cannot read at 0x2C0
is there any way to fix this or maybe another way to include protobuf without other installations ?

**Comment by flymaxty** [comment]
hi @Eyal-Elbaz 
sorry for interrupt, I've met the same problem, how do you fix it?
