### ISSUE TITLE
Release java artifacts for 3.12.0-rc1

### ISSUE THREAD

**Issue by thesamet** [protocolbuffers/protobuf#7473]
Is the binary artifact for Java available somewhere else? I was looking for the release candidate at the usual place:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/

**Comment by haberman** [comment]
Thanks for speaking up. This is my first time doing a release and I think I needed to hit the "Release" button in Sonatype. Hopefully it will show up soon.

**Comment by haberman** [comment]
Looks like the artifacts are up now: https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.12.0-rc-1/
