### ISSUE TITLE
Forbidden in downloading assets 

### ISSUE THREAD

**Issue by maratdr** [protocolbuffers/protobuf#7475]
**What version of protobuf and what language are you using?**
Version: v3.7.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Navigate to `Release`
2. Find any assets under release, e.g. https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0-rc1/protobuf-all-3.12.0-rc-1.tar.gz
3. Click and it will shows
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
```

**What did you expect to see**
Successful download

**What did you see instead?**
Download forbidden

**Comment by adamo57** [comment]
Seeing this issue as well.

**Comment by maratdr** [comment]
it seems to be fixed now.

**Comment by haberman** [comment]
Hmm, I tried clicking on your link above and it worked fine. Should that be enough to reproduce the problem?
