### ISSUE TITLE
[ObjC] Consider using NS_CLOSED_ENUM by default

### ISSUE THREAD

**Issue by Cyberbeni** [protocolbuffers/protobuf#7488]
**What language does this apply to?**
Objective-C (/ Swift)

**Describe the problem you are trying to solve.**
When using the Objective-C generated code from Swift, it will require you to define an `@unknown default` case for future cases when the library gets updated separately. In this case (at least if the library contains Swift code), the BUILD_LIBRARY_FOR_DISTRIBUTION flag will be used for building.

**Describe the solution you'd like**
Use NS_CLOSED_ENUM when BUILD_LIBRARY_FOR_DISTRIBUTION is not set.
https://github.com/protocolbuffers/protobuf/blob/bf3eef94c1fc5470407c4f69bb17cbed2c75b508/objectivec/GPBBootstrap.h#L57

**Describe alternatives you've considered**

**Additional context**

**Comment by thomasvl** [comment]
Shouldn't one have to opt into swift library evolution for one to need a default?

@allevato

**Comment by Cyberbeni** [comment]
NS_ENUM from my other framework is handled properly and neither has "Build library for distribution" turned on, interesting... 🤔

**Comment by thomasvl** [comment]
Were you ever able to figure out why distribution was turned on in your setup?

**Comment by Cyberbeni** [comment]
No. We are also using a mix of both now, so hopefully it doesn't magically fix itself.

**Comment by deannagarcia** [comment]
Closing since it seems a fix was found.
