### ISSUE TITLE
Please remove test files from the Pypi distribution (at least from the wheels)

### ISSUE THREAD

**Issue by mishas** [protocolbuffers/protobuf#7493]
Currently the average size of the Python3 Wheel file in pypi is 1.3MBs, and installed 5.3MBs.

This is wasteful, as those tests are not useful (used) after installation via `pip install protobuf`, and when dealing with small python code that uses protobufs, this is a huge size multiplier.

By just excluding the test files, we're able to reduce the installed size to about 3.4MB (~35% smaller)

**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
Wheel files are too large

**Describe the solution you'd like**
Remove test files from binary (and other) pypi distributions.

**Describe alternatives you've considered**
Delete the files post install.

**Additional context**
https://pypi.org/project/protobuf/#files

**Comment by haberman** [comment]
Would you be able to submit a PR for this?

**Comment by mishas** [comment]
@haberman , I can and I will :)

**Comment by moubctez** [comment]
And, please, upload source code to PyPI
https://pypi.org/project/protobuf/#files
