### ISSUE TITLE
Broken release links for Protobuf 2.6.1

### ISSUE THREAD

**Issue by jobesu14** [protocolbuffers/protobuf#7500]
The links in the release section are broken for version 2.6.1
[https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1](https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1)

Example of broken links: [https://github.com/protocolbuffers/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz](https://github.com/protocolbuffers/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz)

**Comment by jobesu14** [comment]
The links aren't actually broken, but the download rate is super slow and the download fails after few minutes.

**Comment by haberman** [comment]
I was able to download https://github.com/protocolbuffers/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz just now and it finished in a few seconds.

**Comment by jobesu14** [comment]
Ok, yes working fine today.
Sorry for bothering.
