### ISSUE TITLE
google.protobuf.Timestamp causes InvalidProtocolBufferException when parsing from JSON into a protobuf message

### ISSUE THREAD

**Issue by henrywu2019** [protocolbuffers/protobuf#7513]
**What version of protobuf and what language are you using?**
Version: v.3.11.4
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
JVM 1.8

**What did you do?**
1. Create a valid proto file with one field of type `google.protobuf.Timestamp`
2. Try to parse string data with the code:
```
JsonFormat.parser().merge(data, builder);
```
3. See error
```
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException: JsonObject
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1347)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477)
	at infraefficiency.Aggregator.LocalTest(Aggregator.java:150)
	at infraefficiency.Aggregator.main(Aggregator.java:157)
```

**What did you expect to see**
No error.

**What did you see instead?**
It works if I replace google.protobuf.Timestamp with int64.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by hit436** [comment]
Getting the same issue here as well, seems like Timestamp conversion issue in prtobuf-java-util dependency

**Comment by saurabhshadow** [comment]
> Getting the same issue here as well, seems like Timestamp conversion issue in prtobuf-java-util dependency

Is there any way to resolve it?

**Comment by perezd** [comment]
Does anyone have a reproducer for this? We can look into it if it can be reproduced easily.

**Comment by fieldsfarmer** [comment]
I came to the same issue and resolved by following the Timestamp format in Json: https://developers.google.com/protocol-buffers/docs/proto3#json
