### ISSUE TITLE
Rubygems release 3.12.0 differs from github release version

### ISSUE THREAD

**Issue by mikelorant** [protocolbuffers/protobuf#7518]
Checking the code for the tag of the Ruby release 3.12.0 shows the following:

```
s.required_ruby_version = '>= 2.3'
```

https://github.com/protocolbuffers/protobuf/blob/v3.12.0/ruby/google-protobuf.gemspec

However download the Gem from Rubygems shows:

```
s.required_ruby_version = Gem::Requirement.new([">= 2.5".freeze, "< 2.8.dev".freeze])
```

This is causing issues with applications dependent on this such as aws-fluent-plugin-kinesis.

```
ERROR:  Error installing fluent-plugin-kinesis:
	google-protobuf requires Ruby version < 2.8.dev, >= 2.5.
```

**Comment by haberman** [comment]
It appears that RubyGems rewrites our gemspec when the gem is uploaded.

However the rewritten gemspec is arguably more correct, as we dropped support for binary gems for Ruby <2.5: https://github.com/protocolbuffers/protobuf/pull/7453. It had become impossible to build our gem on these versions. Also upstream dropped support for Ruby 2.3 on 2019-03-31 and Ruby 2.4 on 2020-03-31.

This is mentioned in the changelog for Ruby:

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0

Sorry to hear this is causing problems for you. If you are still on an older version of Ruby is it possible to keep using the older version of protobuf?

**Comment by mikelorant** [comment]
Thanks for the explanation. Closing the issue.

**Comment by haberman** [comment]
Ruby 2.3 and 2.4 are supported again in 3.12.1.
