### ISSUE TITLE
spelling error in generated C++ file

### ISSUE THREAD

**Issue by frankseide** [protocolbuffers/protobuf#7522]
It seems there is a spelling error in the file generated with protoc-3.12.0-win64.zip:
```
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
```
I can only compile this way:
```
#ifdef _MSC_VER
#pragma warning(disable : 4100 4125 4127 4244 4267 4512 4456 4510 4610 4800)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wsuggest-override"
#endif

#define AuxillaryParseTableField AuxiliaryParseTableField  // in protobuf 3.12, the generated source has a spelling error

#include "onnx-ml.pb.cc" // this is the actual file we compile
```
It would also be nice if the generated code was warning-free, so that we don't need to wrap it.

**What version of protobuf and what language are you using?**

Version: protoc-3.12.0-win64.zip
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

Visual Studio 2017

**What did you do?**
```
protoc -I=. --cpp_out=. onnx-ml.proto
```

**What did you expect to see**

**What did you see instead?**

A compilation error due to a mis-spelled symbol in the generated file `onnx-ml.pb.h`

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Thank you for reporting this, but luckily PR #7496 just recently fixed the spelling of "auxiliary". That didn't make it into 3.12 but should make it into the next release.
