### ISSUE TITLE
[protobuf-mode]: wrong type argument error

### ISSUE THREAD

**Issue by ThatHai** [protocolbuffers/protobuf#7523]
This issue is filed against protobuf-mode for emacs, not a protobuf issue.
* protobuf-mode version: 0.3, or protobuf-mode-20170526.1650 from ELPA
* Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)

**What did you do?**
1. Associate .proto files with protobuf-mode
2. In emacs, edit a new proto file, e.g. example.proto
3. Type the below:
```
enum Example {
```

**What did you expect to see**
When typing the character '{', I expect to see that character in emacs

**What did you see instead?**
An error with the below stacktrace
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  c-semi-pp-to-literal(14)
  c-in-literal(nil)
  c-electric-brace(nil)
  funcall-interactively(c-electric-brace nil)
  call-interactively(c-electric-brace nil nil)
  command-execute(c-electric-brace)
```

**Anything else we should know about your project / environment**
I noticed this message in the *Message* buffer when loading the .proto file, that might be related to the above error.
```
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c++-template-syntax-table’ (fallback source eval - protobuf-mode compiled with CC Mode 5.33.2 but loaded with 5.34): (error "‘c++-make-template-syntax-table’ got no (prior) value in protobuf-mode (might be a cyclic reference)")
```

**Comment by b-t-g** [comment]
I'm encountering the same issue. I get the same behavior when trying to type one of: `; ( ) { } / ,`

Unfortunately, I don't have much else to help debug than what ThatHai already has except that I do also see:
```
c-full-pp-to-literal: Wrong type argument: stringp, nilError during redisplay: (jit-lock-function 195) signaled (wrong-type-argument stringp nil)
...
Error during redisplay: (jit-lock-function 157) signaled (wrong-type-argument stringp nil)
```

**Comment by elharo** [comment]
This issue is filed against protobuf-mode for emacs, not a protobuf issue.

**Comment by ThatHai** [comment]
@elharo 
The [protobuf-mode.el](https://github.com/protocolbuffers/protobuf/blob/master/editors/protobuf-mode.el) is part of this repository. Seems like filing the issue in this repo is the right place.

**Comment by elharo** [comment]
Hmm, I was looking at I find https://github.com/protobufel/protobuf-el but you're right.

**Comment by deannagarcia** [comment]
Closing this since there is a workaround and it looks like work has been done specifically for protobuf-mode in https://github.com/protocolbuffers/protobuf/commit/5f632bef3827a1d95d95bce92c5a3a1f903b6679, although I'm not sure that solves this particular problem. Feel free to reopen if you're still seeing the error and need a better solution!
