### ISSUE TITLE
python 3.8 windows binaries missing

### ISSUE THREAD

**Issue by kapilt** [protocolbuffers/protobuf#7530]
This seems to be across the last several releases. it would be good to publish wheels for them to pypi.

https://pypi.org/project/protobuf/3.12.0/#files
https://pypi.org/project/protobuf/3.11.3/#files

**Comment by Luttik** [comment]
Yup seems to be missing mainly for python 3.8  but since that has been out for quite a while it is a big issue.

**Comment by atollk** [comment]
#7520

**Comment by markgras** [comment]
#6214 also covers this issue. It's been open for over a year now.

**Comment by anandolee** [comment]
Fixed by https://github.com/protocolbuffers/protobuf/pull/8757
