### ISSUE TITLE
Need a darwin kokoro runner to run bazel test

### ISSUE THREAD

**Issue by stanley-cheung** [protocolbuffers/protobuf#7540]
This comes from #7538 

In that PR, we need to fix the bazel target `:protobuf_objc`, but we can't add the test target to `kokoro/linux/bazel/build.sh` because it's a linux kokoro runner. The `:protobuf_objc` target probably have something in it that says that will only build in darwin.

```
BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'                     
ERROR: Analysis of target '//:protobuf_objc' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted   
```

So we need a darwin kokoro runner to run this bazel test.

**Comment by haberman** [comment]
Closing as obsolete.
