### ISSUE TITLE
FieldOptions protoc c++ from a different folder

### ISSUE THREAD

**Issue by thomas-olszamowski** [protocolbuffers/protobuf#7545]
**What version of protobuf and what language are you using?**
libprotoc 3.11.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
* Apple clang version 11.0.3 (clang-1103.0.32.59)
* Up to date gcc compiler

**What did you do?**
1. Create a minimal file "field.proto" that extends field options:
````
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message FieldOptions {
  double value = 1;
}

extend google.protobuf.FieldOptions {
  FieldOptions my_option = 91576;
}
````

2. Import this file `import "field.proto";` in a different .proto file in the same folder. 
3. Be happy that everything works fine (protoc / c++ compiler / c++ linker)
4. move field.proto into a subdirectory "options".
5. Import the file in the same .proto file `import "options/field.proto";`

**What did you expect to see**
everything should work out just fine

**What did you see instead?**
A compiler error of the generated .cc file that imports "field.proto" that looks like this:
```
No member named 'descriptor_table_options_2ffield_2eproto' in the global namespace; did you mean 'descriptor_table_field_2eproto'?
```

in a line that looks like this (generated .cc file that imports "field.proto")

```
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_data_2dobjects_2eproto_deps[1] = {
  &::descriptor_table_options_2ffield_2eproto,
};
```

**Anything else we should know about your project / environment**
No. It works without problems for golang and ruby. It's a pure c++ problem.

**Comment by acozzette** [comment]
I believe you just need to rebuild your .proto file that imports the moved one. Let me know if that doesn't solve the problem.

**Comment by thomas-olszamowski** [comment]
It doesn't solve the problem neither for clang (MacOs) nor gcc (Linux).
