### ISSUE TITLE
Update documentation to clarify that packed repeated fields are not wire-compatible with optional fields

### ISSUE THREAD

**Issue by BenBirt** [protocolbuffers/protobuf#7553]
(This was previously discussed in https://github.com/protocolbuffers/protobuf/issues/2905.)

As far as I can tell, protobuf wire-format parsers are not expected to translate packed repeated fields -> optional fields (indeed, this would be acting contrary to the behaviour of at least the Go and Java generated client libraries, both of which I have tested).

As discussed in the linked issue, it sounds like it's expected that optional is compatible with repeated, and repeated is compatible with packed repeated, but packed repeated is not compatible with optional.

That's fine, but it's very confusing because the documentation doesn't really say anything about this. In particular confusion arises in the proto2 documentation [here](https://developers.google.com/protocol-buffers/docs/proto#updating): `optional is compatible with repeated. Given serialized data of a repeated field as input, clients that expect this field to be optional will take the last input value if it's a primitive type field or merge all input elements if it's a message type field.` This documentation doesn't say anything about packed repeated fields.

It's also especially confusing in the proto3 documentation [here](https://developers.google.com/protocol-buffers/docs/proto3#updating), because there's not even mention of optional <-> repeated compatibility. Users who are used to proto2 semantics may assume that optional is compatible with repeated, without realising that since proto3 repeated fields are packed by default, this compatibility is broken (at least until they explicitly set `packed=false`).

Can the documentation here please be updated?

Suggestion (for the proto2 paragraph quoted above): `optional is compatible with repeated. Given serialized data of a repeated field as input, clients that expect this field to be optional will take the last input value if it's a primitive type field or merge all input elements if it's a message type field. Note that if the repeated field has packed=true, serialized data in this format will not be interpreted as an optional field, and will instead be treated as an unknown field.`

Suggestion for the proto3 documentation: `As in proto2, optional is compatible with repeated. However, by default all repeated proto3 fields are packed. For proto3 repeated fields to be compatible with optional, those fields must be annotated with packed=false.`

(Obviously the optimal answer would be to make packed repeated compatible with optional, but I suspect that might be impossible!)

**Comment by acozzette** [comment]
The documentation update is now live:
https://developers.google.com/protocol-buffers/docs/proto#updating
https://developers.google.com/protocol-buffers/docs/proto3#updating

**Comment by BenBirt** [comment]
@acozzette thanks for the docs update!
