### ISSUE TITLE
Incorrect source generation for GPBExtensionDescription

### ISSUE THREAD

**Issue by emlynmac** [protocolbuffers/protobuf#7555]
**What version of protobuf and what language are you using?**
Version: 3.11.2
Language:Objective-C

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Xcode 11.5
coocapods 1.9.2

**What did you do?**
Steps to reproduce the behaviour:
Using the code at https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/text-to-speech, and locking the gRPCPlugin to version 1.27.
`pod install`

**What did you expect to see**
When compiling the `annotations.proto` file, a section of generated code is:

```
+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    static GPBExtensionDescription descriptions[] = {
      {
        .defaultValue.valueMessage = nil,
        .singletonName = GPBStringifySymbol(AnnotationsRoot_HTTP),
        .extendedClass = GPBStringifySymbol(GPBMethodOptions),
        .messageOrGroupClassName = GPBStringifySymbol(HttpRule),
        .enumDescriptorFunc = NULL,
        .fieldNumber = 72295728,
        .dataType = GPBDataTypeMessage,
        .options = GPBExtensionNone,
      },
    };
    for (size_t i = 0; i < sizeof(descriptions) / sizeof(descriptions[0]); ++i) {
      GPBExtensionDescriptor *extension =
          [[GPBExtensionDescriptor alloc] initWithExtensionDescription:&descriptions[i]];
      [registry addExtension:extension];
      [self globallyRegisterExtension:extension];
      [extension release];
    }
    // None of the imports (direct or indirect) defined extensions, so no need to add
    // them to this registry.
  }
  return registry;
}
```

**What did you see instead?**
The struct does not have this signature and the code that should be generated is:
```
+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    static GPBExtensionDescription descriptions[] = {
      {
        .defaultValue.valueMessage = nil,
        .singletonName = GPBStringifySymbol(AnnotationsRoot_HTTP),
        .extendedClass = GPBStringifySymbol(GPBMethodOptions),
        .messageOrGroupClass.name = GPBStringifySymbol(HttpRule),
        .enumDescriptorFunc = NULL,
        .fieldNumber = 72295728,
        .dataType = GPBDataTypeMessage,
        .options = GPBExtensionNone,
      },
    };
    for (size_t i = 0; i < sizeof(descriptions) / sizeof(descriptions[0]); ++i) {
      GPBExtensionDescriptor *extension =
          [[GPBExtensionDescriptor alloc] initWithExtensionDescription:&descriptions[i]];
      [registry addExtension:extension];
      [self globallyRegisterExtension:extension];
      [extension release];
    }
    // None of the imports (direct or indirect) defined extensions, so no need to add
    // them to this registry.
  }
  return registry;
}
```

Note that `messageOrGroupClassName` has been turned into a union type:

The description of the struct is in `GPBDescriptor_PackagePrivate.h`:
```
// An extension
typedef struct GPBExtensionDescription {
  GPBGenericValue defaultValue;
  const char *singletonName;
  union {
    const char *name;
    Class clazz;
  } extendedClass;
  union {
    const char *name;
    Class clazz;
  } messageOrGroupClass;
  GPBEnumDescriptorFunc enumDescriptorFunc;
  int32_t fieldNumber;
  GPBDataType dataType;
  GPBExtensionOptions options;
} GPBExtensionDescription;
```

**Comment by thomasvl** [comment]
Can you provide more specific repo steps?

The current code never uses the `name` part of the union, that is left over to allow supporting running with that was compiled against older headers with the new runtime.  The current extension code always does the `clazz` reference: https://github.com/protocolbuffers/protobuf/blob/3.12.x/src/google/protobuf/compiler/objectivec/objectivec_extension.cc#L128

I don't think a `pod install` can actually take care of building `protoc`, so the this might actually be down to the binary you have installed and are generating with (`protoc --version` / `which protoc`).

**Comment by emlynmac** [comment]
Repo steps:

Pull the source linked above.
Build it with `pod install` and then open Xcode and build.
Note that there is an error from the code being incorrectly generated as described.

The `protoc` executable inside of the `Pods/!ProtoCompiler/` directory is the one that is used and it works for all other code generation reliably, just not this particular component.

**Comment by thomasvl** [comment]
What's your exact error message?

**Comment by emlynmac** [comment]
The compiler error about not having the struct existing because the code generated doesn't match the headers.

**Comment by thomasvl** [comment]
We're looking for the exact error message.  We're sorta surprised there aren't errors for the `extendedClass` either.

The code is not generated, it is checked in: https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/text-to-speech/Swift/TextToSpeech/google/api

**Comment by thomasvl** [comment]
> locking the gRPCPlugin to version 1.27

What did you do for this?  I'm not clear where that plugin comes into play?

**Comment by emlynmac** [comment]
Right - in that project it is checked in. In the private project that I cannot share I have run into the issue as we don't want to check in generated files if possible...

re. locking to 1.27, this was because of a dependency problem: https://github.com/grpc/grpc/issues/22781

It should now be resolved, as 1.29.1 works fine as of yesterday.

**Comment by thomasvl** [comment]
If you aren't checking in generated files and getting this problem it means you are using a non matching version of protoc to the runtime version you are using.  Keeping those in sync will avoid the problem.

**Comment by thomasvl** [comment]
What's your exact step for pinning, I haven't had to do that, so I want to be sure I'm doing the same thing.

**Comment by emlynmac** [comment]
in the `googleapis.podspec` (https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/text-to-speech/Swift/TextToSpeech/googleapis.podspec)

Change the line:
`s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0"`
to
`s.dependency "!ProtoCompiler-gRPCPlugin", "1.27.0"`

**Comment by thomasvl** [comment]
As I'm tracking things, it looks like grpc isn't building protoc, it is picking up an old one: https://github.com/grpc/grpc/blob/master/src/objective-c/!ProtoCompiler.podspec

So it actually does seem to allow the runtime support (Protobuf.podspec) to be a different version that what the compile being used is (!ProtoCompiler.podspec).

**Comment by emlynmac** [comment]
Interesting - so you're suggesting pinning the `protoc` version somewhere too then?

**Comment by thomasvl** [comment]
ObjC protos does have an issue in that we try to support old generated code, but the setup here seems to not really ensure that the version of the runtime matcher the version of the generator.  As log as the generator (protoc) doesn't get _ahead_ of the runtime, it should work.

**Comment by emlynmac** [comment]
From what I can see, `!ProtoCompiler` is at 3.11.2, and the `Protobuf` is at 3.12.

Is this break expected between these versions?

To test, I added a further dependency to the googleapis.podspec:
`s.dependency "Protobuf", "3.11.2"`

It now generates the code just fine.

**Comment by emlynmac** [comment]
So is the real issue that https://github.com/grpc/grpc/blob/master/src/objective-c/!ProtoCompiler.podspec should lock to the correct version it needs?

**Comment by thomasvl** [comment]
yes and no?  😄   I haven't traced through all the flows here yet, generally you want to use a protoc that matches the runtime you are using.  This would have "just worked" if we didn't have this bug as we try to ensure the runtime supports sources from older versions of the library.  We're working on a fix here to maintain that source compatibility contract in either case, just trying to figure out the right way to do so.

**Comment by thomasvl** [comment]
Fixed on the branch.

**Comment by thomasvl** [comment]
3.12.3 is released with the fix.
