### ISSUE TITLE
protoc-3.12.2-linux-x86_64.zip: protoc --version is 3.12.1

### ISSUE THREAD

**Issue by ukai** [protocolbuffers/protobuf#7560]
**What version of protobuf and what language are you using?**
Version: v3.12.2

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Download protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.12.2/protoc-3.12.2-linux-x86_64.zip
2. Extract zip file.
3. Run `protoc --version`

**What did you expect to see**
libprotoc 3.12.2

**What did you see instead?**
libprotoc 3.12.1

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by EdwinBetanc0urt** [comment]
Greetings @ukai , I have the same problem, I use a script [(install-protoc.sh)](https://github.com/erpcya/gRPC-Core-Client/blob/master/install-protoc.sh) to download and unzip the last release to the folder I need, however I notice that it downloads version 3.12.2 and when I check the version in my operating system it shows that it has the previous version 3.12.1.

To get out of doubts I downloaded and unzipped manually the release 3.12.2 and I get the same result:
`libprotoc 3.12.1`

**Comment by chengzh2008** [comment]
I have also seen this issue for the mac version. protoc-3.12.2-osx-x86_64.zip: protoc --version is 3.12.1

**Comment by llimllib** [comment]
Reproducer as a single command:

```
$ (cd /tmp && wget -q https://github.com/protocolbuffers/protobuf/releases/download/v3.12.2/protoc-3.12.2-osx-x86_64.zip && unzip -qf protoc-3.12.2-osx-x86_64.zip && bin/protoc --version)
libprotoc 3.12.1
```

is there any hope of updating the binary?
