### ISSUE TITLE
Getting protobuf linking error while compiling Tink library

### ISSUE THREAD

**Issue by gopall-blr** [protocolbuffers/protobuf#7566]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
RHEL7
Bazel version: 3.1.0

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version: 4.8.5, later updated to gcc-7.3.1

**What did you do?**

Code location: https://github.com/google/tink/tree/master/examples/cc/hybrid_encryption

Our partner needed to use the above linked utility for encrypting the data that they send to Google. They tried compiling the library on their server, which is RHEL7 having gcc version 4.8.5, but it failed due to older version of compiler. Based on our advice, they tried updating gcc to newer version, still they got the attached error.

![unnamed](https://user-images.githubusercontent.com/63314372/83059501-a0f22e80-a077-11ea-9625-5fd0365c9abf.png)

**Comment by acozzette** [comment]
I'm not sure what's causing the error, but it's interesting that the error messages refer to C++ exceptions, which we don't use at all in protobuf.
