### ISSUE TITLE
Compiling protobuf on Windows requires pthread.h, how do I get this!?

### ISSUE THREAD

**Issue by kingoftheconnors** [protocolbuffers/protobuf#7577]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows Pro 10.0.18363 Build 18363

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 9.2.0
cmake version 3.16.19112601-MSVC_2

**What did you do?**
1. Use Visual Studio Developer Console 2019 and traverse to the cloned protobuf repository
2. Build using cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\sdk\protobuf-amd64 ..\cmake
3. See the line `looking for pthreads - not found`
4. Go to CMakeError.log to see elaborated:

```
C:\MinGW\bin\gcc.exe    -o CMakeFiles/cmTC_74cdf.dir/CheckIncludeFile.c.obj   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: pthread.h: No such file or directory
    1 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**What did you expect to see**
As Windows is not a UNIX system, I expected that protobuf would not require a UNIX library like pthreads. Perhaps using a cross-platform alternative, or the windows API

**Anything else we should know about your project / environment**
I am compiling protobuf to use the GameNetworkingSockets library, which recommends building protobuf using cmake.

**Comment by kingoftheconnors** [comment]
NOTE: Using ninja after setting up the cmake still builds and compiles. I'm not sure if the system is silently screaming beneath the surface, and that may cause problems down the line, but there is no _visible_ problem caused by this error...

**Comment by acozzette** [comment]
I suspect this is just CMake testing for whether pthreads are available. It would be ideal if we could hide the error message, though.

**Comment by sfhacker** [comment]
Any news/update on this open issue?
We have just downloaded master branch and built it from source without a hitch!

Windows 10 x64 // MinGW

![image](https://user-images.githubusercontent.com/25817529/90016495-6cdcf000-dced-11ea-8a38-8a50542d744b.png)

**Comment by kingoftheconnors** [comment]
Yes, it seems to be just a warning message. If it compiles safely, it should be fine. Thank you!
