### ISSUE TITLE
Java JSON Format includingDefaultValueFields Not Print Empty Field Option

### ISSUE THREAD

**Issue by PeiyuanQi** [protocolbuffers/protobuf#7578]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
Current Java Util, JsonFormat has option to do `includingDefaultValueFields`. It is usually used as the default value of the Proto field is not printed in converted JSON String. However, those empty fields will also be printed with this option. So could we have an option to not print empty fields? 

**Describe the solution you'd like**
Another option to only include default values but do not print empty fields.

**Describe alternatives you've considered**
I could eliminate those fields on the output of JsonFormat, but it is not easy, and introducing implicit dependency.

**Additional context**

In the transfer of existing REST service to gRPC, it always has middle stages, when part of the system will using the gRPC but downstream data component requires JSON input. Converting gRPC message to JSON should not happen in the beginning but it is happening. And the problem stated here is common when we want to convert messages to json payload.

**Comment by elharo** [comment]
This seems too special purpose. I don't think we want the extra code complexity for this.
