### ISSUE TITLE
add a python api to test message equivalence

### ISSUE THREAD

**Issue by benjaminp** [protocolbuffers/protobuf#7582]
**What language does this apply to?**
python

**Describe the problem you are trying to solve.**

`__eq__` on Python generated messages invokes `MessageDifferencer::Equals`. Sometimes it's useful to compare messages by the slightly different notion of "equivalence" as embodied by the C++ `MessageDifferencer::Equivalent` API.

**Describe the solution you'd like**

Expose a `google.protobuf.util.messages_equivalent(msg1, msg2)` function that mirrors `MessageDifferencer::Equivalent` in C++.

(Perhaps, more generally, it would be useful to have the full API surface of `MessageDifferencer` available in Python.)

**Additional context**

**Comment by SanjayVas** [comment]
This is absolutely still sorely needed.
