### ISSUE TITLE
Protobuf visualization using Natvis custom visualizer in Visual Studio 2017 or higher

### ISSUE THREAD

**Issue by mahithinkhub** [protocolbuffers/protobuf#7586]
Hi Team,

I'm working on the requirement , where in debugging the protobuf c++ objects , its very complex to understand the internal fields and attributs. Thinking to write an formatting those protobuf variables using natvis schema in VS.

Could you please assist in understanding the protobuf internal class or sample code where i can decode and use it. 
Any reference links or guidelines will be great.

lang: C++ 

Thanks in advance

**Comment by shaod2** [comment]
We can help you if you have more specific questions. If you want to see some sample codes, see https://developers.google.com/protocol-buffers for more details, and try to download it and generate sample classes you want. Thanks.
