### ISSUE TITLE
RFE: switch to use system installed googletest

### ISSUE THREAD

**Issue by kloczek** [protocolbuffers/protobuf#7594]
It does not make to much sense to link other repository.

**Comment by deannagarcia** [comment]
We link to googletest mostly to allow us to pin the version of googletest. This allows users to not have to have the correct version of googletest installed and rather just use the version we link.

**Comment by kloczek** [comment]
googletest offers pkgconfig file which allows check presence odf the devel resources of the googletest with at least or exact version.

Would you accept PR to use system available googletest?
I've done already patch for that.
