### ISSUE TITLE
protobuf to JSON schema as part of compiler

### ISSUE THREAD

**Issue by bencyoung** [protocolbuffers/protobuf#7595]
As protocol buffers have a canonical representation in JSON it would be really nice if you could take the IDL and use protoc to produce a JSON Schema for that canonical representation.

For various reasons we define proto schemas but then sometime pass around the objects as JSON, but currently there's no easy way of giving someone the schema for that data. It would nice to be able to say "pass us data in this format" via JSON Schema externally and then we can map and create the binary format internally?

**Comment by fowles** [comment]
There is some underway work that might help here, but I don't think we are going to get to this any time in the near term
