### ISSUE TITLE
program linked to protobuf crashes before main in Ubuntu 20.04

### ISSUE THREAD

**Issue by drdgl** [protocolbuffers/protobuf#7597]
**What version of protobuf and what language are you using?**
Version: libprotobuf.so.17.0.0
Language: C++
Ubuntu 20.04

gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

echo "syntax = \\"proto2\\";" >| test.pbc
echo "message TestMsg" >> test.pbc
echo "{" >> test.pbc
echo " required double f1 = 1;" >> test.pbc
echo "}" >> test.pbc

echo "int main() {return 0;}" >| test.cc

protoc --cpp_out=. ./test.pbc
g++ -c -o test.pbc.pb.o test.pbc.pb.cc
g++ -c -o test.o test.cc
g++ -o test test.o test.pbc.pb.o -lprotobuf
./test
**What did you expect to see**
No crash
**What did you see instead?**

./test 
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)

valgrind ./test 
==726673== Memcheck, a memory error detector
==726673== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==726673== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==726673== Command: ./test
==726673== 
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
==726673== 
==726673== Process terminating with default action of signal 6 (SIGABRT)
==726673==    at 0x4EF718B: raise (raise.c:51)
==726673==    by 0x4ED6858: abort (abort.c:79)
==726673==    by 0x4C04950: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==726673==    by 0x4C1047B: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==726673==    by 0x4C104E6: std::terminate() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==726673==    by 0x4C10798: __cxa_throw (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==726673==    by 0x4C0777E: std::__throw_system_error(int) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==726673==    by 0x4980B8E: ??? (in /usr/lib/x86_64-linux-gnu/libprotobuf.so.17.0.0)
==726673==    by 0x4011B89: call_init.part.0 (dl-init.c:72)
==726673==    by 0x4011C90: call_init (dl-init.c:30)
==726673==    by 0x4011C90: _dl_init (dl-init.c:119)
==726673==    by 0x4001139: ??? (in /usr/lib/x86_64-linux-gnu/ld-2.31.so)

**Comment by drdgl** [comment]
FWIW, I downloaded protobuf-cpp-3.12.3.tar.gz and the problem isn't happening there... at least not on the simple example above. So I'll start testing with the original applications (which had intermittent problems like the one that is reproducible on Ubuntu 20.04 with the simple example). If I don't see any more crashes, I'll close this.

**Comment by shaod2** [comment]
Hi, do you have any updates? Is it fixed?

**Comment by drdgl** [comment]
Yea, I haven't seen the issue when I compile protobuf myself from git. The Ubuntu version in 20.04 was (and still is last time I checked). I'll close this issue here since it's working in git.
