### ISSUE TITLE
C# ByteString.Memory property not found in latest nuget pkg

### ISSUE THREAD

**Issue by yabli** [protocolbuffers/protobuf#7598]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
msbuild

**What did you do?**
1. installed Ver. 3.12.2 from nuget
    https://www.nuget.org/packages/Google.Protobuf/
2. About to use ByteString.Memory, 

**What did you expect to see**
I can use ByteString.Memory

**What did you see instead?**
found this property is not in this ver.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
This change was in Nov. last year per file histry, why I don't see this property in the nuget pkg?

**Comment by jtattermusch** [comment]
The `ByteString.Memory` property is still there
https://github.com/protocolbuffers/protobuf/blob/022078d3ee642816688228e9434775f2a137536d/csharp/src/Google.Protobuf/ByteString.cs#L132

The property is protected by the GOOGLE_PROTOBUF_SUPPORT_SYSTEM_MEMORY define, but as AFAIK that one is now defined for all the target frameworks, so it should always be there.
https://github.com/protocolbuffers/protobuf/blob/022078d3ee642816688228e9434775f2a137536d/csharp/src/Google.Protobuf/Google.Protobuf.csproj#L22


What is the target framework you're using in your project? (protobuf currently targets netstandard1.1;netstandard2.0;net45)

**Comment by jtattermusch** [comment]
Btw, Google.Protobuf 3.13.0 is available, so I recommend using it.

**Comment by jtattermusch** [comment]
Looks like ByteString.Memory is available in 3.13.x
https://github.com/protocolbuffers/protobuf/blob/3.13.x/csharp/src/Google.Protobuf/ByteString.cs

but not in 
https://github.com/protocolbuffers/protobuf/blob/3.12.x/csharp/src/Google.Protobuf/ByteString.cs (or any of the earlier releases).

So the answer seems simple - use Google.Protobuf 3.13.0
