### ISSUE TITLE
cpp_implementation build issue with protobuf 3.11.4 on windows

### ISSUE THREAD

**Issue by Jayatubi** [protocolbuffers/protobuf#7606]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC 2019, Visual C++ for Python 9.0

**What did you do?**
1. Goto folder 'python'
3. Execute `python setup.py build --cpp_implementation`

**What did you expect to see**
Build succefully.

**What did you see instead?**
An error stops the build process:
```
C:/Users/****/AppData/Local/Programs/Common/Microsoft/Visual C++ for Python/9.0/VC/include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
../src\google/protobuf/io/coded_stream.h(115) : fatal error C1083: Cannot open include file: 'atomic': No such file or directory
```

**Comment by acozzette** [comment]
I'm going to close this issue because protobuf 3.11 is quite old at this point and no longer supported.
