### ISSUE TITLE
Can't get `import ` info in the `.proto` file recursively

### ISSUE THREAD

**Issue by Abbyyan** [protocolbuffers/protobuf#7607]
I've write a proto file `test1.proto` which import another file `test2.proto` , and `test2.proto` import `test3.proto`. They are just like follows.
`test1.proto` 
```
syntax = "proto3";
import test2.proto
```
and here is `test2.proto `.
```
syntax = "proto3";
import test3.proto
```

But when i use `Importer` to process `test1.prot` and get its dependencies, i can only get the outer most dependency which is `test2.proto` (which i thought should be `test2.proto` and `test3.proto`). 
```cpp
google::protobuf::compiler::DiskSourceTree sourceTree;  // source tree
  sourceTree.MapPath("", "./proto_info");
  MyErrorCollector errorCollector;
  google::protobuf::compiler::Importer importer(&sourceTree, &errorCollector);
  const google::protobuf::FileDescriptor* filedes =
      importer.Import("test1.proto");
// cout<< "file des = "<<filedes->DebugString()<<endl;
  cout<<"dependecies count = "<<filedes->dependency_count()<<endl;
for(int i =0 ;i<filedes->dependency_count();i++){
      cout<<"index = "<<i<<" ; dependency = "<<filedes->dependency(i)->name()<<endl;
  }
```
The output info is as follows:
```shell
>>> dependecies count = 1
>>> index = 0; dependency = test2.cpp

```
Any problems there please? How can i get all the dependencies recursively please? Hope for your help. Thanks a lot.

**Comment by thomasvl** [comment]
`filedes->dependency(i)` is a `FileDescriptor*`, you can recurse on it for it's dependencies (and for those files' dependencies...).

**Comment by Abbyyan** [comment]
> `filedes->dependency(i)` is a `FileDescriptor*`, you can recurse on it for it's dependencies (and for those files' dependencies...).

It shows in the doc that `FileDescriptor ` will return all the dependencies recursively, so i want to know if there are something wrong with my usage. Ok, i can recursive it myself. Thanks a lot.
