### ISSUE TITLE
Python 3.8 MergeFrom error

### ISSUE THREAD

**Issue by wildfire810** [protocolbuffers/protobuf#7608]
Python 3.8 MergeFrom error
Because 'list' doesn't have _values

**Comment by shaod2** [comment]
Can you provide more details?

**Comment by wildfire810** [comment]
Yes, of course

Before the Python version 3.8, the built in type 'list', have a attr '_values'.
The offical protobuf library use this attr in 'MergeFrom' function.
At more the Python version 3.8, the 'MergeFrom' function must crash, because there is no attr '_values'.

**Comment by anandolee** [comment]
Sorry for late reply. But the info is not enough for us to reproduce the error. 
If it is still an issue, you may need to provide some steps and maybe a few lines of source code for us to know how it happens.

Close it as it is an old issue. Feel free to reopen if needed
