### ISSUE TITLE
Proto message parsing is ~4x slower in the latest java lite runtime compared to 3.0.1

### ISSUE THREAD

**Issue by m0hamed** [protocolbuffers/protobuf#7622]
**What version of protobuf and what language are you using?**
Version: v3.12.2
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Android

**What runtime / compiler are you using (e.g., python version or gcc version)**
prebuilt protoc + Java lite runtime v3.12.2

**What did you do?**
We recently noticed an increase in latency in protobuf message parsing using the new/latest lite runtime vs the slightly older, now deprecated lite runtime that used the code-gen plugin (aka v3.0.1). 

The [proto](https://source.chromium.org/chromium/chromium/src/+/master:android_webview/proto/aw_variations_seed.proto) messages are usually ~8K in size. Comparing proto parsing using the v3.0.1 runtime (takes <5ms) vs the latest v3.12.2 (takes >20ms). This unscientific testing was done using 5 samples each but we originally detected the regression from aggregated metrics from millions of user devices.
 
**What did you expect to see**
Not that much of a latency drop between versions.

**What did you see instead?**
large increase in latency in proto parsing.

**Anything else we should know about your project / environment**
Nothing comes to mind.

**Comment by googleberg** [comment]
Not enough information to go on.
