### ISSUE TITLE
Proto3 - PHP assign zeo value

### ISSUE THREAD

**Issue by d4rkr3pt0r** [protocolbuffers/protobuf#7625]
Hi. I did a lot of research on how to assign 0 value for a message but I couldn't find an answer.
Here is my sample message:
```
message Test {
  int32 active = 1;
}
```
And this is how I'm assigning 0 value:
```
$test = new Test();
$test->setActive(0);
```
But after using `serializeToString()`, it removes all nodes with zero values; I NEED THESE NODES.Please just don't say use proto v2 :(

**Comment by kalaspuff** [comment]
For numeric types, the default value is zero. As far as I know, explicitly setting it to zero or not setting it at all, wouldn't make any difference when serializing the message. As the documentation regarding default values also mentions, if a scalar message field is set to its default value, the value will not be serialized.

https://developers.google.com/protocol-buffers/docs/proto3#default_values

This would in turn mean that the field won't show in the output you get when running `serializeToString()` if it has the default value. Later on the receiving end, when you parse the serialized message data (using for example `mergeFromString($data)` in PHP or  `ParseFromString(data)` in Python) and get the field value using the getter function on the object you'll end up with the default value again (in your case `0`).

```php

$from = new Test();
$from->setActive(0);

$data = $from->serializeToString();

$to = new Test();
$to->mergeFromString($data);

var_dump($to->getActive());
/* Output should be int(0) */
```

**Comment by haberman** [comment]
Normal proto3 fields cannot serialize zero values. However the good news it that `optional` fields are coming to proto3, which will allow you to serialize zero values. For more information see:

https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0

This is not yet implemented for PHP, but will be soon.

**Comment by haberman** [comment]
Proto3 optional is implemented for PHP. The feature currently requires an experimental flag, but this will be enabled by default in the next release.
