### ISSUE TITLE
IBufferMessage Missing in 3.12.3

### ISSUE THREAD

**Issue by Zehua-Chen** [protocolbuffers/protobuf#7627]
**What version of protobuf and what language are you using?**
Version: 3.12.3.
Language: C#

**What operating system (Linux, Windows, ...) and version?**

macOS 10.15.5

**What runtime / compiler are you using (e.g., python version or gcc version)**

- protoc version 3.12.3
- Unity 2019.2.11f1
- API Compatibility Level: .Net Standard 2.0

**What did you do?**
1. Compile .proto files using protoc
2. Download packages from NuGet and find dll files under `netstandard2.0` folder:
   - [Google.Protobuf](https://www.nuget.org/packages/Google.Protobuf/)
   - [System.Memory](https://www.nuget.org/packages/System.Memory/)
   - [System.Buffers](https://www.nuget.org/packages/System.Buffers/)
3. Import the dll files into Unity
4. See compiler error saying that `IBufferMessage` is missing

**What did you expect to see**

No compiler errors

**What did you see instead?**

Compiler error saying that `IBufferMessage` is missing

**Anything else we should know about your project / environment**

If I clone the repo and checkout v3.12.3, build it on my own machine, import the dlls, then there are no errors. But if I use the dll I got from NuGet, then there are errors

**Comment by TehcJS** [comment]
I'm having the same issue as well.

**Comment by TehcJS** [comment]
It appears that `ParseContext` is also missing from `3.12.3`

**Comment by TehcJS** [comment]
`ReadRawMessage` is missing as well. Is this an older version of protobuf?

**Comment by haberman** [comment]
The 3.12.3 release was broken; the wrong branch was tagged, which led to lots of unfortunate breakage. I think we can likely attribute this brokenness to that. Please re-open if you can reproduce this error with 3.12.4.
