### ISSUE TITLE
Proto3, I can't Merge zero value to a new object

### ISSUE THREAD

**Issue by imsoul** [protocolbuffers/protobuf#7634]
Sometimes I want to update one field or several fields of the object.
I use the method "MergeFrom"
but when the new object has zeo value, I can't update the value.

For example:

```
  message User{
  int32 uid = 1; 
  string name= 2; 
  int32 age= 3; 
  int32 coin= 4; 
  int32 exp= 5; 
  }
```

```
$data = [
            'uid'=>1,
            'name'=>'Soul',
            'age'=>20,
            'coin'=>1000,
            'exp'=>1000
        ];
        $roleProto = new User($data);

        $data2 = [
            'uid'=>1,
            'coin'=>0,
            'exp'=>1100,
        ];

        $roleProto2 = new User($data2);
        $str = $roleProto2->serializeToString();
        $roleProto->mergeFromString($str);
        var_dump($roleProto->serializeToJsonString());
```

It dosen't work. the field "coin" isn't update.
but when I use "google.protobuf.Int64Value", it works in PHP, but it dosen't work in C#(unity).

**Comment by haberman** [comment]
This is expected behavior. The good news is that `optional` fields are coming to proto3, which will allow you to merge a zero value. For more info see:

https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

**Comment by imsoul** [comment]
Thank you very much. but I get a new problem.

I try it, C# is OK, but PHP ERROR.

````
protoc --proto_path=./ --php_out=. --experimental_allow_proto3_optional ./*.proto
````

```
User.proto: is a proto3 file that contains optional fields, but code generator --php_out hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```

**Comment by imsoul** [comment]
> This is expected behavior. The good news is that `optional` fields are coming to proto3, which will allow you to merge a zero value. For more info see:
> 
> https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
> 
> https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md


Thank you very much. but I got a new problem.

I try to build C# is OK, but PHP get an ERROR.

````
protoc --proto_path=./ --php_out=. --experimental_allow_proto3_optional ./*.proto
````

```
User.proto: is a proto3 file that contains optional fields, but code generator --php_out hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```

**Comment by haberman** [comment]
PHP hasn't been updated to support proto3 presence yet. This should be added in the next month or so.

**Comment by ShaoZeMing** [comment]
> PHP 尚未更新以支持 proto3 存在。这应该在下个月左右添加。
抱歉，目前还是未更新这个功能
