### ISSUE TITLE
JS serializeBinaryToWriter behave different from that in java, python version. 

### ISSUE THREAD

**Issue by AbnerZheng** [protocolbuffers/protobuf#7635]
**What version of protobuf and what language are you using?**
Version: master
Language: Javascript

**What operating system (Linux, Windows, ...) and version?
Linux, MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 11.0.3 (clang-1103.0.32.59)

**What did you do?**
I have a proto file like:
```
message Code {
        reserved 2;
        reserved 3, 4, 5;
        oneof contract {
            bytes wasm = 1;
            StoredContract stored_code = 7;
            StoredVersionedContract stored_versioned_contract = 9;
        }
        repeated Arg args = 6;
}
```
I want to get serialized byte array by calling code.serializeBinary,  then I find the byte array it generated in JS environment is different from that in Python and Java environment. 

Here is the JS code generated by protoc:
```
proto.io.casperlabs.casper.consensus.Deploy.Code.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
 f = message.getStoredContract();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.io.casperlabs.casper.consensus.Deploy.Code.StoredContract.serializeBinaryToWriter
    );
  }
  f = message.getStoredVersionedContract();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.io.casperlabs.casper.consensus.Deploy.Code.StoredVersionedContract.serializeBinaryToWriter
    );
  }
  f = message.getArgsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.io.casperlabs.casper.consensus.Deploy.Arg.serializeBinaryToWriter
    );
  }
};
```

So as you can see, it serializes `stored_code`(index 7) and `stored_version_code`(index 9) before `args`(index 6).  

But in java and python generate code, they would generate one by one by index order, in other words, they would serialize `args` before serializing `stored_code` and `stored_version_code`. 

I think we should keep JS version consistent with other version.

**Comment by TeBoring** [comment]
Sorry, there is no restriction for fields serializing order. Please relax your test to not enforce any field order.
In c++, there is something like deterministic serialization, but that is not feasible in js for performance reason.

**Comment by jcready** [comment]
According to the documentation https://developers.google.com/protocol-buffers/docs/encoding#order

> Field numbers may be declared in any order in a `.proto` file. **The order chosen has no effect on how the messages are serialized.**

This implies that this is indeed a bug in the implementation as the order that the fields appears in the `.proto` file does in fact affect the serialization.
