### ISSUE TITLE
[Docs] Language Guide (proto3) reference errors

### ISSUE THREAD

**Issue by DazWilkin** [protocolbuffers/protobuf#7636]
Documentation errors:

https://developers.google.com/protocol-buffers/docs/proto3

The in-page content has incorrect in-page references:

```HTML
<a href="#services">Defining Services</a>
<a href="#json">JSON Mapping</a>
```
Are both incorrect:

https://developers.google.com/protocol-buffers/docs/proto3#services
https://developers.google.com/protocol-buffers/docs/proto3#json

The right-hand content list has these correctly as:

https://developers.google.com/protocol-buffers/docs/proto3#defining_services
https://developers.google.com/protocol-buffers/docs/proto3#json_mapping

There are possibly others.

It would be helpful to have and I was unable to find a "Send feedback" option on pages on this site as is found with e.g. Google Cloud Platform documentation

**Comment by acozzette** [comment]
@DazWilkin Thank you for reporting these errors. I believe they have all now been fixed, but let me know if you find any that still exist.
