### ISSUE TITLE
Ruby: proto3_optional fields' generated oneofs do not track presence

### ISSUE THREAD

**Issue by viacheslav-rostovtsev** [protocolbuffers/protobuf#7640]
**What version of protobuf and what language are you using?**
Version: 3.12.2
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
x86_64-linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby 2.5.7

**What did you do?**
I'm trying to use the new proto3_optional field and check it's generated oneof field to track its presence. Please refer to the example below:
```
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "TestMessage" do
    oneof :oneof_singular do
      optional :oneof_singular_str, :string, 1
    end
    proto3_optional :optional_str, :string, 2
  end
end

TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("TestMessage").msgclass
message = TestMessage.new

# Non-default value
message.oneof_singular_str = "foo"
puts message.oneof_singular == :oneof_singular_str # => true
puts message.oneof_singular_str == "foo" # => true

# Default value
message.optional_str = "foo"
puts message.optional_str == "foo" # => true
puts message._optional_str == :optional_str # => false (unexpected)
puts message._optional_str == nil # => true (unexpected)
```

**Comment by TeBoring** [comment]
Is `_optional_str` for user to access?
I think there should be some public api to check presence

**Comment by haberman** [comment]
The public API is `has_foo?`.
