### ISSUE TITLE
JsonFormat double parsing can silently lose precision

### ISSUE THREAD

**Issue by jhaber** [protocolbuffers/protobuf#7643]
**What version of protobuf and what language are you using?**

Version: 3.8.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**

OSX 10.15.5

**What did you do?**

This isn't necessarily a bug report, but that seemed more appropriate than feature request. It seems like `JsonFormat` checks for loss of precision as well as overflow/underflow when parsing integral values, however it doesn't appear that `double` gets the same treatment. For example this code sample:
```java
long longValue = -8747832031878802303L;

Int32Value.Builder builder = Int32Value.newBuilder();
JsonFormat.parser().merge(Long.toString(longValue), builder);
```

Throws an exception:
```
com.google.protobuf.InvalidProtocolBufferException: Not an int32 value: -8747832031878802303
```

However this code sample runs fine and silently loses precision:
```java
long longValue = -8747832031878802303L;

DoubleValue.Builder builder = DoubleValue.newBuilder();
JsonFormat.parser().merge(Long.toString(longValue), builder);
DoubleValue value = builder.build();

System.out.println(longValue);
System.out.println(BigDecimal.valueOf(value.getValue()).longValue());
```

Prints:
```
-8747832031878802303
-8747832031878802400
```

Would it make sense for `parseDouble` to throw `InvalidProtocolBufferException` if the input is an integral value which can't be represented properly as a `double`?

For some context, we ran into an issue with this when using `google.protobuf.Value` to store arbitrary metadata, using a message like so:
```protobuf
message Example {
  int64 id = 1;
  string name = 2;
  google.protobuf.Value metadata = 3;
}
```

This is exposed as a JSON API, so users can send arbitrary JSON structures for `metadata` and have them persisted. But `google.protobuf.Value` stores all numbers as `double`, so we were silently losing precision for some inputs, which caused problems when the users fetched the metadata and tried to use it.

**Comment by jhaber** [comment]
Hi there, just wanted to see if anyone had thoughts on this issue. It might be hard to change behavior at this point and make these inputs throw `InvalidProtocolBufferException`, but maybe it could be gated behind a parser option

**Comment by perezd** [comment]
@shaod2 would you mind taking a peek at this?

**Comment by googleberg** [comment]
Fixing would likely break other users. Parsing strings into doubles often loses precision.
