### ISSUE TITLE
Any message type throws access violation error in C++

### ISSUE THREAD

**Issue by hazdazzler009** [protocolbuffers/protobuf#7647]
I am using the following proto file:

```
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message foo {
 string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
  google.protobuf.Any details = 2;
}

```
On server side, this is how I populate the reply:

 ```
std::string prefix("Hello ");
reply->set_message(prefix + request->name());
foo f;
f.set_name("my name is foo");

Any any;
any.PackFrom(f);
reply->set_allocated_details(&any);
	
return Status::OK;
```
On the client side I get the following error:
```
14: Endpoint read failed
Greeter received: RPC failed
```
If I uncomment the set_allocated_details line then everything works. Can anyone tell me what am I doing wrong, seems like I am missing something obvious?
protoc version: libprotoc 3.2.0
platform : windows

**Comment by hazdazzler009** [comment]
Debuging server side, here's the error:
```
Unhandled exception thrown: read access violation.
std::_String_alloc<std::_String_base_types<char,std::allocator<char> > >::_Mysize(...) returned 0xFFFFFFFFFFFFFFFF.
```

**Comment by acozzette** [comment]
The `set_allocated_` accessors expect to be given a pointer to a heap-allocated message. Since you're passing it a pointer to an `Any` on the stack, it's going to take ownership of it and try to `delete` it, which will cause problems. You could try something like this instead:
`reply->mutable_details()->PackFrom(f);`

**Comment by hazdazzler009** [comment]
Thank you so much @acozzette for not only the solution but also the explanation. It makes sense.
