### ISSUE TITLE
Conversion Google\Protobuf\Internal\RepeatedField Object to php array

### ISSUE THREAD

**Issue by yoola** [protocolbuffers/protobuf#7648]
I'm retrieving my repeated values in php (proto3) by, e.g. 

$data->mergeFromString($binary);
$timestampsUnix = $data2->getTimestamps()->getUnix();

As a result, I get a Google\Protobuf\Internal\RepeatedField Object. 
So I still need to do ...

$timestampsUnix2 = array();
foreach ($timestampsUnix as $timeSt) {
            array_push($timestampsUnix2, $timeSt);
}

... to get a valid array format which I can work with. It would be great if there could be a conversion function for php which converts those repeated object values into a php array. Thanks a lot!

**Comment by haberman** [comment]
If I'm understanding correctly, you can write the following function to get your desired result:

```php
function toArray($rf) {
  $ret = array();
  foreach ($rf as $elem) {
    array_push($ret, $elem);
  }
  return $ret;
}
```

While we could include a `RepeatedField::toArray()` function ourselves, I'm not convinced we should add this to the main library, since this function is so easy to write manually.

**Comment by yoola** [comment]
I don't think this is a good argument, since it makes sense to have functionalities in a package that are frequently used, so that not every user has to implement them himself even if it's simple to do so.

**Comment by DeveloperRob** [comment]
I was looking into this myself, but I found it is actually easier than @haberman suggested - you can wrap the call that returns the repeated field with iterator_to_array (https://www.php.net/manual/en/function.iterator-to-array.php). 

So for example, using the OP example, you can do:
```
$data->mergeFromString($binary);
$timestampsUnix = \iterator_to_array(
    $data2->getTimestamps()->getUnix()
);
```

**Comment by vmasdani** [comment]
Thanks a bunch @DeveloperRob. I was having difficulties turning `RepeatedField` iterator to array in decoding protobuf message to Eloquent model, I didn't know that there's `iterator_to_array` method, problem instantly solved.

I tried casting like
```php 
(array) $vx->getStorageRecords()
```
But it did not work, as my `decode` function accepts `StorageProto`. Casting with `(array)` turns the `$sr` in the lambda function to `array` instead of `StorageProto`. But this works:
```php
iterator_to_array($vx->getStorageRecords())
```

Full code:
```php
// Storage is Eloquent model, StorageProto is protobuf message
public static function decode(StorageProto $vx): Storage
{
    $v = new Storage();
    // base model
    if ($vx->hasBaseModel()) {
        Helper::decodeBaseModel($vx->getBaseModel(), $v);
    }
    // base model end
    if ($vx->hasValue()) {
        $v->value = $vx->getValue();
    }
    if ($vx->hasKey()) {
        $v->key = $vx->getKey();
    }
    if ($vx->hasUserId()) {
        $v->user_id = $vx->getUserId();
    }
    if ($vx->hasSandbox()) {
        $v->sandbox = $vx->getSandbox();
    }
    if ($vx->getStorageRecords()) {
        $v->storage_records = array_map(function ($sr) {
            return StorageRecord::decode($sr);
        }, iterator_to_array($vx->getStorageRecords()));
    }

    return $v;
}
```

**Comment by haberman** [comment]
Thanks @DeveloperRob, `iterator_to_array()` is a great suggestion here. Since that is available, I am closing this issue.
