### ISSUE TITLE
undefined symbol: _ZN6google8protobuf5Arena18CreateMaybeMessageIN7demo10Demo

### ISSUE THREAD

**Issue by GOGOYAO** [protocolbuffers/protobuf#7649]
**What version of protobuf and what language are you using?**
Version: 3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
centos 7

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 8.3.1

**What did you do?**

I generate a static lib using the codes generated by protoc. And Then I compile out a shared lib (.so) with the static lib. Finnaly I will compile out my binary with the shared lib. The proto is like this,
```
package demo;
message Demo {
   optional string name = 1;
}

message a {
   repeated Demo demo = 1;
}
```
Then, my binary whill link my `.so` file but I get the error `undefined symbol` when I run the binary.

**What did you expect to see**
I can run my binary successfully.

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

If I modify the `message a` like this,
```
message a {
   repeated string demo = 1;
}
```
I will run my binary successfully. Or I did not use the `add_demo()` function, it works too.

I check the symbol of my `.so` file. I can see two records about `_ZN6google8protobuf5Arena18CreateMaybeMessageIN7demo10Demo`.

```
                 U _ZN6google8protobuf5Arena18CreateMaybeMessageIN7demo10DemoEIEEEPT_PS1_DpOT0_
00000000001e36fc T _ZN6google8protobuf5Arena18CreateMaybeMessageIN7demo10DemoEJEEEPT_PS1_DpOT0_
```
I use the `c++filt` and I can see they are the same function, which I can find in the `pb.cc`.

**Anything else we should know about your project / environment**

**Comment by lingbin** [comment]
First check the compilation options of your static and dynamic libraries to see if they use different `ABI` related options, such as `-fabi-version`.

For more information about `abi-version` option, see: https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html

> 6. Changes to the default compiler option for -fabi-version.
> It is versioned as follows:
> GCC 3.0: (Error, not versioned)
> GCC 3.1: (Error, not versioned)
> GCC 3.2: -fabi-version=1
> GCC 3.3: -fabi-version=1
> GCC 3.4, GCC 4.x: -fabi-version=2 (Incompatible with previous)
> GCC 5 and higher: -fabi-version=0 (See GCC manual for meaning)

From the two symbols you provide, you may have used a higher version of GCC(>gcc5, default `abi-version=0`), but your dynamic library(`.so` file) is compiled with an old `abi-version`(maybe with `-fabi-version=2`).

**Solution**: 
  If `abi-version` is different, you can solve this problem by compiling both your static and dynamic libraries under the same `abi-version`
