### ISSUE TITLE
PHP equality comparison between messages always returns true

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/protobuf#7650]
Comparing messages (or repeated fields, etc) in PHP always returns true, regardless of the contents:

```php
        $m1 = new TestMessage();
        $m2 = new TestMessage();
        $m3 = new TestMessage();
        $rf1 = new RepeatedField(GPBType::INT32);
        $rf2 = new RepeatedField(GPBType::INT32);

        $rf1[] = 5;

        $m1->setOptionalInt32(1);
        $m2->setOptionalInt32(1);
        $m3->setOptionalInt32(3);

        // These succeed.
        $this->assertTrue($m1 == $m2);
        $this->assertFalse($m1 == $rf1);  // Mixing types

        // These fail.
        $this->assertFalse($m1 == $m3);
        $this->assertFalse($rf1 == $rf2);
```

This is true for the C extension (haven't tested pure-PHP).

Should we change this? Should equality compare contents? Should it be a deep comparison? We should provide answers to these questions and possibly change/fix the existing behavior.

**Comment by jtattermusch** [comment]
AFAIK, using `==` is an antipattern in PHP? ("Always use ==="?)

**Comment by haberman** [comment]
@jtattermusch I think that `==` (comparison) and `===` (object identity) implement different operations? Why would object comparison be an anti-pattern?

We support deep comparison in other languages, [for example in Ruby](https://developers.google.com/protocol-buffers/docs/reference/ruby-generated#message):

* `Message#==`: Performs a deep equality comparison between two messages.

**Comment by haberman** [comment]
I'm leaning towards having `==` in PHP implement a deep comparison between two objects of the same type. For objects of different types it could either return false or signal an error.

**Comment by bshaffer** [comment]
In addition to it being intuitive, the PHP `stdClass` objects behave in the way you suggest the objects behaving:

```php
$s1 = new stdClass();
$s2 = new stdClass();
var_dump($s1 == $s2);
// bool(true)
var_dump($s1 === $s2);
// bool(false)

$s1->foo = 'bar';
var_dump($s1 == $s2);
// bool(false)
```

**Comment by fiboknacky** [comment]
I'm aligned with Brent (incidentally again). :)

**Comment by jtattermusch** [comment]
> @jtattermusch I think that `==` (comparison) and `===` (object identity) implement different operations? Why would object comparison be an anti-pattern?

I'm not an expert on PHP, but looks like "==" behavior is deeply flawed in PHP (in general, not in relation to protobuf at all).
See "Operator Madness" section in https://whydoesitsuck.com/why-does-php-suck/

> 
> We support deep comparison in other languages, [for example in Ruby](https://developers.google.com/protocol-buffers/docs/reference/ruby-generated#message):
> 
> * `Message#==`: Performs a deep equality comparison between two messages.

**Comment by PierrickVoulet** [comment]
> This is true for the C extension (haven't tested pure-PHP).

I just tested with pure-PHP and it behaves differently: it seems to perform a deep equality comparison instead.

```php
$rf1 = new RepeatedField(GPBType::INT32);
$rf2 = new RepeatedField(GPBType::INT32);
$rf2[] = 1;

var_dump($rf1 == $rf2);
// With PHP Extension (C implementation)
// bool(true)

// With PHP Module (PHP implementation)
// bool(false)
```

**Comment by PierrickVoulet** [comment]
@haberman @TeBoring this issue is becoming problematic for https://github.com/googleads/google-ads-php, is there anything that we could do to prioritize this?

**Comment by TeBoring** [comment]
Can user code compare field by field for now?

**Comment by haberman** [comment]
I agree it's problematic if the two implementations are having different behavior.

Is the behavior given by pure-PHP right now the right behavior? Or are they both wrong?

Maybe the first step would be to determine exactly what semantics are implemented by pure-PHP right now.

**Comment by TeBoring** [comment]
I think pure php compare implementation detail that the array
representation of both are equal.

**Comment by TeBoring** [comment]
pure php’s implementation was provided by default. In our c extension, we
didn’t provide the handler to convert to array, so we couldn’t use the
default implementation.

**Comment by haberman** [comment]
But does pure-PHP do deep comparison between messages? If you have two arrays of messages, how will it compare the messages? Will it compare them field by field, recursively? What about maps?

**Comment by TeBoring** [comment]
I think it’s deep. Map would be dict.

**Comment by haberman** [comment]
We should verify this. Specifically, we should add tests that check the pure-PHP behavior, and then verify that it implements the semantics we want.

If the pure-PHP semantics are correct, then we can change the C extension to match.

**Comment by AnashOommen** [comment]
Folks, gentle ping for an update on this issue. We have broken code examples in Google Ads that are dependent on the resolution of this bug.

**Comment by PierrickVoulet** [comment]
@haberman I may be missing something obvious but I am still getting the same behavior while using your new version:

```php
$rf1 = new RepeatedField(GPBType::INT32);
$rf2 = new RepeatedField(GPBType::INT32);
$rf2[] = 1;

var_dump($rf1 == $rf2);
// With PHP Extension (C implementation)
// bool(true)

// With PHP Module (PHP implementation)
// bool(false)
```

**Comment by TeBoring** [comment]
I think user is not supposed to create repeated field by himself.

**Comment by PierrickVoulet** [comment]
I did more digging and 2 of our comparison tests are fixed with the new version, thanks!

I still see our comparison test failing with a repeated field of messages though:

```
============ TEST 'Modify message in a repeated field'
LEFT: {"foos":[{"num":"1"},{"num":"2"}]}
RIGHT: {"foos":[{"num":"1"},{"num":"3"}]}
- expected diff: foos 
- actual diff: 
```
