### ISSUE TITLE
[MSVC] fails on protostream_objectwriter_test.cc

### ISSUE THREAD

**Issue by gvanem** [protocolbuffers/protobuf#7653]
The file `util/internal/protostream_objectwriter_test.cc` fails to compile with MSVC-2019:
```
protostream_objectwriter_test.cc(107): error C2039: 'tr1': is not a member of 'std'
f:\gv\VC_2019\VC\Tools\MSVC\14.26.28801\include\stack(20): note: see declaration of 'std'
protostream_objectwriter_test.cc(107): error C3083: 'tr1': the symbol to the left of a '::' must be a type
```

Reason seems to be that with `cl -std:c++14`, it does not set the value of `__cplusplus` to a suitable value for:
```c
#if __cplusplus >= 201103L
using std::get;
#else
using std::tr1::get;
#endif
```

But with this, it compiles with any `-std:cxx` value.
```c
#if (__cplusplus >= 201103L) || (_MSVC_LANG >= 201103L)
using std::get;
#else
using std::tr1::get;
#endif
```

**Comment by acozzette** [comment]
@gvanem Thanks for the bug report. We have been requiring C++11 (or newer) starting from protobuf 3.5, so we can just remove this logic that checks for C++11. I made that change to our internal codebase and it should get pushed to GitHub within a few days.
