### ISSUE TITLE
Consider change HasFoo to methods instead of  fields in C# when proto2

### ISSUE THREAD

**Issue by rozbo** [protocolbuffers/protobuf#7657]
## current

```c#
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
```

we can check it by
```c#
{
if (someObj.HasCode){
    xxxxx
}
```

## want to 
```c#
    public bool HasCode() {
           return (_hasBits0 & 1) != 0; 
    }
```

# reason
1. Be consistent with other languages like c++ 
2. This will have side effects on generating json （There will be some additional members HasFoo:true）

#7395

**Comment by rozbo** [comment]
@jskeet bro, do you think so?

**Comment by jskeet** [comment]
No, these are naturally properties (they're not fields) in my view... and changing them now would be breaking change, too.

I'll leave this open for others to consider, but I'm personally strongly opposed to it.

**Comment by rozbo** [comment]
It is really a breaking change, but now hasn't officially announced it support for proto2 , so I think it's a great opportunity to change it (if want to change it)  
On the contrary, I think only those defined by metadata can be naturally properties, and this is a supplementary and instrumental field, which should not be its naturally properties.
At this point, other language implementations do this(c++,javascript,php)
I have no intention of arguing with you, I just hope you reconsider.

**Comment by rozbo** [comment]
for other one who encountered this, can ref https://stackoverflow.com/questions/12754463/json-net-ignore-property-during-deserialization to ignore all properties start with `Has`

**Comment by jskeet** [comment]
> On the contrary, I think only those defined by metadata can be naturally properties

It's part of the state of the object. It's as naturally a property as (say) `DateTime.Hour` is.

> At this point, other language implementations do this(c++,javascript,php)

Do all those languages *have* properties in the same way? Each language generates idiomatic code, and I can't see why it would be idiomatic for this to be a method. 

In terms of JSON serialization, you shouldn't try to serialize using Json.NET anyway: use the built-in JSON serialization, in order to guarantee compatibility with other languages. There are various ways in which using external JSON serializers will do the wrong thing - not just "Has" properties.

**Comment by rozbo** [comment]
but, the state of the object can be private. all public properties will be serialized, has nothing to do with the serializer. 
btw, JSON.NET is recommended by official documentation, ref: https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1

**Comment by jskeet** [comment]
> but, the state of the object can be private. all public properties will be serialized, has nothing to do with the serializer.

That's got *everything* to do with the serializer. The serializer chooses what it decides to serialize - that's its job. (And that's precisely why you can configure the serializer to ignore certain properties.)

> btw, JSON.NET is recommended by official documentation, ref: https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1

That's not the *protocol buffers* documentation though, is it?

If you serialize protobuf objects using Json.NET, they may well not be deserializable via other protobuf platforms. The naming conventions etc are all specified by protobuf. We would add Json.NET configuration attributes to the generated code, but that would then require a dependency on Json.NET, which we definitely don't want to do.

If you want to serialize something using Json.NET and some of the members are protobuf messages, you should create a Json.NET custom serializer that just uses the `ToString()` method of the protobuf object. (You'd need to configure enums separately.) I suspect that for 99% of the time, you don't really want to mix and match between protobuf and non-protobuf though - so just using the protobuf JSON serializer is fine.

**Comment by rozbo** [comment]
Does the protobuf has it own serializer? 
My scene：
```c#
public IActionResult foo(){
     var obj = Foo.Parser.ParseFrom(dat);
     return obj;
}
```
the asp.net will serialize it to json automatically, how can I use the protobuf's own serializer?

**Comment by rozbo** [comment]
oh I got it , is the `ToString()`

thank you!

**Comment by jskeet** [comment]
Use `Foo.Parse.ParseJson` to parse, and either call `ToString()` or use `JsonFormatter` for formatting.
