### ISSUE TITLE
Python modules are generated with incorrect syntax when the folder path contains a folder starting with a number

### ISSUE THREAD

**Issue by Jebediah** [protocolbuffers/protobuf#7661]
Protoc version 3.11.2 on Ubuntu 16.04.6

There's probably an easier way to reproduce, but how I found it was to:
1. grab https://github.com/cartographer-project/cartographer
2. Edit https://github.com/cartographer-project/cartographer/blob/master/CMakeLists.txt#L147 and add --python_out ${PROJECT_BINARY_DIR}
3. Build and try to import one of the python files whose path contains a "2d" or "3d" folder.

I think the problem is that the generated python code contains statements like

from whatever.2d.whatever import something as alias

which is apparently a syntax error. I think this is a bug because on this page (https://developers.google.com/protocol-buffers/docs/reference/python-generated) it states  "Note that if the .proto file or its path contains any characters which cannot be used in Python module names (for example, hyphens), they will be replaced with underscores. So, the file foo-bar.proto becomes the Python file foo_bar_pb2.py".

A workaround is to use sed to change all these imports to
alias = __import__('whatever.2d.whatever', fromlist=['something']).something, though I'm not sure if this might cause an issue later.

**Comment by fowles** [comment]
Closing out old issues.  Please reopen if this still occurs on recent releases.
