### ISSUE TITLE
unity2018 不能加载 Google.Protobuf.dll

### ISSUE THREAD

**Issue by jiangjiali** [protocolbuffers/protobuf#7668]
Assembly 'Assets/Plugins/Google.Protobuf.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Memory'. Is the assembly missing or incompatible with the current platform?

**Comment by jiangjiali** [comment]
unity 2018.3.0f2 运行时，出现一下bug提示：
Unloading broken assembly Assets/Plugins/Google.Protobuf/Google.Protobuf/Google.Protobuf.dll, this assembly can cause crashes in the runtime

**Comment by vitorbaraujo** [comment]
Have you added the System.Memory DLL? Also, if you're using .NET 3.5, be aware that newer versions of Google.Protobuf do not support .NET 3.5 (the latest version I got it working with .NET 3.5 what 3.6.1).

**Comment by jiangjiali** [comment]
it's ok
