### ISSUE TITLE
encoding (serialization)  Map Fields

### ISSUE THREAD

**Issue by zavarat** [protocolbuffers/protobuf#7671]
According to the google guide, "JavaScript Generated Code" contains the following function for Map Fields. But no matter how hard I look, I can't see a function for encoding. (Of course, I thought there would be a function like setXXXMap(), but I couldn't find it.) How should I encode Map Fields?

https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#map
---

Map Fields
For this message with a map field:

```
message Bar {}

message Baz {
  map<string, Bar> foo = 1;
}
```
the compiler generates the following instance method:
getFooMap(): Returns the Map containing foo's key-value pairs. You can then use Map methods to interact with the map.

---

**Comment by zhushenhang** [comment]
same issue.
did you solve it?
