### ISSUE TITLE
New argument `create_key` in Python 

### ISSUE THREAD

**Issue by craynic** [protocolbuffers/protobuf#7672]
I noticed that there comes a new argument `create_key` in class init `DescriptorBase`. The `pb2.py` file template also got modified and `create_key=_descriptor._internal_create_key` added.
It brought me a little trouble because I always use the latest version of protoc to generate Python pb2 files while use them in environments with old protobuf lib installed. After I upgrade protobuf lib, all things get OK.
The errors should look like:
```python
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
I see the changes in #7344. But it didn't explain why they are added. Could anyone give a reference about what they are used for?

**Comment by jjdressel11** [comment]
This was a breaking change for us. We had to revert to 3.11.4 to generate python files that weren't causing crashes with this error.

**Comment by acozzette** [comment]
I'm not familiar with this particular change, but the general rule for Python protobuf is that the protobuf library has to be at least as new as the protoc version used. If you upgrade protoc without upgrading the library, these kind of breakages can occur.

**Comment by jjdressel11** [comment]
Having protoc and protobuf at 13.12.4 was causing the following error:
```
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

You should also look into the reason why `create_key` was added as as an argument to all descriptors without any documentation in https://github.com/protocolbuffers/protobuf/pull/7344

**Comment by jjdressel11** [comment]
False alarm on this one. We discovered that Dataflow workers are using the 3.12.2 version of protobuf. Forcing these workers to use version 3.12.4 resolved this issue.

Regardless, there should be documentation for the `create_key` argument that was added to all descriptors.

**Comment by HemantPatil0219** [comment]
I am facing same error i.e  AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key' 
i am using protoc version 3.13.0 and protobuf version 3.13.0 both are same still i am facing above error. Help me with this please

**Comment by craynic** [comment]
Now I have a new job, so I may not have the need to struggle in gRPC Python any longer, while the doc on why it is added and how it works is still valuable.

And, I don't think submitting a large PR with no comments is a good way to maintain an opensource project. At least, some change-logs could be copied to comment in the PR.

**Comment by anandolee** [comment]
As acozzette mentioned above "The general rule for Python protobuf is that the protobuf library has to be at least as new as the protoc version used. If you upgrade protoc without upgrading the library, these kind of breakages can occur."  This issue is caused because protoc is newer than protobuf runtime. Upgrade the runtime can solve the problem
