### ISSUE TITLE
Expose resetting the position in CodedOutputStream (C#)

### ISSUE THREAD

**Issue by MaximGurschi** [protocolbuffers/protobuf#7676]
Hi,

What do you think of a small update to the COS, to support resetting the position, if the data is written to a flat array directly?
The use case is the ability to reuse the same COS with a preallocated buffer. 
This should help with some GC concerns around COS.

The effect of resetting the position is achievable by using the Stream ctors on COS, but that means that every byte must go through an intermediary stream before landing in the preallocated buffer.

**Comment by acozzette** [comment]
Why not just call `msg.SerializeToArray(...)` and not use a `CodedOutputStream` at all?

**Comment by MaximGurschi** [comment]
@acozzette That API is not available in C#? I should have specified the language in the post.

**Comment by MaximGurschi** [comment]
I think this will be achievable once
https://github.com/protocolbuffers/protobuf/pull/7576

, is released. Closing for now.
