### ISSUE TITLE
C++ enum_Name functions are now templates, breaking existing code.

### ISSUE THREAD

**Issue by inazarenko** [protocolbuffers/protobuf#7679]
I'm upgrading a fairly large codebase to v3.12.3. One change between the versions was that <EnumType>_Name functions are now templates. Here's the list of breakage kinds that I encountered. All examples assume:
```
message X {
  enum E { ... }
}
```

- code that attempts to introduce a short alias for the `_Name` function
  ```
  auto& E_Name = X::E_Name;
  ```
- code that takes the address of the `_Name` function:  
  ```
  void foo(std::function<string(X::E)> bar);
  ...
  foo(&X::E_Name);
  ```
- code that passes a type implicitly convertible to `E`:
  ```
  std::atomic<X::E> e;
  ...
  return X::E_Name(e);
  ```

I realize that reverting the change is not practical at this point, so this is mostly FYI. From the comments on the commits that introduced the change, I got a feeling that the authors weren't sure if this would be a backward-compatible change. It wasn't :)

**What version of protobuf and what language are you using?**
Version: 3.12.3.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu LTS 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 9.0.1

**Comment by acozzette** [comment]
@inazarenko Thanks for the heads-up and sorry for the trouble. An alternative that you might find useful is that you can do `google::protobuf::GetEnumDescriptor<MyEnum>()->FindValueByNumber(number)->name()`. Then instead of passing a function pointer, you can pass the enum type as a template parameter.
