### ISSUE TITLE
Afford "services()" method on FileDescriptor instances and "methods()" on ServiceDescriptor instances

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#7680]
DESCRIPTION:
In working with C++ `FileDescriptor` instances it would be nice to have a `.services()` method on those rather than just [`.service_count()`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor#FileDescriptor.service_count) and [`.service(int index)`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor#FileDescriptor.service.details) so that rather than writing

```C++
void FrobnicateServices(const google::protobuf::FileDescriptor* file) {
  for (int index = 0; index < file->service_count(); index++) {
    FrobnicateService(file->service(index));
  } 
}
```
one could rather write
```C++
void FrobnicateServices(const google::protobuf::FileDescriptor* file) {
  for (const google::protobuf::ServiceDescriptor* service : file->services()) {
    FrobnicateService(service);
  } 
}
```
(and similarly for the `MethodDescriptor`s accessible from a `ServiceDescriptor` instance).

**Comment by deannagarcia** [comment]
Sorry for the very late response. In general, protocol buffers rarely return arrays/other collections of variables. This is a combination of wanting all languages to have very similar methods and not wanting to reconstruct the array on call. Unfortunately, we will not be implementing this feature.
