### ISSUE TITLE
What is the rationale of compiling importer.cc and parser.cc into libprotobuf rather than in libprotoc?

### ISSUE THREAD

**Issue by georgthegreat** [protocolbuffers/protobuf#7681]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**All of the above.**

**Describe the problem you are trying to solve.**

At the time, [compiler/importer.cc](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/importer.cc) and [compiler/parser.cc](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/parser.cc) are linked into `libprotobuf.so` rather than in `libprotoc.so`. See [Makefile.am](https://github.com/protocolbuffers/protobuf/blob/86b3ccf28ca437330cc42a2b3a75a1314977fcfd/src/Makefile.am#L261), [libprotobuf.cmake](https://github.com/protocolbuffers/protobuf/blob/86b3ccf28ca437330cc42a2b3a75a1314977fcfd/cmake/libprotobuf.cmake#L5), [BUILD](https://github.com/protocolbuffers/protobuf/blob/86b3ccf28ca437330cc42a2b3a75a1314977fcfd/BUILD#L215).

These two files, however, implement `.proto` files parsing and thus should be linked into `libprotoc.so`. According to the [statement](https://developers.google.com/protocol-buffers/docs/reference/cpp#google.protobuf.compiler) in C++ API Reference regarding `google::protobuf::compiler` namespace:

> Since this functionality is only useful to those writing custom compilers, it is in a separate library called "libprotoc" which you will have to link against. 

**Describe the solution you'd like**

Fix the build scripts by moving these two files into corresponding section / library.

**Comment by georgthegreat** [comment]
@haberman @acozzette, could you, please, take a look onto this?
Looks like an old and dusty build configuration bug, yet I have no real proofs.

**Comment by acozzette** [comment]
@georgthegreat This does seem like a mistake, but I'm not sure that it is worth fixing at this point. If we moved importer.cc and parser.cc into libprotoc, any code relying on them being present in libprotobuf could break.

**Comment by georgthegreat** [comment]
Could ABI breakabe happen during next major / minor upgrade?
I could not find any policy describing ABI / API compatibility between protobuf releases. Is there some policy?

Generally, I am fine that you have agreed that this is indeed a bug in configuration. If there is no real option to fix this, I suggest closing this issue.

**Comment by acozzette** [comment]
We don't make any attempt to preserve ABI compatibility, so the ABI breaks on effectively every release and you must rebuild from source when upgrading. In this case it is a bit different, though, because rebuilding wouldn't necessarily be enough, and you might also have to change your build setup to add a dependency on libprotoc.
