### ISSUE TITLE
How should PHP report errors?

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/protobuf#7685]
There appear to be several related but distinct ways of signaling errors in PHP:

1. Zend Exceptions: raise with `zend_throw_exception()`.
2. Zend Errors: raise with `zend_error()`.
3. PHP errors: raise with `php_error_docref()`.

The old extension uses a mix of (1) and (2). I've seem [some info](https://stackoverflow.com/a/52324314) suggesting that PHP extensions should never use (2), only (3). I haven't found a way to unit test for (2) or (3) in a way that works across versions.

What is the right answer here? Can we choose one of these options to use for all errors?

**Comment by bshaffer** [comment]
See [PHP 7 Errors](https://www.php.net/manual/en/language.errors.php7.php) for the main difference. What used to be an uncatchable PHP "error" in PHP 5 is now a catchable `Error` which extends `Throwable` in PHP 7. I do not believe there is a very good argument for throwing errors as opposed to exceptions in the protobuf extension.

You can read more on this [here](https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/)

**Comment by haberman** [comment]
Great info, thanks!

Should protobuf define its own exception class, or should we continue to use `Exception` as we do now?

**Comment by bshaffer** [comment]
I think it depends. If an [exception exists already](https://www.php.net/manual/en/spl.exceptions.php) which does a good job describing the error (e.g. `InvalidArgumentException` or `RuntimeException`, it's okay to use these. If there's a unique type of exception that doesn't map well to these (say, a `SerializationException`), then defining a protobuf Exception class is preferred so it can be explicitly caught in try/catch blocks.

**Comment by fiboknacky** [comment]
I'm aligned with @bshaffer
