### ISSUE TITLE
How to access python enums in protobufs?

### ISSUE THREAD

**Issue by vvksahoo** [protocolbuffers/protobuf#7687]
**What version of protobuf and what language are you using?**

protobuf==3.12.2(pip install protobuf), python

**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.7
**What did you do?**
1:  pip install protobuf
2: pip install grpcio-tools
3: Written .proto file
```
syntax = "proto3";


message Person {
   string name = 1;
   int32 id = 2;
   string email = 3;

   enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
     string number = 1;
     PhoneType type = 2;
  }
  repeated PhoneNumber phone = 4;
}
````
4: python -m grpc_tools.protoc --proto_path=./ --python_out=./ my_example.proto
5: Set the enum value 
```
import my_example_pb2
person_obj = my_example_pb2.Person()
person_obj.name = 'Google'
person_obj.id = 1
person_obj.email = 'gmail'
phn_obj = person_obj.phone.add()
phn_obj.number = '1800-500-501'
phn_obj.type = my_example_pb2.Person.PhoneType.Value('MOBILE')

```

**What did you expect to see**
```
phones {
  number: "1800-500-501"
  type: MOBILE

```
**What did you see instead?**
```
phones {
  number: "1800-500-501"
}
```
strange thing is if i use ```phn_obj.type = my_example_pb2.Person.PhoneType.Value('HOME')``` or ```phn_obj.type = my_example_pb2.Person.PhoneType.Value('WORK ')``` its giving the expected result .
```
phone {
  number: "213234334"
  type: HOME
}
or phone {
  number: "213234334"
  type: WORK 
}
```
Why it is not working in the case of MOBILE?

**Comment by tiagomdiogo** [comment]
I Found that index 0 was the default value for enum on Protobuf. Maybe its causing some conflit.
A Solution for your problem is creating a default value, for example:
```
enum PhoneType{
    DEFAULT = 0;
    MOBILE = 1;
    HOME = 2;
    WORK = 3;
}
```
And you should be fine doing that. Im still trying to figure out why this happens but in the mean time you have a workaround solution.
