### ISSUE TITLE
Make protobuf C++ backend default with pip install on AArch64/32 platforms

### ISSUE THREAD

**Issue by jvsd** [protocolbuffers/protobuf#7693]
C++ backend should be the default when pip installing on arm platforms. 

https://github.com/protocolbuffers/protobuf/issues/1332

**Comment by jangrzybek** [comment]
Please do.

**Comment by jtattermusch** [comment]
Starting from protobuf 3.17.0, we started publishing python aarch64 manylinux2014 wheels: https://pypi.org/project/protobuf/3.17.0/#files

What that means is that when you pip install google.protobuf on aarch64 linux, you'll by default get a version that supports the fast C++ based version.

I don't think there's currently any plan to provide aarch64 wheels for other operating systems or for aarch32.

**Comment by elharo** [comment]
Addressed
