### ISSUE TITLE
TextFormat.printToUnicodeString does not escape newlines in strings

### ISSUE THREAD

**Issue by genady** [protocolbuffers/protobuf#77]
String produced by this method cannot be parsed back with merge() due to unescaped newlines.

Shouldn't the escapeDoubleQuotesAndBackslashes() method replace newlines with \n?

**Comment by genady** [comment]
Can you please backport that to 2.6.x release?

**Comment by xfxyjwf** [comment]
@genady we don't plan to have more 2.x.x releases. Could you just use the v3.0.0-alpha-2 version? You can stick with proto2 syntax in your existing code.
