### ISSUE TITLE
google::protobuf::util::JsonStringToMessage How to reject a json string when the json string missing a proto3 message field ?

### ISSUE THREAD

**Issue by YuanYingdong** [protocolbuffers/protobuf#7702]
Pb3 removed the keyword required and optional, And we want to do the field check when converting from a json string to pb3 message, we find when a field is missing the Jong string, JsonStringToMessage API will automatically set the missing field to the default value, for example empty json string "{}” will set all message fields to default by calling this API, but such json request is obviously illegal. how to do this json field check in pb3?

**Comment by acozzette** [comment]
Proto3 doesn't make a distinction between a primitive field being absent and it being set to its default value (i.e. 0 for numeric types or "" for strings/bytes). Once you have parsed the json into a proto message, there is no way to tell whether or not a particular field was set.
