### ISSUE TITLE
Some releases are not found in PECL

### ISSUE THREAD

**Issue by PierrickVoulet** [protocolbuffers/protobuf#7714]
**What version of protobuf and what language are you using?**
Version: 3.12.3, 4.0.0RC1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP Extension (C implementation)

**What did you do?**
I went to https://pecl.php.net/package/protobuf

**What did you expect to see**
All the released versions of protobuf to date

**What did you see instead?**
I could not find the versions 3.12.3 and 4.0.0RC1, the latest available is 3.12.2

**Anything else we should know about your project / environment**
None

**Comment by haberman** [comment]
4.0.0RC1 is uploaded now.

**Comment by haberman** [comment]
3.12.3 is uploaded now too.
