### ISSUE TITLE
Version 4.0

### ISSUE THREAD

**Issue by GrahamCampbell** [protocolbuffers/protobuf#7717]
The PHP community usually does not consider dropping support for older versions of PHP to be a BC break. If this is the only reason for a 4.0 release, I'd question if it is worth it.

**Comment by remicollet** [comment]
Looking at reflection for [3.2.13](https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-protobuf.git/plain/REFLECTION) and [4.0.0RC1](https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-protobuf4.git/plain/REFLECTION) it seems there are lot of changes (54 classes => 14 classes)

**Comment by GrahamCampbell** [comment]
How many of those classes where `@internal`?

**Comment by bshaffer** [comment]
I believe PHP 5 users will receive an error when compiling Version 4.0, which means it is actually a backwards compatibility break and deserves a major version bump.

**Comment by GrahamCampbell** [comment]
Right, but as I said, the PHP community doesn't consider that to be a breaking change. PECL packages and Composer packages drop support for older PHP versions all the time in minor releases, and this is considered to be compatible with semantic versioning.

**Comment by bshaffer** [comment]
@GrahamCampbell thank you for weighing in. Can you provide some examples of this?

**Comment by GrahamCampbell** [comment]
Of course. The 2nd most popular PECL extension "yaml" dropped PHP 7.0 support in a minor release in April this year. The 3rd most popular PECL extension "xdebug" dropped PHP 5.5, 5.6, 7.0, and 7.1 support all in minor releases, over the last few years. The package manager Composer itself will be dropping PHP 5.3 (and maybe others) in a minor release later this year (https://github.com/composer/composer/issues/8785). The 15th most popular composer package https://packagist.org/packages/doctrine/instantiator with over 200 million downloads dropped PHP 5.3-7.0 in a minor release earlier this year and so did the 16th most popular package https://packagist.org/packages/doctrine/lexer. The list goes on. Even those packages that have not yet done this, have authors that plan to do it in the future, or agree that it is not a BC break.

**Comment by haberman** [comment]
> Looking at reflection for 3.2.13 and 4.0.0RC1 it seems there are lot of changes (54 classes => 14 classes)

To clarify, many of the classes that appear to have disappeared are still there, but are now implemented with pure PHP that is embedded into the C extension and lazily loaded with `protobuf_internal_loadbundled`:

https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/protobuf.c#L165-L167

**Comment by GrahamCampbell** [comment]
Also, Microsoft dropped PHP 7.0 in version 5.6.0, and PHP 7.1 in version 5.8.0 of their sql server extension: https://github.com/Microsoft/msphpsql.

**Comment by bshaffer** [comment]
@GrahamCampbell thank you so much for providing all this information. This is very helpful. I agree that we should keep this a minor version bump for both the composer package and PECL extension given that:

  1. No other changes took place that will break backwards compatibility 
  2. Both the PECL and Composer packages are updated to only be compatible with the appropriate versions of PHP

**Comment by haberman** [comment]
Regarding #2, the PECL package has already been updated to depend on PHP >= 7.0 in https://github.com/protocolbuffers/protobuf/pull/7730. Composer doesn't need to be updated because the pure-PHP library still supports PHP 5.

**Comment by TeBoring** [comment]
Without a major version bump, do we still want to have #7692 (stop referencing legacy class names) in this release?
That change is a API breaking change for very old protobuf php generated code.
My thinking is to include that change, because we have introduced the new class name more than a year ago. Users should have already got enough time to migrate (by just regenerating their generated code.)

**Comment by dwsupplee** [comment]
> The 2nd most popular PECL extension "yaml" dropped PHP 7.0 support in a minor release in April this year.

It looks like this actually happened in a 2.0 release: https://pecl.php.net/package/yaml/2.0.0

> The 3rd most popular PECL extension "xdebug" dropped PHP 5.5, 5.6, 7.0, and 7.1 support all in minor releases, over the last few years. The package manager Composer itself will be dropping PHP 5.3 (and maybe others) in a minor release later this year (composer/composer#8785).

Xdebug also supplies a nice [wizard](https://xdebug.org/wizard) that helps guide users into which versions are supported. This is one approach, but I think this information can also be signaled to users by using major version bumps when striking changes are applied.

> The 15th most popular composer package https://packagist.org/packages/doctrine/instantiator with over 200 million downloads dropped PHP 5.3-7.0 in a minor release earlier this year and so did the 16th most popular package https://packagist.org/packages/doctrine/lexer. The list goes on. Even those packages that have not yet done this, have authors that plan to do it in the future, or agree that it is not a BC break.

This seems a bit different to me as these are packages installed via composer and not pecl, users can still resolve older versions of the package easily. Also, looking through issues it seems there was a fair amount of confusion brought about by this that may have been avoided by a major version bump.

From what I can tell, this seems to be a fragmented issue with no broad consensus. For each example of teams that don't bump the major version, there are examples of others that do - I think it just comes down to what makes the team comfortable in how they convey this information effectively to users. Personally, I still think a major bump is a nice way to inform folks PHP5 is no longer usable with the extension.

**Comment by haberman** [comment]
We ultimately decided not to introduce a new major version for dropping PHP 5.x in PECL.
