### ISSUE TITLE
[js] export BinaryEncoder, BinaryDecoder

### ISSUE THREAD

**Issue by jackielii** [protocolbuffers/protobuf#7739]
**What language does this apply to?**

javascript, nodejs

**Describe the problem you are trying to solve.**

I want to use the low level binary serialisation

**Describe the solution you'd like**

export BinaryEncoder, BinaryDecoder & arith.Int64, arith.Uint64

**Describe alternatives you've considered**

fork the project

**Additional context**

Actually the typescript typings seems to think they're exported:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-protobuf/index.d.ts

**Comment by perezd** [comment]
I think your best option here is to fork it.

**Comment by jackieli-tes** [comment]
Update:

I found that using [patch-package](https://github.com/ds300/patch-package) is a better approach. The only line need to be added is:
```
exports.BinaryDecoder=jspb.BinaryDecoder;exports.BinaryEncoder=jspb.BinaryEncoder;exports.arith={};exports.arith.Int64=jspb.arith.Int64;exports.arith.UInt64=jspb.arith.UInt64;
```
