### ISSUE TITLE
version 3.12.0 crash on iPhone5

### ISSUE THREAD

**Issue by aiqinxuancai** [protocolbuffers/protobuf#7742]
We use the OC version of Protobuf 3.12.0 which is install by pod.

According to the collected crash logs, the problem only occurs on 32-bit devices such as iPhone5, iPhone4s, iPad4, and iPadMini.

```0	Wolf
GPBCodedInputStreamReadDouble (GPBCodedInputStream.m:134 [Inline: GPBConvertInt64ToDouble])
1	Wolf
GPBCodedInputStreamReadDouble (GPBCodedInputStream.m:103)
2	Wolf
-[GPBMessage mergeFromCodedInputStream:extensionRegistry:] (GPBMessage.m:2143)
3	Wolf
-[GPBMessage mergeFromData:extensionRegistry:] (GPBMessage.m:1928)
4	Wolf
-[GPBMessage initWithData:extensionRegistry:error:] (GPBMessage.m:0)
5	Wolf
+[GPBMessage parseFromData:extensionRegistry:error:] (GPBMessage.m:1957)
6	Wolf
+[GPBMessage parseFromData:error:] (GPBMessage.m:1951)
7	Wolf
__45-[NetworkServiceManager receiveData:reqInfo:]_block_invoke (NetworkServiceManager.mm:0)
8	libdispatch.dylib
__dispatch_call_block_and_release + 11
9	libdispatch.dylib
__dispatch_queue_drain$VARIANT$mp + 1759
10	libdispatch.dylib
__dispatch_queue_invoke$VARIANT$mp + 285
11	libdispatch.dylib
__dispatch_root_queue_drain + 1561
12	libdispatch.dylib
__dispatch_worker_thread3 + 97
13	libsystem_pthread.dylib
_pthread_wqthread + 1024```

**Comment by thomasvl** [comment]
This sounds like what was fixed in #6678 last year.

What version of Xcode? Are you sure you are getting 3.12.x protobuf?  Can you make a simple repro project that shows the issue?

**Comment by thomasvl** [comment]
From your call stack, `GPBCodedInputStream.m:134` lines up with a valid line from before the mentioned fix.  Looking at the sources in the 3.12 release, that line number does not match.  So it does seem to indicate you aren't using the 3.12 release and using someting older that does have the bug.

**Comment by aiqinxuancai** [comment]
Sorry, I made a mistake.

It has been confirmed that there is no crash when using version 3.12.0, which seems to be caused by Jenkins not being updated to the latest version in time.
