### ISSUE TITLE
PHP immutable messages

### ISSUE THREAD

**Issue by mssimi** [protocolbuffers/protobuf#7743]
PHP messages are generated mutable, that is actually not good idea, do we really want to let programmer to modify message data once received from by client from server for example? I think not, I should not be possible to modify message once instantiated. 

I do propose that generated PHP message should not contain setters, everything should be set via constructor to ensure message immutability. This will force programmer to not mess with message data when he should not.

**Comment by vfalduto** [comment]
Not a good idea. 
It's currently impossible to mock a Message object in unit test (segfault)

**Comment by esorot** [comment]
This would be a major project which we lack staffing. 
Closing for now, please re-open to help raise priority
