### ISSUE TITLE
enum value ZERO and toString()

### ISSUE THREAD

**Issue by aaajjjlll** [protocolbuffers/protobuf#7745]
proto3

protoc-3.12.3-win32\bin

enum value ZERO with toString()

Java

package test;

import test.Outer.Text;
import test.Outer.Text.Builder;
import test.Outer.Text.Color;

public class X {

	public static void main(String[] args) {
		
		//  Color value = Color.WHITE;    // <- NO issue
		//  Color value = Color.BLUE;     // <- NO issue 
		Color value = Color.RED;          // <- issue with text.toString() 
		
		
		Builder builder = Outer.Text.newBuilder().setColor(value).setValue("Hello World");
		Text text = builder.build();
		
		System.out.println(text.getColorValue());
		System.out.println(text.getColor());
		
		System.out.println("Test ---> " + text.toString());   //<-  issue
		
	}
}

/***** proto file
 
syntax = "proto3";
option java_outer_classname = "Outer";
option java_package = "test";
message Text {
 enum Color {
    RED = 0;
    BLUE = 1;
    WHITE = 2;
  }

    string value = 1;
    Color color = 2;
 }

*****/

**Comment by perezd** [comment]
Sorry but what exactly is the issue here? What do you expect to see?

**Comment by elharo** [comment]
Reopen if this can be clarified.

**Comment by ThomasCollignon** [comment]
When applying `toString()` to a Java object generated by _protoc_, the enum names are replaced by blank if the value defined in the .proto file is zero.

In the sample code it's the case for the name `RED`.

It's annoying because when avoiding zero value we get the message
> First enum value must be 0 in proto3

**Comment by ThomasCollignon** [comment]
I've created another issue since I can't reopen this one.
