### ISSUE TITLE
Missing  protobuf/php/ext/google/protobuf/bundled_php.c

### ISSUE THREAD

**Issue by muzzlerator** [protocolbuffers/protobuf#7746]
**What version of protobuf and what language are you using?**
Version: master/v4.0.0rc1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Freebsd 12, Debian 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Clone repository
2. 
> cd ./protobuf/php/ext/google/protobuf/
> pear package
Error: File "./LICENSE" in package.xml does not exist
Error: File "./bundled_php.c" in package.xml does not exist
Error: Channel validator warning: field "date" - Release Date "2020-06-01" is not today
Cannot package, errors in package

**What did you expect to see**
Compiled package

**What did you see instead?**
No package

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by TeBoring** [comment]
To use the c extension, please download the extension from https://pecl.php.net/package/protobuf
Or ```pecl install protobuf```
