### ISSUE TITLE
Missing release assets in 4.0.0-rc2?

### ISSUE THREAD

**Issue by botovq** [protocolbuffers/protobuf#7748]
The [4.0.0-rc-2 release](https://github.com/protocolbuffers/protobuf/releases/tag/v4.0.0-rc2) does not include the rc-2 versions of the following archives. Note that rc-1 has 28 assets while rc-2 has 20 assets.

- protobuf-all-4.0.0-rc-1.tar.gz
- protobuf-all-4.0.0-rc-1.zip
- protobuf-cpp-4.0.0-rc-1.tar.gz
- protobuf-cpp-4.0.0-rc-1.zip
- protobuf-csharp-4.0.0-rc-1.tar.gz
- protobuf-csharp-4.0.0-rc-1.zip
- protobuf-java-4.0.0-rc-1.tar.gz
- protobuf-java-4.0.0-rc-1.zip

Is this deliberate, an oversight or am I too early?

**Comment by acozzette** [comment]
@botovq Thank you for pointing this out. I updated the rc2 release to add the missing artifacts.
