### ISSUE TITLE
C# IMessage.MergeFrom CodedInputStream for oneof field to not allocate

### ISSUE THREAD

**Issue by MaximGurschi** [protocolbuffers/protobuf#7762]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
I am attempting to reuse IMessage instances to avoid high frequency allocation. I notice that the generated code for the proto message, allocates sub messages in case the field is **oneof**. This is when calling MergeFrom CodedInputStream?

**Describe the solution you'd like**
It would be better if the generated code would attempt to reuse the sub field instance if it is already allocated. Is this possible?

Example:

message MyMessage {
  oneof field {
     type1 t1 = 1;
     type2 t2 = 2; 
 }
}

MyMessage m = ....;
m.MergeFrom(Cis);

The code under the hood of MergeFrom will allocate an instance of t1 always, even if m already has an allocated instance.

For non **oneof** nested message fields this is not the case. Can the generating message code be altered to avoid this allocation? Or is this a fundamental limitation of **oneof**?

**Comment by MaximGurschi** [comment]
Related to #6686

**Comment by jtattermusch** [comment]
I don't think we want to do improvements towards "allocation free parsing" unless there's a clear design & plan first.
See my explanation here: https://github.com/protocolbuffers/protobuf/issues/6686#issuecomment-717171573.
