### ISSUE TITLE
C# - Async methods request

### ISSUE THREAD

**Issue by Fabiest** [protocolbuffers/protobuf#7764]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
I'have a web api using .net 3.1, and by default, synchronous operations are not allowed. I have a endpoint that is supposed to return a protobuf message and uses the writeTo from MessageExtensions. This fails because it is not async. Yes i can work it around, but the right think would be to have async methos I believe.

**Describe the solution you'd like**
Async methods to deal with memory and IO operations.

**Comment by xqrzd** [comment]
You could do something like this, there's no synchronous blocking:

```csharp
// set headers here...
await Response.StartAsync();

var bodyWriter = Response.BodyWriter;
message.WriteTo(bodyWriter);
await bodyWriter.FlushAsync();
```

**Comment by Fabiest** [comment]
Explanation of the issue : (https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#http-synchronous-io-disabled-in-all-servers).
I tried to use the code provided but the WriteTo I have only accepts the type CodeOutputStream which is not what response.BodyWriter is. 
Also, the exception is thrown when calling WriteTo, so i'm not sure if the solution provided will work.

**Comment by xqrzd** [comment]
Ah I see, this was a recent addition to Google.Protobuf (in 3.13) that adds an overload to WriteTo that accepts an IBufferWriter<byte>. Updating the library and re-generating the C# code should add that.

**Comment by jtattermusch** [comment]
Looks like this is solved (by using the new IBufferWriter based serialization)?

**Comment by jskeet** [comment]
Closing this issue based on the last comment.
