### ISSUE TITLE
ImportError: cannot import name '_message' from 'google.protobuf.pyext' on windows and python3.8

### ISSUE THREAD

**Issue by TobKed** [protocolbuffers/protobuf#7765]
Problem similar to https://github.com/protocolbuffers/protobuf/issues/5775
I'm working on tests for https://github.com/apache/beam and it fails during importing `google.protobuf.pyext._message` for mentioned below environment.

**What version of protobuf and what language are you using?**
Version: 3.12.2/3.12.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows Server 2019
10.0.17763
Datacenter

**What runtime / compiler are you using (e.g., python version or gcc version)**
CPython (3.8.5)

**What did you do?**

I run github action with tox tests for python3.8 on windows.
Verified on my PC on windows10 as well: `import google.protobuf.pyext._message as pyext_message` fails.

```
Traceback (most recent call last):
  File "setup.py", line 274, in <module>
    setuptools.setup(
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\site-packages\setuptools\command\sdist.py", line 44, in run
    self.run_command('egg_info')
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\hostedtoolcache\windows\python\3.8.5\x64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 253, in run
    gen_protos.generate_proto_files()
  File "D:\a\beam\beam\sdks\python\gen_protos.py", line 347, in generate_proto_files
    generate_urn_files(log, out_dir)
  File "D:\a\beam\beam\sdks\python\gen_protos.py", line 66, in generate_urn_files
    import google.protobuf.pyext._message as pyext_message
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```

Place in the code where it is used: https://github.com/apache/beam/blob/631cb81b39d1beaf53e9fd4b9f144e098c2aeace/sdks/python/gen_protos.py#L66

Logs to github action workflow run on my apache/beam frok: https://github.com/TobKed/beam/runs/928788738?check_suite_focus=true#step:7:99

**Comment by kotori2** [comment]
same here with Python 3.8.3 and protobuf 3.12.4

**Comment by robertwb** [comment]
I'm seeing this with protobuf==3.14.0 and Python 3.9.

**Comment by 0zero** [comment]
Hi, are there any updates on this... seeing this issue a lot with windows, python3.8+ and protobuf.

**Comment by Laurens-T** [comment]
I had the same issue after upgrading from python 3.7 to python 3.9. I was using protobuf==3.14.0 on Mac/Debian.
Updating protobuf to the latest version solved this issue for me.

**Comment by dsandbrink** [comment]
This problem still exists on Windows for Python 3.8 and protobuf 3.17.3

**Comment by dsandbrink** [comment]
It seems that for Python 2.7, 3.5, 3.6 and 3.7 protobuf is build with the C++ extension and has special wheels for Windows on the PyPI server, e.g. [protobuf-3.17.3-cp37-cp37m-win_amd64.whl](https://files.pythonhosted.org/packages/fe/b6/0b5fedc572c8771aa4f4916f81ef404203bafbd7461e859c3338316ec016/protobuf-3.17.3-cp37-cp37m-win_amd64.whl).

However starting with Python 3.8 the Windows wheels are no longer available, so the installation defaults back to the general wheel [protobuf-3.17.3-py2.py3-none-any.whl](https://files.pythonhosted.org/packages/d5/e0/20ba06eb42155cdb4c741e5caf9946e4569e26d71165abaecada18c58603/protobuf-3.17.3-py2.py3-none-any.whl), which does not contain the extension.

**Comment by anandolee** [comment]
The windows VM we are using haven't install python 3.8/3.9. Just merged #8757 to install them. Will see if we can push the artifacts to 3.17.3 or need a new release version

**Comment by anandolee** [comment]
Update: python 3.8/3.9 for windows have released for 3.17.3.
https://pypi.org/project/protobuf/3.17.3/#files

**Comment by JimPlayboy** [comment]
I came up with the same problem with protobuf 3.20.3. Reinstall protobuf with a lower version is useful for me. In my case, it is 3.19.6 which is the minimum version required by tensorboard 2.12.2.

**Comment by emmanuelajaero** [comment]
Same for I downgraded protobuf
`pip install protobuf==3.19.6`

**Comment by astrojuanlu** [comment]
Experiencing this error with all versions of protobuf, macOS arm64

**Comment by leonardo-deoliveirasaldanha-oxb** [comment]
> Experiencing this error with all versions of protobuf, macOS arm64

Me too!

**Comment by przna** [comment]
Experiencing this issue with mac m2

**Comment by roei3000b** [comment]
Me too

**Comment by toransahu** [comment]
Me too with mac m1
