### ISSUE TITLE
MessageToJsonString() serializes integer type map-values as strings

### ISSUE THREAD

**Issue by oschaaf** [protocolbuffers/protobuf#7769]
**Describe the problem you are trying to solve.**

Consider a map defined as:

```proto3
 map<string, uint64> RetCodes = 11;
```

`MessageToJsonString()` will output:

```json
{
  "200": "49988"
}
```

**Describe the solution you'd like**

`MessageToJsonString()` will instead output:

```json
{
  "200": 49988
}
```

As the map value is int typed, and can be serialised as such.

**Describe alternatives you've considered**

Consuming it as is-is possible, but may require extra handling when no schema is used
(e.g. explicitly convert to an int post deserialize)

**Additional context**
https://github.com/envoyproxy/nighthawk/issues/422

**Comment by acozzette** [comment]
I haven't looked closely at this code, but I suspect the motivation might have to do with the fact that JSON numbers are floating-point doubles, so not every uint64 can be represented exactly as JSON, unless it's formatted as a string.

**Comment by oschaaf** [comment]
@acozzette  Thanks for the context, reading up on the internets about json and integer values, I think that suspicion sense. 
So the string serialisation then seems like the sane default. But sometimes the consuming side might be able to take huge
values well, in which case an option to tweak how (u)int64 values are send to the output could be convenient (similar to, or possibly overlapping with `always_print_enums_as_ints`?)

**Comment by keithmattix** [comment]
This seems to be the most relevant issue, so I'll leave my comment here. The protobuf JSON serialization behavior of converting `u/int64` values to strings is, in my opinion, a leak of the behavior of 1 particular language that has nontrivial consequences for other protobuf supported languages. I have a [change request](https://go-review.googlesource.com/c/protobuf/+/288353) open to support an `EmitInt64Unquoted` option for the Go library, and I'd like to request for that feature to be standard in JSON serializers across all officially-supported protobuf languages.

**Comment by deannagarcia** [comment]
Closing this due to Adam's comment above and the comments on the change request in the Go library.
