### ISSUE TITLE
Duplicate symbols with Unity (Jumbo) builds

### ISSUE THREAD

**Issue by greenkalx** [protocolbuffers/protobuf#7770]
Hello, 

We have multiple projects in Visual Studio that compile with 'protoc.exe' from .proto files to .h and .cc.

When compiling with Unity (Jumbo) builds,
is there a recommended way to work with the duplicate symbols (One Definition Rule) that collide when compiling the merged .cc files?

The errors that are produced:
```
1>C:\app\ProtoBuf\generated\Pelican.pb.cc(284,65): error C2374: 'schemas': redefinition; multiple initialization
1>C:\app\ProtoBuf\generated\Pelican.Ipc.pb.cc(393): message : see declaration of 'schemas'
1>C:\app\ProtoBuf\generated\Pelican.pb.cc(295,55): error C2374: 'file_default_instances': redefinition; multiple initialization
1>C:\app\ProtoBuf\generated\Pelican.Ipc.pb.cc(409): message : see declaration of 'file_default_instances'
```

References:
https://onqtam.com/programming/2019-12-20-pch-unity-cmake-3-16/
https://onqtam.com/programming/2018-07-07-unity-builds/
https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html
https://devblogs.microsoft.com/cppblog/support-for-unity-jumbo-files-in-visual-studio-2017-15-8-experimental/

Running v3.9.1:
c:\>C:\protobuf-compiler\bin\protoc.exe --version
libprotoc 3.9.1

Regards

**Comment by acozzette** [comment]
So far we have not made any attempt to make protobuf generated code compatible with unity builds. I think you might need to use a CMake option such as `SKIP_UNITY_BUILD_INCLUSION` to exclude protobuf generated code from being compiled this way.

**Comment by greenkalx** [comment]
Thanks for the quick reply.
Can I make this a feature request? I would think a lot of teams would benefit from it.

Meanwhile, I can exclude our protobuf projects from unity builds, yes.

The Visual Studio unity builds allow for exclude at the project level, not sure if cmake excludes only at the file level. Looks like SKIP_UNITY_BUILD_INCLUSION is file level only.

**Comment by acozzette** [comment]
This looks like a C++ issue rather than C# anyway. Sorry but I don't think we have time to prioritize this feature. Actually I would guess that most builds would be faster by compiling protobuf generated code separately anyway, since presumably C++ developers spend much more time editing C++ code than .proto files. If you included pb.cc files in a unity build then you would have to keep recompiling that code even when there are no changes in the .proto files.

**Comment by mkkim1129** [comment]
This is how I fixed it.
https://github.com/mkkim1129/protobuf/commit/03526cdca5695bb885d23fd3808255e17b7d2e49

**Comment by pps83** [comment]
> So far we have not made any attempt to make protobuf generated code compatible with unity builds. I think you might need to use a CMake option such as `SKIP_UNITY_BUILD_INCLUSION` to exclude protobuf generated code from being compiled this way.

FYI, I had the same issues, these are the fixes I made to make it work:
 - fix global var names ([schemas](https://github.com/protocolbuffers/protobuf/pull/25554), [_static_init](https://github.com/protocolbuffers/protobuf/pull/25578), [file_default_instances](https://github.com/protocolbuffers/protobuf/pull/25579))
 -  [guard for PROTOBUF_PRAGMA_INIT_SEG](https://github.com/protocolbuffers/protobuf/pull/25633)
