### ISSUE TITLE
optional serialize error in 4.0.0-RC2

### ISSUE THREAD

**Issue by imsoul** [protocolbuffers/protobuf#7784]
Version: 4.0.0-RC2.
Language: PHP
System: Linux

composer package: 

`composer require google/protobuf 4.0.0-RC2`

example:

```
message PRoom{
  sint64 roomid = 1;
  optional sint64 uid = 2;
  string title = 3;
  optional sint32 styleid = 4;
  optional sint32 level = 5;
}
```

```
$room = [
            'roomid'=>1,
            'uid'=>1000,
            'title'=>'101',
            'style'=>1,
            'level'=>1
        ];
$protoRoom = new PRoom($room);
var_dump($protoRoom->serializeToJsonString());

//output:  {"roomid":"1","title":"101"}

```

The fields with optional had gone away.
But when I use the PECL package, it's OK.

**Comment by TeBoring** [comment]
https://github.com/TeBoring/protobuf/commit/5dfaf1de6bf7956dfa2ce6e5728063e295e70b64#diff-e1bfd762321e409cee4ac0b6e841963c

I tested with php 7.4. The output is "{"roomid":"1","uid":"1000","title":"101","styleid":1,"level":1}"

**Comment by TeBoring** [comment]
When running protoc, did you add ```--experimental_allow_proto3_optional```

**Comment by TeBoring** [comment]
Can you also show me how do you generate code for your proto?

**Comment by TeBoring** [comment]
Let me know how to reproduce the error.
