### ISSUE TITLE
protoc --go_out=plugins=grpc,mode=server:. mode/echo.proto  not work

### ISSUE THREAD

**Issue by iweixubin** [protocolbuffers/protobuf#7785]
Go  is server side, i don't want gen client code
protoc --go_out=plugins=grpc,**mode=server**:. mode/echo.proto

C# is client side, i don't want gen server code
protoc  --plugin=protoc-gen-grpc=grpc_csharp_plugin.exe  **--grpc_opt=no_server**

**Comment by acozzette** [comment]
Sorry but we are not directly involved with gRPC, so for this issue you may want to ask the gRPC maintainers for Go and C#.
