### ISSUE TITLE
Linking error with protobuf on windows

### ISSUE THREAD

**Issue by NavaniSrivastava** [protocolbuffers/protobuf#7787]
**What version of protobuf and what language are you using?**
Version: 3.12.4
Language: C++

**What operating system and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Microsoft Visual Studio 2019

**What did you do?**
1. Configured protobuf using "cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -Dprotobuf_WITH_ZLIB=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -DCMAKE_INSTALL_PREFIX=../../../../install ../.."
2. Compiled solution in Microsoft Visual Studio 2019 for x64 Release Version
3. Created .cc and .h file for .proto file using generated protoc binary
4. Added .cc, .h and libprotobuf.lib, libprotoc.lib and libprotobuf.lib to my Qt project.
5. Compiled the code. It gives linking error saying "qtmain.lib(qtmain_win.obj):- 1: error: LNK2019: unresolved external symbol main referenced in function WinMain". On removing compilation of .cc, .h and all protobuf libraries, build works fine. We need to disable entry point for these libraries.

**What did you expect to see**
Libraries should not have entry point

**What did you see instead?**
Application received winmain from protbuf
qtmain.lib(qtmain_win.obj):- 1: error: LNK2019: unresolved external symbol main referenced in function WinMain
win32-build\bin\release\Test_app.exe:- 1: error: LNK1120: 1 unresolved externals

**Anything else we should know about your project / environment**
I am including protobuf in application built on Qt 5.15.0 version. On building the same version of protobuf for linux, everything works fine for my application. Issue comes while I use it in windows.

**Comment by acozzette** [comment]
I'm not sure if this is related, but it shouldn't be necessary to link against libprotoc. The error makes it sound like the main() function is missing; does that explain the problem?

**Comment by NavaniSrivastava** [comment]
Yes, actually linking libprotoc is not necessary. Linking only libprotobuf.lib should work. I am doubtful about main function issue. If I remove protobuf library linking and usage, application works fine.  This makes me to doubt protobuf library.

Any link from where I can download protobuf library will be helpful.

**Comment by NavaniSrivastava** [comment]
> I'm not sure if this is related, but it shouldn't be necessary to link against libprotoc. The error makes it sound like the main() function is missing; does that explain the problem?

Yes, actually linking libprotoc is not necessary. Linking only libprotobuf.lib should work. I am doubtful about main function issue. If I remove protobuf library linking and usage, application works fine. This makes me to doubt protobuf library.

Any link from where I can download protobuf library will be helpful.

**Comment by teramototoya** [comment]
@NavaniSrivastava
How to resolve this issue?

**Comment by NavaniSrivastava** [comment]
> @NavaniSrivastava
> How to resolve this issue?

@teramototoya  Are you using Qt? I have done static linking and it worked. I used following command to build the package -
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=../../../../install ../..
