### ISSUE TITLE
lack of specification for serializating NaN and infinity for google.protobuf.Value.number_value

### ISSUE THREAD

**Issue by cybrcodr** [protocolbuffers/protobuf#7796]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Go (probably other ones too)

I think the following issue https://github.com/golang/protobuf/issues/1182 is best addressed here first.

The [developers guide](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value) mentions that the JSON representation for Value.number_value "Represents a double value."  The [guide](https://developers.google.com/protocol-buffers/docs/proto3#json) also mentions for "float, double" --

"JSON value will be a number or one of the special string values "NaN", "Infinity", and "-Infinity". Either numbers or strings are accepted. Exponent notation is also accepted."

Both the C++ and the Go implementations serialize these values with those special string values.  However, this presents a flaw in round-trip serialization.  Both C++ and Go implementations deserialize the JSON values into google.protobuf.Value.string_value as those are JSON strings.

Given the ambiguity, I think there needs to be better clarification for this and/or treat serialization of these special values as an error for google.protobuf.Value.number_value as proposed by @dsnet .

**Comment by TeBoring** [comment]
I think this is unavoidable because "NaN" can also mean a real string. We have no way to tell whether it means a string or a double. Could you use DoubleValue instead?

**Comment by dsnet** [comment]
This issue is not so much about what users can do instead, but what is supposed to be correct serialization behavior.

**Comment by cybrcodr** [comment]
> I think this is unavoidable because "NaN" can also mean a real string. We have no way to tell whether it means a string or a double.

Precisely, and hence treating NaN and infinity as an error during serialization will ensure that Value.number_value can round-trip properly if it can only contain a real number.

**Comment by TeBoring** [comment]
Doc has been updated: https://developers.google.com/protocol-buffers/docs/proto3#json
