### ISSUE TITLE
Add Lua file generation function

### ISSUE THREAD

**Issue by 1050229** [protocolbuffers/protobuf#7798]
protoc_release.exe --lua_out=./ game.proto

This does not generate Lua protocol files

What should I do?

**Comment by acozzette** [comment]
Our team does not maintain a protobuf implementation for Lua, but if you need Lua support you can try one of the third-party implementations listed [here](https://github.com/protocolbuffers/protobuf/blob/master/docs/third_party.md).

**Comment by 1050229** [comment]
All three Lua plug-ins are plug-ins from 8 years ago and 10 years ago

Protobuf 3.0 version is not supported

Please maintain Lua's protobuf implementation!

**Comment by 1050229** [comment]
> 我们的团队并未维护Lua的protobuf实现，但是如果您需要Lua支持，则可以尝试[此处](https://github.com/protocolbuffers/protobuf/blob/master/docs/third_party.md)列出的第三方实现之一。

All three Lua plug-ins are plug-ins from 8 years ago and 10 years ago

Protobuf 3.0 version is not supported

Please maintain Lua's protobuf implementation!

**Comment by 1050229** [comment]
> 我们的团队并未维护Lua的protobuf实现，但是如果您需要Lua支持，则可以尝试[此处](https://github.com/protocolbuffers/protobuf/blob/master/docs/third_party.md)列出的第三方实现之一。

All three Lua plug-ins are plug-ins from 8 years ago and 10 years ago

Protobuf 3.0 version is not supported
Lua5.4 is not supported

Please maintain Lua's protobuf implementation!
