### ISSUE TITLE
Protobuf uses legacy go package name

### ISSUE THREAD

**Issue by pkpfr** [protocolbuffers/protobuf#7807]
**What version of protobuf and what language are you using?**
Version: 3.12.4
Language: Go

**What operating system (Linux, Windows, ...) and version?**
All

**What runtime / compiler are you using (e.g., python version or gcc version)**
go 1.14.6

**What did you do?**
The GitHub project github.com/golang/protobuf states that it has been superseded by google.golang.org/protobuf but protobuf is still uses the old go package name.
```
syntax = "proto3";

package google.protobuf;

option csharp_namespace = "Google.Protobuf.WellKnownTypes";
option cc_enable_arenas = true;
option go_package = "github.com/golang/protobuf/ptypes/timestamppb";
option java_package = "com.google.protobuf";
option java_outer_classname = "TimestampProto";
option java_multiple_files = true;
option objc_class_prefix = "GPB";
```

**What did you expect to see**
```
option go_package = "google.golang.org/protobuf/types/known/timestamp";
```

**Comment by TeBoring** [comment]
Do you mind send this issue to https://github.com/golang/protobuf instead?
