### ISSUE TITLE
bundled_php.c is missing.

### ISSUE THREAD

**Issue by walliammeng** [protocolbuffers/protobuf#7816]
master/v3.13.0
PHP

missing file. Had you forgot to upload bundled_php.c into github?

![image](https://user-images.githubusercontent.com/65137233/90341522-d3864480-e032-11ea-90bf-35521a865685.png)
![image](https://user-images.githubusercontent.com/65137233/90341524-d8e38f00-e032-11ea-9e1c-b856b674c9bf.png)

**Comment by TeBoring** [comment]
If you use the source code from github directly, you need to generated the bundled_php.cc by your own: https://github.com/protocolbuffers/protobuf/blob/master/php/tests/compile_extension.sh#L18
