### ISSUE TITLE
[C++] Allow serialization to *any* stream using type traits/templates

### ISSUE THREAD

**Issue by darkdragon-001** [protocolbuffers/protobuf#7818]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
Directly serialize to custom classes not inheriting from `std::ostream` instead of going the detour over creating a string.

Specifically, I want to serialize directly to ZeroMQ via [`zmqpp::message`](https://github.com/zeromq/zmqpp/blob/85ae96020f2376c53d2176e04e88e8e51021b748/src/zmqpp/message.hpp#L260-L277).

**Describe the solution you'd like**
Probably it would be best to just use the `operator<<()` in combination with a template.
```
template <class T>
void SerializeToStream(T& stream) {
    stream << "serialized content";
}
```

**Describe alternatives you've considered**
Converting to string and then composing ZeroMQ messages.

**Additional context**

**Comment by acozzette** [comment]
I think the best way to do this efficiently is to provide your own implementation of ZeroCopyOutputStream. That will let you output the serialized data however you want, without needing to create a temporary string.
