### ISSUE TITLE
Please ask the owner of this code generator to support proto3 optional.--dart_out: 

### ISSUE THREAD

**Issue by girirajthara** [protocolbuffers/protobuf#7829]
**What language does this apply to?**
 proto3?
If it's about generated code change, what programming language?
dart

**Describe the problem you are trying to solve.**
 --experimental_allow_proto3_optional in dart

**Describe the solution you'd like**
  All other languages have it. It would be great as we want it in dart

**Comment by acozzette** [comment]
Sorry but our team does not maintain Dart protobuf. I see that you filed an [issue](https://github.com/dart-lang/protobuf/issues/396) with the Dart protobuf maintainers and I think they are the right people to work on this.
