### ISSUE TITLE
How can I generate java mutable message bean.

### ISSUE THREAD

**Issue by huhuang03** [protocolbuffers/protobuf#7833]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
proto2

If it's about generated code change, what programming language?

java

**Describe the problem you are trying to solve.**
I have an old android project, which use the java-nano generate, which generate filed modifiable bean. But now java-nano is deprecated. I upgrade t use java-lite, which can only generate the immutable bean. But in the old android project. The api designed used many bean field modify in-place feature.

**Describe the solution you'd like**
Can I generate the java Message bean as mutable?

**Comment by TeBoring** [comment]
@dlj-NaN I remember we haven't released our new java-lite.
AFAIK, java's mutable API is the builder.

**Comment by huhuang03** [comment]
Ok, thanks for your reply, I will post some example code later.
