### ISSUE TITLE
Type wrappers (newtypes) encoding optimisation

### ISSUE THREAD

**Issue by tim2CF** [protocolbuffers/protobuf#7838]
Protobuf is binary format, and in general, protobuf schema is segregated from runtime data. This means information about types and fields don't exist in encoded messages (opposite to JSON). We completely rely on decoder and assume it knows schema and can figure out how to decode given bytes. Let's say we have 2 messages

```protobuf
message Date {
  uint32 iso_days = 1;
}

message DateWrapper {
  Date date = 1;
}
```

From my point of view, encoded representation of them should be completely the same (uint32) because they both have only one field, and there are no alternative ways how to decode the value - meaningful part is always just uint32, all information about types is coming from the schema which is not a part of encoded message. But at the same time, for some reason encoded representation contains some extra bytes which seems for me completely redundant (because of reasons I described before like segregated schema). Example

```elixir
iex> d = Date
iex> dw = DateWrapper
iex> d.new(iso_days: 1) |> d.encode
<<8, 1>>
iex> dw.new(date: d.new(iso_days: 1)) |> dw.encode
<<10, 2, 8, 1>>
```

Can we optimise encoding of these type wrappers aka newtypes?

**Comment by elharo** [comment]
no. The wire format can't change in this way and must remain compatible. If we had a green field, the answer might be different, but hindsight's 20/20.
