### ISSUE TITLE
lua version needed

### ISSUE THREAD

**Issue by zhycheng** [protocolbuffers/protobuf#7841]
lua is ofen used in games,so we can hot update.so it is of great value to develop a lua version protobuf.

**Comment by perezd** [comment]
Have you seen upb's Lua bindings? Perhaps this would be useful: 
https://github.com/protocolbuffers/upb/tree/master/upb/bindings/lua

**Comment by zhycheng** [comment]
thanks,the binding way was not uesed very often,i'd search others,thanks again
