### ISSUE TITLE
Allow ByteString to implement Comparable

### ISSUE THREAD

**Issue by belugabehr** [protocolbuffers/protobuf#7842]
**What language does this apply to?**

If it's about generated code change, what programming language? Java

**Describe the problem you are trying to solve.**

Use Guava Range/TreeRangeMap with Proto ByteString

**Describe the solution you'd like**

Make ByteString implement Java Comparable.  The natural sorted order should be using the already provided unsignedLexicographicalComparator.

**Describe alternatives you've considered**

Wrapping ByteString in another object, having Guava Range accept a Comparator,....

```
ConcurrentSkipListMap<>(UnsignedByteBufComparator.INSTANCE)
```

**Comment by elharo** [comment]
Seems reasonable. This would require a Tier 2 review.
