### ISSUE TITLE
Protobuf to JSON: default values not serialized for oneof

### ISSUE THREAD

**Issue by lucaghera** [protocolbuffers/protobuf#7843]
**What version of protobuf and what language are you using?**

I'm using the version coming with Ubuntu 18.04
Version: 3.0.0 (GOOGLE_PROTOBUF_VERSION says `3000000`)
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux, Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**What did you do?**

1. I created a protobuf message that contains another message, both as part of a oneof and as standalone field
2. I write the message to JSON using the function `google::protobuf::util::MessageToJsonString`. I pass to the function `google::protobuf::util::JsonPrintOptions` with `add_whitespace` and `always_print_primitive_fields` set to true and 
3. In the output JSON string, fields with default values are serialized for the standalone variable, but not for the oneof.

Proto message:
```
message MyMessage {
    int32 value = 1;
}
message MyCompositeMessage{
    
    MyMessage standaloneVariable = 1;

    oneof oneOfVariable{
        MyMessage myMessageOneOfVariable = 2;
    }

}
```

C++ code:
```
google::protobuf::util::JsonPrintOptions printOptions;
printOptions.add_whitespace                = true;
printOptions.always_print_primitive_fields = true;

MyCompositeMessage msg;
msg.mutable_standalonevariable()->set_value(0);
msg.mutable_mymessageoneofvariable()->set_value(0);

std::string output;
const auto status = google::protobuf::util::MessageToJsonString(msg, &output, printOptions);

std::cout << output << std::endl;
```

**What did you expect to see**

I would expect the default value to be serialized in both cases.

```
{
 "standaloneVariable": {
  "value": 0
 },
 "myMessageOneOfVariable": {
  "value": 0
 }
}
```

**What did you see instead?**

```
{
 "standaloneVariable": {
  "value": 0
 },
 "myMessageOneOfVariable": {}
}
```

**Anything else we should know about your project / environment**

I've seen that for python this is expected behavior (https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py) however the C++ documentation (https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions.always_print_primitive_fields.details) does not state it explicitly.

**Comment by gerhard-pretorius** [comment]
This works as expected when using v3.13.0 (or the master branch).
Have you tried building the latest version from source ?

**Comment by lucaghera** [comment]
@gerhard-pretorius We tested with the version coming with our new dependencies release (running protoc 3.6.1) and the problem is fixed.

**Comment by haberman** [comment]
Closing as fixed.
