### ISSUE TITLE
PHP Package Incorrect in Packagist

### ISSUE THREAD

**Issue by jblacker** [protocolbuffers/protobuf#7846]
This issue might belong in the [protocolbuffers/protobuf-php](https://github.com/protocolbuffers/protobuf-php)  repo, but the README in that repo directs devs here.

I have a PHP application that uses composer to handle dependencies.  That project has a dependency on `grpg/grpg` and takes a dependency of this project as `google/protobuf-php:3.4.1`

For some reason when updating OTHER packages unrelated to gprg or protobuf the composer.lock file is being updated with an invalid reference hash.  The existing composer.lock file has the following:
```json
            "name": "google/protobuf",
            "version": "v3.4.1",
            "source": {
                "type": "git",
                "url": "https://github.com/protocolbuffers/protobuf-php.git",
                "reference": "c9c1bf278a77b66bc44a9478670e5d8c62ff861a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/c9c1bf278a77b66bc44a9478670e5d8c62ff861a",
                "reference": "c9c1bf278a77b66bc44a9478670e5d8c62ff861a",
                "shasum": ""
            },
            "require": {
                "php": ">=5.5.0"
            },
            "require-dev": {
                "phpunit/phpunit": ">=4.8.0"
            },
            "suggest": {
                "ext-bcmath": "Need to support JSON deserialization"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Google\\Protobuf\\": "src/Google/Protobuf",
                    "GPBMetadata\\Google\\Protobuf\\": "src/GPBMetadata/Google/Protobuf"
                }
```

The hash `c9c1bf278a77b66bc44a9478670e5d8c62ff861a` corresponds correctly to the commit in the [protocolbuffers/protobuf-php](https://github.com/protocolbuffers/protobuf-php) repository tagged with v3.4.1.  Upon running any updates composer will incorrectly update the hash to `b04e5cba356212e4e8c66c61bbe0c3a20537c5b9`.  This is not a valid commit hash within the protobuf-php repo and causes composer to error out.

The Packagist URL:  https://packagist.org/packages/google/protobuf#v3.4.1 correctly displays the valid hash.  However, when running composer via `php composer.phar update` it called this URL http://repo.packagist.org/p/provider-2020-07$9450ac5f0d5b2895bbc63b9b539be97d43a791687a60729c48516d9bc2d33c1f.json which shows the invalid hash in that JSON file and incorrectly updates the lock file causing builds to fail.

**Comment by haberman** [comment]
What is the correct way of solving this problem? Could you possibly submit a PR with a fix?

**Comment by jblacker** [comment]
@haberman Unfortunately I have no idea how to fix this.  I'm not a PHP expert, but I'm working in a legacy project where this came up and I've been trying to dig down into how this is happening in the first place.  I was trying to dig into both the composer & the packagist code bases to find out how those JSON files are generated that composer pulls to get the hash values / pointers to the artifacts, but have not figured that out yet.

Whoever has the account access to submit the packages to packagist is probably the person that can fix this.  Most likely it's either @TeBoring or @jkolhe since those are the only two contributors to the [protocolbuffers/protobuf-php](https://github.com/protocolbuffers/protobuf-php) repo.

**Comment by TeBoring** [comment]
Is it possible to update to newer version of protobuf?

**Comment by jblacker** [comment]
@TeBoring Unfortunately not easily since it's a huge enterprise application: the PHP portion is our legacy monolith with all the microservices (written in Java, not in PHP) are using a version that we know is compatible with the v3.4.1 of the PHP implementation.  I can try upgrading it to the next version, but it'll require a ton of regression testing so I'm hoping that could be avoided.

**Comment by TeBoring** [comment]
Our protobuf is fully backward compatible. I think as long as none of your
dependence depends on a fixed version of protobuf, you should be able to do
that.
