### ISSUE TITLE
Generate incorrect source files with cross referenced types

### ISSUE THREAD

**Issue by wasphin** [protocolbuffers/protobuf#7849]
**What version of protobuf and what language are you using?**
Version: v3.5.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux RHEL8

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc (GCC) 8.3.1 20191121

**What did you do?**
``foobar.proto`` with content:
```protobuf
message Foo {
    optional Bar bar = 1;
}

message Bar {
    optional Foo foo = 1;
}
```

**What did you expect to see**
```c++
void InitDefaultsFooImpl();
void InitDefaultsFoo();
void InitDefaultsBarImpl();
void InitDefaultsBar();
```

**What did you see instead?**
```c++
void InitDefaultsBarImpl();
void InitDefaultsBar();
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Thank you for the bug report but I believe this is actually working as intended. We generate one `InitDefaults()` function per strongly-connected component in the message graph, so two mutually dependent messages will share an `InitDefaults()` function. Note: these functions are implementation details only and shouldn't be called directly.

**Comment by wasphin** [comment]
@acozzette thanks for the reply, I actually don't care much about the implementation details, but these functions are required by the service. If the ``Foo`` is part of a ``rpc`` argument, it can't compile:
> error: ‘InitDefaultsFoo’ is not a member of ‘protobuf_foobar_2eproto’

**Comment by acozzette** [comment]
Is the service defined in a separate .proto file? I think you might just need to rebuild the generated code for the service.

**Comment by wasphin** [comment]
@acozzette thank you very much, you are right, the separate service .proto file has not been updated. It works now. Thank you so much.
