### ISSUE TITLE
add protoc command used to generate proto along with versions of plugins/protoc toolchain used

### ISSUE THREAD

**Issue by daodennis** [protocolbuffers/protobuf#7851]
Hi,

I'm trying to generate protos (I'm using Gorm v1  and grpc-gateway and, against my own will the specter of, gogopro) and it would be useful to be able to deconstruct what versions of plugins/code were used to generate the protobufs. Right now I only see which plugin was used*:

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

It seems possible to generate protobufs with different includes and command line options where compilation may work but still fail at runtime. for instance using `--go-out` and `--grpc-gateway-out` vs `--gogo-out` and `--grpc-gateway-out`
It may also help understand what I need as a build-time or tooling dependency vs a run-time dependency which I am not sure I understand completely understand how to determine one vs the other.

* I see that some newer versions of protoc plugins add some version information, I don't believe it is as detailed as this request.

Thank you!

**Comment by daodennis** [comment]
I noticed that generated code has the plugins that are used like:
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0

However, iirc the intent of this particular bug is to add the command line used to generate the source.

**Comment by fowles** [comment]
This is a really great idea, we will look into adding it

**Comment by daodennis** [comment]
Any updates here?
