### ISSUE TITLE
can not create java file from .proto

### ISSUE THREAD

**Issue by xaidanwang** [protocolbuffers/protobuf#7859]
**What version of protobuf and what language are you using?**
Version: 3.13.0  ..
Language: Java
operating system: Windows 10

create file commandLine:
protoc.exe --jar_out=. addressbook.proto
--jar_out: protoc-gen-jar: Plugin failed with status code 1.

addressbook.proto

syntax = "proto3";
package tutorial;
option java_package = "com.example.tutorial";
option java_outer_classname = "AddressBookProtos";
message Person {
   string name = 1;
   int32 id = 2;
   string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
     string number = 1;
     PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;
}

message AddressBook {
  repeated Person people = 1;
}

**Comment by perezd** [comment]
https://developers.google.com/protocol-buffers/docs/reference/java-generated#invocation 
for the record, use `--java_out` not `--jar_out`
