### ISSUE TITLE
protobuf-test Failed: FAIL protobuf-test (exit status: 137)

### ISSUE THREAD

**Issue by snowday-everyday** [protocolbuffers/protobuf#7860]
[test-suite.log](https://github.com/protocolbuffers/protobuf/files/5145650/test-suite.log)
idk why does it failed :((

**Comment by dragon8609** [comment]
I got the same error,too.

**Comment by vpanichkin** [comment]
+1

**Comment by akjain2052** [comment]
Are you still seeing the failure in latest protobuf version v3.14.0 ? Please provide the details in which OS are you testing Windows/Linux, and what protobuf version are using ?

**Comment by moonlight2596** [comment]
I am definitely seeing this error.
`FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test`

` TOTAL: 6
 PASS:  5
 SKIP:  0
 XFAIL: 0
 FAIL:  1
 XPASS: 0
 ERROR: 0`

 I am also attaching my test-suite.log. My OS is Ubuntu 18.04 64 bits and my g++ version is 7.5.
[test-suite.log](https://github.com/protocolbuffers/protobuf/files/5786855/test-suite.log)
Please help.
(P.S. I am new so please forgive the formatting mistakes.)

**Comment by paleboot** [comment]
Encountered the same error on Ubuntu 20.04, Protobuf v3.14.0, and gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04). Looking at the test log I see lots of `[libprotobuf ERROR google/protobuf/descriptor.cc:3623]` lines. [test-suite.log](https://github.com/protocolbuffers/protobuf/files/5828218/test-suite.log) for more details. Thanks in advance for any help given!

**Comment by jonahcoding** [comment]
I also encountered the same error on Centos7.5, Protobuf v3.14.0, and the GCC version is 9.3.1.Ask for help, thanks!

**Comment by kubotaku1119** [comment]
I also encountered the same error on Docker build, Protobuf v3.14.0, but I finally passed that UnitTest(IoTest.LargeOutput) by up the resources limit for Docker.  Hope it helps you guys!

**Comment by Y2Kai** [comment]
I also encountered the same error on Ubuntu 18.04.5 LTS ，Virtualbox , 8g Ram ,  Protobuf v3.14.0, gcc version 7.5.0.
I don't know it mean what. Ask for help ,thanks;

**Comment by Y2Kai** [comment]
I also encountered the same error on Ubuntu 18.04.5 LTS ，Virtualbox , 8g Ram , Protobuf v3.14.0, gcc version 7.5.0.
I don't know it mean what. Ask for help ,thanks;
[test-suite.log](https://github.com/protocolbuffers/protobuf/files/5926692/test-suite.log)

**Comment by twright-4354** [comment]
Same for me when building within Docker; upping the resources resolved it - thanks kubotaku1119!

**Comment by mina-101** [comment]
same for me on Ubuntu 18.04 and Protobuf v3.15.4 
thanks for any help

**Comment by thaprau** [comment]
I got the same error on Ubuntu 20.04, running on a virtual machine. I increase the ram to 8gb and now it works! Hope this helps someone.

**Comment by thaprau** [comment]
Manage to install protobuf 3.15.7 on ubuntu 20.04 Lts

**Comment by pavanKulkarni2000** [comment]
> Same for me when building within Docker; upping the resources resolved it - thanks kubotaku1119!



> Same for me when building within Docker; upping the resources resolved it - thanks kubotaku1119!



> I also encountered the same error on Docker build, Protobuf v3.14.0, but I finally passed that UnitTest(IoTest.LargeOutput) by up the resources limit for Docker. Hope it helps you guys!

Can you please say what all resources has to be increased.

**Comment by thaprau** [comment]
@pavanKulkarni2000  Sry for late response. The resource I changed was only the ram

**Comment by kubotaku1119** [comment]
@pavanKulkarni2000 Sorry for late too. I increased CPU and RAM. Here is my settings for Docker. 
<img width="482" alt="スクリーンショット 2021-04-19 23 08 34" src="https://user-images.githubusercontent.com/4922634/115250349-6ea46080-a164-11eb-9dae-6e2bbaea3442.png">

**Comment by hammersmith-xie** [comment]
![image](https://user-images.githubusercontent.com/22334829/118090842-a5d0ff00-b3fc-11eb-8683-2f7b4f946a66.png)
@kubotaku1119 is right. When you execute 'make check', the maximum memory usage reaches 8.6g。

**Comment by songning4** [comment]
+1

**Comment by ItamarRocha** [comment]
I had the same issue, freed some memory and it worked fine.

**Comment by elharo** [comment]
proto tests do need non-trivial anounts of memory these days

**Comment by Nickrader** [comment]
If you open the test-suite.log in an editor and search for 'failed', it should take you right to the failing test.
```
[ RUN      ] IoTest.LargeOutput
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] IoTest.LargeOutput (66424 ms)
```
I have about 650 MB of free physical memory on my device.  It seems to just be the one test that uses more than that. 
42@42:/$ cat /proc/meminfo
MemTotal:        1912400 kB
MemFree:          652620 kB
MemAvailable:     629584 kB


```[----------] Global test environment tear-down
[==========] 2320 tests from 207 test suites ran. (182466 ms total)
[  PASSED  ] 2319 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IoTest.LargeOutput

 1 FAILED TEST
FAIL protobuf-test (exit status: 1)
```

**Comment by Plwy** [comment]
I had the same issue , i use ```free -h ``` check my cpu memory , only 4 G is aviliable, i close some application to free some memory ,```make check ``` again and it works fine.
