### ISSUE TITLE
Use SLF4j logger instead of java util logger

### ISSUE THREAD

**Issue by ashish198511** [protocolbuffers/protobuf#7862]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3? - No
If it's about generated code change, what programming language? - No

**Describe the problem you are trying to solve.**
Protobuf uses java util logger for logging. Java util logger doesn't do async logging and can cause performance issues in the code.
**Describe the solution you'd like**
Use SLF4J which abstracts the logging mechanism to be used

**Comment by elharo** [comment]
Google Java policy is to use java.util.logging and to minimize dependencies.
