### ISSUE TITLE
registry addition: protoc-gen-graphql

### ISSUE THREAD

**Issue by tmc** [protocolbuffers/protobuf#7866]
Can you add a reserved id for https://github.com/tmc/protoc-gen-graphql ?

**Comment by acozzette** [comment]
@tmc Would you mind sending me a pull request to update docs/options.md to assign your extension number? I can do it if you prefer not to sign the CLA, but it would be slightly easier if you could send the PR.

**Comment by tmc** [comment]
Wups! Missed this :)

**Comment by acozzette** [comment]
Oh, I assumed you didn't need this anymore but are you still interested in having an assigned extension number? If you're OK with signing the CLA then you can do that and just send a pull request.
