### ISSUE TITLE
C# How to get messages to implement IBufferMessage?

### ISSUE THREAD

**Issue by MaximGurschi** [protocolbuffers/protobuf#7870]
I've updated my .NET standard 2.1 project to reference the latest protobuf nuget package, and expected the following code to work:

myMessage.WriteTo(**Span**);

, however it does not work because myMessage does not implement **IBufferMessage**. What is the trick to get the generated message to implement the interface?

I'm currently referencing:
"Google.Protobuf" Version="3.13.0"
"Grpc.Tools" Version="2.31.0"

, is the issue that Grpc.Tools was not updated yet?

**Comment by JamesNK** [comment]
> , is the issue that Grpc.Tools was not updated yet?

Correct. 2.32.0-pre1 should come out soon which will support IBufferMessage.

**Comment by MaximGurschi** [comment]
Thanks, eagerly waiting the official release!
