### ISSUE TITLE
iPhone5 parseFromData:error: Crash

### ISSUE THREAD

**Issue by chengssir** [protocolbuffers/protobuf#7875]
1Protobuf0xa568GPBCodedInputStreamReadDouble (malformed)
2Protobuf0x348fb-[GPBMessage mergeFromCodedInputStream:extensionRegistry:] (malformed)
3Protobuf0xae29-[GPBCodedInputStream readMessage:extensionRegistry:] (malformed)
4Protobuf0x34a71-[GPBMessage mergeFromCodedInputStream:extensionRegistry:] (malformed)
5Protobuf0x34059-[GPBMessage mergeFromData:extensionRegistry:] (malformed)
6Protobuf0x31ba5-[GPBMessage initWithData:extensionRegistry:error:] (malformed)
7Protobuf0x34109+[GPBMessage parseFromData:extensionRegistry:error:] (malformed)
8Protobuf0x340df+[GPBMessage parseFromData:error:] (malformed)

**Comment by thomasvl** [comment]
There isn't enought data to go on here.

Are things crashing or simply returning an error? What version of the protobuf library are you using to generate and to link into your application?

Can you share any more information about your proto file definitions and the example input so we can see the specifics to figure out what's happening?

**Comment by thomasvl** [comment]
BTW - This could be an old bug that was fixed in #6678.  Please make sure you are using a recent version of the library to have that fix.

**Comment by perezd** [comment]
Closing this, re-open if it is still an issue.
