### ISSUE TITLE
Linking fails on armv6l due to missing libatomic

### ISSUE THREAD

**Issue by martinblech** [protocolbuffers/protobuf#7876]
Looks like there's been a regression on this issue somewhere between v3.11.4 and v3.12.2. I'm getting the same link error compiling "@com_google_protobuf//:protoc" v3.12.2 on a Raspberry Pi. v3.11.4 compiles just fine.

_Originally posted by @martinblech in https://github.com/protocolbuffers/protobuf/issues/5219#issuecomment-636399513_

**Comment by haberman** [comment]
Sorry this did not get a timely response. So much has changed about our build system that I'm going to close this now. If this still occurs with a CMake or Bazel build, please feel free to file a new issue.
