### ISSUE TITLE
Python: with the generate_py_protobufs extension installed, cannot find google.api_core on import

### ISSUE THREAD

**Issue by bobhancock** [protocolbuffers/protobuf#7877]
**What version of protobuf and what language are you using?**
Version: master/v3.13.0.
Language: Python
OS: Linux
Python 3.7.0 and 3.8.5
tl;dr
If you import google.protobuf or proto prior to google.api_core, the module is found and loaded..
If you import google.api_core before importing these two if you attempt to import google.api_core the module is not found.
Why isn’t google.api_core found with the PathFinder in sys.meta_path find it?
I can duplicate this on my desktop, on a fresh cloudtop, and on our kokoro-ubuntu machines.

```
rwh@rhw8:python_cpp_pyext$ source /tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/bin/activate
(cpp_pyext) rwh@rhw8:python_cpp_pyext$ python
Python 3.8.5 (default, Sep  5 2020, 16:13:02) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import google.api_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.api_core'
>>> sys.meta_path
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>]
>>> sys.path
['', '/usr/local/buildtools/current/sitecustomize', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python38.zip', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python3.8', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python3.8/lib-dynload', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/protobuf_distutils-1.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/setuptools-44.0.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/proto_plus-1.9.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/grpcio-1.32.0rc1-py3.8-linux-x86_64.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg']
>>> import google.protobuf
>>> sys.meta_path
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>, <pkg_resources.extern.VendorImporter object at 0x7ff1f5bfea00>, <pkg_resources._vendor.six._SixMetaPathImporter object at 0x7ff1f5b8d880>]
>>> sys.path
['', '/usr/local/buildtools/current/sitecustomize', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python38.zip', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python3.8', '/usr/local/google/home/rwh/.pyenv/versions/3.8.5/lib/python3.8/lib-dynload', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/protobuf_distutils-1.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/setuptools-44.0.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/proto_plus-1.9.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/grpcio-1.32.0rc1-py3.8-linux-x86_64.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg', '/tmp/cpp-pyext-O2Xfh0IBIS/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg']
>>> import google.api_core
>>> 
```

**Comment by dlj-NaN** [comment]
I'm having trouble reproducing the environment. It looks like this is pyenv and venv together, but I'm not able to construct an environment with an analogous `sys.path`.

Bob: Can you share the steps you followed to set up the environment? I have a suspicion, but I can't verify it without reproducing the semantics of your `sys.path`.

**Comment by bobhancock** [comment]
I removed pyenv from my system and ran the test with the default python3 with the same end result.

Python 3.8.5 (default, Jul 20 2020, 18:32:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import google.api_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.api_core'
>>> sys.path
['', '/usr/local/buildtools/current/sitecustomize', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/protobuf_distutils-1.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/proto_plus-1.9.1-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/grpcio-1.32.0-py3.8-linux-x86_64.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg']
>>> sys.meta_path
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>]
>>> 
>>> import google.protobuf
>>> sys.path
['', '/usr/local/buildtools/current/sitecustomize', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/protobuf_distutils-1.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/proto_plus-1.9.1-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/grpcio-1.32.0-py3.8-linux-x86_64.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg', '/tmp/cpp-pyext-uLYBj8n0Mt/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg']
>>> sys.meta_path
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>, <pkg_resources.extern.VendorImporter object at 0x7fb2f72f8370>, <pkg_resources._vendor.six._SixMetaPathImporter object at 0x7fb2f729c760>]
>>> import google.api_core
>>>

**Comment by dlj-NaN** [comment]
Bob provided me a reproducer script locally (it has some Google-internal details, so it's not attached here). The steps boiled down to this:

1.  Fetch sources from Git for these packages:
    * google-ads-python (internal fork of https://github.com/googleads/google-ads-python, which includes some patches Bob is working on)
    * googleads-python-lib (https://github.com/googleads/googleads-python-lib)
    * protobuf (https://github.com/protocolbuffers/protobuf)
2.  Create and activate a new Python venv
3.  Install googleads-python-lib using `pip install .` inside the checkout.
4.  Install the protobuf_distutils package from the protobuf checkout:
    ```
    cd path/to/protobuf
    cd python/protobuf_distutils
    python setup.py build
    python setup.py install
    ```
5.  Install google-ads-python from its checkout:
    ```
    cd path/to/google-ads-python
    python setup.py generate_py_protobufs
    python setup.py build
    python setup.py install
    ```
6.  Pin protobuf==3.13.0 with:
    ```
    python -m pip uninstall -y protobuf
    python -m pip install protobuf==3.13.0
    ```

The problem is that the pip-installed packages go into a native namespace package, while `setup.py` creates eggs that internally use `pkg_resources`-style packages. ([Details on different package types](https://packaging.python.org/guides/packaging-namespace-packages/))

So, for example, this is the directory tree (heavily edited for brevity) from a venv that has the import problem:

```
lib/python3.8/site-packages
├── (...snip...)
├── google
│   ├── auth
│   ├── oauth2
│   └── protobuf
├── googleads
├── googleads-25.0.0.dist-info
├── google_ads-6.0.0-py3.8.egg
│   ├── EGG-INFO
│   └── google
│       └── ads
├── google_api_core-1.22.2-py3.8.egg
│   ├── EGG-INFO
│   └── google
│       └── api_core
├── googleapis_common_protos-1.52.0-py3.8.egg
│   ├── EGG-INFO
│   └── google
│       ├── api
│       ├── logging
│       ├── longrunning
│       ├── rpc
│       └── type
├── google_auth-1.21.1.dist-info
├── google_auth_oauthlib
│   └── tool
├── google_auth_oauthlib-0.4.1.dist-info
├── grpcio-1.32.0-py3.8-linux-x86_64.egg
│   ├── EGG-INFO
│   └── grpc
├── protobuf-3.13.0.dist-info
├── (...snip...)
```

So, the fix is to change the google-ads-python installation step to use `pip install .` instead of `python setup.py install`. This ensures that all of the packages which share `namespace_packages = ["google"]` will all follow pip's convention.

Using `pip install .` for google-ads-python results in this directory tree (again, heavily edited for brevity):

```
lib/python3.8/site-packages
├── (...snip...)
├── google
│   ├── ads
│   ├── api
│   ├── api_core
│   ├── auth
│   ├── logging
│   ├── longrunning
│   ├── oauth2
│   ├── protobuf
│   ├── rpc
│   └── type
├── googleads
├── googleads-25.0.0.dist-info
├── google_ads-6.0.0.dist-info
├── google_api_core-1.22.2.dist-info
├── googleapis_common_protos-1.52.0.dist-info
├── google_auth-1.21.1.dist-info
├── google_auth_oauthlib
│   └── tool
├── google_auth_oauthlib-0.4.1.dist-info
├── grpc
│   ├── aio
│   ├── beta
│   ├── _cython
│   ├── experimental
│   └── framework
├── grpcio-1.32.0.dist-info
├── (...snip...)
├── protobuf-3.13.0.dist-info
├── (...snip...)
```

In this case, the only `google` directory is the native namespace package.

Notably, `python setup.py install` will still work for other packages, as long as they don't share the `google` namespace package.

Bob: I will send you a patch for your script.

**Comment by gpshead** [comment]
I've narrowed this down a bit.

```
$ python
Python 3.8.5 (default, Jul 20 2020, 18:32:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google
>>> import google.api_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.api_core'
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7fb8572f9790>, submodule_search_locations=_NamespacePath(['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google']))
>>> google.__path__
_NamespacePath(['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google'])
>>> google.__file__
>>> import pkg_resources
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fb856c47700>, origin='/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google/__init__.py', submodule_search_locations=['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google'])
>>> google.__path__
['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google']
>>> google.__file__
'/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google/__init__.py'
>>> import google.api_core
>>> 
```

if pkg_resources has not been imported, the `google` package doesn't appear to work for things outside of the installed google/ directory living in their own .egg subdirectories.

**Comment by gpshead** [comment]
ah, messages crossed (thanks github for not autorefreshing).  yes, David's analysis makes sense!

A key signature of this problem is the following (before applying David's fix) was looking at what happens to `google.__spec__` at various points in time:

BEFORE:

```
Python 3.8.5 (default, Jul 20 2020, 18:32:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f1fc7cd6790>, submodule_search_locations=_NamespacePath(['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google']))
>>> import google.protobuf
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f1fc7610610>, origin='/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google/__init__.py', submodule_search_locations=['/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_ads-6.0.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/googleapis_common_protos-1.52.0-py3.8.egg/google', '/tmp/cpp-pyext-kqrTGFEKOT/cpp_pyext/lib/python3.8/site-packages/google_api_core-1.22.2-py3.8.egg/google'])
```

Notice how the protobuf import changed the spec and loader for the google package?  (I believe this was indirectly done by google.protobuf's `import pkg_resources`).  that was wrong.  it should remain a namespace package.  similarly doing a `import pkg_resources` before `import google.api_core` was also a workaround while in this mixed install-type state.

AFTER David's fix:

`google.__spec__` remains the NamespacePackage after the `google.api_core` and/or `google.protobuf` imports in any order:

```
Python 3.8.5 (default, Jul 20 2020, 18:32:44)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f6658fb6790>, submodule_search_locations=_NamespacePath(['/tmp/cpp-pyext-SryIqv6SnS/cpp_pyext/lib/python3.8/site-packages/google']))
>>> import google.api_core
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f6658fb6790>, submodule_search_locations=_NamespacePath(['/tmp/cpp-pyext-SryIqv6SnS/cpp_pyext/lib/python3.8/site-packages/google']))
>>> import google.protobuf
>>> google.api_core
<module 'google.api_core' from '/tmp/cpp-pyext-SryIqv6SnS/cpp_pyext/lib/python3.8/site-packages/google/api_core/__init__.py'>
>>> google.__spec__
ModuleSpec(name='google', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f6658fb6790>, submodule_search_locations=_NamespacePath(['/tmp/cpp-pyext-SryIqv6SnS/cpp_pyext/lib/python3.8/site-packages/google']))
```

**Comment by dlj-NaN** [comment]
@gpshead : good sleuthing on the `pkg_resources` import... that's why _only_ importing `google.protobuf` will allow import of the egg packages. Neither `google.auth` nor `google.oauth2` do that dance, so:

```
Python 3.8.5 (default, Jul 20 2020, 18:32:44)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.auth
>>> import google.api_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.api_core'
>>> import google.ads
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.ads'
>>> import google.oauth2
>>> import google.api_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.api_core'
>>> import google.ads
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.ads'
>>> import google.protobuf
>>> import google.api_core
>>> import google.ads
```

**Comment by bobhancock** [comment]
Great explanation. I've made the change to our build process and verified that using pip to install the Ads client library works.
