### ISSUE TITLE
Pascal language support

### ISSUE THREAD

**Issue by number201724** [protocolbuffers/protobuf#7881]
**What language does this apply to?**
pascal language

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**
add pascal language support and generate

**Describe alternatives you've considered**

**Additional context**

**Comment by perezd** [comment]
Looks like there is an external solution for this:
https://github.com/lalexs75/protobuf-fpc

**Comment by perezd** [comment]
We don't have any plans to support pascal directly, but thank you for the suggestion. I hope that link above helps.
