### ISSUE TITLE
Protoc does not compile the file correctly

### ISSUE THREAD

**Issue by phillipweinstock** [protocolbuffers/protobuf#7884]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
The one that comes with Grpc.ASP.NET
**What did you do?**
Compile the following proto file 
`syntax = "proto3";

// The sales service definition.
service Sale {
  // Sends a sales insertion
  rpc AddSale (AddSaleRequest) returns (ErrorCodeReply);
}
//The Item to be added to the sale, item_id is a foreign key
//item_id is also a foreign key for the actual item we are trying to get
message ItemDetail {
  uint32 quantity_id = 1;
  uint32 item_id = 2;
}

// The request message containing the Item Ids to be added
message AddSaleRequest {
  repeated  ItemDetail item_details = 1;
  float total_billed = 2;
  
}

// Error Code 
message ErrorCodeReply {
   bool error_code = 1;
}

`
2. Click on 'build'

3. The generated code file has read only properties on the repeated field
`using Google.Protobuf;
using Google.Protobuf.Collections;
using Grpc.Net.Client;
using PHP_SRePS_Backend;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PHP_SRePS_Frontend
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            _ = RpcTest();
        }

        //Rpc test example
        private async Task RpcTest()
        {
            var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new Sale.SaleClient(channel);
            var inputParse = new RepeatedField<ItemDetail>();;
            inputParse.Add(new ItemDetail() {ItemId =1, QuantityId =2 });
            var inputdata = new AddSaleRequest()
            {
                ItemDetails = inputParse,
                TotalBilled = 1
            
            };
            
     
            await Task<ErrorCodeReply>.FromResult(client.AddSale(inputdata));

          
        }
    }
}
`

![image](https://user-images.githubusercontent.com/7949635/92858751-c7c34d80-f439-11ea-87ce-ad4594abaaa1.png)
![image](https://user-images.githubusercontent.com/7949635/92858802-d873c380-f439-11ea-89d9-dc095fa34fbd.png)

**Comment by MaximGurschi** [comment]
That has always been the case i believe. The idea is that you should populate the already allocated repeated field directly. You should be able to observe a line in the generated message similar to: 

itemDetails_ = new pbc::RepeatedField<...>()

**Comment by perezd** [comment]
This behavior is correct and documented: https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#repeated
