### ISSUE TITLE
C# MergeFrom ReadOnlySpan with no allocations

### ISSUE THREAD

**Issue by MaximGurschi** [protocolbuffers/protobuf#7885]
Hi,

With the latest release of Grpc.Tools, we are now able to execute code that writes the serialized message directly to Span<byte> without incurring allocations. This is based on IBufferMessage. Thank you for that release!

My questions is what is the way to achieve the reverse process? Specifically without allocating a CodedInputStream or any other heap based objects. Is there (or are the plans for) an API that can help us achieve the following:
1. Given an instantiated (new allocated) Message - M,
2. Execute M.MergeFrom(ReadOnlySpan)
3. The above to complete without allocating heap memory (for things like CodedInputStream, etc.)

I have been using a custom solution to achieve the above steps but it involves subclassing **Stream** and a buffer copy to a preallocated buffer. If there were to be a native solution to achieve the equivalent of IMessage.MergeFrom(ReadOnlySpan) without additional allocation then that would help get rid of the workaround code.

**Comment by MaximGurschi** [comment]
The issue with my solution is that the CodedInputStream eventually hits the state.sizelimit, so i have to allocate a new one.

A native solution that does M.MergeFrom(ReadOnlySpan) without allocating any CodedInputStream would be great.

**Comment by jtattermusch** [comment]
Currently there is 

`YourMessage.Parser.ParseFrom(ReadOnlySequence<byte>)` which allows you to parse without needing a CodedInputStream (and getting a ReadOnlySequence without requiring allocations is relatively easy). 
https://github.com/protocolbuffers/protobuf/blob/022078d3ee642816688228e9434775f2a137536d/csharp/src/Google.Protobuf/MessageParser.cs#L124

There is also a MergeFrom variant of this method, but that one is internal.
https://github.com/protocolbuffers/protobuf/blob/022078d3ee642816688228e9434775f2a137536d/csharp/src/Google.Protobuf/MessageExtensions.cs#L288

Does that satisfy your needs?

**Comment by MaximGurschi** [comment]
@jtattermusch Thank you for that. Unfortunately not it does not as that API allocates the holding proto. My goal is to reuse the proto and also not allocate the CIS.

**Comment by jtattermusch** [comment]
@MaximGurschi  alright, so you'd basically need a public API for msg.MergeFrom(ReadOnlySequence<byte> data) (something along the lines of the latter internal method I posted), is that correct?

**Comment by MaximGurschi** [comment]
@jtattermusch Precisely :)

**Comment by jtattermusch** [comment]
Feel free to come up with a PR that proposes the addition of new public method then?

**Comment by Jensaarai** [comment]
@jtattermusch it seems like it would still be useful to have overloads that take ReadOnlySpan, as sometimes that's what you're given. For instance, [Confluent.Kafka's IDeserializer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IDeserializer.cs#L42) provides a ReadOnlySpan, which would then have to be copied to the heap to use the ReadOnlySequence overload :/

`T Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context);`

Is there something I'm missing that would allow `ReadOnlySpan<byte>` to `ReadOnlySequence<byte>` conversion without allocations?

**Comment by jtattermusch** [comment]
> @jtattermusch it seems like it would still be useful to have overloads that take ReadOnlySpan, as sometimes that's what you're given. For instance, [Confluent.Kafka's IDeserializer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IDeserializer.cs#L42) provides a ReadOnlySpan, which would then have to be copied to the heap to use the ReadOnlySequence overload :/
> 
> `T Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context);`
> 
> Is there something I'm missing that would allow `ReadOnlySpan<byte>` to `ReadOnlySequence<byte>` conversion without allocations or copying?

Adding overloads that parse directly from `ReadOnlySpan<byte>` is definitely feasible (and it's something you can currently achieve using internal APIs) - it's just we want to add new public APIs carefully, to ensure that the public API has small footprint, doesn't degrade after time and will allow us preserve backwards compatibility.

FTR see
https://github.com/protocolbuffers/protobuf/blob/70531697bcac53d6d6c6952ee211ceb9374544f7/csharp/src/Google.Protobuf/ParseContext.cs#L62
https://github.com/protocolbuffers/protobuf/blob/70531697bcac53d6d6c6952ee211ceb9374544f7/csharp/src/Google.Protobuf/MessageExtensions.cs#L290

Feel free to propose a new public API for parsing from ReadOnlySpan<> and open a pull request (note that there are some other enhancement requests around the newly added APIs - please check the github issues for them first).

**Comment by jtattermusch** [comment]
slightly related: 
https://github.com/protocolbuffers/protobuf/issues/8036
https://github.com/protocolbuffers/protobuf/issues/7886
