### ISSUE TITLE
C# WriteDelimitedTo(Span)

### ISSUE THREAD

**Issue by MaximGurschi** [protocolbuffers/protobuf#7886]
Hello, is there an API we can use to achieve the equivalent of WriteDelimitedTo a Span<byte> output?

**Comment by jtattermusch** [comment]
I suspect this is not possible at the moment, unless you come up with a workaround (you can use `WriteTo(this IMessage message, IBufferWriter<byte> output` to write the message content and write the delimiter yourself). 
Note that you can still use the old WriteDelimitedTo API if that's a functionality you need.
What is your use case?

**Comment by MaximGurschi** [comment]
@jtattermusch My use case is serializing many small messages to a **preallocated** byte array.

1.Write 5 length prefix messages to the array.
2.Send the written portion of the array over the wire.
3.Receive the bytes and read them one by one. This is achievable since the items are length prefixed. So i pick up the 5 items on the other side.
4.Achieve all of the above without additional allocations.

The way i achieve "WriteDelimitedTo a Span" currently is:
1.Given a message i want to put in the array, calculate the size of the message.
2.Call CodedOutputStream.WriteLength.
3.Write the message to the CodedOutputStream.
4.The CodedOutputStream is special in that it wraps my a special stream object i wrote that is resettable on the current position so that i can use a single allocated CodedOutputStream around my single preallocated array.

If there was a native "WriteDelimitedTo a Span" then i could do what i want without needing to allocate a CodedOutputStream and needing to implement a custom Stream that is resettable.
I then could just call var writtenBytes = Message.WriteDelimetedTo(array). The way i would write my 5 messages would then become:

for (var i = 0; i < 5; ++i)
   span = span.Slice(0, messages[i].WriteDelimetedTo(span));

So as you can see no need for a CodedOutputStream allocation or any special Stream implementation.

**Comment by jtattermusch** [comment]
@MaximGurschi  I don't have the bandwidth to look into implementing this myself, but we can consider adding this if there's a PR that implements WriteDelimitedTo.
