### ISSUE TITLE
[3.7.1-C++]not generate SerializeToString and ParseFromString

### ISSUE THREAD

**Issue by jun-best** [protocolbuffers/protobuf#7890]
I'm using protobuf in C++ and met one problem, is there any suggestion? thanks.

Version: 3.7.1.
Language: C++

CentOS 6.3

Gcc 4.8.1

1. create test.proto
syntax = "proto3";
message Header {
    string Name = 1;
    int64 Timestamp = 2;
    string ClientID = 3;
}

2. generate C++ pb files
protoc --cpp_out=xx test.proto

3. check test.pb.h and test.pb.cc, and there is no function of SerializeToString and ParseFromString, there is only SerializeWithCachedSizes function

**Comment by acozzette** [comment]
Those are defined on `google::protobuf::MessageLite`, which all generated messages inherit from.
