### ISSUE TITLE
protoc allows recursive request + response body definitions with no warning

### ISSUE THREAD

**Issue by capsocrates** [protocolbuffers/protobuf#7897]
**What version of protobuf and what language are you using?**
Version: v3.12.3
Language: golang 1.14.2

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
golang 1.14.2

**What did you do?**
1. Create a .proto file with
```
message HealthServiceRequest {
  string service = 1;
}

message HealthServiceResponse {
  enum ServingStatus {
    SERVING_STATUS_UNSPECIFIED = 0;
    SERVING_STATUS_SERVING = 1;
    SERVING_STATUS_NOT_SERVING = 2;
    SERVING_STATUS_SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
  }
  ServingStatus status = 1;
}

message HealthServiceWatchResponse {
  HealthServiceWatchResponse body = 1;
}

message HealthServiceWatchRequest {
  HealthServiceWatchRequest body = 1;
}

service HealthService {
  rpc Watch(HealthServiceWatchRequest) returns (stream HealthServiceWatchResponse);
}
```
2. Run `buf check lint --input proto`
3. run
```
mkdir -p gen;
protoc \
  -I proto \
  --go_out=gen \
  --go_opt=paths=source_relative \
  --go-grpc_out=gen \
  --go-grpc_opt=paths=source_relative \
  $(find . -name *.proto)
```

**What did you expect to see**
A linter warning and/or a proto gen failure

**What did you see instead?**
No warning and no failure--but the generated code created objects that were impossible to initialize.

**Comment by acozzette** [comment]
Thank you for the bug report, but this is actually working as intended; you can create self-referential messages or even multiple messages that form a cycle.
