### ISSUE TITLE
How to support zero copy when decode the message ?

### ISSUE THREAD

**Issue by runzhiwang** [protocolbuffers/protobuf#7899]
**What language does this apply to?**

proto3, java

**Describe the problem you are trying to solve.**

My request is similar to https://groups.google.com/g/protobuf/c/ZaDigptdcHM

Currently, when read ByteString.readBytes, the order is InputStream -> StreamDecoder.buffer with 4kB size -> copy StreamDecoder.buffer to byte array on heap. Can we  change the order to InputStream ->  byte array on heap directly ?  Besides, instead use byte array on heap, can we use byte array off-heap ?

As the image shows, arraycopy in StreamDecoder.readBytesSlowPath really cost too much CPU. I want to improve it by avoid arraycopy. If there is other suggestions, I would appreciate it, thank you very much.

![image](https://user-images.githubusercontent.com/51938049/93728381-4a929800-fbf2-11ea-8bad-6135a9156a0a.png)

**Comment by deannagarcia** [comment]
As explained in the comment you linked, unfortunately it is impossible to return the byte array directly because it must be copied to guarantee immutability.
