### ISSUE TITLE
Window Service deserialization issue with Protobuf-net.

### ISSUE THREAD

**Issue by Dharnendra** [protocolbuffers/protobuf#7903]
Hi,

When we try to use protobuf within windows service, its giving issue on deserialization. Its working fine with console but with windows service its giving exception on invalid wire tipe . Now sure whether this package is compatible with windows service or not. PLease update me if any specific configuration require for it

**Comment by jskeet** [comment]
@Dharnendra: Is this still an issue for you? If so, please give more information, ideally with a minimal example and complete error details.
