### ISSUE TITLE
Add 'now' to Timestamps Utility Class

### ISSUE THREAD

**Issue by belugabehr** [protocolbuffers/protobuf#7906]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
Being able to quickly and conveniently get a 'now' timestamp

**Describe the solution you'd like**

In the com/google/protobuf/util/Timestamps class:
```
  public static TimeStamp now() {
    final Instant now = Instant.now();
    return Timestamp.newBuilder().setSeconds(now.getEpochSecond()).setNanos(now.getNano()).build();
  }
```

**Describe alternatives you've considered**
Made my own utility class

**Comment by elharo** [comment]
I think we're unlikely to add this. It doesn't add a lot of functionality, and the use of Instant.now() makes the output of this method and any method that calls it difficult to test.
