### ISSUE TITLE
`Import "google/protobuf/descriptor.proto" was not found or had errors` with [Importer](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.importer#Importer)

### ISSUE THREAD

**Issue by Abbyyan** [protocolbuffers/protobuf#7921]
I'm using reflection of protobuf to parse a `.proto` file. The C++ code `test.cpp` is as follows:
```c++
google::protobuf::compiler::DiskSourceTree sourceTree;  // source tree
  sourceTree.MapPath("", "./");
  MyErrorCollector errorCollector;
  google::protobuf::compiler::Importer importer(&sourceTree, &errorCollector);
  string filename="test.proto";
  cout<<"filename init "<<filename<<endl;
  const google::protobuf::FileDescriptor* filedes =
      importer.Import(filename);
```
and my `test.proto` file is as follows:
```shell
// test.proto

syntax = "proto3";
import "google/protobuf/descriptor.proto";

package lm;

message helloworld

{

  int32 id = 1;

  string name = 2;

  repeated string hero = 3;
}
```
I use clang to compile `test.cpp` and it works fine , only if there are some warnings.
```shell
clang++ test.cpp -pthread -I/xxx/protobuf/include -L/xxx/protobuf/lib64 -lprotobuf
```
But when i run the generated `a.out ` , it cored with error `test.proto, -1, 0, Import "google/protobuf/descriptor.proto" was not found or had errors.` .
```shell
 ./a.out
>>>test.proto, -1, 0, Import "google/protobuf/descriptor.proto" was not found or had errors.
```
I've install `protoc` and if i remove the `import "google/protobuf/descriptor.proto";` line in `test.proto`, the `a.out` can works.  How can i use `FileDescriptor ` to parse a `.proto` with some `import xx` please? Thanks a lot.

**Comment by TeBoring** [comment]
You proto file doesn't depend on descriptor.proto. So you should be fine if you don't import that.
The protoc code depends on pre-generated code for descriptor.proto. So you should already be able to use that in your c++ code.

**Comment by Abbyyan** [comment]
> You proto file doesn't depend on descriptor.proto. So you should be fine if you don't import that.
> The protoc code depends on pre-generated code for descriptor.proto. So you should already be able to use that in your c++ code.

It just a demo so i did't write the usage of `google/protobuf/descriptor.proto`. Now i find the run with `-I/protobuf_include_path -I./` can solve this problem. Thanks a lot.
