### ISSUE TITLE
Add ruby 3.0.0 support

### ISSUE THREAD

**Issue by sriedel** [protocolbuffers/protobuf#7922]
**What language does this apply to?**
ruby

**Describe the problem you are trying to solve.**
Ruby 3.0.0-preview1 was released over the weekend. We'd like to check our ruby services before the official ruby 3.0 release (probably on christmas, as this is the usual ruby release date for new versions). However the google-protobuf gem explicitly prohibits bumping the ruby version to beyond 2.7 (the current stable version):

    Gem::RuntimeRequirementNotMetError: google-protobuf requires Ruby version >= 2.3, < 2.8.dev. The current ruby version is 3.0.0.preview1.
     An error occurred while installing google-protobuf (3.13.0), and Bundler cannot continue.    
     Make sure that `gem install google-protobuf -v '3.13.0' --source 'https://gem.givve.io/'` succeeds before bundling.

**Describe the solution you'd like**
The google-protobuf gem is installable under ruby 3.0.0. I'd be happy with a solution that is locked to the preview without any guarantee of functionality in production environments.

**Comment by acozzette** [comment]
Do you know where this requirement is coming from? I see that our gemspec requires `>= 2.3` but I don't see the `< 2.8.dev` anywhere (is that coming from one of our dependencies?)

**Comment by sriedel** [comment]
After hours of being stumped and studying the code for both bundler and gem (since if it isn't provided by you, it must be injected somewhere, right?), it dawned on me that the google-protobuf gem is being supplied in different versions:
- the plain version which we've been looking at, which apparently doesn't have the restriction
- a precompiled version, which has the restriction in place, see https://rubygems.org/gems/google-protobuf/versions/3.13.0-x86_64-linux 

So this seems to be injected by the build process or build system. Which makes sense in a why, since the ABI has changed.
I'll have to figure out how to tell bundler that I don't want the precompiled version. Adding a ruby-3.0.0 version to your build system would be great too, though :)

**Comment by acozzette** [comment]
@sriedel Thanks for tracking that down, that is a little surprising but I guess it makes sense. I think in principle we should be able to make our next release add a ruby-3.0 compatible version. @haberman Does that sound doable?

**Comment by bilby91** [comment]
Is there any ETA for supporting ruby 3.0 ?

**Comment by KapilSachdev** [comment]
xref: #8134

**Comment by haberman** [comment]
This should be fixed as of #8184, released in 3.15.0-rc1. Please let us know if you run into problems.
