### ISSUE TITLE
v3.13.0 from Packagist is not up-to-date

### ISSUE THREAD

**Issue by PierrickVoulet** [protocolbuffers/protobuf#7926]
**What version of protobuf and what language are you using?**
Version: v3.13.0
Language: PHP
Implementation: pure-PHP

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Create a new `composer.json` file with `{
  "require": {
    "google/protobuf": "3.13.0"
  }
}`
2. Run `composer install`
3. Go to `vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php`
4. Look at the content of the function `private function existField`: its content starts with **`$oneof_index = $field->getOneofIndex();`**
5. Go to the v3.13.0 source in [GitHub](https://github.com/protocolbuffers/protobuf/blob/v3.13.0/php/src/Google/Protobuf/Internal/Message.php#L1571), its content starts with **`$getter = $field->getGetter();`**

**What did you expect to see**
The same content in the vendor package as in the GitHub source.

**What did you see instead?**
An older version of the source code in the vendor package.

**Anything else we should know about your project / environment**
Because of this, the `Message->serializeToJsonString()` method fails to print proto3 optional fields (see https://github.com/googleads/google-ads-php/issues/425). There may be other consequences we did not notice yet.

**Comment by acoulton** [comment]
This appears to be related to https://github.com/protocolbuffers/protobuf-php/issues/7 

As well as the error above the `hasOneOf()` etc method is missing in both the packagist install and the native extension.

As a result packages compiled with protoc 3.13.0 now contain multiple `hasXXXX()` methods that all throw fatal errors when called - for example many of the methods added in https://github.com/googleapis/google-cloud-php/pull/3327

**Comment by PierrickVoulet** [comment]
There seem to be another consequence of this issue as reported by https://github.com/googleads/google-ads-php/issues/432: the [`Message.hasOneof` method is defined in v3.13.0](https://github.com/protocolbuffers/protobuf/blob/v3.13.0/php/src/Google/Protobuf/Internal/Message.php#L228) but is does not seem to be present when using `"google/protobuf": "3.13.0"` in `composer.json`.

**Comment by bshaffer** [comment]
Looks like v3.13.0 of [protobuf-php](https://github.com/protocolbuffers/protobuf-php/blob/v3.13.0/src/Google/Protobuf/Internal/Message.php#L1560) includes the `getOneofIndex`. We should try to get v3.13.0 retagged with the correct code

**Comment by TeBoring** [comment]
Fixed on packagist: https://packagist.org/packages/google/protobuf

**Comment by TeBoring** [comment]
Fixed on packagist: https://packagist.org/packages/google/protobuf
