### ISSUE TITLE
Java toString() skips enums if the index is 0 (proto3)

### ISSUE THREAD

**Issue by jonross09** [protocolbuffers/protobuf#7934]
The java toString() on protobuf objects does not print out enum, if the enum value is 0.
Since proto version 3 requires that the first enum's value must be 0, you are guaranteed that any message using that enum value will not print anything out for that field in a message.

**Comment by acozzette** [comment]
Thank you for the bug report but I think this is working as intended. Proto3 ordinarily makes no distinction between a primitive field being absent and being set to its default value, so if an enum field is set to 0 then that's the same as it not being set at all. However, we are bringing proto2-style optional fields back to proto3. If you want this behavior, you can just mark the field `optional` in your `.proto` file and make sure to pass `--experimental_allow_proto3_optional` to protoc.

**Comment by jonross09** [comment]
No 0 is not the same as not being set. 0 is a valid value. In fact it's a
required valid value because the first entry in the enum must have a value
of zero.

The enum also generates a undefined value of -1. That should be the unset
value. I assume thats why it's there.

If your telling me you cant tell the difference between a unset and set
value and that's correct behavior , that seems crazy to me.

**Comment by acozzette** [comment]
Enums need to have a zero value precisely because that is the value they hold when they're unset. The -1 `UNRECOGNIZED` value in Java is different and is what you get if you parse a message containing an unknown enum value. Have you tried setting your field to `optional`? I think that would give you the behavior you're looking for.
