### ISSUE TITLE
AttributeError: 'DESCRIPTOR' when converting Vision API response using MessageToJson

### ISSUE THREAD

**Issue by monark12** [protocolbuffers/protobuf#7941]
I have been using MessageToJson to convert Vision API response to JSON. But today it suddenly stopped working. 

After doing, 
response = client.document_text_detection(image=image)

Then I convert it to JSON using,
json_string = MessageToJson(response)

But I am getting this error
![Screenshot 2020-10-05 at 3 48 06 PM](https://user-images.githubusercontent.com/12967301/95068399-e0661100-0722-11eb-8297-558534bcb729.png)

I need your help as this is being used in a production environment and I am not able to figure out why I suddenly start getting this error.

**Comment by dlj-NaN** [comment]
@monark12 Could you verify what library has the `client.document_text_detection` function?

**Comment by software-dov** [comment]
I think I know what's happening.
I am assuming that the client library version was update recently. The new versions of Google Cloud API client libraries use [Proto Plus](https://github.com/googleapis/proto-plus-python) to define message types.
The new means of converting to/from json is now:
```python
response = client.document_text_detection(image=image)
json_string = type(response).to_json(response)  # Also works to use the message type directly, e.g.
                                                                             # json_string = MyMessageType.to_json(response)
```
`to_json` and `from_json` aren't visible to message instances; they _must_ be called from the message class, and the message itself is then passed in.
https://proto-plus-python.readthedocs.io/en/stable/messages.html#serialization

Let us know if that solves the problem!

**Comment by mcobzarenco** [comment]
I've had the same problem as OP, @software-dov's solution does the job :+1:

**Comment by barlaensdoonn** [comment]
@software-dov's solution still works Aug 2021 for AutoML Natural Language model prediction responses
