### ISSUE TITLE
any.UnpackTo(MessageType) leads to a Run-Time Check Failure #1 - A cast to a smaller data type has caused a loss of data.

### ISSUE THREAD

**Issue by Shaomane** [protocolbuffers/protobuf#7942]
![image](https://user-images.githubusercontent.com/16363993/95103687-c5c37600-06e9-11eb-99e3-57e8aa5c4ffc.png)

**What version of protobuf and what language are you using?**
Version: **master**
Language: **C++**

**What operating system (Linux, Windows, ...) and version?**
**Windows**

**What runtime / compiler are you using (e.g., python version or gcc version)**
**Visual C++ Compiler, cl.exe**

**What did you do?**
1. Compiled a .proto with a Message type 'Dummy' with protoc.exe 
2. Made a call to server to get instance of this 'Dummy' type object, getting back a generic 'Any' type
3. Attempted to unpack the generated class/object from 'Any' to 'Dummy' type, like so... 

if (any.Is<Dummy>()) {
    Dummy dummy = new Dummy();
    any.UnpackTo(dummy);
    return dummy;
}

**What did you expect to see**
Didn't expect to see any errors. 

**What did you see instead?**
any.UnpackTo(dummy) line leads to the following error:

_A 'Run-Time Check Failure #1 - A cast to a smaller data type has caused a loss of data. If this was intentional, you should mask the source of the cast with the appropriate bitmask. For example: char c = (i & 0xFF);
Changing the code in this way will not affect the quality of the..._

**Anything else we should know about your project / environment**

I'm able to bypass this by turning off the compiler Run-Time Checks, but do we want to be forcing this behavior? During runtime, the debugger shows that the 'tag' (variable in the image) is a uint32 (e.g. 802) being cast into an uint8. 

_Note: the anonymized parts on the code is the 'Dummy' namespace and class name._

**Comment by TeBoring** [comment]
Could you help send a fix like the warning suggested to us?
