### ISSUE TITLE
Use ujson or orjson (or any other fast implementation of json) in json_format.py

### ISSUE THREAD

**Issue by mishas** [protocolbuffers/protobuf#7943]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
Serializing to and deserializing from json in python is painfully slow.

**Describe the solution you'd like**
There're many fast implementations of json in python. The most popular ones are ujson and orjson.
Those implementations are up to 11x times faster than the builtin Json implementation ([source](https://github.com/ijl/orjson#performance)).
Using those (whenever they exist) will make this much faster.
We should also add the optional extra `protobuf[fastjson]` in the python package that will install the fast json implementation as a dependency.

**Describe alternatives you've considered**
In our project we're using `json_format.MessageToDict` and `json_format.ParseDict` and serializing to/from json ourselves. But we feel like having it built-in would be nicer.

**Comment by yiga2** [comment]
Any traction on this ? Some messages can be very long and using `orjson` would speed up de-/serialization a lot.

Since `orjson` is a drop-in replacement of `json`, https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/json_format.py#L53 could be rewritten as 
```
try:
    import orjson as json
except ImportError:
    import json
```

**Comment by dlj-NaN** [comment]
As far as I can tell, neither ujson nor orjson support `object_pairs_hook`. Duplicate rejection is part of the observable interface in json_format:

https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/json_format.py#L431

https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/json_format.py#L390-L396

Unfortunately, that means `ujson` and `orjson` would not be suitable for use in protobuf.
