### ISSUE TITLE
MobSF reported use of unsecured function

### ISSUE THREAD

**Issue by Lakshaya** [protocolbuffers/protobuf#7945]
**What version of protobuf and what language are you using?**
Version: v3.12.0 etc.
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
iOS
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
We have used MobSF client to analyse our app and it has reported the use of following unsecured functions which are used by protobuf

_strlen/strlen
_memcpy/memcpy

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by thomasvl** [comment]
Do they have more details about what they think is insecure about using these functions?  Yes, mistakes can be made with these apis, but the params are controlled, and the calls all should be safe; if they have suggestions of safer alternatives, it would be interesting to hear what they are.

**Comment by thomasvl** [comment]
ps - if their scan just checks for these calls without actually looking at the usage, be warning, that's not always great advice and it can lead folks to not call the standard api, and instead roll their own which means more chance for making mistakes in that custom code.

**Comment by thomasvl** [comment]
Closing since the tools seems to be trying to just check for strings in sources and not really auditing the code.
