### ISSUE TITLE
Unmarshal into incorrect type does NOT result in error

### ISSUE THREAD

**Issue by ideasculptor** [protocolbuffers/protobuf#7946]
Golang

github.com/golang/protobuf v1.4.2
google.golang.org/protobuf v1.25.0
protoc 3.12.1 (running in a linux container and fetched from https://github.com/protocolbuffers/protobuf/releasesj/download/v3.12.1/protoc-3.12.1-linux-x86_64.zip) 
protoc-gen-go from google.golang.org/protobuf/cmd/protoc-gen-go v1.25.0

**What operating system (Linux, Windows, ...) and version?**
OS X 10.15.5 and protoc was run from centos:8 container

**What runtime / compiler are you using (e.g., python version or gcc version)**
go 1.13.10 darwin/amd64

**What did you do?**
1. Define 2 protobuf Message types and compile with protoc
2. Write golang code which instantates proto #1 and populates it.
3. call `buf, err := proto.Marshal(p1)`
4. instantiate an empty instance of proto #2 and then call `err := proto.Unmarshal(buf, &p2)`

**What did you expect to see**
I expected err in line 4 to be non-nil

**What did you see instead?**
the call to proto.Unmarshal appeared to succeed but the values of various fields were garbage.  I've looked high and low for some way to validate that an unmarshaled protobuf was correctly unmarshaled but I have found nothing.  The fact that proto.Unmarshal returns an error might lead one to think that an incompatible type would result in an error, but that doesn't appear to be the case.  Documentation for the function in question doesn't mention what might cause an error return value, nor does searching the internet reveal much.

The definition of proto1 (the message that gets marshaled to a buffer) is as follows:
```
package test;

message TestAlert {
    string msg = 1;
    int32 num = 2;
    message NestedMessage {
        string nestedMsg = 1;
        int32 nestedNum = 2;
    }
    NestedMessage nested = 3;
}
```

It is populated as follows:
```
	alert := &test.TestAlert{
		Msg: "a message",
		Num: 123,
		Nested: &test.TestAlert_NestedMessage{
			NestedMsg: "nested message",
			NestedNum: 456,
		},
	}
```

definition for proto2 (the destination proto when unmarshaling) is as follows:
```
package events;

message Event {
  // unique identifier for the Event.  Must be unique for the source but
  // preferably completely unique (eg: uuid4)
  string id = 1;

  // An optional class for the type of event, potentially for use by
  // event delivery protocol.  May be empty.
  string class = 2;

  // Timestamp to associate with the event
  google.protobuf.Timestamp timestamp = 3;

  // Describe the source of the event, including any return communication
  // channel - host/port, topic/bucket, etc
  tunein.events.EventSource source = 4;

  // A protobuf message encoded as Any which contains the details of the 
  // event. If working with a message for which there is no descriptor, 
  // message may be encoded as a TypedStruct message encoded as Any.
  // https://github.com/cncf/udpa/blob/master/udpa/type/v1/typed_struct.proto
  repeated google.protobuf.Any details = 5;
}

message EventSource {
  enum Process {
    UNKNOWN = 0;
    SOME = 1;
    OTHER = 2;
    ENUM = 3;
    VALUES = 4;
  }
  // The process type which generated the event
  Process process = 1;

  // A specific instance identifier for the process
  string instance = 2;

  // optional additional information about the event source, encoded as string
  string extra = 3;

  // An optional return channel, should an event consumer wish to respond to 
  // this event
  oneof return_channel {
    events.RestReturn rest_return = 4;
    events.KafkaReturn kafka_return = 5;
  }
}

message RestReturn {
  string url = 1;
}

message KafkaReturn {
  string topic = 1;
  string bucket = 2;
}
```

Actual code looks like this:
```
	alert := &test.TestAlert{
		Msg: "a message",
		Num: 123,
		Nested: &test.TestAlert_NestedMessage{
			NestedMsg: "nested message",
			NestedNum: 456,
		},
	}
	buf, _ := proto.Marshal(alert)
	event := &events.Event{}
	err := proto.Unmarshal(buf, event)
	if err != nil {
		fmt.Printf("error while unmarshaling\n")
		return
	}
	fmt.Printf("finished unmarshaling\n")
```

**Comment by acozzette** [comment]
Thank you for the bug report but this is actually expected behavior. A protobuf message's schema is expected to change over time, adding new fields and/or removing old ones. The parser ultimately has to be fairly lenient and able to tolerate unexpected fields. As a result, it is pretty typical for a serialized proto to be parsable as a proto of a completely different type. You can get an error if there are missing required fields or if a `string` field has non-UTF8 data (or maybe a few other cases I'm forgetting), but otherwise there usually won't be an error.

**Comment by ideasculptor** [comment]
To my mind, that's still a bug until it is documented to be the case.  But beyond that, a lenient parser should still provide the ability to determine if you deserialized something incorrectly, even if it is simply comparing typeURL in a serialized form with a static typeURL in the structure. Otherwise, it is literally impossible to determine if you've deserialized a buffer into the correct form, and untold errors could result.  Even if you want the parser to allow that to be done, for deserializing into compatible protos or something, providing a function which would at least allow a check to be performed explicitly seems more than reasonable to provide.  

But documenting the behaviour of the marshal and unmarshal functions when using incompatible protobufs is absolutely necessary.  There is probably lots of inadequately tested code out there that is assuming that the error return value from Unmarshal() is actually meaningful.

**Comment by jvalecillos** [comment]
For me it is still a bug and not expected behaviour as stated above, unless all the common fields match type, name and position/order in the proto definition, which is not the case here.
