### ISSUE TITLE
protoc cannot find descriptor.proto on FreeBSD

### ISSUE THREAD

**Issue by alxrmorozov** [protocolbuffers/protobuf#7948]
**What version of protobuf and what language are you using?**
Version: v3.13.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 12.1-RELEASE

**What did you do?**
I try to compile proto file which imports descriptor.proto

**What did you expect to see**
On Linux I can make it without errors

**What did you see instead?**
```
user@freebsd12:~% cat t.proto
syntax = "proto2";
import "google/protobuf/descriptor.proto";
message t {}
user@freebsd12:~% protoc --cpp_out=. t.proto
google/protobuf/descriptor.proto: File not found.
t.proto:2:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
```

**Anything else we should know about your project / environment**
protoc is in /usr/local/bin/protoc, descriptor.proto is in /usr/local/include/google/protobuf/descriptor.proto.
It seems that the problem is connected with GetProtocAbsolutePath which is not implemented really for FreeBSD: https://github.com/protocolbuffers/protobuf/blob/93d8e89374947aa6c05c290b08efd211c6703087/src/google/protobuf/compiler/command_line_interface.cc#L190-L215

**Comment by TeBoring** [comment]
Could you send us a fix?

**Comment by alxrmorozov** [comment]
I do not have a fix now but I could make it
