### ISSUE TITLE
"Well-known" cc proto libraries are declared private

### ISSUE THREAD

**Issue by smolkaj** [protocolbuffers/protobuf#7953]
Currently, the root `BUILD` file declares:
```
[native_cc_proto_library(
    name = proto + "_cc_proto",
    deps = [proto + "_proto"],
    visibility = ["//visibility:private"],
) for proto in WELL_KNOWN_PROTO_MAP.keys()]
```
It seems like these should have `//visibility:public` so they can be depended on by third party cc_proto_libraries.

**Comment by perezd** [comment]
Seems like an oversight, please submit a PR to fix.

**Comment by dlj-NaN** [comment]
These are actually a different target type, used for validating Bazel internals... 723a85f797 has some details, but for your use case, the `:protobuf` target has the necessary files:

https://github.com/protocolbuffers/protobuf/blob/2558c5deefffa3f01c206d5b132b999a18da7573/BUILD#L264
