### ISSUE TITLE
Python: Using slicing with ListValue results in an error

### ISSUE THREAD

**Issue by kwkbtr** [protocolbuffers/protobuf#7958]
**What version of protobuf and what language are you using?**
Version: v3.13.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**

macOS 10.15.7

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.7.3

**What did you do?**
1. Run the following in Python REPL

```
>>> from google.protobuf import struct_pb2
>>> l = struct_pb2.ListValue()
>>> l.append(1)
>>> l
values {
  number_value: 1.0
}

>>> l[0:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/google/protobuf/internal/well_known_types.py", line 827, in __getitem__
    return _GetStructValue(self.values.__getitem__(index))
  File ".../lib/python3.7/site-packages/google/protobuf/internal/well_known_types.py", line 740, in _GetStructValue
    which = struct_value.WhichOneof('kind')
AttributeError: 'list' object has no attribute 'WhichOneof'
>>> l[0]
1.0
```

**What did you expect to see**

Able to use list slicing without an error.

**What did you see instead?**

An error described above.

**Anything else we should know about your project / environment**

**Comment by nagyt2** [comment]
Are there any update on this?
