### ISSUE TITLE
v3.13.0.1 from PECL fails due to missing `Message::hasOneOf()` method

### ISSUE THREAD

**Issue by PierrickVoulet** [protocolbuffers/protobuf#7961]
Following up on #7926, initially reported by https://github.com/googleads/google-ads-php/issues/432#issuecomment-707673553 

**What version of protobuf and what language are you using?**
Version: v3.13.0.1
Language: PHP
Implementation: C

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
Run some code that uses a `hasXXX` generated method which calls `Message::hasOneOf()`:
1. It runs fine when using the pure-PHP implementation
2. It fails when using the C implementation with the following message (see related [source](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V5/Resources/Ad.php#L771)):

```
PHP Fatal error:  Uncaught Error: Call to undefined method Google\Ads\GoogleAds\V5\Resources\Ad::hasOneof() in /usr/local/google/home/pierrick/git/gob/ga/google-ads-php/src/Google/Ads/GoogleAds/V5/Resources/Ad.php:771
Stack trace:
#0 /usr/local/google/home/pierrick/git/gob/ga/google-ads-php/examples/BasicOperations/GetExpandedTextAds.php(131): Google\Ads\GoogleAds\V5\Resources\Ad->hasExpandedTextAd()
```

**What did you expect to see**
A successful run when using the C implementation like it is the case when using the pure-PHP implementation.

**Comment by PierrickVoulet** [comment]
This seems to be fixed, I do not reproduce this issue with the version 3.14.0 (tested with both the PHP and C implementations).

Could you confirm?

**Comment by leongersen** [comment]
I can confirm this is resolved with the updated extension. Thanks!
