### ISSUE TITLE
Failed protobuf-test(exit status: 1)

### ISSUE THREAD

**Issue by junlinliu1** [protocolbuffers/protobuf#7962]
When I  try the make check, it says that the protobuf-test fail one.
And in the test-suite log:
it says: Failed: IoTest.LargeOutput

**Comment by perezd** [comment]
Sorry, this is not enough detail to be actionable. Please provide more details if you're still seeing problems.

**Comment by xavierallem** [comment]
Having the same issue while installing protobuf




`FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.14.0-rc-1
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
Makefile:7977: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/xavierallem/Downloads/protobuf-3.14.0-rc-1/src'
Makefile:8083: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/xavierallem/Downloads/protobuf-3.14.0-rc-1/src'
Makefile:8201: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/xavierallem/Downloads/protobuf-3.14.0-rc-1/src'
Makefile:1872: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
`


This is the log output at the end



[test-suite.log](https://github.com/protocolbuffers/protobuf/files/5510150/test-suite.log)

**Comment by Guiraud** [comment]
Having the same issue.
Uname -a : 
Linux pi4 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
on protobuf-3.14.0

 RUN      ] IoTest.LargeOutput
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] IoTest.LargeOutput (5033 ms)

===============
[----------] Global test environment tear-down
[==========] 2174 tests from 198 test suites ran. (88557 ms total)
[  PASSED  ] 2173 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IoTest.LargeOutput

 1 FAILED TEST
FAIL protobuf-test (exit status: 1)

[test-suite.log](https://github.com/protocolbuffers/protobuf/files/5736223/test-suite.log)

**Comment by JoaoHenriqueOliveira** [comment]
Same here 
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Ubuntu 20.04.1 LTS


../test-driver: line 107: 97596 Killed                  "$@" > $log_file 2>&1
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
=================================
Testsuite summary for Protocol Buffers 3.14.0
=================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
==========================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================
make[3]: *** [Makefile:7978: test-suite.log] Error 1
make[3]: Leaving directory '/home/protobuf-3.14.0/src'
make[2]: *** [Makefile:8086: check-TESTS] Error 2
make[2]: Leaving directory '/home/j/protobuf-3.14.0/src'
make[1]: *** [Makefile:8202: check-am] Error 2
make[1]: Leaving directory '/home/protobuf-3.14.0/src'
make: *** [Makefile:1872: check-recursive] Error 1

**Comment by JoaoHenriqueOliveira** [comment]
I had the same error .....

**Comment by bullekeup** [comment]
@perezd : I have more info concerning this issue, if you can look at it.

As mentioned before, the protobuf-test check failed for the IoTest.LargeOutput test.

From what I understood looking at the source, the IoTest.LargeOutput test declared in [src/google/protobuf/io/zero_copy_stream_unittest.cc](https://github.com/protocolbuffers/protobuf/blob/d18df4f76436799a9d7b5f903d043075248fae66/src/google/protobuf/io/zero_copy_stream_unittest.cc#L716) line 716 tries to increase buffer size to kint32max (a little bit more than 2GB). This is more than usually available as contiguous memory on RPis and similar hardware (I suppose the StringOutputStream uses contiguous memory, correct me if that's wrong).

I just had the issue on a Jetson Nano (4GB of RAM), when starting the check, memory usage grows from 1.4 GB to around 3.5 - 3.9 GB and the test fails with no swap space used (4GB swap available).

If it just indicates that we won't be able to process huge buffers at once (but on theses constrained platforms we probably don't want / need to anyway), this fail may be ignored without much risk ?

**Comment by erlingrj** [comment]
This tests also fails on Khadas VIM3.
uname - a
Linux Khadas 4.9.224 #29 SMP PREEMPT Sat May 30 14:20:51 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

It has 4GB RAM
