### ISSUE TITLE
Syntax for adding a map field to a message builder using FieldDescriptors

### ISSUE THREAD

**Issue by zolstein** [protocolbuffers/protobuf#7964]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**

I'm trying to write a function to populate a message object with arbitrary data for fuzz testing. It recursively traverses the object setting values using FieldDescriptors. The getField/setField API doesn't adequately support doing this for map objects. It requires constructing protobuf.MapEntry objects and adding them as repeated fields. Not only is this syntax unwieldy, but the MapEntry objects fall outside the public API.

**Describe the solution you'd like**

A syntax along the lines of `Message.Builder.putMapField(fieldDescriptor, Object key, Object value)` would make this easier and avoid the explicit use of private APIs.

**Describe alternatives you've considered**

Alternately, I plan to use private APIs and deal with any breakages that might suddenly arise from this.

**Comment by elharo** [comment]
Fuzzing is valuable and also an edge case that deliberately violates normal boundaries. I'm not hugely surprised or bothered if you have to do weird reflection stuff here to make it work. We'd need a more normal use case to consider this.

**Comment by jazdw** [comment]
@elharo this really has nothing to do with fuzzing and is not at all violating normal boundaries. Every other field type has a natural way to set a field using it's `FieldDescriptor` why not map entries?

If anyone finds this issue and is wondering how to do this without using the private `MapEntry` API, this is how you can do it -

```java
if (field.isMapField()) {
    Descriptors.Descriptor messageType = field.getMessageType();
    // see com.google.protobuf.MapEntryLite for field numbers
    Descriptors.FieldDescriptor keyField = messageType.findFieldByNumber(KEY_FIELD_NUMBER); // KEY_FIELD_NUMBER = 1
    Descriptors.FieldDescriptor valueField = messageType.findFieldByNumber(VALUE_FIELD_NUMBER); // VALUE_FIELD_NUMBER = 2
    Message.Builder entryBuilder = builder.newBuilderForField(field);
    entryBuilder.setField(keyField, key);
    entryBuilder.setField(valueField, value);
    builder.addRepeatedField(field, entryBuilder.build());
}
```
