### ISSUE TITLE
Python 3.8 wheel for Windows missing on PyPI

### ISSUE THREAD

**Issue by ivanst0** [protocolbuffers/protobuf#7967]
https://pypi.org/project/protobuf/#files contains Python 3.8 wheels for Mac OS and Linux, but not for Windows.

Could you please publish a wheel for Windows as well?

**Comment by ivanst0** [comment]
@anandolee It seems that your PR (https://github.com/protocolbuffers/protobuf/pull/7009) added support for building Python 3.8 wheels for Windows almost a year ago.
What else needs to happen in order to have the Windows wheels on PyPI?

**Comment by busunkim96** [comment]
Friendly ping @anandolee. It looks like the current setup only creates wheels for windows up through 3.7. 

> https://pypi.org/project/protobuf/3.15.0rc1/#files has now the python 3.9 release candidate builds. Yet both python 3.8 and 3.9 are missing the Windows builds. I hope they will show up in the final release.
> 
> The Windows builds for python 3.8 were also missing in v3.14.0, so not entirely sure what's behind it, if there's a plan to build them?

_Originally posted by @ahtik in https://github.com/protocolbuffers/protobuf/issues/8121#issuecomment-777285787_

**Comment by ahtik** [comment]
protobuf 3.15.1 got released now (Feb 20, 2021), but unfortunately also here the Windows binaries are missing for Python 3.8 and 3.9: https://pypi.org/project/protobuf/3.15.1/#files

Is there anything we (I) can help with to get them built and published? Not sure what to do as the link https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:protobuf%2Fgithub%2Fmaster%2Fwindows%2Fpython_release%2Fcontinuous is not public and the KOKORO CI itself is internal/don't have access to. This PR itself includes the Windows building bits.

**Comment by duckmatt** [comment]
Hi @TeBoring @anandolee any idea what might be missing for the 3.8 and 3.9 Windows wheels? #8121 seemed to cover most of the ground but thinking maybe there's something small missing from the CI which we're unable to see from an external perspective

A fix will also knock off these duplicates: #7530  #6214

Slightly related minor note: I've noticed is that in the `setup.py`  classifiers for 3.8 and 3.9 were added in #8121: https://github.com/protocolbuffers/protobuf/blob/51c80ce1d574b3b82f1163cae502b853b7ac2be3/python/setup.py#L272-L284 but seem to have been lost from master: 
https://github.com/protocolbuffers/protobuf/blob/master/python/setup.py#L272-L282

**Comment by busunkim96** [comment]
It seems like this has been resolved in the latest release. https://pypi.org/project/protobuf/3.17.3/#files. (fix was made in https://github.com/protocolbuffers/protobuf/pull/8757)

**Comment by anandolee** [comment]
Thank you Bu Sun Kim, and yes it is fixed by #8757
