### ISSUE TITLE
Question: Why are protobufs not designed to handle large messages?

### ISSUE THREAD

**Issue by ben-xD** [protocolbuffers/protobuf#7968]
Dear Protobuf developers

I found https://developers.google.com/protocol-buffers/docs/techniques#large-data,
> Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy.

However, on [StackOverflow](https://stackoverflow.com/questions/47564437/why-protobuf-is-bad-for-large-data-structures), it seems like answerers have concluded protobufs are not optimal for large data for 1 reason: serialisation/ deserialization overhead. I guess you mean as a file gets bigger, you're less likely going to need all the data, so protobufs (where deserialization is a requirement) would be unoptimal.

_1. Are there any other reasons that come to mind as to why you wouldn't recommend ?_

Finally, the documentation states
> Protocol Buffers do not include any built-in support for large data sets 
_2. What would built-in support look like?_

3. What would you say is the best option for uploading many lists of many numbers (Floats/ doubles)? Serialization is expensive, but sending a stringified list is also space inefficient.

Thanks for reading 🙂

**Comment by dlj-NaN** [comment]
Strictly speaking, there is a system limit around 2GiB, so it's possible to deal with serialized data up to that size.

The main reason for the advice, however, is that serialization and deserialization incurs unavoidable copies, and often, users store the entire _serialized_ message in memory (in addition to the _deserialized_ structures).

The de/serialization overhead is sort of a red herring in this case... there is overhead, but it's doing something useful. Without understanding your use case, I don't see how the cost of de/serializing could be argued to be worthwhile or not.

**Comment by ben-xD** [comment]
Thanks 👍 

> Without understanding your use case, I don't see how the cost of de/serializing could be argued to be worthwhile or not.

Is it right to think that applications which are already processing that data (and thus have it in memory) would find protobufs more useful? This is my use case. An idea I had was to send the output (e.g. feature vector of 2048 floats) of a neural network running on device for many inputs (1000 images) to a server over http in a protobuf message. For 1000, this could be 8MB, but for more images it could be 100MB. 

It seems I am prematurely optimizing, and should just try this approach and see if there are any bottlenecks. Alternatively I can send each feature vector separately in a protobuf message, and incur the overhead of making separate network requests and separate protobuf objects. (Protobuf serialization performance is probably linear though). In this case it would be 8KB of feature vector data per request.

**Comment by daohu527** [comment]
@ben-xD 
It seems that the individual time is reduced, but your transmission times have increased, and the overall time is not necessarily reduced.
