### ISSUE TITLE
About style guide for repeated fields

### ISSUE THREAD

**Issue by zxeoc** [protocolbuffers/protobuf#7972]
In the [style guide](https://developers.google.com/protocol-buffers/docs/style#repeated_fields), it said we should use pluralized names for repeated fields. But if we add a repeated field like "members", generated code gives methods like getMembersList() and getMembers(int index). Should we update the style guide?

**Comment by acozzette** [comment]
I think this is a case where some language implementations are set up better than others when it comes to repeated field naming. For example, the C++ accessors work well with plural names, but in Javascript they sound better with singular names. Unfortunately it is hard to go back and fix things at this point, and I'm afraid we're stuck with the imperfect style guide decision.
