### ISSUE TITLE
JSON Serialization with Objective-C

### ISSUE THREAD

**Issue by zhungxd** [protocolbuffers/protobuf#7976]
**What language does this apply to?**
Objective-C

**Describe the problem you are trying to solve.**
JSON Serialization with Objective-C.in #1675,said:  "To support it we'd likely need to include a lot more string data so it would bloat the binaries" ,and close the issue in 2016.

but now Java（Android）has it [JsonFormat.java](https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java)

We need it Because we use it in debug binaries for testing and debuging.Mocking test data is more convenient with json.

**Comment by thomasvl** [comment]
@acozzette @haberman - isn't that Java support just for server usage, and not on the Android side?

**Comment by acozzette** [comment]
I guess one could technically use that JSON support on Android, but you're right that it is intended only for server usage and doesn't work with Java lite protos, which are optimized for mobile.

**Comment by thomasvl** [comment]
@acozzette thanks.

@zhungxd - still no plans to support for objc, it would need the same data left out of the lite runtimes in other languages that is intended for mobile spaces.
