### ISSUE TITLE
about c# property name.

### ISSUE THREAD

**Issue by woshihuo12** [protocolbuffers/protobuf#7979]
message A
{
      int gidAbCd;
}

because "UnderscoresToCamelCase"   the property will change to GidAbCd.  but i want keep my field name to property, i dont want use First letter to CamelCase.

can add some option to c# generate code ?

**Comment by jtattermusch** [comment]
When designing Protobuf C#, we chose naming for properties that matched the generally accepted code style for C#.
So no, we're not going to introduce a new codegen option (which comes at significant maintenance cost and intellectual load) just for aesthetic reasons like this.
