### ISSUE TITLE
`containingType` not getting set

### ISSUE THREAD

**Issue by noel-yap** [protocolbuffers/protobuf#7996]
**What version of protobuf and what language are you using?**
Version: com.google.protobuf:protobuf-java:3.13.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux ******** 5.4.0-51-generic #56~18.04.1-Ubuntu SMP Tue Oct 6 09:47:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
openjdk version "14.0.2" 2020-07-14

**What did you do?**
1. In a Kotlin test using JUnit 5 and AssertJ:
```
  @Test
  fun `Should use containing type to get specific Java file name`() {
    val innerMessageDescriptorProto = DescriptorProtos.DescriptorProto.newBuilder()
        .setName("InnerMessage")
        .build()
    val outerMessageDescriptorProto = DescriptorProtos.DescriptorProto.newBuilder()
        .setName("OuterMessage")
        .addNestedType(innerMessageDescriptorProto)
        .build()

    assertThat(innerMessageDescriptorProto.descriptorForType.containingType)
        .isNotNull
    assertThat(innerMessageDescriptorProto.descriptorForType.containingType.toProto())
        .isEqualTo(outerMessageDescriptorProto)
  }
```
2. Run the test
3. See error:
```
Expecting actual not to be null
```

**What did you expect to see**
The test to pass

**What did you see instead?**
The test fails

**Comment by acozzette** [comment]
I'm not 100% sure but I suspect that `innerMessageDescriptorProto.descriptorForType` is returning the descriptor for `DescriptorProto` itself, which would explain why it doesn't have a containing type.

**Comment by noel-yap** [comment]
I guess the real question is whether it's behaving as designed or not. I'm trying to understand the difference between the `Descriptor` and the `DescriptorProto`. Would you know of any docs talking about this difference?

**Comment by acozzette** [comment]
`DescriptorProto` (and `FileDescriptorProto`, etc.) is the proto you can use to represent descriptors and is useful for saving on disk, whereas `Descriptor` has more logic beyond the plain proto. For example, given a `Descriptor` you can query its containing file, which you couldn't do with a plain `DescriptorProto`.

**Comment by elharo** [comment]
seems like error in user program; repoen if there's a reproducible test case
