### ISSUE TITLE
Documentation: Using CMake for non-Windows builds

### ISSUE THREAD

**Issue by JanosGit** [protocolbuffers/protobuf#8008]
**What language does this apply to?**
CMake

**Describe the problem you are trying to solve.**
I want to integrate protobuf in a CMake based cross platform build, especially the library. The documentation of the cmake subfolder only mentions Windows. However, building on MacOS with CMake works as intended for me.

**Describe the solution you'd like**
If possible I'd like to use CMake to perform the build on all platforms :) So I'd really appreciate if the documentation would contain any information on building for different platforms than Windows to be sure that I'm not relying on untested or undefined behaviour.

**Describe alternatives you've considered**
If that's indeed untested or risky for some reasons, I'd like to find some more explanation about that in the cmake subfolders readme on why it's not possible and if this will be possible in future.

**Comment by acozzette** [comment]
CMake should work on other platforms and we were actually thinking about using CMake as a general replacement for the autotools builds, but we do need to update the documentation.

**Comment by kblaschke** [comment]
One caveat here: the new CMake files installed by protobuf itself use a lower-case package name (`protobuf`), while CMake itself ships with a `FindProtobuf.cmake` script that requires an upper-case package name (`Protobuf`). This can cause issues, either the newer scripts not being found on UNIX systems (as filesystems are case-senstive there) or the older ones being used, resulting in an error with `find_package_handle_standard_args` complaining about wrong casing in the package name.

To mitigate the issue, explicitly tell CMake which method you want to use, either the find module or the package config files.

For older protobuf versions without CMake support, or if you don't want to use the newer scripts and have headers/libs in your prefix path list, use:

```cmake
find_package(Protobuf MODULE REQUIRED)
``` 

To use the probotbuf-provided config files, call it like this:

```cmake
find_package(protobuf NO_MODULE REQUIRED)
```

Make writing CMake scripts for builds you don't have under your control a bit iffy though, you'd need to run both commands and see if one of them finds protobuf:

```cmake
find_package(Protobuf MODULE)
if(NOT TARGET protobuf::libprotobuf)
    find_package(protobuf NO_MODULE)
    if(NOT TARGET protobuf::libprotobuf)
        message(FATAL_ERROR "Protobuf not found, but required!")
    endif()
endif()
```
