### ISSUE TITLE
Support repeated / map fields in explicit presence tracking

### ISSUE THREAD

**Issue by kskalski** [protocolbuffers/protobuf#8012]
**What language does this apply to?**
Regarding proto3 optional fields added experimentally in https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Describe the problem you are trying to solve.**
With re-introduction of presence tracking (thank you!) since 3.12 it's now much more convenient to use protobuf for "patch" functionality where the same message format / API can be used to store state, as well as incremental updates to it. However it's still not a complete system, since repeated and map fields do not support presence tracking, thus there is no way to distinguish repeated/map field not being set and being set to empty value.

My use case is for proto3 message to represent a "patch" / "diff" / "override" of other message, where fields set on given message are treated as higher priority / updated values of prior/existing message. When repeated field in the new message is set to non-empty value there is no problem, I can replace the existing value with new collection, but when new message has empty repeated field, there is no way to distinguish whether the empty collection is intended as new value or simply lack of update.

**Describe the solution you'd like**
repeated and map fields should support HasField functionality, depending on language 'null' could be used to represent lack of presence for given field.

**Describe alternatives you've considered**
- not using repeated fields, or wrapping them in sub-messages
- using external mechanisms for tracking presence of repeated/map fields (separate / field mask field)
- using a sentinel "special" value inside repeated field collection to mark "empty" collection (in this scenario empty repeated field could be interpreted as no-presence of that field and singleton with sentinel value could be interpreted as present "empty" value)

**Additional context**
I suppose this feature is currently not supported due to wire-format used for repeated fields (and map fields, which AFAIK are simply repeated key-value pairs underneath), which doesn't explicitly track the repeated collection itself and instead relies on elements using the repeated field's number to be appended to the collection in the object. Because of this design unfortunately I don't see a way to add such feature while keeping binary compatibility with repeated fields not using optional presence tracking.

I suppose the only way to implement it would be to add some special marker for optional repeated fields in the wire format. Anyway, it would be great to have this feature considered or to get your opinions on that - this would bring much more completeness to the API exposed by proto3. For "patch" functionality specifically it's still not the end of the topic, since that needs to also represent "field removal", however it's easier to settle on workarounds and conventions for that than solving repeated field assignment / presence checks.

**Comment by acozzette** [comment]
I'm afraid we will not be able to support this directly, since as you mentioned the wire format has no inherent way to represent presence for repeated fields and maps. A separate field mask might be the best way to go.

**Comment by JustinEdwardKennedy** [comment]
Does anyone else prioritize having field presence for repeated fields and maps over the current repeated/map wire format? Is it possible (in proto4, for example) to reconsider the repeated/map wire format in order to support the `optional` flag for maps and repeated fields, even though it will sacrifice the benefits of the current wire format?

Apologies if the question is naive, I recently joined the community and am working through gRPC Update RPCs and would prefer not to use FieldMasks. I have read and am aware of https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/field_presence.md but don't have too much context on historical decisions with regards to field precense in the Protobuf community.

**Comment by elharo** [comment]
Closing per @acozzette 's comment
