### ISSUE TITLE
[3.14.0RC1] pecl package is corrupted

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#8016]
Looks like some file are missing
```

/dev/shm/BUILD/php-pecl-protobuf-3.14.0~RC1/NTS/message.c:1310:10: fatal error: wkt.inc: No such file or directory
 1310 | #include "wkt.inc"
      |          ^~~~~~~~~
compilation terminated.

```

**Comment by remicollet** [comment]
And again notes are wrong in package.xml  as already reported in #7813

**Comment by haberman** [comment]
I think the bug is that https://github.com/protocolbuffers/protobuf/pull/7944 didn't add `wkt.inc` to https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/package.xml

**Comment by haberman** [comment]
We should change our testing pipeline to build the PECL extension using the same release-to-pecl process that we use for releases. Otherwise we have no validation that `package.xml` is correct until we release.

**Comment by fiboknacky** [comment]
Thanks for the update. When is the approx. time for fixing this?

**Comment by haberman** [comment]
I just sent a fix out here: https://github.com/protocolbuffers/protobuf/pull/8022

Once the fix is merged we can cut an -rc2, which will hopefully go out today.

**Comment by haberman** [comment]
This was fixed in https://github.com/protocolbuffers/protobuf/pull/8022.
