### ISSUE TITLE
[3.14.0RC1] bad version reported

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#8017]
```
$ php --ri protobuf 
protobuf

Version => 3.13.0

Directive => Local Value => Master Value
protobuf.keep_descriptor_pool_after_request => 0 => 0

```

Obviously  `protobuf_module_entry` in https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/protobuf.c#L314 should use `PHP_PROTOBUF_VERSION` defined in https://github.com/protocolbuffers/protobuf/blob/master/php/ext/google/protobuf/protobuf.h#L72

**Comment by acozzette** [comment]
@remicollet Thank you for flagging this issue, I sent out #8025 to fix this.
