### ISSUE TITLE
Questions about version 3.8.0

### ISSUE THREAD

**Issue by jinyaohui** [protocolbuffers/protobuf#8018]
Version: 3.8.0
Language: C++

Linux EulerOS release 2.0

Python 3.7.5

Hello, we are using protobuf 3.8.0 version, please ask, if this version has security vulnerabilities, will you still maintain it? （Currently no vulnerabilities have been found），Looking forward to your reply.

**Comment by acozzette** [comment]
No, we are not actively maintaining 3.8 anymore. We rarely make significant breaking changes, so it is generally best to upgrade to the most recent version.
