### ISSUE TITLE
[3.14.0RC1] strange changes

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#8019]
Is it tag from the right branch / sources ?

Looks like major changes introduced in 3.13 were reverted:

* Relection changes in 3.13 https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-protobuf.git/diff/REFLECTION?id=0226e1053903de87d8040904d15d1a07ddf12519 (From 54 to 14 classes)
* Reflection changes in 3.14 https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-protobuf.git/diff/REFLECTION?id=14bb07db224f6e39932fefd304ff337438f3e57e (From 14 to 56 classes)

Compatibility with PHP 8.0 is broken again.

**Comment by haberman** [comment]
The major changes in 3.13 were not reverted. What you are seeing is the result of https://github.com/protocolbuffers/protobuf/pull/7944, which does effectively revert one small part of the 3.13 changes. The well-known types are now implemented in native C again, in an effort to avoid the overhead of autoloading PHP for them. But all of the major architectural changes to the C extension and the corresponding performance gains should still be present in 3.14.0RC1.

Thanks for the note about PHP 8.0 compatibility. We haven't been able to get PHP8.0 testing into our pipeline yet.

**Comment by stevesweets** [comment]
Do you have some idea when php8 support may arrive?

**Comment by haberman** [comment]
PHP8 support is fixed in master (https://github.com/protocolbuffers/protobuf/pull/8105) and will be a part of the next release.
