### ISSUE TITLE
Can we support nested prototxt?

### ISSUE THREAD

**Issue by CHOcho-quan** [protocolbuffers/protobuf#8038]
A single prototxt can be very long now and it's not so readable.

Can we make prototxt nested with another prototxt ?

example prototxt like
`name: something`
`type: something`
`data: {another.prototxt}`

in another.prototxt defines a data message. And the prototxt can be separated to components.

Thank you for your attention.

**Comment by elharo** [comment]
Changes to textproto format are not being considered here.
