### ISSUE TITLE
Runtime Exception at deployed .Net Framework application: missing assembly that is not required

### ISSUE THREAD

**Issue by SwissKnife64** [protocolbuffers/protobuf#8041]
**Version:** master/v3.14.0-rc3, master/v3.13.0
**Language:** C#
**Operating System:** Windows 10 Enterprise LTSC, 1809, OS build 17763.1577
**Development Environment:** Visual Studio 2019, WindowsForm Application, .Net Framework 4.8

**What did you do?**
1. Upgrade to NuGet package "Google.Protobuf v3.14.0-rc3"
2. Clean and Rebuild solution with incremented assembly version
3. make windows installer project with "Microsoft Visual Studio Installer Project"
4. install on target machine
5. Start application and call module that uses Google.ProtoBuf

**What did you expect to see**
application running without exception

**What did you see instead?**
application crash with runtime exception:

'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)', Exception='System.BadImageFormatException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at System.Span`1..ctor(T[] array)
   at Pt10PbMsg.ToolCommand.WriteTo(CodedOutputStream output)
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at PowerToolServiceInterface.BluetoothDongle.MakeToolCommandFrameParameterRead(UInt32 parameterId)
   at PowerToolConnect.ConnectPt10.GetVersion(UInt16 versionId)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
The application runs without exception with Google.ProtoBuf version <= 3.12.4
Application crash with exception with Google.ProtoBuf version >= 3.13.0

Starting with V3.13.0, there is a NuGet dependency added for ".NETStandard=v2.0" to the assembly "System.Runtime.Compiler.Unsafe (>=4.5.2), but this is NOT my framework used, I use .NETFramwork V4.8

**Comment by jtattermusch** [comment]
Can you please provide an example project that reproduces the issue? (ideally as e.g. a github repository).

**Comment by jtattermusch** [comment]
CC @JamesNK  @JunTaoLuo

**Comment by SwissKnife64** [comment]
I will try to make a minimal project with this issue in the next days.

**Comment by SwissKnife64** [comment]
I have made a minimal Project for Visual Studio 2019. 
The project uses the extension "Microsoft Visual Studio Installer Projects"
The NuGet packages was added as "app.config" first and then updated to "References"
The installed application crashes when using NuGet "Google.Protobuf"  3.13 or higher, it works with v3.12.4 and older.

The complete VS Project is here
https://drive.google.com/file/d/1-smW1Nvsx4gmLJaaJDCB0qxhpSO1iG4s/view?usp=sharing

**Comment by sturegus** [comment]
I have the exact same problem. I use .NET Framework V4.5.2. Any workarounds available?
Works fine when running Debug version from Visual Studio, but the installed release version (vdproj) throws that same exception.

**Comment by sturegus** [comment]
Actually this is a bug in the Installer Project (vdproj):
https://stackoverflow.com/questions/58717068/how-to-make-visual-studio-setup-project-detect-nuget-dependencies-consistent-wit

I got it working by making some very ugly workarounds where the csproj copies "manually" the correct dependencies from the .nuget lib folders instead of using the once that are automatically added by vdproj.
