### ISSUE TITLE
MapPair key should not be const.

### ISSUE THREAD

**Issue by deeplearningrobotics** [protocolbuffers/protobuf#8054]
The key in `MapPair` should [not be const](https://github.com/protocolbuffers/protobuf/blob/7b352d318b9ae8f65ddc85b7eb7e9921911cec6f/src/google/protobuf/map.h#L352). It makes for example using `std::transform` etc. impossible.

```

  google::protobuf::MapPair<int, int> mm(1,2);
  google::protobuf::MapPair<int, int> nn(1,2);

  nn = mm; // Does not compile!
  
  google::protobuf::Map<int, int> map;
  map.insert(1,1);
  
  *map.begin() = nn; // Does not compile!
```

**Comment by TeBoring** [comment]
http://www.cplusplus.com/reference/unordered_map/unordered_map/

Protobuf's map behaves exactly the same as `std::unordered_map`, which also uses const for key.
