### ISSUE TITLE
Different output on casting proto object to string in Go and Py vs JavaScript

### ISSUE THREAD

**Issue by chautob0t** [protocolbuffers/protobuf#8058]
I am using the following command to compile proto files to use with my JavaScript project - 
```
./protoc \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --js_out="import_style=commonjs,binary:${OUT_DIR}" \
    --ts_out="${OUT_DIR}" \
    *.proto
```

Command used for golang files generation - 
`./protoc -I protos/ protos/myFile.proto --go_out=plugins=grpc:./protocol/`

And a similar one for python files generation.

In golang I use the following to marshal the proto to string and push it to SQS.
`out := proto.MarshalTextString(&myProtoObject)`

The output produced by the above statement is this - 
```
ID: "someID"
name: "someName"
messageType: ABC
push {
  template: "https://some.url"
  token: "someToken"
  context: "{\"first_name\": \"JOHN\", \"designation\": \"XYZ\", \"company_name\": \"ABC Company\"}"
  waterfallConfig {
  }
  expiry: 1605010281
  userID: "someUserId"
  extraPayload: "{\"data\": {\"redirect\": \"ENDPOINT\"}}"
}
sentByID: "test"
client: "test-c;ient"
triggeredOn: 1604405481
platform: PQR
```

When I do the same in python, the output to string is the same and it work fine. 

For JavaScript the output format is completely different and not usable by my application - 
I have use `myProtoObject.toString()` which produces the following output - 

`someID,Test,,,https://test.url,8888881111,{},,,1605613930,someID2,,,someID3,Test Client,,1605009130,1`

And `myProtoObject.toObject()` which I then pass to `JSON.Stringify()` before pushing to SQS, it's output is -

```
{
  "id": "someID",
  "name": "Test",
  "messagetype": 0,
  "sms": {
    "template": "https://some.url",
    "mobile": "8888881111",
    "context": "{}",
    "waterfallconfig": {
      "priority": 0,
      "offsettime": 0
    },
    "expiry": 1605614118,
    "userid": "someID2"
  },
  "sentbyid": "someID3",
  "client": "Test Client",
  "waterfalltype": 0,
  "triggeredon": 1605009318,
  "platform": 1
}
```

Both of these formats are not unmarshalled by the consumer application. How can I generate text representation of the first kind (Golang and Python) from JavaScript proto object?

**Comment by acozzette** [comment]
The first output you posted is called "text format" and is not supported by the Javascript implementation. I think your best bet is probably to use switch to using the binary format instead of text format. If for some reason the payload has to be expressed in UTF-8 or ASCII, you can always base64-encode the binary format.
