### ISSUE TITLE
Pkg-config - Libs - No "-pthread"

### ISSUE THREAD

**Issue by RaMdsC** [protocolbuffers/protobuf#8059]
Version: 7b352d318b9ae8f65ddc85b7eb7e9921911cec6f
OS: Ubuntu 18.04.2, Linux 4.15
Toolchain: G++ 7.4

### Context

Version 4b389fad575f830fee4a39287ebfd53a6f0862b2 removed PTHREAD_CFLAGS from "Libs" in protobuf.pc.in and protobuf-lite.pc.in. This results in "-pthread" not passed to the linker.

GCC manuals from version 7+ state, for "-pthread":
"You should use this option consistently for both compilation and linking"

Due to this, ldd shows no libpthread being linked, which results in segfaults on launching threads.

### Possible solutions

Update "m4/ax_pthread.m4" to use latest version. Have not verified if latest version adds "-pthread" to PTHREAD_LIBS, I'd expect so. Can this be a submodule so this is up-to-date with the GNU repo?
Otherwise, passing PTHREAD_CFLAGS on linking would also work.

**Comment by RaMdsC** [comment]
Updating to use "ax_pthread.m4" from version fd1d25c14855037f6ccd7dbc7fe9ae5fc9bea8f4 of https://git.savannah.gnu.org/git/autoconf-archive.git adds "-lpthread" to PTHREAD_LIBS, which solves this issue.

**Comment by acozzette** [comment]
Thanks for the bug report, I sent out #8077 to upgrade ax_pthread.m4.
