### ISSUE TITLE
Python: AttributeError: 'DESCRIPTOR' when parsing Vision API response.full_text_annotation to TextAnnotation() 

### ISSUE THREAD

**Issue by nodje** [protocolbuffers/protobuf#8060]
I've just upgraded from 
```
google-cloud-vision==1.0.0
protobuf==3.13.0
```
to
```
google-cloud-vision==2.0.0
protobuf==3.14.0
proto-plus==1.11.0
```
and my parsing code doesn't work anymore:

```
from google.cloud.vision_v1 import TextAnnotation
from google.protobuf.text_format import Parse


def parse_string_to_text_annotation(text) -> TextAnnotation:
    text_annotation = TextAnnotation()
    Parse(text, text_annotation)
    return text_annotation
```

I post this here  as I haven't been able to find a single reference to this problem, except https://github.com/protocolbuffers/protobuf/issues/7941 but it didn't help me.

I just don't know why I get this error now when it's working fine with the previous version.
I've tried 

I really hope the `response.full_text_annotation` provided by the previous Vision API are still compatible with the new version.

**Comment by acozzette** [comment]
What kind of error are you getting?

**Comment by nodje** [comment]
I get `AttributeError: 'DESCRIPTOR'` just like https://github.com/protocolbuffers/protobuf/issues/7941

Would it be useful if I provided a full stacktrace? I thought he error would be clearly identifiable from 1.0->2.0 migration context.

**Comment by IanMHoffman** [comment]
I would look at this answer I missed it the first time but he is spot on for me. I am assuming Parse will have to be changed to the new style of Proto Plus, but then again I am not sure I am using JSON not text format.
https://github.com/protocolbuffers/protobuf/issues/7941#issuecomment-709586668

**Comment by nodje** [comment]
Yeah Proto Plus definitely introduces the problem.

I just have no idea how to solve it, and I can't find any reference to this in the documentation anywhere...

**Comment by acozzette** [comment]
The protobuf team actually has no involvement in Proto Plus (I had never heard of it until this thread). You might want to talk to the owners of Proto Plus and/or the Vision API.
