### ISSUE TITLE
Add support for zOS

### ISSUE THREAD

**Issue by mahdi-hm** [protocolbuffers/protobuf#8061]
I faced with numerous problem while I was trying to compile and run protocol buffer on zOS since tools like autoconf, cmake and configure are not fully available on zOS as in most unix. Having zOS support would be a nice feature.

**Comment by TeBoring** [comment]
Could you send us a fix.

**Comment by mahdi-hm** [comment]
> Could you send us a fix.

I created a PR for that https://github.com/protocolbuffers/protobuf/pull/8087
I removed the Makefile and one source file from it as requested btw

**Comment by elharo** [comment]
Seems google is not able to maintain this patch. A fork would be required.

**Comment by mahdi-hm** [comment]
> Seems google is not able to maintain this patch. A fork would be required.

Thanks, A fork will be created for IBM zOS (mainframe) users
