### ISSUE TITLE
macOS Apple M1/Arm Support

### ISSUE THREAD

**Issue by etmartinkazoo** [protocolbuffers/protobuf#8062]
Are there plans to add macOS Apple M1/Arm Support. I'd like to install Mosh on my machine but Protocol Buffer is a required dependency. I imagine there will be a greater and greater demand for compatibility.

**Comment by acozzette** [comment]
What build error are you getting?

**Comment by etmartinkazoo** [comment]
The only Arm based package that I can see on the release page is `protoc-3.14.0-linux-aarch_64.zip`.

When adding the `protoc` binary to my PATH, I receive a `cannot execute binary file` when executing `protoc --version` in my terminal for example.

**Comment by acozzette** [comment]
It might take us some time to be able to start publishing precompiled binaries for Apple ARM machines, but you should still be able to use protobuf by building from source.

**Comment by jurmous** [comment]
Why was this issue closed? I still see no precompiled binaries for Mac arch 64? I am particularly interested in a precompiled Java build. 

```
   > Could not find protoc-3.14.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.14.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protoc/3.14.0/protoc-3.14.0-osx-aarch_64.exe
```

**Comment by Eric-Arellano** [comment]
I'd love to see pre-compiled binaries for macOS Arm too, although I know that might be non-trivial. Is there anything a first-time contributor might be able to help with?

**Comment by NielsKSchjoedt** [comment]
> It might take us some time to be able to start publishing precompiled binaries for Apple ARM machines, but you should still be able to use protobuf by building from source.

@acozzette how would you do that - I'm unable to do so: https://github.com/protocolbuffers/protobuf/issues/8372

**Comment by studyzy** [comment]
Why closed this issue?

**Comment by askdesigners** [comment]
LOL. Classic Google move.

**Comment by nresare** [comment]
Having this Just Work™️ would be fantastic, and I think it makes sense to keep this issue open until then.

While waiting, I have had success by using the `protoc` binary from brew:
* follow instructions on https://brew.sh to install brew
* run `brew install protobuf` in a terminal.
This should result in `protoc` being available in your path. Note that with the default zsh, the default shell on recent macOS, one needs to type the command `rehash` to detect newly installed binaries or changes to the `PATH` environment variable.

**Comment by bbeaupain** [comment]
Would really love to see some support for this - protobuf is an awesome project, but there are a lot of automated build systems (Maven for example) that break when including standard protobuf dependencies. M1 is most likely here to stay for quite a while and I'd be happy to provide remote access to an M1 machine if Google doesn't have them readily available.

**Comment by yuzawa-san** [comment]
A stopgap solution was merged https://github.com/protocolbuffers/protobuf/pull/8557 However this issue is about true native support, rather than reusing the x86_64 artifact, so I feel this issue should be reopened.

**Comment by vborbely** [comment]
What I did for a quick fix is that, I opened the project in Android Studio. I opened the Gradle section on the right, and looked for the problematic package (_flutter_blue_ package in my case).
Then I right clicked -> Open Gradle config -> changed the 2 parts show below:

![flutter_blue_protobuf](https://user-images.githubusercontent.com/29902370/128195156-aec6325b-c83e-4348-9ad4-d86549774f6b.png)

When I did a "flutter pub get" it did not appear. However, I feel it will go away with a "flutter clean".

I hope this helped for someone.

Good luck,
Viktor

**Comment by toffentoffen** [comment]
In the issue https://github.com/grpc/grpc-java/issues/8724 I found a workaround for using grpc-java M1/Arm compatible artifacts. For compatibility reasons on which grpc-java relies on, only protoc 3.17.3 can be used.

**Comment by cmal** [comment]
Can protoc 2.x support m1 chip?

**Comment by perezd** [comment]
Sorry, no. Please upgrade to a newer compiler for support for M1.

**Comment by teejae** [comment]
can we keep this issue open until there's support for m1 in the default releases?

**Comment by perezd** [comment]
I've opened this issue: https://github.com/protocolbuffers/protobuf/issues/9397

**Comment by MDeMel-Dev** [comment]
This worked for my team:

protobuf {

    protoc {
        artifact = if (project.hasProperty("protocPlatform")) {
            "com.google.protobuf:protoc:${protobuf_version}:osx-x86_64"
        } else {
            "com.google.protobuf:protoc:${protobuf_version}"
        }
    }

    generateProtoTasks {
        all().forEach { task ->

            task.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}

// It checks if your pc is mac silicon or not and adds the correct configuration.

**Comment by Eric-Arellano** [comment]
Hi, thanks so much for releasing Apple Silicon binaries at https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.19.2/! 

Would it be possible to please include a macOS ARM zip file with the GitHub release too, for folks who prefer downloading the zip file? https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4

**Comment by Eric-Arellano** [comment]
For anyone who messed it, macOS Arm is released via GitHub! https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.1

Thank you so much to the folks who made this happen :)

**Comment by rkmaul** [comment]
> What I did for a quick fix is that, I opened the project in Android Studio. I opened the Gradle section on the right, and looked for the problematic package (_flutter_blue_ package in my case). Then I right clicked -> Open Gradle config -> changed the 2 parts show below:
> 
> ![flutter_blue_protobuf](https://user-images.githubusercontent.com/29902370/128195156-aec6325b-c83e-4348-9ad4-d86549774f6b.png)
> 
> When I did a "flutter pub get" it did not appear. However, I feel it will go away with a "flutter clean".
> 
> I hope this helped for someone.
> 
> Good luck, Viktor

Mantep mas bro

**Comment by muava12** [comment]
> What I did for a quick fix is that, I opened the project in Android Studio. I opened the Gradle section on the right, and looked for the problematic package (_flutter_blue_ package in my case). Then I right clicked -> Open Gradle config -> changed the 2 parts show below:
> 
> ![flutter_blue_protobuf](https://user-images.githubusercontent.com/29902370/128195156-aec6325b-c83e-4348-9ad4-d86549774f6b.png)
> 
> When I did a "flutter pub get" it did not appear. However, I feel it will go away with a "flutter clean".
> 
> I hope this helped for someone.
> 
> Good luck, Viktor

I can't find thet folder inside android/app/

**Comment by muava12** [comment]
> > What I did for a quick fix is that, I opened the project in Android Studio. I opened the Gradle section on the right, and looked for the problematic package (_flutter_blue_ package in my case). Then I right clicked -> Open Gradle config -> changed the 2 parts show below:
> > ![flutter_blue_protobuf](https://user-images.githubusercontent.com/29902370/128195156-aec6325b-c83e-4348-9ad4-d86549774f6b.png)
> > When I did a "flutter pub get" it did not appear. However, I feel it will go away with a "flutter clean".
> > I hope this helped for someone.
> > Good luck, Viktor
> 
> Mantep mas bro

Kok saya gak nemu folder flutter_blue ya di dalam folder android??

**Comment by leonovi** [comment]
> Having this Just Work™️ would be fantastic, and I think it makes sense to keep this issue open until then.
> 
> While waiting, I have had success by using the `protoc` binary from brew:
> 
>     * follow instructions on https://brew.sh to install brew
> 
>     * run `brew install protobuf` in a terminal.
>       This should result in `protoc` being available in your path. Note that with the default zsh, the default shell on recent macOS, one needs to type the command `rehash` to detect newly installed binaries or changes to the `PATH` environment variable.

It worked for me, thank you 😊

**Comment by azizur-rahaman** [comment]
what I have done,
Open android folder in Android Studio > from left bar open gradle view >  from here find flutter_blue and then right on it and click config > change it with latest version 

you will get the latest version from here: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.18.0/


<img width="849" alt="Screenshot 2023-11-03 at 5 25 34 PM" src="https://github.com/protocolbuffers/protobuf/assets/91342806/a1b83552-a478-4978-91d7-cc1fc3edcd5f">
