### ISSUE TITLE
support for code generation by urls

### ISSUE THREAD

**Issue by danielleiszen** [protocolbuffers/protobuf#8067]
**What language does this apply to?**
I do not know the internal architecture of protoc, but I guess loading .proto files are common for all languages. So it should apply to all supported plugins. (At least that's how I would do it)

**Describe the problem you are trying to solve.**
Sharing .protoc files between different projects in a microservice arrangement is challenging. Even if someone owns all the client and server ends its not obvious to share the same proto definitions between them. Furthermore, protoc's dumbness about relative and absolute paths does not help. If a service publishes its interface definitions on a HTTP endpoint that can be downloaded by clients, however the process is complicate to automatize. The trivial solution would be if the code generation mechanism used the HTTP endpont (URL) directly for generation.

**Describe the solution you'd like**
Generating a single proto file with a plugin (plugin is a placeholder here):
`protoc --plugin_out=plugin_specific_stuff http://my.service/proto/service_definition.proto`
Searching for imports using a "wildcard" url:
`protoc --plugin_out=plugin_specific_stuff --proto_path=http://protos.google.com/well-known-types/ http://my.service/proto/service_definition.proto`
In this case the generator would use the url specified at --proto_path to find any import in the service_definition.proto file by appending the given url with the proto file name such as 
`http://protos.google.com/well-known-types/google/protobuff/empty.proto`
for an import defined as
`import "google/protobuf/empty.proto";`
[note: the http://protos.google.com/well-known-types/ url is just an idealistic example]

**Additional context**
As GRPC becomes the de facto standard for interservice communication and as being supported by frameworks like .NETCore or Flutter it is evidently going to be the standard for client-server communication also - it should have bigger and better support in terms of tooling and automatization. The difficulties that protoc has at the moment will avert developers coming from convenient development environments from using it and therefore slowing down adoption of this great technology. I think it is inevitable to provide better support for the most common usage scenarios. If my case seems to be one, thank you for considering my suggestions. Anyways, great work, thanks.

**Comment by elharo** [comment]
Inside google this problem is completely solved by the source repository. .proto files are source code and can be shared just like .java files, .xml files, .py files or anything else. This doesn't seem like a feature that belongs in the layer of the proto library itself.
