### ISSUE TITLE
Makefile dependencies appear to be incompletely specified for conformance/

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#8069]
**What version of protobuf and what language are you using?**
Version: master
Language: all (just building the package)

**What operating system (Linux, Windows, ...) and version?**
Linux (any it seems)

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. clean checkout
2. ./autogen.sh
3. ./configure
4. make -C ./src -j 50 all
5. make -C ./conformance -j 2 conformance-test-runner

**What did you expect to see**

Builds work

**What did you see instead?**

Step 5 some times fails for missing generated proto headers.

**Anything else we should know about your project / environment**

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blame/master/conformance/Makefile.am#L221-L224

Is this issue related to this?
