### ISSUE TITLE
Fortify flags memory leak

### ISSUE THREAD

**Issue by jwmelto** [protocolbuffers/protobuf#8072]
Microfocus Fortify is (sadly) the current standard static code analysis tool for the department of defense. Among the many false positives it detects, this construct does appear to be a real memory leak.

https://github.com/protocolbuffers/protobuf/blob/d7a26435fb36b61d742c053407e3a61fb1012706/src/google/protobuf/repeated_field.h#L1572

`new_rep` is last referenced on line line 1585, and I can't see where it is assigned to any RAII type or otherwise managed before it goes out of scope.

If I'm missing something, I'll mark this as yet another false-positive and move on.

**Comment by acozzette** [comment]
The logic here is a bit convoluted but new_rep does end up getting deleted. `arena_or_elements_` stores `new_rep->elements` [here](https://github.com/protocolbuffers/protobuf/blob/d7a26435fb36b61d742c053407e3a61fb1012706/src/google/protobuf/repeated_field.h#L1583), and the destructor deletes it [here](https://github.com/protocolbuffers/protobuf/blob/d7a26435fb36b61d742c053407e3a61fb1012706/src/google/protobuf/repeated_field.h#L1210), using the `rep()` member function which subtracts an offset from `arena_or_elements_` to get back a pointer to the `Rep`.

**Comment by jwmelto** [comment]
Could you walk through it in a bit more detail? The line in question is only reached if the `arena` is null. Here is a naked new, assigned to a pointer, and no initialization. The pointer is cast, but no constructor fires. On line 1583, where `arena_or_elements_` is assigned, it has no value.

Fortify is incredibly stupid, and protobuf gives it fits, but I'm just not able to justify this finding yet.

**Comment by jwmelto** [comment]
Hmmm. Looks like `rep()` is ... questionable, but I guess I see how it's working. `new_rep->elements` is an array, so it is a valid address to assign on 1583. "Clever" pointer arithmetic lets you back up to the base address.

**Comment by acozzette** [comment]
Right, `new_rep->elements` is basically equivalent to `new_rep + 8`, so we can get back the original pointer by subtracting 8 again. (It would be different on 32-bit platforms but you get the idea.)
