### ISSUE TITLE
bufferSize must be >= 0

### ISSUE THREAD

**Issue by 1wpro2** [protocolbuffers/protobuf#8075]
**What language does this apply to?**
Java

If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Java

**Describe the problem you are trying to solve.**

The current type for serializedSize is `int`, which has a size limit of 2,147,483,648. For a larger sized data, it will throw out
`bufferSize must be >= 0` during serialization.

**Describe the solution you'd like**

instead of 
```
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;
...
```

Can we change to `long`

```
    public int getSerializedSize() {
      **long** size = memoizedSize;
      if (size != -1) return size;
...
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ObsidianMinor** [comment]
This is a constraint imposed by the protobuf format. A length-delimited value's length is an int32, so this can't be changed without breaking the format.
