### ISSUE TITLE
Why use 64-bit representation for negative numbers

### ISSUE THREAD

**Issue by mastery001** [protocolbuffers/protobuf#8079]
```
public final void writeInt32NoTag(int value) throws IOException {
      if (value >= 0) {
        writeUInt32NoTag(value);
      } else {
        // Must sign-extend.
        writeUInt64NoTag(value);
      }
    }
```

why negative integers must sign-extend？

**Comment by mastery001** [comment]
@jtattermusch  

When the field is defined as sint32, some values will overflow (the value will become negative at this time), such as Integer.MAX_VALUE / 2 + 1, at this time, the writeUInt32NoTag method is directly called to write（@see https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L399-L401）：

```
  /** Write a {@code sint32} field to the stream. */
  public final void writeSInt32NoTag(final int value) throws IOException {
    writeUInt32NoTag(encodeZigZag32(value));
  }
```

So my question is, why the treatment of negative numbers is different when the type is int32 and sint32. If the type is int32, negative numbers will be written to 10 bytes; but when the type is sint32, negative numbers are only written 5 bytes。

**Comment by jtattermusch** [comment]
this is as per protobuf wire format:

*If you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer.*
https://developers.google.com/protocol-buffers/docs/encoding

I guess the exact reason is that there's only one "varint" wire type in protobuf wire format and  you need to be able to decode a value even without prior knowledge of whether something is int32 or int64
 https://developers.google.com/protocol-buffers/docs/encoding#varints 
(but I'm actually not an expert on protobuf wire format design - perhaps other would have a better explanation).

**Comment by mastery001** [comment]
According to the current design of Protobuf, the data can be decoded in the absence of type information;

But in fact, there is type information in the code generated by the proto file, so if I hold the type information of the field, can I not need to store 10 bytes?

**Comment by jtattermusch** [comment]
> According to the current design of Protobuf, the data can be decoded in the absence of type information;
> 
> But in fact, there is type information in the code generated by the proto file, so if I hold the type information of the field, can I not need to store 10 bytes?

Pragmatically, it's quite simple - if you need negative values to not be 10bytes long when encoded, just use the `sint32` type and you're done.

**Comment by mastery001** [comment]
Yep I understand it. thanks！！
