### ISSUE TITLE
How to use the new Span API on the C# project

### ISSUE THREAD

**Issue by felipejfc** [protocolbuffers/protobuf#8084]
I'm trying to do the following:

I have a C# application that uses a C shared library and does a pinvoke to this C lib, it then receives a IntPtr pointing to data allocated in C side containing a protobuf message.

I'm trying to build this message on C# side by using Message.MergeFrom() on the C# side but without allocating new memory, just accessing directly the unmanaged memory from C side.

I thought this would be possible now since https://github.com/protocolbuffers/protobuf/pull/5888 but I'm having a hard time trying to figure out how.

Any help?

Best!

**Comment by jskeet** [comment]
Removed assignment from myself - I haven't looked at the Span API in detail with protobuf and don't have time to take on work outside my main projects right now.

**Comment by jtattermusch** [comment]
Note that general usage questions shouldn't be posted here, just actual issues.

Nevertheless: to parse from unmanaged memory, what you want to do is to first create a Span<byte> from the unmanaged pointer to the data. (That needs to be done under `unsafe` block). After that you can just call, 
e.g. `YourMessage.Parser.ParseFrom(ReadOnlySequence<byte> data)`.  A read only sequence can be created allocation-free from a Span<byte>.  

FTR the API was added here: https://github.com/protocolbuffers/protobuf/pull/7351

**Comment by felipejfc** [comment]
Sorry and thanks @jtattermusch. Can you say how do I create the ReadOnlySequence from the Span? I can't find any method for doing so...

I'm trying like:

```
Span<byte> data = new Span...
Protos.Request.Parser.ParseFrom(new ReadOnlySequence<byte>(data));
```

But this isn't allowed: Argument 1: cannot convert from 'System.Span<byte>' to 'System.ReadOnlyMemory<byte>' csharp(CS1503)

**Comment by jtattermusch** [comment]
> Sorry and thanks @jtattermusch. Can you say how do I create the ReadOnlySequence from the Span? I can't find any method for doing so...
> 
> I'm trying like:
> 
> ```
> Span<byte> data = new Span...
> Protos.Request.Parser.ParseFrom(new ReadOnlySequence<byte>(data));
> ```
> 
> But this isn't allowed: Argument 1: cannot convert from 'System.Span' to 'System.ReadOnlyMemory' csharp(CS1503)

Sorry, I spoke too soon.

Yes, you need to create a ReadOnlyMemory<byte> from an unmanaged pointer (as ReadOnlySequence doesn't take Span).
That's done by subclassing a MemoryManager:
https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorymanager-1?view=net-5.0

Examples:
https://github.com/protocolbuffers/protobuf/blob/d7a26435fb36b61d742c053407e3a61fb1012706/csharp/src/Google.Protobuf.Test/ByteStringTest.cs#L392

https://github.com/grpc/grpc/blob/a1ad4800da2bb02c843bdaea8fb06518916b6fba/src/csharp/Grpc.Core/Internal/SliceMemoryManager.cs#L32
