### ISSUE TITLE
Submodule googletest will not update

### ISSUE THREAD

**Issue by bobhancock** [protocolbuffers/protobuf#8085]
**What version of protobuf and what language are you using?**
master/3.13.0

Language: C++/Python

OS: Linux

Python 3.7.0, 3.8.5, 3.9.0

  pushd "${_protobuf_dir}"
  git submodule update --init --recursive

  ./autogen.sh 
  
   ./configure \
    CXXFLAGS="-std=c++11 -fPIC -m64" \
    LDFLAGS="-static-libgcc -static-libstdc++ -s" \
    --disable-shared 

  jobs="$(lscpu -p | grep '^[0-9]' | wc -l)"

 make -j"${jobs}" \
 
 make dist 
 
   1 make  dist-gzip am__post_remove_distdir='@:'
  2 make[1]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf'
  3 make  distdir-am
  4 make[2]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf'
  5 if test -d "protobuf-3.13.0"; then find "protobuf-3.13.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "pro    tobuf-3.13.0" || { sleep 5 && rm -rf "protobuf-3.13.0"; }; else :; fi
  6 test -d "protobuf-3.13.0" || mkdir "protobuf-3.13.0"
  7  (cd src && make  top_distdir=../protobuf-3.13.0 distdir=../protobuf-3.13.0/src \
  8      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
  9 make[3]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/src'
 10 make  distdir-am
 11 make[4]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/src'
 12 make[4]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/src'
 13 make[3]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/src'
 14  (cd conformance && make  top_distdir=../protobuf-3.13.0 distdir=../protobuf-3.13.0/conformance \
 15      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 16 make[3]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/conformance'
 17 make  distdir-am
 18 make[4]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/conformance'
 19 make[4]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/conformance'
 20 make[3]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/conformance'
 21  (cd benchmarks && make  top_distdir=../protobuf-3.13.0 distdir=../protobuf-3.13.0/benchmarks \
 22      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 23 make[3]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/benchmarks'
 24 make  distdir-am
 25 make[4]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/benchmarks'
 26 cp ./cpp/cpp_benchmark.cc gogo/cpp_no_group/cpp_benchmark.cc
 27 sed -i -e "s/\#include \"datasets/\#include \"gogo\/cpp_no_group\/datasets/g" gogo/cpp_no_group/cpp_benchmark.cc
 28 sed -i -e "s/\#include \"benchmarks.pb.h/\#include \"gogo\/cpp_no_group\/benchmarks.pb.h/g" gogo/cpp_no_group/cpp_be    nchmark.cc
 29 touch generate_cpp_no_group_benchmark_code
 30 make[4]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/benchmarks'
 31 make[3]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/benchmarks'
 32  (cd third_party/googletest && make  top_distdir=../../protobuf-3.13.0 distdir=../../protobuf-3.13.0/third_party/goo    gletest \
 33      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 34 make[3]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest'
 35 make  distdir-am
 36 make[4]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest'
 37 :
 38 test -d "../../protobuf-3.13.0/third_party/googletest" || mkdir "../../protobuf-3.13.0/third_party/googletest"
 39  (cd googletest && make  top_distdir=../../../protobuf-3.13.0 distdir=../../../protobuf-3.13.0/third_party/googletes    t/googletest \
 40      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 41 make[5]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googletest'
 42 make  distdir-am
make[6]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googletest'
 44 mkdir -p "./fused-src"
 45 chmod -R u+w "./fused-src"
 46 rm -f "./fused-src/gtest/gtest-all.cc"
 47 rm -f "./fused-src/gtest/gtest.h"
 48 "./scripts/fuse_gtest_files.py" "./fused-src"
 49 cp -f "./src/gtest_main.cc" "./fused-src/gtest/"
 50 :
 51 test -d "../../../protobuf-3.13.0/third_party/googletest/googletest" || mkdir "../../../protobuf-3.13.0/third_party/    googletest/googletest"
 52 test -n ":" \
 53 || find "../../../protobuf-3.13.0/third_party/googletest/googletest" -type d ! -perm -755 \
 54 »   -exec chmod u+rwx,go+rx {} \; -o \
 55   ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 56   ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
 57   ! -type d ! -perm -444 -exec /bin/sh /tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googletest/build-au    x/install-sh -c -m a+r {} {} \; \
 58 || chmod -R a+r "../../../protobuf-3.13.0/third_party/googletest/googletest"
 59 make[6]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googletest'
 60 make[5]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googletest'
 61  (cd googlemock && make  top_distdir=../../../protobuf-3.13.0 distdir=../../../protobuf-3.13.0/third_party/googletes    t/googlemock \
 62      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 63 make[5]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googlemock'
 64 make  distdir-am
 65 make[6]: Entering directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googlemock'
 66 mkdir -p "./fused-src"
 67 chmod -R u+w "./fused-src"
 68 rm -f "./fused-src/gtest/gtest.h"
 69 rm -f "./fused-src/gmock/gmock.h"
 70 rm -f "./fused-src/gmock-gtest-all.cc"
 71 "./scripts/fuse_gmock_files.py" "./fused-src"
 72   File "/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googlemock/./scripts/fuse_gmock_files.py", line 23    5
 73     print __doc__
 74           ^
 75 SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__doc__)?
 76 make[6]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googlemock'
 77 make[6]: *** [Makefile:1749: fused-gmock-internal] Error 1
 78 make[5]: *** [Makefile:1363: distdir] Error 2
 79 make[5]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest/googlemock'
 80 make[4]: *** [Makefile:439: distdir-am] Error 1
 81 make[4]: Leaving directory '/tmp/cpp-pyext-aPCyguKH       
82 make[3]: *** [Makefile:433: distdir] Error 2
 83 make[3]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf/third_party/googletest'
 84 make[2]: *** [Makefile:1974: distdir-am] Error 1
 85 make[2]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf'
 86 make[1]: Leaving directory '/tmp/cpp-pyext-aPCyguKHAL/protobuf'
 87 make[1]: *** [Makefile:1968: distdir] Error 2
 88 make: *** [Makefile:2074: dist] Error 2

The error cited in fust_gmock_files.py was corrected in googletest on 15 October 2020 but the change is not applied with the submodule update. If I interrupt the process and physically copy the file, the build works.

I also tried use --remote with with the url for googletest which produced a different failure: 
[update_remote_googletest.txt](https://github.com/protocolbuffers/protobuf/files/5586682/update_remote_googletest.txt)

How do I get the googletest submodule to update?

**Comment by TeBoring** [comment]
Where was fust_gmock_files.py fixed? Do you have a link?

**Comment by TeBoring** [comment]
I tried the following anf works:
```
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git submodule update --init --recursive
./autogen.sh
./configure
make -j4
make dist
```

**Comment by dlj-NaN** [comment]
It looks like googletest is broken for us at google/googletest@6b8c13815 and later.
