### ISSUE TITLE
Documentation is a little misleading and it should be updated

### ISSUE THREAD

**Issue by yehudamakarov** [protocolbuffers/protobuf#8090]
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation

> If the --go_opt=paths=source_relative flag is given to protoc, the output file is placed in the same relative directory as the input file. For example, the file protos/foo.proto results in a file named protos/foo.pb.go.
When you run the proto compiler like this:
`protoc --proto_path=src --go_out=build/gen --go_opt=paths=source_relative src/foo.proto src/bar/baz.proto`
the compiler will read the files src/foo.proto and src/bar/baz.proto. It produces two output files: build/gen/foo.pb.go and build/gen/bar/baz.pb.go.

The problem here is 
> the output file is placed in the same relative directory as the input file

and then 
> It produces two output files: build/gen/foo.pb.go and build/gen/bar/baz.pb.go.

Why are the new files not placed where the docs say they should be placed i.e. `src/` and are instead placed where the flag `--go_out=build/gen` dictates? It seems if both flags are provided there is special behavior where the compiler doesn't guess the output directory based on the package name, but it _**doesn't**_ necessarily put the output files where `--go_opt=paths=source_relative` dictates they should go. Seems like the special behavior is when both are provided just use `--go_out` to calculate the output directory from the root.

Either way, can we please make this more clear? I can't find the repo for the google-developers documentation as it is probably not open.

**Comment by TeBoring** [comment]
go questions is supported at https://github.com/golang/protobuf
