### ISSUE TITLE
Add null as new wire type. 

### ISSUE THREAD

**Issue by bibmaster** [protocolbuffers/protobuf#8093]
Protobuf as tagged protocol has field presence but not nullability. All proposed nullability approaches like message boxing or oneof have various disadvantages. Explicit nullability could be useful for mapping Json merge patches (https://tools.ietf.org/html/rfc7396) to gRPC.
I guess it would be convenient to have explicit nullability at wire protocol level. Null value can be expressed as a new wire type, i.e. 7. Null encoding should be empty, without any data following tag. Fields can be marked as nullable with some attribute in proto definition. Nullable field can be present on wire as tag with null wire type or field own type. Like in json, fields will have three possible states: none/null/value.

**Comment by elharo** [comment]
Wire protocol changes must follow internal Tier 1 change procedures and do not start in this issue tracker.
