### ISSUE TITLE
It seems UBSAN is being overzealous here. As far as I know, there is no section in the standard that explicitly disallows writing out of bounds if there is sufficient storage.

### ISSUE THREAD

**Issue by Chachi69w** [protocolbuffers/protobuf#8094]
It seems UBSAN is being overzealous here. As far as I know, there is no section in the standard that explicitly disallows writing out of bounds if there is sufficient storage.

_Originally posted by @seishun in https://github.com/protocolbuffers/protobuf/issues/2073#issuecomment-245885390_

**Comment by acozzette** [comment]
I don't understand what this issue is referring to. Let me close this but feel free to comment if I am missing something.
