### ISSUE TITLE
Implement string_view setter on string fields in generated code.

### ISSUE THREAD

**Issue by blais** [protocolbuffers/protobuf#8096]
**What language does this apply to?**
proto2
C++

**Describe the problem you are trying to solve.**

I'm using std::string_view liberally. I'm having to do this everywhere, it's driving me crazy:
```
   message->set_field(value.data(), value.size();
```

**Describe the solution you'd like**

Just... please add an overload to the setters accepting the new pretty much ubiquitous std::string_view.

**Describe alternatives you've considered**

Macros. (Ugly.)

**Comment by acozzette** [comment]
The only reason we have held off on this so far as it we need to remain compatible with C++11. This might be possible to do if we can guard the string_view setters so that they only apply to C++17, though.

**Comment by blais** [comment]
I hear you, but I mean... 11 is for 2011, which is 10 years ago. Isn't there a standardized guard working across compilers already?

**Comment by ujos** [comment]
Why don't you add `#if/else`

```cpp
#if __cplusplus >= 201703
void set_abc(std::string_view) {}
#else
void set_abc(std::string cost&) {}
```

**Comment by kwaegel** [comment]
Is this still open after two years? It doesn't seem that difficult to add with the appropriate version guards mentioned above.

**Comment by fowles** [comment]
The above suggestion makes user calls like `msg.set_abc("asdf")` fail to compile with ambiguous conversion errors.  With the advent of our dependency on abseil, we will be able to get this feature soon, but it not as easy as you may expect

**Comment by fowles** [comment]
Does 22.x already have this, or do we need to remove more of our strips to enable it in OSS?
