### ISSUE TITLE
Lifting proto2 native map restriction for Ruby

### ISSUE THREAD

**Issue by RomanHargrave** [protocolbuffers/protobuf#8097]
**What version of protobuf and what language are you using?**
Version: 3.13.0 (gentoo)
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Linux, Gentoo. Kernel version not relevant.

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 2.7.0p0 MRI (`647ee6f091`)

**What did you do?**
1. Generate Ruby code for a proto2 file containing maps (the [Murmur gRPC definitions](https://raw.githubusercontent.com/mumble-voip/mumble/master/src/murmur/MurmurRPC.proto) in this case)
2. Observe the runtime error 'Cannot add a native map field using proto2 syntax.'

**What did you expect to see**

That native maps were supported.

**What did you see instead?**

The aforementioned error

**Specific details**

What work needs to be done on this? If this is straightforward and does not require extensive familiarity with protoc and the Ruby protobuf library, I would be glad to fix this.

Relevant code: https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/defs.c#L1725

Ping @haberman (your name is in the TODO comment for this)

**Comment by haberman** [comment]
This is fixed in https://github.com/protocolbuffers/protobuf/pull/8184
