### ISSUE TITLE
Reopening Security Vulnerability issue #8088

### ISSUE THREAD

**Issue by eugrin** [protocolbuffers/protobuf#8102]
Veracode scan found this security vulnerability - integer Overflow or Wraparound in map_entry_lite.h in int GetCachedSize() const override.
The faulty line is
size += has_key() ? static_cast<int>(kTagSize) + KeyTypeHandler::GetCachedSize(key()) : 0;

The explanation provided in issue #8088 was 
GetCachedSize is always called after ByteSizeLong, which ensures the size doesn't exceed 2G.

However, the summation is done inside GetCacheSize(), calling ByteSizeLong before GetCacheSize doesn't guarantee that the sum of kTagSize and KeyTypeHandler::GetCachedSize(key()) is not going to wraparound.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/bd9a7104e11740e4bcfbde46c190c2d908ef331a/src/google/protobuf/message_lite.cc#L379

The same work of summation should have been done in a ByteSizeLong before calling  the GetCacheSize. Besides, the result of that ByteSizeLong has been checked in the link above. Therefore, the result of GetCacheSize has been pre-checked.

The GetCachedSize for map entry is a little different from other messages'. However, the result is also pre-checked in the way mentioned above.

**Comment by eugrin** [comment]
It doesn't resolve the problem in GetCachedSize itself. It has 2 summations, each one can wrap around.
int GetCachedSize() const override {
    int size = 0;
    size += has_key() ? static_cast<int>(kTagSize) +
                            KeyTypeHandler::GetCachedSize(key())
                      : 0;
    size += has_value() ? static_cast<int>(kTagSize) +
                              ValueTypeHandler::GetCachedSize(value())
                        : 0;
    return size;
  }

**Comment by eugrin** [comment]
ByteSizeLong is different type and summing different things:
size_t ByteSizeLong() const override {
    size_t size = 0;
    size += has_key() ? kTagSize +
                            static_cast<size_t>(KeyTypeHandler::ByteSize(key()))
                      : 0;
    size += has_value()
                ? kTagSize +
                      static_cast<size_t>(ValueTypeHandler::ByteSize(value()))
                : 0;
    return size;
  }

**Comment by TeBoring** [comment]
ByteSizeLong: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/map_entry_lite.h#L258
GetCachedSize: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/map_entry_lite.h#L273

1. Calculation in ByteSizeLong never overflows because of the type is long.
2. The result from ByteSizeLong also doesn't overflow for int32 because of the check in message_lite.cc
3. The thing calculated in ByteSizeLong is strictly larger than the thing calculated in GetCachedSize.

Given those 3, the result (and also each step) in GetCachedSize doesn't overflow for int32.

Could you point out which part of the induction is incorrect?

**Comment by TeBoring** [comment]
Feel free to reopen this issue.

**Comment by snnn** [comment]
> * Calculation in ByteSizeLong never overflows because of the type is long.

But I saw the type is size_t?  So overflow is still possible in 32-bit applications?

**Comment by acozzette** [comment]
I believe 32-bit platforms are still OK, because in that environment it would be impossible to make ByteSizeLong large enough to overflow. If you tried to create a large enough message to do this, you would run out of memory first, since on 32-bit the address space is capped at 4 GiB.
