### ISSUE TITLE
Improve linter documentation on the protobuf website

### ISSUE THREAD

**Issue by remyleone** [protocolbuffers/protobuf#8109]
When I'm visiting https://developers.google.com/protocol-buffers/docs/overview I would like to find some information about tooling that is available for using the protobuf language.

For instance, as a beginner I would like to know that well-supported linters exists for protobuf, for instance, [clang-format](https://clang.llvm.org/docs/ClangFormat.html)

Could you add this information to the website to <https://developers.google.com/protocol-buffers> to make it easier for beginners to find this information?

**Comment by remyleone** [comment]
Hello would this be considered?

**Comment by Logofile** [comment]
This seems like a reasonable request, and easy enough to implement. Let's keep it open and I'll see if I can carve out some time for this.
