### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Protobuf" - Protobuf (~> 3.14.0)

### ISSUE THREAD

**Issue by longbct** [protocolbuffers/protobuf#8113]
I have seen Protobuf 3.14.0 has been released, but still not able to install it via `pod 'Protobuf', '~> 3.14.0'`

Get the following error:
```
CocoaPods could not find compatible versions for pod "Protobuf":
  In Podfile:
    Protobuf (~> 3.14.0)

```
I have done `pod cache clean --all
` and `pod repo update` to make sure I have the latest pods still seeing the issue when doing `pod install`. 
Does the 3.14.0 has been also released in Cocoapods?

**Comment by acozzette** [comment]
@longbct Thanks for reporting this, I did the 3.14.0 release but forgot about the Objective-C pod. @TeBoring did the Cocoapods release just now, so this should be fixed now.

**Comment by ToGre** [comment]
I have the same problems with version 3.19.3

```
[!] CocoaPods could not find compatible versions for pod "Protobuf":
 In snapshot (Podfile.lock):
  Protobuf (= 3.19.3)
```

Will Protobuf 3.19.3 also  releasing in Cocoapods?

**Comment by acozzette** [comment]
Sorry for the delay, 3.19.3 and 3.19.4 are now available on Cocoapods.

**Comment by ToGre** [comment]
I did that. Thanks for answer

**Comment by luisaverza** [comment]
Hi, could you do the release for the new version?

```
CocoaPods could not find compatible versions for pod "Protobuf":
In snapshot (Podfile.lock):
Protobuf (= 3.20.0, >= 3.9.2, ~> 3.9)
```
