### ISSUE TITLE
PHP: Protocol Buffer "number" in PHP does not conform to protobuf spec

### ISSUE THREAD

**Issue by bshaffer** [protocolbuffers/protobuf#8114]
The [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#assigning_field_numbers), the maximum field number allowed is **2^29-1**. In the [PHP code](https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/GPBWire.php#L398), this number is being limited to `2147483647 >> 3`, or **2^28-1**. 

As a result, the serialization of any proto field with a field number greater than **2^28-1** is failing when using the PHP protobuf native library and extension. 

```
message TestMessage {
  string description = 456214797;
}
```

```php
// serialize
$message = new TestMessage();
$message->setDescription('this string will not be serialized');
$serializedMessage = $message->serializeToString();

// unserialize
$message2 = new TestMessage();
$message2->mergeFromString($serializedMessage);
var_dump($message2->getDescription());
// outputs an empty string ('')
```

**Comment by vam-google** [comment]
@TeBoring Any updates on this?

**Comment by haberman** [comment]
This is fixed in https://github.com/protocolbuffers/protobuf/pull/8235
