### ISSUE TITLE
Unexpected behavior of JsonParser

### ISSUE THREAD

**Issue by Nk185** [protocolbuffers/protobuf#8118]
**What version of protobuf and what language are you using?**
Version: 3.14.0.
Language: C#

**What operating system (Linux, Windows, ...) and version?**
OS: Windows 10.0.17134.885 (1803/April2018Update/Redstone4)

**What runtime / compiler are you using (e.g., python version or gcc version)**
.Net Core SDK: 3.1.102; 
.NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
Build configuration: Release x64

**What did you do?**
1. Create .proto file with similar content:
```
message Success {
    int32 Payload = 1;
}
```
2. Compile it in whatever way you prefer (protoc/grpc tools/etc) 
3. Compose JSON like the one below:
```
{ "payload": "56" }
```
4. Try to parse it to C# class produced by compiler:
```
var success = JsonParser.Default.Parse<Success>("{ \"payload\": \"56\" }");
```
5. Observe exception `Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: payload'`

**What did you expect to see**
Properly deserialized C# object. Per [JSON Mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) section of Protocol Buffers documentation, parser should recognize both `{ "payload": "56" }` and `{ "Payload": "56" }` as valid JSON for the provided class:

> Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name.

**What did you see instead?**
An exception.

**Additional info**
Looks like the problem is in method `internal static string ToJsonName(string name)` of `JsonFormatter.cs` ([line 257](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/JsonFormatter.cs#L257)). 
What it does, is actually converting `xxx_yyy` to `xxxYyy` leaving input as-is in all other cases, and this works only in certain cases. E.g., if one called a field `xxx_yyy` and passed either `xxx_yyy` or `xxxYyy` field in JSON.
But this does not respect the statement from the documentation. IMO, the `ToJsonName()` method should produce several strings which will match all cases, including case when one doesn't follow naming guidelines. I.e.,:
| Given input | Current Output | Suggested Output |
|--|--|--|
| xxx | xxx | Xxx |
| Xxx | Xxx |  xxx |
| xxxYyy | xxxYyy | XxxYyy |
| XxxYyy | XxxYyy | xxxYyy |
| xxx_yyy | xxxYyy | xxxYyy, XxxYyy |

**Comment by haberman** [comment]
This could be documented better, but the behavior you are seeing is intended.

Our definition of lowerCamelCase is:
1. Convert all characters immediately after an underscore “_” to uppercase.
1. Remove all underscores.

This is the algorithm implemented by C# and all other languages's protobuf implementations.

This algorithm converts `Payload` to `Payload`, true. But this field doesn't follow the naming conventions laid out here, which says that fields should be `snake_case`: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names

You can use the `json_name` option in `.proto` files if you want to specify exactly what JSON name will be recognized by the parser.
