### ISSUE TITLE
The use of ```option cc_enable_arenas =```

### ISSUE THREAD

**Issue by hazelnutsgz** [protocolbuffers/protobuf#8119]
I am using proto2 syntax, and find that no matter enable or disable the ```option cc_enable_arena```, the generated .pb.h and .pb.cc by ```protoc``` are exactly the same.  (The master branch of protobuf is used.)

Does that mean that arena is enable by default?

Thanks.

**Comment by haberman** [comment]
Yes, this is documented in [the release notes for 3.14.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0):

> Arenas are now unconditionally enabled. `cc_enable_arenas` no longer has
> any effect.
