### ISSUE TITLE
protoc-artifacts container is broken by sunsetting of CentOS 6

### ISSUE THREAD

**Issue by ejona86** [protocolbuffers/protobuf#8120]
The [protoc-artifacts](https://github.com/protocolbuffers/protobuf/tree/master/protoc-artifacts) container can no longer be built, as on Nov 30 CentOS 6 support ended and we noticed the servers being shut down on Dec 3rd.

That means we are forced to drop support to those old distributions, but that makes the maintenance much easier. Previously it required using the "devtoolset" tools, but that is no longer required. I updated gRPC to a new container based on CentOS 7 in https://github.com/grpc/grpc-java/pull/7693 and the build result seems to work fine in Debian 9 (Stretch). You can see it is now a pretty generic container with just "install stuff with yum".

**Comment by haberman** [comment]
What is the action here? We need to update our Dockerfile to reference centos7 instead of centos6?

**Comment by ejona86** [comment]
Yes, referencing CentOS 7 is probably the best way forward. Although the devtoolset goo needs to be stripped out as well and replaced with debian-standard packages. So it isn't hard, but not trivial.
