### ISSUE TITLE
`ShortDebugString()` and `DebugString()` omits booleans that are false

### ISSUE THREAD

**Issue by jade2k11598** [protocolbuffers/protobuf#8123]
**What version of protobuf and what language are you using?**
Version: 3.14
Language: C++

**What operating system and version?**
Linux -- Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gnu g++ 5.5.0

**What did you do?**
When a message that has a bool as a data member and that data is set false, `ShortDebugString()` and `DebugString()` won't print out the value of that field.  Here's the following example:

Created the following protobuf message:
```
syntax = "proto3";

message MyTest {
    bool a = 1;
    bool b = 2;
    bool c = 3;
}
```
Then wrote the following C++ code using this message:
```
    MyTest first;
    first.set_a(true);
    first.set_b(false);
    first.set_c(true);

    std::cout << "first: < " << first.ShortDebugString() << " >" << std::endl;

    MyTest second;
    second.set_a(false);
    second.set_b(true);
    second.set_c(true);

    std::cout << "second: < " << second.ShortDebugString() << " >" << std::endl;

    MyTest third;
    third.set_a(false);
    third.set_b(false);
    third.set_c(true);

    std::cout << "third: < " << third.ShortDebugString() << " >" << std::endl;
```
**What did you expect to see**
I expected to see the **contents of *all* data members** printed to stdout.

**What did you see instead?**
This is the output I saw when I ran the test code above:
```
first: < a: true c: true >
second: < b: true c: true >
third: < c: true >
```
It only prints the data that was set to true.

**Anything else we should know about your project / environment**
No.  Pretty much covered everything.

**Comment by haberman** [comment]
This is how proto3 fields without the `optional` keyword behave. Default values are never printed or serialized. For more information please see: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

If you want to see fields explicitly set to false, you can use `optional` fields, which are available in proto2 and still experimental in proto3.
