### ISSUE TITLE
FloatValue breaks when packed and unpacked in Any

### ISSUE THREAD

**Issue by WarriorXK** [protocolbuffers/protobuf#8127]
**What version of protobuf and what language are you using?**
Version: v3.14
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Debian 8

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
I've used the following script:
```
<?php

$float = 1607289928.810415;

$floatVal = new \Google\Protobuf\FloatValue();
$floatVal->setValue($float);

$floatValAny = new \Google\Protobuf\Any();
$floatValAny->pack($floatVal);

var_dump($floatValAny->unpack()->getValue());
var_dump($float);
```

**What did you expect to see**
```
Test.php:11:
double(1607289928.8104)
Test.php:12:
double(1607289928.8104)
```

**What did you see instead?**
```
Test.php:11:
double(1607289984)
Test.php:12:
double(1607289928.8104)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

PHP version 7.3.19 with the following modules:
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
ldap
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
```

**Comment by haberman** [comment]
Floating point values have limited precision, and the value `1607289928.8104` cannot be exactly stored in a float. It gets rounded to `1607289984`.

If you want to store more precision, use `DoubleValue` instead.
