### ISSUE TITLE
[ruby] `decode_json` unexpected / inconsistent behaviour parsing JSON

### ISSUE THREAD

**Issue by mt-kelvintaywl** [protocolbuffers/protobuf#8135]
**What version of protobuf and what language are you using?**
Protobuf version: 3
ruby gem version: 3.12.0.rc.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.14.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Ruby 2.7

**What did you do?**

Assuming i have a generated Ruby class from Protobuf, called MyMessage

```rb
# raises Google::Protobuf::ParseError (expected)
MyMessage.decode_json("I cannot understand this", ignore_unknown_fields: true)

# returns a MyMessage.new object (expected since number is a valid JSON)
MyMessage.decode_json("1", ignore_unknown_fields: true)

# returns a MyMessage.new object (unexpected? this is a string so I expected it to throw)
MyMessage.decode_json("1 cannot understand this", ignore_unknown_fields: true) 
```

Would this be a known or expected behaviour? 🙇

**Comment by haberman** [comment]
The Ruby JSON decoder may not be properly verifying that it is at end-of-file.

There is a major change to the Ruby implementation coming soon. I'll revisit this bug after that is complete, and we can see if the new JSON parser has the same issue.

**Comment by mt-kelvintaywl** [comment]
HI @haberman thank you for the updates and details :)
Looking forward to the new releases 🙇 

would there also be a public roadmap that we can track the progress of this? 🤔

**Comment by haberman** [comment]
I just tested your examples on https://github.com/protocolbuffers/protobuf/pull/8184 and all of your examples throw errors now. This is expected since parsing a message from JSON requires a top-level object in `{}`.

Your second example now throws this error: `Error occurred during parsing: Error parsing JSON @1:0: Expected: '{'`
