### ISSUE TITLE
'make install' does not generate so files when protobuf building to cross-arm. 

### ISSUE THREAD

**Issue by Rivand** [protocolbuffers/protobuf#8137]
protobuf-cpp-3.14.0
OS - Ubuntu 20.04 

When I build a protobuff for arm and then install it, I don't see `*.so` files in the lib/ directory, only `*.a` and `*.la`. If I build it for x86, then everything is fine. 

The sequence of commands is as follows: 

```
sudo ./configure --host=amd64 --build=arm-linux-gnueabihf --target=arm-linux-gnueabihf --enable-shared --prefix=/home/rivand/install/tmp CC=/usr/bin/arm-linux-gnueabihf-gcc CXX=/usr/bin/arm-linux-gnueabihf-g++ 
sudo make -j4
sudo make install
```

**Comment by haberman** [comment]
I don't believe we have any arm or x86-specific logic in our automake setup. Are you able to get `.so` output from other automake libraries using this cross-compile setup?

**Comment by elharo** [comment]
No one responded to request for more details. Issue can be reopened if more details are available.

**Comment by rushipatel** [comment]
Would it be possible to reopen this issue. I am also having this issue when I cross compile. There is not .so generated when I compile protobuf for aarch64 architecture on x86_64 host. `--enable-shared` has no effect.

I have tried the latest version 3.18.0 and 3.15.5

```
    ./autogen.sh
    ./configure \
      --host=x86_64-linux-gnu \
      CC="/usr/bin/aarch64-linux-gnu-gcc-7" \
      CXX="/usr/bin/aarch64-linux-gnu-g++-7" \
      --with-pic \
      --with-protoc=protoc \
      --without-zlib
```

**Comment by elharo** [comment]
Question remains, are you able to get .so output from other automake libraries using this cross-compile setup?

**Comment by rushipatel** [comment]
Actually, I am not able to get .so using automake for the cross-compile setup I have.

To circumvent this, I used cmake to build protobuf repo and that worked just fine.

**Comment by elharo** [comment]
We're trying to get rid of autotools in favor of cmake so if that works, then I doubt we'll invest any more effort in this.
