### ISSUE TITLE
protobuf-3.14.0-py2.py3-none-any.whl still seems to omit compiled libraries

### ISSUE THREAD

**Issue by rschwiebert** [protocolbuffers/protobuf#8141]
**What version of protobuf and what language are you using?**
python 3.8.5
protobuf==3.14.0

**What operating system (Linux, Windows, ...) and version?**
alpine 3.12.2

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
```
 / # pip install protobuf==3.14.0
Collecting protobuf==3.14.0
  Downloading protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 1.5 MB/s
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf==3.14.0) (1.15.0)
Installing collected packages: protobuf
Successfully installed protobuf-3.14.0
/ # python3
Python 3.8.5 (default, Jul 20 2020, 23:11:29)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf.pyext._message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```

**What did you expect to see**
No ModuleNotFoundError

**What did you see instead?**
The above traceback

This appears to have been fixed for linux distros in https://github.com/protocolbuffers/protobuf/issues/6958.

Could someone please rectify the protobuf-3.14.0-py2.py3-none-any.whl wheel so it can be used in Alpine?

**Comment by tvalentyn** [comment]
It looks like older versions of pip are not able to correctly install protobuf package.
For example, it appears that to install `protobuf==3.18` and newer, you need `pip>=20.1`. Otherwise,

```python3.8 -m venv /tmp/env3 ; . /tmp/env3/bin/activate ; pip install pip<20.1 ; pip install protobuf==3.18.1 ; python3 -c "import google.protobuf.pyext._message" ; deactivate ; rm -rf /tmp/env3```
fails with: 
```
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```
and the compiled `.so` is missing in site-packages.

**Comment by tvalentyn** [comment]
Protobuf maintainers:

would it make sense for protobuf to add an install requirement:
`pip>=20.1` 
?

**Comment by tvalentyn** [comment]
thought some more, i am not sure adding a dependency on pip is a commonly used approach.
some related discussion: https://github.com/pypa/pip/issues/4145

**Comment by haberman** [comment]
Closing as obsolete. The backend has been rewritten to use upb, and the release process for building binary wheels has been completely reimplemented.
