### ISSUE TITLE
Compiler Warning on GOOGLE_CHECK

### ISSUE THREAD

**Issue by frobnitzem** [protocolbuffers/protobuf#8145]
My compiler noted line 1073 of this file might have meant to use `utf8_check == VERIFY` instead of `utf8_check = VERIFY`.  I think it might be right based on line 1044.

https://github.com/protocolbuffers/protobuf/blob/64dd751868d633421563e53e68da831a0a02c923/src/google/protobuf/compiler/cpp/cpp_message.cc#L1073

**Comment by haberman** [comment]
Confirmed. I'll make sure a fix is included in the next sync.

**Comment by elharo** [comment]
Fixed?

**Comment by frobnitzem** [comment]
Yes! Sorry for the long dwell time. It's definitely fixed.  In fact, other than unused variables, fields, and functions, there are no other warnings emitted by clang at all.
