### ISSUE TITLE
map_field.h:332:37: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]

### ISSUE THREAD

**Issue by vollkommenheit** [protocolbuffers/protobuf#8150]
Got the following with clang-8 on macOS even with the latest git code:
>   CXX      google/protobuf/descriptor.pb.lo
  CXX      google/protobuf/duration.pb.lo
  CXX      google/protobuf/dynamic_message.lo
In file included from google/protobuf/dynamic_message.cc:80:
./google/protobuf/map_field.h:332:37: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
  explicit PROTOBUF_MAYBE_CONSTEXPR MapFieldBase(ConstantInitialized)
                                    ^
./google/protobuf/map_field.h:335:9: note: non-literal type 'internal::WrappedMutex' cannot be used in a constant expression
        mutex_(GOOGLE_PROTOBUF_LINKER_INITIALIZED),
        ^
1 error generated.
make[2]: *** [google/protobuf/dynamic_message.lo] Error 1

The following discussion might be relevant, but I'm not a programmer: 
https://github.com/RIOT-OS/RIOT/issues/4583

**Comment by Schamschula** [comment]
See: https://trac.macports.org/ticket/62158

**Comment by vollkommenheit** [comment]
@Schamschula, great, closing the issue.
