### ISSUE TITLE
Failure of Bazel build "protobuf_test"

### ISSUE THREAD

**Issue by hazelnutsgz** [protocolbuffers/protobuf#8158]
After run ```bazel test protobuf_test```, it would produce the failure and said:

```
ERROR: /data00/guozhen/protobuf/WORKSPACE:39:1: //external:gtest_main depends on @submodule_gmock//:gtest_main in repository @submodule_gmock which failed to fetch. no such package '@submodule_gmock//': /data00/guozhen/protobuf/third_party/googletest/BUILD.bazel is not a regular file
ERROR: Analysis of target '//:protobuf_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.065s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

And I checked that there is no file called in ```protobuf/third_party/googletest/BUILD.bazel```, is there any workaround for that?

Thanks.

**Comment by akjain2052** [comment]
Please provide more details eg. Which OS are you using ? What protocol version are using ?
I have not seen any failure like this with protobuf_test.

**Used command to run protobuf_test**: bazel test :protobuf_test

**Comment by elharo** [comment]
non-responsive
