### ISSUE TITLE
Allow for Duration deconstruction into constituent member components

### ISSUE THREAD

**Issue by mwpowellhtx** [protocolbuffers/protobuf#8168]
For use with _CSharp_, allow for [Duration](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/duration.proto) deconstruction into constituent member components.

Stemming from a [`Google.OrTools 7.5.7466`](https://nuget.org/packages/Google.OrTools/7.5.7466) dependency, which has dependency on [`Google.Protobuf 3.11.2`](https://nuget.org/packages/Google.Protobuf/3.11.2).

What do I mean by that? For instance:

```C#
namespace Google.Protobuf.WellKnownTypes
{
    public partial class Duration
    {
        // ...

        public void Deconstruct(long seconds, int? nanos) => (seconds, nanos) = (
            this.Seconds
            , this.Nanos == default ? (int?)null : this.Nanos
        );

        // ...
    }
}
```

Today I am doing this via extension method, which is adequate, however, I think [a better factoring](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/WellKnownTypes/DurationPartial.cs#L41) would be in the source assembly:

```C#
namespace Google.Protobuf.WellKnownTypes
{
    public static void Deconstruct(this Duration value, out long seconds, out int? nanos) =>
        (seconds, nanos) = (value.Seconds, value.Nanos == default ? (int?)null : value.Nanos);
}
```

`nanos` being `int?` due to the fact that, as far as I can tell, it can be an optional component. When it is `0` or `default`, I think it can be safely ignored? Anyway... as appropriate to do so.

**Comment by jskeet** [comment]
It feels quite odd to me to have `nanos` as `int?` instead of `int` - if I *were* to add a `Deconstruct` method, it would just be with `long` and `int` parameters. However, this still feels like quite a niche requirement - I believe it's better to stick with it being an extension method in libraries that particularly need it, until we see a more widespread requirement for this.

**Comment by mwpowellhtx** [comment]
@jskeet I didn't design the original class; was simply looking for a better way to incorporate it into our own bases. However, we can continue with our internal extensions. Fair enough, but that being said, won't know the adoption until it is "there".

**Comment by mwpowellhtx** [comment]
@jskeet Stuff like this one, and your comments, I wonder you are making arbitrary administrative decisions here lacking adequate root cause analysis. Cocking an eyebrow over `long s, int n` is one thing, but stuff like that in my experience is usually there for _"reasons"_.

Best.

**Comment by jskeet** [comment]
> stuff like that in my experience is usually there for "reasons".

Stuff life what? The use of a nullable type for one component of a value? There may well be a reason for *one specific use case* but that doesn't mean it's universally applicable... which is even more reason for different projects with different requirements to use their own extension methods.

(Fundamentally I don't see `nanos` as "optional" - it's merely the least-significant unit. If I were creating a `Deconstruct` method for `DateTime`, I'd probably have year, month, day, hour, minute, second, tick-of-second - but none of them would be nullable.)

**Comment by mwpowellhtx** [comment]
Ah okay I see. Is it a simple `Duration`? `seconds` is the whole part with `nanos` expressing _fractions of a second_? That was my understanding, but in our case we were wondering `seconds` was more than adequate. Anywho... is what it is. Thank you.
