### ISSUE TITLE
[php] float/double serialization is locale aware and produces invalid json!

### ISSUE THREAD

**Issue by thehe** [protocolbuffers/protobuf#8179]
**What version of protobuf and what language are you using?**
Version: v3.14.0
Language: PHP 7.3.25 (cli) (built: Nov 24 2020 11:10:55) ( NTS )

**What operating system (Linux, Windows, ...) and version?**
CentOS Linux release 7.9.2009 (Core)

**What runtime / compiler are you using (e.g., python version or gcc version)**
libprotoc 3.14.0

**What did you do?**
1. Create any message that contains double/float
```
message Demo{
    float floatVal = 1;
    double doubleVal = 2;
}
```

2. Take a look at demo code:
```
setlocale(LC_ALL, "en_US.utf8");
$demo = new Demo();
$demo->setFloatVal(pi());
$demo->setDoubleVal(pi());
$usJson = $demo->serializeToJsonString();
```
and
```
setlocale(LC_ALL, "de_DE.utf8");
$demo = new Demo();
$demo->setFloatVal(pi());
$demo->setDoubleVal(pi());
$deJson = $demo->serializeToJsonString();
```

```
echo 'DE-JSON: ', $deJson, PHP_EOL, ' but expected ', PHP_EOL, 'EN-JSON: ', $usJson, PHP_EOL;
```

3. See output:
```
DE-JSON: {"floatVal":3,14159274,"doubleVal":3,1415926535897931}
 but expected
EN-JSON: {"floatVal":3.14159274,"doubleVal":3.1415926535897931}
```

**What did you expect to see**
Same JSON for all locales!

**What did you see instead?**
Wrong double/float decimal-separators in JSON which produces invalid json.

**Problem hints**
At least in PHP-Version the Problem is located in 
`Google\Protobuf\Internal\GPBJsonWire::182`,
`Google\Protobuf\Internal\GPBJsonWire::194`,
`Google\Protobuf\Internal\Message::1711`,
`Google\Protobuf\Internal\Message::1722`

where the double/float value is formatted with `sprintf('%.8g')`/`sprintf('%.17g')`.

As you can see in [php-documentation for sprintf](https://www.php.net/manual/en/function.sprintf.php), 
the modifier `f` (small f) is locale-aware, while `F` isn't.
Modifier `g` falls back to `e` or `f` (depending on precision) so that it *is* locale-aware in most cases.

`Let P equal the precision if nonzero, 6 if the precision is omitted, or 1 if the precision is zero. Then, if a conversion with style E would have an exponent of X: If P > X ≥ −4, the conversion is with style f and precision P − (X + 1). Otherwise, the conversion is with style e and precision P − 1.`

**Solution**
You could just use `sprintf('%.8F')` or, at least, wait for modifier `H` which will be introduced in PHP 8.

**Comment by thehe** [comment]
Same for c-function:
`php-upb,c::7831` and `php-upb,c::7834` and the size-calculation...

**Comment by deannagarcia** [comment]
I think this was fixed by https://github.com/protocolbuffers/upb/pull/395. Feel free to reopen if you are still seeing this error.
