### ISSUE TITLE
C++ SIGSEGV happen in proto deserialization 

### ISSUE THREAD

**Issue by cdjingit** [protocolbuffers/protobuf#8181]
**What version of protobuf and what language are you using?**
Version: master/v3.10.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc-4.8.5

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Access memory at address 0 when deserialize string feilds of proto. Following is stack trace:

*** SIGSEGV (@0x0) received by PID 179661 (TID 0x7fb3d810d700) from PID 0; stack trace: ***
    @     0x7fb3df8375e0 (unknown)
    @           0xd12065 /ads-backend/adapter/bin/adapter_server std::string::assign()
    @     0x7fb3de6b0ba6 /usr/lib64/libprotobuf.so.21.0.0 google::protobuf::internal::InlineGreedyStringParser()
    @           0x635e98 /ads-backend/adapter/bin/adapter_server ads_proto::ExtraParam::_InternalParse()
    @           0x6534e3 /ads-backend/adapter/bin/adapter_server ads_proto::OrderItemResult::_InternalParse()
    @           0x62d0df /ads-backend/adapter/bin/adapter_server ads_serving::proto::BidExtensions::_InternalParse()
    @     0x7fb3de6afd06 /usr/lib64/libprotobuf.so.21.0.0 google::protobuf::internal::ParseContext::ParseMessage()
    @     0x7fb3de7436f2 /usr/lib64/libprotobuf.so.21.0.0 google::protobuf::internal::ExtensionSet::ParseFieldWithExtensionInfo<>()
    @     0x7fb3de7429f8 /usr/lib64/libprotobuf.so.21.0.0 google::protobuf::internal::ExtensionSet::ParseField()
    @           0x68c2e1 /ads-backend/adapter/bin/adapter_server ads_serving::proto::Bid::_InternalParse()
    @           0x61fb4f /ads-backend/adapter/bin/adapter_server google::protobuf::internal::ParseContext::ParseMessage<>()
    @           0x61eb5c /ads-backend/adapter/bin/adapter_server ads_serving::exchange::AdxResponse::_InternalParse()

**Comment by gerben-s** [comment]
Hi, thanks for the bug report. Do you have a repro or a link to the source code, so that I can see what code is generated?
