### ISSUE TITLE
Can't instantiate a Map in Ruby

### ISSUE THREAD

**Issue by i0jupiter** [protocolbuffers/protobuf#8183]
Using proto3 for Ruby with the [google-protobuf](https://rubygems.org/gems/google-protobuf/versions/3.0.0.alpha.2.0) gem. 

### Proto

```
message Person {
   message KeyValueMap {
      repeated string values = 1;
  }
  map<int32, KeyValueMap> values_by_key = 1;
}
```

### Ruby code
```
my_map = Google::Protobuf::Map.new(:int32, Person::KeyValueMap.to_s.to_sym)
```

### Error on the `Map.new()` line

```
in `initialize': Unknown field type. (ArgumentError)
```

Any ideas why?

**Comment by haberman** [comment]
You need to pass `:message` as the value type, see: https://github.com/protocolbuffers/protobuf/blob/master/ruby/tests/common_tests.rb#L514

So something like:

```
my_map = Google::Protobuf::Map.new(:int32, :message, Person)
```

But it's usually easier to just let the map be auto-constructed by referring to a map field in a `Person` message:

```
  p = Person.new
  p.values_by_key[5].values += "abc"
```
```

**Comment by i0jupiter** [comment]
`Google::Protobuf::Map.new(:int32, :message, Person::KeyValueMap)`

`in `initialize': Unknown field name 'message' in initialization map entry. (ArgumentError)`

**Comment by i0jupiter** [comment]
```
p.values_by_key = {
        2020 => Person::KeyValueMap.new(values: ["migration"]),
    }
```

```
in `method_missing': Expected Map instance (Google::Protobuf::TypeError)```

**Comment by i0jupiter** [comment]
Thanks, adding `:message` to the ctor worked.

Also, maps can be initialized more simply like this:

```
values_by_key: {
            2019 => Person::KeyValueMap.new(values: ["foo"]),
            2018 => Person::KeyValueMap.new(values: ["bar", "baz"])
        }
```

**Comment by i0jupiter** [comment]
@haberman Please consider including an example for non-primitive types [here](https://developers.google.com/protocol-buffers/docs/reference/ruby-generated) :)
