### ISSUE TITLE
Java builders missing function for repeated primitives

### ISSUE THREAD

**Issue by zachdeibert** [protocolbuffers/protobuf#8188]
**What version of protobuf and what language are you using?**
Version: v3.14.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 1.8.0_241

**What did you do?**

```
PS> cat .\test.proto
syntax = "proto3";

message ObjectType {
}

message MyMessage {
    repeated ObjectType workingField = 1;
    repeated int32 nonworkingField = 2;
}
PS> protoc --java_out=. .\test.proto
```

**What did you expect to see**

The following methods (among others) generated in `MyMessage.Builder` (as described [here](https://developers.google.com/protocol-buffers/docs/reference/java-generated#repeated-fields)):

```java
public Builder addWorkingField(Test.ObjectType value)
public Builder addWorkingField(int index, Test.ObjectType value)
public Builder addNonworkingFiled(int value)
public Builder addNonworkingField(int index, int value)
```

**What did you see instead?**

The following method is missing:

```java
public Builder addNonworkingField(int index, int value)
```

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
`public Builder addWorkingField(int index, Test.ObjectType value)` should be `public Builder setWorkingField(int index, Test.ObjectType value)`. That's the mistake here. There should be a `setNonworkingField(int index, int value)`

**Comment by elharo** [comment]
Need to investigate further but we might have to won't fix this one, valid as it is, for reasons of backwards compatibility.

**Comment by elharo** [comment]
This is working as documented and expected. I can't personally explain why it's addFoo(int index, int value) for message types and setFoo(int index, int value) for primitive types, but that's the way it is.
