### ISSUE TITLE
Remove or rename the 4.0.0rc tags from github

### ISSUE THREAD

**Issue by jeroen** [protocolbuffers/protobuf#8200]
Somewhere a while ago it was decided to revert the bump to 4.0.0 and stick with 3.x for now. However this repository has two tagged releases `v4.0.0-rc2` and `v4.0.0-rc1`.

As a result, many uses and automated systems assume this tag is the newest release. For example: https://tracker.debian.org/pkg/protobuf says `HIGH: A new upstream version is available: 4.0.0~rc2`

**Comment by haberman** [comment]
I just deleted the `v4.0.0-rc*` tags.

**Comment by rayman1104** [comment]
Is there an alternative tag for v4.0.0-rc2?
Just deleting release is a bit rude. Our development process was blocked until we found an alternative version of protobuf that's also compatible with all other libs.

**Comment by jeroen** [comment]
@rayman1104 as explained above, `v4.0.0-rc2` was renamed to `v3.14.0-rc2`
