### ISSUE TITLE
error: ‘memcpy’ was not declared in this scope

### ISSUE THREAD

**Issue by Frankenstein-bit** [protocolbuffers/protobuf#8207]
when i compiler something in ubuntu 18.04 use mingw-64,i get the following error,someone can help me ?

/usr/x86_64-w64-mingw32/include/google/protobuf/repeated_field.h:1398:11: error: ‘memcpy’ was not declared in this scope
     memcpy(to, from, static_cast<size_t>(array_size) * sizeof(Element));

**Comment by haberman** [comment]
Does it help if you add `#include <string.h>` to the top of that file?
