### ISSUE TITLE
JavaLite still suffers from issue #5139

### ISSUE THREAD

**Issue by bmarwell** [protocolbuffers/protobuf#8208]
https://github.com/protocolbuffers/protobuf/issues/5139

Specifically, this comment: 
https://github.com/protocolbuffers/protobuf/issues/5139#issuecomment-599711532

**What version of protobuf and what language are you using?**

3.11.0 and 3.14.0

Language: Java

**What operating system (Linux, Windows, ...) and version?**

Linux (Ubuntu 18.04 and 20.04) and Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

Eclipse and Maven

**What did you do?**
1. Generate sources
2. Compilation failed – only in eclipse, because the casting to (Builder) is ambiguous.

**What did you expect to see**

No casting, fixed in #5139 for the java version.

**What did you see instead?**

Cast still there. Works in IntelliJ but not in Eclipse.

**Anything else we should know about your project / environment**

./.

**Comment by perezd** [comment]
Hi there, thanks for re-raising this, please comment on the original bug in the future, going to close this as its a duplicate.

**Comment by bmarwell** [comment]
@perezd seriously? There are already comments in the original issue, but you did not reopen the issue.
So what I can comment every day, but this would not help if you do not reopen this issue.

**Comment by perezd** [comment]
Hi didn't realize it was closed, my mistake have a nice day.
