### ISSUE TITLE
[PHP] add support for field option "[deprecated=true]"

### ISSUE THREAD

**Issue by cawolf** [protocolbuffers/protobuf#8211]
**What language does this apply to?**
PHP (using proto3 with protoc-gen-php)

**Describe the problem you are trying to solve.**
As a developer of a service client, I would like to be able to identify deprecated message fields instantly in order to not use them anymore and replace them correctly.

**Describe the solution you'd like**
This could be implemented by adding a `@deprecated` annotation to the field accessors of the generated code, as already stated in the [documentation](https://developers.google.com/protocol-buffers/docs/overview#options).

**Describe alternatives you've considered**
Alternatively, triggering `error_log()` with a `$message_type = E_USER_DEPRECATED` would have a similar effect.

**Additional context**
-

**Comment by TeBoring** [comment]
LGTM, would you mind send us a PR?

**Comment by cawolf** [comment]
Sure, I opened #8223 - but the label check fails immediately, and I am not able to add the labels "php" and "release notes: yes" to it.
