### ISSUE TITLE
Readme badges are broken

### ISSUE THREAD

**Issue by stof** [protocolbuffers/protobuf#8216]
The readme contains lots of badges in https://github.com/protocolbuffers/protobuf#protobuf-runtime-installation
But most of them are broken, as they seem to target an internal system rather than a public URL. Links when clicking on them also go to pages requiring to authenticate with a google.com SSO account.

**Comment by TeBoring** [comment]
working on the fix

**Comment by sourabh-agrawal** [comment]
@TeBoring 
This is still broken. For example IMO https://storage.googleapis.com/protobuf-kokoro-badges/status-badge/linux-ruby23.png is private file but others file like https://storage.googleapis.com/protobuf-kokoro-badges/status-badge/linux-ruby24.png is publicly accessible. 
`Thinking out loud here, most of these ruby version badges are tied to same image but different .png file on the server. Why are
we not using a single badge url if the final outcome is same? Maintaining same png file with different version names are just an overkill.`

**Comment by elharo** [comment]
I think these have been removed
