### ISSUE TITLE
PHP8 Protobuf PECL install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by JimmyBanks** [protocolbuffers/protobuf#8217]
**What version of protobuf and what language are you using?**
Version: master/v3.14.0
Language: PHP 8.0.0

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
PEAR/PECL on PHP 8.0.0

**What did you do?**
1. sudo pecl install protobuf

**What did you expect to see**
Successful installation

**What did you see instead?**
/tmp/pear/temp/protobuf/array.c:639:6: error: ‘zend_object_handlers {aka struct _zend_object_handlers}’ has no member named ‘compare_objects’; did you mean ‘cast_object’?
h->compare_objects = RepeatedField_compare_objects;

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by chiragvels** [comment]
I am also facing same issue.

/tmp/pear/temp/protobuf/array.c: In function ‘Array_ModuleInit’:
/tmp/pear/temp/protobuf/array.c:639:6: error: ‘zend_object_handlers {aka struct _zend_object_handlers}’ has no member named ‘compare_objects’; did you mean ‘cast_object’?
   h->compare_objects = RepeatedField_compare_objects;
      ^~~~~~~~~~~~~~~
      cast_object

Makefile:210: recipe for target 'array.lo' failed
make: *** [array.lo] Error 1
ERROR: `make' failed

Thanks,

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/pull/8105

This fix hasn't been released yet.

**Comment by chiragvels** [comment]
Hi @TeBoring ,

Any expected time, to release same? Ot how we could use the fix?

Thanks,

**Comment by JimmyBanks** [comment]
@TeBoring 

> Hi @TeBoring ,
> 
> Any expected time, to release same? Ot how we could use the fix?
> 
> Thanks,
