### ISSUE TITLE
Using the repeated field causes memory to grow

### ISSUE THREAD

**Issue by zidanefr33** [protocolbuffers/protobuf#8222]
Version: v3.6.0
Language: C++
operating system:Windows

compiler are you using VS2015

**What did you do?**
Send data with repeated field every few seconds

**What did you see instead?
Memory keeps rising

**Comment by haberman** [comment]
Can you be more specific? What APIs did you call? Also can you try a newer version of protobuf? v3.6.0 is 2.5 years old at this point.
