### ISSUE TITLE
[PHP] Delimited encoding utilities for PHP

### ISSUE THREAD

**Issue by stof** [protocolbuffers/protobuf#8226]
**What language does this apply to?**
PHP

**Describe the problem you are trying to solve.**
https://developers.google.com/protocol-buffers/docs/techniques#streaming describes a standard technique to stream protobuf messages by delimiting them with their length as a varint. The [C](https://github.com/protocolbuffers/protobuf/blob/64dd751868d633421563e53e68da831a0a02c923/src/google/protobuf/util/delimited_message_util.cc#L108) and [Java](https://github.com/protocolbuffers/protobuf/blob/64dd751868d633421563e53e68da831a0a02c923/java/core/src/main/java/com/google/protobuf/AbstractMessageLite.java#L94) runtimes are exposing helpers for that

**Describe the solution you'd like**

It would be great if the PHP runtime could expose similar helpers

**Describe alternatives you've considered**

**Comment by esorot** [comment]
Open to PRs
Closing: Please reopen to help raise priority
