### ISSUE TITLE
Documentation should show users how to wrap their enum types in a message declaration

### ISSUE THREAD

**Issue by doctorpangloss** [protocolbuffers/protobuf#8230]
Addresses issues like #3625, #6912 

**What language does this apply to?**
`proto3`

**Describe the problem you are trying to solve.**
There is no practice for enum naming advocated by the docs, even though it's really tricky due to name collisions on C++ causing protoc to report an error if you have two enum constants with the same name in the same scope logical for your target language.

One school advocates:
```
// top level enum
enum MyEnum {
  MY_ENUM_A = 0;
  MY_ENUM_B = 0;
}

enum MyOtherEnum {
  MY_OTHER_ENUM_A = 0;
  MY_OTHER_ENUM_B = 0;
}
```

Another school advocates:
```
message MyEnumMessage {
  enum MyEnum {
   A = 0;
   B = 1;
  }
}

message MyOtherEnumMessage {
  enum MyOtherEnum {
   A = 0;
   B = 1;
  }
}
```

The second is superior, because it better maps to every other language and makes your decision to not deal with C++11 idiomatically a moot point. Everything just works. It is of course a huge chore to only do this after writing enum declarations with essentially no documentation around the limitations that actually matter. Like I get that Java can't support 10,000 enums or whatever, but you could have also given this example because there are 1,000x more applications that use the same names in different enums than there are applications that use thousands of enum names in a single declaration.

**Describe the solution you'd like**

The docs should show an example of the second enum naming practice, "message wrapping", and hopefully everyone adopts it because Google says so.

**Describe alternatives you've considered**

Emit C++11 enum types.

**Additional context**

The rest of the experience with protobufs has been awesome.

**Comment by haberman** [comment]
We actually recommend the first approach, see: https://developers.google.com/protocol-buffers/docs/style#enums

> Prefer prefixing enum values instead of surrounding them in an enclosing message.

Some languages, such as C#, actually special-case this pattern to produce nice output: https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#enum

I agree this is a bit of a wart. Ideally the whole proto language would move to proper scoped enums.

> The rest of the experience with protobufs has been awesome.

I'm glad to hear that!

**Comment by doctorpangloss** [comment]
For what it's worth I wound up wrapping because the prefixes are so painful to deal with in Java. I was migrating from OpenAPI and also transitioned application models to protos. Maybe doc both? Thanks for the consideration and either way people will find the way!

**Comment by hellt** [comment]
I wonder why so many googleapis examples prefix only the UNSPECIFIED enum field for even unwrapped messages?

https://github.com/googleapis/googleapis/blob/4d27ae79c480f0de8e88aae02c53ee7fb9fc03f5/google/type/dayofweek.proto#L26

Should we really prefix every enum value?

[Protolint](https://github.com/yoheimuta/protolint), for example, warns if not every enum value is prefixed.

**Comment by luangong** [comment]
@hellt I found this: [Google API Improvement Proposals › General AIPs › Enumerations](https://google.aip.dev/126#:~:text=Enums%20which%20will%20only%20be,code%2C%20which%20is%20unnecessarily%20verbose.).
