### ISSUE TITLE
Is there a way to set int32Value to be 0

### ISSUE THREAD

**Issue by Anoupz** [protocolbuffers/protobuf#8237]
Hi, is it possible to set the value to be 0

```
const int32Value = new Int32Value()
int32Value.setValue(0)
```
This doesn't work as it returns the value as 

```
{
  "array": [
    null
  ],
  "arrayIndexOffset_": -1,
  "convertedPrimitiveFields_": {},
  "pivot_": 1.7976931348623157e+308,
  "wrappers_": null
}
```

Appreciate all the help.

**Comment by haberman** [comment]
It looks like you are using JavaScript with the Int32Value type from `wrappers.proto`?

Plain proto3 fields, like `Int32Value.value` do not distinguish between `0` and empty. If you want to support an explicit `0` you can use proto3 optional fields (this feature is currently experimental, but will become a standard feature in the next release).

For more information see: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#presence-in-proto3-apis

**Comment by Anoupz** [comment]
Thank you @haberman
