### ISSUE TITLE
add findValueByNumber to generated enum classes in PHP

### ISSUE THREAD

**Issue by lauren** [protocolbuffers/protobuf#8239]
In my issue https://github.com/protocolbuffers/protobuf/issues/6875 I requested an addition of enum mappings from value to key in the enum classes generated in PHP. @haberman suggested the following solution and asked me to re-open if I thought it would be helpful.

> I think the best option here is to use reflection. For any enum type you can easily build your own mapping at runtime:
> 
>   $enumDesc = $pool->getEnumDescriptorByClassName(get_class(new Animals()));
>   $names = [];
>   for ($i = 0; $i < $enumDesc->getValueCount(); $i++) {
>     $value = $enumDesc->getValue($i);
>     $names[$value->getNumber()] = $value->getName();
>   }
> The only thing to watch out for is that multiple names can have the same number.
> 
> This could be slightly simplified if $enumDesc->findValueByNumber($number) was supported like it is in C++. Then you wouldn't need to build your own map.
> 
> Please feel free to re-open if this enhancement ($enumDesc->findValueByNumber($number)) would be helpful for you. Sorry this issue went so long without an answer.

I do think his suggestion would be very helpful so that it's not necessary to build reflection methods for each enum. I don't see an option to re-open https://github.com/protocolbuffers/protobuf/issues/6875, so I'm opening a new feature request.

**What language does this apply to?**
generated code in PHP

**Describe the problem you are trying to solve.**
If I define an enum like this in a proto file:

```proto
enum Animals {
  CATS = 0;
  DOGS = 1;
}
```

When I generate code in Go I end up with mappings from the key to the value and from the value to the key like this:

```go
var Animals_name = map[int32]string{
    0: "CATS",
    1: "DOGS",
}

var Animals_value = map[string]int32{
    "CATS": 0,
    "DOGS":  1,
}
```

But when I generate code in PHP, I only get mappings from the key to the value and not the other way around:
```php
class Animals
{
    /**
     * Generated from protobuf enum <code>CATS = 0;</code>
     */
    const CATS = 0;
    /**
     * Generated from protobuf enum <code>DOGS = 1;</code>
     */
    const DOGS = 1;
}
```

**Describe the solution you'd like**
A method similar to the C++ method`findValueByNumber` as mentioned by @haberman. https://github.com/grpc/grpc/blob/3e2cca4afccf8601bfb1411ba3618168d564a185/third_party/upb/upb/def.hpp#L313-L318

**Describe alternatives you've considered**
1) My previous suggestion was having the generated code include both mappings: 

```php
class Animals
{
    const VALUES = [
        "CATS" => 0,
        "DOGS" => 1,
    ];

    const NAMES = [
        0 => "CATS",
        1 => "DOGS",
    ];
}
```

2) @haberman suggested using reflection, but I believe it'd be more useful to have this kind of boilerplate generated automatically.

**Comment by deannagarcia** [comment]
I think this is a great suggestion, but unfortunately the protobuf team doesn't have the bandwidth to support this right now. It would be great if someone was interested in sending a PR to add this!
