### ISSUE TITLE
sizePointerSlow() runs very slow

### ISSUE THREAD

**Issue by ianthpun** [protocolbuffers/protobuf#8241]
**What version of protobuf and what language are you using?**
Version: v3.8
Language: Go

mac osx

**What did you do?**

Hi im currently doing some CPU profiling as one of our GRPC servers are using quite a bit of CPU for the amount of traffic it is receiving. I noticed in our profiler there may be a ton of lag here:

![image](https://user-images.githubusercontent.com/6364887/106232022-e2f3e700-61a7-11eb-82da-d39509bd16ca.png)

Does anyone know what the cause of this is? Thanks!

**Comment by haberman** [comment]
This repository does not contain protobuf for Go. Please file Go-related issues at https://github.com/golang/protobuf.
