### ISSUE TITLE
Invalid enum value in JSON conversion when adding new enum value

### ISSUE THREAD

**Issue by kristianmo** [protocolbuffers/protobuf#8244]
Protobuf .Net NuGet package v3.14.0.

Protoc 3.12.0.

Hey, I have a producer using the protobuf below that produces serialized messages in either json or binary, about 50/50.

```proto
syntax = "proto3";
...

enum EventType {
    EVENT_TYPE_UNSPECIFIED = 0;
    EVENT_TYPE_TROUBLE = 1;
    EVENT_TYPE_LOT_OF_TROUBLE = 2;
}

message ProcessEvent {
    EventType event_type = 1;
}
```

On the consuming side I use the same protobuf but without the last enum entry.

```proto
syntax = "proto3";
...

enum EventType {
    EVENT_TYPE_UNSPECIFIED = 0;
    EVENT_TYPE_TROUBLE = 1;
}

message ProcessEvent {
    EventType event_type = 1;
}
```

In C# consumer I deserialize binary payload with the below code. This works.
```csharp
        ...
        private ProcessEvent ConvertMessage(byte[] body)
        {           
               return ProcessEvent.Parser.ParseFrom(body);            
        }
       ...
```

In C# consumer I deserialize json payload using the below code. This does not work. I get an exception with
Invalid enum value: XXX for enum type: processevent.EventType
```csharp
        ...
        private ProcessEvent ConvertMessageJson(byte[] body)
        {           
               return ProcessEvent.Parser.WithDiscardUnknownFields(true).ParseJsonFrom(System.Text.Encoding.UTF8.GetString(body));            
        }
       ...
```

With `WithDiscardUnknownFields(true)`  to true or false I get the same result.

Possible bug in the C# parser or a usage issue?

**Comment by haberman** [comment]
I think this is a dup of https://github.com/protocolbuffers/protobuf/issues/7392.
