### ISSUE TITLE
[!!help!!]Unbuntu env execution python-protobuf returns " TypeError: Descriptors should not be created directly, but only retrieved from their parent" message 

### ISSUE THREAD

**Issue by baot20** [protocolbuffers/protobuf#8259]
I know it is an old issue and have been duplicated with the others . But I have searched related issue and tried everything I can do . 
I have been trapped with this issue for 2 days. Please kindly help. 

**What version of protobuf and what language are you using?**
Version:  3.14.0

Language: Python 3.6.9

**What operating system (Linux, Windows, ...) and version?**
1. execution in Python env in Mac os 11.0.1 works fine 
2.  executed in Unbuntu 18.04 will reported this error TypeError: Descriptors should not be created directly, but only retrieved from their parent" message 

detail unbuntu info : 'Platform': 'Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic'

**What runtime / compiler are you using (e.g., python version or gcc version)**
Language: Python 3.6.9

**What did you do?**
1.    set up a test.proto file 
2. use command to compile it into py file : protoc ./test.proto  --python_out=./     , then come out test_pb2.py file 
3. include tesy_pb2 in other code 
4. python run the other code  
5. execution in Python env in Mac os 11.0.1 works fine 
   executed in Unbuntu 18.04 will reported this error TypeError: Descriptors should not be created directly, but only retrieved from their parent" message 
from test import (
  File "/home/jenkins/agent/workspace/QAE/test_pb2.py", line 38, in <module>
    create_key=_descriptor._internal_create_key),
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/descriptor.py", line 718, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**What did you expect to see**
Please kindly tell me how to resolve this issue . Please please help . It really block my work and the progress of my project .

**Comment by anandolee** [comment]
Looks like something went wrong in here:
https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/pyext/descriptor.cc#L99

Are you able to debug which check in this function returns false?

**Comment by baot20** [comment]
It is quite strange that I move all the code to another Ubuntu machine and it all works fine . So temporary close this issue
