### ISSUE TITLE
Option to disable the generation of deprecated classes for PHP

### ISSUE THREAD

**Issue by stof** [protocolbuffers/protobuf#8260]
**What language does this apply to?**
PHP

**Describe the problem you are trying to solve.**

The generated code for nested types is currently done in 2 ways for the PHP code:
- namespaced classes, which will be there for Protobuf 4
- `_`-separated names, marked as deprecated, for compatibility with older Protobuf 3.x versions

When starting a new project using protobuf-php, there is no need for the compat classes, as these classes are not used anywhere in consumer code (as that's a new project so none of the classes are used yet). These deprecated compat classes are creating useless noise in the project.
If the generated code is exposed as a public project (instead of staying purely internal), things become even worse because these classes are then part of the API of your package, which means that removing them requires a major version of the package.

**Describe the solution you'd like**

For such case, I'd like a way to opt-in for generating only the new code (i.e. namespaced classes for nested types).
Ideally, this opt-in should be available through an option controlled when running `protoc` rather than something set inside the `proto3` file itself, as that's a setting that makes sense to be controlled by the maintainer of the PHP package (which is the one running `protoc`), not by the author of the `proto3` file (and someone else might have started using the same `proto3` file to generate PHP code for their own project earlier and so benefits from the compat layer).

**Describe alternatives you've considered**

I could post-process the generated code to remove the BC layer after running `protoc`. But this does not only involve removing files for the old names. The new files also contain some `class_alias` logic. So this complicates things and it might be fragile if the code generator changes things in its output.

**Additional context**
I discovered this when working with the sass/embedded-protocol definitions, in which we have 34 nested types among the total of 39 types, so the generated code current contains 73 classes, with 34 (46%) being for the compat layer that's irrelevant for my use case.

**Comment by haberman** [comment]
These options have been marked deprecated with `@trigger_error` since [Protobuf 3.6.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.0), released in June 2018 (committed in https://github.com/protocolbuffers/protobuf/pull/4536).

I'm inclined to think we should just remove the legacy names at this point.

**Comment by stof** [comment]
From a semver point of view, this might require releasing Protobuf 4.0 though.

But anyway, I'm fine either way (personally, I don't care as I don't have a legacy project relying on old class names)

**Comment by esorot** [comment]
Open to PRs
Closing, please re-open to help raise priority
