### ISSUE TITLE
Add merge option for protojson.Unmarshal

### ISSUE THREAD

**Issue by mmelitzer** [protocolbuffers/protobuf#8263]
**What language does this apply to?**
Go

**If it's a proto syntax change, is it for proto2 or proto3?**
proto3

**Describe the problem you are trying to solve.**
Unmarshal JSON onto an existing proto message without resetting the message first.

Updating from proto2 to proto3 breaks backwards compatibility when unmarshalling json.
Using jsonpb.UnmarshalString with proto2 only set the properties available in the JSON and left all other properties untouched.
Using protojson.Unmarshal with proto3 resets the passed proto object and doesn't allow to merge anymore.
```
func (o UnmarshalOptions) unmarshal(b []byte, m proto.Message) error {
	proto.Reset(m)
```

The workaround for now is to convert from proto3 to proto2, UnmarshalString and convert back to proto3.

**Example**
```
message SomeType {
   string propA = 1;
   string propB = 2;
}
json :=`"{"PropA": "value"}"`

myMsg := SomeType{PropB:"abc"}
protojson.Unmarshal(json, myMsg)

myMsg == {PropA: "value"} instead of {PropA: "value", PropB: "abc"}
```

**Describe the solution you'd like**
Add an option like in proto(3).Unmarshal to either reset or not.
```
	// Merge merges the input into the destination message.
	// The default behavior is to always reset the message before unmarshaling,
	// unless Merge is specified.
	Merge bool
```

```
func (o UnmarshalOptions) unmarshal(b []byte, m protoreflect.Message) (out protoiface.UnmarshalOutput, err error) {
	if o.Resolver == nil {
		o.Resolver = protoregistry.GlobalTypes
	}
	if !o.Merge {
		Reset(m.Interface())
	}
```

**Describe alternatives you've considered**
First unmarshalling onto a temp message and then merging onto the final message doesn't work as the absence of properties is lost, which then results in resetting properties that aren't in the JSON.

**Comment by znkr** [comment]
If we were to add this, we would want it to behave the same way as `Merge` in [`proto.UnmarshalOptions`](https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/proto#UnmarshalOptions). Which has an equivalent behavior in [`proto.Merge`](https://kotlinlang.org/docs/data-classes.html). IIUC, this means that

```
var m proto.Message
_ := proto.Unmarshal(ba, m)
_ := proto.UnmarshalOptions{Merge: true}.Unmarshal(bb, m)
```

is equivalent to

```
var m, tmp proto.Message
_ := proto.Unmarshal(ba, m)
_ := proto.Unmarshal(bb, tmp)
proto.Merge(m, tmp)
```

You mention that this doesn't work for you though, so I am wondering if the behavior you're looking for really is merging. Could you elaborate a bit on what you want to achieve?

**Comment by mmelitzer** [comment]
The problem is when using the following 2 JSON examples (using the types from the initial msg):
```
{"PropA": "value"}  != {"PropA": "value", "PropB": ""}
```
When first unmarshalling either of those 2 JSON objects we end up with the same proto message though:
```
{
   "PropA": "value",
   "PropB": "",
}
````

When I now use `proto.Merge` I end up with `PropB` not being overwritten, no matter which JSON was used.
From looking at `proto.Merge` the doc reads:
```
Populated scalar fields in src are copied to dst
```
So no matter if `PropB` is populated in JSON or not, once converted to proto this information is lost.

Comparing this `merge` functionality with UnmarshalString, I'd end up with either (assuming PropB was set to "X"):
```
{
   "PropA": "value",
   "PropB": "X",
}
````
and 
```
{
   "PropA": "value",
   "PropB": "",
}
```
So the 'new' Unmarshal' first resets the object, which wipes out my `PropB / X` and by using Merge we lost the notion of `ProbB` existing in the JSON or not.
It's a 'shortcoming' in the language as the absence of a primitive is not distinguishable from the default value. 

Another alternative would be to convert all types to use proto.wrapper values, unfortunately we don't have control over all types being used and it'd be inconvenient.

jsonpb offers UnmarshalString, which merges only available properties and doesn't overwrite missing props.
We'd either need UnmarshalString in `protojson` or the `Merge` option to avoid calling `Reset` on the proto message.

**Comment by deannagarcia** [comment]
Sorry for the long delay. This repository does not maintain go protos, you should file a bug in [their repository](https://github.com/golang/protobuf) for help.
