### ISSUE TITLE
defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr

### ISSUE THREAD

**Issue by bitnick10** [protocolbuffers/protobuf#8268]
**What version of protobuf and what language are you using?**
Version: v3.14.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**Windows 10

**What runtime / compiler are you using** Visual studio 2019 16.8.4 with C++20 stanard.

**What did you do?**
1. Change C++ standard to C++ latest.
2. Click build
3. Error (active) E2422 C:\Programs\vcpkg\installed\x64-windows\include\google\protobuf\message_lite.h	209	

**Anything else we should know about your project / environment** Change C++ starndard to C++ 17 can be build correctly.

**Comment by deannagarcia** [comment]
Sorry for the long delay. Unfortunately, we must move slow on updating to new C++ versions to maintain compatibility for users using old versions of C++. You should keep an eye out for announcements to see what versions of C++ we will support!
