### ISSUE TITLE
Python precision wrong in Float fields

### ISSUE THREAD

**Issue by jcwchen** [protocolbuffers/protobuf#8269]
**What version of protobuf and what language are you using?**
Version: v3.11.3
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows/Mac

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7

**What did you do?**
`pip install onnx`
```
import onnx
value = 0.1
attr = onnx.AttributeProto(type="FLOAT", f=value)
assert attr.f == value # AssertionError
#  0.10000000149011612
```

**What did you expect to see**
Assert successfully.

**What did you see instead?**
Assertion failed.

**Anything else we should know about your project / environment**
Issue: https://github.com/onnx/onnx/issues/3261
ONNX uses protobuf (3.11.3) to define its model graph. Actually I am not sure it's a protobuf issue or it's something we can handle from ONNX. I also tried a solution here: https://github.com/protocolbuffers/protobuf/issues/4569 by setting `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`, but I still encountered the same error.

Is it a known float issue in protobuf? Thank you!

**Comment by anandolee** [comment]
This is the expect behavior.

History: python language itself does not have C-style 32-bit floats, a Python float is a C-style 64-bit double. Thus the pure Python protobuf implementation was using double precision for both float and double fields in memory (the cpp extension implementation uses 32-bit single float precision for float fields). However the wire format for float is always 4 bytes (32-bits), so after a serialize/parse round trip, pure python could have a different number.. Example:
  msg.float_f = 99.997
  self.assertEqual(msg.float_f, 99.997)  # pass
  msg.ParseFromString(msg.SerializeToString())
  self.assertEqual(msg.float_f, 99.997)  # fail

Thus we changed pure protobuf python behavior to use 4 bytes (32-bits)  for float field.


Doing equality comparisons on floating point values is fragile. Ways to prevent breakages for compare: 
    1. Use assertAlmostEqual(), assertSequenceAlmostEqual(), round(), format()... 
    2. Change the float field to a double field in .proto files if required and safe (usually not safe).
    3. Only use float precision accurately presentable values in tests.

**Comment by Moxie1337** [comment]
Hi, I wonder if there is any other solution besides set `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` or replace `float` to `double`.because datatype must be distinguished in out projects。
I look forward to hearing from you soon.

**Comment by vishalratnam6** [comment]
Hey @Moxie1337 , did you find any solution?
