### ISSUE TITLE
There is no way to get JsonMapping for Proto3 from DescriptorProto in Java !

### ISSUE THREAD

**Issue by harshpat** [protocolbuffers/protobuf#8273]
When using google.protobuf.Timestamp in the proto file. We have Timestamp DescriptorProto Java class to get field information but there is no way to know whats proto object JSON mapping, in this case its string as per proto3 doc.

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by deannagarcia** [comment]
Sorry for the long delay. The best way to see the JSON mappings is through the documentation you linked. I'm not sure if I'm missing another part of your question, so feel free to reopen if you still have questions/requests.
