### ISSUE TITLE
Optional big testing data appears to be no longer available

### ISSUE THREAD

**Issue by carols10cents** [protocolbuffers/protobuf#8283]
In the benchmarks/README.md, [there's a section called "Big data"](https://github.com/protocolbuffers/protobuf/blame/59b3d97f6d7e3ff67bc5d89f030017c60b483549/benchmarks/README.md#L74-L81) that says:

> ### Big data
>
> There's some optional big testing data which is not included in the directory
> initially, you need to run the following command to download the testing data:
>
> ```
> $ ./download_data.sh
> ```

The [current contents of benchmarks/download_data.sh are](https://github.com/protocolbuffers/protobuf/blob/59b3d97f6d7e3ff67bc5d89f030017c60b483549/benchmarks/download_data.sh):

```
#! /bin/sh

curl -O https://storage.googleapis.com/protobuf_opensource_benchmark_data/datasets.tar.gz
tar -zvxf datasets.tar.gz
```

If I run `curl https://storage.googleapis.com/protobuf_opensource_benchmark_data/datasets.tar.gz`, I get a 404 with the error message:

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

I expected to get a tarball with big data for benchmarking. I'm not sure if this data was moved somewhere else or if this isn't used anymore and the download_data.sh script and directions in the benchmark README should be removed.

I'm actually trying to build [prost](https://github.com/danburkert/prost), which [tries to use this dataset in its tests](https://github.com/danburkert/prost/blob/79f0dfd8ed703fcce27f053c3b29c360c7ead5cb/protobuf/build.rs#L274). If this dataset was moved somewhere else, I'll send prost a PR to update where they're downloading it from, or I'll send them a PR to remove their use of the dataset if it's not something that should be used anymore.

So please let me know, thanks!

**Comment by danburkert** [comment]
I have copies of these datasets saved in case it's useful.  Let me know and I can provide an S3 link privately.

**Comment by tony612** [comment]
@danburkert Could you send a copy to me? I want to run a benchmark using it. My email is h.bing612@gmail.com. Thanks!

**Comment by deannagarcia** [comment]
Sorry for the long delay here, but we no longer publish the big testing data.
