### ISSUE TITLE
Mark Reflection::UnsafeArenaReleaseMessage as a public method

### ISSUE THREAD

**Issue by kevin1** [protocolbuffers/protobuf#8284]
**What language does this apply to?**
C++ generated code

**Describe the problem you are trying to solve.**

I am using protobuf with arena allocation enabled. When I called Reflection::SetAllocatedMessage and Reflection::ReleaseMessage on the message with arena enabled, I noticed that ReleaseMessage returns a heap object as expected.

Based on the [arena documentation](https://developers.google.com/protocol-buffers/docs/reference/arenas):

> `Bar* unsafe_arena_release_foo()`: Similar to `release_foo()`, but assumes the parent message is on the arena, and returns an arena-allocated object that should not be deleted directly. This method should only be used when the parent message is on the arena.

I tried to call the reflection equivalent, [Reflection::UnsafeArenaReleaseMessage](https://github.com/protocolbuffers/protobuf/blob/69694080ff3fbc496ec01d9a88248aa3e6faaf67/src/google/protobuf/generated_message_reflection.cc#L1628), but found that it's private. 

**Describe the solution you'd like**

Since the implementation of UnsafeArenaReleaseMessage repeats the error checking from ReleaseMessage, it might be simple as marking UnsafeArenaReleaseMessage as public:

https://github.com/protocolbuffers/protobuf/blob/69694080ff3fbc496ec01d9a88248aa3e6faaf67/src/google/protobuf/generated_message_reflection.cc#L1661-L1663
https://github.com/protocolbuffers/protobuf/blob/69694080ff3fbc496ec01d9a88248aa3e6faaf67/src/google/protobuf/generated_message_reflection.cc#L1631-L1632

I'm happy to submit a PR if the maintainers agree that this method can be made public.

**Describe alternatives you've considered**

Avoid using arenas and reflection at the same time, but this would cause a big performance regression in my application.

**Additional context**
none

Thanks for your consideration!

**Comment by deannagarcia** [comment]
This method was made public in https://github.com/protocolbuffers/protobuf/pull/8505.
