### ISSUE TITLE
php: Implement JsonSerializable interface

### ISSUE THREAD

**Issue by mterwill** [protocolbuffers/protobuf#8292]
**What language does this apply to?**
PHP

**Describe the problem you are trying to solve.**
I would like to be able to serialize my protobufs with PHP's native [`json_encode`](https://www.php.net/manual/en/function.json-encode.php). This would make working with protos in a mixed environment significantly easier – consider a case like the below, where an existing endpoint returns data that is serialized to JSON farther up the stack:

```php
return $this->json([
  'some' => 'existing data',
]);
```

Ideally, you could return data from a proto like this:

```php
return $this->json([
  'some' => 'existing data',
  'some_additional_data_from_proto' => $my_proto,
]);
```

However, protos currently `json_encode` to an empty object.

**Describe the solution you'd like**
PHP proto message objects should implement the [`JsonSerializable`](https://www.php.net/manual/en/class.jsonserializable.php) interface.

**Describe alternatives you've considered**
For responses that are entirely proto, you can return the result of `serializeToJsonString` directly. As demonstrated above, this breaks down when you are working with existing non-protobuf data. As a workaround, one could `json_decode($proto->serializeToJsonString())` to get a natively serializable object, but that doesn't feel particularly idiomatic.

**Comment by flyhope** [comment]
+1

**Comment by esorot** [comment]
Open to PRs, 
Closing: Please re-open to raise priority
