### ISSUE TITLE
Failed to generate libprotobuf.lib on Windows10

### ISSUE THREAD

**Issue by Breezewrf** [protocolbuffers/protobuf#8312]
**What version of protobuf and what language are you using?**
Version:  v3.4.0.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
   Windows10
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc
**What did you do?**
1. in the path"./protobuf/build/", using the vs2017x64_x86 with the command`cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_LIBPROTOC=ON -DCMAKE_CXX_COMPILER=C:/"Program Files"/mingw-w64/x86_64/mingw64/bin/g++.exe -DCMAKE_C_COMPILER=C:/"Program Files"/mingw-w64/x86_64/mingw64/bin/gcc.exe ../cmake`
  and got Generating done successfully.
2. open the vs2017IDE to click INSTALL, generating.
3. successfully generated, **but only see protobufd.lib and protocd.lib in the directory ./protobuf/build/install/lib instead of libprotobuf.lib**

**What did you expect to see**
the file like `libprotoxxxx.lib` in the directory ./protobuf/build/install/lib  (libprotobuf.lib)
**What did you see instead?**
the file like `protoxxxx.lib` in the directory ./protobuf/build/install/lib   (protobuf.lib)

**Comment by deannagarcia** [comment]
I'm sorry for the long delay.

Are you still seeing this error on newer versions of protobuf?

**Comment by deannagarcia** [comment]
Closing due to no response. Please reopen if this is still an issue!
