### ISSUE TITLE
[c#] Parser.WithDiscardUnknownFields throws exception with unknown field

### ISSUE THREAD

**Issue by acurrens** [protocolbuffers/protobuf#8316]
**What version of protobuf and what language are you using?**
Version: 3.15.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
* Visual Studio 2019
* .net Core 5.0
* Grpc.AspNetCore (v2.34.0)
* Grpc.Tools (2.36.0-pre1)
* Google.Protobuf (3.15.0)

**What did you do?**
Parse json object with GrpcService Parser.
`var parser = CarList.Parser.WithDiscardUnknownFields(true);`
` var cList = parser.ParseJson(newCarJson);`

Knowing that there are extra fields in the json objects that are not defined in the proto file I attempted to use the WithDiscardUnknownFields option set to true.

**What did you expect to see**
Grpc message of repeated objects derived from the parsed json.

**What did you see instead?**
An Exception when the ParseJson() method was called:`"Unknown field: <field name>"`

It seems like the Message parser is always using the default settings and not considering the ignoreUnknown flag:
https://github.com/protocolbuffers/protobuf/blob/133e5e75263be696c06599ab97614a1e1e6d9c66/csharp/src/Google.Protobuf/MessageParser.cs#L353-L358

**Anything else we should know about your project / environment**
I've setup a simple demo project illustrating the issue in my git repo here:
https://github.com/acurrens/GrpcJsonParseIssue

Feel free to clone/review the demo project and let me know if I'm doing something wrong on my end
Thanks,
Andrew

**Comment by kwaclaw** [comment]
I can confirm this

**Comment by TheFireCookie** [comment]
I encounter the same issue too.

**Comment by shaneqld** [comment]
Can reproduce and it's clear looking at the code that this has been forgotten.  If you want a work around in the meantime you can do something like this:

```cs
public static T ParseJson<T>(string json, bool discardUnknownFields = true) where T : IMessage<T>, new()
{
    var jp = new JsonParser(JsonParser.Settings.Default.WithIgnoreUnknownFields(discardUnknownFields));
    T msg = jp.Parse<T>(json);
    return msg;
}
```

**Comment by jskeet** [comment]
I don't think we'd want to change the actual behavior here (it could be a very significantly breaking change), but we can certainly clarify the documentation. I'll create a PR for that.

**Comment by jskeet** [comment]
Closing this as the documentation is now clearer and we don't intend to link the binary and JSON parser behavior. (Note that the two settings don't mean quite the same thing anyway.)
