### ISSUE TITLE
Use pooled memory for ToByteArray in C#

### ISSUE THREAD

**Issue by jonso4** [protocolbuffers/protobuf#8321]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
`ToByteArray` in C# allocates a buffer for the message. This can lead to performance impact and heavy GC load at scale.

**Describe the solution you'd like**
It would be great if `ToByteArray` could use pooled memory to avoid allocations. It would be great if Grpc could also be updated to use this version of `ToByteArray`.

**Describe alternatives you've considered**
I have considered manually serializing the message with pooled memory, but this seems better handled by Protobuf itself.

**Additional context**

**Comment by deannagarcia** [comment]
Sorry for the long delay.

I think https://github.com/protocolbuffers/protobuf/pull/7645 implemented this. Please file a bug with GRPC if you want changes on their end as well.
