### ISSUE TITLE
protobuf_generate_cpp is not defined when using add_subdirectory

### ISSUE THREAD

**Issue by Ravbug** [protocolbuffers/protobuf#8324]
**What version of protobuf and what language are you using?**
Version: v3.15.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS 11.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple Clang via Xcode
CMake 3.19.2

**What did you do?**
I am trying to compile Valve's [GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets), which uses protobuf. I added the protobuf library via `add_subdirectory`, however, when trying to use `protobuf_generate_cpp`, CMake errors with ` Unknown CMake command "protobuf_generate_cpp".`

My CMakeLists looks like this:
```cmake
project(GameNetworkingSocketsFull C CXX)

# dependencies
add_subdirectory(openssl-cmake)
set(protobuf_BUILD_TESTS OFF CACHE INTERNAL "")
add_subdirectory(protobuf/cmake)

# ... 

protobuf_generate_cpp(GNS_PROTO_SRCS GNS_PROTO_HDRS ${GNS_PROTOS})

# ...
```
I'm trying to avoid FindPackage to keep it self-contained.

**Comment by igxactly** [comment]
This affects me too, when I am using CPM(https://github.com/cpm-cmake/CPM.cmake)
