### ISSUE TITLE
[Ruby] reflection on a repeated field yields an incorrect value or SEGV

### ISSUE THREAD

**Issue by qnighy** [protocolbuffers/protobuf#8325]
**What version of protobuf and what language are you using?**
Version: 3.15.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
macOS and Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

Run the following:

```ruby
require 'google/protobuf'
require 'google/protobuf/struct_pb'
p Google::Protobuf::ListValue.descriptor.lookup("values").get(Google::Protobuf::ListValue.new(values: [Google::Protobuf::Value.new(string_value: "Hello")]))
```

**What did you expect to see**

```
[<Google::Protobuf::Value: null_value: :NULL_VALUE, number_value: 0.0, string_value: "Hello", bool_value: false, struct_value: nil, list_value: nil>]
```

**What did you see instead?**

```
<Google::Protobuf::Value: >
```

In more complex cases, SEGV is also obeserved.

**Anything else we should know about your project / environment**

**Comment by haberman** [comment]
Fix in: https://github.com/protocolbuffers/protobuf/pull/8330
