### ISSUE TITLE
Python runtime MethodDescriptor is missing a CopyToProto() method

### ISSUE THREAD

**Issue by alkasm** [protocolbuffers/protobuf#8326]
**What version of protobuf and what language are you using?**

Version: master
Language: Python

**What operating system (Linux, Windows, ...) and version?**

OS independent

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python version

**What did you do?**

Here's an example script showing that the `CopyToProto` method doesn't exist in the Python implementation, and how it might be implemented otherwise. You can comment out the line changing the env var to get it to instead use the CPP runtime, in which case the extra redirection is unnecessary. Run this script in the same directory as generated Route Guide stubs.

```python
import os

os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

from google.protobuf import descriptor_pb2, descriptor_pool

# import for side effect of registering descriptors to the pool
import route_guide_pb2, route_guide_pb2_grpc

pool = descriptor_pool.Default()
method_desc = pool.FindMethodByName("routeguide.RouteGuide.ListFeatures")
method_desc_proto = descriptor_pb2.MethodDescriptorProto()

try:
    method_desc.CopyToProto(method_desc_proto)
    print("Copied the method descriptor to the proto.")
    print(method_desc_proto)
except AttributeError as e:
    print(e)
    service_desc = method_desc.containing_service
    service_desc_proto = descriptor_pb2.ServiceDescriptorProto()
    service_desc.CopyToProto(service_desc_proto)
    method_desc_proto = service_desc_proto.method[method_desc.index]
    print("Got the method descriptor proto from the service proto.")
    print(method_desc_proto)
```

**What did you expect to see**

The CPP runtime does have a `CopyToProto()` method.

**What did you see instead?**

The Python runtime does not have a `MethodDescriptor.CopyToProto()` method, as can be seen here: https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/descriptor.py#L869

**Anything else we should know about your project / environment**

Overall my project was doing the `MethodDescriptor.CopyToProto()` dance because method descriptors don't have discoverable method cardinality (see https://github.com/protocolbuffers/protobuf/issues/4731). 

The code above gives a possible implementation. Unfortunately since the construction of `MethodDescriptor`s (and other descriptors) happens inside generated code files and the method descriptors don't contain the `_serialized_start`/`_serialized_end` attributes, I don't think there's any better way than reaching up to the service descriptors and letting `ServiceDescriptor.CopyToProto()` grab the information from the serialized file descriptor.

**Comment by allysa08** [comment]
omy god idk wat happen 😥😭
