### ISSUE TITLE
Maximum 32 bit float value fails to round trip.

### ISSUE THREAD

**Issue by jmphilli** [protocolbuffers/protobuf#8336]
**What version of protobuf and what language are you using?**
Version: 3.14.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS X 10.15.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.0

**What did you do?**
1. Encode a message with a float who has the maximum 32 bit float value as defined in `type_checkers._FLOAT_MAX`.
2. Decode that message into a python dictionary using `json_format.MessageToDict`
3. ReEncode the python dictionary into a new protobuf message using `json_format.ParseDict`

**What did you expect to see**
A new protobuf message with the `float_value` set to the maximum float value.

**What did you see instead?**
The library raised an error because the float value was too large.

I created a pull request [not intending to merge] to exemplify the round trip failure over [here](https://github.com/protocolbuffers/protobuf/pull/8335). If that test were to pass we would know that the issue has been resolved.

The crux of the issue is [this code](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/type_checkers.py#L75).
Python rounds up on this maximum float value. That causes the actual number to be greater than the max float which means it cannot be encoded in four bytes.

[Possibly related to this old issue in C++](https://github.com/protocolbuffers/protobuf/issues/3615)
**Anything else we should know about your project / environment**
N/A

**Comment by jmphilli** [comment]
@acozzette any chance a fix will make it into future versions [pinging you because you had activity on the relevant pr]

**Comment by ericsalo** [comment]
I have just patched the upb JSON parser to correctly handle float values very near the overflow limit, which is necessary but not sufficient for fixing this bug. The rest of the work will need to happen at the Python layer.
