### ISSUE TITLE
s390x protoc artifact on Maven Central uses the wrong classifier

### ISSUE THREAD

**Issue by ejona86** [protocolbuffers/protobuf#8340]
protoc artifacts on Maven Central should be using names agreed upon with the os-detector plugin so that the correct binary can be automatically downloaded when available by the Maven and Gradle protoc plugins. The current classifier "s390x" disagrees with os-detector's "s390_64" so can't be found by the plugins. See https://github.com/google/protobuf-gradle-plugin/issues/472

It's not clear how the current s390x classifier name was chosen. I see https://github.com/protocolbuffers/protobuf/pull/7073 explicitly remove the _64 suffix, but there's no background or reasoning provided. I see they were added in https://github.com/protocolbuffers/protobuf/pull/6558, but I didn't see discussion about the classifier name. I have to assume that people just weren't aware that the names were important and not arbitrary.

CC @salamaniibm, @Hendrik-H, @voidzcy

**Comment by ejona86** [comment]
I could understand if the binaries published as part of the [release on GitHub](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.2) didn't want to use s390_64, since it is atypical. But the binaries published on Maven Central should use the s390_64 or try you should argue with os-detector about changing it (which is probably a bad idea as it'd break other usages of os-detector).

**Comment by Hendrik-H** [comment]
@salamani I expected the fix to be part of protoc 3.15.6, which was release shortly after the fix for this issue was merged but https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.15.6/ still shows the wrong name. Which release will pick up the fix?

**Comment by acozzette** [comment]
The fix didn't make it in until after we cut the 3.15.x branch, so the fix will be released with 3.16.0.

**Comment by Hendrik-H** [comment]
thanks, looking forward for that
