### ISSUE TITLE
Is there any chance to make protobuf self-describing?

### ISSUE THREAD

**Issue by RobberPhex** [protocolbuffers/protobuf#8343]
**What language does this apply to?**
Currently protobuf 2&3's binary format for one field is:

| 5bit(or more bit) | 3bit   | n bit |
|-------------------|--------|-------|
| field id          | typeId | value |

And the TypeId could be:

| Type | Meaning          | Used For                                                 |
|------|------------------|----------------------------------------------------------|
| 0    | Varint           | int32, int64, uint32, uint64, sint32, sint64, bool, enum |
| 1    | 64-bit           | fixed64, sfixed64, double                                |
| 2    | Length-delimited | string, bytes, embedded messages, packed repeated fields |
| 3    | Start group      | groups (deprecated)                                      |
| 4    | End group        | groups (deprecated)                                      |
| 5    | 32-bit           | fixed32, sfixed32, float                                 |

The meaning of typeId is not unique for type. The disadvantages are:

1. The gateway couldn't parse binary data completely. So the HAProxy ntroduce new instruction [ungrpc](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#ungrpc).
2. Some troubleshooting tools cannot parse binary data without description. So wireshark need [setting protobuf search paths](https://grpc.io/blog/wireshark/), the Charles Web Proxy needs to [set descriptor_set paths](https://www.charlesproxy.com/documentation/using-charles/protocol-buffers/).
3. Some storage components, such as DB, need to convert when the description changed.

**Describe the problem you are trying to solve.**

1. let gateway could resolve binary data without description.
2. let troubleshooting tools can parse binary data completely
3. storage components needn't convert when the description changed.

**Describe the solution you'd like**

So I want to replace TypeId with 8bit:

| 5bit(or more bit) | 3bit                    | 8bit   | n bit |
|-------------------|-------------------------|--------|-------|
| field id          | pseudo-typeId(always 7) | typeId | value |

So we have a new chance to redesign typeId, the new typeId could be:

| Type | Meaning          | Used For                    |
|------|------------------|-----------------------------|
| 0    | Varint           | int32, int64, bool, or enum |
| 1    | Varint           | uint32, uint64              |
| 2    | Varint           | sint32, sint64              |
| 3    | 64-bit           | fixed64                     |
| 4    | 64-bit           | sfixed64                    |
| 5    | 64-bit           | double                      |
| 6    | Length-delimited | string                      |
| 7    | Length-delimited | bytes                       |
| 8    | Length-delimited | embedded messages           |
| 9    | Length-delimited | packed repeated fields      |
| 10   | 32-bit           | fixed32                     |
| 11   | 32-bit           | sfixed32                    |
| 12   | 32-bit           | float                       |

At protobuf v4, the pseudo-typeId 0-5, and 7 can be accepted.
At protobuf v5, the pseudo-typeId 7 is only accepted.

**Describe alternatives you've considered**

I thought to extend 3bit to 4bit or more, but it will break compatibility. So `pseudo-typeId(always 7)` is used.

**Additional context**

**Comment by rowillia** [comment]
Would https://developers.google.com/protocol-buffers/docs/techniques#self-description work for you?

**Comment by jorgbrown** [comment]
Any change to the binary format would have to be incredibly beneficial in order to adopt it; I don't think this would meet that bar.  Roy's suggestion, https://developers.google.com/protocol-buffers/docs/techniques#self-description , is probably the best for now.
