### ISSUE TITLE
Question about subclassing generated Message classes

### ISSUE THREAD

**Issue by danieljennings** [protocolbuffers/protobuf#8360]
Hi, I'm an engineer at Valve working on upgrading some of our projects from Protobuf 3.5.1 to 3.15.3, and the one problem I've run into is that generated Message classes are marked as final. We have some code that derives from generate Message classes, and I'm trying to evaluate whether (temporarily) disabling ShouldMarkClassAsFinal for generated Message classes is going to result in any bad behavior, or if it's just going to result in poorer optimization of the resulting classes.

https://github.com/protocolbuffers/protobuf/blob/9d203953a9950a2f2054b9029490940859ba153f/src/google/protobuf/compiler/cpp/cpp_message.cc#L987

It looks like that came across in a quite large merge, so I don't see any useful commit messages, and the only documentation I've seen regarding it is in v3.12 where it states "Mark generated classes as final; inheriting from protos is strongly discouraged."

I will be evaluating the removal of such sub-classing from our code, but I was wondering if the reasoning for this is documented anywhere? We're proto2 syntax, if that matters and wasn't somehow implied already in my question.

Thanks,
Daniel

**Comment by acozzette** [comment]
I believe the main motivation for the change was that the compiler could generate more optimal code if it knew that generated messages couldn't be subclassed. It should be fine to undo this change in your local fork of protobuf if you just want to upgrade without having to remove message subclassing first.

**Comment by danieljennings** [comment]
Thanks Adam, I'm happy with that answer as my preliminary tests with that change haven't caught anything on fire.

Have a good evening!
