### ISSUE TITLE
Better Error messages on unmarshal of JSON

### ISSUE THREAD

**Issue by charlesoconor** [protocolbuffers/protobuf#8371]
```
2021/03/02 17:07:24 Failed to read configuration from storage.jsonnet: rpc error: code = Unknown desc = Failed to unmarshal configuration: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```

**What version of protobuf and what language are you using?**
go

**What operating system (Linux, Windows, ...) and version?**
Linux 

**What runtime / compiler are you using**
go

**What did you do?**
When running JSON through the unmarshaler it will always work when formatted correctly. When formating incorrectly you're given a very unhelpful error message.  Something like 

```2021/03/02 17:07:24 Failed to read configuration from storage.jsonnet: rpc error: code = Unknown desc = Failed to unmarshal configuration: json: cannot unmarshal string into Go value of type map[string]json.RawMessage```

This makes it very hard to determine why the unmarshaler doesn't work. What would be great is if it would tell you what field was off or anything to help you dig into to issue. I've currently been commenting out JSON in a binary search to figure out the issues which isn't the most efficient way to do it. 

Thank you!

**Comment by deannagarcia** [comment]
Sorry for the long delay.

We don't support go protos in this repository, if you still have issues you should file a bug [in golang's protobuf repo](https://github.com/golang/protobuf).
