### ISSUE TITLE
how can i revert the FileDescriptor to a formatted proto file?

### ISSUE THREAD

**Issue by Abbyyan** [protocolbuffers/protobuf#8384]
I'm trying to read the FileDescriptor of a proto file A, modify it (by adding or removing some messages) and revert it to a formatted proto file. Thanks to the excellent ` plug-in` support of proto3, i can get the FileDescriptor of the input file. But I'm stuck in the process of revert a FileDescriptor to a formatted proto file. 

After searching from the documentation, I've found  [java.Descriptor.toProto](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Descriptors.Descriptor.html#toProto--) . It seems like using this api can convert a FileDescriptor to a formatted proto str but sorry i've not tried yet.

I'm confused with such questions. (1) Can [java.Descriptor.toProto](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Descriptors.Descriptor.html#toProto--) act like convert a FileDescriptor to a formatted proto string. If so, could you please give me some suggestions about how to use it? (2) If not , whether there are any methods(in python or in c++ ) could convert the FileDescriptor to a formatted proto file please? 

Hope for your help. Thanks a lot.

**Comment by Abbyyan** [comment]
Found from [c++.Descriptor.DebugString](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor#Descriptor.DebugString.details).Can i only get the DebugString and re-parse it into proto message please?

**Comment by tiolan** [comment]
For C++ you found the method already.
There is one easily adaptable example, that can give you the .proto format:
https://vdna.be/site/index.php/2016/05/google-protobuf-at-run-time-deserialization-example-in-c/

According to:
http://www.jackson-t.ca/protobuf-recovery.html
there is this for Python:
https://github.com/marin-m/pbtk/blob/777254e0fe38819fddee58ab6cb554c219f74908/utils/descpb_to_proto.py

Can someone say whether there is an "official" equivalent to [std::string Descriptor::DebugString() const](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor#Descriptor.DebugString.details) available in Python meanwhile?

**Comment by fowles** [comment]
`__str__()` is the equivalent of `DebugString()`

**Comment by tiolan** [comment]
When I was testing with `__str__()`, I got something similar to a json, that also had all required fields and information in it, but in a different syntax.
It was not in an actual .proto syntax.
Did I maybe do it on the wrong object?
I think tried it on `google.protobuf.descriptor.Descriptor` and also on `google.protobuf.descriptor_pb2.DescriptorProto`

**Comment by fowles** [comment]
`DebugString()` and `__str__()` are in a format we call "text format" it is not quite json.

**Comment by tiolan** [comment]
@fowles sorry I do not quite understand. Can you help me sorting?

When I do this in C++
```
[...]
const google::protobuf::FileDescriptor *file_desc = pool.BuildFile(file_desc_proto);
std::cout << file_desc->DebugString() << std::endl;
```
it gives me a `.proto` string:
```
syntax = "proto3";

message APIPort3 {
  uint32 AppLedStateOn = 1;
  uint32 PotiPercentage = 2;
  uint32 VDD = 3;
}
```
I want to get the same in python3,
but when I do this:
```
fd = google.protobuf.descriptor_pb2.FileDescriptorProto(name="file", package="Package", syntax="proto2", message_type=[msg])
print(fd)
```
it prints the "text format":
```
name: "file"
package: "Package"
message_type {
  name: "myMsg"
  field {
    name: "myField"
    number: 1
  }
}
syntax: "proto2"
```
----------
This here:
```
fd = google.protobuf.descriptor_pb2.FileDescriptorProto(
    name="file", package="Package", syntax="proto2", message_type=[msg])

pool = google.protobuf.descriptor_pool.DescriptorPool()
pool.Add(fd)
file = pool.FindFileByName("file")
print(file.__str__())
```
only prints:
`<google.protobuf.pyext._message.FileDescriptor object at 0x7f2e5d05f280>`

**Comment by fowles** [comment]
Sorry, I didn't read carefully enough.  I thought you were working with a protobuf directly and failed to notice that FileDescriptor is a bit special
