### ISSUE TITLE
Java generated code attempts to assign a value to a final variable

### ISSUE THREAD

**Issue by wangwalton** [protocolbuffers/protobuf#8393]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
3.15.5
**What operating system (Linux, Windows, ...) and version?**
Mac
**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 11

**What did you do?**
1. ./gradlew generateProto
2. ./gradlew build

**What did you expect to see**
No errors

**What did you see instead?**
```
 error: cannot assign a value to final variable internal_static_MyMessage_descriptor
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
Hi, I'm migrating from using oneof to optional in order detect field presence, it successfully generates the code but the code has the above error and doesn't build:

The generated function `_clinit_autosplit_dinit_1` should be assigning to a `static` MyMessage_descriptor, but it is actually static final. 

Generated Java code:
```
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_citadel_entdata_gfin_MyOtherMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_citadel_entdata_gfin_MyMessage_descriptor;
...

...
    internal_static_MyOtherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyOtherMessage_descriptor,
        new java.lang.String[] { "Filter", "UseFilterAsProjection", "Range", });
    _clinit_autosplit_dinit_1();
  }
  private static void _clinit_autosplit_dinit_1() {
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(200);
```

MyOtherMessage is fine since it's not generated in `_clinit_autosplit_dinit_1`

**Comment by elharo** [comment]
Do you have the .proto file that creates this problem? Without that, I'm not sure I can reproduce this.

**Comment by elharo** [comment]
comment and we'll reopen if there's a reproducible test case
