### ISSUE TITLE
Range based for loop does not work as expected for repeated enum fields in c++

### ISSUE THREAD

**Issue by happykeyboard** [protocolbuffers/protobuf#8400]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
ubuntu 20.04.1 LTS
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 9.3.0

**What did you do?**
consider a simple protobuf file with two messages 
```
enum AnimalEnum {
    CAT = 0;
    DOG = 1;
}
message A {
    repeated AnimalEnum animals = 1;
}

message AnimalInfo {
    string name = 1;
}

message B {
    repeated AnimalInfo animal_infos = 1;
}
```
Message A contains a repeated enum field. Per tutorial, https://developers.google.com/protocol-buffers/docs/cpptutorial 
I can iterate over `repeated AnimalEnum` field as expected in the following snippet

```
void PrintAnimal(AnimalEnum animal){
    printf("%s\n", AnimalEnum_Name(animal).c_str());
}
int main(){
    A a;
    a.add_animals(AnimalEnum::CAT);
    a.add_animals(AnimalEnum::DOG);
    for (int i = 0; i < a.animals_size(); i++){
        PrintAnimal(a.animals(i));
    }
    return 0;
}
```
If I try a range based loop, I get a compiler error
```
void PrintAnimal(AnimalEnum animal){
    printf("%s\n", AnimalEnum_Name(animal).c_str());
}
int main(){
    A a;
    a.add_animals(AnimalEnum::CAT);
    a.add_animals(AnimalEnum::DOG);
    for (auto& animal : a.animals()){
        //animal type is const int&!
        //error: invalid conversion from ‘int’ to ‘AnimalEnum’ [-fpermissive]
        PrintAnimal(animal);
    }
    return 0;
}
```

Range based loop works for a repeated non enum field
```
void PrintAnimalInfo(const AnimalInfo& info){
    printf("%s\n", info.name().c_str());
}
int main(){
    B b;
    for (auto name : {"Luna", "Max"}){
        AnimalInfo animalInfo;
        animalInfo.set_name(name);
        b.add_animal_infos()->CopyFrom(animalInfo);
    }

    for (auto& info : b.animal_infos()){
        PrintAnimalInfo(info);
    }
    return 1;
}
```

In the autogenerated protobuf code, `class RepeatedField` is used to represent repeated enums.
Should repeated enums be represented with `RepeatedPtrField` instead?
one could certainly do something like this to fix the compiler error
```
    for (auto& animal : a.animals()){
        //animal type is const int&! 
        PrintAnimal(static_cast<AnimalEnum>(animal));  //"fixed" with casting
    }
```

**Comment by deannagarcia** [comment]
Sorry for the long response.

Unfortunately this is intended behavior as documented [here](https://engdoc.corp.google.com/eng/doc/devguide/proto/reference/cpp-generated.md?cl=head#repeated_enum). For repeated enum fields `.animals()` returns `RepeatedField<int>&`. This is mainly due to how repeated enums are stored. Implementing it like this would cause us to not be backwards compatible and change the efficiency, so it will not be reimplemented.

I think the alternatives you offered are the best way to work around this.
