### ISSUE TITLE
[proto3][C++] Maybe error of value of 0

### ISSUE THREAD

**Issue by pedia** [protocolbuffers/protobuf#8413]
**What version of protobuf and what language are you using?**
Version: 3.14.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Mac/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 12.0.0 (clang-1200.0.32.29)

**What did you do?**
1. proto file:
```
syntax = "proto3";

message Foo {
  uint32 code = 1;
}
```

`protoc --cpp_out=. foo.proto`

2. Compile c++ code:
```
#include "foo.pb.h"

int main() {
  Foo foo;
  foo.set_code(0);
  foo.PrintDebugString();

  foo.set_code(1);
  foo.PrintDebugString();
  return 0;
}

```
Build with `clang++ -std=c++11 -o foo foo.cc foo.pb.cc -lprotobuf`.

**What did you expect to see**
```
code: 0
code: 1
```

**What did you see instead?**
```
code: 1
```

I think `Foo.code` = 0 is legal, `DebugString` should contain `code: 0`.

**Comment by haberman** [comment]
Singular proto3 fields do not distinguish between `0` and unset. If you change your field to `optional uint32 code = 1`, you will get your expected behavior.

For more info see: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
