### ISSUE TITLE
Ruby version `Timestamp.from_time` feels like there should be a class method

### ISSUE THREAD

**Issue by tmtrademarked** [protocolbuffers/protobuf#8424]
**What language does this apply to?**
Generated Ruby code

**Describe the problem you are trying to solve.**
Working with timestamps is somewhat awkward. To create a protobuf timestamp from Ruby time objects, you have to do the following:
```
ts = Google::Protobuf::Timestamp.new
ts.from_time(Time.now) # returns the nanos rather than the Timestamp itself.
```

**Describe the solution you'd like**
It seems like it would be easier if the Timestamp class just defined a class method as well as an instance method. Something like:
```
def self.from_time(time)
  return if time.nil?
  new(seconds: time.seconds, nanos: time.nsec)
end
```

This would allow developers to create timestamp objects in a slightly more natural syntax:
```
ts = Google::Protobuf::Timestamp.from_time(Time.now)
```

**Comment by deannagarcia** [comment]
This functionality was added in https://github.com/protocolbuffers/protobuf/pull/8562, so newer forms of protobuf should have it!
