### ISSUE TITLE
csharp protoc generates different descriptor from java one

### ISSUE THREAD

**Issue by fjod** [protocolbuffers/protobuf#8425]
**What version of protobuf and what language are you using?**
Version: 3.5.16 - I use .exe from nuget C:\Users\fjod\.nuget\packages\google.protobuf.tools\3.15.6\tools\windows_x86
Language: Java C#
apache pulsar 2.7.0

**What operating system (Linux, Windows, ...) and version?**
Windows 10 20H2

**What runtime / compiler are you using (e.g., python version or gcc version)**
.net 5.0 

**What did you do?**

Create simple protoc file for java:
```
syntax = "proto3";
package proto;

option java_package = "dfgdagfd";
option java_outer_classname = "Test";


message XXXMessage {
    string foo = 1;
    double bar = 2;
}
```
Generate output class using protoc (--java_out). Descriptor will be **ClUKClRlc3QucHJvdG8SBXByb3RvIiYKClhYWE1lc3NhZ2USCwoDZm9vGAEgASgJEgsKA2JhchgCIAEoAUIQCghkZmdkYWdmZEIEVGVzdGIGcHJvdG8z**

Create proto file for C#:
```
syntax = "proto3";
package proto;

option csharp_namespace = "nativeCheck2"; 


message XXXMessage {
    string foo = 1;
    double bar = 2;
}
```
Generate output class   using protoc (--csharp_out). Descriptor will be **CgpUZXN0LnByb3RvEgVwcm90byImCgpYWFhNZXNzYWdlEgsKA2ZvbxgBIAEoCRILCgNiYXIYAiABKAFCD6oCDG5hdGl2ZUNoZWNrMmIGcHJvdG8z**

**What did you expect to see**
If one try to decode both descriptors (https://protogen.marcgravell.com/decode), C# one will lack top tag:
![topTag](https://user-images.githubusercontent.com/7898721/112310304-7aac1800-8cb5-11eb-9386-4831e45f3bf3.jpg)

**Anything else we should know about your project / environment**
I am trying to implement protobuf support in apache pulsar schema messaging. Schema is basically the Descriptor of the message with some additional string fields. I check my work with pulsar working on Docker on my machine. When I use hardcoded Descriptor from java output, it works fine. When I try to use Descriptor from csharp output (hardcoded or taken from generated class), pulsar can not deserialize the descriptor from the schema. I believe it's because of the absence of top tag. Even if my code is wrong, I believe protoc should generate equal descriptors.

**Comment by deannagarcia** [comment]
Sorry for the long delay. This is expected behavior because adding `java_outer_classname` changes the format of the generated code to be a single message per file. In order to fix the disparity, you should just not use `java_outer_classname`.
