### ISSUE TITLE
Ruby message class equality changed in 3.15.0

### ISSUE THREAD

**Issue by ob-stripe** [protocolbuffers/protobuf#8427]
**What version of protobuf and what language are you using?**
Version: v3.15.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina 10.15.7

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**What did you do?**
Run the following Ruby script:

```ruby
require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foo.proto", :syntax => :proto3) do
    add_message "Foo" do
      optional :type, :enum, 1, "Foo.Type"
    end
    add_enum "Foo.Type" do
      value :TYPE_FOO_ZERO, 0
      value :TYPE_FOO_ONE, 1
    end
    add_message "Bar" do
      optional :type, :enum, 1, "Bar.Type"
    end
    add_enum "Bar.Type" do
      value :TYPE_BAR_ZERO, 0
      value :TYPE_BAR_ONE, 1
    end
  end
end

Foo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Foo").msgclass
Bar = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Bar").msgclass

foo = Foo.new(type: :TYPE_FOO_ONE)
p foo

bar = Bar.new(type: :TYPE_BAR_ONE)
p bar

p foo == bar
```

**What did you expect to see**
With google-protobuf 3.14.0, the script returns:
```
<Foo: type: :TYPE_FOO_ONE>
<Bar: type: :TYPE_BAR_ONE>
false
```

**What did you see instead?**
With google-protobuf 3.15.0, the script returns:
```
<Foo: type: :TYPE_FOO_ONE>
<Bar: type: :TYPE_BAR_ONE>
true
```

I assume the new behavior is due to the fact that the two messages have the same Proto serialization (`"\b\x01"` in both cases), but I think the previous behavior was more correct. Generally, comparing two instances of different classes should return false. Even ignoring that, the inner enum types are different. Just because the numerical values happen to be the same does not mean the messages are equal.

**Anything else we should know about your project / environment**
N/A

**Comment by ob-stripe** [comment]
Note that the latest version 3.15.6 behaves the same as 3.15.0.

**Comment by haberman** [comment]
I believe the fix here is just to also compare the classes of the messages. I'll write up a fix.

**Comment by haberman** [comment]
Fix is released in https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.7
