### ISSUE TITLE
Question concerning the encoding document of protobuf

### ISSUE THREAD

**Issue by pmixer** [protocolbuffers/protobuf#8435]
**What version of protobuf and what language are you using?**

doesn't matter

**What operating system (Linux, Windows, ...) and version?**

doesn't matter

**What runtime / compiler are you using (e.g., python version or gcc version)**

doestn't matter

**What did you do?**

Just reading https://developers.google.com/protocol-buffers/docs/encoding and found the "As you can see, the last three bytes are exactly the same as our first example (08 96 01), and they're preceded by the number 3 – embedded messages are treated in exactly the same way as strings (wire type = 2)." sentence.

**What did you expect to see**

Just expect that "the same way as strings" would be better be replaced by "the same way as bytes".

**What did you see instead?**

"the same way as strings"

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

If possible, could you pls specify when string unicode checking would be turned on? I assume it would be turned on if we specify a field as string in .proto file, thus if we replace it with bytes or message, such checking would be turned off.

**Comment by pmixer** [comment]
@TeBoring at dalao randomly to try my luck for response...

**Comment by haberman** [comment]
Message fields are not checked for UTF-8, since serialized messages are not UTF-8 strings.

The page you linked does not discuss UTF-8 checking. UTF-8 checking happens at parse time for string fields only, and only in proto3 (not proto2).

**Comment by pmixer** [comment]
@haberman thank you Joshua, it make sense in some way.
