### ISSUE TITLE
Cannot find the relative document of such protobuf definition. Could you please kindly share some advice here? Thanks!

### ISSUE THREAD

**Issue by bugzyz** [protocolbuffers/protobuf#8451]
Hi, I am recently working at a project which contains such protobuf definition which I'm not able to find any document in your official doc.
ref:  [https://github.com/mlflow/mlflow/blob/master/mlflow/protos/service.proto#L67](url)

![image](https://user-images.githubusercontent.com/31982774/113560042-f3579080-9634-11eb-8d8a-94947fcb8f87.png)

Is this an official definition of protobuf, if it is, it will be nice if you can share some link about that!
Or this is a user-defined option? if it is, could you please send some document of how user define their own option?

Looking forward to your reply, thanks a lot!

**Comment by helintongh** [comment]
related links: https://developers.google.com/protocol-buffers/docs/proto#customoptions
Custom options can be defined for every kind of construct in the Protocol Buffers language. Here is an example that uses every kind of option:
`
service MyService {
  option (my_service_option) = FOO;

  rpc MyMethod(RequestType) returns(ResponseType) {
    // Note:  my_method_option has type MyMessage.  We can set each field
    //   within it using a separate "option" line.
    option (my_method_option).foo = 567;
    option (my_method_option).bar = "Some string";
  }
}
`
Note that creating custom options uses extensions, which are permitted only for custom options in proto3.

**Comment by haberman** [comment]
Yes, you found the correct link. This is a custom option, defined in the protobuf language.

**Comment by bugzyz** [comment]
Thanks you @helintongh ! Finally I got what this field is about.
