### ISSUE TITLE
[Javascript] Use toObject() exception

### ISSUE THREAD

**Issue by zhushenhang** [protocolbuffers/protobuf#8453]
**What version of protobuf and what language are you using?**
Version: "google-protobuf": "^3.15.6"
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
grpc-tools:1.11.1

**What did you do?**
1. Use grpc-tools to generate code
2. ``` console.log(systemStatus.getStatusgroupList().toObject());   ```

**What did you expect to see**
{ title: 'status', status: [] }
**What did you see instead?**
{ title: 'status', statusList: [] }

My field is ```status```, why does it become ```statusList```.
I am a novice and I am very confused about this.
Any help would be greatly appreciated.

**Comment by zhushenhang** [comment]
```
proto.request.StatusGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    statusList: jspb.Message.toObjectList(msg.getStatusList(),
    proto.request.Status.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};

```
I found that this pb code did change my field status to statusList

**Comment by zhushenhang** [comment]
Forget it, don’t worry about it, just don’t affect my getStatus

**Comment by thesayyn** [comment]
I think your problem is that protocol buffers put `List` as a suffix to your generated classes.
i am opinion of that it will help to solve your problem.
Checkout https://github.com/thesayyn/protoc-gen-ts#example

**Comment by zhushenhang** [comment]
@thesayyn thank you very much !
