### ISSUE TITLE
RepeatedPtrField Resize missing

### ISSUE THREAD

**Issue by yoavmil** [protocolbuffers/protobuf#8458]
Although `RepeatedField` has an `Resize` method, `RepeatedPtrField` does not. Is this intended?

**What language does this apply to?** `c++`
**Describe the problem you are trying to solve.** n/a
**Describe the solution you'd like**, just add the `resize` method, like in STL.
**Describe alternatives you've considered** looping and using 'Add()' method.
**Additional context** [see question from 2015, and my comment there](https://stackoverflow.com/questions/33193372/how-to-initialize-a-repeated-element-in-protocol-buffer).

**Comment by fowles** [comment]
Long ago, there was an intention that `RepeatedPtrField` not model "expensive" operations.  In particular `Resize` requires N heap allocations, and it was not clear it that is what the user would actually want.  I lean towards filling out the matrix fully, but we need to chat about this internally to see if there is something I am missing here.
