### ISSUE TITLE
AnyTest.TestPackFromSerializationExceedsSizeLimit fails on 32bit alpine linux

### ISSUE THREAD

**Issue by ncopa** [protocolbuffers/protobuf#8460]
**What version of protobuf and what language are you using?**
Version: protobuf-3.15.7
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Alpine linux edge (rolling release)

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Alpine 10.2.1_git20210328) 10.2.1 20210328
Python 3.9.4

**What did you do?**
1. `CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -Wno-error" ./configure --prefix=/usr ...`
2. `make -j24`
3. `cd src`
4. `make -j24 protobuf-test && ./protobuf-test --gtest_filter=AnyTest.TestPackFromSerializationExceedsSizeLimit`

**What did you expect to see**
test passed

**What did you see instead?**
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AnyTest
[ RUN      ] AnyTest.TestPackFromSerializationExceedsSizeLimit
unknown file: Failure
C++ exception with description "basic_string::_M_replace_aux" thrown in the test body.
[  FAILED  ] AnyTest.TestPackFromSerializationExceedsSizeLimit (34 ms)
[----------] 1 test from AnyTest (34 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (34 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AnyTest.TestPackFromSerializationExceedsSizeLimit

 1 FAILED TEST
```

**Anything else we should know about your project / environment**
This happens on both 32 bit x86 and armv7.

musl libc is used.

**Comment by rolandjitsu** [comment]
I have the same issue on armv7 32 bits.

**Comment by rolandjitsu** [comment]
Do previous versions have this issue? Or, is there a version where this doesn't happen?

**Comment by Apteryks** [comment]
Hello.  This test also failed for me on i686-linux.

**Comment by tatokis** [comment]
This issue is still occurring and should not have been closed. We are currently patching around it on Arch32.
