### ISSUE TITLE
Protoc PHP --grpc_out does not look in path for plugin

### ISSUE THREAD

**Issue by stemis** [protocolbuffers/protobuf#8468]
### What version of gRPC and what language are you using?
v1.36.0 through pecl

### What operating system (Linux, Windows,...) and version?
Debian 10 buster

### What runtime / compiler are you using (e.g. python version or version of gcc)
protoc-3.15.6-linux-x86_64 from protobuf/github
gcc version 8.3.0 (Debian 8.3.0-6)

### What did you do?
Protoc: The `--grpc_out` module for php is not looking at path

### Steps to reproduce the issue

**Works:**
```
protoc -I=protofiles/ \
x.proto \
--php_out=generated \
--plugin=protoc-gen-grpc=grpc_php_plugin \
```

**Doesn't work**
When adding `--grpc_out` the code fails
```
protoc -I=protofiles/ \
x.proto \
--php_out=generated/ \
--grpc_out=generated// \
--plugin=protoc-gen-grpc=grpc_php_plugin \
```
Error:
```
grpc_php_plugin: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
```

**Workaround**
Specify full path
```
protoc -I=protofiles/ \
x.proto \
--php_out=generated/ \
--grpc_out=generated// \
--plugin=protoc-gen-grpc=`which grpc_php_plugin` \
```

**Comment by TeBoring** [comment]
Could you also send this issue to grpc's repo and verify it's not an issue of grpc first?

**Comment by deannagarcia** [comment]
I'm closing this due to no response. It seems very likely to me that this is a grpc issue and not one specific to protobuf.
