### ISSUE TITLE
Conformance Required.Proto3.ProtobufInput.ValidDataOneof.MESSAGE.Merge.ProtobufOutput

### ISSUE THREAD

**Issue by jamesdbrock** [protocolbuffers/protobuf#8474]
I'm working on conformance for https://github.com/xc-jp/purescript-protobuf and I I'm having trouble understanding this failing conformance test: 

__Required.Proto3.ProtobufInput.ValidDataOneof.MESSAGE.Merge.ProtobufOutput__

What behavior, exactly, is expected by this test?

```
CONFORMANCE TEST BEGIN ====================================

ERROR, test=Required.Proto3.ProtobufInput.ValidDataOneof.MESSAGE.Merge.ProtobufOutput: Output was not equivalent to reference message: deleted: oneof_nested_message.corecursive.optional_int32: 1
deleted: oneof_nested_message.corecursive.unpacked_int32[1]: 1
. request=protobuf_payload: "\202\007\t\022\007\010\001\020\001\310\005\001\202\007\007\022\005\020\001\310\005\001" requested_output_format: PROTOBUF message_type: "protobuf_test_messages.proto3.TestAllTypesProto3" test_category: BINARY_TEST, response=protobuf_payload: "\202\007\007\022\005\020\001\310\005\001"
ERROR, test=Recommended.Proto3.ProtobufInput.ValidDataOneofBinary.MESSAGE.Merge.ProtobufOutput: Output was not equivalent to reference message: Expect: \202\007\014\022\012\010\001\020\001\310\005\001\310\005\001, but got: \202\007\007\022\005\020\001\310\005\001. request=protobuf_payload: "\202\007\t\022\007\010\001\020\001\310\005\001\202\007\007\022\005\020\001\310\005\001" requested_output_format: PROTOBUF message_type: "protobuf_test_messages.proto3.TestAllTypesProto3" test_category: BINARY_TEST, response=protobuf_payload: "\202\007\007\022\005\020\001\310\005\001"

These tests failed.  If they can't be fixed right now, you can add them to the failure list so the overall suite can succeed.  Add them to the failure list by running:
  ./update_failure_list.py  --add failing_tests.txt

  Recommended.Proto3.ProtobufInput.ValidDataOneofBinary.MESSAGE.Merge.ProtobufOutput
  Required.Proto3.ProtobufInput.ValidDataOneof.MESSAGE.Merge.ProtobufOutput
```

**Comment by jamesdbrock** [comment]
My guess is that this test is about field 112 in `test_messages_proto3.proto`. It requires that when two `TestAllTypesProto3` messages are merged, and if both message have the field 112, then the field 112 nested messages must be recursively merged. Is that it?

```
message TestAllTypesProto3 {
  message NestedMessage {
    int32 a = 1;
    TestAllTypesProto3 corecursive = 2;
  }

  // Singular
  int32 optional_int32 = 1;

  oneof oneof_field {
    uint32 oneof_uint32 = 111;
    NestedMessage oneof_nested_message = 112;
  }
```

https://github.com/protocolbuffers/protobuf/blob/ee04809540c098718121e092107fbc0abc231725/src/google/protobuf/test_messages_proto3.proto#L196-L198

**Comment by jamesdbrock** [comment]
> check that MergeFrom copies if nonzero/nondefault only.

https://github.com/protocolbuffers/protobuf/blob/ee04809540c098718121e092107fbc0abc231725/src/google/protobuf/no_field_presence_test.cc#L463

> If you set a oneof field to the default value (such as setting an int32 oneof field to 0), the "case" of that oneof field will be set, and the value will be serialized on the wire.

https://developers.google.com/protocol-buffers/docs/proto3#oneof_features

My new theory is that the test is failing because when merging messages which contain a Oneof, we must check for default values in the Oneof, because Oneof default values are serialized to the wire.

**Comment by jamesdbrock** [comment]
So if we have an old message with a Oneof field set to default, and then we merge a new message with the Oneof field set to default but with a different case, then the resulting merged message should get the new case, right? Is that how it's supposed to work? Or do we keep the case of the old message?

**Comment by acozzette** [comment]
I'm not familiar with that particular conformance test, but to answer your last question, the merged question should get the new case. With merging or concatenating messages, later appearances generally supersede earlier ones.

**Comment by jamesdbrock** [comment]
What if we have an old message with a Oneof field set to non-default, and then we merge a new message with the Oneof field set to default value and with a different case?

Then the resulting message should have the case and default value of the new message, right?

**Comment by acozzette** [comment]
Right, the resulting message should take one the case and value of the new message. (By the way, I could be missing something but I don't think it really matters whether the field in a oneof is set to its default value or not. The notion of _which_ field within the oneof is currently set is significant, but as far as merging goes there is nothing special about the default value.)

**Comment by jamesdbrock** [comment]
I think these are the tests which are failing.

https://github.com/protocolbuffers/protobuf/blob/0ef575beff5a627a4a1e8e15e462039d3aed2ad3/conformance/binary_json_conformance_suite.cc#L1228-L1231

**Comment by jamesdbrock** [comment]
Ok I solved it. I was neglecting to merge optional Oneof nested message fields, exactly as the conformance test was reporting. Also I made this thing http://jamesdbrock.github.io/protobuf-decoder-explainer/
