### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by fmeum** [protocolbuffers/protobuf#8480]
OSS-Fuzz has added support for Java fuzzing with [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) and could thus be used for continuous fuzzing of `protobuf-java`. Jazzer has already found the bugs fixed in https://github.com/protocolbuffers/protobuf/commit/4008d229aa7505775486d6a86705efd2800599b3#diff-39e30ba0f9474a5c558a5c5496dd085d7ff93ae2f3521416735287a1ae4153e3.

I have prepared the integration over at https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/ae8efb88f0b73e906f02ecdd06b581656091dfc5. In case you are interested, I would only need a list of email addresses that should receive the bug reports. @acozzette I included you as the maintainer in this draft of the integration only because you synced the change with the fixes for my VRP bug report. 

If you have any questions concerning the integration, I'm happy to help.

**Comment by huornlmj** [comment]
Hi @fmeum .  Does this mean that all contributions to this repo eventually get included in fuzzing?

**Comment by fmeum** [comment]
@huornlmj At least for the Java and C++ parts that should be the case.

**Comment by fmeum** [comment]
The corpus and crashes are confidential and only accessible to registered project maintainers. Coverage reports are public though: https://storage.googleapis.com/oss-fuzz-coverage/protobuf-c/reports/20230213/linux/report.html

**Comment by huornlmj** [comment]
That's great.  Have you considered adding the oss-fuzz badge? https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge
