### ISSUE TITLE
How am I able to create strings enum of Typescript?

### ISSUE THREAD

**Issue by antonphilin** [protocolbuffers/protobuf#8483]
**What language does this apply to?**
I use proto3.
programming language - typescript

**Describe the problem you are trying to solve.**
I have quite a lot of string enums used on my project

enum Corpus {
  INSTANT = "INSTANT",
  FULL = "FULL",
}

but, as far as I see in the .proto file allow use number enum.

**Describe the solution you'd like**
I want to crate strings enum, is there any way to describe string enums in the proto file?

**Describe alternatives you've considered**
Using string type instead of strings enum (but it incorrect type)

**Comment by deannagarcia** [comment]
Unfortunately proto fields do not support that syntax and very likely never will. This is about consistency of language and implementation/wire format. You can read more about this design [in the proto enum documentation](https://developers.google.com/protocol-buffers/docs/proto3#enum).
