### ISSUE TITLE
constexpr defaulted default constructor of WrappedMutex causes compile errors

### ISSUE THREAD

**Issue by przole** [protocolbuffers/protobuf#8492]
Version: 3.15.8
Language: C++

Windows 10 Enterprise 20H2 19042.867

Microsoft Visual Studio Enterprise 2019 Version 16.9.4

1. Compile project with generated protobuf class causes:

Error		defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr	...\include\google\protobuf\stubs\mutex.h	119

**constexpr** _WrappedMutex()_ = **default;**
should be:
**constexpr** _WrappedMutex()_ {}

**Comment by elharo** [comment]
fixed, I think
