### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe.dll compatibility issue with latest version

### ISSUE THREAD

**Issue by Giakalis** [protocolbuffers/protobuf#8515]
Hi,

I am struggling very hard with a very annoying problem about the System.Runtime.CompilerServices.Unsafe.dll.

In a .NET Framework project, Google.Protobuff seems like it depends on System.Memory.dll >= v4.5.3 which it is depending on System.Runtime.CompilerServices.Unsafe.dll v4.5.3 (which is the 4.0.4.1 in assembly version). If you have another project that has reference for example in MavLink library which has a direct dependency on System.Runtime.CompilerServices.Unsafe.dll v4.7.0 (which is the 4.0.6.0 in assembly version) then your main project that reference those 2 projects at the end it will have the greater versioning unsafe dll in the output folder and that will break Google.Protobuff communication because it cannot find the System.Runtime.CompilerServices.Unsafe.dll 4.0.4.1. I have tried many stuff (redirect dependencies etc) but nothing really works.

Most annoying is that the fact that if you have a .NET Standard v2.0 project, the Google.Protobuff says that it depends directly on the System.Runtime.CompilerServices.Unsafe.dll >= 4.5.3 which someone would thing that if you have a greater unsafe dll version will work but apparently it does not!

What I found working though is that if I download the Google.Protbuff source code and remove from the project files all the .NET project dependencies and keep only the .NET Standard v2.0 and change the required System.Runtime.CompilerServices.Unsafe.dll version from 4.5.3 to 4.7.0 then it seems that it works.

So my question is, if it is possible to look on this problem and maybe make Google.Protobuff able to compile/work with the System.Runtime.CompilerServices.Unsafe.dll v4.7.0?

Thank you for your time.

**Comment by jtattermusch** [comment]
Feel free to propose changes to the protobuf source code, but I think working around the System.Runtime.CompilerServices.Unsafe is not going to be easy. Btw, it seems that this is a problem that isn't directly related to Google.Protobuf. IIUC, any other library that depends on System.Memory will suffer from exactly the same problem - so this seems to be more of a problem of System.Memory, rather than Google.Protobuf.

**Comment by Giakalis** [comment]
I agree that this seems to be a problem of System.Memory and yes any other library that depends on System.Memory will have the same issue. But wouldn't be possible in the project file where there is a reference for the .NET Standard 2.0 projects that requires directly System.Runtime.CompilerServices.Unsafe 4.5.3 to change it to 4.7.0?

I mean that's how I managed to make it to work for my specific problem.
Of course .NET Framework projects will still have the issue but at least .NET Standard Projects 2.0 will be able to work with System.Memory 4.5.1 and System.Runtime.CompilerServices.Unsafe 4.7.0 right?

The only difference will be that the compiler will not complain that it cannot find the System.Runtime.CompilerServices.Unsafe 4.0.4 (assembly version).  Unfortunately redirecting does not help the compiler since the System.Memory depends on that 4.0.4 unsafe. But if there is a direct reference to a later version of unsafe like I am suggesting, I think it would work.

**Comment by jtattermusch** [comment]
What we currently have is this:
https://github.com/protocolbuffers/protobuf/blob/5e84a6169cf0f9716c9285c95c860bcb355dbdc1/csharp/src/Google.Protobuf/Google.Protobuf.csproj#L44

what is it that you're suggesting?

**Comment by Giakalis** [comment]
Yes. Would it possible in Net Standard dependency to have unsafe 4.7.0 instead?

Best Regards
Alexandros

________________________________
