### ISSUE TITLE
MessageToDict converts uint64 to string in python

### ISSUE THREAD

**Issue by chris-from-the-coast** [protocolbuffers/protobuf#8520]
**What version of protobuf and what language are you using?**
Version: protobuf 3.12.4 and 3.15.8
syntax = "proto3"

Language: Python

**What operating system (Linux, Windows, ...) and version?**
Macos: 10.15.7 64-bit

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.7
`import struct;print( 8 * struct.calcsize("P"))`
Output:
> 64

**What did you do?**

1. Create a source proto file with
```
message transmitter {
  ...
  uint64 transmitter_ticks = 8;
  ...
}
```

2. Compile
`protoc -I=$SRC --python_out=./ $SRC/transmitter.proto

3. Parse a transmitter message with the ticks set to 1618188465. (Note ticks is of the type int)

4.  Pass the message to `MessageToDict(parsed_transmitter_message)`

**What did you expect to see**
type(transmitter_ticks) should be an int

**What did you see instead?**
type(transmitter_ticks) is a str

**Anything else we should know about your project / environment**
Example code:
Source protobuf code:
```
...
syntax = "proto3";
message transmitter {
  string xxx = 1;
  optional Units xxx = 2;
  TimestampWithOffset xxx = 3;
  TimestampWithOffset xxx = 4;
  uint32 xxx = 5;
  string xxx = 6;
  string xxx = 7;
  uint64 transmitter_ticks = 8;
  string xxx = 9;
  string xxx = 10;
}
```
Client code:
```
MessageToDict(transmitter_message)
Output:
{
  ...
  'transmitterTicks' = '1618188465', # Should be an int
  ...
}
```

**Comment by chris-from-the-coast** [comment]
Hey guys. I just wanted to check up on this issue.

**Comment by anandolee** [comment]
The behavior is correct according to our json mapping:

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by hxtk** [comment]
I wonder how you intend that behavior to interact with the `jstype` pseudo-option. From my reading, the `jstype` option would allow a user to annotate a field as preferring a numeric type with a message definition such as the following:

```proto
message Foo {
   int64 bar = 1 [jstype = JS_NUMBER];
}
```

It would be relatively easy to implement this functionality with [this 3-line patch](https://github.com/protocolbuffers/protobuf/compare/main...hxtk:protobuf:push-zwnnxwmwulup?expand=1). If you agree with my interpretation of the intended behavior of the `jstype` field option, I'd be happy to open a pull request of that patch or a modified version of it (perhaps a modified version that includes at least one test that includes a JSType annotation), or a maintainer can make the change themselves. I'm quite sure I've gotten something wrong with the imports and I don't think that change is ready for a pull request as-is, but I think the diff at least paints a picture of the intent.

Alternately, if maintainers disagree with my interpretation of the `jstype` field option, I would appreciate a correction.
