### ISSUE TITLE
Need help with GPBUtil::checkMapField

### ISSUE THREAD

**Issue by sanmiguel2019** [protocolbuffers/protobuf#8527]
For one of my projects I automatically generated php classes from protofile.

One of the files contains this function:

```
    public function setHead($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->head = $arr;        
        return $this;
    }
```

I have no idea how to pass data to this function. It only accepts array, so I use it in this way:

```
$head = array("mime"=>"text/x-drafty");
$clientPu->setHead($head);
```

Unfortunately, the result is now what I need.

I need to send to the server:

`"head":{"mime":"text/x-drafty"}`

but function setHead produces:

`head:<key:"mime" value:"text/x-drafty" >`

What I am doing wrong? Thanks.

**Comment by TeBoring** [comment]
You can do `foo->getHead()["mime"] = "text/x-drafty"`
