### ISSUE TITLE
how to use vs2015 compile protobuf v3.15.8

### ISSUE THREAD

**Issue by Uangski** [protocolbuffers/protobuf#8533]
how to use vs2015 compile protobuf v3.15.8

**Comment by Sbarbacil** [comment]
Good morning,

I too am having problems compiling v3.15.8. I am using Visual Studio 2015 (14.0.23107.0 D14REL) on Windows10. I cannot install a newer version of Visual Studio so I would like to know how to proceed.

I generate with cmake the project like this:

C:\U64078Downloadsprotobuf-3.15.8\cmakebuilddebug>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../install_debug -Dprotobuf_BUILD_TESTS=OFF ../....
--
-- 3.15.8.0
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/U64078/Downloads/protobuf-3.15.8/cmake/build/debug

And when I compile with nmake I get the following error:

C:\U64078/Downloads/protobuf-3.15.8/cmake/build/debug>nmake.

Microsoft Program Maintenance Utility (R) version 14.00.23026.0
(C) Microsoft Corporation. All rights reserved.

Scanning dependencies of target libprotobuf-lite
[ 1%] Building CXX object CMakeFiles/libprotobuf-lite.dir/C_/Users/U64078/Downloads/protobuf-3.15.8/src/google/protobuf/any_lite.cc.obj
any_lite.cc
C:\Usersers\U6407878/Downloads/protobuf-3.15.8/src/google/protobuf/arena.h(427): error C2228: left operand of '.GetArena' must have class/struct/union
C:\Usersers\U6407878Downloads\protobuf-3.15.8\src\google/protobuf/arena.h(427): note: type is 'add_rvalue_reference<const U>::type'.
C:\U6407878Downloads\protobuf-3.15.8\src\google/protobuf/arena.h(292): note: see reference to creating template instances of class 'google::protobuf::Arena::InternalHelper<T>' that is being compiled
        with
        [
            T=google::protobuf::internal::ImplicitWeakMessage
        ]
C:\Usersers\U64078\Downloads\protobuf-3.15.8\src\google/protobuf/implicit_weak_message. h(68): note: see reference to function template instance creation 'T *google::protobuf::Arena::CreateMessage<google::protobuf::internal::ImplicitWeakMessage,>(google::protobuf::Arena *)' being compiled
        with
        [
            T=google::protobuf::internal::ImplicitWeakMessage
        ]
NMAKE : fatal error U1077: 'C:\ProgramData\cmake-3.20.1\bin\cmake.exe' : code returned '0x2'.
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0.0\VC\BIN\nmake.exe"' : code returned '0x2' Stop. : code returned '0x2'.
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0.0\VC\BINNmake.exe"' : code returned '0x2' Stop. : code returned '0x2'.
Stop.

If I compile with Visual Studio 2015 IDE I get the same errors.

Translated with www.DeepL.com/Translator (free version)

**Comment by elharo** [comment]
I'm afraid we don't have resources to support older versions of Visual Studio.
