### ISSUE TITLE
proto3 C# System.ArgumentException: method return type is incompatible

### ISSUE THREAD

**Issue by FreeMotion45** [protocolbuffers/protobuf#8535]
Constantly crashing when my application starts up if I want to use protobuf:

The line that crashes:
```
descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RpgGame.Proto.Position), global::RpgGame.Proto.Position.Parser, new[]{ "X", "Y" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RpgGame.Proto.Monster), global::RpgGame.Proto.Monster.Parser, new[]{ "Id", "HP", "Position" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RpgGame.Proto.Character), global::RpgGame.Proto.Character.Parser, new[]{ "CharacterName", "Positon" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RpgGame.Proto.NPC), global::RpgGame.Proto.NPC.Parser, new[]{ "NpcName", "Position" }, null, null, null, null)
          }));
```

Error message:
```
System.ArgumentException: method return type is incompatible
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) [0x00069] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Reflection.RuntimeMethodInfo.CreateDelegate (System.Type delegateType) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at Google.Protobuf.Reflection.ReflectionUtil.CheckCanConvertEnumFuncToInt32Func () [0x00014] in <0085ba399ecf44e18e22d9f5d20521e8>:0 
```

My .proto file:
```
message Position {
    int32 x = 1;
    int32 y = 2;
}

message Monster {
    int32 id = 1;
    int32 HP = 2;
    Position position = 3;
}

message Character {
    string characterName = 1;
    Position positon = 2;
}

message NPC {
    string npcName = 1;
    Position position = 2;
}
```

**Comment by jtattermusch** [comment]
Key information is missing:
- what .NET version and what platform / OS are you running your code?
- what version of protobuf runtime and what version of protoc (the codegen) are you using?

First thing I'd check is whether your runtime matches the version of codegen (perhaps you're using a very recent version of generated code with older runtime  or so).

It would also help if you provided a ready-to-run reproduction (e.g. as a github repo).

**Comment by jtattermusch** [comment]
> > Key information is missing:
> > 
> > * what .NET version and what platform / OS are you running your code?
> > * what version of protobuf runtime and what version of protoc (the codegen) are you using?
> > 
> > First thing I'd check is whether your runtime matches the version of codegen (perhaps you're using a very recent version of generated code with older runtime or so).
> > It would also help if you provided a ready-to-run reproduction (e.g. as a github repo).
> 
> OS: Windows 10 64 bit.
> Running the latest version of the protobuf runtime and codegen with .NET Framework 4.7.

Can you provide the reproduction?

**Comment by FreeMotion45** [comment]
I just added the generated .cs files to the solution, and the static constructor inside them throws this exception. I will link them here in a comment when I get my hands on them again (matter of hours).

**Comment by deannagarcia** [comment]
Closing due to no response, but feel free to reopen with a simple reproduction case!
