### ISSUE TITLE
Update protobuf copyright notice

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#854]
Currently we use "Copyright Google Inc." in the copyright header, but as we accept more and more contributions from the community, Google Inc. is not the only copyright holder and we should reflect that in the header. Also there are files with a different copyright header right now in our repository and we'd better unify them.

The recommended way is to:
1. Use "Copyright The [Project] Authors" in the header.
2. List all copyright holders in AUTHORS
3. List individual contributors in CONTRIBUTORS

**Comment by elharo** [comment]
https://g3doc.corp.google.com/company/teams/opensource/copyright.md?cl=head are the official rules we need to follow.
