### ISSUE TITLE
Provide actual install instructions that work

### ISSUE THREAD

**Issue by dumbjarvis** [protocolbuffers/protobuf#8540]
Please provide install instructions in README.md file that actually work.

Error:
```
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

**Comment by deannagarcia** [comment]
I'm sorry it took so long to get this.

We don't maintain `protoc-gen-go`. If you are still having this problem please file with the golang team here: https://github.com/golang/protobuf.
