### ISSUE TITLE
${PROTOBUF_INCLUDE_DIR} should *not* point to <prefix>/usr/include

### ISSUE THREAD

**Issue by darkdragon-001** [protocolbuffers/protobuf#8543]
**What version of protobuf and what language are you using?**
Version: v3.15.8
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 21.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
`armv7at2hf-neon-fslc-linux-gnueabi`

**What did you do?**
Add following code to `CMakeLists.txt`
```
find_package(Protobuf REQUIRED)
include_directories(SYSTEM ${PROTOBUF_INCLUDE_DIR})
```
aka adding protobuf includes as `SYSTEM` includes. The variable is filled with `<prefix>/usr/include`.

**What did you expect to see**
Compilation should work just fine.

**What did you see instead?**

Can't compile because `stdlib.h` not found.

**Anything else we should know about your project / environment**

This is the case, because it adds `-isystem<prefix>/usr/include` to the compilation flags which conflicts with `#include_next <stdlib.h>` within `cstdlib`.
More details in: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

**Comment by haberman** [comment]
Would you be able to send a PR for this?

**Comment by darkdragon-001** [comment]
After reading over the details again, I think there is nothing which protobuf can do to fix the issue. There are multiple approaches listed in the linked GCC bug though.
