### ISSUE TITLE
Define field mask path for non-last repeated fields

### ISSUE THREAD

**Issue by nnutter** [protocolbuffers/protobuf#8547]
**What language does this apply to?**

proto3 I guess since [google/protobuf/field_mask.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto) seems to be proto3 only.

**Describe the problem you are trying to solve.**

Given,

```protobuf
syntax = "proto3";
package example;

message M {
  repeated N ns = 1;
}

message N {
  string a = 1;
  string b = 2;
}
```

Why does [google/protobuf/field_mask.proto](https://github.com/protocolbuffers/protobuf/blob/5e84a6169cf0f9716c9285c95c860bcb355dbdc1/src/google/protobuf/field_mask.proto#L85-L86) say,

> A repeated field is not allowed except at the last position of a paths string.

This makes the official field masks incredibly crippled for any message which uses repeated fields and it seems reasonable to want to be able to say I only want `ns.a` or `ns.b` just as if the field were not repeated.  Obviously one could be concerned about filtering/indexing like how JSONPath uses `[0]`/`[*]` but it seems like allowing `ns.a` would not preclude something more complex being added later.

**Describe the solution you'd like**

I would like to be able to specify a field mask path with a repeated field in a non-last position.

**Describe alternatives you've considered**

- Forking or using something besides field masks.
- Having to specify additional field masks for each repeated field.

**Additional context**

A recent change in the Go implementation of Field Masks, https://github.com/golang/protobuf/issues/1179, broke us.  It is just trying to comply with a constraint from here,

> [field_mask.proto](https://github.com/protocolbuffers/protobuf/blob/9b0fa3e7fbaf3463c3afa1c9ab111682108eeadb/src/google/protobuf/field_mask.proto) mentions that ...
> 
> ```protobuf
> // Field masks are used to specify a subset of fields that should be
> // returned by a get operation or modified by an update operation.
> 
> ...
> 
> // # Field Masks in Projections
> // ...
> // A repeated field is not allowed except at the last position of a
> // paths string.
> 
> ...
> 
> // # Field Masks in Update Operations
> // ...
> // Note that a repeated field is only allowed in the last position of a `paths` string.
> ```
> 
> Given those statements, I think FieldMask.IsValid should return false if a path contains a repeated field that is not in the last position.

I also found this question asked, [How do I create a field mask for a field of a repeated field?](https://groups.google.com/g/protobuf/c/vfOKR5Hq0Mk/m/jx-dGpFPBwAJ), but the response was from two years ago,

> This is not supported at the moment, i.e., you can't use 'cats.name' in the FieldMask because 'cats' is a repeated field.

**Comment by VAllens** [comment]
We need it !!!

**Comment by xistz** [comment]
Would like to hear if there are any updates on this too 🙏

**Comment by alok87** [comment]
This is such an important thing to be out there. Proto helps in making things language agnostic but this becomes a big blocker, anyone knows if this was agreed to be taken in atleast?

**Comment by alok87** [comment]
hey m interested to contribute to, any info on how and I can also help out  @jskeet

**Comment by jskeet** [comment]
@alok87: The first order of business is working out what to do. There's a lot of complexity here. Once we've discussed this internally, I'll get back to you.

**Comment by ericning00** [comment]
Hey @jskeet! Thanks for responding here. Wondering if there are any updates since we're considering forking some utilities (e.g. FieldMaskUtil) to support AIP-161

**Comment by jskeet** [comment]
@ericning00: I need to chase my proposal internally - but that proposal is broadly:

- Don't break anything! Avoid changing any existing behavior
- Add documentation to both the standard proto and the AIP indicating that other behavior is available

There are multiple different ways in which the AIP diverges from the standard behavior; some of that is already supported in standard proto libraries (at least for many languages) but not all.

I wouldn't expect to see *new* functionality in standard libraries any time soon, so you may well wish to fork.

**Comment by caseymanusbayer** [comment]
What's the status on this issue?  We've pinned our dependency to v1.25 for a long time but can't continue that practice much longer.

**Comment by jskeet** [comment]
@caseymanusbayer It's been low priority, I'm afraid. I don't know much about the Go code, but I wouldn't personally expect to be making changes soon.

**Comment by jskeet** [comment]
Note: I'm coming back to FieldMasks at the moment, initially to make a plan for what's required. No promises yet, but I'll be bearing this issue in mind.

**Comment by VAllens** [comment]
Please reopen it, this is an important feature

**Comment by jskeet** [comment]
Reopening, but I don't know when we'll get to it.

**Comment by rofrankel** [comment]
This is also relevant to our interests over at Roblox.  Support for the wildcard described by the AIPs would be great.

**Comment by kellen-miller** [comment]
bump to re-open this.

**Comment by VAllens** [comment]
Please reopen it

**Comment by TTPO100AJIEX** [comment]
> Note: I'm coming back to FieldMasks at the moment, initially to make a plan for what's required. No promises yet, but I'll be bearing this issue in mind.

Hello, @jskeet . Have there been any updates on the implementation of AIP-161? Is there any chance to complete it any time soon?

**Comment by jskeet** [comment]
@TTPO100AJIEX: No updates at the moment - I'm not personally working in this area any more. I wouldn't expect anything *soon* I'm afraid.

**Comment by TTPO100AJIEX** [comment]
Hello again, @jskeet. 
We recently implemented AIP-161-compliant field masks for read operations in C++ for our project. We might be able to backport our implementation to make it available for all protobuf users. Could you (or anyone else working in this area) please share your experience on how you tried to introduce it in this package?
- Should we extend the original google.protobuf.FieldMask, or should it be a separate implementation to avoid affecting existing users?
- What minimal scope is required for you to consider merging our contribution? For example, we do not have full support for all FieldMaskUtil methods.
- Should the contribution be made in all languages at the same time? Can we limit ourselves to C++ only?
- What pitfalls have you encountered when trying to work on this issue? You mentioned there are many concerns about compatibility. Could you please elaborate?

As you mentioned previously, you are not working on this project anymore. But could you please direct us to someone who can consult us on these issues?

**Comment by jskeet** [comment]
> Could you (or anyone else working in this area) please share your experience on how you tried to introduce it in this package?

I'm afraid I haven't looked at any field mask work for a long time now. I will ask (on Monday) folks who have been looking at field masks more recently. (Even just answering your questions thoroughly would take rather longer than I have to spare at the moment.)

**Comment by TTPO100AJIEX** [comment]
Hello, @jskeet. Gentle reminder :)

**Comment by jskeet** [comment]
@TTPO100AJIEX: I've sent an email to the person who has taken on the field mask work. I'm now on vacation until January, so please don't expect any further responses until then (and even then, I don't know whether anything will happen).
