### ISSUE TITLE
Support a way to statically represent a field as a int64 id

### ISSUE THREAD

**Issue by mohitmv** [protocolbuffers/protobuf#8549]
Assume I need to represent a field - `Table::Column::DataType::FieldA`  and I need to pass this field to some function, which is suppose to visit on a proto message of `Table` type and it's supposed to do something on all fields of Table (recursively)  excluding `FieldA`. How do I pass `FieldA` without passing the `"Table::Column::DataType::FieldA"` string ? I need a int64_t representation for performance reasons.

I know that I can do this with:

1. Member function pointer - `DataType::has_FieldA`, and cast it to int64_t, because this function pointer is guaranteed to be unique as long as `has_FieldA` is not inline and it's is defined in `table.pb.cc`. But it's not guaranteed that future version of protobuf will not break this requirement.

2. I can use Pair(const Descriptor*, int field_number)... where Descriptor is for the parent `Message` (DataType in this case) and `field_number` is calculated using `DataType::k{Field}FieldNumber`... This is kind of ok but has require 16 bytes to store and not seamless to use.

How about creating a method: 
`static int64_t DataType::FieldA_Id();` ?

This Id is going to be unique for FieldA. One way to create this id is  - `combined_hash(int64 casted Descriptor*, field_number)`....

This cannot be solved by adding a wrapper on top of generated C++ code. It has to be incorporated in the generation layer itself.

**What language does this apply to?**
C++14

**Describe the problem you are trying to solve.**
Described above.

**Describe the solution you'd like**
Described above.
Here is another solution : Generate a type for each field.. 
Currently it's generated for each Message field but we need to generate it for primitive types as well.
For example - Generate an opaque type `struct fieldA_t { };`  for each field in a message. I could use typeinfo or other things to generate a unique id for a unique id. In fact there are lot other benefits of a unique type for each field.

**Describe alternatives you've considered**
Described above.

**Additional context**
N/A

**Comment by haberman** [comment]
If your performance requirements necessitate some custom codegen for this, I'd recommend implementing your own code generator. It's reasonably easy to do this with the code generator framework (see https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.plugin) and it would give you full freedom to implement whatever extra code you need.

I think your use case is specialized enough that it probably wouldn't make sense to add this to the main C++ code generator.

**Comment by mohitmv** [comment]
Ok. Thanks.
