### ISSUE TITLE
Seems like the Python example is quite outdated 

### ISSUE THREAD

**Issue by nonopolarity** [protocolbuffers/protobuf#8551]
**What version of protobuf and what language are you using?**
Version: master/6.11.2
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Mac Big Sur

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.2

**What did you do?**

https://stackoverflow.com/questions/67344867/how-to-make-a-basic-protobuf-program-work-using-python-as-on-googles-developer

Follow https://developers.google.com/protocol-buffers/docs/pythontutorial
and got
```
Traceback (most recent call last):
  File "run.py", line 40, in <module>
    address_book = addressbook_pb2.AddressBook()
NameError: name 'addressbook_pb2' is not defined
```

**What did you expect to see**
see it working

**What did you see instead?**
the error

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by fowles** [comment]
David, do the new docs help with this?
