### ISSUE TITLE
[Ruby] Exception inspecting a message on Windows (3.15 regression)

### ISSUE THREAD

**Issue by dazuma** [protocolbuffers/protobuf#8554]
/attn: @haberman

**What version of protobuf and what language are you using?**
Version: 3.15.8
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Windows Server 2019 (10.0.17763), via the "windows-latest" platform on GitHub Actions.

**What runtime / compiler are you using (e.g., python version or gcc version)**
n/a (using the binary gem release)

**What did you do?**

```ruby
require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("windoze.proto", :syntax => :proto3) do
    add_message "windoze.SimpleTest" do
      # Note: No fields necessary
    end
  end
end
module Windoze
  SimpleTest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("windoze.SimpleTest").msgclass
end

message = Windoze::SimpleTest.new
puts message.inspect
```

**What did you expect to see**

I expect a string representation of an empty message to be displayed.

**What did you see instead?**

A `TypeError` is raised with the following message: ```in `inspect': wrong argument type nil (expected Google::Protobuf::DescriptorPool)```.

The stack trace identifies the final line in the provided Ruby code (`puts message.inspect`) but no further information is given. (I believe the `inspect` method is [implemented in C](https://github.com/protocolbuffers/protobuf/blob/38e1b592581983548eb8012e45a3a1da64b6504f/ruby/ext/google/protobuf_c/message.c#L748).)

**Anything else we should know about your project / environment**

* This appears to be a 3.15 regression. It does not reproduce on 3.14, but does reproduce on various patchlevels of 3.15. (I tried 3.15.8, 3.15.6, and 3.15.2.)
* This appears to be Windows-specific. I can get it to reproduce on a Windows machine (via GitHub Actions), but not on MacOS or Linux.
* I can reproduce it by installing the `x64-mingw32` build of the gem, and by forcing the platform to `ruby` and building the gem from source on install.
* The error appears regardless of whether there are fields present in the proto description or not.
* There are different ways of reproducing the error. The sample code above is the simplest, but I'm also able to reproduce it under certain circumstances when fetching fields in a nested message structure. I can provide additional repro examples if needed.

**Comment by dazuma** [comment]
It's been difficult for me to get a real stack trace since I don't actually have a Windows machine to test or build on, but based on an analysis of what kind of code will trigger the exception and what won't, I believe the exception is coming from the following call stack. (Links are from the 3.15.8 tag.)

* `ruby_to_Descriptor()` ([`ruby/ext/google/protobuf_c/defs.c` line 401](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L401))
* `Descriptor_DefToClass()` ([`ruby/ext/google/protobuf_c/defs.c` line 2486](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2486))
* `Message_PrintMessage()` ([`ruby/ext/google/protobuf_c/message.c` line 141](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L141))
* `Message_inspect()` ([`ruby/ext/google/protobuf_c/message.c` line 752](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L752))

If I'm reading this right, `Qnil` is being passed to `ruby_to_Descriptor()`. Tracing this back out, the only way I can account for that is if the `msgdef` field is`NULL`, and gets passed in [here](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2485) and runs afoul of [this code](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2441-L2443). I think the only place that `msgdef` gets set is [here](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L83). Is there a way that a class's Descriptor could be uninitialized?

**Comment by dazuma** [comment]
No, that's not it. The descriptor seems fine. I can retrieve it from the class and call methods that reference the `msgdef`. And looking again at the exception I'm getting, it's actually the DescriptorPool that's nil:

* `ruby_to_DescriptorPool()` ([`ruby/ext/google/protobuf_c/defs.c` line 273](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L273))
* `get_def_obj()` ([`ruby/ext/google/protobuf_c/defs.c` line 2435](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2435))
* `get_msgdef_obj()` ([`ruby/ext/google/protobuf_c/defs.c` line 2456](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2456))
* `Descriptor_DefToClass()` ([`ruby/ext/google/protobuf_c/defs.c` line 2485](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/defs.c#L2485))
* `Message_PrintMessage()` ([`ruby/ext/google/protobuf_c/message.c` line 141](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L141))
* `Message_inspect()` ([`ruby/ext/google/protobuf_c/message.c` line 752](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L752))

The DescriptorPool is coming from the ObjectCache. I'll see if I can confirm whether that indeed is coming back as nil...

**Comment by haberman** [comment]
Wow excellent debugging work.

What version of Ruby is this on? Ruby <2.7 has big differences with Ruby >=2.7 in the object cache.

**Comment by dazuma** [comment]
I've tried it on both 2.7 and 3.0. Same behavior.

**Comment by dazuma** [comment]
oh but I haven't tried 2.6. Lemme try that.

**Comment by haberman** [comment]
Good to know. Ruby 2.7 is using the simpler ObjectCache code, so that somewhat narrows down where the bug could be.

I'm worried we're running into weirdness with `ObjectSpace::WeakMap` itself, which could be hard to work around. :/

**Comment by dazuma** [comment]
Does not reproduce on 2.6!!

**Comment by haberman** [comment]
I have a theory. If you're able to modify the source, could you add the following line here, before the return: https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/protobuf.c#L347

```
  if (!RB_FIXNUM_P(ret)) rb_raise(rb_eRuntimeError, "Key must be fixed!");
```

**Comment by haberman** [comment]
Ah sorry, I mean right before `#if USE_SECONDARY_MAP`

**Comment by dazuma** [comment]
I am not sure if I can come up with a way to modify the source, but I'll try.

(Note: if I understand where you're going with this, it suggests something else I've seen but haven't gotten a chance to report yet, might be related. Sometimes, calculating the hash of a message on Windows, results in Ruby asserting internally saying the value is not a legal fixnum.)

**Comment by haberman** [comment]
After a bit more investigation, I'm having more confidence in my theory.

The theory is that on Windows, pointer values when converted to an integer are too big to fit in a Ruby `Fixnum`. I think this is true because [Ruby uses `LONG_MAX` to decide what will fit in a `Fixnum`](https://github.com/ruby/ruby/blob/b85fd1d690b65efaa126cf9c24da73f31eee7a4e/include/ruby/internal/arithmetic/fixnum.h#L41-L42), but [on 64-bit Windows `long` is 32 bits](https://stackoverflow.com/a/59852878/77070).

The object cache uses `ObjectSpace::WeakMap`, which will collect and erase any entries where the key *or* value is collectible. We were counting on the keys not being collectible because they are `Fixnum`, but on Windows this assumption doesn't hold, causing object cache entries to get evicted prematurely.

The workaround code from Ruby 2.6 and earlier helps because it create a secondary map that is not weak to store WeakMap keys. Since the WeakMap keys are referenced from the secondary map, and because the value (the DescriptorPool) is presumably referenced from somewhere else, the entries don't get collected and the object cache lookup succeeds.

**Comment by dazuma** [comment]
And I can confirm that the key is not a fixnum.

**Comment by haberman** [comment]
I actually wonder if this is a bug in Ruby. The [comment here](https://github.com/ruby/ruby/blob/b85fd1d690b65efaa126cf9c24da73f31eee7a4e/include/ruby/internal/arithmetic/fixnum.h#L32-L34) says:

```c
 /* FIXABLE can be applied to anything, from double to intmax_t.  The problem is
 * double.   On a  64bit system  RUBY_FIXNUM_MAX is  4,611,686,018,427,387,903,
 * which is not representable by a double.
```

But this is not true on Windows 64-bit systems.

In any case, we'll clearly need a workaround for this to accommodate existing Ruby deployments on Windows.

**Comment by dazuma** [comment]
Yeah, I can confirm the behavior.

```c
sprintf(infostr,
  "key=%p ret=%llx ptrsiz=%d valsiz=%d fixmaxsiz=%d fixmin=%lx fixmax=%lx lonmin=%lx lonmax=%lx",
  key, ret, sizeof(key), sizeof(ret), sizeof(RUBY_FIXNUM_MIN),
  RUBY_FIXNUM_MIN, RUBY_FIXNUM_MAX, LONG_MIN, LONG_MAX);
```

(where `key` is the incoming pointer, and `ret` is a VALUE, the result of running `LL2NUM((intptr_t)key >> 2)`)

A typical run for 64-bit windows:

```
key=0000020db8d824c0 ret=20db8eedbb8 ptrsiz=8 valsiz=8 fixmaxsiz=4
fixmin=c0000000 fixmax=3fffffff lonmin=80000000 lonmax=7fffffff
```

Note that `ret` is clearly a different pointer. Ruby has allocated a new object. And sizeof(long) is 4, so the 64-bit pointer is outside the range.

A typical run for 64-bit Linux (or MacOS):

```
key=0x5570071017f0 ret=2ab803880bf9 ptrsiz=8 valsiz=8 fixmaxsiz=8
fixmin=c000000000000000 fixmax=3fffffffffffffff lonmin=8000000000000000 lonmax=7fffffffffffffff
```

In this case, `ret` is the expected `((key >> 2) << 1) + 1` for a Fixnum.

I can try to reach out to Aaron; he'd at least know who to talk to. It may be that they agree that it's an error to assume `sizeof(long) == sizeof(ptr)`. However, that said, it's also possible the intent actually is to ensure that fixnums always fit in a `long`, independent of the size of a pointer. I think we should consider retaining the secondary map (or otherwise creating some other workaround) for platforms where the size is indeed different.

**Comment by dazuma** [comment]
In fact, looking at more of the Ruby headers, there's a lot of code that just assumes `long` for representing fixnums. For example, Fixnum creation funnels into [`RB_INT2FIX`](https://github.com/ruby/ruby/blob/b85fd1d690b65efaa126cf9c24da73f31eee7a4e/include/ruby/internal/arithmetic/long.h#L82-L96), which uses `long`, and there is no `long long` equivalent. I suspect that's the intent (for now), and we're just going to have to adjust our assumptions on the protobuf side.

**Comment by haberman** [comment]
Thanks for the confirmation!

I agree that fixing Ruby on Windows to use 64-bit fixnum would be a bigger fix that would involve replacing `long` with `intptr_t` or similar in a lot of places. Changing the constant alone would not be enough.

It would surprise me if it's truly the intent that 64-bit Windows systems behave differently than 64-bit Linux/Mac. But maybe there's some history there that I'm not aware of.

I agree we'll need a workaround for now regardless. It should be a simple matter to change the `#ifdef` so that the secondary map is used unconditionally on Windows. It's a bit of a bummer because it's some complex code and it has a measurable performance impact. But it's our only option at this point I think.

**Comment by dazuma** [comment]
It may have been an oversight originally, but at this point it may very well be a backward compatibility issue, if there are a lot of C extensions that assume fixnums can fit in a long.

In any case, I confirmed that turning on `USE_SECONDARY_MAP` fixes the issue on Ruby 2.7.3 and 3.0.1 on Windows, so I think we can call that a fix for now.

**Comment by haberman** [comment]
Ah yes I could see that.

I found this: https://bugs.ruby-lang.org/issues/14378  The main rationale given there is that it would be a big change to the source code.

Glad that the workaround works. Feel free to send a PR for that!

**Comment by dazuma** [comment]
And BTW, it looks like this is indeed related to the other issue I was seeing. Calling `Message#hash` on Windows results in a C assertion. I suspect the reason is, again, `Message_Hash()` is returning `uint64_t` and then `Message_hash()` is trying to call `INT2FIX` on that.
