### ISSUE TITLE
Protobufs creation is slow when using nested objects compared to using bytes

### ISSUE THREAD

**Issue by tudorcebere** [protocolbuffers/protobuf#8567]
I would like to serialize a small tensor, but I've experienced different performance outcomes. The scenario is: I want to send a tensor over the network, for which I have a protobuf implementation <torch_tensor_proto>.I have multiple proto messages in my use case, the best approach being to use an  `oneof`. The two methods that I have considered are:
* serialize the tensor to bytes and then store the bytes in the oneof protobuf (I considered this slower)
* include the torch tensor message in the oneof message

A minimal snippet of code is here

```
from syft import serialize
from syft.proto.syft_message_pb2 import SyftNative
import boltons.gcutils
import torch

# message Syft Native{
#   oneof {
#       bytes data = 1;
#       <torch_tensor_proto> data_tensorproto_57 = 2;
#   }
# }



def serialize_to_bytes(proto):
    torch_bytes = proto.SerializeToString() # 14
    proto_wrapper_object =  SyftNative(data=torch_bytes) # 15
    wire_bytes = proto_wrapper_object.SerializeToString() # 16
    return wire_bytes

def wrap_in_proto(proto):
    proto_wrapper_object = SyftNative(data_tensorproto_57=proto) # 20
    wire_bytes = proto_wrapper_object.SerializeToString() # 21
    return wire_bytes


#disable GC
with boltons.gcutils.toggle_gc:
    obj = torch.randn((100, 100))
    # <torch_tensor_proto>
    proto = serialize(obj, to_proto=True)

    while True:
        serialize_to_bytes(proto)
        wrap_in_proto(proto)

```

The problem is that the solution where I store directly the bytes is fine in terms of speed, while the other one is really slow. Benchmarks of this using `py-spy` gave me:

```
 89.00%  89.00%   56.55s    56.55s   wrap_in_proto (bench.py:20)
  3.00%   3.00%    2.06s     2.06s   wrap_in_proto (bench.py:21)
  3.00%   3.00%    1.45s     1.45s   serialize_to_bytes (bench.py:14)
  2.00%   2.00%   0.610s    0.610s   serialize_to_bytes (bench.py:15)
  2.00%   2.00%   0.530s    0.530s   serialize_to_bytes (bench.py:16)
```

I've annotated the lines that are present in the benchmark. The constructor of SyftNative with another protobuf object passed in it Python is very slow.

**What version of protobuf and what language are you using?**
libprotoc 3.15.8

**What operating system (Linux, Windows, ...) and version?**
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.7 with a c++  compiled backend for protobuf as described here: https://github.com/protocolbuffers/protobuf/tree/master/python

**What did you expect to see**
Using a protobuf message in the constructor instead of copying bytes to be faster.

**What did you see instead?**
Using bytes is way faster than passing another probuf message in the constructor. You can see that line 21 according to the posted benchmark is eating up most of the cpu time. Why?

**Anything else we should know about your project / environment**
The inner message that I am transforming to bytes/wrapping:
https://github.com/OpenMined/PySyft/blob/dev/proto/lib/torch/tensor.proto

**Comment by tudorcebere** [comment]
Another benchmark to prove the issue (moved in proto creation in each func):


```
Function: serialize_to_bytes at line 7
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     7                                           def serialize_to_bytes(obj):
     8     10001       4223.0      0.4      0.1      for _ in range(10000):
     9     10000    6418457.0    641.8     97.7          proto = serialize(obj, to_proto=True)
    10     10000      85156.0      8.5      1.3          torch_bytes = proto.SerializeToString() # 14
    11     10000      32823.0      3.3      0.5          proto_wrapper_object =  SyftNative(data=torch_bytes) # 15
    12     10000      27083.0      2.7      0.4          wire_bytes = proto_wrapper_object.SerializeToString() # 16
Timer unit: 1e-06 s

Function: wrap_in_proto at line 14
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    14                                           def wrap_in_proto(obj):
    15     10001       5024.0      0.5      0.1      for _ in range(10000):
    16     10000    6413906.0    641.4     80.2          proto = serialize(obj, to_proto=True)
    17     10000    1492723.0    149.3     18.7          proto_wrapper_object = SyftNative(data_tensorproto_57=proto) # 20
    18     10000      83373.0      8.3      1.0          wire_bytes = proto_wrapper_object.SerializeToString() # 21
```

**Comment by haberman** [comment]
Protobuf message objects  in Python do not support reparenting. This means that the line:

```python
proto_wrapper_object = SyftNative(data_tensorproto_57=proto)
```

is actually copying the entire message tree from one message to another.

It so happens that these two protos are wire compatible with each other:

```
message SyftNative1 {
  bytes data = 1;
}

message SyftNative2 {
  <torch_tensor_proto> data_tensorproto_57 = 1;
}
```

So one option would be to serialize as `SyftNative1` when you want to wrap an existing message and then parse as `SyftNative2` on the other side.

This is a little bit tricky, but I think it might be your best option given the current APIs.
