### ISSUE TITLE
[Python] Setting fixed32 field with numpy-array (size=1) behaves differently on Windows/Linux

### ISSUE THREAD

**Issue by sschnug** [protocolbuffers/protobuf#8569]
**What version of protobuf and what language are you using?**
Version: 3.15.8 
Language: Python

**What operating system (Linux, Windows, ...) and version?**
- Linux (Ubuntu 20 LTS)
- Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.5

**What did you do?**
Running this (potentially erroneous program):

    import grpc  # only used to simplify compilation
    import numpy as np

    msg_proto = grpc.protos('test.proto')

    my_msg = msg_proto.Test(
      value = np.array([4], dtype=np.int64)  # also with np.int32
    )

with test.proto:

    syntax = "proto3";

    package testpkg;

    message Test {

      fixed32 value = 1;

    }

**What did you expect to see**
Same behaviour on Windows as well as Linux.

Either throw an error or accept (although the np.int64 cases looks wrong then).

**What did you see instead?**
Different behaviour on Linux and Windows.

Linux: Ok -> Status-code 0 -> No error thrown!

Windows:

    # Traceback (most recent call last):
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 713, in field_setter
    #     new_value = type_checker.CheckValue(new_value)
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\type_checkers.py", line 166, in CheckValue
    #     raise TypeError(message)
    # TypeError: array([4], dtype=int64) has type <class 'numpy.ndarray'>, but expected one of: (<class 'int'>,)  

    # During handling of the above exception, another exception occurred:

    # Traceback (most recent call last):
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 569, in init
    #     setattr(self, field_name, field_value)
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    #     raise TypeError(
    # TypeError: Cannot set testpkg.Test.value to array([4], dtype=int64): array([4], dtype=int64) has type <class 'numpy.ndarray'>, but expected one of: (<class 'int'>,)

    # During handling of the above exception, another exception occurred:

    # Traceback (most recent call last):
    #   File ".\test.py", line 6, in <module>
    #     my_msg = msg_proto.Test(
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 571, in init
    #     _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 488, in _ReraiseTypeErrorWithFieldName
    #     six.reraise(type(exc), exc, sys.exc_info()[2])
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\six.py", line 702, in reraise
    #     raise value.with_traceback(tb)
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 569, in init
    #     setattr(self, field_name, field_value)
    #   File "C:\Users\sascha\AppData\Local\Programs\Python\Python385\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    #     raise TypeError(
    # TypeError: Cannot set testpkg.Test.value to array([4], dtype=int64): array([4], dtype=int64) has type <class 'numpy.ndarray'>, but expected one of: (<class 'int'>,) for field Test.value

**Anything else we should know about your project / environment**
    
    # protobuf                      3.15.8 
    # grpcio                        1.37.1              
    # grpcio-tools                  1.37.1   
    # numpy                         1.17.4
    # six                           1.15.0              

The example uses grpc to *easily use protoc* in this minimal example. My original used AOT protoc-usage!

Without knowing protobufs internals, i cannot predict if this is a protobuf- or a numpy-induced thing.

**Comment by deannagarcia** [comment]
Sorry for the long delay. 

I'm pretty sure this isn't a proto problem and the error is from another package. If you can provide us an isolated reproduction test without the other packages, feel free to reopen and we will look into it!
