### ISSUE TITLE
Make check fail on alpine linux 

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [protocolbuffers/protobuf#8572]
trying to build from source the protobuf compiler 3.16
following dockerfile should reproduce the issue 

```Dockerfile
FROM alpine:3.12


WORKDIR /src
COPY . .

RUN apk add autoconf automake libtool curl make g++ unzip bash
RUN ./autogen.sh
RUN ./configure
RUN make
RUN make check
```

the dockerfile expects to copy the entire git repo root into the image and build.
the `make check` produce the following error

```
make[2]: Leaving directory '/src/src'
make  check-TESTS
make[2]: Entering directory '/src/src'
make[3]: Entering directory '/src/src'
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.16.0-rc-1
============================================================================
# TOTAL: 6
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
make[3]: *** [Makefile:7980: test-suite.log] Error 1
make[3]: Leaving directory '/src/src'
make[2]: *** [Makefile:8088: check-TESTS] Error 2
make[2]: Leaving directory '/src/src'
make[1]: *** [Makefile:8204: check-am] Error 2
make[1]: Leaving directory '/src/src'
make: *** [Makefile:1879: check-recursive] Error 1
```

**Comment by cihancalli** [comment]
make  check-TESTS
make[2]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
make[3]: Entering directory '/home/pi/tf/protobuf-3.17.2/src'
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.17.2
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
make[3]: *** [Makefile:7997: test-suite.log] Error 1
make[3]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make[2]: *** [Makefile:8105: check-TESTS] Error 2
make[2]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make[1]: *** [Makefile:8221: check-am] Error 2
make[1]: Leaving directory '/home/pi/tf/protobuf-3.17.2/src'
make: *** [Makefile:1906: check-recursive] Error 1

**Comment by deannagarcia** [comment]
Sorry for the long delay. Is this issue still present in newer versions of protobuf?

**Comment by deannagarcia** [comment]
Closing due to no response, pleas reopen if you are still running into this problem.
