### ISSUE TITLE
[Ruby] warning: delegator does not forward private method #to_ary

### ISSUE THREAD

**Issue by papa-cool** [protocolbuffers/protobuf#8577]
**What version of protobuf and what language are you using?**
Version: 3.15.8
Language: Ruby 2.6.6

**What operating system (Linux, Windows, ...) and version?**
ubuntu:20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
irb

**What did you do?**
Call delegated methods defined in `Google::Protobug::RepeatedField` class at https://github.com/protocolbuffers/protobuf/blob/master/ruby/lib/google/protobuf/repeated_field.rb#L70.

`warning: delegator does not forward private method #to_ary`

**What did you expect to see**
No warning

**What did you see instead?**
A warning

Ruby 2.4 changes the behavior of Forwardable to issue a warning whenever a protected or private method is called via delegation. See https://bugs.ruby-lang.org/issues/12782
That's why we get this warning.

**Anything else we should know about your project / environment**

**Comment by JasonLunn** [comment]
Tested this on Ruby 2.6.0 today via `irb`, but I'm unable to reproduce:

```
require 'google/protobuf'
r = Google::Protobuf::RepeatedField.new :int32, [1,2,3]
 => [1, 2, 3] 
r.to_ary
 => [1, 2, 3] 
r.count
 => 3 
```

If this issue is still reproducible for you, please reopen with detailed steps.
