### ISSUE TITLE
error: PythonPipBuilder:ResolveDependencies - {protobuf==3.16.0(wheel)}

### ISSUE THREAD

**Issue by amersaw** [protocolbuffers/protobuf#8590]
**What version of protobuf and what language are you using?**
Version: v3.16.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Version 2004 OS Build 19041.928

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python : 3.7.10
pip: 21.0.1 

**What did you do?**
1. Create a new aws sam python app using `sam init`
2. Add the requirement `protobuf` to `requirements.txt`
3. run `sam build`

**What did you expect to see**
I'm expecting the `sam build` to complete successfully

**What did you see instead?**
I get the following error 

```
error: PythonPipBuilder:ResolveDependencies - {protobuf==3.16.0(wheel)} 
```
Check the following [issue on `aws-sam-cli` repo](https://github.com/aws/aws-sam-cli/issues/2861) for more logs

**Anything else we should know about your project / environment**
Specifying the previous version of protobuf package `3.15.8` in the requirements.txt file is fixing the issue

**Comment by michaelbrewer** [comment]
Same issue using SAM CLI, version 1.23.0 and Python 3.9.5

requirements.txt:
protobuf==3.15.8

**Comment by dlj-NaN** [comment]
Just to verify: based on the logs in aws/aws-sam-cli#2861, it looks like the error is occurring on the remote AWS host, not on your local machine(s). Is that correct?

**Comment by amersaw** [comment]
@dlj-NaN 

No on my local machine, while packaging (building) the AWS app before deploying it to the AWS host

The `sam build` process is checking and getting all the requirements before building the sam app, where this problem happens

**Comment by TARehman** [comment]
@dlj-NaN Just wanted to chime in that I am getting a similar issue with my AWS build as well.

`Error: PythonPipBuilder:ResolveDependencies - {protobuf==3.17.3(wheel)}`

I plan to roll back to 3.15.8 as others seem to have had success with that for now.
