### ISSUE TITLE
Use of alignas(64) on struct ThreadCache (arena_impl.h) causes link problems on 32 bit platform esp32

### ISSUE THREAD

**Issue by bpietsch** [protocolbuffers/protobuf#8591]
Version: 3.15.8
Language: C++

**What operating system (Linux, Windows, ...) and version?**
esp-idf v4.2 

**What runtime / compiler are you using (e.g., python version or gcc version)**
xtensa gcc 8.4.0

**What did you do?**
created a custom cmake file to compile protobuf lite for this architecture

**What did you expect to see**
**What did you see instead?**
The binary image for this chip / architecture has a specific address requirement for certain headers. The use of alignas(64) on struct ThreadCache causes some sort of alignment offset to be introduced that shifts these headers by 32 bytes, resulting in an invalid binary. Changing to alignas(32) addresses the issue. Recommend the following change to address this:

#if GOOGLE_PROTOBUF_ARCH_64_BIT
  struct alignas(64) ThreadCache {
#else
  struct alignas(32) ThreadCache {
#endif

**Anything else we should know about your project / environment**
https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32/index.html

**Comment by hillcrest-reedley** [comment]
Not sure if this issue is still present.
