### ISSUE TITLE
MessageToJsonString prints wrong formatting when a message is stored into an Any type

### ISSUE THREAD

**Issue by bcrobo** [protocolbuffers/protobuf#8607]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Fedora 31
```
$ uname -a
Linux localhost.localdomain 5.8.18-100.fc31.x86_64 #1 SMP Mon Nov 2 20:32:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
**What runtime / compiler are you using (e.g., python version or gcc version)**

`gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)` 

**What did you do?**
1. I defined a `message.proto` file with two messages. One made of regular fields, and the other one holding a unique `google.protobuf.Any` field. Here is the message declaration:
```
syntax = "proto3";

import "google/protobuf/any.proto";

message Message {
  uint32 this_is_a_magic_number = 1;
  uint32 iam_a_version = 2;
  uint32 another_field = 3;
}

message OtherMessage {
  google.protobuf.Any msg = 1;
}
```
2. I declared one `Message` that I filled and then pack into another `OtherMessage` using `PackFrom` method of the `google.protobuf.Any` type. I turned `add_whitespace`, `always_print_primitive_fields` and `preserve_proto_field_names` flags to true for:
* Add whitespaces formatting into my output.
* Print all primitive fields (even the unset ones).
* Print proto fields as they are defined in my  `.proto` file.

Here is the code: 
```
#include <iostream>
#include "message.pb.h"

#include <google/protobuf/util/json_util.h>

int main()
{
  auto msg = Message{};
  msg.set_this_is_a_magic_number(3);
  msg.set_iam_a_version(4);
  msg.set_another_field(5);

  auto other_msg = OtherMessage{};
  other_msg.mutable_msg()->PackFrom(msg);

  std::string json;
  google::protobuf::util::JsonPrintOptions options;
  options.add_whitespace = true;
  options.always_print_primitive_fields = true;
  options.preserve_proto_field_names = true;

  if(google::protobuf::util::MessageToJsonString(other_msg, &json, options).ok()) {
    std::cout << json << std::endl;
  } else {
    std::cerr << "JSON serializaton failed" << std::endl;
  }
  
  return 0;
}
```

3. The output I got is

```
{
 "msg": {
  "@type": "type.googleapis.com/Message",
  "this_is_a_magic_number": 0,
  "iam_a_version": 0,
  "another_field": 0,
  "thisIsAMagicNumber": 3,
  "iamAVersion": 4,
  "anotherField": 5
 }
}

```

**What did you expect to see**

```
{
 "msg": {
  "@type": "type.googleapis.com/Message",
  "this_is_a_magic_number": 3,
  "iam_a_version": 4,
  "another_field": 5
 }
}

```

**What did you see instead?**

See the above output. 

**Anything else we should know about your project / environment**

Setting the `always_print_primitive_fields` flag to `false` ends with the following output:
```

 "msg": {
  "@type": "type.googleapis.com/Message",
  "thisIsAMagicNumber": 3,
  "iamAVersion": 4,
  "anotherField": 5
 }
}
```
It seems `preserve_proto_field_names` flag does not seems to be taken into account in that case (even if I add `[json_name = "ma_variable"];` tag in my proto file).

**Comment by fowles** [comment]
I think I am missing something.  It looks like you set the `options.always_print_primitive_fields = true;` option and are seeing them.
