### ISSUE TITLE
Is it safe to cast different versions of protobuf pointers in C++?

### ISSUE THREAD

**Issue by medivh-x** [protocolbuffers/protobuf#8625]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
I have two different versions of task.proto, say v1 and v2, and I compiled them into two C++ classes, namespace1::V1 and namespace::V2. If I change the pointer of the new type to the old type, like (V1*)(&V2). Is this safe? Is there a difference between with using V1.ParseFromString(V2.SerializeToString())?

**Describe the solution you'd like**
At the moment my program works fine, but I don't know if it's safe. like (V1*)(&V2)

Can you give me some advice?

**Comment by acozzette** [comment]
Casting is not safe since V1 and V2 are different C++ classes, but you can safely convert between them by serializing one and parsing it into the other as you mentioned.
