### ISSUE TITLE
Repeated of message which wraps "oneof" filed is not packed.

### ISSUE THREAD

**Issue by yiakwy-mapping-team** [protocolbuffers/protobuf#8628]
# The message I am implementing 

I am using proto3 syntax and implement exchangeable messages : 

```
// matrix.proto
message Number {
  oneof val_of {
    float val_f = 1;
    int32 val_i32 = 2;
    double val_d = 3;
    int64 val_i64 = 4;
  };
}

message MatrixArray {
  repeated Number val = 1; // repeated keys for none scalar fields
  repeated int32 shape = 2;
}

// plugin.proto
message Param {
  string key = 1;
  oneof val_of {
    math.matrix_array.Number val_number = 2;
    math.matrix_array.MatrixArray val_array = 3;
    string val_str = 4;
    bool  val_boolean = 5;
  }
}

message Plugin {
  string name = 1;
  repeated Param params = 2;
}
```

When it serialize to text format, I got unwanted serialization result.

# Serialization result

```
// x.conf (prototxt)
...
 params {
    key: "norm"
    val_array {
      val {
        val_d: 0
      }
      val {
        val_d: 0
      }
      val {
        val_d: 1
      }
    }
```
# What I expect

```
// x.conf (prototxt)
...
// remove repeated keys and one
 params {
    key: "norm"
    val_array [
      {
        val_d: 0
      }, 
      {
        val_d: 0
      },
      {
        val_d: 1
      }
    ]

```

Moreover, if it is possible (any method, rewrite parser ? I am really confused in the current packet policies ), I also need an option (when remove repeated keys) to remove "val_d" when many fields of the same type is repeated, such that it looks like : 

```
// x.conf (prototxt)
...
// remove repeated keys and one
 params {
    key: "norm"
    val_array { data : [ 0, 0, 1], data_type : int32 } 

```

Could protobuf team make it happen ?

also see #2592

**Comment by fowles** [comment]
The first suggestion (omitting `val`) is not going to work as the parser won't know whether the repeated blocks refer to `val` or `shape`.  The second suggestion (omitting both `val` and `val_d`) suffers from the larger problem of synthesizing the name for `data` and `data_type` that is not ambiguous in a larger context.

**Comment by yiakwy-mapping-team** [comment]
@fowles get it. So, from your perspective, what is better way for me to encode above message. I miss json data type for ascii messages.

**Comment by fowles** [comment]
If you are wed to that format, I would recommend custom parsing and serialization

**Comment by yiakwy-mapping-team** [comment]
It is cool if I can have customized serialization format to achieve that. (hopefully, proto text parser is also able to deserialize to object). How can I start from it ?

**Comment by fowles** [comment]
I suggest you start with one of the many json parsers that are available and then write a wrapper function that takes json and fills in a protobuf that corresponds to what you want.

**Comment by yiakwy-mapping-team** [comment]
ok
