### ISSUE TITLE
Protoc generates empty Kotlin outer class

### ISSUE THREAD

**Issue by meavydev** [protocolbuffers/protobuf#8629]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.17.0 proto3
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina 10.15.7 x64

**What did you do?**
protoc -I=. --kotlin_out=. kinesis_data.proto

**What did you expect to see**
The generated outer class KinesisProtoKt.kt should not be empty.

**What did you see instead?**
 KinesisProtoKt.kt is empty.

The attached .zip contains both the .proto file and the generated output with the empty outer class file.

[ProtocFail.zip](https://github.com/protocolbuffers/protobuf/files/6507703/ProtocFail.zip)

**Comment by deannagarcia** [comment]
The outer class file is sometimes empty, since all of the necessary generated code is created for each of the messages. We are keeping the file just in case we will need to put something in there, but I think this should be working as intended. Are the protos successfully compiling even with the empty file?

**Comment by meavydev** [comment]
Ah OK.
I was used to the Java implementation, so seeing an empty file I thought it was broken.
I think this is the Kotlin implementation that is working (not run yet), so I am closing this as user error ;) 
`        val kinesisBleData = ble {
            deviceAddress = bleData.payload.deviceAddress
            rssi = bleData.payload.rssi
            txPower = bleData.payload.txPower
            timestampMillis = bleData.payload.timestampMillis
            timestampNanos = bleData.payload.timestampNanos
        }

        val kinesisData = kinesisData {
            type = bleData.type.name
            identityId = bleData.identityId
            timestampMs = bleData.timeStamp
            selectedVenue = bleData.selectedVenue
            bleData = kinesisBleData
            sdkSessionId = bleData.sdkSessionId
            sdkSessionUuid = bleData.sdkSessionUuid
        }`

**Comment by meavydev** [comment]
I spoke too soon.
The generated KinesisDataKt.kt seems to be referring to the KinesisOuterDataClass and it won't compile:
`android/sdk/build/tmp/kapt3/stubs/debug/com/navenio/sdk/aws/kinesis/protobuf/EddystoneUrlKt.java:16: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass`

**Comment by deannagarcia** [comment]
Is the Protobuf compiler generating the file EddystoneUrlKt.java? As far as I know, we should not be generating a java file with a Kt suffix, so that would definitely be a bug. Can you send me a new zip file or more of your project files so I can reproduce this?

**Comment by meavydev** [comment]
If you look at the path, it's the Java generated from Kotlin, as that's how Android Studio (AF Beta 1) builds Kotlin files.
build/tmp/kapt3/stubs...

**Comment by deannagarcia** [comment]
Oh okay, well looking in the first zip file you sent, it doesn't appear that KinesisDataKt.kt or EddystoneUrlKt.kt are referring to the outer data class, so I'm not sure if this is because that file is empty.
