### ISSUE TITLE
C++ compile error for GetRepeatedFieldRef

### ISSUE THREAD

**Issue by fy2462** [protocolbuffers/protobuf#8630]
Hi guys:

I have a compile error when using `GetRepeatedFieldRef` to get the repeated message.
the code is following:

```c++
void PrintProto(Message& message) {
  const Descriptor* descriptor = message.GetDescriptor();
  const Reflection* reflection = message.GetReflection();
  int filed_size = descriptor->field_count();
  for (int i = 1; i <= filed_size; ++i) {
    const FieldDescriptor* field = descriptor->FindFieldByNumber(i);
    if (field->is_repeated()) {
      int size = reflection->FieldSize(message, field);
      if (size > 0 && field->cpp_type() == FieldDescriptor::CPPTYPE_MESSAGE) {
          auto repeate_ref = reflection->GetRepeatedFieldRef<Message>(message, field);
      }
    }
  }
}
```
But I got the compile error, How to fix that, any idea? thanks all of you.

> In function 'void PrintProtoTree(const google::protobuf::Message&, google::protobuf::Message&)':
error: invalid use of incomplete type 'class google::protobuf::RepeatedFieldRef<google::protobuf::Message, void>'
  334 |         auto repeate_ref = reflection->GetRepeatedFieldRef<Message>(message, field);
|     ^
external/com_google_protobuf/src/google/protobuf/message.h:385:7: note: declaration of 'class google::protobuf::RepeatedFieldRef<google::protobuf::Message, void>'
  385 | class RepeatedFieldRef;
            |       ^~~~~~~~~~~~~~~~

**Comment by fowles** [comment]
Looks like you are missing an include for "google/protobuf/reflection.h" can you post the full file you are compiling somewhere?

**Comment by fy2462** [comment]
> Looks like you are missing an include for "google/protobuf/reflection.h" can you post the full file you are compiling somewhere?

Yes，I miss the `google/protobuf/reflection.h` header, it is ok now, thanks @fowles very much.
