### ISSUE TITLE
Expose ReadVarint64FromArray from coded_stream.cc

### ISSUE THREAD

**Issue by RyanAfrish7** [protocolbuffers/protobuf#8643]
**What language does this apply to?**
C++

**Describe the problem you are trying to solve.**
ReadVarint64FromArray is not accessible. There are usecases where the message is already in memory and constructing a CodedInputStream to read a varint is not worth it. I see multiple places where a different (or copied) implementation of these functions exist.

**Describe the solution you'd like**
Consider exposing ReadVarint64FromArray and similar functions to allow reading from byte array directly

**Comment by haberman** [comment]
We try to avoid exposing our internal functions too much. If you want to reuse the code you can always copy+paste it into your own project.

If you see duplication within the protobuf repo, you can try submitting a PR to deduplicate, but keep in mind that this is all very performance-sensitive, so it might be important in some cases that separate implementations remain separate.
