### ISSUE TITLE
Is there any way that can speed up the process of seralization and deserialization by some kind of changing the internal encoding and decoding algorithm?? 

### ISSUE THREAD

**Issue by AlanYiNew** [protocolbuffers/protobuf#8644]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fowles** [comment]
We are working on several such optimizations.  If you have specific suggestions we are happy to entertain them.

https://blog.reverberate.org/2021/04/21/musttail-efficient-interpreters.html is one such effort underway.
