### ISSUE TITLE
fatal error: google/protobuf/compiler/parser.h: No such file or directory  #include "google/protobuf/compiler/parser.h"

### ISSUE THREAD

**Issue by jinfagang** [protocolbuffers/protobuf#8646]
```
fatal error: google/protobuf/compiler/parser.h: No such file or directory
 #include "google/protobuf/compiler/parser.h"

```

**Comment by deannagarcia** [comment]
Thanks for this report! Can you provide more information on what caused this error and how we could reproduce it?

**Comment by jinfagang** [comment]
I found ubuntu systems's protobuf doesn't have this file. If I build from source it have. I don't know why though

**Comment by deannagarcia** [comment]
What version of protobuf are you using?

**Comment by jinfagang** [comment]
ubuntu 18.04 default is libprotobuf-10

**Comment by deannagarcia** [comment]
The ubuntu community maintains ubuntu protos, so you should redirect this question to them.

**Comment by felixf4xu** [comment]
> ubuntu 18.04 default is libprotobuf-10

you should install `libprotoc-dev`

**Comment by nathanoy** [comment]
> > ubuntu 18.04 default is libprotobuf-10
> 
> you should install `libprotoc-dev`

thank you very much. This was the perfect fix.
