### ISSUE TITLE
edited

### ISSUE THREAD

**Issue by trevor13mffm** [protocolbuffers/protobuf#8647]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

- **Anything else we should know about your project / environment**

**Comment by fowles** [comment]
I don't think this bug report contains any information.  Feel free to reopen with an actual repro if this was not opened an accidental issue
