### ISSUE TITLE
Kotlin: Missing classes/ weird outer class generation

### ISSUE THREAD

**Issue by amytang0** [protocolbuffers/protobuf#8651]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.17.0
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
Mac OS X 11.3.1

**What did you do?**
1. cd into `analyticsproto/proto` folder
2.  `~/protoc/bin/protoc  `find . -name '*.proto'` --kotlin_out=../output`
3. Check the `output` folder

Files can be found here:
[analyticsproto.zip](https://github.com/protocolbuffers/protobuf/files/6535110/analyticsproto.zip)

**What did you expect to see**
No outer classes generated

**What did you see instead?**
Empty outer classes generated, that also don't compile

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Potentially related to https://github.com/protocolbuffers/protobuf/issues/8629

**Comment by deannagarcia** [comment]
Hi! The reason there isn't an outer class is because we have set Kotlin to automatically use the `java_multiple_files = true` option and we don't need any outer class methods yet for Kotlin. When you run protoc to compile kotlin protos you also need to use `--java_out` as well as `--kotlin_out` because the generated Kotlin files rely on the generated Java files. If you change that, will the code compile?

**Comment by amytang0** [comment]
Oh I see, the [docs](https://developers.google.com/protocol-buffers/docs/kotlintutorial) make it seem like `--kotlin_out` is the only parameter needed.
![Screen Shot 2021-05-26 at 11 37 51 AM](https://user-images.githubusercontent.com/863461/119713698-d6f6f980-be16-11eb-92c1-a446d9c7f128.png)

 I ran `--java-out` with the same output folder and it builds now!

In a related vein, does the team plan to move to a purely Kotlin-based implementation eventually? If yes, will the Kotlin models generated now be roughly the same syntactically?

**Comment by lowasser** [comment]
Moving to Kotlin-only is a long-term goal, but we are not willing to break source compatibility.  Any future changes will remain fully compatible, not just "roughly the same syntactically."

**Comment by deannagarcia** [comment]
And I will update the docs, thanks for pointing out the documentation problem!
