### ISSUE TITLE
Kotlin: Why not use kotlinx serialization?

### ISSUE THREAD

**Issue by lz1998** [protocolbuffers/protobuf#8656]
The code will looks more clean and simple.

**Comment by lz1998** [comment]
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#protobuf-experimental

**Comment by lowasser** [comment]
It's not an unreasonable choice to use kotlinx.serialization, but we believe continuing to use .proto files to generate message types adds significant value.

- Cross-language support, especially with Java interop.
- proto3 support
- A variety of issues associated with message evolution, including:
  - Adding a field to Kotlin protos can never break code.
  - Field numbers can be marked reserved after deletion.
  - Message extensions are supported.
- Existing proto infrastructure is heavily optimized.
