### ISSUE TITLE
Provide an object reserve method for RepeatedPtrField

### ISSUE THREAD

**Issue by BoshenGuan** [protocolbuffers/protobuf#8674]
The `Reserve` method for `RepeatedPtrField` only reserves for pointer itself. If it is possible to provide a method for reserve the objects in bulk? It would be great to do that for efficiency reason.

Language: C++
gRPC version: 1.37.0
OS: Windows 10

**Comment by deannagarcia** [comment]
Sorry for the long delay.

I'm not sure I understand your question. The `Reserve` method accepts a variable size, which would allow you to increase the size by more than a single pointer.

Can you give an example of what you currently have to do to get around this and what you would like it to look like?

**Comment by deannagarcia** [comment]
Closing this due to no response, feel free to reopen if you are still seeing this issue.
