### ISSUE TITLE
warning about missing pragma warning push

### ISSUE THREAD

**Issue by yoavmil** [protocolbuffers/protobuf#8679]
when compiling some specific file I get a warning about missing pragma warning push.

I've made a [pull request](https://github.com/protocolbuffers/protobuf/pull/8678) that fixes it without risk, but I'm not sure it passes. too complicated.

Version: 3.15.8.
Language: C++
Windows X64

**Comment by acozzette** [comment]
Let me mark this closed since it should be fixed by the pull request.
