### ISSUE TITLE
Python benchmarks only use python2.7 (which is after EOL)

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#8681]
Based on my experiments (https://github.com/protocolbuffers/protobuf/pull/8665), the python benchmark from https://github.com/protocolbuffers/protobuf/blob/0b8d13a1d4cd9be16ed8a2230577aa9c296aa1ca/kokoro/linux/benchmark/run.sh#L39 only runs python2.7 benchmarks - but python2.7 has been deprecated for long time.
The benchmark python benchmark should be updated to run python 3.x.

**Comment by corydolphin** [comment]
Are there any details or example of using the C++ generated Protobuf implementation for Python 3+? 

Beyond the benchmarks (which are Python 2.7 only), the only references I can find are a [few lines in the docs](https://developers.google.com/protocol-buffers/docs/reference/python-generated#cpp_impl) and a dated blog post. http://yz.mit.edu/wp/fast-native-c-protocol-buffers-from-python/

**Comment by corydolphin** [comment]
Additionally, while trying to reproduce them with Python 2.7, the `download_data.sh` script is missing, and the data in google cloud also appears to be missing 
https://chromium.googlesource.com/external/github.com/google/protobuf/+/v3.6.0/benchmarks/download_data.sh

**Comment by fowles** [comment]
Did this get fixed as part of the 4.21 effort?

**Comment by haberman** [comment]
The benchmarks were deleted in https://github.com/protocolbuffers/protobuf/pull/10479.
