### ISSUE TITLE
Backward incompatible change in 3.8.0: 

### ISSUE THREAD

**Issue by georgthegreat** [protocolbuffers/protobuf#8692]
protobuf 3.8.0 introduced the following changelog entry:

```
* Always declare enums to be int-sized
```

In practice, this results in a generated code change for 
```
enum Foo { 
    ONE = 1,
    TWO = 2
}
```

Due to this change the generated C++ code was changed from
```
enum Foo {
    ONE = 1,
    TWO = 2
}
```
to 
```
enum Foo : int{
    ONE = 1,
    TWO = 2
}
```

This resulted in a migration problem for the following case:
```
enum Foo { ... };
message Bar {
    optional uint32 foobar = 1; // for possible values @see Foo
}
```

This technique was used to workaround enum expansion problem: foobar field was always valid and it was comparable with any enum values. As all enums are inherited from int, an attempt to compare signed and unsigned integers will trigger `-Wsign-compare` warning.

Could you, please, elaborate a bit? Why int was chosen? Have you considered an option to allow alternative basic types?

**Comment by acozzette** [comment]
The original motivation for the enum base was to make it possible to forward-declare enums, which we rely on in an internal-only feature. I'm not sure how much thought went into the signedness of the type; I think we were probably more concerned with just making sure it was large enough to store any enum value. Proto3 allows unknown enum values to be set directly via the getters and setters, so in principle they need to be able to handle values that are larger than any of the values explicitly defined in the .proto file.

We generally try hard to avoid adding any new options if we can avoid it, so I don't think we would want to add one in this case unfortunately. One thing you could try would be to just change your `foobar` field to be of type `int32`, which would be a compatible change.

**Comment by georgthegreat** [comment]
Thanks for the clarification.

I will consider both options (that is, changing enum to proto3 and convering field types into signed ints) and will try to work something out.

**Comment by acozzette** [comment]
Just to clarify one thing, I didn't mean to suggest changing the enum to proto3 and I don't think that would make a difference. I just meant to say that proto3's handling of unknown enums is another motivation for explicitly specifying the enum base, since the type has to be large enough to be able to handle any possible value, even if the value is larger than any enum values defined in the proto file.
