### ISSUE TITLE
`include` directory in Linux x86_64 download has restrictive permissions (710)

### ISSUE THREAD

**Issue by jmelion** [protocolbuffers/protobuf#8693]
**What version of protobuf and what language are you using?**
Version: v3.11.1
Language: all
**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux 20.04

This was experienced specifically with the download `protoc-3.11.1-linux-x86_64.zip` on the page https://github.com/protocolbuffers/protobuf/releases/tag/v3.11.1 . 
I haven't tested other versions.

After extracting from the ZIP, the `include` directory has the permissions 710, which means there is no user read access to the files.
This results in the following kind of errors when running protoc:
```
google/protobuf/any.proto: File not found.
Import "google/protobuf/any.proto" was not found or had errors.
"google.protobuf.Any" is not defined.
```

I imagine this is not intentional, which is why I am reporting this. 
Doing `chmod -R 755 ./include` fixes the issue but I think the permissions should be 755 by default.

**Comment by fowles** [comment]
Closing out old issues. Please reopen if this still occurs on recent releases.
