### ISSUE TITLE
Kotlin library cause duplicate file error

### ISSUE THREAD

**Issue by JeroenMols** [protocolbuffers/protobuf#8694]
**What version of protobuf and what language are you using?**
Version: v3.17.2
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
OSX 11.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Protoc version 3.17.2
Gradle version 7.0.2
Android Studio 4.2.1

**What did you do?**
1. Create a new Android studio project
2. Add dependency on `com.google.protobuf:protobuf-kotlin:3.17.2`
3. Build project

**What did you expect to see**
Project builds successfully

**What did you see instead?**
Gradle outputs the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'google/protobuf/field_mask.proto' from inputs:
      - /Users/jmols/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-kotlin/3.17.2/3edd99a5479d55c364eb75027d925ece524e77d5/protobuf-kotlin-3.17.2.jar
      - /Users/jmols/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.17.2/d7eec2ad499b605f24d07f49bdcb41c801aafbfc/protobuf-java-3.17.2.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

As the error suggests, this is caused because both `protobuf-kotlin` and `protobuf-java` include the same `*.proto` files.

<img width="478" alt="Screen Shot 2021-06-04 at 10 12 24 AM" src="https://user-images.githubusercontent.com/6319637/120770264-3f805d80-c51e-11eb-927c-a34595b0d02c.png">

This can be worked around by adding the following to your `build.gradle` file:

```groovy
android {
    packagingOptions {
        pickFirst 'google/protobuf/*.proto'
        pickFirst 'google/protobuf/compiler/*.proto'
    }
}
```

This however is not an option for us as we ship `protobuf-kotlin` as a transitive dependency in our SDK. Hence this would require all our customers to add this to their `build.gradle` file, which increases the integration effort or our SDK.

> Note: this issue is very similar to https://github.com/protocolbuffers/protobuf/issues/8631, though now the conflict arrises from duplicate `.proto` files instead of source files.

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
Thanks for reporting this! I am working on a fix and an associated point release.

**Comment by JeroenMols** [comment]
Verified this on 3.17.3

**Comment by JStr84galaxy** [comment]
deannagarcia:morePomFixes
