### ISSUE TITLE
Protoc generates lite Kotlin/Java that doesn't compile

### ISSUE THREAD

**Issue by JeroenMols** [protocolbuffers/protobuf#8697]
**What version of protobuf and what language are you using?**
Version: 3.17.2
Language: Java/Kotlin

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Protoc v 3.17.2
`protobuf-kotlin-lite` or `protobuf-javalite` v 3.17.2
Gradle version 7.0.2
Android Studio 4.2.1

**What did you do?**
1. Use the following proto file:

```
syntax = "proto3";

package analyticalcore;

import "google/protobuf/descriptor.proto";

message Meta {
  string id = 1;
}

// see
// https://developers.google.com/protocol-buffers/docs/proto#customoptions
// https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto
//
// custom options can be defined after 50000.
extend google.protobuf.MessageOptions {
  string stream_name = 50001;
}
```

2. Convert this to the lite variant of Java (or Kotlin) models using protoc:

```
protoc --java_out=lite:code --kotlin_out=lite:code analytical.proto 
protoc --java_out=lite:code analytical.proto 
```

3. Try to compile the code with `protobuf-javalite` as a dependency

**What did you expect to see**
I would either expect:
- `protoc` to return an error that this syntax isn't supported for lite code generation
- add `DescriptorProtos` class as part of the `protobuf-<language>lite` binaries

**What did you see instead?**
```
> Task :core:workflow-protos:compileReleaseJavaWithJavac
/Users/jmols/development/test/protos/src/main/java/analyticalcore/Analytical.java:1344: error: package com.google.protobuf.DescriptorProtos does not exist
      com.google.protobuf.DescriptorProtos.MessageOptions,
                                          ^
/Users/jmols/development/test/protos/src/main/java/analyticalcore/Analytical.java:1347: error: package com.google.protobuf.DescriptorProtos does not exist
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
                                            ^
2 errors

> Task :core:workflow-protos:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```
Note that this compilation error makes sense, as neither `protobuf-javalite`, nor `protobuf-kotlin-lite` contain the `DescriptorProtos` class. Whereas `protobuf-java` does contain this.

Fully generated class here: [Analytical.java](https://github.com/protocolbuffers/protobuf/files/6599975/Analytical.md)

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
This is currently working as intended, the lite versions are not meant to contain the DescriptorProtos class. See https://github.com/protocolbuffers/protobuf/issues/7331
