### ISSUE TITLE
older version 2.5.0 make err in os 11.2.3

### ISSUE THREAD

**Issue by kdYY** [protocolbuffers/protobuf#8705]
1 download from https://github.com/protocolbuffers/protobuf/releases/tag/v2.5.0
2 ./configure
3 make
when make command be called, it errors:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT atomicops_internals_x86_gcc.lo -MD -MP -MF .deps/atomicops_internals_x86_gcc.Tpo -c google/protobuf/stubs/atomicops_internals_x86_gcc.cc  -fno-common -DPIC -o .libs/atomicops_internals_x86_gcc.o
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:59:
./google/protobuf/stubs/platform_macros.h:61:2: error: Host architecture was not detected as supported by protobuf
#error Host architecture was not detected as supported by protobuf
 ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:47:9: warning: 'OSAtomicCompareAndSwap32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32(old_value, new_value,
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:503:9: note: 'OSAtomicCompareAndSwap32' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:61:13: warning: 'OSAtomicCompareAndSwap32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
  } while (!OSAtomicCompareAndSwap32(old_value, new_value,
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:503:9: note: 'OSAtomicCompareAndSwap32' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:68:10: warning: 'OSAtomicAdd32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
  return OSAtomicAdd32(increment, const_cast<Atomic32*>(ptr));
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:147:9: note: 'OSAtomicAdd32' has been explicitly marked deprecated here
int32_t OSAtomicAdd32( int32_t __theAmount, volatile int32_t *__theValue );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:73:10: warning: 'OSAtomicAdd32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
  return OSAtomicAdd32Barrier(increment, const_cast<Atomic32*>(ptr));
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:162:9: note: 'OSAtomicAdd32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicAdd32Barrier( int32_t __theAmount, volatile int32_t *__theValue );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:77:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:750:9: note: 'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:85:9: warning: 'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32Barrier(old_value, new_value,
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:519:9: note: 'OSAtomicCompareAndSwap32Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:133:8: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
inline Atomic64 NoBarrier_CompareAndSwap(volatile Atomic64* ptr,
       ^~~~~~~~
       Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:133:51: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
inline Atomic64 NoBarrier_CompareAndSwap(volatile Atomic64* ptr,
                                                  ^~~~~~~~
                                                  Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:134:42: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
                                         Atomic64 old_value,
                                         ^~~~~~~~
                                         Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:135:42: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
                                         Atomic64 new_value) {
                                         ^~~~~~~~
                                         Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:133:17: error: redefinition of 'NoBarrier_CompareAndSwap'
inline Atomic64 NoBarrier_CompareAndSwap(volatile Atomic64* ptr,
                ^
./google/protobuf/stubs/atomicops_internals_macosx.h:42:17: note: previous definition is here
inline Atomic32 NoBarrier_CompareAndSwap(volatile Atomic32* ptr,
                ^
./google/protobuf/stubs/atomicops_internals_macosx.h:136:3: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
  Atomic64 prev_value;
  ^~~~~~~~
  Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^

**Comment by acozzette** [comment]
Sorry but since that is a very old version we are not going to work on fixing the error. I would recommend trying a recent version and I would expect that to likely fix the problem.
