### ISSUE TITLE
Please publish sha256sum for easier verification

### ISSUE THREAD

**Issue by Cryptophobia** [protocolbuffers/protobuf#8712]
**What version of protobuf and what language are you using?**
Multiple versions

**What operating system (Linux, Windows, ...) and version?**
Any OS

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
```bash
curl -sSL -o protoc.zip https://github.com/google/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip

sha256sum protoc-3.17.3-linux-x86_64.zip
d669987da1c7daa6e08fc48de29c795ebfa184fb4d1cd64b9498de683c410820  protoc.zip

curl -sSL -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip

sha256sum protoc-3.17.3-linux-x86_64.zip
d4246a5136cf9cd1abc851c521a1ad6b8884df4feded8b9cbd5e2a2226d4b357  protoc.zip
```

**What did you expect to see**
Same sha256sums

**What did you see instead?**
Different sha256sums

What's going on? Can the sha256sums of the protoc.zip files be uploaded for verification somewhere? I am not sure what is going on. First link is from google protocolbuffers website and second link is from github.com .

**Comment by fowles** [comment]
@deannagarcia can you cover this with your BTR work?
