### ISSUE TITLE
generated_message_table_driven.h uses C++20-deprecated enum arithmetic

### ISSUE THREAD

**Issue by danieljennings** [protocolbuffers/protobuf#8713]
**What version of protobuf and what language are you using?**
Version: `3.15.3` (though code looks same in `master` tree)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC 16.10 (VS2019)

**What did you do?**
1. Compiler set to `C++20` standard (currently `-std:c++latest` but will be `-std:c++20` soon)
2. Include a `generated_message_table_driven.h` via a generated `pb.h`

**What did you see?**

```
src\google\protobuf\generated_message_table_driven.h(108,26): warning C5054: operator '*': deprecated between enumerations of different types
```

See `depr.arith.conv.enum` in C++20 standard for deprecation. Presumably other compilers warn about the deprecation, but I've only tested MSVC thusfar.

Workaround available by adding 5054 to MSVC warnings list in `port_def.inc`.

Edit, meant to link to the lines in question:

https://github.com/protocolbuffers/protobuf/blob/37b18c5f1205038c848a199060d84989ca5e51a0/src/google/protobuf/generated_message_table_driven.h#L100-L108

**Comment by Amanjain98** [comment]
Hello There, 

Here is suggestion to fix this warning. Is to use `kSpecial = static_cast<datatype> kNumTypes * static_cast<datatype> kNumTypeClasses`

Thanks

**Comment by davidhunter22** [comment]
Maybe better to use the newer stuff

#if defined(__cpp_lib_to_underlying)
kSpecial = std::to_underlying(kNumTypes ) * std::to_underlying( kNumTypeClasses)  
#else
kSpecial = kNumTypes * kNumTypeClasses  
#endif  

std::to_underlying is already avaialble in at least VS 17.1

**Comment by deannagarcia** [comment]
Unfortunately protobuf does not support C++ 20 at this time. Since this is only a warning, the fix will need to wait until protobuf officially decides to support C++ 20.
