### ISSUE TITLE
Benchmarks are using an old version of tcmalloc

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#8725]
The benchmarks are using tcmalloc from gperftools, which is old.
The benchmarks should be using this version of tcmalloc: https://github.com/google/tcmalloc (which is much newer).

https://github.com/protocolbuffers/protobuf/blob/d1ef6d98261f874714bac0b3ef50f10227c5fe34/kokoro/linux/benchmark/run.sh#L13

The challenge is that google/tcmalloc has a different build system and currently only supports bazel (which might make it tricky to integrate it with benchmarks since the current approach of enabling tcmalloc uses make and libtcmalloc.so pre-loading).

**Comment by jtattermusch** [comment]
CC @fowles @amidlash

**Comment by deannagarcia** [comment]
@mkruskal-google Do you think we would be able to transition here after we bazelfy our tests more?
