### ISSUE TITLE
Optimize varint deserialization

### ISSUE THREAD

**Issue by zhaozheng09** [protocolbuffers/protobuf#8731]
We find a hot spot that deserialize varint64 when we deserialize PB disk files to memory data.
Current deserialization logic：
1. Find out the length of the data by judging highest bit of every 8 bits.
2. Splice the lower 7bit of each 8bit.

We can optimize deserialization by SIMD/AVX
for 1: we can find highest 1 bit by batch compare 0x80.
for 2: we can batch right shift data.

my optimize use 64bit in SIMD/AVX, I think we can merge 1,2 to to improve the performance of SIMD/AVX processing data.

My test:18% increase in deserialization process. 
Ps:my data is **hash64**, and I think SIMD/AVX does not significantly improve short data, but improves long data.

I am happy to contribute my code

**Comment by fowles** [comment]
We have looked at this a bit in the past.  We explicitly do not wish to use AVX instructions as those can cause the processor to down clock and have antagonistic behavior for other programs sharing that core.  Early instructions like SSE are potential options.  That said, the vast vast majority of these are actually 1 byte versions in a real world setting.

**Comment by acozzette** [comment]
One thing to consider is that if you're storing a hash then it's probably best to use a `fixed64` instead of `int64`. Hash values will almost always be large enough to require the maximum number of bytes, so the variable-length format of varints won't help there. This would not be a wire-compatible change, though, so you would need to migrate carefully (e.g. create a new `fixed64` field with a fresh field number, migrate to that field, and then delete the old field).

**Comment by zhaozheng09** [comment]
> One thing to consider is that if you're storing a hash then it's probably best to use a `fixed64` instead of `int64`. Hash values will almost always be large enough to require the maximum number of bytes, so the variable-length format of varints won't help there. This would not be a wire-compatible change, though, so you would need to migrate carefully (e.g. create a new `fixed64` field with a fresh field number, migrate to that field, and then delete the old field).

You are right, but changing the pb format is very difficult.

**Comment by zhaozheng09** [comment]
> We have looked at this a bit in the past. We explicitly do not wish to use AVX instructions as those can cause the processor to down clock and have antagonistic behavior for other programs sharing that core. Early instructions like SSE are potential options. That said, the vast vast majority of these are actually 1 byte versions in a real world setting.

SIMD degraded to 1bit version performance will only be the same as it is now.
<those can cause the processor to down clock and have antagonistic behavior for other programs sharing that core.> Is there a document for me to learn？

**Comment by zhaozheng09** [comment]
> > We have looked at this a bit in the past. We explicitly do not wish to use AVX instructions as those can cause the processor to down clock and have antagonistic behavior for other programs sharing that core. Early instructions like SSE are potential options. That said, the vast vast majority of these are actually 1 byte versions in a real world setting.
> 
> SIMD degraded to 1bit version performance will only be the same as it is now.
> "down clock and have antagonistic behavior" Is there a document for me to learn？

**Comment by fowles** [comment]
https://www.mjr19.org.uk/IT/clocks.html#:~:text=When%20executing%20AVX2%20instructions%20its,turbo%20frequency%20of%203.6GHz.

**Comment by deannagarcia** [comment]
Closing because it appears this has been resolved, feel free to reopen if I was incorrect in that assumption.
