### ISSUE TITLE
undefined reference to GetMessageA when using mingw64 and cmake

### ISSUE THREAD

**Issue by xidang** [protocolbuffers/protobuf#8748]
**What version of protobuf and what language are you using?**
Version: master/v3.17.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Window 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc.exe (GCC with MCF thread model, built by LH_Mouse.) 11.1.1 20210604

**What did you do?**
1. open protobuf/cmake using vscode
2. build with vscode cmake tools

we got the following errors while linking tests.ext

`[build] [ 99%] Linking CXX executable tests.exe
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\tests.dir/objects.a(map_test.cc.obj):D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1315: undefined reference to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const'
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\tests.dir/objects.a(map_test.cc.obj): in function `TestBody':
[build] D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1351: undefined reference to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const'
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\tests.dir/objects.a(map_test.cc.obj):D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1542: undefined reference to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const'
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\tests.dir/objects.a(map_test.cc.obj): in function `TestBody':
[build] D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1582: undefined reference to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const'
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1710: undefined reference to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const'
[build] C:/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\tests.dir/objects.a(map_test.cc.obj):D:/Workspace/C_CPP/protobuf-3.17.3/src/google/protobuf/map_test.cc:1865: more undefined references to `google::protobuf::Reflection::GetMessageA(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::MessageFactory*) const' follow
[build] collect2.exe: error: ld returned 1 exit status
[build] mingw32-make[2]: *** [CMakeFiles\tests.dir\build.make:2401: tests.exe] Error 1
[build] mingw32-make[1]: *** [CMakeFiles\Makefile2:262: CMakeFiles/tests.dir/all] Error 2
[build] mingw32-make: *** [Makefile:135: all] Error 2
[build] Build finished with exit code 2
`

**Comment by acozzette** [comment]
I think this is because Windows defines a macro called `GetMessage` which conflicts with the `Reflection::GetMessage()` member function. We try to work around it here by temporarily undefining that macro: https://github.com/protocolbuffers/protobuf/blob/9b3aaf4bc576ddda62da6d2deed6ad59a8a5f892/src/google/protobuf/port_def.inc#L621 Maybe that workaround is not working in this case because perhaps `_MSC_VER` is not defined for mingw builds? If you could figure out a fix and send a pull request then I would be happy to merge it.

**Comment by xidang** [comment]
> I think this is because Windows defines a macro called `GetMessage` which conflicts with the `Reflection::GetMessage()` member function. We try to work around it here by temporarily undefining that macro:
> 
> https://github.com/protocolbuffers/protobuf/blob/9b3aaf4bc576ddda62da6d2deed6ad59a8a5f892/src/google/protobuf/port_def.inc#L621
> 
> Maybe that workaround is not working in this case because perhaps `_MSC_VER` is not defined for mingw builds? If you could figure out a fix and send a pull request then I would be happy to merge it.

I've changed the _WIN32 macro to _MSC_VER in map_test.cc and  send a pull request.

**Comment by khomin** [comment]
I have same error both windows and similar error on linux
Have to look for an alternative protobuf
