### ISSUE TITLE
Protobuf failing on Bazel CI (Windows)

### ISSUE THREAD

**Issue by comius** [protocolbuffers/protobuf#8754]
Build @head is failing on Windows.

https://buildkite.com/bazel/protobuf/builds/3732#5e9ea0bb-db47-4277-91bb-6aa9de40e48d

```
Executing tests from //java/core:TextFormatTest
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.016
There was 1 failure:
1) initializationError(com.google.protobuf.TextFormatTest)
...
Caused by: java.lang.IllegalArgumentException: Couldn't read file: C:\b\vxgrmk6i\execroot\com_google_protobuf\bazel-out\x64_windows-fastbuild\bin\src\google\protobuf\testdata\text_format_unittest_data_oneof_implemented.txt
	at com.google.protobuf.TestUtil.readBytesFromFile(TestUtil.java:3798)
	at com.google.protobuf.TestUtil.readTextFromFile(TestUtil.java:3761)
	at com.google.protobuf.TextFormatTest.<clinit>(TextFormatTest.java:83)
	... 36 more
Caused by: java.io.FileNotFoundException: C:\b\vxgrmk6i\execroot\com_google_protobuf\bazel-out\x64_windows-fastbuild\bin\src\google\protobuf\testdata\text_format_unittest_data_oneof_implemented.txt (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.google.protobuf.TestUtil.readBytesFromFile(TestUtil.java:3791)
	... 38 more

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by comius** [comment]
Thanks for the quick fix. Unfortunately it doesn't seem it worked:
https://buildkite.com/bazel/protobuf/builds/3734#0d08cfee-4662-41ef-a9ed-b1d533b4e76e

**Comment by perezd** [comment]
well shoot, OK I'll try again!

**Comment by perezd** [comment]
Ha, so I fixed a different problem, I'm not sure why it can't find these files....it appears to be environmental because here on a local windows 10 installation this is passing for me :/ Could there be something strange happening? Can we log into these machines remotely and debug?

**Comment by comius** [comment]
Yes, this is 4.1.0. If you have bazelisk setup, it's enough to put 4.1.0 to .bazelversion and it will download when running bazel.

There is a windows testing machine go/bazel-windows-vm, @meteorcloudy knows more than me about CI setup.

**Comment by meteorcloudy** [comment]
I believe this issue is similar to https://github.com/protocolbuffers/protobuf/issues/5691 (which happen in cpp) and was fixed by https://github.com/protocolbuffers/protobuf/pull/5927, we might need to do the same for the java test? /cc @acozzette

**Comment by meteorcloudy** [comment]
In this case, if I run `//java/core:TextFormatTest` individually, it will succeed. But if I first run `//:protobuf_test` then `//java/core:TextFormatTest`, it will fail because the first test will create `bazel-out\x64_windows-fastbuild\bin\src\google\protobuf`, which confuses the TestUtil.java. 
I guess this isn't a problem on Linux because we have sandbox so tests won't influence each other that much.

**Comment by perezd** [comment]
OK I'll attempt to repro this, great find! I would have never guessed.

**Comment by perezd** [comment]
Repro'd and fixed! Thank you for the suggestion, I would have never guessed that.

**Comment by meteorcloudy** [comment]
![image](https://user-images.githubusercontent.com/4171702/123396990-38d78a00-d5a2-11eb-98f7-4dedc7413fb7.png)


Thanks for working on this! This indeed turned the Windows build green, but unfortunately broke Linux and macOS 😅

**Comment by perezd** [comment]
OK! Time to fix this once and for all!

**Comment by perezd** [comment]
OK I think I have made this sufficiently resilient, I have now tested: blaze, bazel, and maven. Windows + Linux.

**Comment by meteorcloudy** [comment]
Thank you, it's green again!
