### ISSUE TITLE
[!] Error installing Protobuf

### ISSUE THREAD

**Issue by noamhavivv** [protocolbuffers/protobuf#8755]
[!] Error installing Protobuf
[!] /usr/bin/git clone https://github.com/protocolbuffers/protobuf.git /var/folders/hj/1wwh2ttj0450vl70z9683vch0000gn/T/d20210622-18502-pq5imj --template= --single-branch --depth 1 --branch v3.17.0

Cloning into '/var/folders/hj/1wwh2ttj0450vl70z9683vch0000gn/T/d20210622-18502-pq5imj'...
warning: Could not find remote branch v3.17.0 to clone.
fatal: Remote branch v3.17.0 not found in upstream origin

'pod install' command failed.

**Comment by perezd** [comment]
The branch you want is: https://github.com/protocolbuffers/protobuf/tree/3.17.x

**Comment by perezd** [comment]
Or this tag: https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.0

**Comment by noamhavivv** [comment]
@perezd I've tried running the following, but still same error

/usr/bin/git clone https://github.com/protocolbuffers/protobuf/tree/3.17.x /var/folders/hj/1wwh2ttj0450vl70z9683vch0000gn/T/d20210623-34317-1ohd303 --template= --single-branch --depth 1 --branch v3.17.0

(I've also tried the same and just switched the url to: https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.0 

Cloning into '/var/folders/hj/1wwh2ttj0450vl70z9683vch0000gn/T/d20210623-34317-1ohd303'...
warning: Could not find remote branch v3.17.0 to clone.
fatal: Remote branch v3.17.0 not found in upstream origin

**Comment by perezd** [comment]
what is the command and tooling your using? Pod makes me think Mac/iOS? Can you share more details of how you're getting this error message?
