### ISSUE TITLE
Why defining protobuf in this way will bring improvements

### ISSUE THREAD

**Issue by seaverwu** [protocolbuffers/protobuf#8764]
I'm doing an experiment recently. If for a structure Person, it has three attributes of id, name, and age, and an array of Person is transmitted in the protocol. When defining a .proto file, there are two methods:
```
(1)message example1 {

repeated int id = 1;

repeated string name = 2;

repeated int age = 3;

}

(2)message example2 {

message Person{

required int id = 1;

required string name = 2;

required int age = 3;

}

repeated Person person_vec = 1;

}
```
Format 1 is to split the Person array into three Person arrays with attributes, and format 2 is to pass the Person array directly

Using clock() to count the serialization/deserialization time, memory usage and other indicators of the two formats, it is found that format 1 is better than format 2. Could you please tell me what is the deep reason for this optimization?

**Comment by coreyzzp** [comment]
because for each message in protocolbuf, the encoder need to caculate the object size in advance to reserve enough space to encode the msg, while the the former one "repeated string name = 2" need to do the same stuff.
