### ISSUE TITLE
PHP RepeatedField - it's not possible to remove not last element

### ISSUE THREAD

**Issue by piotrantosik** [protocolbuffers/protobuf#8766]
**What version of protobuf and what language are you using?**
Version:v3.17.3
Language: PHP, c extension

**What operating system (Linux, Windows, ...) and version?**

Linux, alpine

**What did you do?**
I want to remove aby element from `RepeatedField` but in PHP implementation it's not possibled. When i try remove non last element exception was triggered https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/RepeatedField.php#L209

It's confused because I don't see this limitation in other languages.

**Comment by TeBoring** [comment]
Sorry, this is intended behavior. You can see this is the same as c++. You need to swap the one you want to remove to the last and remove it.
