### ISSUE TITLE
MessageLiteToString  isDefaultValue method does not include Long comparing

### ISSUE THREAD

**Issue by MrPaperMoon** [protocolbuffers/protobuf#8774]
Version: v3.4.0
Language: Java

I have structure like:
```
message Example {

    int64 id = 1;

    string name = 2;
}
```

and when I serializes an instance of "Example" with id == 0L by toString, I expect empty string at result.

1. Example example = new Example.newBuilder().setId(0L).build();
2. example.toString();

E.R.
`# Example@fbb89133`

A.R.
```
# Example@fbb89133
id: 0
```

-------------------------------
isDefaultValue includes all numbers, but not int64
https://github.com/protocolbuffers/protobuf/blob/991bcada050d7e9919503adef5b52547ec249d35/java/core/src/main/java/com/google/protobuf/MessageLiteToString.java#L182

**Comment by elharo** [comment]
I see what you mean. However  isDefaultValue is private implementation detail. Is there some way this leaks into the public API and results? The toString method alone isn't guaranteed output.

**Comment by elharo** [comment]
A PR with a failing unit test might help. As is, I don't yet see how this throws an error or returns an incorrect result. Thanks.

**Comment by elharo** [comment]
I am unable to reproduce this. Please comment if you can provide a reproducible test case.
