### ISSUE TITLE
Didn't find any option for csharp_outer_classname in protocol buffers with C#. Is there any other way I can setup outer classname in proto file?

### ISSUE THREAD

**Issue by vishaldhanani** [protocolbuffers/protobuf#8780]
Hi,
Is there any option for csharp_outer_classname in protocol buffers with C#? I am using "option java_outer_classname" for java based setup. But I didn't find this kind of outer class declaration for the C#.

My protobuf file name starts with digits such as 180myfile.proto and option csharp_namespace = "com.180myfile.Proto"; and when I am building an auto-generated file in C# it's not liking namespace and class name which is starting with a digit and throwing error. 

Can anyone help me to get any other solution to work around it?

Thanks!

**Comment by jskeet** [comment]
No, there's no option for this. The C# namespace you've specified isn't a valid C# namespace, but that part is very easily under your control - just change your option. (I'd also suggest making it a namespace that follows C# conventions, which the one you've specified at the moment doesn't.)

For the class name, there's no option to control this - but I'd strongly recommend that you just rename the proto file. I suspect this won't be the only issue you face by naming the file using a digit to start with. I suspect it'll save a lot of time if you face that now and just rename the file.

You *could* rename the file just temporarily, as part of your build, then name it back after generating the C#, if you absolutely *must* keep it named that for some other reason.

**Comment by vishaldhanani** [comment]
Hi Jon,

Thanks for providing the simplest solution. Yes, I am aware of renaming the protobuf file name and remove the numbers from the starting, it is working well. My concern is only if we can tweak it or change the class name any other way. I have rigid things from my side to maintain the file name starting with numbers. 

I also checked GRPC tools settings to make changes in the class name but they don't have anything like that. 

Thanks for your help!
