### ISSUE TITLE
Handle null values 

### ISSUE THREAD

**Issue by mah454** [protocolbuffers/protobuf#8781]
**What version of protobuf and what language are you using?**
Version: 3.17.3
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 16

**What did you do?**
set null value on DoubleValue field

**What did you expect to see**
empty or null value

**What did you see instead?**
NullPointerException

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
I asked a question about this bug in stackoverflow :      
https://stackoverflow.com/questions/68202081/google-protobuf-handle-null-values

**Anything else we should know about your project / environment**

**Comment by shaod2** [comment]
It is an expected behavior and the answer in your link explains very well. **The getters will never return null** and we enforce the setters as well.

**Comment by mah454** [comment]
Thank you , 
why you does not allow to set null ? 
i think this statement is unnecessary 
```
 if (value == null) {        //<-- unnecessary statement block
        throw new NullPointerException();
}
```

**Comment by perezd** [comment]
Prefer using clear*() field methods instead of setting null, this is consistent with all protobuf implementations across languages. If you set null we'd have to manage semantically what it means to record that nullness, that behavior is unspecified currently.
