### ISSUE TITLE
protoc生产的go代码小写字母需要改成大写字母

### ISSUE THREAD

**Issue by xionglihdfs** [protocolbuffers/protobuf#8784]
用如下命令生成的文件 demo.pb.go 和 demo_grpc.pb.go
$ protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative demo/proto/demo.proto

其中文件demo_grpc.pb.go的接口DemoServer的成员函数MustEmbedUnimplementedDemoServer()首字母是小写，需要改成大写；同时func (UnimplementedDemoServer) MustEmbedUnimplementedDemoServer() {}接口实现也要改成大写，在服务注册pb.RegisterDemoServer(grpcServer, &DemoService{})的时候会报不通过。

也可以去掉生成的成员函数MustEmbedUnimplementedDemoServer()和接口func (UnimplementedDemoServer) MustEmbedUnimplementedDemoServer() {}也是可以注册通过的。

**Comment by xionglihdfs** [comment]
版本型号为

$ go version
go version go1.16.5 darwin/amd64

$ protoc --version
libprotoc 3.17.3

**Comment by TeBoring** [comment]
For go questions, please ask https://github.com/golang/protobuf
