### ISSUE TITLE
"NMAKE: fatal error U1077" occurs when running "nmake check" - protobuf-cpp-3.17.3

### ISSUE THREAD

**Issue by RS357** [protocolbuffers/protobuf#8785]
**What version of protobuf and what language are you using?**
Version: v3.17.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro

**What runtime / compiler are you using (e.g., python version or gcc version)**
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x86

**What did you do?**

Downloaded and unpacked protobuf-cpp-3.17.3.tar.
Followed instructions in cmake/README.md to generate  nmake Makefile in cmake\build\release, cmake\build\debug and to generate Visual Studio solution file in cmake\build\solution.
Ran command "nmake" in cmake\build\release and cmake\build\debug.
Ran "nmake check" in cmake\build\release.

**What did you expect to see**
All tests passing 100%.

**What did you see instead?**
Error in Command Prompt:

```
Running main() from gmock_main.cc
[==========] Running 2275 tests from 201 test suites.
[----------] Global test environment set-up.
[----------] 1 test from AnyMetadataTest
[ RUN      ] AnyMetadataTest.ConstInit
[       OK ] AnyMetadataTest.ConstInit (0 ms)
[----------] 1 test from AnyMetadataTest (1 ms total)

[----------] 9 tests from AnyTest
[ RUN      ] AnyTest.TestPackAndUnpack
[       OK ] AnyTest.TestPackAndUnpack (0 ms)
[ RUN      ] AnyTest.TestPackFromSerializationExceedsSizeLimit
NMAKE : fatal error U1077: 'C:\Users\Riz\Downloads\protobuf-3.17.3\cmake\build\release\tests.exe' : return code '0x3'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

Anything else we should know about your project / environment?

When running:
```
     C:\Path\to\protobuf\cmake\build>mkdir release & cd release
     C:\Path\to\protobuf\cmake\build\release>cmake -G "NMake Makefiles" ^
     -DCMAKE_BUILD_TYPE=Release ^
     -DCMAKE_INSTALL_PREFIX=../../../../install ^

 ../..
```

...in `protobuf-3.17.3\cmake\build\release` via the MSVC Developer Command Prompt the following error is outputted:
```
-- 3.17.3.0
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Riz/Downloads/protobuf-3.17.3/cmake/build/release
```

**Comment by TeBoring** [comment]
Sorry that we don't officially support namke. If you have a PR to fix it, we are happy to accept.
