### ISSUE TITLE
Support generating original .proto file from FileDescriptor in Java

### ISSUE THREAD

**Issue by blacktooth** [protocolbuffers/protobuf#8795]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**

I am implementing a schema registry for Protobuf schema definitions and looking for a functionality to obtain the original `.proto` file content from a `Message` object. It is possible to fetch the `FileDescriptor` from a `Message` object and get it's proto content by using following code. However, the generated proto content is not in `.proto` format. It would be helpful if `FileDescriptorProto` can preserve the original `.proto` content or a new `getSource` method is added to generate the text in `.proto`.

**Describe the solution you'd like**

```
message.getDescriptorForType().getFile().toProto().toString()
```

**Current format**

```
name: "Phone.proto"
package: "com.foo.bar"
message_type {
  name: "Phone"
  field {
    name: "model"
    number: 1
    label: LABEL_OPTIONAL
    type: TYPE_STRING
  }
  field {
    name: "name"
    number: 2
    label: LABEL_OPTIONAL
    type: TYPE_STRING
  }
  field {
    name: "serial"
    number: 3
    label: LABEL_OPTIONAL
    type: TYPE_INT32
  }
}
options {
  java_package: "com.foo.bar"
  java_outer_classname: "Contact"
}
syntax: "proto3"
```

**Proposed format**

```
message.getDescriptorForType().getFile().toProto().getSource()
```

```
syntax = "proto3";

package com.foo.bar;

option java_outer_classname = "Contact";
option java_package = "com.foo.bar";
message Phone {
    string model = 1;
    string name = 2;
    int32 serial = 3;
}
```

**Describe alternatives you've considered**

The alternative now is to generate it manually by either parsing above text or using other helper methods. It would be helpful is this functionality is provided natively within the library.

**Comment by TeBoring** [comment]
I think the FileDescriptor contains all the information. Why the original format is required?

**Comment by blacktooth** [comment]
It's helpful in schema registry like use-cases used with streaming services like Kafka, Kinesis etc. When producers produce data, they need to validate if the schema they are using is valid and accepted by consumers. They do it by querying a central service over HTTP with the original `.proto` text. If schema is valid, the service returns a UUID corresponding to the schema. The producers embed the schema UUID into messages that they produce. When the messages are de-serialized by consumers, they query the central service to verify the schema UUID is valid and get corresponding schema (`.proto` file) to read the message. 
The process of converting `FileDescriptor` to `.proto` file is tedious and can be error prone if developers implement their own versions. It would be great if the original reference is retained or Protobuf library provides a standard implementation of it.

**Comment by perezd** [comment]
Sorry but this isn't something we'll be doing. Generally if you need this, its advised to provide it through a sidechannel adjacent to the Protos themselves, this can lead to significant jarfile bloat that most users don't need.

**Comment by blacktooth** [comment]
I agree JAR size is a big concern. Alternatively, is it possible to provide a method that can generate it at runtime? In case of separate implementation, it's hard to keep it consistent with changes in Protobuf. With growing use-cases for schema registry with protobuf, we believe this will be useful.

**Comment by perezd** [comment]
When you say changes in protobuf, do you mean the protobuf library itself? Or your own .proto files? There are tools out there such as https://github.com/perezd/protopoet (shameless plug) that you could use to generate these yourself, but we're not likely to support this directly in the protobuf library itself. This sort of thing we like to leave to customers to design externally as there are so many way people want to approach this.

**Comment by perezd** [comment]
FWIW, free design review opinion: Whatever you're needs are, if you're basing it on the source code and not the descriptor, this is probably more brittle than you mean for it to be. The DescriptorProto API is really the source of truth in all cases internally and externally.

**Comment by blacktooth** [comment]
> When you say changes in protobuf, do you mean the protobuf library itself?
I meant the protobuf library. 

> The DescriptorProto API is really the source of truth in all cases internally and externally.

Can a serialized form of the DescriptorProto be used to uniquely identify a Proto version?

**Comment by perezd** [comment]
> Can a serialized form of the DescriptorProto be used to uniquely identify a Proto definition? 

Yes it should be, now how are you going to encode/represent that? That is up to you! I'd suggest a deterministic hashing process.

**Comment by blacktooth** [comment]
>Yes it should be, now how are you going to encode/represent that? 

MD5 hash the `FileDescriptor.toByteString`. Is it guaranteed to be same with future Protobuf library upgrades?

**Comment by perezd** [comment]
I'd check the code and double check that deserialization ordering keeps that deterministic, I am not positive that anything guarantees that and it may need to be externally guaranteed by your code in a more explicit way.
