### ISSUE TITLE
Protobuf CI broken for Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [protocolbuffers/protobuf#8799]
Breakage example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2091#c17c0576-e53f-40b5-8519-7b4e70af06b2

Culprit: bazelbuild/bazel@7800ff9

Solution alternatives:
1. Update rules_jvm_external version to newest version.
2. Run CI builds with --incompatible_enable_exports_provider. We'll need to follow up to fix these builds before the flag may be removed.

**Comment by c-parsons** [comment]
https://github.com/protocolbuffers/protobuf/pull/8800 is a proposal for solution (1), but I"m unable to manually verify this fixes the builds, because I'm unable to get builds to work cloned from this repo at all.

ERROR: .../external/rules_jvm_external/private/tools/java/rules/jvm/external/maven/BUILD:3:12: no such package '@rules_jvm_external_deps//': The repository '@rules_jvm_external_deps' could not be resolved and referenced by '@rules_jvm_external//private/tools/java/rules/jvm/external/maven:MavenPublisher'

**Comment by perezd** [comment]
Thanks for the heads up!
