### ISSUE TITLE
Generated Kotlin files cause compilation to fail on Kotlin/JVM 1.5 with progressive mode enabled

### ISSUE THREAD

**Issue by Oneiriac** [protocolbuffers/protobuf#8804]
**What version of protobuf and what language are you using?**
Version: v3.17.3
Language: Kotlin 1.5.20

**What operating system (Linux, Windows, ...) and version?**
macOS - Big Sur version 11.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Kotlin 1.5.20 on AdoptOpenJDK 11, with [progressive mode](https://kotlinlang.org/docs/whatsnew13.html#progressive-mode) ("deprecations and bug fixes for unstable code take effect immediately") enabled for the compiler via the `-progressive` flag.

**What did you do?**
1. Clone https://github.com/Oneiriac/gradle-kotlin-proto-test (project with demo source files, Gradle configs and dependencies already set up)
2. Run `./gradlew clean compileKotlin`
3. See the error output below.

**What did you expect to see**
Project should compile successfully.

**What did you see instead?**
Compilation fails with `JvmField has no effect on a private property` errors:
```
> Task :compileKotlin FAILED
e: .../gradle-kotlin-proto-test/build/generated/source/proto/main/kotlin/org/example/addressbook/AddressBookKt.kt: (13, 5): JvmField has no effect on a private property
e: .../gradle-kotlin-proto-test/build/generated/source/proto/main/kotlin/org/example/addressbook/PersonKt.kt: (13, 5): JvmField has no effect on a private property
e: .../gradle-kotlin-proto-test/build/generated/source/proto/main/kotlin/org/example/addressbook/PersonKt.kt: (154, 7): JvmField has no effect on a private property
```

These stem from lines such as the snippet below:
```kotlin
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: org.example.addressbook.AddressBookOuterClass.AddressBook.Builder
  )
```

The files in this repo that have these forbidden `JvmField` annotations on private properties are:
- https://github.com/protocolbuffers/protobuf/blob/76188afb94c985c859823b6a64ff88bed3be667b/src/google/protobuf/compiler/java/java_message_lite.cc#L735
- https://github.com/protocolbuffers/protobuf/blob/4e0a1119c0c5cdfe89b54b9d66cb76223f17861a/src/google/protobuf/compiler/java/java_message.cc#L1412
- https://github.com/protocolbuffers/protobuf/blob/4e0a1119c0c5cdfe89b54b9d66cb76223f17861a/java/kotlin/src/main/kotlin/com/google/protobuf/ExtensionList.kt#L43

**Anything else we should know about your project / environment**
The compilation error doesn't occur when dropping to Kotlin 1.4, ~~but the generated Kotlin sources still have these lines highlighted as errors in IntelliJ IDEA~~.

**Comment by keith-miller** [comment]
Any word on when the fix version will go out? Thanks!

**Comment by perezd** [comment]
Not positive, but it'll go out with our next release which isn't yet scheduled but likely sometime in the next month or so.

**Comment by keith-miller** [comment]
Thank you!

**Comment by snijsure** [comment]
I am using 3.19.4 and Kotlin version 1.6.10 and I still see ```JvmField has no effect on a private property```

But this issue is marked as closed, is there an option to protoc I should be using when generating code?

```
protoc --version
libprotoc 3.19.4
```

**Comment by mmaico** [comment]
@snijsure i had the same problem and i solved using [this project](https://github.com/GoogleCloudPlatform/kotlin-samples) as an example. The [subproject](https://github.com/GoogleCloudPlatform/kotlin-samples/tree/main/run/grpc-hello-world-mvn)  has the configurations of the versions you are using.
