### ISSUE TITLE
C#: Equals field name does not compile successfully

### ISSUE THREAD

**Issue by frondeus** [protocolbuffers/protobuf#8810]
**What version of protobuf and what language are you using?**
Version: 3.17.3 via Nuget Google.Protobuf
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Linux, Manjaro.

**What runtime / compiler are you using (e.g., python version or gcc version)**

dotnet 5.0.203

**What did you do?**
1. `dotnet new console --interactive`
2. Write to csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>protobuf_err</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.17.3" />
    <PackageReference Include="Grpc.Net.Client" Version="2.38.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.38.0" />
    <PackageReference Include="Grpc.Tools" Version="2.38.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="test.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
```
3. Create new file `test.proto` in root directory:
```
syntax = "proto2";

package test;

service Test {
  rpc Test(TestMsg) returns (TestMsg);
}

message TestMsg {
  oneof test_msg {
    EqualsMsg equals = 1;
  }
}

message EqualsMsg {
  required string foo = 1;
}
```

**What did you expect to see**

Test.cs compiled successfully

**What did you see instead?**

```
/tmp/protobuf-err/obj/Debug/net5.0/Test.cs(88,35): warning CS0108: 'Element „TestMsg.Equals” uses inherited „object.Equals(object?)”. Use keyword new. [/tmp/protobuf-err/protobuf-err.csproj]
/tmp/protobuf-err/obj/Debug/net5.0/Test.cs(115,26): error CS0102: Type „TestMsg” already contains definition „Equals” [/tmp/protobuf-err/protobuf-err.csproj]
/tmp/protobuf-err/obj/Debug/net5.0/Test.cs(120,17): error CS0102: Type „TestMsg” already contains definition „Equals” [/tmp/protobuf-err/protobuf-err.csproj]

Could not compile.
```
(The error message is loosely translated, sorry).

As far as I understand there is a collision between my `Equals` variant and C# `Equals` method used for Object comparison. 

I don't know what the solution should be. Maybe `new` keyword as suggested for method hiding, maybe simply renaming (by the codegen) the field to `_Equals`? 

In the worst scenario - at least document such an edge case somewhere so it's more obvious why it happened and what names are forbidden.

**Anything else we should know about your project / environment**

I know I can simply rename the field manually in my proto because Protobuf does care only about the order and the types, but the proto comes from external services and I'd love to avoid copying and `sed`ing it every time I build my project.

**Comment by jskeet** [comment]
Hmm. The problem is that we're generating an `Equals` property for the `equals` field, and that's causing problems with the `Equals` method. You'd have the same problem with a field called `to_string` or `get_hash_code`, I suspect.
It's easy to change the generator to do that... it would be a breaking change if we *only* generated a warning, but as there's already an error, there can't be any code that already relies on this working. I'll need to check that we *do* always get an error though. I'll try to get to it this week.
