### ISSUE TITLE
Protobuf CI broken for Bazel@HEAD

### ISSUE THREAD

**Issue by mai93** [protocolbuffers/protobuf#8815]
Breakage example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2100#c019c4f3-39a5-498c-abc1-88106c92a2b4

The last green commit cannot be updated to include the fix in d652d8059c55cda60d8abb4c353d2896c82d55e2. The scheduled build fails with Bazel 4.1.0
Breakage example: https://buildkite.com/bazel/protobuf/builds/3775#de7b3239-f52a-4645-8e98-87cc1e4937ce

**Comment by perezd** [comment]
This target failed: `//:build_files_updated_unittest`

Looks like this is the relevant log: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/9db98e93-aad1-40e2-ab70-042d2ee219c4/build_files_updated_unittest/attempt_3.log

Which seems related to this change: https://github.com/protocolbuffers/protobuf/commit/336ed1820a4f2649c9aa3953d5059b03b7a77100

Do you know if there's something else that needs updating? I can't actually repro this failure locally on MacOS, weirdly. Maybe its already fixed and this is lagging behind?

**Comment by mai93** [comment]
The target fails only on ubuntu 20.04. I think this test has been failing with scheduled builds of Protobuf with Bazel 4.1.0 [since 29th June](https://buildkite.com/bazel/protobuf/builds/3743#e4040ba1-7e70-4984-85a5-d8b265194b44) but we could not get the log files of the failed test due to an issue with BazelCI script.

**Comment by acozzette** [comment]
Sorry for the trouble, this should be fixed with #8823.
