### ISSUE TITLE
Implement __iter__ in Python RepeatedScalarContainer

### ISSUE THREAD

**Issue by erik-hasse** [protocolbuffers/protobuf#8816]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
The `__iter__` attribute is commonly used to check whether an object is list-like, so neglecting to include it can cause issues, for example this bug in pandas: pandas-dev/pandas#42549. This results in weird behavior where `list(obj)` works fine even though `hasattr(obj, '__iter__')` is False. 

**Describe the solution you'd like**
The Python [`RepeatedScalarContainer`](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/pyext/repeated_scalar_container.cc#L767-L781) should implement `tp_iter` in addition to `tp_as_sequence`.

**Describe alternatives you've considered**
Manually convert to a list every time we use RepeatedScalarContainer (`list(obj)`).

**Comment by barshaul** [comment]
@zhangskz Are there any updates on this?

**Comment by caneff** [comment]
Ping on this.

**Comment by caneff** [comment]
This is still a problem, and internally at Google we still have to patch Pandas in order to make it work with proto repeated fields. Any updates as to fixing this?
