### ISSUE TITLE
Ability to reuse existing memory for RepeatedField

### ISSUE THREAD

**Issue by Azmisov** [protocolbuffers/protobuf#8817]
My particular use case in C++, where the data for a RepeatedField is constructed elsewhere via more advanced computation on std::vector, Eigen matrices, etc, which would not be possible with the RepeatedField data structure. As these outside data structures are already contiguous memory blocks, I'd like to just reuse their underlying memory for RepeatedField. Right now, it seems the only way to convert to a RepeatedField is copying all the elements over (constructor or Add w/ iterator uses std::copy internally). As it is just using an Elements* buffer internally, seems we could do a zero-copy reuse.

I have a couple suggestions for how we could add that API:

- Have a `set_allocated(Elements* data, int current_size, int total_size)` method for RepeatedField. Internally `data` would get wrapped in a `Rep` struct with arena being null. Could have a second signature where user provides a `Rep` struct or `Arena`.  Looking at source code for `Reserve`, it doesn't look like you realloc the `Elements*` memory block, instead just creating a new one. So I believe this should work out of the box with all other class methods.
- Have another class `ConstRepeatedField`, which only implements the getter methods (e.g. elements cannot be modified). We'd still have a method `set_allocated(Elements* data, int current_size, int total_size, bool own)` (possibly with overload for additional `Arena`/`Rep`). There is an additional `own` flag, which functions like the `release_foo` API for Message; when false, the class destructor will not try to deallocate `data`.

**Comment by fowles** [comment]
Experience with borrow/steal APIs like this for strings have not been good.  It turns out that these things leak implementation details pretty heavily.  It is unlikely we will add something like this in the near term.

**Comment by Azmisov** [comment]
The API already exposes the pointer to `Elements*`, so I don't see that we'd be leaking any implementation details that aren't already. We'd just be adding that `set_allocated` method. I think it would be a very quick pull request... work out of the box. If we're concerned with the `delete` that would happen in `Reserve` method, I personally would be fine having a `ConstRepeatedField` instead, which does not have setter methods, only `set_allocated` and getters.

Did you have any specific concerns regarding the API I changes I suggested, specifically? Perhaps you could explain further what implementation details would get leaked.

**Comment by fowles** [comment]
To start with RepeatField only backs primitives, not Message or strings, so there is RepeatedPtrField as well whose underlying buffer is a T**.  Next issue is that to extract the values from a vector you need some way to steal the underlying buffer from that vector (or you can lie about actual ownership, which has a bag of worms).

**Comment by Azmisov** [comment]
For `RepeatedPtrField`, I personally am not using so I haven't thought about if the same or different API would be used there.

Your second concern is noted, but I figure this would be used for more advanced users wanting to optimize further, so we can let the user manage the memory themselves in those cases. We already have the `release_foo` API's available, so I think this is similar, letting user own the memory themselves. True, you couldn't use `RepeatedField.set_allocated` with `std::vector`, but you could with `ConstRepeatedField`, with own=false. Non-STL structures may allow safe borrowing, which is why I suggested the `RepeatedField.set_allocated` interface (e.g. if user manually created an array). Some examples:

```c++
{
    std::vector<int> data;
    for (int i=0; i<15; i++)
        data.push_back(i);
    ConstRepeatedField &field = ...;
    field.set_allocated(data.data(), data.size(), false); // doesn't own data
    msg.SerializeToOstream(&std::cout);
}
{
    int *data = new int[100];
    for (int i=0; i<15; i++)
        data[i] = i;
    RepeatedField &field = ...;
    field.set_allocated(data, 100, 15); // own's data
    msg.SerializeToOstream(&std::cout);
}
```

**Comment by fowles** [comment]
As you go down this path, you will discover that `set_allocate`/`release` behave differently when arenas are involved and that the fixes you are suggesting end up increasing the volume of allocations and copies.  Then you start to play games with `unsafe_arena_set_allocated`/`unsafe_arena_release`.  There is a really large space of complexity here that we have found the hard way.  We are not going to broach this particular bag of worms lightly and do not have time to go into the detailed designs required right now.
