### ISSUE TITLE
PHP - Add support for insertion points

### ISSUE THREAD

**Issue by phphphphphp** [protocolbuffers/protobuf#8818]
**What language does this apply to?**
If it's about generated code change, what programming language?
PHP

**Describe the problem you are trying to solve.**
PHP doesn't seem to have support for `@@protoc_insertion_point(NAME)` comments, which makes extending existing generated code classes messy/not possible in non-static contexts.

**Describe the solution you'd like**
Add support for `// @@protoc_insertion_point` type comments so plugins can better extend existing generated PHP code.

**Describe alternatives you've considered**
Alternates include attempting to extend the code generated by the main protoc generator, however as mentioned before this becomes messy and redundant.

**Comment by fowles** [comment]
We have learned (through painful experience) that insertion points are a very fragile extension mechanism.  They expose all of our internals in a way that makes future evolution very difficult.  As such, we have avoided adding them to newer language bindings.

**Comment by phphphphphp** [comment]
Ah ok I could see that being the case, thanks for the heads up!

I opened this ticket because what I'm really looking for is for PHP to support custom options by adding API support for it, however the [existing issue for this](https://github.com/protocolbuffers/protobuf/issues/3065) has been open for ~4 years now with no resolution, so I figured instead I'd look into the feasibility of emulating this functionality via a custom plugin. I think this should still be possible even without insertion points, but am still trying to flesh out the details.

**Comment by haberman** [comment]
I added an update to https://github.com/protocolbuffers/protobuf/issues/3065. Sorry it's been such a long wait.

I'll plan to close this bug because we don't want to add insertion points. But hopefully we will have true custom option support in PHP before too long.
