### ISSUE TITLE
how to generate message NOT order by field number in C# ?

### ISSUE THREAD

**Issue by rozbo** [protocolbuffers/protobuf#8826]
In other language such as go nodejs, thinking the proto file like this

```
message Test{
    int32 b = 2;
    int32 a = 1;
}
```

after serialize , the b is in front of a .
but if c#, whatever the order in proto file, a is always front of b,  seem  it already order by field number.
so, is there a way to serialize but  **NOT** order by field number ?

**Comment by rozbo** [comment]
@jskeet help pls

**Comment by jskeet** [comment]
No, there is no way to do this and I wouldn't expect there to be. No guarantee is made as to serialization order, but IIRC there are internal documents *recommending* that field number order is used, which is what we do for C#. (I believe Java also uses this approach, or at least did when we first implemented the C# plugin.)

**Comment by jskeet** [comment]
The [documentation](https://developers.google.com/protocol-buffers/docs/encoding#order) states:

> Field numbers may be used in any order in a .proto file. The order chosen has no effect on how the messages are serialized.

That suggests that the C# implementation is doing the right thing here - the second sentence suggests that reordering the fields shouldn't make a difference to serialization, whereas you're asserting that it *does* make a difference in Go and Node.

Note that parsers should be able to parse values in any order anyway.

**Comment by rozbo** [comment]
Thank you for your quick response. You're right. I see
