### ISSUE TITLE
Type Error is thrown when _implementation_version_str is None

### ISSUE THREAD

**Issue by michael-richey** [protocolbuffers/protobuf#8831]
Need to wrap `_implementation_version_str` in `str()` so that the proper error is raised when the value is `None`

https://github.com/protocolbuffers/protobuf/blob/d662ec9c2e4f8ca21cb500b25cfe7430511014b2/python/google/protobuf/internal/api_implementation.py#L111

**Comment by deannagarcia** [comment]
Thanks for this report! Do you have an example of an error being thrown? I'm not sure if _implementation_version_str can be None given that it has a default value.

**Comment by michael-richey** [comment]
I should have kept the env around. I don't see how it's possible now looking over the code, but I did see the error. It was trying to concat `None` with the string
