### ISSUE TITLE
ProtoBuf2.5.0 Mac M1 cpu make failed

### ISSUE THREAD

**Issue by QinchengZhang** [protocolbuffers/protobuf#8836]
**What version of protobuf and what language are you using?**
Version: v2.5.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS Big Sur 11.5 (20G71)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 12.0.5 (clang-1205.0.22.11)

**What did you do?**
./configure
sudo make && make install

**What did you see instead?**
fatal error: too many errors emitted, stopping now [-ferror-limit=]
9 warnings and 20 errors generated.
make[2]: *** [atomicops_internals_x86_gcc.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by xuexuelove** [comment]
help! me too

**Comment by fowles** [comment]
This is a fairly old release.  Does this issue persist on 3.17.x ?

**Comment by xuexuelove** [comment]
> This is a fairly old release. Does this issue persist on 3.17.x ?

My project needs this version

**Comment by fowles** [comment]
Unfortunately, supporting all old releases on new hardware and new toolchains is not a thing we likely to spend resources on.

**Comment by xuexuelove** [comment]
> Unfortunately, supporting all old releases on new hardware and new toolchains is not a thing we likely to spend resources on.
thanks

**Comment by xuexuelove** [comment]
./google/protobuf/stubs/atomicops_internals_macosx.h:157:52: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
inline Atomic64 NoBarrier_AtomicIncrement(volatile Atomic64* ptr,
                                                   ^~~~~~~~
                                                   Atomic32

Does anyone have an idea?

**Comment by DapengShi** [comment]
@xuexuelove 
I meet the same question. To resolve it, I have added 
#elif defined(__arm64__)
#define GOOGLE_PROTOBUF_ARCH_ARM 1
#define GOOGLE_PROTOBUF_ARCH_64_BIT 1
before 
#else
#error Host architecture was not detected as supported by protobuf
in src/google/protobuf/stubs/platform_macros.h for version 2.5.0
, then I made install successfully.  Maybe you can try it.

**Comment by rangareddy** [comment]
Hi @DapengShi 

I am able to resolve the issue with your comment. Thank you very much.

`#elif defined(__arm64__)
#define GOOGLE_PROTOBUF_ARCH_ARM 1
#define GOOGLE_PROTOBUF_ARCH_64_BIT 1`

**Comment by mrtisttt** [comment]
It works. Thanks~
