### ISSUE TITLE
Kotlin reserved word "in" is not escaped when using in the package name

### ISSUE THREAD

**Issue by hualong-shen** [protocolbuffers/protobuf#8837]
**What version of protobuf and what language are you using?**
Version: 3.17.3
Language: Java/Kotlin

**What operating system (Linux, Windows, ...) and version?**
macOS, 11.2.3

**What runtime / compiler are you using (e.g., python version or gcc version)**
Kotlin 1.5.21

**What did you do?**
1. Write a proto and specify `option java_package = "in.some.path";`
2. User protoc to generate the code `protoc --java_out=... --kotlin_out=... *.proto`
3. Check the generated java file, the package name is `package in.some.path` which is expacted
4. Check the generated kotlin file, the package name is same `package in.some.path` which throw an error because `in` is a reserved word in kotlin.

**What did you expect to see**
In Kotlin file the reserved word should be escaped automatically: ``package `in`.some.path``. 
I use Android Studio. The IDE does the escape for me when I use `in` in the package name. I think protoc should do the same, to escape any reserved word in the package name.

**What did you see instead?**
`package in.some.path`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
Hello, thanks for this report! I don't think we want to allow for the package name in Java and Kotlin to be different (where one is escaped and one is not) as that makes the imports look different. We currently don't error check package names in either Java or Kotlin and I think it makes sense to keep it that way since this can be fixed by changing the java package name to either be escaped already or to have a different name that isn't a Kotlin keyword.

**Comment by hualong-shen** [comment]
@deannagarcia Yes, not using the keywords will not have problems. But escaping the keywords in the package name is valid in Kotlin.   
Consider this case, I already use `in` in the Java package name as it is not a keyword in Java. Then I start to use Kotlin and I want to use the same package. Kotlin allows us to do this by escaping the keyword. So for now I have to escape all the things manually or change to another package both are not best for my case.
Please consider supporting this.

**Comment by deannagarcia** [comment]
Thanks for explaining this case, it's helpful to understand why this is a problem. I will look into fixing it and keep you updated when I have a fix.

**Comment by deannagarcia** [comment]
This issue should be resolved with https://github.com/protocolbuffers/protobuf/commit/cc696d4babf8c4faf59984c596033701ed479ef6
