### ISSUE TITLE
Number tags inside oneof with nested messages don’t work as intended

### ISSUE THREAD

**Issue by kfirtaizi** [protocolbuffers/protobuf#8838]
**What version of protobuf and what language are you using?**
Version: v3.17.3
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.9.4

**What did you do?**
**Steps to reproduce the behavior:**
I have three .proto files:

```
syntax = "proto3";

package first;

message Message {
    string a1 = 1;
    bool b1 = 2;
}
```
```
syntax = "proto3";

package second;

message Message {
    string a2 = 1;
}
```
```
syntax = "proto3";

import "first.proto";
import "second.proto";

package my_oneof;

message Message {
    oneof test {
        first.Message first = 1;
        second.Message second = 2;
    }
}
```
From my understanding, this oneof is supposed to work, but when I try this:
```python
from google.protobuf.json_format import ParseDict

import first_pb2 as First
import my_oneof_pb2 as MyOneOf

if __name__ == '__main__':
    json = {"a1": "testtest123", "b1": True}
    m = ParseDict(json, First.Message())
    x = MyOneOf.Message()
    x.ParseFromString(m.SerializeToString())
    print(x)
```

I get the error:
```
Traceback (most recent call last):
  File (hidden), line 10, in <module>
    x.ParseFromString(m.SerializeToString())
google.protobuf.message.DecodeError: Error parsing message
```

Now the weird thing is, when I modify the number tags in the oneof a little bit, it works. In this instance, if I start the first field from `2` it finishes running without error, like so:
```
message Message {
    oneof test {
        first.Message first = 2;
        second.Message second = 3;
    }
}
```

What's the definition of the tags inside a oneof? If it's a oneof, and the tags mean where the data is located in the bytes, shouldn't all fields be `=1` as only one of them anyways is the one in every occurrence? Why does it work with `=2` but not with `=1` like I mentioned?

**What did you see instead?**
```
Traceback (most recent call last):
  File (hidden), line 10, in <module>
    x.ParseFromString(m.SerializeToString())
google.protobuf.message.DecodeError: Error parsing message
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Anything else we should know about your project / environment

**Comment by deannagarcia** [comment]
Sorry for the long delay. Are you still seeing this error in newer versions of protobuf?

**Comment by deannagarcia** [comment]
Closing due to no response, feel free to reopen if you are still facing this issue.
