### ISSUE TITLE
Failed to resolve com_google_protobuf_javalite

### ISSUE THREAD

**Issue by electricmind007** [protocolbuffers/protobuf#8840]
**What version of protobuf and what language are you using?**
Version: master
Language:Java/Python

**What operating system (Linux, Windows, ...) and version?**
Redhat 7.7

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 1.8.0

**What did you do?**
While resolving io_grpc_grpc_java deps of rules_proto, we are getting below issue 

java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found
ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/io_grpc_grpc_java/protobuf-lite/BUILD.bazel:1:13: no such package '@com_google_protobuf_javalite//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found and referenced by '@io_grpc_grpc_java//protobuf-lite:protobuf-lite'

**What did you expect to see**
Successful resolution

**What did you see instead?**
java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found
ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/io_grpc_grpc_java/protobuf-lite/BUILD.bazel:1:13: no such package '@com_google_protobuf_javalite//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found and referenced by '@io_grpc_grpc_java//protobuf-lite:protobuf-lite'
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by perezd** [comment]
This appears to be caused by grpc-java attempting to download something that doesn't exist. I'd suggest filing an issue with their project: https://github.com/grpc/grpc-java

**Comment by ejona86** [comment]
This is an old version of gRPC that was referencing google/protobuf. The google/protobuf → protocolbuffers/protobuf redirect broke yesterday, which caused the problem. The redirect has since been fixed.
