### ISSUE TITLE
`JsonFormat` helper library for PHP

### ISSUE THREAD

**Issue by srth12** [protocolbuffers/protobuf#8846]
**What language does this apply to?** PHP
If it's a proto syntax change, is it for proto2 or proto3? proto3
If it's about generated code change, what programming language? PHP

**Describe the problem you are trying to solve.**
In PHP, on designing or extendign an API, we often require responses in JSON format, but this language does not have `JsonFormat` to convert Protobuf object to JSON, whereas other languages like Java does have this functionality in the `util` folder. This force as to manually create the JSON from the Protobuf object. For java, we could use the `JsonFormat` under the `util` folder  - https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java

**Describe the solution you'd like**
Expecting a util to support the conversion of Protobuf object to a JSON string. 

**Describe alternatives you've considered**
I have manually created the json using the Protobuf object, which is tiresome and error prone if the object is large or complex.

**Additional context**

**Comment by haberman** [comment]
In PHP you can serialize to/from JSON by calling:

```php
  $json = $message->serializeToJsonString();
  $message = $message->mergeFromJsonString($json);
```

This should be better documented.

**Comment by srth12** [comment]
Yes, we could serialise it back to object but not # to JSON string. How 

```$json = $message->serializeToJsonString();
  $message = $message->mergeFromJsonString($json);

//`JsonFormat` library is missing in PHP, but is available in
//other languages. I am expecting something like this
print( JsonFormat.parse( $message ) );
```
