### ISSUE TITLE
improve protoc-gen-X  parameter documation

### ISSUE THREAD

**Issue by coreyzzp** [protocolbuffers/protobuf#8848]
protoc-gen-X plugin mechanism is a great way to write tool based on proto file, but by far I found each plugin has no clear
way to print out its own plugins (you can not use -h to print the help message of each plugin as the plugin's default behavior is listening on the STDIN as the plugin.proto CodeGeneratorRequest ) , and the plugin's parameter need to found on its own website or even the source code ! ?

for example you need to read the  `https://github.com/pseudomuto/protoc-gen-doc/blob/master/plugin.go` file to fully understand the parameters of `protoc-gen-doc `

```
// The parameter (`--doc_opt`) must be of the format <TYPE|TEMPLATE_FILE>,<OUTPUT_FILE>:<EXCLUDE_PATTERN>,<EXCLUDE_PATTERN>*.
// The file will be written to the directory specified with the `--doc_out` argument to protoc.
```

is there any official method to make plugin writer keep an standard method to make users of their plugs has a better 
understanding of their plugin's usage ?

**Comment by perezd** [comment]
There is currently no way to expose params like this in protoc, however, because the plugins themselves must be executables, the plugin authors could print output if the executable is ran directly w/o any STDIN piped data.

**Comment by coreyzzp** [comment]
you are right, but it would be better to be a officail guide line for all plugin developers
