### ISSUE TITLE
Support explicit API mode in Kotlin

### ISSUE THREAD

**Issue by dmdashenkov** [protocolbuffers/protobuf#8857]
Kotlin compiler supports a "strict" mode called [explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md). The mode enforces explicit visibility modifiers and type declarations in public API.

Right now, if the mode is enabled and Kotlin is generated from Protobuf, Kotlin compiler fails with an error because the generated code does not comply with the explicit mode.

There could be two possible scenarios:
 1. Allow users to specify whether or not we want to generate code with explicit visibility modifiers.
 2. Generate all the code this way. Disabling this compiler mode would not break the more explicit code.

**Comment by fowles** [comment]
Seems like (2) is the better choice.  Generate the strictest thing we can and let others opt in.  What do you think?

**Comment by dmdashenkov** [comment]
If you ask me, (2) seems preferable indeed, as it implies less effort and less code to maintain in the future.

**Comment by zhangskz** [comment]
Approach (2) was submitted in #8968, so the generated code should be explicit API mode compatible now. Please reopen if you encounter any issues with this!

**Comment by zhangskz** [comment]
I believe 3.18.1 was already in the works when this was added. This should make it into the 3.19.0 release which is in the works right now and should be released soon, tentatively today.
