### ISSUE TITLE
PHP Any::is trigger fatal error on not protobuf messages

### ISSUE THREAD

**Issue by solodkiy** [protocolbuffers/protobuf#8865]
**What version of protobuf and what language are you using?**
Version: v3.17.3
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.5 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.2.24-0ubuntu0.18.04.8

**What did you do?**
Run
```
$any = new \Google\Protobuf\Any();
var_dump($any->is(\stdClass::class));
```

**What did you expect to see**
`false`

**What did you see instead?**
```
PHP Fatal error:  Uncaught Error: Call to a member function getFullName() on null in /home/doc/projects/test/twirp/vendor/google/protobuf/src/Google/Protobuf/Internal/AnyBase.php:82
Stack trace:
#0 /home/doc/projects/test/twirp/x.php(12): Google\Protobuf\Internal\AnyBase->is('stdClass')
#1 {main}
  thrown in /home/doc/projects/test/twirp/vendor/google/protobuf/src/Google/Protobuf/Internal/AnyBase.php on line 82
```

**Comment by solodkiy** [comment]
fix: https://github.com/protocolbuffers/protobuf/pull/8703

**Comment by TeBoring** [comment]
This is an invalid use case. You have to check proto message for Any.
