### ISSUE TITLE
Deserialization of large message (> 64MB) randomly slient-fails. 

### ISSUE THREAD

**Issue by zayg** [protocolbuffers/protobuf#8866]
**What version of protobuf and what language are you using?**
Version: v3.0.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux 4.9

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 4.9

**What did you do?**

We are using c++ protocol buffer v3.0.2 for some structures' serialization and deserialization.
We are able to serialize a large PB message (~ 600MB) to a buffer and verfied the serialized size equals to PB.ByteSize(). 
Then when we try to deserialize the buffer back to the PB message. We are expecting the deserialization fails. But randomly, sometimes we see the deserialization succeeds, but the deserialized PB message only has a partial content with a ByteSize() == 64MB.

We wonder if there is anyone encountered this issue before. We would like to have a consistent behavior that all deserialization should fail (not succeed but return some wrong result).

serialization function we use: SerializeWithCachedSizesToArray(uint8 * target) const
deserialization function we use: ParseFromArray(const void * data, int size).

PB structure:
message response
{
    message A
    {
         required uint64 a = 1;
         repeated uint64 b = 2;
    }；
    repeated A c = 1;
}

**What did you expect to see**

We would like to have a consistent behavior that all deserialization should fail (not succeed but return some wrong result).

**What did you see instead?**

But randomly, sometimes we see the deserialization succeeds, but the deserialized PB message only has a partial content with a ByteSize() == 64MB.

**Comment by acozzette** [comment]
Let me close this issue since I already replied on the email [thread](https://groups.google.com/d/msgid/protobuf/ed13812d-d115-4c10-a3a6-d07066698050n%40googlegroups.com?utm_medium=email&utm_source=footer).
