### ISSUE TITLE
C++ generated code missing global scope operator

### ISSUE THREAD

**Issue by gabrbedd** [protocolbuffers/protobuf#8871]
**What version of protobuf and what language are you using?**
Version: master/v3.12.4 master/v.3.17.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Debian Testing

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
1. Create a protobuf file with one of the fields being of type ".google.protobuf.Any". Have the package be "com.google.*"
1. Compile to c++ (e.g. "protoc --cpp_out=. minimal_with_any.proto" with the attached file)
2. Inspect output ("minimal_with_any.pb.h")

**What did you expect to see**

I expected all references to `Any` be "::PROTOBUF_NAMESPACE_ID::Any" (because I used a leading '.' in the protobuf file)

**What did you see instead?**

The message class implementation used "PROTOBUF_NAMESPACE_ID::Any"

**Anything else we should know about your project / environment**

Because the package is "com.google.*", this will cause a compilation failure because the compiler will search in the local namespace (looking for "::com::google::protobuf::Any") and not the global namespace ("::google::protobuf::Any").

See attached example.
[minimal_with_any.proto.txt](https://github.com/protocolbuffers/protobuf/files/6970685/minimal_with_any.proto.txt)

**Comment by acozzette** [comment]
Thank you for the bug report. I would be happy to accept a pull request if you would like to send one with a fix.

**Comment by acozzette** [comment]
Actually let me close this since I saw just now that you commented on an existing internal bug about this.
