### ISSUE TITLE
Library/Tool for enforcing backward compatibility

### ISSUE THREAD

**Issue by hhkkxxx133** [protocolbuffers/protobuf#8872]
Hello,

Are there any libraries or tools that enforce backward compatibility of Protobuf schemas based on the [documentation](https://developers.google.com/protocol-buffers/docs/overview#updating)?

Thanks!

**Comment by acozzette** [comment]
I don't have any direct experience with it, but there is a tool called [Buf](https://docs.buf.build/) which helps enforce backward compatibility among many other things. I was also going to mention [ProtoTool](https://github.com/uber/prototool), but I see that project also now recommends migrating to Buf.
