### ISSUE TITLE
Which version supports proto2?

### ISSUE THREAD

**Issue by henryhu712** [protocolbuffers/protobuf#8876]
I need to compile proto2. Which version can I use for that?

**Comment by perezd** [comment]
All versions of protoc support syntax proto2 and syntax proto3. Also, for general questions like this please reach out through our mailing list or StackOverflow: https://groups.google.com/g/protobuf

**Comment by henryhu712** [comment]
Sorry, I need to compiler proto2 to ruby, but got the error:

# protoc -I ./def --ruby_out ./lib def/foo/wwdocument.proto
--ruby_out: foo/wwdocument.proto: Can only generate Ruby code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.

**Comment by perezd** [comment]
Oh ok, I didn't see any mention of Ruby. I believe the ruby bindings only support the proto3 runtime. If you need proto2 you'd need to use a different runtime, but that's likely not a viable option for you.
