### ISSUE TITLE
Add a SECURITY.md with contact info

### ISSUE THREAD

**Issue by zidingz** [protocolbuffers/protobuf#8877]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fowles** [comment]
Let me dig a bit and get back to you with a good contact

**Comment by fowles** [comment]
https://www.google.com/appserve/security-bugs/m2/new?report=%7B%22config_whitelisted%22%3A%22checked%22%2C%22continue_next%22%3A%22checked%22%2C%22config_googler%22%3A%22checked%22%7D

is the public contact for google.  I will adjust this issue to track adding a security.md file for this info
