### ISSUE TITLE
Aliases by which other modules are referred in generated module should be available to plug-ins

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#888]
(This is coming out of a work session the other day with @haberman and he may be able to better express or clarify the details of what I am asking here.)

For Python `protoc` plugins, it would be really good to be able to know the name by which another module is known in the namespace of the generated module. For example, when inserting code into a generated module that contains `from customer_package.customer_subpackage import customer_module as customer_package_customer_subpackage_customer_module`, it would be really nice for our plugin code to have access to a data structure that informs us "the generated class for the message that is the input type of the RPC method you are currently examining is defined in the `customer_package_customer_subpackage_customer_module` module".

@haberman thinks it would be a simple matter of making the `ModuleAlias` method available to plugins but I don't think I understand the problem enough to be confident.

**Comment by nathanielmanistaatgoogle** [comment]
Some more context on this: the problem that we're trying to solve is that we need to state in our generated code the Python class names of the input and output message types of RPCs defined in the `.proto`. If a message type is defined in the same `.proto` as the service for which we are generating RPC code, the name by which we refer to the Python class shouldn't be module-qualified, and if the message type is defined in a different `.proto` than the service for which we are generating RPC code, the name by which we refer to the Python class almost certainly should be something like `customer_package_customer_subpackage_customer_module.CustomerMessageClass`.

We have some logic for calculating message module names and class names (https://github.com/grpc/grpc/blob/f65d3c11023cd39b73c8832947889f656f2427a3/src/compiler/python_generator.cc#L245), but I think we should be eliminating that in favor of delegating from our plug-in code to core protobuf code.

cc @soltanmm

**Comment by haberman** [comment]
@anandolee any chance you could take a look at this?

I think this will mainly involve exposing as public functions ModuleAlias() and/or ModuleName() from https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc. They could be declared as static functions on google::protobuf::compiler::python::Generator.

Nathaniel needs to go from a filename (ie. google/protobuf/type.proto) to the Python module import alias (ie. google_protobuf_type__pb2, or whatever it is that is used as the module alias in generated code).

**Comment by nathanielmanistaatgoogle** [comment]
I think this is going to be necessary for gRPC soon; @anandolee might we be able to find time to discuss it this week?

**Comment by anandolee** [comment]
Sorry I missed the issue.
@nathanielmanistaatgoogle is it still needed? There's a TODO(protobuf team): Export `ModuleName`. So expose ModuleName and ModuleAlias would be good enough?

**Comment by nathanielmanistaatgoogle** [comment]
Yes, this is still needed. As indicated [here](https://github.com/grpc/grpc/blob/7d729b134e949be2503977180e3146df63678eaf/src/compiler/python_generator.cc#L101-L103) and [here](https://github.com/grpc/grpc/blob/7d729b134e949be2503977180e3146df63678eaf/src/compiler/python_generator.cc#L111-L113) `ModuleName` and `ModuleAlias` would be enough (we think, for now).

**Comment by elharo** [comment]
Is this still needed?

**Comment by nathanielmanistaatgoogle** [comment]
To the best of my knowledge: [yes](https://github.com/grpc/grpc/blob/36b0e06e2044fa1eb7b100f35ac2065345d46ab3/src/compiler/python_generator_helpers.h#L64-L66) and [yes](https://github.com/grpc/grpc/blob/36b0e06e2044fa1eb7b100f35ac2065345d46ab3/src/compiler/python_generator_helpers.h#L77-L79). On more of an architecture level: there's logic here that is [easy to get wrong](https://github.com/protocolbuffers/protobuf/issues/1491); ever since I came to understand the problem I've had the impression that the logic ought exist in one place, in Protocol Buffers, and that Protocol Buffers ought offer it for use by plug-in authors. As long as the principal expected use case of `protoc` plug-ins is something like "customers will write C++ code that generates Python code", the opportunity remains for Protocol Buffers to help those plug-ins handle module names and module aliases.

I may be out of touch with some of the details; @gnossen and/or @lidizheng may have a more up-to-date or more informed perspective on this.

**Comment by haberman** [comment]
This is now exposed through the functions in https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/python/helpers.h

(Though ideally we would rename that to `names.h` instead of `helpers.h` to match what other languages do).
