### ISSUE TITLE
 Plugin output is unparseable: hello go 2012

### ISSUE THREAD

**Issue by mafa1993** [protocolbuffers/protobuf#8882]
**What version of protobuf and what language are you using?**
Version: 3.17.3.
Language:go

**What operating system (Linux, Windows, ...) and version?**
windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
go version go1.15.5 windows/amd64

**What did you do?**
protoc -I . --go_out=. *.proto
--go_out: protoc-gen-go: Plugin output is unparseable: hello go 2012\n\350\216\267\345\217\226\345\210\260\347\232\204\345\206\205\345\256\271 goods.proto\032\010\010\003\020\021\030\003\"\000z\357\277\275\005\n

 protoc -I . --go_out=plugins=grpc:. goods.proto
--go_out: protoc-gen-go: Plugin output is unparseable: hello go 2012\n\350\216\267\345\217\226\345\210\260\347\232\204\345\206\205\345\256\271 goods.proto\022\n

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
Possibly a bug in the proto file? We'd need the source proto to reproduce this. Please add that.

**Comment by elharo** [comment]
comment and we'll take a look if you have a proto that reproduces this

**Comment by CCpro10** [comment]
I have a proto that reproduces this
