### ISSUE TITLE
Official support for lz4 stream

### ISSUE THREAD

**Issue by zhihaoy** [protocolbuffers/protobuf#8886]
**Describe the problem you are trying to solve.**

We want to read and write Protobuf transparently from/to an LZ4 compressed file.

**Describe the solution you'd like**

Include https://github.com/JohannesEbke/protobuf-zerocopy-compression along with the gzip_stream.h, keep them maintained.
Make sure that we are producing the portable LZ4 frame format.

**Comment by elharo** [comment]
feels like this could/should be handled simply by chaining streams, at least in Java. I'm not sure about other languages.
