### ISSUE TITLE
`JsonFormat` helper library for PHP

### ISSUE THREAD

**Issue by srth12** [protocolbuffers/protobuf#8890]
**What language does this apply to?** PHP
If it's a proto syntax change, is it for proto2 or proto3? proto3
If it's about generated code change, what programming language? PHP

**Describe the problem you are trying to solve.**
In PHP, on designing or extending an API, we often require responses in JSON format, but this language does not have `JsonFormat` to convert Protobuf object to JSON string, whereas other languages like Java does have this functionality in the `util` folder. This force as to manually create the JSON from the Protobuf object. For java, we could use the `JsonFormat` under the `util` folder  - https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java

**Describe the solution you'd like**
Expecting a util to support the conversion of Protobuf object to a JSON string. 

```
$json = $message->serializeToJsonString();
$message = $message->mergeFromJsonString($json);

//`JsonFormat` library is missing in PHP, but is available in
//other languages. I am expecting something like below. This
//will print JSON string.
print( JsonFormat.parse( $message ) );
```

Right now, it is impossible to print Protobuf object or convert it to JSON. We have to manually create the JSON in PHP, which is not the best way.

**Describe alternatives you've considered**
I have manually created the json using the Protobuf object, which is tiresome and error prone if the object is large or complex.

**Comment by haberman** [comment]
I don't understand what you are asking for.

In https://github.com/protocolbuffers/protobuf/issues/8846 I mentioned that these two lines work right now:

```php
$json = $message->serializeToJsonString();  // Serialize to JSON
$message = $message->mergeFromJsonString($json);  // Parse from JSON
```

So I am confused when you say:

> Right now, it is impossible to print Protobuf object or convert it to JSON.

The first line quoted above will do exactly that. What is wrong with this solution?

If you want it in a separate function, you can implement that manually:

```php
function JsonFormatParse($message) {
  return $message->serializeToJsonString();
}
```

**Comment by srth12** [comment]
@haberman Correct me if I am wrong, in my point of view serialised JSON string would not always be human readable(I mean the key/value inside the JSON). There could be encoded content in it. So, in order to get the original content, we have to either deserialise it or use a method like `JsonFormatParse`.

**Comment by haberman** [comment]
@srth12 The results of `$message->serializeToJsonString()` will generally be very readable. You should see readable key/value pairs for all of your proto fields.

The only exception is for bytes fields, which will be encoded using base64. But bytes fields are not expected to be readable anyway.

I would encourage you to try `$message->serializeToJsonString()` on your protos. It should be very easy to try. You can see if you like the output. If you have any specific concerns about it, feel free to post a follow-up.
