### ISSUE TITLE
Determining whether we are under address/thread sanitizer in port.h

### ISSUE THREAD

**Issue by mskurydin** [protocolbuffers/protobuf#8897]
Looking at the portability header, noticed we detect asan/tsan in the following way:

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/port.h#L146

```c++
#if defined(ADDRESS_SANITIZER) || defined(THREAD_SANITIZER) ||\
    defined(MEMORY_SANITIZER)
```

Why don't we use the standard defines automatically defined when sanitizers are enabled?

```
__SANITIZE_ADDRESS__
__SANITIZE_THREAD__
```

Are the library users expected to set THREAD_SANITIZER and MEMORY_SANITIZER explicitly?

**Comment by acozzette** [comment]
I suspect the existing setup is just a legacy that made sense internally at Google in the past but probably isn't correct today. I would be happy to merge a pull request if you would like to update that code to rely on the proper defines.
