### ISSUE TITLE
Skip store UnknownFieldSet

### ISSUE THREAD

**Issue by WangRuoFanbt** [protocolbuffers/protobuf#8898]
**What language does this apply to?**
c++ proto2 or proto 3

**Describe the problem you are trying to solve.**
I use pb structure to store Item information in the recommendation system. I found that UnknownFieldSet:: fields_ takes up a lot of memory，when i cache lots of Item information in memory.  It's because DiscardUnknownFields do not free the memory,  I can solve this problem by adding fields_.shrink_to_fit() to the UnknownFieldSet::ClearFallback function.

**Describe the solution you'd like**
I think it is a better solution to provide a switch that skips storing UnknownFieldSet when the SkipField method is parsed

![image](https://user-images.githubusercontent.com/89468951/130907436-1833e5cb-76c6-409b-94d7-a3266f23fad3.png)

**Comment by GoodGooGleINS** [comment]
Android Dump 1
<https://drive.google.com/file/d/11Wtako3sGJsf7lIOGhPoutpueCqDNtUZ/view?usp=drivesdk>

**Comment by WangRuoFanbt** [comment]
We use a common proto file in company which have more than 5000 fields, and most of then are useless in our model. We use proto cut to avoid memory usage by default values for useless fields. It is better for me to have a method which can avoid store the unknow field.

**Comment by TeBoring** [comment]
1) Having a proto with 5000 fields is strongly not recommended.
2) The decoder receives a field not recognized implies that the pruned proto is not inclusive enough. Seems to me the problem is in proto cut.
