### ISSUE TITLE
Faster Python Protobuf implementation?

### ISSUE THREAD

**Issue by danbosnichill** [protocolbuffers/protobuf#8899]
I tried creating ~100 protobuf messages (~20 fields) in Python.  No serialization.  Just creating the messages.  It takes me 4ms to create 100 messages.  This is very slow compared to other language implementations of protobufs. 

I'm curious if other implementations of proto are recommended.  I verified that we're using the cpp implementation of the proto library.

**What language does this apply to?**
Python.  Proto3.

**Describe the problem you are trying to solve.**
Latency.

**Describe the solution you'd like**
I'd like performance that is a similar order of magnitude as other languages.

**Describe alternatives you've considered**
Not using protobufs at all.
Not using protobufs for Python.
Not using Python.

**Additional context**

**Comment by fowles** [comment]
Obviously we cannot promise timelines, but this is something we have an active project for right now

**Comment by danbosnichill** [comment]
Any rough guess on timelines?  No promises.  We added more latency logging and python protobuf latency is a significant portion of our latency.

**Comment by haberman** [comment]
We're aiming to have something in prerelease in the next few months.

If you're feeling adventurous, you can try it out from my development branch now. It is not 100% complete, but most APIs are implemented and passing tests. The performance should give you a rough ballpark of what to expect.

To try it out:

1. install the Python protobuf package from the master branch of [protobuf/python](https://github.com/protocolbuffers/protobuf/tree/master/python).
2. compile your Python protos with a `protoc` built from the master branch of [protobuf](https://github.com/protocolbuffers/protobuf). You'll know you did this correctly if your `_pb2.py` files contain the string `AddSerializedFile`.
3. Build the C extension from my development branch using Bazel:

```shell
$ git clone --branch python https://github.com/haberman/upb.git
$ cd upb
$ bazel build -c opt python:message_ext python:api_implementation_ext
$ ls bazel-bin/python/google/protobuf/**/*.so
bazel-bin/python/google/protobuf/internal/_api_implementation.cpython-39-x86_64-linux-gnu.so
bazel-bin/python/google/protobuf/pyext/_message.cpython-39-x86_64-linux-gnu.so
```

Copy these `.so`'s to your PYTHONPATH, such that they can be loaded as `google.protobuf.internal._api_implementation` and `google.protobuf.pyext._message`, respectively.

If you have any feedback it could be useful in helping to gauge the performance improvement vs. the existing C++ extension. It could also help point to any places where we still need to optimize further.

**Comment by danbosnichill** [comment]
Awesome!  Great to hear!

**Comment by elharo** [comment]
actively underway and being tracked in other issues
