### ISSUE TITLE
Please include the license file in the Python package distribution

### ISSUE THREAD

**Issue by stevecj** [protocolbuffers/protobuf#8904]
We use a script to collect license files for all of the Python distribution packages we include with our product. protobuf is one of the few that does not bundle a license file into the distribution, so we can't collect it that way.

**Comment by f0ff886f** [comment]
Hello, I am checking the latest wheels for the `protobuf` Python package and none of them have a LICENSE in the dist-info.

Package: https://pypi.org/project/protobuf/#files

Opening any of those wheels does not have a LICENSE file inside.

This is the same issue as https://github.com/protocolbuffers/protobuf/issues/7536 it looks like too.
