### ISSUE TITLE
TimeUtils::GetCurrentTime() and fractions of second

### ISSUE THREAD

**Issue by aafemt** [protocolbuffers/protobuf#8930]
Version: 3.16
Language: C++
Linux
GCC 7.2

I do "message.mutable_timestamp->CopyFrom(util::TimeUtil::GetCurrentTime());"

I expect resulting timestamp field to contain current time up to milliseconds at least because Linux has gettimeofday() supporting milliseconds.
I see the time rounded to whole seconds.

In protobuf sources I see
```
void GetCurrentTime(int64* seconds, int32* nanos) {
  // TODO(xiaofeng): Improve the accuracy of this implementation (or just
  // remove this method from protobuf).
  *seconds = time(nullptr);
  *nanos = 0;
}
```

**Comment by elharo** [comment]
xiaofeng was right. This method shouldn't be here. However now it is and we're stuck with it. I'm not sure if changing the behavior now is likely to break any clients or not.

**Comment by cyuanli** [comment]
Could this be included in the documentation? Might avoid some confusion.
