### ISSUE TITLE
Optional Field Presence Check for Python in Protobuf3 (_pb2.py)

### ISSUE THREAD

**Issue by ssezgin-cpi** [protocolbuffers/protobuf#8933]
There's no way to tell the difference between a field being explicitly set to its default value vs. not having been set at all using the auto generated .pb2 files from the protobuf. (version 3.17.3)
I followed the recommended solution to include optional support(that by default not been supported) for proto3 that seems to only work for C++. (https://newbedev.com/how-to-define-an-optional-field-in-protobuf-3)

Details:

`import "google/protobuf/wrappers.proto";`

When `wrappers.proto` included to .proto file, protobuf compiler gives me the `has_value` method for each optional fields in protobuf messages only in the generated code for **C++** (.h .cc) but not for a **python** (_pb2.py). 

Is there any way to provide _optional field presence support_ to protobuf3  for Python?

Thanks
Sezer

**Comment by haberman** [comment]
The advice given in https://newbedev.com/how-to-define-an-optional-field-in-protobuf-3 is obsolete. Since protobuf 3.15.0, it has been possible to add the `optional` keyword to fields in proto3, which will give them explicit field presence.

```protobuf
// test.proto
syntax = "proto3";

message Foo {
  optional int32 bar = 1;
}
```

```python

import test_pb2

foo = test_pb2.Foo()
foo.HasField('bar')  # => returns false
foo.bar = 0
foo.HasField('bar')  # => returns true
```
