### ISSUE TITLE
Proto Java code generator generates uncompilable code when Java keywords are used as field names.

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#894]
See: https://github.com/google/protobuf-gradle-plugin/issues/46

**Comment by jimmidyson** [comment]
This is affecting me too. Any workaround or fix forthcoming?

**Comment by xfxyjwf** [comment]
I suggest updating your .proto definition and avoid any Java keywords. We can add a workaround in protoc, but what that does is simply replacing keywords like interface with interface_, and you certainly can come up with a better name than interface_.

**Comment by raould** [comment]
hi, I am wondering if there's a problematic use case of: what if you are given .proto files from some service you don't control?

**Comment by hnlq715** [comment]
I think this issue should be fixed.

**Comment by elharo** [comment]
I checked a couple of keywords (interface and enum) and they are now properly mangled and handled in the current release of protoc so I'm going to close this. If you discover any specific keywords that are still causing problems, please open a new bug with details, ideally exactly one bug per non-handled keyword.
