### ISSUE TITLE
Correct file extension for text format

### ISSUE THREAD

**Issue by 89z** [protocolbuffers/protobuf#8940]
Can someone please clarify the correct file extension for the Protobuf text format? I see `.pbtxt` used with Vim:

https://github.com/vim/vim/blob/ba02e472/runtime/filetype.vim#L1376-L1378

But Google for example, seems to use both `.pbtxt` and `.prototxt`:

- https://github.com/search?q=org:google+extension:pbtxt
- https://github.com/search?q=org:google+extension:prototxt

**Comment by elharo** [comment]
There aren't any hard and fast rules about this. .textproto is also used.
