### ISSUE TITLE
Define an interface (IParseableMessage) that allows custom parsing of a message from JSON

### ISSUE THREAD

**Issue by RonPeters** [protocolbuffers/protobuf#8952]
Language: C#
Proposal: Add an IParseableMessage interface to allow messages to parse their own JSON

I understand there is no built-in decimal type. That's fine, I guess. However, for compatibility reasons, I want to be able to load and save the JSON for my custom type as a straight decimal value, not an object.

Right now, a DecimalValue of 12345.6789 would be serialized like so (example from <https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-5.0>):
`myValue: { units = 12345, nanos = 678900000 }`
and therefore the JSON deserializer expects that object format.

I would like to serialize and deserialize this object instead as `myValue: 12345.6789`

The well-known types can do something similar because they are special-cased in JsonParser.cs. How do we extend to support custom types?

The JsonFormatter seems to allow marking a message class as IFormattable, which would allow me to output the desired value. What we're missing is an equivalent interface in the Parser that would allow arbitrary strings to be parsed into messages.

Adding an interface like IParseableMessage would be a very maintainable addition. JsonParser would use the interface to parse the JSON token and merge the fields. And JsonFormatter just continues to call IFormatter. Maybe even the well-known types would use the interface instead of being hardcoded in the parser.

FYI, as an attempted workaround, I created custom converters for System.Text.Json. Loading the object was successful, but it turns out using the system JSON parser doesn't work for `repeated` proto fields because they cannot be directly assigned to. `Add` or `AddRange` must be called. So all my arrays were empty, and this was not acceptable for my use case.

**Comment by RonPeters** [comment]
On further consideration, I think one interface that does parsing and formatting would be best. 
```
public interface IParseableMessage
{
    string MessageToJson();
    void MessageFromJson(string json);
}
```
    
What I can't figure out is how to get the JSON fragment as a string. The code has an internal tokenizer class, so can't pass the tokens out. How do I get the fragment as a string?

**Comment by RonPeters** [comment]
On even further consideration, i realized that full control over the JSON is unnecessary to solve the problem. I just need a single value.

So instead, I propose IStringValueSerializer and INumericValueSerializer interfaces. These will address the core need.

I'm experimenting on a branch now

**Comment by elharo** [comment]
The goal for the formats is interoperability, not customizability. It is an explicit non-goal to custom serializations.

**Comment by RonPeters** [comment]
I think this is an interoperability issue. Timestamp and Duration have custom JSON serializations because it makes sense. If protobuf implemented IEEE 754-2008, you would probably implement the same serialization I'm trying to accomplish.

I'm only making this proposal because there is no other way I've found to read in a decimal from JSON.
