### ISSUE TITLE
python_output arg control in py_proto_library

### ISSUE THREAD

**Issue by bhack** [protocolbuffers/protobuf#8975]
**What language does this apply to?**
python
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Describe the problem you are trying to solve.**
It seems that I cannot control `protoc` `python_output` arg in `py_proto_library` genrule
**Describe the solution you'd like**
I want to control `protoc` `python_output` args in `py_proto_library` genrule
**Describe alternatives you've considered**

**Additional context**
I want to use `setuptools` in edit/developer mode e.g. `pip install -e .` in a git checkout.
The problem is that I need to import the generated python files from source dir without creating too much problem in the version control so I need that the source dir with `.proto` and the generated python file with `bazel build` will  have a different names. In this way I can a create symbolic link on the generated python files back in the source without name conflicts.

See https://github.com/keras-team/tf-keras/issues/86

**Comment by elharo** [comment]
If I'm interpreting this correctly, you want to check generated files into version control? That's a little known antipattern. Do you still need this if you're not checking generated files into version control?

**Comment by bhack** [comment]
Not exactly, this is why I want to control the output directory like `python_output` `protoc` arg.

In the specific case in the source code we have `keras/portobuf` subfolder with only `.proto` fiiles.
If we cannot control the `python_output` arg in `bazel-bin/` we  will have the generated file under `keras/protobuf`.
So I cannot create e.g. a symbolic link between `bazel-bin/protobuf` and source `keras/protobuf` as the directory has the same name.
Instead If rename `keras/protobuf` as `keras/protobuf_defs` and control the `python_output` name as `keras/protobuf` then I can create a symbolic link  between `bazel-bin/protobuf` and source `keras/protobuf` and put `keras/protobuf` under `.gitignore` as we have still the source available under version control in `keras/protobuf_defs`.

It seems that I don't have any other plausible workaround as playing with `PYTHONPATH=bazel-bin/` will be ignored for the conflict with the `keras/protobuf` parent namespace between the source and the compiled one.
In `setuptools` [develompent/edit mode](https://setuptools.readthedocs.io/en/latest/userguide/development_mode.html) we work in source tree directly.

**Comment by deannagarcia** [comment]
Sorry for the long delay.

This seems like more of a problem in how you generate the protos. Are you still using a bazel genrule? If so, you can use that to copy the file to the place you want it to go. In general, it is dangerous to use generated files in version control because if something in the proto files change you will have an error that is hard to track down.
