### ISSUE TITLE
Protobuf is not updated to the latest version on vcpkg

### ISSUE THREAD

**Issue by aurelien-m** [protocolbuffers/protobuf#8976]
**What version of protobuf and what language are you using?**
Version: v3.15.8#4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2019 Professionnal

**What did you do?**
1. Downloaded `protobuf` using `vcpkg`.
2. Checking latest version after update:
```powershell
PS C:\dev\vcpkg> vcpkg list
protobuf:x64-windows                               3.15.8#4         Protocol Buffers - Google's data interchange format
protobuf:x86-windows                               3.15.8#4         Protocol Buffers - Google's data interchange format
```

**What did you expect to see**
I expected to see protobuf version 3.17.3.

**What did you see instead?**
It only goes up to 3.15.8.

**Anything else we should know about your project / environment**
Maybe I might be missing something :) is this normal?

**Comment by Sil3ntStorm** [comment]
vcpkg packages are updated by creating pull requests in the [microsoft/vcpkg](https://github.com/microsoft/vcpkg) repository. You may update protobuf yourself (by updating the port in the [ports](https://github.com/microsoft/vcpkg/tree/master/ports/protobuf) directory) and create a pull request in the vcpkg repository.
There appears to one in progress already: https://github.com/microsoft/vcpkg/pull/20208

**Comment by fowles** [comment]
Fixed by coryan in https://github.com/microsoft/vcpkg/pull/20208
