### ISSUE TITLE
Protobuf CI Windows tests are broken

### ISSUE THREAD

**Issue by mai93** [protocolbuffers/protobuf#8982]
Protobuf Python Windows tests are failing for [Bazel@Head](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2175#7f7d59f3-97ec-4fcf-8683-0cbf651307ed) as well as [Bazel 4.2.1](https://buildkite.com/bazel/protobuf/builds/3876#14ffed52-64c7-4036-9876-b3ea03629bb5).

Example error from logs:
```
Executing tests from //:py_descriptor_database_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\temp\Bazel.runfiles_bw5ytbl8\runfiles\com_google_protobuf\python\google\protobuf\internal\descriptor_database_test.py", line 43, in <module>
    from google.protobuf import unittest_pb2
ImportError: cannot import name 'unittest_pb2' from 'google.protobuf' (C:\python3\lib\site-packages\google\protobuf\__init__.py)
```

**Comment by meteorcloudy** [comment]
Ping, this is still failing on Bazel CI
https://buildkite.com/bazel/protobuf/builds/3994#_

**Comment by haberman** [comment]
Sorry for not giving a response on this bug sooner. I think the bug is obsolete now.
