### ISSUE TITLE
3.18.0 isn't compatible with Python 2 despite being installable

### ISSUE THREAD

**Issue by convoliution** [protocolbuffers/protobuf#8984]
**What version of protobuf and what language are you using?**
Version: v3.18.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
macOS Mojave 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
```bash
Python 2.7.18 (default, Mar 30 2021, 14:20:09) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
```

**What did you do?**
1. Activate a Python 2 environment
2. `pip install protobuf==3.18.0`
3. `python -c "from google.protobuf import descriptor"`

**What did you expect to see**
Either:
- `ERROR: Could not find a version that satisfies the requirement protobuf==3.18.0`
  in (2)
- no errors in (3)

**What did you see instead?**
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/convoliution/.pyenv/versions/dev2/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
    class DescriptorBase(metaclass=DescriptorMetaclass):
                                  ^
SyntaxError: invalid syntax
```
in (3)

**Comment by srenauld** [comment]
This breaks [nrfutil](https://www.nordicsemi.com/Products/Development-tools/nRF-Command-Line-Tools/Download#infotabs), rendering a major provider's CLI tool for DFU upgrades inoperable with no way to pin this dependency.

**Comment by odelrio** [comment]
https://github.com/googleapis/python-api-core depends on protobuf and this version breaks Python2.7-based builds. My workaround was to force v3.17.3 in `requirements.txt`.

**Comment by busunkim96** [comment]
@odelrio I just released a 1.x version of google-api-core that pins to protobuf <3.18.0. https://pypi.org/project/google-api-core/1.31.3/

**Comment by alanyee** [comment]
https://github.com/protocolbuffers/protobuf/issues/9045

**Comment by convoliution** [comment]
> Ok, I went ahead and yanked 3.18.0, so hopefully that should fix the problem. Users who still need Python 2 support can keep using 3.17.3.

—https://github.com/protocolbuffers/protobuf/issues/9045#issuecomment-943640239

Perfect!
