### ISSUE TITLE
Mismatch in latest versions for protoc and protobuf-java?

### ISSUE THREAD

**Issue by JimNero009** [protocolbuffers/protobuf#8990]
Hello,

I notice that protoc version 3.18.0 is released and available in maven: https://mvnrepository.com/artifact/com.google.protobuf/protoc/3.18.0

However, there does not appear to be a version 3.18.0 for protobuf-java: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

It appears that things generated via protoc 3.18.0 aren't compatible with protobuf-java 3.17.3 (the latest I can find), so I'm wondering if there is perhaps a publishing issue on your end and that there should be a 3.18.0 release also of the latter?

**Comment by perezd** [comment]
Checking on this now, sometimes it takes a while to propagate.

**Comment by perezd** [comment]
It's present here at actual maven:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/

I think that website just needs time to update.

**Comment by JimNero009** [comment]
Thanks for double checking that. We were earlier having issues with pulling it through to our internal artifact store, but seems that was related to general network problems that were happening at the time. I've just tried again now and can indeed pull 3.18.0 through, so agree with your assessment that the website is lagging behind reality a bit.

Apologies for the noise!
