### ISSUE TITLE
[KOTLIN] Null-safety for parseFrom()

### ISSUE THREAD

**Issue by Salzian** [protocolbuffers/protobuf#8996]
**What language does this apply to?**

Kotlin

**Describe the problem you are trying to solve.**

We ran into an issue, were we had NullPointerExceptions from trying to parse null values using `MyJavaProtoClass.parseFrom(someByteArray)` in Kotlin.

**Describe the solution you'd like**

Having a generated, null-safe function in Kotlin.

```kotlin
MyProtoClass.parseFrom(byteArray: ByteArray): MyProtoClass
``` 

**Describe alternatives you've considered**

I was thinking about implementing an extension function that finds the parseFrom function from the java class and wraps it in a try/catch, returning `null` in case of a NullPointerException. However, with this approach I'd either have to search on every call or somehow keep a reference to the function. A direct call through a generated Kotlin method would make more sense.

**Comment by Salzian** [comment]
Hey deannagarcia. Thanks for having a look at this issue.

It has been some time sine we encountered this issue, so let me try to refresh my memory.

IIRC, we had a service crash on us due to a NullPointerException. Something a Kotlin dev really does not like to see.

As it turns out, the parseFrom function does not check if the value passed in is null. Java/Kotlin interop also omits null check by default ([which I think was a horrible decision considering their argument of "better developer experience"](https://blog.jetbrains.com/kotlin/2014/10/making-platform-interop-even-smoother/)). So it would be nice to have some Kotlin wrapping around parseFrom that ensures me as a Kotlin dev the function will do what I expect it to do. 

I hope this makes the issue a bit more clear.

**Comment by deannagarcia** [comment]
What would you expect to happen if you called `parseFrom(null)`?

My instinct here is that we would want that call to fail loudly, so I'm a little worried about allowing it to succeed.

**Comment by Salzian** [comment]
fail loudly, yes. But it would be nice to know beforehand that I cannot plug a non-nullable value in.

Right now, the Kotlin support of protobuf is limited to Kotlin DSL builders. It would be nice if we could also add Nullability annotations. Like in this example to the parameters of all parseFrom functions. That way, my IDE and the Kotlin compiler will warn me if I try to plug a nullable value into the functions.

More info here: https://kotlinlang.org/docs/java-interop.html#nullability-annotations

**Comment by deannagarcia** [comment]
I've been discussing with the team and we agree null-safety is a good goal and we do have some implementation of this internally.

The main difficulty here is to add the annotations without adding more dependencies (we try to keep the number of proto dependencies as close to 0 as possible). If you have ideas to get around this I would be happy to work with you to get something implemented!

**Comment by Salzian** [comment]
As a pure Kotlin dev that doesn't touch Java that often, first-class support would be the nicest solution. However, given the comfort Java interop offers plus the resources required to fully add another language to protoc, I can see how this is a hard sell.

Would it be possible to add a Kotlin wrapper for `parseFrom`? This would at least give the developer facing API the required nullability support by disallowing nullable types. Then, no annotations are needed in the generated Java source, as the nullability enforcement would only be done in the Kotlin API.

That brings the question, is it possible to overload a Java method in Kotlin? Seems like this would require some weird partial class magic. I'm not too familiar with the interop, so I'm not sure if this would even be possible. Otherwise, the Kotlin wrapper function would need a new name, which would still give developers the ability to accidentally use the "unsafe" Java method in their Kotlin code.
