### ISSUE TITLE
PROTOBUF_FUTURE_MUST_USE_RESULT   undeclared identifier?

### ISSUE THREAD

**Issue by Gzzgz** [protocolbuffers/protobuf#8998]
error: use of undeclared identifier
      'PROTOBUF_FUTURE_MUST_USE_RESULT'
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Rasterization* release_rasterization();

**Comment by elharo** [comment]
Any chance you're using an older version of protobuf? This doesn't appear in current sources.

**Comment by jorgbrown** [comment]
Or perhaps you're somehow using some proto source that was generated with a previous version of proto... together with a more recent version of protocol buffer library sources?

**Comment by deannagarcia** [comment]
Closing due to no response. Feel free to open it back up if you're still seeing this error!
