### ISSUE TITLE
Java: Create UnknownFieldSet Builder lazily

### ISSUE THREAD

**Issue by chietti** [protocolbuffers/protobuf#9000]
The generated Java code always allocates a local **UnknownFieldSet.Builder** which adds up over time in object churn especially in small messages. Unknown fields are rather uncommon in our environment so in most cases this allocation is unnecessary.

Here the generated code of a custom _String_ message we use in our product (it shows up in our metrics which means that this is not covered by escape analysis):

![string proto](https://user-images.githubusercontent.com/64537681/133987869-da650726-5a11-41a6-92d5-65e3ca0710b9.png)

```
private String(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              ...
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
...
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
```

_unknownFields_ could be initialized with _null_ and only allocated in the _default_ case when an actual unknown field is received. In the _finally_ block a check for null would be necessary.

**Comment by elharo** [comment]
Can you elaborate on the metrics here? How much is this costing?

**Comment by chietti** [comment]
It is not a huge problem since we are talking about very short lived objects. Still we get a very large amount of such messages per minute (the 25 GB of the screenshot were allocated within 2 hours)

So in short: it is not really hurting us but it seemed like a good idea to me (the proposed change appears to be rather local and small)

**Comment by chietti** [comment]
Update: with the recent addition of the TreeMap in the builder the problem has become even worse.
On our small messages about 50% of allocated memory is now for the unknown field handling even if there are no unknown fields:

![image](https://user-images.githubusercontent.com/64537681/160079508-8a63f926-d5ba-4b9a-b873-605d15c2d702.png)

As mentioned in my first post this could be easily avoided by allocating the builder lazily only if it is needed (which is not the case most of the time)

**Comment by elharo** [comment]
I think I can lazily initialize the builder but that still leaves an UnknownFieldSet and its TreeMap in every message. Is fixing the builder alone worthwhile? Or would this need a more carefully implemented EmptyUnknownFieldSset obhect too?

**Comment by elharo** [comment]
This does make me wonder if it's worth making UnknownFieldSet use a Collections.emptyMap for the default instance rather than an empty TreeMap.

**Comment by elharo** [comment]
OK, probably not. The UnknownFieldSet default instance is effectively a singleton so it doesn't occupy much memory as the single instance is shared. That probably also answers my earlier question. Only the builder really matters here.

**Comment by chietti** [comment]
As I stated earlier: this is not huge deal most cases and in big messages it is rather insignificant (< 5% overhead). But in the specific case I added as a screenshot it sums up to ~50% because it is a very small and widely used message in our system. It also never changed since we introduced it, so I assume that the builder is only used to init the "unknownFields" member with the default instance.

I played around with the code recently and came up with something like this as a possible solution:

```
com.google.protobuf.UnknownFieldSet.Builder unknownFields = null;           // init with null
try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
...
            default: {
              // lazy init if necessary
              if (unknownFields == null) unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
...
      } finally {
        // check if exists and init to default instance if not
        this.unknownFields = unknownFields == null ? UnknownFieldSet.getDefaultInstance() : unknownFields.build();
        makeExtensionsImmutable();
      }
```

But I am not 100% sure that my reverse engineered assessment is correct....

**Comment by elharo** [comment]
It's not quite that simple. Some proto schemas create code that looks like this that might come into play with unknown enums:

```
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                int32ToEnumField_ = com.google.protobuf.MapField.newMapField(
                    Int32ToEnumFieldDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.ByteString bytes = input.readBytes();
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              int32ToEnumField__ = Int32ToEnumFieldDefaultEntryHolder.defaultEntry.getParserForType().parseFrom(bytes);
              if (foo.Test.TestMap.EnumValue.forNumber(int32ToEnumField__.getValue()) == null) {
                unknownFields.mergeLengthDelimitedField(4, bytes);
              } else {
                int32ToEnumField_.getMutableMap().put(
                    int32ToEnumField__.getKey(), int32ToEnumField__.getValue());
              }
              break;
            }
```

This happens before the default clause and also needs to be considered.

**Comment by elharo** [comment]
This code comes from map_field.cc and mutable_map_field.cc

**Comment by elharo** [comment]
FYI, I'm not sure this is going to be feasible. Adding the extra few lines of code to lazily initialize the unknown field set before use breaks Java's size limits on how much byte code a method can contain for some protos with many (1000+) enums. There might be a way around this without completely changing how protoc handles enums, but everything I've thought of so far seems likely to cost more than lazy initialization solves.

**Comment by chietti** [comment]
Thanks for the info. As I said in the beginning, it is not a big deal in most cases. Without knowing the details to consider it looked like a simple improvement to me. We could consider to add some special source code manipulation in the special case we have ("String" message only) since we know exactly what to deal with.

**Comment by elharo** [comment]
One idea: we might be able to create the TreeSet lazily but the UnknownFieldSet eagerly.
