### ISSUE TITLE
Bazel "build //..." broken

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#9007]
Running `bazel build //...` on a clean checkout:

ERROR: /usr/local/google/home/elharo/.cache/bazel/_bazel_elharo/828a9ad4e554dec702fc52a6a973f27b/external/rules_jvm_external/private/tools/java/rules/jvm/external/maven/BUILD:3:12: no such package '@rules_jvm_external_deps//': The repository '@rules_jvm_external_deps' could not be resolved and referenced by '@rules_jvm_external//private/tools/java/rules/jvm/external/maven:MavenPublisher'
ERROR: /usr/local/google/home/elharo/.cache/bazel/_bazel_elharo/828a9ad4e554dec702fc52a6a973f27b/external/rules_jvm_external/private/tools/java/rules/jvm/external/maven/BUILD:3:12: no such package '@rules_jvm_external_deps//': The repository '@rules_jvm_external_deps' could not be resolved and referenced by '@rules_jvm_external//private/tools/java/rules/jvm/external/maven:MavenPublisher'
ERROR: Analysis of target '//java/util:util_mvn.publish' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.373s
INFO: 0 processes.

some individual targets work

**Comment by deannagarcia** [comment]
Some bazel targets require specific setups that the average user might not have set-up, which is causing the failure.
