### ISSUE TITLE
Support for Custom Collections

### ISSUE THREAD

**Issue by shaileshpjoshi** [protocolbuffers/protobuf#9015]
**What language does this apply to?**
C#

If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Yes. C#

**Describe the problem you are trying to solve.**

We have Custom Collections that get used pervasively throughout the code.
These collections are primarily ReadOnlyDictionary, ReadOnlyHashSet, ReadOnlyList
that allow those to be created and marked as ReadOnly after which point they cannot
be modified. 

Those collections allow the objects to be immutable once they are created while being
passed around.

We could always repopulate these objects on Protobuf Serialization/Deserialization. But
that will incur additional cost.

**Describe the solution you'd like**

During the code generation, we would like to specify what collections to use instead of
standard collections.

**Describe alternatives you've considered**

I have also considered writing ReadOnly wrappers around the generated collections. But, haven't
found that solution to be full-proof.

**Additional context**

**Comment by jskeet** [comment]
This strikes me as a compatibility problem in the making, with different versions of protos being generated using different options etc. It would be very hard for the reflection library to handle all the possible variations involved. Fundamentally, protobuf messages are *not* immutable in the C# implementation - at some point we may well consider a record-based approach which would no doubt use immutable collections, but for the moment I don't think mixing and matching between the mutability of the current generated classes an immutable collections would help; it would just cause a lot of pain. (That's on top of the fact that we try to keep the number of compiler options to a minimum.)

Closing as I don't think we're going to do this; please add a comment with more information if you think we should revisit this.
