### ISSUE TITLE
[Question] What is CSharpProtoc?

### ISSUE THREAD

**Issue by GF-Huang** [protocolbuffers/protobuf#9035]
The online generator has 2 options about C#, I try the `CSharp` and it's output is good, easy and short.

But what is `CSharpProtoc`? Its output so complex. I can't search any informations about `CSharpProtoc` by google.

![image](https://user-images.githubusercontent.com/4510984/135373552-555019f7-09cf-4982-b23c-c4ac78ea59ab.png)

**Comment by elharo** [comment]
What's the URL? I don't recognize this. I'm not sure it's a Google product.

**Comment by GF-Huang** [comment]
Sorry, I post to the wrong repo..
