### ISSUE TITLE
Add support for nullable strings in autogenerated code in c#

### ISSUE THREAD

**Issue by stavros-georgiou-cy** [protocolbuffers/protobuf#9036]
**What language does this apply to?**
C#

If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Yes. C#

**Describe the problem you are trying to solve.**
Lets say we have a message:

```
message foo{
google.protobuf.StringValue a=1;
google.protobuf.BoolValue b=2;
}
```

This will generate class Foo.cs with 2 variables:
public **string** a
and 
public **bool?** b

The problem here is that when we are using BoolValue in the autogenerated file it will include the nullable ? but on strings this is not there.

**Describe the solution you'd like**
We would like to have on both variables the nullable ? so client can make for both variables the same checks (ex. if b != null)

**Describe alternatives you've considered**

**Additional context**

**Comment by deannagarcia** [comment]
Not all languages support the same nullable types that C# does. We generally like to keep languages consistent, and so diverging in this way isn't great. Additionally, it's not clear what null strings would be equivalent to in other languages (empty string? But what if that's the actual content?) So unfortunately we won't be supporting this in the near term.
