### ISSUE TITLE
package names that are C++ keywords generate code that does not compile

### ISSUE THREAD

**Issue by spikecurtis** [protocolbuffers/protobuf#9058]
**What version of protobuf and what language are you using?**
Version: 3.17.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc 9.3.0

**What did you do?**

We have .proto files with

```
syntax = "proto2";

package public;
```

When protoc compiles these, it outputs things like `namespace public` which is invalid because `public` is a reserved keyword in C++. 

**What did you expect to see**

Some option to override the package name for C++, a la `option java_package` or `option go_package`.

**What did you see instead?**

No override option, and the generated files fail to compile.

**Anything else we should know about your project / environment**

We started the project with Python, Go, and grpc-web/Javascript clients & servers, where "public" is not a reserved keyword.  Now, we want to add a C++ client, and renaming the package would break lots of existing code.

We have interest in trying to build a solution that could be upstreamed, e.g. `option cpp_package` or similar.  Would you be willing to advise us and accept a patch of this type?

**Comment by AlexanderVolkovTCS** [comment]
We have the same problem with the "package tinkoff.public.invest.api.contract.v1"
The best solution would be to do something like "option cpp_package"

**Comment by fowles** [comment]
This is a dup of #9058

**Comment by spikecurtis** [comment]
Ah, this is #9058 - @fowles did you mean to list some other ticket? I'd like to know the number to track

**Comment by AlexanderVolkovTCS** [comment]
@fowles
Ah, this is https://github.com/protocolbuffers/protobuf/issues/9058 - @fowles did you mean to list some other ticket? I'd like to know the number to track

**Comment by fowles** [comment]
clearly I was having a bad day...

**Comment by fowles** [comment]
#10491 is the real issue I am going to dedup a bunch of symptoms into as there is really an overarching problem
