### ISSUE TITLE
Generated kotlin code still throws "expected performance impact from inlining is insignificant" warnings

### ISSUE THREAD

**Issue by acruise** [protocolbuffers/protobuf#9063]
Contrary to the assertion in #8896 and [the changelog](https://github.com/protocolbuffers/protobuf/blob/99612d0885f2fe76400803ccdb425af46f29f481/CHANGES.txt#L133-L134), the protoc binary that's packaged in the jar with 3.18.1 doesn't seem to include this change.

Some evidence:

```
$ sha1sum <the file>
00b97c1fefac42a993e66cdd10760b7797b67cfb  $HOME/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.18.1/b97c1fefac42a993e66cdd10760b7797b67cfb/protoc-3.18.1-linux-x86_64.exe

$ strings $HOME/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.18.1/b97c1fefac42a993e66cdd10760b7797b67cfb/protoc-3.18.1-linux-x86_64.exe |grep -i suppresswarnings
@SuppressWarnings({"unused"})
@SuppressWarnings({"rawtypes"})
@java.lang.SuppressWarnings("unchecked")
@SuppressWarnings({"rawtypes"})
@SuppressWarnings({"rawtypes"})
@java.lang.SuppressWarnings({"unchecked", "fallthrough"})
@java.lang.SuppressWarnings({"ReferenceEquality"})
  @SuppressWarnings("deprecation")
  @SuppressWarnings("deprecation")
  @SuppressWarnings("deprecation")
    @SuppressWarnings("deprecation")
    @SuppressWarnings("deprecation")
@SuppressWarnings("deprecation")
            @SuppressWarnings("deprecation")
@SuppressWarnings("deprecation")

$ strings $HOME/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.18.1/b97c1fefac42a993e66cdd10760b7797b67cfb/protoc-3.18.1-linux-x86_64.exe |grep INLIN
template<> PROTOBUF_NOINLINE $classtype$* Arena::CreateMaybeMessage< $classtype$ >(Arena* arena) {
inline PROTOBUF_ALWAYS_INLINE void _internal_set_$name$(const std::string& value);
inline PROTOBUF_ALWAYS_INLINE bool _internal_$name$_donated() const;
inline PROTOBUF_ALWAYS_INLINE
inline PROTOBUF_ALWAYS_INLINE
```

I might be led to conclude that when the 3.18.1 jar was built, it mistakenly included older native binaries, but:

```
$ $HOME/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.18.1/b97c1fefac42a993e66cdd10760b7797b67cfb/protoc-3.18.1-linux-x86_64.exe --version
libprotoc 3.18.1
```

**What version of protobuf and what language are you using?**
Version: 3.18.1
Language: Java & Kotlin

**What operating system (Linux, Windows, ...) and version?**
Fedora 33

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 11, Gradle plugin 0.8.17

**What did you do?**
Generated Kotlin code from protobuf

**What did you expect to see**
Generated Kotlin code containing `@SuppressWarnings("NOTHING_TO_INLINE")`

**What did you see instead?**
Generated Kotlin code doesn't contain the `@SuppressWarnings`, so I get warnings ;)

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
Possible but are you certain you generated this with protoc 3.18.1? I ask because I recently wasted a day or so because I wasn't using the version of protoc I thought I was.

**Comment by deannagarcia** [comment]
I think I found the error, and it seems specific to non-lite string fields, I'm hoping my PR #9102 will fix it.

**Comment by deannagarcia** [comment]
Closing this due to no response, feel free to open it back up if you see the error again.
