### ISSUE TITLE
OrderedDict in output of json_format.MessageToDict is unnecessary for Python >= 3.7

### ISSUE THREAD

**Issue by adampauls** [protocolbuffers/protobuf#9064]
When serializing an `Any`, MessageToDict will [construct an OrderedDict](https://github.com/protocolbuffers/protobuf/blob/75eff10d81233d3d08ce5ded215e526c1fcace88/python/google/protobuf/json_format.py#L320) instead of a regular built-in `dict`. Built-in dicts preserve order as of python 3.7, so I believe this is unnecessary and would ideally be at least optional. Or perhaps for a later version of protoc, Python 3.7 could be required.

This is not a bug per se, but it is annoying. If you try to write the output of MessageToDict to yaml using PyYAML 6.0b1, it will not serialize properly. Instead of a simple dict like 

```yaml
'@type': type.googleapis.com/google.protobuf.StringValue
 value: Some value
```

you get
```yaml
 - - - '@type'
      - type.googleapis.com/google.protobuf.StringValue
    - - value
      - Some value
```

Arguably this is a bug in PyYAML (and there is [an issue](https://github.com/yaml/pyyaml/issues/315) tracking it), but it would be nice to simplify here anyways. 

**What version of protobuf and what language are you using?**
Version: 3.17.3
Language: Python 3.10

1. Create a Message containing an `Any` message.
2. Call `yaml.dump(json_format.MessageToDict(message))`

**What did you expect to see**
A nice dict like
```yaml
'@type': type.googleapis.com/google.protobuf.StringValue
 value: Some value
```

**What did you see instead?**
Something like 
```yaml
 - - - '@type'
      - type.googleapis.com/google.protobuf.StringValue
    - - value
      - Some value
```

It's easy to work around this behavior by recursively calling `dict` on the the output of `MessageToDict`.

**Comment by elharo** [comment]
Our minimum Python version is 3.4 right now so I don't think we can consider a change that requires 3.7 unless there's some sneaky Python way to make the code version dependent.

**Comment by adampauls** [comment]
Passing an optional flag is out of the question?

**Comment by adampauls** [comment]
I think for code-dependency you can check `platform.sys.version_info`, but that is more than a little gross.

**Comment by deannagarcia** [comment]
For now, we don't want to support optional flags for language versions because that will explode our support burden. Especially since this isn't a bug, we won't be supporting it.
