### ISSUE TITLE
Failed AnyTest.TestPackFromSerializationExceedsSizeLimit (unknown file: error: C++ exception with description "bad allocation" thrown in the test body)

### ISSUE THREAD

**Issue by jaygitdev** [protocolbuffers/protobuf#9080]
**What version of protobuf and what language are you using?**
Version: v3.1.8.
Language: Cmake

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Cmake commands in VS 2019 Command Prompt

**What did you do?**
1. Setup Cmake by following setup instructions in protobuf-3.18.1\cmake\README.md
2. Navigate to \protobuf-3.18.1\cmake\build\release in x64 Native Tools Command Prompt for VS 2019
3. Run test script "tests.exe --gtest_filter=AnyTest*"

**What did you expect to see**
I expected all tests to pass

**What did you see instead?**
Running main() from gmock_main.cc
Note: Google Test filter = AnyTest*
[==========] Running 9 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 9 tests from AnyTest
[ RUN      ] AnyTest.TestPackAndUnpack
[       OK ] AnyTest.TestPackAndUnpack (1 ms)
[ RUN      ] AnyTest.TestPackFromSerializationExceedsSizeLimit
unknown file: error: C++ exception with description "bad allocation" thrown in the test body.
[  FAILED  ] AnyTest.TestPackFromSerializationExceedsSizeLimit (0 ms)
[ RUN      ] AnyTest.TestUnpackWithTypeMismatch
[       OK ] AnyTest.TestUnpackWithTypeMismatch (1 ms)
[ RUN      ] AnyTest.TestPackAndUnpackAny
[       OK ] AnyTest.TestPackAndUnpackAny (0 ms)
[ RUN      ] AnyTest.TestPackWithCustomTypeUrl
[       OK ] AnyTest.TestPackWithCustomTypeUrl (0 ms)
[ RUN      ] AnyTest.TestIs
[       OK ] AnyTest.TestIs (0 ms)
[ RUN      ] AnyTest.MoveConstructor
[       OK ] AnyTest.MoveConstructor (0 ms)
[ RUN      ] AnyTest.MoveAssignment
[       OK ] AnyTest.MoveAssignment (0 ms)
[ RUN      ] AnyTest.Simple
[       OK ] AnyTest.Simple (0 ms)
[----------] 9 tests from AnyTest (4 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test suite ran. (6 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AnyTest.TestPackFromSerializationExceedsSizeLimit

 1 FAILED TEST

**Anything else we should know about your project / environment**
For setup, I followed this video (for reference):
https://www.youtube.com/watch?v=ZKMCe3DNXh4

**Comment by mfwerwolff** [comment]
I encountered the same failure on
Raspbian GNU/Linux 11 (bullseye)

Steps to reproduce:
- cloned repository
- typed 
`git submodule update --init third_party/googletest`
`git submodule update --init --recursive`
- i added 
`set(protobuf_ABSL_PROVIDER "module")`
`set(ABSL_ROOT_DIR ${CMAKE_SOURCE_DIR}/third_party/abseil-cpp)`
to the CMakeLists.txt right before the line (26 for me)
`option(protobuf_INSTALL "Install protobuf binaries and files" ON)`
- ran `cmake -DABSL_PROPAGATE_CXX_STD=ON ..` (in folder build)
- ran `cmake --build . --parallel 3`
- ran `ctest --verbose`

got:
2: [ RUN      ] AnyTest.TestPackFromSerializationExceedsSizeLimit
2: unknown file: Failure
2: C++ exception with description "basic_string::_M_replace_aux" thrown in the test body.
2: [  FAILED  ] AnyTest.TestPackFromSerializationExceedsSizeLimit (0 ms)
