### ISSUE TITLE
Poor performance to create and serialize message  containing map in Python

### ISSUE THREAD

**Issue by lilida** [protocolbuffers/protobuf#9091]
**What version of protobuf and what language are you using?**
Version: 3.18.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1039-aws x86_64)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.9

**What did you do?**
I have the following .proto defined:
```

//A message to hold a map
message FeatureMap {
  map<int32, double> idx_to_value = 1;
}

//The message holds variant inputs
message InputValue {
    message ListValue {
        repeated int64 i64=1;
        repeated int32 i32 = 2;
        repeated float f = 3;
        repeated FeatureMap featureMaps = 5;
    }
    message ReferenceValue {
        string name = 1;
        string field =2;
    }

    message MapValue {
        map<int32, int32> i32_to_i32 = 1;
    }

    oneof value {
        ListValue list = 1;
        int64 i = 2;
        float f = 3;
        bool b = 4;
        string s = 5;
        ReferenceValue ref = 6;
        FeatureMap featureMap = 7;
        MapValue map = 8;
        bytes bytes = 9;
    }
}

// Input
message NodeInput {
    string field = 1;
    InputValue value = 2;
}
```

Why I try to create messages from a python List[Dict[int,double]] to a list of FeatureMap, I see pretty bad performance
```
In [8]: %timeit vals = [FeatureMap(idx_to_value=features_dict) for features_dict in python_features]
12.3 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [9]: len(python_features)
Out[9]: 386

In [10]: len(python_features[0])
Out[10]: 57
```
It took 12 ms to create 386 FeatureMap messages each one contains a dictionary with 57 entries. Even worse, when I try to create a NodeInput message and assign the vals to its value.

```
In [14]: %timeit n=NodeInput(field="Inputs",value=InputValue(list=InputValue.ListValue(featureMaps=vals)))
22.3 ms ± 358 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So creating a new message is taking 22ms now! However, if I put the same data in bytes (using serialized result) here. 

```
In [22]: i_val = InputValue.ListValue(featureMaps=vals)

In [23]: i_val.ByteSize()
Out[23]: 307642

In [24]: bytesdata = i_val.SerializeToString()

In [25]: %timeit n=NodeInput(field="Inputs",value=InputValue(bytes=bytesdata))
14 µs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
So for the same amount of data, we are seeing 22 ms vs 14 µs.  That is a 1000 x difference

The serialization is also very slow

```
In [35]: %timeit i_val.SerializeToString()
7.34 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
**What did you expect to see**
The performance of create NodeInput with InputValue of a list of FeatureMap should be much better

**What did you see instead?**
It is very slow. 1000 times slower than passing bytes

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
```
In [32]: import google.protobuf as pb

In [33]: print(pb.__version__)
3.18.1

In [34]: pb.internal.api_implementation.Type()
Out[34]: 'cpp'
```

**Comment by haberman** [comment]
There is currently a new Python protobuf extension in development that should be released to early adopters in Q4. It should have much better performance.

More info here: https://github.com/protocolbuffers/protobuf/issues/8899#issuecomment-926289133

**Comment by lilida** [comment]
> There is currently a new Python protobuf extension in development that should be released to early adopters in Q4. It should have much better performance.
> 
> More info here: [#8899 (comment)](https://github.com/protocolbuffers/protobuf/issues/8899#issuecomment-926289133)

Any update on this new implementation?

**Comment by haberman** [comment]
> Any update on this new implementation?

You can build a binary wheel for it with:

```
$ git clone https://github.com/protocolbuffers/upb.git
$ cd upb
$ bazel build -c opt python:binary_wheel
```

We're aiming to release this in the next few months.

**Comment by lilida** [comment]
> > Any update on this new implementation?
> 
> You can build a binary wheel for it with:
> 
> ```
> $ git clone https://github.com/protocolbuffers/upb.git
> $ cd upb
> $ bazel build -c opt python:binary_wheel
> ```
> 
> We're aiming to release this in the next few months.

Does recent 3.20 release have contained the enhancement?

**Comment by fowles** [comment]
No, we plan on release this with 3.21

**Comment by anandolee** [comment]
Close it as 3.21 has been released. Feel free to reopen if the new version does not work
