### ISSUE TITLE
More helpful error message for plugins which don't support proto3 optionals

### ISSUE THREAD

**Issue by alecbarber** [protocolbuffers/protobuf#9111]
**What language does this apply to?**
proto3 compiler plugins

**Describe the problem you are trying to solve.**
When compiling a proto3 file containing `optional` fields with a plugin that doesn't support proto3 optionals, the following no output is produced (expected behaviour) with the following error message:
```
$ protoc --PLUGIN_out=. proto_with_optionals.proto
proto_with_optionals.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-PLUGIN hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--PLUGIN_out:
```
This error message is a bit confusing because it's not clear that compilation failed; for a user who doesn't know that this means that compilation failed it's not immediately obvious why no output was produced.

**Describe the solution you'd like**
An error message which looks something like this:
```
$ protoc --PLUGIN_out=. proto_with_optionals.proto
proto_with_optionals.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-PLUGIN hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
--PLUGIN_out: Failed: optional fields in proto3 files are not supported.
```

**Comment by fowles** [comment]
This feels like it will fit well with upcoming projects
