### ISSUE TITLE
protoc allows more than one field of oneof to be set in custom options

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#9125]
The `protoc` compiler attempts to reject custom options where oneof therein has more than one field set. However, it fails to do so when the fields are specified in two different option statements.

**What version of protobuf and what language are you using?**
Version: 3.18.1 (latest)
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
OS X 10.14.6 (Mojave)

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
Example source:
```proto
// test.proto
syntax = "proto2";

import "google/protobuf/descriptor.proto";

message Foo {
  oneof bar {
    string a = 1;
    string b = 2;
  }
}

extend google.protobuf.MessageOptions {
  optional Foo foo = 10000;
}

message Baz {
  option (foo).a = "abc";
  option (foo).b = "xyz";
}

```

Compile the above protoc:
```bash
protoc -o/dev/null test.proto 
```

**What did you expect to see**
I expected to see an error message along the lines of this:
```
test.proto:18:18: Error while parsing option value for "foo": Field "b" is specified along with field "a", another member of oneof "bar".
```

This is the error that would have been printed had I instead defined the option values like so:
```proto
  option (foo) = {
    a:"abc"
    b:"xyz"
  };
```

**What did you see instead?**

No error. The source is accepted and the resulting descriptor includes both values, though the former value (for field `a`) is discarded at runtime when the descriptor is unmarshaled.

**Anything else we should know about your project / environment**
No

**Comment by fowles** [comment]
Seems like it would be worth fixing this at some point
