### ISSUE TITLE
A plea in favor of resurrecting "group" encoding, for sub-messages, for serializer performance

### ISSUE THREAD

**Issue by mgravell** [protocolbuffers/protobuf#9134]
## Problem statement

Currently, sub-messages are always encoded with the length-delimited wire type, which means that in the scenario

``` proto
message A {
    B b = 1;
    // other things
}
message B {
    // other things
}
```

we write this as:

- field header: field 1, wire-type 2 (2=length prefixed)
- varint of the serialized byte-length of `b`
- that same number of raw bytes representing the payload of `b`

This is effective, but it has the problem that before we can start writing `b`, we need to know the *length* of `b`; this has problems; in particular, it requires us to *either*:

1. buffer the entire payload in-memory; write the buffer length as varint; copy the buffer out
2. serialize twice, once to a nul output
3. already know the length (see †)

This starts to get particularly gnarly for deep models, where A->B->C->D->E (or whatever, perhaps recursive, perhaps lists) - forcing multiple buffer operations or computations.

† In some API implementations, this may be simple because the lengths are computed while building the data model, but this is not universal between platforms and libraries.

When handling nested deep/recursive models there *are* some internal optimizations that can be done here so that the length of E isn't computed multiple times, but: fundamentally, this is a design that is not hugely compatible with zero-copy low latency output streaming.

## Proposal

Historically, there was another encoding variant available, that was used by the "groups" metaphor in the proto DSL. The "groups" metaphor has been removed from proto3 - which is fine, and I **do not** propose that we look at that. However, the *raw encoding* used by groups may still have utility.

Let's consider we had an opt-in mechanism in the .proto schema to enable this mode, which means that the serializer would use the group *encoding* (but still talking about a message in all ways):

we write this as:

- field header: field 1, wire-type 3 (3=start group, already exists, disavowed)
- payload of `b`
- field header: field 1, wire-type 4 (4=end group, already exists, disavowed)

Here, the "start group" and "end group" tokens are used as sentinels around the payload. This means we can now write in a purely forwards-way, with zero buffering and zero payload length pre-calculations, and true zero-copy writes in suitable scenarios. In terms of implementation impact, this comes down to:

### serialization

1. a different wire-type gets gets written in the field header
2. we *do not* compute or write the length before the message
3. we stomp the end-group sentinel *after* the message

### deserialization

1. when deserializing a group-encoded sub-message, we store or pass-onwards the expected "end group" field-header/field-number
2. after reading a field-header, in the "unexpected field" branch, we check whether it is an end-group that matches the number we stored in 1. immediately above; if so, we exit out as though we had reached the end of the length
3. assertions that we *have* correctly exited out from the group, i.e. we didn't EOF mid-group

The code for all of this should already exist in all implementations, precisely because it existed for groups historically.

It is my view that this should significantly help serialization performance, especially for large/deep models. Even when an overall payload length is required (for example, as an http content-length header), this should still help, by simplifying the work required in that operation, and limiting us to only *one* event of "write to a buffer, write the buffer length, copy the buffer" or "write to a nul stream and count what we would have written, write the length, write to the real stream" (depending on the implementation). We no longer have the problem of deep/recursive/repeated models forcing multiple length computations.

Emphasis I do not propose to resurrect the groups concept in terms of the object model; purely the encoding. This would also be strictly opt-in, presumably as a custom option or new DSL feature. Note that it is also perfectly possible for a deserializer to permit either encoding, if desired (similar to how a primitive list/array deserializer may allow packed and non-packed).

A minor payload size difference exists in that since the field number now gets written twice, large magnitude field numbers on sub-messages are marginally more expensive. A counterpoint to that is that large *payload size* sub-messages used to add a few extra bytes for the length prefix, which no longer applies. In the best case (small field number and small payload size) they are identical, each taking 2 bytes cumulatively.

One complication is that it makes the "skip unexpected field" a little more expensive than just jumping a number of bytes (as it requires parsing the sub-headers until the end-group), but not hugely so; and this code should already exist in all implementations *anyway*, since groups undeniably exist. Perhaps with that in mind, this is effectively "optimize for read" (default) vs "optimize for write" (opt-in).

I welcome thoughts.

**Comment by fowles** [comment]
Changes to the wire format have an incredibly high bar for happening because of the potential for data loss and long term risks associated with this kind of evolution.  We are currently focused on other optimization opportunities and won't be pursuing this for several years at the soonest.

**Comment by maloo** [comment]
@mgravell do you have some scenarios in mind that could be shown in benchmark.net? if so, people could look at it and try out different ideas... or maybe some unit tests in protobuf-net

**Comment by davidfowl** [comment]
@fowles Have you looked at @mgravell 's change in detail?

**Comment by mgravell** [comment]
(well yes bot, I'd absolutely love to keep this on the radar...)

**Comment by fowles** [comment]
It isn't exactly what you are asking for but it might serve your purpose.  Editions allows for explicitly specifying encoding on specific fields (or all fields in a file).  It does not support saying "this message is always encoded with groups".

https://protobuf.dev/editions/features/#message_encoding

Cheers!

**Comment by mgravell** [comment]
That... actually might be perfect, thanks @fowles ; I need to catch up on the status of "editions"

**Comment by ennerf** [comment]
Nice! @fowles is there a way to generate parsing code for both delimited & length-prefixed cases?

That'd allow migrating existing fields without breaking backwards compatibility with old serializers (similarly to how the `packed = true` flag worked).

**Comment by fowles** [comment]
@ennerf if it on our internal roadmap and plan, but likely won't get done until late 2024.

**Comment by ennerf** [comment]
Thanks. Great to know that this is on the roadmap.

**Comment by mgravell** [comment]
Is there an ETA on any of the tooling being available to play with here? I see that prototiller is mentioned as:

> It hasn’t been released yet, but is referenced throughout this topic.

So... presumably *today* this is purely speculative; for planning purposes, is there a timeline in mind for this feature? I'm also curious how things will actually happen here (in the future tense), i.e. does protiller *replace* protoc? can protoc now parse "editions" natively? And in particular, *how* this works, because I'd want to understand how *this* would be expressed in proto2:

``` proto
edition = "2023";

message Bar {
    optional int32 x = 1;
    repeated int32 y = 2;
}

message Foo {
  Bar bar = 1 [features.message_encoding = DELIMITED];
}
message Blap {
  Bar bar = 1 [features.message_encoding = DELIMITED];
}
```

and in particular: how many `group Bar` are in the final thing, and are they interchangeable; I think this is an important consideration, because it hugely impacts the semantics in terms of message resuse.

**Comment by mkruskal-google** [comment]
So I think there's 3 questions here, all of which we have concrete plans for:

1) **Group encoding for submessages** - edition 2023 removes the group syntax and allows you to specify DELIMITED encoding on any message field.  This is already released under an `--experimental_editions` flag, and we plan to ship it in all of our supported languages for the 26.0 release in a few months

2) **Allow parsing of both group delimited and length prefixed encoding for the same field**.  This will provide a migration path and a way for us to eventually remove length prefixed encoding.  We plan to implement this in 2024, and flip the default encoding to DELIMITED for edition 2024.  Actual removal of length-prefixed encoding will likely take many years while we wait for those changes to roll out everywhere

3) **Prototiller** - this is just a tool for programmatically modifying proto files.  It is orthogonal to protoc atm, but we might want to unify those at some point in the future.  We hope to release prototiller this year, and it can be used to help migrate your protos to editions.  It's won't be doing any special magic though, and you could also migrate them by hand fairly easily

**Comment by mgravell** [comment]
@mkruskal-google very clear and helpful response, thanks; also....

OMGOMGOMGOMGOMG

SO HAPPY RIGHT NOW
