### ISSUE TITLE
C# code generator can truncate enum names with mismatched prefix

### ISSUE THREAD

**Issue by astarche** [protocolbuffers/protobuf#9138]
**What version of protobuf and what language are you using?**
Version: v3.17
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10, Mac Catalina

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version

**What did you do?**

protoc an enum with a plural enum name and singular prefix. Simplified example:

```proto
enum Attributes {
  ATTRIBUTE_INVALID = 0;
  ATTRIBUTE_SIZE = 1;
  ATTRIBUTE_DISPOSITION = 2;
}
```

**What did you expect to see**

```csharp
  public enum Attributes {
    [pbr::OriginalName("ATTRIBUTE_INVALID")] AttributeInvalid = 0,
    [pbr::OriginalName("ATTRIBUTE_SIZE")] AttributeSize = 1,
    [pbr::OriginalName("ATTRIBUTE_DISPOSITION")] AttributeDisposition = 2,
  }
```

**What did you see instead?**

Note `Size` was truncated as `Ize` because [TryRemovePrefix ](https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/src/google/protobuf/compiler/csharp/csharp_helpers.cc#L227) matches `ATTRIBUTE_S` to the enum name `Attributes`.

```csharp
  public enum Attributes {
    [pbr::OriginalName("ATTRIBUTE_INVALID")] AttributeInvalid = 0,
    [pbr::OriginalName("ATTRIBUTE_SIZE")] Ize = 1,
    [pbr::OriginalName("ATTRIBUTE_DISPOSITION")] AttributeDisposition = 2,
  }
```

**Anything else we should know about your project / environment**

I realize that it's hard to change this. Can the prefix matching logic require that there be a trailing `_` after the match to avoid splitting words?

**Comment by krishnacx** [comment]
@astarche Any reason of why is this issue still open ?

**Comment by astarche** [comment]
I worked around this in my code because I was able to rename the enums in our `proto` files so that the prefix exactly matched the enum name. So it doesn't affect me now and I will know how to avoid the issue in the future. The issue in the C# protoc plugin still exists (I assume).

I'm OK with the issue being rejected if it's not considered worth fixing. It's not clear to me if fixing this is even allowed in `protoc`. The current behavior is "wrong" but fixing it could break client code.

**Comment by jskeet** [comment]
Fixing this would definitely be a breaking change. It's definitely *unpleasant* behavior... I'm not sure what the "right" fix would be even if we were willing to change it though. (This is one of those features which is really helpful when it does the right thing, and pretty awful when it doesn't.)

One way of fixing it in a non-breaking way would be to add a C#-specific option for either an enum as a whole ("don't perform prefix-removal") or a specific enum value (either suppression, or "use this name instead"). But given that this *appears* to rarely be a problem (this is the first time I've encountered it) I think it's probably best to close the issue with no further action for now.
