### ISSUE TITLE
commonjs no longer works in Node.js

### ISSUE THREAD

**Issue by joshkel** [protocolbuffers/protobuf#9152]
As a result of #8864, the generated commonjs `*_pb.js` files no longer work in a Node.js environment, because it [references `window`](https://github.com/protocolbuffers/protobuf/blob/v3.19.0/src/google/protobuf/compiler/js/js_generator.cc#L3637), which is undefined in Node.js.

**What version of protobuf and what language are you using?**
Version: 3.19.0
Language: JavaScript

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Node.js 14.18.1

**What did you do?**

1. Run protoc: `protoc --js_out=import_style=commonjs,binary:path/to/out/dir --proto_path=. *.proto`
2. Try to import and use the generated `*_pb.js` files.

**What did you expect to see**

Import and use without errors (just as prior to 3.19.0)

**What did you see instead?**

```
    ReferenceError: window is not defined

      14 | var jspb = require('google-protobuf');
      15 | var goog = jspb;
    > 16 | var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);
```

**Anything else we should know about your project / environment**

N/A

**Comment by nottmey** [comment]
We are forced to use 3.20.3 because of https://github.com/protocolbuffers/protobuf-javascript/issues/127,
but were able to workaround this via 
```
// @ts-ignore
globalThis.window = null;
// @ts-ignore
globalThis.self = null;
```
at the start of our `index.ts`.

**Comment by maelp** [comment]
@nottmey when I do this I have errors such as `Cannot read properties of null (reading 'Event')`, any idea where this might come from?

**Comment by nottmey** [comment]
@maelp sorry, no idea. Our generated files don't even contain any access on `Event` so I suspect it's an error that was previously hidden from you. (My fix also only applies to a Node.js environment. You don't wan't to do this where any code actually needs `window` or `self`.)

**Comment by nottmey** [comment]
@maelp yes that could be the case

**Comment by Aaron1011** [comment]
I was also forced to downgrade, but I was able to work around this issue by using `commonjs_strict` instead of `commonjs`:

```
protoc --js_out=import_style=commonjs_strict:. my_proto_file.proto
```

The generated code doesn't access `window`, allowing it work in strict mode.
