### ISSUE TITLE
core dump initializing at google::protobuf::internal::EpsCopyInputStream::ReadString

### ISSUE THREAD

**Issue by xianggao** [protocolbuffers/protobuf#9163]
**What version of protobuf and what language are you using?**
Version: 3.14.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
4.18.0-305.7.1.el8_4.x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 8.3.0

**What did you do?**
compile my code with -flto
run the help command, it core dumps

if I take out the -flto, the command runs fine

Stack Trace:

#0  0x0000000000000000 in ?? ()
**#1  0x00007f98ca2e90ff in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__n=25, __s=<optimized out>, this=0x202b420)
    at ./google/protobuf/parse_context.h:156
#2  google::protobuf::internal::EpsCopyInputStream::ReadString (this=0x7ffdf151f330, s=0x202b420, size=<optimized out>, ptr=<optimized out>)**
    at ./google/protobuf/parse_context.h:156
#3  google::protobuf::internal::EpsCopyInputStream::ReadString (s=0x202b420, size=<optimized out>, ptr=<optimized out>, this=0x7ffdf151f330)
    at ./google/protobuf/parse_context.h:153
#4  google::protobuf::internal::InlineGreedyStringParser (s=0x202b420, ptr=<optimized out>,
    ptr@entry=0x7f98ca40a041 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto+1> "\031google/protobuf/any.proto\022\017google.protobuf\"&\n\003Any\022\020
\n\btype_url\030\001 \001(\t\022\r\n\005value\030\002 \001(\fBv\n\023com.google.protobufB\bAnyProtoP\001Z,google.golang.org/protobuf/types/known/anypb\242\002\003GP
B\252\002\036Google.Protobuf.WellKnownTy"..., ctx=ctx@entry=0x7ffdf151f330) at google/protobuf/parse_context.cc:441
#5  0x00007f98ca34bd73 in google::protobuf::FileDescriptorProto::_InternalParse (this=0x7ffdf151f420,
    ptr=0x7f98ca40a041 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto+1> "\031google/protobuf/any.proto\022\017google.protobuf\"&\n\003Any\022\020\n\bty
pe_url\030\001 \001(\t\022\r\n\005value\030\002 \001(\fBv\n\023com.google.protobufB\bAnyProtoP\001Z,google.golang.org/protobuf/types/known/anypb\242\002\003GPB\252\
002\036Google.Protobuf.WellKnownTy"..., ctx=0x7ffdf151f330) at google/protobuf/descriptor.pb.cc:1853
#6  0x00007f98ca2e804d in google::protobuf::internal::MergeFromImpl<false> (input=..., msg=msg@entry=0x7ffdf151f420,
    parse_flags=parse_flags@entry=google::protobuf::MessageLite::kParse) at ./google/protobuf/parse_context.h:231
#7  0x00007f98ca2e6c04 in google::protobuf::MessageLite::ParseFrom<(google::protobuf::MessageLite::ParseFlags)1, google::protobuf::StringPiece> (input=...,
    this=0x7ffdf151f420) at /mnt/nfs1/apps/gcc/gcc-8.3.0/CentOS7/x86_64/.install/include/c++/8.3.0/bits/char_traits.h:287
#8  google::protobuf::MessageLite::ParseFromArray (this=this@entry=0x7f98ca40a040 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto>,
    data=data@entry=0x7f98ca40a040 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto>, size=size@entry=33731664) at google/protobuf/message_lite.cc:325
#9  0x00007f98ca333863 in google::protobuf::EncodedDescriptorDatabase::Add (this=0x202b450,
    encoded_file_descriptor=encoded_file_descriptor@entry=0x7f98ca40a040 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto>, size=33731664,
    size@entry=212) at google/protobuf/descriptor_database.cc:556
#10 0x00007f98ca3008ad in google::protobuf::DescriptorPool::InternalAddGeneratedFile (
    encoded_file_descriptor=0x7f98ca40a040 <descriptor_table_protodef_google_2fprotobuf_2fany_2eproto>, size=212) at google/protobuf/descriptor.cc:1371
#11 0x00007f98ca35b99f in google::protobuf::(anonymous namespace)::AddDescriptorsImpl (table=0x7f98ca681fc0 <descriptor_table_google_2fprotobuf_2fany_2eproto>)
    at google/protobuf/generated_message_reflection.cc:2492
#12 google::protobuf::internal::AddDescriptors (table=0x7f98ca681fc0 <descriptor_table_google_2fprotobuf_2fany_2eproto>)
    at google/protobuf/generated_message_reflection.cc:2523
#13 0x00007f98cf39d8ba in call_init.part () from /lib64/ld-linux-x86-64.so.2
#14 0x00007f98cf39d9ba in _dl_init () from /lib64/ld-linux-x86-64.so.2
#15 0x00007f98cf38efda in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#16 0x0000000000000001 in ?? ()
#17 0x00007ffdf15216ca in ?? ()
#18 0x0000000000000000 in ?? ()

**Comment by deannagarcia** [comment]
Closing due to no response. Feel free to reopen with more details if you're still having this problem!
