### ISSUE TITLE
Can't generate .NET 3.5 version for protobuf C#

### ISSUE THREAD

**Issue by Auhill** [protocolbuffers/protobuf#9174]
**What version of protobuf and what language are you using?**
Version: 3.19.1
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
I'm using the C# .net 3.5 version, and trying to generated a .net 3.5 protobuf dll. According to the readme.md in C# src folder, i added `net35` to  the `TargetFrameworks` config in Google.Protobuf.csproj, but the build failed with 300+ errors. And also the description in the readme.md maybe out-of-date. it said that the `TargetFrameworks` element appears twice in
the file (once in the first `PropertyGroup` element, and again in the second`PropertyGroup` element. But in the file, there are only one `PropertyGroup`

**Comment by jskeet** [comment]
We need to amend the README to remove any mention of .NET 3.5, basically. I recently evaluated how hard it would be to make the code compatible again, and there are *lots* of changes that are basically very hard to backport to .NET 3.5. Given the way everything has moved on, we don't intend to support .NET 3.5 I'm afraid. I'll create a PR to amend the README though.
