### ISSUE TITLE
.NET SDK 2.1 runtime End of Life warning

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#9189]
Not sure how serious this is, Trying to build the .Net code I get

```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.20 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.11 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.11.0-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

But Microsoft says about this release:

"This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as .NET 5.0 Runtime. See our support policy for more details."

**Comment by elharo** [comment]
FYI installing the EOL 2.1.0 version enabled the code to build successfully. This is all on a Mac.

**Comment by elharo** [comment]
Building at command line I get almost unreadable yellow text warning that

/usr/local/share/dotnet/sdk/5.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/elharo/protobuf/csharp/src/AddressBook/AddressBook.csproj]

**Comment by jtattermusch** [comment]
We should eventually migrate the build to .NET Core 3.1 or to .NET 5, but as long as the builds and tests are passing on the CI (AFAIK they are), this is not urgent.

**Comment by jtattermusch** [comment]
FTR https://github.com/protocolbuffers/protobuf/pull/7669, but the test targets still need to be moved to netcoreapp3.1 I think.

**Comment by jskeet** [comment]
Closing this now as the test projects were updated a little while ago.
