### ISSUE TITLE
.NET SDK version and Visual Studio

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#9190]
When I tried to load the csharp project into Visual Stdio 2019 I got not run tests and got errors that I needed to install .Net runtime 5.0.102 which maps to SDK 5.0.2. I had the more recent 5.0.11 installed but it didn't like that. Once I installed 5.0.2 it worked.

We should be able to build with a broader range of SDKs and certainly with the most recent one. 

I'm not a .NET expert so there may be context and clues I'm missing here.

**Comment by jskeet** [comment]
@elharo: I'd expect to be able to build with a newer version, certainly. Things have changed here fairly recently (we now require .NET 6 for a start) - are you happy for us to close this issue for now, and reopen with more information if something similar happens? (I don't think it would be productive to try to reproduce the exact situation you were in.)

**Comment by elharo** [comment]
One other piece of info: this was likely on a Mac. 

But sure, close for now if it works with the most recent SDK.

**Comment by jskeet** [comment]
(I'll clone this on my personal Mac Mini and try building on that, just from the command line - I'll reopen if that fails.)
