### ISSUE TITLE
PVS-Studio: few issues

### ISSUE THREAD

**Issue by AndreyKarpov** [protocolbuffers/protobuf#9191]
Article: [Protocol Buffers, a brutal protocol from Google, vs. PVS-Studio, a static code analyzer](https://pvs-studio.com/en/blog/posts/cpp/0882/).

Issues:

```
void SetPrimitiveVariables(....) {
  ....
  if (HasHasbit(descriptor)) {
    (*variables)["get_has_field_bit_message"] = ....;
    (*variables)["set_has_field_bit_message"] = ....;
    (*variables)["clear_has_field_bit_message"] = ....;
    ....
  } else {
    (*variables)["set_has_field_bit_message"] = "";      // <=
    (*variables)["set_has_field_bit_message"] = "";      // <=
    (*variables)["clear_has_field_bit_message"] = "";
  ....
}
```

PVS-Studio: [V519](https://pvs-studio.com/en/docs/warnings/v519/) [CWE-563] The variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 163, 164. java_primitive_field_lite.cc 164

```
ExpandWildcardsResult ExpandWildcards(
    const string& path, std::function<void(const string&)> consume) {
  ....
  HANDLE handle = ::FindFirstFileW(wpath.c_str(), &metadata);
  ....
  do {
    // Ignore ".", "..", and directories.
    if ((metadata.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == 0 &&
        kDot != metadata.cFileName && kDotDot != metadata.cFileName) {
      matched = ExpandWildcardsResult::kSuccess;
      string filename;
      if (!strings::wcs_to_utf8(metadata.cFileName, &filename)) {
        return ExpandWildcardsResult::kErrorOutputPathConversion;       // <=
      }
    ....
  } while (::FindNextFileW(handle, &metadata));
  FindClose(handle);
  return matched;
}
```

PVS-Studio: [V773](https://pvs-studio.com/en/docs/warnings/v773/) [CWE-401] The function was exited without releasing the 'handle' handle. A resource leak is possible. io_win32.cc 400

```
uint32_t GetFieldOffset(const FieldDescriptor* field) const {
  if (InRealOneof(field)) {
    size_t offset =
        static_cast<size_t>(field->containing_type()->field_count() +
                            field->containing_oneof()->index());
    return OffsetValue(offsets_[offset], field->type());
  } else {
    return GetFieldOffsetNonOneof(field);
  }
}
```

PVS-Studio: [V1028](https://pvs-studio.com/en/docs/warnings/v1028/) [CWE-190] Possible overflow. Consider casting operands, not the result. generated_message_reflection.h 140

```
bool KotlinGenerator::Generate(....)
{
  ....
  std::unique_ptr<FileGenerator> file_generator;
  if (file_options.generate_immutable_code) {
    file_generator.reset(
        new FileGenerator(file, file_options, /* immutable_api = */ true));
  }

  if (!file_generator->Validate(error)) {
    return false;
  }
  ....
}
```

PVS-Studio: [V614](https://pvs-studio.com/en/docs/warnings/v614/) [CWE-457] Potentially null smart pointer 'file_generator' used. java_kotlin_generator.cc 100

```
AlphaNum::AlphaNum(strings::Hex hex) {
  char *const end = &digits[kFastToBufferSize];
  char *writer = end;
  uint64 value = hex.value;
  uint64 width = hex.spec;
  // We accomplish minimum width by OR'ing in 0x10000 to the user's value,
  // where 0x10000 is the smallest hex number that is as wide as the user
  // asked for.
  uint64 mask = ((static_cast<uint64>(1) << (width - 1) * 4)) | value;
  ....
}
```

Is the parenthesis in the right spot? The analyzer does not like this code for two reasons:

* [V634](https://pvs-studio.com/en/docs/warnings/v634/) [CWE-783] The priority of the '*' operation is higher than that of the '<<' operation. It's possible that parentheses should be used in the expression. strutil.cc 1408
* [V592](https://pvs-studio.com/en/docs/warnings/v592/) The expression was enclosed by parentheses twice: ((expression)). One pair of parentheses is unnecessary or misprint is present. strutil.cc 1408

**Comment by acozzette** [comment]
Thank you for reporting these findings. We should be able to get fixes submitted soon.
