### ISSUE TITLE
@com_google_protobuf//:protobuf_java_util pulls in duplicate classes

### ISSUE THREAD

**Issue by eikemeier** [protocolbuffers/protobuf#9192]
**What version of protobuf and what language are you using?**
Version: v3.19.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS 10.15.7

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 17.0.1

**What did you do?**
This is a follow-up to #8925

    Check out https://github.com/eikemeier/proto-java2
    bazel run //:main

**What did you expect to see**
No duplicate resources.

**What did you see instead?**
Multiple copies of the same class, see output of the tool. `@com_google_protobuf//:protobuf_java_util` pulls in 
```
com_google_protobuf/libtimestamp_proto-speed.jar
com_google_protobuf/java/core/libcore.jar
com_google_protobuf/java/core/liblite_runtime_only.jar
com_google_protobuf/java/util/libutil.jar
com_google_protobuf/java/core/liblite.jar
```

See also the README in the repository above to reproduce.

**Anything else we should know about your project / environment**
Nothing special, Bazelisk or Bazel 5.0rc1 required.

**Comment by perezd** [comment]
hmmm, aside from the changes we made to bazel to remove the dupes, I am not sure what to do here. Looking at the graph, it's depending on standard java_library targets which shouldn't be causing duplication. Is there any more debugging you can help us with?

**Comment by eikemeier** [comment]
> Is there any more debugging you can help us with?

I'm not an expert, but `@com_google_protobuf//:protobuf_java` aka `@com_google_protobuf//java/core` doesn't depend on lite:

```
$ bazel query 'deps(@com_google_protobuf//java/core)' --output package | fgrep com_google_protobuf  
@com_google_protobuf//
@com_google_protobuf//java/core
```

while `@com_google_protobuf//java/util` does:
```
$ eik@Silver proto_java2 % bazel query 'deps(@com_google_protobuf//java/util)' --output package | fgrep com_google_protobuf  
@com_google_protobuf//
@com_google_protobuf//java/core
@com_google_protobuf//java/lite
@com_google_protobuf//java/util
```

and I guess it shouldn't.

**Comment by perezd** [comment]
Oh interesting, can you try a PR that removes it and see if it's OK? https://github.com/protocolbuffers/protobuf/blob/master/java/util/BUILD#L15

That is probably just an error.

**Comment by eikemeier** [comment]
> Oh interesting, can you try a PR that removes it and see if it's OK?

Indeed, it does, see the latest commit of https://github.com/eikemeier/proto-java2
