### ISSUE TITLE
Remove lastField and lastFieldNumber from UnknownFieldSet.cs

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#9194]
This looks like copy-pasta from the immutable Java code. However the mutable C# class doesn't need this optimization since it stores the fields in a Dictionary and TryGetValue is very close to O(1).

**Comment by jskeet** [comment]
I think I'd like to benchmark this before just removing it. (That shouldn't be too hard to do.) Given that `UnknownFieldSet` is only instantiated if there's at least one unknown field, the *cost* of keeping this is fairly small. (It's also only used in one piece of code, and only in a straightforward way.) I can imagine that with a repeated unknown field with a large element count, even the dictionary lookup could be significantly more expensive than the current code... but as always, I don't want to guess when we have benchmarking available :)

We already have a benchmark project, so this should be terribly hard to do.

**Comment by elharo** [comment]
My claim here is that benchmarks should have been done before adding this. It's an unnecessary optimization that makes the code large and more complex.
