### ISSUE TITLE
Does MessageDifferencer on proto messages handles map?

### ISSUE THREAD

**Issue by AadilHoda1** [protocolbuffers/protobuf#9198]
Hi,
I have to check the differences between the two protobuf messages for my program(C++). I am trying [MessageDifferencer::Compare][1] and [MessageDifferencer::Equals][2] for this.

I have a `map` field inside the proto message, which as we know is not guaranteed to be ordered. So, I want to know what is the `MessageDifferencer` take on this? Is anyone out of `Compare` or `Equals` functions have something to handle this case?

I mean that if the map is not ordered, how we can be sure that all of the elements in the first message are compared to the right elements in the second message? 

My message is something like:

    message foo
    {
        // some-fields
        map<string, int64> bar = 2;
        // more-fields
    }

Even if I am comparing the same message, it is showing *mismatch* and I can see in the *difference-report* that it is because the same field is not getting match against each other.

From the protobuf [documentation][3]:

    Wire format ordering and map iteration ordering of map values is undefined, so you cannot rely on your map items being in a particular order.

  [1]: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.message_differencer#MessageDifferencer.Compare.details
  [2]: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.message_differencer#MessageDifferencer.Equals.details
  [3]: https://developers.google.com/protocol-buffers/docs/proto3#maps

It is the first time I am attempting to create an issue, please let me know if there is something I missed in the issue formation.

Thankyou

**Comment by acozzette** [comment]
MessageDifferencer should be able to handle maps without any problems. If you can post an example of the problem then that would help to figure out what is going on. It might be that the difference report output is confusing even though the differencer is returning the right answer.

**Comment by AadilHoda1** [comment]
Hi @acozzette , thanks for attending my issue.

From my observation, in one of the case this ordering issue is showing up:
```
using google::protobuf::util::MessageDifferencer;

MessageDifferencer differencer;

std::string report;
differencer.ReportDifferencesToString(&report);
differencer.set_float_comparison(MessageDifferencer::FloatComparison::APPROXIMATE);
differencer.set_repeated_field_comparison(MessageDifferencer::RepeatedFieldComparison::AS_SMART_SET);
```

As you can see in the above piece of code, first I enabled the report, then configured the RepeatedFieldComparison = AS_SMART_SET and afterwards calling the Compare() method. For this specific case,  I am facing ordering issue.

Surprisingly, if I change the  AS_SMART_SET to AS_SET, this issue is not happening.

I will try to reproduce the issue and get back to you. Meanwhile let me know if you can think of something which can trigger this issue at hand.
