### ISSUE TITLE
Release binaries for darwin arm64 (M1 Macs) are missing from GitHub release

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#9200]
Since v3.17.3, the Maven central releases include files for M1 Macs ("osx_aarch_64"). However, the GitHub releases (even the latest one 10 days ago) do not.

Can the GH releases also include a ZIP file for this platform?

(Also see related issue #8428. Last comment there, for which there was not yet any reply, mentions this problem.)

**Comment by acozzette** [comment]
Thank you for the bug report. I just merged the fix, so this will be fixed going forward, starting with 3.20.

**Comment by maver1ck** [comment]
@acozzette Is there a chance you will add osx_aarch_64 binaries for older version of protoc to maven ?
Reason: https://issues.apache.org/jira/browse/FLINK-23230

**Comment by acozzette** [comment]
No, sorry but I don't think we will go back and provide binaries for older releases.
