### ISSUE TITLE
Why does protoc convert properties name with 'Url' suffix to 'URL' when converting Objective-C?

### ISSUE THREAD

**Issue by Cedric-jc** [protocolbuffers/protobuf#9204]
eg
```
message User
{
string logoUrl
}

@interface User
@property logoURL;
@end
```

I see that you have a `kUpperSegmentsList` in `src/google/protobuf/compiler/objectivec/objectivec_helpers.cc`. What is the use of this? It causes the url in the property name to be converted to all-caps.

**Comment by elharo** [comment]
For questions or troubleshooting, please use the protobuf mailing list: https://groups.google.com/forum/#!forum/protobuf
