### ISSUE TITLE
Two-way map/conversion between two proto messages

### ISSUE THREAD

**Issue by Your-Eye** [protocolbuffers/protobuf#9220]
**What language does this apply to?**
A proto syntax addition (can apply to both proto2 or proto3, but for proto2 it's better).

**Describe the problem you are trying to solve.**

I'm trying to have a cross-platform way to automate conversions between two proto messages.
Very useful for refactorings, API changes, etc. When you want to create a better proto message without breaking existing APIs.

**Describe the solution you'd like**

Using proto annotations (like [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate)) to map between an old field to a new field (using full field paths, possibly enabling some general conversion methods, like int->string, or string->enum, etc.)

Each language would need to implement its usage separately.

**Describe alternatives you've considered**

Creating a conversion per-language separately. There are libraries I found that do it for Java. But that's not cross-language, and wouldn't work for API-clients using another language.

**Additional context**

***Requirements:***

1. The two messages could have a completely different structure (e.g., sub messages, field renames, different enum types)
2. I'd want the conversion to be automatically created for all languages (e.g., by a build rule). If it's not possible, support for both Java and C++ is mandatory.

***Example:***
Conversion between A and B:

```
message A {
  optional string name = 1;
  optional Enum type = 2;
  enum Enum {
    TYPE1 = 1,
    TYPE2 = 2,
  }
}

message B {
  message Metadata {
      optional string name = 1;
  }
  optional Metadata metadata = 1;

  message SemanticData {
      optional SimilarEnum type = 1;
      enum SimilarEnum {
        TYPE_RENAMED1 = 1,
        TYPE_RENAMED_REVALUED2 = 5,
      }
  }
  optional SemanticData value = 2;  
}
```

**Comment by elharo** [comment]
This would make a nice third party utility. It doesn't seem like it's something that needs to be in core.

**Comment by Your-Eye** [comment]
Is there a way to suggest/request something like this as a third party utility?

**Comment by elharo** [comment]
I doubt the core team has the resources to prioritize or create such a thing right now. However this could be done by anybody with the interest. Not every good idea needs to b done in this repo.

**Comment by deannagarcia** [comment]
While the proto team won't be able to support this effort directly, I'm going to reopen the issue and tag it with help wanted in order to preserve this idea and hopefully get some help implementing from contributors.

**Comment by elharo** [comment]
If this is implemented would this belong in this repo or a separate project? That is, would it need to be in core?

**Comment by sumitraturi1982** [comment]
Hi, @Your-Eye I am having a similar requirement as stated above by you. Wanted to know how you were able to achieve it ? Thanks.

**Comment by sumitraturi1982** [comment]
> @Your-Eye Hi.. If you know any utility specific to C++, kindly let me know. Either way, appreciate you replying. Thanks !!

**Comment by fowles** [comment]
I think this is better off outside the core of protobuf.  If I were designing a thing like this, I would probably use custom options to define the interfaces and then publish a spec for how each language must interpret those options.  Then you can handle them on a per language basis either with a code generator plugin or with reflection.

**Comment by Your-Eye** [comment]
@fowles So what is the correct location to request this? How can the idea be preserved so a third party can implement this as @deannagarcia suggested?

**Comment by fowles** [comment]
I don't know that there is a good clearing house for ideas for OSS projects that people wish existed.
