### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Salompas** [protocolbuffers/protobuf#9221]
In the Python installation page (https://github.com/protocolbuffers/protobuf/tree/master/python), there is a link on step 2 to this page: https://packaging.python.org/en/latest/installing/#setup-for-installing-packages. The link leads to a non-existent page:

<img width="586" alt="Screen Shot 2021-11-14 at 3 22 35 PM" src="https://user-images.githubusercontent.com/7663115/141697295-2aa0c847-803c-4238-9bff-95facd8ce4fd.png">

**Comment by barbacbd** [comment]
I went back through the web archives and found now sources for the link listed. I was trying to compare it to what is there now. I am not sure if this bullet point wants to point to [installing packages](https://packaging.python.org/en/latest/tutorials/installing-packages/), [installing python from source](https://www.python.org/downloads/source/), or something else. If I get an answer, I can make this change very quickly.
