### ISSUE TITLE
Missing fields error in pyext/descriptor_containers.cc after turning on use_fast_cpp_protos

### ISSUE THREAD

**Issue by JuichungKuoKodiak** [protocolbuffers/protobuf#9225]
**What version of protobuf and what language are you using?**
Version: protobuf-3.19.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
python3.7
I also use bazel for building

**What did you do?**
1. enable the flag: use_fast_cpp_protos=true
2. compile some library that uses protobuf

**What did you expect to see**
no error

**What did you see instead?**

`external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:447:1: error: missing field 'sq_inplace_concat' initializer [-Werror,-Wmissing-field-initializers]
};
^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:542:44: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "get", (PyCFunction)Get, METH_VARARGS, },
                                           ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:543:45: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "keys", (PyCFunction)Keys, METH_NOARGS, },
                                            ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:544:49: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "values", (PyCFunction)Values, METH_NOARGS, },
                                                ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:545:47: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "items", (PyCFunction)Items, METH_NOARGS, },
                                              ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:546:53: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "iterkeys", (PyCFunction)IterKeys, METH_NOARGS, },
                                                    ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:547:57: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "itervalues", (PyCFunction)IterValues, METH_NOARGS, },
                                                        ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:548:55: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "iteritems", (PyCFunction)IterItems, METH_NOARGS, },
                                                      ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:549:8: error: missing field 'ml_meth' initializer [-Werror,-Wmissing-field-initializers]
  {NULL}
       ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:592:1: error: missing field 'tp_is_gc' initializer [-Werror,-Wmissing-field-initializers]
};
^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:713:42: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "index", (PyCFunction)Index, METH_O, },
                                         ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:714:42: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "count", (PyCFunction)Count, METH_O, },
                                         ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:715:44: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "append", (PyCFunction)Append, METH_O, },
                                           ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:716:57: error: missing field 'ml_doc' initializer [-Werror,-Wmissing-field-initializers]
  { "__reversed__", (PyCFunction)Reversed, METH_NOARGS, },
                                                        ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:717:8: error: missing field 'ml_meth' initializer [-Werror,-Wmissing-field-initializers]
  {NULL}
       ^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:729:1: error: missing field 'sq_inplace_concat' initializer [-Werror,-Wmissing-field-initializers]
};
^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:777:1: error: missing field 'tp_is_gc' initializer [-Werror,-Wmissing-field-initializers]
};
^
external/com_google_protobuf/python/google/protobuf/pyext/descriptor_containers.cc:920:1: error: missing field 'tp_is_gc' initializer [-Werror,-Wmissing-field-initializers]
};
`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by haberman** [comment]
This is obsolete; the C extension is rewritten to use upb instead: https://protobuf.dev/news/2022-05-06/#python-updates
