### ISSUE TITLE
Generated descriptor set reserved field range end off by one

### ISSUE THREAD

**Issue by jroper** [protocolbuffers/protobuf#9237]
If I generate a descriptor (with `--descriptor_set_out`) for the following:

```protobuf
message Foo {
  reserved 1, 5 to 6;
}
```

I get the following (formatted as JSON for readability):

```json
{
  "name": "Foo",
  "reserved_range": [
    { "start": 1, "end": 2 },
    { "start": 5, "end": 7 },
  ]
}
```

What I expect to get is this:

```json
{
  "name": "Foo",
  "reserved_range": [
    { "start": 1, "end": 1 },
    { "start": 5, "end": 6 },
  ]
}
```

For enum reserved ranges, I do get the expected output, this is only for message reserved ranges.

protoc version:

```
$ protoc --version
libprotoc 3.19.1
```

**Comment by elharo** [comment]
Just a guess but it looks to me like the ranges are half-open: that is start is inclusive but end is  exclusive. This pattern has always confused me to, but it is common in programming for reasons I've never really followed. E.g. in Java String indices.

**Comment by jroper** [comment]
If that's the case, then there is a bug in the ranges for enums, because as I stated above, it's the opposite, the range is inclusive. One of them has to have a bug, they can't both have conflicting behaviour and be right. Which one will you accept? Should I raise another bug for enums?

**Comment by elharo** [comment]
That certainly sounds confusing and less than ideal. I'm not sure it's a bug though. They are two different things and could perhaps have been implemented at different times by different programmers who didn't realize they were being inconsistent with each other. Is one of them contrary to the specification? Or can you show a failing test that demonstrates a bug?

**Comment by jroper** [comment]
I don't think there is a specification for the output of the file descriptors, except that it's supposed to be a binary representation of what's in the protobuf files. And what's in the protobuf files is an inclusive range.

I mean, are you telling me that in:

```protobuf
enum Foo {
  reserved 1 to 2;
}
```

the `reserved 1 to 2` should be interpreted and compile to something different to the the `reserved 1 to 2` in here::

```protobuf
message Foo {
  reserved 1 to 2;
}
```

Because that's exactly what's happening. And I'm dumbfounded that that could be considered anything other than a bug.

**Comment by elharo** [comment]
If there isn't a specification for the output of the file descriptors, that's a doc bug we should fix. 

And yes, I am saying that it is not a bug if enums and messages define the reserved ranges differently. It's not good that they do, and if anyone had noticed this way back when this was first created it certainly wouldn't have been done this way. However it's not wrong, just surprising and confusing. I doubt we could change the behavior now without breaking backwards compatibility.

**Comment by acozzette** [comment]
I'm going to mark this closed since it appears to have been fixed. There are comments in descriptor.proto indicating which fields are meant to be inclusive and which are exclusive.
