### ISSUE TITLE
C# Server Generator - Add option to declare method abstract virtual instead of providing default implementation

### ISSUE THREAD

**Issue by Blackclaws** [protocolbuffers/protobuf#9241]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
I want to get a compiler error in case my service definition file is changed in a way that an endpoint is added that is not implemented

**Describe the solution you'd like**
I'd like an option to pass to protoc that creates the server side stubs with abstract virtual functions instead of virtual functions whose body throws an unimplemented exception. The current solution only throws on an actual call, the proposed solution would fail compilation.

**Describe alternatives you've considered**
None

**Additional context**
While in general its good form to add unit tests that cover any new endpoints that are added and those would of course fail on a non-implemented service, its also a nice and easy reminder that some method simple wasn't implemented if there doesn't exist a default implementation that fails anyway.

**Comment by Blackclaws** [comment]
I'm a bit confused on which is actually the right repository for this request. It seems the client generator lives here but the server generator might be over in https://github.com/grpc/grpc in the Grpc.Tools package.

**Comment by deannagarcia** [comment]
I think this is a GRPC question, closing this report.
