### ISSUE TITLE
How to pass -fPIE to protobuf build to generate the .a and .so

### ISSUE THREAD

**Issue by gopalak** [protocolbuffers/protobuf#9247]
I am trying to build 3.17.0 version from src and want to pass -fPIE option to the build process
passing it as 👍🏽 ./configure CXXFLAGS=-fPIE 
doesnt seem to be passing it to the actual make flags

Is there a way to pass extra C and CPP flags via configure to the build process

**Comment by elharo** [comment]
For questions or troubleshooting, please see the protobuf mailing list: https://groups.google.com/forum/#!forum/protobuf
