### ISSUE TITLE
Problem with protobuf 3.9.2

### ISSUE THREAD

**Issue by Wistar1308** [protocolbuffers/protobuf#9249]
**What version of protobuf and what language are you using?**
Version: 3.9.2
Language: C++

**What operating system (Linux, Windows, ...) and version?** 
windows 10 
![image](https://user-images.githubusercontent.com/41325962/143221502-b36c0914-3415-44e2-a92d-0dc11fc8b526.png)

**What runtime / compiler are you using (e.g., python version or gcc version)** msvc 2019

Recently I tried tensorflow 2.5 c++. It required protobuf-3.9.2. 
When I run code that used protobuf, I got errors like the following image.
![image](https://user-images.githubusercontent.com/41325962/143220459-d8690389-a595-49ed-954e-9cb8fb087dde.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
This looks like a tensorflow issue (and I do wish they'd upgrade their protobuf version). Have you tried reporting it there?
