### ISSUE TITLE
Concatenate Protobuf messages

### ISSUE THREAD

**Issue by Krzmbrzl** [protocolbuffers/protobuf#9257]
I was reading the [Encoding specs](https://developers.google.com/protocol-buffers/docs/encoding#structure) and noticed that protobuf-messages are not self-delimiting (the parser has no way of knowing where the message ends and will simply read until EOF/EOS is encountered). Furthermore, a protobuf message seems to essentially only be a sequence of key-value pairs where each key-value pair is self-delimiting.

This got me wondering whether it was possible to comply concatenate Protobuf messages in a single stream in a way that the decoding side would treat the entire stream as a single message.

Consider for instance this message definition:
```protobuf
syntax = "proto3";

message MainMessage {
	int32 myNumber = 1;
    string myString = 2;
	bytes myBlob = 3;
	uint32 myOtherNumber = 4;
}

message Part {
	bytes myBlob = 3;
	uint32 myOtherNumber = 4;
}
```

Now create a message object of type `MainMessage` and set it's `myNumber` and `myString` fields only. Also create a `Part` message and set its `myBlob` and `myOtherNumber` fields.
Could we now serialize the `MainMessage` object and append to the serialized output the serialized version of the `Part` message such that a deserialization as `MainMessage` would have all four fields populated (as previously set on the two separate message instances)?

**Comment by fowles** [comment]
In short, yes.  Protobuf messages are designed to have concatenation of the wire format be equivalent to `Merge` of the parsed format.  `repeated` fields will concatenate, singular fields will overwrite older values when present.  This can be used in many different ways.

**Comment by Krzmbrzl** [comment]
Great, that's just what I need. Thanks! :)

**Comment by willfaught** [comment]
@fowles I'm curious, when is that useful?

**Comment by Krzmbrzl** [comment]
@willfaught in my case, I am using this to essentially re-serialize messages only partly. So I have a client that expects a full message but the server sends that same message to multiple clients. However, for each client some of the fields of said message will vary ever so slightly. If the server was just using a single protobuf message object and change the required fields using the standard methods, it would have to re-encode the entire message into wire-format every time (involving copying of non-trivially sized byte strings).
Using the trick above, I can make sure that the parts of the message that are subject to change are at the end of the message and then I only have to remember where the constant part of the message ends and just overwrite the rest with a re-serialized partial message that only contains the changed fields.

This could also have been solved by splitting the message in the first place, but from a client's point of view, it is semantically much more logical to have all that information grouped together as a single message.

**Comment by willfaught** [comment]
@Krzmbrzl The protobuf doc [says](https://developers.google.com/protocol-buffers/docs/encoding#optional) it's sometimes useful to concatenate wire format data when you don't have the schema:

>The effect of these rules is that parsing the concatenation of two encoded messages produces exactly the same result as if you had parsed the two messages separately and merged the resulting objects. [...] This property is occasionally useful, as it allows you to merge two messages even if you do not know their types.

 Have you ever found or observed such a case/need?

**Comment by Krzmbrzl** [comment]
No, so far I never needed that :shrug:
