### ISSUE TITLE
`-Wreserved-identifier` warnings

### ISSUE THREAD

**Issue by tolikzinovyev** [protocolbuffers/protobuf#9258]
**What version of protobuf and what language are you using?**
Version: v3.19.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Arch Linux (fully updated)

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 13

**What did you do?**
Compile a C++ program that uses generated protobuf code.

**What did you expect to see**
Compilation is without warnings.

**What did you see instead?**
Compiling a .cc file that includes a generated protobuf .h file results in the following kind of warnings (errors in my case).
```
error: identifier '_InternalParse' is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier]
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
```

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
Are you still seeing this error with newer releases? Can you provide a small reproduction example?

**Comment by fowles** [comment]
I can save time here, we would definitely still be seeing this
