### ISSUE TITLE
Enum definition with a value "VALUES" generates code that fails to compile in Java

### ISSUE THREAD

**Issue by dcitron** [protocolbuffers/protobuf#9264]
Given the following proto file:

```syntax = "proto3";

package test;

enum TestEnum {
  VALUES = 0;
}
```

the generated Java code fails to compile:

```variable VALUES is already defined...```

This is because the generated enum java code includes the following generated declaration (in order to implement `valueOf()`)

```private static final TestEnum[] VALUES = values();```

A solution might be to use more unlikely internal names in the generated code (perhaps with a prefix, etc.).

**Comment by olim7t** [comment]
I also ran into that. Java is my main target so I was able to change the value name immediately, but this could be more serious if it is not detected until later.

I agree that something like `__VALUES` in the generated code would be less likely to clash. The protobuf compiler could also detect that special name and warn the user.

**Comment by dcitron** [comment]
I looked into this more and perhaps all that's required is to change `VALUES` to something like `__VALUES__` at the following two places:

https://github.com/protocolbuffers/protobuf/blob/2ef1b7a9fad4c02c7e85aeac4819fb44406b2a17/src/google/protobuf/compiler/java/enum.cc#L309-L313

https://github.com/protocolbuffers/protobuf/blob/2ef1b7a9fad4c02c7e85aeac4819fb44406b2a17/src/google/protobuf/compiler/java/enum.cc#L355-L358

There could be more to it than that, though -- should I work up a PR?

**Comment by googleberg** [comment]
Ideally, that would be the case. Unfortunately, there are cases within Google that use reflection to get to some of these fields by name. I need to verify that changing this name doesn't break anything.

**Comment by dcitron** [comment]
Sounds good, @googleberg! I re-built it locally after changing `VALUES` to `__VALUES__` in those two places, and the fix is working for me (and allowing me to proceed), but I understand that it might be a risky change.

Hopefully the Google code is calling `valueOf()` and not directly accessing the private static final `VALUES` field, but anything is possible.

**Comment by gwenshap** [comment]
FWIW, we also ran into this issue.
Hopefully Google can validate these soon and the simple fix can be merged and released.

**Comment by dcitron** [comment]
Hi, @googleberg ! Is there any update on this? Thank you!

**Comment by googleberg** [comment]
Unfortunately, we have not yet had the bandwidth to do the prerequisite cleanup to do the fix.

**Comment by froque** [comment]
This also fails to compile 
```
package test;

enum TestEnum {
  FOO = 1;
  FOO_VALUE = 2;
}
```

```
❯ javac --class-path protobuf-java-4.28.3.jar Test.java  
Test.java:55: error: variable FOO_VALUE is already defined in enum TestEnum
    public static final int FOO_VALUE = 1;
                            ^
Test.java:83: error: incompatible types: int cannot be converted to TestEnum
        case 2: return FOO_VALUE;
                       ^
2 errors
```
Seems related to 
https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/java/full/enum.cc#L147-L149

Would a new option/config to fix these be acceptable ?
