### ISSUE TITLE
stdout/stderr/stdin are allowed fields in C++ despite being reserved by the C specification

### ISSUE THREAD

**Issue by deeglaze** [protocolbuffers/protobuf#9265]
These names are specified as #define'd symbols, and as such should not be compiled to. When a libc implements these macros as, say _REENT->stdin_ the way newlib does, then the clash causes compilation errors rather than simply rebinding a name.

Version: v3.5.0
Language: C++

I expect these fields to be rejected by the compiler, renamed and not aliased as they currently are, or at least provide a warning that can be made into an error with an appropriate flag. I know the Google codebase couldn't handle introducing an error or removing a symbol definition right now, but it'd be nice to selectively be stricter in a proto_library_cc build rule.

**Comment by elharo** [comment]
Do you have a test case? Might be just my limited C++ knowledge here, but it's not obvious to me what exactly you're suggesting.

**Comment by deeglaze** [comment]
test.proto:
```proto
package test;
message Test {
  string stdout;
}
```

test.cc
```c++
#include <stdio.h>

#include "test.proto.h"

int main() {
  test::Test t;
  t.set_stdout("awkward...");
  fprintf(stdout, "oh, uh, %s\n", t.stdout());
  return 0;
}
```
When you build this in a toolchain whose libc has the (specified as implementation-defined macro) stdout symbol #defined as something that doesn't work as valid syntax for `string test::Test::stdout() const;` then we have a compilation error. One such libc is newlib, which is used in cygwin, many embedded devices, and the Asylo project I'm a part of (https://github.com/google/asylo).

**Comment by not-a-user** [comment]
I can confirm this is an issue with musl (alpine) which has `#define stdout (stdout)` in its [stdio.h](https://git.musl-libc.org/cgit/musl/tree/include/stdio.h).

**Comment by deeglaze** [comment]
Given the language has gone into a different versioning scheme, can we reassess if the next major release can reserve these field names?
