### ISSUE TITLE
the result of serializing same data is not same in Javascript and golang

### ISSUE THREAD

**Issue by kysee** [protocolbuffers/protobuf#9268]
**What version of protobuf and what language are you using?**
Version:   
```bash
$ protoc --version
libprotoc 3.17.3
```
- javascrip(node module)   "google-protobuf": "^3.18.0-rc.2",
- golang pakcate1:   google.golang.org/protobuf v1.27.1
- golang pakcate2:   github.com/gogo/protobuf v1.3.2

Language: 
Javascript and Golang

**What operating system (Linux, Windows, ...) and version?**
OSX Monterey 12.0.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
- Javascript environment  
  - node v14.17.6
  - npm module "google-protobuf": "^3.18.0-rc.2",
- Golang environment
  - go1.16.2 darwin/amd64
  - google.golang.org/protobuf v1.27.1
  - github.com/gogo/protobuf v1.3.2

**What did you do?**

1. Write `prototest.proto` for a proto3 message including int64 type.
```proto
syntax = "proto3";
package tmp
option go_package = "my_project_path/tmp";

message Int64Msg {
  int64 i64 = 1;
}
```

2. Generate go source code
`protoc --go_out=$(GOPATH)/src -I./proto/ prototest.proto`

3. Run the following code in go.    

```go
func TestInt64(t *testing.T) {
	st := &Int64Msg{}
	st.I64 = 1638243612614987000

	bz, err := proto.Marshal(st)
	require.NoError(t, err)
	fmt.Printf("%x\n", bz0))
}
```

**Output is `08f899e0cbacbc8dde16`**

4. Generate javascript source code
`protoc --js_out=import_style=commonjs,binary:./proto -I./proto/ prototest.proto`

5. Run the following code in javascript.      

```js
import Proto from '../proto/prototest_pb.cjs';

let st = new Proto.Int64Msg();
st.setI64(1638243612614987000);
let bz = st.serializeBinary();
console.debug(Buffer.from(bz).toString('hex'));
```

**Output is `08809ae0cbacbc8dde16`**

6. golang's output (`08f899e0cbacbc8dde16`) is not equal to Javascript's output(`08809ae0cbacbc8dde16`)

**What did you expect to see**

The result of serializing the same data should be the same in both javascript and golang.

**What did you see instead?**

As mentioned,   
**golang's output (`08f899e0cbacbc8dde16`) is not equal to Javascript's output(`08809ae0cbacbc8dde16`)**

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
Generally proto serialization is not deterministic at the byte level, not even within the same language binding, much less between languages. As long as the protos decode the same given the same schema, there's no bug here.

**Comment by kysee** [comment]
@elharo 

When the serialized in javascript is deserialized in golang, is the same value deserialized ?
In my case, it is not true.

the result of javascript (`08809ae0cbacbc8dde16`) is deserialized as `1638243612614987008` not `1638243612614987000`.

isn't it bug?

**Comment by elharo** [comment]
OK, that makes a little more sense. That said I think there's something inobvious happening here that has nothing to do with protos. What happens when you go JavaScript to JavaScript? JavaScript (not protos but JavaScript itself) represents all numbers as IEEE 754 doubles which do not have as much precision in the integer part as a true int64 or long. I suspect your long value is rounded because JavaScript cannot precisely represent 1638243612614987000.

See https://stackoverflow.com/questions/5353388/javascript-parsing-int64

**Comment by kysee** [comment]
@elharo 

Thank you!!!

I have one more question.

Why `jspb.BinaryConstants.TWO_TO_63` is `0x7fffffffffffffff`, which is larger than `2^53-1`
In the protobuf lib for javascript ("google-protobuf": "^3.18.0-rc.2"), 
the function writeInt64() allows integer less than this value to be serialized.
