### ISSUE TITLE
Unexpected Behavior from EnumValueToPascalCase

### ISSUE THREAD

**Issue by mchristen-astranis** [protocolbuffers/protobuf#9272]
The EnumValueToPascalCase function shouldn't generate the same output for XYZ_1_1 as XYZ_11. I wanted to raise as an issue before implementing the fix because a possible response may be that pascal case isn't well-defined, so we can't expect language-specific code generators to implement this behavior. Let me know what you think and I'd be happy to make some tests and the change.

I believe the expected functionality should look something like this:

XYZ_11 -> XYZ11
XYZ_11_A -> XYZ_11A
XYZ_1_1 -> XYZ1_1

Basically the functional change should be:
* If the 2 characters surrounding an underscore or set of underscores is numeric, then we should keep the underscore.

Example error:

> Enum name XYZ_11 has the same name as XYZ_1_1 if you ignore case and strip
> out the enum name prefix (if any). This is error-prone and can lead to
> undefined behavior. Please avoid doing this. If you are using allow_alias,
> please assign the same numeric value to both enums.

[Reference to the function under question](https://github.com/protocolbuffers/protobuf/blob/3e1967e10be786062ccd026275866c3aef487eba/src/google/protobuf/descriptor.cc#L424-L443)

**Comment by elharo** [comment]
Would any such change be backwards compatible?

**Comment by mchristen-astranis** [comment]
Interesting question, what do you mean by backwards compatible? As far as I could tell from the source, it seems that this is just used internally for validation that 2 enum names aren't identical, not used for generation of code, etc. The outcome of this change would basically be that things that used to be seen as identical no longer are; which seems backwards compatible in the sense that we won't be disallowing things that weren't before. Does that make sense, or am I missing something?

**Comment by mchristen-astranis** [comment]
@elharo, thoughts on the next best steps to make some progress on this?

**Comment by mchristen-astranis** [comment]
ping / how can I get some more feedback on this?

**Comment by elharo** [comment]
If you're allowing new things, they need to be uniformly allowed across all languages, not just C++.

**Comment by mchristen-astranis** [comment]
Yep, that would be necessary.

In regards to the larger consideration of how to handle generated enum names (not stripping out all `_`), if I make a diff that does this and it maintains backwards compatiblity am I likely to get it accepted, or is the approach / feature ask fundamentally opposed?

**Comment by elharo** [comment]
At this point, the proposal is not clear enough to decide. We need a detailed, language independent description of what this means for the names of protobuf fields. This needs to consider the .proto schema text format and the binary wire format.

**Comment by CuteLeon** [comment]
Check out this alternative for integrating .proto files into C# projects: protobuf-net.BuildTools. It offers automatic compilation and consistent naming：

https://github.com/protocolbuffers/protobuf/issues/22278#issuecomment-2986326116
