### ISSUE TITLE
protoc --decode_raw --show_default_values

### ISSUE THREAD

**Issue by daveyostcom** [protocolbuffers/protobuf#9279]
**Describe the problem you are trying to solve.**
When looking at a text display of a protobuf that is unfamiliar, it is a considerable cognitive load to have to take into account the fields that are not shown because they have default values and therefore are not present in the binary representation.

**Describe the solution you'd like**
A command-line option to `protoc` to afford the desired behavior.

**Describe alternatives you've considered**
Asking my IDE vendor to implement this feature somehow in their debugger.
https://youtrack.jetbrains.com/issue/IDEA-284076

**Comment by deannagarcia** [comment]
What do you mean "text display"? The best way to inspect a protobuf is to read the `.proto` file.

**Comment by daveyostcom** [comment]
I mean text that results from using the `protoc` command to dump an actual message that was sent.

This is not about seeing all of the field names in the schema, which is declared in a `.proto` file;  it is about seeing the names and values of all fields, present or implied, in an actual sent message.

I am suggesting an option to `protoc` that might be called `--show-default-values`.  For example,
```
protoc --decode_raw --show-default-values < message.bin
```
would show the name and value of a `"port"` field that is `0` as
```
    "port": 0
```
instead of not mentioning the field.

**Comment by fowles** [comment]
We don't have any plans to add this right now

**Comment by daveyostcom** [comment]
It is normal for issue trackers to have a way to preserve requests for enhancement, which are, of course not yet planned.  The fact that at new feature request is not yet planned seems an odd reason to close it.
