### ISSUE TITLE
DynamicMessage.java does not support explicit presence

### ISSUE THREAD

**Issue by rayokota** [protocolbuffers/protobuf#9285]
**What version of protobuf and what language are you using?**
Version: master
Language: Java

**What did you do?**
I called `DynamicMessage.setField(FieldDescriptor field, Object value)` with a default value on a FieldDescriptor with explicit presence and expected it to be set.

**What did you see instead?**

The default value was not set due to this code:
```
      } else if (field.getFile().getSyntax() == Descriptors.FileDescriptor.Syntax.PROTO3) {
        if (!field.isRepeated()
            && field.getJavaType() != FieldDescriptor.JavaType.MESSAGE
            && value.equals(field.getDefaultValue())) {
          // In proto3, setting a field to its default value is equivalent to clearing the field.
          fields.clearField(field);
          return this;
        }
      }
```

Perhaps there needs to be a check of `field.getProto().isProto3Optional()` before calling `clearField()`

**Comment by elharo** [comment]
I'm not 100% sure but I think this is working as intended. "Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types. For example, don't have a boolean that switches on some behaviour when set to false if you don't want that behaviour to also happen by default. Also note that if a scalar message field is set to its default, the value will not be serialized on the wire."

Can you point to language in the spec that suggests the code shouldn't be behaving as you observe? Or produce a test case that gives clearly wrong output? I don't think there's a setField method in DynamicMessage

**Comment by acozzette** [comment]
This sounds like a real bug to me. I think the key thing is that this field is explicitly marked `optional`, so it should not behave the same as usual proto3 singular fields: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by rayokota** [comment]
Yes, I believe this is a real bug that is blocking our use of the `optional` keyword that was added back to Protobuf v3 in release 3.15.   Here is the language indicating that this is a bug:

```
- Explicit presence discipline:
   -  Explicitly set values are always serialized, including default values.
```
from https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by rayokota** [comment]
This is not a bug after all.  The optional FieldDescriptor that I had created by hand with was not in a synthetic oneof.

**Comment by elharo** [comment]
Thanks for closing the loop on this.
