### ISSUE TITLE
Wrong relative path in protobuf_generate

### ISSUE THREAD

**Issue by git-ruttmann** [protocolbuffers/protobuf#9290]
https://github.com/protocolbuffers/protobuf/blob/88384c99ec9621c0054e24bc80cab7709f550357/cmake/protobuf-config.cmake.in#L111
Under Windows, the command `file(RELATIVE_PATH _rel_dir ${DIR} ${_abs_dir})` returns an absolute path when the include path and the file path are on different drives.
Sample: called with $DIR=C:/include_path and _abs_dir = D:/current_repository/, the command returns an absolute path without any `..` in it.
The `_is_in_parent_folder` is set to false and therefore a wrong directory is accepted as relative path.
The result is that `_rel_dir` points to an absolute path which generates bad pathnames line 126

Tested with cmake 3.21

**Comment by elharo** [comment]
Thanks. What's the impact of this? What fails?

**Comment by git-ruttmann** [comment]
If you translate a file `D:/current_repository/package/proto_file.proto` with an include path of `[ C:/include_path, D:/current_repository ]`, the relative path should be `package`. But it is `D:/current_repository/package`

The generated cmake file contains a path "D:/current_repository/out_dir/D:/current_repository/package/proto_file.pb.h".
The inner `D:/current_repository/package` should only be `package`. In effect I'm unable to build the project.

As workaround, the order in the `IMPORT_DIRS` can be changed. If the "good" directory is the first entry in the list, the loop breaks in line 114 with the correct `package` and everything works fine.

**Comment by GeneKong** [comment]
It's this problem have some improve?

```cmake
find_package(Protobuf REQUIRED)
set(PROTO_GEN_DIR "${PROJECT_SOURCE_DIR}/pb")

protobuf_generate(
        PROTOS "${PROJECT_SOURCE_DIR}/../../pb/test.proto"
        TARGET Test
        IMPORT_DIRS "${PROJECT_SOURCE_DIR}/../../pb/"
        PROTOC_OUT_DIR "${PROTO_GEN_DIR}")

include_directories("${PROTO_GEN_DIR}")
target_link_libraries(Test PUBLIC protobuf::libprotobuf)
```

The Test target will include bad test.pb.cc path which in "../../pb/" but not "pb" directory.

**Comment by cgudrian** [comment]
I've encountered this issue today as well and was able to fix the behavior with a [simple check](https://github.com/cgudrian/protobuf/commit/668f6dc900870756f0ad17cfed0441cb128d84f5) in protobuf-generate.cmake. I have not yet tested whether this still works on non-Windows systems.

**Comment by cgudrian** [comment]
Here's the output of
```cmake
file(RELATIVE_PATH rel_dir ${base_dir} ${abs_dir})
```
for some combinations of `base_dir` and `abs_dir`:

|     base_dir      |           abs_dir           |           rel_dir           |
| ----------------- | --------------------------- | --------------------------- |
| `c:/Users/Me`     | `c:/Users/Me/test.cmake`    | `test.cmake`                |
| `c:/Users/Me`     | `c:/Users/You/test.cmake`   | `../You/test.cmake`         |
| **`c:/Users/Me`** | **`d:/project/test.cmake`** | **`d:/project/test.cmake`** |
| `/Users/Me`       | `/Users/Me/test.cmake`      | `test.cmake`                |
| `/Users/Me`       | `/Users/You/test.cmake`     | `../You/test.cmake`         |
| `/Users/Me`       | `/project/test.cmake`       | `../../project/test.cmake`  |

The bold combination is the one that makes path composition fail in Windows as this leads to the final composed path
```
c:/Users/Me/d:/project/test.cmake
```
which obviously won't work.

Looking at the other results (especially those using POSIX paths) I think that my quick workaround (see previous comment) should work on all systems (not only Windows). That workaround detects the problematic case (where CMake returns `abs_dir` unaltered) and skips to the next entry in the loop.

I'll open a pull request for this change.
