### ISSUE TITLE
Add support for nested maps and lists

### ISSUE THREAD

**Issue by xakepp35** [protocolbuffers/protobuf#9292]
**What language does this apply to?**
proto3, generating for golang

**Describe the problem you are trying to solve.**
In a message, I want to be able to declare field of type `map<string, map<string, repeated string>>`
For now compiler is failing

**Describe the solution you'd like**
I'd like to be able to define described schema directly it in proto,
protoc should make me a field in a golang struct with exactly that typing:
`map[string]map[string][]string`

**Describe alternatives you've considered**
wrapping maps in messages as a fields. 
in some cases it can be workaround,
but some data formats tends to be fully unsupportable by proto

**Comment by elharo** [comment]
This is deliberate. Proto maps don't allow maps as values.

**Comment by xakepp35** [comment]
@elharo And what is the point of having such a bad impl? Why not have a generic one, where it is allowed? It turns out that you cannot serialize arbitary data structure, and that is bad, leading to inefficiences, unnesesary conversions, etc. What is the goal of such limitation?
