### ISSUE TITLE
SerializationException: Type 'Google.Protobuf.UnknownFieldSet' in Assembly 'Google.Protobuf, Version=3.18.1.0' is not marked as serializable.

### ISSUE THREAD

**Issue by iluiluilu** [protocolbuffers/protobuf#9295]
Version=3.18.1.0
I use grpc_unity_package.2.43.0-dev202112021021.zip on my Unity project, grpc-protoc_windows_x64-1.43.0-dev.zip to generate .cs file from .proto file. All zip file has been download from https://packages.grpc.io/archive/2021/12/50a207ee9cc2cf4ffbf3e34f7a46af854b3535f5-fbaf5dd5-6c0a-4db9-81f4-1c7396507c4d/index.xml
After generate .cs file, I put [global::System.SerializableAttribute] on each message class, but when I run the game, I got an error

`SerializationException: Type 'Google.Protobuf.UnknownFieldSet' in Assembly 'Google.Protobuf, Version=3.18.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' is not marked as serializable.`

I try to research but I got stuck.
Any idea/workaround?

**Comment by elharo** [comment]
Protobufs are designed as an interoperable, language independent serialization mechanism. There's no expectation they'll support language specific serialization mechanisms, and there are a multitude of reasons not to do that.
