### ISSUE TITLE
Auto-generated Enum_ARRAYSIZE is incorrect if enum has negative values

### ISSUE THREAD

**Issue by joe-polin** [protocolbuffers/protobuf#9300]
What version of protobuf and what language are you using?
Version: latest (haven't tested, just inspected code. originally discovered in the protobuf version that shipped with grpc v1.41.1)

What did you do?
Try making an enum that has a negative value. Then size will be wrong.

Summary:
The array size for an enum is computed [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_enum.cc#L151) as the `max + 1`. The `max` is hard-coded to be the largest value in the enum, just as the `min` is defined to be the minimum value (which can be negative). Therefore, I believe the length should actually be `(max - min) + 1` (assuming values are continuous).

Without fixing this, the `Enum_ARRAYSIZE` will be too small (one short for every negative enum there is).

**Comment by samrrr** [comment]
This bug still exist.

**Comment by joe-polin** [comment]
> This bug still exist.

Yes it does

**Comment by deannagarcia** [comment]
I'm sorry this got missed. Is the bug still in the newest release? Can you fill out the bug template form with version numbers and reproduction instructions?

**Comment by joe-polin** [comment]
> I'm sorry this got missed. Is the bug still in the newest release? Can you fill out the bug template form with version numbers and reproduction instructions?

Hm, not running the latest so not sure. But inspecting the code, it seems to be:

https://github.com/protocolbuffers/protobuf/blob/v21.2/src/google/protobuf/compiler/cpp/enum.cc#L148-L153
