### ISSUE TITLE
continuous builds breaking

### ISSUE THREAD

**Issue by perezd** [protocolbuffers/protobuf#9302]
Seeing this in CI logs:

```
[ RUN      ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc:92: Failure
Value of: actual_contents == expected_contents
  Actual: false
Expected: true
../csharp/src/Google.Protobuf/Reflection/Descriptor.cs needs to be regenerated.  Please run generate_descriptor_proto.sh. Then add this file to your CL.
```

Do you have awareness on how to get this fixed? I see it says to run a script but I don't know what other environmental context I may be missing in CSharp. Can you help with this?

**Comment by perezd** [comment]
I believe this may have been introduced around here: https://github.com/protocolbuffers/protobuf/pull/9182

**Comment by haberman** [comment]
I think this may be obsolete; current builds for C# are passing.
