### ISSUE TITLE
[CMake] Can not use `protobuf-module.cmake` when compiling without libprotoc or protoc

### ISSUE THREAD

**Issue by owent** [protocolbuffers/protobuf#9306]
**What version of protobuf and what language are you using?**
Version: master/v3.19.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux, Windows and macOS

**What runtime / compiler are you using (e.g., python version or gcc version)**

MSVC,GCC,Clang

**What did you do?**

Using cmake to configure buildsystem and with `-Dprotobuf_BUILD_LIBPROTOC=OFF` or `-Dprotobuf_BUILD_PROTOC_BINARIES=OFF` (crossing compile) and use the prebuilt package with

```cmake
set(protobuf_MODULE_COMPATIBLE ON)
set(Protobuf_PROTOC_EXECUTABLE "<Where to find host prebuilt protoc>")
find_package(protobuf)
```

**What did you expect to see**

Protobuf found with `protobuf::libprotobuf` and `protobuf::libprotobuf-lite` .

**What did you see instead?**

`get_target_property() called with non-existent target "protobuf::*"`

**Comment by elharo** [comment]
3.9.1 is pretty old. Is this still an issue in 3.19.1?

**Comment by owent** [comment]
> 3.9.1 is pretty old. Is this still an issue in 3.19.1?

My mistake, it's 3.19.1, not 3.9.1. I have modified the description.
