### ISSUE TITLE
Comment/code inconsistency in utf8 decodeUtils

### ISSUE THREAD

**Issue by ChoKaPeek** [protocolbuffers/protobuf#9314]
Hi,

I think these comments are inconsistent with the code they refer to:
https://github.com/protocolbuffers/protobuf/blob/8c29dc2c4d55bb620bfe15ca6b74f8097cbb006d/java/core/src/main/java/com/google/protobuf/Utf8.java#L1911-L1920

`byte < 0xE0` should be of the form 110XXXXX
and `byte < 0xF0` should be of the form 1110XXXX

Similarly:
https://github.com/protocolbuffers/protobuf/blob/8c29dc2c4d55bb620bfe15ca6b74f8097cbb006d/java/core/src/main/java/com/google/protobuf/Utf8.java#L1925-L1933
`byte1 < 0xC2` would be < 11000010, and `byte2 > 0xBF` would be > 10111111, which doesn't match the comments

I don't know which one of the code or comment is wrong though

**Comment by elharo** [comment]
This class is non-public so we have some room to change it in either direction as needed.

**Comment by elharo** [comment]
I see at least one other example of code using exactly this logic in google3 though the comments are a little better:

```
   /**
     * Returns whether this is a two-byte codepoint with the form '10XXXXXX' iff {@link
     * #isOneByte(byte)} is false.
     */
    private static boolean isTwoBytes(byte b) {
      return b < (byte) 0xE0;
    }

    /**
     * Returns whether this is a three-byte codepoint with the form '110XXXXX' iff {@link
     * #isTwoBytes(byte)} is false.
     */
    private static boolean isThreeBytes(byte b) {
      return b < (byte) 0xF0;
    }
```

I suspect (need to verify) that these private methods are only used in order (i.e. first test one byte, then two bytes, then three bytes) and that makes this logic OK for the actual uses.

**Comment by elharo** [comment]
The comments are incomplete. These are highly optimized private methods only suitable for very specific code paths within this one class where other patterns have already been ruled out, not general purpose byte checking methods. The comments will be updated in the next sync from the internal repo. Thanks for the report.
