### ISSUE TITLE
Segfault when parsing textproto (3.11.2 works find, 3.13.0 and later breaks).

### ISSUE THREAD

**Issue by jackshi0912** [protocolbuffers/protobuf#9326]
**What version of protobuf and what language are you using?**
Version: 3.13.0 and later
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 9.3.0

**What did you do?**
  const int file_descriptor = open("data.textproto" O_RDONLY);
  google::protobuf::io::FileInputStream file_input(file_descriptor);
  google::protobuf::TextFormat::Parse(&file_input, &proto)

**What did you expect to see**
Parse complete correctly.

**What did you see instead?**
Exited with error code 139 (segfault)
This was not an issue in 3.11.2. This became an issue for releases after (at most) 3.13.0.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by jackshi0912** [comment]
Same is true for ParseFromString

**Comment by acozzette** [comment]
Usually when this happens it is because of problem with the build configuration. For C++ protobuf the following two things are important:
1. Only link against one copy of `libprotobuf`.
2. Make sure the `protoc` version used to generate code exactly matches the `libprotobuf` version used.
