### ISSUE TITLE
序列化/反序列化 如何添加Type信息或者解析Type信息？

### ISSUE THREAD

**Issue by bw2015** [protocolbuffers/protobuf#9327]
程序语言：C#

在进行反序列化的时候，服务器提供过来的内容是：
![image](https://user-images.githubusercontent.com/38880080/146686749-80dde6f6-0768-4e40-a20b-ec9a14c5c7d5.png)

多了一个头部的内容： type.googleapis.com/GetTaskInfoResponse
导致我无法进行反序列化。

同样的原因，我对本地的内容进行序列化的时候，也没有携带上这个头部的Type的信息，导致服务端无法解析。

---
PS：服务端代码无法查看。
---

我的序列化和反序列化代码：
![image](https://user-images.githubusercontent.com/38880080/146686831-77e13442-df95-487d-be97-024a8f7fab99.png)

**Comment by shaod2** [comment]
可能有两种情况
1. 服务器发送了一个内容是`GetTaskInfoResponse` Protobuf [Any](https://developers.google.com/protocol-buffers/docs/proto3#any) 
2. 服务器发送了两个不同的消息并且合在一起了

请问连的是什么服务器？能看到具体服务器发了什么内容？服务器和本地是共享同一个.proto还是两个不同的？（可能本地的protobuf message定义和服务器的有偏差/缺少了Any）

**Comment by bw2015** [comment]
原因已经找到，是外层多包了一层，类型是Any。
