### ISSUE TITLE
C++ Add constexpr to if statements that are constant at compile time

### ISSUE THREAD

**Issue by davidhunter22** [protocolbuffers/protobuf#9331]
As of v3.19.0

I was getting various warnings in a Visual Studio 2022 C++ compile 
`protobuf/stubs/strutil.h : warning C4127: conditional expression is constant`
These correspond to source lines such as
`if (sizeof(int32) == sizeof(long))`
It would be good to remove the warning and the, admitedly tiny, runtime cost by adding constexpr
`if constexpr (sizeof(int32) == sizeof(long))`
The constexpr  can obviously be a macro if it needed to support older compilers that doesn't have this.
Note sure how many instances of this there are but the compiler is good at finding them

**Comment by haberman** [comment]
We do need to support C++11, which doesn't support `if constexpr`.

Could you find out what [Abseil](https://github.com/abseil/abseil-cpp) does for this case? Abseil is also compatible with C++11. Whatever they do I think we would be comfortable following suit. A macro like `IF_CONSTEXPR(cond)` would be a possible solution, but it also obfuscates the code, so there is a tradeoff.

**Comment by dlj-NaN** [comment]
It looks like this was addressed in 1473d74, which should be in 3.19.0.

**Comment by dlj-NaN** [comment]
@davidhunter22 Do you still see this? It looks like the 3.19.0 sources should have included 1473d74, and src/google/protobuf/stubs/strutil.h includes `port_def.inc`. Could you double-check the version of your sources?
