### ISSUE TITLE
Add std::optional support to generated C++ proto code.

### ISSUE THREAD

**Issue by mikemol** [protocolbuffers/protobuf#9332]
**What language does this apply to?**

C++

**Describe the problem you are trying to solve.**

Transparently preserve presence information between proto and C++'s std::optional type.

Consider the code:

```proto
package my.proto;

message MyProto {
  optional double my_optional_field = 1;
}
```

```c++
struct MyStruct {
  explicit MyStruct(const MyProto& input)
      : my_optional_field(input.my_optional_field()) {}
  std::optional<double> my_optional_field;
};

int main() {
  MyProto my_proto;
  MyStruct my_struct(my_proto);
  return !(my_proto.has_my_optional_field() == my_strict.my_optional_field.has_value());
}
```

The program will return a nonzero (failure) exit code, but it should return success. That is, the presence data in the std::optional field should convey the presence data in the proto for the corresponding optional field. I only discovered that this occurs while tracking down how an unpopulated optional field was manifesting as a populated-but-invalid value in my program.

**Describe the solution you'd like**

The generated code should include casting operators for std::optional<typename> for optional fields of that type, wherein the returned `std::optional` object does or does not have a value depending on whether or not the field in the proto is or is not populated.

**Describe alternatives you've considered**

My code for MyStruct at present must look like:

```c++
struct MyStruct {
  explicit MyStruct(const MyProto& input) {
    if(input.has_my_optional_field()) {
      my_optional_field = input.my_optional_field();
    }
  }
  std::optional<double> my_optional_field;
};
```

This is ungainly, especially when there is a mixture of optional and non-optional fields.

**Additional context**

**Comment by deannagarcia** [comment]
We have looked into this option, but have decided not to support it for a few reasons. First, it is in the best interest of the proto team to have pretty similar APIs across languages and having this specific ability in C++ but not in other languages could be problematic. Additionally, this would cause a large change in the design of Protocol Buffers since unset fields currently return a default value which users likely depend on.
