### ISSUE TITLE
the benchmark performance of protobuf 3.19.1 at gcc -O3 optimization level is slower

### ISSUE THREAD

**Issue by liuzhijiang** [protocolbuffers/protobuf#9338]
**What version of protobuf and what language are you using?**
Version: 3.19.1
Language: c++

**What operating system (Linux, Windows, ...) and version?**
CentOS Linux release 7.4.1708

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc-8.3.0

**What did you do?**
I used -O2 optimization level or -O3 optimization level to run benchmark tests respectively. 

**What did you expect to see**

**What did you see instead?**
The benchmark result of -O3 is slower than -O2 in the case google_message2_serialize. as follows:
-O2 benchmark result:
<img width="728" alt="图片" src="https://user-images.githubusercontent.com/5087288/147208759-dec50a85-43f8-4948-8406-9c1f94e9cefd.png">

-O3 benchmark result:
<img width="738" alt="图片" src="https://user-images.githubusercontent.com/5087288/147207740-a51a2853-9846-4237-adc3-a4c551769f33.png">

**Anything else we should know about your project / environment**
I found that the function GoogleMessage2GroupedMessage::ByteSizeLong() is a hot spot, as follows:
```
size_t GoogleMessage2GroupedMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:benchmarks.proto2.GoogleMessage2GroupedMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional float field1 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional float field2 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 4;
    }

    // optional float field3 = 3 [default = 0];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 4;
    }

    // optional bool field4 = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool field5 = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional bool field7 = 7 [default = false];
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

    // optional bool field9 = 9;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

    // optional float field8 = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 4;
    }

  }
  if (cached_has_bits & 0x00000700u) {
    // optional float field10 = 10;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + 4;
    }

    // optional int64 field11 = 11;
    if (cached_has_bits & 0x00000200u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_field11());
    }

    // optional bool field6 = 6 [default = true];
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}
```
When compiled with -O3 optimization level, this function will generate a lot of phi instructions.
So there is a way to avoid this problem:
use -fno-tree-partial-pre or use --param max-partial-antic-length=4

Can someone help solve this problem completely?

**Comment by haberman** [comment]
There's not much we can do about this. We can't control how the compiler will compile our code, and there are situations where `-O3` can be slower than `-O2` for various reasons.  I don't think we want to add very specific optimization flags like `-fno-tree-partial-pre` to the build.
