### ISSUE TITLE
C++: Can I get the actual memory usage of a specific message object

### ISSUE THREAD

**Issue by wu-hanqing** [protocolbuffers/protobuf#9340]
**What language does this apply to?**

protobuf 3.5 with syntax `proto2`, and doesn't specify `option cc_enable_arenas = true` in proto

**Describe the problem you are trying to solve.**

There are many long-lived message objects in my code.

Currently, I'm using `ByteSizeLong` to calculate total memory usage of message objects, but `ByteSizeLong` is serialized size of the message, not the actual memory usage.

I also see huge gap between `ByteSizeLong` memory usage and process RSS, like this

![image](https://user-images.githubusercontent.com/10327590/147337429-4cbffafc-e92d-4a2e-8abf-d5c2c035682e.png)

**Describe the solution you'd like**

Is there an interface that can directly get the actual memory usage or other alternatives?

**Describe alternatives you've considered**

**Additional context**
memory profiling is here:

![je6](https://user-images.githubusercontent.com/10327590/147339948-fe84ee14-1e05-4796-ad1c-61aa0e1637c6.gif)

**Comment by elharo** [comment]
You probably need a profiler. This is not something I expect to find in the library itself.
