### ISSUE TITLE
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'

### ISSUE THREAD

**Issue by chronoxor** [protocolbuffers/protobuf#9347]
If you need to build protobuf as static library and link it with dynamic runtime libraries the error message will appear

```
  SET(protobuf_BUILD_SHARED_LIBS OFF CACHE BOOL "Build Shared Libraries" FORCE)
  SET(protobuf_MSVC_STATIC_RUNTIME OFF CACHE BOOL "Link static runtime libraries" FORCE)
```

Error message:
```
libprotobuf.lib(any.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in test.obj
```

**Comment by chronoxor** [comment]
This is cause because in CMakeLists.txt option protobuf_MSVC_STATIC_RUNTIME is stick to protobuf_BUILD_SHARED_LIBS using cmake_dependent_option:
```
cmake_dependent_option(protobuf_MSVC_STATIC_RUNTIME "Link static runtime libraries" ON
    "NOT protobuf_BUILD_SHARED_LIBS" OFF)
```

As you see in example above it is possible to have combination (static libs linked to dynamic MSVC runtime):
```
protobuf_BUILD_SHARED_LIBS OFF
protobuf_MSVC_STATIC_RUNTIME OFF
```

**Comment by elharo** [comment]
We need more details to look into this: platform, compiler, commands, etc.

**Comment by elharo** [comment]
can be reopened if there are more details.

**Comment by chronoxor** [comment]
Thanks! Works fine for me now!

**Comment by jsrdzhk** [comment]
can you tell me how did you solve this problem? 😅

**Comment by srikanthachanta1** [comment]
@chronoxor can you tell me how you resolve the error LNK 2038 problem?
