### ISSUE TITLE
Can you add a parameter in json_format.MessageToJson method?

### ISSUE THREAD

**Issue by wuranxu** [protocolbuffers/protobuf#9351]
https://github.com/protocolbuffers/protobuf/blob/01e84b129361913e5613464c857734fcfe095367/python/google/protobuf/json_format.py#L195

😭 Hi! I'm newer to grpc.
when I convert my proto message to json string, I found my result is not correct because of the parameter `ensure_ascii` is not selectable.
Can u help me ?

**Comment by anandolee** [comment]
ensure_ascii default is True. Do you need (and why) set the ensure_ascii False?

**Comment by wuranxu** [comment]
> ensure_ascii default is True. Do you need (and why) set the ensure_ascii False?

I know. When Chinese character in my response data, it will not work well.
I usually use ```json.dumps(data, ensure_ascii=False)``` to solve it. =.=

**Comment by LeiYangGH** [comment]
the parameter only exists in some higher version.
in my case, 

- not exists: `protobuf-3.19.0`
- exists: `protobuf-4.21.5`
