### ISSUE TITLE
configure: error: newly created file is older than distributed files!

### ISSUE THREAD

**Issue by TadeuOliveira** [protocolbuffers/protobuf#9358]
**What version of protobuf and what language are you using?**
Version: master/v3.19.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 21.10

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2)

**What did you do?**
Installation failed on the following step:
```
./configure
```
From [installation instructions from this repo](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md)

**What did you expect to see**
Some success message.

**What did you see instead?**
The following log:
```
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: newly created file is older than dist
ributed files!
Check your system clock
```

**Anything else we should know about your project / environment**
My clock is synced to UTC-03
![image](https://user-images.githubusercontent.com/12589387/147840026-442584dc-5ab4-48bc-9edc-fd3eec333988.png)

I've checked the ```./configure``` script to get some hint on what's going on. 
It appears to be failing on line 2957, where the following condition should be met: ```test "$2" = conftest.file```.
The value for $2 is "gnu".

configure file:
```
  \ etc.
   test "$2" = conftest.file
   )
then
   # Ok.
   :
else
		echo -e "\n" '$2 value:' $2 
   as_fn_error $? "newly created file is older than distributed files!
Check your system clock" "$LINENO" 5
fi
  \ etc.
```

logs from ./configure command:
```
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane...
 $2 value: gnu
configure: error: newly created file is older than distributed files!
Check your system clock
```

If I surpass this check, the rest of the script runs with no issues, until I hit an error with the same ```error: newly created file is older than distributed files!``` error but on ```third_party/googletest```.

**Comment by Elbuort-Lee** [comment]
I have same issues, and looking for answer.

**Comment by Elbuort-Lee** [comment]
将所有文件设置成当前时间 参考Linux下修改文件创建时间(修改文件更改时间)。
find . -name "*" -exec touch '{}' \;
