### ISSUE TITLE
can't find protobuf_generate  when we use cmake 3.21.1

### ISSUE THREAD

**Issue by introspection3** [protocolbuffers/protobuf#9361]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
CMake Error at proto/CMakeLists.txt:39 (protobuf_generate):
  Unknown CMake command "protobuf_generate".

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by fowles** [comment]
3.6 is a very old version of protobuf.  Please retry on a more recent version

**Comment by deannagarcia** [comment]
Closing this because of a lack of response, if you try a new version of protobuf and still face the same issue feel free to reopen.

**Comment by introspection3** [comment]
@deannagarcia  even if I use the lastlest cmake version,the problem is still exist.

**Comment by deannagarcia** [comment]
Ok so you're getting this error with the latest version of cmake, what version of protobuf are you using?

**Comment by dailylama** [comment]
5: Task failed with an exception.
	-----------
	* What went wrong:
	Execution failed for task ':app:configureCMakeDebug[x86_64]'.
	> [CXX1429] error when building with cmake using CMakeLists.txt: -- The C compiler identification is Clang 14.0.7
	  -- The CXX compiler identification is Clang 14.0.7
	  -- Detecting C compiler ABI info
	  -- Detecting C compiler ABI info - done
	  -- Check for working C compiler: ~/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
	  -- Detecting C compile features
	  -- Detecting C compile features - done
	  -- Detecting CXX compiler ABI info
	  -- Detecting CXX compiler ABI info - done
	  -- Check for working CXX compiler: ~/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
	  -- Detecting CXX compile features
	  -- Detecting CXX compile features - done
	  -- 
	  -- 24.0.0
	  -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT
	  -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT - Success
	  -- Looking for pthread.h
	  -- Looking for pthread.h - found
	  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
	  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
	  -- Looking for pthread_create in pthreads
	  -- Looking for pthread_create in pthreads - not found
	  -- Looking for pthread_create in pthread
	  -- Looking for pthread_create in pthread - not found
	  -- Check if compiler accepts -pthread
	  -- Check if compiler accepts -pthread - yes
	  -- Found Threads: TRUE  
	  -- Found ZLIB: ~/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/21/libz.so (found version "1.2.12") 
	  -- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
	  -- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Success
	  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
	  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
	  -- Configuring incomplete, errors occurred!
	  See also "CMakeOutput.log".
	  See also "CMakeError.log".

	  C++ build system [configure] failed while executing:
	      ~/Library/Android/sdk/cmake/3.22.1/bin/cmake \
		-H <...>
		-DCMAKE_SYSTEM_NAME=Android \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		-DCMAKE_SYSTEM_VERSION=21 \
		-DANDROID_PLATFORM=android-21 \
		-DANDROID_ABI=x86_64 \
		-DCMAKE_ANDROID_ARCH_ABI=x86_64 \
		-DANDROID_NDK=~/Library/Android/sdk/ndk/25.2.9519653 \
		-DCMAKE_ANDROID_NDK=~/Library/Android/sdk/ndk/25.2.9519653 \
		-DCMAKE_TOOLCHAIN_FILE=~/Library/Android/sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
		-DCMAKE_MAKE_PROGRAM=~/Library/Android/sdk/cmake/3.22.1/bin/ninja \
		-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=<...>/x86_64 \
		-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=<...>/x86_64 \
		-DCMAKE_BUILD_TYPE=Debug \
		-B<...>/x86_64 \
		-GNinja

	  CMake Warning at protobuf/third_party/abseil-cpp/CMakeLists.txt:77 (message):
	    A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake
	    3.8 and up.  We recommend enabling this option to ensure your project still
	    builds correctly.
	  
	  
	  CMake Error at CMakeLists.txt:77 (protobuf_generate):
	    Unknown CMake command "protobuf_generate".
