### ISSUE TITLE
Add Ruby 3.1 compability

### ISSUE THREAD

**Issue by spickermann** [protocolbuffers/protobuf#9364]
[Ruby 3.1.0 was released](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/) on Christmas. 

Today I started updating our apps and noticed that `google-protobuf` is not compatible with Ruby 3.1 yet.

```
google-protobuf-3.19.1-x86_64-darwin requires ruby version < 3.1.dev, >= 2.3, which is incompatible with 
the current version, ruby 3.1.0p0
```

I understand that it might take some time to get this fixes – especially during the end of year break. I created this issue to keep track of this and me notified when a updated version was released.

Cheers and Happy New Year.

**Comment by spickermann** [comment]
google protobuf still doesn't support Ruby 3.1, see https://github.com/protocolbuffers/protobuf/issues/9364

**Comment by brauliobo** [comment]
same here, what is holding this?

**Comment by perezd** [comment]
Has anyone tried upgrading this to see what the breakages are? We're accepting PRs.

**Comment by arathunku** [comment]
We've been running an updated version in ~medium size app for the last few weeks, no new errors.

**Comment by perezd** [comment]
@arathunku, would you be comfortable sending a PR to allow Ruby 3.1 to be acceptable? We're not immediately sure where this limitation is coming from.

**Comment by jchestershopify** [comment]
As another data point, we are seeing this problem across multiple apps, affecting `google-protobuf` up to and including v3.19.4.

**Comment by haberman** [comment]
It's unclear to me why our gem is not compatible with Ruby 3.1.

Our gemspec's `required_ruby_version` is `>=2.3`:

https://github.com/protocolbuffers/protobuf/blob/020e4e33d179db705433ac41fa747a2cd7882296/ruby/google-protobuf.gemspec#L25

There is nothing from our end that should be prohibiting 3.1.

**Comment by Maaarcocr** [comment]
> It's unclear to me why our gem is not compatible with Ruby 3.1.
> 
> Our gemspec's `required_ruby_version` is `>=2.3`:
> 
> https://github.com/protocolbuffers/protobuf/blob/020e4e33d179db705433ac41fa747a2cd7882296/ruby/google-protobuf.gemspec#L25
> 
> There is nothing from our end that should be prohibiting 3.1.

The issue is that the pre-compiled versions of the gem do not support 3.1 as per https://github.com/protocolbuffers/protobuf/blob/1d13b60904eaeb08d35cc3f84a3801ef7381a64f/ruby/Rakefile#L128

I made a PR to fix it here: https://github.com/protocolbuffers/protobuf/pull/9566
