### ISSUE TITLE
protoc: imports and descriptors resolver plugin support

### ISSUE THREAD

**Issue by cloneable** [protocolbuffers/protobuf#9380]
**What language does this apply to?**

protoc, just the compiler itself.

**Describe the problem you are trying to solve.**

At the moment, protoc loads imports and descriptors from local files only. All dependencies have to be either vendored, causing redundancy and risk getting out of sync, or complex build tools like Bazel have to be used to specify repos to map a source to an include path. And there's still a risk that import paths are ambiguous: a too generic path like `"service/options.proto"` might come from more than one source.

**Describe the solution you'd like**

It would be great if protoc allows specifying an imports and descriptors resolver plugin via flag, similar to how output plugins are supported. The default resolver looks for local files. A custom resolver could fetch and make available external imports, like `import "github.com/owner/repo/path/file.proto@v1.2.3";` (similar to Go module resolution) or Bazel like labels: `import "@repo//package:path/file.proto";`.

Additionally and to safeguard backwards compatibility, the `remote` qualifier keyword for imports would trigger non-local resolution. That should prevent any surprises, but requires change to the syntax.

`import remote "github.com/owner/repo/path/file.proto@v1.2.3";`

(Can be combined with `public`.)

**Describe alternatives you've considered**

A syntactical change to proto files in form of a new directive or a file option to specify the source location(s).

**Comment by cloneable** [comment]
#8067 is related. That case could be handled by the above proposal by allowing remote files like `github.com/owner/repo/path/file.proto@latest` to be specified on the command line and the resolver would do the same as for imports.

**Comment by cloneable** [comment]
Maybe an ExternalResolverSourceTree implementation would be a good start. It runs the executable resolver plugin in the background and relays mapping requests via stdin/stdout.

**Comment by elharo** [comment]
Inside google this problem is completely solved by the source repository. .proto files are source code and can be shared just like .java files, .xml files, .py files or anything else. This doesn't seem like a feature that belongs in the layer of the proto library itself.

**Comment by cloneable** [comment]
Yes, I know how it works inside Google, spent over eight years there. The outside world is a lot less homogenous, source code is much more distributed, not everyone can use blaze/bazel. And I wasn't suggesting to turn the protoc compiler into a package manager, just to add a hook that would allow external tools to handle import-path translations.
