### ISSUE TITLE
php: Not possible to emit unpopulated fields in JSON encoding

### ISSUE THREAD

**Issue by mterwill** [protocolbuffers/protobuf#9385]
**What language does this apply to?** 
PHP

**Describe the problem you are trying to solve.**
With `google.golang.org/protobuf/encoding/protojson`, there's an [option](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions) to emit unpopulated fields:

```go
	// EmitUnpopulated specifies whether to emit unpopulated fields. It does not
	// emit unpopulated oneof fields or unpopulated extension fields.
	// The JSON value emitted for unpopulated fields are as follows:
	//  ╔═══════╤════════════════════════════╗
	//  ║ JSON  │ Protobuf field             ║
	//  ╠═══════╪════════════════════════════╣
	//  ║ false │ proto3 boolean fields      ║
	//  ║ 0     │ proto3 numeric fields      ║
	//  ║ ""    │ proto3 string/bytes fields ║
	//  ║ null  │ proto2 scalar fields       ║
	//  ║ null  │ message fields             ║
	//  ║ []    │ list fields                ║
	//  ║ {}    │ map fields                 ║
	//  ╚═══════╧════════════════════════════╝
	EmitUnpopulated bool

```

In the PHP extension, I [see](https://github.com/protocolbuffers/protobuf/blob/66d749188ff2a2e30e932110222d58da7c6a8d49/php/ext/google/protobuf/php-upb.h#L4802) `UPB_JSONENC_EMITDEFAULTS`, which looks like what we're looking for, but no way to set it in `serializeToJsonString` on the message itself.

https://github.com/protocolbuffers/protobuf/blob/a1d8f8f96900468f09ced2ce9d23dea5a1bc070c/php/ext/google/protobuf/message.c#L773-L812

I also took a glance through the pure PHP protobuf library and didn't see any reference to this functionality.

My organization uses PHP (w/ protobuf C extension) to serialize messages to JSON for consumption by non-protobuf-enabled clients, so an absent field is functionally different than one with its default value.

**Describe the solution you'd like**
Parity with Golang protobuf JSON encoding: the ability to emit unpopulated fields.

**Describe alternatives you've considered**
🤷‍♂️ 

**Additional context**
N/A

**Comment by haberman** [comment]
Yes this is missing functionality in PHP that would make sense to add.

The only tricky part is API. Currently there is a single optional `bool` parameter for `preserve_proto_fieldnames`. We would want to change this into a keyword arguments array, so a user could specify either one of these options by name.

I don't remember exactly how arguments arrays work in PHP, but feel free to send a PR for this.

**Comment by esorot** [comment]
duplicate: https://github.com/protocolbuffers/protobuf/issues/6035
Open to PRs
