### ISSUE TITLE
Disable check for Objective C compiler (AC_PROG_OBJC) on non-macOS systems

### ISSUE THREAD

**Issue by Arfrever** [protocolbuffers/protobuf#9392]
Autotools build system currently unconditionally checks for Objective C compiler:
https://github.com/protocolbuffers/protobuf/blob/0ac74b8126b76498075f43c37603d67a15d8d205/configure.ac#L83

However later there is:
https://github.com/protocolbuffers/protobuf/blob/0ac74b8126b76498075f43c37603d67a15d8d205/configure.ac#L217-L224

`OBJC_CONFORMANCE_TEST` is used in `conformance/Makefile.am`.
The only usage of Objective C compiler is for compiling source files which are used only when `OBJC_CONFORMANCE_TEST` is true.

This means that aforementioned check for Objective C compiler is unnecessary on non-macOS systems (when `$target_os` != `darwin*`).

Fix:
```
--- configure.ac
+++ configure.ac
@@ -80,7 +80,7 @@
 ACX_USE_SYSTEM_EXTENSIONS
 m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
 AM_CONDITIONAL(GCC, test "$GCC" = yes)   # let the Makefile know if we're gcc
-AC_PROG_OBJC
+AS_CASE([$target_os], [darwin*], [AC_PROG_OBJC], [AM_CONDITIONAL([am__fastdepOBJC], [false])])
 
 # test_util.cc takes forever to compile with GCC and optimization turned on.
 AC_MSG_CHECKING([C++ compiler flags...])
```

**Comment by elharo** [comment]
Does this beak anything?

**Comment by Arfrever** [comment]
We have downstream report of user complaining about check for Objective-C compiler selection: https://bugs.gentoo.org/830584

**Comment by thesamesam** [comment]
cc @10ne1

**Comment by 10ne1** [comment]
Thanks for reporting this. It is just a minor annoyance for us (ChromiumOS based on Gentoo) and it would be nice to avoid having to set an OBJC compiler if it is not necessary.

For context, we are interested in building packages only with LLVM tools/Clang and OBJC defaults to gcc. We intentionally block GCC/binutils, but we still need to keep it around for glibc and a very small handful of other packages which can't be built with LLVM/Clang (yet! it will happen eventually heh).

Again this is only a minor annoyance because we can explicitly set OBJC to Clang, but it would be nice to not have to do so. Thanks again!

**Comment by thomasvl** [comment]
I'm not likely to get the to look at this in the near future, if someone wants to submit a patch, great.

**Comment by haberman** [comment]
Can you migrate to use the CMake build instead?

Our autotools build is on its last legs, and I anticipate we will be deprecating it before too long in favor of CMake.

**Comment by Arfrever** [comment]
Protobuf's CMake build system is still in poorer state.
Until commit a9cf69a0ed7766f56976e48a0c96300e94433511 3 days ago, CMake build system was not setting sonames of libraries properly, which means that they were ABI-incompatible with libraries created by Autotools build system.
`https://github.com/protocolbuffers/protobuf/issues/6113` (also important for ABI compatibility) and possibly other bugs still remain.
`cmake/README.md` file still says:
> This directory contains CMake files that can be used to build protobuf with MSVC on Windows.

**Comment by thomasvl** [comment]
@Arfrever looks like you might have a have the start of a patch already?  Is this something you could put up a PR for?  And while I'm asking, what's the `AM_CONDITIONAL` block in that diff needed for?

**Comment by thomasvl** [comment]
Testing out a minimal version of the above diff to see if it atleast works on the CI systems.

**Comment by thomasvl** [comment]
> Testing out a minimal version of the above diff to see if it atleast works on the CI systems.

Looks like something trips up on `am__fastdepOBJC`, so I guess that's why it ends up being forced false.  Testing adding that in also.
