### ISSUE TITLE
3.19.2 not yet released on pypi

### ISSUE THREAD

**Issue by nipunn1313** [protocolbuffers/protobuf#9393]
**What version of protobuf and what language are you using?**
3.19.2 python

**What did you do?**
Look here - https://pypi.org/project/protobuf/#history
vs here https://github.com/protocolbuffers/protobuf/releases

**What did you expect to see**
3.19.2 up on pypi to match the latest published release shown on github

**What did you see instead?**
3.19.1 is the latest

**Comment by acozzette** [comment]
This is now done.

**Comment by nipunn1313** [comment]
Thanks!
