### ISSUE TITLE
"Make libprotobuf symbols local on OSX" - fix missing

### ISSUE THREAD

**Issue by peteboothroyd** [protocolbuffers/protobuf#9395]
The initial problem is described [here](https://github.com/protocolbuffers/protobuf/pull/8346). The current issue is that a piper import issue has caused the fix to be removed, meaning that the problem has been reintroduced. The import issue is discussed further [here](https://github.com/protocolbuffers/protobuf/pull/8966). This issue is opened to track the reintroduction of the fix.

Perhaps part of the issue is that there wasn't an associated test added to verify that only a limited subset of all the available symbols were exposed in the resulting dylib. I'm not sure how/if this is possible in the current wheel building pipeline.

**What version of protobuf and what language are you using?**
Version: All versions as far as I know.
Language: Python

**What operating system (Linux, Windows, ...) and version?** macOS

**What did you expect to see**

The fix introduced in https://github.com/protocolbuffers/protobuf/pull/8346 should be present in the `setup.py` file.

**What did you see instead?**

The fix has been removed.

**Comment by deannagarcia** [comment]
Closing the issue since the PR is merged, but feel free to open again if you still see the problem.

**Comment by alalek** [comment]
FYI, the similar problem of "all global" symbols on Linux: #3899
