### ISSUE TITLE
Ensure OSX aarch64 builds are added as assets to our releases

### ISSUE THREAD

**Issue by perezd** [protocolbuffers/protobuf#9397]
the M1 binaries don't appear to be making it onto our releases page:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.19.2/

We've had reports from customers about confusion w.r.t our M1 support so we should add it there to clarify going forward.

**Comment by teejae** [comment]
FYI, I've attempted to download/use the osx-aarch64 binary from the maven repo linked in this issue, but noticed it isn't verified/signed, so won't work out of the box either.

Ref:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.19.2/protoc-3.19.2-osx-aarch_64.exe

**Comment by perezd** [comment]
Good catch, we'll get this working.

**Comment by teejae** [comment]
thanks! looking forward to it. any likely ETA?

**Comment by paradox118181** [comment]
osx-aarch64 still not on release page, any progress or substitution?

**Comment by perezd** [comment]
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.19.2/protoc-3.19.2-osx-aarch_64.exe

This is the workaround, its unsigned so just go manually allow it in the sys prefs.
We are working on this, but I'd like to set expectations that it'll take more than 5 days. Signing infra for Google is complex and we need to get it spun up properly for these artifacts.

**Comment by deannagarcia** [comment]
Adding for tracking that this issue will also include universal binary releases.

**Comment by PolarBear292208** [comment]
Any idea on an ETA? I'm trying to decide how much work to put into a workaround in our build process. I'm been inside the Plex, so I know how painful these types of things can be!

**Comment by deannagarcia** [comment]
I would expect at least a month or two, but unfortunately I don't have a more precise estimate.

**Comment by fabulias** [comment]
is there an advance related to this? I need protobuf 😢

**Comment by PolarBear292208** [comment]
M1 binaries of protobuf are available via homebrew, it's also pretty straightforward to build it from source.

**Comment by 6congyao** [comment]
Is there any progress to this? we need the osx-aarch_64 protoc for m1

**Comment by deannagarcia** [comment]
Unfortunately it's still going to be a bit until we are able to publish signed and notarized binaries, but as mentioned you can use them from homebrew, build from source, or use the unsigned binaries and configure your machine to still run it.

**Comment by yueban** [comment]
There has been a new release, version [3.20.0-rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0-rc1). But I can't find anything about osx-aarch_64 in the changelog.

**Comment by deannagarcia** [comment]
I'm sorry, we still haven't been able to add it to the new release. The only options are the workarounds that I mentioned before, but I will keep updating when we have anything to report.

**Comment by dragonsinth** [comment]
FYI: https://github.com/protocolbuffers/protobuf/releases 3.20.0 has an OSX aarch_64, but the linked tarball (https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-osx-aarch_64.zip) is actually wrong-- the embedded `protoc` binary is x86_64.

```
~/protoc-3.20.0-osx-aarch_64> file bin/protoc 
bin/protoc: Mach-O 64-bit executable x86_64
```

**Comment by perezd** [comment]
Yes, we recently discovered that the aarch64 build was produced to create a placeholder, but hasn't actually had the work done to convert it. We're actively working on this within our release tooling and will provide updates soon.

**Comment by deannagarcia** [comment]
The most recent release of protobuf (21.0) has an OSX aarch64 binary and an OSX universal binary! 

Unfortunately, we have not been able sign it yet due to internal infrastructure problems. I will continue to keep you updated on that when there is progress.

**Comment by abhijeet-shinde264** [comment]
The app is a bit lagging and the search function and the user icon does not work. I have tested my Samsung S21 FE 5G, which runs on Android 12. I hope it is fixed in the next update.
The app is handy and it's a great platform to learn and get the latest updates.

**Comment by deannagarcia** [comment]
21 and 22 releases have an OSX aarch64 binary and an OSX universal binary. Signing is still in progress.

**Comment by deannagarcia** [comment]
Our newest releases (22.4+ and 23.x) will now have signed OSX binaries, closing this issue.
