### ISSUE TITLE
AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by Only2125** [protocolbuffers/protobuf#9409]
**What version of protobuf and what language are you using?**
Version: 3.6.1 and update it to 3.19.3
Language: python

**What operating system (Linux, Windows, ...) and version?**
linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
python version
**What did you do?**
We originally have protobuf-3.6.1. I am working to connect a new SDK and this will require the protobuf version > 3.10.0
1. `pip install protobuf 3.19.3`
2. Found existing installation: protobuf 3.6.1
           Uninstalling protobuf-3.6.1:
           Successfully uninstalled protobuf-3.6.1
3. Successfully installed protobuf-3.19.3

**What did you expect to see**
no error
**What did you see instead?**
    `File "/usr/local/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 47, in <module>`
     `from google.protobuf.pyext import _message`
   `AttributeError:` module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'`
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by bcduck89** [comment]
![image](https://user-images.githubusercontent.com/58922802/149702680-7133b501-9253-4041-a01c-b4be15d8c33f.png)


![image](https://user-images.githubusercontent.com/58922802/149702633-1ac71059-79a4-4255-94e5-7d55f8955e89.png)

**Comment by anandolee** [comment]
We have dropped Python < 3.7 support, because Python 3.6 reached end-of-life upstream on Dec 23, 2021

**Comment by crifan** [comment]
if want no change to python file, then:

* upgrade `protobuf` to latest version
  * `pip install --upgrade protobuf`
    *  here upgrade from `protobuf-3.2.0` to latest `protobuf-6.30.2`
