### ISSUE TITLE
Specify that varints should be encoded shortest possible way

### ISSUE THREAD

**Issue by safinaskar** [protocolbuffers/protobuf#9411]
Encoding spec at https://developers.google.com/protocol-buffers/docs/encoding is underspecified. It doesn't say whether non-canonical varint serializations are allowed (i. e. whether it is okey to serialize number "5" as two bytes). I propose to explicitly forbid such serializations. I. e. to require reader to fail when reading such serialization. This will ensure (at least for simple schemas) that equal values serialize to equal binary strings.

This bug is also present in other binary formats, which explicitly refer to "protobuf varint", for example, Avro ( https://avro.apache.org/docs/current/spec.html ), this page contains link to https://code.google.com/apis/protocolbuffers/docs/encoding.html#types . So, I propose using very careful wording, which will refer not only to protobuf, but to varint itself. I. e. use wording, which implies you are defining meaning of "varint", not meaning of "protobuf". I. e. write "non-canonical byte strings are not valid varints" instead of "non-canonical byte strings are not allowed in protobuf". The former wording defines term "varint", not term "protobuf" and thus "fixes" not only protobuf, but also all specs explicitly referring to protobuf varint, such as Avro.

It would be even better to explicitly write "In all other specs for various binary formats non-canonical varint encodings are forbidden unless explicitly stated otherwise in that spec"

**Comment by acozzette** [comment]
I think we actually want to allow non-canonical varints. Our implementations always make them as short as possible, but sometimes it's useful to make them larger than necessary so that you have a consistent size. There's an implementation called [ProtoZero](https://perfetto.dev/docs/design-docs/protozero#deferred-patching) that does this for example.

**Comment by safinaskar** [comment]
@acozzette , if you really want to support non-canonical varints, then please write in spec explicitly that they are allowed

**Comment by elharo** [comment]
Everything not forbidden is permitted.

Might be worth clarifying this point, but the spec is not incomplete as written, nor could we add an additional requirement like this at this time without breaking backwards compatibility. On a related note, it might be worth auditing our code to make sure it behaves correctly in the face of longer than required varints.
