### ISSUE TITLE
Utf8.decodeUtf8: Simplify and optimize for ascii strings

### ISSUE THREAD

**Issue by amirhadadi** [protocolbuffers/protobuf#9414]
`Utf8.decodeUtf8` can be replaced with a call to `String(byte[] bytes, int offset, int length, Charset charset)` and then a search for the replacement string `'\uFFFD'` in order to decide whether to throw `InvalidProtocolBufferException`.

If this idea is not ruled out, I can provide benchmark results that compare different strings (ascii / non ascii). Spoiler: for ascii strings of 50 characters this method is ~30% faster than the current implementation on modern JVMs.

I created a PR that makes this idea concrete.

**Comment by elharo** [comment]
What do benchmarks show for non-ASCII strings?

**Comment by amirhadadi** [comment]
Tested out the following strings:
"The quick brown fox jumps over the lazy dog" (ascii)
"Quizdeltagerne spiste jordbær med fløde, mens cirkusklovnen" (German, ISO-8859-1 code points, requiring a single byte per codepoint in Java 9)
"𠜎𠜱𠝹𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎𠸏𠹷𠺝𠺢" (Chinese)

The comparison was between current `Utf8.decodeUtf8` with `UnsafeProcessor` and the suggested version of `decodeUtf8`.

I ran the tests with Java 8/11/17 on my Mac.

Regarding the terrible performance of Java 11/17 for German, this baffled me so after consulting with HotSpot folks, it will get resolved in [this](https://github.com/openjdk/jdk/pull/7034) PR.

Summarizing the results for Java 11/17:
ascii is 30% faster.
German is 100% slower but the allocation rate is 25% lower.
Chinese is 12 - 20% slower

Here are the results:

Java 8

Runtime (nanoseconds)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|50|78|121|
|suggested|65|100|147|

Allocation (Bytes / operation)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|128|304|248|
|suggested|168|344|288|

Java 11

Runtime (nanoseconds)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|35|84|128|
|suggested|25|170|154|

Allocation (Bytes / operation)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|88|248|296|
|suggested|88|184|328|

Java 17

Runtime (nanoseconds)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|28|72|96|
|suggested|19|139|108|

Allocation (Bytes / operation)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|88|248|296|
|suggested|88|184|328|

**Comment by amirhadadi** [comment]
@elharo one point I'm not sure about is whether all byte sequences that would presently cause `decodeUtf8` to throw `InvalidProtocolBufferException` would cause a '\uFFFD' to appear in the decoded String.

**Comment by elharo** [comment]
Reminder to self: use GWP to see if this method shows up as a hotspot that's worth optimizing.

The simplfication of code seems nice regardless.

**Comment by elharo** [comment]
My initial investigation with GWP suggests this method is not frequently called enough to be worth optimizing. I need to dig a little deeper, but the only thing that likely matters here is whether the code is cleaner and less buggy.

**Comment by acozzette** [comment]
@amirhadadi Do your results above take into account the fix you mentioned [here](https://github.com/openjdk/jdk/pull/7034)?

**Comment by amirhadadi** [comment]
@acozzette here are the timing results with the [fix](https://github.com/openjdk/jdk/pull/7034):

Tested with OpenJDK 19-ea+8-441

Runtime (nanoseconds)
|implementation|ascii|Latin1|Chinese|
|----|---|---|--------------------|
|current|28|75|103|
|suggested|19|66|105|

**Comment by acozzette** [comment]
@amirhadadi Thanks! Those numbers look pretty good: significantly better for ASCII and Latin-1 with perhaps a negligible regression for Chinese.

**Comment by X-czh** [comment]
It might be possible to speed up the encoding path as well with modern JDK: https://bugs.openjdk.org/browse/JDK-8275863
