### ISSUE TITLE
How can I process the compilation of Protobuf source code into Java binary to keep the same as that in Release 3.13.0?

### ISSUE THREAD

**Issue by ICT-YuJia** [protocolbuffers/protobuf#9416]
**What language does this apply to?**
protobuf java 

**Describe the problem you are trying to solve.**
How can I process the compilation of Protobuf source code into Java binary to keep the same as that in Release 3.13.0?
we use hw jdk 1.8 or openjdk 11.0.7 but binary and source are not same.

**Describe the solution you'd like**
Please tell me use which version of jdk to compile can get the same binary.

**Describe alternatives you've considered**

**Additional context**

**Comment by elharo** [comment]
I don't think we have a fully reproducible build at this time. It is a good idea, we just haven't done it yet. Also, I'm not sure JDK 1.8 can be relied on to produce byte-per-byte identical builds. There are a lot of places where the unspecifiedness of map ordering  comes into play in the compiler, for example.
