### ISSUE TITLE
Negative int32 ten bytes?

### ISSUE THREAD

**Issue by paul35621** [protocolbuffers/protobuf#9420]
In the [encoding documentation](https://developers.google.com/protocol-buffers/docs/encoding), I read:

`If you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long`

Shouldn't this be 5 bytes for int32? Since a varint can store 7 bits per byte, with 5 bytes we can store 5 * 7 = 35 bits, which is enough for any 32 bit value.

**Comment by elharo** [comment]
The docs are correct as written. Negative int32's occupy ten bytes. I whipped up a quick test to verify this, and if you dig around in CodedOutputStream.java you'll see how.

**Comment by paul35621** [comment]
Okay, thanks for clearing this up.
