### ISSUE TITLE
Compile error with clang for x86 Windows in debug mode

### ISSUE THREAD

**Issue by ngg** [protocolbuffers/protobuf#9421]
**What version of protobuf and what language are you using?**
Version: v3.19.3 / master

**What operating system (Linux, Windows, ...) and version?**
Linux / Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 13.0.0 / trunk

**What did you do?**
Try to compile the `generated_message_tctable_lite.cc` file with Clang to x86 Windows target without optimizations.
Example command for this (paths to windows sysroot must be changed):
```sh
cd src
clang++ -I. -target i386-windows -Xclang -internal-isystem -Xclang path_to_win_sysroot/msvc/include -Xclang -internal-isystem -Xclang path_to_win_sysroot/winsdk/include/ucrt -Xclang -internal-isystem -Xclang path_to_win_sysroot/winsdk/include/shared -Xclang -internal-isystem -Xclang path_to_win_sysroot/winsdk/include/um -std=c++20 -c google/protobuf/generated_message_tctable_lite.cc
```

**What did you expect to see**
Compile succeeds

**What did you see instead?**
Clang crashes with `fatal error: error in backend: failed to perform tail call elimination on a call site marked musttail` error
The bug is in LLVM, I've reported it there as well with a minimized reproduction case: https://github.com/llvm/llvm-project/issues/53271

**Proposed solution**
This happens because the `[[clang::musttail]]` attribute is not properly working on Windows x86. In https://github.com/protocolbuffers/protobuf/blob/41e22cde8d8a44c35127a26c19e08b180e0b30a4/src/google/protobuf/port_def.inc#L233 there is already some architectures listed where this attribute is disabled, add x86 windows to that list. I'll open a PR with this approach.

**Comment by elharo** [comment]
https://blog.reverberate.org/2021/04/21/musttail-efficient-interpreters.html

**Comment by icepic** [comment]
This applies to mips64 too, so protobuf with clang13 (on openbsd 7.2 for instance) fails unless something like this is added:
 #endif
-#if __has_cpp_attribute(clang::musttail) && !defined(__arm__) && \
+#if __has_cpp_attribute(clang::musttail) && !defined(__arm__) && !defined(__mips64__) && \
     !defined(_ARCH_PPC) && !defined(__wasm__) &&                 \
     !(defined(_MSC_VER) && defined(_M_IX86)) &&                  \
     !(defined(__NDK_MAJOR__) && __NDK_MAJOR <= 24)
