### ISSUE TITLE
Generated Kotlin fails to compile when comments includes certain strings in brackets

### ISSUE THREAD

**Issue by wfhartford** [protocolbuffers/protobuf#9427]
**What version of protobuf and what language are you using?**
Version: v3.19.3
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 17.0.1 & Kotlin 1.6.10

**What did you do?**
1. Create a simple protobuf message with a single field, add this comment to that field: `// [a.]`
```
message TestMessage {
  // [a.]
  string testField = 1;
}
```
2. Generate kotlin based on this message, the functions and field generated for this field will include the following in their comment:
```
    /**
     * <pre>
     * [a.]
     * </pre>
     */
```
3. Build the kotlin code, the kotlin compiler will emit an error something like `Identifier expected`.

**What did you expect to see**
Generated kotlin code comments should be well formed. 

**What did you see instead?**
Kotlin comments which cause compile error. Kotlin comments use a syntax similar to markdown. The compile error is caused by a malformed link in the brackets.

I think that the correct fix for this would be to replace the HTML style `<pre>...</pre>` and `<code>...</code>` tags added to the comments with markdown syntax using backticks. The brackets, and most other syntax elements do not get interpreted within markdown code blocks.

**Comment by deannagarcia** [comment]
Thanks for this report! I'm going to need to do a pretty significant rewrite here to completely decouple java and kotlin comment generation and make Kotlin comments more idiomatic. Since there is an easy workaround (don't add those specific comments), I'm going to group this in with a broader rewrite. Will update with progress here.

**Comment by wfhartford** [comment]
Thanks, is there an issue or discussion page regarding the broader rewrite?

**Comment by deannagarcia** [comment]
I don't have one right now, I figured I will update here.

**Comment by deannagarcia** [comment]
https://github.com/protocolbuffers/protobuf/pull/10196 should fix the error and adds some support for Kdoc
