### ISSUE TITLE
protobuf >=3.18.0 (including 3.19.3) fails to build on HPPA (`error: static assertion failed: static_assert(alignof(T) <= 8, "")`)

### ISSUE THREAD

**Issue by thesamesam** [protocolbuffers/protobuf#9433]
**What version of protobuf and what language are you using?**
Version: `>=3.18.0` (including 3.19.3)
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Gentoo Linux.

**What runtime / compiler are you using (e.g., python version or gcc version)**

GCC 10.3.0.

**What did you do?**
1. Build `dev-libs/protobuf-3.19.1` on Gentoo Linux on HPPA.
2. Build fails.

**What did you expect to see**

Successful build.

**What did you see instead?**

```
/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src/google/protobuf/descriptor.cc: In instantiation of ‘T* google::protobuf::{anonymous}::TableArena::Create(Args&& ...) [with T = google::protobuf::FileDescriptorTables; Args = {}]’:
/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src/google/protobuf/descriptor.cc:1868:46:   required from here
/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src/google/protobuf/descriptor.cc:707:30: error: static assertion failed
  707 |     static_assert(alignof(T) <= 8, "");
      |                   ~~~~~~~~~~~^~~~
/bin/sh ../libtool  --tag=CXX   --mode=compile hppa2.0-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src -I..   -DGOOGLE_PROTOBUF_NO_RTTI -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare  -O2 -pipe -march=2.0 -fdiagnostics-color=always -frecord-gcc-switches -c -o google/protobuf/duration.pb.lo /var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src/google/protobuf/duration.pb.cc
make[2]: *** [Makefile:4145: google/protobuf/descriptor.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  hppa2.0-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src -I.. -DGOOGLE_PROTOBUF_NO_RTTI -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -march=2.0 -fdiagnostics-color=always -frecord-gcc-switches -c /var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1/src/google/protobuf/duration.pb.cc  -fPIC -DPIC -o google/protobuf/.libs/duration.pb.o
make[2]: Leaving directory '/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1-.hppa/src'
make[1]: *** [Makefile:1895: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/protobuf-3.19.1/work/protobuf-3.19.1-.hppa'
make: *** [Makefile:1802: all] Error 2
```

Full log is available here: [build.log](https://github.com/protocolbuffers/protobuf/files/7913816/build.log).

**Anything else we should know about your project / environment**

- The machine is using the HPPA CPU architecture.
- Reported downstream in Gentoo [here](https://bugs.gentoo.org/831728).
- Previous issue on HPPA which has since been fixed: #7682

**Comment by thesamesam** [comment]
David Seifert (@SoapGentoo) analysed the [bug](https://bugs.gentoo.org/831728#c1) on our Bugzilla:
>on my Ryzen:
>alignof(std::mutex):      8
>alignof(pthread_mutex_t): 8
>alignof(max_align_t):     16
>
>on a HP C8000:
>alignof(std::mutex):      16
>alignof(pthread_mutex_t): 16
>alignof(max_align_t):     8
>
>That is, on HPPA any struct/class that includes a std::mutex as member automatically becomes an over-aligned type. Over-aligned types have a history of being hard to deal with in C and C++, because std::malloc only guarantees the alignment of >its returned pointer to alignof(std::max_align_t). As such, up to and including C++14, such types could not be used in >standard containers like std::vector, as they lacked the mechanisms to request correctly aligned memory for such types >(C++17 has fixed this).
>
>The alignment to 16 bytes is not a bug, this is due to PA-RISC's requirement for 16 byte aligned words and doublewords for >memory locking (https://parisc.wiki.kernel.org/images-parisc/7/73/Parisc2.0.pdf, p106 last paragraph).
>
>I have tried protobuf by just sed'ing out the offending static_assert on a C8000, and the code compiled fine for me. I >haven't done any in-depth tests to check whether the code works fine.

It looks like Debian have needed to use a similar workaround for e.g. [MySQL](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1793133.html). Note that the contributor of that patch is one of the maintainers of the HPPA GCC port, so with the above analysis, I'm reasonably sure that we need to just `#ifdef` this for HPPA for the time being until C++17.

I'll try running the test suite on 3.17 (which builds for me) and on 3.19.1 with the workaround applied and compare.

**Comment by thesamesam** [comment]
Test suite passes with the assert removed on HPPA.

**Comment by sbenzaquen** [comment]
This code no longer exists at head. Please confirm if this is still an issue.
