### ISSUE TITLE
The c++ output needs to add more keywords for c++20

### ISSUE THREAD

**Issue by xim** [protocolbuffers/protobuf#9442]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
All

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 10.2

**What did you do?**
Make a .proto with a type "concept" in it.

**What did you expect to see**
A successful compile with e.g. `g++ -std=gnu++2a` 

**What did you see instead?**
```cpp
In file included from ./test.pb.cc:4:
./test.pb.h:901:19: error: C++20 concept definition syntax is ‘concept <name> = <expr>’ [-Werror]
  901 |   ::test::Concept concept() const;
```

**Anything else we should know about your project / environment**
`cpp_helpers.cc` just need "concept" added to the keyword list. Maybe others, if c++20 adds more keywords.

**Comment by fowles** [comment]
unfortunately, this would be a breaking change for pre C++11, so we will likely avoid doing this until we release a major version for C++.

**Comment by xim** [comment]
Just to make it easier to plan, is there a rough timeline on that? I'll have to wait for that release or run a patched protobuf before I can enable c++20...

**Comment by xim** [comment]
Also, maybe add everything from the list at https://en.cppreference.com/w/cpp/keyword for that release =)

**Comment by fowles** [comment]
Obviously, I am not committing to anything, but I anticipate a major version in the next 6 months.

**Comment by fowles** [comment]
Yes, this would include all C++20 keywords (for all the users who have fields named `co_await`, `co_return`, and `co_yield`).

We are behind on the 6 month thing I mentioned, but I am still hopeful we will manage it in the next 3.  This work uncovered some significant shortcomings in our build infra that we need to fix first.

**Comment by haberman** [comment]
Closing as obsolete, as this has been done for a while.
