### ISSUE TITLE
Java: TextFormat.unescapeBytes unable to decode a valid UTF8 escape

### ISSUE THREAD

**Issue by robertasg** [protocolbuffers/protobuf#9447]
**What version of protobuf and what language are you using?**
Version: `com.google.protobuf:protobuf-java:3.17.3`
Language: `Java/Kotlin`

**What operating system (Linux, Windows, ...) and version?**

macOS 12.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

`kotlin` @ `1.4.20`

```
...
    kotlinOptions.jvmTarget = "11
....
```

**What did you do?**

```
TextFormat.unescapeBytes("\\U000358da")
```

Happy to set up the full file if needed.

**What did you expect to see**

String with unescaped sequences.

**What did you see instead?**

```
Exception in thread "main" java.lang.NullPointerException
        at com.google.protobuf.TextFormat.unescapeBytes(TextFormat.java:2432)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Using `org.apache.commons.lang3.StringEscapeUtils` I was able to unescape this sequence and get a character that got properly converted to bytes.

**Comment by elharo** [comment]
\u was introduced in C++ 11. I'm not sure we support that format, though the docs should be clearer on this point.

**Comment by elharo** [comment]
"Escapes bytes in the format used in protocol buffer text format, which is the same as the format used for C string literals. All bytes that are not printable 7-bit ASCII characters are escaped, as well as backslash, single-quote, and double-quote characters. Characters for which no defined short-hand escape sequence is defined will be escaped using 3-digit octal sequences."

**Comment by elharo** [comment]
See TextFormatTest. \U000358da is not a valid escape sequence for this method.

**Comment by robertasg** [comment]
@elharo 

> See TextFormatTest. \U000358da is not a valid escape sequence for this method.

Could you please clarify that? I definitely see tests for unicode escapes:

https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/test/java/com/google/protobuf/TextFormatTest.java#L916

Looking at the implementation, it's 8 bytes as expected. So it's definitely being handled.

https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/TextFormat.java#L2409

I see an example of invalid code point handling 

https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/test/java/com/google/protobuf/TextFormatTest.java#L1008

However, the case I've specified here doesn't seem to be handled.

I'd also like to clarify that this is the output I got via `cbt`, so I'm assuming the string was escaped used this library.

**Comment by elharo** [comment]
I have an open bugs to clarify the docs on this behavior.

**Comment by elharo** [comment]
I can repro this. Still not sure exactly what's happening.

**Comment by elharo** [comment]
Looks like this is returning null:

                Character.UnicodeBlock unicodeBlock = Character.UnicodeBlock.of(codepoint);

**Comment by elharo** [comment]
Fixed in google3 and will arrive in this repo with next sync.

**Comment by robertasg** [comment]
Amazing, thank you! 🙏
