### ISSUE TITLE
NullPointerException in GeneratedMessageTest.testOneofParseFailurePropagatesUnderlyingException

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#9453]
`mvn test` build from open source pretty close to head of open source. Logging here for further investigation. 

[INFO] Running com.google.protobuf.GeneratedMessageTest
[ERROR] Tests run: 84, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.095 s <<< FAILURE! - in com.google.protobuf.GeneratedMessageTest
[ERROR] com.google.protobuf.GeneratedMessageTest.testOneofParseFailurePropagatesUnderlyingException  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NullPointerException
	at com.google.protobuf.GeneratedMessageTest.testOneofParseFailurePropagatesUnderlyingException(GeneratedMessageTest.java:1780)

**Comment by elharo** [comment]
Just maybe this is a Mac specific bug.

**Comment by deannagarcia** [comment]
This hasn't been reproduced or reported elsewhere, so I'm closing.
