### ISSUE TITLE
Crash using `FieldMask.MergeMessage` and deserialized messages

### ISSUE THREAD

**Issue by coryan** [protocolbuffers/protobuf#9463]
**What version of protobuf and what language are you using?**

Version: 3.19.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Linux, I think 

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.9

**What did you do?**

Consider this proto file:

```proto
syntax = "proto3";

package repro.crash;

message Thing {
    string name = 1;
    map<string, string> labels = 2;
}
```

This code works:

```py
def works():
    print("This works")
    target = test_pb2.Thing(name="original", labels={"k0": "label0", "k1": "label1"})
    changes = test_pb2.Thing(name="changed", labels={"k0": "label0", "k1": "label1"})
    mask = field_mask_pb2.FieldMask(paths=["name", "labels"])
    mask.MergeMessage(changes, target)
```

While this code, which only serializes and deserializes the `changes` proto crashes:

```py
def crashes():
    print("This crashes")
    target = test_pb2.Thing(name="original", labels={"k0": "label0", "k1": "label1"})
    changes = test_pb2.Thing(name="changed", labels={"k0": "label0", "k1": "label1"})
    serialized = changes.SerializeToString()
    changes = test_pb2.Thing()
    changes.ParseFromString(serialized)

    mask = field_mask_pb2.FieldMask(paths=["name", "labels"])
    mask.MergeMessage(changes, target)
```

The error message I get is:

```
[libprotobuf FATAL google/protobuf/map_field.cc:357] CHECK failed: IsMapValid() && other.IsMapValid(): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: IsMapValid() && other.IsMapValid(): 
Aborted (core dumped)
```

**What did you expect to see**

I expected both functions to work and produce the same results.

**What did you see instead?**

A crash, see above.

**Anything else we should know about your project / environment**

I am a Googler, ping me directly if you have additional questions.   I have attached a tarball that reproduces the problem, the instructions on how to use it are in the Dockerfile.

[repro-v1.tar.gz](https://github.com/protocolbuffers/protobuf/files/7987130/repro-v1.tar.gz)

**Comment by fowles** [comment]
Thanks for taking the time to minimize the test case!  This really helps a great deal.

**Comment by anandolee** [comment]
It is a known issue that ParseFromString() in our c++ side put the map into repeated. We've tried to fix it before but was rolled back for some breakage. Will see what I can do for it

**Comment by aravind-tonita** [comment]
> It is a known issue that ParseFromString() in our c++ side put the map into repeated. We've tried to fix it before but was rolled back for some breakage. Will see what I can do for it

@anandolee is there any fix for this?  I'm facing a very similar issue that has do do with how map fields get parsed in ParseFromString().

Thanks!
