### ISSUE TITLE
protoc exe gives segmentation fault

### ISSUE THREAD

**Issue by Abhishek2011992** [protocolbuffers/protobuf#9465]
Hi,
On Ubuntu 20.04
when protobuf source is compiled with -fpack-struct=2, compilation gets completed but when we execute ./protoc , we get segmentation fault(core dump)

please help!!!

**Comment by elharo** [comment]
We need more details. Which compiler? 

TBH this does sound a bit like, "Doctor, my arm really hurts when I raise it up over my head". Is -fpack-struct=2 criotical for some reason?

**Comment by haberman** [comment]
We cannot support `-fpack-struct`, this is an ABI-impacting flag that will make our library ABI-incompatible with anything else that was not compiled with `-fpack-struct` (for example libc or libc++).
