### ISSUE TITLE
Parsing multiple JSON objects from a Reader in java

### ISSUE THREAD

**Issue by philsttr** [protocolbuffers/protobuf#947]
In `protobuf-java-util` from 3.0.0-beta-1, it is possible to write multiple objects in JSON format to an `Appendable` like this:

``` java
Printer jsonPrinter = JsonFormat.printer();
Writer writer = ...
jsonPrinter.appendTo(protoObject1, writer);
jsonPrinter.appendTo(protoObject2, writer);
```

However, it is impossible to read multiple objects in JSON format from a `Reader`.  I would like to be able to do something similar to this:

``` java
Parser jsonParser = JsonFormat.parser();
Reader reader = ...
jsonParser.merge(reader, protoObject1Builder);
jsonParser.merge(reader, protoObject2Builder);
```

This _does not work_ because the first call to `jsonParser.merge` constructs a `JsonReader` which fills an internal buffer (`JsonReader.buffer`) from data from the `reader`.  This advances the `reader` past the end of the JSON object being read.  After the merge is complete, the `JsonReader` is thrown away, which also throws away any unread data from its internal buffer.

In the second call to `jsonParser.merge`, a new `JsonReader` is constructed.  But since the `reader` has advanced too far, it is unable to read the next object.

This can easily be reproduced using a proto message with no fields.  When trying to read two instances of the message in JSON format (`{}{}`) from the same reader, the second merge will fail with an exception like this: `com.google.protobuf.InvalidProtocolBufferException: Expect message object but got: null`

**Comment by xfxyjwf** [comment]
Hmm, the JSON API is not designed to write/read multiple objects. This is an interesting use case though. I guess we can provide additional methods for reading/writing multiple objects at once.

**Comment by philsttr** [comment]
Hmm.  Ok.  The current API _implies_ that it can write/read multiple objects, since the printer can write to an `Appendable`, and parser can read from a `Reader`.  I am surprised to hear that that is not the intended purpose.

In any case, yes, I would really appreciate the ability to write/read multiple objects to the same Writer/Reader.

Thanks for considering this!

**Comment by RenEvo** [comment]
+1

**Comment by philsttr** [comment]
I'm considering implementing and submitting a PR that exposes a merge method that takes a JsonReader as input.

e.g.
```
    public void merge(JsonReader json, Message.Builder builder)
```
This would avoid the "overbuffering" problems I mentioned in the description, allow reading multiple objects from the same stream, and enable nesting of protobuf json objects within other json objects/arrays.

The downside is that it would expose the usage of GSON, but I don't really see that as too much of a problem.

Any concerns?

**Comment by xfxyjwf** [comment]
@philsttr 

Although we haven't decided, we may need to use a different parser for consistency of the JSON implementation between Java and other languages (GSON is more lenient  than we would like in some cases). For this reason we would like to avoid exposing GSON in public interfaces.

**Comment by philsttr** [comment]
Ok. Thanks for the info.

And just FYI, the "overbuffering" problem has also been reported directly against GSON in https://github.com/google/gson/issues/536

**Comment by haon4** [comment]
We are unlikely to make any change for this. Closing.
