### ISSUE TITLE
Need v3.0.0. Please, add a tag so I can install it on my Mac

### ISSUE THREAD

**Issue by pythagoreantree** [protocolbuffers/protobuf#9472]
Hello, 

I need to install protobuf 3.0.0 on my Mac for BigARTM, cause this library requires exactly the v.3.0.0
I don't know how to do it except for using 'pip install https://github.com/protocolbuffers/protobuf.git@3.0.0' but there is no such tag there. 
Could you, please, create the tag for me or tell me another way I can install 3.0.0
I need it for my ML course. I wouldn't be able to finish my course without it.

Thank you for understanding.

**Comment by elharo** [comment]
We don't support older versions. Please bring the version issues up with your professor or TA.
