### ISSUE TITLE
Please use Semantic versioning for javalite if ABI / API breaks happen in the future

### ISSUE THREAD

**Issue by elevenfive** [protocolbuffers/protobuf#9487]
**What language does this apply to?**
Java

**Describe the problem you are trying to solve.**
If multiple dependencies are compiled with different versions of javalite, runtime breaks could happen unless javalite bumps its major version to signal an incompatibility between versions.

**Describe the solution you'd like**
If ABI / API breaks happen, bump the major version of javalite (eg 3.19.4 -> 4.0.0)

**Describe alternatives you've considered**
Have to scan all dependencies and manually test every build to be sure nothing breaks

**Additional context**
N/A

**Comment by elharo** [comment]
Thanks for the feedback. Not sure if this will happen but discussions are underway about updating our versioning strategy.
