### ISSUE TITLE
Improve IDE support for Ruby

### ISSUE THREAD

**Issue by acozzette** [protocolbuffers/protobuf#9495]
The generated Ruby code is not very IDE-friendly, and could be improved to support things like auto-completion. For Python, we're going in the direction of making the main generated code small and efficient but not human-readable, and generating separate `.pyi` files that are more human-readable and IDE-friendly. We need to figure out a plan for Ruby, though.

#7593 suggests one solution, which would be to embed code in `if false` blocks so that it's visible to the IDE and to human readers without changing behavior. @haberman also suggesting doing something like this:
```
Google::Protobuf::DescriptorPool.generated_pool.add_serialized_descriptor(
  "<serialized_descriptor>"
)

# Google::Protobuf::Message defines #inherited to hook in the correct behaviors.
# This fails if #add_serialized_descriptor has not been called for "Foo."
class Foo < Google::Protobuf::Message
  # The base class overrides attr_accessor to do the right thing (maybe even
  # define it as a no-op if #inherited is handling the hard part.
  attr_accessor :foo
end
```

**Comment by haberman** [comment]
I think RBS is a promising direction here: https://blog.appsignal.com/2021/01/27/rbs-the-new-ruby-3-typing-language-in-action.html

We could make the main generated code `foo_pb.rb` nothing but a serialized descriptor. Then we could have a separate `foo_pb.rbs` file that contains full static typing information, for IDE-friendliness.

**Comment by zhangskz** [comment]
This issue is still active per pending PR https://github.com/protocolbuffers/protobuf/pull/15633
