### ISSUE TITLE
mingw cross build error

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/protobuf#9499]
### What version of gRPC and what language are you using?

I use the default protocolbuffers version from https://github.com/grpc/grpc/releases/tag/v1.43.2

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)

cross build mingw from linux with https://github.com/mstorsjo/llvm-mingw/releases/download/20211002/llvm-mingw-20211002-msvcrt-ubuntu-18.04-x86_64.tar.xz

### What did you do?

cmake with minimal options to build libgrpc.a

### What did you expect to see?

expect build finish without error.

### What did you see instead?

```sh
grpc/third_party/protobuf/src/google/protobuf/io/zero_copy_stream_impl.cc:108:28: error: use of undeclared identifier 'F_GETFL'
  int flags = fcntl(file_, F_GETFL);
```

The error come from code:
```c
FileInputStream::CopyingFileInputStream::CopyingFileInputStream(
    int file_descriptor)
    : file_(file_descriptor),
      close_on_delete_(false),
      is_closed_(false),
      errno_(0),
      previous_seek_failed_(false) {
#ifndef _MSC_VER
  int flags = fcntl(file_, F_GETFL);
  flags &= ~O_NONBLOCK;
  fcntl(file_, F_SETFL, flags);
#endif
}
```

https://github.com/mstorsjo/llvm-mingw/issues/258

https://github.com/grpc/grpc/issues/28855

@[Biswa96](https://github.com/Biswa96) from LLVM-mingw suggestion upstream replace _MSC_VER with _WIN32 here.

**Comment by deannagarcia** [comment]
Are you still seeing this issue with a newer version of protobuf?

**Comment by deannagarcia** [comment]
Closing this due to no response, feel free to reopen this if you are still seeing the issue.
