### ISSUE TITLE
Request to remove use of the problematic term, 'dummy' in codegen

### ISSUE THREAD

**Issue by Tibrim** [protocolbuffers/protobuf#9503]
**What language does this apply to?**
If it's about generated code change, what programming language? **C++**

**Describe the problem you are trying to solve.**
A generated variable name is prefixed with `dynamic_init_dummy_` in the generated C++ file.  

**Describe the solution you'd like**
Requesting the removal of the term, `dummy` from this variable name.

**Describe alternatives you've considered**
N/A

**Additional context**
We scan for problematic terms at our organization and this popped up recently.

**Comment by fowles** [comment]
There are other problematic terms we would prioritize far ahead of this one, so I don't think we will get to this in any reasonable timeframe.
