### ISSUE TITLE
Ruby Protobuf Map `#Merge` inconsistent with Hash behaviour

### ISSUE THREAD

**Issue by lucas-s-work** [protocolbuffers/protobuf#9515]
**What version of protobuf and what language are you using?**

Version: v3.14.0
Language: Ruby

**What operating system and version?**

Debian GNU/Linux 10 (buster)

**What runtime / compiler are you using (e.g., python version or gcc version)**

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**What did you do?**

1. Attempt to merge two `::Google::Protobuf::Map`'s with a provided block and duplicate keys
2. See map returned with field overriden and block not called

Minimal reproduction of the issue:

```ruby
hash1 = {
  "a": "First element", 
  "b": "Second element"
}
hash2 = {
  "a": "Different first element"
}
# Raises the exception "collision found a"
hash1.merge(hash2) { |key, _, _| raise "collision found #{key} "}

map1 = ::Google::Protobuf::Map.new(:string, :string, hash1)
map2 = ::Google::Protobuf::Map.new(:string, :string, hash2)

# Does not raise exception, returns the following (written as a hash):
# {
#   "a": "Different first element",
#   "b": "Second element"
# }
map1.merge(map2)  { |key, _, _| raise "collision found #{key} "}
```

**What did you expect to see**

As per the [ruby generated code guidelines](https://developers.google.com/protocol-buffers/docs/reference/ruby-generated#map-fields) which state "Map fields are represented using a special class that acts like a Ruby Hash", it was expected that `#Merge` would behave the same for `::Google::Protobuf::Map` as it does for a `Hash`. That is, if a block is provided then the block is executed whenever there is a key collision. 

In the above example it is expected for `map1.merge(map2)...` to raise the exception `collision found a`.

**What did you see instead?**

The block was not executed for the duplicate keys and the original value was overwritten.

**Comment by haberman** [comment]
The `merge` operation has a special meaning for protobuf, and `Map#merge` implements the protobuf semantics for merge.

While we could support a callback for collisions, the callback would have extra limitations, for example the type of the returned element would need to match the value of the map.

Given how easy this is to implement manually, I am inclined to keep `#merge` the way it is, which is to just implement the standard protobuf semantics.
