### ISSUE TITLE
Normalize line endings for C# sources

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#9526]
Followup for incident in https://github.com/protocolbuffers/protobuf/pull/6307/files#r806572011

Run this command to see the current status:
```
git ls-files --eol csharp/src
```

Currently most files use LF, some files use CRLF and some files have mixed line endings.

Also see https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

**Comment by jtattermusch** [comment]
CC @jskeet

**Comment by jskeet** [comment]
We should probably work out any advice we need to give (or repo settings) to avoid users getting into problems in the future.
It would be good to add a test for this too.

**Comment by jskeet** [comment]
I'll try to get to this next week. (This week is pretty busy.)

**Comment by jskeet** [comment]
Okay, (not having read the first comment that shows `git ls-files --eol`, doh) I've written some code to categorize text files (from `src` and `csharp`, recursively) into "empty", "CRLF", "LF" or "mixed". Attaching the results at the bottom of this comment. 

In summary:

- LF: 774
- CRLF: 38
- Mixed: 4

It shouldn't be too hard to normalize on LF - I'm currently not sure of the best place to put a test for that though (to make sure we don't get regressions). I suspect `git ls-files` is the way forward though.

We *might* want to make an exception for .sln files as they're not usually hand-written - it's entirely possible that Visual Studio would clobber them anyway.

[output.txt](https://github.com/protocolbuffers/protobuf/files/8197054/output.txt)
