### ISSUE TITLE
Proposal: Generics/template syntax

### ISSUE THREAD

**Issue by Ludonope** [protocolbuffers/protobuf#9527]
**What language does this apply to?**
proto3 syntax change

**Describe the problem you are trying to solve.**
I am working with "delta" types which basically store modifications on the field of an object.

For example if my object is the following:
```go
type User struct {
    Subscriptions        []string
    NotificationsEnabled bool
}
```

I will then have the following delta object:
```go
type UserDelta struct {
    Subscriptions        *delta.List[string]
    NotificationsEnabled *delta.Value[bool]
}
```

Using that I can then send the following delta:
```json
{
    "Subscriptions": {
        "Operation": "ADD",
        "Value": ["hello", "world"]
    }
}
```

Which will add those values to the `Subscriptions` list, or:
```json
{
    "NotificationsEnabled":  {
        "Operation": "SET",
        "Value": true
    }
}
```

Which will set `NotificationsEnabled` to true.

> This is very very simplified here

I would like to change my json API to a protobuf one.
In my `UserDelta` object I would like to use similar types such as `*delta.Value[bool]` or with any other subtype.

**Describe the solution you'd like**

```proto
message DeltaList<type T> {
  oneof input {
    T add = 1;
    T remove = 2;
  }  
}

message DeltaValue<type T> {
  T set = 1;
}

message UserDelta {
  DeltaList<string> subscriptions = 1;
  DeltaValue<bool> notifications_enabled = 2;
}
```

**Describe alternatives you've considered**

I have two other solutions, each with massive drawbacks:

1. Use `any` which loses the type information:
```proto
message DeltaList {
  oneof input {
    any add = 1;
    any remove = 2;
  }  
}

message DeltaValue {
  any set = 1;
}

message UserDelta {
  DeltaList subscriptions = 1;
  DeltaValue notifications_enabled = 2;
}
```

I will definitely not use that as it loses a lot of the benefits of protobuf.

2. Define a specialized type for each variant:
```proto
message DeltaListString {
  oneof input {
    string add = 1;
    string remove = 2;
  }  
}

message DeltaValueBool {
  bool set = 1;
}

message UserDelta {
  DeltaListString subscriptions = 1;
  DeltaValueBool notifications_enabled = 2;
}
```

This would be acceptable in that scenario, however in my case I have many more specializations to do which would be extra-cumbersome.

**Additional context**
The second alternative could simply be the processed result of the generic syntax I proposed.

The parser's and compiler's job is much simpler than in the case of a regular programmation language as we only need to generate the types that were explicitely instanciated.

Each language could implement it as a "hardcoded" type such as `DeltaValueBool` or if the language supports generics/templating it could be implemented as such for readability.

I feel like this could simplify the job of many people without adding too much complexity:
- There is no metaprogramming in any way (I'm particularly thinking of C++)
- There is no type inference needed
- It's almost like a glorified `Find and Replace`

**Comment by fowles** [comment]
Generics like this are very complex and will impact every language we target (many of which have their own generic systems we will want to interact with).  Given that it took multiple years of design to add generics to a language like Go, I expect this would be a similarly sized effort.

Even reviewing an external design would require a huge volume of effort.  We have no plans to start this exploration nor would we be likely to accept an external design for it.

**Comment by Ludonope** [comment]
I understand your point of view tho I disagree on the size of the effort.

With imperative languages such as Go or C++ there are many complexities added: type inference, casting, constraints, type erasure, ...

Protobuf is a declarative language, here there is no need for all of those "features". Everything is static, everything is explicit.

It doesn't have to correlate to generics in the output language, every message can be defined as a static type.

I understand that the idea of generics seems a bit spooky, particularly after the example of implementing them in Go, but with a declarative language it's basically syntactic sugar.

I'll totally understand if you are still against it as even that effort might not be worth the benefits, but I just hope it can make it look less like that giant spaghetti monster and more like a yummy spaghetti plate :)

**Comment by fowles** [comment]
While I appreciate the aspects that make this simpler than a full language, I think there is way more here than you give credit for.

* can languages refer to messages without fully in there generics or must they be fully specialized.  If they must be fully specialized I can tell you what one of the earliest feature requests we would receive is. If you can refer to the generic without instantiation in host languages, what is the API for that and how does it interact with that languages generic system?
* what does reflection for these types look like?  Presumably we will need to do something to augment the APIs for reflection in all most all of the languages.
* descriptor.proto will need enhancements so folks can import these things and then instantiate them after import, those will require design
* do generics allow primitives or only Messages? if the former there is a big bag of worms, if the latter I know what your second bevy of feature requests will be
* how do generics show up in serialized format for Any?  
* How do generics interact with extensions?  Should they allow injection of an extension number?  This one doesn't seem to have a "no" alternative, but is going to provide a fair amount of complexity that we have not broached yet.

So yeah, I am going to stick with my initial assessment.

**Comment by Ludonope** [comment]
That's a lot of good points, would probably be easier to start everything from scratch.

Thanks for the very detailed answer!
