### ISSUE TITLE
Use of banned api in library

### ISSUE THREAD

**Issue by Gautam-zodape** [protocolbuffers/protobuf#9533]
I have run the penetrating security test on the iOS app found issue with protobuf library.
pen test error : The binary may contain the following insecure API(s).

Following are the classes which used insecure api methods (memcpy)-
 - Protobuf/objectivec/GPBDescriptor.m (Line number 66, 67, 70, 73)
 - Protobuf/objectivec/GPBMessage.m (Line number 957)
 - objectivec/GPBRootObject.m (Line number 179, 181)
 - Protobuf/objectivec/GPBCodedOutputStream.m (Line number 290, 360, 960, 966, 979)
 - Protobuf/objectivec/GPBCodedInputStream.m (Line number 90, 110)
 - Protobuf/objectivec/GPBArray.m (Line number 242, 346, 463 ... so on)

Could you correct this issue or provide a probable fix for it?

**Comment by elharo** [comment]
We need more details than this. What is the actual bug that you see? memcpy can be misused in a buggy way. Its design is not great. However its mere presence does not prove that it is called insecurely. Can you point to a place where memcpy is used incorrectly?

**Comment by thomasvl** [comment]
As @elharo points out, what are the actual issues with the `memcpy` usage?  In all cases, the copies seem to be bounce checked/etc. So it seems whatever tool you are using is blinding flagging things just by api calls, and not actually be real issues.

**Comment by thomasvl** [comment]
Likely a dup of https://github.com/protocolbuffers/protobuf/issues/7945
