### ISSUE TITLE
generated java code on windows end with 'LF' , hope to end with "CRLF" 

### ISSUE THREAD

**Issue by elroy93** [protocolbuffers/protobuf#9539]
## Simple description
generated java code on windows end with 'LF' , hope to end with "CRLF" so that the codes could work on git diff tools. 

 ## Detailed description

Our code is written under windows, using protoc to generate the code . git is configured to automatically convert "LF" and CRLF so that it works properly under both win/linux. But the code generated by protoc ends in "LF" .  Every time you re-generate a proto file, a lot of diff files are generated on the visual git commit tool due to different line breaks.

**Comment by elharo** [comment]
This is unlikely to change in protobuf. The cost exceeds the benefits. Perhaps look into configuring the diff tool to better handle different line endings.

**Comment by elroy93** [comment]
Thank you, the problem has been solved through the configuration of git . 
## Solution
add "directory path"  to  `.gitattributes` file. 
> /src/generated/main/java/com/github/x/protocol/*.java text eol=lf
