### ISSUE TITLE
option to handle integer fields that have decimal values in JSON string

### ISSUE THREAD

**Issue by yoavmil** [protocolbuffers/protobuf#9541]
**What language does this apply to?**
C++, the JSON util

**Describe the problem you are trying to solve.**
```proto
message Foo { int32 bar = 1 ; }
```
```json 
{
 "bar" : 12.2
}
```
This will fail to parse with `google::protobuf::util::JsonStringToMessage`
Errer message will be 
`INVALID_ARGUMENT:(Foo.bar): invalid value 12.2 for type TYPE_INT32`

**Describe the solution you'd like**
have a new option in `google::protobuf::util::JsonParseOptions` for ways to hadnle such problems.
maybe an enum with options for Error/Round/Ceil/Floor.

**Describe alternatives you've considered**
Just a bool would be sufficiant, similar to `ignore_unknown_fields`

**Additional context**
This happened to me in production, when the JSON file was generated in a web TS frontend, which doesn't distinguish between int/float. Its just `number` there.

Cheers.

**Comment by elharo** [comment]
I've said it before and I'm sure I'll say it many times again. This library handles one very specific JSON format. It can't be customized to handle arbitrary or idiosyncratic JSON. If necessary transform the JSON before passing it into protobuf, but this repo os not the right place for that code.
