### ISSUE TITLE
protoc: inconsistent scope rules when resolving type names vs. custom options

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#9550]
**What version of protobuf and what language are you using?**
3.19.0

**What operating system (Linux, Windows, ...) and version?**
OS X

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A, just using `protoc` to compile descriptors.

**What did you do?**
I tried to compile the following file, via `protoc -o /dev/null test.proto`:
```proto
// test.proto
syntax = "proto3";

package test.pkg;

import "google/protobuf/descriptor.proto";

message Foo {
  message Bar {
    string baz = 1;
  }

  extend google.protobuf.MessageOptions {
    int32 x = 101010;
  }

  // for scoping, the following works and protoc can correctly resolve "Bar" w/out qualification
  Bar bar = 1;

  // so why can't protoc find "x" the same way?
  option (x) = 123;
  // instead, we have to do this for protoc to accept it:
  option (Foo.x) = 123;
}
```

**What did you expect to see**
Success

**What did you see instead?**
An error about the unqualified reference to `x`:
```
test.proto:21:10: Option "(x)" unknown. Ensure that your proto definition file imports the proto which defines the option.
```

**Anything else we should know about your project / environment**
Nope.

**Comment by elharo** [comment]
For better or worse, this seems to be working as designed:

https://developers.google.com/protocol-buffers/docs/proto#customoptions

I doubt it will be changed.

**Comment by jhump** [comment]
@elharo, I've read that whole section. I see nothing about the scoping rules described in this bug report. In fact, the doc site in general seriously _under-specifies_ the scoping rules.

If it's in there, could you be more specific -- like show me the verbage that describes this as expected behavior? Nothing in there, after reviewing it twice looking for it, seems to mention anything about nesting extensions in messages.

I apologize if the bug report was unclear, but the issue is related to referring to a _nested_ extension, which behaves differently from referring to a _nested_ type (message or enum). For top-level extensions, everything behaves as expected.

**Comment by elharo** [comment]
The docs site underspecifies a lot of things, I'm afraid. Please do file docs bugs for anything you find to be missing. We have a couple of folks rethinking our docs now.

**Comment by jhump** [comment]
@elharo, in this case, I'm still trying to decide if it's a doc bug. You pasted a link to the docs suggesting that this bug is _expected behavior_. But the docs do not state that. Why do you say it is expected? Can you re-read the example more closely, in the context of it being explicitly about _nested_ extensions (extensions defined inside of a message)?

Changing the behavior would not break any existing protos. It would only allow `protoc` to begin accepting sources that today it rejects.

So if it's not documented as expected behavior and would not be a risky change, why should the behavior remain this way?
