### ISSUE TITLE
When is the next release going to happen?

### ISSUE THREAD

**Issue by ptarjan** [protocolbuffers/protobuf#9564]
I'd like to use have https://github.com/protocolbuffers/protobuf/commit/15add1af49f13d1661d3910d0eb6697b415a19d1 included in a point release if it can be backported and the next release is a long ways away. Or if the next release happens soon I'm happy to just wait for that too.

Thank you!

**Comment by fowles** [comment]
We are in process on another release right now.  It is slightly slow going because we are improving some of our internal release tooling and this is the first one with parts of that tooling.

**Comment by ptarjan** [comment]
Ah excellent. Thank you.

**Comment by acozzette** [comment]
The 3.20.0-rc1 release is out now, and the final 3.20.0 release should be out soon, probably this week or next.

**Comment by ptarjan** [comment]
Thank you!
