### ISSUE TITLE
Linux arch releases should be tar.gz

### ISSUE THREAD

**Issue by brendensoares** [protocolbuffers/protobuf#9569]
**What language does this apply to?**
Github release process

**Describe the problem you are trying to solve.**
Linux distro's like Ubuntu don't include `unzip` by default. The releases already include `tar.gz`. Why would the linux binary builds not use `tar.gz`? Might make sense for Windows, but not Linux.

**Describe the solution you'd like**
Archive with `tar.gz` instead of `zip`

**Describe alternatives you've considered**
Installing `unzip` which is an unnecessary step if the archive was not `zip`.

**Comment by perezd** [comment]
I don't see us replacing the existing zips, as we have to be mindful of people's existing dependencies on our release artifacts. If anything, it's possible we'd _add_ tar.gz variants, but this is overall low value work (hard for us to prioritize it in the near term), and there's a reasonable workaround.
