### ISSUE TITLE
google::protobuf::util::JsonStringToMessage bug  0x%5D 

### ISSUE THREAD

**Issue by ms-zhibinwang** [protocolbuffers/protobuf#9574]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
c++
**What operating system (Linux, Windows, ...) and version?**
win
**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

i code :

try{
        std::string input  = "0x%5D ";
        auto status = google::protobuf::util::JsonStringToMessage(input, &request, options);
        if (!status.ok())
        {
           std::cout << "error"; 
        }
    }
    catch (const std::exception& e)
    {
       std::cout << "exception"; 
    }

not cache exception  , coredump  

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by dlj-NaN** [comment]
The provided snippet works fine for me at current HEAD on Windows (CMake+VS2019), using `proto3::TestMessage`. No exception is thrown, and control correctly enters the `!status.ok()` block. Please feel free to re-open if you have different instructions to reproduce the error.
