### ISSUE TITLE
v3.18.1 build out as libprotobuf.so.29.1 under linux,why?

### ISSUE THREAD

**Issue by AlexLuya** [protocolbuffers/protobuf#9575]
Hello,I downloaded souce code with tag v3.18.1,

```
./autogen.sh
./configure --enable-shared
sudo make install install

```
then 
```
 /usr/local/lib/libprotobuf-lite.so
/usr/local/lib/libprotobuf-lite.so.29
/usr/local/lib/libprotobuf-lite.so.29.0.1
/usr/local/lib/libprotobuf-lited.so
/usr/local/lib/libprotobuf.so
/usr/local/lib/libprotobuf.so.29
/usr/local/lib/libprotobuf.so.29.0.1
```
got installed,why?

**Comment by acozzette** [comment]
The so version number gets incremented with every minor release.

**Comment by AlexLuya** [comment]
So,which tagged source can be built out libprotobuf.so.3.18.1?

**Comment by acozzette** [comment]
There is no tagged commit that will produce libprotobuf.so.3.18.1. We increment the soversion number with each release to indicate that releases are not ABI-compatible, but that number is not intended to match the protobuf version number.

**Comment by AlexLuya** [comment]
Thanks，as you can see below:
```
/usr/local/lib/libprotobuf-lited.so
/usr/local/lib/libprotobuf-lited.so.3.18.1.0
/usr/local/lib/libprotobuf.so
/usr/local/lib/libprotobuf.so.29
/usr/local/lib/libprotobuf.so.29.0.1
/usr/local/lib/libprotobufd.so
/usr/local/lib/libprotobufd.so.3.18.1.0
```
Which tagged commit will produce: the libprotobufd.so.3.18.1.0

**Comment by acozzette** [comment]
Actually now that I think of it, the CMake build might generate a file of that name, since it wasn't until recently that the CMake build was updated to have the same soversion behavior as the autotools build. You could try building with CMake at v3.18.1.
