### ISSUE TITLE
Consider enabling libtool/configure silent mode by default

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#958]
https://www.gnu.org/software/automake/manual/html_node/Automake-Silent-Rules.html

I believe all that is needed is AM_SILENT_RULES([yes]) in configure.ac

Developers could still override locally with --disable-silent-rules on configure or via make V=1.  But having it off by default would likely make the logs far less chatty (which could also help travis logs).

**Comment by thomasvl** [comment]
Looks like silent mode isn't enough to suppress a bunch of libtool output (atleast on OS X).  So it might take enabling plus other cleanups in the automake/configure/makefile setup.

**Comment by elharo** [comment]
autotools is not in our future, we're trying to drop our dependency on it and move to bazel
