### ISSUE TITLE
[3.20.0RC] [release-notes] add php8.1 compatibility to release notes

### ISSUE THREAD

**Issue by brettmc** [protocolbuffers/protobuf#9587]
In https://github.com/protocolbuffers/protobuf/pull/9370 I originally asked for the `release-notes: no` tag because it was a minor change. It grew to be quite a bit bigger over time though, and I think it should be added to the release notes for 3.20.0 (eg "php 8.1 compatibility")

**Comment by acozzette** [comment]
Sure, would you mind sending another pull request to add that to `CHANGES.txt` on the 3.20.x branch?

**Comment by brettmc** [comment]
fixed by #9590
