### ISSUE TITLE
CMakeLists.txt should be in top-level directory

### ISSUE THREAD

**Issue by Arfrever** [protocolbuffers/protobuf#9596]
The standard practice is to put main `CMakeLists.txt` in top-level directory, not in subdirectory called `cmake` or similar.
Some examples of projects:
[abseil-cpp](https://github.com/abseil/abseil-cpp)
[gflags](https://github.com/gflags/gflags)
[glog](https://github.com/google/glog)

I would suggest to move Protobuf's `cmake/CMakeLists.txt` to top-level directory and adjust appropriate paths.
If there is agreement with this suggestion, then I can try to work on it.

**Comment by acozzette** [comment]
Is there a way to do this without breaking scripts that rely on the existing location? Maybe we could leave a symlink at the old location if that works.

**Comment by bsergean** [comment]
Old versions of Windows don't support symlinks, but newer might. It would be great if the Cmakefile was usable on linux/mac as well.

**Comment by Arfrever** [comment]
`cmake/CMakeLists.txt` can become a small regular file with few lines:
```
cmake_minimum_required(VERSION 3.5)

message(WARNING "Calling of cmake with Protocol Buffers' \"cmake\" subdirectory as source directory is deprecated. Top-level directory should be used instead.")

project(protobuf C CXX)

set(protobuf_DEPRECATED_CMAKE_SUBDIRECTORY_USAGE TRUE)

include(../CMakeLists.txt)
```

**Comment by bsergean** [comment]
Nice, that’s much in my opinion to the symlink approach.

**Comment by acozzette** [comment]
Yeah, that looks like a good way to do it!
