### ISSUE TITLE
 C++ 20 

### ISSUE THREAD

**Issue by PARKGIBAEK** [protocolbuffers/protobuf#9599]
What version of protobuf and what language are you using?
Version: master/v4.0.x

Language: C++

What operating system (Linux, Windows, ...) and version?
Windows 10

What runtime / compiler are you using (e.g., python version or gcc version)
MSVC++ 20

**What did you do?**
1. complie message class without string type using protoc.exe.
![image](https://user-images.githubusercontent.com/36660156/157248530-f003ded0-2043-4834-8cf5-af7376e0ad6a.png)

2. add file ~.pb.h & ~.pb.cc to my project.

3. tried to compile.

4. See error.

5. So I input macro.
![image](https://user-images.githubusercontent.com/36660156/157248695-94ca4cd2-1f54-4bd2-8cd9-5b453d6faee5.png)

6. But still same.

**What did you expect to see**

**What did you see instead?**
![image](https://user-images.githubusercontent.com/36660156/157248084-5679954a-0bff-4b8d-8833-c2e73a66f0a4.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
I checked out the `v3.17.0` tag and the string `is_pod` doesn't appear anywhere in the source (except `CHANGES.txt`). I suspect that you must have an old version of the protobuf runtime lying around that is causing the error.

**Comment by PARKGIBAEK** [comment]
> I checked out the `v3.17.0` tag and the string `is_pod` doesn't appear anywhere in the source (except `CHANGES.txt`). I suspect that you must have an old version of the protobuf runtime lying around that is causing the error.

Sorry for this, I tested it only v4.0 for this issue.
As I copied and used other issue reports as they were, there was a mistake.

**Comment by acozzette** [comment]
No problem!
