### ISSUE TITLE
[C#] oneof cannot have a field named none

### ISSUE THREAD

**Issue by homuler** [protocolbuffers/protobuf#9605]
**What version of protobuf and what language are you using?**
Version: master (https://github.com/protocolbuffers/protobuf/commit/5ad0697c868235f24559dc07f8a42870d160af76)
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Linux (ArchLinux 5.16.12-arch1-1), x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version

**What did you do?**
1. Build `protoc` in a way described [here](https://github.com/protocolbuffers/protobuf/tree/5ad0697c868235f24559dc07f8a42870d160af76/src).
   ```sh
   ./configure
   make -j `nproc`
   ```

1. Define `OneOfTest` and save as `one_of_test.proto`.
   ```proto
   syntax = "proto3";

   message OneOfTest {
     oneof options {
       int32 none = 1;
       string name = 2;
     }
   }
   ```

1. Compile `one_of_test.proto` (this step finishes successfully).
   ```sh
   ./src/protoc one_of_test.proto --csharp_out=.
   ```

**What did you expect to see**
The generated file (`OneOfTest.cs`) can be compiled successfully.

**What did you see instead?**
Fails to compile `OneOfTest.cs` with the following message:

> OneOfTest.cs(117,5): error CS0102: The type 'OneOfTest.OptionsOneofCase' already contains a definition for 'None'

Here is an excerpt of the generated code.
```cs
  private object options_;
  /// <summary>Enum of possible cases for the "options" oneof.</summary>
  public enum OptionsOneofCase {
    None = 0,
    None = 1,
    Name = 2,
  }
```

Currently, it seems that the compiler generates `None = 0` as a default field value.
https://github.com/protocolbuffers/protobuf/blob/5ad0697c868235f24559dc07f8a42870d160af76/src/google/protobuf/compiler/csharp/csharp_message.cc#L238

If `none` is already defined in `.proto`, the above compilation error will occur.

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
Looks like we need to mangle "none" in C#

**Comment by jskeet** [comment]
Yup. We already have code for this somewhere in the generator, and hopefully already for oneofs. It's "just" a matter of adding the None special casing. Will have a look when I get the chance.
