### ISSUE TITLE
PHP GPBUtil::checkRepeatedField reference parameter

### ISSUE THREAD

**Issue by Jurigag** [protocolbuffers/protobuf#9609]
https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/GPBUtil.php#L202

Even though here it doesn't modify `$var` anyhow it requires it as reference. What's the point of this when it still return the value and doesn't modify it?

**Comment by haberman** [comment]
I think it's probably written that way because other functions in this family (eg `checkString()`) do mutate the argument.

Is this causing a problem for you? These are internal APIs that should not affect users at all.
