### ISSUE TITLE
Ruby: int64 type using decond_json always get even number even if its original value is odd number.

### ISSUE THREAD

**Issue by simonwu-os** [protocolbuffers/protobuf#9615]
ProtoBuf:
Version: 3.19.4
Language: Ruby
Operating System: Ubuntu 18.04

protoc --version: libprotoc 3.19.4

1) using the proto file:

syntax = "proto3";
option optimize_for = LITE_RUNTIME;
message SveCodeSameGoodsData{
    int64 goods_id = 1;    
    int32 source = 2;       
    int64 scid = 3;         
    string name = 4;     
    string shop_name = 5;
    string sku = 6;         
    string main_pic_url = 7;
    int32 type_flag = 8;       
    double origin_price = 9; 
    double current_price = 10;
    int32 stock_num = 11;       
    bool has_discount = 12;    
    int32 opt_price_days = 13;
    string reason_desc = 14;   
    string recommend_desc = 15;
    string recommend_user_name = 16;
}
generate class:
SveCodeSameGoodsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SveCodeSameGoodsData").msgclass

2) sample data:
      hash_data = { :source => 1, :scid => 10, :name => "iPhone x", :sku => "00112233",
                    :main_pic_url => "http://xxx.xxx.xxx01",
                    :goods_id => 554490979814473729, :type_flag => 8, :origin_price => 6999.9,
                    :current_price => 5999.8, :stock_num => 211, :has_discount => true,
                    :opt_price_days => 31 }
   
 3) decode_json 
json_str = hash_data.to_json

```ruby
# json_str is the following content.
# json_str="{\"source\":1,\"scid\":10,\"name\":\"iPhone x\",\"sku\":\"00112233\",\"main_pic_url\":\"http://xxx.xxx.xxx01\",\"goods_id\":554490979814473729,\"type_flag\":8,\"origin_price\":6999.9,\"current_price\":5999.8,\"stock_num\":211,\"has_discount\":true,\"opt_price_days\":31}"
```

message = SveCodeSameGoodsData.decond_json(json_str)
4) error:
puts message_data.goods_id   ### the result is 554490979814473728
which is not 554490979814473729.
We expect the result is 554490979814473729.

I test with another datas. If the goods_id is even number ,it's right.
If the goods_id is odd number, then the value loss 1.
I guess the least bit is always 0.

**Comment by elharo** [comment]
How does ruby represent int64? This feels like a loss of precision on large numbers. goods_id perhaps should be a string if you're not doing arithmetic with it.

**Comment by simonwu-os** [comment]
> How does ruby represent int64? This feels like a loss of precision on large numbers. goods_id perhaps should be a string if you're not doing arithmetic with it.

We use ruby 2.7.5.  Since ruby 2.0, Integer can represent any large number.
irb(main):009:0> m
=> 554490979814473729
irb(main):010:0> m.class
=> Integer
irb(main):012:0> z=m*10338133830491
=> 5732401957122113052510058670939
irb(main):013:0> z.class
=> Integer

```ruby

irb(main):014:0> json_str
=> "{\"source\":1,\"scid\":10,\"name\":\"iPhone x\",\"sku\":\"00112233\",\"main_pic_url\":\"http://xxx.xxx.xxx01\",\"goods_id\":554490979814473729,\"type_flag\":8,\"origin_price\":6999.9,\"current_price\":5999.8,\"stock_num\":211,\"has_discount\":true,\"opt_price_days\":31}"
irb(main):015:0> hash=JSON.parse(json_str)
=> {"source"=>1, "scid"=>10, "name"=>"iPhone x", "sku"=>"00112233", "main_pic_url"=>"http://xxx.xxx.xxx01", "goods_id"=>55449...
irb(main):016:0> m=hash["goods_id"]
=> 554490979814473729
irb(main):017:0> z=m*10338133834091
=> 5732401959118280579842164095339
irb(main):018:0> z.class
=> Integer
```

**Comment by haberman** [comment]
To get full precision for an int64 in JSON, you need to quote the number.

Instead of:

```
\"goods_id\":554490979814473729
```

you should use:

```
\"goods_id\":\"554490979814473729\"
```

This is documented in the JSON mapping, which shows int64 integers as quoted values: https://developers.google.com/protocol-buffers/docs/proto3#json

Like most JSON parsers, the Ruby protobuf JSON parser will parse any unquoted number into a `double`, which will lose precision for large int64 values.

**Comment by simonwu-os** [comment]
Thanks. We add some tranfer to it. It passed.

In javascript,  we just avoid use max int64,  because it use double to present it.
But in Ruby, the json parser can parse big number than 2**52 without losing precision. 
So I think there is confused for ruby programmer.

```ruby
irb(main):001:0> require 'json'
=> true
irb(main):002:0> data = { :begin_timestamp => 0, :count => 2, :goods_id => 577848671777849345 }
=> {:begin_timestamp=>0, :count=>2, :goods_id=>577848671777849345}
irb(main):003:0> json_data = data.to_json
=> "{\"begin_timestamp\":0,\"count\":2,\"goods_id\":577848671777849345}"
irb(main):004:0> hash_data=JSON.parse(json_data)
=> {"begin_timestamp"=>0, "count"=>2, "goods_id"=>577848671777849345}
irb(main):005:0> hash_data["goods_id"] == 577848671777849345
=> true
irb(main):006:0> 
```
