### ISSUE TITLE
Add a build() method to MessageOrBuilder interface

### ISSUE THREAD

**Issue by mickare** [protocolbuffers/protobuf#962]
Please consider a message-type value setter for MessageOrBuilder.

Currently there are two setters generated for a message-type value.
MessageOrBuilder provides equivalency. So it would be logically to combine the setters to a single one.

How could you solve it?
### First approach

Add a method to the MessageOrBuilder interface and make it generic.

``` java
public interface MessageOrBuilder<T> {
...
public T build();
...
}
```

An object of the generated message would just return itself.
### Second approach

Change somehow the setter in the generated message builder.
- Visitor Pattern
- etc.

Those are only the approaches i quickly came up with. 

Greetings from Germany,
mike

**Comment by xfxyjwf** [comment]
Sorry but I don't get what you are talking about. What are the "two setters generated for a message-type value" and what's the problem you are trying solve?

From "First apporach" it seems you are proposing adding a build() method to MessageOrBuilder, but from "Second approach" it sounds like you are talking about something completely different. I'm very confused...

**Comment by mickare** [comment]
Sry I was also confused. ^^

But let's consider this:

protbuf protocol:
```
message A {
}

...

message Packet {
  oneof content {
    A a = 1;
    ...
  }
}
```

Currently this is the way to go if you want to send B over the network with a **nice-to-use api**:
```
// Packet
public void send(Packet packet) {
  doSomething(packet);
}
public void send(Packet.Builder builder) {
  send(builder.build);
}

// A
public void send(A a) {
  send(Packet.newBuilder().setA(a));
}
public void send(A.Builder builder) {
  send(builder.build);
}
...
```

This is twice the amount of methods to achieve a nice api, which would look like this:
```
// Packet
public void send(PacketOrBuilder packet) {
  doSomething(packet.build());
}

// A
public void send(AOrBuilder a) {
  send(Packet.newBuilder().setA(a));
}
...
```

In the generated Java classes the builder and messages  of each A, ...  and Packet share a generated *Message*OrBuilder interface.
So there is already a common and shared interface that is only waiting to be used like that.

**Comment by xfxyjwf** [comment]
Thanks for the explanation. I see what you are proposing now.

**Comment by mickare** [comment]
Should I change the title from
*Single value setter for MessageOrBuilder interface (3.0.0-beta-1)*
to
*Only one setter per value by adding method build() to MessageOrBuilder interface (3.0.0-beta-1)
?

**Comment by xfxyjwf** [comment]
How about just "Add a build() method to MessageOrBuilder interface"?

**Comment by bpourkazemi** [comment]
+1

**Comment by elharo** [comment]
We probably can't add methods to existing interfaces until we drop support for Java 7 for backwards compatibility reasons.
