### ISSUE TITLE
python import error, when there are files with the same name in different project. 

### ISSUE THREAD

**Issue by EthanZhangYi** [protocolbuffers/protobuf#9623]
When there are two repo:
```
project_a/
    - base.proto
project_b/
    - base.proto
```
In python
```
import project_a.base_pb2 as A
import project_b.base_pb2 as B
```
An error will be raised.
```
TypeError: Couldn't build proto file into descriptor pool!
```
How to fix it?

**Comment by haberman** [comment]
How are you running `protoc`?

When you run `protoc` avoid using `-Iproject_a` or `-Iproject_b`. You need to let protoc see the full path of the proto (eg `project_a/base.proto` and `project_b/base.proto`) so that it does not appear to be a duplicate filename.
