### ISSUE TITLE
AttributeError: WhichOneOf

### ISSUE THREAD

**Issue by gzzo** [protocolbuffers/protobuf#9625]
**What version of protobuf and what language are you using?**
Version: 3.19.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**
OSX

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.7.7

**What did you do?**
```
syntax = "proto3";

message A {
    int32 first = 1;
}

message B {
    int32 second = 1;
}

message C {
    oneof payload {
        A a = 1;
        B b = 2;
    }
}
```

```
c = C()
a = A()
a.first = 1
c.a.CopyFrom(a)

print(c.WhichOneOf("payload"))
```

**What did you expect to see**
`a`

**What did you see instead?**
`AttributeError: WhichOneOf`

**Comment by gzzo** [comment]
This also happens without the `CopyFrom`, so just doing `C().WhichOneOf("payload")` causes the issue

**Comment by esorot** [comment]
```python
assert message.WhichOneof("test_oneof") is None
message.name = "Bender"
assert message.WhichOneof("test_oneof") == "name"
```
https://developers.google.com/protocol-buffers/docs/reference/python-generated#oneof
Looks like you have a typo
