### ISSUE TITLE
repeated Enums fail to optimize like repeated int32

### ISSUE THREAD

**Issue by kjeet** [protocolbuffers/protobuf#9639]
**What version of protobuf and what language are you using?**
Version:  3.6.1 and 3.15.8
Language: Java

**What operating system (Linux, Windows, ...) and version?**
All

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC, I think

**What did you do?**
Compile `A.proto` with `protoc -I=. --java_out=OUT/ A.proto` with a protoc from version 3.6.1 and 3.15.8.
```$ cat A.proto
syntax = "proto3";
message Example {
  repeated int32 ages = 1;
  repeated Pet pets = 2;

  enum Pet { DOG = 0; CAT = 1; BIRD = 2; }
}
```

**What did you expect to see**
I expected to see, from A.java generated by 3.6.1 (with line numbers)
```
285     private java.util.List<java.lang.Integer> ages_;
308     private java.util.List<java.lang.Integer> pets_;
```

and from A.java generated by 3.15.8 (with line numbers)
```
313     private com.google.protobuf.Internal.IntList ages_;
341     private com.google.protobuf.Internal.IntList pets_;
```

**What did you see instead?**
Instead I saw from A.java generated by 3.6.1 (with line numbers)
```
285     private java.util.List<java.lang.Integer> ages_;
308     private java.util.List<java.lang.Integer> pets_;
```

and from A.java generated by 3.15.8 (with line numbers)
```
313     private com.google.protobuf.Internal.IntList ages_;
341     private java.util.List<java.lang.Integer> pets_;
```

I expected both fields to leverage the optimizations that come with an unboxed `IntList` over an `ArrayList<Integers>` by switching to version  3.15.8.

**Comment by kjeet** [comment]
Poking around, it looks like all the changes are confined to https://github.com/protocolbuffers/protobuf/blob/2d69d44cc18beaa0a3a62d353f80aead669abb5c/src/google/protobuf/compiler/java/java_enum_field.cc

**Comment by deannagarcia** [comment]
Thanks for this report and investigation! I'm going to work on an internal fix and will update this thread accordingly.

**Comment by kjeet** [comment]
Hi @deannagarcia ! Thanks for taking a look. I'd love to know how it's going and if it's as straightforward as I'd hoped.

**Comment by deannagarcia** [comment]
I'm still working on it, been distracted by other things and I need to run benchmarks to prove that this will get the optimization we expect. Will keep you updated!

**Comment by deannagarcia** [comment]
I implemented this change and ran benchmarks. Unfortunately, the change caused significant slow downs in all of our benchmarks. 

Due to these results, we will likely not be implementing this change. If you have a specific use case and data to prove the speed up I can take another look, but that speed up would also have to be large enough to make up for the slow downs in the other benchmarks.
