### ISSUE TITLE
Generated code doesn't compile if lowercase type name conflicts with file name

### ISSUE THREAD

**Issue by Scottmitch** [protocolbuffers/protobuf#9653]
**What version of protobuf and what language are you using?**
Version: 3.19.2
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS 12.2.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
OpenJDK 17.0.2+8

**What did you do?**
`test_conflict_message3.proto`:
```proto
syntax = "proto3";
option java_multiple_files = true;
option java_package = "example";
// don't specify java_outer_classname
// This name conflicts with the what protobuf computes the outer file name,
// but has lower case first char
message testConflictMessage3 {}
```

`test_conflict_enum3.proto`:
```proto
syntax = "proto3";
option java_multiple_files = true;
option java_package = "example";
// don't specify java_outer_classname
// This name conflicts with the what protobuf computes the outer file name,
// but has lower case first char
enum testConflictEnum3 {
  A = 0;
}
```

**What did you expect to see**
- No compile errors
- Class `testConflictMessage3` in package `example` with message generated code
- Class `TestConflictMessage3OuterClass` in package `example` with generated descriptor methods/data
- Class `testConflictEnum3` in package `example` with enum generated code
- Class `TestConflictEnum3OuterClass` in package `example` with generated descriptor methods/data 

**What did you see instead?**
```bash
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:13: error: class testConflictMessage3 is public, should be declared in a file named testConflictMessage3.java
public final class testConflictMessage3 extends
             ^
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictEnum3.java:13: error: enum testConflictEnum3 is public, should be declared in a file named testConflictEnum3.java
public enum testConflictEnum3
       ^
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:76: error: cannot find symbol
    return example.TestConflictMessage3.internal_static_testConflictMessage3_descriptor;
                  ^
  symbol:   class TestConflictMessage3
  location: package example
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:82: error: package example.TestConflictMessage3 does not exist
    return example.TestConflictMessage3.internal_static_testConflictMessage3_fieldAccessorTable
                                       ^
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:244: error: cannot find symbol
      return example.TestConflictMessage3.internal_static_testConflictMessage3_descriptor;
                    ^
  symbol:   class TestConflictMessage3
  location: package example
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:250: error: package example.TestConflictMessage3 does not exist
      return example.TestConflictMessage3.internal_static_testConflictMessage3_fieldAccessorTable
                                         ^
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictMessage3.java:279: error: cannot find symbol
      return example.TestConflictMessage3.internal_static_testConflictMessage3_descriptor;
                    ^
  symbol:   class TestConflictMessage3
  location: package example
/Users/scott/git/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/example/TestConflictEnum3.java:83: error: cannot find symbol
    return example.TestConflictEnum3.getDescriptor().getEnumTypes().get(0);
                  ^
  symbol:   class TestConflictEnum3
  location: package example
```

**Comment by elharo** [comment]
Compiling on Linux I see

```
$ protoc --java_out=/tmp  test_conflict_message3.proto
[libprotobuf WARNING google/protobuf/compiler/java/java_file.cc:232] test_conflict_message3.proto: The file's outer class name, "TestConflictMessage3", matches the name of one of the types declared inside it when case is ignored. This can cause compilation issues on Windows / MacOS. Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file to be safe.
```

That suggests this is a known issue, but perhaps we should emit a better error message on Mac/Windows?

**Comment by elharo** [comment]
I see the same message on my MacBook. What's realy weird is that on Linux I get

```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_conflict_message3.proto

package example;

public final class TestConflictMessage3 {
``` 

but on my MacBook I get

```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_conflict_message3.proto

package example;

/**
 * <pre>
 * don't specify java_outer_classname
 * This name conflicts with the what protobuf computes the outer file name,
 * but has lower case first char
 * </pre>
 *
 * Protobuf type {@code example.testConflictMessage3}
 */
public final class testConflictMessage3 extends
```

**Comment by elharo** [comment]
I'm using protoc 3.18.0 on the MacBook and 3.19.4 on Linux. This could explain the difference in comments, but why the difference in the capitalization of the class name?

**Comment by elharo** [comment]
Upgraded my MacBook to 3.19.4 but that didn't change anything. Perhaps gLinux was built from head and not 3.19.4?

**Comment by elharo** [comment]
I suppose we could sidestep this by compiling straight to jar files without materializing the .java files on disk, but I seriously doubt that's worth the effort.

**Comment by Scottmitch** [comment]
I suspected it was due to case-sensitive quirks. In other scenarios protobuf's way to handle name conflicts with types is to append [OuterClass](https://github.com/protocolbuffers/protobuf/blob/2d69d44cc18beaa0a3a62d353f80aead669abb5c/src/google/protobuf/compiler/java/java_name_resolver.cc#L49) to the top level file/typename. Does it make sense to handle this case in the same way? If that was the case the generated type names would be the same between `java_multiple_files = true` (top level file, first char lower case, class matches file name) but just be located in a different spot as `java_multiple_files = false` (embedded in the top level type that doesn't have any name conflicts and doesn't need `OuterClass` suffix).

**Comment by elharo** [comment]
That would likely be incompatible with how it works presently on Linux. The real disconnect here is in Java, which believes that test.java and Test.java are two different files.

**Comment by andyfurnival** [comment]
I have the same problem

I have in a file called I18nLangPStringPair.proto
```syntax = "proto3";
package md;

option java_multiple_files = true;
option java_package = "com.ps.proto.md";


message I18nLangPStringPair {
 uint32 locale = 1;
 string str = 2;
}
```

Once I have run protobuf compile (3.19.4) it generates a class name called I18**n**LangPStringPair, but a filename called I18**N**LangPStringPair.java. - this capitalisation of the java file just occurs arbitrarily for some reason in this example, but I have another message which starts with a lowercase, also gets automatically capitalised.

What is the purpose  to alter the file name of the generated class, from the source protobuf definition? Should they not match in case and letters?  

I'm on Apple Silicon MacOS 12.3.1

**Comment by deannagarcia** [comment]
This is working as intended. The generated class name is transformed with `UnderscoresToCamelCase` [here](https://github.com/protocolbuffers/protobuf/blob/2d69d44cc18beaa0a3a62d353f80aead669abb5c/src/google/protobuf/compiler/java/java_name_resolver.cc#L154). That function is defined [here](https://github.com/protocolbuffers/protobuf/blob/2d69d44cc18beaa0a3a62d353f80aead669abb5c/src/google/protobuf/compiler/java/java_helpers.cc#L207) to capitalize every letter that is preceded by a non-alpha character. This follows protobuf's general enforcement of camel case for fields as well.

**Comment by Scottmitch** [comment]
JLS specifies that top level type name and file name should match [1], which is what the compile errors [2] refers to. The bug is that the generation is not consistently camel casing the file name and type name for top level types.

[1] https://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.6
> If and only if packages are stored in a file system ([§7.2](https://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.2)), the host system may choose to enforce the restriction that it is a compile-time error if a type is not found in a file under a name composed of the type name plus an extension (such as .java or .jav) if either of the following is true:
> The type is referred to by code in other compilation units of the package in which the type is declared.
> The type is declared public (and therefore is potentially accessible from code in other packages).

[2] `error: class testConflictMessage3 is public, should be declared in a file named testConflictMessage3.java`

**Comment by elharo** [comment]
@andyfurnival I don't think what you're describing is the same problem, though the symptoms look similar. Please open a new issue to track this, though it might indeed be working as intended.

**Comment by DanielLiu1123** [comment]
I ran into the same issue: the generated outer class overrides the `UserName` message. Is it possible to make the compiler smarter so that the generated outer class is named `UsernameOuterClass` instead of `Username`? In practice, very few people explicitly set the outer class since it’s not that important. A simpler approach could be to just use “filename in CamelCase + OuterClass” as the outer class name.

Reproduce:

```shell
mkdir -p proto-test/out && cd proto-test

cat > username.proto <<'EOF'
syntax = "proto3";

package user.v1;

option java_multiple_files = true;

message UserName {
  string first_name = 1;
  string last_name = 2;
}
EOF

protoc --java_out=./out username.proto

tree out
```
