### ISSUE TITLE
How to support package option for a custom CLI?

### ISSUE THREAD

**Issue by BuddhiWathsala** [protocolbuffers/protobuf#9656]
We have implemented a custom CLI to generate relevant [Ballerina language](https://ballerina.io/) stubs from a given protobuf file. Now, we need to support a protobuf package option in our CLI. Something like Java and Go packages;

```proto
option go_package = "example.com/messages1";
```
```proto
option java_package = "com.example.tutorial.protos";
```

Our idea is to have something like,
```proto
option ballerina_package = "example.com/messages1";
```

As far as we understood, to address that, we can either:
- contribute to the [descriptor.proto]( https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L341) OR
- introduce a custom file option

We want to know, what would be the standard procedure to introduce such an option from the protobuf perspective?. What is your opinion on this requirement?.

**Comment by acozzette** [comment]
A custom file option is the way to go. You can send us a pull request to update docs/options.md to allocate an extension number for this.
