### ISSUE TITLE
use struct deserialization error in c#

### ISSUE THREAD

**Issue by liyou54** [protocolbuffers/protobuf#9658]
I want to change warp file from class to csharp
then I change the type :
![image](https://user-images.githubusercontent.com/33220619/159402402-5a952a22-4ad3-4f12-af4d-87176e5b3a4e.png)
buf error happen ,finally I find the error happen at 
![image](https://user-images.githubusercontent.com/33220619/159402649-46ced630-2430-40b6-93b4-ebb475c1ceb4.png)
![image](https://user-images.githubusercontent.com/33220619/159402676-ae892805-6124-468a-8d71-2689ad31e0ae.png)
it check T is struct or no ，
How can I solve this

**Comment by jskeet** [comment]
I'm finding it hard to understand what you're attempting to do - but fundamentally, if you're manually changing the generated code to write messages as structs instead of classes, I wouldn't expect that to work, and I wouldn't expect us to support that.

**Comment by xoofx** [comment]
> I'm finding it hard to understand what you're attempting to do - but fundamentally, if you're manually changing the generated code to write messages as structs instead of classes, I wouldn't expect that to work, and I wouldn't expect us to support that.

@jskeet Should I open an issue to allow to use a struct for message in [message options](https://github.com/protocolbuffers/protobuf/blob/b5a35bcc7e4cc4ff00eb105449b300fca3a8b0d2/src/google/protobuf/descriptor.proto#L466) like:

```proto
message MyMessage {
    option csharp_generate_struct = true;
    // fields...
}
```

When streaming data, you might want to really avoid any kind of managed allocations between client and servers and the protobuf doesn't allow to take benefit of this in C#. We should be able to specify such bebavior.

**Comment by jskeet** [comment]
You can file a feature request, but I make no promises that I'll get to it at all. Aside from anything else, there's a *lot* of code that uses `IMessage`, so without a huge amount of work you'd end up boxing the structs anyway.

If you want to investigate implementing this yourself, that's at least *more likely* to get somewhere - but again, I make no promises that we'd want to accept the changes. (If it drops out neatly without any breaking changes and without constraining future work, then *maybe* - but that seems unlikely.)

**Comment by liyou54** [comment]
I have change the Code and it can work
First I change the TypeSupportsPacking 
![image](https://user-images.githubusercontent.com/33220619/160284639-dd09aaa3-71eb-4731-a5c0-d75f16a60ec3.png)
Then I overload the methon ReadMessage
![image](https://user-images.githubusercontent.com/33220619/160284771-f0ce2ab1-297c-448e-8a02-f4ef8af1b40a.png)

**Comment by liyou54** [comment]
What's wrong with what I did

**Comment by xoofx** [comment]
Your changes are not going to work with struct. This should use proper generic in google protobuf and it requires to few additions there. You can't add struct support just by modifying the generated code as explained by @jskeet.

**Comment by liyou54** [comment]
thanks lot

**Comment by liyou54** [comment]
but it really work and the data have serialized 
![image](https://user-images.githubusercontent.com/33220619/160285645-6673e007-e451-4fc7-8b41-1aa16c8f9f38.png)

**Comment by jskeet** [comment]
If you believe you have a complete solution, please create a pull request with everything in, including comprehensive tests.

I can easily imagine a situation where you've got *some* parts working but not others - or potentially you have things working but with frequent boxing.

I'm afraid posting a lot of screenshots of code really isn't going to help to progress this.

**Comment by liyou54** [comment]
OK，Maybe you're right, this can go wrong in some cases. I should have run more tests
