### ISSUE TITLE
Please remove 4.0.0RC* from pecl

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#9660]
Version 4.0.0 was never released, and this is very confusing for users:

```
# pecl list-upgrades
...
pecl.php.net Available Upgrades (stable):
=========================================
Channel      Package  Local            Remote          Size
pecl.php.net protobuf 3.20.0RC2 (beta) 4.0.0RC2 (beta) 188kB
```

(this only affects users of beta versions)

**Comment by simonberger** [comment]
This repository also has a 3.20.0 tag which came around the same time as 3.20.0-rc3. It is not on packagist but rc3 isn't as well. Was this a mistake?

**Comment by perezd** [comment]
Are we allowed to yank a published version? I was under the impression this was normally considered a bad idea.

**Comment by remicollet** [comment]
> Are we allowed to yank a published version? 

> I was under the impression this was normally considered a bad idea.

Indeed, should be used carefully, but I think such issue justify it

**Comment by deannagarcia** [comment]
Unfortunately we have made the decision to not yank any 4.0.0 releases in order to stay consistent and not take the risk in yanking a published version.
