### ISSUE TITLE
Enum String() resulting in panic

### ISSUE THREAD

**Issue by subuqq** [protocolbuffers/protobuf#9663]
**What version of protobuf and what language are you using?**
Version: Proto3.
github.com/golang/protobuf v1.5.2/go.mod h1:XVQd3VNwM+JqD3oG2Ue2ip4fOMUkwXdXDdiuN0vRsmY=
Language: Go

**What operating system (Linux, Windows, ...) and version?** Windows10

**What runtime / compiler are you using (e.g., python version or gcc version)** 
see above
**What did you do?**
Create a simple Enum file
```
syntax = "proto3";

option go_package = "github.com/subuqq/Automata/common";

package common;

enum TestEnum {
  TestEnum_INVALID = 0;
  APPLE = 1;
  ORANGE = 2;
}

```

Generate Go classes
```

protoc -I . --go_out=./common --go_opt=module=github.com/subuqq/Automata/common --go-grpc_out=./common --go-grpc_opt=module=github.com/subuqq/Automata/common protos/test_enum.proto 
```

This generates a Go file with no initialization of enumTypes
```

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_test_enum_proto_enumTypes[0].Descriptor()
}
...
var file_protos_test_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_test_enum_proto_goTypes = []interface{}{
	(TestEnum)(0), // 0: common.TestEnum
}
...
```

**What did you expect to see**
String should work
**What did you see instead?**
Panic from nil pointer reference above
```
anic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x78 pc=0x449ea2]

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.Export.EnumStringOf({}, {0x0, 0x0}, 0x1)
	C:/Users/subu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/api_export.go:75 +0x22
github.com/subuqq/Automata/common.TestEnum.String(...)
	C:/Users/subu/go/src/github.com/subuqq/Automata/common/test_enum.pb.go:52
...
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by elharo** [comment]
Go bugs go here: https://github.com/golang/protobuf/issues
