### ISSUE TITLE
Fix generated Python imports

### ISSUE THREAD

**Issue by darkdragon-001** [protocolbuffers/protobuf#9667]
**What version of protobuf and what language are you using?**
Version: v3.12.4
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Debian 11

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc

**What did you do?**
Proto structure:
```
pkg1
  pkg2
    file.proto
```
with
```protobuf
// file.proto
message MyType {
  uint64 my_field = 1;
}
```

Run protobuf python compiler:
```sh
protoc --python_out=. --proto_path=.
```

**What did you expect to see**
```python
# file pkg1/pkg2/__init__.py
from .file_pb2 import *
```

Such that I can use it like
```python3
import pkg1.pkg2.MyType
```

**What did you see instead?**
I need to import
```python3
import pkg1.pkg2.file_pb2.MyType
```

**Workaround**
I am running the additional method on the generated files:
```python3
def create_init_py_recursive(package_dir):
    package_files = []
    for package_node in package_dir.iterdir():
        if package_node.is_dir():
            subpackage_files = create_init_py_recursive(package_node)
            init = package_node / "__init__.py"
            with open(init, "w") as f:
                for subpackage_file in subpackage_files:
                    if subpackage_file.name == '__init__.py':
                        continue
                    f.write(f"from .{subpackage_file.stem} import *\n")
        elif package_node.is_file() and package_node.suffix == '.py':
            package_files.append(package_node)
    return package_files
```

**Additional references**
All other programming language bindings hide the name of the proto file from the user and only take package names into account as described in the [documentation](https://developers.google.com/protocol-buffers/docs/proto3#packages).

**Comment by anandolee** [comment]
The behavior is expected and also avoid name conflict between different .proto files.

**Comment by darkdragon-001** [comment]
@anandolee

> The behavior is expected and also avoid name conflict between different .proto files.

How do other languages deal with these possible conflicts? I guess one anyways cannot produce such conflicts as bindings for other languages will fail then. This also also what a `package` concept is supposed to work like.

> Change the behavior will also break users

How does adding _additional_ files break for existing users? They can still continue to import directly from these files but now, they _also_ have the possibility of using the convenience imports...
