### ISSUE TITLE
Failed to Build Visual Stuido C++ Project  with .pb.h and .pb.cc 

### ISSUE THREAD

**Issue by CodeFish711** [protocolbuffers/protobuf#9676]
**What version of protobuf and what language are you using?**
Version: protobuf-3.19.4
Language: C++ 14

**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC 19.29.30141.0
CMake 3.22.0 -- Configure BUILD_SHARED_LIBS 

**What did you do?**
1. build Release x64 protobuf.sln using Visual Studio 2019

> libprotobuf.dll
> libprotobuf.lib
> libprotoc.dll
> libprotoc.lib
> protoc.exe

2. Write my test.proto
```
syntax = "proto3";

package test;

message Person {
  optional string name = 1;
  optional int32 id = 2;
  optional string email = 3;
}

```
3. run ```.\protoc.exe --cpp_out=./ .\test.proto```

> test.pb.h
> test.pb.cc

4. Create Simple **Hello_World** ConsoleApplication using using Visual Studio 2019 Release x64

> add src ```test.pb.h``` and ```test.pb.cc```
> add link lirary ```libprotobuf.lib``` and ```libprotoc.lib```
> add include dir ```google```
> copy DLL ```libprotobuf.dll``` and ```libprotoc.dll```
> #include "test.pb.h"

5. Build 

**What did you expect to see**
build suceess
**What did you see instead?**

> Error LNK2001	unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)

And once I opened "test.pb.h" in vs editor, hundreds of errors occured
e.g some macro marked error
```PROTOBUF_NAMESPACE_OPEN```
Error (active)	E0077	this declaration has no storage class or type specifier

```::PROTOBUF_NAMESPACE_ID::```
Error (active)	E0276	name followed by '::' must be a class or namespace name

Furthermore, if ```import "google/protobuf/any.proto";```

> Error LNK2001	unresolved external symbol "struct google::protobuf::AnyDefaultTypeInternal google::protobuf::_Any_default_instance_" (?_Any_default_instance_@protobuf@google@@3UAnyDefaultTypeInternal@12@A)	

How Can I correctly build? Thanks a lot!!!

**Comment by SMaton** [comment]
No solution to this yet?

**Comment by sigaaron** [comment]
same issue. I add PROTOBUF_USE_DLLS  to predefined macros in vs, the error will be eliminate. but I get a lot of stl export warnings

**Comment by vasdev8** [comment]
changing the "_C++ Language Standard_" to _"ISO C++ 17 Standard (/std:c++17)"_ resolved the header issues _"Error (active) E0077_".
Other issues can be resolved using the solution mentioned [above ](https://github.com/protocolbuffers/protobuf/issues/9676#issuecomment-1150018090)by @sigaaron.

**Comment by harryqk** [comment]
same problem, but can build, run without error

**Comment by KuiLeiZS** [comment]
same problem,but my OS is Ubuntu 18.04
And once I opened "test.pb.h" in vs code, hundreds of errors occured
e.g some macro marked error
PROTOBUF_NAMESPACE_OPEN
Error (active) E0077 this declaration has no storage class or type specifier

::PROTOBUF_NAMESPACE_ID::
Error (active) E0276 name followed by '::' must be a class or namespace name
How Can I correctly build? Thanks a lot!!!!!!!!!!!!!!!!!!

**Comment by nbreen** [comment]
I am having the same issue. Compiling with Visual Studio 2022. I've tried the suggestions by @vasdev8 and @sigaaron with no luck

**Comment by imadourabi** [comment]
Same issue here in VS 2022.
However, when I open the project as a folder (not as solution), it seems likely to work, although, this is not the desired solution for this issue.

**Comment by huaqfantasy** [comment]
1. I have same issue in vs2019 when i build grpc examples. 
2. I try to enable grpc_MSVC_STATIC_RUNTIME ,protobuf_MSVC_STATIC_RUNTIME,Cares_MSVC_STATIC_RUNTIME in cmake configuration，then I try to generate a static lib by”*.grpc.pb.cc“、”*.grpc.pb.h“、”*.pb.cc“、”*.pb.h“rather than dynamic library.
3. although it still have errors such as E0077,but it build success 。
4. According to the header file "<google/protobuf/port_def.inc>",The definitions in this file are intended to be portable across Clang,GCC, and MSVC. Function-like macros are usable without an #ifdef guard. Syntax macros (for example, attributes) are always defined, although they may be empty.
5. maybe just the IntelliSense error?

**Comment by onlyou2030** [comment]
Same issue in VS2022.

**Comment by historyliao** [comment]
> changing the "_C++ Language Standard_" to _"ISO C++ 17 Standard (/std:c++17)"_ resolved the header issues _"Error (active) E0077_". Other issues can be resolved using the solution mentioned [above ](https://github.com/protocolbuffers/protobuf/issues/9676#issuecomment-1150018090)by @sigaaron.

changing standard to c++17  successfully clears errors

**Comment by jotalanusse** [comment]
Still having this issue (#17076), updating CPP Standard to c++17 did not fix the errors.
