### ISSUE TITLE
clang-tidy reports errors with protobuf headers on Windows

### ISSUE THREAD

**Issue by giles45** [protocolbuffers/protobuf#9680]
**What version of protobuf and what language are you using?**
Version: 3.19.4
Language: C++ (17)

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang-tidy 13.0.0

**What did you do?**
1. Create any simple protobuf message defintion and use protoc to create the C++ bindings. And then include the header in C++ program. E.g.
```
syntax = "proto3";

message TestMessage {
	string id = 1;
}
```

```
protoc --cpp_out=. test.proto
```

```
#include <iostream>
#include "test.pb.h"

int main()
{
    std::cout << "Hello World!\n";
}

```

2. Run clang-tidy on the file. There is no .clang-tidy file in the directory hierarchy. i.e. it's running with defaults.

compile_commands.json
```
[
  {
    "directory": "C:\\workspace\\utc\\scratch\\TestApp",
    "command": "\"C:\\Windows\\system32\\CL.exe\" \/c \/I\"C:\\workspace\\utc\\scratch\\TestApp\\vcpkg_installed\\x64-windows\\x64-windows\\include\" \/ZI \/JMC \/nologo \/W3 \/WX- \/diagnostics:column \/Od \/D _DEBUG \/D _CONSOLE \/D _UNICODE \/D UNICODE \/EHsc \/RTC1 \/MDd \/GS \/fp:precise \/std:c++17 \/permissive- \/Fo\"x64\\Debug\\\\\" \/Gd \/TP   \"C:\\workspace\\utc\\scratch\\TestApp\\test.cpp\"",
    "file": "C:\\workspace\\utc\\scratch\\TestApp\\test.cpp"
  }
]
```

```
clang-tidy -p=x64\Debug\TestApp.ClangTidy\ test.cpp
```

3. See error 'an attribute list cannot appear here'

```
Error while processing C:\workspace\utc\scratch\TestApp\test.cpp.
warning: argument unused during compilation: '/ZI' [clang-diagnostic-unused-command-line-argument]
C:\workspace\utc\scratch\TestApp\vcpkg_installed\x64-windows\x64-windows\include\google/protobuf/parse_context.h:790:17:
 error: an attribute list cannot appear here [clang-diagnostic-error]
PROTOBUF_EXPORT PROTOBUF_NODISCARD const char* InlineGreedyStringParser(
                ^
C:\workspace\utc\scratch\TestApp\vcpkg_installed\x64-windows\x64-windows\include\google/protobuf/port_def.inc:463:28: note: expanded from macro 'PROTOBUF_NODISCARD'
#define PROTOBUF_NODISCARD [[nodiscard]]
                           ^~~~~~~~~~~~~
C:\workspace\utc\scratch\TestApp\vcpkg_installed\x64-windows\x64-windows\include\google/protobuf/parse_context.h:862:17:
 error: an attribute list cannot appear here [clang-diagnostic-error]
PROTOBUF_EXPORT PROTOBUF_NODISCARD const char* PackedInt32Parser(

...
Error output truncated.

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

In this build environment PROTOBUF_EXPORT expands to __declspec(dllimport)

**Anything else we should know about your project / environment**
The project is actually built against MSVC (2022) but we use clang-tidy for static analysis checks. clang-tidy is as supplied by Visual Studio.
MSVC compiles this program without issue.

This issue didn't happen with the previous version of Protobuf. We were using 3.18.0. Now 3.19.4.

clang-tidy looks to be complaining about the fact that [[nodiscard]] is appearing after __declspec(dllimport) - i.e. rather
than 

```
PROTOBUF_EXPORT PROTOBUF_NODISCARD const char* InlineGreedyStringParser(
// expands to __declspec(dllimport) [[nodiscard]] const char* InlineGreedyStringParser(
```

it should be

```
PROTOBUF_NODISCARD PROTOBUF_EXPORT const char* InlineGreedyStringParser(...
// expands to [[nodiscard]] __declspec(dllimport) const char* InlineGreedyStringParser(
```

With compiler explorer it can be seen that this error would also occur with clang (when compiling with ms extensions)

https://godbolt.org/z/Yr8o7dnKj

**Comment by mkruskal-google** [comment]
This is fixed by https://github.com/protocolbuffers/protobuf/commit/1d2e8d93027d988f497a4690eb47ece1fe47d665
