### ISSUE TITLE
Add support for generating a struct for a message type in C#

### ISSUE THREAD

**Issue by xoofx** [protocolbuffers/protobuf#9682]
Follow-up of #9658

This is important when passing messages that would be better represented as plain struct in C#, to avoid lots of allocations (e.g a `Point { float x, float y }` with a `repeated Point points` on it)

The idea is to support generating struct for message types by having an option on the message:

```
message MyMessage {
    option csharp_generate_struct = true;
    // fields...
}
```

The generated code for serialization/deserialization should generate optimal code using struct with by ref/in.

**Comment by jskeet** [comment]
As per the other issue, I still believe would be a very, very large amount of work to implement and make sure we get "right", particularly with regard to reflection. I very much doubt we'll get to this earlier than a rather larger revamp which would probably include using record types.

**Comment by AqlaSolutions** [comment]
I need this

**Comment by stebet** [comment]
@jskeet Is there a way to have this triaged and put on the backlog if there is enough interest? I have a feeling with the increasing amount of gRPC usage in .NET code that people really might want this feature to reduce allocations for high-traffic services. Is a revamp as you mention the possibility of to support record types as well on the radar? CC: @davidfowl @JamesNK

**Comment by jskeet** [comment]
@stebet: There's no specific backlog that I'd put it on. But I really don't anticipate having the time to devote to considering all the many, many implications of this any time in the near future I'm afraid. It's just a *huge* change - and one that I can't justify spending large amounts of time on.

**Comment by jskeet** [comment]
@AqlaSolutions: I'm not saying it wouldn't be potentially worthwhile. I'm saying that it's a huge amount of work, and not something I have capacity for at the moment, or in the foreseeable future.

**Comment by stebet** [comment]
> @stebet: There's no specific backlog that I'd put it on. But I really don't anticipate having the time to devote to considering all the many, many implications of this any time in the near future I'm afraid. It's just a *huge* change - and one that I can't justify spending large amounts of time on.

Not the answer I was hoping for but I do appreciate the honest answer regardless. I realize it's a "niche" request in the grand scheme of things.

**Comment by jskeet** [comment]
> Since it’s a short term servicing release, it’s more suitable for making infra changes

The .NET release cycle isn't the Protobuf release cycle. Protocol Buffers is not a .NET project that decides when to make breaking changes based on the .NET support dates.

> Anyway, I suggest that we reopen this issue to be handled this year.

If you're willing to put all the very, very significant amount of effort required into writing a comprehensive design doc covering both the generator and runtime to ensure backward compatibility, think about all the corner cases around boxing, mutability etc, and then do the implementation, then I'd be happy to look at the design doc. But I doubt that anyone within the Protocol Buffers team is going to have cycles to put significant work into it.
