### ISSUE TITLE
Docs on the necessity of --experimental_allow_proto3_optional are outdated

### ISSUE THREAD

**Issue by Leedehai** [protocolbuffers/protobuf#9684]
Doc [protobuf/docs/implementing_proto3_presence.md](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md) mentioned using option `--experimental_allow_proto3_optional` to enable [the feature of explicit `optional` label in proto3](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md). However, protoc 3.19.4 is able to compile a `syntax = "proto3"` protocol file that uses the feature without needing this option on the command line.

Therefore, it seems the two docs linked above are outdated. Could you add a notice on those docs that the feature is no longer behind an experimental flag & since which version? Thanks.

**Comment by SanjayVas** [comment]
I believe this option is still needed in order for the presence accessors to be generated, at least in Java.
