### ISSUE TITLE
can't build with clang on windows

### ISSUE THREAD

**Issue by AndreyMlashkin** [protocolbuffers/protobuf#9685]
Initial report is for conan
https://github.com/conan-io/conan-center-index/issues/9965

**What version of protobuf and what language are you using?**
Version: 3.17.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang-cl 

**What did you do?**
1. install conan
2. make clang profile like this
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.runtime=MD
compiler.version=12
cppstd=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CC=clang-cl
CONAN_CMAKE_GENERATOR=Ninja
CXX=clang-cl
profile is in ~/.conan/profile/default

3.  conan install protobuf/3.17.1@ --build missing -u

**What did you expect to see**
successfull compilation

**What did you see instead?**

[24/202] Building RC object source_subfolder\cmake\CMakeFiles\protoc.dir\version.rc.res
FAILED: source_subfolder/cmake/CMakeFiles/protoc.dir/version.rc.res
"C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmcldeps.exe" RC D:\.conan\375717\1\build_subfolder\source_subfolder\cmake\version.rc source_subfolder\cmake\CMakeFiles\protoc.dir\version.rc.res.d source_subfolder\cmake\CMakeFiles\protoc.dir\version.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/Llvm/x64/bin/clang-cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe /l0x409 -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_ZLIB /fosource_subfolder\cmake\CMakeFiles\protoc.dir\version.rc.res D:\.conan\375717\1\build_subfolder\source_subfolder\cmake\version.rc
clang-cl: error: no such file or directory: '/l0x409'
clang-cl: error: no such file or directory: '/fosource_subfolder\cmake\CMakeFiles\protoc.dir\version.rc.res.dep.obj'
[25/202] Building CXX object source_subfolder\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\structurally_valid.cc.obj
clang-cl: warning: argument unused during compilation: '/MP' [-Wunused-command-line-argument]
[26/202] Building RC object source_subfolder\cmake\CMakeFiles\libprotobuf-lite.dir\version.rc.res
F

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by acozzette** [comment]
Let me close this since it appears to have been fixed in Conan. We actually don't have any involvement with the Conan package anyway.
