### ISSUE TITLE
Method to Unpack the protobuf Any message in c++  for  invalid type_url?

### ISSUE THREAD

**Issue by kruti11** [protocolbuffers/protobuf#9694]
Is there any method to unpack the protobuf message value  of "Any" type  for  type_url = "a.b.c"  (just the package name not having any slash)

**Comment by deannagarcia** [comment]
Unfortunately it is required that `type_url` have at least one slash: https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto#L128.
