### ISSUE TITLE
libprotobuf ERROR google/protobuf/message_lite.cc:449

### ISSUE THREAD

**Issue by creworkg** [protocolbuffers/protobuf#9716]
These two pictures show what I encountered:

![image](https://user-images.githubusercontent.com/99306490/161207602-4e0eda86-2fb8-42eb-88c5-2143ba9ad004.png)

![image](https://user-images.githubusercontent.com/99306490/161207625-36ca6b37-cf2a-4cd5-ba3c-422248a87cd2.png)

**Comment by perezd** [comment]
@acozzette can you look into this when you have a moment?

**Comment by acozzette** [comment]
@creworkg Could you post the full error log? The error message in your second screenshot is not a test failure but is just appearing there because the test is deliberately exercising an error code path. So there must be something else causing the test failure.

**Comment by deannagarcia** [comment]
Closing due to a lack of response, feel free to reopen to add more details if you are still seeing this error.
