### ISSUE TITLE
[Question] Use protobuf C++ within Matlab S-function Builder?

### ISSUE THREAD

**Issue by rebeccasc** [protocolbuffers/protobuf#9718]
Is there a way to use C++ protobuf within a [Matlab S-function Builder](https://de.mathworks.com/help/simulink/sfg/s-function-builder-dialog-box.html) (C++)?
More precisely: I have a Matlab Simulink model which includes a [Matlab S-function Builder](https://de.mathworks.com/help/simulink/sfg/s-function-builder-dialog-box.html) block. Within this block I want so serialize some data and send it via udp.

Using a windows machine I already tried the following steps:
1. installed protobuf via vcpkg: [`vcpkg install protobuf protobuf:x64-windows`](https://github.com/protocolbuffers/protobuf/blob/main/src/README.md#c-installation---windows)
2. created `addressbook.proto` as shown in the [example](https://developers.google.com/protocol-buffers/docs/cpptutorial) (here I used `syntax="proto3"` to match the current protobuf version)
3. created `addressbook.pb.h` and  `addressbook.pb.cc` using `protoc` as shown in the [example](https://developers.google.com/protocol-buffers/docs/cpptutorial)
4. placed the folder `<protobuf_folder>/include/google` in `<matlab_simulink_model_folder>/include` which is used as include folder for my Matlab Simulink Model
5. placed `<protobuf_folder>/lib/libprotobuf.lib` in  `<matlab_simulink_model_folder>/include`
6. placed `addressbook.pb.h` and  `addressbook.pb.cc` in  `<matlab_simulink_model_folder>/include`
7. In Matlab S-function Builder window -> Libraries: add path and entry of `addressbook.pb.h`  and `libprotobuf.lib` as descripted in section ["Use the Libraries Table to Specify External Code and Paths"](https://de.mathworks.com/help/simulink/sfg/s-function-builder-dialog-box.html) (for section scroll down)
8. Adding the header file `#include "addressbook.pb.h"`
9. Adding `GOOGLE_PROTOBUF_VERIFY_VERSION;` to the code

The error:
Compiling this fails with a lot of linker errors. Basically I can find the `addressbook.pb.h` but not the basic class `google::protobuf::Message` and it's methods.

What I checked:
I checked for the correct library for my architecture (it's x64)

Is this perhaps caused by different compile options (debug-flags, runtime library, etc.) of S-function and libprotobuf.lib? (I'm not very familiar with compiler stuff). 

Does anyone have any ideas on how to make it work?

Thanks in advance!

**Comment by perezd** [comment]
You'll be better off asking this sort of question on StackOverflow, we don't have any specific expertise/guidance/support to offer you here. Sorry!
