### ISSUE TITLE
[Question] Using the Java library, how to convert from protoText file to protoBinary ?

### ISSUE THREAD

**Issue by leobenkel** [protocolbuffers/protobuf#9720]
Hello,

I have a protoText file and I'd like to convert it to a binary format so i can be used by the library to parse incoming messages. Is there a way to do this using the library ? I'd hate to have to write the code to implement https://developers.google.com/protocol-buffers/docs/encoding :) 

Thank you !

**Comment by perezd** [comment]
Something like:

```
TextFormat.parse(protoTextString, YourProto.class).toByteArray();
```

Would convert the text string into a serialized message as bytes.
More docs:
https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TextFormat.html#parse-java.lang.CharSequence-java.lang.Class-
