### ISSUE TITLE
[Question] 3.20.0 Release in Maven Central

### ISSUE THREAD

**Issue by Scottmitch** [protocolbuffers/protobuf#9725]
[v3.20.0 release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0) was published on GitHub 8 days ago, but there is no corresponding artifact in [maven central](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java). Is this expected?

**Comment by Scottmitch** [comment]
possibly related/duplicate of https://github.com/protocolbuffers/protobuf/issues/9681

**Comment by fowles** [comment]
We have hit some snags in the 3.20 release, but it should get to maven central soon

**Comment by slachiewicz** [comment]
looks like [protoc-3.20.0-osx-aarch_64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-osx-aarch_64.zip) contains wrong binary - ie. contains bin for x86_64

**Comment by mkruskal-google** [comment]
3.20.0 is now release to maven central, sorry for the delay
