### ISSUE TITLE
SIGBUS with UnsafeUtil.getLong on Solaris

### ISSUE THREAD

**Issue by henryju** [protocolbuffers/protobuf#9728]
(Possibly related to old #3394 that is supposed to be fixed)

We have a user reporting SIGBUS error when using our product:

```text
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0xffffffff7e423198, pid=5198, tid=2
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.14+8) (build 11.0.14+8-LTS-263)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.14+8-LTS-263, mixed mode, tiered, compressed oops, g1 gc, solaris-sparc)
# Problematic frame:
# V  [libjvm.so+0x1823198]  Unsafe_GetLong+0x1c8
```

Here is the call stack:

```text
V  [libjvm.so+0x1823198]  Unsafe_GetLong+0x1c8
J 272  jdk.internal.misc.Unsafe.getLong(Ljava/lang/Object;J)J java.base@11.0.14 (0 bytes) @ 0xffffffff6a80e468 [0xffffffff6a80e320+0x0000000000000148]
j  sun.misc.Unsafe.getLong(Ljava/lang/Object;J)J+5 jdk.unsupported@11.0.14
j  com.google.protobuf.UnsafeUtil$MemoryAccessor.getLong(Ljava/lang/Object;J)J+6
j  com.google.protobuf.UnsafeUtil.getLong(Ljava/lang/Object;J)J+5
j  com.google.protobuf.Utf8$UnsafeProcessor.unsafeEstimateConsecutiveAscii([BJI)I+26
j  com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8([BII)Ljava/lang/String;+57
j  com.google.protobuf.Utf8.decodeUtf8([BII)Ljava/lang/String;+6
j  com.google.protobuf.CodedInputStream$StreamDecoder.readStringRequireUtf8()Ljava/lang/String;+95
j  org.sonarqube.ws.Settings$Setting.<init>(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)V+127
j  org.sonarqube.ws.Settings$Setting.<init>(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;Lorg/sonarqube/ws/Settings$1;)V+3
[...]
```

The message definition is available here:
https://github.com/SonarSource/sonarqube/blob/20afbdaec8a746a8d07624f5927f8ee14b32cf7f/sonar-ws/src/main/protobuf/ws-settings.proto#L88

**What version of protobuf and what language are you using?**
Version: 3.19.3
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Solaris Sparc 64bit

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.14+8-LTS-263, mixed mode, tiered, compressed oops, g1 gc, solaris-sparc)

**Comment by elharo** [comment]
Hmm, do we have a Solaris system anywhere I can test on?

**Comment by henryju** [comment]
Not sure if you were asking to me, but we don't have any. If you can't find one on your side, I can see if our customer would be able to help, but I can't promise.

**Comment by fan-yang-sonarsource** [comment]
Our customer can provide help, as long as it's not exposing customer data. @elharo could you please let me know what you want to test and how?

**Comment by elharo** [comment]
That comment was mostly for the google team. Solaris is not an OS we use anywhere that I know of so it might be tricky to debug this one.

**Comment by elharo** [comment]
#9415 looks suspicious, except that the dates don't line up. You're reporting this in 3.19.3 and that change shouldn't be present until at least 3.20.0. In fact, that change might already address this bug. I need to double check that #9415 made the cut for 3.20.0. Assuming that's true, can you try updating to 3.20.0 and see if this fixes things on your end?

**Comment by elharo** [comment]
I'm afraid it didn't make the cut, so no reason to test right now. However this should be fixed at HEAD in main if you'd like to try building from source and testing that. Otherwise it should be fixed eventually in 3.21.

**Comment by elharo** [comment]
NVM, I just checked and we haven't synced the fix in from google3 yet. I'll keep this bug open until we sync the change and let you know when it's available to test.

**Comment by elharo** [comment]
OK, I was wrong about all that. unsafeEstimateConsecutiveAscii still uses Unsafe at head so I need to dig into this further.

**Comment by elharo** [comment]
It appears cl/154976142 removed the eight-byte alignment code from `Utf8.unsafeEstimateConsecutiveAscii(byte[] bytes, long offset, final int maxChars)`. It probably just needs to be restored.

**Comment by fan-yang-sonarsource** [comment]
Hi @elharo, may I ask if you see the estimated time for this fix, please? Thank you.

**Comment by fan-yang-sonarsource** [comment]
@elharo Do you have any updates here? Many thanks.

**Comment by elharo** [comment]
Fixed in google3. (I hope. I have no easy way of testing this.) It should make it's way into Github on the next sync.

**Comment by fan-yang-sonarsource** [comment]
Hi @elharo, if I'm not wrong, the fix should be in 3.20.1-rc-1. Do you have any idea when it will be released? Thank you!

**Comment by elharo** [comment]
It won't be in 3.20.1. There was an issue with the first attempted fix internally. The second attempt has now been in production for a few days so it's probably good. I expect we'll sync the fix to Github sometime this week. It will probably be part of 3.21, but I don't know when that will be.

**Comment by fan-yang-sonarsource** [comment]
Thank you for the information. Could you please let me know when the fix is synced to Github so that I can follow the release?

**Comment by fan-yang-sonarsource** [comment]
@elharo sorry to bother you. Could you please let me know if the fix is synced to GitHub? Do you know if it will be in 3.21? Thank you so much!

**Comment by elharo** [comment]
The fix has been synced to Github

**Comment by fan-yang-sonarsource** [comment]
@elharo Do you have any timeline for the release of 3.21? Thank you!
