### ISSUE TITLE
JSON serialization produces invalid results for certain unicode values

### ISSUE THREAD

**Issue by jmarantz** [protocolbuffers/protobuf#9729]
*Version:* v3.19.4
*Language:* C++
*O/S:* Linux (5.15.15-1rodete2-amd64 #1 SMP Debian 5.15.15-1rodete2 (2022-02-23) x86_64 GNU/Linux)
*Compiler:* clang 13.0.1-3

**What did you do?**

Using Protobufs as a JSON string serializer, and differentially test/fuzz against other string serializer operations. There are several ranges of valid UTF-8 sequences where protobuf serialization produces incorrect values. In some cases protobuf serialization prints an error message and returns an empty string. In other cases it takes a valid 4-byte UTF-8 sequence and produces two unicode escapes, which is incorrect. It would be correct for it to return a single unicode escape or leave the UTF-8 sequence as is.

The code in question that behaves incorrectly is in a PR in the Envoy codebase, in a PR where we are trying to switch to a faster serializer but want to test and fuzz against protobuf behavior. We are working around this now by generating a list of unicodes where the protobuf serialization does not work as expected. 

The 3-byte UTF-8 sequences where protobuf serialization fails are discovered here: https://github.com/envoyproxy/envoy/blob/0fd80eef63bc9770186c4f4aa345ee63e464cab3/test/common/json/gen_excluded_unicodes.cc#L81

and the 4-byte ones are discovered here: https://github.com/envoyproxy/envoy/blob/0fd80eef63bc9770186c4f4aa345ee63e464cab3/test/common/json/gen_excluded_unicodes.cc#L109

The code in question ultimately calls `Protobuf::util::MessageToJsonString`.

The unicode ranges where the bad behavior occurs are:
```
    // Range of unicodes from 3-byte UTF8 sequences where protobuf serialization spews an error message
    // and returns an empty string
    [0xd800, 0xe000) from utf8 \355\240\200 ... \355\277\277

    // Unicode ranges generated from 4-byte utf-8 where protobuf serialization generates two small Unicode
    // values instead of the correct one.
    [0x1d173, 0x1d17b)  utf8  \360\235\205\263 ... \360\235\205\272
    [0xe0001, 0xe0002)  utf8  \363\240\200\201
    [0xe0020, 0xe0080)  utf8  \363\240\200\240 ... \363\240\201\277
```
 I will add the utf-8 sequences that get you to those unicodes.

**What did you expect to see**: valid hex unicode escapes, or pass-through the valid UTF-8

**What did you see instead?**: two incorrect unicode escapes, or an empty string.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by jmarantz** [comment]
The PR with the repro has now merged so I updated the description to reference the Envoy main branch rather than a PR.

**Comment by jorgbrown** [comment]
You said the problems are generated inside of `Protobuf::util::MessageToJsonString`.

What is the message that you are serializing?  Specifically, I assume you can repro this with a simple proto that just has a single field which is a string.  What are all the bytes of that string?

You mentioned these ranges as being problematic:

    [0xd800, 0xe000) 3-byte utf8 => these correspond to Unicode surrogates...
    [0x1d173, 0x1d17b)  4-byte utf8  => these correspond to musical symbols
    [0xe0001, 0xe0002)  4-byte utf8  => these correspond to tags
    [0xe0020, 0xe0080)  4-byte utf8  => these are also tags

For the first range, you said that the code "spews an error message".  Can you say what the error message is?  Your example cites D800 and DFFF but those are both undefined in unicode, so an error message would appear to be called for.

For the tag space, e0000 through e001f are either unallocated or deprecated.  e0020 through e007f are now emoji modifiers.  So again, it would seem these are potentially invalid, depending on context.

**Comment by jmarantz** [comment]
RE repro with a simple string: correct. I put the byte-sequence being serialized in the Issue description. Range is \355\240\200 ... \355\277\277.  but I can enumerate them more completely if you like.

RE error message: `[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:581] String field 'google.protobuf.Value.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. `

I think it's OK to return an error code if the input sequence generates a unicode that's not considered valid. However I think the inputs are all valid utf-8 based on the wikipedia definition of utf-8.

In any case I think it'd be better not to send bytes to stderr when that happens. If we could get that info back as a StatusOr instead that would be a little bit nicer :)

But I do think generating two small unicode values from what looks (based on wikipedia's utf-8 definition) to be a valid 4-byte utf-8 sequence seems broken.

Note -- this was not discovered using "normal" use-cases in production -- these corner-cases were found by exhaustive differential testing and fuzzing against the nlohman json library, so it's not surprising this finds the dark corners of the spec :)

**Comment by jorgbrown** [comment]
The unicode characters you're talking about may be valid, or not, depending on the context of the full utf-8 string that they are in.  That's why I'm asking for entire contents of the string field of the proto message that you are passing to MessageToJsonString.  because it appears that the routine `IsStructurallyValidUTF8` from src/google/protobuf/stubs/structurally_valid.cc is returning false on the string in question, and absent any more context, that appears to be correct.

**Comment by jmarantz** [comment]
These are entirely synthetic benchmarks so the entire sequence being tested is what's in the Issue description -- just the 3 or 4 byte utf-8 sequence; no other context.

I'm not a unicode expert and I don't know why a unicode character would be valid or not depending on other bytes in the sequence. Also I think it's OK for the protobuf serialization to declare "this is bogus I'm not translating that". But I think it's behavior in the presence of invalid sequences is not convenient:
 * in the 3-byte cases it writes messages directly to stderr which can't be trapped
 * in the 4-byte cases it looks to me like it make incorrect translations.
