### ISSUE TITLE
Generated file not found when imported in bazel build

### ISSUE THREAD

**Issue by vincent-mirian-google** [protocolbuffers/protobuf#9731]
**What version of protobuf and what language are you using?**
Version: HEAD (commit: 3be07ab3208ba34835091d4166d023926e302965)
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Bazel

**What did you do?**

BUILD file content:
-----------------------------------
genrule(
    name = "generated_proto_content",
    outs = ["generated.proto"],
    cmd = "echo 'syntax = \"proto3\";' > $(OUTS) && " +
          "echo 'message A {' >> $(OUTS) && " +
          "echo '  string info = 1;' >> $(OUTS) && " +
          "echo '}' >> $(OUTS)",
)

proto_library(
    name = "generated_proto",
    srcs = ["generated.proto"],
)

py_proto_library(
    name = "generated_py_pb2",
    srcs = ["generated.proto"],
    internal_deps = [":generated_proto"],
)

proto_library(
    name = "other_proto",
    srcs = ["other.proto"],
    deps = [":generated_proto"],
)

py_proto_library(
    name = "other_py_pb2",
    srcs = ["other.proto"],
    internal_deps = [
        ":other_proto",
        ":generated_proto",
    ],
    deps = [
        ":generated_py_pb2",
    ],
)

other.proto file content:
-----------------------------------
syntax = "proto2";

import "generated.proto";

command:
-----------------------------------
bazel build  -c opt //path/to:other_py_pb2

**What did you expect to see**
**A successful compilation.**

**What did you see instead?**
**error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/k8-opt/bin' -I. path/to/other.proto**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by perezd** [comment]
I believe this has been adequately addressed, thanks for bringing this to our attention!
