### ISSUE TITLE
Coverity Issues Reported in Auto Generated Code by Protobuf Compiler

### ISSUE THREAD

**Issue by nuwankarunaratne** [protocolbuffers/protobuf#9756]
Following issues reported in auto generated Code by protobuf Compiler

1. Dereference null return value (NULL_RETURNS) **Impact: Medium**

![image](https://user-images.githubusercontent.com/103212703/162267878-1f56f192-73d6-4d8a-ac3d-9562d72ab06a.png)

2. UCF: Useless control flow **Impact: Low**

![image](https://user-images.githubusercontent.com/103212703/162268029-e93dd997-15ff-4b5a-b73f-840b4be1480b.png)

**Comment by elharo** [comment]
This is from src/compiler/java/message_builder.cc

To reproduce, we need the .proto that was compiled. 

Number 1 is probably a false positive though I'd need to look a little closer.
Number 2 should only happen with very simple, almost trivial messages. In other cases, that if block will not be empty. The added complexity of fixing it is probably not worthwhile.

**Comment by nuwankarunaratne** [comment]
Hi, thanks for the update. please find the attached .proto file related to two issues

`// Copyright(c) 2022; All rights reserved by Millennium IT Software (Private) Limited

// This file contains the optional messages to assist null values.
// Can be used for the purpose of serialization and de-serialization of the message payload using google protobuf library (web link).
// Style used in this file available at https://developers.google.com/protocol-buffers/docs/style

syntax = "proto3";

package tradecho;

import "google/protobuf/struct.proto";

option java_package = "com.millenniumit.tradecho.protobuf.refd";
option java_outer_classname = "OptionalDataTypesDef";

//--- optional int messages --- //
message OptionalUint32{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    uint32 data = 2;
  }
}

message OptionalInt32{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    int32 data = 2;
  }
}

message OptionalUint64{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    uint64 data = 2;
  }
}

message OptionalInt64{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    int64 data = 2;
  }
}
//--- end of optional int messages --- //

//--- optional float messages --- //
message OptionalFloat{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    float data = 2;
  }
}
//--- end of optional float messages --- //

//--- optional double messages --- //
message OptionalDouble{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    double data = 2;
  }
}
//--- end of optional double messages --- //

//--- optional string messages --- //
message OptionalString{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    string data = 2;
  }
}
//--- end of optional string messages --- //

//--- optional bool messages --- //
message OptionalBool{
  oneof kind {
    google.protobuf.NullValue nullData = 1;
    bool data = 2;
  }
}
//--- end of optional bool messages --- //`

**Comment by elharo** [comment]
Number 1 is a false positive under most circumstances. There just might be a possibility where reading a corrupt data stream might cause kindCase_ to be not 0, 1, or 2 which would lead to an NPE here. I'm not sure, still checking.

**Comment by elharo** [comment]
Number two happens here in the case where every field is a oneof:

```
  printer->Print(
      "private void maybeForceBuilderInitialization() {\n"
      "  if (com.google.protobuf.GeneratedMessage$ver$\n"
      "          .alwaysUseFieldBuilders) {\n",
      "ver", GeneratedCodeVersionSuffix());

  printer->Indent();
  printer->Indent();
  for (int i = 0; i < descriptor_->field_count(); i++) {
    if (!IsRealOneof(descriptor_->field(i))) {
      field_generators_.get(descriptor_->field(i))
          .GenerateFieldBuilderInitializationCode(printer);
    }
  }
  printer->Outdent();
  printer->Outdent();
```

This is very minor and harmless. I doubt we'll fix this.

**Comment by elharo** [comment]
Per spec, "Be careful when adding or removing oneof fields. If checking the value of a oneof returns None/NOT_SET, it could mean that the oneof has not been set or it has been set to a field in a different version of the oneof. There is no way to tell the difference, since there's no way to know if an unknown field on the wire is a member of the oneof." 

In other words, even if the wire format uses an unknown field in a oneof, it will still be 0 when parsed. Absent a bug in this logic, this NullPointerException can't happen.
