### ISSUE TITLE
[Python] Generated PYI files for enums cause runtime errors

### ISSUE THREAD

**Issue by oheyzhiwei** [protocolbuffers/protobuf#9765]
**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python: 3.8.13

**What did you do?**
1. Build protos with `--pyi_out`. The `pyi` looks like:
```
$ cat holder_pb2.pyi
[...]
# Our enum
HOLDER_STATE_ADDITIONAL_INFO_REQUESTED: HolderState
HOLDER_STATE_APPROVED: HolderState
[...]

class HolderState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []
```
2. Create a Python snippet like so:
```
d: Dict[str, holder_pb2.HolderState] = {
    'asd': holder_pb2.HOLDER_STATE_APPROVED
} 
```
3. Run the snippet in 2)

**What did you expect to see**
The annotated type shouldn't cause a runtime error.

**What did you see instead?**
This snippet passes the type-checks, but causes a runtime error when run :
```
TypeError: Parameters to generic types must be types. Got <google.protobuf.internal.enum_type_wrapper.EnumTypeWrapper object at 0x7f136f2c5fd0>.
```

**Anything else we should know about your project / environment**
Running in Bazel. Using `pyright` for the type-checks

**Comment by oheyzhiwei** [comment]
Another example:
```
print(holder_pb2.HolderState(1))
```

This passes the typechecks in `pyright`, but gets a runtime error:
```
TypeError: 'EnumTypeWrapper' object is not callable
```

**Comment by perezd** [comment]
@anandolee can you look into this when you have a moment?

**Comment by anandolee** [comment]
I tested in pytype for:
```
d: dict[str, holder_pb2.HolderState] = {
    'asd': holder_pb2.HOLDER_STATE_APPROVED
} 
```
and 
```
my_enum: holder_pb2.HolderState = holder_pb2.HolderState(1))
```

They pass. 

Not sure for pyright, will check with some others

**Comment by anandolee** [comment]
I tested in pytype for:
```
d: dict[str, holder_pb2.HolderState] = {
    'asd': holder_pb2.HOLDER_STATE_APPROVED
} 
```
and 
```
my_enum: holder_pb2.HolderState = holder_pb2.HolderState(1))
```

They pass. 

Not sure for pyright, will check with some others

**Comment by anandolee** [comment]
I checked with google python team, and here's the reply:

"That looks like that long-standing issue with protobuf enums actually being ints. (The stubs lie and say they have their own subclasses because that makes for better type-checking.) The fix is to either put quotes around the enum type (Dict[str, "holder_pb2.HolderState"] or add from __future__ import annotations to the top of the file to automatically stringify all annotations"
