### ISSUE TITLE
Convert python object to protocol buffer object

### ISSUE THREAD

**Issue by daohu527** [protocolbuffers/protobuf#9766]
**What language does this apply to?**
python

**Describe the problem you are trying to solve.**
I have some objects which are generated by other deserialization and now I want to convert these objects to protobuf format.

> I can guarantee that the proto file is defined by the format of the object

**Describe the solution you'd like**
1. The current method requires manual assignment. For example, I have 3 objects Person, House, and Car. I need to assign values to the proto objects according to the properties in the objects.
2. In python i can get the properties of the object and then can assign values to the proto object based on the properties and type

The problem is that **protobuf doesn't provide a way to assign values based on property names**

**Additional context**
Is there any general way for me to flexibly convert objects to proto format? like
```python
class Car:
 def __init__(self):
   self.id = 0
   self.speed = 0

car = Car()
car.id = 1
car.speed = 40

proto_car.build_by(car)
```

**Comment by perezd** [comment]
We don't have any particular plans to support this feature request at this time. As for workarounds, you might wanna ask on StackOverflow.
