### ISSUE TITLE
Protobuf build error... With ndk 

### ISSUE THREAD

**Issue by Saikatsaha1996** [protocolbuffers/protobuf#9774]
../configure --prefix=$HOME/armnn-devenv/google/pb_install --enable-static --disable-shared --enable-cross-compile

make -j8

ld.lld: error: undefined symbol: __android_log_write
>>> referenced by common.cc:146 (../../src/google/protobuf/stubs/common.cc:146)
>>>               common.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)) in archive ./.libs/libprotobuf.a
>>> referenced by common.cc:154 (../../src/google/protobuf/stubs/common.cc:154)
>>>               common.o:(google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)) in archive ./.libs/libprotobuf.a
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by acozzette** [comment]
@Saikatsaha1996 The `__android_log_write` symbol looks like something that should ordinarily be made available on Android by the `-llog` linker flag. I suspect that the problem has something to do with the cross-compilation setup--maybe the build is trying to build protoc for Android when you actually need it built for the host machine. You might need to build protoc normally (no special `configure` flags) and copy it somewhere, and then pass `--with-protoc=<path to protoc>` to `./configure` when you do the cross compilation.
