### ISSUE TITLE
Clarification: Field presence for message

### ISSUE THREAD

**Issue by Timovzl** [protocolbuffers/protobuf#9776]
The field presence docs show a [table](https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#presence-in-proto3-apis) indicating that "explicit presence" applies to message-typed fields _regardless of the optional keyword_.

**Does the optional keyword have any effect on message-typed fields?**

The reason I am asking, and the feature that I am looking for, in the context of update requests, is distinguishing between (A) "please null out this field for me" versus (B) "I do not know or do not want to change this field, so please keep its existing value".

As such, I'm wondering if the optional keyword on a message-typed field can be used to distinguish between a _deliberately assigned_ null/default value versus "no value was set".

**Comment by haberman** [comment]
> Does the optional keyword have any effect on message-typed fields?

It does not have any semantic effect. It doesn't change the generated API or the semantic behavior of the field in any way.

> As such, I'm wondering if the optional keyword on a message-typed field can be used to distinguish between a deliberately assigned null/default value versus "no value was set".

Yes, for a message-typed field you can distinguish between a deliberately assigned default value versus "no value was set."

However, this is always true, regardless of whether or not `optional` is specified. Even for a field *without* optional, you can still tell whether the field was set or not, as long as the field is a message.

**Comment by Timovzl** [comment]
@haberman Thank you for your quick response! For clarification, could you show a quick example, on a message-typed field, of an "is not set" check versus a "null value" check?

**Comment by haberman** [comment]
Message fields are bi-state: either set or unset. They are not tri-state (set, not set, null value).

**Comment by Timovzl** [comment]
> Message fields are bi-state: either set or unset. They are not tri-state (set, not set, null value).

This is the essence of my question.

Say we are performing an update of our personal details, which includes (among other things) a complex Address field. What is the recommended way that we address the tri-state nature of updates?

1. "Set my address to this set of fields"
2. "Set my address to null" (say, because [GDPR](https://gdpr-info.eu/))
3. "Do not touch my address, since I am only updating _other_ components with this call" (say, because the client is on a version that does not _know_ about the new Address field)

I'd like to emphasize how important such distinctions are to contract versioning. For example, imagine the server introducing the Address field in v2, and a client on v1 omitting this field it does not even know about. It'd be a shame if the server went and nulled out everybody's address as a result.

**Comment by haberman** [comment]
> "Set my address to null" (say, because [GDPR](https://gdpr-info.eu/))

It sounds like you are looking for a tombstone: an affirmative marker that a certain value should be deleted.

Protobuf does not have tombstones per se. But for message fields, a set-but-empty sub-message seems like it would fit the bill, if you write some logic to recognize it as such, eg.

```c++
  // Sending side: create a set-but-empty message.
  patch->mutable_address();

  // Receiving side: recognize empty message.
  if (patch->has_address() && patch->address()->ByteSize() == 0) {
    record->clear_address();
  }
```

The code above is C++, but any language that supports protobuf should have equivalent APIs.

**Comment by Timovzl** [comment]
@haberman Apologies for my delayed reply.

I appreciate your efforts at a solution, but I do not believe that we have a foolproof one yet. For example:

- If the object happens to be a set of three integers, then there is no difference between an "empty" object and an object containing three `0`s. (Correct me if am wrong.)
- If the object contains nullable properties, then we cannot always distinguish between "unset the address property" vs. "update the address property to these fields, and I just happen to want to set all of them to null".

These things create confusion, in my experience. Protocols rely on utter clarity, and we are talking about a fairly common occurrence for updates.

I realize that I could create a separate tombstone property, but that seems to defeat the purpose and applicability of the optional keyword. Is there a cleaner way to achieve what I'm talking about?
