### ISSUE TITLE
ImportError: cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by ptarjan** [protocolbuffers/protobuf#9778]
https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal 

This seems to have changed between 3.19.4 and 3.20.0. Is this an intentional backward incompatibility? If so, is there a required client library upgrade to version 3.20.0 now?

**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc.
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
3.20.0

**What did you do?**
1. Use an older client library like 3.15.5.
2. See error in title

**What did you expect to see**
No error

**What did you see instead?**
Title error

**Comment by anandolee** [comment]
"Use an older client library like 3.15.5."  We only guarantee old generated code work with new runtime, but new version of generated code may not work with old runtime.

Use 3.20 version of protoc with 3.15 runtime is not what we  generated

**Comment by vsennak** [comment]
Is the solution to use **"3.20 version of protoc with 3.15 runtime"** to avoid the error to avoid the error "ImportError: cannot import name 'builder' from 'google.protobuf.internal'"?

**Comment by Nasiruddin696** [comment]
i face this problem any body help plz 

TypeError: Cannot set tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference.local_name to None: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)

**Comment by vsennak** [comment]
Try the solution mentioned here, this had worked for me.
https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal

**Comment by Mohammadakhavan75** [comment]
> Try the solution mentioned here, this had worked for me. https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal

This works for me! Thank you.

**Comment by liujingmao** [comment]
Try the solution mentioned here, this had worked for me. https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal
This works for me! Thank you.
