### ISSUE TITLE
`make maintainer-clean` leaves a few files behind

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#979]
After doing a `make all && make check` at top level and `cd conformance && make && make test_cpp && cd ..`, `make maintainer-clean` should remove everything.  But `git status --ignored` reports `ar-lib` and `gmock/` get left behind.  It seems like atelast the `ar-lib` should get cleaned up.

**Comment by thomasvl** [comment]
https://github.com/google/protobuf/pull/1498 landed the other week and cleans a bunch of things up, but there is still some bits, and nothing prevents it from regressing.  It might make sense to have a travis build that do a all/maintainer-clean followed by git status --ignored to make sure things don't get missed.

**Comment by elharo** [comment]
we plan to replace make with bazel
