### ISSUE TITLE
Is cxx11 required to compile .pb.cc genrated code?

### ISSUE THREAD

**Issue by stickM4N** [protocolbuffers/protobuf#9796]
Is cxx11 required to compile .pb.cc generated code?
If not, is it planed to be migrated to cxx11 minimum at some point?

I want to make a pull request to allow enums to behave as enum clasess, which I think is the best way to use enums, but want to comply with the cxx98 or cxx11 requirement the project has.

**Comment by fowles** [comment]
We do require C++11; however, we are extremely unlikely to accept a patch that adds an option to generate enums as enum classes.

Generally speaking, conditional options like this fragment the ecosystem so we only add options when:
-  there is a clear path to migrate and remove the old option
-  the value of the new option is sufficient to justify the cost of the migration inside google
