### ISSUE TITLE
protobuf doesn't see .proto files in gradle project

### ISSUE THREAD

**Issue by igorek9191** [protocolbuffers/protobuf#9798]
Protobuf plugin for gradle:
`id 'com.google.protobuf' version '0.8.13'`

Here is dependencies from build.gradle
`implementation "io.grpc:grpc-protobuf:${grpcVersion}"`
` implementation "io.grpc:grpc-stub:${grpcVersion}"`
` compileOnly 'javax.annotation:javax.annotation-api:1.3.2'`
` implementation "com.google.protobuf:protobuf-java:${protobufVersion}"` 
`runtimeOnly "io.grpc:grpc-netty-shaded:${grpcVersion}"`

I'm trying to start a test in a project. But I get the following error:
`Could not make proto path relative: D:\Users\�������������\IdeaProjects\service-tester\src\main\proto\messaging_core\message\message.proto: No such file or directory`

while `message.proto` file is present of project
![Screenshot_1](https://user-images.githubusercontent.com/17683306/163803443-db279ecd-a744-4183-b640-8d2e6c131786.png)

What I need to make protobuf start to see .proto files ?

**Comment by perezd** [comment]
We aren't the maintainers of the gradle plugin, I'll transfer you over to the right spot:
https://github.com/google/protobuf-gradle-plugin
