### ISSUE TITLE
Wrong executable published to rubygems for arm64-darwin on > v3.20

### ISSUE THREAD

**Issue by DerekStride** [protocolbuffers/protobuf#9804]
**What version of protobuf and what language are you using?**
Version: > v3.20
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

MacOS 12.3.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

arm64

**What did you do?**

Download either one of the following gems from arm64-darwin:

[3.20.1.rc.1](https://rubygems.org/gems/google-protobuf/versions/3.20.1.rc.1-arm64-darwin) - April 06, 2022 arm64-darwin (274 KB)
[3.20.0](https://rubygems.org/gems/google-protobuf/versions/3.20.0-arm64-darwin) - April 01, 2022 arm64-darwin (274 KB)

See all here: https://rubygems.org/gems/google-protobuf/versions

Check the Mach-O Header and it's for x86 architecture (small script to parse the headers: [gist://derekstride/mach-o.rb](https://gist.github.com/DerekStride/712e843b6c1b17bb1b086dfa73a2dc71))

**What did you expect to see**

An executable from arm64 architecture.

**What did you see instead?**

An executable from x86 architecture.

**Error from stacktrace:**

```
Caused by:
LoadError: dlopen(~/.gem/ruby/3.1.0/gems/google-protobuf-3.20.0-arm64-darwin/lib/google/3.1/protobuf_c.bundle, 0x0009): tried: '~/.gem/ruby/3.1.0/gems/google-protobuf-3.20.0-arm64-darwin/lib/google/3.1/protobuf_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - ~/.gem/ruby/3.1.0/gems/google-protobuf-3.20.0-arm64-darwin/lib/google/3.1/protobuf_c.bundle
```

**Comment by haberman** [comment]
Has this ever worked? I see there is an open bug for it here: https://github.com/protocolbuffers/protobuf/issues/8682

This may have been broken by: https://github.com/protocolbuffers/protobuf/pull/9566. If that's the case, then reverting would break Ruby 3.1 binaries on other platforms.

**Comment by haberman** [comment]
Unless there is a quick fix for this, we may have to just disable the arm64 build on macOS for 3.20.1. arm64 users would need to build from a source gem.

**Comment by DerekStride** [comment]
> Has this ever worked? I see there is an open bug for it here: https://github.com/protocolbuffers/protobuf/issues/8682

I don't think so, All existing gems published with pre-built packages for arm64-darwin were broken when I created the issue. If you have access you may want to yank them from RubyGems so projects running on arm64-darwin can build from source as a fallback.

**Comment by haberman** [comment]
I've yanked the arm64-darwin gems. Closing in favor of https://github.com/protocolbuffers/protobuf/issues/8682.
