### ISSUE TITLE
Cut support for .NET Standard 1.1, Framework 4.5, increase min to Framework 4.6.2

### ISSUE THREAD

**Issue by erikmav** [protocolbuffers/protobuf#9806]
Older framework and netstandard targets are out of support lifetime and hinder use of newer C# and .NET features. Cut netstandard1.1 and net45, add net462. Recommend also taking a moment to make use of Array.Empty<T>, Enumerable.Empty<T> to replace several empty collections used in the class library and tests.

**Comment by erikma** [comment]
Two other notes: Support lifecycle updated in Sep 2021, 4.6.2 is the earliest supported: https://docs.microsoft.com/en-US/lifecycle/faq/dotnet-framework

Plus VS2022 no longer has an option to install targeting pack for pre-4.6.2.

**Comment by perezd** [comment]
I'll look to @jskeet to help us decide when it's safe to drop what support and how to communicate that to the C# community.

**Comment by erikma** [comment]
netstandard2.0 is sufficient, it's rare to find an actual package that uses it instead of selecting a netcore or net6 targeting instead.

**Comment by jskeet** [comment]
See #9666 for thoughts on this.

**Comment by jskeet** [comment]
We do intend to do this - I'm expecting targets of net462, net60, netstandard2.0. But it's a matter of finding time to do it thoroughly.
