### ISSUE TITLE
move semantics friendly StatusOr

### ISSUE THREAD

**Issue by wbpcode** [protocolbuffers/protobuf#9827]
**What language does this apply to?**
C++.

**Describe the problem you are trying to solve.**
Make the `StatusOr` more fast.

**Describe the solution you'd like**

Add the move constructor to the `StatusOr` and add non-const method to get `status` and `value`.

**Describe alternatives you've considered**
None.

**Additional context**

Nope.

**Comment by acozzette** [comment]
It might not be worth putting too much effort into this now, because there is a good chance that we will delete our StatusOr type and switch to `absl::StatusOr` soon after we take a dependency on Abseil.

**Comment by wbpcode** [comment]
That is enough. Thanks.

**Comment by Montyc1** [comment]
```
[](![inherit](https://user-images.githubusercontent.com/102581536/165871074-3f69bc29-4d11-4176-affe-e5470f0f9cbf.gif)
#9882 [](url))
```
