### ISSUE TITLE
[Python] No protobuf-3.20.1-py2.py3-none-any.whl package in latest PYPI release

### ISSUE THREAD

**Issue by lmunch** [protocolbuffers/protobuf#9838]
In releases prior to 3.20.1 there has been platform and abi agnostic packages like "protobuf-3.20.0-py2.py3-none-any.whl" on PYPI but with latest release this was not included.

**Comment by zware** [comment]
The source package is also missing from PyPI.

**Comment by haberman** [comment]
The `non-any` file has been uploaded for 3.20.1: https://pypi.org/project/protobuf/#files
