### ISSUE TITLE
[Releasing] Create release artifacts from Bazel

### ISSUE THREAD

**Issue by dlj-NaN** [protocolbuffers/protobuf#9842]
# Executive Summary

This is a heads-up for users of the protobuf library about an internal change in our release process. Most users should be unaffected, but downstream users who repackage or redistribute protobuf sources may be affected.

Protobuf releases include several source archives, most of which are ostensibly duplicates, but sliced by target language (e.g., protoc sources with the Java runtime). These are currently (< 3.21) produced by a combination of autotools logic and a postprocessing script. At some point in the future, these will be produced from Bazel instead, using rules from bazelbuild/rules_pkg, and the autotools dist build will be retired.

# Background

[Autotools](https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html) is historically the primary meta-build system for the protobuf project, including building the C++ runtime and protocol compiler. As a meta-build system, the role of Autotools is to produce rules for a build system, which is `make`. In other words, the overall build is defined somewhat abstractly, and the meta-build logic is ultimately what produces a `Makefile`.

In addition to its typical roles in `./configure`, `make`, and `make check`, Autotools also includes a lot of logic for generating distribution rules. The protobuf project uses this logic to produce source tarballs at release time. (The meta-build also produces rules for `make install`, but these are not part of this particular description.)

For the C++ runtime, this works fairly well: since the metabuild steps are aware of all of the inputs in order to produce build rules, it is a fairly straightforward extension to use that information to produce source distributions. For other languages (e.g., the protobuf Java runtime), the sources are simply treated as "extra files" in the distribution. The Protobuf project also uses a separate post-processing step to create individual, target language-specific artifacts. So, while the Autotools distribution is attractive on the surface, there is actually quite a bit of additional cost to meet all of the needs of the project.

[Bazel](https://bazel.build/) is an all-in-one build system. It uses a somewhat stricter model for dependency modeling and execution than Make (for example, a Bazel build is *comprehensive* -- there are no recursive invocations, in addition to other properties around soundness of the build graph, hermeticity of execution, and side-effect freedom).

Bazel exposes its internal graph programmatically via *Starlark*, its internal scripting language. (Syntactically, Starlark is a subset of Python, but there are substantial differences in semantics). Through this API, extensions can be written which implement build steps with full awareness of dependency structure and actions.

The [bazelbuild/rules_pkg](https://github.com/bazelbuild/rules_pkg) project implements packaging rules, and is analogous to Autotools' distribution logic. However, the rules_pkg approach uses rules in `BUILD` files (which are written in a restricted subset of Starlark) to define the distribution structure, rather than autotools definitions.

# Design and motivation

The goal is to build source distribution artifacts from Bazel using rules_pkg. The major benefit is to consolidate build and release logic into one system: Bazel. Continuing to support Autotools has cost beyond simply maintaining lists of files; dependencies (such as googletest) no longer provide Autotools build definitions, which leaves us either stuck on an old version, or patching local workarounds.

The new distribution rules will be added on a per-package basis. Currently, these are the Bazel packages defined in the protobuf tree:

```
//:BUILD
//benchmarks:BUILD
//benchmarks/cpp:BUILD
//benchmarks/datasets:BUILD
//benchmarks/datasets/google_message1/proto2:BUILD
//benchmarks/datasets/google_message1/proto3:BUILD
//benchmarks/datasets/google_message2:BUILD
//benchmarks/datasets/google_message3:BUILD
//benchmarks/datasets/google_message4:BUILD
//java:BUILD
//java/core:BUILD
//java/internal:BUILD
//java/internal:testing.bzl
//java/kotlin:BUILD
//java/kotlin-lite:BUILD
//java/lite:BUILD
//java/util:BUILD
//objectivec:BUILD
//pkg:BUILD
//third_party/utf8_range:BUILD
//toolchain:BUILD
//util/python:BUILD
```

Most of these packages cover files included in source distributions. Packaging rules will be added as necessary to include all of the files that are included in the autotools dist archives.

The rules_pkg rules are broken down into rules that define files (`pkg_files`, which can be aggregated by `pkg_filegroup`) and artifacts (such as `pkg_tar` to produce a tarball). This means that the source-specific archives can be directly defined in terms of what files they are intended to contain, and the "all" output simply contains all of the sources.

# Drawbacks

While this design would reduce the Protobuf project's dependence on autotools for one major use case, it does not necessarily remove the burden of supporting multiple build systems. Currently, the project supports 3 build systems for C++ alone: autotools, Bazel, and CMake. Moving release artifact production to Bazel does not remove any of these, since there will still be users who, say, rely upon CMake rules to integrate with their own projects. However, Bazel does have a substantially better outlook for languages other than C/C++, so it is a much more natural place for the Protobuf team to consolidate the complex cross-language release definition(s).

The rules_pkg rules themselves are still fundamentally file lists. In some cases, such as languages like PHP that are not built under Bazel, this is effectively parity with the autotools lists of files. For our Bazel-built runtimes, including a label like `//:protobuf` in a packaging rule would package the outputs, whereas the source distribution is intended to package the inputs (`srcs`, `hdrs`, etc.). In these cases, we can use `filegroup` rules, or write a Starlark macro to emit both `cc_library` and `pkg_files` rules consistently on a per-library basis. It may also be possible to write a Starlark aspect to extract sources transitively, although this may be complicated by transitive dependencies that should not necessarily be packaged.

Writing Bazel rules for distribution sources also means that the source definitions have to be defined within package boundaries. This is not necessarily a drawback, though, since package boundaries usually represent reasonable divisions for cohesive code boundaries.

The rules_pkg rules do include some rules to perform installation, but this may not be sufficient for users who are accustomed to the autotools-driven `./configure && make && make install` pattern.

# Alternatives considered

* Continue using autotools: Since autotools support has been dropped from googletest for quite a while, our focus will move towards Bazel as the single, canonical source of truth for the build. Regardless of whether we continue to provide autotools rules for users of the release distribution, we will be better served by consolidating logic in our Bazel build.
* CPack (from CMake): The CMake ecosystem is arguably a very attractive target due to the large number of projects which use it. However, the major drawback is the paucity of support for languages outside of C and C++. The CMake system in general also lacks the degree of comprehension and extensibility that is provided by Bazel's Starlark API -- working in Starlark provides a much better base for future extensibility.
* Stop providing distribution tarballs: Snapshots of our releases are available from Github, so this may actually be a reasonable direction longer-term. For now, though, we will aim for parity with our existing release practices.

**Comment by deannagarcia** [comment]
Closing as this is being tracked internally.
