### ISSUE TITLE
Possible race / clarification

### ISSUE THREAD

**Issue by jeremy-rifkin** [protocolbuffers/protobuf#9853]
This code strikes me as possibly an error. Is there reasoning for this racy code?

https://github.com/protocolbuffers/protobuf/blob/d76f8c868c271ce57241119f9316b6f5a7109e32/src/google/protobuf/arenaz_sampler.cc#L98-L109
 
I take it the idea is to avoid a store except when actually necessary. To me it seems better to replace the `.store` in the branch with `info->thread_ids.fetch_or(tid, std::memory_order_relaxed)`;

**Comment by acozzette** [comment]
@fowles told me offline: "This is a deliberate benign race that only occurs in code that collects statistics." So I think you are right about there being a race, but we're OK with this given that the code is only used for collecting stats.

**Comment by jeremy-rifkin** [comment]
Thank you so much for the response :)

**Comment by fowles** [comment]
On closer inspection, there is a genuine race here that I will fix.  Thanks for raising this.
