### ISSUE TITLE
Conformance tests/runners aren't always endian-correct.

### ISSUE THREAD

**Issue by thomasvl** [protocolbuffers/protobuf#986]
conformance_test_runner.cc documents the wire format for the two lengths as a little endian 32bit int, but the code in there and some of the language runners doesn't actually have any byte flipping code.  They should all get updated instead of assuming they are on little endian runtimes.

**Comment by haberman** [comment]
I agree that this is wrong in principle, but do we know of anyone it is affecting in practice? Big-endian hardware is hard to come by these days (which also makes big-endian fixes hard to test).

**Comment by fowles** [comment]
Please reopen if you find hardware where we can verify this.
