### ISSUE TITLE
Python: using native namespace packages 

### ISSUE THREAD

**Issue by fancl20** [protocolbuffers/protobuf#9876]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
https://github.com/protocolbuffers/protobuf/blob/main/python/google/__init__.py
Python package is using pkg_resources style namespace by default, which is not compatible with PEP420

**Describe the solution you'd like**
Delete the `google/__init__.py`
From https://github.com/pypa/packaging.python.org/blob/main/source/guides/packaging-namespace-packages.rst

> It is extremely important that every distribution that uses the namespace package omits the :file:`__init__.py` or uses a pkgutil-style :file:`__init__.py`. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable.
 
And also:

> Some older recommendations advise the following in the namespace package :file:`__init__.py`:
> ```
> try:
>     __import__('pkg_resources').declare_namespace(__name__)
> except ImportError:
>     __path__ = __import__('pkgutil').extend_path(__path__, __name__)
> ```
> The idea behind this was that in the rare case that setuptools isn't available packages would fall-back to the pkgutil-style packages. This isn't advisable because pkgutil and pkg_resources-style namespace packages are not cross-compatible. If the presence of setuptools is a concern then the package should just explicitly depend on setuptools via install_requires.

Is there any use cases that require using legacy style pacakge namespace?

**Comment by dlj-NaN** [comment]
@fancl20 : If you install the package with pip (and not `setup.py install`), the `__init__.py` files will not be installed. That will maintain the native namespace package for `google`. You can install to an isolated venv, or to your user-level library, to avoid conflicting with system packages.

(Sadly, the `__init__.py` file is still around in the repo for various reasons, none of which are good reasons. However, this should not be an issue as long as you use pip for the final installation step.)

**Comment by mering** [comment]
.
