### ISSUE TITLE
Python ParseFromString gets "error: Error parsing message" when reading Serialiezed String from file.

### ISSUE THREAD

**Issue by bowenatbear** [protocolbuffers/protobuf#9884]
I have the following codes in my project:
```
message Log {
  string id = 1;
  string code = 2;
  string message = 3;
}
```
and I am serialize the data into string and write it with other information (e.g. timestamp) into files. (each line contains a serialized message)
```
msg = logs_pb.Log(id = "id", code = "code", message = "message")
logfd = os.open(file_path, os.O_APPEND | os.O_RDWR | os.O_CREAT)
gevent_file_obj = gevent.fileobject.FileObject(logfd, 'w')
gevent_file_obj.write('{} | {}\n'.format(time.time(), serialized_msg.strip('\n').strip('\t')))
```
then when reading the file, I get the serialized data by
```
logfd = os.open(file_path, os.O_RDONLY)
gevent_file_obj = gevent.fileobject.FileObject(logfd, 'r')
data = gevent_file_obj.readline()
msg = data.split('|')[1].strip()
```
The errors `error: Error parsing message` occurs when I tried to deserialize the string using
```
parse_data = logs_pb.Log()
parse_data.ParseFromString(msg)
```

I understand writing the serialized data into string in files might cause some problem
`gevent_file_obj.write('{} | {}\n'.format(time.time(), serialized_msg.strip('\n').strip('\t')))`
as the serialized string might have some special characters like `\t`.

Then if there any recommendation if I would like to write the serialized data with other strings in files and let it be read and parsed later? What's the proper way to store the data and read it later?

**Comment by acozzette** [comment]
I would recommend storing the serialized proto in a file by itself. This would simplify things quite a bit since then you wouldn't be mixing text and binary in the same file. If you need to include the current time, you can always just make that a field in the proto. Otherwise if you really need to have free-form text along with your proto, you could base64-encode your serialized proto so that it's represented in plain text.

**Comment by bowenatbear** [comment]
@acozzette Thank you so much for the fast response. I understand it would be better to store the serialized binary data in a file by itself, but based on some special requirement, I might need to store it with several other data together in a file.

Could you help me understand and elaborate more on "free-form text along with your proto"? Are you recommending `import base64` and something like `base64.b64encode(the_byte_message)`, so the encoded bytes will not contain those special characters and could be parsed as normal string?
