### ISSUE TITLE
aarch-x86 shows zsh: bad CPU type in executable: protoc

### ISSUE THREAD

**Issue by Answerlord** [protocolbuffers/protobuf#9893]
hey,guys,i download the protoc-3.20.1-rc-1-osx-aarch_64 ,but when i type `protoc --version` on the terminal for checking my cfg ,the terminal shows that `zsh: bad CPU type in executable: protoc`,my device is macbookpro 2021(m1). plz give me some advice to solve this problem. thks 4 ur help

**Comment by acozzette** [comment]
We are hoping to fix this soon, but this is to be expected right now. The published Mac aarch64 binaries are actually just x86-64 binaries but we will soon start publishing real binaries for M1 Macs.

**Comment by tisonkun** [comment]
@acozzette since you close this issue, I suppose there're other issues or PRs tracking this movement? Could you please link it here?
