### ISSUE TITLE
Casting issues in protobuf auto generated codes.

### ISSUE THREAD

**Issue by mahela97** [protocolbuffers/protobuf#9904]
**What version of protobuf and what language are you using?**
Version: 3..19.1
Language: Java

**What operating system and version?** windows 10

Following casting issues are reported from the protobuf auto generated codes.

**proto files are in attached zip file**
[protoFIles.zip](https://github.com/protocolbuffers/protobuf/files/8609251/protoFIles.zip)

1.  Deprecated method valudOf() called in auto generated code.  
-  health.proto (dependencies - service.proto)

Following code is generated
![image](https://user-images.githubusercontent.com/61684744/166426230-f9e30580-e021-4584-be92-d401e9f18e1c.png)

This gives **_Avoid using deprecated method, constructor, field, type or package_** casting issue.

2. Floating point numbers are checking for equality in auto generated codes. 

- exchange-rate.proto

Following code is generated.

![image](https://user-images.githubusercontent.com/61684744/166426406-5ea6b4d4-6fbc-47f7-a93d-137f398424f7.png)

This gives **_Avoid testing floating point numbers for equality_** casting issue.

**Comment by elharo** [comment]
I don't think we can or probably should avoid the direct floating point equality comparison here. I'm pretty sure we don't want a tolerance value. However there might be some weird issues around NaN and positive and negative zero.  In fact, I'm pretty sure we're not handling NaN correctly here. I'll open a separate issue to track that.

**Comment by elharo** [comment]
Actually, NaN should be OK since nothing is equal to NaN. I wouldn't be surprised if there are other issues around NaN though.

**Comment by elharo** [comment]
valueOf should likely now be forNumber.

**Comment by elharo** [comment]
In the code I see this:

```
  // Use deprecated valueOf() method to be compatible with old generated code
  // for v2.5.0/v2.6.1.
  // TODO(xiaofeng): Use "forNumber" when we no longer support compatibility
  // with v2.5.0/v2.6.1, and remove the @SuppressWarnings annotations.
  (*variables)["for_number"] = "valueOf";
```

Can we now drop 2.5/2.6 compatibility?

**Comment by elharo** [comment]
Fixed in google3. The change should make its way into github on the next sync.
