### ISSUE TITLE
Python bindings should coerce pathlib objects to strings when serializing

### ISSUE THREAD

**Issue by vapier** [protocolbuffers/protobuf#9914]
**What language does this apply to?**
If it's about generated code change, what programming language?

generate Python bindings

**Describe the problem you are trying to solve.**

as we migrate our codebase from `str` for paths to `pathlib.Path` (with our APIs usually accepting `Union[str, os.PathLike]` akin to Python stdlibs), we find ourselves having to coerce Path's into strings when generating messages.

**Describe the solution you'd like**

generate protobuf bindings should accept `Path` for `string` types and coerce them into strings for us

**Comment by anandolee** [comment]
Discussed with some other team members and we think we do not want accept Path for string field.

Any class can define `__str__` for string representation. If we did `str(val)` without a type check then we would accept any kind of object and convert it to string. But we want stronger type checking than that.

**Comment by vapier** [comment]
that's why you'd type check against `pathlib.PurePath`, not just see if the class has `__str__` (since, afaik, every class does)

**Comment by anandolee** [comment]
Thanks for raise it up. But it seems to me that Path is not special enough to be accept for string field. It is only a type that has string representation 

Let's see a message defined as
```
message Something {
  optional string file_path = 1;
}
```
It make sense to have the file_path field accept both string and Path. But how about:
```
message person {
  optional string name = 1;
  ...
}
```
People may reach us and complain a hiding bug that they assign a Path to the name field.

Another example
```
message AnotherMessage {
  optional string huge_number = 1;
  optional string json_representation = 2; 
}
```
Should we accept int for huge_number field, accept json struct for json_representation representation? We don't usually coerce things, and different usages may need different coerce support once we accept one.
