### ISSUE TITLE
FromJsonString timezone_offset set to wrong character

### ISSUE THREAD

**Issue by rbisecke** [protocolbuffers/protobuf#9919]
**What version of protobuf and what language are you using?**
Version: protobuf==3.19.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Mac 

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.5

**What did you do?**
1. Define a proto definition with the google timestamp type `google.protobuf.Timestamp time`
2. Generate the python message stubs
3. Convert a json string with that value mapping to the protobuf python type using `json_format` 
```
from google.protobuf import json_format
```
Example time string:  `2022-05-02T16:18:58.925142` which matches the documented expected format:
```Example of accepted format: '1972-01-01T10:00:20.021-05:00'```
from the source code [here](https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/well_known_types.py#L135)
**What did you expect to see**
Successful mapping
**What did you see instead?**
```
google.protobuf.json_format.ParseError: ... time data '2022-05' does not match format '%Y-%m-%dT%H:%M:%S'...
```
No error occurs if I replace the `T` with a `Z` to match the code but that doesn't match the expected format. 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by deannagarcia** [comment]
The `Z` character isn't meant to match the `T` in the middle, but rather matches information given about the timezone (hence the name `timezone_offset`). The format of this time requires a time zone specified. You can see in the example of accepted format the `-05:00` suffix denotes the timezone. If you don't want to specify a timezone, you can append the character `Z` to specify a UTC offset of `00:00`. You can read more about this format [here](https://datatracker.ietf.org/doc/html/rfc3339).
