### ISSUE TITLE
float type set error

### ISSUE THREAD

**Issue by cluoliang** [protocolbuffers/protobuf#9924]
proto:
message Box {
     float left = 1;
     float top = 1;
     float right = 1;
     float bottom = 1;
}

Box *box =  mutable_box();
box->set_left (1)
box->set_top(1)
box->set_right (0)
box->set_bottom (0)

when i set right/bottom value 0,call std:fstream input("./1.txt",std::ios::out | std::ios::binary);
imput.write(box.DebugString().c_str() , box.DebugString().length());

the result :

Box {
     left = 1;
     top = 1;
}

the question is : why right 、bottom is not exist

**Comment by deannagarcia** [comment]
From a quick look I would assume that it is related to the fact that 0 is a default value for int fields. In order to help more, we will need more information. Can you use the template provided to give us more info (i.e. version of protobuf, how to reproduce)

**Comment by devjgm** [comment]
@cluoliang Can you please provide a slightly more complete repro case? Your `Box` message reuses the tag `1` for all fields, which I assume is not what you're actually doing.

**Comment by deannagarcia** [comment]
Closing due to a lack of response. Feel free to open with more details if you are still seeing this error.
