### ISSUE TITLE
protoc generates invalid c++ becasue of name colisions

### ISSUE THREAD

**Issue by DS-Serafin** [protocolbuffers/protobuf#9925]
**What version of protobuf and what language are you using?**
Version: v3.129.2.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 12 with stdlibc++ (gcc-11)

**What did you do?**
create a proto service definition with `service Service`

**What did you expect to see**
Generated code compiles

**What did you see instead?**
The c++ code is generated but the generated code is not valid c++

```
hello-api.grpc.pb.h:93:9: error: member 'Service' has the same name as its class
  class Service : public ::grpc::Service {
        ^
```

A class `Service` is Generated (line 13) and this calss contains a nested class also called `Service` (line 93).
Same problem would be if you called your Service `Stub`.

I think all those internal classes should be prefixes with `_` like _Service or something similar. Or protoc should refuse to compile the service.

As it is now you can have a running Service for example in go. Which no c++ client can connect. 

See the protofile (remove .txt):
[hello.proto.txt](https://github.com/protocolbuffers/protobuf/files/8640079/hello.proto.txt)

And the generated gprc.pb.h (remove.txt):
[hello.grpc.pb.h.txt](https://github.com/protocolbuffers/protobuf/files/8640078/hello.grpc.pb.h.txt)

**Comment by deannagarcia** [comment]
This seems to be more of a problem with grpc since it should be valid in other contexts to name your proto field `Service` and a rename would be unexpected. Additionally, it's the grpc generated code that is invalid and not the protoc generated code. I think you should reach out to them instead.

**Comment by DS-Serafin** [comment]
I can raise the issue there, I was under the impressin protoc was maintained here
