### ISSUE TITLE
zlib needs -Wnodeprecated-non-prototype copts when building using new clang

### ISSUE THREAD

**Issue by zhzhzoo-autra** [protocolbuffers/protobuf#9931]
**What version of protobuf and what language are you using?**
v3.14.0

**What runtime / compiler are you using (e.g., python version or gcc version)**
emscripten clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)

Clang added a new warning (https://reviews.llvm.org/rG11da1b53d8cd3507959022cd790d5a7ad4573d94), so we need
to add -Wnodeprecated-non-prototype to zlib copts if we want to build using new clang

**Comment by thomasvl** [comment]
@zhangskz why is this labeled "objective-c"?  I can't think of any place ObjC is dependent of zlib.

**Comment by jskeet** [comment]
It's not clear why this is labeled c# either. Removing the label...

**Comment by fowles** [comment]
This feels like a zlib issue not a protobuf one
