### ISSUE TITLE
Using the class generated by proto may lead to the memery increse. 

### ISSUE THREAD

**Issue by KJsouth** [protocolbuffers/protobuf#9932]
**What version of protobuf and what language are you using?**
Version: 3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
linux 

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
I use the class generated by proto to define and init local object in the  for loop. I find that the program memery is incresase.   I want to know using default deconstructor to clear local object, this action whether free the memery or not.
thank you !!!  freinds.

**Comment by fowles** [comment]
I am sorry, this is not enough information to understand or reproduce this issue.  Please reopen with:

- a full version 
- the actual code causing an issue
- a description of how the memory usage was measured
