### ISSUE TITLE
Using  "string_view" to represent the "string" key

### ISSUE THREAD

**Issue by Derfei** [protocolbuffers/protobuf#9933]
when I use the struct "map<string, string> kv;", 
In protobuf3.8.0, the next codes work:
`
std::string_view key("key");
kv[key] = "value";
`
While in protobuf3.19.4, the above code doesn't works.
The error msg is:
 error: no match for 'operator[]' (operand types are 'google::protobuf::Map<std::__cxx11::basic_string
<char>, std::__cxx11::basic_string<char>>' and 'std::string_view' {aka 'std::basic_string_view<char>'})

**Comment by sbenzaquen** [comment]
What compilation options are being used?
Heterogeneous lookup by `std::string_view` is enabled when `__cpp_lib_string_view` is defined.
See https://en.cppreference.com/w/cpp/string/basic_string_view#Notes
This should generally be enabled when compiling in C++17 mode and above, but some toolchains do it with older language versions too.
