### ISSUE TITLE
Can't download v1.2.11.tar.gz for now

### ISSUE THREAD

**Issue by daohu527** [protocolbuffers/protobuf#9935]
I use bazel to build, which depends on protobuf, but for now I can't download `v1.2.11.tar.gz`.

Then I change the version to `v1.2.12.tar.gz` in `protobuf_deps.bzl`, but it still need `v1.2.11.tar.gz`, how can I update the version of zlib?

https://github.com/protocolbuffers/protobuf/blob/637a699969baf5930c77b87fbd89bd3286c09c98/protobuf_deps.bzl#L47-L53

**Comment by devjgm** [comment]
Thanks for filing an issue, but I'm not sure I understand the problem or situation yet. Which project are you building with bazel? Protobuf or some other project that uses protobuf? And what is the change you're trying to make: Are you trying to change zlib to version 1.2.12?

If you get an error, what's the error?

Also, can you provide simple steps to reproduce the issue?

**Comment by daohu527** [comment]
Bazel itself will depend on `com_google_protobuf`, the version is `bazel 3.4.1`, is there some way to fix this url https://github.com/madler/zlib/issues/649

**Comment by devjgm** [comment]
The short answer, is that I don't think there's anything you can do about it, other than maybe upgrading the version of bazel that you're using. However, can you provide any details about how to reproduce the problem? I tried and was unable to repro on Linux:

```console
$ ls
BUILD  main.cc  WORKSPACE
$ cat WORKSPACE
workspace(name = "foo")
$ cat BUILD
cc_binary(
    name = "foo",
    srcs = ["main.cc"],
)
$ cat main.cc
int main() { return 42; }
$ USE_BAZEL_VERSION=3.4.1 bazelisk run :foo
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 0.144s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
$ echo $?
42
```

**Comment by daohu527** [comment]
You mean there won't be dependency issues with bazel 3.4.1 compiling?

> can you provide any details about how to reproduce the problem?

This is not easy, because I am compiling a large project [apollo](https://github.com/ApolloAuto/apollo/tree/v6.0.0). I am not sure whether other projects have introduced this dependency, but it is probably introduced by bazel. Thank you for your help. I will try to find the cause of the problem first.

```
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(01:14:41) WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
(01:14:41) ERROR: An error occurred during the fetch of repository 'zlib':
   java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/zlib-1.2.11.tar.gz: GET returned 404 Not Found
(01:14:41) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:209:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/zlib-1.2.11.tar.gz: GET returned 404 Not Found
```
