### ISSUE TITLE
protobuf compatible versions for go 1.17

### ISSUE THREAD

**Issue by umishra21** [protocolbuffers/protobuf#9940]
Hi, I am upgrading my go version from 1.14 to 1.17. My current protobuf version is 3.8.0 and want to know which version should I upgrade to for the same?

Thanks!

**Comment by devjgm** [comment]
Hi, thanks for the question. Unfortunately, Protobuf-go is in another repo so you'll want to ask your question over at https://github.com/golang/protobuf/issues
