### ISSUE TITLE
google::protobuf::internal::implicit_weak_message_default_instance does not have a constant initializer

### ISSUE THREAD

**Issue by ashley-b** [protocolbuffers/protobuf#9948]
## What version of protobuf and what language are you using?
Protobuf version: 3.20.0
Language: C++
Operating system: Fedora 36 x86_64
Compiler: gcc (GCC) 12.0.1 20220413 (Red Hat 12.0.1-0)

## Build failed with the following error:
.conan/data/protobuf/3.20.0/_/_/build/2f35e172d6ce2a8be1b82606922d799ab21e1525/source_subfolder/src/google/protobuf/implicit_weak_message.cc:61:5: error: ‘constinit’ variable ‘google::protobuf::internal::implicit_weak_message_default_instance’ does not have a constant initializer
   61 |     implicit_weak_message_default_instance;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/.conan/data/protobuf/3.20.0/_/_/build/2f35e172d6ce2a8be1b82606922d799ab21e1525/source_subfolder/src/google/protobuf/implicit_weak_message.cc:61:5: error: ‘google::protobuf::internal::ImplicitWeakMessageDefaultType{google::protobuf::internal::ImplicitWeakMessageDefaultType::<unnamed union>{google::protobuf::internal::ImplicitWeakMessage{google::protobuf::MessageLite{((& google::protobuf::internal::ImplicitWeakMessage::_ZTVN6google8protobuf8internal19ImplicitWeakMessageE) + 16), google::protobuf::internal::InternalMetadata{0}}, 0}}}’ is not a constant expression

## Additional information
This was  built via conancenter package protobuf/3.20.0

**Comment by acozzette** [comment]
Thank you for the bug report. I believe this should be fixed by #9936 in the upcoming 3.21.0 release.
