### ISSUE TITLE
Running protoc-osx-aarch_64-3.19.4 on ARM64 Mac Does not Work

### ISSUE THREAD

**Issue by mgrand-topl** [protocolbuffers/protobuf#9955]
**What version of protobuf and what language are you using?**
prebuilt protoc-osx-aarch_64-3.19.4

**What operating system (Linux, Windows, ...) and version?**
  System Version:	macOS 12.3.1 (21E258)
  Kernel Version:	Darwin 21.4.0
  running on 
   Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro

**What did you do?**
1. Download https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-osx-aarch_64.zip
2. `unzip protoc-3.20.1-osx-aarch_64.zip`
3. `./bin/protoc`
4. zsh: bad CPU type in executable: ./bin/protoc

**What did you expect to see**
```
Usage: protoc [OPTION] PROTO_FILES
...
```

**What did you see instead?**
```
zsh: bad CPU type in executable: ./bin/protoc
```

**Comment by slachiewicz** [comment]
Was this expected to change the version from 3.20 to just 21.0?
