### ISSUE TITLE
PHP: `ReflectionProperty` returns default values for `optional` fields

### ISSUE THREAD

**Issue by rauanmayemir** [protocolbuffers/protobuf#9960]
Let's consider the following:

```
syntax = "proto3";

message Payload {
  int32 value1 = 1;
  optional int32 value2 = 2;
}
```

Then for the generated `Payload` class we will do this:

```php

$payload = new Payload([
    'value1' => 1,
]);

$reflProperty = new \ReflectionProperty(Payload::class, 'value2');
$reflProperty->setAccessible(true);

var_dump($reflProperty->getValue($payload));
```

The behavior is different for native extension and 'polyfill'.

In polyfill, resulting dump is `null`. As it should, because the property is set to NULL.
However, if native extension is enabled, returned value is the default (0 or empty string, etc).

This happens on the latest version `3.20.1`, also tested for `3.17.2`.

**Comment by haberman** [comment]
The properties of our generated class are `protected` and are therefore an implementation detail. No contract is made about what these properties will contain if you access them directly.

The correct way to do this with protobuf would be to use protobuf reflection. However the protobuf library does not currently support reflection in PHP. Feel free to file a feature request for this.

Another option would be to call the generated accessor by string name. However you would have to camel-case the name yourself, eg.

```php
$name = 'getValue2';
var_dump($payload->{$name}());
```

**Comment by rauanmayemir** [comment]
@haberman What's the difference between `$payload->getValue2()` and `$payload->{$name}()`?

I'm assuming there's some magic happening in the native extension, however, non-native extension in this case would return the default value and that again leaves us with different outcome.

So I guess the main issue is not about the difference in reflection results, but in the way polyfill and native extension generally works. My impression was that native extension is the drop-in performance boost.

**Comment by haberman** [comment]
> My impression was that native extension is the drop-in performance boost.

The native extension is a drop-in performance boost as -- long as you use the public API only.

For example, a call like `$payload->getValue2()` will behave the same whether you have the native extension or not.

Accessing protected properties of the generated class using `ReflectionProperty` is not supported, and therefore the results are not guaranteed to be the same.

> What's the difference between `$payload->getValue2()` and `$payload->{$name}()`?

If `$name == 'getValue2` then those two should be identical -- they are both calling `$payload->getValue2()`.

**Comment by rauanmayemir** [comment]
I see, then extension would also return the default value, not accounting for the optional null.

Would changing getters’ behaviour to return nulls for optional be a non-starter? This values are not passed into the serialized payload, so not sure why do they have to carry defaults.

**Comment by haberman** [comment]
Protobuf semantics are always to return a default value for primitive types like strings/numbers. When implementations deviate from this, it tends to cause problems.

For example, for `syntax="proto2";` files (which PHP doesn't currently support, but should someday) [users can specify explicit defaults](https://developers.google.com/protocol-buffers/docs/proto#optional). If we returned null for unset values, any user-specified default value would be ignored.
