### ISSUE TITLE
Failed to parse the serialized value with gcc -O2

### ISSUE THREAD

**Issue by x2c3z4** [protocolbuffers/protobuf#9961]
This is the test proto and cc file:

hello.proto
```

syntax = "proto2";

package helloworld;


message HelloRequest {
    required string name = 1;
    optional bool test_a = 2;
}
```

main.cc
```
#include "hello.pb.h"
#include <iostream>

int main() {
  helloworld::HelloRequest request, tmp_request;
  request.set_name("world");

  bool a = true;
 // Just emulate the uninitialized bool value.
  *(char *)&a = 0xff; 
  request.set_test_a(a);

  std::string value;
  if (!request.SerializeToString(&value)) {
    std::cerr << "Failed to serialize the request." << std::endl;
    return -1;
  }

  if (!tmp_request.ParseFromString(value)) {
    std::cerr << "Failed to parse the request." << std::endl;
    return -1;
  }
  std::cout << "[AFTER PARSE] " << tmp_request.ShortDebugString() << std::endl;

  return 0;
}
```

This is the compile command:
```
protoc -I=. --cpp_out=. ./hello.proto
g++ -I. main.cc hello.pb.cc  -lprotobuf -g -O2
./a.out
```
The output is:
```
Failed to parse the request.
```

If I change the `-O2` to `-O0`, it will ok.

**Comment by dlj-NaN** [comment]
This line:

```
*(char *)&a = 0xff; 
```

is Undefined Behavior in C++.

Under C++ rules, once Undefined Behavior is exercised, the behavior of the entire program is undefined: the compiler is free to optimize and rearrange code while assuming well-defined behavior, so anything depending on a `bool` variable actually being 1 bit may no longer function correctly.

Unfortunately, per C++ language rules, if your code has undefined behavior, there is not much that protobufs can do to make sense of it.

**Comment by x2c3z4** [comment]
Hi @dlj-NaN

Thanks for your reply.
My question is why serialization can succeed, but deserialization fails? When serializing, it can save 0xff to bool value, and when deserializing, it should be able to parse out from 0xff to bool value.
