### ISSUE TITLE
Wrong version of protoc 21.0-rc1 for aarm64 published to Maven Central

### ISSUE THREAD

**Issue by slachiewicz** [protocolbuffers/protobuf#9973]
looks like publishing to Maven Central should be verified because 

[protoc-21.0-rc-1-osx-x86_64.exe](https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/21.0-rc-1/protoc-21.0-rc-1-osx-x86_64.exe)                   2022-05-11 17:46   4249112
[protoc-21.0-rc-1-osx-aarch_64.exe](https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/21.0-rc-1/protoc-21.0-rc-1-osx-aarch_64.exe)                 2022-05-11 17:46   4249112

looks like the same file (have even the same hash).

Files published to GH Releases look good.

https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/21.0-rc-1/

**Comment by deannagarcia** [comment]
Thanks for reporting this issue and sorry the upload was wrong. I have fixed the problem and next release will have the proper osx aarch_64 binary. I'm going to leave this issue open and close when the binary has been successfully published.

**Comment by slachiewicz** [comment]
All works fine with 3.21.0-rc-2. Thx!

**Comment by deannagarcia** [comment]
Great, thanks for confirming!
