### ISSUE TITLE
Regression of #9152

### ISSUE THREAD

**Issue by ben-harris-5** [protocolbuffers/protobuf#9984]
**What version of protobuf and what language are you using?**
Version: v3.20.1
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04 running in WSL (this isn't relevant)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Node v16.14.2

**What did you do?**
1. Write a proto
2. Compile it with `protoc --js_out="import_style=commonjs,binary:${OUT_DIR}" ...`
3. Try and require/import the output file
4. NodeJS complains

**What did you expect to see**

NodeJS load the file correctly

**What did you see instead?**

```text
/path/to/sample_proto_pb.js:16
var global = (function () { return this || window || global || self || Function('return this')(); }).call(null);
                                           ^

ReferenceError: window is not defined
```

**Anything else we should know about your project / environment**

n/a

This was fixed in [3.19.x](https://github.com/protocolbuffers/protobuf/blob/633cef56e8a2e8f009c5f79d4250c04c03367143/src/google/protobuf/compiler/js/js_generator.cc#L3637) by PR #9156, but regressed to the old behavior in [3.20.x](https://github.com/protocolbuffers/protobuf/blob/6e9e60367d8744e86856590d8ea0e793c61deeec/src/google/protobuf/compiler/js/js_generator.cc#L3639). I've verified that this works with protoc version 3.19.4, but fails with 3.20.1.

**Comment by elharo** [comment]
JavaScript issues have moved to https://github.com/protocolbuffers/protobuf-javascript/issues
Please open this request there.
