### ISSUE TITLE
change repeated field to synchronized list in java

### ISSUE THREAD

**Issue by 1zg12** [protocolbuffers/protobuf#9991]
**What language does this apply to?**
Java

If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Java

**Describe the problem you are trying to solve.**
the generated java code for repeated field is `ArrayList`, which is not thread safe. This will become a problem when the field is mutated in multithread environment.

For example, for this message
```
message PositionGroup{
   repeated Position payloads =1;
    ....
}
```
this would generated as 
![image](https://user-images.githubusercontent.com/52658745/169005728-f55bc2cc-7e8e-43d4-b55f-05e8dc7b21e1.png)

since the `payloads_` is not thread safe, this will result in exception in following code
```
payloads //payloads is a customized list of position
     .parallelStream()
    .reduce(PositionGroup.newBuilder(), (g, p) -> g.addRepeatedFiled(field, g), (b1, b2) ->b1.mergeFrom(b2.build())
```

**Describe the solution you'd like**

**Describe alternatives you've considered**
The generated code could be like
```
   payloads_ = Collections.synchronizedList(new ArrayList());
```

**Additional context**

**Comment by elharo** [comment]
Protobufs generally require external synchronization. However they should be immutable after construction which is enough for most needs.
